### ISSUE TITLE
Problem implementing Softmax Regression (Multinomial Logistic)

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#1004]
I am trying to implement a logistic multinomial regression (AKA softmax regression). In this example I am trying to classify the iris dataset.

I have a problem specifying the model, I get an optimization error with find_MAP(). If I avoid using find_MAP() I get a "sample” of all zero vectors for _alfa_ and _beta_ and  a vector of 0.33 for _p_ if I use a Categorical for the likelihood. if I use Mutinomial(n=1, p=p) the posterior is exactly the same as the priors. 

``` python
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

iris = sns.load_dataset("iris")
y_2 = pd.Categorical(iris['species']).labels
x_n = iris.columns[:-1]
x_2 = iris[x_n].values
x_2 = (x_2 - x_2.mean(axis=0))/x_2.std(axis=0)
indice = list(set(y_2))

with pm.Model() as modelo_s:
    alfa = pm.Normal('alfa', mu=0, sd=100, shape=3)
    beta = pm.Normal('beta', mu=0, sd=100, shape=(4,3))

    mu = (alfa[indice] + pm.dot(x_2, beta[:,indice])).T
    p = pm.exp(mu)/pm.sum(pm.exp(mu), axis=0)

    yl = pm.Categorical('yl', p=p, observed=y_2)
    #yl = pm.Multinomial('yl', n=1, p=p, observed=y_2)

    #start = {'alfa': np.random.rand(3), 'beta':np.random.rand(4,3)}
    #start = pm.find_MAP(start)
    #step = pm.NUTS(scaling=start)
    start = pm.find_MAP()
    step = pm.Metropolis()
    trace_s = pm.sample(1000, step, start)
```

This is also an open question on [stackoverflow](http://stackoverflow.com/questions/35368902/softmax-regression-multinomial-logistic-with-pymc3)

**Comment by twiecki** [comment]
Hm, I gave this a fair shot. This model should be correct:

``` python
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import theano.tensor as T

iris = sns.load_dataset("iris")
y_2 = pd.Categorical(iris['species']).labels
x_n = iris.columns[:-1]
x_2 = iris[x_n].values
x_2 = (x_2 - x_2.mean(axis=0))/x_2.std(axis=0)
indice = list(set(y_2))
x_2 = x_2[:, indice]

with pm.Model() as modelo_s:
    alfa = pm.Normal('alfa', mu=0, sd=100, shape=len(np.unique(y_2)), testval=np.random.rand(len(np.unique(y_2))))
    beta = pm.Normal('beta', mu=0, sd=100, shape=(len(np.unique(y_2)), x_2.shape[1]))

    #mu = T.printing.Print('mu')(alfa + pm.dot(x_2, beta))
    mu = (alfa + pm.dot(x_2, beta))
    #p = T.printing.Print('p')(T.nnet.softmax(mu)) #pm.exp(mu)/pm.sum(pm.exp(mu), axis=0)
    p = (T.nnet.softmax(mu))

    yl = pm.Categorical('yl', p=p, observed=y_2)
    #yl = pm.Multinomial('yl', n=1, p=p, observed=y_2)

    #start = {'alfa': np.random.rand(3), 'beta':np.random.rand(4,3)}
    #start = pm.find_MAP(start)
    #step = pm.NUTS(scaling=start)
    #start = pm.find_MAP()
    step = pm.Metropolis()
    trace_s = pm.sample(50000, step)#, step)#, start)
pm.traceplot(trace_s);
```

However, that leads to an error. I couldn't figure out the `Categorical` really, it seems wrong, this is what I did instead:

``` python
class Categorical(Discrete):
    R"""
    Categorical log-likelihood.

    The most general discrete distribution.

    .. math:: f(x \mid p) = p_x

    ========  ===================================
    Support   :math:`x \in \{1, 2, \ldots, |p|\}`
    ========  ===================================

    Parameters
    ----------
    p : float
        p > 0 and the elements of p must sum to 1.
    """
    def __init__(self, p, *args, **kwargs):
        super(Categorical, self).__init__(*args, **kwargs)
        self.k = np.shape(p)[-1]
        self.p = T.as_tensor_variable(p)
        self.mode = T.argmax(p)

    def random(self, point=None, size=None, repeat=None):
        p, k = draw_values([self.p, self.k], point=point)
        return generate_samples(partial(np.random.choice, np.arange(k)),
                                p=p,
                                broadcast_shape=p.shape[:-1] or (1,),
                                dist_shape=self.shape,
                                size=size)

    def logp(self, value):
        p = self.p
        k = self.k

        sumto1 = theano.gradient.zero_grad(T.le(abs(T.sum(p, axis=1) - 1), 1e-5))
        return bound(T.log(p[T.arange(p.shape[0]), value]),
                     value >= 0, value <= (k - 1),
                     sumto1)
```

That samples but doesn't converge.

**Comment by twiecki** [comment]
This is the trace btw:
![image](https://cloud.githubusercontent.com/assets/674200/13454782/98591ad2-e059-11e5-85c8-073b6feba4af.png)

I think at this point it might be a model issue where there are co-linearities.

**Comment by aloctavodia** [comment]
Nice!

If I use the Softmax model, just for 2 categories, I can recover the results obtained with a logistic regression. I also tried to classify the 3 species using the 2 least correlated features or just one feature and I also get poor mixing. I will keep exploring the model.

**Comment by twiecki** [comment]
I think `y_2` needs to be a binary array like `[[1, 0, 0], [0, 1, 0], ...]]`.

**Comment by aloctavodia** [comment]
OK, I will try, but I should also change the shape of p, shouldn't I?

**Comment by twiecki** [comment]
`p` should already have the correct shape (i.e. `3xN`).

**Comment by aloctavodia** [comment]
Sorry for the delay, I turn  y_2 into a binary array with:

``` python
y_2 = (np.arange(np.max(y_2) + 1) == y_2[:, None]).astype(float)
```

As you said `p` have the correct shape, nevertheless I get the error 

``` python
ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 150)
```

I tried transposing `p` and I get zeros array and I also tried messing around with the definition of the logp, but I only get non-nonsensical results, probably because I am doing nonsensical changes ;-) .

**Comment by twiecki** [comment]
@aloctavodia can you post an updated NB?

**Comment by aloctavodia** [comment]
``` python
iris = sns.load_dataset("iris")
y_2 = pd.Categorical(iris['species']).labels
x_n = iris.columns[:-1]
x_2 = iris[x_n].values

with pm.Model() as modelo_s:
    alfa = pm.Normal('alfa', mu=0, sd=10, shape=3)
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3))

    mu = alfa + pm.dot(x_2, beta)
    p = pm.Deterministic('p', tt.nnet.softmax(mu))

    yl = pm.Categorical('yl', p=p, observed=y_2)
    step = pm.Metropolis()
    trace_s = pm.sample(5000, step)
```

And the result is:

![index](https://cloud.githubusercontent.com/assets/1338958/13863935/76adbeb8-ec7c-11e5-8dc2-4d97bf2cc587.png)

**Comment by twiecki** [comment]
OK, well the code looks clean and right now and it's sampling, so that's something at least. I wonder if there is a co-linearity perhaps. I haven't thought it through but maybe beta should only be upper triangular?

**Comment by aloctavodia** [comment]
It's sampling and also is possible to reduce the model to a logistic regression and get the correct result, that's a lot! I think you are right the problem is co-linearity. I have just checked the accuracy of the prediction  and I get ~98% of correct prediction, now I am worried because this sounds to good to be true :-P, I will check again later and also I will compare the results with those obtained by Kruschke in his book. I will let you know of any news.

**Comment by twiecki** [comment]
Ah, this is a replication of a Kruschke model?

**Comment by aloctavodia** [comment]
@twiecki Not exactly, but the second edition of Krusche's book has a chapter about softmax regression, that I should check.

**Comment by twiecki** [comment]
Took another stab at this.

I think the correct model should look like this:

``` python
iris = sns.load_dataset("iris")
y_2 = pd.Categorical(iris['species']).labels
x_n = iris.columns[:-1]
x_2 = iris[x_n].values

import sklearn.preprocessing
y_2_bin = sklearn.preprocessing.LabelBinarizer().fit_transform(y_2)

with pm.Model() as modelo_s:
    alfa = pm.Normal('alfa', mu=0, sd=10, shape=3, testval=np.random.randn(3))
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3), testval=np.random.randn(4, 3))
    mu = alfa + pm.dot(x_2, beta)
    p = pm.Deterministic('p', tt.nnet.softmax(mu))
    yl = pm.Categorical('yl', p=p, observed=np.bool8(y_2_bin))
    step = pm.Metropolis()
    trace_s = pm.sample(5000, step)
```

The problem then are the bounds in the `Categorical` which I think is a pymc3 bug. It's indexing as if the input data needs to be a binary vector (`[1, 0, 0]`) but placing bounds as if it were a class-based one (`[2]`).

Removing the bounds draws samples but the problem persists and I think I know why:
https://en.wikipedia.org/wiki/Multinomial_logistic_regression (look at "Note that not all of the \beta_k vectors of coefficients are uniquely identifiable."). You can multiply (or add a constant to) the outcome mu vector and not change the result of the softmax. I'm not sure which the easiest fix would be.

**Comment by hedgy123** [comment]
Wouldn't the solution be just to force one of the coefficients (say, the last one) to zero?

**Comment by twiecki** [comment]
I think so, yeah.

**Comment by twiecki** [comment]
Actually not sure if 0 makes, sense, I think -beta_x where x is one of the other factors.

**Comment by aloctavodia** [comment]
@twiecki  The last  [model](https://github.com/pymc-devs/pymc3/issues/1004#issuecomment-198125981) I posted (without transforming y_2 to a binary array), and using your definition of the [Categorical](https://github.com/pymc-devs/pymc3/issues/1004#issuecomment-190899225) works OK for me.  I get the same class assignment with the bayesian model than with scikit-learn's logistic regression.

The only remaining issue is that that definition of the `Categorical` will not work for a unidimensional `p`

a quick hack will be: 

``` python
        sumto1 = theano.gradient.zero_grad(T.le(abs(T.sum(p, axis=-1) - 1), 1e-5))
        if p.ndim > 1:
            a = T.log(p[T.arange(p.shape[0]), value])
        else:
            a = T.log(p[value])
        return bound(a,
                     value >= 0, value <= (k - 1),
                     sumto1)
```

But probably there is a better solution.

**Comment by twiecki** [comment]
It's a bit hacky, but I can't think of a better solution.

**Comment by twiecki** [comment]
But the bounds would need to be changed too I think. Want to do a PR?

**Comment by aloctavodia** [comment]
OK, but first let me check with a couple of different datasets.

**Comment by hedgy123** [comment]
@twiecki Could you please show me how to do this correctly?  In my model I have MVN-distributed parameters 

```
  w = pm.MvNormal('w', mu=np.ones(3), tau=prec, shape=3)
```

not quite sure how to properly subtract off w[3], for example, for a pymc3.model.FreeRV variable...

**Comment by aloctavodia** [comment]
@hedgy123  you could try something like:

``` python
w = w*[0,1,1]
```

or maybe setting `tau` to an array where one of the values is a really large one

**Comment by hedgy123** [comment]
Thanks @aloctavodia!  My model is now sampling and converging. One more question though: how would you now do predictions with such a model?   (or with the iris one for that matter)

**Comment by twiecki** [comment]
@hedgy123 can you post the updated model and output? Check here for prediction: http://pymc-devs.github.io/pymc3/posterior_predictive/

**Comment by hedgy123** [comment]
This is what I have:

```
 with pm.Model() as model:

      prec = WishartBartlett('prec', S, nu)
      cov = pm.Deterministic('cov', T.nlinalg.matrix_inverse(prec))

      w = pm.MvNormal('w', mu=np.ones(3), tau=prec, shape=3)
      w = w*[0,1,1]
      theta = (pm.dot(x_2,w))   
      p = pm.exp(theta)/pm.sum(pm.exp(theta), axis=0)
      yl = pm.Categorical('yl', p=p, observed=y_2)

      start = pm.find_MAP()
      #step = pm.NUTS(scaling=start) 
      step = pm.Metropolis()
      trace = pm.sample(1000, step, start)
      pm.traceplot(trace[100:]);
```

About the prediction step.  This is where I am stuck because of a). the w's trick with artificially setting one of them to 0, b) the softmax denominator, c) the output is Categorical, which is not available in scipy as far as I know.  So here's as far as I got:

```
    df_trace = pm.trace_to_dataframe(trace)
    ws =(df_trace[-1000//2:].mean(0))[3:6]

    def predict(x_new,ws = ws):
          theta = (pm.dot(x_new,ws))    
          return pm.exp(theta)/???????

    test_x = np.array([1,1,1])
    test_y = predict(test_x)
```

**Comment by hedgy123** [comment]
Forgot to post the output:

 [-----------------100%-----------------] 1000 of 1000 complete in 0.7 sec

![image](https://cloud.githubusercontent.com/assets/6642667/14154862/daf88e42-f68c-11e5-98dc-e8f32f779a1b.jpeg)

**Comment by aloctavodia** [comment]
@hedgy123 you could write something like this

``` python
def predict(A, B, X):
    Y_pred = A.mean(axis=0) + np.dot(X, B.mean(axis=0))
    p = np.exp(Y_pred).T/np.sum(np.exp(Y_pred), axis=1)
    p_class = np.argmax(p, axis=0)
    return p, p_class
```

_i.e._ you use the mean of the estimated parameters, you could also use [Posterior Predictive Checks](http://pymc-devs.github.io/pymc3/posterior_predictive/) to generate _predictive/synthetic_ data from the posterior. In the second case instead of using the mean values of the estimated parameters you are taking into account the uncertainty contained in the posterior.

**Comment by aloctavodia** [comment]
@twiecki  Using the [model](https://github.com/pymc-devs/pymc3/issues/1004#issuecomment-198125981) I posted (without transforming y_2 to a binary array) and the `Categorical` in my pull request #1052  I am able to reproduce the accuracy of scikit-learn's logistic regression for the iris and digits dataset. I also check against Kruschke's example, since for this case I want to check the values of the estimated parameters I add the constraint that `alfa[0]=0` and `beta[:,0]=0` following Kruschke's example, the values I get are equivalent to those in the book.

**Comment by twiecki** [comment]
Really cool. Can you also post the full model?

**Comment by hedgy123** [comment]
With the prediction part of the full model if possible, please :)  

@aloctavodia, using your suggestion for the prediction code:

```
 def predict(x_new,ws = ws):    
     theta_pred = (pm.dot(x_new,ws))    
     p = pm.exp(theta_pred)/pm.sum(pm.exp(theta_pred),axis=1)
     p_class= np.argmax(p,axis=0)
     return p,p_class

 test_x = np.array([1,1,1])
 test_y = predict(test_x)
 print(test_y.eval())
```

I get the following error about line p = pm.exp(theta_pred)/pm.sum(pm.exp(theta_pred),axis=1)

```
 ValueError: Not enough dimensions on Elemwise{exp,no_inplace}.0 to reduce on axis 1
```

**Comment by twiecki** [comment]
Why can't you use the `shared` trick I posted above?

**Comment by twiecki** [comment]
I think this is fixed, reopen if not.

**Comment by Johnnyboycurtis** [comment]
I decided to look at the multinomial regression example above with the iris data set. I took @twiecki  code (with some slight updates) but doesn't seem to run. I believe there's an issue with the data types. Have any idea what's going on?


        import pymc3 as pm
        import numpy as np
        import matplotlib.pyplot as plt
        import seaborn as sns
        import pandas as pd
        import theano.tensor as T
        import sklearn.preprocessing
        
        
        iris = sns.load_dataset("iris")
        y_2 = pd.Categorical(iris['species']).labels
        x_n = iris.columns[:-1]
        x_2 = iris[x_n].values
        
        y_2_bin = sklearn.preprocessing.LabelBinarizer().fit_transform(y_2)
        
        with pm.Model() as modelo_s:
            alfa = pm.Normal('alfa', mu=0, sd=10, shape=(3, 1), testval=np.random.randn(3)) ## shape 3 --> (3,1)
            beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3), testval=np.random.randn(4, 3))
            mu = alfa + pm.math.dot(x_2, beta)
            p = pm.Deterministic('p', T.nnet.softmax(mu))
            yl = pm.Categorical('yl', p=p, observed=np.bool(y_2_bin))
            step = pm.Metropolis()
            trace_s = pm.sample(5000, step)
            
        pm.traceplot(trace_s)
        plt.show()

Here is the error it throws

> TypeError: For compute_test_value, one input test value does not have the requested type.
>
>The error when converting the test value to that variable type:
>Non-unit value on shape on a broadcastable dimension.
>(3, 3)
>(False, True)

**Comment by plison** [comment]
I'm also trying to run a multinomial logistic regression model with PyMC3, but without success so far. I tried, the solution suggested by @aloctavodia, but it doesn't converge on the Iris dataset:

```python
import sklearn.datasets
import pymc3 as pm
import theano
import theano.tensor as tt

# Loading the Iris dataset
X, y = sklearn.datasets.load_iris(True)

with pm.Model() as iris_model:
    
    # Creating the model
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3))
    alpha = pm.Normal('alfa', mu=0, sd=10, shape=3)
    mu = tt.dot(X,beta) + alpha
    p = pm.Deterministic('p', tt.nnet.softmax(mu))
    yl = pm.Categorical('yl', p=p, observed=y)
  
    trace = pm.sample(5000, step = pm.Metropolis(), chains=3, njobs=5)
    pm.traceplot(trace)
```

![index](https://user-images.githubusercontent.com/11574012/43520672-c71412a4-9593-11e8-9a4d-2c973fc32e08.png)

Any suggestions?

**Comment by ColCarroll** [comment]
This runs as is if you use all the defaults for `pm.sample` (that is, replace your `trace = pm.sample(5000, ...)` line with just `trace = pm.sample()`.  Metropolis is not a recommended sampler to use in general when you have a continuous model.  

As a sanity check, you can check the median prediction from all the samples against an sklearn logistic regressor:

```python
import numpy as np
from sklearn import linear_model

print((np.argmax(np.median(trace['p'], axis=0), axis=1) == y).sum())  # 147

lm = linear_model.LogisticRegression()
lm = lm.fit(X, y)

print(np.argmax(lm.predict_proba(X), axis=1) == y).sum())  # 144
```

**Comment by plison** [comment]
OK, I now got it to work, thanks for the help!

**Comment by fjssharpsword** [comment]
@plison Thanks for your share! I also face divergences.
------Code Start------
import sklearn.datasets
import pymc3 as pm
import theano
import theano.tensor as tt

X, y = sklearn.datasets.load_iris(True)
X_input = theano.shared(X)#转numpy array
Y_output = theano.shared(y)#转numpy array
with pm.Model() as iris_model:
    
    # Creating the model
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3))
    alpha = pm.Normal('alfa', mu=0, sd=10, shape=3)
    mu = tt.dot(X_input,beta) + alpha
    p = pm.Deterministic('p', tt.nnet.softmax(mu))
    yl = pm.Categorical('yl', p=p, observed=Y_output)
    
    trace = pm.sample(step = pm.NUTS())
    pm.traceplot(trace)

X_input.set_value(X[[0, 1, 2], :])#转numpy array
Y_output.set_value(y[0:3])
with iris_model:
    ppc = pm.sample_posterior_predictive(trace, samples=500, progressbar=False) 
    pred = ppc['yl'].mean(axis=0)
print (pred)
------Code End------
![image](https://user-images.githubusercontent.com/46018480/57205685-c8043b00-6ff2-11e9-8a8f-7180167a74e2.png)

**Comment by twiecki** [comment]
Can you post this on our discourse?

**Comment by kawairine** [comment]
> @hedgy123 you could write something like this
> 
> ```python
> def predict(A, B, X):
>     Y_pred = A.mean(axis=0) + np.dot(X, B.mean(axis=0))
>     p = np.exp(Y_pred).T/np.sum(np.exp(Y_pred), axis=1)
>     p_class = np.argmax(p, axis=0)
>     return p, p_class
> ```
> 
> _i.e._ you use the mean of the estimated parameters, you could also use [Posterior Predictive Checks](http://pymc-devs.github.io/pymc3/posterior_predictive/) to generate _predictive/synthetic_ data from the posterior. In the second case instead of using the mean values of the estimated parameters you are taking into account the uncertainty contained in the posterior.

Hi @aloctavodia, or in general,

I was wondering for the 2nd case you mentioned with posterior predictive checks, the uncertainties are about the beta and alpha but rather not the uncertainties about the prediction. Is there a way to get prediction probability and also the uncertainty about it? 

Thank you!

**Comment by aloctavodia** [comment]
Hi @kawairine this kind of question is better suited for our discourse. 

the posterior distribution reflects the uncertainty you have about the parameters (given the data and the model) and the posterior predictive distribution reflects the uncertainty you have about your predictions (which is taking into account the uncertainty in your parameters).
