### ISSUE TITLE
discrete types again

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1005]
Dear all,

I know we had this already, but with the new way as it is implemented now in metropolis a new problem has been created:

```
self.discrete = np.ravel([[v.dtype in discrete_types] * (v.dsize or 1) for v in vars])
```

the following lines rely on self.discrete

```
self.discrete = self.discrete.any()
self.discrete = self.discrete.all()
```

They are supposed to return booleans, but they return a list of booleans so that the if statements in astep of metropolis do not work properly and do always pass. So everything is always converted to integers. I didnt notie this before, because I was using discrete variables ;) . Now floats dont work anymore.
This could be easily fixed by:

```
self.discrete = self.discrete.any()[0]
self.discrete = self.discrete.all()[0]
```

But propably that is not professional enough for you guys? So you may want to fix it in the way how self.discrete is being created. @fonnesbeck didnt like my earlier proposal and changed to the way it is now. ;)
I proposed, which was actually working here: https://github.com/pymc-devs/pymc3/pull/979

```
self.discrete = np.hstack(np.ravel([[v.dtype in discrete_types ] * v.dsize for v in vars]))
```

Cheers!
Hannes

**Comment by twiecki** [comment]
Can you provide pointers to the code directly?

**Comment by hvasbath** [comment]
metropolis.py lines 94-96. I dont know how to link it in here if this is possible somehow.

**Comment by fonnesbeck** [comment]
@eigenblutwurst I had tried to adopt most of what you had suggested when I merged #980. What you had originally proposed would fail when `v.dsize` was an empty tuple (which it sometimes is) so I had to modify it. Sounds like it just needs another tweak.

**Comment by hvasbath** [comment]
ah ok didnt think of this ;) . Then lets tweak it!

**Comment by hvasbath** [comment]
btw as I proposed above:
self.discrete = self.discrete.all()[0]
doesnt work if you only have one variable. So definitely the line 
self.discrete = np.ravel([[v.dtype in discrete_types] \* (v.dsize or 1) for v in vars])
has to be changed somehow.

**Comment by hvasbath** [comment]
My new suggestion:

```
self.discrete = num.concatenate([[v.dtype in pm.discrete_types] * (v.dsize or 1) for v in vars])
```

So far had no case when this was not working. What do you think?
