### ISSUE TITLE
variable bounds and transforms

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1006]
I still didnt get how these variable transforms work.
You transform them to have -inf and +inf bounds and sample on this space then you dont have to care about the bounds, transform back and use that sample which will be in between its bounds to give to the likelihood calculation?
Because, for me this still doesnt work with transforms enabled. I still get values out of the bounds.
I guess, because of the delta that is being added to q (for metropolis) and then it can land outside of the solution space! So I guess I will have to switch to my bound check again. Is there any suggestion how a bound check could be implemented more efficient than that one?
https://github.com/pymc-devs/pymc3/pull/979
Cheers!
Hannes

**Comment by twiecki** [comment]
> I guess, because of the delta that is being added to q (for metropolis) and then it can land outside of the solution space!

How can that happen in the transformed space? Are you talking about discrete RVs? Those shouldn't get transformed in the first place.

**Comment by hvasbath** [comment]
No continuous ones. So the delta_logp is executed with the values of the transformed variables in q? This will produce complete non-sense at least in physical models. So I definitely have to switch of transforms.

**Comment by twiecki** [comment]
The likelihood is evaluated on the non-transformed variables, only the sampler proposes parameter in the unconstrained space. Likelihoods are also not transformed. It shouldn't thus make a difference.

**Comment by hvasbath** [comment]
Ok then it is like I thought. If my variable q is defined up to 7.5 my q0 is 7.2 and I get a delta of 0.4 it will try to evaluate my delta_logp with 7.6 and it will crash as my likelihood function is not defined for values above 7.5.

**Comment by twiecki** [comment]
So your likelihood only has limited support? It seems like you should instead adjust your priors to not have mass over those ranges, e.g. by bounding.

**Comment by hvasbath** [comment]
But thats what I tried to do and thought pm.Uniform(upper=7.5, lower=1.) would do. But it does not. Is there any other way of providing bounds?

**Comment by twiecki** [comment]
So that _should_ definitely do the trick. The sampler might propose a value of 100 in the unconstrained space, but that would get transformed to e.g. 7.49999. 

Can you post a minimal example that triggers this?

**Comment by hvasbath** [comment]
I mean the inital q0 will always fulfill this and do exactly what you say- this is inside the bounds. But we are adding delta from the proposal distribution to create q (metropolis.py 118-124) - which then may fall out of bounds. 
Then the likelihood is evaluated. For any function that would be defined it would simply work and put after that -inf propability afterwards as the model logpt, because the variable is out of its bounds and the select_metropolis step would reject it. Nevertheless it would be sampled and the likelihood function would be executed. Will try to provide an example.

**Comment by hvasbath** [comment]
``` python
import pymc3 as pm
import numpy as num
import theano.tensor as tt

x = num.array((num.linspace(0,2*num.pi)))
y = 3 * num.sin(x) + num.random.rand(x.shape[0])/0.3

with pm.Model() as toymod:
    amp = pm.Uniform('amp', lower=0, upper=num.pi, testval=0.01)
    y_mod = tt.sin(x) * amp
    like = pm.Normal('likelihood', mu=y_mod, observed=y)

with toymod:
    S = 10
    step = pm.Metropolis(S=10)
    trc = pm.sample(100,step=step, njobs=1)

pm.summary(trc)
```

you also have to add
print 'sampled', q
in metropolis.py line 124
before
q_new = metrop_select(self.delta_logp(q, q0), q, q0)

Then your output will be similar to this:

```
sampled [-13.21322549]
sampled [ 17.07057677]
sampled [ 20.11240187]
sampled [ 9.04538388]
sampled [ 9.54619559]
sampled [ 12.82527997]
sampled [ 9.27366496]
sampled [-2.1887121]
sampled [ 1.49946683]
sampled [ 13.23480485]
sampled [ 2.22423406]
sampled [ 8.26175784]
sampled [ 0.42104816]
sampled [ 13.86173466]
 [-----------------100%-----------------] 100 of 100 complete in 0.0 sec
```

And as you can see from the upper and lower bounds in the code they are between 0 and pi, but values far outside of these bounds have been sampled.
Cheers!
Hannes

**Comment by twiecki** [comment]
Ah, sorry, yes. The sampler is free to suggest values wherever, it doesn't care about bounds. But the model should get evaluated to -inf outside of the support so such a jump should never be accepted. Is it a problem that the sampler proposes values outside the support?

**Comment by hvasbath** [comment]
Exactly as I wrote above. My likelihood function crashes as it is a physical model and simply not defined outside of the reasonable bounds. Thats why I defined a check bounds function after proposing the new q. But I wanted to know if there could be a less cost intensive solution.

**Comment by twiecki** [comment]
OK, sorry this took me a while to understand.

The easiest solution is to add a check in your likelihood that returns `-np.inf` for values outside the support. If some reason you can't do that, you could maybe try to write a custom proposal distribution that does not propose certain values. I can't see how you couldn't just add a check though.

**Comment by twiecki** [comment]
Btw this is all completely unrelated to transforms.
