### ISSUE TITLE
Remove transformed variables warning from waic, dic

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1007]
The `waic` and `dic` functions currently issue warnings when the model contains transformed random variables. However, since it appears that the model is evaluated using the original (un-transformed) likelihood for the variable, this is should not be a relevant warning.

**Comment by aloctavodia** [comment]
This example shows that the result of `waic` and  `dic` is not the same for transformed or un-transformed variables.

``` python
import numpy as np
import pymc3 as pm

x_obs = np.arange(6)

with pm.Model() as model:
    p = pm.Beta('p', 1., 1., transform=None)
    x = pm.Binomial('x', 5, p, observed=x_obs)

    step = pm.Metropolis()
    trace = pm.sample(100, step, random_seed=1)
    print(pm.waic(trace), pm.dic(trace))

with pm.Model() as model:
    p = pm.Beta('p', 1., 1.)
    x = pm.Binomial('x', 5, p, observed=x_obs)

    step = pm.Metropolis()
    trace = pm.sample(100, step, random_seed=1)
    print(pm.waic(trace), pm.dic(trace))
```

I get `waic= 27.9604516973, dic=27.1083415432` for the untransformed variable and  `waic= 27.8107988547 , dic=29.8149577885`

Should we change how `waic` and  `dic` are computed?

**Comment by fonnesbeck** [comment]
I know that they are not equivalent, but the variables are transformed in PyMC3 simply to make MCMC easier. They are not modeled as transformed variables, and we are not interested in their transformed values (if we did, we would include the transformation in the model), so we should not be calculating these criteria on the transformations. Variables that are transformed automatically to facilitate sampling should be ignored by the functions (in fact, I think they should be invisible to the user altogether to avoid confusion).

**Comment by aloctavodia** [comment]
I understand the motivation behind transforming variables, and I agree they should be invisible to the user. But I just realized why the transformation of variables does not matter for the computation of  `waic` or `dic`. they are different just because the trace  is different!. If I compute the mean of `p` (or whatever) I will get two different results. Ok then, I will remove the warnings (after lunch!).
