### ISSUE TITLE
sqlite and text trace backends do not uniquely name traces

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1008]
Specifying 'text' or 'sqlite' as the trace backend for `sample()` always results in a trace called 'mcmc'. As a result, when running two different models in the same session with, say, a sqlite backend will result in both models' trace being included in the same file/database. The trace should be given a unique name.

**Comment by kyleam** [comment]
Right, in that situation, the user is currently expected to initialize
the backend class directly:

``` python
from pymc3.backends import Text
trace = pm.sample(..., trace=Text('name.csv'))
```

Perhaps the handling of the string argument for trace should be changed
so that the extension maps to a backend (so "*.csv" -> Text, ".sqlite"
-> SQLite).  What do you think?

**Comment by fonnesbeck** [comment]
I like that idea. Its analogous to what matplotlib's `savefig` does for saving figures, inferring the type from the filename.

**Comment by ColCarroll** [comment]
There are other more current issues and discussions around backends, but reopen if wanted!
