### ISSUE TITLE
Selectively excluding variables from saving to trace

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1009]
For very large models, one often wishes to exclude variables that are not of direct interest. It is currently possible to do this by passing the desired variables as the `trace` argument when calling `sample`. However, this argument is also used to specify the type of backend, so it is not possible to both specify the variables of interest and a non-RAM backend. 

We should not overload the `trace` argument this way, but rather have a separate `vars` argument to specify variables to include.

**Comment by kyleam** [comment]
> so it is not possible to both specify the variables of interest and
> a non-RAM backend.

You can do it by passing `vars` to the backend instance that you use
as the `trace` argument to `sample`.  But I agree that it's probably a
good idea to separate `vars` as an argument to `sample`.  This is a
holdover from the `sample` call from before the backend merge.
