### ISSUE TITLE
Specify burn-in to sample

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1010]
While keeping all generated samples is fine for HMC/NUTS, it is not practical for Metropolis sampling. It is often necessary to run 100K+ iterations before convergence, and these values should not be stored.

**Comment by kyleabeauchamp** [comment]
+1 for this feature, it is necessary for me to port my existing pymc2 models with discrete variables.  

Furthermore, I would love a `thin` argument as well.  I believe the current recommendation is to use slicing to thin.  However, I have situations where the un-thinned traces are too big to fit in RAM, but the thinned traces are more than small enough.  This means that post-hoc slicing is not really an answer.

I would possibly assign this to the 3.0 or 3.1 milestones, as they are necessary for re-capturing feature parity with 2.0.

**Comment by kyleabeauchamp** [comment]
Yikes saw the other thread.  I realize that thinning is somewhat out of
fashion, but i thought thinning was a reasonable way to reduce the memory
usage required to obtain a fixed number of effective samples. This would
also accelerate any postprocessing calculations that iterate over the trace.

It's easier than changing the model or the sampler imho.

In molecular simulations (eg hmc), the decorrelation times are multiple
orders of magnitude slower than the timesteps required to do sampling.
It's literally impossible to proceed without thinning by at least 1000X.

**Comment by fonnesbeck** [comment]
Man, I would be nervous about inference based on MCMC output that was significantly autocorrelated to 1000 order. 

Is using a non-RAM backend not an option to deal with hefty samples? My main reservation about including burning and thinning in `sample` (despite my comments on March 2) is that it (1) forces you to determine burn in intervals and thinning factors *a priori* and (2) does unnecessary condition checking at every iteration for those who don't want it. So, my preference is to stick with dealing with both as a post-processing step. 

If I'm in the minority on this, I'm happy to go along with including them as `sample` arguments if we can implement it a little neater. What about passing `thin` and `burn` onto the `Trace` and it can configure itself up front to do thinning/burn-in when these arguments are not `None` and ignore them otherwise? This would mostly involve refactoring `record` to do the right thing.

**Comment by kyleabeauchamp** [comment]
I'm not 100% wedded to `thin` and `burn`.  I guess I was assuming that people might want them to work similarly to pymc2, which may not be the case.  

For now, I can play tricks with slicing and `for` loops of sampling.  

When I get time, I can look into the other ways as well.  Handling it on the trace side sound reasonable, but I'm not yet familiar with the internals.

**Comment by fonnesbeck** [comment]
Lets see what other folks think. I'm happy to help engineer a good solution if I'm the one whining about a change everyone wants.

**Comment by twiecki** [comment]
I don't think we need it. @kyleabeauchamp have you tried using NUTS?

**Comment by kyleabeauchamp** [comment]
AFAIK NUTS requires that all variables are continuous, right?

**Comment by twiecki** [comment]
@kyleabeauchamp I've heard both. In my experiments, mixing NUTS with e.g. Metropolis for discrete vars works well. See the coal mining model for example.

**Comment by fonnesbeck** [comment]
Correct. There isn't any literature that I can tell on the theoretical guarantees of using Metropolis with HMC, but I've had some success. The downside, of course, is that you generally have to run chains longer that you would under a pure NUTS sampler, since Metropolis usually does not converge as fast.
