### ISSUE TITLE
Use logdet() instead of log(det())

### ISSUE THREAD

**Issue by taku-y** [pymc-devs/pymc#1012]
harpone is going to implement logdet() in Theano (https://github.com/Theano/Theano/pull/3959), though maybe not merged yet. What do you think of using this in PyMC3 multivariate normal distribution? It is numerically stable than using log(det()) as in the current implementation. 

When I used a sparse ARD regression model with ADVI, the current implementation of mvnormal failed to calculate its log probability because of using log(det()).

**Comment by superbobry** [comment]
I wonder if Theano optimizer could do the `lod(det())->logdet` transformation automatically?

**Comment by twiecki** [comment]
@taku-y Great find. If that get's merged into theano I think we should definitely switch. Especially when it fixes a modelijng problem. Btw. an example of an ARD model would be a great contribution.

@superbobry That's a good point too, maybe we should raise that point in the PR.

**Comment by twiecki** [comment]
Let's just copy&paste the LogsAbsDet() code into pymc3/theanof.py, it does not look like it would get merged soon and we really need it. Should add a note to remove it if that PR ever gets merged in Theano.

**Comment by ferrine** [comment]
It will be useful in #1694, so waiting for merging logdet

**Comment by bhargavvader** [comment]
#1777 is merged, so this can be closed :)
