### ISSUE TITLE
Incorrect parameters in Beta distribution

### ISSUE THREAD

**Issue by tdshepard** [pymc-devs/pymc#1014]
Both the documentation and corresponding source code have a serious error in the parameters for the Beta distribution. The documentation incorrectly states that the relation between the alpha, beta parametrization and the mu, sigma parametrization is

alpha = mu \* sigma
beta = ( 1 - mu ) \* sigma

The source code in distributions/continuous.py has implemented it in the same incorrect manner:

```
def get_alpha_beta(self, alpha=None, beta=None, mu=None, sd=None):
    if (alpha is not None) and (beta is not None):
        pass
    elif (mu is not None) and (sd is not None):
        alpha = mu * sd
        beta = (1 - mu) * sd
    else: ...
```

The correct relationship between the two parametrizations is

alpha = mu \* ( mu \* ( 1 - mu ) / sd *\* 2 - 1 )
beta = ( 1 - mu ) \* ( mu \* ( 1 - mu ) / sd *\* 2 - 1 )

**Comment by twiecki** [comment]
I got that from the Kruschke book. I suppose you wrote the relationship with the mean and standard deviation?

**Comment by aloctavodia** [comment]
The parametrization is correct in terms of mu (mean) and kappa (concentration or sample size) not standard deviation.

alpha = mu \* kappa
beta = ( 1 - mu ) \* kappa

**Comment by tdshepard** [comment]
I've never heard of kappa. But if

kappa = mu \* ( 1 - mu ) / sd *\* 2 + 1

then that would be correct.

It's not hard to find references that give the formulas I showed. It's also not hard to just invert the expressions

mu = alpha / ( alpha + beta )
sigma *\* 2 = alpha \* beta / ( ( alpha + beta ) *\* 2 ) \* ( alpha + beta + 1 ))

to verify these formulas. And it is pretty easy to substitute expressions in the formulas shown in the documentation to show that they are wrong.

**Comment by fonnesbeck** [comment]
Good catch. I can put together a PR for this.

kappa is just "sample size", that is alpha + beta
