### ISSUE TITLE
Unexpected behavior in uniform distribution with shape parameter

### ISSUE THREAD

**Issue by robdmc** [pymc-devs/pymc#1016]
I'm seeing some unexpected behavior in generating uniform distributions which may or may not be related to issues with transforms.

Basically, the sampled distribution looks as expected for shape=1, but is quite different when shape>1.

I apologize if this is just me not properly understanding the role of the transform kwarg.

See  the following which was run with `pymc3.__version__ ==  '3.0'`
https://gist.github.com/robdmc/9472cff61302a7b5c8f7

**Comment by fonnesbeck** [comment]
Yes, that is definitely a bug. I will take a look at it. Thanks for reporting.

**Comment by fonnesbeck** [comment]
Actually, I cannot replicate this here. [It appears to work with each of the samplers I tried](https://gist.github.com/47fb5f99767ce728e7da), including `Metropolis`. 

How did you install PyMC3? From pip? Can you try:

```
pip install -U https://github.com/pymc-devs/pymc3.git
```

**Comment by robdmc** [comment]
Hello.  I'm at work now, and can't replicate on my work machine either.  Weird.  When I get home, I'll take a careful snapshot of the state of my personal laptop to figure out what's going on.

**Comment by robdmc** [comment]
@fonnesbeck I think I know what happened.  I just ran `pip freeze` on the offending laptop and discovered `Theano==0.8.0.dev0` was installed.  I created a new env and verified that a fresh pip install of pymc3 works fine.  Just as an additional check, I updated to `Theano==0.8.0rc1` and this problem did not manifest.

My guess is that it was a bug in that particular dev release of Theano.  Sorry for the false alarm, and thanks for responding so quickly.  Unless you guys feel you need further investigation, I think this issue is safe to close out.
