### ISSUE TITLE
NUTS seems broken in simple uniform model

### ISSUE THREAD

**Issue by robdmc** [pymc-devs/pymc#1017]
Hello.

I've been having a heck of a time getting Theano and pymc3 to play nicely together.  I think I made an example as simple and repeatable as I know how.

I am running on a macbook air (Yosemite 10.10.5) with Python 2.7.10

I have a super simple model in a file called `test_pymc3.py` that contains the following:

``` python
import pymc3
import sys

sys.stdout.write('='*80 + '\n')
with pymc3.Model() as model:
    x = pymc3.Uniform('x', lower=-1, upper=1)
    trace = pymc3.sample(500)
    _ = pymc3.summary(trace)
```

I then install an environment and run the test file by exectuing
`bash install_and_run.sh`
on the following bash file

``` bash
<mac send]$ cat install_and_run.sh
virtualenv pymc3_test_env
. ./pymc3_test_env/bin/activate
pip install --no-cache-dir -U pip
pip install --no-cache-dir -U git+https://github.com/pymc-devs/pymc3.git
python test_pymc3.py
```

The `test_pymc3.py` script returns the following output to the console.

```
===============================================================================
Applied interval-transform to x and added transformed x_interval to model.
Assigned NUTS to x_interval
ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x111f99e10>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/env/send/pymc3_test_env/lib/python2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/env/send/pymc3_test_env/lib/python2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/env/send/pymc3_test_env/lib/python2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/env/send/pymc3_test_env/lib/python2.7/site-packages/theano/tensor/opt.py", line 5433, in local_fuse
    n = OP(C)(*inputs).owner
  File "/env/send/pymc3_test_env/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 496, in __init__
    scalar_op.nout)
ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 34 and outputs = 1)

[-----------------100%-----------------] 500 of 500 complete in 0.2 sec

x_interval:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------

  -0.128           2.175            0.129            [-5.100, 3.946]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|

  -5.060         -1.248         -0.016         1.128          4.179


x:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------

  -0.007           0.607            0.036            [-1.000, 0.907]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|

  -0.987         -0.554         -0.008         0.511          0.970

(pymc3_test_env)<mac send]$
```

I even completely removed the `~/.theano` directory with the thought that some weird caching thing was happening, but no dice.  As far as I can tell, the distrubtion doesn't look wrong, but the `ValueError` makes me not trust it.  Any help you could provide would be greatly appreciated.

Oh... incidentally.  If I cange the modeled variable to be

``` python
x = pymc3.Uniform('x', lower=-1, upper=1, shape=5)
```

everything works fine.

One final note.  Here is the value of `pip freeze` on the env

```
(pymc3_test_env)<mac send]$ pip freeze
cycler==0.10.0
enum34==1.1.2
joblib==0.9.4
matplotlib==1.5.1
numpy==1.10.4
pandas==0.18.0
patsy==0.4.1
pymc3==3.0
pyparsing==2.1.0
python-dateutil==2.5.0
pytz==2015.7
scipy==0.17.0
six==1.10.0
Theano==0.7.0
```

**Comment by twiecki** [comment]
You need theano dev from the current git master to run pymc3: `pip install -U git+https://github.com/theano/theano`

**Comment by robdmc** [comment]
Okay.  Installing latest Theano does indeed fix compile problems.  Thank you.

I am encountering another problem now.  It might be expected behavior though, so please feel free to close out this issue if the following is not helpful to your dev process.

I've modified my install script to be

``` bash
#virtualenv pymc3_test_env

# create a virtualenv
virtualenv pymc3_test_env

# activate env and pip install packages
. ./pymc3_test_env/bin/activate
pip install -U pip
pip install -U git+https://github.com/pymc-devs/pymc3.git
pip install -U ipython
pip install -U jupyter
pip install -U git+https://github.com/theano/theano
```

And now comes the tricky part.  I cannot figure a way to reliably reproduce the following, but maybe every 10th run or so, it looks like NUTS is getting stuck.  https://gist.github.com/robdmc/c74b1afe30075a25ed57

Even when it doesn't get stuck, the results look suspect.
https://gist.github.com/robdmc/242c869706026187f2aa

Also.  Is there a better place for me to ask questions like this instead of cluttering your issues page?

**Comment by robdmc** [comment]
@twiecki  Actually, unless I'm doing something silly, I'm seeing some unexpected behavior for bounded continuous distributions.

https://gist.github.com/robdmc/84d4d65f0cbf7a16cce3

pymc3 installed with the following commdands

``` bash
#virtualenv pymc3_test_env

# create a virtualenv
virtualenv pymc3_test_env

# activate env and pip install packages
. ./pymc3_test_env/bin/activate
pip install -U pip
pip install -U git+https://github.com/pymc-devs/pymc3.git
pip install -U ipython
pip install -U jupyter
pip install -U git+https://github.com/theano/theano
```

**Comment by fonnesbeck** [comment]
Yeah, those look like artifacts of back-transforming form the real line for bounded variables. We need to fix that.

**Comment by twiecki** [comment]
I'm not sure it's the transform as it works fine under Metropolis which operates in the same space. We've seen some strange behavior with NUTS in the past which makes me suspicious that there might be a bug. @robdmc why do you set `target_accept=.9`? We should also try this with HMC which doesn't seem to have these problems.

**Comment by twiecki** [comment]
Indeed, HMC doesn't have that problem:
![image](https://cloud.githubusercontent.com/assets/674200/13741200/487a8c32-e9d5-11e5-9ef5-321f27f49700.png)

**Comment by twiecki** [comment]
Huh, NUTS actually seems to get stuck with a lower acceptance ratio.

**Comment by robdmc** [comment]
@twiecki Yea.  Setting `target_accept` was the only way I could reliably keep NUTS from getting stuck.  I was concerned this might some how be related.  I started exploring the pymc3 code base, but haven't spent nearly enough time with it to make any useful comments.  Maybe I'll just blame Theano.  :)

**Comment by twiecki** [comment]
@robdmc No no, this is super valuable and I think it's the best example of failing NUTS we have. I can only imagine that it must be a bug within NUTS which we have to find and solve. Just going through the code a bit: https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/nuts.py#L15

**Comment by twiecki** [comment]
I reverted to commit 81c5ad9cbb3f5f99ff6ced453c980af2e84edb80 and it seems to work:
![image](https://cloud.githubusercontent.com/assets/674200/13741976/82aabdd8-e9d9-11e5-9cea-af6d81800b07.png)

So maybe https://github.com/pymc-devs/pymc3/commit/79971ca0ea3cc62d614324c0567385e362e02fb9 introduced the problem.

**Comment by twiecki** [comment]
OK, a git bisect indeed found https://github.com/pymc-devs/pymc3/commit/79971ca0ea3cc62d614324c0567385e362e02fb9 to introduce the problem.

**Comment by robdmc** [comment]
@twiecki  Does NUTS still get stuck for lower target_accept in the reverted version?

**Comment by twiecki** [comment]
@robdmc it does not get stuck.

**Comment by fonnesbeck** [comment]
I wonder if #982 is related?

**Comment by twiecki** [comment]
Yes, that's a duplicate.

**Comment by twiecki** [comment]
CC @jsalvatier

**Comment by fonnesbeck** [comment]
It appears that `FastArrayStep` is what introduced the issue.

**Comment by twiecki** [comment]
Which was later replaced with the current `ArrayStepShared`

**Comment by twiecki** [comment]
There's a lot more going on in that PR though, what makes you say it was `FastArrayStep` specifically?

**Comment by twiecki** [comment]
This should be fixed with https://github.com/pymc-devs/pymc3/commit/141f5f7e3ddd330ce75d1f8404d6113717c8cfec. Thanks @jsalvatier for debugging this with me.
![image](https://cloud.githubusercontent.com/assets/674200/13831309/12a20a22-ebd3-11e5-820f-d01d5ad1d3e3.png)

**Comment by robdmc** [comment]
Just reinstalled and confirmed its fixed for me as well.  @twiecki @jsalvatier @fonnesbeck thanks for such a quick response for diagnosing and fixing this.  Much appreciated.

**Comment by twiecki** [comment]
Thanks for checking @robdmc. Very happy we fixed this and now able to close this issue.
