### ISSUE TITLE
Slice sample slow to start for large (~400) parameter models

### ISSUE THREAD

**Issue by grburgess** [pymc-devs/pymc#1019]
Hello, this is probably simply a matter of having to wait, but I'm finding that the slice sampler can take an incredibly long time (in fact I have yet to get it started) to start when there are a large number of parameters. Metropolis starts right up very quickly, butI have hierarchical priors which need Gibbs sampling.

My model is below:
`with lcModel2:

```
# Light Curve Priors
#t0 = pm.Uniform('t0',lower=0.,upper=100.,    shape=nData)
#x0 = pm.Uniform('x0',lower=1E-7, upper=1E-1, shape=nData)
#x1 = pm.Normal('x1',mu=0., sd=2.,            shape=nData)


# Cosmology Priors
#H0 = theano.shared#pm.Normal("H0",mu=72.,sd=8.)
OmegaM = pm.Uniform("OmegaM",lower=0,upper=1.)

M = pm.Uniform("M",lower=-20.,upper=-18.)
taninv_alpha = pm.Uniform("taninv_alpha",lower=-.2,upper=.3)
taninv_beta = pm.Uniform("taninv_beta",lower=-1.4,upper=1.4)
sysScat_log = pm.Uniform("sysScat_log",lower=log10(0.05),upper=0)





xm=pm.Cauchy('xm',alpha=0,beta=1)
cm=pm.Cauchy('cm',alpha=0,beta=0.3)
Rx_log=pm.Uniform('Rx_log',lower=-0.5,upper=0.5)
Rc_log=pm.Uniform('Rc_log',lower=-1.5,upper=1.5)


alpha=pm.Deterministic('alpha',T.tan(taninv_alpha))
beta=pm.Deterministic('beta',T.tan(taninv_beta))
Rx=pm.Deterministic("Rx",10**Rx_log)
Rc=pm.Deterministic("Rc",10**Rc_log)
sysScat = pm.Deterministic('sysScat',10**sysScat_log)



x_true  = pm.Normal('x_true',mu=xm, sd=Rx,shape=len(jlaSet['color']))
c_true  = pm.Normal('c_true',mu=cm, sd=Rc,shape=len(jlaSet['color']))

dm = get_distMod(OmegaM)

mb = pm.Normal("mb",mu=M + dm - alpha*x_true + beta*c_true,sd=sysScat,shape=len(jlaSet['color']))

obsc=pm.Normal("obsc",mu=c_true,sd=array(jlaSet['dcolor']), observed=jlaSet['color'])
obsx=pm.Normal("obsx",mu=x_true,sd=array(jlaSet['dx1']), observed=jlaSet['x1'])

obsm = pm.Normal("obsm",mu=mb,sd=array(jlaSet['dmb']),observed=jlaSet['mb'])
`
```

and 

`
with lcModel2:
    start2=pm.find_MAP(fmin=optimize.fmin_powell)
with lcModel2:

```
step1=pm.Slice()
trace2=pm.sample(20000,step=step1,start=start2,progressbar=True,)`
```

Is this just an issue of having to wait, or is there a more efficient way to start up the sampler?

Thanks in advance!

**Comment by fonnesbeck** [comment]
The slice sampler, as currently implemented in PyMC3, is really only intended for scalar variables. It can be generalized to vector-valued stochastic, but we have not done that yet. This may be the source of your issue. In general, we recommend using NUTS or HMC for continuous variables, as it is more efficient. In fact, if you do not even specify a step method, PyMC should do a reasonable job of auto-selecting.

**Comment by grburgess** [comment]
Ah, this explains a lot :)

My problem then comes because I'm using as @as_op decorator for one of the functions. Therefore (if I understand correctly) Theano can't compute the gradient and I cannot use HMC. Importing this function from python is basically why I'm using PyMC over Stan. I can't easily re-code the function for Stan.

When you say vector-values stochastic, you mean anything that is pm.<distribution>(....., shape=N), correct? 

Is there a hack around this? I could in principle create a scalar variable  for each via a loop. But this would be very impractical.

Metropolis really does not want to converge.

**Comment by fonnesbeck** [comment]
Well, the "hack" is to generalize `Slice` to do multivariate slice sampling (see Neal 2003). Failing that, PyMC2 also has AdaptiveMetropolis (Haario et al). which can sometimes improve convergence when Metropolis fails, so re-imlementing the model in PyMC2 is another way forward. If you cannot use gradient based methods, then Theano doesn't do you much good, so there isn't an advantage to PyMC3.

**Comment by grburgess** [comment]
Yeah :(  That is unfortunate. But I'm right to assume that with a hierarchy, Metropolis will most likely fail, correct? 

Thanks again!

**Comment by fonnesbeck** [comment]
As in hierarchical models? Not necessarily. Metropolis can be inefficient for larger models, and particularly when there are correlations among variables (which is where adaptive Metropolis can help), but I have fit many a hierarchical model with just Metropolis sampling.

**Comment by grburgess** [comment]
Ok, then I will see how it runs. PYMC is awesome, thanks for it!
