### ISSUE TITLE
wouldn't a v3.0.0b2 nicely fit with a Theano0.8.0 ?

### ISSUE THREAD

**Issue by stonebig** [pymc-devs/pymc#1027]
Theano0.8.1rc1 is out, so a new pymc3 beta would be helpfull for me.

**Comment by twiecki** [comment]
I like that suggestion. Lets make it happen.

**Comment by stonebig** [comment]
how to make it happen ?

**Comment by twiecki** [comment]
You could send in a PR that updates the version numbers.

**Comment by stonebig** [comment]
current tag is '3.0' ... shall I replace per '3.0.0b2' ?

**Comment by twiecki** [comment]
We need to delete that tag. But yes, for the new version, the tag should be `v3.0b2`.

**Comment by twiecki** [comment]
or is it `v3.0.b2`? Maybe you can check if there's an official standard.

**Comment by stonebig** [comment]
standard has been modernized recently. there is a pep-0440 https://www.python.org/dev/peps/pep-0440/

it is written 
`
X.Y and X.Y.0 are not considered distinct release numbers, as the release segment comparison rules implicit expand the two component form to X.Y.0 when comparing it to any release segment that includes three components. 
`

I prefer an explicit second zero in the source, rather getting it by algorithmic method.

**Comment by twiecki** [comment]
I'd prefer to only use 2, we probably won't do these fine-grained releases.

**Comment by stonebig** [comment]
any timeline to get this b2 out ? (the 'Milestones' page of github is not helpfull to guess pymc3 intentions)
