### ISSUE TITLE
small tweak suggestion for `getting_started.ipynb` example

### ISSUE THREAD

**Issue by stonebig** [pymc-devs/pymc#1028]
Some PC are 10 times slower than the one used to build the `getting_started.ipynb` example.

This may comfort the new user discovering pymc3:
- place `progressbar=True` everywhere on this first notebook ,
- suggest in comments an 'SP500.csv'  with an alternate address that always works.

```
# if  'SP500.csv' doesn't work, try with
# returns = pd.read_csv(
'https://raw.githubusercontent.com/pymc-devs/pymc3/master/docs/notebooks/data/SP500.csv', index_col=0, parse_dates=True)
```

**Comment by stonebig** [comment]
suggesting an 'SP500.csv'  with an address that works always may help ?
````
# or:
# returns = pd.read_csv('https://raw.githubusercontent.com/pymc-devs/pymc3/master/pymc3/examples/data/SP500.csv', index_col=0, parse_dates=True)
````

**Comment by stonebig** [comment]
the SP500.csv has only one column and no title ?

**Comment by twiecki** [comment]
+1 want to do a PR with your updates?

**Comment by springcoil** [comment]
:+1:

**Comment by stonebig** [comment]
will try. resulting Notebook will be upgraded to Ipython4 (python3) format

**Comment by stonebig** [comment]
PR https://github.com/pymc-devs/pymc3/pull/1030

**Comment by springcoil** [comment]
Closing this because of the other PR.
