### ISSUE TITLE
PPC Predictions for Randomwalk/Defining RV shape at runtime

### ISSUE THREAD

**Issue by Miles-Garnsey** [pymc-devs/pymc#1036]
How is it intended that the PPC (#862) function works with randomwalk variables for prediction? I'm trying to get predictions out of a latent variable/state space model and I'm having trouble.

I have the below model which tracks a simple mean over time with some added noise in the observations (based on this link) but because it sets the shape of the random walk based on the data at compile time, I can't find a way to predict outcomes for new data.

There are two problems here;
1. You can't use a TensorVariable (and hence a shared variable) to set a shape
2. You can't concatenate TensorVariables where you don't know the length of the output

```

import theano as th, pandas as pd, numpy as np, pymc3 as pm, theano.tensor as T, ggplot as gg

#Create some simulated data - imagine a different mean for each day, where a variable number of 
#observations occurs for each day.
data = np.array([1,1,1,1,4,4,4,4,4,4,3,3,3,7,7,7,8,8,8,6,6,6,6,6])
data = pd.DataFrame({'nonoise': data})
data['vals'] = data.nonoise + np.random.normal(0, .3, size = len(data))

#array counting number of rows for each "day"
data_repeats = data.groupby(by = 'nonoise').count().vals.values

#try setting the shared variables with a numpy array instead of a pandas df
data_repeats = th.shared(data_repeats)
data = th.shared(data.values)
test_model = pm.Model()

expected_time_var = 10.0
expected_within_time_var = .3

with test_model:
    sigma_alpha = pm.Exponential('sigma_alpha', 1/expected_time_var, testval = .5)

    #First issue - leaving the data in a shared variable (which is advised in the PPC tutorial) 
    #means you can't use it to set the shape. simply using the argument shape = data.shape will fail with
    #TypeError: Expected int elements in shape because the shape argument can't handle symbolic variables.

    alpha = pm.GaussianRandomWalk('alpha', sd=sigma_alpha, mu=0, 
                                  shape = data_repeats.get_value().shape)    

    #Second issue - using the below code gives an error: length not known: ARange{dtype='int64'} [id A] ''
    #alpha_daily = [alpha[i].repeat(pattern[i]) for i in T.arange(0, data_repeats.shape[0])]    
    #Using this code does work, but appears to set the computational graph for a dataset of a specific length at compile time?
    alpha_daily = T.concatenate([alpha[i].repeat(data_repeats[i]) for i in range(0, data_repeats.shape[0].eval())])

    sigma_L = pm.Exponential('sigma_L', 1/expected_within_time_var)

    likelihood = pm.Normal('like', mu=alpha_daily, tau=sigma_L, 
                           observed = data[:,1]) #observed is the vals from the shared data set

#Compute MAP
from scipy import optimize
with test_model:
    MAP = pm.find_MAP(vars = [alpha, sigma_L], fmin = optimize.fmin_bfgs)
    ppc_MAP =  pm.sample_ppc(np.array([MAP]), size = 10000)

##################################################################################################################
##########################################All works OK up to here.################################################
##################################################################################################################
#construct some new data of length 8
steps = [np.random.normal() for i in range(0, 7)]
new_data = [reduce(lambda x, y: x+y, steps[i-2:i]) for i in range(2, len(steps)+2)]
new_data = pd.DataFrame({'nonoise': np.zeros(len(steps)), 'vals': new_data })

#load data into the shared variable
data.set_value(new_data.values)

#generate new predictions using the existing trace (which is actually just a MAP)
with test_model:
    newdata_ppc =  pm.sample_ppc(np.array([MAP]), size = 10000)
    newdata_pred = np.mean(ppc_MAP['like'], axis = 1)#.reshape(len(steps))

newdata_pred.shape # = (1L, 24L) - Not 8 as expected

```

**I think maybe this raises a more general question for me about how the shape argument works.** Even in a simple situation where we have a piecewise linear model and wanted to infer the number of breakpoints as a random variable from the data, would this be possible to do without being able to pass a Stochastic to the shape parameter of another RV?

I think pymc3 has amazing potential for creating really flexible models, but I keep encountering issues like this - I guess what Fonnesbeck calls show stoppers? Maybe my Theano knowledge just isn't good enough to see the solutions to this stuff, hopefully someone can give me some advice if there is a workaround?

**Comment by twiecki** [comment]
Just to give you a way forward with the stoch vol model, you can just append nans to your input data. PyMC3 will treat that as missing values an sample it which will give you your predictions.

I haven't experimented with flexible shape arguments, I was hoping that it might work. Changing dimensionality of your model is very hard to deal with, for the samplers alone, so I don't see us supporting that anytime soon. It probably requires an architecture that takes that into account from the beginning.

**Comment by hvasbath** [comment]
The shape of intermediate tensors could change within the graph, but the shape of inputs cannot change.
Also you dont need to make your data shared before setting up your model. So that you can get its shapes. 

Then after that, you can make the data shared right at the time once you access it.
observed = T.shared(data[:,1])

**Comment by Miles-Garnsey** [comment]
This is some really interesting info guys, thanks for your help!

@eigenblutwurst, if the shape of intermediate tensors can change does that mean that you could potentially make the shape of an RV change at runtime as long as your input remained the same size? I'm not sure how the RVs are implemented in pymc3, I had the naive idea that each element of an array type RV was a node in the computational graph, but that doesn't sound right now I think about it... I'm guessing the RV is a node and has a shape property?

@twiecki , I can see an NA padding scheme like you describe working. Just FYI I'm not doing stochastic vol, it's more of a [rolling regression](https://pymc-devs.github.io/pymc3/rolling_regression/). Realized the link got lost in my original post sorry.

Two questions on your suggestion (apologies for my ignorance if they're silly). 
1. Will having NA values padding out the end of the dataset add to the  runtime of the sampler at training time? Or are these simply ignored because they make no contribution to the likelihood? 
2. Assuming the above is correct, is there any way we could create a method which updates the likelihood to include those points without a complete refit? Mathematically, using the posterior as a prior and then running the model over the new points should work I think?

If I'm right about the above two questions, then I can see a few ways forward... But maybe point 2 might require the addition of the particle filter sampler? Also I'm happy to contribute/ update a tutorial if that would help out as I'm keen to contribute back.

**Comment by hvasbath** [comment]
@Miles-Garnsey  Thats right each RV is a theano tensor, which has a node and a shape, but as mentioned this needs to be constant during initialisation. Everything after that can change.

**Comment by twiecki** [comment]
> Will having NA values padding out the end of the dataset add to the runtime of the sampler at training time? Or are these simply ignored because they make no contribution to the likelihood?

It definitely slows it down in my experiences, PPC from the trace is faster but harder to implement for non-iid models. I'm not quite sure where the slow-down comes from, can only be the addition of new RVs and increased dim for the sampler. And you still have to evaluate the priors. 

> Assuming the above is correct, is there any way we could create a method which updates the likelihood to include those points without a complete refit? Mathematically, using the posterior as a prior and then running the model over the new points should work I think?

Not a bad idea, that could definitely work.

**Comment by fretchen** [comment]
Hi,

I am not sure if this is exactly the same issue. But let me assume that I had data, that I modeled with a GaussianRandomWalk. Then I would typically like to compare them to the posterior and run something like this:

`ppc = pm.sample_ppc(trace, samples=500, model=RwModel)`

However, as I run this I obtain the following:

`AttributeError: 'GaussianRandomWalk' object has no attribute 'random'`

Could this be fixed in an intermediate step ?

**Comment by ferrine** [comment]
@fretchen it is not implemented, we'd rather raise `NotImplementedError`

**Comment by twiecki** [comment]
Actually, you can add missing values for your predictions which will then show up in the trace.

**Comment by matfiore** [comment]
I was wondering if there has been any follow-up on this topic.

@Miles-Garnsey I am also interested in point 2 you described and would be happy to understand if there is the chance to team-up and contribute.
