### ISSUE TITLE
Mini-batch in ADVI

### ISSUE THREAD

**Issue by taku-y** [pymc-devs/pymc#1038]
I'm going to implement mini-batch in advi (https://github.com/taku-y/pymc3/commit/0424b9373caef6b04b64b5b7913303095f7316a2; https://gist.github.com/taku-y/b4da34be310718a6ea02) and don't know how to implement the sample size correction; for fair comparison with full-batch estimation, log likelihood needs to be multiplied by (total sample size) / (mini-batch size), but I don't know the best way to do that. Do I need to modify logp methods in distribution classes, or is there another option?

**Comment by twiecki** [comment]
That's exciting!

Multiplying the summed model logp (i.e.https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L190)? Seems like it would be easiest to just do the scaling where you retrieve the model logp for evaluating it. I'm afraid I might be missing something.

**Comment by taku-y** [comment]
@twiecki Thanks for your reply. 

Thanks to the code you pointed out, I have solved the problem. In the modified code (https://github.com/taku-y/pymc3/commit/3565d2e1d2216e3dec0cec6c44c59c7b8a1b840a), logpt is constructed with separation of mini-batched RVs (observed RVs given tensors as observations) and other RVs. It worked fine for the simple Gaussian model (https://gist.github.com/taku-y/b4da34be310718a6ea02). I will do test with the radon model.

**Comment by springcoil** [comment]
Cool! Awesome stuff

**Comment by taku-y** [comment]
The minibatch advi seems to work on the hierarchical regression model for radon data: https://gist.github.com/taku-y/4a60e7c610fb6ea7d2d3

**Comment by twiecki** [comment]
Nice! How did you fix the scaling issue?

**Comment by taku-y** [comment]
I have written the following code for calculation of logp. 

``` python
    # Correction sample size 
    r = 1 if total_size is None else \
        float(total_size) / minibatch_tensors[0].shape[0]

    is_minibatch = lambda var: True if var.data_ in minibatch_tensors else False
    minibatched_RVs = [var for var in model.observed_RVs if is_minibatch(var)]
    other_RVs = set(model.basic_RVs) - set(minibatched_RVs)
    factors = [r * var.logpt for var in minibatched_RVs] + \
              [var.logpt for var in other_RVs] + model.potentials
    logpt = T.add(*map(T.sum, factors))
```

is_minibatch is used to check that given RV is mini-batched, which means that observations of that RV are given as theano tensor and replaced with mini-batch in calculation of logp. 

For this check, I also added a field data_ in the class ObservedRV in model.py. This field is used only to keep the tensor representing observation of that RV. Instead, we can keep the ObsveredRVs when constructing the model as follows:

``` python
data_t = T.vector()
data_t.tag.test_value = np.zeros(1)
minibatched_RVs = []
with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sd=1, testval=0)
    sd = pm.HalfNormal('sd', sd=1)
    n = pm.Normal('n', mu=mu, sd=sd, observed=data_t)
    minibatched_RVs.append(n)
```

minibatched_RVs should be passed to the advi function. If using this way, we don't need to modify  the code of ObservedRV.

**Comment by twiecki** [comment]
> If using this way, we don't need to modify the code of ObservedRV.

If it simplifies the code, I think it's worth considering changing ObservedRV. I suppose you would want to add a mini-batch flag?

**Comment by taku-y** [comment]
Thanks for your suggestion. But keeping mini-batch RVs is easy, so currently I will change my code where mini-batch RVs are explicitly given to the advi function.

**Comment by twiecki** [comment]
:+1:

**Comment by taku-y** [comment]
Make a notebook with a simple gaussian mixture model. https://gist.github.com/taku-y/a884a0ee78fb89bf5735

**Comment by twiecki** [comment]
This is my favorite thread -- great new example!

Are you working on a PR for all of ADVI? Seems like it's pretty close but should have some tests.

**Comment by springcoil** [comment]
I am enjoying this thread too

**Comment by taku-y** [comment]
@twiecki I'm not sure the quality of code is enough, anyway I'll send a PR onto the advi branchi. I also  added a test on ELBO for a simple Gaussian model the same in Stan. 

@springcoil Thank you for looking at the notebooks. That motivates me : )

**Comment by taku-y** [comment]
It should be noted that the current impl of mini-batch does not support local latent variables. A specific example is LDA, which have document-wise topic proportion theta. This random variable is associated with a mini-batch and has variational posterior. Thus, in addition to the subsample mini-batch, variational parameters corresponding to the mini-batch should be replaced on the graphical model during ADVI computation. I will try to implement thin near future.

**Comment by twiecki** [comment]
Sounds great, thanks for the heads up.

**Comment by taku-y** [comment]
I implemented mini-batch ADVI with local latent variables. To demonstrate, I have applied it to LDA (https://gist.github.com/taku-y/66c9613ab29a150e4493b899a6507354).  But it need to check the program works correctly. To this end, I'm trying to calculate predictive distribution as suggested in a paper (Hoffman et al., 2013 JMLR). In addition, I will check words with high probability in topics. 

In the notebook, I described how mini-batch ADVI with local latent variables work. Since both local and global latent variables are included in the model, these two types of parameters are alternately updated. This is achieved by an interface similar to MCMC. Specifically, ADVI step objects are defined for the local and global variables. 

The program (uploaded to my local repo https://github.com/taku-y/pymc3/tree/advi_minibatch) and interface should be refined. Any comments are appreciated.

**Comment by twiecki** [comment]
@taku-y This is really cool, and the speed of inference is very impressive.

The API looks pretty good to me too. I suppose it's better to do a full code-review during a PR, do you think it's close?

I also tried ADVI on a bayesian neural network I have been working on, but without much success: https://gist.github.com/aa6f4eb469bb12d5959c5f51a04e68ec (see at the very bottom). Any ideas?

**Comment by taku-y** [comment]
@twiecki Thanks for checking the notebook. 

First, I apologizes that there was a bug in putting local variational parameters into the model. After fixing this, the speed of inference became slow. I updated the notebook. 

I think at least we need to check that inference works fine. To this end, I'm trying to calculate the predictive log likelihood for a dataset and compare it with the reported value in a paper (say, Hoffman et al., 2013). After that, I will send a PR. 

Your ADVI example on NN is very appealing. Your model looks fine for me so I'm not sure why ADVI does not work. I will try to run your notebook to check.

**Comment by taku-y** [comment]
@twiecki I tested your notebook and ADVI works well on your Bayesian NN model as long as looking at ELBO (https://gist.github.com/taku-y/6fabb9b905a6639019369ef418960bd2). Your problem could be due to setting of Theano (.theanorc).

**Comment by twiecki** [comment]
@taku-y Thanks for your help. After updating Theano it works correctly. I'll use this in my PyData talk tomorrow :).

**Comment by twiecki** [comment]
Even works with mini-batch ADVI, this is amazing!

**Comment by twiecki** [comment]
It only works if I set the mini-batch inputs to be theano vector/matrix, but not shared:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-c369f5d94f75> in <module>()
      2     model=neural_network, n=40000, minibatch_tensors=minibatch_tensors,
      3     minibatch_RVs=minibatch_RVs, minibatches=minibatches,
----> 4     total_size=total_size, learning_rate=1e-2, epsilon=1.0
      5 )

/home/wiecki/working/projects/pymc/pymc3/variational/advi.py in advi_minibatch(vars, start, model, n, n_mcsamples, minibatch_RVs, minibatch_tensors, minibatches, total_size, learning_rate, epsilon, verbose)
    173 
    174     # Create in-place update function
--> 175     f = theano.function(minibatch_tensors, [shared_inarray, grad, elbo], updates=updates)
    176 
    177     # Run adagrad steps

/home/wiecki/miniconda3/lib/python3.5/site-packages/theano/compile/function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    318                    on_unused_input=on_unused_input,
    319                    profile=profile,
--> 320                    output_keys=output_keys)
    321     # We need to add the flag check_aliased inputs if we have any mutable or
    322     # borrowed used defined inputs

/home/wiecki/miniconda3/lib/python3.5/site-packages/theano/compile/pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    440                                          rebuild_strict=rebuild_strict,
    441                                          copy_inputs_over=True,
--> 442                                          no_default_updates=no_default_updates)
    443     # extracting the arguments
    444     input_variables, cloned_extended_outputs, other_stuff = output_vars

/home/wiecki/miniconda3/lib/python3.5/site-packages/theano/compile/pfunc.py in rebuild_collect_shared(outputs, inputs, replace, updates, rebuild_strict, copy_inputs_over, no_default_updates)
    173             raise TypeError(('Cannot use a shared variable (%s) as explicit '
    174                              'input. Consider substituting a non-shared'
--> 175                              ' variable via the `givens` parameter') % v)
    176 
    177     # Fill update_d and update_expr with provided updates

TypeError: Cannot use a shared variable (<TensorType(float64, matrix)>) as explicit input. Consider substituting a non-shared variable via the `givens` parameter
```

Any idea?

**Comment by taku-y** [comment]
To use shared variables instead of tensors, we need to modify advi.py L173-183 as follows:

``` python
    # Create in-place update function
    f = theano.function([], [shared_inarray, grad, elbo], updates=updates)

    # Run adagrad steps
    elbos = np.empty(n)
    for i in range(n):
        for m, t in zip(minibatches, minibatch_tensors):
            t.set_value(next(m))
        uw_i, g, e = f()
        elbos[i] = e
        if verbose and not i % (n//10):
            print('Iteration {0} [{1}%]: ELBO = {2}'.format(i, 100*i//n, e.round(2)))
```

In the original code, tensors in 'minibatch_tensors' are treated as function inputs and then the arrays in 'minibatches' are given to the function. In the above code, the values of shared variables in 'minibatch_tensors' are set to the arrays in 'minibatches'. 

If we should change the interface of advi_minibatch() to accept shared variables, I will modify the code and send a PR. 

Hope your talk will go well!

**Comment by twiecki** [comment]
@taku-y this is implemented now, right? I'll close it.
