### ISSUE TITLE
Wrong logp in LKJ prior

### ISSUE THREAD

**Issue by ssnl** [pymc-devs/pymc#1042]
As we know, LKJ prior with parameters n, p defines a distribution over p-by-p correlation matrices. When n = 1, it is uniform over all such matrices. As n goes large, the distribution becomes more concentrated around the identity matrix.

To illustrate this bug, let's restrict our attention to the case where p = 2. 
From [this paper (page 6)](http://www.sciencedirect.com/science/article/pii/S0047259X09000876), we know that Pr[R] \propto |R|^(n-1). For 2-d correlation matrices, |R| is apparently maximized at R = I, when |R| = 1. All other R has 0 < |R| < 1.

So if we increase n (> 1), \sum_{R} |R|^(n-1) decreases, and Pr[I] = (|I|^(n-1)) / (\int_{R} |R|^(n-1)) should increase.

However, 

```
>>> import pymc3 as pm
>>> f = theano.function([], pm.LKJCorr.dist(1, 2).logp(np.array([0])))
>>> f()
array(0.6931471824645996)
>>> f = theano.function([], pm.LKJCorr.dist(10, 2).logp(np.array([0])))
>>> f()
array(-0.5664327677286938)
>>> f = theano.function([], pm.LKJCorr.dist(100, 2).logp(np.array([0])))
>>> f()
array(-1.728976562499895)
```

**Comment by twiecki** [comment]
CC @kiudee.

**Comment by kiudee** [comment]
The determinant of the identity matrix is always 1, which is why the log probability

``` python
(n - 1.) * T.log(det(X))
```

is zero. Thus in this case the decreasing log probability is caused only by the normalization constant.

**Comment by ssnl** [comment]
@kiudee Yes, but the normalizing constant should be decreasing since each <code>(n - 1.) \* T.log(det(X))</code> decreases (or stays the same in case of <code>X = I</code>). Then <code>logp(I)</code> should increase.

**Comment by fonnesbeck** [comment]
Did this get resolved? Sounds like something that needs a test.

**Comment by twiecki** [comment]
@kiudee?

**Comment by kiudee** [comment]
If we suspect a bug in the normalization constant it could be fruitful to check the implementation in Stan:
[stan::math::do_lkj_constant(eta, K)](https://github.com/stan-dev/math/blob/afe06d84d1b92dd3e16c01d5ed0d508e0fe9e047/stan/math/prim/mat/prob/lkj_corr_log.hpp)

**Comment by twiecki** [comment]
@kiudee Thanks. For now, I trust your judgement that @SsnL's comments are moot.

**Comment by ssnl** [comment]
My arguments are fairly simple and easy to follow. So I still hold the opinion that this is a bug. But whether to investigate/fix it or not is up to you guys.

**Comment by junpenglao** [comment]
Cross comparing the implementation in [stan::math](https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/prob/lkj_corr_lpdf.hpp), I believe our implementation is correct.
You can also validate the normalizing constant of LKJCorr using eq 17 and 18 in LKJ:
```python
def lkj_norm(eta, n):
    constant = 0.
    for k in range(1, n):
        constant += np.log(np.pi) * (k / 2.)
        constant += gammaln(eta + (n - 1 - k) / 2.)
        constant -= gammaln(eta + (n - 1) / 2.)
    return constant
```
