### ISSUE TITLE
import convention theano.tensor

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1044]
Now I start the pedantic housekeeping as @fonnesbeck called it

At the moment theano.tensor is imported in three different ways throughout the code:
    import theano.tensor as t, T, tt

I think we should agree on one version as @twiecki keeps track on that so nicely for numpy as np ;)

I vote for (if I have a right for voting):
    import theano.tensor as tt

**Comment by twiecki** [comment]
Yes, we have a bit of a mess there that would be good to clean up. I kinda like `tt` too. Is there an established standard?

**Comment by springcoil** [comment]
I like tt too.

On Mon, Mar 28, 2016 at 5:45 PM, Thomas Wiecki notifications@github.com
wrote:

> Yes, we have a bit of a mess there that would be good to clean up. I kinda
> like tt too. Is there an established standard?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/1044#issuecomment-202449454

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
Theano itself is a little inconsistent in usage. I have seen `tt` in the code base, but several tutorial examples use `T`. I don't really care, as long as it is consistent, though for readability simply using `tensor` is kind of nice.

**Comment by twiecki** [comment]
The problem with `tensor` is that it makes some math hard to read as it's using a lot in one from the same namespace.

**Comment by fonnesbeck** [comment]
Fair enough. Let's just go with `tt` then, and replace everything else globally (including examples).

**Comment by stonebig** [comment]
keras and Lasagne seem to use `from theano import tensor as T`

**Comment by twiecki** [comment]
`T` has the benefit of being one letter shorter (seems small but it does help with many calls). @nouiz Any theano-endorsed standard?

**Comment by nouiz** [comment]
Personnaly, I prefre tt.
- a capital t like T.sum() put emphasis on the T, I prefer not that as this isn't the important part. tt.sum() don't put emphasis on the tt.
- tt is more like np, np is standard.

We didn't agree strongly on something, but that something was "from theano import tensor" and I find it too long.

T is longer, but as it is a capital and most font take a size that depend of the leter, tt don't take much more space in the screen. You also don't need to press the sift key, so you end up pressing the same number of key.

**Comment by twiecki** [comment]
Thanks @nouiz! It seems like most people prefer `tt` so lets go with that.

**Comment by springcoil** [comment]
Cool

**Comment by twiecki** [comment]
@hvasbath Want to do a PR?

**Comment by hvasbath** [comment]
Yes will do that!

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/1141.
