### ISSUE TITLE
Hide auto-transformed variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1050]
We presently keep variables that have been auto-transformed by the sampler in the same data structures as the user-specified variables. This results in more variables in the trace than the user specified, which can be confusing for the user. Since these transformations are simply an internal tool for the sampler, we should keep them entirely separate from the rest of the variables in the model. In fact, do we even need to record traces for these? Seems like unnecessary overhead.

**Comment by twiecki** [comment]
Or maybe at least make it optional with the default to false.

**Comment by fonnesbeck** [comment]
This has been resolved (to my satisfaction, at least) by the underscore convention.
