### ISSUE TITLE
ImportError: No module named variational

### ISSUE THREAD

**Issue by pinqinshen** [pymc-devs/pymc#1056]
I installed pymc3 through the default git branch with pip, when I am trying to import pymc3, I have this error (I use python 2.7):

 `from pymc3 import Model, Normal, HalfNormal`

```
Traceback (most recent call last):
  File "<pyshell#55>", line 1, in <module>
    from pymc3 import Model, Normal, HalfNormal
  File "F:\ApplySoftwareBase\User\Scripts\Python\lib\site-packages\pymc3\__init__.py", line 12, in <module>
    from .variational import *
ImportError: No module named variational `
```

I uninstalled Theano and reinstall it again and couldn't fix this problem

**Comment by fonnesbeck** [comment]
Actually, this is an artifact. `variational` should not be in master yet. It is only in the advi branch.

EDIT: scratch that, did not notice the merge of advi yesterday. How did that merge pass TravisCI?

**Comment by pinqinshen** [comment]
Thanks for your attention, but how could I fix this problem and use this package??

**Comment by fonnesbeck** [comment]
Should be fixed in master now.
