### ISSUE TITLE
Rugby analytics example implementation is wrong

### ISSUE THREAD

**Issue by lwiklendt** [pymc-devs/pymc#1059]
No wonder Peadar had trouble predicting the result ;)
`home_theta  = tt.exp(intercept + home + atts[away_team] + defs[home_team])`
should really be:
`home_theta  = tt.exp(intercept + home + atts[home_team] + defs[away_team])`

**Comment by springcoil** [comment]
Wanna do the PR?

**Comment by lwiklendt** [comment]
Nah, go ahead, I don't have the proper setup at the moment.

**Comment by springcoil** [comment]
I fixed this up.
