### ISSUE TITLE
Extremly slow stochastic block model

### ISSUE THREAD

**Issue by abojchevski** [pymc-devs/pymc#1063]
Consider the following model:

```
N = A_obs.shape[0]
K = 2
model = pm.Model()
with model:
    pi = pm.Dirichlet('pi', a=0.5 * np.ones(K))
    eta = pm.Beta('eta', alpha=1, beta=1, shape=(K, K))
    q = pm.Categorical('q', p=pi, shape=(N,))

    A = [pm.Bernoulli('A_{}_{}'.format(i, j), p=eta[q[i], q[j]])
                                     for i in range(N) for j in range(N)]

    step1 = pm.Metropolis(vars=A + [pi, eta])
    step2 = pm.ElemwiseCategoricalStep(vars=[q], values=[0, 1])
    tr = pm.sample(3000, step=[step1, step2])
```

The model takes extremly long time to run even for small values of `N < 10`. The actually sampling is fast, however building the model is not.

I'm guessing because A is written as a list of `N * N` random variables. I tried to specify A with `shape=(N, N)` but without much success.

Any suggestions?

**Comment by abojchevski** [comment]
Most of the time is spent it theano's `process_node`

**Comment by fonnesbeck** [comment]
Can you make this example runnable so that we can debug it?

**Comment by usptact** [comment]
@abojchevski Did you have a success to get this model run? I also notices that model building get slowed down very significantly if the random variables are built iteratively in a list (or using T.stack to hold an array of RVs).

**Comment by joseduc10** [comment]
This issue has been inactive for more than a year, but in case someone is still interested, I was able to infer the parameters for the basic stochastic block model by building it as below:

```python
def make_pymc3_sbm(Gs, k, weighted=False, directed=False, selfloops=False):
    # input can be a single graph or a list of graphs
    if isinstance(Gs, nx.Graph):
        Gs = [Gs]
    n = len(Gs[0])
    # whether to include the diagonal or not
    if selfloops:
        triu_indices = np.triu_indices(n, k=1)
    else:
        triu_indices = np.triu_indices(n)
    # convert to adjacency matrix
    # if graph is undirected, we just need the upper triangular part
    if directed:
        A_obs = np.array([nx.to_numpy_array(G) for G in Gs])
    else:
        A_obs = np.array([nx.to_numpy_array(G)[triu_indices] for G in Gs])

    model = pm.Model()
    with model:
        pi = pm.Dirichlet('pi', a=np.ones(k), shape=(k,))
        z = pm.Categorical('z', p=pi, shape=(n,))
        if weighted:
            eta = pm.Gamma('eta', alpha=.001, beta=.001, shape=(k, k))
        else:
            eta = pm.Beta('eta', alpha=1, beta=1, shape=(k, k))
        # parameters to sample the adjacency matrix
        # p[i, j] = eta[z[i], z[j]] is the parameter corresponding to A[i, j]
        p = eta[(z.reshape((n, 1)), z.reshape((1, n)))]
        if not selfloops:
            tt.set_subtensor(p[np.diag_indices(n)], 0.)
        if not directed:
            p = eta[(z.reshape((n, 1)), z.reshape((1, n)))][triu_indices]
        if weighted:
            A = pm.Poisson('A', mu=p, shape=A_obs[0].shape, observed=A_obs)
        else:
            A = pm.Bernoulli('A', p=p, shape=A_obs[0].shape, observed=A_obs)
    return model
```

This model doesn't scale that well. Even for relatively small graphs (n=120) and number of blocks (k=16), it starts to take 20 minutes for 5,000 iterations with NUTS. Also, the convergence tests show poor convergence for some parameters. If someone has any suggestions on how to improve convergence speed by reparameterization, that would be great.

**Comment by usptact** [comment]
@joseduc10 Thanks for the code snippet! Do you have some sample observations and/or a full script to run this?

**Comment by joseduc10** [comment]
@usptact Thank you for the quick reply! I am using the following  synthetic data generator:

```python
import networkx as nx

# let's generate some data
# there are 2 communities (even and odd nodes)
# intra community edge probability is 0.8
# inter community edge probability is 0.1
Gs = []
p = .8
q = .1
t = 100
for i in xrange(t):
    G = nx.Graph()
    G.add_nodes_from(range(10))
    for i in xrange(10):
        for j in xrange(i + 1, 10):
            theta = p if (i % 2 == j % 2) else q
            if np.random.random() < theta:
                G.add_edge(i, j)
    Gs.append(G)
    
# show first 5 graphs
pos = nx.spring_layout(Gs[0])
colors = np.array(['r', 'b'])
ground_truth = np.array([i % 2 for i in xrange(10)])
for i in xrange(5):
    G = Gs[i]
    nx.draw(G, node_color=colors[ground_truth], with_labels=True, pos=pos)
    plt.show()
    plt.close()
```
Then, I prepare the model and sample with default options:
```python
k = 2
model = make_pymc3_sbm(Gs, k)
with model:
    tr = pm.sample(5000)
```

This runs in about 26 seconds in my Mac with an Intel Core i7 2.5GHz and 16GBs of memory. However, I get warnings about the gelman-rubin statistic being larger than 1.4.

**Comment by joseduc10** [comment]
This other model for a weighted directed graph with 120 nodes takes more than 2 hours per chain. Also, the chains are sampled sequentially because the model cannot be pickled! I hope these examples help. I can send you a jupyter notebook too.

```python
def generate_sbm(eta, z, selfloops=False, directed=False, weighted=False):
    G = nx.DiGraph() if directed else nx.Graph()
    k = eta.shape[0]
    n = len(z)
    G.add_nodes_from(range(n))
    for i in xrange(n):
        # if graph is directed, consider all (i, j) pairs
        # otherwise, just consider pairs for which i <= j
        start = 0 if directed else i
        for j in xrange(start, n):
            # skip selfloop
            if i == j and not selfloops:
                continue
            eta_e = eta[z[i], z[j]]
            # if weighted sample edge from Poisson
            # otherwise, sample from Bernoulli
            if weighted:
                w_e = np.random.poisson(eta_e)
            else:
                w_e = 1 * (np.random.random() < eta_e)
            # we add an edge if the weight is greater than 0
            if w_e > 0:
                G.add_edge(i, j, weight=w_e)
    return G

t = 100
k = 3
n = 120
eta = np.array([
               [2, 1, 1], 
               [1, 10, 1], 
               [1, 1, 3]
              ])

z = np.array([i / (n / k) for i in xrange(n)]) # split the graph evenly
Gs = [generate_sbm(eta, z, directed=True, weighted=True) for i in xrange(t)]

model = make_pymc3_sbm(Gs, k, weighted=True, directed=True)
with model:
    tr = pm.sample(5000)
```

**Comment by joseduc10** [comment]
One more comment about my model. For undirected graphs, I still generate an (n x n) matrix of parameters p, for each entry of the adjacency matrix, even though we really just need (n * (n - 1) / 2) parameters. This feels hacky, but I could not think of a better way to express the model in vector form.

**Comment by usptact** [comment]
@joseduc10 Fantastic! Yes, a notebook would be even better. Thanks a lot for sharing the code!
(1) About the number of parameters: perhaps you can keep your matrix (n x n) but add pairwise factors that make respective entries of the matrix equal? This restriction should effectively reduce the number of parameters in the model (you still need memory to store those). Maybe PyMC3 devs can chime in to approve or not this idea.
(2) To speed up sampling: maybe you need to do better initialization? E.g. use some MLE solver's output as initialization and see if you get speedup.
(3) Maybe it makes sense to randomly initialize "z" with cluster assignments.
