### ISSUE TITLE
`njobs=None` Sampling Error

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#1064]
When running `pm.sample(..., njobs=None)`, I get a `NameError`.  Looks like [this](https://github.com/pymc-devs/pymc3/blob/master/pymc3/sampling.py#L132) line wants to use `mp` as an alias for `multiprocessing`, but the import above it is missing the `... as mp` portion.

**Comment by twiecki** [comment]
Fixed by #1065.
