### ISSUE TITLE
Modeling question (Switch)

### ISSUE THREAD

**Issue by abojchevski** [pymc-devs/pymc#1067]
First of all I am not sure if this belongs here or on stackoverflow but anyhow here is the problem.

Suppose I have the following model 

```
pi = pm.Dirichlet('pi', a=0.5 * np.ones(K))
q_ij = pm.Categorical('q_ij', p=pi, shape=(N, 1))
q_ji = pm.Categorical('q_ji', p=pi, shape=(1, N))
eta = pm.Beta('eta', alpha=1, beta=1, shape=(K, K))

A = pm.Bernoulli('A', eta[q_ij, q_ji], shape=(N, N), observed=A_obs)
```

This works just fine with `Metropolis` and `SequentialScanDiscreteMetropolis` steps and I am able to learn the correct parameters.

Now suppose I want to create an additional node `A_prime` such that:

```
A_prime[i, j] = 
    Bernoulli (1 - theta)       if A[i, j] == 1
    Bernoulli (theta)           if A[i, j] == 0
```

where`theta = pm.Beta('theta', alpha=1, beta=1)`.

And then instead of providing the observations to `A`, I provided them to `A_prime`

In order to achieve that I tried the following:

`A_prime = pm.Bernoulli('A_prime', t.switch(t.eq(A, 1), 1 - theta, theta), shape=(N, N), observed=A_obs)`
where  `t`  is `theano.tensor`.

But with that change I am no longer able to learn the correct parameters. Any idea what might be going on?

**Comment by fonnesbeck** [comment]
Using the Theano `switch` function is indeed the correct approach. Do post this to StackOverflow with a runnable example for some help.
