### ISSUE TITLE
How did you check convergence based on the z-score?

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#1071]
I am reading the source code to find out what approach do you use for checking convergence. The first one is to calculate the z-score. But when I search `geweke` on further, I can't find anything. I wonder how do you use the array `zscores` to determine whether the chain is convergent? Thanks in advance!

**Comment by fonnesbeck** [comment]
You are looking for evidence of lack of convergence from z-scores that are extreme (e.g. > 2 standard deviations from zero). Initial z-scores correspond to pieces of the chain that are closer to the start, so you can use it to see if you have excluded a large enough portion of the chain as burn-in. I don't use it a whole lot, however; I think Gelman-Rubin is more useful.

**Comment by ghost** [comment]
Thanks for your reply! So if the -scores are all within 2 standard deviation from zero, I can determine that it is likely convergent and I can start to use the following samples?

**Comment by fonnesbeck** [comment]
Using statistical convergence diagnostics, you can't prove convergence. It can provide evidence for _lack_ of convergence if the test is positive. That's why it is better to use a couple of methods rather than relying on just one.

**Comment by ghost** [comment]
@fonnesbeck  So what if there are two parameters to estimated? How should I store them in the parameter of `x`. Should it be like:

```
[x_1,x_2,x_1,x_2] 
```

or

```
[[x_1,x_1],[x_2,x_2]]
```

?
Thanks!

**Comment by fonnesbeck** [comment]
Check out the [documentation](https://pymc-devs.github.io/pymc/modelchecking.html) for details.

**Comment by ghost** [comment]
@fonnesbeck  I have tried that piece of code directly. Seems that you have assumed the estimated value as scalar variable. But what if it is a matrix, say, a topic distribution over documents? How can I modify it to calculate the z-score fast? Thanks!

**Comment by fonnesbeck** [comment]
It will call itself recursively. See line 284:

``` python
if np.ndim(x) > 1:
        return [geweke(y, first, last, intervals) for y in np.transpose(x)]
```

**Comment by ghost** [comment]
@fonnesbeck Yes, it works when the parameter is a vector. But when the parameter is a matrix, it will measure the z-score between the vectors within the matrix, which is totally wrong.

**Comment by fonnesbeck** [comment]
I see. You could extract the raw trace, flatten it and then pass it to `geweke`. The diagnostics should work on raw output as well as PyMC nodes.
