### ISSUE TITLE
Broken example: survival_analysis

### ISSUE THREAD

**Issue by ppope** [pymc-devs/pymc#1074]
Greetings `pymc3` developers, 

I attempted to run the 'survival_analysis' notebook in pymc3/examples but was unsuccessful. Can anyone advise on a fix? 

Here's what I did. I installed `pymc3` to a virtual environment:

```
conda create -n pymc3_test_env python=2.7 ipython-notebook seaborn statsmodels
source activate pymc3_test_env
pip install git+https://github.com/pymc-devs/pymc3.git
```

The notebook runs as expected until we inspect mean of the traces of beta, where I obtain

```
np.exp(trace['beta'].mean())
Out[17]:
1.0
```

implying that the sampling for $\beta$ is all zeros. The expected result is `1.645592148084472` (referenced from [the original blog post](http://austinrochford.com/posts/2015-10-05-bayes-survival.html)).

[Issue #1072](https://github.com/pymc-devs/pymc3/issues/1072) suggests the model is misspecified. However, I'm unable to find any misspecifications in the model, and of course the notebook worked at some point. So I'm lead to believe that a bug has been introduced somewhere in development.

A gist of my attempt at running the notebook can be found [here](https://gist.github.com/ppope/ba619020542237db9a2199c9f59e577f).

Also, note that in the [gist](https://gist.github.com/AustinRochford/afe6862e622c31494b2f) where this notebook was originally posted, several users have commented about the same problem.

I'd be happy to dig into this further. Please let me know how I can help.

**Comment by gkalman1** [comment]
As someone not very knowledgeable of pymc3, who is frustrated with the same issue running the [survival analysis example](https://pymc-devs.github.io/pymc3/survival_analysis/), I am wondering if this problem is being acknowledged (i.e., reproducible by those much more knowledgeable about pymc3)? Or should I keep spending time on trying to install/reinstall various components with the hope that the installation needs to be somehow different than what I have?.

**Comment by AustinRochford** [comment]
Hi, I am the author of that example.  I will look into this over the weekend.

**Comment by AustinRochford** [comment]
Can confirm that this notebook is broken on a fresh install of `pymc3`, will look into fixing it when I can.

**Comment by AustinRochford** [comment]
When I change the initial `test_val` of `beta` to ones, `trace['beta']` is all ones.  No jumps are being accepted; perhaps some of the `Metropolis` step defaults have changed since I initially wrote this?

**Comment by fonnesbeck** [comment]
I came across this as well. I can't get it to work with any samplers. I'm actually not sure how it ever worked, since some of the exposure values are zero, which would reduce the Poisson parameter to zero, returning -inf, and hence, rejection.

**Comment by AustinRochford** [comment]
@fonnesbeck that is a good point; perhaps something has changed with how Poisson RVs handle zero means?  (This seems unlikely.)

I don't have a ton of time to work on fixing this in the next couple of weeks.  Do we want to pull it until I have time to revisit and hopefully fix in a month or two?

**Comment by ppope** [comment]
Some colleagues of mine noticed that the example can be made to work by adding a small perturbation to the exposure matrix. See this [gist](https://gist.github.com/ppope/8f51411f51a139cdc8ebc56b981439c2).

**Comment by ppope** [comment]
Perhaps the problem is with [`Poisson.logp`](https://github.com/pymc-devs/pymc3/blob/efbca862f0065769902d515469253ae99a4790fd/pymc3/distributions/discrete.py#L200-204)? It looks like it allows values of zero.

**Comment by fonnesbeck** [comment]
Strictly speaking, the Poisson rate parameter only has positive support, however you can contrive to have it return a defined likelihood for lambda=0 when the value is also 0. I can try this and see what happens.

**Comment by fonnesbeck** [comment]
An additional issue is that there is hierarchical structure specified for beta, but there is only one beta:

```
tau = pm.Deterministic('tau', sigma**-2)
mu_beta = pm.Normal('mu_beta', 0., 10**-2)
beta = pm.Normal('beta', mu_beta, tau)
```

Unless you are modeling group or individual effects (i.e. `beta` has a non-scalar value), the hierarchical structure is not going to do anything for you.

**Comment by AustinRochford** [comment]
Excellent catch.  I had been experimenting individual effects and forgot to
remove that.

On Wed, May 11, 2016 at 8:28 AM, Chris Fonnesbeck notifications@github.com
wrote:

> An additional issue is that there is hierarchical structure specified for
> beta, but there is only one beta:
> 
> tau = pm.Deterministic('tau', sigma**-2)
> mu_beta = pm.Normal('mu_beta', 0., 10**-2)
> beta = pm.Normal('beta', mu_beta, tau)
> 
> Unless you are modeling group or individual effects (i.e. beta has a
> non-scalar value), the hierarchical structure is not going to do anything
> for you.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/1074#issuecomment-218444523

## 

## 

_Austin Rochford_
Principal Data Scientist @ Monetate
o: (877) 666-3828 x382 | m:
arochford@monetate.com

Watch our Video
http://content.monetate.com/h/i/11572086-welcome-to-monetate | Marketing
Blog http://monetate.com/blog/ | Free Resources
http://monetate.com/resources/ | Follow Monetate on Twitter
http://twitter.com/monetate
http://www.monetatesummit.com
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016
https://www.regonline.com/monetatesummit2016

**Comment by fonnesbeck** [comment]
I think this is taken care of now. Please have a look. The example now uses NUTS.

**Comment by AustinRochford** [comment]
👍 looks great! Thanks for jumping on this.

**Comment by dbikiel** [comment]
Could it be broken again? The example runs but the chains do not converge. I am not quite sure how to add what @fonnesbeck commented.
