### ISSUE TITLE
Error in PeerJ article

### ISSUE THREAD

**Issue by andrewgiessel** [pymc-devs/pymc#1075]
Hey guys fantastic work.  I was reading the peerj publication and found some discrepancies between the code and figures there.  Basically, the figures are from the most recent "Getting started" notebook, 
but the code to build the predictor (X) and observed data (Y) is not.  It is a simple change:

The code in the paper is: 

```
# Predictor variable
X1 = np.linspace(0, 1, size)
X2 = np.linspace(0,.2, size)
```

but should actually read:

```
# Predictor variable
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2
```

After this change, everything matches (the plots in figure 1 as well as the resulting trace).

Thanks for all your hard work, this is a fantastic package and the paper is extremely lucid as well!

**Comment by fonnesbeck** [comment]
Thanks for the catch. Unfortunately, I don't think there is an avenue for correcting this in the paper, and the error seems not to be present in the corresponding documentation notebook.
