### ISSUE TITLE
HMM in pymc3

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1077]
Hi,

I am trying to convert a stan example to pymc3 which uses HMM. The log likelihood is calculated (using the forward algorithm) as follows:

```
    for (t in 2:N) {
        for (k in 1:K) {
            for (j in 1:K)
                acc[j] <- lg_alpha[t-1,j] + log(theta[j,k]) + normal_log(y[t],mu[k],sigma[k]);
            lg_alpha[t,k] <- log_sum_exp(acc);
        }
    }
    increment_log_prob(log_sum_exp(lg_alpha[N]));
```

I understand that I probably have to use `DensityDist` but I'm not too familiar with theano to write the above code efficiently. Could someone give me a starting point so that I could implement this? `y[t]` are the only obesrvations here.

My second question is that is there a way to ensure that mu[1]>mu[2]>mu[3]. This will avoid some of the problems of label switching and stan implements this with `ordered` variables.

**Comment by springcoil** [comment]
Can you reproduce the stan code in full and your PyMC3 version?

**Comment by springcoil** [comment]
Any update on this?

**Comment by twiecki** [comment]
Closing for now, feel free to reopen if this is still relevant @sachinruk
