### ISSUE TITLE
Mixture of Categoricals

### ISSUE THREAD

**Issue by psinger** [pymc-devs/pymc#1080]
I am currently playing around with PyMC3 and am trying to implement a simple mixture of categoricals. However, I have quite some troubles with achieving results I expect. I have summarized my individual attempts in a notebook: http://nbviewer.jupyter.org/gist/psinger/045bd92f0c096c69a4b8762cc6040ed1

In general, we can see that the results are really odd, when I am trying to use 2 or 3 clusters with some clustered data and then use symmetric Dirichlet priors for the categoricals. Only in one case I end up with the results I expect: When I have extreme data with corresponding extreme Dirichlet priors for two clusters (last experiment in notebook).

Any idea what I am doing wrong here? Thanks!

**Comment by twiecki** [comment]
Seems like you forgot to post the notebook.

**Comment by psinger** [comment]
Sorry about that, I edited the post.

**Comment by twiecki** [comment]
Feel free to reopen if this is still an issue.
