### ISSUE TITLE
summy definition

### ISSUE THREAD

**Issue by jtamagnan** [pymc-devs/pymc#1081]
The definition of the `summary` function in stats.py seems to be incorrect. The description describes a function parameter called `tofile` but the name of the parameter in the function is `to_file`. Either the documentation should be changed to reflect the function or the function should be changed to reflect the documentation. One of the other parameters is called `roundto` so it would make sense to rename the `to_file` to `tofile` but that would not be backwards compatible.

**Comment by bhargavvader** [comment]
Can this be closed now?
