### ISSUE TITLE
Survival model example fails with NUTS

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1086]
I have been unable to get the survival model to run when using the NUTS sampler. I have tried using reasonable `testval` values and `find_MAP`, but to no avail. This should be an appropriate model for NUTS, since all the model parameters are continuous. In general, I find `find_MAP` to be unreliable, as it either fails or produces poor initial values.

**Comment by fonnesbeck** [comment]
One issue is that the survival model ends up having some zeros in the exposure times, which will always return a `-inf` log likelihood. So, using `Metropolis` fails as well. When was the last time this example worked?

**Comment by fonnesbeck** [comment]
Duplicate of #1074

**Comment by AustinRochford** [comment]
@fonnesbeck I [posted](http://austinrochford.com/posts/2015-10-05-bayes-survival.html) this example on my blog on October 5, 2015, so it worked at least that recently.
