### ISSUE TITLE
Exception on Categorical with missing value imputation

### ISSUE THREAD

**Issue by gabrielelanaro** [pymc-devs/pymc#1091]
Hi, I was experimenting with the missing values imputation (which is pretty awesome) for a variety of variable types.

I stumbled across this problem: if I sample with a (useless) model in this way:

``` python
x_obs = [1, 1, 0, 0, 2, 2, 2]

with pm.Model() as multin_model:
    x = pm.Categorical('x',  [0.33, 0.33, 0.33], shape=3, observed=x_obs)
    y = pm.Normal('y', shape=3)
    v = y[x] * pm.Normal('z')
    step = pm.Metropolis()
    trace = pm.sample(1000, step=step)
```

It runs without exception, but as soon as I introduce missing values I get an IndexError exception:

``` python
x_obs = np.ma.masked_equal([1, 1, 0, 0, 2, -1, -1], -1)

with pm.Model() as multin_model:
    x = pm.Categorical('x',  [0.33, 0.33, 0.33], shape=3, observed=x_obs)
    y = pm.Normal('y', shape=3)
    v = y[x] * pm.Normal('z')
    step = pm.Metropolis()
    trace = pm.sample(1000, step=step)
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/gabriele/anaconda/envs/medschool/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

IndexError: index 3 is out of bounds for size 3

During handling of the above exception, another exception occurred:
... long traceback
```

Is the feature unsupported?

**Comment by fonnesbeck** [comment]
For some reason PyMC is assigning `Metropolis` to the missing values of the Categorical; it should be `ElemwiseCategoricalStep`. I will have a look.

**Comment by fonnesbeck** [comment]
OK, this is because missing values get assigned a Metropolis sampler by default. This is very bad news for binary or categorical variables, as proposals will be very inefficient. I will fix this, thanks.

**Comment by fonnesbeck** [comment]
There is another issue here, in that you declare the shape of your variable as 3, when it is actually 7 (it is the size of the values, not the parameters), but this does not get caught.

**Comment by gabrielelanaro** [comment]
Thank you so much!
