### ISSUE TITLE
Feature Request: Add option for custom distributions

### ISSUE THREAD

**Issue by jolespin** [pymc-devs/pymc#1092]
One distribution I am particularly interested in is "spike-and-slab prior" which is contains a bernoulli spike and gaussian slab.  I've found an example an implementation in R (https://github.com/snowdj/BoomSpikeSlab/blob/master/R/spike.slab.prior.R) but would rather implement this in Python and PyMC3 seems to be like the perfect avenue.  If this feature is currently available, can someone direct me to a tutorial. Thanks :)

**Comment by twiecki** [comment]
It's not available but shouldn't be hard to construct. At the core it's a mixture model and there are a couple examples of that, e.g.: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/gaussian_mixture_model.ipynb

**Comment by jolespin** [comment]
Perfect, that's what I needed to get started.  Thanks again!
