### ISSUE TITLE
Categorical distribution bound not enforced early enough

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1093]
In the `logp` for the categorical distribution, the method rightly bounds the value at the appropriate index limits for the vector of probabilities, However, since the log-probability is calculated before the bound is checked, you can still get an IndexError. Unfortunately, Theano breaks the usual exception handling for this.

**Comment by srlindsay** [comment]
Is it sufficient to just mod by k to avoid the index error and allow the bound to handle the invalid value?

e.g. `a = T.log(p[value % k])`

**Comment by twiecki** [comment]
@srlindsay I think that would hide useful model errors.

@fonnesbeck Seems like bounds should always be checked before evaluation, can `bound()` be rewritten to do so?

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/3386.
