### ISSUE TITLE
Shape argument passed to an observed variable is ignored

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1094]
If you specify a `shape` argument for an observed variable, this parameter is silently ignored in favor of the shape of the `observed` value. Specifying `shape` should return an error if specified and does not correspond to the passed data.

**Comment by ColCarroll** [comment]
This is still a funny corner case if anyone wants to fix it: 
![image](https://user-images.githubusercontent.com/2295568/63176372-d3b0c600-c013-11e9-829b-ce7e26687b0d.png)

**Comment by twiecki** [comment]
Feel free to reopen if this is still an issue.
