### ISSUE TITLE
ElemwiseCategoricalStep is broken

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1096]
ElemwiseCategoricalStep appears not to be sampling validly. Here is a simple example:

```
x_obs = [1, 1, 0, 0, 2, 2, 2]

with pm.Model() as model:
    x = pm.Categorical('x',  [0.33, 0.33, 0.33], observed=x_obs)
    x_ = pm.Categorical('x_',  [0.33, 0.33, 0.33], shape=1)
    trace = pm.sample(1000)
```

Results in:

![unknown-3](https://cloud.githubusercontent.com/assets/81476/15269348/9b8b0b4c-19c1-11e6-98fe-22efe761d19c.png)

Somehow this step method was merged without a real test. The current test only checks whether assignment works as expected, and not the functionality of the sampler itself.

**Comment by fonnesbeck** [comment]
I am going to set `ElemwiseCategoricalStep` competence universally to INCOMPATIBLE until this can be fixed.

**Comment by abojchevski** [comment]
Changing the probability assignment to `[0.33, 0.33, 0.34]` in your example seem to fix the problem. Something weird happens if `p` doesn't sum up to 1 maybe?

**Comment by twiecki** [comment]
Interesting, that's probably just hitting a `bound` restriction in the likelihood. Maybe a simple renormalization will fix it.

**Comment by fonnesbeck** [comment]
I noticed that also. I'm not sure we should renormalize without letting the user know. Maybe better to just enforce sum-to-one arguments?

**Comment by twiecki** [comment]
yeah, that's easy enough to do.

**Comment by fonnesbeck** [comment]
Working on it now

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/1135.

**Comment by abojchevski** [comment]
The check does not work when the sum-to-one input is another random variable. 

Minimum example that throws the error:

```
import pymc3 as pm
import numpy as np

with pm.Model() as model:
    pi = pm.Dirichlet('pi', a=np.ones(3))
    x_ = pm.Categorical('x_',  pi, shape=1)
    trace = pm.sample(1000)
```

The error is:

```
TypeError: sum() got an unexpected keyword argument 'out'
```

**Comment by twiecki** [comment]
Ah, good catch.

**Comment by fonnesbeck** [comment]
The PR was not ready for merge.

**Comment by abojchevski** [comment]
In the current implementation an else statement is missing:

```
    def competence(var):
        distribution = getattr(var.distribution, 'parent_dist', var.distribution)
        if isinstance(var.distribution, Categorical):
            if var.distribution.k>2:
                return Competence.IDEAL
            else:
                return Competence.COMPATIBLE
        # this is missing
        else:
            return Competence.INCOMPATIBLE
```

If the if statement fails, the `Competence` returned is `None`, which in turn yields an error when sorting through the competences and assigning step values

```
TypeError: unorderable types: NoneType() > Competence()
```

**Comment by fonnesbeck** [comment]
Actually, on master it is still set to `INCOMPATIBLE`:

```
    @staticmethod
    def competence(var):
        distribution = getattr(var.distribution, 'parent_dist', var.distribution)
        # if isinstance(var.distribution, Categorical):
        #     if var.distribution.k>2:
        #         return Competence.ideal
        #     else:
        #         return Competence.compatible
        return Competence.INCOMPATIBLE
```

but I need to go in and turn it on again.
