### ISSUE TITLE
Still errors with Cox model

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1105]
I tried to reproduce this http://nbviewer.jupyter.org/gist/fonnesbeck/1be22dba803645fcc949 and see if the recent changes in advi etc would work - it failed however. 
Any reason why this fails, is there anything we can fix?
cc @fonnesbeck

**Comment by springcoil** [comment]
cc @twiecki this is what I was talking about

**Comment by twiecki** [comment]
After rebasing the init-advi branch I got it to work: https://gist.github.com/3df8f0067c367f09eed2f97a7d3b0ab3

**Comment by fonnesbeck** [comment]
Actually, I am confused by this model. All of the columns of `X` are not of the same length (`inter2` is shorter than the others), so I'm not sure how the dot product with beta works.

``` python
In [21]: [len(Xi) for Xi in X]
Out[21]: [430, 430, 430, 430, 430, 430, 301]
```

I need to have a closer look at this.

**Comment by fonnesbeck** [comment]
Never mind, the error seems only to be in my copy of the  model.
