### ISSUE TITLE
Two questions on sum of distributions/convolution

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#1108]
Dear all!

I have an imaging experiment which I want to model and infer some parameters.

The observed signal is the sum of two Poisson distributions, i.e. noise at a certain level, that I want to infer and some signal. 
How to set up this sum? Something like:

```
image = pymc3.Poisson("image", shape=two_d_shape,mu=image_ideal)
noise = pymc3.Poisson("noise", shape=two_d_shape,mu=mu_noise)
model = pymc3.DensityDist("model", logp=noise+image)
```

does not work. That's probably a simple question, but I have no idea. That might be related to my  missing knowledge of theano?

----- 2.

However, `image_ideal` is not so ideal. In fact, it is blurred and can be described by a convolution of the theoretical image and a blurring term. The kernel size of this blurring is generally smaller than the image. How to handle this convolution with pymc3.

Thanks a lot in advance for any help!

Best wishes

Markus

**Comment by fonnesbeck** [comment]
If you have already assigned distributions to the original variables, and all you want is the sum, you would want to use a `Deterministic` object instead.

```
model = pymc3.Deterministic('model', noise+image)
```

or if you werent interested in keeping the trace of this object, you can even just do:

```
model = noise + image
```

BTW, for questions about PyMC, we recommend posting to StackOverflow's [pymc tag](http://stackoverflow.com/questions/tagged/pymc) or the PyMC Gitter channel. Please restrict posts here to bug reports.
