### ISSUE TITLE
Feature Request: Option between Theano & Tensorflow Backend (eventually)

### ISSUE THREAD

**Issue by jolespin** [pymc-devs/pymc#1115]
As PyMC3 continues to grow, it would be nice to be able to choose backends eventually.  `Theano` is great but `Tensorflow` would be nice to use as well.  An example of this type of backend choice would be `holoviews` that can use either `matplotlib` or `bokeh` as a backend.  It also wouldn't hurt having backing by `Google` :)

**Comment by springcoil** [comment]
This has been discussed. I don't think it's in the pipeline right now. The backend idea for Bokeh and Matplotlib is an interesting idea - do you think it's difficult to do?

**Comment by jolespin** [comment]
Hey thanks for responding, I was talking about `tensorflow` WAY further down the development line to get the idea out there.  As far as `bokeh`, `holoviews` would be a good reference to use since they have some pretty high-level plotting features.  I'm not sure exactly how difficult it would be to implement tho :/

**Comment by twiecki** [comment]
Thanks @jolespin, it's a good suggestion for the future but I'll close this to keep the issue tracker more focused.
