### ISSUE TITLE
Refactor transformed variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1116]
The presence of automatically-transformed variables in the model and output has become a point of confusion in PyMC3. Though they have recently been hidden from the trace of MCMC samplers, they still arise in other places (e.g. MAP estimation). I'm increasingly of the opinion that if a particular sampler requires a transformed variable to improve the mechanics of its particular algorithm, then that transformed variable should be an attribute of that sampler, and not show up in the output in any permanent way (e.g. being tallied in the trace).

**Comment by kyleabeauchamp** [comment]
Couldn't the original model keep track of the the "human" parameterization by various adding some non-tracing deterministics.  Then MAP could operate inplace on a model object.  Then there could be a "show()" function that prints the current state of all variables that are tagged as tracing.  

Alternatively, the MAP function could return an object that is smarted about what it displays.

**Comment by twiecki** [comment]
The other option is to not pass around `start` to begin with. I know it's supposed to be more functional but we do store the state of the model currently in `testval`. Would also simplify the API, but certainly not be as "pure".

**Comment by fonnesbeck** [comment]
@kyleabeauchamp that is sort of already what happens. The original variable is turned into a deterministic while the transformed variable takes its place as a stochastic. This is why the transformed variable is always shown while the original variable is sometimes excluded, depending on the context. 

The simplest approach might be for the transformed variable to be an attribute of the original variable, so that it can be used when needed (I.e. For sampling) but ignored otherwise. We already have the transformation as an attribute, so it may be a natural extension.

**Comment by majidaldo** [comment]
had a usability issue when i wanted to use logp of a model. really shouldn't have to supply both the transformed and the original variable.

**Comment by twiecki** [comment]
I think you only have to supply the transformed variable, no? It is a bit unfortunate in any case though.

**Comment by fonnesbeck** [comment]
To get at the `logp` of the original variable, you can use `v.transformed.distribution.dist.logp`. Is this not what you are after?

**Comment by majidaldo** [comment]
@twiecki  yes you have to supply the transformed variable. else, it will error. the behavior should be that you need to supply /either/ the original or transformed.

**Comment by fonnesbeck** [comment]
No longer relevant

**Comment by rpgoldman** [comment]
Overtaken by events.
