### ISSUE TITLE
hierarchical example needs annotation

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1117]
The `hierarchical.ipynb` example seems to have been committed in an intermediate state, and includes a lot of extraneous code. The example should include extensive annotation to explain what the example is trying to show. We should have a cleaner example for an illustration of hierarchical modeling, which is a core application of Bayesian modeling.

**Comment by twiecki** [comment]
Agreed, that one isn't very useful. We do have the hierarchical regression one which explains a lot of things. I think @jonsedar also has great examples.

**Comment by jonsedar** [comment]
Thanks Tom, I do have this from my PyData talk - it goes overboard on all the comparisons etc, but I could cut it down to the basics if you like. I'll see if I have time to PR at the weekend https://github.com/jonsedar/pymc3_vs_pystan/blob/master/40_HierarchicalLinearRegression.ipynb
