### ISSUE TITLE
TravisCI tests failing due to timeouts with examples

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1130]
Not sure why this has resurfaced, but it may be time to thin out the number of examples that we include in CI. Perhaps those which have corresponding notebooks can be removed from the .py examples folder?

**Comment by springcoil** [comment]
:+1:

**Comment by fonnesbeck** [comment]
Tried arbitrarily removing the first few examples, but it doesn't seem to matter which subset I use; it always times out.

**Comment by springcoil** [comment]
Do we need to pay for a bigger server?

**Comment by fonnesbeck** [comment]
We may just need to stop testing examples, at least for the short term.
