### ISSUE TITLE
Having trouble with custom distribution

### ISSUE THREAD

**Issue by danielbarter** [pymc-devs/pymc#1145]
Hi there,

I have been messing around with pymc3 recently and haven't been able to figure out how to do the following:

If I have two previously implemented distributions f(x|theta) and g(x|phi), is there an easy way to implement the new distribution p(x|theta,phi,b) which equals f when b = 0 and g when b = 1?

**Comment by fonnesbeck** [comment]
Hi Daniel. Best to post this to StackOverflow (with a pymc label) or on Gitter. The issues tracker is just for bug reporting. 

Sounds like you are talking about the `switch` function though.

**Comment by danielbarter** [comment]
@fonnesbeck: thanks! will do
