### ISSUE TITLE
Log probability for each sample

### ISSUE THREAD

**Issue by abojchevski** [pymc-devs/pymc#1150]
Is there a better way to calculate the log probability for each sample that this?

```
  trace = pm.sample(10000)
  logp = [model.logp(trace[i]) for i in range(len(trace))]
```

Since this solution doesn't scale with increasing number of iterations.

**Comment by kyleabeauchamp** [comment]
I can save you 20 keystrokes, but not solve the scaling problem:

```
logp = list(map(model.logp, trace))
```

I think the "real" answer to this question might also belong in the following notebook:

https://pymc-devs.github.io/pymc3/notebooks/howto_debugging.html

E.g. one might want to plot the logp for each step in a trace, or have it printed during sampling.

**Comment by twiecki** [comment]
@abojchevski Have you profiled this? I'm not convinced the loop is really adding a lot of overhead.

**Comment by aseyboldt** [comment]
The logp should really be in the sampler_stats. I'll write a pull request.

**Comment by aseyboldt** [comment]
The logp should really be in the sampler_stats. I'll write a pull request for this.

**Comment by abojchevski** [comment]
@kyleabeauchamp I have not profiled it, but it simply seemed sub-optimal given that we can definitely do it in vector form. As the number of samples get larger, the small overhead can add up.

**Comment by twiecki** [comment]
@abojchevski You should never need that many samples. But in general, having logp be part of the sampler stats seems useful, @aseyboldt.

**Comment by aloctavodia** [comment]
@abojchevski probably a little bit late, but this should be faster

```python
ml = model.logp
logp = [ml(i) for i in trace]
```

**Comment by junpenglao** [comment]
For completeness, this is what you should do (in case of multi-trace):
```python
logp = model.logp
lnp = np.array([logp(trace.point(i, chain=c)) for c in trace.chains for i in range(len(trace))])
```
Otherwise the solution above only takes the samples from the first chain.
