### ISSUE TITLE
Memory usage with sparse matrices

### ISSUE THREAD

**Issue by igorraush** [pymc-devs/pymc#1157]
I've been trying to implement a very simple logistic regression model, using a sparse design matrix of 0's and 1's (coming from one-hot encoded categorical data). I am seeing large spikes in memory usage. 

Here is a simple example demonstrating the problem (**will briefly use 4GB of memory**):

``` python
from __future__ import division, print_function

import numpy as np
import pymc3 as pm
from scipy import sparse as sp
from scipy.optimize import fmin_l_bfgs_b
from scipy.special import expit
from theano import sparse as S
np.random.seed(0)

# properties of sparse design matrix (taken from the real data)
N = 100000  # number of samples
M = 5000    # number of dimensions
D = 0.002   # matrix density

# fake data
mu0, sd0 = 0.0, 1.0
w = np.random.normal(mu0, sd0, M)
X = sp.random(N, M, density=D, format='csr', data_rvs=np.ones)
y = np.random.binomial(1, expit(X.dot(w)), N)

# estimate memory usage
size = X.data.nbytes + X.indices.nbytes + X.indptr.nbytes + y.nbytes
print('{:.2f} MB of data'.format(size / 1024 ** 2))

# model definition
with pm.Model() as model:
    w = pm.Normal('w', mu0, sd=sd0, shape=M)

    p = pm.sigmoid(S.dot(X, w.reshape((-1, 1)))).flatten()
    pm.Bernoulli('y', p, observed=y)

    print(pm.find_MAP(vars=[w], fmin=fmin_l_bfgs_b))
```

The sparse matrix occupies roughly 13MB. Incidentally, when it is converted into a dense matrix, it occupies 4GB which corresponds to the peaks in memory usage:

![memory profile](http://i.stack.imgur.com/g5IqI.png)

I am aware the problem may well lie entirely in Theano, but I am not sure how to reproduce it outside the PyMC context. Hoping someone can point me in the right direction.

**Comment by twiecki** [comment]
Yes, I think that way the array will be converted to dense. Very early on there were some examples of using `scikit-sparse` with pymc3 which we should dig back out.

**Comment by twiecki** [comment]
Just looked at the code, that's just for sparse scaling matrices for HMC, so not relevant here.

It's a good question why that would be converted. Could be a Theano issue, @nouiz, any idea?

**Comment by igorraush** [comment]
I profiled the `find_MAP` function. Memory seems to spike [here](https://github.com/pymc-devs/pymc3/blob/13496d623b510460b04c15484e398d4290566cfc/pymc3/tuning/starting.py#L70) and [here](https://github.com/pymc-devs/pymc3/blob/13496d623b510460b04c15484e398d4290566cfc/pymc3/tuning/starting.py#L94), although if I understand correctly, no actual computation is happening there, it's just preparing a Theano graph... 

Also, tried to reproduce outside PyMC with the following snippet:

``` python
from __future__ import print_function, division

import numpy as np
from theano import tensor as T, sparse as S, function
from scipy import sparse as sp
from memory_profiler import memory_usage

#
N = 100000
M = 5000
D = 0.002

#
X = S.csr_dmatrix('X')
w = T.dvector('w')
p = T.sum(T.nnet.sigmoid(S.dot(X, w.reshape((-1, 1)))).flatten())

f = function([X, w], p)
g = function([X, w], T.grad(p, w))
h = function([X, w], T.hessian(p, w))

X_ = sp.random(N, M, density=D, format='csr', data_rvs=np.ones)
w_ = np.random.normal(0, 1, M)

f_ = f(X_, w_)
g_ = g(X_, w_)
h_ = g(X_, w_)

print(memory_usage())
```

but the memory usages remains under 200 MB.

**Comment by nouiz** [comment]
pymc3 enable compute_test_value. Can you disable it after importing pymc3? I don't know if this will break pymc3 or not. Otherwise, the 2 url to code you give point to pymc3 code. Can you go deeper in those to see more in detail what cause this memory increase?

**Comment by igorraush** [comment]
@nouiz @twiecki Turning off `compute_test_value` did break PyMC, while instantiating the observed RV:

```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python2.7/site-packages/pymc3/model.py", line 312, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "/usr/local/lib/python2.7/site-packages/pymc3/model.py", line 596, in __init__
    self.tag.test_value = theano.compile.view_op(data).tag.test_value
AttributeError: scratchpad instance has no attribute 'test_value'
```

However, it appears that **test values are the culprit**. I modified my Theano snippet from above to enable computing test values (and got rid of the cost function and Hessian which were irrelevant):

``` python
from __future__ import print_function, division

import numpy as np
from scipy import sparse as sp
from theano import tensor as T, sparse as S, function, config

config.compute_test_value = 'raise'

N = 100000
M = 5000
D = 0.002

X_ = sp.random(N, M, density=D, format='csr', data_rvs=np.ones)
w_ = np.random.normal(0, 1, M)

X = S.csr_dmatrix('X'); X.tag.test_value = X_
w = T.dvector('w'); w.tag.test_value = w_
p = T.sum(T.nnet.sigmoid(S.dot(X, w.reshape((-1, 1))).flatten()))

g = function([X, w], T.grad(p, w))

print(g(X_, w_))
```

which gives the following memory profile:
![memory profile](https://cloud.githubusercontent.com/assets/1361385/15833649/9a448376-2bdc-11e6-86bf-cedabdf800e9.png)

Specifically, memory usage spikes at `T.grad(p, w)`.

**Comment by igorraush** [comment]
Finally identified the problem and filed Theano/Theano/issues/4599 (it is entirely outside PyMC). In short, Theano computes the test value of `d(Xw)/dX`, which is a dense matrix with the same dimensions as `X`. Thanks @twiecki and @nouiz!

**Comment by twiecki** [comment]
Thanks for reporting back @igorraush. Hopefully Theano can provide a fix soon, sparse support in pymc3 would be a great feature.

**Comment by nouiz** [comment]
I don't have time today to investigate. But I always taught that having
compute_test_value by default be a bad idea. But I understand that you like
this idea:)

But I think you should at least allow the user to disable this. Also, I
think you should not read var.tag.test_value directly, but use:
gof.op.get_test_value(var) This will raise a better error if the test value
is disabled and you request it.

**Comment by twiecki** [comment]
@nouiz Thanks for the pointers. I think there is a better way than using test_value, it's not the best design choice I think.

**Comment by nouiz** [comment]
A quick hack would be to disable it when calling theano.grad().
