### ISSUE TITLE
Code gets stuck when defining model

### ISSUE THREAD

**Issue by NoahSlv** [pymc-devs/pymc#1162]
Hello,

Trying out very simple model with many rows of data, and 10 factors.

``` python
# Build model
with pm.Model() as speed_model:
    intercept = pm.Normal('intercept', mu=0, sd=100.0)
    beta = pm.Normal('beta', mu=0, sd=100.0, shape=x.shape[1])
    eps = pm.Normal('eps', mu=0, sd=100.0)
    eta = intercept + np.dot(beta, x.T)
    model_like = pm.Normal('model_like', mu=eta, sd=eps, observed=y)
```

This is on a fairly fast i7 CPU with 16GB of RAM.

There are 300,000 rows of data in x.

So far, the code has been running for 3 hours, with the CPU pegged at 100% for the python3 process.

I'm confused as to what pymc is doing, since I haven't asked for samples yet, but simply defined the model.

Thoughts?  Thanks!

**Comment by hvasbath** [comment]
It is constructing the theano graph and compiling the function. Per default, theano does this by running the function once with test values- ergo it does the calculation once. 
Also you are using a numpy operator on symbolic variables! This will do only operations on placeholders and strings which is very slow and leeds you nowhere. You have to use the theano.tensor.dot

Best regards!

**Comment by smartmediacorp** [comment]
Hvasbath,

Thanks for the explanation.  However, I think that you may have misunderstood my model specification.  There are only 10 coefficients, with 300,000 rows.  

x.shape = (300000,10)

So, there should only be samples, from the posterior, for 10 coefficients (not 300,000)

I've run the same model in Stan, and it both builds the model and samples very quickly, while providing samples for the 10 coefficients.

Slightly unrelated, but where is this behavior documented?  I couldn't find any deep explanations of the internals in the normal documentation.

Thanks!

**Comment by hvasbath** [comment]
Yes, just saw it and was just editing the comment ;) . See above you have to use the theano.tensor.dot instead of numpy.dot

**Comment by smartmediacorp** [comment]
Ahhh, will try that ASAP.

Is that documented anywhere?  (I prefer to read docs than bother the group.)

**Comment by hvasbath** [comment]
You have to think of all the operations in your with model block as tensor operations and use specific theano functions in this context.

Theano has a very good documentation here:
http://deeplearning.net/software/theano/index.html

If you have never been using theano before I recommend you do the tutorial first, before anything else, as it is very much different compared to standard numpy calculations.

**Comment by NoahSlv** [comment]
Will do.

Just tried with your suggestion.  Now model building returns instantly, which is great.

However, when I attempt to sample, Theano gives me errors:

``` python

ERROR (theano.gof.opt): SeqOptimizer apply <theano.compile.mode.AddDestroyHandler object at 0x7efd216cc8d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 232, in validate_
    ret = fgraph.execute_callbacks('validate')
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 673, in execute_callbacks
    fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 141, in validate
    "Variable.", r)
theano.gof.fg.InconsistencyError: ('Trying to destroy a protectedVariable.', OutputGuard.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/mode.py", line 135, in apply
    reason='output_guard')
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 300, in replace_validate
    self.replace_all_validate(fgraph, [(r, new_r)], reason=reason)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 334, in replace_all_validate
    fgraph.validate()
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 236, in validate_
    uf_info = inspect.getframeinfo(uf)
  File "/usr/lib/python3.4/inspect.py", line 1296, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib/python3.4/inspect.py", line 661, in findsource
    module = getmodule(object, file)
  File "/usr/lib/python3.4/inspect.py", line 629, in getmodule
    os.path.realpath(f)] = module.__name__
AttributeError: 'module' object has no attribute '__name__'
```

**Comment by hvasbath** [comment]
Could you please post the code how you started the sampling? It looks like there is some error there.

**Comment by NoahSlv** [comment]
Code below:

``` python
with speed_model:
    start = pm.find_MAP()
    step = pm.NUTS(scaling=start)
    trace = pm.sample(100, step, start=start, progressbar=True)
```

I also tried a simpler version, that also fails

``` python
with speed_model:
    trace = pm.sample(100,  progressbar=True)
```

**Comment by hvasbath** [comment]
Seems there is no problem there. Did you make your data ergo x shared?

**Comment by NoahSlv** [comment]
ergo x shared?

Not sure what you mean.

Data is normalized (mean 0 and sd of 1)

Do I need to do something more with it?

**Comment by hvasbath** [comment]
Thats why I suggested you do the tutorial first ...
http://deeplearning.net/software/theano/tutorial/examples.html#using-shared-variables
X = theano.shared(x.T)
before the model block
Then you can replace your x.T with X in your eta line.

**Comment by hvasbath** [comment]
But of course it can be still something else ;) . Theano graphs are very tedious to debug.

**Comment by NoahSlv** [comment]
OK, that returned with no error 👍 

Just a suggestion, but might be worth pointing to more Theano stuff in the documentation for pymc3.  I had no idea, before your suggestions, that I needed to import that library, share the data, etc.

Thanks!!!

**Comment by hvasbath** [comment]
Your welcome I am glad it works now ;). I know how it feels if you get these strange theano errors and they actually seldomly point out the real problem. 
Maybe the developers read it ;) . But I think it is mentioned somewhere, but meanwhile the documentation is quite long and you might miss it. I also havent looked into it quite a while and they worked on that a lot in the last monthes apparently.

**Comment by twiecki** [comment]
Thanks for helping resolve this so quickly @hvasbath. @NoahSlv can we close this?

**Comment by NoahSlv** [comment]
Something strange is happening.  (Probably my fault somewhere.)

Re-ran, what I thought was the same code, with the same data, and am now getting a _new_ Theano error.

Below is what I ran, and the error following:

``` python


x2 = theano.shared(x.T)
y2 = theano.shared(y)

with pm.Model() as speed_model:
    intercept = pm.Normal('intercept', mu=0, sd=100.0)
    beta = pm.Normal('beta', mu=0, sd=100.0, shape=10)
    eps = pm.Normal('eps', mu=0, sd=100.0)
    eta = intercept + theano.tensor.dot(beta, x2)
    speed_like = pm.Normal('speed_like', mu=eta, sd=eps, observed=y2)
```

And the exciting new error is:

``` python
AsTensorError                             Traceback (most recent call last)
<ipython-input-96-af4794151add> in <module>()
      3         beta = pm.Normal('beta', mu=0, sd=100.0, shape=10)
      4         eps = pm.Normal('eps', mu=0, sd=100.0)
----> 5         eta = intercept + theano.tensor.dot(beta, x2)
      6         speed_like = pm.Normal('speed_like', mu=eta, sd=eps, observed=y2)
      7 

/usr/local/lib/python3.4/dist-packages/theano/tensor/basic.py in dot(a, b)
   5609 
   5610     """
-> 5611     a, b = as_tensor_variable(a), as_tensor_variable(b)
   5612 
   5613     if a.ndim == 0 or b.ndim == 0:

/usr/local/lib/python3.4/dist-packages/theano/tensor/basic.py in as_tensor_variable(x, name, ndim)
    165         if not isinstance(x.type, TensorType):
    166             raise AsTensorError(
--> 167                 "Variable type field must be a TensorType.", x, x.type)
    168 
    169         if ndim is None:

AsTensorError: ('Variable type field must be a TensorType.', <Generic>, <theano.gof.type.Generic object at 0x7f33650ca048>)
```

What's strange is that this is the same code and data that worked a few hours ago.  Am I missing something glaringly obvious?

Thanks!

**Comment by twiecki** [comment]
You can try cleaning out your theano cache directory.

**Comment by NoahSlv** [comment]
No luck, same error

**Comment by NoahSlv** [comment]
Some more clues, if it helps:

x is originally a pandas DataFrame.

then x2 - theano.shared(x.T)

The error complains that x2 is "not a TensorType".  Checking the type in ipython shows that it is "Generic".  Could that be part of the problem?

``` python
x2.type
<theano.gof.type.Generic at 0x7faff8f08048>
```

**Comment by NoahSlv** [comment]
Looks like that was the problem.  Converting the DataFrame to a matrix, before making it shared in Theano seems to have solved the issue:

``` python
x2 = theano.shared(x.T.as_matrix())
```

Now the model builds with no errors.

**Comment by twiecki** [comment]
Great!
