### ISSUE TITLE
DOCS: Provide guidance on the use of shared variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1164]
As requested in #1162 we should offer more guidance in the documentation regarding when to present data as Theano `shared` objects. 

Some packages have actual `Data` objects (e.g. edward) that ensure data are in the correct form for the model to use. We could do something similar in PyMC3 if we want to avoid using Theano objects directly. This point may be confusing for many users.

**Comment by springcoil** [comment]
This is a good idea - I've been struggling to get my head around it lately.

**Comment by aloctavodia** [comment]
Closing as the docs now include at least two examples [1](http://docs.pymc.io/advanced_theano.html) and [2](http://docs.pymc.io/notebooks/posterior_predictive.html) on how and when to use shared variables.
