### ISSUE TITLE
Change naming convention of transformed variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1168]
To revisit the issue of hiding variables generated by a particular sampling algorithm from the user, a better approach might be to modify the naming convention of the transformed variables, following the convention adopted by Scikit-learn -- appending an underscore to the name of the variable. This way, such variables would be automatically recognizable as quantities generated by the model or sampler, and would make it easy to filter them out without introspection, etc. 

So, I'm proposing we change `foo_log` to `foo_log_`, for example.

**Comment by twiecki** [comment]
+1

**Comment by springcoil** [comment]
+1

**Comment by taku-y** [comment]
+1

**Comment by fonnesbeck** [comment]
OK, I'm on it.
