### ISSUE TITLE
Markov and Bayesian networks

### ISSUE THREAD

**Issue by rw** [pymc-devs/pymc#1169]
Does PyMC3 support directed and undirected edges within graphical models?

(I've searched for the answer to this in the docs and source.)

**Comment by fonnesbeck** [comment]
There is no built-in support for graphical models in PyMC, though such an extension has been discussed.

**Comment by rw** [comment]
@fonnesbeck Ah, okay! Thanks. How would you contrast PyMC with graphical models?

(I'm learning about statistical modeling by studying graphical models, and my goals are mainly to implement CRFs, HMMs, etc.)

**Comment by fonnesbeck** [comment]
Well, PyMC constructs one particular type of graphical model -- a directed acyclic graph -- but does not generalize beyond this. You can certainly implement a hidden Markov model with a DAG and fit it with MCMC. Eventually, we'd like to have formal classes that represent graphical models, along the lines of [pgmpy](https://github.com/pgmpy/pgmpy)
