### ISSUE TITLE
Bayesian Logistic Regression

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1171]
Hey @twiecki do you have any idea why this isn't in the docs - I thought it was a good example.

**Comment by twiecki** [comment]
Added back via https://github.com/pymc-devs/pymc3/commit/ce550a66e9b566d7c7067339bf0bda099d0af306

**Comment by JWarmenhoven** [comment]
@twiecki 
The notebook does not appear in the 'Examples' section of the docs? Or am I missing something?

![image](https://cloud.githubusercontent.com/assets/7450204/24139882/2d0abeea-0e1e-11e7-9662-213b463970d9.png)
