### ISSUE TITLE
Parallelisation strategy, avoid recompiling?

### ISSUE THREAD

**Issue by davidia** [pymc-devs/pymc#1174]
Imagine if you wanted to fit the following model:

```
import numpy as np
import pymc3 as pm
def fit(data):
    model = pm.Model()

    with model:        
        pm.Normal('x',mu=pm.Normal('mu',0,1), sd=pm.Exponential('sd',1),
                               observed=data)

    with model:
        mu, sds, elbo = pm.variational.advi(n=10000)
        step = pm.NUTS(scaling=model.dict_to_array(sds), is_cov=True)
        trace = pm.sample(500, step, start=mu)       

x = np.random.normal(size=100) * 1.2 + 0.5
fit(x)
```

How can I efficiently fit this model to multiple series in parallel? e.g.

```
with Pool() as pool:
  pool.map(fit,xs)
```

It seems the model needs to recompile on every thread and perfromance sucks (due to theano locking? I get lots of warnings) is there a way to avoid this?

Thanks in advance

**Comment by fonnesbeck** [comment]
I've used IPython's `backgroundjobs` to do something like this with PyMC 2. [Here is an example](https://gist.github.com/fonnesbeck/1859dc732797d9e6922cd50e79529068) on around line 40. Have not tried it with PyMC3.

**Comment by davidia** [comment]
The issues is conntention in the theano compliation step. I've tried running a script from the command line and get the same results. Should a theano shared variable mean I don't have to recompile the model?

**Comment by twiecki** [comment]
I have written a caching mechanism for pymc3 models: https://gist.github.com/twiecki/972496588bf69fbfbd98ed6b01a3c8a8

However, this would not help you necessarily. If you add pickle and unpickle functionality, however, you could just have the workers check if the cached pickle file exists and load it in that case.

**Comment by davidia** [comment]
Would you expect to be able to (un)pickle the cached model? It looks like __new__ in Distribution tries to get the context during unpickling but that fails in the new process

**Comment by twiecki** [comment]
Yeah, that was my hope. Bummer it doesn't work, I'm sure there's a way to make it work but can't look into it right now.

**Comment by davidia** [comment]
Here is what I am using for now:

```
import numpy as np
import pymc3 as pm
from theano import shared
from multiprocessing import Pool


model = pm.Model()

x = shared(np.zeros(100))

with model:
    pm.Normal('x',mu=pm.Normal('mu',0,1), sd=pm.Exponential('sd',1),
                           observed=x)
def fit(data):
    x.set_value(data)
    mu, sds, elbo = pm.variational.advi(n=10000)
    step = pm.NUTS(scaling=model.dict_to_array(sds), is_cov=True)
    trace = pm.sample(500, step, start=mu)
    return trace

xs = [ np.random.normal(size=100) + i for i in np.arange(-10,10) ]

with model:
        with Pool() as pool:
                res = pool.map(fit,xs)

print([ np.mean(trace['mu']) for trace in res])
```

Notes:
- The sub processes can share the model and the shared theano variable seems to work
- There is some recompilation / lock contention in this example but it doesn't seem to take too long so the processes can progress - I think in a long running sampling this wouldn't make much difference to the overall execution time
- Running this example a 2nd time results in less recompilation for reasons I don't understand

**Comment by twiecki** [comment]
Did you get it to work?

**Comment by davidia** [comment]
The above did the job.  Thanks for the help!
