### ISSUE TITLE
Issues/confusion using multidimensional arrays in a model

### ISSUE THREAD

**Issue by jamestwebber** [pymc-devs/pymc#1176]
Apologies if this isn't the right place for such a question but it seems like this is the _de facto_ support forum for pymc3.

I'm trying to implement a mixed-effects model in pymc3, and I thought the easiest way to do that would be to mimic the structure of the data in the arrays that I'm using. With N features, 2 conditions, and 2 replicates, I build a model of observed_data as a N \* 2 \* 2 array, where each axis reflects a different source of variation.

The replicate noise can vary by feature but shouldn't vary by condition or replicate, so I define the hyperprior as a length-N array and then broadcast it to the correct shape with `[:, None, None]`

All of this works in pymc but it seems like the transition to Theano doesn't allow advanced indexing so easily. I get complaints about being unable to broadcast to the correct shape.

Maybe I'm just not going about this correctly--any advice there is welcome. But it seems like this is a current limitation in how Theano can interpret models. If there's some relatively straightforward way to fix this I can try to contribute, I'm very interested in getting pymc3 working for my application.

**Comment by fonnesbeck** [comment]
@jamestwebber the issues tracker is not where support is provided. [Gitter](https://gitter.im/pymc-devs/pymc) and [StackOverflow](http://stackoverflow.com/questions/tagged/pymc) are the best places for general advice. Indexing is more troublesome with Theano, but you should be able to do this. I would provide an example with some detail on SO, and send the link to us on Gitter.
