### ISSUE TITLE
trace_cov() triggers NumPy deprecation warning

### ISSUE THREAD

**Issue by JWarmenhoven** [pymc-devs/pymc#1184]
Calculating the covariance matrix on trace vectors triggers a NumPy deprecation warning. (NumPy 1.11.0)

```
VisibleDeprecationWarning: using a non-integer number instead of an integer 
will result in an error in the future 
return x.reshape((x.shape[0], np.prod(x.shape[1:])))
```

This is because the reshaping operation in `pymc3\tuning\scaling.py` uses a non-integer value in the new-shape argument. 

Considering a vector of trace variable x, `x.shape[1:]` returns an empty array. And `np.prod([])` returns 1.0.

Question:
Under what circumstances do you end up with a trace variable that is not a vector?

``` python
def trace_cov(trace, vars=None):
    """
    Calculate the flattened covariance matrix using a sample trace
    Useful if you want to base your covariance matrix for further sampling on some initial samples.
    Parameters
    ----------
    trace : Trace
    vars : list
        variables for which to calculate covariance matrix
    Returns
    -------
    r : array (n,n)
        covariance matrix
    """

    if vars is None:
        vars = trace.samples.keys

    def flat_t(var):
        x = trace[str(var)]
        return x.reshape((x.shape[0], np.prod(x.shape[1:])))

    return np.cov(np.concatenate(list(map(flat_t, vars)), 1).T)
```

**Comment by jamestwebber** [comment]
`np.prod(x.shape[1:], dtype=int)` would silence the warning/prevent issues with deprecation, is that a satisfactory fix?

**Comment by twiecki** [comment]
Is this still required after #1198?

**Comment by JWarmenhoven** [comment]
No, this issue can be closed. Thanks.
