### ISSUE TITLE
Inaccurate samples with DiscreteUniform distribution

### ISSUE THREAD

**Issue by spencerkent** [pymc-devs/pymc#1194]
Hi, I'm running Pymc 3.0 installed via pip and while testing a model that contained several DiscreteUniform distributions, noticed that the MH sampling I was running was not producing reasonable samples for several of the variables defined by these DiscreteUniform distributions. 

Here is some example code to reproduce what I'm seeing:

Trying to sample from {0, 1} uniformly works okay:

```
import pymc3 as pm
from matplotlib import pyplot as plt

with pm.Model() as my_model:
    discrete_rv = pm.DiscreteUniform('discrete_rv', lower=0, upper=1)
    step = pm.Metropolis()
    trace = pm.sample(10000, step=step)
    pm.traceplot(trace)
    plt.show()
```

![0_to_1](https://cloud.githubusercontent.com/assets/6759112/16167202/16c888e8-34a7-11e6-8f98-0245b69c09c3.png)

But trying to sample from {1, 2} doesn't:

```
import pymc3 as pm
from matplotlib import pyplot as plt

with pm.Model() as my_model:
    discrete_rv = pm.DiscreteUniform('discrete_rv', lower=1, upper=2)
    step = pm.Metropolis()
    trace = pm.sample(10000, step=step)
    pm.traceplot(trace)
    plt.show()

```

![1_to_2](https://cloud.githubusercontent.com/assets/6759112/16167211/36b48206-34a7-11e6-96ca-d04c515e63af.png)

Sampling from {1, 2, 3} does work:

```
import pymc3 as pm
from matplotlib import pyplot as plt

with pm.Model() as my_model:
    discrete_rv = pm.DiscreteUniform('discrete_rv', lower=1, upper=3)
    step = pm.Metropolis()
    trace = pm.sample(10000, step=step)
    pm.traceplot(trace)
    plt.show()
```

![1_to_3](https://cloud.githubusercontent.com/assets/6759112/16167226/600c7118-34a7-11e6-8b75-c0699920a382.png)

But sampling from {2, 3, 4, 5} again doesn't:

```
import pymc3 as pm
from matplotlib import pyplot as plt

with pm.Model() as my_model:
    discrete_rv = pm.DiscreteUniform('discrete_rv', lower=2, upper=5)
    step = pm.Metropolis()
    trace = pm.sample(10000, step=step)
    pm.traceplot(trace)
    plt.show()
```

![2_to_5](https://cloud.githubusercontent.com/assets/6759112/16167255/a656adc8-34a7-11e6-8229-4b124372c40b.png)

This doesn't seem to be the expected behavior from DiscreteUniform...am I using it incorrectly?

**Comment by fonnesbeck** [comment]
Can you try giving the random variable an explicit starting value? 

```
trace = pm.sample(10000, step=step, start={'discrete_rv': 1})
```

BTW, when there are only a handful of discrete values on the support of a variable, its better to use the `ElemwiseCatagorical` instead of `Metropolis`.

**Comment by fonnesbeck** [comment]
Please test #1195

**Comment by spencerkent** [comment]
Cool, seems to have fixed it - thanks! I didn't run more than a few test cases though. Out of curiosity, why is ElemwiseCategorical better in this case?

**Comment by fonnesbeck** [comment]
It is more efficient in the way it proposed values when the number of discrete values is small.
