### ISSUE TITLE
HalfNormal not correct

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1196]
Neither the `pm.HalfNormal` distribution nor taking the absolute value of a zero-mean `pm.Normal` distribution seem to produce accurate half-normal distributions:

``` python
import pymc3 as pm
import matplotlib.pyplot as plt


with pm.Model() as model:

    x = pm.HalfNormal(name='x', sd=1)
    y = pm.Normal(name='y', sd=1)
    z = pm.Deterministic('z', abs(y))
    trace = pm.sample(500000)
    pm.traceplot(trace)
    plt.savefig('test.png')
```

![test](https://cloud.githubusercontent.com/assets/9464950/16172175/c8abd16a-3550-11e6-8bd1-fbf7ff95a751.png)

**Comment by ririw** [comment]
I just noticed that the buggyness seems to change depending on the sampler.
With Metropolis:

```
with pymc3.Model() as model:
    x = pymc3.HalfNormal(name='x', sd=1)
    y = pymc3.Normal(name='y', sd=1)
    z = pymc3.Deterministic('z', abs(y))
    step = pymc3.Metropolis()
    trace = pymc3.sample(500000, step=step)
    pymc3.traceplot(trace)
```

![metrop](https://cloud.githubusercontent.com/assets/741243/16181408/9742883c-36de-11e6-96c7-aebda66d0918.png)

Anyway, just an observation, hopefully it helps. Perhaps the sampler is having trouble taking steps that take it close to zero, given that it'd be so easy to overshoot and end up overshooting and get rejected (in the half-normal case) or overshoot and end up further from zero (in the abs case)

**Comment by twiecki** [comment]
Looks a bit different when I run it with NUTS:
![image](https://cloud.githubusercontent.com/assets/674200/16172814/865ff094-3590-11e6-9b36-3b3498342d09.png)

I think you're not up-to-date. I also ran it without transformation and Metropolis and it looks the same. Probably just very difficult to sample extremely close to 0.

**Comment by aloctavodia** [comment]
I get essentially the same results with NUTS or metropolis (similar to those of @ririw  and @twiecki ). I think part of the problem you are seeing is only due to visualization and not sampling. The Kernel Density Estimation implemented in SciPy does not take into account boundary effects. As a result underestimates values close to the boundaries (like 0). I have made a PR upstream to fix this problem. Once it get merged I will make the necessary changes into PyMC3.

**Comment by twiecki** [comment]
@aloctavodia good catch:
![image](https://cloud.githubusercontent.com/assets/674200/16194176/492e9a2c-36c1-11e6-8f7f-c485fed38b6f.png)

**Comment by sammosummo** [comment]
Just updated by cloning the repo and installing from source, and the issue is resolved. Thanks!
