### ISSUE TITLE
Add method for GroupBy using Theano scan

### ISSUE THREAD

**Issue by NoahSlv** [pymc-devs/pymc#1200]
I'm working on a custom likelihood function for PyMC3 (Attempting to fit a conditional logistic regression.)

The likelihood requires summing values **_by group**_.  In R we have the "ave()" function, in Python Pandas we have "groupby()".  How would I do something similar in PyMC3?

I want to create a cox proportional hazards model (same as conditional logistic regression.)  The log likelihood requires the sum of values by group:

![\sum{_{g=1}^G](http://latex.codecogs.com/gif.latex?%5Csum%7B_%7Bg%3D1%7D%5EG%7D%20%5Csum%7B_%7Bi%5Cing%7D%7D%20%5Clog%20%5Ceta_i)

In Pandas, this would be:

```
temp = df.groupby('groupid')['eta'].aggregate(np.sum)
denominator = np.log(temp).sum()
```

In the data, we have a column with group ID, and the values to be summed

```
group    eta
1        2.1
1        1.8
1        0.9
2        1.2
2        0.75
2        1.42
```

The output for the group sums would then be:

```
group    sum
1        4.8
2        3.37
```

 Then, the sum of the log of the sums:

```
log(4.8) + log(3.37) = 2.7835
```

 This is quick and easy to do in Pandas.  How can I do something similar in PyMC3?  Sure, could write a nested loop, but that seems slow and I try to avoid manually coded loops when possible as they are slow.

Thanks!

**Comment by fonnesbeck** [comment]
Unfortunately there is no `groupby` function or method in Theano, which is what would be needed here. At the moment, you would have to write a `scan` function to do something similar. It would be interesting to see if we could write a function for PyMC3 that would do something like this that hides the Theano implementation.

**Comment by NoahSlv** [comment]
If you knew the starting position, and length of each group's sub-vector, then you could loop over the scan function N times (once for each group).  However, I'm very new to Theano, and haven't mastered the scan function yet.

**Comment by fonnesbeck** [comment]
Changed this to an enhancement request

**Comment by fonnesbeck** [comment]
Changed title to reflect this enhancement request

**Comment by springcoil** [comment]
Does anyone have any examples of functions in PyMC3 that hide the theano implementation?

**Comment by NoahSlv** [comment]
I'm able to get correct results _not_ using the scan function.  Is there any downside to doing it as follows:

In this example, I just create a vector of random values and define 6 groups:

``` python
import theano.tensor as T
y = np.exp(np.random.normal(size=40))
obs_per_group = [5,6,10,8,5,6]

x = T.dmatrix('x')
accumulator = 0
pos = 0
f = theano.function([x], T.log(T.sum(x)))
for g in obs_per_group:
    accumulator = accumulator + f([y[pos:(pos+g)]])
    pos = pos + g
```

This produces the correct result. _However_, I do not know if it is taking advantage of all the internal speedups in Theano.  Can anybody comment on that?

**Comment by hvasbath** [comment]
There wont be much speedup in theano as there is only the log(sum) operation. Your for loop wont be inside theano. For building a pymc3 model then it would be a different story as you cannot have a compiled function within another compiled function- what is what will be done with your final model likelihood function-its compiled into a theano function similar like you did.

I have programmed similar things in theano already using scan. What I found is, that using 'for' inside the theano function is faster than scan if the loop is not very large. If it is, you get too many apply nodes, ergo a long graph what makes it slow first during compilation then also in the computation itself- although there then the theano internal optimisation effect can be quite significant.

However, I suggest using scan if your loop is long ergo if you have many groups - like 50.

At @springcoil what do you mean hiding the theano implementation? Putting scan inside a function and execute only this function in the pymc3 model? I could post such an example.

**Comment by springcoil** [comment]
Hi Hannes,
Yeah - if you have an example of hiding the theano implementation that'd be
really useful.

We could then expose that as a function in pymc3 itself.

On Sun, Jul 3, 2016 at 3:04 PM, Hannes Vasyura-Bathke <
notifications@github.com> wrote:

> There wont be much speedup in theano as there is only the log(sum)
> operation. Your for loop wont be inside theano. For building a pymc3 model
> then it would be a different story as you cannot have a compiled function
> within another compiled function- what is what will be done with your final
> model likelihood function-its compiled into a theano function similar like
> you did.
> 
> I have programmed similar things in theano already using scan. What I
> found is, that using 'for' inside the theano function is faster than scan
> if the loop is not very large. If it is, you get too many apply nodes, ergo
> a long graph what makes it slow first during compilation then also in the
> computation itself- although there then the theano internal optimisation
> effect can be quite significant.
> 
> However, I suggest using scan if your loop is long ergo if you have many
> groups - like 50.
> 
> At @springcoil https://github.com/springcoil what do you mean hiding
> the theano implementation? Putting scan inside a function and execute only
> this function in the pymc3 model? I could post such an example.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/1200#issuecomment-230155026,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA8DiAMXPYCQ1p6yURMuhL_FhvA6mhPkks5qR8FmgaJpZM4I5XXd
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by hvasbath** [comment]
I am not sure if I understand you correctly?
But this is the code I wrote with 2 nested scans, where a lot of features of scan are demonstrated.
The stuff before the 2 scans could be ignored while trying to follow- if one just want to get the syntax right.

``` javascript
def get_rupture_times_symbolic_GPU(slownesses, patch_size, nuc_x, nuc_y):
    '''
    Does the same calculation as get_rupture_times_theano
    just with symbolic variable input and output for pymc3 optimization.
    '''
    [step_dip_max, step_str_max] = slownesses.shape
    StartTimes = tt.ones((step_dip_max, step_str_max), config.floatX) * 1e6
    StartTimes = tt.set_subtensor(StartTimes[nuc_y, nuc_x], 0)

    # Stopping check var
    epsilon = theano.shared(num.array(0.1, config.floatX))
    err_val = theano.shared(num.array(1e6, config.floatX))

    # Iterator matrixes
    dip1 = tt.repeat(tt.arange(step_dip_max, dtype='int16'), step_str_max)
    str1 = tt.tile(tt.arange(step_str_max, dtype='int16'), step_dip_max)

    dip2 = tt.repeat(tt.arange(step_dip_max, dtype='int16'), step_str_max)
    str2 = tt.tile(tt.arange(step_str_max - 1, -1, -1, dtype='int16'), step_dip_max)

    dip3 = tt.repeat(tt.arange(step_dip_max - 1, -1, -1, dtype='int16'), step_str_max)
    str3 = tt.tile(tt.arange(step_str_max - 1, -1, -1, dtype='int16'), step_dip_max)

    dip4 = tt.repeat(tt.arange(step_dip_max - 1, -1, -1, dtype='int16'), step_str_max)
    str4 = tt.tile(tt.arange(step_str_max, dtype='int16'), step_dip_max)

    DIP = tt.concatenate([dip1, dip2, dip3, dip4])
    STR = tt.concatenate([str1, str2, str3, str4])

    ### Upwind scheme ###
    def upwind(dip_ind, str_ind, StartTimes, slownesses, patch_size):
        [n_patch_dip, n_patch_str] = slownesses.shape
        n_patch_dip = tt.cast(n_patch_dip, dtype='int16')
        n_patch_str = tt.cast(n_patch_str, dtype='int16')
        zero = tt.constant(0, dtype='int16')
        s1 = str_ind - 1
        d1 = dip_ind - 1
        s2 = str_ind + 1
        d2 = dip_ind + 1

        # if a < b return b
        checked_s1 = ifelse(tt.lt(s1, zero), zero, s1)
        checked_d1 = ifelse(tt.lt(d1, zero), zero, d1)

        # if a =< b return a-1
        checked_s2 = ifelse(tt.le(n_patch_str, s2), n_patch_str - 1, s2)
        checked_d2 = ifelse(tt.le(n_patch_dip, d2), n_patch_dip - 1, d2)

        ST_xmin = tt.min((StartTimes[checked_d1, str_ind], StartTimes[checked_d2, str_ind]))
        ST_ymin = tt.min((StartTimes[dip_ind, checked_s1], StartTimes[dip_ind, checked_s2]))
        ### Eikonal equation solver ###
        # The unique solution to the equation
        # [(x-a)^+]^2 + [(x-b)^+]^2 = f^2 * h^2
        # where a = u_xmin, b = u_ymin, is
        #
        #         | min(a,b) + f*h,                           |a-b|>= f*h
        # xnew =  |
        #         |0.5 * [ a+b+sqrt( 2*f^2*h^2 - (a-b)^2 ) ], |a-b| < f*h
        start_new = ifelse(
            tt.le(slownesses[dip_ind, str_ind] * patch_size, tt.abs_(ST_xmin - ST_ymin)),
            tt.min((ST_xmin, ST_ymin)) + slownesses[dip_ind, str_ind] * patch_size,
            (ST_xmin + ST_ymin + tt.sqrt(
                 2 * tt.pow(slownesses[dip_ind, str_ind], 2) * \
                 tt.pow(patch_size, 2) - tt.pow((ST_xmin - ST_ymin), 2))) / 2)

        # if a < b return a
        output = ifelse(tt.lt(start_new, StartTimes[dip_ind, str_ind]),
                         start_new, StartTimes[dip_ind, str_ind])
        return tt.set_subtensor(StartTimes[dip_ind:dip_ind + 1, str_ind:str_ind + 1],
                                output)

    def loop_upwind(StartTimes, PreviousTimes, err_val, iteration, epsilon):
        [results, updates] = theano.scan(fn=upwind,
                                         sequences=[DIP, STR],
                                         outputs_info=[StartTimes],
                                         non_sequences=[slownesses, patch_size])

        StartTimes = results[-1]
        err_val = tt.sum(tt.sum(tt.pow((StartTimes - PreviousTimes), 2)))
        PreviousTimes = StartTimes.copy()
        return (StartTimes, PreviousTimes, err_val, iteration + 1),
                            theano.scan_module.until(err_val < epsilon)

    # while loop until err < epsilon
    iteration = theano.shared(num.array(0,dtype='int16'))
    PreviousTimes = StartTimes.copy()
    ([result, PreviousTimes, errs, Iteration], updates) = theano.scan(
            fn=loop_upwind,
            outputs_info=[StartTimes, PreviousTimes, err_val, iteration],
            non_sequences=[epsilon],
            n_steps=500)  # arbitrary set usually stops after few iterations

    return result[-1]
```

This is then called like this within the "with Model as model:" block:

```
#convert velocities to rupture onset
tzero = fast_sweep.get_rupture_times_symbolic_GPU(
                tt.reshape((1 / tt.abs_(m_velocity)), 
                        (tt.cast(num_patch_w, dtype='int64'),
                         tt.cast(num_patch_l, dtype='int64'))),
                patch_size,
                tt.round(nuc_x).astype('int16'),
                tt.round(nuc_y).astype('int16')).flatten()
```

**Comment by hvasbath** [comment]
@springcoil I guess I get what you mean now:
Some kind of wrapping around scan for arbitrary input? Is that feasible?
I doubt that it would be less complex, because you need to support all the scan features!?
Maybe one could make a "reduced_scan" where only the most commonly used formulations are included. Do you have noticed specific features of scan that are often requested by users but scan is too complex? For example the while loop is quite tricky.
I could try to make such a wrapping to produce a reduced scan, but I need to know what is needed most often.

**Comment by twiecki** [comment]
Closing this, I don't think we can significantly simplify this. Feel free to still propose this further.

**Comment by springcoil** [comment]
Agreed
