### ISSUE TITLE
Upper and lower bounds of distributions

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1201]
Hi. Just wondering if there is a way to put upper and lower bounds on continuos distributions in PyMC3. In Stan we do this by real<lower = -1.0, upper=1.0> mu; I understand I can do something similar by multiplying with a bounded uniform distribution but this operation seems inefficient.

Thanks in advance

**Comment by twiecki** [comment]
There is `pm.Bound()`, e.g. `boundedNormal = pm.Bound(pm.Normal, upper=1.0)`

**Comment by twiecki** [comment]
We're still not adding a transformed variable in that case however, so NUTS and ADVI might not work well.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/issues/1170
