### ISSUE TITLE
TypeError with scipy.stats.norm.cdf

### ISSUE THREAD

**Issue by achetverikov** [pymc-devs/pymc#1209]
I'm trying to convert this simple JAGS model to pymc3 and I'm getting type error with scipy.stats.norm.cdf. 

JAGS model (from https://github.com/drbenvincent/bayesian2afc/blob/master/jagsmodels/model1JAGS.txt):

```
model{
    v ~ dunif(0,1000)
    for (c in 1:length(si)) {   
        pc[c] <- phi( (si[c])/( sqrt(2*v) ) )
        k[c] ~ dbin(pc[c],T)
        predk[c] ~ dbin(pc[c],T)
    }
}
```

My attempt at pymc3:

```
from pymc3 import *
from scipy.stats import norm # for cumulative normal distribution

si = [0.01, 0.02, 0.05, 0.1, 0.22, 0.46, 1.0, 2.15, 4.64, 10.0]
k = [50.0, 51.0, 57.0, 55.0, 63.0, 62.0, 82.0, 94.0, 99.0, 100.0]

with Model() as model: # model specifications in PyMC3 are wrapped in a with-statement
    sigma = Uniform('sigma', lower=0, upper=1000, testval = 50)
    pc = norm.cdf(si/sqrt(sigma*sigma))
    predk = Binomial('predk',T, pc, observed = k)

    start = find_MAP() 
    step = NUTS(scaling=start) 
    trace = sample(20000, step, start=start, progressbar=True) 
```

I'm getting the following error:

```
   "Variables do not support boolean operations. This "
TypeError: Variables do not support boolean operations. This can happen if you do a logical operation (<, <=, >, <=, ==, !=) between a numpy.ndarray and a Theano tensorvariable. Due to NumPy implementation before NumPy 1.8, we cannot make the Python syntax work when the ndarray is on the left, and this results in this error. To work around that, either call theano.tensor.{lt,le,eq,ne,gt,ge}(ndarray, tensor), or use the Python syntax with the Theano tensor on the left. Or update to NumPy 1.8 or above.
```

I assume that the problem is in using norm.cdf but I don't know how to fix it. Any help is appreciated. 

PS. I've also tried using Theano functions from basic_scipy but this code 

```
from theano.scalar.basic_scipy import erfc
from theano.scalar import sqrt
from theano import shared
si = shared([0.01, 0.02, 0.05, 0.1, 0.22, 0.46, 1.0, 2.15, 4.64, 10.0])
...
    pc = -erfc(sqrt(2.0)*(si/sqrt(sigma**2))/2.0)/2.0 + 1.0 
```

gives an error: `TypeError: unsupported operand type(s) for /: 'SharedVariable' and 'ScalarVariable'`

**Comment by achetverikov** [comment]
OK, I think I managed to get it working with cdf created with erfc:

```
from pymc3 import *
from theano.tensor import erfc, sqrt
import numpy as np

si = np.ndarray([0.01, 0.02, 0.05, 0.1, 0.22, 0.46, 1.0, 2.15, 4.64, 10.0])
k = [50.0, 51.0, 57.0, 55.0, 63.0, 62.0, 82.0, 94.0, 99.0, 100.0]

T = 100.0

with Model() as model: # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    sigma = HalfCauchy('sigma', beta=3, testval=1.)

    pc = -erfc(sqrt(2.0)*(si/sqrt(sigma**2))/2.0)/2.0 + 1.0 #norm.cdf(si/sqrt(sigma*sigma))
    predk = Binomial('predk',T, pc, observed = k)

    # Inference!
    start = find_MAP() 
    step = NUTS(scaling=start) 
    trace = sample(2000, step, start=start, progressbar=True) 
```

But I still receive a lot of errors like:

```
ERROR (theano.gof.opt): Optimization failure due to: local_grad_log_erfc_neg
ERROR (theano.gof.opt): node: Elemwise{true_div,no_inplace}(Elemwise{mul,no_inplace}.0, Elemwise{erfc,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\SciSoft\Anaconda2\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "C:\SciSoft\Anaconda2\lib\site-packages\theano\tensor\opt.py", line 6098, in local_grad_log_erfc_neg
    if not exp.owner.inputs[0].owner:
AttributeError: 'NoneType' object has no attribute 'owner'
```

So apparently something is wrong, but why?

**Comment by twiecki** [comment]
I think you probably want inverse logit: http://pymc-devs.github.io/pymc3/notebooks/posterior_predictive.html#Prediction

**Comment by achetverikov** [comment]
@twiecki thanks for the answer, but I'm not sure why would I need it? This is a signal-detection model where the probability of correct answer (pc) is defined as: `Pc = phi(si/(sigma**2))` where `phi` is a standard cumulative normal and `si` and `sigma` are signal intensity and noise variance, respectively. Theano does not have its own function for normal CDF, but I think I got it correctly. It can be further broken down as:

```
x = si/sqrt(sigma**2)
pc = 0.5*(1+erf(x/sqrt(2)))
```

However, even with this code I still have the same errors as in the previous comment.

**Comment by msspektor** [comment]
Ran into the same issue today, any solution yet?

**Comment by twiecki** [comment]
Hm, it seems that erf and erfc do not have gradients in theano?

**Comment by fonnesbeck** [comment]
What about using `theano.tensor.erfc`. Surely that will have a gradient?

**Comment by msspektor** [comment]
Tried it. Neither `theano.tensor.erfc` nor `theano.tensor.erf` have gradients.

**Comment by fonnesbeck** [comment]
Theano has `Erf` and `Erfc` classes in [`theano/scalar/basic_scipy.py`](https://github.com/Theano/Theano/blob/master/theano/scalar/basic_scipy.py). Perhaps we could wrap this as a PyMC3 distribution?

**Comment by twiecki** [comment]
I think that's what they used, but those don't seem to have gradients.

**Comment by fonnesbeck** [comment]
They have `grad` methods that look like gradients.

**Comment by twiecki** [comment]
Hm, then maybe that was just a red herring.

**Comment by msspektor** [comment]
So is this an issue of PyMC3 or Theano?

**Comment by jfmoulin** [comment]
I run in a problem identical to the one initially reported here, i.e TypeError on comparison between Theano object and numpy array. My code was written with the Theano object on the left of the operator and using Numpy 1.13.1

Investigating a bit I tested
    
    import pymc3
    with pymc3.Model() as model:
        a = pymc3.Uniform("a", 1,2)
        print 1 < a

which outputs, without complaining:

    Elemwise{gt,no_inplace}.0

Now running 

    with pymc3.Model() as model:
        a = pymc3.Uniform("a", 1,2)
        if 1 < a:
            print "bingo"

produces the TypeError

    /usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in __nonzero__(self)
         73     def __nonzero__(self):
         74         # Python 2.x
    ---> 75         return self.__bool__()
         76 
         77     def __bool__(self):
    /usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in __bool__(self)
         89         else:
         90             raise TypeError(
    ---> 91                 "Variables do not support boolean operations."
         92             )
         93 

    TypeError: Variables do not support boolean operations.

**So my question is, how should I do this type of testing?** I would like to leave my code generic since in most cases it does not run on Theano objects (of course I could have a version of this function to be used in pymc3/Theano context). For what is worth the offending code is

    ......./refsans_tools/abeles/abeles.py in guess_optimal_x(self, thickness, roughness)
       1303                                                safety=self.safety
       1304                                               )
    -> 1305         if this_xmin < self._xmin:
       1306             self._xmin = this_xmin
       1307             self._xmin = - self.shift_orig
    /usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in nonzero(self)
	     73     def nonzero(self):
	     74         # Python 2.x
    ---> 75         return self.bool()
	    76 
	    77     def bool(self):
    /usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in bool(self)
	     89         else:
	     90             raise TypeError(
    ---> 91                 "Variables do not support boolean operations."
	     92             )
	     93 
    TypeError: Variables do not support boolean operations.

**Comment by junpenglao** [comment]
@jfmoulin we are having a similar discussion on discourse you might find it useful:

https://discourse.pymc.io/t/comparing-theano-values/171
