### ISSUE TITLE
variational advi in parallel

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1210]
Hi,

Just wondering if variational.advi runs in parallel, or if there is parameter to set that can make it run as such? Personally I am more interested if advi_minibatch could be run in parallel?

Thanks,
Sachin

**Comment by twiecki** [comment]
There is no such code currently and I'm not sure if it can be done just because the algorithm is sequential. @taku-y might have ideas.

**Comment by taku-y** [comment]
@sachinruk  Unfortunately, ADVI does not support parallel inference. In computation of noisy gradient, Theano's scan function is used. If scan can be executed in parallel, more accurate gradient is obtained in shorter time and result in faster convergence. But, to my knowledge, there is no way to do this.

**Comment by twiecki** [comment]
Thanks @taku-y. Closing.

**Comment by sachinruk** [comment]
Just one last comment/ question regarding this. Since Variational algorithms optimises $\int q(z) \Sum_n \log p(x_n|z) + log p(z)  dz$ shouldn't the ADVI algorithm be of parallelisable nature along the sum of log p(x_n|z)?

I also saw this https://groups.google.com/forum/#!topic/pymc/PkbMK07rQQM (which talks about integrating pymc3 with spark). Has there been any progress in this regard?
