### ISSUE TITLE
Link to the S&P 500 dataset is broken in the getting started documentation

### ISSUE THREAD

**Issue by svenski** [pymc-devs/pymc#1213]
I'm going through the getting started page and the following data set link is not working: https://raw.githubusercontent.com/pymc-devs/pymc3/master/docs/notebooks/data/SP500.csv in this document: http://pymc-devs.github.io/pymc3/notebooks/getting_started.html .

**Comment by dadaromeo** [comment]
This link works https://raw.githubusercontent.com/pymc-devs/pymc3/master/pymc3/examples/data/SP500.csv but the date field is removed.
So you would have to do this:

``` python
returns = pd.read_csv('https://raw.githubusercontent.com/pymc-devs/pymc3/master/pymc3/examples/data/SP500.csv')
```

**Comment by fonnesbeck** [comment]
We probably should not be linking like this, but rather, referring to the data using the file system, as we do with all of our other examples.
