### ISSUE TITLE
Issue scaling with NUTS

### ISSUE THREAD

**Issue by dedwards00** [pymc-devs/pymc#1225]
Hi. Firstly since I haven't commented here before I'd like to say thanks to everyone who has contributed to this package as it makes the initial development of such models incredibly straightforward.

I've been trying to speed up the sampling by following the advice in #544 and have run into an error. Here is a simple example that reproduces the issue:

```
import numpy as np
import pymc3 as pm
# Data
size = 50
a = np.random.normal()
s = np.random.gamma(0.2, 0.5) + 0.1
b = np.random.normal(0., 1.)
X = np.random.randn(size)
Y = a + b * X + np.random.randn(size) * s
basic_model = pm.Model()
with basic_model:
    alpha = pm.Normal('alpha', mu=0., sd=10.)
    beta = pm.Normal('beta', mu=0., sd=10.)
    sigma = pm.HalfNormal('sigma', sd=10.)
    mu = alpha + beta * X
    Y_obs = pm.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)
    C = pm.approx_hessian(basic_model.test_point)
    C += 1.*np.identity(C.shape[0])  # Required to ensure matrix is positive definite
    step = pm.NUTS(scaling=C)
    trace = pm.sample(1000, step=step, start=basic_model.test_point)
```

and here is the traceback:

```
Traceback (most recent call last):
  File "pymc3_nuts_error.py", line 25, in <module>
    step = pm.NUTS(scaling=C)
  File "/Users/dedwards/anaconda/lib/python2.7/site-packages/pymc3/step_methods/nuts.py", line 97, in __init__
    self.leapfrog1_dE = leapfrog1_dE(model.logpt, vars, shared, self.potential, profile=profile)
  File "/Users/dedwards/anaconda/lib/python2.7/site-packages/pymc3/step_methods/nuts.py", line 209, in leapfrog1_dE
    q1, p1 = leapfrog(H, q, p, 1, e)
  File "/Users/dedwards/anaconda/lib/python2.7/site-packages/pymc3/step_methods/hmc.py", line 118, in leapfrog
    q = q + e * pot.velocity(p)
  File "/Users/dedwards/anaconda/lib/python2.7/site-packages/pymc3/step_methods/quadpotential.py", line 97, in velocity
    return cho_solve((self.L, True), x)
  File "/Users/dedwards/anaconda/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 171, in cho_solve
    if c.shape[1] != b1.shape[0]:
IndexError: tuple index out of range
```

Currently I have installed theano==0.8.2, numpy==1.11.1, scipy==0.17.1 - though I have tried older versions of numpy/scipy and the development version of theano with the same results. It is not clear to me whether the error originates in my code, pymc3 or one of the other packages but any help would be greatly appreciated.

**Comment by fonnesbeck** [comment]
The scaling for NUTS appears to be the wrong dimension. It's easier if you pass a dictionary, with a component for each named variable. Try `find_MAP` to get the dimensions that it expects.

**Comment by dadaromeo** [comment]
You can also try `advi` and pass the `means` as scaling and start parameter to `NUTS` and `sample` respectively.

**Comment by dedwards00** [comment]
Thanks for the replies, both of those suggestions run without issue and speed up the sampling on this toy problem (from ~1.5s to ~0.7s on my machine). I am also able to provide a covariance matrix for scaling (is_cov=True) and get the error above for any precision matrix (is_cov=False) - but now I have some options to try on my main application.

**Comment by twiecki** [comment]
Glad it's working.
