### ISSUE TITLE
Scaling of NUTS with dimensionality

### ISSUE THREAD

**Issue by LindleyLentati** [pymc-devs/pymc#1226]
Hey there,

I've recently been trying to use the NUTS sampler in PyMC3 for a research problem i'm working on.  Previously i've been using a HMC sampler in C to which I pass the hessian calculated at some position in parameter space to set the step-size and directionality for the parameters.

I've heard great things about PyMC3 though, and so wanted to try it out, as it uses NUTS, and seems to be able to mix sampling types dependent on parameters (e.g. Adaptive MCMC for some parameters, NUTS for the rest).

I have a very simple piece of code (https://github.com/LindleyLentati/PyProfileDomain/blob/master/ProfileDomainPyMC3.py) which I wanted to try using PyMC3 for.  Up until line 135 it is just loading data and initializing arrays for the subsequent analysis.

Currently I have defined an integer 'useToAs'  which denotes the number of data sets to analyse.  In this example each data set added to the analysis results in 3 more parameters (an amplitude, an offset, and a noise level).  For useToAs = 1, the sampler takes 15 seconds to run,  if it is set to two i takes 45 seconds to run, set to ten it takes 650 seconds to run, and I didn't actually successfully get it to run with it set to 100.

I thought maybe this might be because it had a bad scaling as a start point, so i added functions to calculate the maximum likelihood start point and the hessian analytically.  If I then use:

from pymc3 import NUTS, sample

with basic_model:

```
# Use starting ML point
start = MLpoint

hess = hessian(useToAs)

#Set scaling using hessian
step = NUTS(scaling=basic_model.dict_to_array(hess), is_cov=True)
# draw 2000 posterior samples
trace = sample(2000, start=start)
```

for useToAs = 10 (so only 30 dimensions..) it runs slightly faster, in 620 seconds instead of 650, however I still can't get it to run with useToAs = 100 (so 300 dims).

For comparison, the C-based HMC sampler will run the useToAs = 100 example in a few minutes.

Do you know where I am going wrong?

Many Thanks
Lindley

**Comment by LindleyLentati** [comment]
To provide an update:

If i use the Hamiltonian monte carlo sampler rather than NUTS by using:

from pymc3 import HamiltonianMC, sample

with basic_model:

```
# Use starting ML point
start = MLpoint

hess = hessian(useToAs)

step1 = HamiltonianMC(vars = [noise, offset, amplitude], scaling=basic_model.dict_to_array(hess), is_cov=True)

# draw 2000 posterior samples
trace = sample(2000, start=start, step=step1)
```

Then i get the following run times for 2k samples:

6dims = 6 seconds
30dims = 18 seconds
300 dims = 210 seconds

Using NUTS with everything else identical i get:

6dims = 45 seconds
30dims = 650 seconds
300 dims = Completed 15% in 2500 seconds

Does that sound reasonable?  I guess I had assumed NUTS would be better than standard HMC, but maybe not?

Cheers
Lindley

**Comment by twiecki** [comment]
That's interesting. I suppose it's not surprising that NUTS is slower just because it does more computation per sample (building up the binary tree etc). In principle, you should get better convergence and require less tuning than HMC. If HMC is tuned correctly though and produces unautocorrelated samples, it should be faster. You could look at the effective sample size.

Moreover, I noticed NUTS is extremely dependent on finding a good scaling matrix. I used ADVI before for that which works best. find_MAP() doesn't work at all. If you're passing in a hessian, shouldn't you set `is_cov=False`?

**Comment by springcoil** [comment]
This here might be worth writing up in the documentation - as 'lessons learned' and 'caveats'. However not overly necessary.

**Comment by twiecki** [comment]
Had the same thought, there are many small tricks that make model building much easier.
