### ISSUE TITLE
Any plans to introduce truncated distributions?

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1227]
I found the truncated normal distribution in pymc2 quite useful. Are there any plans to introduce this to pymc3?

**Comment by fonnesbeck** [comment]
Any distribution can be truncated using `Bound`: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/garch_example.py

**Comment by sammosummo** [comment]
Great! Sorry for the dumb question.
