### ISSUE TITLE
Segmentation Fault when trying to multiply a variable with np.float128 constant

### ISSUE THREAD

**Issue by LindleyLentati** [pymc-devs/pymc#1228]
Hi there,

I'm trying to understand a seg fault i'm getting when typing to define a model in pymc3.

The following code works fine and i've used it with various samplers in the package:

from pymc3 import Model, Normal, HalfNormal

```
basic_model = Model()

with basic_model:

# Priors for unknown model parameters
amplitude = Normal('amplitude', mu=0, sd=10000, shape = useToAs)
offset = Normal('offset', mu=0, sd=10000, shape = useToAs)
noise = HalfNormal('noise', sd=10000, shape = useToAs)


ReferencePeriod = ProfileInfo[0][5]
FoldingPeriodDays = ReferencePeriod/SECDAY

phase   = Savex[0]*ReferencePeriod/SECDAY
```

This continues onwards, but the rest isn't really relevant to the problem.  Here Savex is a np.float128  array with some saved parameters in it.

If i change this to:

from pymc3 import Model, Normal, HalfNormal, Uniform

```
basic_model = Model()

with basic_model:

# Priors for unknown model parameters
amplitude = Normal('amplitude', mu=0, sd=10000, shape = useToAs)
offset = Normal('offset', mu=0, sd=10000, shape = useToAs)
noise = HalfNormal('noise', sd=10000, shape = useToAs)
   phase = Uniform('phase', lower = -1, upper = 1) 

ReferencePeriod = ProfileInfo[0][5]
FoldingPeriodDays = ReferencePeriod/SECDAY

phase   = phase*ReferencePeriod/SECDAY
```

I get a seg fault when trying to copy the model into python.  the problem seems to be when i multiply by ReferencePeriod/SECDAY.  Does this not support float128 or could the problem be elsewhere?

Many thanks
Lindley

**Comment by hvasbath** [comment]
First of all, you need to use proper indentation or nothing will work. 
Then as you are using theano tensors, everything that is external data and not a tensor should be converted to shared variables . so here at least your SECDAY and your ReferencePeriod.
It is always better to paste the full error. Especially theano related errors can become quite misleading...
You wrote pasting... you cannot simply copy paste into a shell if you do not use magic functions like %cpaste from ipython.
Hope one of these help ;) .

**Comment by LindleyLentati** [comment]
Hi there, so indeed, the actual code was indented correctly, and i am using %paste.

Unfortunately I didn't get any kind of error, it just segfaults:

```
## -- End pasted text --
Applied log-transform to noise and added transformed noise_log to model.
Applied interval-transform to phase and added transformed phase_interval to model.
Segmentation fault (core dumped)
```

and thats all.  Is there a way to make these things more verbose?  I will have a look at this shared variables thing though now.

Thanks
Lindley

**Comment by hvasbath** [comment]
Ok. How do you know then that it is related to the multiplication of the float128 array?
It would be important to see the whole model setup that you have. Anything that comes after that can cause the error as well. Please be aware that you have to use the theano expressions for any operation in the with Model block instead of numpy.

**Comment by LindleyLentati** [comment]
Honestly i'm not really sure, i don't yet really understand how all the theano stuff works.  It just seemed that changing that one line made it seg fault (or not).  However, even if i cast that thing to a float64, i then get a different error which i assume pops up later:

AsTensorError: ('Cannot convert [ 0.036003078  0.030852386  0.029959499  0.02968633  0.030148086\n  0.031257754  0.032860668  0.034716898  0.036554402  0.038112568\n  0.03917918  0.0376043  0.03961544  0.039394745  0.038529786  0.03713191\n  0.035387941  0.033533897  0.031827219  0.030513711  0.02979067\n  0.029772721  0.038863766  0.030468486  0.031705581  0.033414234\n  0.035294056  0.037072372  0.038499994  0.039384754  0.039613297\n  0.039160974  0.03809163  0.039532023  0.036548241  0.034822099\n  0.032985935  0.031375263  0.030225361  0.029711469  0.029917215\n  0.030816574  0.032275723  0.034075833  0.039525815  0.035951266\n  0.037632733  0.038842482  0.039534228  0.039552885  0.038901361\n  0.037668731  0.036019341  0.034174821  0.032389226  0.038851119\n  0.030916823  0.029975487  0.029707242  0.030145199  0.031235088\n  0.032825523  0.034678636  0.036522439  0.038095366  0.039182981\n  0.03759976  0.039643577  0.03942188  0.038603897  0.037222898\n  0.035488136  0.03363452  0.031919382  0.030589533  0.029844281\n  0.029801792  0.035938412  0.030474605  0.03176428  0.033393542\n  0.035272892  0.037060151  0.038504492  0.03941163  0.039664932\n  0.039236628  0.038187494  0.03409045  0.036658125  0.034853279\n  0.033099107  0.031477119  0.030308284  0.029770646  0.029951588\n  0.030828841  0.032272125  0.034065098  0.03231067] to TensorType', <type 'numpy.ndarray'>)

So I guess there are indeed some theano related issues...   If it helps i've pushed the problem file to git (https://github.com/LindleyLentati/PyProfileDomain/blob/master/ProfileDomainPyMC3.py).  It uses some external libraries, so unfortunately you can't just run it, however the pymc3 stuff starts on line 145.  As i'm sure will be clear, I didn't really understand from the examples online how much theano stuff needs to be used.. I'm not even really sure how to plot the contents of a vector during runtime (e.g. the model vector s in the example).

Essentially its fitting a bunch of gaussians to some light curves, with a global model that links the positions (in time) of those gaussians across multiple observations.  The precision required for the time of these things is nanoseconds over decades, hence using float128.

Anyhow, I will see about trying to convert things to the right format.

Cheers
Lindley

**Comment by hvasbath** [comment]
float128 array should be no problem. But your data actually is a list? What do the line breaks (\n) do in there? This is clearly a format thing of your inputs. 
You have to convert it to a numpy array. You cannot use operations on a list.
This data is ReferencePeriod? 
So I guess someone else wrote that code and you are using it now? So probably it was working at some point. And we can trust the model setup.

**Comment by LindleyLentati** [comment]
So, basically I (until a few days ago) coded in C and Fortran, and had a bunch of code to use a C-based HMC sampler.  Unfortunately it just didn't provide enough tools to do some of the things that I wanted to do, so i'm now trying to recode everything, starting with a super simple case in Python (..and i guess theano) to try and get it to work with PyMC3.

I'm assuming that error came from the following line:

```
MBats = np.float64(psr.satSec() + BatCorrs - phase - residuals/SECDAY)
```

If i just do type(psr.satSec() + BatCorrs - residuals/SECDAY) i get numpy.ndarray, and if i do:

type((psr.satSec() + BatCorrs - residuals/SECDAY)[0])

i get numpy.float128.  So, at least as far as i'm aware that thing should have been a numpy array, so I also have no idea where the \n's come from!  I have a very similar version of this code which works with a generic MCMC in python, and that didn't complain, so i really don't know.

If I change this to:
        MBats = np.float64(psr.satSec() + BatCorrs - residuals/SECDAY)  
    ModelBats = theano.shared(MBats)
    ModelBats -= phase  

Then it at least compiles, but currently gives me nonsense from the sampling.  Do you know if its actually possible to plot the contents of one of these things while PyMC3 is doing the sampling to try and track what its doing?

Cheers
Lindley

**Comment by hvasbath** [comment]
Pymc has a lot of plotting functions, please look into the docs and with the matplotlib library you can plot anything you want, if a plot function doesnt exist yet ;) .

**Comment by LindleyLentati** [comment]
Ok, So it seems as though theano doesn't support float128, however I think the example works for the most part now with float64.  I had a look at the plotting functions in the API:

pymc3.plots.traceplot
pymc3.plots.forestplot
pymc3.plots.autocorrplot
pymc3.plots.plot_posterior

Which all seem to be about plotting the results.  I wanted to plot my model vector and my data vector during sampling to make sure that everything was doing what it should be.  I can take the chains and plot those using a non-theano function, but i really wanted to compare that with whatever theano was doing.  Do you know if that is possible?

Cheers

**Comment by hvasbath** [comment]
You can sample for only few samples and then use the traceplot on the result. During runtime I am not aware of any possibility without major programming effort.

**Comment by twiecki** [comment]
This seems resolved so I'm closing. Feel free to keep discussing.
