### ISSUE TITLE
Self-written function of sampling from Weibull distribution 

### ISSUE THREAD

**Issue by timoryxl** [pymc-devs/pymc#1234]
Recently I have been trying to sample from weibull but it keeps giving me wrong samples, which is more like a log-parameters version. I looked into the _random function in continuous.py, it seems to be wrong compared to wiki. Could anyone take a check on that?

**Comment by twiecki** [comment]
@timoryxl it's possible we have a bug there. Which wiki do you mean?

**Comment by timoryxl** [comment]
@twiecki The Weibull distribution page. I am also double checking on it, seems fine with all those distributions using scipt.stats.rvs but not weibull. Thanks for checking in!

**Comment by twiecki** [comment]
@timoryxl I wonder why we're not using http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.weibull.html directly. Do those produce different values?

**Comment by timoryxl** [comment]
@twiecki Yeah I think that should work too, an easier way is just to change a to 1/a. Just a reminder.

**Comment by twiecki** [comment]
@timoryxl Want to do a PR that fixes this?

**Comment by twiecki** [comment]
It seems like this was changed to `1/a` some time. Closing.
