### ISSUE TITLE
Transformed variable failure during Metropolis sampling

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1235]
I've come across a curious error related to using transformed variables  in Metropolis sampling. Specifically, a `MissingInputError` is raised when `sample` is called. Replacing the variable in question with a constant results in the next transformed variable failing for the same reason. 

[Here is an example of a model that fails because of this](https://gist.github.com/fonnesbeck/7d3ed7234e27159359424202175a95ff)

BTW, setting `exception_verbisity` to "high" does nothing to improve the verbosity of the output.

**Comment by twiecki** [comment]
Did this stop working after https://github.com/pymc-devs/pymc3/pull/1215 was merged?

**Comment by fonnesbeck** [comment]
I don't know, as this is a new model, but it seems unlikely since transformations have always been renamed to something. I will try it though.

**Comment by fonnesbeck** [comment]
Verified that this is not the issue. After reverting to before the pull request was merged:

```
MissingInputError: An input of the graph, used to compute Elemwise{exp,no_inplace}(cold_mort_interval), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.
```

NUTS also fails, but because it receives NaNs in the gradient. So, I believe something deeper is the issue.

**Comment by fonnesbeck** [comment]
Running the same model with ADVI yields:

```
NullTypeGradError: tensor.grad encountered a NaN. This variable is Null because the grad method 
for input 3 (Elemwise{true_div,no_inplace}.0) of the RandomFunction{multinomial_helper} op is 
mathematically undefined. No gradient defined through raw random numbers op
```

**Comment by twiecki** [comment]
It's quite a complex model it seems, perhaps try to work backwards?
