### ISSUE TITLE
Passing start points with uniform interval transforms (KeyError: 'phase_interval_')

### ISSUE THREAD

**Issue by LindleyLentati** [pymc-devs/pymc#1237]
Hi,

I'm not sure how to handle passing start points/covariance matrices when including parameters that have a uniform prior, and thus get an interval transform.

I would have thought that the transforming part was hidden behind the scenes, and so I just pass start points to the 'real space' parameters (i.e. phase in this case), and pymc3 works out the start point for the phase_interval_ parameter on its own.

However, If i try and call:

map_estimate = find_MAP(model=basic_model, start=startpoint)

where startpoint is a dictionary with the entry: 'phase': 0.00288206

I get this KeyError: 'phase_interval_' error.

If i try actually sampling, and then look at the chains for the phase_interval parameter, i find it is around 0.5 in whatever units that is, so if i then call find_MAP again but now with the start point

'phase_interval_': array(0.5322536239617567)

then it works a treat.   

In all the examples i've seen though, i've not seen anyone manually transforming their start points to the _interval_ parameter, so i feel like this is not the usual behaviour?  Or, are there functions to do the transformation that I can use?

Many Thanks
Lindley

**Comment by twiecki** [comment]
Unfortunately that part is not well hidden when supplying your own starting values. After transforming, the model needs trasnformed values. To get around that, instead you can specificy a `testval` when creating the RV.

**Comment by darribas** [comment]
I've had the same experience but with an `InverseGamma`. @twiecki do you have a link to an example about how to set up starting values in these cases? Thank you very much in advance.

**Comment by fonnesbeck** [comment]
It would be nice to be able to pass initial values on the original scale of the parameter, then have `sample` look up the appropriate transform and apply it to the start value automatically.
