### ISSUE TITLE
Dynamic models and Markov Decision Processes (MDPs)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc#1258]
Hello! Apologies if this is something that has been discussed before. 

I'm interested in using PyMC to model **dynamic** inference problems and ultimately solve [**Markov Decision Processes (MDPs)**](https://en.wikipedia.org/wiki/Markov_decision_process) and multi-armed bandit problems. 

For now, I'm starting simple. No real inference, just sampling, from a binary Markov chain. The full example is shown below.

I'm writing this partly because I was surprised by how slow it was to draw a few samples (e.g. 5) from my chain. Maybe this is completely expected given the size of the model, but I 'm concerned that I am not doing it right. 

Ultimately I am hoping to build on top of what you see below to model [a more complex Markov decision process](http://stats.stackexchange.com/questions/222961/regret-minimization-with-hidden-markov-processes).

So I guess my questions here are:
1.  Does the model below strike you as the right way to build (and sample from) a simple chain? Any more efficient ways of building it?
2. Does PyMC3 support built-ins for specifying Markov chains and/or Markov models?
3. Are we aware of any examples in the community of folks using PyMC3 to build [MDPs](https://en.wikipedia.org/wiki/Markov_decision_process) or solve multi-armed bandit problems?

Thanks! I love the energy around PyMC and hope to contribute to it at some point soon :)

``` python
import numpy as np
import pymc3 as pm

# How many nodes
length  = 1000

# P of the initial state
p_init  = 0.8

# Symmetric transition matrix 
p_trans = [0.001, 0.5]

# How many samples
N_runs  = 5

basic_model = pm.Model()

with basic_model:
  timesteps=np.empty(length,dtype=object)

  # Binary chain. Two possible states
  timesteps[0]=pm.Bernoulli('T_0',p_init)

  for i in range(1,length):

      # Prob of being in state 1 at time step "i" given time step "i-1"
      p_i = p_trans[1]*timesteps[i-1] + p_trans[0]*(1-timesteps[i-1])
      timesteps[i] = pm.Bernoulli('T_{}'.format(i),p_i)

with basic_model:
  trace = pm.sample(N_runs)
```

**Comment by twiecki** [comment]
We don't have specific support for that, it should be possible though. For your example, I think you need to vectorize your code, see e.g. https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/timeseries.py#L28. I'm closing this as it's more of a question but feel free to keep asking questions.
