### ISSUE TITLE
can't reproduce Bayesian Survival Analysis example

### ISSUE THREAD

**Issue by DanielWeitzenfeld** [pymc-devs/pymc#1261]
I'm trying to reproduce the [Bayesian Survival Analysis](http://pymc-devs.github.io/pymc3/notebooks/survival_analysis.html#) example, but I'm getting nonsense results.

@AustinRochford included a value for `random_seed`, so I don't think it's just randomness.

Here is the code extracted from the example:

``` python
import numpy as np
import pymc3 as pm
from pymc3.distributions.timeseries import GaussianRandomWalk
import seaborn as sns
from statsmodels import datasets
from theano import tensor as T
from matplotlib import pyplot as plt

df = datasets.get_rdataset('mastectomy', 'HSAUR', cache=True).data
df.event = df.event.astype(np.int64)
df.metastized = (df.metastized == 'yes').astype(np.int64)
n_patients = df.shape[0]
patients = np.arange(n_patients)

interval_length = 3
interval_bounds = np.arange(0, df.time.max() + interval_length + 1, interval_length)
n_intervals = interval_bounds.size - 1
intervals = np.arange(n_intervals)


last_period = np.floor((df.time - 0.01) / interval_length).astype(int)

death = np.zeros((n_patients, n_intervals))
death[patients, last_period] = df.event

exposure = np.greater_equal.outer(df.time, interval_bounds[:-1]) * interval_length
exposure[patients, last_period] = df.time - interval_bounds[last_period]

SEED = 5078864 # from random.org

with pm.Model() as model:

    lambda0 = pm.Gamma('lambda0', 0.01, 0.01, shape=n_intervals)

    beta = pm.Normal('beta', 0, sd=1000)

    lambda_ = pm.Deterministic('lambda_', T.outer(T.exp(beta * df.metastized), lambda0))
    mu = pm.Deterministic('mu', exposure * lambda_)

    obs = pm.Poisson('obs', mu, observed=death)

n_samples = 1000

with model:
    trace_ = pm.sample(n_samples,random_seed=SEED)

trace = trace_[100:]

np.exp(trace['beta'].mean())
```

Output:

```
Applied log-transform to lambda0 and added transformed lambda0_log to model.
Assigned NUTS to lambda0_log
Assigned NUTS to beta
 [-----------------100%-----------------] 1000 of 1000 complete in 3.6 sec
Out[8]:
1.0
```

In the example, the last line (`np.exp(trace['beta'].mean())`) returns `2.1839971003209597`.  I'm getting `1.0` because the trace for beta is always `1.0`.

I'm using `pymc3` version `3.0`

**Comment by fonnesbeck** [comment]
I am able to replicate the result on my machine. It looks like your sampling doesn't even get off the ground. Can you try discarding the `.theano` subdirectory in your home folder, and try again? Sometimes Theano gets confused.

**Comment by DanielWeitzenfeld** [comment]
I tried deleting `.theano`, and various other means of blowing in the cartridge (restarting my computer, reinstalling `pmyc3`) and am still getting `1.0`.  What's more, a colleague sitting next to me is getting the same result.
We're working from a virtualenv - here are the versions of possibly relevant packages:

```
Theano==0.8.2
pandas==0.18.1
numpy==1.11.1
pymc3==3.0
```

**Comment by twiecki** [comment]
is this pymc3 master?

**Comment by DanielWeitzenfeld** [comment]
I reinstalled pymc3 one more time and it's working now.  Sorry for the false alarm.  I'll check if this resolves https://github.com/pymc-devs/pymc3/issues/1254 as well

**Comment by dfs0** [comment]
Not sure if this should be a new issue or a reopening of this one, but I'm running into a similar problem now. I'm running the exact same code as posted above and I'm getting:

```
print np.exp(trace['beta'].mean())
2.0101215317097998e-07
```

I've tried removing ~/.theano, reinstalling pymc3 several times and restarting my computer. Also worth noting I'm running:

Theano==0.8.2
pandas==0.18.1
numpy==1.11.1
pymc3==3.0

Attached a screenshot of my notebook. Any ideas?

<img width="926" alt="screen shot 2017-02-04 at 9 06 12 pm" src="https://cloud.githubusercontent.com/assets/12762691/22623131/ca648280-eb1d-11e6-8961-c5fce0d29883.png">

**Comment by AustinRochford** [comment]
@dfs0 I have just successfully run the survival notebook on the master branch of pymc3 and the master branch of theano.

I would try upgrading theano to the development branch and rerunning to see if that helps

```
pip install git+https://github.com/Theano/Theano.git
```
