### ISSUE TITLE
Inconsistent calling sequence in traceplot

### ISSUE THREAD

**Issue by tdshepard** [pymc-devs/pymc#1262]
(Sorry, I can't cut and paste. Have to type this all manually.)
I'm trying to use a backend with multiple chains. Failure occurs when I attempt to specify combined = True to traceplot. 

Error is
TypeError: get_values() got an unexpected keyword argument 'combine'

The problem exists for all backends.

In plots.py, line 56:
... trace . get_values ( v, combine = combined, squeeze = False ) :

In the source for any of the backends:

```
def get_values ( self, varname, burn = 0, thin = 1 ) :
```

**Comment by fonnesbeck** [comment]
I can't replicate this behavior here. Can you post a small example that shows this?

Also, the line that you cite above is not line 56 in the current source. How did you install pymc3? You might try installing the current master:

```
pip install -U git+https://github.com/pymc-devs/pymc3.git
```

**Comment by tdshepard** [comment]
I will have to set something up on an Internet-connected computer to do that. Not sure how soon I can do that. Meanwhile, if you just look at the source code I referenced, the problem should be fairly obvious. Let me know if that works; otherwise I'll set up an example when I can. 

The following should be sufficient to reproduce the problem:
1. Run any problem to generate a trace with multiple chains. 
2. Run traceplot on the resulting trace with combined = True. 

Dr. Thomas D. Shepard
thomas@tdshepard.com

**Comment by fonnesbeck** [comment]
That does not replicate the issue on my system, so definitely try installing from the master branch.

**Comment by tdshepard** [comment]
Oops. I meant line 75 in plots.py, not line 56. I was looking at an older version of plots.py. However, the current version in github still has the same problem.

traceplot wants to do 

trace . get_values (v, combine = combined, squeeze = False ), but the backends all have 

get_values methods which expect to be called as

trace . get_values ( varname, burn, thin )

**Comment by tdshepard** [comment]
I will re-download and install from the master branch and see what happens then.

**Comment by twiecki** [comment]
Is this fixed?

**Comment by tdshepard** [comment]
Thank's for asking. I'm trying to see if I just had an out-of-date installation. It takes time for me to get the latest download installed on my computing facility due to administrative hurdles. Stay tuned. I'm working on it. As soon as I get the files in place, I'll just look at the source code for those calling sequences and see if it is fixed.

**Comment by tdshepard** [comment]
I looked at the source code but haven't yet built and installed it. It looks like it should work as is, but even if it does, I see potential for future bugs.

I recommend you search for the string get_values in all the source code and see if you think each instance of its use is ok.

Also, sometimes you use the keyword "combine" and other times you use "combined," in a way that looks consistent as is, but that seems like something that could create a mess in the future.

Having said all that, I'll build and test this and if my previous problem works, I'll come back and close this without further ceremony.

**Comment by tdshepard** [comment]
Yes. With the re-installed pymc3 my traceplots now work with combined = True.
