### ISSUE TITLE
Calculation run TWICE during sampling

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1264]
I am not sure if I get everything correctly here. But if I see correctly once the forward model 
is calculated and then AGAIN during recording?
Ok this is only a problem if you want to record the likelihoods- otherwise its only the variables that are written out- right. So I should think about another backend...

**Comment by hvasbath** [comment]
I get it, thats why the unobservedRVs are recorded. So my bad! I have to make my likelihoods observed and write them out somehow in a different way. Thats also why my trace objects take so long to initialise! AHH! Good to know ;) .
Does anyone have suggestion on how to do that efficiently?

Again in numbers thats nice to see.

record time 6.97798299789 forward time 0.00213479995728
 [---------------  40%                  ] 2 of 5 complete in 7.0 sec1469578886.03
1469578892.96
record time 6.93070292473 forward time 0.000688076019287
 [-----------------60%--                ] 3 of 5 complete in 13.9 sec1469578906.74
1469578913.69
record time 6.95339608192 forward time 13.7774348259
 [-----------------80%----------        ] 4 of 5 complete in 34.6 sec1469578927.51

In the first two steps the forward time is so fast because the point was out of bounds and rejected and the forward model not calculated. Then still it records the previous point again and runs again the calculation.
In the last line the new point passed the bound check and was calculated and then again calculated during recording ;) . So thats why ATMCMC performs so slowly now.

But for that the backends we have dont work, we need a special atmcmc backend then. Which is I guess not ideal and not wanted. Easiest probably would be to remove it from the distribution ...

**Comment by hvasbath** [comment]
Just finished a backend for ATMCMC, which is unfortunately incompatible with pymc3s main sample function
So far I had to change even the BaseTrace which is then in conflict with _choose_backends, because it is not recognised anymore. Then the standard way it works now is that in a generator the point dictionary is circling from output to input in _iter_sample. BUT as we have to return the likelihoods from the step in order to write them out we have to return the point dict and the likelihoods. Also I edited the Text backend to get rid of this theano function there, as we dont need to recalculate anything we already have calculated. Which reduces also the initialisation time from 11s for my problem now to 0.01 seconds, as no function needs to be compiled again.
I would be happy to get any input from the devs @twiecki , @fonnesbeck , @springcoil , @kyleam  of how I could make it compatible with the main sampling structure.

**Comment by hvasbath** [comment]
The updated ATMCMC and its backend can be found here, if you find the time to have a look.
https://github.com/hvasbath/beat/tree/master/src
For the next three weeks I will be anyways doing fieldwork so there is no rushing needed, anyways I would appreciate any feedback.

**Comment by twiecki** [comment]
I'll take a look later but Generally I'm not opposed to changing the
backend code.

**Comment by twiecki** [comment]
@hvasbath What do you think in regards to ATMCMC backend in pymc3?

**Comment by hvasbath** [comment]
I wrote one as mentioned above, however it had to leak into a lot of other things like the Array_step_shared, _sample, _iter_sample function etc. So it is not at all compatible with the existing classes. So basically I modified the necessary ones and they are all in the beat/backend.py if you want to take a look. Maybe one can clean things up and make the integration with the rest of the pymc3 library more tight and efficient.
Of course one could simply take the whole thing and transfer it into pymc3.
But it doesnt feel good-if you know what I mean? As I especially like about it, that you use the same sample() function with taking the different step methods. But simply this is not possible with ATMCMC as it is now.
The good thing is, it is now twice as fast, the parallelisation works always and you can restart it at intermediate result steps. But at the moment I had no time to check if it still can be used for more generell cases. I am happy to get any comments on the code, but I guess no one will have time to look through it, as it is quite a lot ...

**Comment by hvasbath** [comment]
Any comments @twiecki ?

**Comment by twiecki** [comment]
So it seems ATMCMC requires a more ground-breaking change to PyMC3 core to work efficiently. Your beat project has all that implemented and works on arbitrary PyMC3 models, correct?

In that case, perhaps ATMCMC best lives outside of PyMC3 as a separate project for people who need that style of sampler. Of course, ideally it would be part of PyMC3 but maybe until we get there that's the quickest path. Not sure, what do you think? We could still have a tutorial of how to install beat and use it on PyMC3 models in the PyMC3 docs.

**Comment by twiecki** [comment]
@hvasbath what are your thoughts?

**Comment by hvasbath** [comment]
I am sorry for being quiet on this for such a long time. We could definitely do what you suggested @twiecki , I would need to rearrange some things in order to make it independent of another package, but this would be no problem. I will keep you updated!

**Comment by twiecki** [comment]
@hvasbath I understand `beat` is a package for other things too. I would suggest to spin out an `ATMCMC` package, it'll definitely be useful to folks!

**Comment by hvasbath** [comment]
Thanks for the hint I will do that!

**Comment by twiecki** [comment]
Closed by #1264.

**Comment by twiecki** [comment]
@hvasbath Just curious if you had a chance to spawn this out? Would be very cool to have this available to users.

**Comment by twiecki** [comment]
You could call it PyATMC3 ;)

**Comment by hvasbath** [comment]
Good suggestion! Thanks! Actually so far not, simply because I dont really know how to do it in the correct way and havent had time yet to look into it. Obviously I would need to have two repositories, but I ultimately would only want to have to do changes once and not repeated in both repos, this is very error prone. So lets say I have the repo beat and the repo pyatmc3 they should be updated both if I do changes in either of them. Any suggestions?

**Comment by twiecki** [comment]
The best way would be to remove the cdoe from beat and have pyatmc3 as a dependency.

**Comment by hvasbath** [comment]
@twiecki I was thinking about it more and was testing a little more. I am confident now that all the new features are working well.
But I think it is very inconvenient for either users BEAT or Pymc3 to have yet another dependency.
What would I need to do so that you agree for including it again into the pymc3 repo? It simply would be independent of the standard sample method. It would get its own backend and it would work fine, wouldnt it? With proper documentation this shouldnt be a problem.
The new features are:
- restart at any state possible
- parallel sampling works
- customized backend, speeds up sampling by factor of 2

**Comment by twiecki** [comment]
That sounds good to me. Maybe turn it into a submodule? But definitely not
against re-adding it if you are up for maintaining that code.

**Comment by hvasbath** [comment]
For sure I will do that! I am still not very familiar with the way the current namespace imports work. Would I need to be aware of certain things to turn it into a submodule?

**Comment by twiecki** [comment]
That should be pretty straightforward to figure out, so no worries on that
front.

**Comment by twiecki** [comment]
@hvasbath Any progress?

**Comment by hvasbath** [comment]
Yes I will likely send the PR next Thursday. On Tuesday I have a presentation and a review due on Wednesday ...
