### ISSUE TITLE
tracetab cannot be imported globally

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1266]
After the namespace change there is no way to import the tracetab module. 
It is not in the pymc3 main namespace. So implementing a backend that is not located in the backend folder from pymc3 does not work easily.

from pymc3 import tracetab

does not work as it is no module.
Or am I missing something here...

**Comment by hvasbath** [comment]
its in backends now! sorry for the panicing!

**Comment by fonnesbeck** [comment]
Yes, the namespace change may have moved some things around, so let us know if anything breaks, as it means we need to add a test.
