### ISSUE TITLE
PyMC3 imports no longer including methods from theanof and blocking

### ISSUE THREAD

**Issue by dustinvtran** [pymc-devs/pymc#1271]
Hi devs. This pull request (https://github.com/pymc-devs/pymc3/pull/1257) removed `core.py`. It used to import to `__init__.py` the method `inputvars`  via `theanof.py`, and the method `DictToArrayBijection` and `ArrayOrdering` via `blocking.py`. These methods are used in Edward for our PyMC3 model wrapper (also see https://github.com/blei-lab/edward/pull/197). 

Is the plan to no longer have these methods available to the user? Do you all suggest we keep hacks as in that pull request to get at PyMC3's utility functions or do you have another approach?

**Comment by fonnesbeck** [comment]
Sorry about that. It was not our intent to break this; we were just trying to clean up the code base, and we had no explicit test for Edward. The best way to more easily expose them is probably through **init**.py, if `blocking` and `theanof` are too cumbersome.

**Comment by dustinvtran** [comment]
No problem! Yep, I agree it makes sense to expose them through adding

``` python
from .blocking import *
from .theanof import *
```

to `__init__.py`.  Are these things in general planned to be exposed to the user? If so, Im happy to submit a pull request which adds to `__init__.py` all the above module imports, also including `vartypes` which was originally imported via `core.py`.

**Comment by springcoil** [comment]
:+1: for this PR any objections @twiecki or @fonnesbeck

**Comment by twiecki** [comment]
Nope that is great.
