### ISSUE TITLE
Issue with sample_ppc when using loaded trace and pickled model

### ISSUE THREAD

**Issue by jt-lab** [pymc-devs/pymc#1277]
Dear all,

I'm trying to draw ppc samples from a hierarchical model. It works if I do it in the same session as the original sampling. However, if I load the trace via the text backend and the model from via pickle, I get an error. I'm relatively new to pymc3, so I may be doing something wrong (maybe something about the model context?).

Does anyone know what might be going on?

Here is the error message:

```
`In [8]: pymc3.sample_ppc(trace,model=model,size=1,samples=1)---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-9126b74f0da9> in <module>()
----> 1 pymc3.sample_ppc(trace,model=model,size=1,samples=1)

/usr/local/lib/python2.7/dist-packages/pymc3/sampling.pyc in sample_ppc(trace, samples, model, vars, size)
    346         for var in vars:
    347             ppc[var.name].append(var.distribution.random(point=param,
--> 348                                                          size=size))
    349 
    350     return {k: asarray(v) for k, v in ppc.items()}

/usr/local/lib/python2.7/dist-packages/pymc3/distributions/discrete.pyc in random(self, point, size, repeat)
     44 
     45     def random(self, point=None, size=None, repeat=None):
---> 46         n, p = draw_values([self.n, self.p], point=point)
     47         return generate_samples(stats.binom.rvs, n=n, p=p,
     48                                 dist_shape=self.shape,

/usr/local/lib/python2.7/dist-packages/pymc3/distributions/distribution.pyc in draw_values(params, point)
    149                 if not isinstance(node, (tt.sharedvar.TensorSharedVariable,
    150                                   tt.TensorConstant)):
--> 151                     givens[name] = (node, draw_value(node, point=point))
    152     values = [None for _ in params]
    153     for i, param in enumerate(params):

/usr/local/lib/python2.7/dist-packages/pymc3/distributions/distribution.pyc in draw_value(param, point, givens)
    207         value = value.value
    208     elif hasattr(value, 'get_value'):
--> 209         value = value.get_value()
    210 
    211     if hasattr(param, 'dtype'):

TypeError: get_value() takes at least 2 arguments (1 given)
```

Many thanks in advance
Jan

**Comment by twiecki** [comment]
Does traceplot work on that loaded trace and do you rebuild the same `model` as the one you used during sampling?

**Comment by jt-lab** [comment]
Yes, traceplot works. Slicing the trace (i.e. trace[100::10]) does not 
work however (I can't remember the error right now, but can check 
later). It works, however, in the same session as the sampling took place.

Could this be a problem?:
- The text backend saves the original trace
- After the sampling run, I slice the trace (thinning it for faster 
  plotting, WAIC calculation, etc.)
- Then the model is pickled

In a new session: after loading I have the original unthinned trace from 
the backend and the unpickled model. Does the model then maybe have some 
reference to thinned trace from during the sampling run?

**Comment by jt-lab** [comment]
Hi,
so I did some more tests. If I load a pickled trace, pcc sampling works fine.
So apparently the trace from the text backend behaves differently. On some low level, the values from the text backend trace apparently have a get_value() which differs from the one sample_pcc expects.

Unfortunately, I have not all traces as pickled objects, therefore I really would like to solve the problem.  Any idea?

Thanks a lot
Jan

P.S.: I just found out this:
`
Pickled trace:
ln [27]: trace.__dict__
Out[27]: 
{'_straces': {0: <pymc3.backends.ndarray.NDArray at 0x7f5f144cf8d0>,
  1: <pymc3.backends.ndarray.NDArray at 0x7f5f104a2390>,
  2: <pymc3.backends.ndarray.NDArray at 0x7f5f0f811150>,
  3: <pymc3.backends.ndarray.NDArray at 0x7f5f0a005cd0>}}

Text backend trace:
In [28]: trace2.__dict__
Out[28]: 
{'_straces': {0: <pymc3.backends.text.Text at 0x7f5f14703690>,
  1: <pymc3.backends.text.Text at 0x7f5f0eb6d990>,
  2: <pymc3.backends.text.Text at 0x7f5f0eb75b90>,
  3: <pymc3.backends.text.Text at 0x7f5f0eb75e90>}}
`
And: 

Pickled:
In [50]: trace._straces[0][0]['varname']
Out[50]: 0.050201422624500003

Text backend:
trace2._straces[0][0]['varname']
Out[51]: array(0.11036452364299999)

**Comment by jt-lab** [comment]
Update:
I provisorily fixed the problem commenting out two lines (208, 209) in distribution.py

(the lower two lines of this block:)

```
# Sanitising values may be necessary.
if hasattr(value, 'value'):
    value = value.value
#elif hasattr(value, 'get_value'):
#  value = value.get_value()
```

**Comment by twiecki** [comment]
Thanks for reporting @jeti182. That's pretty odd. Any idea what the problem is here?

**Comment by jt-lab** [comment]
Well I tried to look into it, but I don't have much time at the moment. Superficially, the draw_value function does not take into account that traces from the text backend contain values with a different get_values function. Maybe it's also theano related?  My fix makes it work with the text backend (and the default one works as well) but probably it breaks the sanitizing required for some other backend? 

Here is the full draw_values function with the problematic part:

```
def draw_value(param, point=None, givens=()):
    if hasattr(param, 'name'):
        if hasattr(param, 'model'):
            if point is not None and param.name in point:
                value = point[param.name]
            elif hasattr(param, 'random') and param.random is not None:
                value = param.random(point=point, size=None)
            else:
                value = param.tag.test_value
        else:
            input_pairs = ([g[0] for g in givens],
                           [g[1] for g in givens])

            value = _compile_theano_function(param,
                                             input_pairs[0])(*input_pairs[1])
    else:
        value = param

    # Sanitising values may be necessary.
    if hasattr(value, 'value'):
        value = value.value
    #jeti# elif hasattr(value, 'get_value'):
    #jeti#     value = value.get_value()

    if hasattr(param, 'dtype'):
        value = np.atleast_1d(value).astype(param.dtype)
    if hasattr(param, 'shape'):
        try:
            shape = param.shape.tag.test_value
        except:
            shape = param.shape
        if len(shape) == 0 and len(value) == 1:
            value = value[0]
    return value

```
