### ISSUE TITLE
'warm' starting with ADVI?

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#1278]
If I run ADVI once with a certain number of steps, and then change the `n` parameter in `pm.variational.advi()`, the ADVI algorithm starts over from scratch if I run it again.

Is it possible to have ADVI do a "warm" start, picking off where it last completed?

(not a feature request, just asking for a yes/no answer, as I don't want to give the devs added pressure)

**Comment by taku-y** [comment]
Unfortunately, we can't do this. But I think this feature can be easily implemented.

**Comment by Spaak** [comment]
I think this is already implemented; at least you can specify the means at which to start:

```
params = mc.variational.advi(n=1000, learning_rate=1, start=model.test_point)
params = mc.variational.advi(n=1000, learning_rate=0.1, start=params.means)
```

This will not re-use the previously computed stds, but in my experience that does not really matter too much.

**Comment by ericmjl** [comment]
@Spaak this should mean I can pickle the params to disk, reload them in another session, and continue from there, is that right?

**Comment by Spaak** [comment]
Yes, exactly.

**Comment by junpenglao** [comment]
No longer an issue in the current Variational API.
