### ISSUE TITLE
QuadPotential confusion

### ISSUE THREAD

**Issue by bwengals** [pymc-devs/pymc#1280]
I don't know if this is the best place to ask, but I'm wondering why the QuadPotential set of classes for setting the momentum in the Hamiltonian [here](https://github.com/pymc-devs/pymc3/blob/3cf54ce12f7efc35af084f2fddff650159c9e2c2/pymc3/step_methods/quadpotential.py) is called "QuadPotential" instead of, say, "QuadKinetic"?  Isn't this the kinetic energy term in the Hamiltonian?  

Also, I am very confused by how to set its parameters, given the docstring.  Would it be possible to make it clearer?

But I have to say, I use this package a lot.  Love it!

**Comment by twiecki** [comment]
@bwengals You might be right, I find that part confusing too. @jsalvatier wrote this a while ago, maybe he has some insight. You could also attempt a refactoring to make it clearer if you think you gained a good enough understanding.

**Comment by twiecki** [comment]
I'll close this for now, feel free to keep asking questions.

**Comment by bwengals** [comment]
Sorry for the slow response.  Sounds good.  I'm getting a handle on this, and I'd be happy to give a refactor a shot then.

**Comment by twiecki** [comment]
Great, looking forward to it!
