### ISSUE TITLE
WAIC and LOO diagnostic 

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#1282]
According to [this paper](http://arxiv.org/abs/1507.04544) when any posterior variance of the log predictive densities (computed by WAIC) exceeds 0.4 and when any shape parameter of Pareto distribution (computed by LOO) is greater than 0.5. Both methods start to fail. 

Should PyMC3 reports those values to the user? They can be used to identify the "problematic" datapoints. And having access to those values could be helpful for diagnosing problems, I guess is not the same to have only one variance above 0.4 than having several and also is not the same to have a value of 0.41 than a value of 3. In the paper the authors also compute the standard error of the WAIC and LOO estimations. Should PyMC3?

May be we can add a plot function to help visualize the variances or the shape parameters. 

What do you think?

**Comment by twiecki** [comment]
That seems useful for sure.
