### ISSUE TITLE
DIC=Inf / WAIC=NaN

### ISSUE THREAD

**Issue by jt-lab** [pymc-devs/pymc#1288]
Hi all,

for a certain model I get DIC=Inf and WAIC=NaN, whereas I get proper values for the same model with other data. The traceplots look; chains have converged.

I suspect a numerical problem. Any suggestions what I can try? 

Thanks,
Jan

**Comment by jt-lab** [comment]
Update: The problem could be similar to this issue described for Stan/R's waic calculation: http://ihrke.github.io/waic_stan.html

I'm currently experimenting with bigfloat.exp to avoid numerical problems, but without success so far. Any ideas are highly welcome!

**Comment by fonnesbeck** [comment]
Can you post a small example that we can replicate?

**Comment by jt-lab** [comment]
I cannot really replicate it. It only occurs for a particular model and a particular trace (I can upload and send you the pickles, if you like). I now got a waic estimate after thinning the trace.

**Comment by twiecki** [comment]
OK, can just be some outlier samples of a non-converged chain.
