### ISSUE TITLE
mvnormal logp

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1289]
This is taken from the pymc3 multivariate.py

``` javascript
def logp(self, value):
        mu = self.mu
        tau = self.tau

        delta = value - mu
        k = tau.shape[0]

        result = k * tt.log(2 * np.pi) + tt.log(1./det(tau))
        result += (delta.dot(tau) * delta).sum(axis=delta.ndim - 1)
        return -1/2. * result
```

Am I totally missing something here or isnt it supposed to be only 

``` python
result = k * tt.log(2 * np.pi) + tt.log(det(tau)) 
```

as the (1/ ...) part is taken care of:

return -1/2. \* result

???

**Comment by twiecki** [comment]
Note that we're expressing this with the precision matrix, not covariance, hence the `1/..`. I did another check here to compare it to scipy logp: https://gist.github.com/a037870e573fd77d362385530309c0c1

Seems correct to me, I'm closing this for now but feel free to keep commenting.
