### ISSUE TITLE
Create guidelines for contributing

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1293]
As has been requested before, we should have formal guidelines for contributing to the project. This would make merging pull requests smoother (assuming contributors read the guidelines), and hopefully reduce noise in the issue tracker.

To facilitate this, we should have a core contributor meeting via Hangout or Gitter to hash out what ought to be in the document.

**Comment by springcoil** [comment]
Let me know when you need me for the hangout...

**Comment by springcoil** [comment]
I started creating this myself - because we're all busy and I had some time. It needs some work but it might do for now.
