### ISSUE TITLE
stickbreaking transform

### ISSUE THREAD

**Issue by fjaekel** [pymc-devs/pymc#1297]
Sampling from a flat Dirichlet distribution (all alphas equal to one): With no transform the samples look fine and the distribution is flat, with the stickbreaking transform the distribution is not flat.

``` python
# using pymc 3.0
from pymc3 import *
import numpy as np

# stickbreaking is the default transform
with Model() as test_stickbreaking:
    alphas = np.ones(3)
    p = Dirichlet('p', a = alphas, shape = (3,))
    trace_stickbreaking = sample(5000)
traceplot(trace_stickbreaking)

# if you don't use the transform the distribution is flat
with Model() as test_none:
    alphas = np.ones(3)
    p = Dirichlet('p', a = alphas, shape = (3,),
                  transform = None)
    trace_none = sample(5000)
traceplot(trace_none)
```

**Comment by twiecki** [comment]
Can you post some plots to show this?

**Comment by fjaekel** [comment]
![stickbreaking](https://cloud.githubusercontent.com/assets/4799839/17884303/e5f7d872-6917-11e6-9ffd-4ee3ed4aa502.png)
![none](https://cloud.githubusercontent.com/assets/4799839/17884311/ee2b3a48-6917-11e6-9608-14cd9265a0db.png)

**Comment by twiecki** [comment]
Hm, yeah, that looks odd. @taku-y any ideas?

**Comment by taku-y** [comment]
I don't come up with any idea for this error. I think there might be a problem in the implementation of the Jacobian of the transform. [This](https://groups.google.com/forum/#!topic/stan-dev/09GIjIvhtkE) post may help us to check the code.

**Comment by taku-y** [comment]
I plotted the samples drawn from Dirichlet distribution with the transform, on the simplex in the 3D space. I visually checked that samples were uniformly distributed on the simplex. See a [notebook](https://gist.github.com/taku-y/65b0887335984ae9140b90c20eecd91f). On the other hand, samples drawn without any transform violates the sum-to-1 constraint. 

The transformation works correctly. If fjaekel agrees with this, I think this issue can be closed.

**Comment by twiecki** [comment]
Thanks @taku-y, that makes a ton of sense: Plotting a histogram over individual dimensions of the dirichlet does not have to look uniform, it has to look uniform over the simplex, which it does.

**Comment by twiecki** [comment]
Intuitively, the samples have to be correlated -- large values in one dimension require small values in the other two to satisfy sum-to-1. This explains the pattern of the decaying histogram we are seeing. With increasing dimensionality, that decay should become more and more pronounced.

**Comment by fjaekel** [comment]
Yes, thanks, classic mistake!
