### ISSUE TITLE
incompatibility with Python 2 due to checking for type str

### ISSUE THREAD

**Issue by tyarkoni** [pymc-devs/pymc#1301]
The README suggests that PyMC3 is meant to be compatible with Python 2, but in at least one place ([checking the `name` argument in the `Distribution` initializer](https://github.com/pymc-devs/pymc3/blob/c396430d3f69d96d807c3d043dcaf147e4396b89/pymc3/distributions/distribution.py#L22)), there's a check for type `str`, which should be `basestring` in Python 2.

The principled solution would be to check against `string_types` from six, but if you want to avoid the dependency, maybe wrap the checks in try/except blocks and check against both `str` and `basestring`? Let me know if you want a PR for this.

**Comment by fonnesbeck** [comment]
No, there is no PyMC2 compatibility. We sought to keep the syntax as close as possible to PyMC2, but there should be no suggestion that a PyMC2 model will run under PyMC3. If you can point me to the misleading part of the README, I will go in and improve the text.

Sorry for the confusion.

**Comment by fonnesbeck** [comment]
Yes, PyMC3 should run under Python 2.7.

**Comment by fonnesbeck** [comment]
We do want to avoid using `six` so a PR would be most appreciated.
