### ISSUE TITLE
Increasingly poor NUTS sampling of parents as children added to a model

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1305]
I'm not sure whether this is an issue with PyMC3 or just something that happens with complex hierarchical models, so I thought I'd post it to be safe. The following code produces reasonable-looking samples:

``` python
from os import system
from os.path import join as pj
import matplotlib.pyplot as plt
import pymc3 as pm


with pm.Model() as model:

    name = 'test_1'
    loc = pm.Normal(name='loc', mu=0., sd=1.)
    scale = pm.HalfCauchy(name='scale', beta=1.)
    nu = pm.Exponential(name='nu_minus_one', lam=1 / 29.) + 1
    children = pm.StudentT(name='children', mu=loc, sd=scale, nu=nu, shape=(10, ))
    backend = pm.backends.Text(name)
    trace = pm.sample(10000, trace=backend)
    pm.traceplot(trace)
    plt.savefig(pj(name, 'traceplot.png'))
```

![traceplot](https://cloud.githubusercontent.com/assets/9464950/18065101/78488540-6e00-11e6-93e3-99c63d1a21bb.png)

However, increasing the number of "children" nodes, and sampling from the parents starts to look strange:

``` python
from os import system
from os.path import join as pj
import matplotlib.pyplot as plt
import pymc3 as pm


with pm.Model() as model:

    name = 'test_2'
    loc = pm.Normal(name='loc', mu=0., sd=1.)
    scale = pm.HalfCauchy(name='scale', beta=1.)
    nu = pm.Exponential(name='nu_minus_one', lam=1 / 29.) + 1
    children = pm.StudentT(name='children', mu=loc, sd=scale, nu=nu, shape=(100, ))
    backend = pm.backends.Text(name)
    trace = pm.sample(10000, trace=backend)
    pm.traceplot(trace)
    plt.savefig(pj(name, 'traceplot.png'))
```

![traceplot](https://cloud.githubusercontent.com/assets/9464950/18065203/df85a99a-6e00-11e6-8800-9affc50bb028.png)

The problem continues are more children are added:

``` python
from os import system
from os.path import join as pj
import matplotlib.pyplot as plt
import pymc3 as pm


with pm.Model() as model:

    name = 'test_3'
    loc = pm.Normal(name='loc', mu=0., sd=1.)
    scale = pm.HalfCauchy(name='scale', beta=1.)
    nu = pm.Exponential(name='nu_minus_one', lam=1 / 29.) + 1
    children = pm.StudentT(name='children', mu=loc, sd=scale, nu=nu, shape=(500, ))
    backend = pm.backends.Text(name)
    trace = pm.sample(10000, trace=backend)
    pm.traceplot(trace)
    plt.savefig(pj(name, 'traceplot.png'))
```

![traceplot](https://cloud.githubusercontent.com/assets/9464950/18065267/3accf272-6e01-11e6-94f6-ce16a9c03ef0.png)

**Comment by twiecki** [comment]
I don't find this very surprising. Because there is no observed you are directly sampling from the prior. Certainly, the correlations between the top and bottom level RVs will be crazy high. You can plot one of `children` vs `scale` to get a view into the "funnel". I discussed with @fjaekel at one point how sampling from the prior could be done more effectively, it's not very straight forward though.

I'm closing this as I think it's not a pymc3 issue but a general issue of MCMC in this case. Feel free to keep asking questions.
