### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1318]
In light of #1313, seems like there exist some existing style problems in the code base.  For example, running `flake8 --statistics pymc3` gives over 2000 style problems in 113 files.  Happy to help tackle this however you'd like -- a single diff with all the changes, or just encouraging new contributions to fix these problems along the way.  

For reference, here are the 10 files with the most warnings:

```
239 pymc3/tests/test_distributions.py
151 pymc3/tests/test_distributions_random.py
95  pymc3/examples/best.py
73  pymc3/distributions/continuous.py
61  pymc3/examples/GHME_2013.py
57  pymc3/__init__.py
57  pymc3/distributions/__init__.py
54  pymc3/math.py
52  pymc3/stats.py
52  pymc3/distributions/dist_math.py
```

**Comment by springcoil** [comment]
- [x] test_distributions
- [x] test_distributions_random
- [x] best.py
- [x] distributions/continuous.py
- [x] GHME_2013.py
- [ ] distributions/**init**.py
- [x] pymc3/math.py
- [ ] pymc3/stats.py
- [ ] distributions/dist_math.py

**Comment by springcoil** [comment]
I've submitted two - best.py and distributions/continuous.py

**Comment by ColCarroll** [comment]
#1321 got test_distributions_random

I'm looking at test_distributions now

**Comment by springcoil** [comment]
Ok cool :) I'm done for the evening :)

**Comment by ColCarroll** [comment]
Thanks for the help in adding everything!

**Comment by springcoil** [comment]
https://github.com/pymc-devs/pymc3/pull/1328 is also another one.

**Comment by ColCarroll** [comment]
#1330 gets test_distributions

**Comment by springcoil** [comment]
I think there are only three files left that need done with pep8 - could you do this @twiecki or @fonnesbeck. One that's done I think we can quickly amend the release notes and go for a release candidate.

**Comment by springcoil** [comment]
Seems https://github.com/pymc-devs/pymc3/pull/1331 used the nuclear option :) Let's see if this works :)

**Comment by ColCarroll** [comment]
Closing this -- seems as though the rest will get cleaned up with time.  This is the output running now:

```
$ pycodestyle --statistics pymc3/
...
3       E265 block comment should start with '# '
1       E302 expected 2 blank lines, found 0
31      E402 module level import not at top of file
58      E501 line too long (112 > 100 characters)
1       E711 comparison to None should be 'if cond is None:'
1       E713 test for membership should be 'not in'
13      E731 do not assign a lambda expression, use a def
84      W291 trailing whitespace
```
