### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1319]
As I saw pymc3 is using the apache license.

How do I have to refer correctly to pymc3 and parts of the code I edited and included in my package? In the docs of each function? Once in the readme of the package? Of course I will cite it correctly in the publication.

Are there any implications from that on which license I should choose for my library?
At the moment I am getting a headache for choosing a license - I have no one around who is familiar with these things and what they imply.

Any comments on that would be very much appreciated!

**Comment by fonnesbeck** [comment]
The Apache license is a permissive one. Unlike the GPL it does not force its licensing upon packages that use and extend it; simply citing where code is derived from PyMC3 is sufficient. Its very similar to the MIT license, but with some additional patent protection language.

**Comment by springcoil** [comment]
I guess it's safe to close this then.
