### ISSUE TITLE
Release candidate on PyPI

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1332]
I think once we all agree we need to stick a release candidate out there - or on PyPI. 

I've never done this before - has anyone else?

**Comment by fonnesbeck** [comment]
I can do one this afternoon.

**Comment by springcoil** [comment]
Cool :) I'll tell the London Data Community this evening.

**Comment by fonnesbeck** [comment]
I will tag a release candidate based on the current master.

**Comment by springcoil** [comment]
Cool

**Comment by fonnesbeck** [comment]
RC1 is tagged and released. Working on PyPI now. If anyone has access to non-Mac platforms on which to build binaries, please do so.

**Comment by fonnesbeck** [comment]
The RC is [posted to PyPI](https://pypi.python.org/pypi/pymc3). Please test!
