### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#1339]
I'm trying to kickstart a conda package for pymc3 (and I'm happy to be the recipe maintainer for it as well). However, it looks like requirements.txt isn't distributed with the source distribution, making the conda skeleton build process error out. Here's the full error message I'm receiving.

``` bash
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
$PYTHONPATH = /var/folders/4d/5h2mymgs27q1sk0828h4wyh00000gn/T/tmpy2d8bhaoconda_skeleton_pymc3-3.0rc1.tar.gz/pymc3-3.0rc1
Error: command failed: /Users/ericmjl/anaconda/envs/_build_placehold_placehold_placehold_placehold_plac/bin/python setup.py install
```

**Comment by fonnesbeck** [comment]
Yes, it looks like `requirements.txt` does not get included in the source distribution. Sounds like we need a `MANIFEST` file.

**Comment by kyleabeauchamp** [comment]
Are you planning to build the conda recipe via conda-forge or manually?  Mostly curious.  Not sure what the GPU theano status is on conda-forge, though.

**Comment by ericmjl** [comment]
@kyleabeauchamp I'm planning to build it via conda-forge, but I have a habit of using conda-skeleton locally first just to catch build errors.

**Comment by kyleabeauchamp** [comment]
SGTM.  

@fonnesbeck we may want to try out conda-forge for handling the pymc2 package at some point.  Not sure how well their Fortran compiler behaves, however.

**Comment by twiecki** [comment]
@ericmjl That'd be a great contribution. I added a requirements.txt file here: https://github.com/pymc-devs/pymc3/commit/b5673fecb9acc6f899dc3b28bbb3e992d638c350

Let me know if that one doesn't work.

**Comment by twiecki** [comment]
Oh, I misunderstood, we had one but it wasn't included.

**Comment by twiecki** [comment]
Added here: https://github.com/pymc-devs/pymc3/commit/f723797428cc67678cfb40f0388f72dd135ca503

**Comment by ericmjl** [comment]
@twiecki has the version with MANIFEST.in been uploaded to PyPI yet? I'm happy to make a conda-forge recipe that builds from the GitHub repository directly, but I think most of the conda-forge recipes are built from a PyPI release.

**Comment by fonnesbeck** [comment]
@ericmjl you'd have to wait until the next release candidate for that. Maybe tomorrow or the weekend?

**Comment by ericmjl** [comment]
@fonnesbeck: not a problem, happy to wait 😄 . I'll check back on the weekend then.
