### ISSUE TITLE
Multivariate GaussianRandomWalks

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1353]
I wish to do a piecewise linear regression for a set of countries. Hence I wish to do something similar to:

```
    beta = pm.GaussianRandomWalk('beta', sigma_beta**-2,
                                 shape=(n_countries, len(prices) // subsample_beta))

    # Make coefficients have the same length as prices
    beta_r = T.repeat(beta, subsample_beta)
```

However, I do not know if firstly if shape is a parameter in GaussianRandomWalk and secondly if in the way that I declared it, is the Gaussian Process across the price section or the countries (which I do not want).

This issue may be similar to: https://github.com/pymc-devs/pymc3/issues/535

**Comment by twiecki** [comment]
I think that looks correct, does it work? A good approach is to check the `.tag.test_value`s to make sure everything lines up. I'm closing this but feel free to keep asking questions. Here's an example of doing that: https://twiecki.github.io/probabilistic_ml.ipynb (towards the very end).
