### ISSUE TITLE
ATMCMC name_error

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1355]
Looks like there's an undefined `sampling` variable that's mentioned in `step_methods/ATMCMC.py`, but not defined anywhere

https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L516
https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L552
https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L561
https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L580
https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L585

**Comment by twiecki** [comment]
CC @hvasbath

**Comment by hvasbath** [comment]
That must have got lost during the name space change ...
It is simply 

from pymc3 import sampling

Will make a PR ...

**Comment by hvasbath** [comment]
Sorry with this relative imports I cannot figure out how to get the _choose_backend, _sample into the name space ...
from ..sampling import _choose_backend, _sample

does not work ...:

cannot import name _choose_backend

I am not a friend of this relative imports and have never been using it ... if anybody can help ...

**Comment by ColCarroll** [comment]
@hvasbath this is actually a problem with a circular import:

pymc3/**init**.py has `from .sampling import *`
pymc3/sampling.py has `from .step_methods import (some stuff)`
pymc3/step_methods/**init**.py has `from .ATMCMC import ATMCMC`,
pymc3/step_methods/ATMCMC.py has `from ..sampling import _choose_backend`

There [are ways to fix this](http://stackoverflow.com/questions/22187279/python-circular-importing), but importing a "private" function (`_choose_backend`) and this circular import makes me think you (or someone!) might need to reorganize things a bit.

**Comment by hvasbath** [comment]
@fonnesbeck could you please have a look at this, as you mainly made the namespace change?

**Comment by fonnesbeck** [comment]
Step methods should not be accessing `sampling` at all; backend choice is meant to be independent of the step method used. 

I'm confused by the fact that ATMCMC is trying to use `_choose_backend` from `sampling`, yet it has its own `_choose_backend` down at [L489](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/ATMCMC.py#L489). Is this intentional? The local version seems not to be used at all.

**Comment by hvasbath** [comment]
I didnt put it there. Then lets simply use that one ;) . But then how to get _sample from sampling? Also copy paste it there?

**Comment by fonnesbeck** [comment]
Why is the step method getting involved in backend selection? Why not leave it to `sample` and remove this altogether?

**Comment by hvasbath** [comment]
Because ATMIP cannot be started with sample, which is why it has its own ATMIP_sample L318 function, which then ultimately does _sample. The backend selection is not the problem ...

**Comment by fonnesbeck** [comment]
It looks like we will need to either refactor the step method to work independently of `sample`, or generalize what is available in `sample` to accommodate more complicated step methods like this.

**Comment by hvasbath** [comment]
Probably we will remove ATMCMC from the pymc3 distribution as stated here:
https://github.com/pymc-devs/pymc3/issues/1264

So maybe dont bother further ...?
