### ISSUE TITLE
Get examples running

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1356]
The example suite touches a lot of the code that the tests miss (for example, #1355), and `test_examples` is a nice way of running them all, but it isn't run on travis (since it fails in a lot of ways).  

I have started working on getting them running again -- any objections to a `Pymc3Example` class to provide a template for example code?  It seems just requiring a `set_up` and `run` method would help.

**Comment by twiecki** [comment]
I completely agree and really like that idea.

**Comment by fonnesbeck** [comment]
My only objection to creating classes is that they add complexity to the examples, in terms of the structure and quantity of code. If the primary role for these examples is now testing, then I am behind it; if it is to show off how to build models in PyMC3, then not so much. 

So, are we now relying on Jupyter notebooks as public-facing examples of how to create and run PyMC models?

**Comment by twiecki** [comment]
@fonnesbeck After looking at the code I realized the same thing. 

Going though some of the examples, they are pretty old and some seem not up-to-date in terms of coding style. They also don't have any explanations. I wonder how many users really use it as a source of documentation. Those we really like we might want to port to NBs.

**Comment by fonnesbeck** [comment]
It is nice having some of the examples to use for quick demos or for teaching purposes, such that you can just `from pymc3.examples import gelman_bioassay`, run the model and look at all the objects and output. Wrapping these in testing objects might make these less useful for these situations. 

I also wouldn't want to give the impression that PyMC3 models are meant to be coded in an object-oriented fashion, which might happen if all the examples are expressed this way.

I wouldnt be opposed to simply moving many of the models (particularly those that have a corresponding notebook) over to the `tests` folder and wrapping them as has been done here, while leaving a smaller set in the `examples` folder. They do need to be standardized and updated, though, I agree.

**Comment by twiecki** [comment]
Yes, that's a good point.

**Comment by fonnesbeck** [comment]
Here's a proposed list of the various examples and what we might do with them. Feel free to edit, as these are just my opinions:

### Move to test classes (as proposed by PR)
- [ ] ARM examples
- [ ] tutorial
- [ ] disaster_model_missing
- [ ] discrete_find_MAP
- [ ] glm_linear
- [ ] lasso_block_update
- [ ] occupancy
- [ ] heirarchical_*
- [ ] stochastic_volatility
- [ ] speedtest_pymc3
- [ ] rsv
- [ ] ATMIP_2gaussians

### Leave in examples and clean up
- [ ] gelman_bioassay
- [ ] gelman_schools
- [ ] arbitrary_stochastic
- [ ] arma_example
- [ ] GHME
- [ ] lightspeed
- [ ] BEST
- [ ] factor_potential
- [ ] disaster_model
- [ ] disaster_model_arbitrary_deterministic
- [ ] glm_robust
- [ ] lasso_missing

### Convert to notebooks and remove
- [ ] garch
- [ ] custom_dists
- [ ] LKJ_correlation

### Retire
- [ ] python_vs_c
- [ ] logistic
- [ ] normal
- [ ] nutstest
- [ ] wishart
- [ ] banana
- [ ] dirichlet

**Comment by ColCarroll** [comment]
@fonnesbeck -- that makes sense, and I agree that examples are good as ways to start experimenting with code, which this PR doesn't necessarily encourage.  

A few motivations for the PR (which I think your suggestion mostly solves):
1. Much of the code runs in the global scope 
2. Increase code coverage for free
3. Use travis to keep examples up to date
4. Identify "hot paths" in the code more realistically -- I had been running `cProfile` on the test suite, but that is not a great proxy for how the library is actually used.

Happy to change the PR to follow this suggestion.  Two questions:
1. Any suggestions for a fate for these examples?
2. ATMIP_2gaussians.py
3. banana.py
4. custom_dists.py
5. dirichlet.py
6. garch_example.py
7. simpletest.py
8. Three of these examples (BEST, disaster, glm_robust) are already in the notebooks section, so seems safe to move them to the retire list?

**Comment by ColCarroll** [comment]
Actually, it also looks like tutorial.py, discrete_find_MAP.py, lasso_block_update.py, and stochastic_volatitility.py are also copied/pasted from the notebooks section.

**Comment by fonnesbeck** [comment]
I've updated the list somewhat, and included another option, which is convert to a useful notebook and remove. Feel free to suggest moving these about if you feel strongly about any.

**Comment by twiecki** [comment]
Looks great. I moved LKJ to also convert to NB because it's critical.

**Comment by ColCarroll** [comment]
I would move `speedtest_pymc3` to "Retire", since it is an unfinished copy of the occupancy example.  Also, seven of the examples are duplicated in both the `examples` folder and the `notebook` folder, so probably one of the two copies should be deleted in each case (to me, the notebook examples look great, so I would just delete them from examples).  These are
- BEST
- disaster
- glm_robust
- tutorial
- discrete_find_MAP
- lasso_block_update
- stochastic_volatility

Thanks for helping out with this -- good examples are what got me using pymc in the first place!

**Comment by fonnesbeck** [comment]
OK, great. I will try and have a go at notebook conversion later today, if I get a chance.
