### ISSUE TITLE
Add a programming guide / architecture overview for new developers to get started

### ISSUE THREAD

**Issue by YanWang2014** [pymc-devs/pymc#1359]
I want to implement an approximate Bayesian computation (ABC) approach in PyMC3. However, I found it difficult to start. 
So will there be a programming guide for PyMC3?

**Comment by twiecki** [comment]
What do you feel is missing in https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md?

**Comment by YanWang2014** [comment]
Hi twiecki,
Thanks for the reply.
By programming guide I mean some kind of code annotation. For example, when I tried to read metropolis.py, I met  `class Metropolis(ArrayStepShared)`, so I had to check arraystep.py, where I found `ArrayStepShared` is a faster version of `ArrayStep`.  Then I went to `class ArrayStep(BlockedStep)`.  Then I found it difficult to understand `class BlockedStep`. 
However in slicer.py I found `class Slice(ArrayStep)` instead of `class Slice(ArrayStepShared)`.
So the way for new members to take part in the development is to read through all the relevant code to get started? 
Regards,
Yan

**Comment by twiecki** [comment]
@YanWang2014 I see, yes, these bits are not really documented anywhere. An architecture overview would be perfect, I agree.

**Comment by twiecki** [comment]
And yes, for now you have to read the code. What feature are you looking to implement?

**Comment by YanWang2014** [comment]
I want to implement [ABC-MCMC or ABC-SMC](https://en.wikipedia.org/wiki/Approximate_Bayesian_computation) method.

**Comment by springcoil** [comment]
Do we add this to the list of things that needs done for the release?

**Comment by twiecki** [comment]
@springcoil I wouldn't say so.

**Comment by majidaldo** [comment]
this would help troubleshoot user problems as well.

**Comment by springcoil** [comment]
I think this is being resolved by doc changes and other issues. So I'll close this.
