### ISSUE TITLE
Leave-one-out Cross Validation error

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1363]
Hi all,
I might not be using this correctly but I get this error. 

``` python
IndexErrorTraceback (most recent call last)
<ipython-input-18-761e10d4ffa5> in <module>()
      1 with mdl_peak:
----> 2     peak_loo = pm.loo(trc_peak)
      3 
      4 peak_loo

/mnt1/anaconda2/lib/python2.7/site-packages/pymc3/stats.pyc in loo(trace, model, n_eff)
    189     M = S - q80
    190     z = (np.arange(M) + 0.5) / M
--> 191     expvals = map(lambda x: pareto.ppf(z, x[0], scale=x[2]), pareto_fit.T)
    192 
    193     # Replace importance ratios with order statistics of fitted Pareto

/mnt1/anaconda2/lib/python2.7/site-packages/pymc3/stats.pyc in <lambda>(x)
    189     M = S - q80
    190     z = (np.arange(M) + 0.5) / M
--> 191     expvals = map(lambda x: pareto.ppf(z, x[0], scale=x[2]), pareto_fit.T)
    192 
    193     # Replace importance ratios with order statistics of fitted Pareto

IndexError: index 2 is out of bounds for axis 0 with size 1
```

Is this evidence that I shouldn't be using LOO here? Has anyone seen a similar error. I can't share the code that caused this but I can share the error. above. @fonnesbeck have you seen this error before?

**Comment by fonnesbeck** [comment]
I can't replicate this with an arbitrary model. Can you confirm that there is nothing odd about your trace? Other than that, you'd have to go in and put a trace to see what `pareto_fit` ends up looking like.

**Comment by springcoil** [comment]
What could be wrong with my trace? Are there any diagnostics you can recommend?
I'll put in the trace and see what happens with `pareto.fit`

**Comment by fonnesbeck** [comment]
No idea, but it looks like the scipy Pareto `fit` function is not returning the expected output, and it is being fit to the values in the trace.

**Comment by springcoil** [comment]
I'll have a go with another model. :)  I added https://github.com/pymc-devs/pymc3/pull/1364 based on this exploration. I think it's beneficial
