### ISSUE TITLE
Full-rank ADVI?

### ISSUE THREAD

**Issue by bsmith89** [pymc-devs/pymc#1366]
Any plans to implement?

**Comment by taku-y** [comment]
I have implemented a part of ADVI in PyMC3. I personally don't have any plan for implementing full-rank ADVI. Instead, I want to implement more flexible sampling methods like [normalizing flows](https://arxiv.org/abs/1505.05770), [Hamiltonian VB](https://arxiv.org/abs/1609.02123), and [Stein VB](https://arxiv.org/abs/1608.04471), which are more flexible than Gaussian (full-rank) ADVI. But any  contribution to ADVI is wellcome. Thanks for your interest.

**Comment by twiecki** [comment]
@bsmith89 I'm closing this, feel free to open a PR if you get around to implementing it.
