### ISSUE TITLE
Discrete Variables with ADVI

### ISSUE THREAD

**Issue by soteri0s** [pymc-devs/pymc#1368]
Hi,

I'm trying to implement a model which entails both binary/discrete and continuous latent variables. So, I thought that I could proceed by using BinaryMetropolis for the former and ADVI for the latter (specifying this via the vars argument). However ADVI crashes due to the existence of the discrete variables in the definition of the model. 

Is there any other way I can perform VI for my model using pymc3? Using sampling (e.g., NUTS) is not an option for me as I have to process very big datasets.

Thanks.

**Comment by twiecki** [comment]
You have to integrate out the discrete variables, but otherwise it's not possible.
