### ISSUE TITLE
Setup script fails

### ISSUE THREAD

**Issue by korkinof-aig** [pymc-devs/pymc#1382]
Hi guys,
When trying to install from source, I had the setup script failing.
It turns out that due to the '*', it tries to copy some folders as files and breaks.
So I fixed it easily, but though I should mention it here just in case you are not aware of this.
Best,
D.

**Comment by twiecki** [comment]
@fonnesbeck Maybe we should just use `Manifest.in` after all?

**Comment by fonnesbeck** [comment]
Is this a platform-specific issue?

**Comment by korkinof-aig** [comment]
I'm on Ubuntu 16.04 and had to add the following exclusions:
`exclude_package_data={
              'pymc3.examples': ['data/pmf-map-d5', 'data/6bb8d06c69c0666e6da14c094d4320d115f1ffc8'],
              'docs': ['source/data/pmf-map-d5', 'source/data/6bb8d06c69c0666e6da14c094d4320d115f1ffc8']},`

**Comment by twiecki** [comment]
Should be fixed with #1399.

@korkinof-aig can you try? 
`pip install --force-reinstall -U git+https://github.com/pymc-devs/pymc3@manifest`

**Comment by twiecki** [comment]
Closed by #1399
