### ISSUE TITLE
Fixme in MvNormal

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1385]
I came across this - https://github.com/pymc-devs/pymc3/blob/a29f7f1602e239b042128fe0d05a55c482d66162/pymc3/distributions/multivariate.py#L57 does this still need fixed? cc @fonnesbeck @twiecki 

A larger follow up question is do we need to run `ack` or something for all the Fixme's ... I'm trying to not add stuff that needs done to the release though - otherwise it'll take years :)

**Comment by twiecki** [comment]
Huh, yeah, that looks definitely wrong.

**Comment by twiecki** [comment]
I'd prefer if we parameterized MvNormal via `cov` to begin with. Same with `Normal` which should default to `sd` instead of `tau`, there have been two issues where that was the problem. Best to do this as well before a release if it's painful to users in the short-term.

**Comment by springcoil** [comment]
Just so I understand is this just a case of sensibly picking defaults? So users are exposed to having to learn about this?

**Comment by twiecki** [comment]
Yes. Most commonly people use standard-deviation and cov to parameterize Normals. However, because of conjugacy, probabilistic programming languages often defaulted to precision instead. Today, conjugacy is not relevant anymore so it's best to make it intuitive.

**Comment by springcoil** [comment]
- [x] - Fix Normals parameterization 
- [x] -Fix MvNormal parameterization

**Comment by fonnesbeck** [comment]
I agree that parameterizing via precision is a little passé. Happy to switch the default to `sd` and `Sigma`, respectively.

**Comment by twiecki** [comment]
Closed with #1398.
