### ISSUE TITLE
MvNormal not accepting stds for arbitrary 2d uncertainties

### ISSUE THREAD

**Issue by philastrophist** [pymc-devs/pymc#1387]
Essentially it is [this problem](http://stackoverflow.com/questions/39677240/multivariate-linear-regression-in-pymc3) on stackoverflow. 

If attempting to fit a straight line to 2d uncertainties with `MvNormal`, it raises `LinAlgError: Last 2 dimensions of the array must be square`.

```
from pymc3 import  *

import numpy as np
import matplotlib.pyplot as plt

size = 200
true_intercept = 1
true_slope = 2

true_x = np.linspace(0, 1, size)
# y = a + b*x
true_regression_line = true_intercept + true_slope * true_x
# add noise

# here the errors are all the same but the real world they are usually not!
std_y, std_x = 0.1, 0.1 
y = true_regression_line + np.random.normal(scale=std_y, size=size)
x = true_x + np.random.normal(scale=std_x, size=size)

y_err = np.ones_like(y) * std_y
x_err = np.ones_like(x) * std_x

data = dict(x=x, y=y)

with Model() as model: # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    intercept = Normal('Intercept', 0, sd=20)
    gradient = Normal('gradient', 0, sd=20)


    # Define likelihood
    likelihood = MvNormal('y', mu=intercept + gradient * x,
                        tau=1./(np.stack((y_err, x_err))**2.), observed=y)

    # start the mcmc!
    start = find_MAP() # Find starting value by optimization
    step = NUTS(scaling=start) # Instantiate MCMC sampling algorithm
    trace = sample(2000, step, start=start, progressbar=False) # draw 2000 posterior samples using NUTS sampling
```

It seems like this should be a common problem but I see no other questions/post about this issue.

Thanks

**Comment by twiecki** [comment]
Not sure which model you are trying to build. Don't you want to estimate the cov matrix? In that case I would look at the LKJ prior: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/LKJ_correlation.py

**Comment by aloctavodia** [comment]
@twiecki I think this problem was solved. He was trying to do linear regression explicitly modeling uncertainty in the input and output variables.

**Comment by twiecki** [comment]
Thanks @aloctavodia.

**Comment by philastrophist** [comment]
Thanks guys, your replies and the stackoverflow have made this a lot clearer. I wasn't aware of the lkj correlation before :)
