### ISSUE TITLE
ADVI should not set seed by default

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1396]
`pm.variational.advi()` and `pm.variational.sample_vp()` set a default seed. As we're changing sampling to never set a seed (https://github.com/pymc-devs/pymc3/pull/1395) we should do the same for ADVI.

@taku-y any thoughts / concerns?

**Comment by taku-y** [comment]
I agree with this change. Thanks to tell me that.

**Comment by twiecki** [comment]
Addressed by https://github.com/pymc-devs/pymc3/pull/1397
