### ISSUE TITLE
ENH - Mixture density class

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1401]
I often find myself marginalizing over discrete variables and using hacks like

```
def normal_mixture_rvs(*args, **kwargs):
    w = kwargs['w']
    mu = kwargs['mu']
    tau = kwargs['tau']

    size = kwargs['size']

    component = np.array([np.random.choice(w.shape[1], size=size, p=w_ / w_.sum())
                          for w_ in w])

    return sp.stats.norm.rvs(mu[np.arange(w.shape[0]), component], tau[component]**-0.5)

class NormalMixture(pm.distributions.Continuous):
    def __init__(self, w, mu, tau, *args, **kwargs):
        super(NormalMixture, self).__init__(*args, **kwargs)

        self.w = w
        self.mu = mu
        self.tau = tau

        self.mean = (w * mu).sum()

    def random(self, point=None, size=None, repeat=None):
        w, mu, tau = draw_values([self.w, self.mu, self.tau], point=point)

        return normal_mixture_rvs(w=w, mu=mu, tau=tau, size=size)

    def logp(self, value):
        w = self.w
        mu = self.mu
        tau = self.tau

        return bound(logsumexp(tt.log(w) + (-tau * (value - mu)**2 + tt.log(tau / np.pi / 2.)) / 2.,
                               axis=1).sum(),
                     tau >=0, w >= 0, w <= 1)
```

to speed up convergence.  It seems to me like we could probably add a nice built-in `MixtureDensity` class to facilitate this flexibly.

Looking for feedback before starting to write this.

**Comment by kyleabeauchamp** [comment]
Do you recall a good citation that discusses this? Is it in the stan paper?

**Comment by twiecki** [comment]
This would be great, I knew the Stan guys use this to pretty good effect, just didn't know how to do it properly.

**Comment by AustinRochford** [comment]
@kyleabeauchamp yes, I think it's Chapter 11, Latent Discrete Parameters, of the [Stan reference v2.8.0](http://www.uvm.edu/~bbeckage/Teaching/DataAnalysis/Manuals/stan-reference-2.8.0.pdf)

**Comment by AustinRochford** [comment]
@twiecki it definitely speeds up mixing drastically for some models.  I will start working on this when I get the chance!

**Comment by fonnesbeck** [comment]
This is essentially what we do in our `ZeroInflated*` models to eliminate the use of latent indicators. Would be handy to have mixtures of often-used distributions like normals.

**Comment by AustinRochford** [comment]
@fonnesbeck I was envisioning a base class that could take arbitrary distributions for the mixture components, with subclasses/encapsulating classes for specific common use cases (zero inflated, normal mixtures, etc.).
