### ISSUE TITLE
LKJ_correlation.py likelihood call is incorrect 

### ISSUE THREAD

**Issue by philastrophist** [pymc-devs/pymc#1409]
[In the LKJ_correlation.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/LKJ_correlation.py) example, the likelihood call should read:
`like = MvNormal('likelihood', mu=mu, tau=matrix_inverse(cov_matrix), observed=dataset)` not `like = MvNormal('likelihood', mu=mu, cov=cov_matrix, observed=dataset)`

The example fails as it stands.

**Comment by springcoil** [comment]
Fancy doing a PR?

**Comment by twiecki** [comment]
It works on my end. Requires https://github.com/pymc-devs/pymc3/pull/1398.
