### ISSUE TITLE
BUG clip effective sample size at maximum number of samples

### ISSUE THREAD

**Issue by beckermr** [pymc-devs/pymc#1413]
It appears that the effective sample size is allowed to be greater than the number of samples taken here: https://github.com/pymc-devs/pymc3/blob/master/pymc3/diagnostics.py#L262.

For noisy autocorr. estimates, maybe this should be clipped at the maximum number of samples like this:

``` python
return min(n * m, int(m * n / (1. + 2 * rho[1:t].sum())))
```

?

**Comment by ColCarroll** [comment]
Is that true?  I think rho is provably positive (not against this change!  seems like a reasonable and cheap check.  just curious now...)

**Comment by ColCarroll** [comment]
Never mind, think I worked out such a situation!  Looks good to me!
