### ISSUE TITLE
Can BinaryGibbsMetropolis be generalized to provide a better implementation of ElemwiseCategorical?

### ISSUE THREAD

**Issue by ozankabak** [pymc-devs/pymc#1431]
I have a high-dimensional (around 1000) vector variable that consists of categorical r.v.s with small support (i.e. k is a small single-digit number). This vector variable takes part in various calculations to produce a custom likelihood.

By default, the system assigns `ElemwiseCategorical` as this variable's sampler. Unfortunately, this sampler does not work for me, as I perform various operations like indexing which `ElemwiseCategorical` does not support.

As a workaround, I tried defining my variable as a vector of `DiscreteUniform` r.v.s, and chose `Metropolis` as my sampler. However, this does not work well.  Even though I compute a 50000-long chain, the variable never transitions from its initial state to some other state.

I have previously worked with such high-dimensional vector variables whose components were binary instead of categorical. In that case, the sampler `BinaryGibbsMetropolis` worked pretty well. For that reason, I was wondering if it is possible to re-write `ElemwiseCategorical` using `BinaryGibbsMetropolis` as a starting point? If there is no technical reason that makes this a non-sensible proposition, I can help with this effort if given some guidance and direction.

I am also interested in hearing about other possible workarounds that can help dealing with my problem. Thanks!

**Comment by twiecki** [comment]
@wanderer2 Yes, that makes a lot of sense. I suppose it makes most sense to refactor `BinaryGibbsMetropolis` to `CategoricalGibbsMetropolis` and binary is just a special case of n_categories=2. The key is to not block-update all elements at the same time which is what `BinaryGibbsMetropolis` does.

**Comment by ozankabak** [comment]
Thanks for prompt response @twiecki. Looking at the definition of `BinaryGibbsMetropolis`, I see the following loop in the `astep` method:

```
for idx in order:
    q_prop[idx] = True - q_prop[idx]
    q_cur = metrop_select(logp(q_prop) - logp(q_cur), q_prop, q_cur)
    q_prop = copy(q_cur)
```

I am a new user of PyMC, and have not spent significant time looking at its code (yet!). However, this seems to me like it is updating each element sequentially already, not blockwise. Am I getting this wrong?

If the above is correct, all we would need to do is to fix (i.e. generalize) this loop. Does this make sense?

**Comment by twiecki** [comment]
Yes, that's what we want. Sequentially, not block-wise.

**Comment by twiecki** [comment]
I think you just need to make `q_prop` sample from a categorical to make it work.

**Comment by ozankabak** [comment]
Hi @twiecki. I implemented `CategoricalGibbsMetropolis` according to our discussions. As a bonus to what we have discussed, this sampler is able to use both uniform and proportional proposals (discussed in [Liu96](http://www.fas.harvard.edu/~junliu/TechRept/96folder/mgibbs.ps)).

**Comment by ozankabak** [comment]
The PR has merged, so closing this issue.
