### ISSUE TITLE
how to combine chains?

### ISSUE THREAD

**Issue by nye17** [pymc-devs/pymc#144]
Hi,

Is there an easy way within PyMC to combine chains of separate chains? For example, I now have 10 independent txt databases that sample the same sets of posteriors, how can I combine them into a single a "pymc.database.txt.Database" object? Thanks!

**Comment by fonnesbeck** [comment]
You can access all 10 chains at once, and your Model.db object should have an index to access each of them. If you want to deal with a single long chain, you can do so by passing `chain=None` to the `trace` method:

```
In [3]: from pymc.examples import gelman_bioassay

In [4]: from pymc import *

In [5]: M = MCMC(gelman_bioassay, db='txt')

In [6]: M.sample(1000)
[****************100%******************]  1000 of 1000 complete

In [7]: M.sample(1000)
[****************100%******************]  1000 of 1000 complete

In [8]: len(M.trace('alpha',chain=None)[:])
Out[8]: 2000
```

**Comment by nye17** [comment]
Thanks! but this is assuming that the model retains its memory of all the independent samplings, right? my 10 databases are all txt dbs on my harddrive that can only be loaded without awareness of their parent models. Right now what I am doing is to concatenate the scattered chain files into a single file and then load into one database...kinda tedious but gets the job done.

**Comment by fonnesbeck** [comment]
You should be able to load those back into Database object pretty easily:

```
In [1]: from pymc import *

In [2]: from pymc.examples import gelman_bioassay

In [3]: db = database.txt.load("MCMC.txt")

In [4]: M = MCMC(gelman_bioassay, db=db)

In [5]: len(M.trace('alpha', chain=None)[:])
Out[5]: 2000

In [6]: db
Out[6]: <pymc.database.txt.Database at 0x10b597b10>
```

**Comment by nye17** [comment]
I see. Mine is a bit different - I ran them independently from different MCMC models, so the txt db file structure is like: run0/Chain0/, run1/Chain0/, ... run9/Chain0. From your example it seems that I can simply move all the "Chain0" subdirectories into the same "run" main diretory as Chain0, Chain1, ... Chain9, and then load the "run" directory as one database using "chain=None". Thanks!

**Comment by fonnesbeck** [comment]
That may work. In your case, I would have chosen the sqlite back end, so that you end up with a sqlite file that can be used anywhere, independently of PyMC.

**Comment by nye17** [comment]
wait, why does saving with sqlite backend help here?

**Comment by fonnesbeck** [comment]
Because, rather than saving traces as a collection of text files, it saves them all to a single sqlite database file indexed by trace number. This database can be accessed via the sqlite library in Python, or any other sqlite module in any environment.

**Comment by nye17** [comment]
I see, I'll try to play with sqlite backend. using txt is easy and straightforward at the beginning, but now it seems getting a bit clunky when the chain number and size grow. Thanks!

**Comment by zeneofa** [comment]
Hi, sorry if this is not the right place or way to ask this. How can the above work if the database is pickled? I have separate runs individually pickled: 'chain1.pickle, chain2.pickle, chain3.pickle' . I would like to combine them in one pymc object so that I can test them with gelman-rubin (unfortunately the chains are quite computationally intensive to generate so rerunning them is not currently possible :( ).

**Comment by fonnesbeck** [comment]
@zeneofa You should not have to manually recombine them:

```
In [1]: from pymc.examples import gelman_bioassay

In [2]: from pymc import *

In [3]: M = MCMC(gelman_bioassay, db='pickle')

In [4]: M.sample(1000)
 [-----------------100%-----------------] 1000 of 1000 complete in 0.2 sec
In [5]: M.sample(1000)
 [-----------------100%-----------------] 1000 of 1000 complete in 0.2 sec
In [6]: gelman_rubin(M)
Out[6]: 
{'LD50': 0.99919105722496693,
 'alpha': 1.0372790737845003,
 'beta': 1.0256964395833315,
 'theta': [1.0019206167151251,
  0.99903249663997129,
  1.0068999425247782,
  1.0042359203490188]}
```

**Comment by fonnesbeck** [comment]
@zeneofa Oh, I see what you've done -- you had _completely_ separate runs saved to different pickle databases. You should be able to reconstruct them via `pymc.database.pickle.load`. Here is an example:

```
In [48]: db = database.pickle.load("MCMC.pickle")

In [49]: db2 = database.pickle.load("MCMC2.pickle")

In [50]: traces1 = [db.trace('alpha', chain=i)[:] for i in range(db.chains)]

In [51]: traces2 = [db2.trace('alpha', chain=i)[:] for i in range(db2.chains)]

In [52]: gelman_rubin(traces1+traces2)
Out[52]: 1.0278078281197147
```

If there is only one chain in each pickle, then it is even easier.
