### ISSUE TITLE
Model comparion 

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#1443]
I found that the example in the notebook [Model Comparison](https://github.com/pymc-devs/pymc3/blob/2e62ba366a2c2e654241fa406919aa0471646ec8/docs/source/notebooks/Model%20Comparison.ipynb) does not work for loo. the problem is related to the `ValuerError` when the variance is larger than 0.7. Maybe this error should be just a warning.

**Comment by springcoil** [comment]
Do you want to change that to a warning? It's recommended in the literature that you change your model though when the variance is larger than 0.7...

**Comment by aloctavodia** [comment]
Probably I should re-read the literature (there are several similar papers out there), but I understood the 0.5-0.7 point as a roughly empirical estimation of when loo could fail, not as a hard cut-off value. I have the impression that better diagnostics are needed to be more confident about when we should distrusts  waic or loo. In summary, I think an error is too harsh and a warning is a better choice. 

Anyway, if you don't think the same, then I think the example should be changed for another that works for loo.

**Comment by twiecki** [comment]
Agreed with @aloctavodia, warning is probably better.

**Comment by springcoil** [comment]
Yeah that seems fair @aloctavodia I interpreted it as a hard cutoff but you're right it's a guideline. And other diagnostic are needed :) Care to do a PR?

**Comment by aloctavodia** [comment]
Sure, I guess I can add it to my pending PR, given that they are both related.

**Comment by springcoil** [comment]
Yeah sure man :)
