### ISSUE TITLE
Add documentation on running tests and building docs

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1444]
Just want to comment here that I'm working on making sure example notebooks run smoothly.  I'm not familiar with a best practice for notebooks in a repo -- let me know if there are specifics with how to run them before committing (i.e., should stderr be suppressed?)

**Comment by twiecki** [comment]
What's your plan? I think it's definitely a good idea to use e.g. `runipy` in the standard test-suite that all NBs are not raising exceptions.

**Comment by ColCarroll** [comment]
Haven't seen `runipy` before -- that definitely looks helpful.  I don't think running all the examples would be good for the test suite -- haven't tried, but I'd guess running them serially would take ~2hrs.  Perhaps just wrapping that functionality into a script?  

It would be good to have a document (or [add a section](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md)) with instructions on 
1. Setting up a dev environment
2. Running the tests locally
3. Generating the docs (this may include re-running notebooks, or maybe that's a separate step)

I'm not sure how to do #3, though.

**Comment by twiecki** [comment]
I don't anticipate us re-running the NBs all that often so probably not worth productizing that. But certainly 1-3 would be useful documentation.
