### ISSUE TITLE
Bad initial scaling in 'getting started' notebook

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1448]
In the "Stochastic volatility" model (https://pymc-devs.github.io/pymc3/notebooks/getting_started.html at `In [17]`) NUTS is initialized with `scaling=sp500_model.dict_to_array(sds)`, where the standard diviations are estimated using advi. Shouldn't this use the variance instead?

**Comment by twiecki** [comment]
Yes, absolutely.
