### ISSUE TITLE
Equation not rendering in notebook example about PMF

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#1453]
The following equation
`E = \frac{1}{2} \sum_{i=1}^N \sum_{j=1}^M I_{ij} (R_{ij} - U_i V_j^T)^2 + \frac{\lambda_U}{2} \sum_{i=1}^N \|U\|_{Fro}^2 + \frac{\lambda_V}{2} \sum_{j=1}^M \|V\|_{Fro}^2,`

under cell [8] of the notebook example on PMF does not render.

**Comment by fonnesbeck** [comment]
Can anyone else reproduce this? I cannot.

**Comment by ColCarroll** [comment]
Works fine for me and on github, though it looks like github's parser is
having trouble with the command defined below cell [7] in the notebook:
"$\newcommand\given[1][]{:#1\vert:}$".
https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/pmf-pymc.ipynb
