### ISSUE TITLE
Unable to calibrate mean, std_dev for Gaussian regime switch

### ISSUE THREAD

**Issue by sumituk1** [pymc-devs/pymc#1460]
Hi;

   I am trying to run the code below where , given the data, I am trying to calibrate 2 Normal distribution to fit the data.

  However, when I run the pm.sample, I get a error message:-
Assigned Metropolis to tau
  0%|          | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Sumit Sengupta\Anaconda3\lib\site-packages\theano\gof\vm.py", line 293, in **call**
    thunk()
  File "C:\Users\Sumit Sengupta\Anaconda3\lib\site-packages\theano\gof\op.py", line 912, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Users\Sumit Sengupta\Anaconda3\lib\site-packages\theano\tensor\elemwise.py", line 861, in perform
    raise ValueError(base_exc_str)
ValueError: Dimension mismatch; shapes are (1), (_), (1), (74), (_), (74), (1), (1), (1), (*)

During handling of the above exception, another exception occurred:

Code below. Please can you help?

Regards;
Sumit
# ==================   source code ===============

`import pymc3 as pm
import numpy as np
from pymc3.math import switch
import theano
from matplotlib import pyplot as plt
import pandas as pd
from scipy import optimize
from interpolate_marketdata import *
import theano.tensor as T
N_sims = 1000

data = [13,24,8,24,7,35,14,11,15,11,22,22,11,57,
        11,19,29,6,19,12,22,12,18,72,32,9,7,13,19,
        23,27,20,6,17,13,10,14,6,16,15,7,2,15,15,19,
        70,49,7,53,22,21,31,19,11,18,20,12,35,17,23,
        17,4,2,31,30,13,27,0,39,37,5,14,13,22]

""" detect any regime change in factors 2 & 3 """
n_count_data = len(data)
basic_model = pm.Model()

with basic_model:
    mu_1 = pm.Normal('mu_1', mu=0, sd=10, shape=1)
    mu_2 = pm.Normal('mu_2', mu=0, sd=10, shape=1)
    sd = pm.HalfNormal('sd', sd=1, shape=1)
    # sigma_2 = pm.HalfNormal('sigma_2', sd=1, shape=1)
    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)

```
mu1_print = T.printing.Print('mu_1')(mu_1)
mu2_print = T.printing.Print('mu_2')(mu_2)
sd_print = T.printing.Print('sd')(sd)

idx = np.arange(n_count_data)
mu_ = switch(tau >= idx, mu_1, mu_2)
# observed data can be a ndarray or a pandas dataframe
obs = pm.Normal('obs', mu=mu_, sd=sd, observed=data)
# obtain starting values via MAP
start = pm.find_MAP(fmin=optimize.fmin_powell)
step=pm.NUTS()
trace = pm.sample(N_sims,step,progressbar=True,start=start)
```

""" get samples from posterior distribution """
pm.traceplot(trace)
plt.show()`

**Comment by twiecki** [comment]
Can you format the code better?

**Comment by sumituk1** [comment]
[test2.zip](https://github.com/pymc-devs/pymc3/files/537244/test2.zip)

Hi;

   I am uploading the file in zip format. Please let me know if you can see the code correctly now.

**Comment by twiecki** [comment]
Best to post a notebook as a gist, or do proper markdown above.

**Comment by sumituk1** [comment]
Can you please check? I updated the source code by clicking on "Insert code"

**Comment by sumituk1** [comment]
https://gist.github.com/sumituk1/509b99f0303110a8cf57952638e4a566

**Comment by sumituk1** [comment]
hoping the above pyMC3 code above is close to producing results using:-
http://blogs.mathworks.com/pick/2011/02/25/markov-regime-switching-models-in-matlab/

**Comment by sumituk1** [comment]
Please let me know if there's anything else you need.

**Comment by ColCarroll** [comment]
Hi @sumituk1 -- 
the example runs if you do not specify the shape arguments (as theano will infer the correct shape for the variables).  Here's a version that runs in a jupyter notebook, though you'll have to mess with it to recreate the matlab example:

```
import pymc3 as pm
import numpy as np
from pymc3.math import switch
from matplotlib import pyplot as plt
%matplotlib inline
from scipy import optimize
N_sims = 1000

data = [13, 24, 8, 24, 7, 35, 14, 11, 15, 11, 22, 22, 11, 57,
        11, 19, 29, 6, 19, 12, 22, 12, 18, 72, 32, 9, 7, 13, 19,
        23, 27, 20, 6, 17, 13, 10, 14, 6, 16, 15, 7, 2, 15, 15, 19,
        70, 49, 7, 53, 22, 21, 31, 19, 11, 18, 20, 12, 35, 17, 23,
        17, 4, 2, 31, 30, 13, 27, 0, 39, 37, 5, 14, 13, 22]

with pm.Model():
    mu_1 = pm.Normal('mu_1', mu=0, sd=10)
    mu_2 = pm.Normal('mu_2', mu=0, sd=10)
    sigma_1 = pm.HalfNormal('sigma_1', sd=1)
    sigma_2 = pm.HalfNormal('sigma_2', sd=1)

    tau = pm.DiscreteUniform("tau", lower=0, upper=len(data))

    idx = np.arange(len(data))
    mu_ = switch(tau >= idx, mu_1, mu_2)
    sigma_ = switch(tau >= idx, sigma_1, sigma_2)

    # observed data can be a ndarray or a pandas dataframe
    obs = pm.Normal('obs', mu=mu_, sd=sigma_, observed=data)
    # obtain starting values via MAP
    start = pm.find_MAP(fmin=optimize.fmin_powell)
    step = pm.NUTS()
    trace = pm.sample(N_sims, step=step, progressbar=True, start=start)

pm.traceplot(trace)
```

**Comment by sumituk1** [comment]
Thanks a lot.
