### ISSUE TITLE
commonmark dependency

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#1467]
ping: @fonnesbeck @twiecki @jsalvatier

Just wondering about the commonmark dependency - does it absolutely have to be `<=0.5.4`? I'm looking to build the "full" PyMC3 on conda-forge, including the docs.

**Comment by ericmjl** [comment]
My bad, I wasn't thinking straight when I posted here. I'm actually supposed to ask on the recommonmark repo, not here. _sheepish_

**Comment by twiecki** [comment]
I bet it can be relaxed.
