### ISSUE TITLE
Error reproducing AEVB-ADVI in Python 3

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1471]
I get an error related to lists and the return of zips in Python 3 here.
https://gist.github.com/springcoil/5d8294ba6fd9638facc539f7a7d54b9d

cc @taku-y did you only test this with python2.7?

**Comment by taku-y** [comment]
Thanks for reporting. I tested on Python3.5. I will check the program.

**Comment by taku-y** [comment]
The notebook docs/source/notebooks/lda-advi-aevb.ipynb worked with the latest PyMC3 code. So I will check your notebook.

**Comment by springcoil** [comment]
Seems to just be an error of my setup. Thanks though :)

**Comment by taku-y** [comment]
Look forward to your documentation!

**Comment by christacular** [comment]
Hi @taku-y and @springcoil , can you tell me if you're still able to run [this](http://pymc-devs.github.io/pymc3/notebooks/lda-advi-aevb.html) example successfully?  I'm getting an error both for the official document and @springcoil, your [Gist](https://gist.github.com/springcoil/5d8294ba6fd9638facc539f7a7d54b9d).  I'm using  Theano-0.9.0b1 and PyMC3 3.0, which should be the latest versions of both.

> Exception: ('The following error happened while compiling the node', Elemwise{Composite{(i0 * (i1 - sqr(i2)))}}[(0, 0)](Dot22.0, TensorConstant{(1L, 1L) of 1.0}, Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)].0), '\n', "Compilation failed (return status=1): C:\\Users\\chrissc\\AppData\\Local\\Temp\\ccZ3Vvk8.s: Assembler messages:\r. C:\\Users\\chrissc\\AppData\\Local\\Temp\\ccZ3Vvk8.s:4292: Error: no such instruction: `vfnmadd312sd (%rax),%xmm0,%xmm0'\r. C:\\Users\\chrissc\\AppData\\Local\\Temp\\ccZ3Vvk8.s:4495: Error: no such instruction: `vfnmadd312sd (%r9),%xmm0,%xmm0'\r. ", '[Elemwise{Composite{(i0 * (i1 - sqr(i2)))}}[(0, 0)](<TensorType(float64, matrix)>, TensorConstant{(1L, 1L) of 1.0}, <TensorType(float64, matrix)>)]')

When I try and run with the CPU

ValueError: ('The following error happened while compiling the node', Elemwise{Composite{(i0 * (i1 - sqr(i2)))}}[(0, 0)](Dot22.0, TensorConstant{(1L, 1L) of 1.0}, Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)].0), '\n', 'I/O operation on closed file', '[Elemwise{Composite{(i0 * (i1 - sqr(i2)))}}[(0, 0)](<TensorType(float64, matrix)>, TensorConstant{(1L, 1L) of 1.0}, <TensorType(float64, matrix)>)]')

**Comment by taku-y** [comment]
Hi @christacular It was able to run the notebook with theano-0.9.0beta1 and PyMC3 3.0 on Docker. How about using Docker?
