### ISSUE TITLE
Feature request - example of SDE

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1480]
CC @maedoc did you ever have an opportunity to write a notebook for this?

I tried myself but I wasn't able to get an example working... 

Maybe this should go on the mailing list rather than here - any suggestions @fonnesbeck?

**Comment by maedoc** [comment]
I can do a small example but my usual applications are pretty big for a
pedagogical notebook so any good examples beyond a linear SDE would be
welcome.

**Comment by springcoil** [comment]
If you can get a linear SDE up and running, I'm sure I can extend it.

**Comment by maedoc** [comment]
OK will do asap.

**Comment by maedoc** [comment]
@springcoil close this issue?

Also, I was thinking of adding some of the more advanced schemes like Milstein or even local linearization (based on matrix exponential) but not sure if there's interest in seeing those here? Or if Theano would support that stuff? What's a good place for that discussion?

**Comment by springcoil** [comment]
I guess open another issue. You can share WIP
