### ISSUE TITLE
Unexpected behavior of `logp` method.

### ISSUE THREAD

**Issue by fredcallaway** [pymc-devs/pymc#1487]
I'm sure this behavior is expected by the devs, but the documentation doesn't make it clear to me what's going on. Here's a minimal example:

```python
s0 = pymc3.Categorical('s0', p=np.array([0.3, 0.3, 0.6]))
sample = s0.random(size=5)
print(sample)
print(s0.logp(sample))  # exception
```

**Traceback:**

```
TypeError                                 Traceback (most recent call last)
<ipython-input-154-16afbc73e9b8> in <module>()
      5     sample = s0.random(size=5)
      6     print(sample)
----> 7     print(s0.logp(sample))
      8 

/usr/local/lib/miniconda3/lib/python3.5/site-packages/pymc3/model.py in __call__(self, *args, **kwargs)
    483 
    484     def __call__(self, *args, **kwargs):
--> 485         point = Point(model=self.model, *args, **kwargs)
    486         return self.f(**point)
    487 

/usr/local/lib/miniconda3/lib/python3.5/site-packages/pymc3/model.py in Point(*args, **kwargs)
    459     except Exception as e:
    460         raise TypeError(
--> 461             "can't turn {} and {} into a dict. {}".format(args, kwargs, e))
    462     return dict((str(k), np.array(v)) for k, v in d.items()
    463                 if str(k) in map(str, model.vars))

TypeError: can't turn [array([2, 2, 0, 2, 2])] and {} into a dict. cannot convert dictionary update sequence element #0 to a sequence
```
My actual use case is constructing a custom distribution where I use the `logp` of a `Dirichlet` to calculate the `lop` of my distribution. I'd be very grateful for any help--I've struggled with this for hours!

**Comment by fonnesbeck** [comment]
The following should work:

``` python
with pymc3.Model() as mod:
    s0 = pymc3.Categorical('s0', p=np.array([0.3, 0.3, 0.6]), shape=5)

sample = s0.random(size=5)
s0.logp({'s0':sample})

```

This isn't in the docs because it isn't really user-facing functionality (we don't intend most users to call `logp` manually), but we probably should have an "advanced programming guide" of some sort.

To use the `logp` the way you are attempting to, you'd want to just use the distribution, rather than the PyMC variable. That is:

``` python
cat = pymc3.Categorical.dist(p=np.array([0.3, 0.3, 0.6]))
cat.logp(sample).tag.test_value
```

**Comment by fredcallaway** [comment]
The first one didn't work immediately (3.0.rc2 downloaded from pip). I got it to work by removing the `size=5` argument to `random`.  Additionally, if I want to sample a single value, I need to set `shape=1` or index the single value out of random which always returns an array. With no shape argument, the distribution expects 0d values. 

The second works great, however the syntax is pretty awkward compared to pymc(2). Maybe a utility method would be appropriate in this situation?

Thanks for the help!

**Comment by fonnesbeck** [comment]
What is it that you are trying to do? The first case (using the Categorical variable itself) is not really intended to be used by the user; in the second case, you are simply using the raw distribution (hence, the `dist` method without the variable attributes. Neither of these would be used very often inside of a PyMC model, so it would be helpful to know what your goal is.

[This notebook](https://github.com/fonnesbeck/Bios8366/blob/master/notebooks/Section4_5-Model-Building-with-PyMC3.ipynb) from my graduate course may be a helpful reference for you.

**Comment by fredcallaway** [comment]
Sorry for the slow response time. I'm trying to write an HMM. I was able to get the transition matrix done with your suggestion: 

https://gist.github.com/fredcallaway/1903a395f9118323de8a1a02e40492f4

That notebook was very helpful indeed! I found it to be concise and broadly informative compared to other tutorials I've found. You should include it in the documentation!

**Comment by twiecki** [comment]
@fredcallaway that's really cool. interested in submitting an example notebook that demonstrates HMMs in pymc3?

**Comment by fredcallaway** [comment]
@twiecki Unfortunately, I haven't been able to get it to work. I was attempting to port from a pymc (2) implementation, which I just realized is the work of @fonnesbeck .

The problem seems to be that the values considered for the `StochasticMatrix` are not dirchlet distributed. I assumed that the `random()` method would be used to generate these values, but this appears to not be the case.

**Comment by twiecki** [comment]
Right, the values are provided by the sampler which does not know about your sum-to-1 constraint. This is where transformations come in, like the stick-breaking we do for dirichlet. Couldn't you create a 2D dirichlet distribution matrix for your transition matrix?
