### ISSUE TITLE
Advanced programming guide

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1488]
To augment the documentation, we should have an advanced programming guide for those who wish to develop and use the more esoteric features of PyMC3 (e.g. using the variable `logp` method directly as in #1487). This could be a chapter on the existing docs, or a separate document.

**Comment by springcoil** [comment]
I'll jot down some ideas:
- [ ] How to use logp
- [ ] How to use the switch statement

**Comment by fredcallaway** [comment]
Request: Switching between more than two options. (e.g. using an RV to index a list of distributions)
