### ISSUE TITLE
Errors on theano master

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1496]
Want to mark this as an issue I'm looking at -- currently we're pinned to the latest stable release (#1494), and I opened an issue over at https://github.com/Theano/Theano/issues/5171, though it isn't clear it is a bug on their end yet.  There's a distressingly small example that breaks when using `theano==0.9.0.dev4`: 

```
import pymc3 as pm
with pm.Model() as model:
    p = pm.Beta('p', alpha=1, beta=1)
    trace = pm.sample(100)

...
TypeError: Elemwise{mul,no_inplace}.grad illegally  returned an integer-valued variable. (Input index 1, dtype bool)

```

**Comment by peadar-elevate** [comment]
Ohh that's disturbing

**Comment by abergeron** [comment]
This should fix the problem: https://github.com/Theano/Theano/pull/5175

**Comment by Spaak** [comment]
Can confirm that abergeron's commit fixes the issue, thanks!

**Comment by ColCarroll** [comment]
#1508 -- thanks @abergeron !
