### ISSUE TITLE
Exhaustive Hamiltonian Monte Carlo 

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1497]
I'm just bringing Exhaustive Hamiltonian Monte Carlo (XMC), as detailed [here](https://arxiv.org/pdf/1601.00225.pdf), to attention of the PyMC3 devs. Seems a fair bit more efficient than NUTS, and could be a good addition to PyMC3!

**Comment by twiecki** [comment]
That looks really neat, thanks for sharing. I wonder if they are using that in STAN.

**Comment by fonnesbeck** [comment]
Apparently they are but have not yet exposed it.

**Comment by twiecki** [comment]
https://github.com/stan-dev/stan/pull/1859 is the PR.

**Comment by twiecki** [comment]
Took a look at the paper, doesn't seem like the numerical experiments suggest that it's really better than NUTS (only in select cases). Thus, I'm not sure we should jump on this right now as the upside does not seem all that big. But maybe I misread that, @betanalpha?

**Comment by betanalpha** [comment]
XHMC introduces an additional tuning parameter and an automated
procedure for setting that parameter is still an active topic of research.
