### ISSUE TITLE
Training same parameters in different datasets

### ISSUE THREAD

**Issue by jianqiaozhu** [pymc-devs/pymc#1498]
Say I have a model containing 3 parameters (**_a,b,c_**) and there are 2 available datasets (**D1,D2**).
However, not all of the parameters should be used to predict all the data.

For instance, the model would only use parameters **_a_** and **_b_** to fit dataset **_D1_**, and only **_b_** and **_c_** are going to predict dataset **_D2_**.

How can I achieve tasks as such in PyMC3? It would be great if you can support me with some existing modeling practices as well. 

Thank you.

**Comment by twiecki** [comment]
You could build one model with two observeds (for D1 and D2), link up the parameters as you see fit (a&b and b&c). Closing but feel free to keep asking questions.
