### ISSUE TITLE
Submitting PR for BEST as a "default model"

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#1502]
Hi PyMC devs!

I'd like to explore what would be the value of "default" models in PyMC3 here.

I looked through the BEST model, and after thinking through it, I did a bit of software tweaks to extend it from a two-treatment comparison to multi-treatment. I like the BEST model, because it applies quite nicely in the life sciences, particularly when we don't necessarily have good underlying theory for describing the data generation process.

Seeing how the GLM module sort of acts like a nice "default" model in PyMC3, would there be value in adding a multi-treatment BEST model as another "default" model? I think having "default" models present, and an example of how to structure the data to bring it into the model, would be a good way to help with the adoption of PyMC3 and Bayesian methods.

I have wrapped my own "default model" for high throughput measurements in a [Python script][htbayes], which I think is equivalent to multi-treatment comparison; I'd also love to see if I've made any mistakes in implementing it, or if I'm making a noob-ish fundamental (theoretical) mistake!

[htbayes]: https://github.com/ericmjl/bayesian-measurement-paper/blob/master/htbayes.py

**Comment by twiecki** [comment]
I completely agree. Currently pymc3 is just a toolbox to build models but certainly it would be helpful to already have pre-existing models that can be used out of the box. Maybe either in a separate repo or maybe as a `modules` submodule. Maybe also apply the sklearn API which is pretty nice. Want to do a PR?

**Comment by ericmjl** [comment]
Happy to work on it! :smile:

**Comment by ericmjl** [comment]
@twiecki PR #1517 is submitted! Please let me know what you think about the API design and the notebook. I'm happy to make changes if needed. 

I took your suggestion on the scikit-learn-ish API, and provided a `.fit()` and a `.plot_posterior()` function, which I think can be "standard" API calls for default models.

**Comment by twiecki** [comment]
Closing in favor of #1517.
