### ISSUE TITLE
Getting errors on Convolutional VAE notebook

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1503]
Here is my gist https://gist.github.com/springcoil/ea1683d8063a067d1ba4ce1ddf3e66cf of my Conda .yml file. 

https://gist.github.com/springcoil/ad78bea36f022b1b08f757642acda387 is my output. I've got nans in this.

cc @fonnesbeck @ColCarroll @taku-y

**Comment by ColCarroll** [comment]
Interesting!  It actually runs fine for me.  I can check for version mismatches, but I wonder if you could rerun the notebook against master (the notebook lists that it is pip installed).  If you start a notebook server in the top folder of the project with master checked out using

```
PYTHONPATH=`pwd`:$PYTHONPATH python -m jupyter notebook
```

It may work (which would mean next release will fix it).  I'll poke around other library changes otherwise.

**Comment by ColCarroll** [comment]
Here's my [env.yaml](https://gist.github.com/ColCarroll/1ef3eb2b98deaa2b84b678ec6d5fb2eb), if you're interested.

**Comment by taku-y** [comment]
I've also got nan with Theano 0.8.2, but ran with Theano 0.9.0dev3.

**Comment by ColCarroll** [comment]
Ah, super interesting -- I guess it'll be fixed once theano merges their change and we unpin.  @taku-y do you happen to know what the offending change is?

**Comment by peadar-elevate** [comment]
I got the same result as @taku-y it works with Theano O.9.0dev3

**Comment by taku-y** [comment]
@ColCarroll I didn't notice this problem was related to theano. I will check the changes in theano from 0.8.2 to 0.9.

**Comment by ColCarroll** [comment]
It'd be interesting to know, but the theano PR is approved, so we should be on 0.9.x again soon.

**Comment by springcoil** [comment]
I'm closing this. However let us consider this a record of this bug.

**Comment by fgadaleta** [comment]
Successfully installed **Theano-0.9.0b1**
Code in convolutional_vae_keras_advi fails with 

`ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 64, 14, 14), but the given topgrad has shape (200, 64, 14, 14)
`

from the Decoder layers

**Comment by taku-y** [comment]
Thanks for your report. I got the same error. I will check the CVAE code.

**Comment by springcoil** [comment]
Is this some sort of numerical instability Taku? I'm confused about what's breaking.

**Comment by taku-y** [comment]
@springcoil No, it's just a careless mistake. I fixed it and running the notebook to check the result.

**Comment by taku-y** [comment]
@worldofpiggy I fixed a bug in the notebook. See [the updated notebook](https://github.com/taku-y/pymc3/blob/fix_cvae_notebook/docs/source/notebooks/convolutional_vae_keras_advi.ipynb).
