### ISSUE TITLE
HamiltonianMC broken?

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1510]
Was using a modified test script from #1421 and, even on master, I get obviously wrong traces from HMC.  There are some common sense checks in the test suite now that continue to pass.

[Here's the gist](https://gist.github.com/ColCarroll/158abc7c0cb51ff1cf9cd4b9a9ea47b9) that I'm running -- I'm checking for any obvious problems...

**Comment by ColCarroll** [comment]
Sigh... poorly initialized step size.  Converges fine if the HamiltonianMC `path_length` is set to 40.

**Comment by twiecki** [comment]
good you figured it out. we really need to review the init code.
