### ISSUE TITLE
AttributeError: module 'pymc3' has no attribute 'NormalMixture'

### ISSUE THREAD

**Issue by rrrafet** [pymc-devs/pymc#1511]
The example on mixture produces the error in the title when running on MacOS Sierra (same code works in Windows)

from matplotlib import pyplot as plt
import numpy as np
import pymc3 as pm
import seaborn as sns

SEED = 383561

np.random.seed(SEED) # from random.org, for reproducibility

N = 1000

W = np.array([0.35, 0.4, 0.25])

MU = np.array([0., 2., 5.])
SIGMA = np.array([0.5, 0.5, 1.])

component = np.random.choice(MU.size, size=N, p=W)
x = np.random.normal(MU[component], SIGMA[component], size=N)

ig, ax = plt.subplots(figsize=(8, 6))

ax.hist(x, bins=30, normed=True, lw=0);

with pm.Model() as model:
    w = pm.Dirichlet('w', np.ones_like(W))

    mu = pm.Normal('mu', 0., 10., shape=W.size)
    tau = pm.Gamma('tau', 1., 1., shape=W.size)

    x_obs = pm.NormalMixture('x_obs', w, mu, tau=tau, observed=x)

with model:
    step = pm.Metropolis()
    trace_ = pm.sample(20000, step, random_seed=SEED)

trace = trace_[10000::10]

**Comment by rrrafet** [comment]
Hm, found the issue. The conda forge repo does not come with distributions/mixture.py

**Comment by twiecki** [comment]
Yeah, that's later than 3.0.rc2
