### ISSUE TITLE
transfer ndarray to trace in pymc3

### ISSUE THREAD

**Issue by MingjunZhong** [pymc-devs/pymc#1521]
I have a sampler for drawing samples from a distribution; the samples are in an ndarray. I want to compute the ESS using pymc3, but the input of the method effective_n() needs to be a `trace'. 
I thus wondering how to transform ndarray to trace? I can then use the methods in pymc3.
Thanks,

**Comment by fonnesbeck** [comment]
There currently is not a way of creating a `Trace` from an array, as it was not meant to be used that way, but I'll bet a `trace_from_array` function could be written. Feel free to give it a try. Alternatively, you could take the `effective_n` code and convert it yourself to a more general one that accepts arrays.

**Comment by MingjunZhong** [comment]
@fonnesbeck Any clues to write a trace_from_array function? I am new to PyMC.

**Comment by fonnesbeck** [comment]
Your best strategy, then, might be to strip out all the trace handling in our function and just pass arrays. [This](https://gist.github.com/fonnesbeck/0f51d0fcb5c0cb29a32b2aca0ca3dfd4) should get you most of the way there. It accepts  dictionary with the variable name as the key and an array as the value. HTH.
