### ISSUE TITLE
Reduce default number of ADVI iterations for initialization

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1540]
500K iterations seems excessive when using ADVI to find starting values for MCMC. I propose cutting it to less than half of that. Thoughts?

**Comment by ColCarroll** [comment]
Agree, though I don't know if there is a good rule of thumb for this.

**Comment by twiecki** [comment]
Yeah, I had the same concern. Ideally we'd just run until convergence but for now can half it.
