### ISSUE TITLE
ZeroInflatedPoisson doesn't infer anything about psi

### ISSUE THREAD

**Issue by DanielWeitzenfeld** [pymc-devs/pymc#1544]
`ZeroInflatedPoisson` seems to not be working, based on this toy dataset:

```python
import pymc3 as pm
import numpy as np

N = 300

percent_nonzero = .6
p_nonzero = np.repeat(percent_nonzero, N)
is_non_zero = np.random.random(size=N) < p_nonzero

rate = 3
observed = np.random.poisson(rate, N)
observed[~is_non_zero] = 0

with pm.Model() as model:
    psi = pm.Beta('psi', 1, 1, testval=percent_nonzero)
    theta = pm.Uniform('theta', 0, 100, testval=1.0*rate)
    yd = pm.ZeroInflatedPoisson('y', theta, psi, observed=observed)
    trace = pm.sample(2000)

_ = pm.traceplot(trace)
```

![unknown-12](https://cloud.githubusercontent.com/assets/834290/20535165/cfcf3540-b0b1-11e6-83c4-6ffbb6455a50.png)

**Comment by DanielWeitzenfeld** [comment]
![unknown-12](https://cloud.githubusercontent.com/assets/834290/20535399/8feac1e6-b0b2-11e6-8316-13eb102dc763.png)

**Comment by twiecki** [comment]
Can you try with this PR from @AustinRochford: https://github.com/pymc-devs/pymc3/pull/1459?

**Comment by aloctavodia** [comment]
I am not able to reproduce the error

![index](https://cloud.githubusercontent.com/assets/1338958/20544564/76fd83d0-b0e9-11e6-89f3-5155bc9daf9f.png)

**Comment by DanielWeitzenfeld** [comment]
It works with `3.0.rc2`, sorry about that. I thought I was on the most up-to-date version because I ran `pip install pymc3 --upgrade`, but that left me on `3.0` - to get `3.0.rc2`, I had to `pip uninstall pymc3` and then reinstall.
