### ISSUE TITLE
Print model specification

### ISSUE THREAD

**Issue by psinger** [pymc-devs/pymc#1547]
I am wondering whether there is some way to print a model specification after using some api to create the model. So e.g., assume I use the built-in glm function, I want to see the whole model specification.

I have not found a way to intuitively do that. In best case it would even be possible to print the python code producing the model, so that you could re-use it and fine-tune it.

**Comment by fonnesbeck** [comment]
Are you talking about a DAG? We had this in PyMC2, but have not yet implemented it in PyMC3. You can print the graph in Theano, via `theano.printing.pydotprint` but it is not usually very readable. We would have to put some thought into how to do this.

**Comment by shkr** [comment]
I would like to use this feature too. Any eta on this ?

**Comment by fonnesbeck** [comment]
@shkr I don't think anyone is working on this. It would first require some brainstorming on how to do it. PyDot worked well years ago, but it is poorly maintained. Daft also seems to have been abandoned. Perhaps NetworkX?--I don't know.

**Comment by psinger** [comment]
I don't necessarily mean a DAG, but just a simple print of the model; i.e.,
what likelihoods, priors, etc.

2016-12-29 20:16 GMT+01:00 Chris Fonnesbeck <notifications@github.com>:

**Comment by twiecki** [comment]
I don't think it would be too hard with networkx. We could build up a graph in the `Model.Variable()` method and use networkx's plotting capabilities.
