### ISSUE TITLE
Add different from miniconda test environment

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#1556]
Working on PR I relied on travis tests. Then I started a project using the branch that had passed all tests in travis and got 2 errors. Is it possible to add new environment with nonminiconda python to travis?

**Comment by ColCarroll** [comment]
Any chance you can give more details of where errors are coming from (and what versions of things you're using)?  I almost always develop without (mini)conda, but my understanding is that miniconda should just install python and `conda`.

**Comment by ferrine** [comment]
commit b27ec20efb1cadf59bb3581a5406b0b24483320e
Here python2.7.12 failed because of syntax
```
 -    def __init__(self, *iterable, parent=None):
 -        if len(iterable) > 1:
 -            raise TypeError('Cannot init more than one positional argument')
 +    def __init__(self, iterable=(), parent=None):
```
commit b27ec20efb1cadf59bb3581a5406b0b24483320e
Here `wraps` from functools could not wrap builtin methods
```
 def withparent(meth):
      """Helper wrapper that passes calls to parent's instance"""
 -    @wraps(meth)
      def wrapped(self, *args, **kwargs):
          res = meth(self, *args, **kwargs)
          if getattr(self, 'parent', None) is not None:
              getattr(self.parent, meth.__name__)(*args, **kwargs)
          return res
 +    # Unfortunately functools wrapper fails
 +    # when decorating built-in methods so I
 +    # need to fix that improper behaviour
 +    wrapped.__name__ = meth.__name__
      return wrapped
```
But all travis checks have passed

**Comment by ferrine** [comment]
It can be closed as all things work
