### ISSUE TITLE
forward-backward algorithm - gibbs sampler and hidden markov chains

### ISSUE THREAD

**Issue by jimenofonseca** [pymc-devs/pymc#1558]
Hello pymc3 devs!

I was wondering if there are some intentions to implement some samplers for hidden-markov chains. I am working on calibration of dynamic simulation models using bayesian inference. I am somehow missing how do the current samplers of PYMC3 tackle the temporal interdependency of dynamic models (which could be found widely in economic, medical and even energy forecasting problems).  I saw some implementations in Matlab of fast-forward algorithms and gibbs samplers which might help : https://projecteuclid.org/download/pdf_1/euclid.ba/1340370283. 
The Matlab code is included at the end of the article.

**Comment by twiecki** [comment]
There is an implicit focus on continuous models in PyMC3. We sometimes hear requests for HMMs but so far no one has worked on that. It's not clear that it should be a focus either given that there are multiple HMM packages for Python that seem quite flexible. Have you tried any of those?

**Comment by jimenofonseca** [comment]
I have seen some similar to hmmlearn, but most lack either documentation or up to date algorithms. It would be great to use some of the functionality of pymc3 with hmm one day.

On 28 Nov 2016, at 19:39, Thomas Wiecki <notifications@github.com<mailto:notifications@github.com>> wrote:


There is an implicit focus on continuous models in PyMC3. We sometimes hear requests for HMMs but so far no one has worked on that. It's not clear that it should be a focus either given that there are multiple HMM packages for Python that seem quite flexible. Have you tried any of those?

**Comment by twiecki** [comment]
I'm closing this as we're not actively pursuing it, if someone wants to do a PR we'll definitely consider it.
