### ISSUE TITLE
ADVI returns NaNs in hierarchical regression

### ISSUE THREAD

**Issue by Kiv** [pymc-devs/pymc#1565]
I'm trying to use ADVI to do regression on a function of two parameters, 'exp' and 'tgc'. However, when I run it I get a bunch of NaNs returned. 

I tried stepping through with the debugger but unfortunately I don't understand what's going on inside - I just want to press the 'inference button' :)

I'm using PyMC3 3.0.rc2 and pandas 0.19.1.

Below is a running excerpt of my code. The value for "exp" should be approximately 1/3, and the 2 "tgc" values should be something like 0.20 and 0.14.

    import pymc3 as pm
    import theano
    import pandas as pd
    import numpy as np
    import pprint
    import io

    data = io.StringIO('''
    ,farm,lot_id,weight,stanza,ibw,dd_delta
    1,A,A090824,40.2,1,28.6,244.8
    2,A,A090824,79.2,1,28.6,727.8
    3,A,A090824,104.4,1,28.6,1038.0
    4,A,A090824,122.0,1,28.6,1038.0
    5,A,A090824,124.9,1,28.6,1163.4
    6,A,A090824,183.6,1,28.6,1373.4
    7,A,A090824,220.0,1,28.6,1518.9
    8,A,A090824,269.0,1,28.6,1645.0
    9,A,A090824,411.8,1,28.6,1961.4
    11,A,A090824,983.6,2,590.8,598.5999999999998
    12,A,A090824,1067.7,2,590.8,782.5999999999998
    13,A,A090824,1228.9,2,590.8,782.5999999999998
    14,A,A090824,1072.0,2,590.8,782.5999999999998
    15,A,A090824,1036.6,2,590.8,782.5999999999998
    186,RE,RE05115,35.0,1,34.0,44.40000000000001
    187,RE,RE05115,79.0,1,34.0,512.4
    188,RE,RE05115,88.0,1,34.0,722.4
    189,RE,RE05115,88.0,1,34.0,722.4
    191,RE,RE05115-8,137.0,1,88.0,441.0
    192,RE,RE05115-8,202.0,1,88.0,624.6
    193,RE,RE05115-8,379.0,1,88.0,1498.2
    195,RE,RE05115-8,693.0,2,551.0,237.0
    196,RE,RE05115-8,740.0,2,551.0,237.0
    197,RE,RE05115-8,743.0,2,551.0,237.0
    198,RE,RE05115-8,747.0,2,551.0,237.0
    199,RE,RE05115-8,748.0,2,551.0,237.0
    200,RE,RE05115-8,763.0,2,551.0,369.0
    201,RE,RE05115-8,1029.0,2,551.0,660.4000000000002
    202,RE,RE05115-8,1253.0,2,551.0,1164.4
    203,RE,RE05115-8,1226.4,2,551.0,1758.9
    ''')
    df = pd.read_csv(data, skiprows=1)
    df["farm"] = df.farm.astype('category')
    farm_codes = df.farm.cat.codes.values
    n_farm = len(df.farm.cat.categories)

    with pm.Model() as model:
        mu_tgc = pm.Normal('mu_tgc', mu=0.25, sd=0.1)
        sigma_tgc = pm.HalfNormal('sigma_tgc', sd=0.2)
        tgc = pm.Normal('tgc', mu=mu_tgc, sd=sigma_tgc, shape=n_farm)[farm_codes]

        # This doesn't work
        exp = pm.Exponential('exp', lam=1, testval=1/3) 

        # This works
        #exp = 1/3

        weight_mu = (df.ibw.values ** exp + tgc / 100 * df.dd_delta.values) ** (1 / exp)
        sigma = pm.HalfNormal('sigma', sd=1000)
        weight_like = pm.Normal('weight_like', mu=weight_mu, sd=sigma, observed=df.weight.values)

        mu, sds, elbo = pm.variational.advi(n=100000, random_seed=1)
        pprint.pprint(mu)

**Comment by taku-y** [comment]
Thanks for your report. I think it would be a bug in `advi`. I will check it.

**Comment by Kiv** [comment]
I'm trying to run this model using NUTS instead of ADVI and I'm seeing a similar problem where some models work, other times similar models give errors like:

"PositiveDefiniteError: Scaling is not positive definite. Simple check failed. Diagonal contains negatives. Check indexes [ 0 15 21 22]"

Any ideas on steps I could take to work around this in the meantime? I don't know what [0 15 21 22] indexes refer to, nor do I know what I would change if I did.

**Comment by twiecki** [comment]
@Kiv have you tried initialization with ADVI? Run `pm.sample(n_samples)` on your model.

**Comment by taku-y** [comment]
When running the model without ADVI, at least I'm not getting NaN. The problem might be specific to ADVI, not in MCMC. And I found NaN might appear in weight_mu, but still I'm not sure what's wrong. Will continue to check the code.

**Comment by springcoil** [comment]
I get the same results Taku-y gets, it'll be interesting to see if some of the changes made lately will fix this. I'm running an old rc2 right now. I'll run with rc4 soon.

**Comment by taku-y** [comment]
I found that weight_mu can be inf with possible values of its independent variables `exp` and `tgc`:

```
>> exp = 0.1
>> tgc = -0.3
>> (df.ibw.values ** exp + tgc / 100 * df.dd_delta.values) ** (1 / exp)
array([  0.00000000e+00,   7.89012361e+71,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf])
```

@Kiv Do you think the above values of `exp` and `tgc` are reasonable? I think it would be better to modify the model to make computation numerically stable.

**Comment by Kiv** [comment]
I see, the intent of the model is for both exp and tgc to be always greater than zero as they represent growth over time. 

I can modify the tgc prior to one like uniform that only covers the positive reals, but a better error message in ADVI would still be useful.

**Comment by springcoil** [comment]
Hmm how would we test for this to get an error message in ADVI. Any ideas @taku-y ?

**Comment by taku-y** [comment]
@springcoil [Nanguardmode](http://deeplearning.net/software/theano/tutorial/nan_tutorial.html) of Theano may work for such cases. I will try it with the model here.

**Comment by twiecki** [comment]
I think we now raise an exception.
