### ISSUE TITLE
Multivariate distributions raise nlinalg AssertionError on "vector input"

### ISSUE THREAD

**Issue by philastrophist** [pymc-devs/pymc#1575]
I call it a vector input since I don't know what else to call it. I mean that `MvNorm` only takes arrays for `tau` which are 2 dimensional.

```
  File "C:\Anaconda\lib\site-packages\theano\gof\op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Anaconda\lib\site-packages\theano\tensor\nlinalg.py", line 73, in make_node
    assert x.ndim == 2
```

My idea, which may or may not work out was to estimate the correlation coefficient/matrix for some data with 2d arbitrary uncertainties using the ideas shown in https://gist.github.com/AustinRochford/fa24221f09df20071c06

I'm not sure how to proceed if `MvNormal` expects only 2D `tau` input. I've used "vector input" before with something like: ```measured_x= pm.Normal('measured_x', mu=x_values, sd=x_errs, shape=len(x_values))```.

Should this not extend to multivariate distributions?

Thanks

Example:
```
import pymc3 as pm
import numpy as np
from theano import tensor as T
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import seaborn as sns


"""
extended from gist.github.com/AustinRochford/fa24221f09df20071c06
"""

def test_correlation(values, uncertainties, rhoxys=0, nsteps=4000, nburnin=2000, nthin=2):
    nmeas, ndim = values.shape
    with pm.Model() as model:
        sigma = pm.Lognormal('sigma', np.zeros(2), np.ones(2), shape=2)
        
        nu = pm.Uniform('nu', 0, 5)
        C_triu = pm.LKJCorr('C_triu', nu, 2) 

        C = pm.Deterministic('C', T.fill_diagonal(C_triu[np.zeros((2, 2), dtype=np.int64)], 1.))
        sigma_diag = pm.Deterministic('sigma_mat', T.nlinalg.diag(sigma))
        cov = pm.Deterministic('cov', T.nlinalg.matrix_dot(sigma_diag, C, sigma_diag))
        tau = pm.Deterministic('tau', T.nlinalg.matrix_inverse(cov))

        mu = pm.MvNormal('mu', 0, tau, shape=2)
        std = np.ones((len(uncertainties), 2, 2))
        std[:, 0, 0] = uncertainties[:, 0] ** 2.
        std[:, 1, 1] = uncertainties[:, 1] ** 2.
        std[:, 0, 1] = uncertainties[:, 0] * uncertainties[:, 1] * rhoxys
        std[:, 1, 0] = std[:, 0, 1]
        obs_xy = pm.MvNormal('obs_xy', mu=values, tau=pm.matrix_inverse(std), shape=(len(values), 2))
        x = pm.MvNormal('x', mu, tau, observed=obs_xy)

        step = pm.Metropolis()
        return pm.sample(nsteps, step)[nburnin::nthin]

if __name__ == '__main__':
    from scipy.stats import multivariate_normal
    mu = [1, 1]
    cov = [[1, 0], [0, 1]]
    data = multivariate_normal.rvs(mu, cov, size=100)
    errs = np.ones_like(data) * 0.0001
    trace = test_correlation(data, errs)
```

**Comment by twiecki** [comment]
Unfortunately, the 2D distributions do not support that yet, see https://github.com/pymc-devs/pymc3/issues/535. To get around that, you can still do a list-comprehension. I'm closing this in favor of the original issue but feel free to keep asking questions.

**Comment by philastrophist** [comment]
Ok, thanks.
I've converted `obs_xy` to a list comprehension:
```
obs_xy = [pm.MvNormal('obs_{}'.format(i), mu=values[i], tau=np.linalg.inv(std)[i] for i in xrange(values.shape[0])]
```
However, now I seem to get  a `ValueError`
`TypeError: For compute_test_value, one input test value does not have the requested type.`

My guess would be that it's not interpreting the list comprehension correctly. I'm using the latest git installations. What am I doing wrong here?

Thanks
