### ISSUE TITLE
supplying numpy.ndarray of subplots to traceplot fails

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#1577]
As is, traceplot returns an orphaned numpy.ndarray of subplots that can't be used (as hard as _I_ have tried). Attempts to supply the subplots as an argument to traceplot, so that they _are_ owned by a matplotlib figure instance results in a KeyError

Minor adaptations to one of the PyMC3 examples provides an MWE:

    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    from pymc3 import *
    import theano.tensor as tt
    from theano import as_op
    from numpy import arange, array, empty

    __all__ = ['disasters_data', 'switchpoint', 'early_mean', 'late_mean', 'rate','disasters']

    # Time series of recorded coal mining disasters in the UK from 1851 to 1962
    disasters_data = array([4, 5, 4, 0, 1, 4, 3, 4, 0, 6, 3, 3, 4, 0, 2, 6,
                            3, 3, 5, 4, 5, 3, 1, 4, 4, 1, 5, 5, 3, 4, 2, 5,
                            2, 2, 3, 4, 2, 1, 3, 2, 2, 1, 1, 1, 1, 3, 0, 0,
                            1, 0, 1, 1, 0, 0, 3, 1, 0, 3, 2, 2, 0, 1, 1, 1,
                            0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2,
                            3, 3, 1, 1, 2, 1, 1, 1, 1, 2, 4, 2, 0, 0, 1, 4,
                            0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1])
    years = len(disasters_data)

    # here is the trick
    @as_op(itypes=[tt.lscalar, tt.dscalar, tt.dscalar], otypes=[tt.dvector])
    def rateFunc(switchpoint, early_mean, late_mean):
        ''' Concatenate Poisson means '''
        out = empty(years)
        out[:switchpoint] = early_mean
        out[switchpoint:] = late_mean
        return out

    with Model() as model:

        # Prior for distribution of switchpoint location
        switchpoint = DiscreteUniform('switchpoint', lower=0, upper=years)
        # Priors for pre- and post-switch mean number of disasters
        early_mean = Exponential('early_mean', lam=1.)
        late_mean = Exponential('late_mean', lam=1.)

        # Allocate appropriate Poisson rates to years before and after current switchpoint location
        rate = rateFunc(switchpoint, early_mean, late_mean)

        # Data likelihood
        disasters = Poisson('disasters', rate, observed=disasters_data)

        # Initial values for stochastic nodes
        start = {'early_mean': 2., 'late_mean': 3.}

        # Use slice sampler for means
        step1 = Slice([early_mean, late_mean])
        # Use Metropolis for switchpoint, since it accomodates discrete variables
        step2 = Metropolis([switchpoint])

        # njobs>1 works only with most recent (mid August 2014) Thenao version
        tr = sample(1000, tune=500, start=start, step=[step1, step2], njobs=1)

        fig, axarr = plt.subplots(3,2)
        axarr = traceplot(tr, axarr)

        fig.savefig("disaster.png")

gives on stdout:

> Applied log-transform to early_mean and added transformed early_mean_log to model.
> Applied log-transform to late_mean and added transformed late_mean_log to model.
> [-----------------55%-                 ] 559 of 1000 complete in 0.5 sec
> [-----------------100%-----------------] 1000 of 1000 complete in 0.8 sec
> Traceback (most recent call last):
>   File "disaster_prototype.py", line 73, in <module>
>     axarr = traceplot(tr, axarr)
>   File "/usr/local/lib/python3.5/dist-packages/pymc3/plots.py", line 72, in traceplot
>     for d in trace.get_values(v, combine=combined, squeeze=False):
>   File "/usr/local/lib/python3.5/dist-packages/pymc3/backends/base.py", line 250, in get_values
>     for chain in chains]
>   File "/usr/local/lib/python3.5/dist-packages/pymc3/backends/base.py", line 250, in <listcomp>
>     for chain in chains]
>   File "/usr/local/lib/python3.5/dist-packages/pymc3/backends/ndarray.py", line 99, in get_values
>     return self.samples[varname][burn::thin]
> KeyError: '[<matplotlib.axes._subplots.AxesSubplot object at 0x7f0aef30df98>\n <matplotlib.axes._subplots.AxesSubplot object at 0x7f0aeea46cc0>]'

I don't know if it's related, but on inspection of code [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/plots.py) together with checking varnames of the trace object, there are two varnames corresponding to each variable, which should correspond to the left and right plot instances within the numpy.ndarray, yet the loop within which those plot instances are built loops through all variable names, rather than treating them as pairs. It doesn't feel like this would necessarily cause the error above, maybe it's a separate matter, or I haven't thought enough about it yet.

**Comment by ColCarroll** [comment]
Not super familiar with matplotlib, but works for me if you change the second to last line to `axarr = traceplot(tr, ax=axarr)`

**Comment by ghost** [comment]
Ahhh. Crap! Apologies!!

I swore I had that earlier, but obviously not. Damn.

Thank you!

**Comment by ColCarroll** [comment]
👍  no problem!  That function could use some love if you have spare cycles...

**Comment by ImportanceOfBeingErnest** [comment]
It may be useful to at least adapt the docstring, such that its clear that the `ax` keyword instead of 
`ax : axes Matplotlib axes. Defaults to None.` would (also?) accept a numpy array of axes. And also state which dimensions that array  would have to have.

**Comment by ghost** [comment]
I had been mulling over adaptations to that function in the background as a workaround measure -- I'll try to work that into my efforts as I continue forward. Thanks!
