### ISSUE TITLE
Feature Request: Triangular distributions

### ISSUE THREAD

**Issue by adam-rysanek** [pymc-devs/pymc#1578]
Am I right that there is no pymc3 distribution object within the API that lets one apply triangular distributions to variables - e.g., pm.Triangular('var',mid = 1, lower = 0, upper = 2) ?
This would be highly useful, unless I'm missing clear easy alternatives?

With thanks A.

**Comment by twiecki** [comment]
We don't have that, correct. A PR would certainly be appreciated.

**Comment by jimenofonseca** [comment]
@twiecki i gave it a shot, however i would appreciate some help with the log function using the function bound of PYMC3 as I am getting the next error:

TypeError: Variables do not support boolean operations. This can happen if you do a logical operation (<, <=, >, <=, ==, !=) between a numpy.ndarray and a Theano tensorvariable. Due to NumPy implementation before NumPy 1.8, we cannot make the Python syntax work when the ndarray is on the left, and this results in this error. To work around that, either call theano.tensor.{lt,le,eq,ne,gt,ge}(ndarray, tensor), or use the Python syntax with the Theano tensor on the left. Or update to NumPy 1.8 or above.

```
from pymc3.distributions.distribution import Continuous, draw_values, generate_samples
from scipy import stats
class Triangular(Continuous):
    """
    Continuous Triangular log-likelihood.

    Parameters
    ----------
    lower : float
        Lower limit.
    c: float
        mode
    upper : float
        Upper limit.
    """
    def __init__(self, lower=0, upper=1, c = 0.5, transform='interval',
                 *args, **kwargs):
        super(Triangular, self).__init__(*args, **kwargs)

        self.c = c
        self.lower = lower
        self.upper = upper
        self.mean, = stats.triang.stats(c, moments='m')
        self.median = self.mean

    def random(self, point=None, size=None, repeat=None):
        lower, c, upper = draw_values([self.lower, self.c, self.upper],
                                   point=point)
        return generate_samples(stats.triang.rvs, c=c, loc=lower, scale=upper - lower,
                                size=size, random_state=None)

    def logp(self, value):
        c = self.c
        lower = self.lower
        upper = self.upper
        if lower <= value < c:
            return -tt.log(2 * (value - lower) / ((upper - lower) * (c - lower)))
        elif value is c:
            return -tt.log(2 / (upper - lower))
        elif c < value <= upper:
            return -tt.log(2 * (upper - value) / ((upper - lower) * (upper - c)))
        else:
            return -np.inf

```

**Comment by jimenofonseca** [comment]
I just tried this new construction and get the next error:

Traceback (most recent call last):
  File "C:/Users/Jimeno/Documents/CEAforArcGIS/cea/demand/calibration/calibration_main.py", line 167, in <module>
    run_as_script()
  File "C:/Users/Jimeno/Documents/CEAforArcGIS/cea/demand/calibration/calibration_main.py", line 164, in run_as_script
    calibration_main(locator, weather_path, building_name, variables, building_load, retrieve_results, niter=100)
  File "C:/Users/Jimeno/Documents/CEAforArcGIS/cea/demand/calibration/calibration_main.py", line 63, in calibration_main
    upper=pdf.loc[variable, 'max'])
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\pymc3\distributions\distribution.py", line 27, in __new__
    return model.Var(name, dist, data)
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\pymc3\model.py", line 285, in Var
    var = FreeRV(name=name, distribution=dist, model=self)
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\pymc3\model.py", line 514, in __init__
    self.logp_elemwiset = distribution.logp(self)
  File "C:/Users/Jimeno/Documents/CEAforArcGIS/cea/demand/calibration/calibration_main.py", line 137, in logp
    return triang_logp(lower, upper, c, value)
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\theano\gof\op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\theano\gof\op.py", line 990, in make_node
    if not all(inp.type == it for inp, it in zip(inputs, self.itypes)):
  File "C:\Users\Jimeno\Anaconda2\envs\esri104\lib\site-packages\theano\gof\op.py", line 990, in <genexpr>
    if not all(inp.type == it for inp, it in zip(inputs, self.itypes)):
AttributeError: 'numpy.float64' object has no attribute 'type'`

```
class Triangular(Continuous):
    R"""
    Continuous Triangular log-likelihood.

    Parameters
    ----------
    lower : float
        Lower limit.
    c: float
        mode
    upper : float
        Upper limit.
    """

    def __init__(self, lower=0, upper=1, c=0.5, transform='interval',
                 *args, **kwargs):
        super(Triangular, self).__init__(*args, **kwargs)

        self.c = c
        self.lower = lower
        self.upper = upper
        self.mean = c
        self.median = self.mean

    def random(self, point=None, size=None, repeat=None):
        lower, c, upper = draw_values([self.lower, self.c, self.upper],
                                      point=point)
        return generate_samples(stats.triang.rvs, c=c, loc=lower, scale=upper - lower,
                                size=size, random_state=None)


    def logp(self, value):
        c = self.c
        lower = self.lower
        upper = self.upper
        #f1 = -tt.log(2 * (value - lower) / ((upper - lower) * (c - lower)))
        #f2 = -tt.log(2 / (upper - lower))
        #f3 = -tt.log(2 * (upper - value) / ((upper - lower) * (upper - c)))
        #return bound(lower <= value < c, f1, bound(value == c, f2, bound(c < value <= upper, f3)))

        return triang_logp(lower, upper, c, value)

@as_op(itypes=[tt.dscalar, tt.dscalar, tt.dscalar, tt.dscalar], otypes=[tt.dscalar])
def triang_logp(lower, upper, c, value):
    if lower <= value < c:
        return -tt.log(2 * (value - lower) / ((upper - lower) * (c - lower)))
    elif value is c:
        return -tt.log(2 / (upper - lower))
    elif c < value <= upper:
        return -tt.log(2 * (upper - value) / ((upper - lower) * (upper - c)))
    else:
        return -np.inf`

```

**Comment by twiecki** [comment]
I think you will have to replace the python `if`s either to `theano.IfElse.ifelse` or `theano.switch` statements. Also, can you improve the formatting of your issue a bit? It's kinda hard to read.

**Comment by jimenofonseca** [comment]
thanks for the input, i used switch and now it works, how can i summit a PR about this? i do not have permissions

**Comment by twiecki** [comment]
Great! https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by sada-narayanappa** [comment]
When can we expect Triangular distributions - I use it in most of my work.
Is it available in latest git - could I pull

**Comment by ColCarroll** [comment]
@JIMENOFONSECA has a PR open, but it is not yet merged (#1646) -- should be available soon!

**Comment by sada-narayanappa** [comment]
HI - Just wondering when could I expect the merge. 
Next, I was wondering how to add custom PMF for multinomial distributions.

I think show casing some examples from Oracle Crystal ball will be super helpful

**Comment by fonnesbeck** [comment]
It has been merged.

**Comment by sada-narayanappa** [comment]
HI This is open for too long. Could someone add Triangular to the repo. I just updated and don;t see it - thanks for all you do

**Comment by junpenglao** [comment]
hi @sada-narayanappa, Triangular distribution has been added:
```
In [29]: pm.Triangular
Out[29]: pymc3.distributions.continuous.Triangular
```

**Comment by springcoil** [comment]
Btw we have no intentions to do examples in oracle crystal ball. All are
welcome to submit examples

On 26 Sep 2017 07:16, "Junpeng Lao" <notifications@github.com> wrote:

hi @sada-narayanappa <https://github.com/sada-narayanappa>, Triangular
distribution has been added:

In [29]: pm.Triangular
Out[29]: pymc3.distributions.continuous.Triangular

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pymc-devs/pymc3/issues/1578#issuecomment-332097296>,
or mute
the thread
