### ISSUE TITLE
Bounded random method fails with shape ndim > 1

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#1583]
This fails
```python
>>> with pm.Model(): a = pm.HalfStudentT('st', nu=10, shape=(10, 10))
>>> a.random()
ValueError: could not broadcast input array from shape (48) into shape (1)
```

**Comment by ferrine** [comment]
I also detected some shape inequalities but due to generic test it is hard to list failing examples

**Comment by ferrine** [comment]
Currently preparing a PR with test suite and hopefully bugfix for shape problem

**Comment by twiecki** [comment]
:+1:

**Comment by ferrine** [comment]
refer #1585

**Comment by ferrine** [comment]
BTW Bounded class is improperly implemented, it yields an instance, not subclass, so `issubclass(distclass, Distribution)` fails. I had to write dirty [ad hoc solution](https://github.com/ferrine/gelato/blob/master/gelato/spec.py#L50) for that

**Comment by twiecki** [comment]
Related: #1579.

Your code works if I make this change in `dist_math.py`:
```python
def alltrue(vals):
    return tt.all([1 * val for val in vals], axis=0)
```

**Comment by twiecki** [comment]
I think we fixed this.
