### ISSUE TITLE
Magic ? Fitting a 3 Gaussians mix data with only a 2 Gaussians model, shouldn't work, but it does ?

### ISSUE THREAD

**Issue by hwassner** [pymc-devs/pymc#1587]
Hi, 

I'm having something that should NOT work , but it does! I just dont understand how is it possible.
Is pymc3 more powerfull that I believe, or is it a very strange bug ?

This is my experiment.

**I have built a toy data set: a mix of 3 gaussians** (means=[100,200,300], with standard deviation =[10,20,30])
**I'm trying to fit that data with a 2 gaussians mix model. I expect that it should NOT work! 
but it does !!**

The trace (shown below) indicates that it fits only my third gaussian (a mean around 300 and standard deviation around 30 and a 0.33 proportion("dirichlet")). But, the parameter of the second gaussian of the model is wrong: it doesn't fit any of the the 2 other gaussian of the data.
It is what I expected : you can't fit 3 gaussian with a model holding only 2... 
(The weird stuff is coming on the next figure...)

This is the trace 
![pymc_bug_trace](https://cloud.githubusercontent.com/assets/7187632/21045690/a41c6186-be01-11e6-93e6-c841a97019a5.png)

Then the Predictive Posterior Check should be wrong for 2 of the 3 gaussians of the data.
But I get this which perfectly fits the data !? **how can this works with only 2 gaussians in the model ???**

![pymc_bug_ppc](https://cloud.githubusercontent.com/assets/7187632/21045995/cfaa2e7c-be02-11e6-9287-e15a5a8d3b27.png)

I know there is a builtin gaussian mix feature, but I want to do it myself for a better understanding
(and I want to do something slightly different).

This is my code 
```python
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import pymc3 as pm

# toy data set 3 gausians with means 100,200, 300 and standard deviation 10,20,30
data = np.concatenate([np.random.randn(333)*10.0+100.0,
    np.random.randn(333)*20.0+200.0,
    np.random.randn(333)*30.0+300.0])

k = 2 # two gaussians
reSample = 2
model = pm.Model()
with model:
    # prior on probabilty to get one of the gaussians
    diri =  pm.Dirichlet('diri', a=np.ones(k), shape=k)
    category = pm.Categorical('category',p=diri, shape=data.size)
    # k gaussians parameters
    means = pm.Uniform('means',lower=0.0, upper=500.0, shape=k)
    sd = pm.HalfNormal('sd', sd=20, shape=k)
    # mix of gaussians according to category sampled
    g = pm.Normal('g', mu=means[category],sd=sd[category], shape=data.size)
    # little error on top of that random process
    sigma = pm.HalfNormal('sigma', sd=0.1)
    # last stage : adding error to the mix draws
    obs = pm.Normal('obs', mu=g,sd=sigma, observed=data)
    # fit model ##########################
    step1 = pm.Metropolis(vars=[  diri,sd, means, sigma]) # we leave g to NUTS
    step2 = pm.ElemwiseCategorical(vars=[category], values=range(k))
    tr = pm.sample(4000, step = [ step1, step2])
    trace = tr[1000::10] # burning & thinning
    ppc_trace = pm.sample_ppc(trace,vars=[obs], samples=reSample)

########## show the trace
pm.plots.traceplot(tr, ['sd', 'means','diri', 'sigma'])
plt.show()

##### show the posterior predictive check
fig, ax = plt.subplots(figsize=(8, 6))
ax.hist(data, bins=list(range(0,500, 3)), normed=True, histtype='step', lw=2, label='Observed data');
# show
for i in range(len(ppc_trace['obs'])): # boucle sur les re-samples
    ax.hist(ppc_trace['obs'][i], bins=list(range(-20,500, 3)),  normed=True, histtype='step', lw=2, label='model re-sample') # [i]
    ax.legend(loc=1);
plt.show()
```

Any help strongly appreciated...

**Comment by fonnesbeck** [comment]
Actually, the model does not fit very well, and running multiple chains shows this to be true:

![](http://d.pr/i/ikQE+)

The sampler tries to account for the third peak by having a long tail on one (or both) of the distributions. This is actually a good lesson for checking convergence with multiple chains!

**Comment by hwassner** [comment]
I totally agree that the convergence is not ok and that the parameters found does not fit 
the ones used to build the data. **I know that, and that's why I dont understand how the PPC 
(predictive posterior check) can be so close to the data ?**

How can it produce a 3 bumps PPC curve with only 2 gaussians in the model ?
(I did a test with 4 gaussians in the data, with only 2 gaussians in the model, and
the PPC is still nice! even with very bad convergence!)

**Comment by twiecki** [comment]
@hwassner You certainly created a model with a multi-modal posterior. The only reasonable explanation is that the posterior manages to explore these modes (which matches well with lack of convergence to a single mode). When you then run PPC you will sometimes get parameters for all 3 normals. You could plot the 2-D posterior of the two means.

**Comment by hwassner** [comment]
Thanks very much @twiecki for that explanation.
If my parameters are latent, and if I'm only interested in the PPC is it ok to use it anyway ?

All I want is to be able to re-sample my data to do test hypothesis (for A/B test)
Is it ok to do so ? Or do I have to have a good R-hat < 1.05  for all my parameters, in order to have a
correct re-sample of the data ? (as suggested by @fonnesbeck )

By the way which function do you use to compute that "R-hat" ?

Thanks very much for your work and support.

Regards,
 Hubert.

**Comment by twiecki** [comment]
R-hat is really only meaningful for single-modal posteriors so it's OK. I would really make sure that your model is really exploring the modes correctly. The PPC makes it seem as it does. You can do stats on multi-modal posteriors too, or just look at the PPC. As long as you have the right posterior everything should be good.

> By the way which function do you use to compute that "R-hat" ?
http://pymc-devs.github.io/pymc3/api.html#pymc3.diagnostics.gelman_rubin
