### ISSUE TITLE
Large multivariate normal sampling with NUTS returns the same N-dimensional sample over and over.

### ISSUE THREAD

**Issue by jasonzutty** [pymc-devs/pymc#1589]
I am drawing from a large multivariate normal (1000+), and drawing many samples (order of 100k), but when I analyze the trace of the variable, every of the 100k rows is exactly the same. I did not have this issue with smaller multivariates. 

`basic_model = pm.Model()
    with basic_model:
        mv_normal = pm.MvNormal('mvn', mu=means_vector, cov=observation_covariance, shape=len(means_vector))
        tr = pm.sample(100000, pm.NUTS())`

**Comment by jasonzutty** [comment]
By implementing my own custom distribution, I have found that it only seems to call logp one time.  Could this be related to the issue?

**Comment by twiecki** [comment]
Yes, it should definitely evaluate the model multiple times. Something seems really weird here, can you post a minimal working example?

**Comment by jasonzutty** [comment]
[same_sample_example.txt](https://github.com/pymc-devs/pymc3/files/647329/same_sample_example.txt)

Simple example attached.  When I run this code (I had to change the extension to upload) it completes in about 21 seconds and hits the line of code that says "ALL THE SAME", furthermore, every row appears to be the means vector.

**Comment by jonathanhfriedman** [comment]
This may be occurring because of numerical instability when calculating the log determinant in the MVN `logp` as discussed [here](https://github.com/Theano/Theano/pull/3959), since the value of `N` where this starts happening is around the same value where `np.linalg.det(tau)` starts returning zero.

**Comment by junpenglao** [comment]
This is not a problem anymore, closing now.
Also FYI, sampling without tuning doesnt work `tr = pm.sample(1000, pm.NUTS())`, as the parameter dimension is high. Use `tr = pm.sample(1000)` instead.
