### ISSUE TITLE
has no attribute 'varnames'

### ISSUE THREAD

**Issue by wuxiyu** [pymc-devs/pymc#1593]
`>>> summary(trace['alpha'])
`
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/anaconda3/lib/python3.5/site-packages/pymc3/stats.py", line 572, in summary
    varnames = [name for name in trace.varnames if not name.endswith('_')]
AttributeError: 'numpy.ndarray' object has no attribute 'varnames'
`

I think maybe because of python3.5 or numpy?

**Comment by fonnesbeck** [comment]
Double check what your `trace` object that you are passing in is. All trace objects will have a `varnames` attribute.

**Comment by ColCarroll** [comment]
I think just a mistake with the api -- should be `summary(trace,
varnames=['alpha']) to only get a summary of `alpha`.

**Comment by wuxiyu** [comment]
Thank you very much! I know what I mistake.
