### ISSUE TITLE
High-dimensional model debugging--should my traces jump around between runs?

### ISSUE THREAD

**Issue by jamestwebber** [pymc-devs/pymc#1595]
I've been working on a regularized logistic regression model using PyMC3. I've had a few different issues, mostly due to slow sampling. NUTS stalls out almost immediately, so I'm using Metropolis for now. If there's some known work needed to get NUTS working I can try to help out.

One thing I've noticed is that relatively short sampling runs (20k samples, say, which takes less than a minute) will stabilize quickly, but if I restart the model everything jumps around and stabilizes somewhere else. That suggests to me that the sampler is not doing a very good job of exploring the parameter space, but I'm not sure what to do about it.

Also it's unclear to me what happens upon restarting that makes the sampler move everything around. Is this expected behavior?

I don't have a toy example right now but I can try to put one together if that would help.

**Comment by twiecki** [comment]
If you set the seed, does that still happen?

It seems you might have multiple modes in your posterior, hence the sampler converging to different ones.

How do you run the NUTS sampler? Have you tried auto-init by just calling `pm.sample(n_iter)`?

**Comment by jamestwebber** [comment]
If I set random_seed=0 for both calls to `sample()` I get the same behavior--the second trace starts in a different spot. Or if I just set the seed in the first call and don't set it for the second. Is there something else I should try?

> It seems you might have multiple modes in your posterior, hence the sampler converging to different ones.

This may be a naïve question, but does that mean I'm sunk? MCMC isn't going to work on this model?

I was initializing NUTS with ADVI, based on what I saw in other discussions here:
```
mu, sds, elbo = pymc3.variational.advi(n=5000)
step = pymc3.NUTS(scaling=model.dict_to_array(sds)**2, is_cov=True)
trace = pymc3.sample(100, step, start=mu, progressbar=True)
```

If I just call pymc3.sample() it assigns NUTS to the variables, takes a while to initialize (I think) and then sampling stalled at the 6th iteration.

**Comment by jamestwebber** [comment]
Revisiting this, it seems to be something in Metropolis. NUTS doesn't do it, but it also doesn't work with my model.

Here's a simple example to show what I mean: the traces reset to zero when I start a new run. Maybe I'm just missing something when it come to multiple samples, but if so that setting is non-obvious.

```python
x = np.random.normal(size=(20, 20))
b = np.random.normal(scale=2.0, size=x.shape[1]) * (np.random.random(size=x.shape[1]) > 0.5).astype(float)
b += np.sign(b)

y = np.dot(x, b)

with pymc3.Model() as model:
    beta = pymc3.Laplace('beta', mu=0, b=0.05/np.sqrt(2), shape=x.shape[1])

    y_hat = pymc3.dot(x, beta)
    data = pymc3.Normal(name='data', mu=y_hat, sd=0.5, observed=y) 
    
    mu, sds, elbo = pymc3.variational.advi(n=5000)
    step = pymc3.Metropolis()
    trace_a = pymc3.sample(1000, step, start=mu, random_seed=0, progressbar=True)

with model:
    trace_b = pymc3.sample(1000, step, progressbar=True)

b_ = np.vstack((trace_a['beta'], trace_b['beta']))

plt.plot(b_, alpha=0.7)

plt.axvline(1000, linestyle=':')
   
plt.show()
```

**Comment by jamestwebber** [comment]
My mistake, it _does_ happen with the NUTS sampler as well, I just couldn't see it with such long traces. Setting sample to something like 10-20 makes it clear.

The pymc3 code is rather Byzantine (for good reasons, I'm sure!) so I'm not sure exactly where this is happening. One guess is [this line of sampling.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/sampling.py#L247). Or rather, because start is `None` at that point, it starts the sample from square one.

Should I be passing a `start` argument to the second call to `sample`? My impression was that it would start from where it left off if I wasn't explicit, and I think that's how it worked in the past.

edit: I guess the answer is to pass the previous `trace` object to the next call to `sample`. If that's how things are supposed to work then this can get closed (but I think some examples need updating). If the second call to `sample` is supposed to find the old trace on its own, then something in the context is borked.

**Comment by twiecki** [comment]
> edit: I guess the answer is to pass the previous trace object to the next call to sample. If that's how things are supposed to work then this can get closed (but I think some examples need updating).

Yes, exactly. The state is supposed to live outside the model / samplers.
