### ISSUE TITLE
Add user defined test_value for missing values

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#1602]
I was experimenting with multivariate time series and found that starting point is essential here for starting sampling.
Results differ in following cases:
1) start sampling missing value from she mean of all the data - very bad result if mean is far from last seen point (sampling for very long time is available)
2) start sampling from the last seen point - expected result

That problem can be the one that made me impossible to implement ARIMA(p,d,q) some time ago. Every sampling resulted in distribution near zero while the truth was far away from it

**Comment by springcoil** [comment]
That's interesting. Any idea how to approach this?

**Comment by ferrine** [comment]
It can be done manually in some obscure way. I don't know another approach. Maybe it's very local problem that can be ignored

**Comment by fonnesbeck** [comment]
What about using the `fill_value` from the masked array directly?
