### ISSUE TITLE
Bind additional variables before sampling?

### ISSUE THREAD

**Issue by niekbouman** [pymc-devs/pymc#1605]
Dear PyMC3 developers,

I'd like to create a PyMC3 model, in such a way that I am able to re-use some parts of the model for purposes other than MCMC sampling, i.e., I want to compile part of my model as a separate Theano function. (My use case is to be able to use the model as a predictor, after training the parameters with PyMC3).

In particular, I'd like to define a symbolic variable (a 'placeholder' in Tensorflow's jargon) in the model, so that I can bind that one only at the evaluation phase. 
My question is: How can I bind this symbolic variable to a certain value before sampling?

best,
Niek

**Comment by ferrine** [comment]
Hi Niek!

We are planning to make variational inference easier in pymc3.1. Ideally you will need to fit the posterior and then make replacements in the graph with fitted stochastic/determitistic parameters. I hope that will solve your case in future.

**Comment by twiecki** [comment]
Niek, `tensorflow.placeholder` is `theano.shared` in `theano`. You can see http://pymc-devs.github.io/pymc3/notebooks/bayesian_neural_network_advi.html for an example of how to use it in the way you describe.

**Comment by niekbouman** [comment]
I also just realized that I can use `shared` for that, and it works well for my use case.
But thanks anyway for your quick reply!

best regards,
Niek
