### ISSUE TITLE
set batches to number of samples if smaller than default

### ISSUE THREAD

**Issue by tyarkoni** [pymc-devs/pymc#1606]
I ran into this while debugging a model, and it probably won't come up very often, but if the number of samples in a `MultiTrace` is < 100, and you try to call `summary` on it, the size of the `batches` argument isn't adjusted, which causes slicing to fail. Can presumably be fixed by setting `batches` to the min of `batches` and length of the trace. I'll submit a PR when I have a chance if no one else gets to it first (just opening this so I don't forget).

**Comment by twiecki** [comment]
Sounds like a valid fix.
