### ISSUE TITLE
Convergence issue with Metropolis for simple hierarchical model

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1607]
[Here is an example](https://github.com/fonnesbeck/uterine_fibroids_MA/blob/master/PyMC%20convergence%20issues.ipynb) of issues I have been seeing with the Metropolis sampler, using a very simple hierarchical model.

You can see that the model, run with different subsets of data, has major convergence issues using the Metropolis sampler. Initializing the model using `find_MAP` doesn't help much, but this sort of model should not require much help with initialization.

I thought it might be the transform issue again, but setting `transform=False` for the standard deviation does not help.

NUTS does better (though it also cannot recover the true result very well), but Metropolis should be able to knock this out just fine, so I'm concerned about it. 

Running from current master under Python 3.5.2 and macOS 10.12.

**Comment by fonnesbeck** [comment]
OK, it occurred to me that this looks like the hierarchical parameterization issue [raised by Betancourt](https://arxiv.org/pdf/1312.0906v1.pdf). The reparameterization in  [this version](https://github.com/fonnesbeck/uterine_fibroids_MA/blob/master/PyMC%20convergence%20issues%20(fixed).ipynb) fixes the problem. I may add this as an example notebook.

**Comment by twiecki** [comment]
@fonnesbeck Yes, I think that'd be a great trick to have in the docs.
