### ISSUE TITLE
bug in stan

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#1616]
Latest news form stan [Stan 2.10 through Stan 2.13 produce biased samples](http://andrewgelman.com/2016/12/20/stan-2-10-stan-2-13-produce-biased-samples/) 
Do we have any test to check that sampling works properly?

**Comment by ColCarroll** [comment]
#1424 -- @beckermr also pointed out the error(s) in my refactor of NUTS!

**Comment by ferrine** [comment]
So sorry @ColCarroll:(

**Comment by ColCarroll** [comment]
ha!  better to have found it -- working on a more careful refactor, since I think NUTS is still pretty hard to read in all implementations I've seen
