### ISSUE TITLE
Question: How to choose the sampling method?

### ISSUE THREAD

**Issue by drlima** [pymc-devs/pymc#1620]
I am new with pymc3 and MCMC, and I am trying to understand the better way to work with it.

I am following the Getting started with PyMC3 tutorial, and trying the example for a linear regression (calculating alpha and beta).
When I use NUTS my code runs in 1+ minute of execution time but when I use the Slice method it executes in 30 secs.

My question is: Should I consider other variables them the time for execution?

**Comment by fonnesbeck** [comment]
I'm going to close this, as its not a bug report. A better place to ask questions is on Gitter (see the badge on our README file on the home page) or on StackOverflow with the `pymc` tag.

The short answer is, NUTS will always take longer, but will sample more efficiently (in terms of effective sample size).

**Comment by drlima** [comment]
Thanks!!
