### ISSUE TITLE
mixing and speed of BinaryMetropolis vs. BinaryGibbsMetropolis steps on mixture models

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc#1621]
I have run into a potential bug in Metropolis inference with pymc3. I'm more familiar with pymc2 but have been trying to switch completely to pymc3. [This](https://gist.github.com/yarden/f7afb4447b2218f56cc29ff9f68ce35a) is my attempt to implement a simple mixture model of univariate LogNormal distributions where the mean and sigma parameters are unknown.

When I try to solve the model using Metropolis (using ``Metropolis`` step to sample continuous variables and ``BinaryMetropolis`` to sample assignments of data points to components), it runs fairly quickly (~5 secs for 500 data points) but doesn't seem to produce good posterior samples. However, if I use ``BinaryGibbsMetropolis`` to sample the assignments, it's about 20 times slower (~95 secs for 500 data points), but gives far better results. 

- The code is here: https://gist.github.com/yarden/f7afb4447b2218f56cc29ff9f68ce35a
- These are the results of non-Gibbs vs. Gibbs attempt to fit a mixture:
![pymc3_gibbs_step](https://cloud.githubusercontent.com/assets/96318/21469583/9c6daf30-ca27-11e6-9854-3f675e88e3dd.png)

My main questions:

1. Is the failure of plain ``BinaryMetropolis`` here a bug? I can understand why Gibbs sampling with ``BinaryGibbsMetropolis`` would be more efficient in exploring the high posterior probability regions, but it seems like a huge difference. Even with more data and sampling iterations, the non-Gibbs method doesn't appear to work.
2. Why is Gibbs so much slower? I assume that the Gibbs step iterates through all data points for each sample.

Finally, I know this has been [discussed here](https://github.com/pymc-devs/pymc3/issues/739) before, but pymc3 appears much slower than pymc2 for me. Is there an easy way to speed up this particular model (ideally sticking to Metropolis for inference)? 

Thanks very much, 
Yarden

PS There might be identifiability issues with this model as formulated, but nonetheless there's a big difference between Gibbs vs. non-Gibbs here and I'm unsure of what explains that.

**Comment by twiecki** [comment]
I'm not hugely surprised. The non-Gibbs sampler has a very low chance of ever accepting a jump, have you checked the acceptance ratio? The Gibbs sampler is actually drawing many samples per iteration, one for each data point. I suppose we could set it up to always only update a single RV which would be way faster but give considerably higher auto-correlation.

Have you considered using a Mixture distribution instead? That should not have the problems. See: http://pymc-devs.github.io/pymc3/notebooks/marginalized_gaussian_mixture_model.html

**Comment by yarden** [comment]
Thanks for this. Sorry for the pedestrian question, but how do you inspect acceptance rate in pymc3? 

I will try to use ``Mixture`` class instead to collapse out the assignments.

**Comment by fonnesbeck** [comment]
Currently, you can't get at it directly. `Metropolis` has an `accepted` counter, and HMC/NUTS does not have any attributes associated with the realized acceptance. Perhaps this should be stored or returned (or better yet, reported at the end of the MCMC run).
