### ISSUE TITLE
Negative phase sampling during RBM training

### ISSUE THREAD

**Issue by Dabuk** [pymc-devs/pymc#1622]
Hi,

I recently stumbled upon pymc3. I am still going through the tutorials.

I want to know if it is possible to use pymc3 NUTS/HMC sampler to sample data using the Restricted Boltzmann Machine's free energy function.

**Comment by springcoil** [comment]
I'm closing this as it's not a bug fix - I'd recommend either Gitter or http://stackoverflow.com/search?q=pymc3 to ask this question.
