### ISSUE TITLE
pip install pymc3-3.0rc5.tar.gz has no package directory 'docs'

### ISSUE THREAD

**Issue by yvesalexandre** [pymc-devs/pymc#1633]
I just tried installing pymc3 using pip on a clean Ubuntu 16.04 and it seems that a directory docs" is missing
best, Yves-Alexandre

pip install -U pymc3

Collecting pymc3
  Downloading pymc3-3.0rc5.tar.gz (992kB)
    100% |████████████████████████████████| 993kB 959kB/s 
    Complete output from command python setup.py egg_info:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '3.0.rc5' to '3.0rc5'
      normalized_version,
    running egg_info
    creating pip-egg-info/pymc3.egg-info
    writing requirements to pip-egg-info/pymc3.egg-info/requires.txt
    writing pip-egg-info/pymc3.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pymc3.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pymc3.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pymc3.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'docs' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u3oT51/pymc3/

**Comment by springcoil** [comment]
Cc @fonnesbeck

**Comment by springcoil** [comment]
Incidentally this causes a break in https://ci.appveyor.com/project/conda-forge/pymc3-feedstock/build/1.0.13/job/8cnj2qv15njfkvxy too

**Comment by yvesalexandre** [comment]
Works great, thanks!

**Comment by springcoil** [comment]
With rc6?

**Comment by yvesalexandre** [comment]
Nope, I guess you rolled back to 3.0.rc4 on pip?

In [2]: pymc3.__version__
Out[2]: '3.0.rc4'

**Comment by twiecki** [comment]
https://pypi.python.org/pypi/pymc3 shows rc6 being available. How did you upgrade?

**Comment by yvesalexandre** [comment]
Just upgraded and it works great.
best, Yves-Alexandre

In [1]: import pymc3

In [2]: pymc3.__version__
Out[2]: '3.0.rc6'

**Comment by twiecki** [comment]
Great, thanks for testing.

**Comment by yvesalexandre** [comment]
Of course, thanks for the great work!
