### ISSUE TITLE
Release Candidate Six for PyPI

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1636]
I can't upload to PyPI for PyMC3 - because I think this belongs to @fonnesbeck.

I'm happy to do the Conda Forge once this is sorted out. 

The changes added in where the docs removing and the SQL change you made Chris. I updated the release candidate name.

**Comment by fonnesbeck** [comment]
Done. 

@springcoil Pass along your PyPI user name and I will add you as a manager.
