### ISSUE TITLE
Making Contours of the total likelihood for the fit parameters (including the log of prior distributions) in the pymc3, something like we make Chi square plots of shoing confindence intervals

### ISSUE THREAD

**Issue by vikaschand** [pymc-devs/pymc#1642]
Hi all,
I am using Bayesian analysis to find a linear correlation fit, I am fitting a line y = a +bx using pymc3. At last I want get Chi^2 contours between my parameters of fit 'a' and 'b'. For this I can write a different function to calculate -2logL using the sampled values of a and b then plot contours of -2logL, but is there any way in pymc3 where I can directly get Chi^2 contours.
Thanks

P.S. There are priors for parameters of the fit also, so what I need is -2logL contour plots, I have traces of a and b, but how to plot the -2logL from these and also set the confidence levels. I would like to plot full likelihood contours using the prior information also which will be addition in -2logL(without prior)-2log(prior distributions)

**Comment by fonnesbeck** [comment]
I'm going to close this because it does not appear to be a bug report. For general questions, please go to the PyMC Gitter channel or use the `pymc` tag on StackOverflow.

The only way to get contours is to derive them from the samples of the posteriors. I'd suggest using Seaborn to plot them.
