### ISSUE TITLE
Using CompletedDirichlet()

### ISSUE THREAD

**Issue by usptact** [pymc-devs/pymc#1644]
I need to have all x variables instead of x-1 variables modelled by Dirichlet(). I see in the CommonDeterministics.py file there is a class CompletedDirichlet. May be I am missing some Python basics but I cannot import that class.

How can I use CompletedDirichlet deterministic?

**Comment by ColCarroll** [comment]
`CommonDeterministics` is actually [from `pymc`](https://github.com/pymc-devs/pymc/blob/master/pymc/CommonDeterministics.py), an earlier version of this library.

**Comment by usptact** [comment]
Indeed!
