### ISSUE TITLE
ValueError: can't copy from un-initialized CudaNdarray during Metropolis using GPU for complex model

### ISSUE THREAD

**Issue by Spaak** [pymc-devs/pymc#1649]
I am now able to get simple linear regression toy models to run on the GPU, using either NUTS or Metropolis, for a speedup between ~1.5x and 3x vs CPU (total time spent sampling).

However, when I use my own more complex model, which works fine on the CPU, and also works fine using ADVI, the sampling code gives an error. I'm focusing on Metropolis for now. I'm running with `theano.config.optimizer = None` (which gives a much more informative error than `fast_compile`). This is the error:

```
  File "/home/eelke/[...]/playground_dec2016_modelchecks.py", line 198, in <module>
    trace = mc.sample(2000, step=step, start=model.test_point)
  File "/home/eelke/repos/pymc3/pymc3/sampling.py", line 175, in sample
    return sample_func(**sample_args)
  File "/home/eelke/repos/pymc3/pymc3/sampling.py", line 185, in _sample
    for strace in sampling:
  File "/home/eelke/python-venvs/newanalysis/lib/python3.4/site-packages/tqdm-4.10.0-py3.4.egg/tqdm/_tqdm.py", line 816, in __iter__
    for obj in iterable:
  File "/home/eelke/repos/pymc3/pymc3/sampling.py", line 267, in _iter_sample
    point = step.step(point)
  File "/home/eelke/repos/pymc3/pymc3/step_methods/compound.py", line 16, in step
    point = method.step(point)
  File "/home/eelke/repos/pymc3/pymc3/step_methods/arraystep.py", line 142, in step
    apoint = self.astep(bij.map(point))
  File "/home/eelke/repos/pymc3/pymc3/step_methods/metropolis.py", line 124, in astep
    q_new = metrop_select(self.delta_logp(q, q0), q, q0)
  File "/home/eelke/repos/Theano/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/eelke/repos/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/eelke/python-venvs/newanalysis/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/eelke/repos/Theano/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
ValueError: can't copy from un-initialized CudaNdarray
Apply node that caused the error: HostFromGpu(theta_i_shared)
Toposort index: 14
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(4,)]
Inputs strides: [(4,)]
Inputs values: [array([ -52.58134079,   70.22975159, -105.15395355,  -50.68397903], dtype=float32)]
Inputs type_num: [11]
Outputs clients: [[Elemwise{sub,no_inplace}(HostFromGpu.0, InplaceDimShuffle{x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
[...]
  File "/home/eelke/[...]/stokes2013-constantinidis/playground_dec2016_modelchecks.py+186", line 11, in <module>
    step = mc.Metropolis()
  File "/home/eelke/repos/pymc3/pymc3/step_methods/arraystep.py", line 60, in __new__
    step.__init__([var], *args, **kwargs)
  File "/home/eelke/repos/pymc3/pymc3/step_methods/metropolis.py", line 98, in __init__
    self.delta_logp = delta_logp(model.logpt, vars, shared)
  File "/home/eelke/repos/pymc3/pymc3/step_methods/metropolis.py", line 426, in delta_logp
    [logp0], inarray0 = pm.join_nonshared_inputs([logp], vars, shared)
  File "/home/eelke/repos/pymc3/pymc3/theanof.py", line 200, in join_nonshared_inputs
    xs_special = [theano.clone(x, replace, strict=False) for x in xs]
  File "/home/eelke/repos/pymc3/pymc3/theanof.py", line 200, in <listcomp>
    xs_special = [theano.clone(x, replace, strict=False) for x in xs]

Debugprint of the apply node: 
HostFromGpu [id A] <TensorType(float32, vector)> ''   
 |theta_i_shared [id B] <CudaNdarrayType(float32, vector)>

Storage map footprint:
 - TensorConstant{[[[[[  0.0..0e+00]]]]]}, Shape: (1, 100, 4, 4, 2000), ElemSize: 4 Byte(s), TotalSize: 12800000 Byte(s)
 - TensorConstant{[[[0 0 0 ..., 0 0 0]]]}, Shape: (100, 4, 2000), ElemSize: 8 Byte(s), TotalSize: 6400000 Byte(s)
 - TensorConstant{[[[[ 0.004..180545]]]]}, Shape: (1, 1, 4, 2000), ElemSize: 4 Byte(s), TotalSize: 32000 Byte(s)
 - TensorConstant{(4, 4) of 0.0}, Shape: (4, 4), ElemSize: 4 Byte(s), TotalSize: 64 Byte(s)
 - inarray1, Input, Shape: (16,), ElemSize: 4 Byte(s), TotalSize: 64 Byte(s)
 - inarray, Input, Shape: (16,), ElemSize: 4 Byte(s), TotalSize: 64 Byte(s)
 - gamma_i_shared, Shared Input, Shape: (4,), ElemSize: 4 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{(2,) of 4}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - theta_i_shared, Shared Input, Shape: (4,), ElemSize: 4 Byte(s), TotalSize: 16 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{16}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{1.59154951..883353e-05}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-inf}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{1.59154951..883353e-05}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{2.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-9.9999997..378752e-05}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{0.00039788..3719461262}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-0.0024999..9441206455}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-9.9999997..378752e-05}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-inf}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{-inf}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - InplaceDimShuffle{x}.0, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{200}, Shape: (), ElemSize: 2 Byte(s), TotalSize: 2.0 Byte(s)
 - InplaceDimShuffle{x}.0, Shape: (1,), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{0}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{2}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 TotalSize: 19232301.0 Byte(s) 0.018 GB
 TotalSize inputs: 19232301.0 Byte(s) 0.018 GB
```

I'm still trying to create a minimal example to reproduce this bug, but like I say simple models run fine, so this is proving a challenge, and I thought I'd post this in the meantime in case it immediately rings a bell with someone. Could it be a Theano issue, and not a PyMC3 one?

**Comment by Spaak** [comment]
The following reproduces the error (on GPU):
```
import pymc3 as mc
import theano.tensor as T

## generate some data

nb = 6
nx = 200

b_true_mean = np.random.normal(size=nb) * 5
b_true_cov = np.random.normal(size=(nb,nb))
# make symmetric and positive semidefinite
b_true_cov = np.dot(b_true_cov, b_true_cov.T)

x = np.random.multivariate_normal(b_true_mean, b_true_cov, size=nx)
y = np.dot(b_true_mean, x.T) + np.random.normal(size=nx)

## generate model

model = mc.Model()
with model:
    sigma = mc.HalfCauchy('sigma', beta=10, testval=np.asarray(2, dtype='float32'), dtype='float32')
    intercept = mc.Normal('intercept', 0, sd=10, testval=np.asarray(2, dtype='float32'), dtype='float32')
    b_model = mc.Normal('b_model', 0, sd=20, shape=(nb,), testval=np.zeros((nb,), dtype='float32'), dtype='float32')
    
    likelihood = mc.Normal('y', mu=intercept + T.dot(b_model, x.T), sd=sigma,
        observed=y.astype('float32'))
    
    step = mc.Metropolis()
    trace = mc.sample(5000, step=step)
```

It seems to have something to do with the test values and the `float32` data type, but I'm not quite sure yet what. (Edit: the way I'm generating test data is almost certainly irrelevant, this is just there because I was toying around with covariance structure in regressors.)

Edit 2: if I remove the `dtype='float32'` from the call to the distribution constructors (yet leave the `testval` exactly as above), the error disappears.

**Comment by twiecki** [comment]
> Edit 2: if I remove the dtype='float32' from the call to the distribution constructors (yet leave the testval exactly as above), the error disappears.

That's quite non-intuitive, right? I would expect all dtypes to be required to be `float32`.

It's quite clear we need to spend some time casting all data the right places, and understanding its impact. Your help with identifying that is much appreciated.

**Comment by twiecki** [comment]
> the error disappears.

and the inference runs on the GPU?

**Comment by Spaak** [comment]
> That's quite non-intuitive, right? I would expect all dtypes to be required to be float32.

Yes, I was puzzled by this too. Perhaps what's going on is Theano cannot put a `float64` on the GPU so there is no `HostFromGpu` node at all and thus no error?

> and the inference runs on the GPU?

Yes!

>It's quite clear we need to spend some time casting all data the right places, and understanding its impact. Your help with identifying that is much appreciated.

Happy to help, of course. I am now suspecting something in `join_nonshared_inputs` and related functions. If I run a model that only has one variable, it all works fine, even when `dtype='float32'` for the distribution.

**Comment by Spaak** [comment]
OK I think I found what is causing this, or at least how to prevent it from happening. If I change [this line](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/arraystep.py#L138) in `ArrayStepShared.step` from `share.container.storage[0] = point[var]` to `share.set_value(point[var])`, the error does not occur anymore and the model runs on the GPU. Apparently, `share.set_value` does something else besides simply updating the value? I don't know what was the rationale behind using a direct assignment (as the code is now)?

~~By the way, when the model runs on the GPU, sampling is either slower than CPU or basically no change, which is of course a disappointment :)~~
Edit: actually, I'm now getting a 15-20x speedup on GPU vs CPU for Metropolis! Yay! (With the change I mentioned above in place, so I guess that's the way to go?) For these figures I set `optimizer = fast_run`, it was still on `None` before.

**Comment by Spaak** [comment]
@twiecki How would you recommend I proceed with fixing this and related GPU things? I think you mentioned the `use_theano_float_type2` branch was quite behind. I'm not a proper git wizard, although I'm starting to understand it somewhat. If I understand correctly, we could rebase that branch to get it up to speed with `master`? Then I might start filing pull requests for that branch? (Although I now read that rebasing is not recommended for branches that are already shared between multiple people, i.e. that are on Github.)

Also, actually, it turns out this particular issue is only indirectly related to `floatX`. Maybe it's an idea if I create a new branch `gpu_compatibility` or so from current `master`, import the changes from `use_theano_float_type2`, and add new commits to that branch? I'd like to also try and get NUTS to run on GPU.

Alternatively I could file PRs directly against master? Or any other workflow, let me know what is best.

**Comment by ColCarroll** [comment]
@Spaak would you mind sharing a gist or something with how you're running this on the gpu?  i've been doing some work with the goal of getting HMC, NUTS, and XHMC implemented in theano -- on the `3.1` branch, HMC is already mostly there.  I haven't run things on the gpu before though, but it may be useful to have a few test/benchmarking scripts available.

**Comment by Spaak** [comment]
@ColCarroll Of course. A toy model (e.g. linear regression with a few variables) does not really get any speedup (I guess because most of the time is spent transferring stuff to/from the GPU), whereas my real model (high-dimensional, hierarchical) gets a significant speedup. I guess you would mostly be interested in the latter then? Basically the script I'm using which sets up the model and calls `sample`? It might take some time to get this together in a single gist.

By the way, the only thing which is different for GPU compatibility in my script from e.g. the various tutorial notebooks is I'm passing `dtype='float32'` to all the distribution constructors, and giving them `float32` test values.

**Comment by ColCarroll** [comment]
Even a toy model for now would be fine -- just to let me verify some stuff.

**Comment by Spaak** [comment]
@ColCarroll sure, see here for instance: https://gist.github.com/Spaak/99dc94577a700a65b63ef4864f0a0d50

This runs on the GPU.
