### ISSUE TITLE
Bump to 3.6

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1651]
Might as well move off of 3.5.  Should involve updating the docs, and the travis configuration.

**Comment by springcoil** [comment]
We've already bumped to Python 3.6 I think in the docs cc @twiecki

**Comment by ColCarroll** [comment]
Not yet in README, at least:

```
Dependencies

PyMC3 is tested on Python 2.7 and 3.5 and depends on Theano, NumPy, SciPy, Pandas, and Matplotlib (see requirements.txt for version information).
```

**Comment by ColCarroll** [comment]
Waiting for https://github.com/conda-forge/python-feedstock/pull/101 to land

**Comment by springcoil** [comment]
Anyone object to leaving this one to 3.1? Given that we need to wait on a feedstock and probably port pyqt to 3.6 if we need it.

**Comment by twiecki** [comment]
that's fine. shouldn't be a blocker. I thought we already were on 3.6

**Comment by twiecki** [comment]
Done by @ColCarroll.
