### ISSUE TITLE
minibatches issue

### ISSUE THREAD

**Issue by vkuznet** [pymc-devs/pymc#1654]
Hi, following the example of Thomas Wiecki London 2016 pymc3 talk (https://www.youtube.com/watch?v=LlzVlqVzeD8&t=2059s), I tried to run the minibatches example and fail with the following exception:
```
Traceback (most recent call last):
  File "./pymc_nn_batches.py", line 92, in <module>
    total_size=total_size, learning_rate=1e-2, epsilon=1.0
  File "/Library/Python/2.7/site-packages/pymc3/variational/advi_minibatch.py", line 394, in advi_minibatch
    e = f(*next(minibatches))
TypeError: list object is not an iterator
```
For simplicity I put code the published notebook into a stand-along python file (https://gist.github.com/vkuznet/d9496b270c5b216c591553a567be0acf) which you can grab and reproduce a problem.

**Comment by twiecki** [comment]
`advi_minibatch()` now expects an iterator for `minibatches`. Thus, you need to change:
```python
minibatches = [
    create_minibatch(X_train),
    create_minibatch(Y_train),
]
```
to:
```python
minibatches = zip(
    create_minibatch(X_train),
    create_minibatch(Y_train),
)
```

(this is on python3, use `izip` on python2).
