### ISSUE TITLE
`linear_component` should take only the right-hand side of a patsy formula.

### ISSUE THREAD

**Issue by fredcallaway** [pymc-devs/pymc#1657]
I want to model an unobserved variable as a linear combination of other variables. I was able to do this with `glm.linear_compenent` by making a minor modification to `glm.py` line 67.

    # _, dmatrix = patsy.dmatrices(formula, data)  # OLD
    dmatrix = patsy.dmatrix(formula, data)         # NEW

There's no reason to use a two-sided formula or `patsy.dmatrices` because the left-hand side isn't used (assigned to `_`). However, to avoid backwards incompatibility, it might be best to check for `~` in the formula and call the corresponding function.

**Comment by fonnesbeck** [comment]
That sounds reasonable. Do you want to do a pull request for this?

**Comment by fredcallaway** [comment]
Sure thing.
