### ISSUE TITLE
Implementing Dawid-Skene model in PyMC3

### ISSUE THREAD

**Issue by usptact** [pymc-devs/pymc#1660]
Hi,

It's been a while since I started working with Dawid-Skene model for multiple annotator vote aggregation. In nutshell, bunch of annotators with different skills cast their votes of category on work items. Work items are of different difficulty as well. The goal is to infer the latent category (distribution over categories) for each work item.

I found this Stan model to be working pretty well on large datasets. That being said, I have troubles trying to port it to PyMC3 due to the following reasons:

1. How to deal with 1- and 2- dimensional arrays of random variables which are themselves of some shape?
2. How to implement the "transformed parameters" block part where the category variable is summed out?
3. How to implement & use likelihood which is a log sum of exponentials?

For 1st, the idea is to use T.stack but I quickly got lost in shapes, dimensions and cryptic error messages. For 2nd, I think I should use theano tensor but I have very little experience here. For 3rd, I would use Potential but I am not sure.

For me, I found the beta and theta variables to be problematic.

Here is the Stan model that I am using (thanks to Bob Carpenter for advice)

`data {
  int<lower=2> K;              // number of categories
  int<lower=1> I;              // number of items
  int<lower=1> J;              // number of coders
  int<lower=1> N;              // number of observations
  int<lower=1,upper=J> jj[N];  // coder for observation n
  int<lower=1,upper=I> ii[N];  // item for observation n
  int<lower=1,upper=K> y[N];   // label for observation n
  vector<lower=0>[K] alpha;    // prior for prevalence (positive)
  vector<lower=0>[K] beta[K];  // prior for coder responses (positive)
}
parameters {
  simplex[K] pi;               // prevalence of categories
  simplex[K] theta[J,K];       // response of anotator j to category k
}
transformed parameters {
  real cat_log[I,K];           // vector of log probs (up to const) for item i
  for (i in 1:I)
    for (k in 1:K)
      cat_log[i,k] <- log(pi[k]);  // efficiency: compute log(pi[k]) once
  for (n in 1:N)
    for (k in 1:K)
      cat_log[ii[n],k] <- cat_log[ii[n],k] + log(theta[jj[n],k,y[n]]);
}
model {
  pi ~ dirichlet(alpha);
  for (j in 1:J)
    for (k in 1:K)
      theta[j,k] ~ dirichlet(beta[k]);

  for (i in 1:I)
    increment_log_prob(log_sum_exp(cat_log[i]));
}`

**Comment by twiecki** [comment]
You can supply shape directly to the RV, e.g.:

`pm.Dirichlet('x', ..., shape=(L, K))`

There is also `pm.math.logsumexp()` which does that calculation. You shouldn't have to do any explicit transformations here.

**Comment by usptact** [comment]
Thanks @twiecki ! Sorry for not following up faster (got sick) but I have few more questions:

1. According to Bob Carpenter, parameter transformation is done for more efficiency (I don't see how) and due to sampler which can work with continuous parameters only (I see).
2. Each theta_jk has a beta_k, I don't see how to create it correctly. Currently I am trying something like this (I am suspecting that it is inefficient):
`
theta = T.stack( [ [pm.Dirichlet('theta_'+str(j)+'_'+str(k),a=beta[k,:]) for k in range(K)] for j in range(J) ] )
`

**Comment by usptact** [comment]
I also tried to implement the very same model without discrete parameters summed out:

> with model:
>     pi = pm.Dirichlet( 'pi', a=alpha )
>     theta = T.stack( [ [pm.Dirichlet('theta_'+str(j)+'_'+str(k),a=beta[k,:]) for k in range(K)] for j in range(J) ] )
>     z = pm.Categorical( 'z', p=pi, shape=I )
>     for n in range( N ):
>         y = pm.Categorical( 'y_obs_'+str(n), p=theta[ jj[n], z[ii[n]] ], observed=y[n] )
>
> with model:
>     step = pm.Metropolis()
>     trace = pm.sample( 1000, step=step, progressbar=True )

The alpha is K-vector, whereas beta is KxK matrix with a dominating diagonal. Finally, the observations come in triplets ( jj[n], ii[n], y[n] ), where jj is annotator ID, ii is item ID and y is category. The index n runs from 1 to N, where N is total number of triplets.

Unfortunately I get the following error:
`Traceback (most recent call last):
  File "C:/Users/vladi/PycharmProjects/dawid-skene/dawid-skene.py", line 72, in <module>
    y = pm.Categorical( 'y_obs_'+str(n), p=theta[ jj[n] ][ z[ii[n]] ], observed=y[n] )
  File "C:\Users\vladi\Anaconda2\envs\py35\lib\site-packages\theano\tensor\var.py", line 536, in __getitem__
    return theano.tensor.subtensor.advanced_subtensor(self, *args)
  File "C:\Users\vladi\Anaconda2\envs\py35\lib\site-packages\theano\gof\op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\vladi\Anaconda2\envs\py35\lib\site-packages\theano\tensor\subtensor.py", line 2136, in make_node
    index = tuple(map(as_index_variable, index))
  File "C:\Users\vladi\Anaconda2\envs\py35\lib\site-packages\theano\tensor\subtensor.py", line 2084, in as_index_variable
    raise TypeError('index must be integers')
TypeError: index must be integers`

I am feeling stuck and don't know how to get around...

**Comment by twiecki** [comment]
Have you tried using `shape`? `pm.Dirichlet('x', ..., shape=(L, K))`.

**Comment by usptact** [comment]
@twiecki Yes. Each pm.Dirichlet(...) is parametrized by a=beta and it is expected to be L*K such variables. When I try this, I get index out of bounds error. I will post my latest script.

Thanks for being patient with me.

**Comment by usptact** [comment]
As in twitter, I post the link to my latest code with comments

https://gist.github.com/usptact/b93137a76ea321227046b8c97562929b

**Comment by usptact** [comment]
@twiecki It looks like I have ran into the issues discussed long before mine:
https://github.com/pymc-devs/pymc3/issues/824
https://github.com/pymc-devs/pymc3/issues/535
https://github.com/pymc-devs/pymc3/issues/1575

**Comment by usptact** [comment]
Version 2 of my attempt to get Dawid-Skene working (messing with shapes, wondering if that is doing what I am expecting):
https://gist.github.com/usptact/7476f3d3a3d89f38090b87e24f38ca91

**Comment by twiecki** [comment]
One important property of shape is that you need to specify the full shape of the RV you are expecting. E.g. if you want 2 3-item Dirichlet's, it would be `(2, 3)`. Sorry didn't have time to look at the code more closely yet.

**Comment by usptact** [comment]
@twiecki Thanks! No worries!

This is is what I figured and finally got running (the latest Gist). It would be great to find a way separating the size of the RV array and the shape of the multinomial nature of the RV itself...

If that code will be working as expected, I will try to contribute a notebook :)

**Comment by twiecki** [comment]
@usptact Glad you got it working! Yes, there is a PR that will seperate those out and make `shape` obsolete.

**Comment by twiecki** [comment]
You can probably also vectorize the Categorical I think.

**Comment by usptact** [comment]
@twiecki I have few more questions if I may draw your attention.

I think that I have trouble with the use of categorical variable ("z") which is expected to contain true category labels after inference is done. Looking at trace, I can't make much sense of it. I must admit that I don't really understand it.

Is there a simple example with Categorical so I can practice on it? If you have a moment, can you look at how I use it in my script?

The trace (SQLite format) after 10K samples can be downloaded here: https://dl.dropboxusercontent.com/u/78736641/dawid-skene.zip

Finally, my hunch is that in this kind of a models, initialization is important. Does it make sense to use find_MAP()? Using Metropolis(), sampling on my pretty powerful workstation is mere ~1.3 it/sec. I tried to use NUTS, but it took forever and hogged lots of memory.. and didn't even start sampling. Do you have any suggestions here? I suspect that my model definition is wrong/ill-defined.

The current script is:
https://gist.github.com/usptact/7476f3d3a3d89f38090b87e24f38ca91

**Comment by twiecki** [comment]
Here is a model with a Categorical you can explore: http://pymc-devs.github.io/pymc3/notebooks/gaussian_mixture_model.html (https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/gaussian_mixture_model.ipynb).

**Comment by usptact** [comment]
Thank you @twiecki

**Comment by usptact** [comment]
@twiecki I got the model running on real-world data! The problem was in my lack of understanding how to parametrize the observed value! Notebook coming soon.

**Comment by twiecki** [comment]
Great feeling, isn't it? :) Look forward to the notebook!

**Comment by usptact** [comment]
@twiecki Yes, you guessed it, I am very happy! It's been more than month since I tried to get this model working (in between higher priority things). I've seen other implementations (EM, Stan) but was not happy for one or another reason.

I have a more or less free evening tonight. Hopefully I will get first draft of the notebook done.

**Comment by twiecki** [comment]
What's EM? Also, could allude more to the reasons why you weren't happy? Just curious.

**Comment by usptact** [comment]
The original Dawid Skene model (1979) uses EM (Expectation Maximization) to find the point estimates of the variables of interest. The scripts and implementations I could find were pretty sketchy and ad-hoc. I also wanted more principled probabilistic approach with priors set.

The Stan version worked great, but from R only. Getting data in/out was not very comfortable (in our application). The PyStan version worked too but extraction of the trace into Python environment stalled for some reason I couldn't see.

All this (and may be few others), led to think harder how to get it working in PyMC3. Ideally I would like to vectorize the part for observations, instead of making for loop. This slows down model building significantly btw. With more observations, this can be a problem.

**Comment by AlessandroChecco** [comment]
Hi @usptact by any change could you share your code?
