### ISSUE TITLE
Run multiple dispersed chains by default

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1662]
So that convergence can adequately be evaluated, as well as to increase sampling efficiency, the default behavior of `sample` should be to use at least 2 chains. The starting points for these chains should be overdispersed. One approach could be to run ADVI, and then use the resulting SD to randomly disperse inits from the mean.

A nice extension of this would be to monitor the Gelman-Rubin diagnostic (i.e. Rhat) on the fly, and only begin recording values to the trace once convergence is achieved. This would eliminate the need for manual burn-in.

**Comment by aloctavodia** [comment]
#1655 is an attempt to provide overdispersed starting points.

**Comment by fonnesbeck** [comment]
In #1655, you select *random* points, correct? To facilitate convergence diagnostics, it may be preferable to have overdispersed inits. For example, a simple approach might be to take, say, points evenly spaced along the circle (or hypersphere, more generally) of 2sd from the optimal point from ADVI/MAP or wherever.

**Comment by aloctavodia** [comment]
Intuitively I think random initialization is a good idea, but I see your
point. What was the default behaviour of PyMC2? what about Stan?

**Comment by fonnesbeck** [comment]
Random is fine for a single chain, but if you are wanting to diagnose convergence, dispersed is more reliable. 

PyMC2 uses a random sample (but we were not thinking about multiple chains or parallel sampling back then); Stan uses dispersed, AFAIK.

**Comment by fonnesbeck** [comment]
For now, we should probably default to `init=None` whenever `njobs` is greater than one. There is no point in initializing parallel chains to the same value.

**Comment by fonnesbeck** [comment]
I'm going to take a stab at a PR for this. There are no good default starting values for multiple chains. I will use @aloctavodia 's PR as a starting point.

**Comment by fonnesbeck** [comment]
Just noticed #1655 got merged. Good stuff.
