### ISSUE TITLE
AttributeError: module 'pymc3' has no attribute 'MvGaussianRandomWalk'

### ISSUE THREAD

**Issue by fretchen** [pymc-devs/pymc#1664]
I updated to 3.1 and I can see that the MvGaussianRandomWalk is part of the timeseries.py .

However if I run:

```
import pymc3 as pm
r = pm.MvGaussianRandomWalk('r', 0)
```

I get the following error:

`AttributeError: module 'pymc3' has no attribute 'MvGaussianRandomWalk'`

Not sure what is going wrong here.

**Comment by twiecki** [comment]
`pm.distributions.timeseries.MvGaussianRandomWalk`.

**Comment by fretchen** [comment]
Perfect. I was really thrown off by the fact that pm.GaussianRandomWalk was working in living in the same file. Maybe this could be changed for consistency ...

But I think that we can actually close it for the moment.

**Comment by twiecki** [comment]
OK, I also added them to the main namespace now.
