### ISSUE TITLE
reading networks saved from other programs?

### ISSUE THREAD

**Issue by rsignell-usgs** [pymc-devs/pymc#1669]
Any capabilities or plans to read networks saved from other programs, like 
BIF, NET, DSC and DOT files as handled in this `bnlearn` R package?
http://www.bnlearn.com/documentation/man/foreign.html

**Comment by fonnesbeck** [comment]
We haven't added any explicit graphical model support yet, so no. Would be a great enhancement, I agree.

**Comment by twiecki** [comment]
Since this is not on the immediate road map I'm closing this.
