### ISSUE TITLE
Testimonials page

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#1670]
I think it might be a good idea to have a file with our testimonials. It could be elsewhere. 

I got one today from "We use PyMC3 to evaluate A/B test performance. Works great with very little code!" - Thomas Hunger https://wearewizards.io/ 

We could add some more in the future. Testimonials are great.

**Comment by fonnesbeck** [comment]
Might be better suited for a Wiki than in the code base.

**Comment by springcoil** [comment]
Created it here - https://github.com/pymc-devs/pymc3/wiki/Testimonials
