### ISSUE TITLE
GSOC 2017: NumFOCUS will be an umbrella organization

### ISSUE THREAD

**Issue by kain88-de** [pymc-devs/pymc#1673]
Hi

Organizations can start submitting applications for Google Summer of Code
2017 on January 19 (and the deadline is February 9)

https://developers.google.com/open-source/gsoc/timeline?hl=en

NumFOCUS will be applying again this year. If you want to work with us
please let me know and if you apply as an organization yourself or under a
different umbrella organization please tell me as well. If you participate
with us it would be great if you start to add possible projects to the
ideas page on github soon. We some general information for mentors on
github.

https://github.com/numfocus/gsoc/blob/master/CONTRIBUTING-mentors.md

We also have a template for ideas that might help. It lists the things
Google likes to see.

https://github.com/numfocus/gsoc/blob/master/2017/ideas-list-skeleton.md

In case you participated in earlier years with NumFOCUS there are some
small changes this year. Raniere won't be the admin this year. Instead I'm
going to be the admin. We are also planning to include two explicit rules
when a student should be failed, they have to communicate regularly and
commit code into your development branch at the end of the summer.

best, Max

**Comment by springcoil** [comment]
Anyone have any ideas? Maybe we should start marking out some `easy to commit` issues. cc @ColCarroll @twiecki @fonnesbeck @AustinRochford

**Comment by springcoil** [comment]
Maybe something related to this one - https://github.com/pymc-devs/pymc3/pull/1338 I think that a good student with some understanding of HPC/ numerical programming could nail that one.

**Comment by springcoil** [comment]
Or this one (and maybe some related ones) https://github.com/pymc-devs/pymc3/pull/1614 - it's something I've just not had time to fix :)

**Comment by twiecki** [comment]
https://github.com/numfocus/gsoc/issues/152

**Comment by ColCarroll** [comment]
It sounds like GSOC is looking for a summer-sized problem that someone could tackle?  I agree we should have an `easy` tag (and maybe other tags!) to encourage new contributors, but this sounds like something more.  

My own wishlist involves 
-- make sampling methods pure theano
-- get rid of recursive calls, especially in NUTS (I look at them with suspicion when there are [issues about memory](http://stackoverflow.com/questions/27564825/recursive-functions-memory-usage))
-- some way to monitor for performance regressions (wes mckinney worked on [something like this once](http://wesmckinney.com/blog/introducing-vbench-new-code-performance-analysis-and-monitoring-tool/)).  This one would probably be an independent project.

**Comment by twiecki** [comment]
I like all of these ideas. Perhaps we should start a wiki.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/wiki/GSoC-2017-projects

**Comment by kain88-de** [comment]
@twiecki It would be nice if you can add the projects to the numFocus repository. Google will look there for projects when we apply.

**Comment by twiecki** [comment]
@kain88-de Sure, would just need to somehow give pymc3-devs edit privileges. Or we first collect ideas here and then add them to the issue.

**Comment by kain88-de** [comment]
You can create PR's for project-ideas. There is a [skeleton](https://github.com/numfocus/gsoc/blob/master/2017/ideas-list-skeleton.md) for ideas that you can use. I don't mind if that happens to be more then one PR for pymc.

**Comment by fonnesbeck** [comment]
We have a [wiki full of ideas](https://github.com/pymc-devs/pymc3/wiki/PyMC-3-Wish-List) if anyone needs inspiration.

**Comment by kain88-de** [comment]
@twiecki I've updated the numfocus project. It would be nice if you could add your mentors to the [team](https://github.com/numfocus/gsoc/blob/master/organization/team.md) once you have them. Thanks.

**Comment by kain88-de** [comment]
@twiecki it would be nice if you could fill your ideas list with some more details. For each project a short 3-4 line description and what you expect/recommend from a student who wants to tackle the project.
