### ISSUE TITLE
Feature request: negative binomial distribution for glm

### ISSUE THREAD

**Issue by hanfang** [pymc-devs/pymc#1688]
Hi,

I am wondering if you have plans to include negative binomial distribution in `glm.families`? To be specific, I meant as a new class in [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/glm/families.py). This distribution could be very useful when dealing with over-dispersed count data. Thanks.

**Comment by twiecki** [comment]
@hanfang Probably fastest if you were to implement this in a PR.

**Comment by jonathanhfriedman** [comment]
I've implemented this and can replicate [this negative binomial regression example](http://www.ats.ucla.edu/stat/dae/). Regarding the default prior on alpha for the negative binomial distribution: Half-Cauchy seems like a reasonable choice works fine for me, but I'm not sure as to whether there's a better/more traditional option.

**Comment by springcoil** [comment]
Open a PR ☺

**Comment by hanfang** [comment]
Thanks @jonathanhfriedman !

**Comment by hanfang** [comment]
Closed. Please refer to https://github.com/pymc-devs/pymc3/pull/1726
