### ISSUE TITLE
PyMC3 release on conda crashes: illegal hardware instruction

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1691]
Installing PyMC3 from conda into a clean virtualenv results in an unstable system that reliably crashes. Specifically, creating and specifying a model results in a `illegal hardware instruction` error that crashes the Python session. The only thing that seems to fix it is to install both theano and pymc3 with pip instead of conda.

Running Python 3.5 (Anaconda) on macOS 10.12.

If this is a replicable error, we need to get to the bottom of it and release a fix in 3.0.1 as soon as possible.

**Comment by springcoil** [comment]
I was unable to reproduce this. Can you outline a script or something maybe someone else can.

**Comment by fonnesbeck** [comment]
I cannot produce this on a second machine. Closing for now. If anyone else sees this on the 2016 MacBook Pro, please let us know.

**Comment by jeiros** [comment]
I'm getting an `Illegal instruction: 4` error (full traceback [here](http://lpaste.net/raw/8028890002035310592)) on a macOS Sierra Version 10.12.3.
I installed pymc3 on a new conda env in three different ways,  all giving the same error. I've tried:

1. `pip install pymc3`
2. `conda install -c conda-forge pymc3`
3. Cloning the repo, pip-install the `requirements.txt` and the running `python setup.py install` on the repo.

All three failed. The code I'm trying to run is the one from the tutorial:
```python
import numpy as np
import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt
np.random.seed(123)
alpha, sigma = 1, 1
beta = [1, 2.5]
size = 100
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2
Y = alpha + beta[0]*X1 + beta[1]*X2 + np.random.randn(size)*sigma
fig, axes = plt.subplots(1, 2, sharex=True, figsize=(10,4))
axes[0].scatter(X1, Y)
axes[1].scatter(X2, Y)
axes[0].set_ylabel('Y'); axes[0].set_xlabel('X1'); axes[1].set_xlabel('X2');
from pymc3 import Model, Normal, HalfNormal
basic_model = Model()
with basic_model:
    # Priors for unknown model parameters
    alpha = Normal('alpha', mu=0, sd=10)
    beta = Normal('beta', mu=0, sd=10, shape=2)
    sigma = HalfNormal('sigma', sd=1)
    # Expected value of outcome
    mu = alpha + beta[0]*X1 + beta[1]*X2
    # Likelihood (sampling distribution) of observations
    Y_obs = Normal('Y_obs', mu=mu, sd=sigma, observed=Y)
```

**Comment by jiafengkevinchen** [comment]
I got an `Illegal instruction: 4` with a Macbook Pro 2016 running Sierra 10.12.3. I `pip uninstall`-ed both `theano` and `pymc3`. I then reinstalled with 
`pip install git+https://github.com/Theano/Theano.git#egg=Theano` and `pip install git+https://github.com/pymc-devs/pymc3` instead of `pip install theano` and `pip install pymc3`. This seems to fix it.
