### ISSUE TITLE
Possible 50% speedup for NUTS

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1693]
The function `trajectory._theano_single_leapfrog` generates a theano function `(q, p, epsilon) -> (q_new, p_new, energy)`. This theano function internally computes H.dlogp(q) and H.dlogp(q_new). In NUTS, this function is called for the new values (q_new, p_new), which computes H.dlogp(q_new) a second time.
If we change the theano function to something like `(q, p, grad_q, epsilon) -> (q_new, p_new, grad_q_new, energy)` and always store the gradient grad_q_new alongside q_new in the recursive algorithm, we could save one of two gradient evaluations for all leapfrog steps but the first (we still need to manually compute the first gradient). Since computing the gradient takes most of the time in complicated models, this should save about half the time (but use a bit more memory for storing the additional gradients).

**Comment by ColCarroll** [comment]
That's a great and pretty subtle observation -- let me do some experiments with that!  When implementing this, I added the separate leapfrog step for NUTS, since the `scan` op with loop size 1 was so slow.  (which is to say: "I find it hard to reason about theano performance")
