### ISSUE TITLE
Posterior predictive sampling with shared variables broken

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1695]
Posterior predictive sampling in models that use `theano.shared` variables appears to be broken; see https://gist.github.com/AustinRochford/b46835738b9f8c4a05d0d6f63ec631ad for a minimal example.

The problem appears to be that when the shape of the shared variable changes, the shape of the `pymc3` variable is not updated; see the final cell of the linked notebook.

I have confirmed that the logistic regression example in the [PPC example notebook](http://pymc-devs.github.io/pymc3/notebooks/posterior_predictive.html) also fails similarly.

**Comment by springcoil** [comment]
Can you share your conda environment/ docker environment and theano version?

**Comment by AustinRochford** [comment]
This is using a fresh container from the `pymc3` `Dockerfile`.  The `theano` version is 0.9.0dev5.dev-9b0f65a8f39134e3adba8a95965c6436cca6d503

**Comment by springcoil** [comment]
The error doesn't happen on.
```
CPython 3.5.2
IPython 5.1.0

theano 0.8.2

compiler   : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)
system     : Darwin
release    : 16.3.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
CPython 3.5.2
IPython 5.1.0

pymc3 3.0

compiler   : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)
system     : Darwin
release    : 16.3.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
```

**Comment by springcoil** [comment]
So it's quite possible that there's a bug in theano or something. Any views @twiecki?

**Comment by fonnesbeck** [comment]
I've replicated this as well with:

```
CPython 3.5.2
IPython 5.1.0

pymc3 3.0
theano 0.9.0dev4.dev-1a42bf9b2b0d02440f6968191e33c5fa858f365f
numpy 1.11.2

compiler   : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)
system     : Darwin
release    : 16.3.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit
```

PyMC3 is current master.

**Comment by springcoil** [comment]
Maybe `git bisect` could tell us when this occured.

**Comment by twiecki** [comment]
I bet that's https://github.com/pymc-devs/pymc3/pull/1585 CC @ferrine.

**Comment by ferrine** [comment]
Cannot be that because of non dynamic shape.

**Comment by ferrine** [comment]
in that PR I rely on dist shape, so samples should have the same shape. I think earlier there was similar problem as samples were reshaped using `prefix_shape`

**Comment by AustinRochford** [comment]
Per `git-bisect`, the first bad commit is [e93def343b5add2be72076be7526b043c81807b2](https://github.com/pymc-devs/pymc3/commit/e93def343b5add2be72076be7526b043c81807b2).  @ferrine any thoughts?

**Comment by AustinRochford** [comment]
The problem appears to be when `repeat_shape` and `dist_shape` are both `()` in [`reshape_sampled`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/distribution.py#L283); I'm working up a quick fix and test.
