### ISSUE TITLE
clarification on WishartBartlett

### ISSUE THREAD

**Issue by laudney** [pymc-devs/pymc#1700]
> def WishartBartlett(name, S, nu, is_cholesky=False, return_cholesky=False, testval=None):

I'd like to use WishartBartlett to model covariance matrix and I have a sample covariance as prior.

1. Should I pass in *np.diagonal(sample_cov)* for *S* or the inverse of it?
2. Should I pass in *sample_cov* for *testval* or the inverse of it?

Thanks

**Comment by twiecki** [comment]
the sample covariance.
