### ISSUE TITLE
Modelling PK data question and is there a user group to ask non-dev related q's?

### ISSUE THREAD

**Issue by MarkPinches** [pymc-devs/pymc#1705]
Hi,
Firstly I am really enjoying using pymc3, and I would just like to thank all the contributors for your efforts. It is outstanding!

I am using pymc3 to perform some pharmacokinetic modelling. I have generated some example data and was expecting to resolve back to the original parameters used to define the test data. However I am unable to do this. I wonder therefore if someone with more experience in bayesian modelling could review my work and make suggestions.  Here is a link to the notebook on git.
[https://github.com/MarkPinches/test/blob/master/Simple%20PK%20modelling.ipynb](url)

I completely understand that this is probably not the appropriate forum for this question, however I have been unable to find a "user group" that would be more appropriate for posting this question. So if you could just point me in the right direction that would be great too.

Thanks!
Mark

**Comment by fonnesbeck** [comment]
Hi Mark. The best places to ask questions and get feedback are:

- [The PyMC Gitter channel](https://gitter.im/pymc-devs/pymc)
- [StackOverflow with the `pymc` tag](http://stackoverflow.com/questions/tagged/pymc)

Thanks for your interest. I may have a peek at your work if I get a chance.

**Comment by twiecki** [comment]
StackOverflow is best for that.

**Comment by MarkPinches** [comment]
Thanks for the pointers Chris. As it happens I re-reviewed the excellent example on multi-level modelling and that helped enormously. I now have a working model with output as I expected.  In addition I will work through your notebook with more extensive examples of multilevel modelling next.

Thanks again!
