### ISSUE TITLE
Shadowing builtin `vars`

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#1710]
I'm working on enabling most pylint checks, and right now a lot of functions shadow the builtin `vars`.  I've never actually used this, but the documentation:
```
Without arguments, equivalent to locals().
With an argument, equivalent to object.__dict__.
```
Wanted to know if there were strong feelings about:
1. Leave as is
2. Change all instances to `vars_`
3. Choose a different variable name

**Comment by ferrine** [comment]
First option LGTM. I see no bad in this

**Comment by fonnesbeck** [comment]
Is there a downside to changing it to `variables`?

**Comment by ferrine** [comment]
@fonnesbeck too long key word argument for functions, change in API

**Comment by ColCarroll** [comment]
The dangerous thing about changing it is that it is an argument to lots of constructors.  

The dangerous thing about not changing it is that it can mask funny behavior.  

I tend to side with @ferrine that 1 is the best choice.  If we wanted to change it, we'd probably start now with deprecation warnings, and not remove it until the next major release.

**Comment by fonnesbeck** [comment]
I'm fine with that decision. Feel free to close.

**Comment by ColCarroll** [comment]
leaving it the same!
