### ISSUE TITLE
Convert test_distributions.TestMatchesScipy to hypothesis

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1711]
[`pymc3.tests.test_distributions.TestMatchesScipy`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_distributions.py#L272-L705) currently tests over a parameter grid using a custom setup.  I've been thinking about converting these to use a generative testing framework (I am personally familiar with [`hypothesis`](https://github.com/HypothesisWorks/hypothesis-python/), but would be open to others).  I think this could potentially streamline a bunch of the custom test harness code from that module.

I would love to get people's thoughts on this.

**Comment by twiecki** [comment]
Yeah, I think that'd be cleaner. Do you have a quick example of what that could look like in practice?

**Comment by AustinRochford** [comment]
I'll try to whip something up over the weekend.

**Comment by ColCarroll** [comment]
I've been interested in trying out hypothesis for a while -- let me know if
you need/want any help!

**Comment by AustinRochford** [comment]
@ColCarroll I'll put a small example together soon and if we decide to go with this, let's definitely collaborate on it.

**Comment by springcoil** [comment]
Happy to review this, we used Hypothesis at work recently :)

**Comment by AustinRochford** [comment]
Interestingly, just prototyping the most basic hypothesis tests seems to have uncovered examples where the passage of the current tests relies on the fixed grid points chosen.

https://gist.github.com/AustinRochford/52828a84cb5eb0311b843aeba96c2efa

**Comment by AustinRochford** [comment]
I'm not sure whether we need that much precision, but it is interesting.

**Comment by twiecki** [comment]
That's really succinct code. I don't find deviations on that scale surprising given the differences in backends.

**Comment by AustinRochford** [comment]
Me neither.

**Comment by AustinRochford** [comment]
@twiecki @ColCarroll @springcoil I think something along the lines of 

https://gist.github.com/AustinRochford/52828a84cb5eb0311b843aeba96c2efa

has similar coverage to the current testing strategy and is quite simple and readable. The downside is, that single test takes ~1 minute to run.  My guess is theano is recompiling something every time hypothesis calls the test.  Any ideas on how to avoid this?  Also, will likely want to not use `SeededTest` to increase the set of values that hypothesis will generate.

**Comment by ColCarroll** [comment]
I'll poke around for the speed side of things.  The whole test suite could
use a going over.

The benefit of `SeededTest` (and the test suite right now) is that it
guarantees tests that passed in the past will continue to pass in the
future.  This seems like it is a more comprehensive test, but it is *not* a
regression test, so it could be more flaky.  There is a way to tell travis
that certain tests are allowed to fail.  We may want to run these alongside
the main test suite for a while to see how much of a signal it gives.

**Comment by AustinRochford** [comment]
> We may want to run these alongside the main test suite for a while to see how much of a signal it gives.

This is a great idea.

There is a way to also get hypothesis to include fixed values in its testing, so we could perhaps with a bit of work also duplicate the function of the current regression tests.  It might be nice to have them all use the same framework.

**Comment by AustinRochford** [comment]
@ColCarroll in addition to `hypothesis` you will also have to install `hypothesis[numpy]`, which is an extra package.

**Comment by souravsingh** [comment]
@AustinRochford Is the test mentioned in the gist the only test that needs to be added?

**Comment by AustinRochford** [comment]
@souravsingh no, I think that before merging this we would want test parity with the current `test_distributions` module.

**Comment by twiecki** [comment]
Feel free to reopen if this is still an issue.
