### ISSUE TITLE
Local variable referenced before assignment

### ISSUE THREAD

**Issue by maedoc** [pymc-devs/pymc#1712]
I interrupted a model running on git master and noticed the traceback ending not with a `KeyboardInterrupt` but

```python
/extern/pymc3/pymc3/sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    193             pass
    194     except KeyboardInterrupt:
--> 195         strace.close()
    196     return MultiTrace([strace])
    197 

UnboundLocalError: local variable 'strace' referenced before assignment
```

it's not a big deal for me but it may be worth looking into.

**Comment by ColCarroll** [comment]
Wow!  I told pylint to ignore that this morning!  Let me look around for an
empty trace to possibly initialize with.

**Comment by maedoc** [comment]
Looking at [the code](https://github.com/pymc-devs/pymc3/blob/master/pymc3/sampling.py#L191), it can only happen if an interrupt occurs while waiting for the first `strace` from `sampling` in which case you could

```python
try:
    strace = None
    for strace in sampling:
        pass
except KeyboardInterrupt:
    if strace is not None:
        strace.close()
```

 unless `strace.close()` should read `trace.close()`, idk.

**Comment by ColCarroll** [comment]
There's also the issue of `sampling` being an empty iterator.

**Comment by maedoc** [comment]
If `sampling` is empty, at least this binds `strace` to `None`, and it won't try to call `close`.

**Comment by ColCarroll** [comment]
Yeah, someone will just have to make sure that `MultiTrace([None])` will do
something reasonable.  I can look into that tonight, unless you have time
to put a small PR together?

**Comment by maedoc** [comment]
D'oh, didn't even see that. Probably best to reraise the `KeyboardInterrupt`. Yeah I've got a branch here with it, just waiting for tests to finish.
