### ISSUE TITLE
Samples are all the same

### ISSUE THREAD

**Issue by ihincks** [pymc-devs/pymc#1718]
I am trying to do simple parameter estimation on a beta-binomial model. I am interested in inferring `mu0` and `t0`, where `mu` is the mean of the beta distribution, and `t` encodes the variance in such a way that `s2=t*mu^2*(1-mu)^2`, where `s2` is the variance of the beta distribution. Here is the code to generate data:

```
%matplotlib inline
import pymc3 as mc
import numpy as np
import matplotlib.pyplot as plt

mu0 = 0.6
t0 = 0.1
# formulas to turn the above into alpha/beta params of beta distribution
a = 1/(t0-t0*mu0)-mu0
b = 1/(t0*mu0)-1+mu0
Nbin = 100
Nsamp = 30
ps = np.random.beta(a,b,Nsamp)
data = np.random.binomial(Nbin,ps)
```

And here is the model:

```
model = mc.Model()
with model:
    mu = mc.Beta('mu', 1,1)
    t = mc.Beta('t',1,1)
    alpha = 1/(t-t*mu)-mu
    beta = 1/(t*mu)-1+mu

    x = mc.BetaBinomial('x',alpha,beta,n=Nbin,observed=data)
    trace = mc.sample(10000, mc.NUTS(), progressbar=True)
```

Now if I look at the trace, all samples are identically equal to `0.5` for both parameters. If I reduce the number of data points to `Nsamp=15`, then things work as expected. If I change the sampler to `Slice`, then it works. However, I hope to generalize the model to many more parameters, where I expect `Slice` to suck.

**Comment by fonnesbeck** [comment]
This just means that the variables were initialized at a value that the sampler is having difficulty with, so it is not changing. You can try using something like `init='nuts'` and see if that helps.

BTW, 10000 samples is overkill for using the `NUTS` sampler. 1000 or 2000 should be plenty.

**Comment by fonnesbeck** [comment]
Just running `trace = mc.sample(1000)` seems to work fine:

```
Auto-assigning NUTS sampler...
Initializing NUTS using advi...
Average ELBO = -116.66: 100%|████████| 200000/200000 [00:13<00:00, 14646.96it/s]
Finished [100%]: Average ELBO = -116.65
100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1857.96it/s]

mu:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------
  
  0.603            0.022            0.001            [0.567, 0.647]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|
  
  0.566          0.589          0.602          0.616          0.647


t:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------
  
  0.164            0.056            0.003            [0.080, 0.286]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|
  
  0.081          0.120          0.157          0.197          0.299
```

**Comment by ihincks** [comment]
@fonnesbeck Thanks for the tips! Is there a way to increase verbosity or something to find out exactly what is happening during initialization? For example, how do I find out the difference between `trace=mc.sample(1000)` and `trace=mc.sample(1000,mc.NUTS(),init='advi',n_init=200000)`?

**Comment by fonnesbeck** [comment]
You can check the default argument values for calls to `sample` by looking at its docstring. In fact what you have is basically it, assuming the variables are all continuous.

**Comment by twiecki** [comment]
Actually it's not the same, passing in a step-method, I think, does not do auto-init via ADVI.
