### ISSUE TITLE
How to create Normal Custom distribution

### ISSUE THREAD

**Issue by sada-narayanappa** [pymc-devs/pymc#1723]
I am trying to create a Normal distribution with mean=8, sd=2 and  has a lower limit of 5.

In other words it is a normal distribution (8,2) but instead of -infinity to infinity, it cuts off at 8.

Thanks

**Comment by fonnesbeck** [comment]
The best place to ask questions is either on our Gitter channel, or on StackOverflow with the PyMC tag. This issue tracker is for bug reporting.
