### ISSUE TITLE
Custom distribution

### ISSUE THREAD

**Issue by sada-narayanappa** [pymc-devs/pymc#1724]
HI

I am confused about custom distributions, basically because I am not able to wrap my head around how it works. Perhaps a post on it would be super useful.

I am trying to create a distribution that is a combination of 

-15% to -5% with 25% probability
0 to 5% with 75 % probability.

Essentially trying to solve the problem given in page 3-11:
http://faculty.insead.edu/delquie/msp/Other%20downloads/Crystal%20Ball%20Tutorial.pdf

Can you please help me how to go about doing it.

P.S> BTW thanks for adding Triangular Distribution; Still waiting for next release.

**Comment by fonnesbeck** [comment]
The best place to ask questions is either on our Gitter channel, or on StackOverflow with the PyMC tag. This issue tracker is for bug reporting.
