### ISSUE TITLE
pymc3/models?

### ISSUE THREAD

**Issue by PaulSorenson** [pymc-devs/pymc#1728]
After fresh clone from github: 

[pms@spidey pymc3]$ sudo pip3 install --upgrade .
Processing /home/pms/build/pymc3
    Complete output from command python setup.py egg_info:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running egg_info
    creating pip-egg-info/pymc3.egg-info
    writing requirements to pip-egg-info/pymc3.egg-info/requires.txt
    writing pip-egg-info/pymc3.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pymc3.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/pymc3.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pymc3.egg-info/SOURCES.txt'
    error: package directory 'pymc3/models' does not exist

**Comment by fonnesbeck** [comment]
Can you try `pip3 install --upgrade -e .` I take it this is not Anaconda if you are using `sudo`?

**Comment by twiecki** [comment]
Fixed by https://github.com/pymc-devs/pymc3/commit/c708345a38e1812eeb24df68a907e099b52c48e0.
