### ISSUE TITLE
mistake on guideline

### ISSUE THREAD

**Issue by keithyin** [pymc-devs/pymc#1741]
I think there is a little mistake on this [website](https://pymc-devs.github.io/pymc3/notebooks/posterior_predictive.html)`This function will randomly draw 50 samples of parameters from the trace. Then, for each sample, it will draw 100 random numbers from a normal distribution specified by the values of mu and std in that sample.`,  in `Examples->Posterior Predictive Checks`. It might be 500 samples instead of 50 samples

**Comment by twiecki** [comment]
Yes, indeed. Want to submit a PR to get credit for the fix?

**Comment by twiecki** [comment]
Closed by #1750.
