### ISSUE TITLE
Implementing non parameteric Bayesian Methods

### ISSUE THREAD

**Issue by souravsingh** [pymc-devs/pymc#1748]
Hello,

I am interested in working on adding non-parameteric Bayesian methods as part of GSoC 2017.

The wiki mentions about adding following things-
1) Implement Dirichlet processes
2) Implement Polya Tree mixtures
3) Improvements to Gaussian Processes

I also add the following ideas, which could be done as part of the project-
1) Implement Pitman-Yor Processes.
2) Implement Indian Buffet Process.

I am looking at giving a long-term commitment to PyMC3. So if I don't get selected for GSoC under PyMC3, I will still be interested in working on the project. 

cc @twiecki @AustinRochford

**Comment by twiecki** [comment]
Hi @souravsingh, we're excited to have you contribute.

Those would all be great additions. I think it's probably easiest to start with DP and try to productize the code from @AustinRochford's notebook example. 

@AustinRochford Thoughts?

**Comment by AustinRochford** [comment]
Hi @souravsingh.  I think @twiecki is right that building the Dirichlet process (and then perhaps a HDP) into pymc3 would be the right place to start.

**Comment by souravsingh** [comment]
@twiecki Is there a Developer Guide on writing methods and tests for pymc3? And How should I start with the implemntation?

**Comment by springcoil** [comment]
I would just follow the code so pattern match based on that.
I don't believe we have a developer guide for tests and methods.

**Comment by souravsingh** [comment]
@twiecki Is the project on adding support for Time-series models open for students? I am interested in the project since I have just finished a course on the same.

**Comment by twiecki** [comment]
@souravsingh Yes, that's open.

**Comment by rpgoldman** [comment]
Closed for lack of discussion.
