### ISSUE TITLE
ADVI fails on random effects models where the random effects influence two observed quantitites

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1764]
See this [notebook](https://gist.github.com/AustinRochford/256d044ae8cf9f67d1fc92897fafc48d) for a simulated example.  ADVI works with only one observed quantity and works intermittently (depending on the seed) with two observed quantities and no random effects.

**Comment by twiecki** [comment]
CC @taku-y

**Comment by twiecki** [comment]
It would be useful to also output the point where the nan occured.

**Comment by AustinRochford** [comment]
Good call, I modified the code to print `uw` and updated the notebook.

**Comment by twiecki** [comment]
Even better would be to pass the array through a bijection mapping to get the dictionary representation.

**Comment by AustinRochford** [comment]
Done, notebook updated.  Since it fails on the first iteration, I just printed `start`.

**Comment by twiecki** [comment]
Try random inits.

**Comment by fonnesbeck** [comment]
Just so happens I have a pull request for random inits #1744

**Comment by AustinRochford** [comment]
Updated the notebook to use random inits, ADVI still fails on the first iteration across a range of seed.

@fonnesbeck nice PR, will be glad to see that land

**Comment by AustinRochford** [comment]
There is a (kind of gross) workaround to still use (mostly) ADVI to initialize NUTS for this model [here](https://gist.github.com/AustinRochford/9c54b331ccc42a573099a06cd704ef8c).

**Comment by twiecki** [comment]
What does ADVI estimate for stds of gamma and err_log?

**Comment by AustinRochford** [comment]
The original problem is not being able to run ADVI with those in the model, so I'm not sure.

**Comment by junpenglao** [comment]
Tried with the new VI api:
```python
with model:
    approx = pm.ADVI()
```
The problem is that, the initial approximation parameters are nan: `approx.approx.params[0].eval()` returns nan.

Setting the value manually to zero solve this:
```python
mu_approx = approx.approx.params[0]
rho_approx = approx.approx.params[1]

mu_approx.set_value(np.zeros(mu_approx.eval().shape))
rho_approx.set_value(np.zeros(rho_approx.eval().shape))
```

@ferrine is there a way to check this before running the optimization? Is it a good idea to always set the initial values to 0? (I guess for meanfield and full-rank it should be fine, but not sure for other approximations)

**Comment by ferrine** [comment]
@junpenglao setting all to zero might not be the best idea. We can replace inf or nan with normal distributed value instead.

**Comment by junpenglao** [comment]
Yep sounds like a fine solution.
