### ISSUE TITLE
Fix GLM references in docs and add alias

### ISSUE THREAD

**Issue by PaulSorenson** [pymc-devs/pymc#1768]
AttributeError                            Traceback (most recent call last)
<ipython-input-22-715d32165b90> in <module>()
      1 with pm.Model() as model:
----> 2     pm.glm.glm('Generation ~ dailyEnergy + weekday', df)

AttributeError: module 'pymc3.glm' has no attribute 'glm'

**Comment by twiecki** [comment]
Can you try with `pm.glm.GLM` instead? Should probably add an alias.

**Comment by PaulSorenson** [comment]
Now I remember what happened when I tried GLM - this was from an existing, stable model.  Same thing happens in notebooks/GLM-linear.ipynb (and presumably others) after I changed case on glm.

ValueError                                Traceback (most recent call last)
<ipython-input-23-0667753930f9> in <module>()
      1 with pm.Model() as model:
----> 2     pm.glm.GLM('Generation ~ dailyEnergy + weekday', df)

/usr/lib/python3.5/site-packages/pymc3/model.py in __call__(cls, *args, **kwargs)
    193         instance = cls.__new__(cls, *args, **kwargs)
    194         with instance:  # appends context
--> 195             instance.__init__(*args, **kwargs)
    196         return instance
    197 

/usr/lib/python3.5/site-packages/pymc3/glm/linear.py in __init__(self, x, y, intercept, labels, priors, vars, family, name, model)
    109         super(GLM, self).__init__(
    110             x, y, intercept=intercept, labels=labels,
--> 111             priors=priors, vars=vars, name=name, model=model
    112         )
    113 

/usr/lib/python3.5/site-packages/pymc3/glm/linear.py in __init__(self, x, y, intercept, labels, priors, vars, name, model)
     38         if vars is None:
     39             vars = {}
---> 40         x, labels = any_to_tensor_and_labels(x, labels)
     41         # now we have x, shape and labels
     42         if intercept:

/usr/lib/python3.5/site-packages/pymc3/glm/utils.py in any_to_tensor_and_labels(x, labels)
     74         x = np.asarray(x)
     75         if x.ndim == 0:
---> 76             raise ValueError('Cannot use scalars')
     77         elif x.ndim == 1:
     78             x = x[:, None]

ValueError: Cannot use scalars

**Comment by PaulSorenson** [comment]
formula string is being passed to any_to_tensor_and_labels()

**Comment by ferrine** [comment]
Hi! You should try `pm.glm.GLM.from_formula('Generation ~ dailyEnergy + weekday', df)`

**Comment by PaulSorenson** [comment]
Thanks that did the trick.  Quite a few notebooks and blogs around the place use the earlier syntax the idea of an alias is a good one.

**Comment by bhargavvader** [comment]
Can this be closed? Or do we keep this open because we would want a `zoo` module sometime in the future?
