### ISSUE TITLE
pymc3.effective_n can return negative results

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1770]
In traces with negative autocorrelation pymc3 sometimes returns negative estimates for the number of effective samples:
```python
import pymc3

class DummyTrace:
    varnames = ['a']
    nchains = 2
    def get_values(self, *args, **kwargs):
        return [[0, 1, 0, 1], [0, 1, 0, 1]]
    
pymc3.effective_n(DummyTrace())
```
This returns `{'a': -8.0}`

**Comment by twiecki** [comment]
CC @aloctavodia.

**Comment by aloctavodia** [comment]
@twiecki I have not worked on the effective sample size (probably you are thinking about the effective number of parameters). Anyway I can take a look at this tonight. Is clear that it should handle negative correlation.

**Comment by twiecki** [comment]
Thanks @aloctavodia. I had somehow assumed you worked on this, didn't mean to pressure you into fixing this but appreciate you taking a look.
