### ISSUE TITLE
Stop ADVI dynamically

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1778]
ADVI is run for a fixed amount of iterations. Better would be to assess convergence via a running-mean of the elbo and stop automatically if no meaningful change is found.

**Comment by bhargavvader** [comment]
Could you confirm if [L142](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/advi.py#L142) is what controls the number of iterations right now? We'd like to escape this if it converges, right?

**Comment by twiecki** [comment]
@bhargavvader Exactly.

**Comment by lbollar** [comment]
Interested in working on this. Would the best way to implement this be to basically set up something like a tolerance argument that user would specify? Would you track mean including full history of ELBO? I didn't know if there were any common practices for checking for convergence of the ELBO.

**Comment by twiecki** [comment]
@lbollar Great! We should probably do whatever stan is doing: https://github.com/stan-dev/stan/blob/1c2075bf8d0fe563b6907e40220aca016864e816/src/stan/variational/advi.hpp#L328

**Comment by lbollar** [comment]
Great, I didn't even think to look there. Looks like they are checking both mean and median convergence using same tolerance argument. Is it best to duplicate that then?

**Comment by twiecki** [comment]
Yes.

**Comment by bhargavvader** [comment]
I'm following this as well - interested to see the solution. :)

**Comment by twiecki** [comment]
Great job @lbollar.

**Comment by fonnesbeck** [comment]
Does #1795 automatically stop ADVI? I thought it just does the checking.

**Comment by twiecki** [comment]
it stops it if convergence is achieved.

**Comment by fonnesbeck** [comment]
So it does. I wonder if it is a little anti-conservative in its stopping rule, based on a visual inspection of the ELBO:

![](http://d.pr/i/Kjb0+)

It might be nice to have an option for turning auto-stopping on or off. Maybe `n=None` could turn the rule on (since specifying a number of iterations is redundant), while specifying a certain number of iterations would turn it off?

**Comment by twiecki** [comment]
You can set `tol_obj` to 0 to turn it off. Or just lower it to see if the convergence looks better.

**Comment by lbollar** [comment]
That was what I thought original implementation should be. I was trying to
duplicate behavior in Stan and didn't see option to not have convergence
checking, but I agree more flexibility makes sense to me.
