### ISSUE TITLE
Online modeling

### ISSUE THREAD

**Issue by usptact** [pymc-devs/pymc#1780]
I am curious whether it is possible to perform initial model fitting followed by incremental model updates and draws from posterior? My data is i.i.d. and if I remember basics right, the Bayesian paradigm is by its nature online -- use posterior from previous step as prior to update the model.

Consider the following example. I have a small dataset of coin flips. I run the classic Beta-Binomial model to find the posterior for the theta parameter (parameter to Bernoulli distribution). Now, instead of fixing the model and using the trace, I would like to perform online updates and drawing from posterior: At some points of the time I have new data points that I can use to improve the model, at some points of time I am using only the most recent posterior.

Is this possible in PyMC3 framework? May be there is an example that shows how to do this?

The only approach I see is to re-fit the model every single time the dataset of observations is updated. This is of course time consuming.

**Comment by twiecki** [comment]
Not possible, unfortunately. I saw some work with particle samplers that allow this.

**Comment by usptact** [comment]
Thanks @twiecki I was suspecting this was the case. Thanks for the mention of particle samplers (read about them some time ago but got lost quickly in technical details).

I will close this ticket then.
