### ISSUE TITLE
Detect transformed RVs without doing endswith('_')

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1783]
There are a [bunch of places](https://github.com/pymc-devs/pymc3/search?utf8=%E2%9C%93&q=endswith%28%27_%27%29) in the code that determine whether or not a variable is transformed by checking `var.name.endswith('_')` which is brittle.  It should not be too difficult to detect a transformed RV by the class of `var.distribution` or the presence of `var.distribution.transform_used`.

**Comment by vik975** [comment]
I was trying to solve this. Can someone please provide  any pointers  to from where should we  fetch(or where should we add this ) variable "transform_used". The variables like trace.varnames does not have this attribute. Thanks

**Comment by fonnesbeck** [comment]
Problem with using a variable attribute to identify them is that it doesn't help you when the object isn't there anymore, such as when trying to filter out meaningless transformations from the trace. The name is all you have to go on in that case. If the worry is non-conventional variable names with underscores, we can change to double underscore, or something more unlikely to occur.

**Comment by twiecki** [comment]
@fonnesbeck has a point, we did think about this alternative but that was the central problem. At the same time, I didn't run into any problems with our naming convention. Are there any good practical counter arguments @AustinRochford?

**Comment by vik975** [comment]
So, I suppose nothing needs to be done with change request then.

**Comment by AustinRochford** [comment]
I haven't run into any problems, just and I think the difficulties that @fonnesbeck points out likely makes this not worth the effort.
