### ISSUE TITLE
Can't get ADVI to mix for a hierarchical LDA-like model

### ISSUE THREAD

**Issue by christacular** [pymc-devs/pymc#1785]
I'm trying to get a hierarchial LDA-like model to work (actually more like a hierarchical Dirichlet Multinomial Mixture model), similar to the implementation in [lda-advi-aevb.html](https://pymc-devs.github.io/pymc3/notebooks/lda-advi-aevb.html) .  I can't seem to get the model to mix (learn the parameters from both the latent variable distributions).  If I just use the Dirichlet directly in my custom likelihood function via DensityDist I can get the 'phi' variable correct, but the 'theta' variable doesn't get learned.  If I use a Categorical based on the 'theta', it gets 'theta' right but doesn't learn 'phi' properly.  I've put together a gist that generates the dataset, sets up the model, and runs the inference.

[LDA-like implementation gist](https://gist.github.com/christacular/deb550180ca400265ccda97706245b98)

Any help that could point me in the right direction would be very, very much appreciated.  Also, thanks to the contributors for PyMC3, it's an amazing toolkit with so many possibilities.

**Comment by taku-y** [comment]
@christacular In general, sampling posterior distribution from LDA-like models would require a customized samplers like [collapsed Gibbs](http://leitang.net/presentation/LDA-Gibbs.pdf), although I'm not sure if this can be implemented on PyMC3. Looking through your code, the default sampler, maybe Gibbs and MH, would be used thus it might not converge. 

In lda-advi-aevb, instead of using a customized sampler, categorical (discrete) variable `z` is marginalized and entirely relys on gradient-based optimization (ADVI). This technique possibly work on your model.

**Comment by christacular** [comment]
Hi @taku-y , thanks for looking into my code and helping me sort this out.

I've tried to explicitly run ADVI with the code below.  My ELBO curve looks like it's still not converging/mixing at all.  Does this seem like an issue with my likelihood function specification, or does it seem like a misunderstanding of how ADVI functions?  Thanks again; it's really interesting trying to learn about ADVI as a (possible) solution to this problem.

```
from pymc3.variational.advi import advi, sample_vp

with model:
    v_params = pm.variational.advi(n=200000)

plt.plot(v_params.elbo_vals)
plt.ylabel('ELBO')
plt.xlabel('iteration')
```

![image](https://cloud.githubusercontent.com/assets/12818418/22954664/a005d118-f2cc-11e6-8fbf-c8c0f5f34eaf.png)

**Comment by taku-y** [comment]
Hi @christacular Did you marginalize out the categorical variable involved in your original model? ADVI shouldn't work with models including discrete unknown variables.

**Comment by gaddamanil16** [comment]
Hi,
I am trying to implement LDA with ADVI with some dummy data. Bu I am having trouble writing likelihood function. Can you please help me with this. My code is as below. Help much appreciated
```
import numpy as np
import pymc3 as pm, theano.tensor as t
K = 2 # number of topics
V = 2 # number of words
D = 3 # number of documents

data = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]])

alpha = np.ones((1, K))
beta = np.ones((1, V))
model = pm.Model()
Wd = [len(doc) for doc in data]
(D, W) = data.shape
n_tokens = np.sum(data[data.nonzero()])

def log_lda(theta,phi):
    def ll_lda(value):  
        dixs, vixs = value.nonzero()
        vfreqs = value[dixs, vixs]
        ll =vfreqs* pm.math.logsumexp(t.log(theta[dixs]) + t.log(phi.T[vixs]), axis =1).ravel()
        return t.sum(ll) 
    return ll_lda

        
with model: 
    theta = pm.Dirichlet("thetas", a=alpha, shape=(D, K))
    phi = pm.Dirichlet("phis", a=beta, shape=(K, V))
    doc = pm.DensityDist('doc', log_lda(theta,phi), observed=data)   
```

**Comment by fonnesbeck** [comment]
I see that you've already found our Discourse page, so I'm going to close the issue.
