### ISSUE TITLE
Termination criterion for nuts

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1787]
While reading through the stan code to double check the new implementation of multinomial sampling, I noticed that the termination criterion in stan is different to the one in pymc3. There have been recent changes in stan (https://github.com/stan-dev/stan/pull/1854, https://github.com/stan-dev/stan/pull/2180), but even in the older code ("classic nuts") it is different. pymc3 fails to take into account the metric and always assumes a unit mass matrix. This is probably because the original paper on nuts used the standard euclidean space.

**Comment by twiecki** [comment]
Yes, we haven't tracked their changes consistently. Should definitely bring our NUTS as much in sync with theirs as possible.

**Comment by aseyboldt** [comment]
This was fixed in #1769
