### ISSUE TITLE
Kernel just dies

### ISSUE THREAD

**Issue by rodriguezisaacjr** [pymc-devs/pymc#1788]
Hi,
I'm just trying to follow the instructions on: 
[https://pymc-devs.github.io/pymc3/notebooks/GLM-linear.html#Bayesian-GLMs-in-PyMC3](url)

But my Notebook kernel just continue dying when I run the following piece of code:

```
with Model() as model: # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    sigma = HalfCauchy('sigma', beta=10, testval=1.)
    intercept = Normal('Intercept', 0, sd=20)
    x_coeff = Normal('x', 0, sd=20)

    # Define likelihood
    likelihood = Normal('y', mu=intercept + x_coeff * x,
                        sd=sigma, observed=y)

    # Inference!
    start = find_MAP() # Find starting value by optimization
    step = NUTS(scaling=start) # Instantiate MCMC sampling algorithm
    trace = sample(2000, step, start=start, progressbar=False) # draw 2000 posterior samples using NUTS sampling
```

Could you please help me to fix this?

<img width="1163" alt="screen shot 2017-02-14 at 4 36 14 pm" src="https://cloud.githubusercontent.com/assets/11196428/22950493/ce37a4ec-f2d3-11e6-9da6-93af0cadcccb.png">

**Comment by twiecki** [comment]
Which OS and theano and pymc3 versions are you on?

**Comment by rodriguezisaacjr** [comment]
OS 10.12.3
Theano 0.8.2
pymc3 (3.0)

**Comment by twiecki** [comment]
Try upgrading both to master.

**Comment by rodriguezisaacjr** [comment]
thanks, it seems to work now

**Comment by twiecki** [comment]
Great!
