### ISSUE TITLE
Incorrect slicing behavior on MultiTrace

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1799]
The `MultiTrace` object does not seem to correctly deal with negative indices:

```
>>> trace
<MultiTrace: 1 chains, 2000 iterations, 8 variables>
>>> trace[-1000:]
<MultiTrace: 1 chains, 3000 iterations, 8 variables>
```

This should return the last 1000 iterations, not more samples than actually exist.

**Comment by kyleam** [comment]
Based on bisecting, it seems that 5d2767de (#1687, 2017-02-06)
introduced the regression.

**Comment by twiecki** [comment]
Thanks @kyleam. CC @aseyboldt .

**Comment by aseyboldt** [comment]
Yes, that was me, sorry. The slicing is a bit complicated, as it needs to work for traces, where more space is allocated than used. `iter_sample` uses it that way. I can't do anything on this today, but I'll have a look tomorrow.

**Comment by twiecki** [comment]
no problem.
