### ISSUE TITLE
text Trace backend broken since sample function update

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#1816]
Using most recent developing branch, python 2.7

I get following error:
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pymc3/sampling.py", line 182, in sample
  File "build/bdist.linux-x86_64/egg/pymc3/sampling.py", line 201, in _sample
  File "build/bdist.linux-x86_64/egg/pymc3/backends/text.py", line 99, in close
AttributeError: 'NoneType' object has no attribute 'close'

This is related to related to the double close - there is one already in 
iter_sample line 295 once the loop is finished,
then there is another close in _sample line 201,

maybe it is only related to the Text backend, there in the close method the dataframe object is replaced with a None after closing, so the second call to close results in that issue.

Obviously there is a ton of ways how to fix it- where do you want to fix it? Obviously it does work for the other backends, as no one reported it yet?

**Comment by twiecki** [comment]
@hvasbath Thanks for the report. Seems like we should remove the one in iter_sample()? Want to do a PR?

**Comment by hvasbath** [comment]
Great will do that right away, the way you suggested.

**Comment by hvasbath** [comment]
Resolved.
