### ISSUE TITLE
Unexpected/problematic Multitrace slice behavior

### ISSUE THREAD

**Issue by jake-westfall** [pymc-devs/pymc#1831]
Consider 3 ways of slicing and taking the mean of samples for a parameter in a Multitrace object (for a random example dataset/model I have):

    >>> trace['param', 1000:].mean()
    0.24100671487168293
    >>> trace[1000:]['param'].mean()
    0.24100671487168293
    >>> trace['param'][1000:].mean()
    0.24372866043714511

The first method is what is illustrated in the docstrings for the Multitrace class, and the answer in this particular example case is about what I expect, based on the density plots. So this seems to be the preferred, safe way. And the second method agrees with this result. But the third method--which seems like it should return the same answer--does not agree and does not seem to be quite right. I'm not sure why this is. But it seems problematic that these three syntaxes all happily return answers that don't necessarily agree.

**Comment by kyleam** [comment]
> Consider 3 ways of slicing and taking the mean of samples for a parameter in a Multitrace object (for a random example dataset/model I have):
>
>     >>> trace['param', 1000:].mean()
>     0.24100671487168293
>     >>> trace[1000:]['param'].mean()
>     0.24100671487168293
>     >>> trace['param'][1000:].mean()
>     0.24372866043714511
>
> The first method is what is illustrated in the docstrings for the
> Multitrace class, and the answer in this particular example case is
> about what I expect, based on the density plots. So this seems to be
> the preferred, safe way. And the second method agrees with this
> result. But the third method--which seems like it should return the
> same answer--does not agree and does not seem to be quite right. I'm
> not sure why this is.

The first two approaches are aware of chains.  They drop the first 1000
from the front of all chains.  The third is returning a concatenated
array for all chains, and then standard slicing on a numpy array is
dropping the first 1000 values, so all chains but the first still have
their initial 1000 values.

> But it seems problematic that these three syntaxes all happily return
> answers that don't necessarily agree.

I don't see a good way to resolve that aside from improving the
documentation.
