### ISSUE TITLE
Sparse Matrix Support

### ISSUE THREAD

**Issue by timothyb0912** [pymc-devs/pymc#1835]
Currently, one cannot pass a sparse matrix through the `observed` kwarg. I may be wrong, but I don't think that pymc3 supports sparse matrices at this time.

My use case was that I was implementing a custom subclass of `pm.Continuous` and my function that returned a Theano expression for the log-likelihood required a sparse matrix as input.

The issue seems to be that `pandas_to_array` and `as_tensor` in pymc3/model.py will attempt to naively transform the sparse matrix into a numpy array.

**Comment by twiecki** [comment]
yep that's a great feature request.

**Comment by timothyb0912** [comment]
Sweet, I'm glad it'll fit. I'm making a branch for a pull request for this now!
