### ISSUE TITLE
Modeling sum of exponential variables

### ISSUE THREAD

**Issue by usptact** [pymc-devs/pymc#1841]
I am trying to self-educate myself on a classic (?) problem recovering the rate parameters for two Exponentially distributed random variables, where the sum of the two is actually observed. My interest was sparked by this [SO ](http://stats.stackexchange.com/questions/263916/parameter-estimation-for-sum-of-independent-exponential-rv)question.

It appears that there exist a simple way finding the rate when it the same. It is slightly more involved when the rates are different.

Assuming that I don't know how to find this distribution with pen and paper, I tried to attempt it in PyMC3.

My first shot was trying to create two random variables X, Y - Exponential rvs, set the prior for their rate parameters and create a deterministic variable Z = X + Y. The problem was that a Deterministic cannot be observed!

My second attempt was to use the log probability of the distribution of Z. I found the probability distribution Z, took log and come up with this:

```
lambda1_true = 0.5
lambda2_true =1.0

x1 = scipy.stats.expon( lambda1_true, size=10 )
x2 = scipy.stats.expon( lambda2_true, size=10 )
y = x1 + x2

model = pm.Model()

with model:
   lambda1 = pm.Gamma( 'lambda1', alpha=1, beta=2, testval=0.1 )
   lambda2 = pm.Gamma( 'lambda2', alpha=1, beta=2, testval=0.1 )
   
   def logp( z ):
      return tt.log(lambda1) + tt.log(lambda2) + tt.log( tt.exp(-lambda2*z) - tt.exp(-lambda1*z) - tt.log( lambda1 - lambda2 )

   pm.DensityDist( 'obs', logp=logp, observed={'z': y} )
   
   step = pm.Metropolis()
   trace = pm.sample( 10000, step=step )

pm.traceplot( trace )
plt.show()
```

The code runs but I cannot manage to get meaningful posteriors for the data that I synthetically generated. The samples just get stuck at the testval=0.1 for both parameters and don't move.

The problem with this second approach is that I *know* the probability of z for two random Exponential rvs. What if I had more that 2? How can I solve it?

UPDATE: I am on the fence whether I should move this question to SO.

Any help would be welcome!

**Comment by twiecki** [comment]
There is pm.math.logsumexp()

**Comment by usptact** [comment]
Thanks @twiecki ! I changed the third term in the logp() expression as follows:

`... + pm.math.logsumexp( -lambda1 * z - lambda2 * z ) + ...
`
I feel that I don't really understand what is going on with this pm.DensityDist(). I know that I am creating custom likelihood whose value I observe (the y array). I still get strange results.

**Comment by aseyboldt** [comment]
I think you are computing the log of negative values. This seems to work if you use nuts:
```python
def logp(z):
    diff = lambda2 - lambda1
    return tt.log(lambda1) + tt.log(lambda2) - lambda2 * z + tt.log(tt.expm1(z * lambda_diff) / lambda_diff)

trace = pm.sample(2000, tune=1000)
```

Keep in mind that you can't distinguish between `lambda1` and `lambda2`, their posteriors are correlated.

**Comment by usptact** [comment]
@aseyboldt Thank you for your feedback! Much appreciated!

I also thought about identifiability problem. What if I force the model lambda1 > lambda2, like this:

`pm.Potential( 'pot', pm.math.switch( lambda1 > lambda2, 1000, 1) )`

Would this help?

Did you manage to run my example? I still can't get meaningful result....

**Comment by aseyboldt** [comment]
This works for me:
```python
lambda1_true = 0.1
lambda2_true = 1.0

x1 = stats.expon(lambda1_true).rvs(10)
x2 = stats.expon(lambda2_true).rvs(10)
y = x1 + x2

model = pm.Model()

with model:
    lambda1 = pm.Gamma('lambda1', alpha=1, beta=2, testval=0.1)
    lambda2 = pm.Gamma('lambda2', alpha=1, beta=2, testval=0.2)
   
    def logp(z):
        lambda_diff = lambda2 - lambda1
        logs = tt.log(lambda1) + tt.log(lambda2)
        return logs + tt.log(tt.expm1(z * lambda_diff) / lambda_diff) - lambda2 * z

    pm.DensityDist('obs', logp=logp, observed={'z': y})
    trace = pm.sample(2000, tune=1000)
```
If `lambda1 == lambda2`, the logp is still ill defined. This leads to some problems during initialisation if the testvals are equal.

**Comment by usptact** [comment]
@aseyboldt Thanks for your example! Are you running a development version of PyMC3 or the release? I run the release version and get wildly different results from run to run!  I get wide posteriors for lambda1 and lambda2 that are virtually identical and not centered on any of true values.

**Comment by aseyboldt** [comment]
I tried both and they both seem to work (master is 5 times faster ;)
For me, the results do not vary from run to run. But they *should* not be centered around the true values, Given those priors it is far more likely that they are both something like 0.5. Take a look at the scatter plot of the two to get a feeling how the posterior looks like:
```python
plt.scatter(trace['lambda1'], trace['lambda2'], marker='.', alpha=0.5)
```

**Comment by usptact** [comment]
@aseyboldt You are super patient with me! My release version returns two estimates that are both centered around 0.7.

What would be a better prior for this problem? I kind of picked Gamma at random...

**Comment by aseyboldt** [comment]
Ups, just noticed the sampling should be
```
x1 = stats.expon(scale=lambda1_true).rvs(10)
x2 = stats.expon(scale=lambda2_true).rvs(10)
```
Otherwise lambda1_true is the loc. Looks a bit better now. Still, With just 20 points the models just can't tell if you have one small and one large exponential rate or two moderate ones. Intuitively I'd probably use a HalfCauchy prior for the rates, but I honestly don't know.
