### ISSUE TITLE
logp of `Bound` distributions is wrong

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1843]
This came up in #1833.
The logp function of `Bounded` returns the raw values of the underlying distribution, but it should correct those with the new normalization constant of the bounded distribution using the cdf and ccdf of the underlying distribution. In many cases this is just a constant, so the results of the samplers do not change, but if `Bound` is used as an observed var (to model truncated data for example), this can lead to wrong results. This should either me mentioned in the doc of `Bound`, and in this case it should probably refuse the `observed` keyword, or we would need to implement cdf and ccdfs for each distribution in pymc3.

**Comment by domenzain** [comment]
The second alternative seems more natural to the users and provides much more modelling power out of the box.

**Comment by ColCarroll** [comment]
I agree the second seems like the "right" answer, but it might be better for everyone to update the documentation and refuse the `observed` keyword for now and leave this issue open for someone to take up.  It just seems like updating the docs is a ~30min exercise and the other would require some more careful work and testing.

**Comment by aseyboldt** [comment]
We might also want to somehow keep the functionality of the current `Bound` around. This does seem useful when defining new distributions.
I think I have a bit of time to work on this sometime this week. I guess we don't need cdfs for all distributions for now.

**Comment by domenzain** [comment]
If there is a place to gradually add cdfs, I can contribute a few of them too during the week.

**Comment by domenzain** [comment]
Maybe this could be called `Truncated`. This way `Bounded` is kept around for other uses and the current code can stay as it is.

**Comment by aseyboldt** [comment]
Closed by #1942, see #1864 for long term plan.
