### ISSUE TITLE
Strange error when incorporating Theano max tensor in model

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1846]
I'm using the bleeding-edge versions of both `Theano` and `pymc3`. Here is a brief example that generates the error:

```python
import numpy as np
import pymc3 as pm
import theano.tensor as tt


with pm.Model():

    y = np.random.random(100)
    a = pm.Normal('a', shape=y.shape)
    b = pm.Normal('b', shape=y.shape)
    x = tt.max([a, b], axis=0)
    z = tt.sum([a, b], axis=0)
    # pm.Normal('yhat', mu=a, sd=1, observed=y)  # is fine
    # pm.Normal('yhat', mu=z, sd=1, observed=y)  # is fine
    pm.Normal('yhat', mu=x, sd=1, observed=y)  # raises error
    pm.sample(100)
```

This produces an enormous error message, the final line of which is:

```
Exception: ("Compilation failed (return status=1): /Users/smathias/.theano/compiledir_Darwin-16.4.0-x86_64-i386-64bit-i386-3.5.2-64/tmpxc5wd9t2/mod.cpp:676:21: warning: comparison of array 'outputs' equal to a null pointer is always false [-Wtautological-pointer-compare].                 if (outputs == NULL) {.                     ^~~~~~~    ~~~~. /Users/smathias/.theano/compiledir_Darwin-16.4.0-x86_64-i386-64bit-i386-3.5.2-64/tmpxc5wd9t2/mod.cpp:701:54: error: arithmetic on a pointer to void.                                     PyArray_DATA(V3) + data_offset,.                                     ~~~~~~~~~~~~~~~~ ^. 1 warning and 1 error generated.. ", '[*1 -> Split{2}(<TensorType(float64, matrix)>, TensorConstant{0}, <TensorType(int64, vector)>), *1::1]')
```

It is not clear to me why there would be a problem computing `min` and `max`, but not `sum`. Both functions work fine in a pure `Theano` script, and when `x` isn't passed to the likelihood above. Googling suggested it might have something to do with the type (of what? not sure).

**Comment by AustinRochford** [comment]
I have successfully executed this example using the bleeding-edge versions of both `theano` and `pymc3` in the development container.  Can you try it in the container on your machine and see if it succeeds?  If so, it might be an odd `gcc` issue on your Mac, which has popped up from time to time in the past.

(Development container directions are [here](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md#developing-in-docker).)
