### ISSUE TITLE
Lower and Upper bound not working for multivariate distributions

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1847]
This is bit of a feature request than anything. I was wondering if it would be possible to implement the bounds of a distribution similar to what is done in stan. eg:
```
parameters{
  real<lower=0,upper=1> sigma;
}
```

The only way I can think of doing this in pymc3 is using densityDist. Lastly if this were to be implemented would it affect ADVI?

**Comment by fonnesbeck** [comment]
You can already do this by wrapping any continuous distribution in `Bound`.

**Comment by sachinruk** [comment]
How would this work in the Multivariate case? I wish to change the following line: 
```
innov_like = pm.MvNormal.dist(mu=x_im1 + mu, tau=tau).logp(x_i)
```
to 
```
BoundedNormal = pm.Bound(pm.MvNormal, lower=0)
innov_like = BoundedNormal.dist(mu=x_im1 + mu, tau=tau).logp(x_i)
```

The above chucked a dimensionality mismatch error. Any thoughts?

Also with regards to using VB, anything I ought to be cautious about when using bounded distributions?

**Comment by twiecki** [comment]
We don't have tests for bounds on multivariate distributions so I'm not surprised it isn't working.

There should be no issue with VB though.

**Comment by domenzain** [comment]
#1843 There are some pitfalls when sampling.
