### ISSUE TITLE
Numerical instability in pymc3.gp.cov.Stationary.square_dist

### ISSUE THREAD

**Issue by chrism0dwk** [pymc-devs/pymc#1848]
Hi,

I think I've discovered a numerical stability issue in pymc3.gp.cov.Stationary.square_dist.  I am working with 2D data for a spatial problem, points in UK OSGB coordinates divided by 1000 for 1km map units.

For certain overlapping points (i.e. the diagonal of the distance matrix, duplicates in the dataset) the square_dist function returns a small negative value, of the order -3e-12.  Obviously this problem has cropped up before, as I notice that Stationary.euclidean_dist applies a correction for this by adding 1e-12 to each distance.  Obviously this correction factor is not large enough in my case, resulting in a covariance matrix with nan elements.

Would a slower, more stable way of calculating the distance matrix be preferable in this case, I wonder?

**Comment by fonnesbeck** [comment]
Hi Chris,

I can see where this might pop up, and I think a numerically stable alternative might be good to have available, perhaps set as a flag when the covariance function is instantiated. We do a similar thing in ADVI when more accurate estimates of the evidence lower bound are required. Theano is sometimes able to recognize numerical stability issues and fix them when it writes its C code, but thad does not seem to be the case here. Did you have an algorithm in mind? If so, feel free to contribute a PR, or point us in the direction of what you were thinking.

**Comment by fonnesbeck** [comment]
I suppose one easy thing we could do is convert to float64 when there is a chance of numerical instability. This would preclude the use of GPU, though.

**Comment by bwengals** [comment]
That's interesting, and makes sense.  Thank you for pointing this out.  Maybe clipping at zero could solve the problem.

**Comment by bwengals** [comment]
The 1e-12 correction factor is there to avoid issues with differentiability of sqrt at zero, so I think some guard for values less than zero or a more numerically stable `square_dist` is needed.

**Comment by chrism0dwk** [comment]
I guess there are two options:

1. Transform coordinates to the unit line/square/(hyper)cube before calculating squared distances, transforming back afterwards.  This seems to work well for my case where my points are distributed reasonably evenly over my study region -- it might not work so well for highly clustered points (but then, neither might a GP approach).

2. Apply a np.where() to the resulting squared distance matrix, setting any negative values to zero.

I think (1) might be preferable from a numerical rounding point of view as errors in positive distances would be controlled in addition to zero distances.

**Comment by bwengals** [comment]
@chrism0dwk I'm having some difficulty reproducing the issue to test a fix (#1857).  Do you happen to have an example handy?

**Comment by chrism0dwk** [comment]
@bwengals sure:

    import numpy as np
    # Test points
    X = np.random.uniform(low=320., high=400., size=[2000,2])
    # Calculate pairwise distance a la pymc3.gp.cov.Stationary
    Xs = np.sum(np.square(X), 1)
    D = -2. * np.dot(X, X.T) + ( np.reshape(Xs, (-1,1)) + np.reshape(Xs, (1,-1)) )
    if np.any(D < 0):
        print "Negative distances found"

**Comment by bwengals** [comment]
close?
