### ISSUE TITLE
pm.sample() ignores n_init argument

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/pymc#1849]
By default, when calling `pm.sample()`, ADVI is run for 200,000 samples or until mean/median ELBO convergence. However, changing the kwarg `n_init` to some other number seems to do nothing.

**Comment by ColCarroll** [comment]
Can you post a sample?  Just glancing at the code on `master`, I can't spot where that would happen.

**Comment by sammosummo** [comment]
Sorry, I couldn't replicate the issue with a simple example. Going back and forth between my real and example scripts, the issue seemed to be be related to scope. In my script (which had the issue), `pm.sample` was called in a function within a function The issue was probably related to my poor coding than pymc.
