### ISSUE TITLE
Cholesky in mvNormal

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1850]
Just out of curiosity shouldn't you be using Cholesky when calculating the log likelihood of a multivariate normal. Right now it seems that the inverse of the covariance is being calculated, which if I understand correctly can be unstable? Atleast when I used matlab I was taught that its always preferable to use `x = solve(A,y)` rather than have `x = inv(A)y`.

https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py

**Comment by aseyboldt** [comment]
Theano optimizes `inv(A) @ y` to `solve(A, y)`. But I guess a version of mvNormal that uses a cholesky decomposed cov matrix would be nice.

**Comment by sachinruk** [comment]
The cholesky would be useful in the case of calculating the log determinant as well. All you have to do is sum(log(diag(L))).

**Comment by bwengals** [comment]
+1 am planning on choleskifying the GP stuff soon.  It would be interesting to test timing differences on current version of MvNormal and one using the Cholesky decomp, particularly when the gradient is calculated.

**Comment by jonathanhfriedman** [comment]
I can try adding this/seeing if it improves performance if no one else has already started, since it should be pretty similar to what I did adding the Cholesky decomposition to the elliptical slice sampler.

**Comment by bwengals** [comment]
Maybe I'm wrong, but it looks like theano 0.8.x doesn't have a gradient implemented for the `Solve` op, see [line 195ish](https://github.com/Theano/Theano/blob/0.8.X/theano/tensor/slinalg.py).  Later versions of theano have a gradient for `Solve`, but pymc3 has its theano version requirement at  > 0.8.x.

**Comment by sachinruk** [comment]
I opened up an issue, https://github.com/Theano/Theano/issues/5647.  I'm assuming you are referring to the fact that you cannot do `T.slinalg.solve(L,delta.T)` with a cholesky matrix? @bwengals

**Comment by bwengals** [comment]
You *can* compute a solve with a cholesky factor, but you cannot compute the gradient through it.  Newer versions of theano do have a gradient implemented for Solve though.  See [line 238 of the version 0.9.x slinalg code here](https://github.com/Theano/Theano/blob/0.9.X/theano/tensor/slinalg.py).

From their docs it looks like theano is planning to release 0.9.x soon though.  Will pymc3 require the newer version of theano?

**Comment by twiecki** [comment]
I think we are already incompat in other places with theano 0.8 and 0.9 is right around the corner so that's not an issue for me.

**Comment by bwengals** [comment]
Alright, so I guess green light.  @jonathanhfriedman have you started working on this?  If you aren't too far along on this already I'd like to collaborate.

**Comment by jonathanhfriedman** [comment]
@bwengals I just created a PR with what I've got so far. I've just rewritten `random()` to use the Cholesky decomposition but haven't touched the log likelihood yet, so there's definitely lots left to do.
