### ISSUE TITLE
ImportError: No module named 'pymc3.plots'

### ISSUE THREAD

**Issue by loneharoon** [pymc-devs/pymc#1859]
I installed pymc3 using `pip`. Whenever I try to import pymc3 using
 `import pymc3 as pm`
I get an error message as: `ImportError: No module named 'pymc3.plots'`.

What can be the possible reason?

**Comment by twiecki** [comment]
@loneharoon Thanks for the report. can you retry?

**Comment by loneharoon** [comment]
@twiecki, I restarted my Ipython notebook, but it still throws the same error.

**Comment by twiecki** [comment]
@loneharoon You need to reinstall via pip.

**Comment by loneharoon** [comment]
@twiecki, Thanks a lot.  It is working now. What was the issue?

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/commit/eb0025bf6c32f642cd467f56df39f413e5f7c6c0
