### ISSUE TITLE
Add description of Bound use in docs

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1860]
The appropriate use of `Bound` is not clear, particularly since there is also a `Bounded` class. This can cause some confusion in usage (e.g. #1858). Would be good to have a subsection on this in the docs.

**Comment by fonnesbeck** [comment]
It occurs to me that we probably need an intermediate/advanced guide to complement our getting started guide.

**Comment by springcoil** [comment]
http://docs.pymc.io/api/bounds.html?highlight=bound -- does this resolve this?

**Comment by junpenglao** [comment]
yes that resolves it.
