### ISSUE TITLE
PDF in Lognormal docstring

### ISSUE THREAD

**Issue by ricklupton** [pymc-devs/pymc#1865]
The [Lognormal distribution docstring](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/continuous.py#L593) says its pdf is this:
```latex
       f(x \mid \mu, \tau) =
           \sqrt{\frac{\tau}{2\pi}}
           \frac{\exp\left\{ -\frac{\tau}{2} (\ln(x)-\mu)^2 \right\}}{x}
```
Which is odd, as usually the lognormal pdf would include a `1/x` term.

[The `logp` function](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/continuous.py#L637) actually returns this:
```py
    def logp(self, value):
        mu = self.mu
        tau = self.tau
        return bound(-0.5 * tau * (tt.log(value) - mu)**2
                     + 0.5 * tt.log(tau / (2. * np.pi))
                     - tt.log(value),
                     tau > 0)
```
The `tt.log(value)` corresponds to a `1/x` term in the pdf, so I think this is just a mistake in the docstring, rather than something weird about the way the lognormal distribution is defined in PyMC3?

**Comment by twiecki** [comment]
Yes, that looks like a bug. Want to submit a PR to fix it?

**Comment by ricklupton** [comment]
Thanks. Actually I was wrong, the docstring is correct: the 1/x is hiding at the end of the line. But I started a PR before I realised so I'll make a change anyway to make it more obvious (to me at least, and I guess maybe to you :)).

The Latex code is what you see in Jupyter docstrings; the online docs have MathJax so this wouldn't have been a problem there.
