### ISSUE TITLE
Problem in `LKJ_correlation.py` example

### ISSUE THREAD

**Issue by tomaskrehlik** [pymc-devs/pymc#1884]
The [example](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/LKJ_correlation.py) has the following code:

````{python}
corr_triangle = pm.LKJCorr('corr', n=1, p=n_var)
corr_matrix = corr_triangle[tri_index]
corr_matrix = tt.fill_diagonal(corr_matrix, 1)
````
where the `tri_index` is a matrix of zeros. This will result into a correlation matrix with identical elements off-diagonal, no? To get it working properly, I had to use:
````{python}
tri_index = np.zeros((k,k), dtype = np.int64)
tri_index[np.triu_indices(k, 1)] = range(0,(k*(k-1)//2))
tri_index[np.tril_indices(k, -1)] = range(0,(k*(k-1)//2))
````
in my code.

**Comment by junpenglao** [comment]
Please find the [updated example](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/LKJ_correlation.py#L32) using `pm.LKJCholeskyCov`, which is a better and more stable parameterization.
