### ISSUE TITLE
The GLM: Logistic Regression example has problems

### ISSUE THREAD

**Issue by MarkDunne** [pymc-devs/pymc#1886]
The example here https://pymc-devs.github.io/pymc3/notebooks/GLM-logistic.html has a couple of problems.

It starts off ok, but from the 'Some Results' section down, the graphics are all wrong. The beta_age/beta_education graph shows that both are estimated at exactly 0.The next 'Posterior Predictive' graph, and the one directly after it are also weird and probably incorrect.

Also looks like there is a bunch of issues with the code samples at the end of the example

**Comment by bhargavvader** [comment]
I stumbled across this too- all the GLM examples are pretty off. I'm trying to fix this in #1782, you are welcome to identify more errors or help with suggestions over there, it will move things across faster!

**Comment by junpenglao** [comment]
This is fixed in #2241.
