### ISSUE TITLE
Failed import pymc3 within ipython notebook but ok with commandline

### ISSUE THREAD

**Issue by mznyc** [pymc-devs/pymc#1887]
"import pymc3" failed with the following error in master build

ImportError                               Traceback (most recent call last)
<ipython-input-8-ab4b676acfe7> in <module>()
----> 1 from pymc3 import Model, Normal, HalfNormal
      2 from pymc3 import find_MAP
      3 
      4 basic_model = Model()
      5 

build/bdist.linux-x86_64/egg/pymc3/__init__.py in <module>()
      5 from .distributions import *
      6 from .external import *
----> 7 from .glm import *
      8 from . import gp
      9 from .math import logsumexp, logit, invlogit

build/bdist.linux-x86_64/egg/pymc3/glm/__init__.py in <module>()
----> 1 from .linear import LinearComponent, GLM
      2 from . import families

build/bdist.linux-x86_64/egg/pymc3/glm/linear.py in <module>()
      2 import numpy as np
      3 from ..distributions import Normal, Flat
----> 4 from . import families
      5 from ..model import Model, Deterministic
      6 from .utils import any_to_tensor_and_labels

ImportError: cannot import name families

**Comment by mznyc** [comment]
Here is the error for firs trying to import  pymc3


ImportError                               Traceback (most recent call last)
<ipython-input-2-a2e56a79c91d> in <module>()
      1 import theano
----> 2 from pymc3 import Model, Normal, HalfNormal

/home/zhongm/anaconda2/lib/python2.7/site-packages/pymc3-3.0-py2.7.egg/pymc3/__init__.pyc in <module>()
      5 from .distributions import *
      6 from .external import *
----> 7 from .glm import *
      8 from . import gp
      9 from .math import logsumexp, logit, invlogit

build/bdist.linux-x86_64/egg/pymc3/glm/__init__.py in <module>()
----> 1 from .linear import LinearComponent, GLM
      2 from . import families

build/bdist.linux-x86_64/egg/pymc3/glm/linear.py in <module>()
     12 
     13 
---> 14 class LinearComponent(Model):
     15     """Creates linear component, y_est is accessible via attribute
     16     Parameters

build/bdist.linux-x86_64/egg/pymc3/glm/linear.py in LinearComponent()
     28     vars : dict - random variables instead of creating new ones
     29     """
---> 30     default_regressor_prior = Normal.dist(mu=0, tau=1.0E-6)
     31     default_intercept_prior = Flat.dist()
     32 

/home/zhongm/anaconda2/lib/python2.7/site-packages/pymc3-3.0-py2.7.egg/pymc3/distributions/distribution.pyc in dist(cls, *args, **kwargs)
     45     def dist(cls, *args, **kwargs):
     46         dist = object.__new__(cls)
---> 47         dist.__init__(*args, **kwargs)
     48         return dist
     49 

/home/zhongm/anaconda2/lib/python2.7/site-packages/pymc3-3.0-py2.7.egg/pymc3/distributions/continuous.pyc in __init__(self, mu, sd, tau, **kwargs)
    210 
    211         self.mean = self.median = self.mode = self.mu = mu = tt.as_tensor_variable(mu)
--> 212         self.variance = 1. / self.tau
    213 
    214         assert_negative_support(sd, 'sd', 'Normal')

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/tensor/var.py in __rtruediv__(self, other)
    210 
    211     def __rtruediv__(self, other):
--> 212         return theano.tensor.basic.true_div(other, self)
    213 
    214     def __rfloordiv__(self, other):

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    655                 # compute output value once with test inputs to validate graph
    656                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 657                                            no_recycling=[])
    658                 thunk.inputs = [storage_map[v] for v in node.inputs]
    659                 thunk.outputs = [storage_map[v] for v in node.outputs]

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    930             try:
    931                 return self.make_c_thunk(node, storage_map, compute_map,
--> 932                                          no_recycling)
    933             except (NotImplementedError, utils.MethodNotDefined):
    934                 logger.debug('Falling back on perform')

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    831         logger.debug('Trying CLinker.make_thunk')
    832         outputs = cl.make_thunk(input_storage=node_input_storage,
--> 833                                 output_storage=node_output_storage)
    834         fill_storage, node_input_filters, node_output_filters = outputs
    835 

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1188         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1189             input_storage, output_storage, storage_map,
-> 1190             keep_lock=keep_lock)
   1191 
   1192         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1129                                     output_storage,
   1130                                     storage_map,
-> 1131                                     keep_lock=keep_lock)
   1132         return (thunk,
   1133                 [link.Container(input, storage) for input, storage in

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1587                 node.op.prepare_node(node, storage_map, None)
   1588             module = get_module_cache().module_from_key(
-> 1589                 key=key, lnk=self, keep_lock=keep_lock)
   1590 
   1591         vars = self.inputs + self.outputs + self.orphans

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1102         """
   1103         # Is the module in the cache?
-> 1104         module = self._get_from_key(key)
   1105         if module is not None:
   1106             return module

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cmodule.py in _get_from_key(self, key, key_data)
   1001         if name is None:
   1002             return None
-> 1003         return self._get_module(name)
   1004 
   1005     def _get_from_hash(self, module_hash, key, keep_lock=False):

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cmodule.py in _get_module(self, name)
    675         if name not in self.module_from_name:
    676             _logger.debug('loading name %s', name)
--> 677             self.module_from_name[name] = dlimport(name)
    678             self.stats[1] += 1
    679         else:

/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages/Theano-0.9.0.dev2-py2.7.egg/theano/gof/cmodule.py in dlimport(fullpath, suffix)
    300             warnings.filterwarnings("ignore",
    301                                     message="numpy.ndarray size changed")
--> 302             rval = __import__(module_name, {}, {}, [module_name])
    303         t1 = time.time()
    304         import_time += t1 - t0

ImportError: /home/zhongm/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.8-Santiago-x86_64-2.7.13-64/tmpcGmD3d/9476a463ad1304ffcc0cb54b38a06cd2.so: undefined symbol: _ZdlPvm

In [3]:

**Comment by fonnesbeck** [comment]
Do you have multiple Python installations on your machine? I typically see this when the notebook is actually using a different Python than you are using on the command line.

Also, go ahead and delete your entire `~/.theano` directory.

**Comment by mznyc** [comment]
1. Same error after deleting ~/.theano directory
2. Verified same python executable running  for both cases

**Comment by mznyc** [comment]
My gcc version is 6.1.0, an allegedly non-compatible version with theano. 
But what confuses me is that why command-line works.

**Comment by aseyboldt** [comment]
The traceback seems to contain different base paths:
`build/bdist.linux-x86_64/egg/pymc3/glm/init.py`
`/qau/share/anaconda2/envs/dl/lib/python2.7/site-packages`
`/home/zhongm/anaconda2/lib/python2.7/site-packages/pymc3-3.0-py2.7.egg`

This somehow seems like it is mixing different anaconda/python installations...

The missing symbol seems to be related to the c++14 `delete` operator: https://git.ics.ele.tue.nl/5LIM0-sources/llvm/commit/2451e5b5812c8e70619b219c9b0ee52fd256ea21

**Comment by ahartikainen** [comment]
Are you running with anaconda?

try to create conda env.

    conda create -n py27 python=2.7

and conda/pip install only needed packages. Could be a problem with anaconda and default libstdc++ files that come with it.
