### ISSUE TITLE
Shape issues when solving cholesky

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#1891]
I created the synthetic **multivariate** Gaussian Random Walk dataset as follows:
```
import numpy as np
import matplotlib.pyplot as plt
import pymc3 as pm
from scipy.linalg import cholesky

Sigma = np.random.randn(3,5)
Sigma = Sigma.dot(Sigma.T)
L = cholesky(Sigma, lower=True)
y = L.dot(np.random.randn(3,10000))
y = np.cumsum(y,1)
```

```
import theano.tensor as T
import theano.tensor.slinalg as sla
from pymc3.distributions import Continuous

class mvNormalRandomWalk(Continuous):
    def __init__(self, mu=0., cov=1., *args, **kwargs):
        super(mvNormalRandomWalk, self).__init__(*args, **kwargs)
        self.cov = cov
        self.mu = mu

    def logp(self, x):
        mu = self.mu

        x_im1 = x[:-1]
        x_i = x[1:]
        
        L = sla.cholesky(self.cov)
        log_det = T.log(L.diagonal()).sum()
        delta = x_i - (x_im1+mu)

        solve_lower_triangular = sla.Solve(A_structure='lower_triangular', lower=True)
        Linv_delta = solve_lower_triangular(L,delta.T)

#         Linv = T.nlinalg.matrix_inverse(L)
#         Linv_delta = T.dot(Linv,delta.T)
        
        k = L.shape[0]
        innov_like = -(0.5*k*T.log(2*np.pi) + log_det + 0.5*T.sum(Linv_delta*Linv_delta,axis=0))
        return T.sum(innov_like)
```
The problem is that the solving part always causes shape error: `ValueError: Input dimension mis-match. (input[0].shape[0] = 3, input[1].shape[0] = 9999)` and doesn't help even if I remove the transpose of `delta` in the solve step. However, what is strange is that when I remove those two lines and replace with the commented out lines, it works fine!

You can test it with:
```
with pm.Model() as model:
    mu = pm.MvNormal('mu',mu=0, cov=np.eye(3))
    likelihood = mvNormalRandomWalk('y',mu=mu,cov=Sigma,observed=y.T)
    step = pm.NUTS()
    trace = pm.sample(n_samples, step)
```
**The second** that is strange is that I cannot send a vector like `mu = np.zeros(3)`, as it seems to only accept scalars. It's multivariate, so should it not accept vectors. This part atleast is a side consideration.

Finally this doesn't seem to be a theano issue as pointed out here: https://github.com/Theano/Theano/issues/5692#issuecomment-285656137

**Comment by aseyboldt** [comment]
Sorry for the long delay.
I could not reproduce the error, if I run your code it starts sampling. There seems to be some issue with detecting the shape of `mu`, however. It is reported as having only one dimension. This is fixed if I manually specify the shape: `pm.MvNormal('mu', mu=np.zeros(3), cov=np.eye(3), shape=3)`.

What version of Theano/pymc3 are you using? CPU or GPU?

**Comment by sachinruk** [comment]
Out of curiosity which version of theano (I'm using Theano v0.8.2) are you using, and also are you using the development branch of pymc3, or just the normal v3.0?

**Comment by twiecki** [comment]
@sachinruk Definitely upgrade to master of theano and pymc3. Both are about to release a new stable version.

**Comment by aseyboldt** [comment]
@sachinuk I'm on master for pymc3 and maybe a couple of commits behind master for theano.

**Comment by sachinruk** [comment]
The `shape=3` part did the trick with getting a truly multivariate normal.

wrt the sampling issue, I upgraded pymc3 without upgrading theano. That didn't help with the cholesky solve component. After I upgraded to theano v0.9 it started sampling.

Cheers.
