### ISSUE TITLE
Release v3.1

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1894]
I think it's time, we have a bunch of new features. If we start now we should be ready when theano 0.9 hits.

I cut a RC1: https://github.com/pymc-devs/pymc3/releases/tag/v3.1.rc1

**Comment by springcoil** [comment]
No problems with this, I think we've a bunch of stuff that's happened recently.

**Comment by aseyboldt** [comment]
It would be great if we could get cholesky MvNormal and LKJCorr finished before this. Judging from SO and the issues people seem to run into this a lot.
