### ISSUE TITLE
ADVI behaving in BVAR

### ISSUE THREAD

**Issue by tomaskrehlik** [pymc-devs/pymc#1896]
I am trying to get Bayesian VAR estimation work in PyMC3 and ADVI has been behaving weirdly. The data I use are [here](https://gist.github.com/tomaskrehlik/b94454a7df73eb7d1977976d5e3c05bf). So I use the following code that should be rather self-explanatory.

````{python3}
%matplotlib inline
import numpy as np
import pymc3 as pm
from scipy import optimize
from theano import tensor as tt

data = np.genfromtxt('data.csv', delimiter=',')

k = 7
window = 500
lags = 2

def get_lags(data, lags):
    return([data[(1 + lags - i):(window + lags - i),0:k] for i in range(0,lags+1)])

data_new = get_lags(data, lags)

# Init values from OLS and its residuals
X = np.concatenate((np.ones((499,1)),np.array(data_new[1]), np.array(data_new[2])), axis = 1)
bet=np.linalg.inv(np.transpose(X)@X)@np.transpose(X)@data_new[0]
init_sigma = np.std(data_new[0] - X@bet, axis=0)
A = np.corrcoef(data_new[0] - X@bet, rowvar=0)
init_corr = A[np.triu_indices_from(A,1)]

tri_ind = np.zeros((k,k), dtype = np.int64)
tri_ind[np.triu_indices(k, 1)] = range(0,(k*(k-1)//2))
tri_ind[np.tril_indices(k, -1)] = range(0,(k*(k-1)//2))
with pm.Model() as model:
    sigma = pm.Lognormal('sigma', np.zeros(k), np.ones(k), shape=k, testval=init_sigma)
    C_triu = pm.LKJCorr('C_triu', n=60, p=k, testval=init_corr)
    C = pm.Deterministic('C', tt.fill_diagonal(C_triu[tri_ind], 1.))
    sigma_diag = pm.Deterministic('sigma_mat', tt.nlinalg.diag(sigma))
    cov = pm.Deterministic('cov', pm.math.matrix_dot(sigma_diag, C, sigma_diag))
    
    alpha = pm.Normal('alpha', mu=0, sd=10, shape=k, testval=bet[0,:])
    beta1 = pm.Normal('beta1', mu=0, sd=0.5, shape=(k,k), testval=bet[1:k+1])
    beta2 = pm.Normal('beta2', mu=0, sd=0.5, shape=(k,k), testval=bet[1+k:2*k+1])   
    mu = tt.transpose(alpha) + pm.math.matrix_dot(data_new[1],beta1) + pm.math.matrix_dot(data_new[2],beta2)
    Y_obs = pm.MvNormal('Y_obs', mu=mu, cov=cov, observed=data_new[0])
````

Now, if I just sample by NUTS I get estimates that converged to reasonable values (the initial values are pretty close so I probably don't really need a starting procedure). But when I run ADVI, it gives reasonable values at the beginning and then breaks. It gets worse with more variables in the model. Any indication why this could be?

**Comment by twiecki** [comment]
Is this on master? There was a recent fix for LKJ. Otherwise, there could be strong correlations that violate ADVIs assumptions.

**Comment by tomaskrehlik** [comment]
Yes, it is on master, I was specifically waiting for those fixes to happen.

**Comment by twiecki** [comment]
Maybe look for correlations, but I don't find it overly concerning that ADVI does not work well on particular models.

**Comment by taku-y** [comment]
@tomaskrehlik Did you check the convergence of ELBO?

**Comment by tomaskrehlik** [comment]
I now suspect the problem will be the optimization algorithm from `optimize`, because trying to find an MAP the minimization routine complains about numerical precision and numerical estimates of MAP are far off from the OLS ones. It is weird though, because I was able to optimize the VAR in `R` without much hassle.

The convergence of ELBO is non-existent. If I initialize it with the OLS estimates at the beginning, it starts with giving some numerical values, though, with more and more steps, it starts giving `-Inf` until it returns nothing but those.

**Comment by aseyboldt** [comment]
`LKJCorr` still returns -inf for a lot of matrices, as it requires the matrix to be positive definite. Maybe the typical set of most mean field approximations contains indefinite matrices. If that is the case, we should be able to fix this by implementing the cholesky parameterization of LKJCorr.

**Comment by taku-y** [comment]
@aseyboldt Interesting. ADVI requires that parameters are on real lines without any constraints. Does the cholesky parametrization satisfy that condition?

**Comment by aseyboldt** [comment]
Yes, but sadly it is not implemented yet. #1898 is a (very much unfinished) start.
