### ISSUE TITLE
Posterior predictive sampling broken for thinned traces

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#1906]
See [this notebook](https://gist.github.com/AustinRochford/463f640b3102e9da61d10132437df0fa) for a very simple example.  I believe the issue is [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/backends/ndarray.py#L127) as it appears elsewhere in that file that `draw_idx` is only updated when the trace is sliced with a start and stop, not a step size.

@aseyboldt the last change to that line appears to have happened in #1687, do you have any thoughts on what the best fix is to support thinning here?

**Comment by aseyboldt** [comment]
Looks like I forgot to divide by the step size [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/backends/ndarray.py#L166). I'll fix this up tomorrow. I think a more general problem and the reason there are so many issues like this is that we use the same object to build up the trace and to represent a finished one. Something similar might be happening in other backends, but I haven't checked.

**Comment by AustinRochford** [comment]
I couldn't figure out where that happened, thanks.  I also think we might be able to make the backend API more intuitive/robust with a bit of work.
