### ISSUE TITLE
Pre-defining functions to instantiate random variables with conditional probabilities

### ISSUE THREAD

**Issue by rtbs-dev** [pymc-devs/pymc#1927]
This is somewhat of a continuation of #1790, in that it uses the same example and builds on the idea of using PyMC3 to make a general bayesian network. I've updated the [notebook gist](https://gist.github.com/tbsexton/1349864212b25cce91dbe5e336d794b4) to incorporate NetworkX to instantiate the random variables semi-programatically, such that it might be possible to loop over some pre-defined network and build up a PyMC3 model from there. 

My issue is this: Is there a way to pre-define a function that *will take* PyMC3 random vars as input and output a number, *before* actually calling on `pymc3.Model()`? 

The idea is to store such a function into a node (a value in a dict, essentially) and call on it later with a list of PyMC3 random vars as input, **as the shape parameter in a new RV**. Is this even possible with theano? I've had a lot of issues using numpy functions like `np.select()` before (see the notebook gist).

**Comment by fonnesbeck** [comment]
By "outputting a number" are you talking about evaluating a log-probability? You can always use theano `function`s to do this, if you need to evaluate a Theano expression. However, PyMC variables need to be instantiated with a model, either in a context manager or explicitly using the `model` argument.
