### ISSUE TITLE
Test Failures on GPUs

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#1931]
I was hoping to get the Lasagne convnet blog post running on my GPU, but I ran into some errors and decided I ought to check that the test suite was OK on my machine before proceeding.  However, there are a bunch of failures, including some like the following.  What's the status of testing on the GPU?  Also, has anyone tested pymc3 with the new libgpuarray theano backend?  

```
theano.gof.utils.MethodNotDefined: ('perform', <class 'theano.gpuarray.elemwise.GpuElemwise'>, 'GpuElemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')
Apply node that caused the error: Gpugammaln(GpuElemwise{add,no_inplace}.0)

[...]
======================================================================
ERROR: test_advi_minibatch (pymc3.tests.test_advi.TestADVI)
----------------------------------------------------------------------

TypeError: For compute_test_value, one input test value does not have the requested type.

The error when converting the test value to that variable type:
TensorType(float32, vector) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([ 0.])"



[...]
# Lots of dtype errors in the backend tests, e.g.: 
FAIL: test_dtype (pymc3.tests.test_text_backend.TestNDArrayTextEquality)
AssertionError: dtype('float32') != dtype('float64')
```

**Comment by kyleabeauchamp** [comment]
Uploaded nosetests log to gist for reference: https://gist.github.com/kyleabeauchamp/aaa20f906f1f0dd129cf6094fb3710d4

**Comment by twiecki** [comment]
Thanks @kyleabeauchamp. Running the test suite on float32 in travis is still on the todo list. Before that, however, we need to make it compatible. I have made some progress with making sure models run on float32 but I'm not surprised the backends still have problems.

For the GammaLn problem, I thought we fixed that by moving to theano, see distributions/special.py: `from theano.scalar.basic_scipy import GammaLn, Psi`

Are you on master?

Any help in that regard would be greatly appreciated.

**Comment by kyleabeauchamp** [comment]
I'm on pymc3 master, theano 0.9.RC4, libgpuarray master, and the cuda (libgpuarray) backend for theano, python 3.6 (anaconda), ubuntu 16.04 and a GTX 1060 GPU (cuda 8).

**Comment by twiecki** [comment]
Is the model using the gamma distribution?

**Comment by kyleabeauchamp** [comment]
I've started the long process of fixing this in #1938

Also: in my experience, there are many more test failures on GPU/CUDA platforms than on cpu+float32.  Thus, I don't think it's sufficient to just have float32 tests running on a CPU.

**Comment by twiecki** [comment]
@kyleabeauchamp Great! And yes, definitely need cpu float32 + gpu float32.

**Comment by springcoil** [comment]
Do we have plans to run on a GPU instance too on Travis? This would need some funding I imagine but perhaps could be done with a spot instance.
