### ISSUE TITLE
Add Histogram example and docs

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1932]
The new Histogram class from #1904 is missing documentation describing its usage, as well as a working example. The latter can be either a simple model in the `examples` folder or a fully annotated notebook if it is merited.

**Comment by ferrine** [comment]
@fonnesbeck I can fix it on weekends

**Comment by ferrine** [comment]
[Here](https://github.com/pymc-devs/pymc3/pull/1953) will be a good example of using Histogram in the right way

**Comment by twiecki** [comment]
Let's close in favor of the PR.
