### ISSUE TITLE
iter_sample is slow

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#1935]
In each iteration `iter_sample` slices the whole trace. In the ndarray backend that is bad, but not terrible (when sampling a single normal it takes about 3 times longer), but in the sqlite and the hdf5 backends that means loading the whole thing into memory from scratch at each iteration.

**Comment by aseyboldt** [comment]
@twiecki in  #1934
> @aseyboldt I hadn't realized that. Any ideas on how this could be improved?

It's possible that we could just skip the slice. I'm pretty sure ndarray will do the right thing (`self.draw_idx` stores how many elements we have at a given time). But we should test that a bit. This might require a bit more work for some of the other backends.

**Comment by aseyboldt** [comment]
But this would be a bit of an api change: Right now, the old traces stay how they are when the iteration continues; without the slice, they would not. They'd become longer, too. We could work around that if we split up the backends into a storage class and a representation of a slice (basically a reference to the storage plus their own `draw_idx`). We could also change the api to return points (tuples of points with several chains) instead. But that would certainly be an incompatible change.

**Comment by twiecki** [comment]
Feel free to reopen if this is still an issue.
