### ISSUE TITLE
Nuts doc string is incomplete 

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#1940]

**Comment by aseyboldt** [comment]
Should I open an Issue 1941: "Doc string of issue 1940 is incomplete"? :-)
But when we are on it, we could also change the description of "diverging" a bit to include a stronger warning against trusting results from traces with divergences.

**Comment by twiecki** [comment]
Haha, I lost connection as I opened the issue.

This was the trigger: https://twitter.com/rahuldave/status/844929758173519872

We should have all kwargs (even those that get passed on) in the NUTS doc-string.
