### ISSUE TITLE
figsize is not interpreted correctly by plot_posterior

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1946]
When passing a `figsize` keyword argument to `plot_posterior` the resulting plot is not of the passed dimensions. For example:

     plot_posterior(samples, varnames=['μ'], ref_val=1, figsize=(10,8));

results in:

![unknown](https://cloud.githubusercontent.com/assets/81476/24279141/04afea48-1016-11e7-87da-28c4effaa207.png)

The figure is expected to be wider than tall. 

Running on master with Anaconda Python 3.6 and matplotlib 2.0.0.

**Comment by bhargavvader** [comment]
Will fix this in #1910

**Comment by shivam-bathla** [comment]
@fonnesbeck Could I also help in this issue? I would love to contribute. Just let me know the starting point for this problem...

**Comment by fonnesbeck** [comment]
@DeadlyHollows you are always welcome to submit pull requests. I'm sure its something happening with the Matplotlib GridSpec that is used to lay out the plots.

**Comment by twiecki** [comment]
@bhargavvader Can this be closed?

**Comment by fonnesbeck** [comment]
No, #1910 did not fix this.

**Comment by aloctavodia** [comment]
I am not able to reproduce this issue, just in case I tried importing seaborn and _plain_ matplotlib.  @fonnesbeck do you still have this problem?

**Comment by fonnesbeck** [comment]
I do still see this, yes.

**Comment by aloctavodia** [comment]
I ask a couple of colleagues to reproduce this issue and they can't (all Ubuntu machines). Could this be platform specific?

**Comment by fonnesbeck** [comment]
I've tried to replicate this just now and cannot. I will close for now, and reopen if I see it again.
