### ISSUE TITLE
Update nose-parameterized

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#1947]
```
UserWarning: The 'nose-parameterized' package has been renamed 'parameterized'. For the two step migration instructions, see: https://github.com/wolever/parameterized#migrating-from-nose-parameterized-to-parameterized (set NOSE_PARAMETERIZED_NO_WARN=1 to suppress this warning)
```

**Comment by kyleabeauchamp** [comment]
Detailed instructions on migration are here:

https://github.com/wolever/parameterized#migrating-from-nose-parameterized-to-parameterized

**Comment by ColCarroll** [comment]
Interesting -- I've got a PR (https://github.com/pymc-devs/pymc3/pull/1954) moving us to `pytest` and updating how we parameterize (or, parametrize) things.  The test suite _still_ has a dependency on `nose-parameterized` through theano, though, so we'll at least need to keep track of when they update.

**Comment by fonnesbeck** [comment]
Is this still an issue? In any case, I thought this was a Theano warning (?).

**Comment by kyleabeauchamp** [comment]
It appears that this is no longer directly our issue.  Happy to close for now.

**Comment by ColCarroll** [comment]
It is a theano issue, but not a theano dependency.  I can change how we run travis tests to quiet that down.
