### ISSUE TITLE
Uniform('x', 0, 0, testval=0) returns NaN

### ISSUE THREAD

**Issue by davidbrochart** [pymc-devs/pymc#1963]
I know it is not very useful, but samples from this distribution are `NaN`, even though a `testval` is provided. This used to work fine, even without the `testval` argument. Here is a testcase:
```
from pymc3 import Model, Uniform
import theano.tensor as T
from theano.compile.ops import as_op

@as_op(itypes=[T.dscalar], otypes=[T.dscalar])
def model(value):
    print(value)
    return value

with Model() as model_deterministic:
    x = Uniform('x', 0, 0, testval=0)
    sim = model(x)
```

**Comment by aseyboldt** [comment]
This might be because of #1890. But why would you expect this to work? Uniform(0, 0) isn't even an absolute continuous distribution anymore. To me, returning nan seems like a reasonable thing to to.

**Comment by davidbrochart** [comment]
I was just trying to change as little code as possible to fix a parameter to a specific value, but I agree it is a dirty hack. Just wanted to check that was not a regression.
Thanks.

**Comment by twiecki** [comment]
@davidbrochart There is a constant distribution I think.
