### ISSUE TITLE
Double cloning fails for generator

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#1965]
Recently I found a bug while using pm.generator
It appears that double stage cloning is not available for it
```python
def test_gen_double_cloning_with_shape_change(self):
    dim = 10
    data = np.random.uniform(size=(1000, dim))
    shared_1000 = theano.shared(data)
    constant_50 = tt.constant(data[:50])
    minibatches_50 = DataSampler(data, batchsize=50)
    gen_50 = generator(minibatches_50)
    stream = tt_rng().normal(size=(dim, ))
    stream_in = tt.vector()
    stream_in.tag.test_value = stream.eval()
    const_modif = constant_50.dot(stream_in)
    const_modif_1_50 = theano.clone(const_modif, {stream_in: stream})
    const_modif_2_1000 = theano.clone(const_modif_1_50, {constant_50: shared_1000})
    assert const_modif_1_50.eval().shape == (50,)
    assert const_modif_2_1000.eval().shape == (1000,)
    gen_modif = gen_50.dot(stream_in)
    gen_modif_1_50 = theano.clone(gen_modif, {stream_in: stream})
    gen_modif_2_1000 = theano.clone(gen_modif_1_50, {gen_50: shared_1000})
    assert gen_modif_1_50.eval().shape == (50,)
    assert gen_modif_2_1000.eval().shape == (1000,) # fails (50,)
```

**Comment by ferrine** [comment]
While reverse order cloning works
```
gen_modif_1_50 = theano.clone(gen_modif, {gen_50: shared_1000})#{stream_in: stream})
gen_modif_2_1000 = theano.clone(gen_modif_1_50, {stream_in: stream})# {gen_50: shared_1000})
#assert gen_modif_1_50.eval().shape == (50,)
 assert gen_modif_2_1000.eval().shape == (1000,)
```
CC @nouiz
That is a very strange behavior in cloning... What can happen with a cloned graph so that old parts (my generator) will not be replaced?
When I call `pprint(theano.clone(gen_modif_1_50, {gen_50: shared_1000}))` I can still see my generator:(

**Comment by nouiz** [comment]
I don't master theano.clone. Can you expand your code sample so that I can run it without modification? Can you modify it to what what you expect and what you got?

In theory, double cloning should work. Blocks does that very frequently. But there is some corner case that is trouble some that you could hit. Blocks don't hit them. I don't recall those corner cases. But with a script as I described above, I could double check that.

**Comment by ferrine** [comment]
@nouiz here is a [reproducible gist](https://gist.github.com/ferrine/2f61214825f7f6d6ae43c65ca04daf02)
