### ISSUE TITLE
Feature Request: Allow multiple random variables be named "_" 

### ISSUE THREAD

**Issue by schlichtanders** [pymc-devs/pymc#1966]
maybe this already exists, or maybe this was already discussed a lot before and found to be unreasonable:

It seems to me that it would be great to have a way to don't specify the name of a random variable. Currently I would fall back to define multiple names like "_1", "_2", ... "_k" myself, but this could be a really useful thing integrated into pymc3 itself.

```python
import pymc3 as pm
with pm.Model() as model:
    noreference_needed_later = pm.Normal("_", 0, 1)
    same_here = pm.Normal("_", 1, 2)
```

What about using "_" as the default name which just means "I don't need a name/reference for this" and internally it is either implemented without name at all, or a running number is appended like above  in order to make the names unique under the hood?

**Comment by twiecki** [comment]
That seems a bit hacky, and we need a reference name internally. You could always create a generator for your names and then do `pm.Normal(name_gen.next(), ...)`. But you should also consider vectorizing your model which would be much faster.
