### ISSUE TITLE
Trouble installing at 3.1rc3

### ISSUE THREAD

**Issue by skatenerd** [pymc-devs/pymc#1967]
When I try to `pip install` (on Linux) at `3.1rc3`, I see the following crash:

```
    copying pymc3/examples/data/srrs2.dat -> build/lib.linux-x86_64-2.7/pymc3/examples/data
    error: can't copy 'pymc3/examples/data/pmf': doesn't exist or not a regular file

    ----------------------------------------
  Rolling back uninstall of pymc3
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-o6ELnS-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2ix0qe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-o6ELnS-build/
```

I am guessing that this failure was introduced with [this change](https://github.com/pymc-devs/pymc3/commit/1210ed6ab3236c3caeed03a8023087501cccd7a6#diff-2eeaed663bd0d25b7e608891384b7298R52).  I think that `/pymc3/examples/data/pmf` is a directory, and `setuptools` expects all of the glob-matches to be flat files (rather than directories).  There is some discussion of the issue in [this SO post](http://stackoverflow.com/questions/3712033/python-distutils-error-directory-doesnt-exist-or-not-a-regular-file).

**Comment by twiecki** [comment]
@skatenerd Thanks for the report. I think @ferrine has some experience with `find_packages`.

**Comment by skatenerd** [comment]
FWIW, I'm consuming [this](https://github.com/skatenerd/pymc3/commit/ff5c835ea9df5a11e566dbcd05b79642a8fa8fd3) and it's building on my machine

**Comment by ferrine** [comment]
I think this solution is better http://stackoverflow.com/a/25375689/74632

**Comment by ferrine** [comment]
@skatenerd Is it solved by #1997?

**Comment by twiecki** [comment]
Closing due to non-response.

**Comment by skatenerd** [comment]
@twiecki @ferrine Yes, this solved the problem!  Thank you!

Sorry for the non-responsiveness.  I've been on vacation, far away from computers.
