### ISSUE TITLE
Update docs for 3.1

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#1968]
I think we need to have the documentation brought up to date with the various innovations that have been introduced to PyMC (including those back in the 3.0 release). There is currently no mention of ADVI in the Sphinx docs, for example. While notebooks are great, they are typically specific examples or use cases, and not a comprehensive documentation of features. There are a few documentation-related issues open that partially cover what needs to be done. A more comprehensive list is as follows:

- [x] ADVI
- [x] OPVI
- [x] SVGD
- [ ] Histogram
- [x] Gaussian processes
- [x] Use of `shared` variables (and other Theano idioms) in PyMC3 
- [x] Use of `Bound`
- [x] Model selection
- [x] Update LKJ notebook
- [x] Generators and minibatch
- [x] Sampling functionality

Please add to or edit this list. It would be great to make some headway on this in conjunction with the 3.1 release. Perhaps we could organize a "Docs Day"  where a few of us knock out drafts of some of this??

**Comment by springcoil** [comment]
Sorry for the silly question but where do we update the sphinx docs - in the docstring itself?

**Comment by ferrine** [comment]
Use of Generators should be documented too.

**Comment by twiecki** [comment]
@springcoil yeah, docs/source directory.

**Comment by springcoil** [comment]
@fonnesbeck https://pymc-devs.github.io/pymc3/api/inference.html#variational ADVI is mentioned in the sphinx docs... However it's not searchable

**Comment by springcoil** [comment]
I made a first stab at this with these first two examples.

**Comment by bwengals** [comment]
Would be happy to help with GP docs.  Right now the docs, not including the examples or API reference, are the paper on PyMC3.  Is the plan to expand this section?  Or fix up API docstrings?

**Comment by fonnesbeck** [comment]
The `getting_started` document is all there is, outside of the API and the examples. It would be great to have additional sections to cover:

- Gaussian processes
- Variational methods
- Plotting and visualization
- Modeling strategies

**Comment by ferrine** [comment]
I see [here](https://github.com/pymc-devs/pymc3/blob/master/docs/source/api/inference.rst#advi-approximations) that approximations  are included in docs but they are not displayed anywhere http://pymc-devs.github.io/pymc3/api.html
How comes?

**Comment by junpenglao** [comment]
I think this can be close now (and open a new one for 3.2 for any remain issue)

**Comment by aseyboldt** [comment]
Most of them? :-(

**Comment by zaxtax** [comment]
What are the remaining issues?
