### ISSUE TITLE
Feature Request: Possibility to not sample intermedite random variables

### ISSUE THREAD

**Issue by schlichtanders** [pymc-devs/pymc#1972]
Maybe this is already possible, however I unfortunately was not able to find it:
If I define my model, I might want to sample only certain parameters of the models, or upside-down want to exclude parameters from being sampled because they are only intermediate helpers.

I expected a parameter at ``pm.sample`` specifying which variables shall be sampled, however couldn't find anything.

One reason I have in mind is that sampling of certain parameters only is probably faster than sampling everything.

Is there a way to accomplish this?
Any help is very much appriciated

**Comment by fonnesbeck** [comment]
By "not sampling", I assume you mean they are constant, then? In that case, set `observed` to a particular value you want to fix them to, and they will not be sampled.

**Comment by schlichtanders** [comment]
interesting, I definitely haven't thought that this could be ambiguous, think of
```python
import pymc3 as pm
with pm.Model as model:
    e = pm.Normal("e", shape=(10,))
    x = pm.Deterministic("x", cumsum(e))
    y = pm.StudentsT("y", mu=x, observed=data)
```
where I don't need to know the samples of ``e``, knowing the samples of ``x`` would be totally enough

**Comment by fonnesbeck** [comment]
So you want to sample `e` in order to get a new value for `x`, but not save the value to the trace?

**Comment by schlichtanders** [comment]
please mind with me if I don't know how the sampling is done within ``pm.sample``.

I can imagine that you can sample ``x`` by composing and simplifying its respective ``logP`` expression in a way which does not imply that you automatically also sample ``e`` meanwhile.

That is not an answer to your question, but rather an explanation why I haven't understood your question.

**Comment by fonnesbeck** [comment]
`x` is not sampled, but is just transformed from `e`, so its impossible to get samples of the former without samples of the latter. The only other way to do this is to create a custom `CumSumNormal` stochastic with the appropriate `logp` for the cumulative sum of a vector of normals.

**Comment by schlichtanders** [comment]
does this reasoning also hold for y? I mean if you use y somewhere in a even more nested model (e.g. as the rate for a Poisson model of the data), would sampling ``y`` still involve sampling of ``e`` ?

**Comment by fonnesbeck** [comment]
It always holds, yes. Deterministics are only random (i.e. not fixed) if their parents are random.

**Comment by schlichtanders** [comment]
Thanks a lot for explaining. Yes then it makes a lot of sense to me now that all parameters are always sampled. It is a very clean interface with neglectible overhead (storing intermediate results).
Thanks a lot for this discussion!

**Comment by fonnesbeck** [comment]
No problem! If you need to extend the discussion, I recommend posting something on StackOverflow.
