### ISSUE TITLE
Error sampling from GP: mean function dimensions

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#1984]
Hi @twiecki & @fonnesbeck! Pardon me if my question is kind of noob here, I've only just started learning & playing around with GPs.

A bit of background: I'm experimenting with GPs as a tool for time-series data. I have used autoencoders to learn a 2D embedding of influenza protein sequences, and it turns out there's a temporal "direction" of sorts when I look at the mean embedding coordinates over time, but it's non-linear. Notebooks can be found here ([GP modelling](https://github.com/ericmjl/autoencoders/blob/master/gaussian-process-regression.ipynb)) and here ([autoencoders](https://github.com/ericmjl/autoencoders/blob/master/gaussian-process-regression.ipynb)) . I am using code from the docs as a starting point. 

On the GP modelling [notebook](https://github.com/ericmjl/autoencoders/blob/master/gaussian-process-regression.ipynb), after specifying the model (eliminating priors on hyperparameters while I do my experimentation, it's for speed), I try sampling from the GP; this is cell 63 near the end of the notebook. At that point, I get an error that says, `ValueError: Array 'mean' must be a vector of length 17.` (or whatever length I specify my `Z` vector to be (which, in the notebook, is the new X-axis coordinates to sample). 

I'm not sure what I might be missing here - do I have to pass in the original data somewhere else in the model specification? Please let me know!

**Comment by fonnesbeck** [comment]
That's odd. Can you try making the `y` 1-D rather than 2-D? It should work in either case, but maybe see if this fixes the issue.

**Comment by ericmjl** [comment]
@fonnesbeck yes, with a 1-D `y`, it works; with a 2-D `y`, it doesn't. 

I'm truly a noob :rofl: thank you for helping!

**Comment by fonnesbeck** [comment]
Cool. We should probably have a better docstring to describe the shape, or at least squeeze the y input to force it into shape.
