### ISSUE TITLE
with keyword error

### ISSUE THREAD

**Issue by prabhant** [pymc-devs/pymc#1986]
Getting error after this line from docs
Y_obs = Normal('Y_obs', mu=mu, sd=sigma, observed=Y) 

> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\LUCIFER\Anaconda3\lib\site-packages\pymc3\model.py in get_context(cls)
    120         try:
--> 121             return cls.get_contexts()[-1]
    122         except IndexError:

IndexError: list index out of range

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
C:\Users\LUCIFER\Anaconda3\lib\site-packages\pymc3\distributions\distribution.py in __new__(cls, name, *args, **kwargs)
     21         try:
---> 22             model = Model.get_context()
     23         except TypeError:

C:\Users\LUCIFER\Anaconda3\lib\site-packages\pymc3\model.py in get_context(cls)
    122         except IndexError:
--> 123             raise TypeError("No context on context stack")
    124 

TypeError: No context on context stack

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-25-f778a5d49032> in <module>()
----> 1 Y_obs = Normal('Y_obs', mu=mu, sd=sigma, observed=Y)

C:\Users\LUCIFER\Anaconda3\lib\site-packages\pymc3\distributions\distribution.py in __new__(cls, name, *args, **kwargs)
     22             model = Model.get_context()
     23         except TypeError:
---> 24             raise TypeError("No model on context stack, which is needed to "
     25                             "use the Normal('x', 0,1) syntax. "
     26                             "Add a 'with model:' block")

TypeError: No model on context stack, which is needed to use the Normal('x', 0,1) syntax. Add a 'with model:' block

**Comment by ColCarroll** [comment]
the `TypeError` at the bottom is pretty descriptive: try changing this to 

```
from pymc3 import model

with model:
    Y_obs = Normal('Y_obs', mu=mu, sd=sigma, observed=Y)

```
