### ISSUE TITLE
Predictive posterior checks for ADVI

### ISSUE THREAD

**Issue by pwl** [pymc-devs/pymc#1996]
It seems to me that `sample_ppc` returns noise if used on trace coming from `sample_vp`.  I prepared a simple [example](https://gist.github.com/pwl/e867e1a8b9413fd8e058bd29ad9ee858) implementing a Poisson Matrix Factorization model.  In the example `sample_ppc` for NUTS recreates the initial data but `sample_ppc` for a trace from ADVI gives me only noise.

**Comment by twiecki** [comment]
@pwl are you sure that ADVI finds a good solution? You might want to compare sampe_vp to the trace returned by NUTS.

**Comment by twiecki** [comment]
Sorry, I see you do have a check for that in place.

**Comment by twiecki** [comment]
The only difference can be the input to sample_ppc, so I would look more closely at the two traces.

**Comment by ferrine** [comment]
Can we close the issue?

**Comment by twiecki** [comment]
@ferrine Sorry, lost track, where was this fixed?

**Comment by ferrine** [comment]
That's not a problem for sample_pcc but for inference method chosen for the problem, isn't it? I'll try to check it out with new advi.

**Comment by ferrine** [comment]
That was ok for new ADVI, see [gist](https://gist.github.com/ferrine/b8e0bd900ad34bfd9debcc23072a7f4a)

**Comment by twiecki** [comment]
@ferrine thanks for checking.

**Comment by ferrine** [comment]
@pwl thanks for providing this gist

**Comment by pwl** [comment]
Nice!  Thanks for fixing this!
