### ISSUE TITLE
Remove memoization of graph nodes

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#2006]
According to https://github.com/Theano/Theano/issues/5809
Memorization can encounter strange problems when you do more than one replacement. We use it in model class for logpt I think we should remove it at all. Moreover calling it before model is finished breaks inference as logpt remains unchanged even after new random variables created

**Comment by twiecki** [comment]
@ferrine Wouldn't that slow down calls to logpt significantly?

**Comment by ferrine** [comment]
logpt just creates a tensor, there is no reason why it will be slow

**Comment by twiecki** [comment]
@ferrine Right, we can remove it then.
