### ISSUE TITLE
Parallel sampling of deterministic models fails (can't pickle as_op())

### ISSUE THREAD

**Issue by davidbrochart** [pymc-devs/pymc#2009]
I updated to 3.1rc3 which depends on theano 0.9.0, and now I get this error message when doing parallel sampling with deterministic models:
PicklingError: Can't pickle as_op(), not the object at __main__.logp

**Comment by aseyboldt** [comment]
Can you post a minimal example? I tried one myself and it worked for me:
```python
@theano.as_op([tt.dscalar], [tt.dscalar])
def f(x):
    return x ** 2

with pm.Model() as model:
    a = pm.Normal('a', 0, 1)
    b = pm.Deterministic('b', f(a))

with model:
    trace = pm.sample(10, njobs=2, init=None)
```

**Comment by davidbrochart** [comment]
This tutorial shows the error, if you change cell 15 with njobs=2:
https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/updating_priors.ipynb

**Comment by aseyboldt** [comment]
I found a smaller example with the same problem:
```python
def blubb():
    @theano.as_op([tt.dscalar], [tt.dscalar])
    def f(x):
        return x ** 2
    return f

with pm.Model() as model:
    a = pm.Normal('a', 0, 1)
    b = pm.Deterministic('b', blubb()(a))

with model:
    trace = pm.sample(10, njobs=2, init=None)
```

**Comment by twiecki** [comment]
That's a Python issue though, not a pymc3 or theano one.

**Comment by aseyboldt** [comment]
Dill can't pickle it either, so I guess there isn't anything we can do here. But it shouldn't be too hard to refactor this such that it does not generate theano ops in functions.

**Comment by kyleabeauchamp** [comment]
cc @aseyboldt  I just re-visited some working code that I had and encountered this bug.  Presumably this is another argument in favor of setting the default `njobs` back to 1, as both GPUs and `as_op` are broken in a multiprocess setting.
