### ISSUE TITLE
Examples pymc2 => pymc3

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2022]
Hello everybody,
first of all thanks for this library. I like it A LOT!

I'm new to pymc3 (and probabilistic programming) and I find many Pymc examples on the web that I cannot convert to pymc3. Would it be possible to add a page on the website to help people converting pymc2 instructions to pymc3?

(example: http://stackoverflow.com/questions/43328715/car-model-from-pymc2-to-pymc3 disclamer I'm the one who asked it)

**Comment by junpenglao** [comment]
For you particular problem, it is worth to have a look at the [GP smoothing](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-smoothing.ipynb) notebook in the example and the new `pymc3.gp.GP` class as this kind of local smoothing problem could be expressed in Gaussian Process quite naturally.

As for you general question of porting pymc2 code into pymc3 (or even generally porting WinBugs, JAGS, or STAN code into pymc3), from my experience you should try to think in matrix/tensor.
The underlying mechanism in pymc3 is very different compared to pymc2, using for-loop to generate RV or stacking multiple RV with arguments such as `[pm.Binomial('obs%'%i, p[i], n) for i in range(K)]` generate unnecessary large number of nodes in theano graph, which then slow down the compiling to an unbearable amount.  

If you are interested in more information of how to port WinBugs, JAGS, or STAN code into pymc3, you can have a look of [my port of Lee and Wagenmakers' book](https://github.com/junpenglao/Bayesian-Cognitive-Modeling-in-Pymc3). For example, in Chapter 19, the STAN code use [a for loop to generate the likelihood function](https://github.com/stan-dev/example-models/blob/master/Bayesian_Cognitive_Modeling/CaseStudies/NumberConcepts/NumberConcept_1_Stan.R#L28-L59), and I [generate the matrix outside and use matrix multiplication etc](http://nbviewer.jupyter.org/github/junpenglao/Bayesian-Cognitive-Modeling-in-Pymc3/blob/master/CaseStudies/NumberConceptDevelopment.ipynb#19.1-Knower-level-model-for-Give-N) to archive the same purpose.

**Comment by denadai2** [comment]
Great answer and examples! Thanks! The problem is how to model in pymc3 these type of parameters:

![screen shot 2017-04-13 at 17 27 18](https://cloud.githubusercontent.com/assets/190799/25020192/b0ab60f2-208d-11e7-9f08-6171d0db6ac9.png)

where you have strong dependencies between prios (b and lambda in this case). A guide would be super useful for everyone :))

**Comment by junpenglao** [comment]
You will need to define your custom likelihood function with `pymc3.DensityDist` using the theano loop `theano.scan`. Something similar to the [timeseries distribution](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/timeseries.py#L125-L130).

I dont think there is any guide for that yet - but I can try to reformulate the CAR model in your question which has something similar.

**Comment by junpenglao** [comment]
@denadai2 I am working on a [Gist](https://gist.github.com/junpenglao/c7e3e7589e5e535def4a00630f4e8569) for porting the CAR model from PyMC2 (and Winbugs) into PyMC3. Will add it to the docs when ready. #1968

**Comment by denadai2** [comment]
Wow this is really awesome! Thanks to you I implemented the BYM model of CAR
I think that your notebook could be really helpful for many people, to understand how pymc3 works

**Comment by twiecki** [comment]
@junpenglao definitely make a PR
