### ISSUE TITLE
sample_vp does not accept Histogram as argument

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2026]
The `Histogram` object that is returned from `SVGD` estimation does not work with the `sample_vp` function to generate samples. The method works, but not the function. To maintain a consistent interface, there should be a function to generate samples.

That is:

```
approx = fit(...)
trace = sample_vp(approx, ...)
```

**Comment by ferrine** [comment]
PR #2027 solves the issue
