### ISSUE TITLE
advi conversion detection for simple models

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#2031]
For very simple models the convergence detection in advi often fails:

```python
with pm.Model() as model:
    pm.Normal('a', mu=0, sd=1)
    trace = pm.sample(2000, tune=1000)
```
```
Auto-assigning NUTS sampler...
Initializing NUTS using advi...
Average ELBO = -0.0041863: 100%|██████████| 200000/200000 [00:09<00:00, 20760.85it/s]
Finished [100%]: Average ELBO = -0.0026801
Evidence of divergence detected, inspect ELBO.
100%|██████████| 2000/2000 [00:00<00:00, 3181.49it/s]
```
Most of the time is spend on uselessly on advi. Any idea how to fix this? CC @lbollar

Also, it tells me to inspect the elbo, but we don't have a way to access that though `pm.sample`.

**Comment by twiecki** [comment]
That's surprising. I would run ADVI independently and look at the ELBO.

**Comment by aseyboldt** [comment]
Maybe that wasn't clear: The problem is not that advi diverges. It is just fine. The problem is that the convergence *detection* doesn't work.

**Comment by junpenglao** [comment]
Maybe the sampling was too fast (20760.85it/s) and the test didn't run in time.

**Comment by twiecki** [comment]
Right, I still think it's useful to look at the ELBO to try and get a sense of why it's failing.

**Comment by aseyboldt** [comment]
The elbo converges too quickly. It gets to the right values after a couple of iterations, and then just goes up and down a little bit. I think the problem is that the current code compares the variance of the elbos in different time windows.  But because it gets to the right values so quickly, the variance never changes.

@junpenglao It checks once every couple of iterations. The time doesn't matter.

**Comment by twiecki** [comment]
@aseyboldt Yep: https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/advi.py#L180

**Comment by twiecki** [comment]
Question is how we can change that criterion to work in this case as well.

**Comment by lbollar** [comment]
Is this just a matter of changing the eval_elbo window length?

I wonder if this is something that happens often, is there a way to tune the value possibly?

**Comment by lbollar** [comment]
Also, might try running in Stan. The goal was to replicate their criterion originally. Does same issue occur there?

**Comment by aseyboldt** [comment]
It might be that simple, I don't know. Pretty sure I've seen that a couple of times even with models that were not *that* simple.

**Comment by aseyboldt** [comment]
Also, there is a `CheckLossConvergence` in #2027, that seems on first glance like it does something similar. Is this related? @ferrine

**Comment by ferrine** [comment]
Old convergence did not work for me too. New convergence check sometimes triggers

**Comment by ferrine** [comment]
I've reimplemented old one but it was breaking my test triggering too early, I'll look closer why is it so

**Comment by lbollar** [comment]
If someone has experience with convergence checking in Stan, it would be
good to know. Maybe it is just something that helps on some occasions...

**Comment by ferrine** [comment]
It would be great I'm not experienced in inventing such criteria. `CheckLossConvergence` is too naive I think

**Comment by ferrine** [comment]
I'm currently trying to write convergence test based on parameters updates, it is needed for SVGD without loss but can be useful somewhere else

**Comment by ferrine** [comment]
checking how parameters change works extremely good

**Comment by lbollar** [comment]
When I ran this I didn't actually replicate it. Is there any set up involved in replicating the above result?

**Comment by aseyboldt** [comment]
This seems to be fixed on master.
