### ISSUE TITLE
update external/edward.py and examples/edward_beta_bernoulli.py following Edward API changes

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2034]

**Comment by junpenglao** [comment]
This is actually more difficult than I though... @ColCarroll 
I think at this point maybe we should remove the `Edward` related support for now (in released, readme, etc). In the future, when we have SMC and ABC we can add back the support (ie. arbitrary black-box model that can be sampled from).

**Comment by twiecki** [comment]
I agree, should probably drop it for now.

**Comment by fonnesbeck** [comment]
I agree too. The integration is cool, but not critical.
