### ISSUE TITLE
GPU (and float32) Support: Tests

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#2053]
Here is the checklist of test modules that are running on the cuda/float32 platform:

- [x] test_advi.py
- [ ] test_diagnostics.py
- [x] test_dist_math.py
- [x] test_distribution_defaults.py
- [ ] test_distributions.py
- [ ] test_distributions_random.py
- [x] test_distributions_timeseries.py
- [x] test_examples.py
- [x] test_glm.py
- [x] test_gp.py
- [x] test_hdf5_backend.py
- [ ] test_hmc.py
- [x] test_math.py
- [x] test_memo.py
- [x] test_missing.py
- [x] test_mixture.py
- [x] test_modelcontext.py
- [x] test_model_func.py
- [x] test_model_helpers.py
- [x] test_model.py
- [x] test_models_linear.py
- [x] test_models_utils.py
- [x] test_ndarray_backend.py
- [x] test_pickling.py
- [ ] test_plots.py
- [x] test_posdef_sym.py
- [ ] test_posteriors.py
- [x] test_profile.py
- [x] test_quadpotential.py
- [ ] test_sampling.py
- [x] test_shared.py
- [x] test_special_functions.py
- [ ] test_sqlite_backend.py
- [x] test_starting.py
- [x] test_stats.py
- [x] test_step.py
- [x] test_text_backend.py
- [x] test_theanof.py
- [x] test_tracetab.py
- [x] test_transforms.py
- [x] test_tuning.py
- [x] test_types.py
- [x] test_variational_inference.py

**Comment by kyleabeauchamp** [comment]
PS: the checkboxes are after my PRs #2054 and #2051 and #2055 .  

Also, I haven't finished going through all the tests, so my list here is incomplete.

**Comment by kyleabeauchamp** [comment]
Also assuming #2060 gets merged.

**Comment by kyleabeauchamp** [comment]
Of the remaining:

test_distributions is do-able but a mild pain because it involves iterating over lots of inputs and Domain() objects, and it's not clear how to easily do the dtype casting in a way that doesn't go overboard with the casting.

test_math has a logDet failure that looks like a possible missing implementation in the cuda platform, similar to the errors we previously got fixed upstream.  Log here: https://gist.github.com/kyleabeauchamp/cf79563c1348f07a260aaf41a9c24f26

The others hit the pickling error and the b"" ndarray errors that I've opened up tickets on.

**Comment by twiecki** [comment]
Can we somehow make Domain() aware of floatX?

And yes, logDet misses a cuda implementation. We used it for MvNormal but removed it since then. The test can be skipped.

**Comment by kyleabeauchamp** [comment]
Here is the remaining error log for test_step (after PR #2065).  There's something funny going on with some of the step methods.  

https://gist.github.com/kyleabeauchamp/723680a10f8d68f4d4d218a5b87caed7

**Comment by twiecki** [comment]
That's an odd one. It seems like an issue with test_values, presumably related to it being float64? Although that doesn't show up in the error (perhaps masked by cloning somehow). Anyway, that's where I'd start. Do you know about http://deeplearning.net/software/theano/library/config.html#config.warn_float64? I found that very helpful.

**Comment by twiecki** [comment]
@kyleabeauchamp Are you still working on this, are you blocked by anything?

**Comment by kyleabeauchamp** [comment]
Haven't done anything for a couple of weeks, main blockage is lack of time.

**Comment by kyleabeauchamp** [comment]
I started re-checking and saw some regressions (test_dist.py).  

We need to add float32 to the Travis matrix so that this is tested automatically, IMHO.

**Comment by kyleabeauchamp** [comment]
I think this is now obsolete; remaining float32 failures are marked by skiptest or xfail.

**Comment by junpenglao** [comment]
Thanks for the work @kyleabeauchamp !
