### ISSUE TITLE
MvNormal: njobs doesn't work

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2057]
Is it possible that MvNormal doesn't respect the njobs of pm.sample(niters, njobs=2, step=pm.Metropolis())? When I use this code, I have many many jobs

    def macnab(tau, n, p, R):
        return tau * (p * R + (1-p)*np.identity(n))

    tau = pm.Gamma('tau', alpha=0.001, beta=0.001)
    p = pm.Uniform('p', lower=0.0, upper=1.0)
    phi = pm.MvNormal('beta', mu=0., tau=macnab(tau, n, p, R), shape=n)

where R is a square matrix.

**Comment by twiecki** [comment]
Is the result different if you don't use mvnormal? How do you test that more than 2 processes are running?

**Comment by denadai2** [comment]
yes. I can share the code, and data in private. I use htop :)

**Comment by aseyboldt** [comment]
This might be due to blas. Depending on which blas you link against (the default should be the same as numpy is linked to), this will use a multithreaded implementation for each job. You can control the number of threads per job by setting the environment variable `OMP_NUM_THREADS`.

**Comment by denadai2** [comment]
ok thanks!
