### ISSUE TITLE
PyData - PyMC3 first commit session

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2062]
At PyData London I've agreed to help a new contributor with a first commit to PyMC3 - I think the session will be on the May 7th 2017. 

Not sure how success this will be but I just wanted to put a remark here. If anyone sees any other beginner friendly issues, please add a label so it's easy to find.

**Comment by ColCarroll** [comment]
Seems like there could be some interesting projects done with the sampler stats, maybe @aseyboldt  has thoughts?

**Comment by springcoil** [comment]
This became basically an intro to the project. No commits happened.
