### ISSUE TITLE
Wrong module in getting started document

### ISSUE THREAD

**Issue by jrings** [pymc-devs/pymc#2069]
In http://pymc-devs.github.io/pymc3/notebooks/getting_started.html, it reads "Here is what the simulated data look like. We use the `pylab` module from the plotting library matplotlib."

I believe this should read 

"Here is what the simulated data look like. We use the `plt` module from the plotting library matplotlib."

**Comment by junpenglao** [comment]
well i am not an expert of Python but I think it is the `pylab` module.
