### ISSUE TITLE
pymc3/pymc3/gp/mean.py seems to assume the same shape for X and Y in Class Zero and Constant

### ISSUE THREAD

**Issue by zero-you** [pymc-devs/pymc#2078]
This causes an exception when I try to create a GP with 6-D inputs and 1-D output, e.g., X.shape=[100,6] and Y.shape=[100,1]

In pymc3/gp/mean.py, the return values of Zero and Constant have the same shape as X:

class Zero(Mean):
    def __call__(self, X):
        return tt.zeros(X.shape, dtype='float32')

class Constant(Mean):
    def __init__(self, c=0):
        Mean.__init__(self)
        self.c = c
    def __call__(self, X):
        return tt.ones(X.shape) * self.c

**Comment by bwengals** [comment]
Good catch, this is definitely a bug.  Are you planning on submitting a PR?  If not, I am happy to.

**Comment by zero-you** [comment]
@bwengals Please go ahead. I am not sure what would be the best way to fix it - Maybe allow users to pass Y shape as an optional input argument?

**Comment by junpenglao** [comment]
Should be fixed now.
