### ISSUE TITLE
Multivariate Normal Dirichlet Process Posterior Distribution is Constant

### ISSUE THREAD

**Issue by databro** [pymc-devs/pymc#2079]
I'm struggling to sample from a Multivariate Normal Dirichlet process I just defined in pymc3. The sampler does not really do well to figure out the posterior distribution over the weights. I think there may be an issue with stick breaking and multivariate distributions. Code is here: 

https://stackoverflow.com/questions/43611458/multivariate-normal-dirichlet-process-posterior-distribution-is-constant

Thanks!

<img width="959" alt="screen shot 2017-04-25 at 13 59 59" src="https://cloud.githubusercontent.com/assets/10848993/25401295/474747a2-29ed-11e7-855c-60f700b42c82.png">

**Comment by databro** [comment]
23 hours later, still no solution. I think this is definitely a bug in pm.Mixture, it's having a great deal of trouble sampling anything but alpha from the posterior, it's like it gets stuck in one state and refuses to move.

**Comment by junpenglao** [comment]
multivariate Gaussian mixture model is not that straight forward to model, you might need to write a custom `logp` for more efficient sampling. I am working on some similar problem but yet to find a satisfying solution (I tried on STAN, edward, and PyMC3).

**Comment by databro** [comment]
Thanks I thought maybe it was a problem with my implementation but clearly it's more difficult than it looks.

**Comment by junpenglao** [comment]
Yeah, it is much more complicated than I think. I worked on it on and off for one of my projects but at the end just settle for the more stable classic EM solution.
You can have a look at my [Gist](https://gist.github.com/junpenglao/f5b3749393c92f516230a1ea389d1380) for some inspiration. It would be great if someone can come up with a robust solution.

**Comment by databro** [comment]
Thanks Homie.
