### ISSUE TITLE
Javascript progress bar

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#208]
As mentioned here https://github.com/ipython/ipython/issues/1527/#issuecomment-16356919 . We have a pretty javascript progress bar ready to go if we can figure out how to only use it when its appropriate.

**Comment by fonnesbeck** [comment]
The text progress bar currently implemented works really well. Much better than the one for PyMC2, which caused the ipython notebook to jitter.

**Comment by jsalvatier** [comment]
Yeah, I noticed that. I think the difference was doing the updates on a timer vs doing them each time.

**Comment by fonnesbeck** [comment]
Closing. Create pull request if there is progress (see what I did there??).
