### ISSUE TITLE
DOCS: explain Compound Step in sampling

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2083]
Currently, there is no information on the compound step method.
There are some examples here and there in the docs, which using a compound step assignment `step = [step1, step2]`. However, is it unclear:
1. what happen when pymc3 assign sampler under the default condition? 
2. the order of step methods. for example, is the next sample propose at the same time or in a sequential manner.
3. is there a way to specify the order of the step methods? Is it possible to do a NUTS within Gibbs kind of idea?
4. some guideline on mixing different sampler, eg bob's comment in [#1990](https://github.com/pymc-devs/pymc3/issues/1990#issuecomment-292199469).

**Comment by springcoil** [comment]
Does anyone have any resources that could help with this?

**Comment by junpenglao** [comment]
I have drafted a notebook explaining this, following [a similar discussion on discourse](https://discourse.pymc.io/t/compounds-steps/954): https://github.com/junpenglao/Planet_Sakaar_Data_Science/blob/master/PyMC3QnA/CompoundStep_Explained.ipynb
Need some help to formatted it and extend it into a proper doc.

**Comment by huangy22** [comment]
Hi, I want to try to work on this as my first issue. Is it okay? Thanks!

**Comment by junpenglao** [comment]
Absolutely! If you have any additional question feel free to post it on discourse.

**Comment by huangy22** [comment]
I wrote some explanation in the sample function (PR #3014) and please let me know if there's any improvement I could make! Thank you!

**Comment by junpenglao** [comment]
close via #3014
