### ISSUE TITLE
GLM hierarchical notebook error

### ISSUE THREAD

**Issue by akansal1** [pymc-devs/pymc#2087]
I am trying to run hierarchical  modelling [example](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GLM-hierarchical.ipynb) notebook, following line:
```python
start, step = pm.init_nuts(n_advi=20000, n_nuts=2000)
```
is giving error **```n_advi```** and **```n_nuts```** do not exist

How should I approach it ?

Thanks

**Comment by junpenglao** [comment]
There are some API changes recently and the notebook will need to be updated. For now you can just skip that cell and do
```python
with hierarchical_model:
    hierarchical_trace = pm.sample(5000, tune=1000, njobs=2)
```
which use the default ADVI initialization.

**Comment by ColCarroll** [comment]
I am about to push a fix!
