### ISSUE TITLE
plot_posterior(): hpd labels overlap

### ISSUE THREAD

**Issue by JWarmenhoven** [pymc-devs/pymc#2090]
When comparing shapes of posterior distributions, it can sometimes be helpful to plot them on the same range of parameter values. The function `plot_posterior()` currently plots the labels for the HPD boundaries centered on their values, which then may overlap in the plot.

Default behavior of `plot_posterior()`. xlimits of the axes are set automatically:
![bild](https://cloud.githubusercontent.com/assets/7450204/25514362/d1b0b3f6-2bdc-11e7-8436-0e6aa57a99ec.png)

Setting same xlimits for both posteriors:
![bild](https://cloud.githubusercontent.com/assets/7450204/25514342/9a6eca40-2bdc-11e7-871f-c7018f2adf6a.png)

The labels of the boundaries could instead be plotted either

1.  as one string (interval) which is centered on the mean ?
Default behavior of `plot_posterior()`
![bild](https://cloud.githubusercontent.com/assets/7450204/25782035/aa1f218e-3342-11e7-8d16-5e79e0b6c029.png)
Setting same range on x-axis
![bild](https://cloud.githubusercontent.com/assets/7450204/25782054/04eac032-3343-11e7-86cb-6638b85c31cc.png)

2.  or right and left justified on the values ?
Default behavior of `plot_posterior()`
![bild](https://cloud.githubusercontent.com/assets/7450204/25782245/3610a952-3347-11e7-8719-6f53d5b5b8e1.png)
Setting same range on x-axis
![bild](https://cloud.githubusercontent.com/assets/7450204/25782392/92fa0dea-334a-11e7-9a4a-7495ba72bc25.png)

**Comment by twiecki** [comment]
@JWarmenhoven hm, that's tricky, we should have a minimum distance here I think.

**Comment by JWarmenhoven** [comment]
@twiecki I added examples of alternatives 1 and 2. To me alternative 2 looks most appealing.
I am not sure how to enforce a minimum (absolute?) distance. Sounds tricky with scaling of the plot elements.

**Comment by junpenglao** [comment]
alternatives 1 looks nice IMO. Could you please also plot the alternative 1 under Default? Just to see how it looks like.

**Comment by twiecki** [comment]
I like 2 as well. Your examples do not show it, but it would suggest that for a wide x-axis, the values would not be far apart on top of the quantiles, but centered in the distribution, correct? Not sure why the x-axis is smaller on the top left plot in your updated version.

**Comment by JWarmenhoven** [comment]
Additional plots added to initial comment. 
@twiecki  In the first alternative the HPD interval labels are always plotted centered, potentially far away from the actual values on the x-axis.

```python

# Alternative 1
        text_props = dict(size=16, horizontalalignment='center')
        ax.text((hpd_intervals[0] + hpd_intervals[1]) / 2, plot_height * 0.07,
                '[{}, {}]'.format(hpd_intervals[0].round(round_to),
                                  hpd_intervals[1].round(round_to)), **text_props)
# Alternative 2
        text_propsr = dict(size=16, horizontalalignment='right')
        text_propsl = dict(size=16, horizontalalignment='left')
        ax.text(hpd_intervals[0], plot_height * 0.07,
                hpd_intervals[0].round(round_to), **text_propsr)
        ax.text(hpd_intervals[1], plot_height * 0.07,
                hpd_intervals[1].round(round_to), **text_propsl)
```

**Comment by twiecki** [comment]
Right, 2 looks like the way to go.
