### ISSUE TITLE
Inconsistent api in ADVI and OPVI

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2102]
This is a small thing, but `opvi.Approximation.sample` and `advi.sample_vp` use the keyword argument `hide_transformed`, while `stats.summary`, `stats.df_summary`, and a few of the plotting functions use the keyword argument `include_transformed`.  We should standardize on just one.

I have a preference for `include_transformed`, since it avoids double negatives (which are awkward in English).

**Comment by fonnesbeck** [comment]
That's a good point. I originally used `hide_transformed` because they are there "by default" (since the model creates them automatically), so the flag is to change the default behavior. However, the users don't care about this distinction, so I am fine with changing it.
