### ISSUE TITLE
Add random method kwarg to DensityDist

### ISSUE THREAD

**Issue by maxliving** [pymc-devs/pymc#2106]
MWE:
```
y = np.random.randn(100)
with pm.Model() as model:
    def gumbel_logp(value):
        scaled = (value - loc) / scale
        logp = -scaled - T.exp(-scaled) - T.log(scale)
        return logp
    
    loc = pm.Normal('loc')
    scale = pm.Uniform('scale', 1., 10.)
    likelihood = pm.DensityDist('gumbel', gumbel_logp, observed=y)
    step = pm.Metropolis()
    trace = pm.sample(5000, step, progressbar=True)

ppc = pm.sample_ppc(trace, samples=500, model=model, size=100)
```

This raises the following error:
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-107-63b8e6c0aae1> in <module>()
----> 1 ppc = pm.sample_ppc(trace, samples=500, model=model, size=100)

/home/ubuntu/venv/local/lib/python2.7/site-packages/pymc3/sampling.pyc in sample_ppc(trace, samples, model, vars, size, random_seed, progressbar)
    388         param = trace[idx]
    389         for var in vars:
--> 390             ppc[var.name].append(var.distribution.random(point=param,
    391                                                          size=size))
    392 

AttributeError: 'DensityDist' object has no attribute 'random'```

What is the recommended way to add the random attribute for custom DensityDists? Is this even possible?

**Comment by twiecki** [comment]
I think in this case you have to inherit from `pm.Continuous` and build your own distribution class and define `random`. We should add `random` to `pm.DensityDist`, however.

**Comment by maxliving** [comment]
@twiecki  Thanks for the response! I'm new to pymc3. Based on a quick glance at `pymc3.distributions.continuous` it seems like adding Gumbel should be relatively straightforward so I might take a swing at that and send a PR. In the meantime though, I don't understand how I could pass in a custom `random` function. Is that possible without a code change?

**Comment by fonnesbeck** [comment]
I can do a PR to add `random` to `DensityDist`. In the meantime, if you implement your distribution as a subclass of `Continuous`, you can add a `random` method (in addition to the `logp`. See any continuous distribution in PyMC3 for a template for doing this.

**Comment by maxliving** [comment]
To be able to create a `random` method from outside of the PyMC3 package, it would be useful to have the `generate_samples` method exposed. I think it just needs to be included in the list at the top of `distribution.py` (line 12): ```__all__ = ['DensityDist', 'Distribution', 'Continuous', 'Bound',
           'Discrete', 'NoDistribution', 'TensorType', 'draw_values', 'generate_samples']```

**Comment by ColCarroll** [comment]
`__all__` only effects *-imports (`from pymc3 import *`).  `pymc3/distributions/__init__.py` actually imports `generate_samples` specifically (most `__init__` files here use *-imports, so we might want to change that), so you can use

```
import pymc3 as pm
pm.distributions.generate_samples(...)
```

**Comment by maxliving** [comment]
Ah OK, my mistake. Thanks!

**Comment by Vaibhavdixit02** [comment]
Hey!
Is this issue resolved or is someone already working on it? If not I would be interested in doing so if someone could guide me on how to proceed. 
Thanks!

**Comment by twiecki** [comment]
@Vaibhavdixit02 Thanks for your interest, you can go ahead, no one is working on it.

**Comment by twiecki** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by Vaibhavdixit02** [comment]
@twiecki I am familiar with Github, what I meant was how to go about solving this issue, an outline of sorts. What I understand is to add a `kwarg` for `random` but I am not clear on how it should be handled, will it be a flag variable and we use an existing `random` method of the passed distribution or do we want the user to pass a defined `random` function for their distribution? What if there isn't a defined `random` function for it though?

**Comment by twiecki** [comment]
@Vaibhavdixit02 I think that's right, the syntax could be `DensityDist('', logp, random=func)`. Then in DensityDist you add a method `random()` that checks if a `random` was passed in and use if it is or raise an Exception if not informing of the ability to define one.
