### ISSUE TITLE
[BUG] order of cov in ADVI init is incorrect

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2108]
While updating a notebook of mine, I found that two mixed model used to ran quite fast with good trace now becomes quite slow (10x slower) and the estimation is off (see the trace). Since the advi is one of the main change (I ran the same notebook around 45 days ago), it might be the main reason.
I put together a notebook [gist](https://gist.github.com/junpenglao/272909957daa3a26fb7e5a1d9dcdff66). I am not sure if this is a common issue - but it would be good if @ferrine you can have a closer look at this.

I dont think the estimation from the old ADVI was very accurate (in fact looking at the trace they are not),  the problem is then the `cov` from the ADVI. It seems to be a bug that the order of the cov is different than before, but we are pluging it into `pm.NUTS` the same way.

**Comment by twiecki** [comment]
I have observed the same.

**Comment by twiecki** [comment]
@junpenglao you have found the order to be different? that would definitely cause this.

**Comment by junpenglao** [comment]
yes, you can see the gist

**Comment by ferrine** [comment]
Thanks for pointing this. I'll try to resolve it

**Comment by junpenglao** [comment]
@ferrine did you find a solution yet? otherwise, I can PR as well.

**Comment by junpenglao** [comment]
The following works, but it's bulky:

```python
    start = approx.sample(draws=njobs)
    cov_ = approx.cov.eval()
    v1 = model.bijection.map(start[0])
    v2 = approx.gbij.map(start[0])
    as1 = np.argsort(v1)
    as1_ = np.argsort(as1)
    as2 = np.argsort(v2)
    P = [as2[as1_]]
    cov = np.take(cov_,P, axis=0).squeeze()
    cov = np.take(cov, P, axis=1).squeeze()
    
    if njobs == 1:
        start = start[0]
```

**Comment by ferrine** [comment]
What was wrong with order? PR would be great

**Comment by junpenglao** [comment]
@twiecki can you check on your notebook to see if things improve?

**Comment by twiecki** [comment]
@junpenglao Yep, that fixes the issue.
