### ISSUE TITLE
OPVI does not seem to work in float32

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2115]
Hello. I'm using a Poisson regression in this way:

    X = X.astype('float32')
    y = y.astype('float32')

    with pm.Model() as pooled_model:

        b0 = pm.Normal('intercept', mu=5, sd=0.5)

        mu = tt.exp(b0 )  #
        nes = pm.Poisson('nes', mu=mu, observed=y)

        pooled_trace = pm.sample(niters, njobs=njobs, tune=5000)

and I get

    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:62: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.switch(tt.eq(x, 0), -np.inf, m * tt.log(x))
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:62: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.switch(tt.eq(x, 0), -np.inf, m * tt.log(x))
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:66: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return gammaln(n + 1)
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/discrete.py:262: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      logpow(mu, value) - factln(value) - mu,
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/discrete.py:262: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      logpow(mu, value) - factln(value) - mu,
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:43: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.switch(alltrue(conditions), logp, -np.inf)
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/discrete.py:266: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      0, log_prob)

with this theano config

    [global]
    floatX = float32
    device = gpu
    optimizer = fast_run
    warn_float64 = warn
    [nvcc]
    fastmath = True

I don't understand why. Can you help me?

**Comment by twiecki** [comment]
@denadai2 Can you try https://github.com/pymc-devs/pymc3/pull/2116?

**Comment by denadai2** [comment]
@twiecki done.

    /home/nadai/.local/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:158: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return c - tt.log(tt.abs_(std)) - (x - mean) ** 2 / (2 * std ** 2)
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/variational/approximations.py:84: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      logq = tt.sum(log_normal(z, mu, rho=rho))
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/variational/opvi.py:923: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.log_q_W_global(z) + self.log_q_W_local(z)
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/variational/opvi.py:926: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.logq(z) / self.normalizing_constant
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/variational/operators.py:21: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.logq_norm(z) - self.logp_norm(z)
    /home/nadai/.local/lib/python3.4/site-packages/theano/compile/pfunc.py:96: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      [clone_d[i] for i in owner.inputs], strict=rebuild_strict)
    /home/nadai/.local/lib/python3.4/site-packages/pymc3/variational/opvi.py:277: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.op.T(a)
    /home/nadai/.local/lib/python3.4/site-packages/theano/gradient.py:1342: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return x.ones_like(dtype=dtype)
    /home/nadai/.local/lib/python3.4/site-packages/theano/gradient.py:1108: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      new_output_grads)
    /home/nadai/.local/lib/python3.4/site-packages/theano/compile/function_module.py:177: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      update_mapping=update_mapping)
    /home/nadai/.local/lib/python3.4/site-packages/theano/compile/function_module.py:1474: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      optimizer_profile = optimizer(fgraph)


and then it continues to raise warnings like the last one

**Comment by twiecki** [comment]
OK, that's progress. Seems like OPVI is not float32 compat yet. CC @ferrine.

**Comment by denadai2** [comment]
I also tried to do:

    pooled_trace = pm.sample(niters, njobs=njobs, tune=5000, init='NUTS')

and I have that the GPU (Nvidia K40) goes at 10.57it/s, while CPU goes at 1860.80it/s. Normal? :D

**Comment by twiecki** [comment]
It only makes sense to set njobs=1, unless you have multiple GPUs. I think the model you posted above would be hard to speed up with the GPU. Things like dot-products are good targets.

**Comment by denadai2** [comment]
@twiecki I don't agree with closing this, since there is still the problem ("Seems like OPVI is not float32 compat yet. CC @ferrine.")

**Comment by twiecki** [comment]
Agreed, it was auto-closed.

**Comment by ferrine** [comment]
I've tested several notebooks on GPU and it worked fine. I use pm.floatX a lot there.
I see b0 in your model can get float64 type because of `sd=.5`

**Comment by denadai2** [comment]
mhh thanks, but shouldn't it be casted in general, for pymc3?

**Comment by twiecki** [comment]
@denadai2 Yes, it should be auto-casted. Your model spec looks fine to me and I was able to initialize without problems.

**Comment by twiecki** [comment]
@ferrine Did you set `warn_float64 = warn` otherwise it would run just fine (just not on the GPU).

**Comment by ferrine** [comment]
Hmm. What happens when such float64 variable is created? It is not executed on gpu?

**Comment by denadai2** [comment]
@ferrine as far as I know it does not compute in a GPU efficiently. If you set floatX = float32 it should stay float32

**Comment by twiecki** [comment]
Correct, it would just use the CPU silently (or the GPU only for small parts which is inefficient).

**Comment by ferrine** [comment]
@denadai2 what's the status of this issue? Recently I moved to `strict_float32` tests that ensure OPVI code doesn't generate float64

**Comment by twiecki** [comment]
Seems like this should work given the tests pass with strict_float32.
