### ISSUE TITLE
Comprehensive example needed for DataSampler

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2128]
The `DataSampler` class looks very useful, but there is not currently a comprehensive example to guide users, particularly when there are predictor variables in addition to response variables in the dataset.

**Comment by twiecki** [comment]
I think @ferrine wrote that.

**Comment by ferrine** [comment]
Example exist in one of updated notebooks. I'll rewrite the `.fit` api and then update them again. I'm still in doubts about adding history to Approximation. But @twiecki's arguments seem very reasonable

**Comment by pwl** [comment]
It could be useful to extend the current implementation to a multi-dimensional data sampler in accordance to the `total_size` interface discussed in #2125.  I am still unsure if an n-dimensional data set is a proper use case, in principle one can always recast it into a 1d problem.

**Comment by fonnesbeck** [comment]
I did a grep for `DataSampler` in the current set of notebooks, but nothing turned up. Is the notebook in a PR?

**Comment by junpenglao** [comment]
I think this is deprecated, close for now.
