### ISSUE TITLE
Improve doc structure

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2132]
Two projects that might be generally useful:

- [x] Add sphinx gallery (https://sphinx-gallery.readthedocs.io/en/latest/) to the docs 
- [ ] Versioned docs (see, for example, http://elasticsearch-py.readthedocs.io/en/master/), which I think was brought up in #2126.

**Comment by souravsingh** [comment]
@ColCarroll We have to use IPython notebooks for sphinx gallery, right?

**Comment by owlas** [comment]
@ColCarroll the documentation versioning you referred to is provided automatically by readthedocs. Have you considered using readthedocs for hosting rather than gh-pages?

**Comment by ColCarroll** [comment]
didn't realize that, thank you!  I guess I should have... read the docs.

There is discussion elsewhere of separating the docs ("how does pymc3 work?") from more didactic text ("how does bayesian inference work?"), and this might be a good way of making that a clean split.  Especially since we just launched https://discourse.pymc.io/, it might make sense to turn gh-pages into a redirect to readthedocs, and host case studies and more academic examples on pymc.io...

**Comment by junpenglao** [comment]
May I suggest we move this discussion to https://discourse.pymc.io/ ;-)

**Comment by owlas** [comment]
@junpenglao [discourse.pymc.io/t/restructure-docs/76/1](https://discourse.pymc.io/t/restructure-docs/76/1)

**Comment by fonnesbeck** [comment]
This should probably still remain open as an issue.

**Comment by owlas** [comment]
I forked the repo and added the requirements file for readthedocs.org (RTD).

You can take a look here: [http://pymc3.readthedocs.io/en/rtd-docs/](http://pymc3.readthedocs.io/en/rtd-docs/)

Currently the pdflatex build is failing with many errors. Were you able to build the pdf offline or was this already broken?

The HTML version looks good though and now versioning info can now be seen on the left-hand bar (though only the current branch is available).

**Comment by owlas** [comment]
I should add that versions are added automatically from the release tags on the GH repo. In the admin settings on RTD you can specify the versions to make public and private.

RTD also adds a webhook to rebuild the docs on a GH push

**Comment by junpenglao** [comment]
Wow, this looks really good! Thanks a lot @owlas !
I don't think we had ever tried to build the pdf.

**Comment by owlas** [comment]
Ok good. We could open a new issue for the pdf build, I think they look great and are nice to read offline.
I should add that the main downside of RTD is the small ad on the left panel. They're usually tasteful as far as advertising goes.

If I open the PR, a maintainer needs create an RTD account (linked to GH) and add the project. I'll remove my version so you have the pymc3 url.

The only settings you'll need to change are:
 - Versioning -> Select the versions you'd like to have build

The versions are generated from tags and additionally you have:
 - Latest -> the most recent commit on the master branch
 - Stable -> the most recent tag that follows PEP440 versioning semantics

**Comment by owlas** [comment]
I've just realised that, since the requirements file is needed to build nbsphinx docs, then the old versions won't actually build. Are we able to hot fix previous releases or are they on the master branch? I didn't see any active release branches.

**Comment by ColCarroll** [comment]
Wow, that looks great!

We have not been using release branches -- I don't think anyone is opposed,
and this seems like a good reason to be a little more disciplined.

**Comment by owlas** [comment]
@ColCarroll are you suggesting that you'll go back and create them?

I'm not sure how you'd prefer to work but you could go back to the `3.0-final` commit, create a new branch (e.g. `3.0.x`) then create a new commit on that branch with the RTD config and tag it `3.0.1`.

This would then show up in the RTD versioning with the `3.0` docs. What do you think? 

The ipython project works with [these branch names](https://github.com/ipython/ipython/branches) for example.

**Comment by ColCarroll** [comment]
That seems wise.  Then also make sure the (exciting!) 3.1 release that is
imminent gets a tag, and we can start versioning for major releases there.

**Comment by owlas** [comment]
Excellent! I'll open a PR on master with the config. This will have RTD working from now and going forward.

After that we can address the previous 3.0 branch

**Comment by twiecki** [comment]
I gave versioned docs a try but it's a huge hassle. I suggest we drop it.
