### ISSUE TITLE
issues with getting_started doc: toc links not correct

### ISSUE THREAD

**Issue by fbnrst** [pymc-devs/pymc#2133]
When using the links in the table of contents on http://pymc-devs.github.io/pymc3/notebooks/getting_started.html, I realized that the link with the anchor `Model-Specification` (http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Model-Specification) is used twice: for `Model-Specification` under `A Motivating Example: Linear Regression` and for `Model-Specification` under `Case study 1: Stochastic volatility`. Hence, if you click on `Model-Specification` under `Case study 1: Stochastic volatility` you end up in the `A Motivating Example: Linear Regression` section. 

Would defining destinations as in `pymc3/docs/source/notebooks/getting_started.ipynb` as described on https://sebastianraschka.com/Articles/2014_ipython_internal_links.html solve this? Then, I could try a PR.

**Comment by twiecki** [comment]
@fabianrost84 Thanks for the report. A PR would be much appreciated.

**Comment by fbnrst** [comment]
@twiecki The problem is that I do not know, whether destinations would "survive" that the notebook is rendered as documentation. And I do not know how to test this.

**Comment by twiecki** [comment]
In the `docs/source` directory, call `make html`, that will create html files in the `_build/html` dir where you can test them locally.

**Comment by fbnrst** [comment]
Thanks @twiecki ! However, thinking about it again, this is rather an issue of how the documentation is created: The automatic creation of the table of contents should take care of subsections with identical names and should make sure that unique links are created. So instead of doing a workaround for this minor issue here, I would prefer to report the issue upstream. But I do not know, who takes care of creating the table of contents. Is it already `jupyter notebook` or afterwards, during `make html`?

**Comment by twiecki** [comment]
I think sphinx-nb is doing that, but I'm not quite sure.
