### ISSUE TITLE
issues with getting_started doc: Latex rendered wrongly

### ISSUE THREAD

**Issue by fbnrst** [pymc-devs/pymc#2134]
- line 784 in `pymc3/docs/source/notebooks/getting_started.ipynb`:
  - `$ \\nu $ and $\\sigma$` renders as "$ :raw-latex:`\nu `$ and :math:`sigma`" on http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Case-study-1:-Stochastic-volatility

- line 1013 in `pymc3/docs/source/notebooks/getting_started.ipynb`:
  - `the parameters are defined as follows:` is not rendered correctly on http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Case-study-2:-Coal-mining-disasters

Both things look good in the notebook itself (http://nbviewer.jupyter.org/github/pymc-devs/pymc3/blob/master/docs/source/notebooks/getting_started.ipynb).

**Comment by twiecki** [comment]
Should be fixed, thanks.
