### ISSUE TITLE
Strange problem with _log

### ISSUE THREAD

**Issue by kpfoley** [pymc-devs/pymc#2138]
I am trying to run the example code for AEVB for LDA from the docs. I'm new to PyMC3 and I'm not sure if this is a bug or something that I'm doing wrong.

Here's the particular line of code that's causing the problem:

```
with pm.Model() as model:
    theta = Dirichlet('theta', a=(1.0 / n_topics) * np.ones((minibatch_size, n_topics)),
                      shape=(minibatch_size, n_topics), transform=t_stick_breaking(1e-9))
```

This runs fine on my OS X laptop (CPU only) but returns an error on an ubuntu server (with GPU). Both are running PyMC3 3.0.

Here's the error I get:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/pymc3/distributions/distribution.py", line 31, in __new__
    return model.Var(name, dist, data)
  File "/home/kfoley/venv/pymc3/lib/python3.5/site-packages/pymc3/model.py", line 285, in Var
    pm._log.debug('Applied {transform}-transform to {name}'
AttributeError: module 'pymc3' has no attribute '_log'
```

The module does include a '_log' attribute on both installations (the server and the laptop).

On the server:
```
import pymc3 as pm
pm._log
<logging.Logger object at 0x7f4a6f5d1550>
```

On the laptop:
```
import pymc3 as pm
pm._log
<Logger pymc3 (INFO)>
```
**Update:**  I don't get this error message if I disable the GPU drivers on the server.

**Comment by ColCarroll** [comment]
the logging module is kind of strange, but as a wild guess, do you have a file named `pymc3` on the server?

**Comment by kpfoley** [comment]
I don't. I just re-ran without the GPU driver disabled on the server and it ran with no problem. Running with GPU, however, I get an error.

**Comment by ferrine** [comment]
So strange, what about GPU here, it did not work for me, I ran into overflow errors

**Comment by ColCarroll** [comment]
This sounds very strange!

lt'll be hard to help without a reproducible example -- it sounds like somehow the import path is getting messed up.  I'd try `print`ing

1. `sys.path`, 
2. `locals()`,
3. `dir(pm)`

 in a few places in `/home/kfoley/venv/pymc3/lib/python3.5/site-packages/pymc3/`, to confirm that `site_packages/` is in the path ahead of anything that might also have a thing called `pymc3` in the namespace, that `pymc3 as pm` has been imported, and that `_log` is in the attributes for `pm`.

**Comment by twiecki** [comment]
Seems related to https://github.com/pymc-devs/pymc3/issues/1613.

**Comment by kpfoley** [comment]
Fortunately I am no longer having this issue after upgrading to libgpuarray / pygpu and changing the GPU accordingly in my .theanorc file. Unfortunately I did this before reading the suggestions above. Thanks for your help, and closing this issue since I can no longer reproduce it (although the connection to the GPU setting is still a puzzle).
