### ISSUE TITLE
Remove RNG initialization from theanof.

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#2144]
Most of the time it takes to import pymc is spend in `pymc3.theanof` initializing something related to the theano rng: https://github.com/pymc-devs/pymc3/blob/master/pymc3/theanof.py#L374
On my machine it spends ~4 of a total of 5s there. Seems a bit excessive.
@ferrine That was introduced in #1694. Any idea why this would take so long?

**Comment by ferrine** [comment]
That's for sure [this](https://github.com/pymc-devs/pymc3/blob/master/pymc3/theanof.py#L374) line. Rng is compiled. I added this code as I got a strange error (raise on no test value) when using rng later in code.

**Comment by ferrine** [comment]
after #2103 this step can be removed
