### ISSUE TITLE
Simple minibatch ADVI model raises FloatingPointError

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2155]
I've got a pretty straightforward model that uses mini-batch with ADVI (since it is a GP). It fails at the first iteration irrespective of the parameters passed to it. I've confirmed that the values for pi are initialized to 0.5, so the Bernoulli should never return a NaN.

```python
lag_batch = generator(create_minibatch(lag.reshape(-1,1)))
confirmed_batch = generator(create_minibatch(confirmed))

with Model() as lag_model:
    
    ρ = HalfCauchy('ρ', 1)
    η = HalfCauchy('η', 1)
    
    K = η * cov.Matern32(1, ρ)
    
    y = MvNormal('y', tt.zeros(batch_size), K(lag_batch), shape=batch_size)
    
    π = invlogit(y)

    confirmation = Bernoulli('confirmation', π, observed=confirmed_batch)
```

This occurs irrespective of which method is used with ADVI (including SVGD).

Running the master branch on macOS 10.12 and Python 3.6.

**Comment by fonnesbeck** [comment]
It turns out that adding a small positive offset to `K` fixes the problem:

    K = η * cov.Matern52(1, ρ) + 1e-6

**Comment by ferrine** [comment]
Could you please try to set debug mode for step function via `fn_kwargs={'mode':mode}`?

**Comment by fonnesbeck** [comment]
I wonder if we shouldn't just add a small offset automatically if this happens?

**Comment by ferrine** [comment]
How can we detect such problems?
