### ISSUE TITLE
Poor inference from GP with Bernoulli likelihood

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2159]
Running a simple classification GP with a Bernoulli likelihood:

```python
with Model() as lag_model:
    
    ρ = Gamma('ρ', 1, 1)
    η = Gamma('η', 1, 1)
    
    K = η * cov.ExpQuad(1, ρ) + 1e-6
    
    y = Normal('y', tt.zeros(len(lag)), K(lag), shape=len(lag))
    
    π = invlogit(y)

    confirmation = Bernoulli('confirmation', π, observed=confirmed)
```

Results in estimates always around p=0.5:

![](http://d.pr/i/jbeep+)

Even when all of the output data (confirmed) are set to ones or zeros, the estimate is the same.

**Comment by junpenglao** [comment]
Shouldn't y be a `MvNormal`?

**Comment by bwengals** [comment]
Could you post your full code?  Not sure what the lag variable is.  Here's [an example with a poisson likelihood](https://gist.github.com/bwengals/c3396c2d5e3127ec4a9969fd69ec5a3f) using some data from @junpenglao.  It uses a reparameterization trick from gpflow to get nuts to sample efficiently.

**Comment by fonnesbeck** [comment]
Yes, @junpenglao got it. Stupid oversight by me. Though, it is worrying that the result turns out as it does with `Normal` -- you would think they would be less correlated. 

I wonder if we should throw an exception when a covariance matrix is used with `Normal`. It should accept a vector of sigmas only.

**Comment by fonnesbeck** [comment]
Running with a proper `MvNormal` results in the `FloatingPointError: NaN occurred in optimization.` error. 

Will close this, as the original error is invalid.

**Comment by fonnesbeck** [comment]
Actually, I get the same behavior with a multivariate normal, so I am reopening. [Here is the full model](https://github.com/fonnesbeck/mongolia_measles/blob/master/notebooks/Confirmation%20Rates%20(GP).ipynb) if anyone wants to take a look.

**Comment by fonnesbeck** [comment]
The reparameterization does not fix the issue, unfortunately. This is the minibatched version.

```python
with Model() as lag_model:
    
    ρ = Gamma('ρ', 1, 1)
    η = HalfCauchy('η', 1)
    σ = HalfCauchy('σ', 1)
    
    K = η * cov.ExpQuad(1, ρ)
    L = tt.slinalg.cholesky(K(lag_batch) + tt.eye(batch_size)*σ)
    v = Normal("v", 0, sd=1, shape=(batch_size, 1))
    
    π = invlogit(tt.dot(L, v))

    confirmation = Bernoulli('confirmation', p=π, observed=confirmed_batch)
```

![unknown-4](https://cloud.githubusercontent.com/assets/81476/25857386/948a4da0-349e-11e7-8f6e-d823833b5729.png)

There is a fair bit of data in this example to suggest the estimates of p should be above 0.6. Here is a reasonable result using a `GaussianRandomWalk`, to get an idea of what an realistic estimate might look like:

![unknown-5](https://cloud.githubusercontent.com/assets/81476/25857664/65c55c66-349f-11e7-90ae-5b0dee7bc5bf.png)

**Comment by junpenglao** [comment]
It might be something to do with the minibatch. How is it in NUTS?

**Comment by fonnesbeck** [comment]
Its way too much data to use the whole set, but I will try with a subset.

**Comment by junpenglao** [comment]
The last time I try using minibatch, it overestimates the lenght scale and under estimated the variance:
without minibatch:
![image](https://cloud.githubusercontent.com/assets/12952641/25857798/692a0cfe-34da-11e7-9f59-a767a52e56a0.png)
with minibatch:
![image](https://cloud.githubusercontent.com/assets/12952641/25857814/7168f222-34da-11e7-919a-42ec291d0af7.png)

**Comment by fonnesbeck** [comment]
BTW, things seem to work fine [with a Poisson likelihood](https://gist.github.com/fonnesbeck/64fb5ce95a93c29118661ebcba56e021) for me as well, so it seems to be something related to the Bernoulli.

**Comment by aseyboldt** [comment]
Just a hunch, but could you try `tt.nnet.sigmoid` instead of `invlogit`? I had some numerics trouble with invlogit before, and theano does a couple of numerical stabilisation with sigmoid.

**Comment by fonnesbeck** [comment]
@aseyboldt that's an excellent guess, but it did not change the result here. Going to try a short NUTS run and see if it is a minibatch problem, as @junpenglao suggests.

**Comment by fonnesbeck** [comment]
(sampling with NUTS with only 500 observation runs at a whopping 74.95s/it)

**Comment by fonnesbeck** [comment]
NUTS fares even worse:

```python
with lag_model:
    lag_trace = sample(500, init=None, tune=250, njobs=2)
```

![unknown-7](https://cloud.githubusercontent.com/assets/81476/25869047/8877182e-34c4-11e7-9055-ce278ed35b5d.png)

I'm stumped on this one.

**Comment by bwengals** [comment]
That's weird, especially since poisson works.  Maybe the new elliptical slice sampler in pymc3 is worth a try here...?

**Comment by fonnesbeck** [comment]
Perhaps, though the problem appears to be independent of the fitting method (NUTS and VI are pretty different). Its worth a try though.

**Comment by aseyboldt** [comment]
@fonnesbeck Is the dataset public? I'd love to have a look if it is (after all, I spend a year in Mongolia :-). I really hope it's not another issue with `MvNormal`...

**Comment by aseyboldt** [comment]
Is it possible that this is just a plotting issue? The prediction is a draw from an unrelated gp with the same kernel.
This works for me:
```python
confirmed = np.r_[np.ones(20), np.zeros(20)]
lag = np.arange(40)[:, None]

with Model() as lag_model:
    ρ = Gamma('ρ', 1, 1)
    η = Gamma('η', 1, 1)
    
    K = η * cov.ExpQuad(1, ρ)
    Σ = K(lag) + 1e-5 * tt.eye(len(lag))
    L = tt.slinalg.cholesky(Σ)
    y = Normal('y', mu=0, sd=1, shape=len(lag))
    π = tt.nnet.sigmoid(tt.dot(L, y))
    confirmation = Bernoulli('confirmation', π, observed=confirmed)

with lag_model:
    trace = pm.fit(20000).sample(100)
    ppc = pm.sample_ppc(trace)

plt.plot(ppc['confirmation'].mean(axis=0))
```

![image](https://cloud.githubusercontent.com/assets/1882397/26024515/cee6d374-37d2-11e7-95d2-67b0d20c116f.png)

Also, is there a reason that there is no intercept?

**Comment by fonnesbeck** [comment]
Yes, I think its just an issue with my posterior predictive sampling. I'm able to get something more reasonable here:

![unknown](https://cloud.githubusercontent.com/assets/81476/26025512/16116a4e-37af-11e7-8840-cf772999d16b.png)

**Comment by fonnesbeck** [comment]
@aseyboldt the dataset is a measles outbreak dataset from the CDC. Parts of it are public, but not all.
