### ISSUE TITLE
Simple regression model failure with ADVI

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2162]
The failure of ADVI to get anywhere close to a good answer for a very simple regression problem alarmed me somewhat. Here is the data:

```python
x = array([ 1.17,  2.97,  3.26,  4.69,  5.83,  6.  ,  6.41])
y =array([ 78.93,  58.2 ,  67.47,  37.47,  45.65,  32.92,  29.97])
plt.plot(x, y, 'ro')
```
![unknown-8](https://cloud.githubusercontent.com/assets/81476/25869969/f844ac18-34c7-11e7-8cf8-cf188255811f.png)

As you can see, a pretty obvious negative slope. 

Here's the model:

```python
with Model() as drugs_model:
    
    intercept = Normal('intercept', 0, sd=100)
    slope = Normal('slope', 0, sd=100)
    σ = HalfCauchy('σ', 5)
    μ = intercept + slope*x
    score = Normal('score', μ, sd=σ, observed=y)

    drugs_sample = fit(n=50000, method='advi').sample(1000)
```

```
Average Loss = 41.678: 100%|██████████| 50000/50000 [00:03<00:00, 14028.93it/s]
Finished [100%]: Average Loss = 41.662
```
Runs without error.

However, here is the resulting estimate of the slope:

![unknown-9](https://cloud.githubusercontent.com/assets/81476/25870044/4891c624-34c8-11e7-9f78-09bcf18e82e0.png)

ADVI, full-rank ADVI and SVGD all get similar answers.

This isn't just an underestimate of the variance, but an estimate that is completely in the wrong direction! Fitting this with NUTS gets the right answer -- a mean slope of about -9. This is a pretty scary failure, since there is absolutely no indication of a poor optimization run.

**Comment by aseyboldt** [comment]
It looks fine for me if I increase the number of iterations in fit by a factor of 10. Not sure why it would take so long to converge, this really doesn't look to complicated.

**Comment by aseyboldt** [comment]
@ferrine Is there a way to get at the values during optimization? Something like a trace during the optimization would be nice to investigate what the optimizer is doing.
And isn't there a learning rate anymore?

**Comment by fonnesbeck** [comment]
Wow, so it does. It seemed like the average loss was stabilizing, but apparently not. How do we get the ELBOs from an `Approximation` object under the new API?

I wonder if the same phenomenon is related to #2159

**Comment by twiecki** [comment]
Well, we either wait for the new results object, or we have fit() return two things, or tack it onto Approximate. I would vote for the third option as an interim solution. @ferrine?

**Comment by fonnesbeck** [comment]
I think it makes sense to have it as an attribute of `Approximation`. There could even be a `plot` method to plot the ELBOs (since that is invariably what we do with them).

**Comment by twiecki** [comment]
Let's add it.

**Comment by ferrine** [comment]
I'm a bit busy till weekends. 
@twiecki Let's use interim solution.
@aseyboldt You can use callbacks to track parameters. Approximation is accessible in it

**Comment by ferrine** [comment]
That takes a lot of time because small default learning rate.
