### ISSUE TITLE
Error in class based optimizers

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#2164]
Just came in mind. Current implementation seems to be wrong(I've not tested them but it is theoretically so). Functions are treated as methods, I think we should go simpler and turn classes to function that return partial objects. Or do a bit more magic class based api with optional auto partial return. In that case we also avoid duplication in module. That's looks better to me and it will not break old api.
That will be a hotfix tomorrow. CC @twiecki

**Comment by fonnesbeck** [comment]
Is this still a thing?

**Comment by ferrine** [comment]
Fixed
