### ISSUE TITLE
Import Failure at Runtime

### ISSUE THREAD

**Issue by CarrieMY** [pymc-devs/pymc#2165]
Hi all,
When importing PyMC3, python is forced to terminate. A screenshot of this failure is showed in Fig.1. And also you may check my environment in a list below. 

Anyone has encountered this problem before? Thanks!
  

Fig.1
![image](https://cloud.githubusercontent.com/assets/18026745/25890269/7a9dc6ae-359f-11e7-96b2-53ea8608d3d8.png)

> alabaster                 0.7.10                    <pip>
algopy                    0.5.3                     <pip>
appdirs                   1.4.3                     <pip>
Babel                     2.4.0                     <pip>
bleach                    2.0.0                     <pip>
ca-certificates           2017.1.23                     1    conda-forge
colorama                  0.3.9                     <pip>
CommonMark                0.5.4                     <pip>
cycler                    0.10.0                   py35_0    conda-forge
cython                    0.25.2                   py35_0
decorator                 4.0.11                    <pip>
docutils                  0.13.1                    <pip>
entrypoints               0.2.2                     <pip>
freetype                  2.7                      vc14_1  [vc14]  conda-forge
h5py                      2.7.0                     <pip>
html5lib                  0.999999999               <pip>
icu                       58.1                     vc14_1  [vc14]  conda-forge
imagesize                 0.7.1                     <pip>
ipykernel                 4.6.1                     <pip>
ipython                   6.0.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                6.0.0                     <pip>
jedi                      0.10.2                    <pip>
Jinja2                    2.9.6                     <pip>
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.0.1                     <pip>
jupyter-console           5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
libgpuarray               0.6.4                    vc14_0  [vc14]
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libpython                 2.0                      py35_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.6                    py35_0
MarkupSafe                1.0                       <pip>
markupsafe                0.23                     py35_2
matplotlib                2.0.0               np111py35_3    conda-forge
mistune                   0.7.4                     <pip>
mkl                       2017.0.1                      0
mkl-service               1.1.2                    py35_3
msys2-conda-epoch         20160418                      1
nbconvert                 5.1.1                     <pip>
nbformat                  4.3.0                     <pip>
nbsphinx                  0.2.13                    <pip>
nose                      1.3.7                    py35_1
notebook                  5.0.0                     <pip>
numdifftools              0.9.20                    <pip>
numpy                     1.11.3                   py35_0
openssl                   1.0.2h                   vc14_3  [vc14]  conda-forge
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py35_1    conda-forge
pandocfilters             1.4.1                     <pip>
patsy                     0.4.1                    py35_0    conda-forge
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py35_1
prompt-toolkit            1.0.14                    <pip>
Pygments                  2.2.0                     <pip>
pygpu                     0.6.4                    py35_0
pymc3                     3.1rc3                    <pip>
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_2    conda-forge
python                    3.5.3                         0
python-dateutil           2.6.0                    py35_0    conda-forge
pytz                      2017.2                   py35_0    conda-forge
pyzmq                     16.0.2                    <pip>
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtconsole                 4.3.0                     <pip>
recommonmark              0.4.0                     <pip>
requests                  2.14.1                    <pip>
scipy                     0.19.0              np111py35_0
setuptools                35.0.2                    <pip>
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                     <pip>
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                    <pip>
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                     <pip>
Sphinx                    1.5.5                     <pip>
testpath                  0.3                       <pip>
theano                    0.9.0                    py35_0
tornado                   4.5.1                    py35_0    conda-forge
tqdm                      4.11.2                   py35_0    conda-forge
traitlets                 4.3.2                     <pip>
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py35_0
widgetsnbextension        2.0.0                     <pip>
win-unicode-console       0.5                       <pip>
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

**Comment by twiecki** [comment]
Can you try installing `conda install -c conda-forge/label/rc pymc3`

**Comment by CarrieMY** [comment]
Unfortunately, this unusual termination happens again after I reinstalled PyMC3 with the command recommended above. Any other idea about solving this problem?

 PyMC3 once worked on my computer and generated pretty good result. But after I uninstalled it, this happened after reinstallation.

**Comment by ColCarroll** [comment]
Can you try upgrading `pygpu` and `libgpuarray`?  It might be related to #2138

**Comment by CarrieMY** [comment]
Thanks so much @ColCarroll  and @twiecki .
After reinstallation and dependencies updated, pymc3 runs finally. So I close this issue.

BTW, another small issue encountered is that it seems pymc3 does work with pandas 0.20.1 so I rolled back to 0.19.2.

![image](https://cloud.githubusercontent.com/assets/18026745/25931699/87200d14-3640-11e7-8930-f94ac0774ed0.png)

**Comment by ColCarroll** [comment]
glad it helped!  the pandas problem is fixed on master -- see #2172 for how to install straight from github
