### ISSUE TITLE
Poisson with minibatch

### ISSUE THREAD

**Issue by pwl** [pymc-devs/pymc#2166]
I run into some trouble when running ADVI on a model with minibatches and a Poisson distribution.  See the enclosed [notebook](https://gist.github.com/pwl/5ea557c2771c95d97a009e3e99fe374c) for a minimal example. The error seems kind of similar to the one from #1939.

I'm using the master branch of pymc3 from a few days ago.

**Comment by twiecki** [comment]
Odd, seems related to the int type in Poisson. Can you try casting your data in the minibatch to int16? Also, make sure you are running post https://github.com/pymc-devs/pymc3/pull/2116.

**Comment by pwl** [comment]
I changed the batch generator to
```python
yield np.arange(n_batch).astype(np.int16)
```
and I also changed the distribution to
```python
test = pm.Poisson('test', mu=mu, observed = data, total_size = 3, dtype='int16')
```
with the same result.  I'm sure I'm running past #2116.

**Comment by pwl** [comment]
Interestingly,
```python
test = pm.DensityDist('test', pm.Poisson.dist(mu=mu).logp, observed = data, total_size = 3, dtype='int16')
```
also raises the same error as `pm.Poisson`.

EDIT: I updated the notebook to include all of the above.

**Comment by twiecki** [comment]
You can set http://deeplearning.net/software/theano/library/config.html#config.warn_float64 to 'raise' and use pdb to see what's going on.

**Comment by pwl** [comment]
@twiecki I added the corresponding log to the gist:
https://gist.github.com/pwl/5ea557c2771c95d97a009e3e99fe374c#file-float64_exception-log

**Comment by twiecki** [comment]
Oh, right, variational inference does not yet support float32.
