### ISSUE TITLE
DOCS: Todo - expand API quickstart

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2178]
Based on the excellent work of @twiecki I think we could do with some more explanation of what things like logp and the gradients mean. At least at an intuitive way. 

I often find when explaining Bayesian stats that people get stuck at that level. 

If I get time I'll have a go with this.

**Comment by twiecki** [comment]
> I often find when explaining Bayesian stats that people get stuck at that level.

This is geared at people who already know Bayesian stats, there are many resources we link to that describe that part.

**Comment by springcoil** [comment]
Hmm maybe that's fair enough. Maybe a quick 'reminder' though would help. 

(I'll close this.)

**Comment by twiecki** [comment]
Perhaps a statement at the beginning saying "If you want a more formal introduction, see..."

**Comment by ferrine** [comment]
How do I explain that one cannot easily sample only having unscaled logp?
