### ISSUE TITLE
float64 warning

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2180]
I'll look at how to fix these things, meanwhile I check the problems with GPU (and CPU) with 

    THEANO_FLAGS=device=cpu,mode=FAST_RUN,warn_float64=warn,floatX=float32

- [ ] simpletest.py

    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/math.py:40: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.log(p / (1 - p))
    Traceback (most recent call last):
      File "simpletest.py", line 16, in <module>
        z = pm.Beta('z', alpha=10, beta=5.5)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/distribution.py", line 38, in __new__
        return model.Var(name, dist, data, total_size)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/model.py", line 531, in Var
        model=self)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/model.py", line 1018, in __init__
        transformed_name, transform.apply(distribution), total_size=total_size)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/model.py", line 525, in Var
        total_size=total_size, model=self)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/model.py", line 817, in __init__
        self.logp_elemwiset = distribution.logp(self)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/transforms.py", line 74, in logp
        return (self.dist.logp(self.transform_used.backward(x)) +
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/transforms.py", line 102, in backward
        return invlogit(x, 0.0)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/math.py", line 36, in invlogit
        return (1 - 2 * eps) / (1 + tt.exp(-x)) + eps
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/var.py", line 41, in __neg__
        return theano.tensor.basic.neg(self)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/op.py", line 625, in __call__
        storage_map[ins] = [self._get_test_value(ins)]
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/gof/op.py", line 562, in _get_test_value
        ret = v.type.filter(v.tag.test_value)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/type.py", line 173, in filter
        raise TypeError(err_msg, data)
    TypeError: For compute_test_value, one input test value does not have the requested type.

- [ ] lasso_missing.py 

    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/math.py:40: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.log(p / (1 - p))
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/math.py:40: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.log(p / (1 - p))
    lasso_missing.py:35: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      beta[4] * age + beta[5] * mother_imp + beta[6] * early_ident)
    lasso_missing.py:35: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      beta[4] * age + beta[5] * mother_imp + beta[6] * early_ident)
    lasso_missing.py:35: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      beta[4] * age + beta[5] * mother_imp + beta[6] * early_ident)
    lasso_missing.py:35: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      beta[4] * age + beta[5] * mother_imp + beta[6] * early_ident)
    lasso_missing.py:35: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      beta[4] * age + beta[5] * mother_imp + beta[6] * early_ident)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/continuous.py:232: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return bound((-tau * (value - mu)**2 + tt.log(tau / np.pi / 2.)) / 2.,
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/continuous.py:232: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return bound((-tau * (value - mu)**2 + tt.log(tau / np.pi / 2.)) / 2.,
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/continuous.py:232: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return bound((-tau * (value - mu)**2 + tt.log(tau / np.pi / 2.)) / 2.,
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/continuous.py:232: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return bound((-tau * (value - mu)**2 + tt.log(tau / np.pi / 2.)) / 2.,
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:46: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.switch(alltrue(conditions), logp, -np.inf)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/model.py:189: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.sum(self.logp_elemwiset)

- [ ] baseball.py

    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/math.py:40: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return tt.log(p / (1 - p))
    Auto-assigning NUTS sampler...
    Initializing NUTS using ADVI...
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/distributions/dist_math.py:161: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return c - tt.log(tt.abs_(std)) - (x - mean) ** 2 / (2 * std ** 2)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/variational/approximations.py:93: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      logq = tt.sum(log_normal(z, mu, rho=rho))
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/variational/opvi.py:923: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.log_q_W_global(z) + self.log_q_W_local(z)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/variational/opvi.py:926: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.logq(z) / self.normalizing_constant
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/variational/operators.py:22: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      return self.logq_norm(z) - self.logp_norm(z)
    /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/compile/pfunc.py:96: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
      [clone_d[i] for i in owner.inputs], strict=rebuild_strict)

**Comment by ferrine** [comment]
Great, this can speed up inference.

**Comment by ferrine** [comment]
I see some common problem spots. Does casting there solve the problem?

**Comment by denadai2** [comment]
@ferrine cast would be a trick. I don't understand the reason behind some of them :/
