### ISSUE TITLE
Default `test_point` for `DiscreteUniform` outside of support for negative lower

### ISSUE THREAD

**Issue by fbnrst** [pymc-devs/pymc#2185]
If the lower bound of a `DiscreteUniform` is negative, the default test_point is outside of the support:

In:
```python
import pymc3 as pm

model1 = pm.Model()
with model1:
    a = pm.DiscreteUniform('a', lower = 0, upper = 10)
print('test_point model1: {}'.format(model1.test_point))

model2 = pm.Model()
with model2:
    b = pm.DiscreteUniform('a', lower = -10, upper = 0)
print('test_point model2: {}'.format(model2.test_point))
```

Out:
```python
test_point model1: {'a': array(5)}
test_point model2: {'a': array(5)}
```

I would expect `-5` for `model2`. Occurs with `pymc3.__version == '3.1rc3'`.

**Comment by junpenglao** [comment]
Didn't we have a similar problem of `Uniform` as well? Was that fixed? @ColCarroll

**Comment by ColCarroll** [comment]
wow!  actually just an overlooked bug here:
https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/discrete.py#L385

the `test_point` is inferred from the `mode` which looks really reasonable but should be a quick PR to switch the `-` to a `+` and add a test!

**Comment by bhargavvader** [comment]
@ColCarroll do you mean line [#L443](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/discrete.py#L443) ?

**Comment by ColCarroll** [comment]
heh -- should have linked to a specific gitrev. yep, that's the line

**Comment by bhargavvader** [comment]
#2248 is merged - this can be closed now.
