### ISSUE TITLE
MvGaussianRandomWalk and MvStudentTRandomWalk distributions raise AttributeError

### ISSUE THREAD

**Issue by phil-mcdowall** [pymc-devs/pymc#2196]
`MvGaussianRandomWalk` and `MvStudentTRandomWalk` distributions use `multivariate.get_tau_cov` which was removed in d15d9ad19021a8a3f26a86fbc6b71838ac37e7d1, resulting in an AttributeError.

**Comment by fonnesbeck** [comment]
Thanks for reporting this. I am inclined to stick with using covariance matrices here; I don't know if there is much demand for a precision matrix in time series models.
