### ISSUE TITLE
random method fails when calling creating dist without context

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#2200]
minimal example that fails on master `pm.Exponential.dist(lam=4).random()`
I think that is related to #2103 
```
with pm.Model():  # good
    pm.Exponential.dist(lam=4).random()
pm.Exponential.dist(lam=4).random()  # bad
```
CC @aseyboldt

**Comment by fonnesbeck** [comment]
Works fine here.

```python
In [3]: pm.Exponential.dist(lam=4).random()
Out[3]: array(0.10221490516974761)
```

What sort of error?

**Comment by ferrine** [comment]
My flags are `compute_test_value=off`. It breaks the behaviour

**Comment by twiecki** [comment]
Hm, that's an unfortunate corner case. #2103 is the behavior we want, but of course it would be preferable if `.dist` could be used without it.

**Comment by aseyboldt** [comment]
We could set use `theano.configparser.change_flags` (or so) to set `compute_test_value` temporarily in a function. I guess we'd need it in the `__init__`, `random` and `logp`, right?

**Comment by twiecki** [comment]
@aseyboldt Yeah, those would be too many places I think. Could be done with a decorator I guess, it would also be the most sure fire option currently.

I wonder if dependence on test_value is as hairy as for the test for something like  `pm.Exponential.dist(lam=4).random()`. We should investigate what code would need to change here.
