### ISSUE TITLE
defining a power-law random variable

### ISSUE THREAD

**Issue by mfouesneau** [pymc-devs/pymc#2202]
I am trying to define properly a random variable that follows a power-law distribution.

However, whatever I try, I obtain -inf or nan or nothing that suggest the variable works.

below is how I define my variable, any idea what's going wrong?

```python 
class PowerLaw(pm.Continuous):
    R"""
    Discrete powerlaw distribution.
    
    Parameters
    ----------
    lower : float
        Lower limit.
    upper : float
        Upper limit (upper > lower).
    slope: float
        index of the power law
    """
    def __init__(self, lower, upper, slope, *args, **kwargs):
        super(DiscretePowerLaw, self).__init__(*args, **kwargs)
        self.lower = tt.as_tensor_variable(lower)
        self.upper = tt.as_tensor_variable(upper)
        self.slope = tt.as_tensor_variable(slope)
        b = slope + 1
        if b == 0:
            self.norm = tt.log(upper / lower)
        else:
            self.norm = tt.as_tensor_variable(1. / b * (upper ** b - lower ** b))
            
    def ppf(self, x, xmin=None, xmax=None, **kwargs):
        """ Percentile point function (i.e. CDF inverse) """
        b = self.slope + 1.
        _x = np.atleast_1d(x)
        xmin = xmin or self.lower
        xmax = xmax or self.upper

        if b == 0:
            return xmin * (xmax / xmin) ** _x
        else:
            return (( xmax ** b - xmin ** b ) * _x + xmin ** b) ** (1. / b)
        
    def rvs(self, xmin=None, xmax=None, size=1, **kwargs):
        """Random samples"""
        y = np.random.uniform(0.0, 1.0, size)
        return self.ppf(y, xmin=xmin, xmax=xmax)

    def random(self, point=None, size=None, repeat=None):
        lower, upper = pm.distributions.draw_values([self.lower, self.upper], point=point)
        return pm.distributions.generate_samples(self.rvs, lower, upper, 
                                                 dist_shape=self.shape,
                                                 size=size)

    def logp(self, value):
        upper = self.upper
        lower = self.lower
        return pm.distributions.dist_math.bound(tt.log(value) * self.slope / self.norm,
                     lower <= value, value <= upper)
```

**Comment by AustinRochford** [comment]
Probably just a typo, but your class name is `PowerLaw` and you do `super(DiscretePowerLaw, self)`.

Can you post the code that is failing?

**Comment by mfouesneau** [comment]
Indeed there are few typos in the code above. also the self.norm should be subtracted not divided.

the code that fails is the following

```python
model = pm.Model()

with model:
    # prior P(n)
    Mmax = pm.Uniform("Mmax", lower=max(Dk), upper=1000)
    slope = pm.Uniform("slope", lower=-4, upper=-1)
    # likelihood: P(Sk|n)
    D_obs = ContinuousPowerLaw("D_obs", lower=Mmin, upper=Mmax, slope=slope, testval=Dk[0])
    M_obs = pm.Lognormal('M_obs', mu=D_obs, sd=0.3, observed=Dk)

    start = {"Mmax": max(Dk),   # the highest number is a reasonable starting point
                 "slope": alpha     # not far from our expectation...
            } 
```

My guess is that I don't properly use the declarations but I cannot figure what's wrong.

**Comment by AustinRochford** [comment]
Can you the full code as a notebook in a gist so I can debug more easily?

**Comment by mfouesneau** [comment]
Gist available at
https://gist.github.com/mfouesneau/43a7c70fcdd2f9b70ce502a7415dfca5

**Comment by mfouesneau** [comment]
This model still does not work. Any progress on why?

**Comment by AustinRochford** [comment]
Sorry, I poked around a bit and nothing popped out at me.  I'll take another look again soon when I get the chance.

**Comment by aseyboldt** [comment]
@mfouesneau You should use a transformation to make sure that the values end up between `lower` and `upper`. Something like this:
```python
    def __init__(self, lower, upper, slope, *args, **kwargs):
        self.lower = tt.as_tensor_variable(lower)
        self.upper = tt.as_tensor_variable(upper)
        trafo = pm.distributions.transforms.interval(self.lower, self.upper)
        super(DiscretePowerLaw, self).__init__(*args, **kwargs, transform=trafo)
        self.slope = tt.as_tensor_variable(slope)
        b = slope + 1
        if b == 0:
            self.norm = tt.log(upper / lower)
        else:
            self.norm = tt.as_tensor_variable(1. / b * (upper ** b - lower ** b))
        # Setting mode/median/mean is probably a good idea, too
        self.mode = ??
        self.mean = ??
```

**Comment by aseyboldt** [comment]
Oh, sorry. I saw the "discrete" part too late. Forget about the transformation then, that is only for continuous dists.

But setting mode etc is still a good idea. This might also be the source of your trouble, as those are used to initialize the model.

**Comment by mfouesneau** [comment]
Where is it used? The distribution is defined as 0 outside the range
already, esp. using the bound method.

Defining the mean does not change the error message. It only allows me to
avoid the test value.

**Comment by aseyboldt** [comment]
The `if b == 0` doesn't work if it is already a tensor. You can do this instead:
```
self.slope = slope = tt.as_tensor_variable(slope)
b = slope + 1
self.norm = tt.switch(b == 0, tt.log(upper / lower), (upper ** b - lower ** b) / b)

**Comment by aseyboldt** [comment]
Yes, the mode/median/mean is used if no testval is specified, and that is pretty much the only use. What error message exactly? Does `PowerLaw.dist(...).logp(value).eval()` give you reasonable answers?

**Comment by mfouesneau** [comment]
Check the gist notebook. You have the full test.

**Comment by aseyboldt** [comment]
In the notebook I think you pass an array with shape (1000,) to start in `Mi`, but the `Mi` variable is a scalar.

**Comment by mfouesneau** [comment]
So what's the right way to do so?  the error seems to be only when I fit with uncertainties not individuals.

**Comment by aseyboldt** [comment]
I don't really know what you are trying to do, but if you want a different `Mi` value for each observation you can set `shape=1000` and also adapt the testval to `np.ones(1000)`

**Comment by mfouesneau** [comment]
I have N observations, each with Normal or lognormal uncertainties. I know that their true values are following the same power-law.

The examples on how to setup the variables suggested arrays or a for loop. But in both cases I get errors.

the model is relatively simple I think:

for each Mi in observations: 
          Mi --> pnoise(Mi, Mtrue_i, noise_i)
          Mtrue_i --> Powerlaw(M, slope, limits)

with slope and limits as variables also

I am sure it's the way I code it but I cannot find how to properly do so.
I simply transposed the straight line example in the doc. (or tried to)

**Comment by mfouesneau** [comment]
updating the class to use switch does not affect the results but thanks.

Updated for:
```python
self.norm = tt.switch(tt.eq(b, 0), tt.log(upper / lower), (upper ** b - lower ** b) / b)
```

**Comment by aseyboldt** [comment]
```python
Mi = ContinuousPowerLaw("Mi", lower=Mmin, upper=Mmax, slope=slope, shape=1000)
```
And since it is continuous after all, you should also use the interval transformation I mentioned earlier.

**Comment by mfouesneau** [comment]
How does Mi defined that way uses the "noise" distribution? 

How the transformation is used? or where is that documented so I can understand how this works?

To be explicit, this is what bugs even though it seems you agree on the definition:

```python
noisy_model = pm.Model()

with noisy_model:
    Mmax = pm.Uniform("Mmax", lower=0.5 * max(Dk_noisy), upper=1000)
    slope = pm.Uniform("slope", lower=-4, upper=-1.1)
    Mi = ContinuousPowerLaw("Mi", lower=Mmin, upper=Mmax, slope=slope, shape=len(Dk))
    M_obs = pm.Lognormal('M_obs', mu=Mi, sd=0.1, observed=Dk)

    # start with mock values already
    start = { 
        "Mmax": Mmax_true,
        "slope": alpha,
        "Mi": Dk,
        "M_obs": Dk
            } 
```

**Comment by nathanielobrown** [comment]
I'm just learning PyMC3 and one of the first examples I tried was fitting to a power law. Is writing your own distribution using theano the only option? I've found some PyMC2 examples that use a `pymc.stochastic` decorator, but that is gone in PyMC3.

If this is the only option, a working example and possible inclusion in PyMC3 would be much appreciated!

**Comment by junpenglao** [comment]
@nathanielobrown No necessary, the easiest way is to define a custom loglikelihood function and use `pm.DensityDist`. You can find a simple example [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/arbitrary_stochastic.py)

BTW, just a reminder that we have https://discourse.pymc.io/ for question and discussion ;-)

**Comment by aseyboldt** [comment]
What distribution are you interested in specifically? We've got `pm.Pareto`. (Although defining an exponential and then taking the exp is probably easier on the sampler if the variable is unobserved.)

**Comment by nathanielobrown** [comment]
Thank you both. I will try your suggestions and check out the forums!

**Comment by mfouesneau** [comment]
Thanks but that does not answer my initial issue, namely, I cannot run a full model of measurements with Gaussian noise

For recollection:
https://gist.github.com/mfouesneau/43a7c70fcdd2f9b70ce502a7415dfca5
