### ISSUE TITLE
NUTS and HamiltonianMC won't begin sampling

### ISSUE THREAD

**Issue by Oedon** [pymc-devs/pymc#2204]
Hello,

This could just be an issue of my local machine not being powerful enough to do what I need it to do, though I'd figured it'd be good to check here first with the devs to see if there's a bigger issue going on.

Here is the code I'm working with:

````
def simpson(f, a, b, n):
    h = (b - a)/n
    k = 0.0
    x = a + h
    for i in range(1, n/2 + 1):
        k += 4 * f(x)
        x += 2 * h
    
    x = a + 2.0 * h
    for i in range(1, n/2):
        k += 2 * f(x)
        x += 2 * h
    return (h/3)*(f(a) + f(b) + k)

from pymc3 import *
import theano.tensor as T

with Model() as model:
    M = Uniform('M', 0.0, 3.0)
    L = Uniform('L', 0.0, 3.0)
    H = Uniform('H', 0.0, 100.0)
    
    def comovingDistance(z):
        return 1.0/(T.sqrt((M*(1.0+z)**3) + ((1.-M-L)*(1.+z)**2) + L))
    
    mean = 5.0 * T.log10((1.0 + z) * c/(H) * (simpson(comovingDistance, 0.000001, z, 100)) / (10.0 ** (-5.0)))
    
    likelihood = Normal('fit', mu = mean, sd = s, observed = y)
    
    start = {'M': 0.3, 'L': 0.7, 'H':70.0}
    trace = sample(10000, step = HamiltonianMC(), start = start)
````

(sorry in advance for my terrible variable and function definition names)
Here, `z`, `y`, and `s` are arrays of values, all of the same size. This sampling works okay with Metropolis and Slice sampling methods, but I've heard from several sources that `NUTS` and `HamiltonianMC` are more applicable to this kind of sampling (since my variables are continuous). No matter the arrays' size (I've tried both 1000 and 5), neither `NUTS` nor `HamiltonianMC` will sample at all, with both just filling up my 8 GiB RAM doing whatever they're doing before sampling, requiring me to interrupt the kernel before my entire RAM space is used up. 

I have a feeling that the issue may be coming from the complexity of my model since it involves approximating a definite integral value using a simpson integral so `NUTS` and `HamiltonianMC` are having issues doing their gradient whatever before they sample. I don't currently have the ability to try this out on a more powerful machine than my own local one, so I can't confirm if my issues are because of its performance. Any help is greatly appreciated.

I am using Python 2.7 in the Jupyter Notebook environment, here is the pip readout for pymc3:

````
$ pip show pymc3

Name: pymc3
Version: 3.0
Summary: PyMC3
Home-page: http://github.com/pymc-devs/pymc3
Author: Thomas Wiecki
Author-email: thomas.wiecki@gmail.com
License: Apache License, Version 2.0
Location: /home/ksk15c/virtualenvironment/my_new_app/lib/python2.7/site-packages
Requires: numpy, theano, nbsphinx, joblib, sphinx, tqdm, numpydoc, patsy, enum34, recommonmark, CommonMark, scipy, pandas, matplotlib
````

Attached is a .txt for `z`, `y`, and `s` (comma delimited), in case anyone would like to try this out as well (i guess).
[sndata.txt](https://github.com/pymc-devs/pymc3/files/1015415/sndata.txt)

EDIT: I actually have 6.9 GiB of total RAM available, I just wrote down what I remembered about the specs of my laptop

**Comment by twiecki** [comment]
Can you upgrade to pymc3 master? and just call `pm.sample()`

**Comment by Oedon** [comment]
Sorry for the late reply, my power decided to go out right when I was about to download the master.
So now with the latest master (3.1rc3), I actually get something (after quite a while):

````
with model:
    sample(100)

Out:
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
  0%|          | 0/200000 [00:00<?, ?it/s]
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-8-2b6581447492> in <module>()
      1 with model:
----> 2     sample(100)

/home/ksk15c/virtualenvironment/my_new_app/local/lib/python2.7/site-packages/pymc3/sampling.pyc in sample(draws, step, init, n_init, start, trace, chain, njobs, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, **kwargs)
    235         start_, step = init_nuts(init=init, njobs=njobs, n_init=n_init,
    236                                  model=model, random_seed=random_seed,
--> 237                                  progressbar=progressbar, **args)
    238         if start is None:
    239             start = start_

/home/ksk15c/virtualenvironment/my_new_app/local/lib/python2.7/site-packages/pymc3/sampling.pyc in init_nuts(init, njobs, n_init, model, random_seed, progressbar, **kwargs)
    581             n=n_init, method='advi', model=model,
    582             callbacks=[pm.callbacks.CheckParametersConvergence(tolerance=1e-2)],
--> 583             progressbar=progressbar
    584         )  # type: pm.MeanField
    585         start = approx.sample(draws=njobs)

/home/ksk15c/virtualenvironment/my_new_app/local/lib/python2.7/site-packages/pymc3/variational/inference.pyc in fit(n, local_rv, method, model, random_seed, start, **kwargs)
    618                         'or Inference instance' %
    619                         set(_select.keys()))
--> 620     return inference.fit(n, **kwargs)

/home/ksk15c/virtualenvironment/my_new_app/local/lib/python2.7/site-packages/pymc3/variational/inference.pyc in fit(self, n, score, callbacks, progressbar, **kwargs)
    117         progress = tqdm.trange(n, disable=not progressbar)
    118         if score:
--> 119             self._iterate_with_loss(n, step_func, progress, callbacks)
    120         else:
    121             self._iterate_without_loss(n, step_func, progress, callbacks)

/home/ksk15c/virtualenvironment/my_new_app/local/lib/python2.7/site-packages/pymc3/variational/inference.pyc in _iterate_with_loss(self, n, step_func, progress, callbacks)
    147                     scores = scores[:i]
    148                     self.hist = np.concatenate([self.hist, scores])
--> 149                     raise FloatingPointError('NaN occurred in optimization.')
    150                 scores[i] = e
    151                 if i % 10 == 0:

FloatingPointError: NaN occurred in optimization.
````

**Comment by twiecki** [comment]
@Oedon Make sure that the model test_value is valid, alternatively, check: http://pymc-devs.github.io/pymc3/notebooks/howto_debugging.html

**Comment by twiecki** [comment]
Oh, I see, this function: def simpson(f, a, b, n): isn't doing what you think it does, the function is called once during model creation, then never again. The model needs to be pure theano code. I would look into theano.scan for the loop and theano.IfElse or theano.switch to theanify that function.

**Comment by Oedon** [comment]
Is there already a theano way to preform definite integrals? The documentation for `theano.scan()` seems rather complex.

**Comment by twiecki** [comment]
@Oedon Yes, `scan` is a bit hard to use. You can also use a theano.op but you will not get gradients: http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Arbitrary-deterministics

**Comment by twiecki** [comment]
Related: https://github.com/Theano/Theano/issues/3564

**Comment by Oedon** [comment]
Sweet thank you for your help. It looks like I may have to be content with not being able to use gradient samplers for the time being. I have been trying out the module `emcee` and it looks like I'm getting good results there, and may be more fitting since apparently astronomers prefer that for MCMC due to complicated non-differentiable likelihood models. 

Again, thanks for the help you provided. Always glad to see devs actively helping people with issues :)

**Comment by twiecki** [comment]
Fair enough, we do have an ensemble sampler ATMCMC that works similar to emcee if you grow tired of writing down you own likelihoods.

**Comment by junpenglao** [comment]
@Oedon we will set up a Discourse forum soon and maybe we can keep the discussion about the implementation there.

**Comment by Oedon** [comment]
@twiecki @junpenglao So it turns out that if I put the `simpson` function in a separate file and Cythonize it, then do (on a separate line):
```
with model:
    trace = sample(nSamples)
```
`ADVI` converges and `NUTS` samples perfectly fine, albeit maybe a bit slowly (~ 30-40 iter/s). In any case it returns the correct values so that's a definite improvement.

**Comment by junpenglao** [comment]
Interesting - did you also write a gradient? 
cc @aseyboldt for potential interested

**Comment by Oedon** [comment]
Nope, I believe `ADVI` calculates that? But I'm not sure. The only thing I changed from my initial post was moving the `simpson` function to `simpson.pyx`, then creating a `setupsimpson.py` file like:
```
from distutils.core import setup
from Cython.Build import cythonize

setup(ext_modules = cythonize("simpson.pyx"))
```
then running in the shell:
`$ python setupsimpson.py build_ext --inplace`
and then importing the file by name like normal. I don't understand why this works but I'm glad it does.

**Comment by aseyboldt** [comment]
@Oedon Could you post your complete code? The definitions of z and y seems to be missing.
I don't think cythonizing does what you think it's doing. simpson should only be called once. I think the reason this is still more or less working is that the loop conditions don't depend on any theano variables. So in those loops you are actually building up one gigantic theano graph with unrolled loops. It then computes the gradient of using this graph.

**Comment by Oedon** [comment]
```
import pymc3 as pm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from simpson2 import simpson
import theano as th
import theano.tensor as T

d    = pd.read_csv("data.csv")
z    = np.array(d['z'])
y    = np.array(d['mu'])
yerr = np.array(d['dmu'])
c    = 299792.458

with pm.Model() as model:
    M = pm.Uniform('pM', 0., 2.)
    L = pm.Uniform('pL', 0., 2.)
    H = pm.Uniform('pH', 50., 100.)
    
    sigma = th.shared(np.asarray(yerr, dtype=th.config.floatX), name='sigma')
    
    def coMovDist(z):
        return c/(H * (T.sqrt(M*((1.+z)**3) + (1.-L-M)*((1.+z)**2) + L)))
    
    mean = 5. * T.log10((1.+z) * simpson(coMovDist,0.,z,10) / (10**(-5)))
    
    likelihood = pm.Normal('likelihood', mu = mean, sd = sigma, observed = y)

with model:
    trace = pm.sample(1000)

Out [ ]:
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
Average Loss = -107.37:  25%|██▌       | 50990/200000 [00:48<02:19, 1066.32it/s]
Convergence archived at 51000
Interrupted at 51,000 [25%]: Average Loss = -83.833
100%|██████████| 1500/1500 [00:39<00:00, 37.54it/s] #it adds 500 draws for some reason

pm.plot_posterior(trace)

Out [ ]:
```
![image](https://user-images.githubusercontent.com/28813958/27704357-61590fae-5cd8-11e7-9a33-1c559c9be716.png)

This is the result for using the same data set on a model created in `emcee` (about 6000 samples):
![image](https://user-images.githubusercontent.com/28813958/27704768-aa1c6410-5cd9-11e7-93e4-08490c364f8c.png)

for a comparison of the results.
