### ISSUE TITLE
Feature request: Add options to run traces sequentially rather than in parallel

### ISSUE THREAD

**Issue by bburan** [pymc-devs/pymc#2205]
For models with hundreds of parameters, each individual process running the trace can take up most of the computer memory. That results in significant swapping and a massive performance hit. Alternatively, it would be nice to be able to do:

trace1 = sample(...)
trace2 = sample(...)
trace3 = sample(...)

multitrace = combine(trace1, trace2, trace3)

**Comment by hvasbath** [comment]
But you can do that exactly like that already!?
```
mtrace = pymc3.backends.base.merge_traces(list_of_traces)
```
However, the traces must have different chain numbers!

**Comment by twiecki** [comment]
Wonder if and where we should add docs on that, I also didn't know about it.

**Comment by junpenglao** [comment]
Maybe a small script in the example folder?

**Comment by bburan** [comment]
This is exactly what I need. Just couldn't find it in the docs. Thanks!
