### ISSUE TITLE
Make logo transparent?

### ISSUE THREAD

**Issue by jakevdp** [pymc-devs/pymc#2206]
I found it useful to have a transparent version of the PyMC3 logo; here it is in case others find it useful (also, the png is about 1/2 the size of the jpg currently on the site :smile:).

![pymc3](https://cloud.githubusercontent.com/assets/781659/26266864/0d462598-3c9c-11e7-8697-2e811e231694.png)

**Comment by twiecki** [comment]
Thanks!

**Comment by ColCarroll** [comment]
Are you swapping this into the repo?  I can put together that pr

**Comment by twiecki** [comment]
I think we have a svg or eps of this too, @fonnesbeck?

**Comment by fonnesbeck** [comment]
I've got them on Dropbox. I will share them with you @ColCarroll
