### ISSUE TITLE
dose the value of 'sd' influence the final result?

### ISSUE THREAD

**Issue by dreamqin68** [pymc-devs/pymc#2214]
Y= pm.Normal('Y',mu,sd,observed =obs)
when sd=1000(maybe more), the speed of convergence is fast. But when sd=1(maybe less), the speed of convergence is more slowly. 
So dose the value of  'sd' influence the final result?

**Comment by twiecki** [comment]
Yes, certainly priors influence inference.

**Comment by dreamqin68** [comment]
@twiecki  I mean that the output of many input parameters. I had a test that the RMSE which between the output predicted value Y and the observed value obs of different values of 'sd' are similar. So I guess that the value of 'sd' just influence the convergence but not the fitting result. Right?
