### ISSUE TITLE
does the value of ‘sd’ of output distribution influence the convergence but  not the fitting result? 

### ISSUE THREAD

**Issue by dreamqin68** [pymc-devs/pymc#2217]
I mean that the output of many prior parameters. eg. 
    x = pm.Normal('x', mu=.5, sd=2, shape=(2, 1))
    y = 2x+1
    d = pm.Normal('data', mu=y, sd=.75 , observed=data)

 I had a test that the RMSE which between the output predicted value y and the observed value obs of different values of 'sd' ( d = pm.Normal('data', mu=y, sd=xxx , observed=data))are similar. So I guess that the value of 'sd' just influence the convergence but not the fitting result. Right?

**Comment by twiecki** [comment]
Yes, `sd` is just the noise term here.  Usually you would place a prior on that. If you want a more formal introduction, check out one of the books here: http://pymc-devs.github.io/pymc3/#learn-bayesian-statistics-with-a-book-together-with-pymc3
