### ISSUE TITLE
Feature Request: Gaussian process with Student likelihood

### ISSUE THREAD

**Issue by aplavin** [pymc-devs/pymc#2222]
I couldn't find examples on how to fit gaussian processes with other (non-gaussian) likelihoods, so tried the obvious solution myself - replace all `MvNormal` with `MvStudentT` (with some fixed `nu`, for example I set 1).

- First I subclassed `GP` class like this:
```python
class GP(pm.gp.GP):
    def logp(self, Y, X=None):
        if X is None:
            X = self.X
        mu = self.M(X).squeeze()
        Sigma = self.K(X) + tt.eye(X.shape[0])*self.sigma**2

        return pm.MvStudentT.dist(mu=mu, Sigma=Sigma, nu=1).logp(Y)
```

- then in `sample_gp` ([gp/gp.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/gp/gp.py)) replaced `MvNormal.dist(m_post, S_post, shape=Z.shape[0])` with `MvStudentT.dist(mu=m_post, Sigma=S_post, nu=1, shape=Z.shape[0])`.

The model fits and samples successfully, but I'm totally not sure if this is the right solution, as the resulting process doesn't seem any more robust than plain `pm.gp.GP`. What's wrong in my solution?

**Comment by junpenglao** [comment]
hmm looking at the code it seems fine and in principle, this should work (sample without problem). 
Maybe it is worth to try modelling the underlying function as a noiseless GP and then realising it as a Student-t distribution. Something like:
```python
    Sigma = f_cov(X)
    meanfuc = f_mu(X).squeeze()
    
    y_mu = pm.MvNormal('y_mu', mu=meanfuc, cov=Sigma, shape=(n,))
    y_obs = pm.StudentT('y_obs', mu=y_mu, lam=1, nu=1, observed=y)
```
There also other ways to formulated it. For example, in http://www.jmlr.org/papers/volume12/jylanki11a/jylanki11a.pdf they suggested using a scale mixture representation of the Student-t distribution.

**Comment by aplavin** [comment]
@junpenglao but as I understand pymc, when we use `y_mu` and `y_obs` as you suggest it considers `y_mu` as extra parameters having gaussian prior and optimizes/samples it as well - am I right? On the other hand, in plain gaussian process we only have covariation function options (like lengthscale) and likelihood options (like sigma) as parameters.

**Comment by junpenglao** [comment]
Yes, you are right: in this case, it will sample from `y_mu` as well.  
In GP with zero-mean function, its marginal likelihood is a function of the hyper-parameter length-scale, signal standard deviation (sometimes called likelihood), and noise standard deviation. For example, in PyMC3 the `GP` has a noise standard deviation `sigma` that can be added to the diagonal of the covariance function: https://github.com/pymc-devs/pymc3/blob/master/pymc3/gp/gp.py#L74. So in my suggestion, it is just saying that the noise is t-distributed instead of also Gaussian. 

Back to your question of robustness, since length-scale and noise standard deviation is usually correlated (e.g., see page 116 of [Gaussian Processes for Machine Learning](http://www.gaussianprocess.org/gpml/chapters/RW.pdf)), a more informative prior usually helps as well.

**Comment by sivark** [comment]
@aplavin The whole point of "Gaussian" processes is that the joint/conditional/marginal distributions are all Gaussian. This means that they're all characterized by a mean vector and a covariance matrix, and both of those are tractable to compute. If you wish to model the randomness by some other distribution, then the formulae to estimate `m_post` and `S_post` (and whatever other quantities are needed to characterize the posterior distribution) will have to change, and for generic distributions there are no easy ways to compute those. So, replacing `MvNormal` by `MvStudentT` inside `sample_gp` doesn't really make any sense. You will have to change many more formulae.

That said, it seems like "Student-T processes" have been studied recently. Here are some interesting links based on a few minutes of googling:
1. [Student-t Processes as Alternatives to Gaussian Processes](https://arxiv.org/abs/1402.4306)
2. [Student-T processes using GPy](https://github.com/SheffieldML/GPy/issues/453)

PS: Maybe I misunderstood the original question? Apologies if I stated what you already knew.

**Comment by aplavin** [comment]
@sivark yes, after asking here I read about student-T processes, and see that almost all the formulae are to be changed. I don't have enough competence to implement it myself in pymc, so as of now will probably use GPy/GPflow for robust gaussian processes.

**Comment by bwengals** [comment]
@aplavin Also check out [GPML](http://www.gaussianprocess.org/gpml/code/matlab/doc/), which has this.  It and GPy are the most extensive GP packages by far.  If you don't have Matlab it does run on Octave.

**Comment by junpenglao** [comment]
Hi @aplavin, I think you can do this quite easy now with the new GP API thanks to @bwengals. You can find an example here http://docs.pymc.io/notebooks/GP-TProcess.html

**Comment by aplavin** [comment]
@junpenglao I just noticed these new features a couple of days ago, they look great! But as I understood gaussian processes with custom (e.g. student) likelihood are described [here](http://docs.pymc.io/notebooks/GP-Latent.html#Example-1:-Regression-with-Student-T-distributed-noise) - and your link describes `T processes` which are not gaussian processes of course. Am I right?

**Comment by aloctavodia** [comment]
@aplavin you are right.

**Comment by fonnesbeck** [comment]
The `Latent` GP class can be associated with any likelihood you want. In fact the [Latent GP example notebook](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-Latent.ipynb) shows the Student-T likelihood as an example.
