### ISSUE TITLE
Feature request: Add new Discontinuous HMC which can handle discrete parameters

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2238]
https://arxiv.org/pdf/1705.08510.pdf

**Comment by junpenglao** [comment]
OMG!!!
The one million question: can it be extended to ADVI? @ferrine

**Comment by ferrine** [comment]
Started reading

**Comment by fonnesbeck** [comment]
I think we have our journal club paper for this month.

**Comment by twiecki** [comment]
Anyone up for leading the discussion?

**Comment by ferrine** [comment]
Still reading in spare time

**Comment by junpenglao** [comment]
FYI, Xian Robert's comment from his blog https://xianblog.wordpress.com/2017/07/03/hamiltonian-mc-on-discrete-spaces/

**Comment by fonnesbeck** [comment]
Funny that he mentions Jolly-Seber models. I spend a large part of my graduate training fitting those models (and their generalizations).

**Comment by junpenglao** [comment]
Follow up from Xian Robert's blog: authors' replies
https://xianblog.wordpress.com/2017/07/08/hamiltonian-mc-on-discrete-spaces-a-reply-from-the-authors/
