### ISSUE TITLE
"from pymc3 import fit" gives ImportError

### ISSUE THREAD

**Issue by curious-techie** [pymc-devs/pymc#2263]
pymc3 version 3.0:  Windows 7: Anaconda, Jupyter Notebook, Python 3.6.1 (64 bit)

How can this be fixed?
Source ( https://www.youtube.com/watch?v=TMmSESkhRtI#t=01h24m28s )

**Comment by junpenglao** [comment]
hi @curious-techie, this is a new feature, you might need to upgrade to master:
`pip3 install --upgrade git+https://github.com/pymc-devs/pymc3.git`

**Comment by fonnesbeck** [comment]
@curious-techie this will be available in 3.1, which we plan on releasing very soon.
