### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by dreamqin68** [pymc-devs/pymc#2266]
when I writed like this:
    x1=pm.Normal(...)
    x2=pm.Normal(...)
     ......
    x20=pm.Normal(...)
    Y =f(x1,x2,.....x20)
    Y=pm.Normal('Y',mu = Y,observed =obs)
    step=pm.HamiltonianMC()
    trace = pm.sample(n_samples,step=step,chain=2,njobs=2)
      ......

then I got "Segmentation fault (core dumped) "

But when I writed like this:
   x1=pm.Uniform(...)
   x2=pm.Uniform(...)
     ......
   x20=pm.Uniform(...)
   Y =f(x1,x2,.....x20)
   Y=pm.Normal('Y',mu = Y,observed =obs)
   step=pm.HamiltonianMC()
   trace = pm.sample(n_samples,step=step,chain=2,njobs=2)
   ......

then I got a normal answer. So why?

**Comment by aseyboldt** [comment]
That sounds bad, and probably like a theano issue (pymc3 itself shouldn't produce any segfaults on its own). Can you maybe post a complete example that I can run on my machine?

**Comment by dreamqin68** [comment]
@aseyboldt  Yes. Can you give a email address to me?  My email : 1315176211@qq.com
