### ISSUE TITLE
FloatingPointError: NaN occurred in optimization with NUTS

### ISSUE THREAD

**Issue by minhhg** [pymc-devs/pymc#2272]
Hi,
I got the following error with NUTS
"FloatingPointError: NaN occurred in optimization",
but without any problem with
 step = pm.Metropolis()
%===============================
System: Ubuntu 16.04.1 LTS (64 bits)
python: Python 2.7.13 |Continuum Analytics
numpy: 1.11.3
pandas: 0.19.2
theano: 0.8.2.dev-901275534cbfe3fbbe290ce85d1abf8bb9a5b203
%================================
It is a simple least square problem. I would appreciate any help.
   Thanks,
     Minh

**Comment by junpenglao** [comment]
Could you please provide a bit more details? Information of your model and data would help us to faster diagnose the problem.

**Comment by twiecki** [comment]
One thing is to update theano to 0.9.

**Comment by minhhg** [comment]
Hi,
Here is the whole code:
%---------------------------------------------------------------
```
import numpy as np
from pymc3 import Model, Normal, HalfNormal
from pymc3 import NUTS, sample
from scipy import optimize
from pymc3 import Slice



def  vsk_bond_price(tau, r, alpha, mu, sigma):
    B = (1 - np.exp (-alpha*tau))/ alpha
    A = np.exp( (mu - sigma**2/2.0/alpha**2)*(B - tau) - sigma**2*B**2 /4.0/alpha )
    bond_price = A* np.exp( -r * B)
    return  bond_price

def  bond_2_yield(bond_price, tau):
     yld = -np.log(bond_price)/tau
     return yld


mu0 = 0.04 #year  4%
#Set model parameters: alpha, mu, sigma
alpha0 = 0.1
sigma_y_lr = 0.02 
a_y = alpha0
sigma0 = sigma_y_lr*np.sqrt(2*a_y)
r0 = 0.03
taus = range(1,120)
taus = np.array(taus)*1.0


#generate noisy observation
yields = [bond_2_yield(vsk_bond_price(tau, r0, alpha0, mu0, sigma0), tau) for tau in taus  ]
s_noise = 2.E-4
yields_noise = np.array(yields) +  s_noise* np.random.randn(len(yields))



def fmu_yld(alpha, mu, sigma):
    #bond_prices = [vsk_bond_price(tau, r0, alpha + 1.e-9, mu, sigma) for tau in taus ]
    yields = [bond_2_yield(vsk_bond_price(tau, r0, alpha, mu, sigma), tau) for tau in taus  ]
    
    return yields


    
basic_model = Model()

with basic_model:

    # Priors for unknown model parameters
    alpha = HalfNormal('alpha', sd=0.3)
    mu = Normal('mu', mu=0.04, sd=0.3)
    sigma = HalfNormal('sigma', sd=0.2)
    
    sigma_noise = 2.E-4

    # Expected value of outcome
    #mu = alpha + beta[0]*X1 + beta[1]*X2
    mu = fmu_yld(alpha, mu, sigma)

    # Likelihood (sampling distribution) of observations
    Y_obs = Normal('Y_obs', mu=mu, sd= sigma_noise, observed=yields_noise)
    


with basic_model:
    # draw 500 posterior samples
    #step = pm.Metropolis()
    #step = pm.Slice()
    #trace = sample(40000, step=step)
    trace = sample(10000)    
    %------------------------------------------------------
```

**Comment by junpenglao** [comment]
Rewriting the function into theano and providing a starting value seems to do the trick:
```python
import theano.tensor as tt
def fmu_yld2(alpha, mu, sigma, r=r0, taus=taus):
    B = (1 - tt.exp (-alpha*taus))/ alpha
    A = tt.exp( (mu - sigma**2/2.0/alpha**2)*(B - taus) - sigma**2*B**2 /4.0/alpha )
    bond_price = A* tt.exp( -r * B)
    yld = -tt.log(bond_price)/taus
    return yld

basic_model = Model()
sigma_noise = 2e-4
with basic_model:
    # Priors for unknown model parameters
    alpha = HalfNormal('alpha', sd=0.3, testval=alpha0)
    mu = Normal('mu', mu=0.04, sd=0.3, testval=mu0)
    sigma = HalfNormal('sigma', sd=0.2, testval=sigma0)

    # Expected value of outcome
    yld = fmu_yld2(alpha, mu, sigma, r=r0, taus=taus)

    # Likelihood (sampling distribution) of observations
    Y_obs = Normal('Y_obs', mu=yld, sd= sigma_noise, observed=yields_noise)
    trace = sample(1000, njobs=2)

    y_ppc=sample_ppc(trace, 100)

plt.plot(y_ppc['Y_obs'].transpose(), alpha=.05, color='gray')
plt.plot(yields_noise,'o');
```

**Comment by junpenglao** [comment]
I am going to close this because it is not an issue but feel free to continue the conversation.

**Comment by minhhg** [comment]
Hi,
testval which you set were the true values. In real applications, we do not know them.  I have tried to set true value +  0.1, the problem came back. Your trick did not solve problem actually.

**Comment by junpenglao** [comment]
In my experience, this is usually b/c some of the parameters are not scaling the same: small change in this parameters leads to the blowing up of logp very quickly. For example, the true value of `sigma` is at a much smaller scale compare to other parameters, moreover, it was taken the square in the function `fmu_yld`, which put it to an even smaller scale.  

We will try to make the default of ADVI handle better of these cases. Meanwhile, you can try to reparameterize your model. For example, if it is valid in your case, you can try to scale the value of `sigma` in the function `fmu_yld`:
```python
def fmu_yld2(alpha, mu, sigma, r=r0, taus=taus):
    B = (1 - tt.exp (-alpha*taus))/ alpha
    A = tt.exp( (mu - (sigma/10.)**2/2.0/alpha**2)*(B - taus) - (sigma/10.)**2*B**2 /4.0/alpha )
    bond_price = A* tt.exp( -r * B)
    yld = -tt.log(bond_price)/taus
    return yld
```
This way, advi wont ran into problem even if you dont provide a starting value.

**Comment by aloctavodia** [comment]
I just want to add that I got the same error for a very simple model (a version of the light speed model) that used to run ok. BTW @junpenglao I agree with you about the different scale, but I was under the impression that this is to be a bigger problem with older version of PyMC3 (but I am not sure) 

``` python
with pm.Model() as modelo_g:
    mu = pm.Uniform('mu', 24000, 25000)
    sigma = pm.HalfNormal('sigma', sd=10)

    # mu = pm.Uniform('mu', datos.mean() / 100.0, datos.mean() * 100.0)
    # sigma = pm.HalfNormal('sigma', datos.std() * 100)

    y = pm.Normal('y', mu=mu, sd=sigma, observed=datos)
    trace_g = pm.sample(2000)
```
Some observations:

* passing a testval `mu = pm.Uniform('mu', 24000, 25000, testval=data.mean())` fix the problem.
* when using the commented priors, the model runs but sampling is slow (about 10 it/s)
* [About 5 moths ago](https://github.com/aloctavodia/EBAD/blob/master/03_Modelos_multiparam%C3%A9tricos_y_modelado_jer%C3%A1rquico.ipynb)  the very same model used to run without problems and without the need to add a testval. 

Any thoughts?

**Comment by junpenglao** [comment]
@aloctavodia seems to do with the Type, so 
`modelo_g.test_point` 
gives 
`{'mu_interval__': array(nan), 'sigma_log__': array(2.076793740349318)}`
 
But if you change `mu` into `mu = pm.Uniform('mu', 24000., 25000.)`, then it's fine:
```python
In [1]: modelo_g.test_point
Out[1]: {'mu_interval__': array(0.0), 'sigma_log__': array(2.076793740349318)}
```

And the sampling is fine as well.

@aloctavodia can you open an issue?
