### ISSUE TITLE
Unused test in test_sampling.py

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2276]
https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_sampling.py#L120-L143

I believe the SoftUpdate test is not being run currently.
Also, the test need to be rename: `pm.sampling._soft_update` -> `pm.sampling._update_start_vals`

**Comment by twiecki** [comment]
CC @fonnesbeck

**Comment by junpenglao** [comment]
Also, I think my theano knowledge ran out trying to fix #2258, which is semi-related to this. Somebody else should take a stab and fix that...

**Comment by fonnesbeck** [comment]
Yeah, I don't think `_soft_update` exists anymore. Was it refactored away by @ferrine?

**Comment by junpenglao** [comment]
@fonnesbeck I think you changed the name at some point.

**Comment by fonnesbeck** [comment]
So I did. I don't remember doing it, but Git doesn't lie. Looks like it is called `_update_start_vals` now. I will fix the test.
