### ISSUE TITLE
Need informative error message for duplicate variable names

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2279]
Having duplicate variable names in a model, such as the following: 

```python
β = pm.Beta('β', 1., α, shape=C)
...
β = pm.Normal('β', 0, sd=10, shape=3)
```

currently results (if you're lucky) in a cryptic error when recording a sampled value results in a shape mismatch.

```python
/Users/fonnescj/Repos/pymc3/pymc3/backends/ndarray.py in record(self, point, sampler_stats)
     95         for varname, value in zip(self.varnames, self.fn(point)):
     96             print(varname)
---> 97             self.samples[varname][self.draw_idx] = value
     98 
     99         if self._stats is not None and sampler_stats is None:

ValueError: could not broadcast input array from shape (3) into shape (20)
```

If the shapes are the same, you might not get any sort of message. There needs to be a name error raised when variables are added to a model that alerts users of the conflict. This model happily ran under ADVI until NUTS sampling began.

**Comment by aseyboldt** [comment]
That's strange. Shouldn't [this](https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L569) throw an exception?

**Comment by fonnesbeck** [comment]
I was surprised. Haven't seen this before. Will try and see why it wasn't triggered.

**Comment by fonnesbeck** [comment]
It has to do with the fact that one of the variables is transformed and the other is not. For example:

```python
with pm.Model():
    a = pm.Beta('a', 1, 1)
    a = pm.Normal('a', 0, 1)
```

will not trigger the exception. But if they are both untransformed, or have the same transformation, PyMC will discover it. We need to make the check more robust.

**Comment by junpenglao** [comment]
Same goes for 
```python
with pm.Model() as model:
    a = pm.Normal('a', 0, 1)
    a = pm.Potential('a', a**2)
```
