### ISSUE TITLE
Partially observed random variable

### ISSUE THREAD

**Issue by popeye007** [pymc-devs/pymc#2282]
Is there any convenient way to create a random variable that is partially observed? (i.e., some values are observed, but some values are not observed.) Thanks in advance.

**Comment by junpenglao** [comment]
Yes, you can just create a masked numpy array with the missing/unobserved value masked.
You can see an example in https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/lasso_missing.py

**Comment by aseyboldt** [comment]
@popeye007 Instead of using masked numpy arrays, you can also use a pandas dataframe with nan values. That is often more convenient. I'll close this issue, feel free to reopen if you disagree.
