### ISSUE TITLE
Multiple Observation vectors in MvGaussianRandomWalk

### ISSUE THREAD

**Issue by kpei** [pymc-devs/pymc#2289]
I am currently trying to implement a Mv gaussian timeseries model that models a pair of (X,Y) coordinates over time.  I want to train a single model and I have multiple observations of the time series of different length (e.g N observations of different length T by 2 vectors).

Working off of https://github.com/pymc-devs/pymc3/issues/535 and using the list comprehension, the Metropolis sampler works quite well.  My question is, is this correct in terms of training the model **over** the entire observation set or is it training N MvGaussianRandomWalk models?

Below my code:

```
with pm.Model() as position_model:
    # covariance matrix
    nu = pm.distributions.continuous.Exponential('nu', lam=0.5)
    sd = pm.distributions.continuous.Exponential('sd', lam=0.5, shape=n)
    C_triu = pm.distributions.multivariate.LKJCorr('C_triu', nu, n)
    C = pm.Deterministic('C', tt.fill_diagonal(C_triu[np.zeros((n, n), dtype=np.int32)], 1.))
    sigma = pm.Deterministic('cov', tt.nlinalg.diag(sd))
    
    mu = pm.distributions.multivariate.Normal('drift', mu=0., sd=100., shape=2)
    pos = [pm.distributions.timeseries.MvGaussianRandomWalk('position_CT_rnd_%i' % i, mu=mu, 
                                                            cov=sigma, observed=obs[i]) for i in range(len(obs))]
    start = pm.find_MAP()
    step = pm.Metropolis()
    trace = pm.sample(n_samples, step, start=start, tune=5000)
```

**Comment by junpenglao** [comment]
In this case the model is training on the entire observation set, since they are all depending on the same set of parameters. 
I will close this for now - let's continue our discussion on discourse: https://discourse.pymc.io/t/geometric-variable-not-being-properly-sampled/28
