### ISSUE TITLE
Docker container build failed

### ISSUE THREAD

**Issue by taku-y** [pymc-devs/pymc#2295]
@ColCarroll `./scripts/start_container.sh` failed on my Mac.
It shows the following error message:

```
Step 7 : RUN /bin/bash /tmp/create_testenv.sh --global --no-setup

...

+ pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1
+ pip install -e .
Directory '.' is not installable. File 'setup.py' not found.
```

Is this a bug, or do I have something wrong?

**Comment by ColCarroll** [comment]
That looks odd.  I'll try it in a few hours.

**Comment by taku-y** [comment]
`create_testenv.sh` try to execute `pip install -e .` at `/home/jovyan/work`, while `start_container.sh` mounts local `$SRC_DIR` to `/home/jovyan/pymc3`.

**Comment by taku-y** [comment]
#2317 solves the problem.
