### ISSUE TITLE
Auto-scale plot font sizes

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2300]
When different figure sizes are specified for our plots, the labels and other text annotations to not scale with them, and end up looking terrible:

![](http://d.pr/i/KhSYje+)

It should be straightforward to scale fonts by default to some acceptable size.

**Comment by junpenglao** [comment]
is this fixed by https://github.com/pymc-devs/pymc3/pull/2304?

**Comment by fonnesbeck** [comment]
It is not. The fix in #2304 is just a bug fix for manually setting text size.

**Comment by twiecki** [comment]
I think there was a PR for this?
