### ISSUE TITLE
compounding GaussianRandomWalk's

### ISSUE THREAD

**Issue by kochede** [pymc-devs/pymc#2308]
Hi,

I try to implement the simplest state-space local-linear trend model: 
```
Observation equation: 
    y_t = \mu_t + \eps_t,   \eps_t is Normal
Transition equations: 
     \mu_t = \mu_t-1 + \nu_t + \eta1_t,       \eta1_t is Normal 
     \nu_t = \nu_t-1 + \eta2_t,       \eta2_t is Normal
```
But I get an exception that looks like a bug. Could you please help?

The following minimal code fails with exception about shape mismatch, although it seems should not:

``` python
from pymc3.distributions.timeseries import GaussianRandomWalk
from pymc3 import Model, Normal
y=range(100)
with Model() as model:
    nu = GaussianRandomWalk('nu', mu=0, sd=1, shape=100)
    mu = GaussianRandomWalk('mu', mu=nu, sd=1, shape=100)
    y = Normal( 'y', mu=mu, sd = 1, observed=y )
```

The exception I get is:

> 
> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-39-30b51cc70c10>", line 3, in <module>
>     mu = GaussianRandomWalk('mu', mu=nu, sd=1, shape=100)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\pymc3\distributions\distribution.py", line 31, in __new__
>     return model.Var(name, dist, data)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\pymc3\model.py", line 280, in Var
>     var = FreeRV(name=name, distribution=dist, model=self)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\pymc3\model.py", line 508, in __init__
>     self.logp_elemwiset = distribution.logp(self)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\pymc3\distributions\timeseries.py", line 75, in logp
>     innov_like = Normal.dist(mu=x_im1 + mu, tau=tau, sd=sd).logp(x_i)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\theano\tensor\var.py", line 128, in __add__
>     return theano.tensor.basic.add(self, other)
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\theano\gof\op.py", line 674, in __call__
>     required = thunk()
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\theano\gof\op.py", line 843, in rval
>     fill_storage()
> 
>   File "C:\Users\Denis\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1698, in __call__
>     reraise(exc_type, exc_value, exc_trace)
> 
>   File "<string>", line 2, in reraise
> 
> ValueError: Input dimension mis-match. (input[0].shape[0] = 99, input[1].shape[0] = 100)

**Comment by junpenglao** [comment]
I dont think you are using the `GaussianRandomWalk` correctly. Parameter `mu` is the initial point of the Random walk (value on t0).

I think what you want is 
```python
with Model() as model:
    nu = GaussianRandomWalk('nu', mu=0, sd=1, shape=100)
    mu = GaussianRandomWalk('mu', mu=0, sd=1, shape=100)
    ymu = mu + nu
```

Since this is not a bug, could you please move this to https://discourse.pymc.io/ ? We are trying to move all modelling related question to discourse for better search and communications.

**Comment by kochede** [comment]
@junpenglao Thanks a lot for such a quick answer - just fantastic! But seems there are couple problems. 

1. First, as the GaussianRandomWalk [docstring states](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/timeseries.py) -- mu is the innovation drift, not the initial value.

2. Second, in the model you suggest the \mu and \nu are independent random walks. While what I need is to compound them, so that \nu is a random walk and \mu is a random walk with a drift equal to \nu.

Do you have a clue why the above code throws an exception? It seems should not...

Thanks a lot in advance.

**Comment by junpenglao** [comment]
Oh yes you are right - my bad.
In that case you can do:
```
    nu = GaussianRandomWalk('nu', mu=0, sd=1, shape=99)
    mu = GaussianRandomWalk('mu', mu=nu, sd=1, shape=100)
```
since GaussianRandomWalk ignored the first element https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/timeseries.py#L91-L94

**Comment by kochede** [comment]
@junpenglao Thanks this works! 
What's the meaning? Why should I specify one random walk shorter than another?

How do I move the thread to https://discourse.pymc.io/  ?

**Comment by junpenglao** [comment]
You can think of it as this way: `nu` is the underlying process controlling the change of `mu`, so each element of `nu` is the differences between mu_k and mu_k+1

You need to manually start a new thread on discourse ;-) You can do that if you have further questions.

**Comment by kochede** [comment]
@junpenglao I see, thanks. 

Probably makes sense to add into the GaussianRandomWalk docstring, that 

> "if  parameters mu= and sd= are not scalar, their shapes should be T-1 if the shape on the new random-walk is T"

**Comment by junpenglao** [comment]
@kochede good idea! wanna submit a PR for that ;-)
