### ISSUE TITLE
Convergence detection for advi in models with one variable

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#2310]
In models with only one variable advi seems to stop after the first iteration. Could this be a problem with convergence detetion, or is this just the progress bar that isn't updated?

```python
with pm.Model():
    pm.Normal('a')
    pm.sample()
```

```
Initializing NUTS using ADVI...
  0%|          | 0/200000 [00:00<?, ?it/s]
Convergence archived at 1000
Interrupted at 1,000 [0%]: Average Loss = 0.077683
100%|██████████| 1000/1000 [00:00<00:00, 2300.64it/s]
```

Also, the progress bar shows two different values for the average loss, one in the line of the actual progress bar, and a second (often very different) value at the end:
```
Auto-assigning NUTS sampler...
Initializing NUTS using ADVI...
Average Loss = -8,844.2:  25%|██▌       | 50473/200000 [00:57<02:24, 1032.93it/s]  
Convergence archived at 50500
Interrupted at 50,500 [25%]: Average Loss = 8.7524e+12
```

CC @ferrine

**Comment by ferrine** [comment]
In the first case it doesn't update. In the second I see negative values sometimes and I can't get why is it so. If we find convergence too fast we can change default `every` parameter
