### ISSUE TITLE
Leave One Out Cross-validation and RMSE

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2318]
Hello,
I'm trying to compare the results of my model with a model that uses a frequentist approach. This frequentist model uses a LOO Cross-validation and gives the RMSE as result.

Thus, my naive solution is to fit the model with (n-1) training examples, change the shared variables, and use sample_ppc to "predict". Finally I compute the RMSE.
This is a looong process (suggest me alternatives in case) and I have some errors about shared variabiles.

using this:

    X_shared = shared(X[features].values[train_index, :])
    [...]
    mu_phi = CAR2('mu_phi', adjacency=adj_shared, rho=rho, tau=tau, shape=X_shared.get_value().shape[0])

    [...]
    X_shared.set_value(X[features].values[test_group_indexes, :])

I have that mu_phi's shape doesn't get updated (n = 76 but it should be n=1). I don't find how to do this, so I am not sure whether it is a bug.

**Comment by junpenglao** [comment]
Did you try the LOO in pm.stats? There is an example here https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/Model%20Comparison.ipynb

Also, could you please move this to our dicourse forum https://discourse.pymc.io/? Thanks!

**Comment by denadai2** [comment]
@junpenglao I don't know how to compute the RMSE from LOO... :(
BTW I moved the discussion. Thanks
