### ISSUE TITLE
Metropolos taking too long to initialize

### ISSUE THREAD

**Issue by san7988** [pymc-devs/pymc#2321]
Hi,

I'm trying to use metropolis method for sampling. It takes too long to initialize the metropolis method.

The code :
`step = pm.Metropolis()`

This single line takes around 3 minutes to execute.
The sampling itself is pretty fast using **metropolis** but the initialization is kind of overshadowing all the speed up I gained over **slice** method.
Is this a known behavior? And can it be improved? In general how long  should it takes ideally for the metropolis method to initialize?

Thanks

**Comment by junpenglao** [comment]
Hi @san7988, I have never met this problem. You can try profiling your code to find out why/where is slow.
Also, do you mind moving this to our discourse forum https://discourse.pymc.io/? Thanks!

**Comment by san7988** [comment]
Thanks for the reply. I'll try and profile my code.
Moving this to discourse forum.

Thanks
