### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gp'

### ISSUE THREAD

**Issue by zachong** [pymc-devs/pymc#2331]
Hi,

I have just downloaded PyMC3 and I am trying the replicate the Gaussian Process Regression problem discussed at this link https://pymc-devs.github.io/pymc3/notebooks/GP-introduction.html
However, when I run the code I get an error for executing the following line
cov = s2_f_true * pm.gp.cov.ExpQuad(1, l_true)
The error message is as follows
AttributeError: 'module' object has no attribute 'gp'

I am using Python 2.7 which was obtained by installing Anaconda. Could it be that the gp object is missing from my installation of PyMC3?

Any help would be greatly appreciated.

Regards,
Adrian

**Comment by twiecki** [comment]
You need to install pymc3 master to get that feature:
`pip install -U git@github.com:pymc-devs/pymc3`
