### ISSUE TITLE
Add database backend for traces

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#234]
At some point, we will need to have a proper database backend to store the traces. For moderate-sized (and larger) models, keeping them in RAM is not feasible. I think we had too many backends in PyMC2, which was hard to maintain. We should maybe pick a couple; I suggest text and SQLite.

**Comment by jsalvatier** [comment]
Those seem pretty reasonable. Any other ones people want to do can done
pretty easily on their own.

**Comment by kyleabeauchamp** [comment]
Another option might be to use the Pandas HDF5 Table writer.  The thing I like about this is that it "looks" like a numpy array that supports `append()`.

**Comment by kyleabeauchamp** [comment]
Example code:

```
        store = pd.io.pytables.HDFStore(filename, "a")
        store.append(frame_key, frame)
```

**Comment by fonnesbeck** [comment]
Supporting HDF5 is a bit of a bear, based on my experience with our PyMC2 backend. PyTables is notoriously tricky to install, unless things have improved recently. PyTables is only an optional dependency for pandas, so most folks probably won't have it. I agree, however, that it is very nice once you have it installed.

**Comment by kyleabeauchamp** [comment]
I agree that HDF5 is hard to install _manually_, but (IMHO) it's not any worse than installing Numpy / Scipy.  For my own projects, I've been instructing users to install Enthought, Anaconda, SuperPack, or the package-repository versions of Python.  This has worked out pretty well.  

FWIW, I think Anaconda is now free for _everyone_, so there's no longer the cost barrier.

**Comment by kyleam** [comment]
Has anyone started to work on this? If not, I'll try to put something together.

**Comment by fonnesbeck** [comment]
I have not. There should probably be a discussion regarding which backends to support. We might want to pick a couple to implement, but make it easy to hook in others if folks want to tinker themselves. Perhaps text files and SQLite, or text and pickle?

**Comment by kyleam** [comment]
I think text files and SQLite seem like a good starting point, but as you said, I think the important thing is that it's easy to add backends (especially because I  prefer HDF5, so I'd like to be able to add that easily even if it's not a supported backend).

**Comment by jsalvatier** [comment]
That seems like a good approach to me.

**Comment by twiecki** [comment]
This was added.
