### ISSUE TITLE
Enable mathjax plugin to discourse

### ISSUE THREAD

**Issue by bwengals** [pymc-devs/pymc#2349]
Might be cool if people could write $\mathrm{math}$ on discourse.  

https://meta.discourse.org/t/is-mathjax-really-not-working/37653

**Comment by twiecki** [comment]
Hm, no idea how to edit the app.yml file on a discourse-hosted forum. @junpenglao ?

**Comment by junpenglao** [comment]
After some search seems we need to ask them to enable it - email sent, will keep you posted.

**Comment by junpenglao** [comment]
Unfortunately, we can't install plugins on free hosted servers. But according to discourse, they are considering supporting the MathJax plugin on the hosted sites, after they finish migrating to a better CommonMark library. They told me it will happen in a month or two.
