### ISSUE TITLE
website clean up

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2356]
I am checking http://docs.pymc.io/, and there are a few places need to be cleaned up.

- [x] API quickstart is under both getting_started.html and examples.html
- [x] Markdown Header within notebook should be `##` and the title being `##`, otherwise they appear the same on the right panel (e.g., see Sampler statistics and Multiple samplers)
- [x] redundent notebook http://docs.pymc.io/en/latest/notebooks/bayesian_neural_network_advi.html and http://docs.pymc.io/en/latest/notebooks/bayesian_neural_network_opvi-advi.html

**Comment by fonnesbeck** [comment]
Let's find a non-generic theme for this too. Should I hire 99designs again?

**Comment by ColCarroll** [comment]
Here are a bunch that might work.  I have not picked out a favorite yet!

https://github.com/yoloseem/awesome-sphinxdoc#themes

**Comment by junpenglao** [comment]
i actually dont mind the default as it suits well with pymc3 blue;-)

@ColCarroll https://github.com/crate/crate-docs-theme is quite nice

**Comment by denadai2** [comment]
I'll take care of some fixes :)

PS: I like more the blue one, although it is standard
