### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by jonmilson** [pymc-devs/pymc#2357]
Hi,

I tried running the pymc3.sample function and came to this particular error, can you please help.

Thanks,
Jon

File "~/pymc3/sampling.py", line 224, in sample
    init = init.lower()
AttributeError: 'dict' object has no attribute 'lower'

**Comment by junpenglao** [comment]
Hi Jon,
The attribute of `init` in `pm.sample` need to be a string of one from the below: 'ADVI', 'ADVI_MAP', 'MAP', 'NUTS', 'auto'. For example: `init='ADVI'`. You can leave it empty to use the default.
