### ISSUE TITLE
Type error for Poisson on GPU

### ISSUE THREAD

**Issue by pwl** [pymc-devs/pymc#2361]
I'm getting a [MethodNotDefined error]( https://gist.github.com/pwl/7c393e722622e4395e48986c76d015a9) when running the following code
```
with pm.Model():
    val = pm.Poisson.dist(
        mu = pm.Gamma('U',1,1,shape=3)).logp(theano.shared(np.arange(3)))
    inference = pm.ADVI()
    inference.approx.sample_node(val)
```
on a GPU with the following flags
```
os.environ['THEANO_FLAGS'] = 'device=cuda,floatX=float32,exception_verbosity=high'
```

**Comment by aseyboldt** [comment]
I don't have a gpu to test this on at the moment, but it looks like gammaln might not work for float64/int64.
Could you maybe try to cast `np.arange(3)` to float32? And also try to set `warn_float64='raise'` to figure out if there are any more float64 around?
(or wait, and I'll try it later ;)

**Comment by junpenglao** [comment]
I recorded in GPU you need to cast int to int16 if you set float to float32

**Comment by pwl** [comment]
Thanks for the help, it worked with `float32` but not with `int16`.

It's a pity that the warnings and API restrictions are not more explicit.  It is not the first time I had a type error like that, so far the only remedy was to start changing types and hope that some combination will work.  It is especially difficult to find a source of these errors in more complicated models because the logs from theano are rather cryptic (at least to me).

Would it be possible to enforce some type checking on a PyMC3 level?
