### ISSUE TITLE
TensorType(int16, vector) cannot store a value of dtype int64 without risking loss of precision

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2365]
From #2326 I implemented a generative model like this one

	with pm.Model():
	    [...]
	    beta = pm.Normal("beta1", mu=0, tau=0.01)
	    para = CAR(**args, shape=Xtrain.shape)
	    likelihood = Poisson("outcome", mu = tt.exp(para + X_train.dot(beta)), observed=Ytrain)
	    [...]
	    para_new = CAR(**args, shape=Xtest.shape)
	    y_predict = Poisson("outcome_test", mu = tt.exp(para_new + X_test.dot(beta)), shape=4)

and I have this error

	/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/theano/tensor/type.py in filter(self=TensorType(int16, vector), data=array([1584, 1606, 1507, 1176]), strict=False, allow_downcast=None)
	    135                             'this loss, you can: '
	    136                             '1) explicitly cast your data to %s, or '
	    137                             '2) set "allow_input_downcast=True" when calling '
	    138                             '"function". Value: "%s"'
	    139                             % (self, data.dtype, self.dtype, repr(data)))
	--> 140                         raise TypeError(err_msg)
	        err_msg = 'TensorType(int16, vector) cannot store a value o...nction". Value: "array([1584, 1606, 1507, 1176])"'
	    141                 elif (allow_downcast is None and
	    142                         type(data) is float and
	    143                         self.dtype == theano.config.floatX):
	    144                     # Special case where we allow downcasting of Python float

	TypeError: Bad input argument to theano function at index 0 (0-based).  
	Backtrace when that variable is created:

	  File "mcmc_kdd.py", line 419, in <module>
	    main()
	  File "mcmc_kdd.py", line 389, in main
	    pooled_trace = pm.sample(1000, njobs=2, tune=5000, step=step)
	  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/sampling.py", line 247, in sample
	    step = assign_step_methods(model, step, step_kwargs=step_kwargs)
	  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/sampling.py", line 90, in assign_step_methods
	    step = step_class(vars=vars, **args)
	  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/step_methods/metropolis.py", line 130, in __init__
	    self.delta_logp = delta_logp(model.logpt, vars, shared)
	  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pymc3/step_methods/metropolis.py", line 482, in delta_logp
	    inarray1 = tensor_type('inarray1')
	TensorType(int16, vector) cannot store a value of dtype int64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int16, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([1584, 1606, 1507, 1176])"

I think there is a bug here. Can you help me?

I also think that this might be related somehow: Why do we have all these int64 here? https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/metropolis.py#L144

Thanks

**Comment by junpenglao** [comment]
@denadai2 is it work by specifying the dtype?
