### ISSUE TITLE
Undeclared input in Gaussian processes example

### ISSUE THREAD

**Issue by denadai2** [pymc-devs/pymc#2368]
At the end of the notebook there is an error: http://docs.pymc.io/en/latest/notebooks/GP-introduction.html

**Comment by junpenglao** [comment]
This should be fix - would you like to rerun the notebook and PR a fix?

**Comment by denadai2** [comment]
I run the notebook, trying to fix the error, but I don't understand the problem. I'm not familiar with GPs

**Comment by junpenglao** [comment]
No problem! Thx for reporting.
