### ISSUE TITLE
Setting test_point for Uniform fails for some integers

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#2370]
@junpenglao  following our conversation in #2272, you are right that the problem is related with the type of the upper and lower arguments.

```python
a = 10000
b = 30000

with pm.Model() as model:
    mu = pm.Uniform('mu', a, b)
    print(model.test_point)
```
returns `{'mu_interval__': array(nan)}` and for `transformed=None`  returns `{'mu': array(-12768.0)}`!

This is only a problem for certain integers, lower values  like `a = 10`, `b = 30` or larger like `a  = 100000, b = 300000`  are ok. So I guess Theano is missing the right type, `int16` instead of `int32` or something like that, right?

A possible solution is to ensure that `lower` and `upper` are always floats doing something like this, inside `Uniform`:

```python
self.lower = lower = floatX(tt.as_tensor_variable(lower))
self.upper = upper = floatX(tt.as_tensor_variable(upper))
```

But I wonder if this easy solution could be hiding some other issue elsewhere.

**Comment by junpenglao** [comment]
> This is only a problem for certain integers, lower values like a = 10, b = 30 or larger like a = 100000, b = 300000 are ok. 

What kind of witchcraft is this LOL.

I think we can just cast it as float - the floatX idea is a good enough solution to me.
Did you check whether there is a same problem in `DiscreteUniform`?

**Comment by aloctavodia** [comment]
It seems `DiscreteUniform` is already doing the [trick](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/discrete.py#L441-L442)

OK then, I will send a PR. Thanks for the assistance!

**Comment by michaelosthege** [comment]
There's a potential for conflict with issue #2370
