### ISSUE TITLE
Side effect of pm.Model.__enter__

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#2378]
Diving in source code of `pymc3.model.py` ([one](https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L113), [two](https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L370)). One can notice that global state theano flags are modified. These manipulations can cause strange errors. I think a warning can solve the problem when entering a context:
```
You are using inconsistent `compute_test_value=%s` flag. To avoid strange bugs with missing test value please set `compute_test_value='raise'` for session
```

**Comment by aseyboldt** [comment]
I agree. I don't know what I was thinking when I wrote this. Just ignoring the given flags if they don't contain `compute_test_value` is clearly a bad idea. @ferrine I hope you didn't loose a lot of time because of this.
