### ISSUE TITLE
Max recursion limit error

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2380]
I've been applying to my internal datasets at work the radon example 

Get this error. 

```---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-29-381437761bf8> in <module>()
     16 
     17     # Linear regression
---> 18     radon_est = a[source_idx]* data.applied.values
     19 
     20     # Data likelihood

/home/springcoil/miniconda3/envs/py35/lib/python3.5/site-packages/theano/tensor/var.py in __getitem__(self, args)
    477                     check_bool(el)
    478 
--> 479         check_bool(args)
    480 
    481         if (isinstance(args, list) and

/home/springcoil/miniconda3/envs/py35/lib/python3.5/site-packages/theano/tensor/var.py in check_bool(args_el)
    475                     isinstance(args_el, collections.Iterable)):
    476                 for el in args_el:
--> 477                     check_bool(el)
    478 
    479         check_bool(args)

... last 1 frames repeated, from the frame below ...

/home/springcoil/miniconda3/envs/py35/lib/python3.5/site-packages/theano/tensor/var.py in check_bool(args_el)
    475                     isinstance(args_el, collections.Iterable)):
    476                 for el in args_el:
--> 477                     check_bool(el)
    478 
    479         check_bool(args)

RecursionError: maximum recursion depth exceeded in comparison
```
Could be similar to https://github.com/pymc-devs/pymc3/issues/893

**Comment by springcoil** [comment]
Anyone have any idea? @junpenglao @aseyboldt

**Comment by aseyboldt** [comment]
Hm, not really. But I don't think this is the same issue as #893, although I guess they could be related. The other one seems to be pickle complaining, this is theano itself. Is your dataset different from the radon one in some way (number of observations/parameters?)

**Comment by springcoil** [comment]
It is different as a dataset can't recall the number of parameters.

**Comment by aseyboldt** [comment]
What type does `source_idx` and its elements have? Looking at the theano code, it looks like it might end up in an infinite recursion if the index is somehow weird: https://github.com/Theano/Theano/blob/master/theano/tensor/var.py#L461

**Comment by springcoil** [comment]
I'll check tomorrow or the next day :)

**Comment by golanor** [comment]
I'm having the exact same issue. Any solution?

**Comment by twiecki** [comment]
What index are you passing in?

**Comment by golanor** [comment]
Similarly to the example - I have my own data set, and I defined the index as data.Region.values

the pandas dtype is categorical.

**Comment by golanor** [comment]
OK - I did a few experiments - this error occurs only for textual indices (i.e. if the dataframe column is categorical/object). If I replace it to ints, there is no error.

**Comment by twiecki** [comment]
OK, glad it's working. Not sure if there's anything we can do, most likely a theano thing. Moved to a different issue here: https://github.com/pymc-devs/pymc3/issues/new
