### ISSUE TITLE
Error in the GP regression example notebook

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc#2385]
FYI Cell # 36 currently prints an error in the notebook posted [here](https://pymc-devs.github.io/pymc3/notebooks/GP-introduction.html?utm_content=buffer622e3&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer):

``` python
Z = np.linspace(0, 40, 100).reshape(-1, 1)
with model:
    gp_samples = pm.gp.sample_gp(trace, y_obs, Z, samples=50, random_seed=42, progressbar=False)
```
last few lines of the output (copying from the URL above):
``` python
/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/theano/gof/fg.py in __init__(self, inputs, outputs, features, clone, update_mapping)
    178
    179         for output in outputs:
--> 180             self.__import_r__(output, reason="init")
    181         for i, output in enumerate(outputs):
    182             output.clients.append(('output', i))

/Users/fonnescj/anaconda3/envs/dev/lib/python3.6/site-packages/theano/gof/fg.py in __import_r__(self, variable, reason)
    359                 raise TypeError("Computation graph contains a NaN. " +
    360                                 variable.type.why_null)
--> 361             raise MissingInputError("Undeclared input", variable=variable)
    362         if not getattr(variable, 'fgraph', None) is self:
    363             self.__setup_r__(variable)

MissingInputError: Undeclared input
```

**Comment by fonnesbeck** [comment]
What version of PyMC3 are you using? Is this the 3.1 release or master? Other?

**Comment by amelio-vazquez-reina** [comment]
@fonnesbeck I copied the error verbatim from what's published in https://pymc-devs.github.io/pymc3/notebooks/GP-introduction.html?utm_content=buffer622e3&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer (near the bottom)

**Comment by junpenglao** [comment]
Thanks @amelio-vazquez-reina , this was reported already and fixed in #2369. Currently we are moving the doc to http://docs.pymc.io/. Sorry about the confusion!

**Comment by junpenglao** [comment]
Also, if you upgrade to master you can run the cell as it is (the related underlying error of sampling from advi.approx was also fixed)

**Comment by amelio-vazquez-reina** [comment]
Excellent! Thanks @junpenglao
