### ISSUE TITLE
Implement imputation of missing data

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#240]
At some point we are going to want to be able to do automatic imputation in PyMC 3, that is, imputing missing elements of a data array. In PyMC 2, we did this by using a Numpy masked array. The node treated the masked missing values as unknown stochastics and imputed them automatically from the distribution of the non-missing data.

**Comment by fonnesbeck** [comment]
Would a syntax like the following work?

```
some_data = [2, 5, 2, None, 6, 3]
masked_data = np.ma.masked_equal(some_data, value=None)
mu = Gamma('mu', 0.1, 0.001)
foo = Poisson('foo', mu, observed=masked_data)
```

Then, under the hood, `Distribution` would detect a masked array in `observed` and create a `Data` node for the unmasked values and a `Var` node for the masked values.

**Comment by jsalvatier** [comment]
That looks pretty good to me. Do we want to be able to easily refer to the imputed values? How should we handle that?

**Comment by fonnesbeck** [comment]
You will have access to them in the trace. In my experience, you generally don't need to access the imputed and non-missing values separately in the course of specifying a model. The main advantage to this approach is that data with missing values can be included with only a single extra line, without having to separate the missing from the non-missing data.

**Comment by twiecki** [comment]
We might want to also consider supporting missing values in pandas DataFrames (i.e. nans).

**Comment by fonnesbeck** [comment]
Yeah, that's a good idea. Should be easily done.

**Comment by jsalvatier** [comment]
That seems useful too. We might want the pandas case to be explicit since I
think nans in pandas are often going to be data errors wheras using a
masked array is going to consistently be people wanting imputed values.

**Comment by fonnesbeck** [comment]
Does anyone know how to replace values of a Theano vector in-place? I'm looking for something like:

``` python
    X = T.shared(np.array([0,1,2,3,4]))
    Y = Poisson('Y', 5, size=2)
    i = np.array([1,3])
    f = function([Y], updates=[(X[i], Y)]
```

but this does not work. I want to be able to substitute values from a PyMC variable into a data array.

**Comment by jsalvatier** [comment]
I haven't used shared variables before, but it looks like the first value
in the tuple should be the whole shared variable, and the second value
should be the new value. Perhaps you need

f = function([Y], updates=[(X, set_subtensor(X[i], Y) )]

**Comment by cmlakhan** [comment]
Has there been any resolution of this problem?  I have some missing values in a dataset and I wanted to use PyMC 3.  If not then how can I revert from PyMC 3 back to PyMC 2.  I'm not sure how to do that.

**Comment by fonnesbeck** [comment]
Support for imputing missing data automatically is not yet implemented in PyMC 3, but will be before it is released. You can still do this in PyMC 3, it is just not automatic the way it is in PyMC 2. If you want to implement your model in PyMC 2, there are a ton of examples in the wiki and in the examples folder of the 2.3 release. The syntax is pretty similar between the versions.

**Comment by stefan-pdx** [comment]
@fonnesbeck: Just checking in to see if there's been any progress on this. Can you point us in the right direction for incorporating missing data?

Thanks!

**Comment by closedLoop** [comment]
@fonnesbeck 

using your example

``` python
import numpy as np
import pymc as pm #pymc3
model_has_none = pm.Model()

with model_has_none:
    some_data = [2, 5, 2, None, 6, 3]
    masked_data = np.ma.masked_equal(some_data, value=None)
    mu = pm.Gamma('mu', 0.1, 0.001)
    foo = pm.Poisson('foo', mu, observed=masked_data)
```

I receive the following assertion error message:

`````` ---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-29-15845c65fec2> in <module>()
      5     masked_data = np.ma.masked_equal(some_data, value=None)
      6     mu = pm.Gamma('mu', 0.1, 0.001)
----> 7     foo = pm.Poisson('foo', mu, observed=masked_data)

/usr/local/lib/python2.7/dist-packages/pymc/distributions/distribution.pyc in __new__(cls, name, *args, **kwargs)
     17             data = kwargs.pop('observed', None)
     18             dist = cls.dist(*args, **kwargs)
---> 19             return model.Var(name, dist, data)
     20         elif name is None:
     21             return object.__new__(cls) #for pickle

/usr/local/lib/python2.7/dist-packages/pymc/model.pyc in Var(self, name, dist, data)
    144             self.free_RVs.append(var)
    145         else:
--> 146             var = ObservedRV(name=name, data=data, distribution=dist, model=self)
    147             self.observed_RVs.append(var)
    148         self.add_random_variable(var)

/usr/local/lib/python2.7/dist-packages/pymc/model.pyc in __init__(self, name, data, distribution, model)
    346                     for d,param in zip(args,params) ]
    347         else:
--> 348             args = [t.constant(args[0], name=name)]
    349 
    350         self.logp_elemwiset = distribution.logp(*args)

/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.pyc in constant(x, name, ndim, dtype)
    402 def constant(x, name=None, ndim=None, dtype=None):
    403     ret = constant_or_value(x, rtype=TensorConstant, name=name, ndim=ndim,
--> 404                              dtype=dtype)
    405 
    406     #We create a small cache of frequently used constant.

/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.pyc in constant_or_value(x, rtype, name, ndim, dtype)
    371             x_ = numpy.asarray(x)
    372 
--> 373     assert type(x_) in [numpy.ndarray, numpy.memmap]
    374 
    375     bcastable = [d == 1 for d in x_.shape]

AssertionError: ```

``````

**Comment by closedLoop** [comment]
I wrote a simple wrapper to generate observed and un-observed random variables to partially overcome this issue

``` python
%matplotlib inline  

import numpy as np
import random
from scipy import optimize
import pymc as pm

def enableMissingVars(fn, *args, **kwargs):
    """ example usage: enableMissingVars(pm.Normal,mu,sd, observed=masked_data))

        if kwargs contains 'observed', it assumes it is a masked array of type np.ma
        if kwargs contains 'group_missing', it will join all masked data into one random variable,
           else it creates a new variable for with name suffix equal to the index of the missing var

        returns a dictonary of random variables

    """
    if 'observed' in kwargs:
        if kwargs['observed'].mask.any():
            missing_locs  = np.where(kwargs['observed'].mask)[0]
            observed_locs  = np.where(kwargs['observed'].mask==False)[0]
        else:
            missing_locs  = []
            observed_locs =  range(len(masked_data))
    else:
        assert False, "If no observed values, pass as np.ma where all values are masked"

    if 'group_missing' in kwargs:
        if kwargs['group_missing']:
            group_missing = True
        else:
            group_missing = False
        kwargs.pop('group_missing')
    else:
        group_missing = False


    #override observed params to only have non-masked values
    kwargs['observed'] = [kwargs['observed'][i] for i in observed_locs]

    #add variable for observed data
    observed_var = fn(*args, **kwargs)

    # save it to dictionary
    all_vars = {}
    all_vars[args[0]] =observed_var #assumes the first argument in *args is the variable name parameter

    #add variables for unobserved data (requires removing 'observed' from kwargs)
    kwargs.pop('observed')
    if group_missing:
        tmp_args = list(args)
        tmp_args[0] = args[0] +'_unobserved'
        all_vars[tmp_args[0]] = fn(*tuple(tmp_args), **kwargs)
    else:
        for idx in missing_locs:
            #assumes the first argument in *args is the variable name parameter
            tmp_args = list(args)
            tmp_args[0] = args[0] +'_'+str(idx)

            all_vars[tmp_args[0]] = fn(*tuple(tmp_args), **kwargs)

    return all_vars

```

Here is a working example:

``` python
some_data = [2, 5, 2, None, 6, 3, None]
masked_data = np.ma.masked_equal(some_data, value=None)

# Define the model

model_has_none_discrete = pm.Model()
with model_has_none_discrete:
    mu = pm.Gamma('mu', 0.1, 0.001)
    all_vars = enableMissingVars(pm.Poisson,'foo', mu, observed=masked_data, group_missing = False)

# Fit the model
with model_has_none_discrete:
    # First optimize random walk
    start = pm.find_MAP(vars=model_has_none_discrete.free_RVs, 
                        fmin=optimize.fmin_l_bfgs_b)

# Define simple sampler
with model_has_none_discrete:
    # Sample
    step = pm.Metropolis()

# Sample
SAMPLE_STEPS  = 50000
SAMPLE_BURNIN = 20000

with model_has_none_discrete:
    # Sample
    trace_rw = pm.sample(SAMPLE_STEPS, step, start=start, progressbar=False, random_seed = 0)

# Visualize it
fig = pm.traceplot(trace_rw[SAMPLE_BURNIN:])

```

It outputs this image:
![image](https://cloud.githubusercontent.com/assets/2898137/4703872/1883b822-586e-11e4-84f6-24ff08e88f06.png)

**Comment by fonnesbeck** [comment]
Thanks for working on this. Its an important missing piece that I have had no time to work on. You are definitely on the right track. Ideally, we would just include this logic, probably as a wrapper, for stochastics so that masked arrays would be detected and dealt with automatically.  I will have a close look at this. Feel free to submit a pull request if you like.

BTW, you can simplify your `group_missing` check with:

```
group_missing = kwargs.get('group_missing') or False
```

**Comment by twiecki** [comment]
This looks really promising.

```
group_missing = kwargs.get('group_missing', False)
```

is also possible :)

**Comment by closedLoop** [comment]
Thank you for the comments.  I will try to put then in a pull request in the next week. 
Two known issues with my approach is that it doesn't handle array parameter for the stochastics  (easily fixed) and that it returns the the list of random variables as a dictionary and not an array / tensor.   This means it is still hard to link data with missing values.

I am getting familiar with this package but haven't spent much time learning the inner Theano workings yet.  

Do you know where is the preferred data-type of should return the variables of `enableMissingVars(*)` in?  

Ideally I would like this code to handle a situation like 

```
step1_vars = enableMissingVars(pm.Poisson,'foo', mu, observed=masked_data, group_missing = False)
step2_vars = enableMissingVars(pm.Poisson,'bar', step1_vars, observed=masked_data2, group_missing = False)
```

**Comment by fonnesbeck** [comment]
@twiecki I suddenly don't feel as clever.

**Comment by twiecki** [comment]
:neckbeard:

**Comment by jsalvatier** [comment]
I'm working on adding this finally. Its a bit tricker than I thought because of the possibility of distributions with multiple different observation arrays. For example, for a summary normal (where the data are: sample mean, N, sample sd), there are three different data arrays which can all have missing values.

**Comment by fonnesbeck** [comment]
Excellent news! Not sure about your example, though -- if your "data" are mean, N and sample sd none of these will be missing, even though some of the elements used to calculate them may have been. These are all scalar values. I'm sure I am misunderstanding.

**Comment by jsalvatier** [comment]
Ah, I meant if you're modeling the summary directly, for example, if all you have as data is the means, Ns, sds for a bunch of different samples rather than the lower level data and some of those values are missing. Make more sense?

**Comment by jsalvatier** [comment]
Okay, I have a rough draft here: https://github.com/pymc-devs/pymc3/commit/ae610ae5e906c5697577b8b9504cdc0ff176b00e 

I need to clean it up and think about it a bit more, but it seems to work with the disasters model with missing data.

**Comment by jsalvatier** [comment]
Interesting, the missing data version of disasters is about 5x slower than the non-missing data version. Is that similar to previous performance difference?

**Comment by fonnesbeck** [comment]
The only additional overhead should be related to the proposals for the missing elements. The likelihoods still have to be evaluated in missing and non-missing cases.

**Comment by jsalvatier** [comment]
Based on my profiling it looks like with `set_subtensor`, theano is going through a partially python code path, which is odd. 

https://groups.google.com/forum/#!topic/theano-users/2YBzWCyM5Oc

I'll explore why.

**Comment by jsalvatier** [comment]
Figured it out. `gammaln` was claiming not to have a c implementation for integer types, but it does, so I just removed that check. More details in that email thread. No speed difference now.
