### ISSUE TITLE
Implement enhanced plotting

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#242]
We probably want a more robust set of plotting functions. For example, multiple plots should be paginated to keep them readable, and publication-quality figures should be automatically saved to disk as well as displayed on-screen. We should be able to borrow heavily from PyMC 2 here. Additional plotting functions should include:
- autocorrelation plots
- goodness-of-fit plots
- forest plots
- convergence diagnostic plots

**Comment by fonnesbeck** [comment]
Also, plotting a multivariate chain currently plots all elements on the same axes, without a legend, which makes them hard to read. Each series should have its own subplot.

**Comment by dmarx** [comment]
@fonnesbeck I think that's a good idea, but there will definitely be cases where people will want them on the same plot. I suggest making whether to produce multiple plots or a single plot a parameter, with the default being a single plot (to prevent users from accidentally creating thousands of plots if they forget to pass in a parameter).

**Comment by twiecki** [comment]
I think we have those plot methods now.
