### ISSUE TITLE
[Feature request] joy plot for vectorized RVs

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2421]
e.g., https://twitter.com/mikedecr/status/886376620004700160

which is already available in seaborn.

**Comment by aseyboldt** [comment]
I've also used horizontal violinplots for this. Not sure which one people would prefer.

**Comment by ferrine** [comment]
We can have both

**Comment by ferrine** [comment]
one more good plot to have
https://twitter.com/mikedecr/status/885227821941096448

**Comment by fonnesbeck** [comment]
[strip plots](http://seaborn.pydata.org/examples/jitter_stripplot.html) would be a good alternative too.

**Comment by junpenglao** [comment]
The thing I like the most of https://twitter.com/mikedecr/status/886376620004700160 is we can see multiple chains easily.

**Comment by fonnesbeck** [comment]
The overlapping could get pretty hairy with a lot of parameters.

**Comment by junpenglao** [comment]
FYI https://github.com/sbebo/joypy

**Comment by fonnesbeck** [comment]
The example on their README is a perfect example of why I dont care for these trendy plots. It hides much of the data. There are far better ways to display multiple distributions than this.

**Comment by junpenglao** [comment]
Completely agree. Now think about it the only attractive use case is displaying the random intercept in a mixed model…

**Comment by springcoil** [comment]
I vote to close this issue.

**Comment by fonnesbeck** [comment]
Seconded
