### ISSUE TITLE
The 95% interval of PyMC3 trace doesn’t cove the real values

### ISSUE THREAD

**Issue by nikzadb** [pymc-devs/pymc#2422]
Well I have a question about how the final trace in PyMC3 works (another application). I used `hpd()` function to find 95% interval but almost all true values are outside of this interval. What that means? how can I improve the results?

<img width="682" alt="screen shot 2017-07-17 at 12 06 47 pm" src="https://user-images.githubusercontent.com/1559636/28255800-f3a53a5c-6afe-11e7-8036-7643b329cec5.png">

Before running the model, I standardized all columns and then reversed to the original sale (using scikit-learn MinMaxScaler)

bd = trace[-1000:]['y_est']
predictions = pd.DataFrame()
predictions['pred'] = bd.mean(axis=0)
predictions = predictions[~predictions.pred.isnull()]
predictions['y'] = new_data.y
predictions['residual'] = predictions.pred - predictions.y

bd_hpd = pm3.hpd(bd)

predictions['prctile_95'] = bd_hpd[:, 1]
predictions['prctile_5'] = bd_hpd[:,0]

**Comment by junpenglao** [comment]
@nikzadb Replied on Discourse.
