### ISSUE TITLE
Estimating non-stochastic (or fixed) parameters

### ISSUE THREAD

**Issue by kpei** [pymc-devs/pymc#2424]
Let's say I have a regression model with large number of covariates e.g 100.  I want to construct a hierarchical model where there are let's say 50 categories.  That's 50x100 total covariates to sample from if I were to apply a prob dist on all of them.  Within the covariates, I'm actually only interested in sampling the posterior of one or two coefficients.  Is there anyway in PyMC to be able to fix certain parameters/coefficients (but still give a decent estimate for them via e.g ADVI or MAP) and sample only the stochastic ones?

**Comment by junpenglao** [comment]
Hi @kpei, for the general question of the usage of PyMC3 please go to https://discourse.pymc.io/. I will close this for now. Thanks!
