### ISSUE TITLE
Implementing Nearest-Neighbor Gaussian Processes

### ISSUE THREAD

**Issue by aasensio** [pymc-devs/pymc#2428]
Hi,
 I would like to contribute by implementing an approximate Gaussian Process using a very smart (and approximate) inversion of the covariance matrix (see [https://arxiv.org/abs/1705.07265](https://arxiv.org/abs/1705.07265) for details). I have already implemented these routines in Theano and it should be pretty straightforward to add them to pymc3 ([example](https://gist.github.com/aasensio/f56a765d2e184a4e50027504dd9bc3df)). The difference lies in how the inverse of the covariance matrix and its log-determinant are calculated, which is done by solving many small linear systems. So, in essence, we would need changes in the GP and MvNormal classes. Any idea of how to do that not very invasively? I was thinking of adding a `n_neighbors` parameter to GP, and then modify MvNormal to accept this parameter as an optional input. Does this make sense to you?

**Comment by junpenglao** [comment]
@bwengals is doing some work on extending GP see https://github.com/pymc-devs/pymc3/pull/2322, which includes some approximation of GPs (currently he implemented FITC and VFE). You can have a look at that PR to see if the Nearest Neighbors approximation could be fit into the current framework easily.
also cc @aseyboldt

**Comment by aseyboldt** [comment]
This sounds very interesting.
I'm not sure modifying MvNormal is the way to go however. It is complicated enough as it is, and adding an approximation to it that makes sense in only a very specific subset of applications to it would be a bit confusing. How about adding an `MvNormalNeighbor` or something like that? It wouldn't need to support covariance, cholesky and precision matrix parametrizations either, right?

**Comment by aasensio** [comment]
That's a possibility. The only thing that makes me uncomfortable defining a new `MvNormalNeighbor` or whatever is that this approximation is only interesting for GP. Only in GPs, where the covariance matrix is obtained through a covariance function, you can define what is a neighbor or not. Then, it makes sense to keep this isolated on the GP class. However, the NNGP approximation directly approximate the inverse of the covariance matrix and its determinant, so the current implementation in terms of `MvNormal` is not appropriate for this approximation. A possibility would be to add in `MvNormal`the possibility of passing the inverse of the covariance matrix. This can be an extra option, that adds to the current ones (covariance and also Cholesky decomposition of the covariance). Does this make sense?

**Comment by aseyboldt** [comment]
`MvNormal` already supports the inverse of the covariance (the `tau` argument).
But it will still factor it to get to the logdet and to transform the variables, so that probably isn't what we want, right?
We could keep `MvNormalNeighbor` private in the gp module. I haven't read the whole paper yet, but couldn't this also be used in other circumstances when you have a metric on the dimensions of a covariance?

**Comment by aasensio** [comment]
I agree that keeping `MvNormalNeighbor`private looks like a good idea. It's true that you can use this approximation to invert any covariance matrix in which you can define a metric on the variables. So, perhaps the best idea would be to keep `MvNormalNeighbor`private and only upgrade it to be more visible when we find more use cases. I'll work on it during these days when I have some time.

**Comment by aseyboldt** [comment]
Sounds good, thanks.

**Comment by bwengals** [comment]
This sounds very cool!  I think it would be a really nice addition.  The #2322 PR the GP classes all have three methods defined: `prior`, `conditional` and `logp`.  `logp` is already in your gist, and would be the only method needed to try NNGP out in PyMC3 with ADVI, NUTS and all that good stuff.  

Then, `conditional` gives the predictive mean and covariance.  `conditional` and `prior` are used by `sample_gp` to draw from the posterior (or prior), so you could implement them second.  

Also, take a look at [GPSparseConjugate](https://github.com/bwengals/pymc3/blob/5b6941f37b77f2a825425b837c5842b4f5f26a5e/pymc3/gp/gp.py#L271).  It was too difficult to shoehorn it to use `MvNormal`, so don't feel like you need to.

**Comment by aasensio** [comment]
I think it's better if I wait until your PR is merged and then I'll PR the NNGP part. Agree, @bwengals?

**Comment by bwengals** [comment]
Only if you would prefer to wait.  IMO it would be great to get your work up in a WIP PR, and then we can deal with how to merge, and how to get your work into the planned `GP` api later.

**Comment by aasensio** [comment]
I have a first working version with the new GP API. So I will wait until this API is merged.

**Comment by bwengals** [comment]
oh that's awesome!  looking forward to it

**Comment by bwengals** [comment]
@aasensio want to let you know that the gp code was merged yesterday.  Still interested in submitting a pr?

**Comment by aasensio** [comment]
Yes, I've following the PR. I still have to fully understand your code and adapt what I did one month ago. I will start working on this soon.

**Comment by bwengals** [comment]
Awesome, looking forward to it
