### ISSUE TITLE
Issue sampling PPC from multinomial likelihood

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#2430]
Hi guys!

I'm having an issue sampling PPC from a multinomial likelihood. Error returned is:

```python
ValueError: object too deep for desired array
```

An example notebook showing this error is here: https://github.com/ericmjl/bayesian-analysis-recipes/blob/master/cover-type.ipynb

For a bit of background, this is just a notebook in which I'm testing the use of PyMC3 for multi-class classification.

I'm not sure if I've implemented the model correctly, so if it's a model issue, I'm happy for this issue to be closed.

Please let me know if more detail is needed - it's after work hours right now, so my brain is a bit fried, and I might have left stuff out.

**Comment by junpenglao** [comment]
Thanks for reporting @ericmjl, it seems that numpy multinomial random do not accept 2D shape:
```python
n=1
p=np.asarray([[.25,.25,.25,.25],[.25,.25,.25,.25]])
np.random.multinomial(n, p, size=None)

Traceback (most recent call last):

  File "<ipython-input-46-e0f50223dacc>", line 3, in <module>
    np.random.multinomial(n, p, size=None)

  File "mtrand.pyx", line 4613, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:37731)

ValueError: object too deep for desired array
```

Also, looking at the trace it is clear that Metropolis is mixing very poorly here (high dimension problem), I tried with NUTS but quickly ran into Bad energy problem. I think in your case the predictor matrix is ill-conditioned, it will work much better if you normalised `X`:
```python
from sklearn.preprocessing import normalize
X1 = normalize(X, axis=1)
```
You can then just call `trace = pm.sample(1000, n_init=500000)` (I used more `n_init` as ADVI was not converging)
![image](https://user-images.githubusercontent.com/12952641/28365911-c0284286-6c8a-11e7-945f-6629a0f89acc.png)

**Comment by junpenglao** [comment]
OK it should be fixed by the above PR, also see the gist below:
https://gist.github.com/junpenglao/0a32ac2b87aa81d59551c7d5ddc54859

**Comment by ericmjl** [comment]
Thanks a ton, @junpenglao! Is your bug fix going to be merged into PyMC3's `master`? (I don't conda-install PyMC3, I have a development setup to track the latest and greatest coming out of the team :smile:) 

For the time being, I've patched my local dev install. 

Btw, how did you figure out what had to be done?

**Comment by junpenglao** [comment]
So my thought process is:
1, try NUTS, get Bad energy error
2, check logp of model and RVs (see cell 11), there is no NaN
3, check test_value of RVs, mostly zeros (default value for Normal, no surprise there)
4, change test_value of RVs and check logps again (see cell 10), got -inf and NaN model logp.
5, go back to check the design matrix, it is highly imbalance (large value in the first few columns and many zeros), likely an ill-condition matrix.
6, normalized design matrix, and rerun model
7, it works ;-)

**Comment by ericmjl** [comment]
@junpenglao will this fix get put into PyMC3's master? If you're overwhelmed, I'm happy to take on putting in the PR, and working with the rest of the team to get the appropriate tests in.

**Comment by junpenglao** [comment]
@ericmjl yes it will be merged into master soon - I am still trying to fix the last little bit ;-)

**Comment by ericmjl** [comment]
Are you noticing a small problem where sometimes `sum(pvals[:-1]) > 1`? I've noticed this issue myself.

**Comment by junpenglao** [comment]
You mean in the posterior? that seems to be a bug.

**Comment by ericmjl** [comment]
@junpenglao yes. There's a hack I've had to use to make sure the probabilities are valid for `numpy`:

```python
p = p / (p.sum(axis=1, keepdims=True)+1E-6)
```

Basically adding a small error term of 1E-6. It's not a good hack, I don't like it, but it's made multinomial sampling errors go away. I think there might be something deeper, like a precision error, that's making the `pvals` sum to greater than one.
