### ISSUE TITLE
Problems with applying replacements

### ISSUE THREAD

**Issue by agarbuno** [pymc-devs/pymc#2435]
I am new to pymc3 and theano. I was going through the pymc3 tutorials and I am currently stuck in the iris example. When I try to run 
```{python}
test_ok = tt.eq(test_probs.argmax(-1), y_test)
```
I get the following error value 
```{python}
Input dimension mis-match. (input[0].shape[1] = 112, input[1].shape[1] = 38)
```
which I assume is something related to theano's shared variables. That is, because the training data has 112 points and the test data 38. I have followed the tutorial to do the point. Any ideas on this?

**Comment by junpenglao** [comment]
I think this might be break by recent update - the `test_probs` has the right shape when evaluted tho.

**Comment by ferrine** [comment]
This is for sure one of the most annoing problems. Theano test_values. There are problems when they are passed through theano.clone. I think this can break because I considered not to use test values in VI module as I got another problems with implementation. I don't know the correct solution as I get problems in both cases.

**Comment by ferrine** [comment]
Work around is to set theano.config.compute_test_value = 'off' there

**Comment by ferrine** [comment]
I should think over my approach to eliminate the problem. This can be done in my new refactoring to support grouped approximations.

**Comment by junpenglao** [comment]
Is there a way to reset the test_value when we apply `apply_replacements` and `more_replacements`? That could be a solution.

**Comment by ferrine** [comment]
What do you mean? I can't change test value in general case to the correct one:( that is exactly what I do in one helper function.

**Comment by junpenglao** [comment]
> This is for sure one of the most annoing problems. Theano test_values. There are problems when they are passed through theano.clone. 

According to your comment above, I am wondering if there is a way to passed new test_value or reset the test_value when we use theano.clone

**Comment by ferrine** [comment]
In the last cell `(11, 11), (11, 11)` was expected
![image](https://user-images.githubusercontent.com/11705326/28454417-dcea5c4a-6e03-11e7-9d30-ca176193a26a.png)

**Comment by ferrine** [comment]
This bug is the reason why I don't use test_values in VI code. CC @nouiz

**Comment by agarbuno** [comment]
Great! setting theano.config.compute_test_value = 'off' allows me to run the code above 👍

**Comment by junpenglao** [comment]
But setting `theano.config.compute_test_value = 'off'` is not consistent with the default setting in PyMC3 right? I think we should think of a general solution to this. 
Also, for building model it is better to have test value for checking the implementation. It is reasonable to have test value as raise or warn as default.

@ferrine are you partly addressing it in https://github.com/pymc-devs/pymc3/pull/2402

**Comment by ferrine** [comment]
Yes. There is no clear solution. BTW it is more theano related issue, we would rather mention it in theano guide.

**Comment by junpenglao** [comment]
Yes that would be fine as well, as long as we are aware of it and give clear instructions to users in different use case.

We should:
1, add this information to our theano guide,
2, add it to apply_replacement docsting,
3, add it to VI quick start guide.

**Comment by AdrianLsk** [comment]
You can set `compute_test_value` in model's `theano_config` argument like

```
with pm.Model(theano_config={'compute_test_value': 'off'}) as model:
  ...
```
Since setting it to `off` causes a theano error
```
AttributeError: 'scratchpad' object has no attribute 'test_value'
```
you can only set it to `ignore`,  which might work fine for other use cases, but unfortunately still gives the error with shapes here.

**Comment by nouiz** [comment]
Can you give the full stack trace for the error you just pasted?
