### ISSUE TITLE
GP-introduction notebook yields poor estimates

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2436]
Running the GP-introduction notebook under current master results in very poor estimates for the second example, which uses full-rank ADVI:

![unknown](https://user-images.githubusercontent.com/81476/28434193-18a09296-6d54-11e7-99d6-d00c329bb113.png)

Not sure if this is due to changes in either the GP code or the VI, but it used to yield reasonable results.

**Comment by fonnesbeck** [comment]
BTW, this notebook has some bizarre priors:

    l_per = pm.Uniform('l_per', lower=1e-5, upper=10)

What's the thinking here?

**Comment by bwengals** [comment]
RE the priors, just me being a noob.   Those estimates are bad..  Definitely a new gp intro will be part of #2322.  Since this is up, i'll update before then

**Comment by bwengals** [comment]
Closing since this example isnt in the notebooks anymore
