### ISSUE TITLE
Variational Inference: Full-Rank versus Mean-Field

### ISSUE THREAD

**Issue by gcgibson** [pymc-devs/pymc#2438]
I know this isn't right for an issue but I didn't know where else to bring it up. Has there been any work done on Full-Rank ADVI? I assume MF is what is currently implemented? Would that be possible/easy to do?

For reference: 
https://arxiv.org/pdf/1603.00788.pdf

**Comment by gcgibson** [comment]
should have read the history ...sorry!

**Comment by junpenglao** [comment]
FYI, we also has a discourse forum for general discussion and questions: https://discourse.pymc.io/
