### ISSUE TITLE
Can't create a Constant with float dtype

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2451]
The pymc3.Constant distribution advertises itself as accepting both `int` and `float` values ([discrete.py#L553](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/discrete.py#L553)).

However the `Discrete` distribution base class enforces integer dtypes ([distribution.py#L129](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/distribution.py#L129))

This code sample also shows that while `theano.tensor.as_tensor_variable` correctly creates a float type tensor, the `Constant` distribution does not:

```python
import pymc3
import theano.tensor

with pymc3.Model() as pmodel:
    d = pymc3.Constant("k1", c=42.3)
    print(d.dtype)
    # >>> int64

t = theano.tensor.as_tensor_variable(42.3)
print(t.dtype)
# >>> float64
```

**Comment by fonnesbeck** [comment]
I think we can just make this subclass `Continuous`. Can anyone think of why they would *need* a constant variable that is integer-typed?

**Comment by twiecki** [comment]
@michaelosthege What do you need `Constant` for? You can just do `pm.Deterministic(' k1', c=42.3)`.

**Comment by michaelosthege** [comment]
@fonnesbeck sounds reasonable - and the only reason I could think of would be using the constant as an integer for slicing or iteration. But then one could provide the dtype as a kwarg.

@twiecki `pymc3.Deterministic` expects `var` as a theano variable and does not have all the attributes of a `Distribution`. I treat initial conditions to a dynamic system as priors that may be `Constant` in some situations.

**Comment by junpenglao** [comment]
Interesting. Point prior is quite common in the classical inference of GMM as well, but I never see anyone attempt to fit one using this formulation in PyMC3.
