### ISSUE TITLE
WAIC/LOO only consider last chain in a Multitrace

### ISSUE THREAD

**Issue by AustinRochford** [pymc-devs/pymc#2457]
See [this gist](https://gist.github.com/AustinRochford/b2287e7e50544f60e8ac811d01dc2ce0) for a demonstration.  Of course, the WAIC values across difference chains should not be _too different_, if the sampling has been effective.  This may also affect other stat functions, I haven't checked yet.

@aseyboldt thoughts on what the correct behavior should be here?

**Comment by aseyboldt** [comment]
Hm. Intuitively I'd say we should probably merge the logp values from the traces, excluding tuning samles. It would be strange to use only one chain. That would though out a lot of data and the choice would be completely arbitrary.
So maybe check `hasattr(trace, 'stat_names') and 'tune' in trace.stat_names` or so and then filter out tuning samples.

**Comment by junpenglao** [comment]
Looks like a bug, we should just combine the traces when njobs>1.

**Comment by AustinRochford** [comment]
Hmm, I think the simplest solution here is, when iterating over a multi trace, to iterate over all chains, not just the last chain, as is currently done.

**Comment by junpenglao** [comment]
Is that how https://github.com/stan-dev/loo compute the loo/waic? Is it better to just combine all the traces together?
