### ISSUE TITLE
Discuss: PR to fix multinomial precision issues

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#2469]
Hi team,

I've been experiencing a multinomial sampling problem, first described [here][mn1], and then surfacing again [here]. The issue that I get is that the `pvals` sum to greater than 1 with float32 precision.

[mn1]: https://github.com/pymc-devs/pymc3/issues/2430
[mn2]: https://github.com/pymc-devs/pymc3/issues/2448#issuecomment-318644294

As I've dug around, I found that the issue is a floating point precision issue in `numpy`'s multinomial. Internally, it casts everything to `float64`. Issue is discussed [on this issue on the `numpy` repository][numpy]. 

[numpy]: https://github.com/numpy/numpy/issues/8317

I'm thinking of submitting a **very** small PR that builds upon @junpenglao's [previous PR][junpeng] on `distributions/multinomial.py`.

[junpeng]: https://github.com/pymc-devs/pymc3/pull/2432

```python
def _random(self, n, p, size=None):
    # Set float type to float64 for numpy.
    p = p.astype('float64')
    # Now, re-normalize all of the values in float64 precision.
    p = p / (p.sum(axis=1, keepdims=True))
    if size == p.shape:
       ...
```

I have done one test using the same [notebook][nb] in which I first discovered the problem, and now they go away. From an empirical standpoint, the performance of the multinomial classification model is identical to when I had the `+ 1E6` hack [previously described][mn1]. 

[nb]: https://github.com/ericmjl/bayesian-analysis-recipes/blob/master/multiclass-logistic-regression-cover-type.ipynb

I wanted to pitch this first here to see if there's something I'm missing, before taking the time to put in the PR - or should I put in the PR first and solicit code review?

**Comment by junpenglao** [comment]
Thanks for the digging @ericmjl! I would say you can just go ahead and submit a PR, we can also see if any test failed on Travis.

**Comment by ColCarroll** [comment]
I've been trying to implement multinomial naive bayes, and keep running into trouble with `Multinomial` as well -- would love to help out/see if your fix also fixes my woes!

**Comment by kyleabeauchamp** [comment]
Seems reasonable if the tests pass.

**Comment by ericmjl** [comment]
Yay, all tests are passing!!!
