### ISSUE TITLE
Handle warnings better in stats.py

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2472]
Looks like there's a manual filter of warnings [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/stats.py#L400) which should probably be removed and handled with `captureWarnings`.

**Comment by datapythonista** [comment]
The link in the ticket doesn't go to the warning anymore (the file changed).

This was the warning when the ticket was created:
https://github.com/pymc-devs/pymc3/blob/4d5997a8b7497a1436463543a2aa24e25566c942/pymc3/stats.py#L400

This is the warning at the time of writing this comment:
https://github.com/pymc-devs/pymc3/blob/master/pymc3/stats.py#L446

Documentation about `captureWarnings` is available here: https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module

**Comment by sharanry** [comment]
Hey, can I take this up?

**Comment by springcoil** [comment]
Feel free to

**Comment by junpenglao** [comment]
@sharanry We will update the warning system following #2677, please dont work on it yet.

**Comment by aloctavodia** [comment]
This was solved by #2824
