### ISSUE TITLE
scipy.optimize.nnls usage problem in pymc3 

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#2474]
Hello everyone,

I am trying to implement a graphical modelling in pymc3 and I probabilistically generate a matrix and a vector. I need to find a third vector which provides A*x=b equality where x has nonnegative elements.  So, I have tried to use scipy.optimize.nnls() function but due to the pm.Model structure, my A and x matrices have zero shapes. The given sample script below provides 'ValueError: expected matrix' error since 'mat' matrix is empty. Does anyone have a solution for this problem?
```python
with Normal_model:
    mu = pm.Uniform('mu', lower=-10, upper=10, shape=5)
    sigma = pm.Uniform('sigma', lower=0, upper=10, shape=2)
    mat = pm.Normal('matrix', mu=mu[0], sd=sigma[0], shape=(5,2))
    t = pm.Deterministic('parametre', optimize.nnls(mat, mu))
    for i in range(0,2):
        data = pm.Normal('data_%i'%i, mu=mu[i], sd=sigma[i], observed=s[i, :])
    start = pm.find_MAP()
    step = pm.Metropolis()
    trace = pm.sample(10000, step, start=start, progressbar=True)
```

**Comment by junpenglao** [comment]
Hi @sezen, could you please move the question to our discourse https://discourse.pymc.io/? The answers there are better organized and searchable.

I will close this for now.
