### ISSUE TITLE
Fix docs in model comparison docs

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#2476]
Docs have dead links for images

https://pymc-devs.github.io/pymc3/notebooks/model_comparison.html#Pooled-model

![image](https://user-images.githubusercontent.com/1900459/28980286-194b0532-7902-11e7-81fa-b3e24109d1f5.png)

**Comment by junpenglao** [comment]
This docs render correctly on http://docs.pymc.io/en/latest/ - what is the plan for moving to the new doc site? @twiecki

**Comment by twiecki** [comment]
We probably just need a github redirect: https://help.github.com/articles/redirects-on-github-pages/

**Comment by springcoil** [comment]
Is this still open?
