### ISSUE TITLE
TypeError: object of type 'TensorVariable' has no len()

### ISSUE THREAD

**Issue by jolespin** [pymc-devs/pymc#2483]
I'm getting an error when I'm trying to sample from my posterior. 
```
import pymc3 as pm

clusters=2
with pm.Model() as model:
    p = pm.Dirichlet('p', a=np.ones(clusters))

    means = pm.Normal('means', mu=[0,1], sd=2, shape=clusters)
    sd = pm.HalfCauchy('sd', 5)
    
    y = pm.NormalMixture('y', w=p, mu=means, sd=sd, observed=u)
    
    step = pm.Metropolis()
    trace = pm.sample(5000, [step], progressbar=True)
pm.traceplot(trace)

# Evaluate
burn = 500
trace_ = trace[burn:]
pm.df_summary(trace, varnames=["means","sd","p"])

ppc = pm.sample_ppc(trace_, samples=500, model=model, size=100)
```
The traceback error below is something in the theano backend
```
TypeError                                 Traceback (most recent call last)
<ipython-input-94-db8db3666fae> in <module>()
----> 1 ppc = pm.sample_ppc(trace_, samples=500, model=model, size=100)
      2 # fig, ax =  plt.subplots()
      3 # for sample in ppc["y"]:
      4 #     sns.kdeplot(sample, alpha=0.1, color="teal", ax=ax)
      5 # sns.kdeplot(u, color="black", ax=ax)

~/anaconda/lib/python3.6/site-packages/pymc3/sampling.py in sample_ppc(trace, samples, model, vars, size, random_seed, progressbar)
    526         for var in vars:
    527             ppc[var.name].append(var.distribution.random(point=param,
--> 528                                                          size=size))
    529 
    530     return {k: np.asarray(v) for k, v in ppc.items()}

~/anaconda/lib/python3.6/site-packages/pymc3/distributions/mixture.py in random(self, point, size, repeat)
    124                 return np.random.choice(k, p=w, *args, **kwargs)
    125 
--> 126         w = draw_values([self.w], point=point)
    127 
    128         w_samples = generate_samples(random_choice,

~/anaconda/lib/python3.6/site-packages/pymc3/distributions/distribution.py in draw_values(params, point)
    183                 if not isinstance(node, (tt.sharedvar.TensorSharedVariable,
    184                                          tt.TensorConstant)):
--> 185                     givens[name] = (node, draw_value(node, point=point))
    186     values = [None for _ in params]
    187     for i, param in enumerate(params):

~/anaconda/lib/python3.6/site-packages/pymc3/distributions/distribution.py in draw_value(param, point, givens)
    251         except:
    252             shape = param.shape
--> 253         if len(shape) == 0 and len(value) == 1:
    254             value = value[0]
    255     return value

TypeError: object of type 'TensorVariable' has no len()
```

Here are my version: 
```
import pymc3 as pm
import theano
pm.__version__, theano.__version_
('3.1rc3', '0.9.0')_
```

**Comment by aseyboldt** [comment]
That error was left over from refactoring `draw_value`, but I think we fixed it before the 3.1 release. You are still on a release candidate. Can you update to 3.1 and try again?
```
pip install --upgrade pymc3
```
Should do it if you are using pip.

On August 7, 2017 9:45:47 PM CEST, "Josh L. Espinoza" <notifications@github.com> wrote:
>I'm getting an error when I'm trying to sample from my posterior. 
>```
>import pymc3 as pm
>
>clusters=2
>with pm.Model() as model:
>    p = pm.Dirichlet('p', a=np.ones(clusters))
>
>    means = pm.Normal('means', mu=[0,1], sd=2, shape=clusters)
>    sd = pm.HalfCauchy('sd', 5)
>    
>    y = pm.NormalMixture('y', w=p, mu=means, sd=sd, observed=u)
>    
>    step = pm.Metropolis()
>    trace = pm.sample(5000, [step], progressbar=True)
>pm.traceplot(trace)
>
># Evaluate
>burn = 500
>trace_ = trace[burn:]
>pm.df_summary(trace, varnames=["means","sd","p"])
>
>ppc = pm.sample_ppc(trace_, samples=500, model=model, size=100)
>
>TypeError                                 Traceback (most recent call
>last)
><ipython-input-94-db8db3666fae> in <module>()
>----> 1 ppc = pm.sample_ppc(trace_, samples=500, model=model, size=100)
>      2 # fig, ax =  plt.subplots()
>      3 # for sample in ppc["y"]:
>      4 #     sns.kdeplot(sample, alpha=0.1, color="teal", ax=ax)
>      5 # sns.kdeplot(u, color="black", ax=ax)
>
>~/anaconda/lib/python3.6/site-packages/pymc3/sampling.py in
>sample_ppc(trace, samples, model, vars, size, random_seed, progressbar)
>    526         for var in vars:
>527            
>ppc[var.name].append(var.distribution.random(point=param,
>--> 528                                                         
>size=size))
>    529 
>    530     return {k: np.asarray(v) for k, v in ppc.items()}
>
>~/anaconda/lib/python3.6/site-packages/pymc3/distributions/mixture.py
>in random(self, point, size, repeat)
>   124                 return np.random.choice(k, p=w, *args, **kwargs)
>    125 
>--> 126         w = draw_values([self.w], point=point)
>    127 
>    128         w_samples = generate_samples(random_choice,
>
>~/anaconda/lib/python3.6/site-packages/pymc3/distributions/distribution.py
>in draw_values(params, point)
>183                 if not isinstance(node,
>(tt.sharedvar.TensorSharedVariable,
>    184                                          tt.TensorConstant)):
>--> 185                     givens[name] = (node, draw_value(node,
>point=point))
>    186     values = [None for _ in params]
>    187     for i, param in enumerate(params):
>
>~/anaconda/lib/python3.6/site-packages/pymc3/distributions/distribution.py
>in draw_value(param, point, givens)
>    251         except:
>    252             shape = param.shape
>--> 253         if len(shape) == 0 and len(value) == 1:
>    254             value = value[0]
>    255     return value
>
>TypeError: object of type 'TensorVariable' has no len()
>```
>
>Here are my version: 
>```
>import pymc3 as pm
>import theano
>pm.__version__, theano.__version_
>('3.1rc3', '0.9.0')_
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pymc-devs/pymc3/issues/2483

-Adrian

**Comment by bryanbocao** [comment]
Followed the instructions on [NVIDIA](https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork)
Installation Instructions:
```
sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda
```

Got
```
sudo apt-get install cuda
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cuda : Depends: cuda-11-2 (>= 11.2.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by bryanbocao** [comment]
After [removing cuda*](https://medium.com/@exesse/cuda-10-1-installation-on-ubuntu-18-04-lts-d04f89287130)
```
sudo rm /etc/apt/sources.list.d/cuda*
sudo apt remove --autoremove nvidia-cuda-toolkit
sudo apt remove --autoremove nvidia-*
```
and
```
sudo dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda
```
again, got
```
nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```
