### ISSUE TITLE
Problem with sample_node and more_replacements

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2496]
```
X = theano.shared(np.array([1., 2., 3.]))
with pm.Model() as model:
    x = pm.Normal('x', mu=0, sd=1)
    n = pm.Normal('n', mu=X*x, sd=1, observed=np.array([1, 2, 3]))
    
    mean_field = pm.fit(method='advi', n=50000, 
                        callbacks=[pm.callbacks.CheckParametersConvergence(diff='relative')])
    
    out_sample = mean_field.sample_node(n, size=100, more_replacements={X: np.random.randn(1000)})
```

I expect `out_sample.eval().shape` to provide shape `(100, 1000)`, but it has shape `(100, 3)`. It seems like the replacement is not correctly applied. This is on pymc3 master.

**Comment by junpenglao** [comment]
The same problem is discussed here: https://github.com/pymc-devs/pymc3/issues/2435 i think

**Comment by twiecki** [comment]
In addition, it seems like `sample_node()` just returns the exact same value for every sample, thus, uncertainty is not taken into account.

**Comment by ferrine** [comment]
@twiecki Your example is a bit wrong, you are sampling the observed

**Comment by twiecki** [comment]
@ferrine Hm, I guess I need to sample the input to the observed?

**Comment by ferrine** [comment]
And add sigma with white noise

**Comment by twiecki** [comment]
That seems to work correctly. But it's a bit confusing as `sample_ppc` samples from the observed.

**Comment by DeliciousHair** [comment]
I know this is old, but I'm running into the same problem and the conversation above is not giving me any clues.

As an example, if I try to replicate the results in [your blog post](http://twiecki.github.io/blog/2016/06/01/bayesian-deep-learning/), I keep hitting this wall here:

```
with pm.Model() as logistic_regression:
    inputs = pm.Normal('inputs', mu=X, sd=X_unc, shape=X.shape)
    coeffs = pm.Normal('beta', mu=0, sd=1, shape=2)
    
    linear = pm.math.dot(inputs, coeffs)
    prob = pm.math.sigmoid(linear)
    obs = pm.Bernoulli('obs', p=prob, observed=Y)
    
    # Run ADVI which returns posterior means, standard deviations, and the evidence lower bound (ELBO)
    mean_field = pm.fit(method='advi', n=50000,
                        callbacks=[pm.callbacks.CheckParametersConvergence(diff='relative')])
    
    out_sample = (mean_field.sample_node(prob, size=100, more_replacements={inputs: grid_2d}) > .5)
```
due to the fact that `out_sample.eval()` has shape `(100, 100)`. Not sure what to make of this...

**Comment by ferrine** [comment]
Hi! I've replicated your issue in a test suit, going to fix soon
