### ISSUE TITLE
pm.compare Error: could not broadcast input array from shape (...) into shape (...)

### ISSUE THREAD

**Issue by jonathanng** [pymc-devs/pymc#2503]
```
pm.compare(
    traces = (trace_A,),
    models = (model_A,),
)

pm.compare(
    traces = (trace_B,),
    models = (model_B,),
)

pm.compare(
    traces = (trace_A, trace_B),
    models = (model_A, model_B),
)
```

In the above code, the first 2 calls work fine. But when it gets to the third call, I get the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-a6395f8f9f8c> in <module>()
     14     traces = (trace_A, trace_B),
     15     models = (model_A, model_B),
---> 16     ic     = 'WAIC'
     17 )

~/anaconda/lib/python3.6/site-packages/pymc3/stats.py in compare(traces, models, ic, bootstrap, b_samples, alpha, seed)
    431         ic_i = np.zeros((len(ics), N))
    432         for i in range(len(ics)):
--> 433             ic_i[i] = ics[i][1][3] * N
    434 
    435         b_weighting = dirichlet.rvs(alpha=[alpha] * N, size=b_samples,

ValueError: could not broadcast input array from shape (356) into shape (3560)

> /Users/jonathanng/anaconda/lib/python3.6/site-packages/pymc3/stats.py(433)compare()
    431         ic_i = np.zeros((len(ics), N))
    432         for i in range(len(ics)):
--> 433             ic_i[i] = ics[i][1][3] * N
    434 
    435         b_weighting = dirichlet.rvs(alpha=[alpha] * N, size=b_samples,```

**Comment by junpenglao** [comment]
Could you please provide a reproducible example?

**Comment by aloctavodia** [comment]
I guess the length of `trace_A` and `trace_B` is not the same, right?

**Comment by aloctavodia** [comment]
humm, sorry I think the number of observations is not the same for both models. You should have the same number of observations.

**Comment by jonathanng** [comment]
```
>>> len(trace_A) == len(trace_B)
True
```

> humm, sorry I think the number of observations is not the same for both models. You should have the same number of observations.

`observed` is the same for both models. Shape and data.

> Could you please provide a reproducible example?

@junpenglao, what is the best way to provide an example if I have a csv with data? In another repository?

**Comment by junpenglao** [comment]
You can create a ipython notebook gist, you can attach data file in the gist

**Comment by jonathanng** [comment]
I created a shared repository: 

https://github.com/jonathanng/shared/blob/master/notebooks/bayesian_correlation.ipynb

**Comment by aloctavodia** [comment]
I will take a look at this tomorrow, but when running:

```python
corr = pm.stats._log_post_trace(correlation_trace, correlation_model)
fac = pm.stats._log_post_trace(factor_trace, factor_model)
```
I can see that the shape `(n_samples, n_observations)` of `corr` (1000, 356) and `fac` (1000, 3560) are different, although the number of observations in the dataset is the same (356, 10) for both models.

**Comment by aloctavodia** [comment]
Is not obvious to me how to solve this problem. The `correlation_model` uses a MultivariateNormal likelihood and then the number of observations are _effectively squished_ to 365. The `factor_model` uses a Normal likelihood and thence the observations are _flattened_ to 3650. All this seems OK, the problem being that you need the same number of observations in order to compare two models.  @junpenglao @aseyboldt  maybe you can help us with this.

**Comment by aseyboldt** [comment]
Hm, I see the problem. I don't see how we could change the logps of the mv normal to match the normal logps, but I guess we can do the reverse. A simple (but somewhat slow) fix would be to change the non-mvnormal model to use a mvnormal with diagonal cov matrix. That should be equivalent to summing up the logp vals that belong to the same vector, but without having to change the model comparison code.
I don't see how we could change `pm.compare` to deal with such problems, but we should at least try to improve the error message.

**Comment by aloctavodia** [comment]
Thanks @aseyboldt for the workaround. I agree we should check the number of observations and give an error message if they don't match. I will send a PR tomorrow...
