### ISSUE TITLE
Gaussian Process example is broken

### ISSUE THREAD

**Issue by gcgibson** [pymc-devs/pymc#2505]
https://pymc-devs.github.io/pymc3/notebooks/GP-introduction.html

/Users/fonnescj/Repos/pymc3/pymc3/distributions/multivariate.py in random(self, point, size)
    154
    155         if self._cov_type == 'cov':
--> 156             mu, cov = draw_values([self.mu, self.cov], point=point)
    157             if mu.shape != cov[0].shape:
    158                 raise ValueError("Shapes for mu an cov don't match")

**Comment by springcoil** [comment]
Thanks for sharing this. Can you share which version of PyMC3 you are using, there's been some changes in GP functionality lately.

**Comment by gcgibson** [comment]
Hi @springcoil I am actually seeing that error both locally and in the notebook posted at that link.
I am running `pymc3==3.1`

**Comment by springcoil** [comment]
Ohh ok thanks very much :) I might get time to dig into this tomorrow. 
 Cc @fonnesbeck or @junpenglao you might have some insight into this.

**Comment by springcoil** [comment]
@gcgibson If you want to investigate with a debugger that'd be cool too :) Maybe

**Comment by junpenglao** [comment]
It's fine on master: https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-introduction.ipynb 
I will close this for now, as @bwengals is still refactoring GP module and the notebooks will also be updated shortly.
