### ISSUE TITLE
Uniform parameter converges to the middle of the range

### ISSUE THREAD

**Issue by GuyPozner** [pymc-devs/pymc#2506]
`
    
    import pymc3
    import theano.tensor as tt

    log10_baseline_obs = np.log10(baseline_obs[baseline_obs > 0])

    with pymc3.Model() as model:
    
        mu_A = pymc3.Uniform('mu_A', -5,  5)
        sd_A = pymc3.Uniform('sd_A', 0, 2)
        x_A = pymc3.Lognormal('x_A', mu = mu_A, sd = sd_A, observed = log10_baseline_obs)
    
        step = pymc3.Metropolis()
        trace = pymc3.sample(18000, step=step)
        burned_trace=trace[1000:]

    >burned_trace['mu_A']
    array([ 0.,  0.,  0., ...,  0.,  0.,  0.])
`

Although log10_baseline_obs shows a clearn lognormal distribution the mu_A and sd_A always converage to the middle of the range that I specify. any help?

**Comment by junpenglao** [comment]
Metropolis proposal is all rejected in this case - can you try sampling using the default: `trace = pymc3.sample()`

**Comment by GuyPozner** [comment]
doing:
`trace = pymc3.sample()`

resulted in another Error:
`FloatingPointError: NaN occurred in optimization.`

I've checked for NaN's in the baseline observation array and found none. do you have a suggestion?

**Update:**
Replacing my input array with:
`log10_baseline_obs = np.random.lognormal(-1, 1, 10000)`
Resulted in a success.
Do you have an idea what could be in the input numpy array that would cause this?

**Update 2:**
I did not notice that I had some negative values in my input array, which are not defined for a lognormal distribution. I think it would help a lot if there was a check with an helpful error :)

Thanks  a lot :)

**Comment by junpenglao** [comment]
Hi @GuyPozner 
Glad you find where the problem is. We dont have any internal function currently to check the nan or inf - but you are right, we should ;-)
For now you can check the logp of each variable by doing:
```python
for RV in model.basic_RVs:
    print(RV.name, RV.logp(model.test_point))
```
More details could be found [in this discussion on Discourse](https://discourse.pymc.io/t/get-nan-or-inf-from-model-logp-model-test-point-is-an-attestation-of-incorrectly-configured-model/111/11?u=junpenglao)

**Comment by GuyPozner** [comment]
Thanks a lot,
I think it would be nice to add a check and allow for a shift transformation if needed for the PositiveContinues class.

**Comment by junpenglao** [comment]
We have a transformation for PositiveContinues to project it into real domain:
https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/transforms.py#L158
