### ISSUE TITLE
find_MAP docstring

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#2508]
I think the find_MAP `vars` argument needs a clarification.  
```
vars : list
    List of variables to set to MAP point (Defaults to all continuous).
```

In reality, I think this variable actually controls which variables are optimized over.  Presumable, the non-optimized variables are fixed at their current position.

**Comment by junpenglao** [comment]
@bwengals, could you please also take care of this in your PR?

**Comment by bwengals** [comment]
yeah can do
