### ISSUE TITLE
Check Logp for each Variable before sampling

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2509]
As suggested by @GuyPozner in #2506 
Currently, if the observed variable is outside of the domain of the RV there is no error or warning. There are some checks you can do as seen [here](https://discourse.pymc.io/t/get-nan-or-inf-from-model-logp-model-test-point-is-an-attestation-of-incorrectly-configured-model/111/11?u=junpenglao), but it would be good to have an internal function for that.

**Comment by kyleabeauchamp** [comment]
See also https://github.com/pymc-devs/pymc3/issues/2086

**Comment by junpenglao** [comment]
Thanks @kyleabeauchamp, I forgot about that one.

**Comment by kyleabeauchamp** [comment]
I also had this interesting PR that suggests strange behavior in the bounds warning stuff: https://github.com/pymc-devs/pymc3/pull/2091/

**Comment by springcoil** [comment]
Would this just involve implementing the code that @junpenglao often uses and some warnings then?
