### ISSUE TITLE
float32 v/s float16? running into error in two different cells in same notebook

### ISSUE THREAD

**Issue by shirishr** [pymc-devs/pymc#2520]
Refer note book at: [Here](http://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb)

At code cell 10 (Titled ### Mysterious code to be explained in Chapter 3.) I get an error: **TypeError: expected type_num 3 (NPY_INT16) got 9** (My .theanorc has floatX=float32). The error goes away if I set floatX=float16

but further down the same notebook in a section ###Why would I want samples from the posterior, anyways?
I find **lambda_1_samples[ix].sum()** becomes **Inf** if floatX=float16
Is there a way pymc3\sampling.py not raise this exception? or is this a Theano issue?

**Comment by junpenglao** [comment]
Hi @shirishr, are you using GPU? Also could you please try setting floatX=float64?

**Comment by shirishr** [comment]
@junpenglao,
Thank you sir for your quick response.
Yes I am using GPU, I will try separately with floatX=float64 and add as a comment.
In the meantime I found out that I could handle this situation in the notebook itself by casting lambda_1_samples to be int32 and overcome the challenge. In a cell where these tensor variables are defined I changed the code to:
**lambda_1_samples = trace['lambda_1'].astype('int32')
lambda_2_samples = trace['lambda_2'].astype('int32')**
I got satisfactory results

**Comment by shirishr** [comment]
@junpenglao,
Interestingly there was no error when floatX=float64
👍 🥇

**Comment by junpenglao** [comment]
I think if you use CPU there should be no error as well. Currently we are still battling with GPU support.

In general, our experience is that under GPU you need to be careful of the type, usually, we find: 
floatX == float32 => int16
floatX == float64 => int64
See discussion here https://github.com/pymc-devs/pymc3/issues/2366

**Comment by shirishr** [comment]
Interesting discussion and good learning for me. I should check if GPU kicked in when the notebook invoked import theano.tensor as tt and my floatX == float16. I am on CUDA version 8.0 and CUDnn version 7001.

**Comment by shirishr** [comment]
Looks like with CUDA 8.0 and CUDnn 7001 float16 is supported on GPU

This is what I see when **import theano.tensor as tt** is executed


![image](https://user-images.githubusercontent.com/7770013/29486683-f58d4ad8-84b9-11e7-9ddc-722bfcf3a0fd.png)
