### ISSUE TITLE
Not an issue...just a clarification sought by a newbie

### ISSUE THREAD

**Issue by shirishr** [pymc-devs/pymc#2521]
In one of the notebooks...I am defining a stochastic variable as

**data = np.array([10, 5])
with model:
    fixed_variable = pm.Poisson("fxd2", 1, observed=data)**

Later I discover that I do not need this variable..how do I delete it in a notebook **(in the context of the model)**?

Thanks in advance

**Comment by fonnesbeck** [comment]
Hi Sam. Please use the [Discourse discussion board](https://discourse.pymc.io) to ask about usage questions. We want to keep the issue tracker for bug reports only. Thanks!

**Comment by shirishr** [comment]
Yes sir, Will do !
