### ISSUE TITLE
compare function mentioned in that link no longer exisits at the top level of the pymc3

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2527]
"Also note that the compare function mentioned in that link no longer exisits at the top level of the pymc3 package, nor is it in the stats package as the API docs state."

From http://disq.us/url?impression=56ef3e0c-891b-11e7-a8b8-002590f0f6c8&thread=2442643474&forum=2494902&url=http%3A%2F%2Ftwiecki.github.com%2Fblog%2F2014%2F03%2F17%2Fbayesian-glms-3%2F%23comment-3485444888%3AUBnukRKubAYO17MOOi9zjlZ_-SE&variant=active&experiment=digests&behavior=click&post=3485444888&type=notification.post.moderator&event=email

**Comment by aloctavodia** [comment]
do you mean this?

https://github.com/pymc-devs/pymc3/blob/d4749cd0865927ff0430800272c39855acb9bc96/pymc3/stats.py#L344

**Comment by junpenglao** [comment]
It is on the top level, you can do `pm.compare`.
Also, it's in the doc... http://docs.pymc.io/en/latest/api/stats.html#pymc3.stats.compare

**Comment by twiecki** [comment]
hm, yeah, that's what I thought. Thanks for confirming.
