### ISSUE TITLE
MeanField object has no attribute 'elbo_vals'

### ISSUE THREAD

**Issue by mullachv** [pymc-devs/pymc#2528]
This attribute (elbo_vals) was available when I used:
```
v_params = pymc3.variational.advi(n=10000)
trace = pymc3.variational.sample_vp(v_params,draws=1000)

```
However, the above was deprecated and asked me to use the following instead:
``` 
v_params = pymc3.fit(n=10000)
trace = pymc3.sample_approx(v_params,draws=1000)
```

So, now I get this error:
```
AttributeErrorTraceback (most recent call last)
<ipython-input-4-40f68f779707> in <module>()
      3     trace = pm.sample_approx(v_params,draws=1000)
      4 
----> 5 plt.plot(v_params.elbo_vals)
      6 plt.ylabel('ELBO')
      7 plt.xlabel('iteration')

AttributeError: 'MeanField' object has no attribute 'elbo_vals'
```

**Comment by junpenglao** [comment]
Hi @mullachv, you can get the elbo from the Meanfield by doing `plt.plot(mean_field.hist)` using the new API. More information could be found in the doc: [variational api quickstart](http://docs.pymc.io/en/latest/notebooks/variational_api_quickstart.html)
