### ISSUE TITLE
iter_sample that return current sample but not save to memory

### ISSUE THREAD

**Issue by adler-j** [pymc-devs/pymc#2530]
When initializing large or long running models, I get `MemoryError`. This is obviously because pymc3 stores every single iteration in an NDarray.

For several applications, there is really no need to store all iterations, and accessing them one by one via an iterator would be fine. This is what i thought `iter_sample` would do, but it seems like it still tries to store all iterates.

Is there some way to stop `iter_sample` from storing all iterates and simply let me use the iterator as it goes?

**Comment by twiecki** [comment]
Can you try with a different backend, like hdf5?

**Comment by adler-j** [comment]
Well, that would only allow a single order of magnitude increase in number of iterates (at the cost of using 1 tb of harddrive space and reducing performance).

Is there any reason that all iterates need to be stored? Perhaps I can make a PR with a backend that does not store the results?

**Comment by junpenglao** [comment]
> Is there any reason that all iterates need to be stored? Perhaps I can make a PR with a backend that does not store the results?

In conventional Bayesian Statistics, we need the samples from the posterior as the approximation. It is thus not sufficient to have only 1 sample/iterates.
But there might be some use cases that you only want the current state/iterate, so yes PR welcome.

**Comment by adler-j** [comment]
Well I would be interested in stuff like computing the posterior mean. This can be done "on the fly", and there is no need to keep all iterates in memory.

I'll see what I can do w.r.t. a PR, should be a good exercise. Love the library otherwise!

**Comment by junpenglao** [comment]
I see. That could be a cool application, we can even add some Rao–Blackwellization for the posterior mean.

**Comment by ColCarroll** [comment]
It would be fairly straightforward to get a batching iterator -- something like

```
def batcher(model, samples, batch_size):
    with model:
        trace = pm.sample(batch_size)
    yield trace
    tot = batch_size
    while tot < samples:
        with model:
            trace = pm.sample(batch_size, tune=0, init=None)
        tot += batch_size
        yield trace
```

but with better book keeping.  Note that you can also iterate over a trace, and you'll get dictionaries.  If you're on python>3.3, you can even use `yield from pm.sample(...)`!
