### ISSUE TITLE
Should approx transform constrained variables?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#2531]
We recently updated find_map() to return both raw and transformed random variables (#2523).  However, I noticed that `means = approx.gbij.rmap(approx.mean.eval())` (http://docs.pymc.io/en/latest/notebooks/GLM-hierarchical-advi-minibatch.html) only returns the means of the "raw" parameters, not of the original variables of interest.  Should we perhaps add functionality to provide the transformed values as well, which are the parameters of human interest?

**Comment by ferrine** [comment]
I thought about this feature as an internal purpose functionality. Yes, we can do it but only after vi refactoring

**Comment by junpenglao** [comment]
You can use the following two lines to get the value of the raw RVs.
https://github.com/pymc-devs/pymc3/blob/d4749cd0865927ff0430800272c39855acb9bc96/pymc3/tuning/starting.py#L159-L160
