### ISSUE TITLE
Add effective sample size and gelman_rubin rhat to `pm.df_summary` output

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2532]
To be in line with the output in Stan [cell 8](http://mc-stan.org/users/documentation/case-studies/pystan_workflow.html). Both are easily available already using `pm.effective_n` and `pm.gelman_rubin`. This should make a good first contribution.

**Comment by SioKCronin** [comment]
Thanks @junpenglao for flagging this as 'beginner_friendly`, as it was a clear addition to make, and a great excuse to get my environment set-up and get to know the codebase. I'll submit the PR today.

**Comment by twiecki** [comment]
Awesome @SioKCronin!

**Comment by springcoil** [comment]
Awsome @SioKCronin :)

**Comment by SioKCronin** [comment]
I encountered an architecture question re: stats.py and diagnostics.py (https://github.com/pymc-devs/pymc3/pull/2576), and warmly welcome feedback.

**Comment by junpenglao** [comment]
Fixed in #2576
