### ISSUE TITLE
find_MAP appends _log__ or _interval__ to variable names

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2545]
I have a model that uses Lognormal and Uniform priors and if I do a `pymc3.find_MAP()`, the resulting dictionary has different variable keys than the names of the prior RVs.

I did observe that Lognormal priors will end up with a `_log__` suffix and Uniform priors get `_interval__`

I searched both the GitHub repo and the documentation, but there is no mention in either of them.

Where does this suffix come from? Is it safe to just `replace("_log__", "")`?

**Comment by junpenglao** [comment]
Hi @michaelosthege, the `_log__` and `_interval__` suffix are the indications that these bound RVs were transformed to real domain, you can see more explanation here: 
http://docs.pymc.io/notebooks/api_quickstart.html#Automatic-transforms-of-bounded-RVs

They are not the same as the original RVs, so you should not just replace them.

Similar discussion here: https://github.com/pymc-devs/pymc3/issues/2531

**Comment by fonnesbeck** [comment]
@michaelosthege the original variables are in the set of Deterministics for the model. They should still be there in the output.

**Comment by fonnesbeck** [comment]
Ignore my previous comment; forgot you were using MAP
