### ISSUE TITLE
Online docs show only master branch, viewing of older releases is not possible

### ISSUE THREAD

**Issue by smartass101** [pymc-devs/pymc#2547]
I'm thrilled by the fast development speed, but the docs at http://docs.pymc.io/
show only the latest master docs with no option to select an older version as is common in many RTD setups. This is especially inconvenient since the PyPi version is 3.1 and e.g. the GP module has changed significantly since then.  BTW, the docs still display  `3.1` as the version of the master branch, which is confusing.

**Comment by fonnesbeck** [comment]
This is a good point. Our online docs should always default to the current release, as it is more reasonable for those working off of master to build their own docs.

**Comment by ColCarroll** [comment]
I think this will also require some work on how releases go -- right after tagging the final release, bumping version to `3.1.dev` (or something).  I'm looking at https://github.com/Robpol86/sphinxcontrib-versioning , which does not look very actively developed, and has some alarming issues, but seems like exactly what we'd want...
