### ISSUE TITLE
Binomial GLM returns incorrect results with bool outcome variable

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2548]
If a GLM is specified using a response variable that has a `bool` dtype, it will yield incorrect inference. Specifically, estimates will have an incorrect sign, implying that `True` is interpreted as a zero rather than a one. For example, the following model:

```python
with pm.Model() as logistic_model:
    pm.glm.GLM.from_formula('dm ~ male + age + waist_hip + bps + bpd + bmi', 
                            diabetes.dropna(subset=['male', 'age', 'waist_hip', 'bps', 'bpd', 'bmi']), 
                            family=pm.glm.families.Binomial())
    trace_logistic_model = pm.sample(2000)
```

returns the following estimates with `dm` of dtype `bool`:

![unknown-2](https://user-images.githubusercontent.com/81476/30194030-65a489c4-9416-11e7-92ba-c7effbc79be1.png)

whereas, casting `dm` to `int` type yields correct estimates:

![unknown-1](https://user-images.githubusercontent.com/81476/30194037-7701ac10-9416-11e7-9a62-c4acd45ccdb3.png)

Running master on Python 3.6.1.

**Comment by RothNRK** [comment]
This is my first contribution to an open project. I'd like to help but where are you sourcing the diabetes data so I can reproduce your results? Is this the diabetes data from sklearn?

http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html
http://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

**Comment by ColCarroll** [comment]
Thanks for the interest!  I can't find @fonnesbeck's data, but this notebook recreates the problem, in that the signs of the sampled points switch when the target is cast to boolean: https://gist.github.com/ColCarroll/4995b4c5320d333be2fe20a62327eca3

**Comment by fonnesbeck** [comment]
Sorry for not posting the complete problem. [Here is the full notebook](https://gist.github.com/fonnesbeck/db6104352dc9257d31902f61d4f25b8b) and the dataset is [here](http://d.pr/f/85josw).

**Comment by RothNRK** [comment]
Thanks for the info.

https://github.com/pymc-devs/pymc3/pull/2636

Return the last column instead of the first column addresses the issue.
