### ISSUE TITLE
Link to Kernels/Covariance functions on Gaussian Processes Examples page is broken

### ISSUE THREAD

**Issue by willferreira** [pymc-devs/pymc#2554]
This one:

http://docs.pymc.io/notebooks/GP-Covariances.html

**Comment by ColCarroll** [comment]
Weird -- it is located at http://docs.pymc.io/notebooks/GP-covariances.html , but sphinx should take care of that (the file is named with a capital "C").  Rebuilding should fix it...

**Comment by bwengals** [comment]
That is weird.  While it works, @ColCarroll your link also shows an older version GP-covariances.ipynb.  I capitalized it to be consistent with the other new GP notebooks.  The new version of the notebook is GP-Covariances.ipynb

**Comment by ColCarroll** [comment]
I would guess that @twiecki hasn't updated the docs since then -- #2538 should fix having to ping him about it.

**Comment by twiecki** [comment]
I just updated them and added a script that does it automatically: https://github.com/pymc-devs/pymc3/blob/master/build_and_deploy_docs.sh

**Comment by twiecki** [comment]
I think this is fixed, re-open if not.
