### ISSUE TITLE
Metropolis sampler wastes performance on sampling constant priors

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2557]
I have a model for which some priors are `Constant` but may be substituted with non-Constant priors in the future.

When performance-profiling it, I noticed that in each iteration of the sampler, it evaluates the likelihood multiple times. That actually makes sense (and correct me if I'm wrong), because the sampler samples the dimensions independently within each iteration.
Now because 3 out of 7 priors are currently `Constant` this wastes a lot of CPU time.

With this script, you can reproduce it for the getting-started example. In the second block, one of the three priors is set `Constant`, so we would expect the sampling to be around 30 % faster.

```python
import numpy as np
import matplotlib.pyplot as plt
import pymc3
import time

# Initialize random number generator
np.random.seed(123)

# True parameter values
alpha, sigma = 1, 1
beta = [1, 2.5]

# Size of dataset
size = 100

# Predictor variable
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2

# Simulate outcome variable
# IMPORTANT: alpha is left out
Y = beta[0]*X1 + beta[1]*X2 + np.random.randn(size)*sigma

def benchmark(stepper):
    t = []
    for i in range(10):
        t_start = time.time()
        trace = pymc3.sample(5000, step=pymc3.Metropolis())
        t_end = time.time()
        t.append(t_end - t_start)
    return np.mean(t), np.std(t)

# run twice to account for compilation

print("--------------- default priors ---------------")
with pymc3.Model() as pmodel:
    # Priors for unknown model parameters
    alpha = pymc3.Normal('alpha', mu=0, sd=10)
    beta = pymc3.Normal('beta', mu=0, sd=10, shape=2)
    sigma = pymc3.HalfNormal('sigma', sd=1)

    # Expected value of outcome
    mu = alpha + beta[0]*X1 + beta[1]*X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pymc3.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)

    # draw 5000 posterior samples
    mean, std = benchmark(pymc3.Metropolis())
    print("Metropolis-Sampling took {:.4f} +- {:.4f} seconds".format(mean, std))

print("--------------- constant alpha ---------------")
with pymc3.Model() as pmodel:
    # Priors for unknown model parameters
    alpha = pymc3.Constant('alpha', c=0)
    beta = pymc3.Normal('beta', mu=0, sd=10, shape=2)
    sigma = pymc3.HalfNormal('sigma', sd=1)

    # Expected value of outcome
    mu = alpha + beta[0]*X1 + beta[1]*X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pymc3.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)
    
    # draw 5000 posterior samples
    mean, std = benchmark(pymc3.Metropolis())
    print("Metropolis-Sampling took {:.4f} +- {:.4f} seconds".format(mean, std))
```

It outputs:

```bash
----- default priors ----
Metropolis: 6.95 +- 0.84
NUTS: 7.82 +- 1.46
----- constant alpha ----
Metropolis: 6.86 +- 0.88
NUTS: 7.12 +- 1.16
```

From the performance profiler it looks like it is introduced in the [`CompoundStep.step`](https://github.com/pymc-devs/pymc3/blob/bf5fd24ab3d43c1bf72fd694023f99e8943347a7/pymc3/step_methods/compound.py#L19) method.

I am not familiar with the `step_methods` API design, but could this be as simple as returning the input point when stepping on a `Constant` dimension?

**Comment by junpenglao** [comment]
Your observation is correct - `Constant` is currently a distribution so it would become a RV in the model, the sampler will try to sample from it.
The recommendation is to replace it with `Deterministic`, in fact, `Constant` will be deprecated in the future release. For more information, please see discussion here https://github.com/pymc-devs/pymc3/pull/2452

**Comment by michaelosthege** [comment]
For the record:
Specifying `c = pm.Deterministic('myconstant', 42)` can lead to type problems if the value is already in the theano cache (eg. low integers).

Instead, one should create a new `TensorConstant`
`mypriorvalue = tt.constant_or_value(42.123, rtype=tt.TensorConstant, name='const42')` (name can be omitted)

To include it in the trace, one can then wrap it in `pm.Deterministic('mypointprior', mypriorvalue)`
