### ISSUE TITLE
'module' object has no attribute '__getitem__' error

### ISSUE THREAD

**Issue by yongsua1989** [pymc-devs/pymc#2559]
Hi, I am trying some GLM code from this website:
[http://twiecki.github.io/blog/2013/08/12/bayesian-glms-1/](url)

But I have problem with the code:

> with Model() as model:
>     GLM.from_formula('y ~ x', data)
>     trace = sample(progressbar=False, tune=1000, njobs=4)

I got this error:

> TypeError                                 Traceback (most recent call last)
> <ipython-input-18-5c6c2a9cc9b0> in <module>()
>       1 with Model() as model:
> ----> 2     GLM.from_formula('y ~ x', data)
>       3     trace = sample(progressbar=False, tune=1000, njobs=4)
>       4 
> 
> /usr/local/lib/python2.7/dist-packages/pymc3/glm/linear.pyc in from_formula(cls, formula, data, priors, vars, family, name, model)
>     131                      vars=None, family='normal', name='', model=None):
>     132         import patsy
> --> 133         y, x = patsy.dmatrices(formula, data)
>     134         labels = x.design_info.column_names
>     135         return cls(np.asarray(x), np.asarray(y)[:, 0], intercept=False, labels=labels,
> 
> /usr/local/lib/python2.7/dist-packages/patsy/highlevel.pyc in dmatrices(formula_like, data, eval_env, NA_action, return_type)
>     308     eval_env = EvalEnvironment.capture(eval_env, reference=1)
>     309     (lhs, rhs) = _do_highlevel_design(formula_like, data, eval_env,
> --> 310                                       NA_action, return_type)
>     311     if lhs.shape[1] == 0:
>     312         raise PatsyError("model is missing required outcome variables")
> 
> /usr/local/lib/python2.7/dist-packages/patsy/highlevel.pyc in _do_highlevel_design(formula_like, data, eval_env, NA_action, return_type)
>     163         return iter([data])
>     164     design_infos = _try_incr_builders(formula_like, data_iter_maker, eval_env,
> --> 165                                       NA_action)
>     166     if design_infos is not None:
>     167         return build_design_matrices(design_infos, data,
> 
> /usr/local/lib/python2.7/dist-packages/patsy/highlevel.pyc in _try_incr_builders(formula_like, data_iter_maker, eval_env, NA_action)
>      68                                       data_iter_maker,
>      69                                       eval_env,
> ---> 70                                       NA_action)
>      71     else:
>      72         return None
> 
> /usr/local/lib/python2.7/dist-packages/patsy/build.pyc in design_matrix_builders(termlists, data_iter_maker, eval_env, NA_action)
>     694                                                    factor_states,
>     695                                                    data_iter_maker,
> --> 696                                                    NA_action)
>     697     # Now we need the factor infos, which encapsulate the knowledge of
>     698     # how to turn any given factor into a chunk of data:
> 
> /usr/local/lib/python2.7/dist-packages/patsy/build.pyc in _examine_factor_types(factors, factor_states, data_iter_maker, NA_action)
>     441     for data in data_iter_maker():
>     442         for factor in list(examine_needed):
> --> 443             value = factor.eval(factor_states[factor], data)
>     444             if factor in cat_sniffers or guess_categorical(value):
>     445                 if factor not in cat_sniffers:
> 
> /usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in eval(self, memorize_state, data)
>     564         return self._eval(memorize_state["eval_code"],
>     565                           memorize_state,
> --> 566                           data)
>     567 
>     568     __getstate__ = no_pickling
> 
> /usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in _eval(self, code, memorize_state, data)
>     549                                  memorize_state["eval_env"].eval,
>     550                                  code,
> --> 551                                  inner_namespace=inner_namespace)
>     552 
>     553     def memorize_chunk(self, state, which_pass, data):
> 
> /usr/local/lib/python2.7/dist-packages/patsy/compat.pyc in call_and_wrap_exc(msg, origin, f, *args, **kwargs)
>     115 def call_and_wrap_exc(msg, origin, f, *args, **kwargs):
>     116     try:
> --> 117         return f(*args, **kwargs)
>     118     except Exception as e:
>     119         if sys.version_info[0] >= 3:
> 
> /usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in eval(self, expr, source_name, inner_namespace)
>     164         code = compile(expr, source_name, "eval", self.flags, False)
>     165         return eval(code, {}, VarLookupDict([inner_namespace]
> --> 166                                             + self._namespaces))
>     167 
>     168     @classmethod
> 
> <string> in <module>()
> 
> /usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in __getitem__(self, key)
>      46         for d in self._dicts:
>      47             try:
> ---> 48                 return d[key]
>      49             except KeyError:
>      50                 pass
> 
> /usr/local/lib/python2.7/dist-packages/patsy/eval.pyc in __getitem__(self, key)
>      46         for d in self._dicts:
>      47             try:
> ---> 48                 return d[key]
>      49             except KeyError:
>      50                 pass
> 
> TypeError: 'module' object has no attribute '__getitem__'
>

**Comment by fonnesbeck** [comment]
Please format your output using Markdown. Thanks.

**Comment by fonnesbeck** [comment]
What version of PyMC3 are you running? Did you install it from GitHub, conda or elsewhere?

**Comment by yongsua1989** [comment]
I'm running PyMC3 version 3.1. I installed with "sudo pip install pymc3" command.

**Comment by yongsua1989** [comment]
Thanks for the concern. I figured out the problem that I did not import patsy to my PyLab. Everything works fine again. 
Thank You.
