### ISSUE TITLE
Text backend does not support tallying a subset of variables (raises KeyError)

### ISSUE THREAD

**Issue by chumsley** [pymc-devs/pymc#2560]
Attempting to use a trace that was loaded from the text backend yields a KeyError, if the trace contains only a subset of the model's variables (e.g., if it was created using the `trace=` argument to `sample`).

Failing example:
```python
with pm.Model() as model:
    a = pm.Gamma('a', mu=10.0, sd=2.0)
    b = pm.Gamma('b', mu=10.0, sd=2.0)

    trace = pm.sample(trace=[model.a, model.a_log__])
    assert len(trace.varnames) == 2

    pm.backends.text.dump('trace.text', trace)

    loaded = pm.backends.text.load('trace.text')
    x = loaded[0] #!!! Will throw a KeyError looking for 'b_log__'
```

**Comment by junpenglao** [comment]
Thanks for reporting. We should add the `vars=None` kwarg into `pm.backends.text.load` and `pm.backends.text.dump`

**Comment by haritha1313** [comment]
@twiecki @junpenglao I'd like to work on this issue.

**Comment by vermashresth** [comment]
Hi @junpenglao 
I have gone through the code base of pymc3 and would like to start working on an issue. This one seems old but is it still relevant?

**Comment by twiecki** [comment]
@vermashresth Definitely, you can just try the above code to see if the problem persists.

**Comment by michaelosthege** [comment]
We're deprecating multiple backends.. (see #3903)
While the text backend may survive a bit longer, only _very_ few people seem to be using it.

As indicated by our deprecation warnings, please switch backends. If you can't please contact us and tell us why.

Closing this issue, because most likely, nobody will take it up.
