### ISSUE TITLE
[Feature request] Bayesian Rsquare for GLM

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2564]
[Gelman, Goodrich, Gabry, & Ali 2017](http://www.stat.columbia.edu/~gelman/research/unpublished/bayes_R2.pdf)

The concept of R^2 and “explained variance” makes most sense for GLM with equal variance, but it seems easy to compute so why not `¯\_(ツ)_/¯`

**Comment by aloctavodia** [comment]
I like the idea! I generally compute the R^2 when doing Bayesian linear regression. Also thanks for the paper.
