### ISSUE TITLE
Dimension mismatching with pm.MvGaussianRandomWalk

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#2565]
I am trying to do build a model that is a multi output rolling regression model. I simulate the data as following: 

```
import numpy as np
import pymc3 as pm
from scipy.linalg import cholesky
import pymc3 as pm
import theano
np.random.seed(1)

N = 1500
D = 3

cov = np.random.randn(D,D)
cov = cov.dot(cov.T)
L = cholesky(cov, lower=True)

y = np.random.randn(N, D)
y = (L.dot(y.T)).T
y = np.cumsum(y, axis=0)
```

The model is posted below. Suppose that N is the number of days and I wish to have a linear trend each year (which is the `window` parameter). The variable `t_section` is an indexing parameter to indicate which year each observation corresponds to.  

However, at the `regression = alpha_r+beta_r*t_t` line I get the error: `ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 1500)`. I got a feeling that all I need to do is transpose one of the variables, but `theano.tensor.transpose` isn't exactly helping. Any thoughts?

```
N, D = y.shape

t = np.arange(len(y))
t_mean = t.mean()
t = t-t_mean

window = 365
t_section = np.int64(t-t.min())//window
k = t_section.max()+1

t_t = theano.shared(t)
y_t = theano.shared(y)
t_section_t = theano.shared(t_section)

with pm.Model() as model:
    packed_L_α = pm.LKJCholeskyCov('packed_L_α', n=D,   
                             eta=2., sd_dist=pm.HalfCauchy.dist(2.5))
    L_α = pm.expand_packed_triangular(D, packed_L_α)
    Σ_α = pm.Deterministic('Σ_α', L_α.dot(L_α.T))

    packed_L_β = pm.LKJCholeskyCov('packed_L_β', n=D,   
                             eta=2., sd_dist=pm.HalfCauchy.dist(2.5))
    L_β = pm.expand_packed_triangular(D, packed_L_β)
    Σ_β = pm.Deterministic('Σ_β', L_β.dot(L_β.T))

    α = pm.MvGaussianRandomWalk('alpha', shape=(k, D), cov=Σ_α)
    β = pm.MvGaussianRandomWalk('beta', shape=(k, D), cov=Σ_β)
    alpha_r = α[t_section_t]
    beta_r = β[t_section_t]
    regression = alpha_r+beta_r*t_t

    sd = pm.Uniform('sd', 0, 20)
    likelihood = pm.Normal('y', mu=regression, sd=sd, observed=y_t)
```

**Comment by junpenglao** [comment]
You can do `t_t = theano.shared(np.repeat(t[:,np.newaxis], 3, axis=1))` instead to make sure they are the same shape.

FYI, this question is more suitable for our discourse forum: https://discourse.pymc.io/. I will close this for now, if you have further question, please post it to discourse :-)
