### ISSUE TITLE
MvGaussianRandomWalk does not have a chol option

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#2569]
Hi all,

Just letting you know that it is compulsory to specify a covariance matrix in `MvGaussianRandomWalk` as opposed to just a Cholesky decomposition as is allowed `MvNormal`, which looks for one of cov, tau or chol to be present.

My Python isn't the best but is it simply a matter of doing (similar to what is in `MvNormal`):
```
class MvGaussianRandomWalk(_QuadFormBase):
    def __init__(self, mu, cov=None, tau=None, chol=None, lower=True,
                 *args, **kwargs):
        super(MvGaussianRandomWalk, self).__init__(mu=mu, cov=cov, tau=tau, chol=chol,
                                       lower=lower, *args, **kwargs)
```
If this is the case I can do a pull-request. Otherwise I'm happy to leave it to you guys.

**Comment by junpenglao** [comment]
Please do a pull-request. While you are on it, `MvStudentTRandomWalk` should be changed similarly.
