### ISSUE TITLE
AttributeError: module 'pymc3' has no attribute 'KLqp' in 3.1

### ISSUE THREAD

**Issue by dataoverflow** [pymc-devs/pymc#2570]
I am trying to run this notebook:

https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/lda-advi-aevb.ipynb

In cell 10 there is a line `inference = pm.KLqp(approx)` 

I get `AttributeError: module 'pymc3' has no attribute 'KLqp'` when running the cell.

How to fix it?

**Comment by ferrine** [comment]
Are you on master?

**Comment by dataoverflow** [comment]
No, just installed 3.1 via pip

**Comment by ferrine** [comment]
To run the example you need master. We update them while development so they work on latest commit.

[Here](https://github.com/pymc-devs/pymc3/tree/v3.1)  is the 3.1 tag commit where you can find the example that works with your version

**Comment by dataoverflow** [comment]
Thanks!
