### ISSUE TITLE
Theano DLL error after importing PyMC3

### ISSUE THREAD

**Issue by tt293** [pymc-devs/pymc#2571]
Conda 4.3.25, Python 3.5.3 64 bit, Windows 10, no GPU. Everything looks ok when importing Theano, but after importing PyMC3, things go wrong:

In [1]: import theano.tensor as tt

In [2]: tt.log(2)
Out[2]: Elemwise{log,no_inplace}.0

In [3]: import pymc3

In [4]: tt.log(2)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-f1a1f959b680> in <module>()
----> 1 tt.log(2)

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\op.py in __call__(self, *inputs, **kwargs)
    668                 # compute output value once with test inputs to validate graph
    669                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 670                                            no_recycling=[])
    671                 thunk.inputs = [storage_map[v] for v in node.inputs]
    672                 thunk.outputs = [storage_map[v] for v in node.outputs]

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    933             try:
    934                 return self.make_c_thunk(node, storage_map, compute_map,
--> 935                                          no_recycling)
    936             except (NotImplementedError, utils.MethodNotDefined):
    937                 # We requested the c code, so don't catch the error.

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    837         _logger.debug('Trying CLinker.make_thunk')
    838         outputs = cl.make_thunk(input_storage=node_input_storage,
--> 839                                 output_storage=node_output_storage)
    840         fill_storage, node_input_filters, node_output_filters = outputs
    841

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1188         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1189             input_storage, output_storage, storage_map,
-> 1190             keep_lock=keep_lock)
   1191
   1192         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1129                                     output_storage,
   1130                                     storage_map,
-> 1131                                     keep_lock=keep_lock)
   1132         return (thunk,
   1133                 [link.Container(input, storage) for input, storage in

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1584                 node.op.prepare_node(node, storage_map, None, 'c')
   1585             module = get_module_cache().module_from_key(
-> 1586                 key=key, lnk=self, keep_lock=keep_lock)
   1587
   1588         vars = self.inputs + self.outputs + self.orphans

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1157             try:
   1158                 location = dlimport_workdir(self.dirname)
-> 1159                 module = lnk.compile_cmodule(location)
   1160                 name = module.__file__
   1161                 assert name.startswith(location)

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cc.py in compile_cmodule(self, location)
   1487                 lib_dirs=self.lib_dirs(),
   1488                 libs=libs,
-> 1489                 preargs=preargs)
   1490         except Exception as e:
   1491             e.args += (str(self.fgraph),)

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2323             open(os.path.join(location, "__init__.py"), 'w').close()
   2324             assert os.path.isfile(lib_filename)
-> 2325             return dlimport(lib_filename)
   2326
   2327

C:\Users\thoma\Anaconda3\lib\site-packages\theano\gof\cmodule.py in dlimport(fullpath, suffix)
    300             warnings.filterwarnings("ignore",
    301                                     message="numpy.ndarray size changed")
--> 302             rval = __import__(module_name, {}, {}, [module_name])
    303         t1 = time.time()
    304         import_time += t1 - t0

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

**Comment by fonnesbeck** [comment]
Did you build Theano yourself, or install it via conda?

**Comment by tt293** [comment]
Installed via conda

**Comment by twiecki** [comment]
Hm, if it only happens with pymc3 maybe related to test-values? What happens if you set  `theano.config.compute_test_value = 'raise'` after importing theano?

**Comment by tt293** [comment]
That leads to the same error as after importing pymc3

**Comment by tt293** [comment]
I've found a workaround for now. Disabling the c++ compiler in .thenorc:
[global]
cxx =

**Comment by twiecki** [comment]
Very curious, never seen this before. Thanks for posting the answer. I'll close this in the hopes that someone will find it with the same problem.

**Comment by Ali-Ashtari** [comment]
Similar issue.

@twiecki I am seeing a similar problem when I try to import pymc3:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda33\lib\configparser.py in _unify_values(self, section, vars)
   1137         try:
-> 1138             sectiondict = self._sections[section]
   1139         except KeyError:

KeyError: 'blas'

During handling of the above exception, another exception occurred:

NoSectionError                            Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configparser.py in fetch_val_for_key(key, delete_key)
    167         try:
--> 168             return theano_cfg.get(section, option)
    169         except ConfigParser.InterpolationError:

~\AppData\Local\Continuum\anaconda33\lib\configparser.py in get(self, section, option, raw, vars, fallback)
    780         try:
--> 781             d = self._unify_values(section, vars)
    782         except NoSectionError:

~\AppData\Local\Continuum\anaconda33\lib\configparser.py in _unify_values(self, section, vars)
   1140             if section != self.default_section:
-> 1141                 raise NoSectionError(section)
   1142         # Update with the entry specific variables

NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configparser.py in __get__(self, cls, type_, delete_key)
    327                 val_str = fetch_val_for_key(self.fullname,
--> 328                                             delete_key=delete_key)
    329                 self.is_default = False

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configparser.py in fetch_val_for_key(key, delete_key)
    171     except (ConfigParser.NoOptionError, ConfigParser.NoSectionError):
--> 172         raise KeyError(key)
    173 

KeyError: 'blas.ldflags'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-1a95cb4612db> in <module>()
----> 1 import pymc3 as pm

~\AppData\Local\Continuum\anaconda33\lib\site-packages\pymc3\__init__.py in <module>()
      3 
      4 from .blocking import *
----> 5 from .distributions import *
      6 from .external import *
      7 from .glm import *

~\AppData\Local\Continuum\anaconda33\lib\site-packages\pymc3\distributions\__init__.py in <module>()
----> 1 from . import timeseries
      2 from . import transforms
      3 
      4 from .continuous import Uniform
      5 from .continuous import Flat

~\AppData\Local\Continuum\anaconda33\lib\site-packages\pymc3\distributions\timeseries.py in <module>()
----> 1 import theano.tensor as tt
      2 from theano import scan
      3 
      4 from pymc3.util import get_variable_name
      5 from .continuous import get_tau_sd, Normal, Flat

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\__init__.py in <module>()
    122 from theano.printing import pprint, pp
    123 
--> 124 from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
    125                                 scan_checkpoints)
    126 

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\scan_module\__init__.py in <module>()
     39 __contact__ = "Razvan Pascanu <r.pascanu@gmail>"
     40 
---> 41 from theano.scan_module import scan_opt
     42 from theano.scan_module.scan import scan
     43 from theano.scan_module.scan_checkpoints import scan_checkpoints

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\scan_module\scan_opt.py in <module>()
     58 
     59 import theano
---> 60 from theano import tensor, scalar
     61 from theano.tensor import opt, get_scalar_constant_value, Alloc, AllocEmpty
     62 from theano import gof

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\tensor\__init__.py in <module>()
     15 from theano.tensor import opt
     16 from theano.tensor import opt_uncanonicalize
---> 17 from theano.tensor import blas
     18 from theano.tensor import blas_scipy
     19 from theano.tensor import blas_c

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\tensor\blas.py in <module>()
    153 from theano.scalar import bool as bool_t
    154 from theano.tensor import basic as T
--> 155 from theano.tensor.blas_headers import blas_header_text
    156 from theano.tensor.blas_headers import blas_header_version
    157 from theano.tensor.opt import in2out, local_dimshuffle_lift

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\tensor\blas_headers.py in <module>()
    985 
    986 
--> 987 if not config.blas.ldflags:
    988     _logger.warning('Using NumPy C-API based implementation for BLAS functions.')
    989 

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configparser.py in __get__(self, cls, type_, delete_key)
    330             except KeyError:
    331                 if callable(self.default):
--> 332                     val_str = self.default()
    333                 else:
    334                     val_str = self.default

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configdefaults.py in default_blas_ldflags()
   1428         if res:
   1429             if 'mkl' in res:
-> 1430                 check_mkl_openmp()
   1431             return res
   1432 

~\AppData\Local\Continuum\anaconda33\lib\site-packages\theano\configdefaults.py in check_mkl_openmp()
   1250         import mkl
   1251         if '2018' in mkl.get_version_string():
-> 1252             raise RuntimeError('To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.')
   1253     except ImportError:
   1254         raise RuntimeError("""

RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

**Comment by ColCarroll** [comment]
This is a linux only problem we've been dealing with on travis – can you run `export MKL_THREADING_LAYER=GNU` in your shell before running the above command and let us know if that works?  If it does, you may wish to add that command to your `.bashrc`

See https://github.com/Theano/Theano/issues/6499#issuecomment-342160463

**Comment by Ali-Ashtari** [comment]
Thanks @ColCarroll! It worked! I appreciate the prompt response :)
