### ISSUE TITLE
What to do with divergences for my case

### ISSUE THREAD

**Issue by yongsua1989** [pymc-devs/pymc#2573]
Yearly data for stock price
![yearly1](https://user-images.githubusercontent.com/31859413/30514176-ae28c128-9b42-11e7-8982-e7a96925b094.png)

Monthly data for stock price
![monthly1](https://user-images.githubusercontent.com/31859413/30514178-b8ff4658-9b42-11e7-9cd3-d113aee4b447.png)

Weekly data for stock price
![weekly1](https://user-images.githubusercontent.com/31859413/30514181-c329ce50-9b42-11e7-9e76-325d19636840.png)

I have divergence problems possibly due to the parameter values I have followed from the example of stochastic volatility model, leading to biased inference. I need some guidance what parameters should be adjusted to solve this issue.

Parameters from example:

σ∼exp(50)
ν∼exp(.1)
si∼N(si−1, σ^−2)
log(yi)∼ t(ν,0,exp(−2si))

We have four variables here, so which parameters should I change? I have hard time understanding how stochastic volatility model works with PyMC3.

Thank You.

**Comment by junpenglao** [comment]
Hi @yongsua1989, could you please move this to https://discourse.pymc.io/? We are trying to keep the Github issue for bugs only. I will close this for now, thanks!
