### ISSUE TITLE
rendering error in Readme.rst

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2577]
There seems to be some problem in the rendering, also the links are not working:
![screenshot from 2017-09-19 11-35-14](https://user-images.githubusercontent.com/12952641/30585948-ae8ed862-9d2e-11e7-809a-87a2085ea7a0.png)

**Comment by twiecki** [comment]
This is on github?

**Comment by twiecki** [comment]
It's displaying correctly on the site as sphinx resolves these local references, but github doesn't know about them. The only solution is to go back to direct links for the readme.

**Comment by ColCarroll** [comment]
Any interest in just redirecting the github pages traffic to the new site?

https://stackoverflow.com/questions/30167113/redirect-github-pages-to-custom-domain

looks like it'd be just a `CNAME` file in the top level with `docs.pymc.io`

**Comment by twiecki** [comment]
We do set the CNAME.
