### ISSUE TITLE
Start ADVI with initialization 

### ISSUE THREAD

**Issue by messcode** [pymc-devs/pymc#2586]
I built a probabilistic model and I want to investigate the convergence property of  latent parameter every  N steps. The procedure can be summarized as follows: 
``` python
import pymc3 as pm
means = None
for dummy_i in xrange(10):
    with my_model:
        (means, std, elbos) = pm.variational.advi(n=N, start=means)
    check_means(means) 
```
I intend to track the model performance with iterations. However, I found it is relying on the step length N.  In my case, when N=5000,  I found that the model performance( AUC) is fluctuating at around 0.6. N =10000, the model performance is approaching 1 and the final model performance is around 0.9. It seems that stopping advi and continuing with the means of parameters gets a different result. 
So my problem is how can I stop iteration and continue? 
Thanks in advance.

**Comment by junpenglao** [comment]
Hi @messcode,
Please post non-bug related question to [our discourse](https://discourse.pymc.io/). I will close this for now.
Thanks!

**Comment by messcode** [comment]
@junpenglao  sorry for that.  I have post my question on [it](https://discourse.pymc.io/t/advi-start-with-initialization/359)

**Comment by junpenglao** [comment]
No worries ;-) I will answer you there.
