### ISSUE TITLE
a meteorological model writed by Fortran

### ISSUE THREAD

**Issue by dreamqin68** [pymc-devs/pymc#2591]
I have a work to run a meteorological model through pymc3. But the model is not simple explicit, and it has many files writed by Fortran. 
The model runned by a executable file eveytime.
In pymc3, it needs 'with model' . so how to write it make the model rationalization in pymc3 ?
can package model in it?

**Comment by fonnesbeck** [comment]
Please post general questions to [our Discourse page](https://discourse.pymc.io). Closing.
