### ISSUE TITLE
Broken links on docs.pymc.io website

### ISSUE THREAD

**Issue by mattooca** [pymc-devs/pymc#2594]
I'm trying to look at the examples on http://docs.pymc.io/notebooks/GP-Covariances.html, but getting a 404 - File Not Found error.
To get there I followed the link from http://docs.pymc.io/examples.html#gaussian-processes.  Other links on that page are working, but nothing in the GP-Covariances section.

**Comment by bwengals** [comment]
Yeah, this is a known issue (#2554).  This should be fixed on master, the docs will show up properly online when they get rebuilt next.

**Comment by twiecki** [comment]
Should be fixed. Can you try?

**Comment by mattooca** [comment]
Yes, it's working now. Thanks!
