### ISSUE TITLE
Covariance matrix in Metroplis Step

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#260]
I've been having some issues with using a covariance matrix in the Metrepolis step.  Here is some example code:

```
import pymc

n = 10

with pymc.Model() as model:
    alpha = pymc.distributions.Flat('alpha', shape=(n))
    model.AddPotential(-1 * (alpha ** 2.).sum())
    start = pymc.find_MAP()
    h = pymc.approx_hessian(start)
    step = pymc.Metropolis(model.vars, S=h)
    trace = pymc.sample(3000, step, start)
```

This code raises an error:

```
pymc/step_methods/metropolis.pyc in astep(self, q0, logp)
     95             self.accepted = 0
     96 
---> 97         delta = self.proposal_dist() * self.scaling
     98 
     99         q = q0 + delta

/pymc/step_methods/metropolis.pyc in __call__(self)
     21 class NormalProposal(Proposal):
     22     def __call__(self):
---> 23         return normal(scale=self.s)
     24 
     25 
numpy/random/mtrand.so in mtrand.RandomState.normal (numpy/random/mtrand/mtrand.c:9268)()
```

If I disable the proposal covariance, things run fine:

```
with pymc.Model() as model:
    alpha = pymc.distributions.Flat('alpha', shape=(n))
    model.AddPotential(-1 * (alpha ** 2.).sum())
    start = pymc.find_MAP()
    h = pymc.approx_hess(start)
    step = pymc.Metropolis(model.vars)
    trace = pymc.sample(3000, step, start)
```

If I use an identity matrix for the proposal distribution, I _still_ get the error.  Am I building my model incorrectly, or is there something wrong here?

**Comment by kyleabeauchamp** [comment]
I'm using the latest GIT of pymc3.

**Comment by jsalvatier** [comment]
I _think_ the problem is that NormalProposal doesn't take a covariance
matrix, just an array of stdevs.

You can either use MultivariateNormalProposal instead or pass an array of
ones. Also, the hessian is something like a precision matrix, not a
covariance matrix, so you shouldn't pass it to Metropolis since its
expecting a covariance matrix. Try inverting first or passing the identity.

We should probably have NormalProposal accept a covariance matrix or at
least give better errors.

**Comment by kyleabeauchamp** [comment]
Thanks, that was the problem.  Here is the fix:

```
step = pymc.Metropolis(model.vars, h, proposal_dist=pymc.step_methods.MultivariateNormalProposal)
```

**Comment by jsalvatier** [comment]
I think you probably also want to set `h = eye(n)` or `h =
numpy.linalg.inv(h)`.

**Comment by kyleabeauchamp** [comment]
Sounds good, I'll fix that too.
