### ISSUE TITLE
Multiprocessing by default in sample

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2611]
As we know, the default setting for multiprocessing (`njobs`) in `sample` is 1. We should change this to at least two chains, both for efficiency and to facilitate Gelman-Rubin estimation. Given the prevalence of multi-core machines, there does not seem to be a good reason for defaulting to single core. 

This raises the question of how the number of chains relates to the number of samples. If we are multiprocessing, the `draws` argument ought to be split evenly among the cores. Thus, you get `draws` number of samples total, irrespective of the number of cores used to generate them. 

This seems like better default behavior to me, and would improve the overall user experience.

**Comment by kyleabeauchamp** [comment]
I recall seeing some Theano GPU bugs that only appeared with multiprocessing.  Not sure if we fixed all of them, but that would be one downside to this.

**Comment by fonnesbeck** [comment]
True, though it can always be set to `njobs=1` manually. Default behavior should be what you want "most of the time", which I am arguing is using >1 cores. Not sure if that default should be all available cores or just 2 or 4 of them.

**Comment by arose13** [comment]
I think all available cores is a good default. It is also the same default at TensorFlow is that is some form of validation

**Comment by aseyboldt** [comment]
How about `min(4, CPUs)`? That way we don't suddenly start 20 chains on a multi socket machine. Also, we mean number of cores, not hardware threads, right?

On October 5, 2017 12:52:08 AM CEST, Stephen Anthony Rose <notifications@github.com> wrote:
>I think all available cores is a good default. It is also the same
>default at TensorFlow is that is some form of validation
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pymc-devs/pymc3/issues/2611#issuecomment-334312262

-Adrian

**Comment by junpenglao** [comment]
Agree with @aseyboldt.

**Comment by springcoil** [comment]
Great idea.

**Comment by aplavin** [comment]
But theano itself uses many cores even for njobs=1 (at least for some kinds of models). In such cases, it takes about twice the time to sample two chains of the same length. And if the default is 4 jobs it most probably will slow down the sampling process on machines with e.g. 4 cores/threads.

**Comment by fonnesbeck** [comment]
We should be able to come up with a good default, which is neither 1 nor n. I think its good statistical practice to have >1 chain.

**Comment by junpenglao** [comment]
fixed in #2613
