### ISSUE TITLE
Can I instantiate multiple random walks with different means

### ISSUE THREAD

**Issue by jrmxn** [pymc-devs/pymc#2612]
I am wondering if someone can tell me if this does what I think it does:

`HP = pm.Normal('HP', mu =0, sd= 1, shape = n2)`
`gm = pm.GaussianRandomWalk('gm', mu = HP, sd = 1, shape = (n1, n2))`

Which is to make n2 independent random walks each of length n1, each with a drift instantiated from each element of HP?

The line runs, but I can't find an explanation of how shape is handled here - tried looking in the code too, but 

If not maybe I can do this with a MvGaussianRandomWalk, with identity covariance and mean set to HP?

Thanks!

**Comment by AustinRochford** [comment]
Since this is not obviously a bug, it's better to ask on [Discourse](https://discourse.pymc.io/) than in GitHub issues.
