### ISSUE TITLE
Upgrading backend away from Theano

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#2620]
Hi all, 

Apologies if this is already been discussed elsewhere. But as you know Theano 1.0 will be the last release which means PyMC3 will have to move away from it. I was hoping to maybe help out with this. I assumed that there would be pymc3 backend/ engine in the source that imported all relevant basic functions from theano into pymc3 (similar to [keras backend](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py)) but couldn't find it.

Can someone point me in the direction/ source files I could get started in helping with the migration process. Can't promise anything given my coding skills but worth a shot maybe.

Cheers,
Sachin

**Comment by fonnesbeck** [comment]
This discussion is ongoing on our Discourse page. Unfortunately it’s not as simple as plugging in a new backend, as Theano is tightly integrated into PyMC3. We are considering several options.

**Comment by alfredaita** [comment]
Is there further progress in this area, I have never been able to install Theano on windows 10 python 3.6
 I have had success with tensorflow ; tensorflow-gpu

**Comment by fonnesbeck** [comment]
PyMC is very tightly integrated with Theano, so any changes to a new backend will involve extensive development, and therefore be part of a longer process than most changes to the project. Look for a new backend in PyMC4, but we have no timeline yet.
