### ISSUE TITLE
Handling missing gradients in sampler auto-assignment

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2625]
## Problem
The current implementation of sampler auto-assignment only looks at the `RandomVariable`s being `Continuous` or `Discrete` to determine the `Competence` and assign methods.

This fails whenever the computation graph involves a custom theano `Op` that does not implement a `grad` for whatever reason.

I believe it should be possible to check both the type (`Continuous`/`Discrete`) and the availability of the gradient **before** attempting to assign a sampler.

This can be achieved by attempting to get the gradient, but catching the expected exceptions.

## Example
```python
import numpy
import pymc3
import theano
import theano.tensor as tt

real_a = 0.6
real_b = 2.4
x = numpy.linspace(0, 10, 5)
real_data = real_a * x + real_b
real_data = numpy.random.normal(loc=real_data, scale=0.3)


class UndifferentiableLinregOp(theano.Op):
    """This is a theano Op that becomes a node in the computation graph.
    It is not differentiable, because the output is computed in Python.
    """
    __props__ = ("x",)

    def __init__(self, x):
        self.x = x
        return super().__init__()

    def __hash__(self):
        subhashes = (
            hash(type(self)),
            hash(self.x.tostring())     # because numpy.ndarray is not hashable
        )
        return hash(subhashes)

    def make_node(self, inputs:list):
        a = tt.as_tensor_variable(inputs[0])
        b = tt.as_tensor_variable(inputs[1])
        apply_node = theano.Apply(self,
                            [a,b],              # symbolic inputs
                            [tt.dmatrix()])     # symbolic outputs
        return apply_node

    def perform(self, node, inputs, output_storage):
        a, b = inputs
        y = a * self.x + b
        output_storage[0][0] = numpy.array([y])
        return

    # when this is implemented according to theano's recommendation
    # http://deeplearning.net/software/theano/sandbox/how_to_make_ops.html#grad ->
    #   "If the op is not differentiable wrt one of its inputs, the gradient
    #    for that input should be None; if the op is not differentiable with
    #    respect to any of its inputs, it should return something equivalent
    #    to [None] * len(inputs). If grad is not implemented for any op in a
    #    graph, then the symbolic gradient engine will complain (with an attribute exception)."
    # then theano.gradient.NullTypeGradError or NotImplementedError is raised
    # but not caught by pymc3
    def grad(self, inputs, outputs):
        # theano.gradient.grad_undefined or theano.gradient.grad_not_implemented
        # are both acceptable
        return [theano.gradient.grad_undefined(self, k, inp,
                        'No gradient defined through UndifferentiableLinregOp.')
                for k, inp in enumerate(inputs)]

    def infer_shape(self, node, input_shapes):
        return [(len(self.x),)]

with pymc3.Model() as pmodel:
    a = pymc3.Beta("a", alpha=2, beta=5)
    b = pymc3.Normal("b", mu=2, sd=1)

    # make a prediction (y = (a * x + 0) + b)
    incline = UndifferentiableLinregOp(x)([a, 0])   # no gradient available
    shifted = incline + b                           # gradient available
    y_obs = pymc3.Normal("y", mu=shifted, sd=0.3, observed=real_data)

    multitrace = pymc3.sample()
    # expected:
    # a -> Metropolis
    # b -> NUTS
    # actual:
    # AttributeError: 'UndifferentiableLinregOp' object has no attribute 'grad'
    # OR (when grad is implemented according to theano specification)
    # theano.gradient.NullTypeGradError
```

I'll start working on a solution and open a PR accordingly.

**Comment by michaelosthege** [comment]
Some initial analysis:
1. the auto-assignment of NUTS assumes that `tt.grad(RV, model.logpt)` works for any RV, which is clearly **not** the case
2. `assign_step_methods` should be the default
3. `method._competence(var)` should also consider if `tt.grad(var, model.logpt)` works

So there's an API change required here. The least invasive way I can think of would be to introduce a new kwarg `has_grad=None` to `BlockedStep._competence`:

```python
class BlockedStep(object):
    ...
    @staticmethod
    def competence(var, has_grad=None):
        return Competence.INCOMPATIBLE

    @classmethod
    def _competence(cls, vars, have_grad=None):
        if have_grad is None:
            have_grad = [None] * len(vars)
        vars = np.atleast_1d(vars)
        have_grad = np.atleast_1d(have_grad)
        competences = []
        for var, has_grad in zip(vars, have_grad):
            if "has_grad" in inspect.signature(cls.competence).parameters:
                competences.append(cls.competence(var, has_grad))
            else:
                competences.append(cls.competence(var))
        return competences
```

In `assign_step_methods` we can then try `tt.grad` for each RV and feed `True/False` to `method._competence`:

```python
for var in model.free_RVs:
    if var not in assigned_vars:
        has_grad = True
        try:
            tt.grad(model.logpt, [var])
        except:
            has_grad = False

        selected = max(methods, key=lambda method, var=var: method._competence(var, has_grad))
        pm._log.info('Assigned {0} to {1}'.format(selected.__name__, var))
        selected_steps[selected].append(var)
```

It is then up to the implementation of the stepper to consider the additional information.

Within  `assign_step_methods` we can then group the assignments and if NUTS was assigned to each RV, proceed with `init_nuts`.


Any thoughts/alternatives?

**Comment by fonnesbeck** [comment]
More robust auto-assignment would definitely be welcome, and checking for the availability of gradients is an obvious place to start. Off hand, I would suggest leaving it up to each distribution to self-identify as having a gradient or not, with appropriate defaults depending on the class of distribution. We definitely want to avoid slowing down initialization a great deal.

**Comment by michaelosthege** [comment]
Unfortunately it's not up to the distribution to decide, because the distributions don't know about the arbitrary theano operations inbetween (such as the custom Op above).  And unless `tt.grad` (thereby `Op.grad`) is invoked, one does not actually know if the gradient is available.

When the grad is computed the first time, it may take a while, but theoretically the second time (done by the sampler) should then be much faster.

But you are right that `tt.grad` on discrete RVs should not even be attempted!

**EDIT:** `@theano.as_op` also does not provide gradients
