### ISSUE TITLE
The README file has inconsistent syntax and is displayed incorrectly on GitHub

### ISSUE THREAD

**Issue by Naereen** [pymc-devs/pymc#2626]
The README file has inconsistent syntax and is displayed incorrectly on GitHub: the `:ref:...` syntax is fine when the file gets processed by Sphinx but not for the default rST viewer used on GitHub.

**Comment by junpenglao** [comment]
Thanks for reporting @Naereen, the same issue is already reported in https://github.com/pymc-devs/pymc3/issues/2577.

**Comment by Naereen** [comment]
Hi, OK sorry for the double issue. I tried to fix it (more useful than an issue)...

**Comment by Naereen** [comment]
This should fix the inconsistent rST markup in README.rst (see #2577 and #2626).

At least it fixes the display on GitHub website, can anyone confirm that it will not break the links in the doc?
