### ISSUE TITLE
Bare import takes ~1.2s

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2630]
## Description of your problem
On my machine, importing `pymc3` takes ~1.2s.  It seems somewhat unavoidable, but wanted to mention it in case anyone had ideas.

**Please provide a minimal, self-contained, and reproducible example.**
In a fresh `conda` environment:
```
$ conda install -c conda-forge pymc3
...
$ pip install cprofilev
...
$ echo 'import pymc3' > check.py 
$ cprofilev check.py 
[cProfileV]: cProfile output available at http://127.0.0.1:4000
```
**Please provide the full traceback.**
`897272 function calls (875407 primitive calls) in 1.233 seconds`

**Please provide any additional information below.**
It looks like the main culprits are 
* `theano`: (0.414s)
* `pandas`: (0.222s)
*  `matplotlib`: (0.166s)
*  `scipy`: (0.116s)

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 0.9.0
* Python Version: 3.6.3 (anaconda)
* Operating system: OSX
* How did you install PyMC3: (conda/pip) conda

**Comment by junpenglao** [comment]
Is it get better under theano 1.0?

**Comment by ColCarroll** [comment]
Nope: pretty similar.  

4 months with no ideas on how to fix, whether it is worth fixing, or whether it even bothers anyone else, so I'm marking as closed (arguably, making matplotlib optional helped!)

 Will reopen if I get any bright ideas!
