### ISSUE TITLE
Ordered transformation

### ISSUE THREAD

**Issue by bwengals** [pymc-devs/pymc#2631]
Been working on a regression model where the output was ordinal.  This might also be handy for mixture models.  Any interest in adding this to the code base?   If so I'll submit a WIP PR with what I have started.

**Comment by junpenglao** [comment]
I have been bugging @aseyboldt to add this for some time, he has an implementation [on Discourse](https://discourse.pymc.io/t/mixture-models-and-breaking-class-symmetry/208/5?u=junpenglao)

**Comment by twiecki** [comment]
@bwengals Definitely!
