### ISSUE TITLE
sample_ppc uses a single chain only

### ISSUE THREAD

**Issue by aplavin** [pymc-devs/pymc#2633]
Judging both by the behavior of `sample_ppc` and its implementation code I see that it samples from a single chain of a `MultiTrace`. I guess that's because indexing into such trace returns samples from a single chain only and its `len()` is equal to the number of samples per chain. Not sure if that's on purpose, but it's certainly unexpected.

## Versions and main components

* PyMC3 Version: 3.1
* Theano Version: 0.9.0
* Python Version: 3.6
* Operating system: Linux
* How did you install PyMC3: conda

**Comment by junpenglao** [comment]
Thanks for reporting @aplavin. @AustinRochford was working on a PR a while back https://github.com/pymc-devs/pymc3/pull/2460. 

Any recent progress @AustinRochford?

**Comment by junpenglao** [comment]
Oops found it, actually I think this is already resolved: https://github.com/pymc-devs/pymc3/pull/2567

**Comment by aplavin** [comment]
@junpenglao well, it doesn't look resolved. I have e.g. the `points` iterator defined there, but `sample_ppc` doesn't use it anyway.

**Comment by junpenglao** [comment]
Oh I see. PR welcome ;-)
