### ISSUE TITLE
Impossible to get ppc samples corresponding to specific trace samples with sample_ppc

### ISSUE THREAD

**Issue by aplavin** [pymc-devs/pymc#2634]
Sometimes I need samples both from model parameters (which are contained in a trace) and ppc samples corresponding to exactly these values of parameters, e.g. for some further computations. There is no way to generate them using `sample_ppc` as it can take random trace samples only. Currently, I use this ad-hoc implementation which generates a single ppc sample per sample from the trace:

```python
def sample_ppc(trace, vars, size=None):
    try:
        ppc = defaultdict(list)
        for param in trace.points():
            for var in vars:
                ppc[var.name].append(var.distribution.random(point=param,
                                                             size=size))
    except KeyboardInterrupt:
        pass
    return {k: np.asarray(v) for k, v in ppc.items()}
```

As a bonus, this correctly takes samples from all chains of a multitrace (see #2633).

I could make a PR with something similar but want to hear your input on how to structure it better:
* Just add an argument to `sample_ppc` like `deterministic=False` which, when enabled, turns samples into ppc samples 1-to-1.
* or ditch random indices from `sample_ppc` altogether as I don't see why they are needed - trace samples are already random. So we can just take the number of ppc samples required and generate them, possibly either skipping some samples (if trace contains more than needed) or generating several ppc samples per single sample from the trace (if trace contains less). This also solves #2633 :)

## Versions and main components

* PyMC3 Version: 3.1
* Theano Version: 0.9.0
* Python Version: 3.6
* Operating system: Linux
* How did you install PyMC3: conda

**Comment by junpenglao** [comment]
> or ditch random indices from sample_ppc altogether as I don't see why they are needed - trace samples are already random. So we can just take the number of ppc samples required and generate them, possibly either skipping some samples (if trace contains more than needed) or generating several ppc samples per single sample from the trace (if trace contains less). 

I like this solution ;-)

**Comment by aloctavodia** [comment]
Agree with @junpenglao, the second solution looks nice
