### ISSUE TITLE
Add benchmark models

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2638]
Thanks to the work from @ColCarroll and @TomAugspurger in https://github.com/pymc-devs/pymc3/pull/1829 we now have a way to benchmark: http://pandas.pydata.org/speed/pymc3/ 

We should port some of the models from our docs to have more benchmark model to better cover our code base. The following comes to mind:

- [ ] Variational Inference
- [x] Mixture model
- [ ] GP
- [x] Same model with different sampling initialization (e.g., adapt_diag vs adapt_diag_grad)

**Comment by aseyboldt** [comment]
It would also be great if we could report effective samples per second for some models. Or is the benchmark limited to looking at the time?

**Comment by ColCarroll** [comment]
That's a great idea.  I _don't_ think you could benchmark both time and effective samples in one go, but looks like it would be added under the "generic tracking":

http://asv.readthedocs.io/en/latest/writing_benchmarks.html#tracking-generic

I may add another instance of the `radon` model to watch ESS.

**Comment by springcoil** [comment]
I made a first stab at the mixture model. I hope that'll work.
