### ISSUE TITLE
Severe memory leaks on Amazon AWS Linux platform

### ISSUE THREAD

**Issue by spudthorpe** [pymc-devs/pymc#2646]
Please see thread:
https://discourse.pymc.io/t/excessive-memory-usage-in-pymc3-solved-aws-linux-platform-issue-works-on-aws-windows/446/9

PyMC3 3.2 and 3.1, Python 3.5.2, Theano 0.9.0, Ubuntu 16.04

Tried running the notebook at https://github.com/twiecki/WhileMyMCMCGentlySamples/blob/master/content/downloads/notebooks/random_walk_deep_net.ipynb

on an AWS Ubuntu instance. The python process allocated about 100MB of memory per second; allocated memory kept growing until the machine was effectively dead from memory swapping. The notebook exhausted memory on 61GB, 122GB, and 244GB instances. I also saw similar behavior on Amazon Linux but primarily investigated on Ubuntu. I tried the HDF5 backend and it did not make a difference.

The same setup worked fine on an AWS Windows instance.

There are other issues open reporting a similar problem:
https://github.com/pymc-devs/pymc3/issues/1825
https://github.com/pymc-devs/pymc3/issues/1959

**Comment by junpenglao** [comment]
Hi @spudthorpe, could you try again from pymc3 master? @ferrine removed a few theano copy and the issue might be fixed now.
