### ISSUE TITLE
NUTS sampler - on divergence during tuneup - tries to write weird tuple to backend

### ISSUE THREAD

**Issue by arabidopsis** [pymc-devs/pymc#2648]
This shows up when - say- using the HDF5 backend (The error I get is
the same as #2347). The diverging dtype for HDF5 is bool
but the NUTS sampler tries to write a tuple created from the _Tree._single_step
method in nuts.py .
viz:
`("Energy change in leapfrog step is too large: %s. "  % energy_change ,None, Edge(...))`

The extend method doc say that it 
Returns a tuple `(diverging, turning)` of type (bool, bool). So this can't be right.

This might happen also if a `LinAlgError during leapfrog step.` error occurs due to
fall through to end.

Looks like you want to return more information than just True/False so
I don't known if the cleanup should occur in the extend  method or if the backend should
do the check.

Software	Version
Python	3.5.2 64bit [GCC 5.4.0 20160609]
IPython	6.2.1
OS	Linux 4.4.0 83 generic x86_64 with LinuxMint 18.1 serena
pandas	0.21.0rc1
numpy	1.13.3
pymc3	3.1

**Comment by aseyboldt** [comment]
This might be the same thing as in #2467. Could you update to 3.2 and see if that fixes this?
The docstring of `_Tree.extend` is wrong in master as well though, I'll submit a fix for that.

**Comment by arabidopsis** [comment]
Yes upgrading to 3.2 (sorry about that) removes the error  but  I think
that's because no diverging steps are now produced on my models during warmup -- despite my best efforts (well done pymc3 team!)

I still think the `nuts.py::_single_step` code as it exists currently on github is wrong. But your
comment shows that you are on to this.

**Comment by junpenglao** [comment]
This should be fixed now.
