### ISSUE TITLE
Progressbar prints to console on Windows + Jupyter notebook + multiprocessing

### ISSUE THREAD

**Issue by kpei** [pymc-devs/pymc#2653]
Whenever I try to sample multiple chains (njobs > 1), the output gets printed on the console instead,

[https://discourse-cdn-sjc1.com/standard5/uploads/pymc3/optimized/1X/31d080e55f6d0c404f5d38c31270632a58545cae_1_690x140.png](url)

Not a huge issue but perhaps something to add to the list? I feel like the combination of notebook + windows platform often throws multiprocessing under the bus and produces a lot of bugs. I’ve also encountered other issues but currently have trouble consistently replicating it.

**Comment by twiecki** [comment]
The reason is probably that the output location (the NB) is not carried over to the subprocesses spawned via `joblib`.

**Comment by twiecki** [comment]
https://github.com/joblib/joblib/issues/266

Are you up-to-date on jupyter?

**Comment by junpenglao** [comment]
Seems nothing much could be done on our side, closing for now.
