### ISSUE TITLE
README file links return 404 on github page

### ISSUE THREAD

**Issue by motatoes** [pymc-devs/pymc#2655]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem
The links to the notebooks in the [readme file](https://github.com/pymc-devs/pymc3/blob/c32a09736824dd3a13369cedc091d141336fe130/README.rst) point to `/notebooks`. Alot of these links don't work on the github page because they are linking to the symlink `/notebooks` which then points to `docs/source/notebooks/`. These links to the notebooks need to updated to point to `/docs/source/notebooks`

**Please provide a minimal, self-contained, and reproducible example.**
- Visit the [README file](https://github.com/pymc-devs/pymc3/blob/c32a09736824dd3a13369cedc091d141336fe130/README.rst) in a browser.
- Click on the link of 'API quickstart guide' which currently points to https://github.com/pymc-devs/pymc3/blob/master/notebooks/api_quickstart.ipynb 
- You will receive a github 404 error

**Comment by junpenglao** [comment]
FYI:
https://github.com/pymc-devs/pymc3/pull/2629
and
https://github.com/pymc-devs/pymc3/pull/2627#issuecomment-338683377

**Comment by motatoes** [comment]
Changed to hardcoded links in PR https://github.com/pymc-devs/pymc3/compare/master...motatoes:fix-docs-404
