### ISSUE TITLE
Terminal hangs on exit when using PyMC 3

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#267]
I'm not sure what is responsible for this (a Theano issue?), but when I am using PyMC 3 from the Python/iPython command prompt on OSX (10.8.3), exiting the session (e.g. via ctrl-d), the terminal frequently hangs and the entire terminal window must be forcibly closed. Anyone else get this?

**Comment by jsalvatier** [comment]
I have occasionally seen this after some parallel sampling, especially if
something has gone wrong.

**Comment by twiecki** [comment]
Is the parallel sampling using python multiprocessing?

**Comment by jsalvatier** [comment]
Yup.

**Comment by twiecki** [comment]
Yeah, multiprocessing is annoying in this way. A better alternative is IPython parallel which also runs on multi-host settings, allows debugging and has better error handling overall. IPython is also not an unreasonable dependency I think so that's something to consider.

**Comment by jsalvatier** [comment]
Interesting, it still allows us to call it in a nice programatic way?

**Comment by fonnesbeck** [comment]
[Here is a nice intro presentation](http://vimeo.com/63262448) that Min gave at PyData.

**Comment by jsalvatier** [comment]
Do we know if this is still an issue?

**Comment by fonnesbeck** [comment]
Haven't seen it in awhile. Closing.
