### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by NateAM** [pymc-devs/pymc#2670]
When sampling from an external theano function I received the following error message:

    Warning: gradient not available.(E.g. vars contains discrete variables). MAP estimates may not be accurate for the default parameters. Defaulting to non-gradient minimization 'Powell'.
    logp = -1,006.1:   8%|█████                                                         | 413/5000 [00:39<07:22, 10.36it/s]

    Optimization terminated successfully.
             Current function value: 1006.091766
             Iterations: 5
             Function evaluations: 414

    Auto-assigning NUTS sampler...
    Initializing NUTS using jitter+adapt_diag...
    Initializing NUTS failed. Falling back to elementwise auto-assignment.
    Assigned Slice to t_params_interval__
    Assigned NUTS to sigma_log__

    logp = -1,006.1:   8%|█████▏                                                        | 414/5000 [00:50<09:14,  8.27it/s]
    Exception in thread Thread-35:
    Traceback (most recent call last):
      File "C:\Users\Natha\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
        self.run()
      File "C:\Users\Natha\Anaconda2\lib\site-packages\tqdm\_tqdm.py", line 144, in run
        for instance in self.tqdm_cls._instances:
      File "C:\Users\Natha\Anaconda2\lib\_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
    RuntimeError: Set changed size during iteration`

Similarly, I have been unable to use multiple cores. The pymc model is given here:

    data = tt.shared(s11s[0])
    rate = tt.shared(nominal_rates[0])

    number_maxwell_elements = 3

    t_params = tt.shared(np.zeros([2+2*number_maxwell_elements]))

    tausm  = tt.tensor.as_tensor_variable(np.array([1e-1,1e0,1e1]))

    with pm.Model() as model:
        #Parameter defintions
        t_params = pm.Uniform("t_params", lower=0., upper=100., shape=(5,))
        Km    = pm.Deterministic("Km", t_params[0])
        Ginfm = pm.Deterministic("Ginfm", t_params[1])
        Gsm   = pm.Deterministic("Gsm", t_params[2:])
        sigma = pm.HalfNormal('sigma', sd=1)
    
        #Evaluate the response
        response = pm.Deterministic("response",evaluate_trace(rate,t_params,tausm,tt.tensor.as_tensor_variable(npts)))
    
        measured_stress   = pm.Normal( "measured_stress", mu=response, sd = sigma, observed=data)#data)
    
        start = pm.find_MAP(fmin=sciopt.fmin_powell)

        traces = pm.sample(500,njobs=1,start=start)

The full jupyter notebook of the problem is available [here](https://github.com/NateAM/constitutive_optimization/blob/master/viscoelasticity.ipynb). Once the iterations should have been completed, the model proceeds to re-run the iterations again. I suspect this is related to [this issue](https://github.com/pymc-devs/pymc3/issues/1991).

## Versions and main components

* PyMC3 Version: PyMC3 3.2 (October 10, 2017)
* Theano Version: 0.9.0
* Python Version:  Python 2.7.13 :: Anaconda, Inc.
* Operating system: Windows 10
* How did you install PyMC3: pip from github

**Comment by omelnikov** [comment]
It seems to be related to `tqdm` package. Here is a [related discussion](https://github.com/tqdm/tqdm/issues/481).

**Comment by NateAM** [comment]
Okay, I will try and test that out when I can. Thanks for letting me know.
