### ISSUE TITLE
Slice sampling can get stuck

### ISSUE THREAD

**Issue by rdturnermtl** [pymc-devs/pymc#2712]
There are 3 while loops in astep() in pymc3/step_methods/slicer.py on lines 56, 58, and 62. These can get stuck for a very long time if given an oddly shaped distribution.

The simplest fix for this is to add some sort of loop counter that throws an error when a max iterations limit has been exceeded. A quick implementation of this can be found in:
https://github.com/rdturnermtl/pymc3/blob/slicer_safe/pymc3/step_methods/slicer.py

However, the original Neal (2003) paper also describes a window doubling procedure that would not be as prone to getting stuck. Perhaps that should be the fall back mode?

Maybe there is a way to fall back to a random walk Metropolis step if slice sampling gets stuck and still maintain detailed balance?

**Comment by junpenglao** [comment]
> However, the original Neal (2003) paper also describes a window doubling procedure that would not be as prone to getting stuck. Perhaps that should be the fall back mode?

I agree this seems an appropriate fall back option.

> Maybe there is a way to fall back to a random walk Metropolis step if slice sampling gets stuck and still maintain detailed balance?

If you mean if slice sampling stuck it restart with a MH sampler then yes. But in general, I dont think detailed balance is ensured if the previous (i.e., before slice sampler stuck) samples are kept.

> The simplest fix for this is to add some sort of loop counter that throws an error when a max iterations limit has been exceeded. 

I think your solution is reasonable, PR welcome ;-)

**Comment by rdturnermtl** [comment]
How do I upgrade this to a PR?

**Comment by junpenglao** [comment]
you can find more information here https://help.github.com/articles/about-pull-requests/

**Comment by ColCarroll** [comment]
You'll need to [fork the repo](https://help.github.com/articles/fork-a-repo/), make your changes locally, push them to your version, then open a pull request by navigating to your fork (and link this issue by adding the text "#2712" somewhere in the message).  

[This has more detail](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md#steps), though I think that file also needs some editing, so feel free to open issues about what is unclear there!
