### ISSUE TITLE
sample returns incorrect number of samples

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#2739]
`sample` currently returns the wrong number of iterations. 

```
In [1]: import pymc3 as pm
In [2]: with pm.Model() as m: x = pm.Normal('x')
In [3]: with m: trace = pm.sample(1000)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
100%|█████████████████████████████████████| 1500/1500 [00:00<00:00, 2277.61it/s]
In [4]: trace['x'].shape
Out[4]: (2000,)
```

There should only be 1000 samples here (500 from each chain, by default). The total number of iterations should always be the value passed, irrespective of how many chains are used to sample them.

Running current master on Python 3.6

**Comment by junpenglao** [comment]
it returns 1000 from each chain? as the tunning sample does not count

**Comment by fonnesbeck** [comment]
It’s sampling 1500 from each chain (500 tuning is the default) and keeping 1000 from each.
