### ISSUE TITLE
Feature request - Plots of divergences

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2745]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem
This is more a feature request than a problem - I might even hack it myself. 

**Please provide a minimal, self-contained, and reproducible example.**
In http://docs.pymc.io/notebooks/Diagnosing_biased_Inference_with_Divergences.html#A-Dangerously-Short-Markov-Chain there's some neat plots. Would they be useful as functions for plotting divergences for better diagnostics?

**Please provide the full traceback.**

**Please provide any additional information below.**

**Comment by springcoil** [comment]
@ColCarroll Any views on this?

**Comment by aloctavodia** [comment]
I think the people from STAN have this kind of plots _ready-to-use_, what about a diagnostic summary, could that also be useful?

**Comment by springcoil** [comment]
Yeah I think a diagnostic summary would also be excellent. I think my thinking was inspired by some Stan examples.

**Comment by junpenglao** [comment]
Something like Figure 5 in https://arxiv.org/pdf/1709.01449.pdf?

**Comment by springcoil** [comment]
Yeah figure 5 is what I had in mind

**Comment by aseyboldt** [comment]
#2677 should make that easier. You can access the warnings explicitly with that, and also see the exact point where the divergence happened. I still need to finish it up though...

**Comment by springcoil** [comment]
Any update on this?

**Comment by junpenglao** [comment]
I dont think anybody is actively working on this. But it should make a good beginner issue.

**Comment by agustinaarroyuelo** [comment]
I will try to work on this one

**Comment by junpenglao** [comment]
@agustinaarroyuelo you can have a look at http://docs.pymc.io/notebooks/Diagnosing_biased_Inference_with_Divergences.html - There is a prototype of how it would look like.
