### ISSUE TITLE
Ordered logistic log likelihood and rng

### ISSUE THREAD

**Issue by ColinMcAuliffe** [pymc-devs/pymc#2746]
Would it be possible to add an ordered logistic log likelihood?

Stan has a convenient implementation where you just pass in your linear predictor and a set of cut points. This would be a big help for doing ordinal logistic regression. Thanks! Colin

**Comment by bwengals** [comment]
This is part of PR #2637.  Hopefully we can get it in soon!

**Comment by junpenglao** [comment]
@bwengals any update on that PR?

**Comment by ColinMcAuliffe** [comment]
This may be related to the functionality the PR is implementing https://cran.r-project.org/web/packages/rstanarm/vignettes/polr.html

Note how they define the prior for the cutpoints, so that they are ordered by construction. Clever!

**Comment by bwengals** [comment]
Need to find a moment to finish that up.  There isn't too much to do, some tests on the transforms is all if I remember right.

**Comment by junpenglao** [comment]
close in #2637
