### ISSUE TITLE
Binder integration?

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2757]
Any interest in advertising binder (launches a live jupyter notebook into our examples directory) integration?  

Looks like @AustinRochford's docker file made it easy to build:
https://mybinder.org/v2/gh/pymc-devs/pymc3/master?filepath=%2Fdocs%2Fsource%2Fnotebooks

They have github badges, so I can just add a badge linking to the above URL if there are no objections.

More info here:
https://mybinder.readthedocs.io/en/latest/index.html

**Comment by fonnesbeck** [comment]
This is definitely something we should have.

**Comment by ColCarroll** [comment]
#2758
