### ISSUE TITLE
Applying stick breaking transform to multidimensional variables

### ISSUE THREAD

**Issue by aasensio** [pymc-devs/pymc#2765]
I'm trying to build a model in which there are some variables that need to add to 1 and these variables change in time following a Gaussian Random walk. An example of it is the following:

    stick = pm.distributions.transforms.StickBreaking()
    model = pm.Model()
    N = 10
    with model:
       s = pm.GaussianRandomWalk('s', mu=0.0, sd=1.0, shape=(N,2), 
              testval=np.ones((N,2)), transform=stick)
       trace = pm.sample()

It took me a while to make it work because the current stick transformation is only valid when the shape of the variable is square, i.e., `(N,N)`. In any other case, Theano complains about a mismatch between the dimensions of the Jacobian of the transformation and the call to the backward method of the transformation. 

A quick and dirty fix for this is to change the return value of `jacobian_det` in the `StickBreaking`class in `transforms.py` to:

    ....
    out = tt.sum(tt.log(S[:-1]) - tt.log1p(tt.exp(yl)) - tt.log1p(tt.exp(-yl)), 0).T
    return out[:,None] * tt.ones_like(yu.T)

Additionally, I need to add the testval to the definition of the random variable. Otherwise, I get the following error:
        
    276         x = x_.T
    277         # reverse cumsum
    --> 278         x0 = x[:-1]
    279         s = tt.extra_ops.cumsum(x0[::-1], 0)[::-1] + x[-1]
    280         z = x0 / s

    IndexError: too many indices for array

## Versions and main components

* PyMC3 Version: 3.2 (cloned from repository)
* Theano Version: 0.9.0
* Python Version: 3.6
* Operating system: MacOS

**Comment by junpenglao** [comment]
Contribution welcomes.
