### ISSUE TITLE
Build failing on travis

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2768]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or 
## Description of your problem
The build seems to be failing cc @ColCarroll 
**Please provide a minimal, self-contained, and reproducible example.**

**Please provide the full traceback.**

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by ColCarroll** [comment]
`test_clear_cache` fails intermittently.  I got it to fail twice in a row locally, but then it passed the next five times. I have also seen it fail repeatedly on travis, but sometimes it passes.  A mystery!

**Comment by junpenglao** [comment]
Maybe the delete cache is not run, what happen if we repeat the `del ` line?

**Comment by junpenglao** [comment]
This should be mostly fixed now. Some Tests are not very robust and I opened separate issues.
