### ISSUE TITLE
Weird behavior with GaussianRandomWalk + math.exp + Poisson

### ISSUE THREAD

**Issue by erikbern** [pymc-devs/pymc#2769]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

I'm trying to fit data to a time series model where the observations are event counts and I have missing values. A super dumbed down version below. I created an artificial time series consisting of `100 * [42]` and then 100 missing values, and then `100 * [42]` again.

When I use a normal distribution, it "works" – the timeseries drift a bit more during the gap:

```python
data = numpy.ma.masked_values([42] * 100 + [-1] * 100 + [42] * 100, value=-1)

with pymc3.Model() as model:
    s = pymc3.distributions.timeseries.GaussianRandomWalk('s', sd=1e-2, shape=len(data))
    n = pymc3.Normal('n', mu=pymc3.math.exp(s), observed=data)

    trace = pymc3.sample()
    pyplot.plot(trace['s'].T, alpha=0.1)
```

![image](https://user-images.githubusercontent.com/1027979/34505274-3e5c59ea-eff2-11e7-9473-cd026c928475.png)

However, when I try to model the event counts using a Poisson (of the exponent of the underlying timeseries), the series go down a lot for the missing values, in a weird way. Super confused why they would do that (there's nothing that penalizes the rates as far as I know)

```python
data = numpy.ma.masked_values([42] * 100 + [-1] * 100 + [42] * 100, value=-1)

with pymc3.Model() as model:
    s = pymc3.distributions.timeseries.GaussianRandomWalk('s', sd=1e-2, shape=len(data))
    n = pymc3.distributions.discrete.Poisson('n', mu=pymc3.math.exp(s), observed=data)

    trace = pymc3.sample()
    pyplot.plot(trace['s'].T, alpha=0.1)
```

![image](https://user-images.githubusercontent.com/1027979/34505350-b93a798a-eff2-11e7-8a0f-6482d1fdc1dd.png)

**Please provide the full traceback.**

```
Assigned NUTS to s
Assigned Metropolis to n_missing
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:42<00:00, 23.79it/s]
```

**Please provide any additional information below.**

What I really tried to do is to estimate a "Bayesian cone" of uncertainty of the future. In my original example, all missing values were after a certain point. 

I'm a severe newbie to PyMC3 and Bayesian methods, it's highly likely I'm just doing something dumb. I'll close this issue in a few days if no one has any ideas. Anyway, any pointers would be highly appreciated!

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 1.0.1
* Python Version: 3.6
* Operating system: OS X
* How did you install PyMC3: (conda/pip) pip

**Comment by junpenglao** [comment]
Hi @erikbern, could you please post this to our discourse https://discourse.pymc.io/? These kinds of questions are more suitable there.
I will close this for now.

**Comment by ColCarroll** [comment]
This looks like a bug to me – the missing values are stuck getting sampled at their initial value, and I cannot figure out how to unstick them...  in particular, if you pass a `start` dictionary, `n_missing` will stay at whatever value is in there.

**Comment by junpenglao** [comment]
Either that or the inefficiency of Metropolis, as if you sample `n_missing` with Slice sampler it is fine.

**Comment by erikbern** [comment]
I did get some better results if I increased the `tune` parameter a lot and set `discard_tuned_samples` to `True`. But not sure why it makes a huge difference to use Poisson rather than `Normal`

Anyway I think I'm just going to fit the model with no missing values, and then implement my own sampling. It's a bit unfortunate that I have to basically implement the same model twice, but seems more robust that way

**Comment by springcoil** [comment]
Have you worked out the bfmi or rhat etc

**Comment by erikbern** [comment]
> Have you worked out the bfmi or rhat etc

what's that? how do i do it?

**Comment by springcoil** [comment]
Let me see if I can do a demo tonight

On 3 Jan 2018 20:28, "Erik Bernhardsson" <notifications@github.com> wrote:

Have you worked out the bfmi or rhat etc

what's that? how do i do it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pymc-devs/pymc3/issues/2769#issuecomment-355118144>,
or mute
the thread
