### ISSUE TITLE
`test_sgfs.py` failed with njobs=1

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2784]
Discovered while trying to fix Travis test in #2777 
The fail seems quite consistent whenever sampling with `njobs=1`, setting `njobs=2, chains=4` fail quite a lot of times as well.
cc @shkr

**Comment by shkr** [comment]
okay. I will look into this.

**Comment by shkr** [comment]
Submitted PR with fix. 

While working on it, I found an issue where njobs=1, and chains > 1 generates redundant chains with index > 0. I can investigate this, I think I would prefer to handle it in a separate issue that I can create. Let me know if that makes sense to you.

**Comment by junpenglao** [comment]
Thanks.
Yep I notice the same thing. If you found a solution please send a separate PR.

**Comment by shkr** [comment]
Will do. I think it might have to do something with the fact, that when njobs=1, there is no re-initialization of the data feed, because of which subsequent chains (index>0) do not sample anywhere outside of the initial values, since gradients also don't change.

**Comment by junpenglao** [comment]
Good catch - ploting the trace when njobs=1, I find that the first chain usually looks fine, but then the second chain is just completely frozen.

**Comment by shkr** [comment]
@junpenglao The SGFS step method and other SG methods when initialized create State Variables. This means, when SequentialSampling, an initialized step method can be used only on one chain.

Based on this reasoning, I have updated sampling.py to create a deepcopy of an initialized step methods, whenever it starts sampling from a new chain.

Check the PR. Let me know if your feedback. If there is a better way around this, without creating a deepcopy, happy to make the change.
