### ISSUE TITLE
PyMC3- Unable to do numerical integration and incorporate into the user defined likelihood function

### ISSUE THREAD

**Issue by Lekshmi288** [pymc-devs/pymc#2785]
I am using PyMC3 for parameter estimation using a particular likelihood function which has to be defined. Here L is the analytic form of my Likelihood function. I have some observational data for the radial velocity(vr) and postion (r) for some objects, which is imported from excel file. My priors are M and beta which is assumed to be a uniform distribution. I am facing a problem in incorporating a numerical integration defined by li(beta) without which i am getting an output. But my likelihood requires li(beta). The following is my code and the error message i am getting.

`import pymc3 as pm`
`from pymc3 import find_MAP`
`import theano`
`import theano.tensor as tt`
`import pandas`
`import random as rm`
`import decimal as dm`
`data_ = np.array(pandas.read_excel('aaa.xlsx',header=None))`
`gamma=3.77;`
`G = 4.302*10**-6;`
`rmin = 3.0;`
`R = 95.7;`
`vr=data_[:,1];`
`r= data_[:,0];`
`h= np.pi;`

`basic_model = pm.Model()'

` with basic_model:`
 ` M=[]`
  `  beta=[]`
   ` interval=0.01*10**12`
    `M=pm.Uniform('M', lower=0.5*10**8, upper=3.50*10**13,transform='interval')`
    `beta=pm.Uniform('beta',lower=2.001,upper=2.999,transform='interval')`
    `gamma=3.77`
    `logp=[]`
    `arr=[]`
    `vnew=[]`
    `rnew=[]`
    `for j in np.arange(0,59,1):`
     `    vnew.append(vr[j]+(0.05*vr[j]*float(dm.Decimal(rm.randrange(1, 20))/10)))`
      `   rnew.append(r[j]+(0.05*r[j]*float(dm.Decimal(rm.randrange(1, 20))/10)))`
    `vn=np.array(vnew)`
    `rn=np.array(rnew)`

    `def integrand(theta,beta):`
     `   q =( gamma/(beta - 2)) - 3/2`
      `  return (tt.cos(theta))**(2*q + 3)`
    `def li(beta):`
     `   l=integrate.quad(lambda theta:integrand(theta,beta),-h/2,h/2)`
      `  return l[0]`
    `i=np.arange(0,59,1) `
    `q =( gamma/(beta - 2)) - 3/2`
    `B = (G*M*10**12)/((beta -2 )*( R**(3 - beta)))`
    `K = (gamma - 3)/((rmin**(3 - gamma))*li(beta)*((2*B)**0.5))`
    `logp= -tt.log(K*((1 -(( 1/(2*B) )*((vn[i]**2)*rn[i]**(beta - 2))))**(q+1))*(rn[i]**(1-gamma +(beta/2))))`
    `def logp_func(rn,vn):`
     ` return  tt.sum(logp)  `
    `logpvar = pm.DensityDist("logpvar", logp_func, observed={"rn": rn,"vn":vn})`
    `start = pm.find_MAP(model=basic_model)`
    `step = pm.Metropolis()`
   ` basicmodeltrace = pm.sample(10000)`
    `print(pm.summary(basicmodeltrace))`
    `map_estimate = pm.find_MAP(model=basic_model)`
    `print(map_estimate)`

i am getting the following error:

`runfile('E:/MCMC/theano_glob.py', wdir='E:/MCMC')`
`Traceback (most recent call last):`
 ` File "<ipython-input-22-7756059e0113>", line 1, in <module>`
   ` runfile('E:/MCMC/theano_glob.py', wdir='E:/MCMC')`
  `File "C:\Users\mypc\Anaconda3\Anaconda_3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile`
`   execfile(filename, namespace)`
`  File "C:\Users\mypc\Anaconda3\Anaconda_3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile`
   `exec(compile(f.read(), filename, 'exec'), namespace)`
 `File "E:/MCMC/theano_glob.py", line 56, in <module>`
    `K = (gamma - 3)/((rmin**(3 - gamma))*li(beta)*((2*B)**0.5))`
 ` File "E:/MCMC/theano_glob.py", line 51, in li`
    `l=integrate.quad(lambda theta:integrand(theta,beta),-h/2,h/2)`
 ` File "C:\Users\mypc\Anaconda3\Anaconda_3\lib\site-packages\scipy\integrate\quadpack.py", line 323, in quad
    points)`
  `File "C:\Users\mypc\Anaconda3\Anaconda_3\lib\site-packages\scipy\integrate\quadpack.py", line 388, in _quad`
    `return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)`

`TypeError: must be real number, not TensorVariable`

Any help is appreciated!

**Comment by aloctavodia** [comment]
Issues are mainly for bugs. This kind of question is better suited to our discourse channel, notice there is an open [thread](https://discourse.pymc.io/t/using-quad-from-scipy-integrate-with-pymc-rvs-as-parameter/613/5) about this very same issue.
