### ISSUE TITLE
Parameterization docs to fix.

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#2788]
I am creating this issue to keep track of what distributions have precision/variance parameterization, and whether I've put in PRs for the docs or not.

Check boxes to remind myself that they have been included in PR #2789.

- [x] Normal
- [x] LogNormal
- [x] HalfNormal
- [x] StudentT
- [x] HalfStudentT
- [x] AR
- [x] GaussianRandomWalk

This list is compiled from #2786, in which @ColCarroll grepped for `get_tau_sd`. Happy to have more added to the list. I will also reference exact PR.

Example from @fonnesbeck:

(1) Change docstring

```
sd : array of floats
        the component standard deviations (only required if tau is not specified)
tau : array of floats
        the component precision (only required if sd is not specified)
```

(2) Add Example

```
Examples
--------
with pm.Model():
    x = pm.Normal('x', mu=0, sd=10)
```

**Comment by fonnesbeck** [comment]
Let's target this for 3.4
