### ISSUE TITLE
Robustify test_variational_inference.py::test_clear_cache

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2791]
pymc3/tests/test_variational_inference.py::test_clear_cache failed (both locally and on Travis CI) 50% of the times, as `del inference` does not always delete the cache reliably.

**Comment by junpenglao** [comment]
Judging from the recent build on master, we should mark it as xfail under py2.7 float32

**Comment by fonnesbeck** [comment]
Let's do this before tagging 3.3, shall we?

**Comment by junpenglao** [comment]
fix in #2875
