### ISSUE TITLE
Bug in the new NUTS warning

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2800]
Getting a lot of `The chain reached the maximum tree depth. Increase max_treedepth, increase target_accept or reparameterize.` and found the bug below: 

https://github.com/pymc-devs/pymc3/blob/5eefc14b524378b1773d374004452b512523485a/pymc3/step_methods/hmc/nuts.py#L189

Since `self._reached_max_treedepth` is a non-negative integer this line will be true with 1 max_treedepth.
Changing it to something like `if self._reached_max_treedepth/nsample > 0.05: ` should work, but I think the nsample information is not available? cc @aseyboldt

**Comment by junpenglao** [comment]
Also, `_reached_max_treedepth` is currently also counting the ones in the tuning steps.

**Comment by aseyboldt** [comment]
Ah, you are right on both points. I'll fix this tomorrow.
I wanted to get that warning with >= 5% of samples reaching max_treedepth...

**Comment by junpenglao** [comment]
While you are at it maybe we can also change
https://github.com/pymc-devs/pymc3/blob/90215a8552d37d610f7ae1416a117073a5eb0306/pymc3/backends/report.py#L105-L107

warning at 25% seems too sensitive...
