### ISSUE TITLE
Weibull distribution has no mode.

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#2803]
I noticed in the codebase that the Weibull distribution has no mode defined. Is this because there are two modes possible depending on the parameter value of alpha (0 if alpha <= 1, and something if alpha > 1)? I'm asking because I'm trying to figure out how to do mixture Weibulls, which currently don't seem possible because of a lack of a defined mode.

**Comment by twiecki** [comment]
We can just add a mode with a switch-statement. PR welcome.

**Comment by ColCarroll** [comment]
Looks like this got merged
