### ISSUE TITLE
Example code in Mixture docs does not display correctly

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2806]
http://docs.pymc.io/api/distributions/mixture.html
PR: https://github.com/pymc-devs/pymc3/pull/2799
cc @ericmjl

**Comment by sharanry** [comment]
Hey, could I take this up?

**Comment by fonnesbeck** [comment]
@sharanry feel free to!

**Comment by sharanry** [comment]
@twiecki just realized `.. code-block:: python` is not added for many more example codes in `bound.py` too. I will change that too?

**Comment by twiecki** [comment]
Yes, that'd be great!

**Comment by ericmjl** [comment]
@sharanry yay! Thank you for contributing!! :smile:
