### ISSUE TITLE
Update effective sample size computation

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2810]
...without truncating it. See [blog post](http://andrewgelman.com/2018/01/18/measuring-speed-stan-incorrectly-faster-thought-cases-due-antithetical-sampling/).
Related Stan issue:
https://github.com/stan-dev/stan/issues/2450
and PR:
https://github.com/stan-dev/stan/pull/2451

**Comment by avehtari** [comment]
Truncate it. Just use the correct truncation.

**Comment by junpenglao** [comment]
Thanks for the clarification @avehtari! Will study your PR.

**Comment by avehtari** [comment]
More specific: Stan had wrong truncation of the autocorrelation series, which happened to lead capping also N_eff. Corrected truncation allows N_eff>N.

**Comment by sharanry** [comment]
Could I take this up?

**Comment by junpenglao** [comment]
@sharanry feel free to do so!

**Comment by huaTIANming** [comment]
Maybe I found another problem. 
The error, I think, goes down as **ess = ess / (1. + 2. * np.sum(rho_hat_t))**  in line 255 in diagnostics.py rather than ess = ess / (-1. + 2. * np.sum(rho_hat_t)) according to Gelman et al. BDA (2014).

**Comment by junpenglao** [comment]
The current implementation is correct. You can have a look at the discussion in the [Stan PR](https://github.com/stan-dev/stan/pull/2451).
