### ISSUE TITLE
Speed up random method for Multinominal

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2811]
Come across these two tweets, which might allow us to improve the speed of Multinominal random:
https://twitter.com/jeremyphoward/status/954871616277655552
https://twitter.com/RadimRehurek/status/928671225861296128

**Comment by ColCarroll** [comment]
Or, if you have some experience with `numpy`, this PR has lost some steam...

https://github.com/numpy/numpy/pull/9710

**Comment by junpenglao** [comment]
Ah cool! Why is that PR not merged?

**Comment by ColCarroll** [comment]
I _think_ the ball is in `numpy`'s court, though I really don't know enough Cython to reason about it. I'll ping that thread again and ask if there's something I could do.

**Comment by sharanry** [comment]
@junpenglao @ColCarroll Are we going to implement this at the pymc3 end?

**Comment by ColCarroll** [comment]
I would vote to leave the code as is, unless the numpy implementation gets a speedup: I am not sure of a case where multinomial sampling is the bottleneck, such that the added complexity of implementing something on our side is worth it.

**Comment by springcoil** [comment]
What is there to be done here? Replacing the np.random.choice with Radim's suggestion?

**Comment by ColCarroll** [comment]
I am going to just close (feel free to reopen if disagree!)

I doubt this is the bottleneck for anyone's analysis, and implementing radim's makes the code less readable, and means we would not get automatic speedups if/when changes are merged upstream (though still no word on the numpy pr).
