### ISSUE TITLE
Feature request: Sparse matrix compatibility for Minibatches

### ISSUE THREAD

**Issue by miksyr** [pymc-devs/pymc#2813]
Hi all,

I was wondering how easy it'd be to allow the use of csr sparse matrices in the Minibatch function?

I've got a large training set, and casting to dense before taking minibatches means that the RAM requirements explode with training size.  It'd be nice to have a flag for indicating a sparse input to Minibatch so that they can be expanded after the minibatch indexes have been chosen (so everything will scale more nicely).

I've played about with the Minibatch class a bit myself, but I'm having trouble wrapping my head around how this could actually work.

**Comment by kyleabeauchamp** [comment]
I've wanted to propagate sparsity further in models more, although not just in the minibatch module.

**Comment by miksyr** [comment]
What type of input does the 'replacements' or 'more_replacements' flag expect in it's dictionary?

It's usually {x: minibatch_x}, but is there an easy way to create a custom generator that takes a subset of indices from a sparse matrix, casts them as dense, and puts them in the "minibatch_x" part of the argument?  That way, only the minibatch that is needed is expanded

**Comment by mtvector** [comment]
Did anyone ever figure out how to do the minibatching with the more_replacements = {x: ?} for sparse matrices?

**Comment by canyon289** [comment]
Closing and deferring to discourse if this further discussion
