### ISSUE TITLE
sampling in GLM: Logistic Regression example very slow

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#2819]
Standardizing the data seems to help a little but still very slow. @springcoil maybe you want to take a look at this.

**Comment by springcoil** [comment]
Can you elaborate?

**Comment by fonnesbeck** [comment]
Probably poor default priors are being assigned. Can't imagine what else it could be.

**Comment by canyon289** [comment]
@aloctavodia let us know if you're still having issues, were closing as part of cleanup for now
