### ISSUE TITLE
Update notebooks and examples

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2834]
As discussed in the lab meeting today, we should update all notebooks and examples to the most recent recommended practice, including:
- remove find_MAP as initiating the sampling
- multiple chains
- update kwarg (especially after #2831)
- unify notebook format, eg: 
  - moving original author information to the bottom of the notebook
  - color style (maybe `plt.style.use('seaborn-darkgrid')`?)
  - move import below title (some are above)
- simplify http://docs.pymc.io/notebooks/getting_started.html (maybe a bit too formal as the content is mostly taken from the pymc3 paper)
- some notebook is not indexed on the website: eg updating_priors.ipynb

----
Checklist for updating notebook:
- move original author information to the bottom of the notebook
- remove find_MAP as initiating the sampling, use multiple chains and default sampling as much as possible
- update kwarg when possible
- move import below the title and use below format for the first cell
```python
%matplotlib inline
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('seaborn-darkgrid')
print('Running on PyMC3 v{}'.format(pm.__version__))
```

**Comment by aloctavodia** [comment]
thumbs up to `plt.style.use(['seaborn-darkgrid'])`

**Comment by junpenglao** [comment]
I think it fits well with our PyMC3 blue scheme

**Comment by aloctavodia** [comment]
just nitpicking, we can directly use `plt.style.use('seaborn-darkgrid')`

**Comment by junpenglao** [comment]
For ppl participating Docathon today, please follow the checklist below:
- move original author information to the bottom of the notebook
- move import below the title
- use `plt.style.use('seaborn-darkgrid')`
- remove `find_MAP` as initiating the sampling, use multiple chains and default sampling as much as possible
- update kwarg when possible

**Comment by junpenglao** [comment]
Template import (suggestion/edit welcome):
```python
%pylab inline

import numpy as np
import pymc3 as pm
import theano.tensor as tt

plt.style.use('seaborn-darkgrid')
print('Running on PyMC3 v%s'%pm.__version__)
```

**Comment by aloctavodia** [comment]
I would prefer

```python
%matplotlib inline
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('seaborn-darkgrid')
print('Running on PyMC3 v{}'.format(pm.__version__))
```

**Comment by junpenglao** [comment]
I prefer `print()` which doesnt leave a `''` mark :-p

**Comment by aloctavodia** [comment]
I updated my previous comment with the `print()` function.

**Comment by junpenglao** [comment]
Close as it is outdated.
