### ISSUE TITLE
First two links (to notebooks) in this documentation page are broken

### ISSUE THREAD

**Issue by EtienneT** [pymc-devs/pymc#2836]
The first two links on this page are broken.

http://docs.pymc.io/notebooks/model_averaging.html

**Comment by aloctavodia** [comment]
Thanks for the report, in the meantime the corrects links should point to http://docs.pymc.io/notebooks/model_comparison.html and  http://docs.pymc.io/notebooks/GLM-model-selection.html

**Comment by ArjitJ** [comment]
Updated the two links
Attaching the .txt file for the code
[model_averaging.txt](https://github.com/pymc-devs/pymc3/files/1698146/model_averaging.txt)

**Comment by aloctavodia** [comment]
@ArjitJ do you want to send aPR?

**Comment by ArjitJ** [comment]
@aloctavodia Yes, but i couldnt find the .html file on your repo, so thats why i uploaded a .txt file

**Comment by ColCarroll** [comment]
@ArjitJ the documentation is rendered using [Sphinx](http://www.sphinx-doc.org/), which has a bit of a learning curve. The page you found is generated from the [model averaging notebook](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/model_averaging.ipynb), so you can edit that notebook and make a pull request.
