### ISSUE TITLE
distribution.logp returns strange error

### ISSUE THREAD

**Issue by shkr** [pymc-devs/pymc#2851]
## Description of your problem
call to `distribution.logp(data)` returns an index error

Expectation is to calculate elemwise logp given `data`

However fn call returns a strange error

https://github.com/shkr/pymc3/blob/issue_2850/docs/source/notebooks/issue_2850.ipynb

don't mind the nb name - failed at guessing the right issue number :P

I have attached the code in the linked nb to replicate error.

## Versions and main components
watermark included in nb

**Comment by junpenglao** [comment]
Try casing the data to tensor: `obs.distribution.logp(theano.shared(X[:10]))`

**Comment by shkr** [comment]
@junpenglao That helped. However, I am unable to understand the `ndim` of the output value.

distribution.logp is used to set Var.logp_elemwiset which implies it should return an array element for each row in X.

https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L1237

However in the nb ndim=0. Can you explain what I am missing here ?

nb updated
https://github.com/shkr/pymc3/blob/issue_2850/docs/source/notebooks/issue_2850.ipynb

**Comment by junpenglao** [comment]
It only works if your logp returns element_wise logp, then `logp_sum` will output total logp. see
https://github.com/pymc-devs/pymc3/blob/760fba43442d4a6669407e8c45ae2824f77d3eec/pymc3/distributions/distribution.py#L108-L114
In your code you need to change the output of `logp_` to `return logsumexp(tt.stacklists(logps), axis=0)`
I think this might be easier to discuss in the discourse. I will close here for now.
