### ISSUE TITLE
Log Likelihood of MvGaussianRandomWalk Returns Array Rather Than Scalar

### ISSUE THREAD

**Issue by a3huang** [pymc-devs/pymc#2859]
I noticed another small quirk with `MvGaussianRandomWalk`. When I run:
```
pm.MvGaussianRandomWalk.dist(mu=tt.constant([1,1]), tau=tt.constant(np.eye(2)))\
    .logp(tt.constant([[1,2], [3,4]])).eval()
```
I get:
```
array([-2.83787707, -2.83787707])
```
This output seems strange to me as I was expecting to see a single number representing the log likelihood of the single sequence of vectors I input. The log likelihood itself seems correct, but is repeated twice in this case.

Looking into this, I found the problem to be the line:
```
return self.init.logp(x[0]) + tt.sum(innov_like)
```

By default, `self.init = Flat.dist()` and since this is actually a univariate distribution, calling `self.init.logp(x[0])` actually returns an array of shape (2,) since `x[0]` is an array of shape (2,). Therefore, this results in `tt.sum(innov_like)` being broadcasted into an array rather than a scalar.

I was thinking that we could probably replace this with:
```
return tt.sum(self.init.logp(x[0])) + tt.sum(innov_like)
```
This way, we will correctly return a scalar value when the initial distribution provided is univariate (i.e. the components of the initial vector are iid). Please let me know if I'm mistaken and this was actually the intended behavior.

## Versions and main components
PyMC3 Version: 3.3
Theano Version: 1.0.1
Python Version: 2.7.12
Operating system: MacOS 10.13.3
How did you install PyMC3: pip

**Comment by junpenglao** [comment]
I think you are right, cc @gBokiau so we can also change it in #2847

**Comment by krishamehta** [comment]
Can I work on this?

**Comment by junpenglao** [comment]
@krishamehta thanks for your interested! However, it might be better to address it in #2847.
You can have a look at https://github.com/pymc-devs/pymc3/issues?q=is%3Aissue+is%3Aopen+label%3Abeginner_friendly which contains some beginer friendly issues :-)

**Comment by gBokiau** [comment]
Once #3008 gets approval and merged, we should:
- [ ] replace all instances of `tt.sum(logp)` with `logp_sum`
- [ ] add tests that assert that timeseries return log-probabilities of the expected shapes
- [ ] use `logp_sum` where the tests fail
