### ISSUE TITLE
Add Kronecker GP doc

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2860]
We should add the doc for Kronecker GP after PR #2731:

- [x] missing index in https://github.com/pymc-devs/pymc3/blob/master/docs/source/api/distributions/multivariate.rst and https://github.com/pymc-devs/pymc3/blob/master/docs/source/api/gp.rst
- [x] Demonstration of Coregion kernel (put after Gibbs kernel in https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-MeansAndCovs.ipynb)
- [x] A Coregionalized regression example similar to GPy: https://github.com/SheffieldML/notebook/blob/master/GPy/coregionalized_regression_tutorial.ipynb

cc @jordan-melendez @fonnesbeck @bwengals

**Comment by bwengals** [comment]
Would also like to add a box for an example of `MarginalKron`.  What is your timeline @jordan-melendez?  I'd be happy to work on some of these with you if you don't mind.

**Comment by jordan-melendez** [comment]
Ah, I knew I missed something, thanks for pointing out the index. These are good ideas though. Sorry for not getting to this sooner. I'd gladly accept some help since research and other work is taking priority at the moment. I could probably get started on these in the next week though, sound good?

**Comment by bwengals** [comment]
no deadlines for unpaid open source labor!  Making sure i dont step on any toes :)

**Comment by jordan-melendez** [comment]
@bwengals You are welcome to take the lead on the coregionalized regression examples if you'd like. That would take a while for me to get to anyways. Thanks for the help 😃
