### ISSUE TITLE
summary not returning data frame anymore?

### ISSUE THREAD

**Issue by JLivingston01** [pymc-devs/pymc#2862]
Hi guys, 

Using pymc3 for creating some models, after updating some related packages to speed up computation, my only issue is that the pymc3.summary() and pymc3.stats.summary() of my trace will only return the pretty print summary, but not the data frame summary that used to be returned before I updated. There are no errors thrown, just no data frame returned. Is this a known issue? I couldn't attach a .py script but I've copied a reproduction script into the bottom of this message. 

## Versions and main components

* PyMC3 Version: 3.2
* Theano Version: 1.0.1
* Python Version: 3.6
* Operating system: Windows 10
* How did you install PyMC3: previously pip, reinstalled all packages with conda.

import pandas as pd
import numpy as np
import pymc3 as pm
#Some data to play with
data = pd.DataFrame()
data['x1'] = np.random.randint(5,10,5)
data['x2'] = np.random.randint(5,10,5)
data['y'] = data['x1']+data['x2']+np.random.normal(0,2,5)

#Specify a model
with pm.Model() as lm_model:
    #hyper priors
    boundednormal = pm.Bound(pm.Normal,lower = .01)
    slope_mu = pm.Normal('slope_mu',mu = 1, sd = .3)
    slope_sigma = boundednormal('slope_sigma',mu = .3, sd = .08)
    intercept_mu = pm.Normal('intercept_mu',mu = 0,sd = .3)
    intercept_sigma = boundednormal('intercept_sigma', mu = .3,sd = .08)
    
    ## Coefficients
    bx1 = boundednormal('bx1', mu = slope_mu, sd = slope_sigma)
    bx2 =boundednormal('bx2', mu = slope_mu, sd = slope_sigma)
    b0 = boundednormal('b0', mu = intercept_mu, sd = intercept_sigma)
    
    #error
    eps = boundednormal('eps',mu = 2, sd = .06)
    
    #Expected
    
    y_Est = \
    bx1*(data.x1.values)+\
    bx2*(data.x2.values)+\
    b0
    #Likelihood
    y_like = pm.Normal('y_like',mu = y_Est, sd = eps, observed = data.y.values)

#Fit the model  
with lm_model:
    lm_trace = pm.sample(njobs = 1, draws = 2000, tune = 2000, init = None,step=pm.Metropolis(), progressbar = True)
    
#pm.traceplot(lm_trace)
#Summarize the model. Not returning DataFrame, only pretty print.
summary = pm.summary(lm_trace)

**Comment by junpenglao** [comment]
Could you update your PyMC3? It should return pandas dataframe in v3.3

**Comment by JLivingston01** [comment]
Thanks for the feedback. Actually I found that pymc3.df_summary(trace) gives me what I'm looking for.

**Comment by junpenglao** [comment]
Yes but `pymc3.df_summary()` is deprecated, so i would still suggest you to update your pymc3.
