### ISSUE TITLE
Cov arguments in TP and MvStudentT

### ISSUE THREAD

**Issue by jordan-melendez** [pymc-devs/pymc#2865]
I am migrating this discussion from [Discourse](https://discourse.pymc.io/t/marginal-student-t-process-and-misleading-parameters/867):

> ... It seems like `cov_func` and `cov` are misleading parameter names, since they aren’t actually the covariances of the distributions. Rather, they refer to the `Sigma` parameter of `MvStudentT`, which is related to the covariance by `nu * Sigma / (nu-2)`. Thus, [here](http://docs.pymc.io/notebooks/GP-TProcess.html#Samples-from-a-TP-prior), for example, it looks like apples and oranges are being compared when using the same `cov_func` in a `GP` and `TP`. Can these arguments be changed so that they really are covariances, or at least be better documented so that people know that they aren’t actually what they seem to be?

What is the correct course of action here? Better documentation or changing the functionality to align with the argument names?

**Comment by fonnesbeck** [comment]
Ideally, it would be nice to have the option of parameterizing via `Sigma` or a true covariance (just as we can parameterize a beta with scale and shape parameters or mean and variance).

**Comment by bwengals** [comment]
Would a good alternative name maybe be `scale_func`?

**Comment by jordan-melendez** [comment]
I agree on allowing options for parameterizing with a `cov_func` or something like a `scale_func`. Does the current `MvStudentT` actually treat `Sigma` differently than `cov`? And if so, how does it handle the `cov` if `nu` is less than 2, where it should be undefined? This seems tricky if `nu` is unobserved, unless `cov` is always converted back to `Sigma` behind the scenes.

**Comment by michaelosthege** [comment]
This is the oldest open issue right now.
@bwengals is it still relevant?
It would be a good time to rename kwargs now if needed.

**Comment by bwengals** [comment]
Yes this should still be fixed
