### ISSUE TITLE
Discrete variables not sampling independently

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#2866]
Spurred on by this on [StackOverflow](https://stackoverflow.com/questions/48834717/coin-tosses-arithmetic-of-random-variables-and-pymc3), I can confirm that this is reproducible on `pymc3-3.3`:

    with pm.Model():
        x = pm.Bernoulli('x', 0.5)
        y = pm.Bernoulli('y', 0.5)
        z = pm.Deterministic('z', x + y)
        trace = pm.sample(40)

    # trace[z] is array([2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0])

One commenter did some debugging and suspects `BinaryGibbsMetropolis` being in the wrong.

**Comment by junpenglao** [comment]
This is a fun one... The stationary distribution of `x` and `y` is exactly Bernoulli(.5):
Looking at `astep`:
https://github.com/pymc-devs/pymc3/blob/5dfd08215e00003150bea98306cea12f6fba9867/pymc3/step_methods/metropolis.py#L333-L337

In this case, `logp_prop - logp_curr` is 0 so the proposal is always accepted, which gives this alternating behaviour. 

To be honest I am not sure if it is really a bug, as if there is observed the update is correct. I think a more throughout solution is to have something different for the pure forward random generation.
