### ISSUE TITLE
External model with its derivative

### ISSUE THREAD

**Issue by madarshahian** [pymc-devs/pymc#2874]
I know how to use an external model for pymc3. I also know what are derivatives with respect to my model's parameters.
I want to use NUTS sampler, not Metropolis. But I do not know how to let the NUTS know that derivatives are also available externally? 
Any suggestion?

**Comment by junpenglao** [comment]
Hi @madarshahian, could you please post this to our discourse: https://discourse.pymc.io/
I am closing this for now.
