### ISSUE TITLE
Wrong logp function in ElemwiseCategoricalStep

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2879]
cc @twiecki, related #1563

It seems that the logp being evaluated in `ElemwiseCategoricalStep` is incorrect:
`ElemwiseCategorical` evaluate the logp of the RV and its parent:
https://github.com/pymc-devs/pymc3/blob/fde52a4a69be1b0887a2f7861801fb48c941bbe6/pymc3/step_methods/gibbs.py#L39-L40
https://github.com/pymc-devs/pymc3/blob/fde52a4a69be1b0887a2f7861801fb48c941bbe6/pymc3/step_methods/gibbs.py#L53-L56

Instead, it should evaluate on the conditional logp only (as in Gibbs sampling).

**Comment by junpenglao** [comment]
cc @rrkarim

**Comment by ricardoV94** [comment]
Method was removed in https://github.com/pymc-devs/pymc/pull/4701
