### ISSUE TITLE
[Metropolis] delta_log makes costly re-evaluations

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#2881]
The `delta_logp` function to evaluate the metropolis acceptance ratio evaluates both `q` and `q0`.

## Description of your problem
+ re-evaluation of `logp(q0)` is unnecessary (except in iteration 0)
+ re-evaluation of `logp(q0)` prohibits sampling of noisy target densities [[1](https://darrenjw.wordpress.com/2010/09/20/the-pseudo-marginal-approach-to-exact-approximate-mcmc-algorithms/)]
+ models with slow forward-passes suffer an up to 2x performance drop

## Possible solutions
+ caching `logp(q0)` from one iteration to the next (what's the best/fastest way to do this?)
+ evaluate `logp(q)` directly (fastlogp?)

Note that this only affects `Metropolis` and `DEMetropolis` because other samplers use different ways to compute the acceptance ratio.

**Comment by michaelosthege** [comment]
Closing this for now because caching is dangerous when combined with compound sampling:
+ in compound sampling, other dimensions (not included in q) can change from one iteration to the next
+ when this happens, logp(q0) has also changed, because the chain has been displaced in a dimension that is not considered in q
+ the acceptance ratio would then be incorrect

In other words:
+ caching **may only be used if all dimensions are jointly updated**

**Comment by junpenglao** [comment]
Alternatively, it would involve a global logp constantly cache and update whenever an RV is updated, a careful monitoring is needed whenever `astep` within a `Compound.method` accepted a new proposal.
