### ISSUE TITLE
The samples resulted by pymc3 are all the same

### ISSUE THREAD

**Issue by Nedahp** [pymc-devs/pymc#2887]
Hi there,

I am new to pymc3 and gibbs sampling. I am using pymc3 to use inference to solve a specific problem. Here are the list of inputs to my model, and the way I have defined the model.

import numpy as np
import pymc3 as pm
import pandas as pd

# inputs to the model which are prepared based on the datasets I am woking with 
pathways  --> an integer equal to 86
features --> an integer equal to 1534
masses --> an integer equal to 864
landa --> a float equal to 0.5
mu  --> a matrix of float values 0.90 and 0.001 with size 86 * 1534
tau --> a matrix of 0 and 1 with size 1534 * 864
w_obs --> a vector of 0 and 1 with length 864

# model definition 
myModel = pm.Model()
with myModel:
    a = pm.Bernoulli('a',p = landa, shape = (pathways,1)) 
    mu_hat = a * np.array(mu) 
    phi = 1 - (1 - mu_hat).prod(axis = 0) 
    indexes = [[row for row in range(len(tau)) if tau[row][k] == 1] for k in range(masses)] 
    psi = [1 - ((1-phi)[index].prod(axis = 0)) for index in indexes] 
    w = pm.Bernoulli('w',p = psi, observed = w_obs, shape = masses) 
   

# set the start point 
df = pd.read_csv('estimate_initialpoint.csv')
startpoint = df['pathway_activities'].tolist()
startpoint = np.array(startpoint)
start_point = {'a': startpoint.reshape(pathways,1)}

with myModel:
    # draw posterior samples
    trace = pm.sample(start=start_point)

I have tried running the model with different start points (random, not random, all ones, or even no start point). But, the samples are always the same as the initial point and do not get changed. I greatly appreciate if somebody can help me with this problem.

Thank you.

**Comment by junpenglao** [comment]
Hi @Nedahp, please post user question to https://discourse.pymc.io/, thanks!
Closing here...
