### ISSUE TITLE
Declaring  Deterministic Matrix with random variables

### ISSUE THREAD

**Issue by Nilavro** [pymc-devs/pymc#2898]
I wish to declare a matrix of known dynamics - 

cos(w)    -sin(w )  0  0
sin(w)    cos(w )  0  0
0         0               1   0
0       0             0      1

something like following - 

with pm.Model() as model:
              w = pm.Normal('w', mu = 0 , tau = 1)
              A = pm.Deterministic('A' , ([[np.cos(w), -np.sin(w), 0, 0],[np.sin(w), -np.cos(w), 0, 0],[0, 0, 1, 0],[0, 0, 0, 0]])  )
              Y = pm.Normal('y', mu = T.dot(A , X),  tau = 1 , observed = X)

Can anyone suggest how to do this?

**Comment by junpenglao** [comment]
Hi @Nilavro, please post questions to [our discourse](https://discourse.pymc.io), as we only use Github issue for bug reports. Thanks!
Closing for now...
