### ISSUE TITLE
Enhancement of Survival Analysis documentation

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#2899]
Just a quick remark/ placeholder.

Would it be possible to stick https://github.com/pymc-devs/pymc3/pull/1870 in a notebook, with the examples of survival analysis/ censoring like @fonnesbeck has done in the past.

**Comment by twiecki** [comment]
CC @domenzain

**Comment by domenzain** [comment]
Oh, the notebooks in the docs look neat.
Is there a particularly good one to emulate?

**Comment by springcoil** [comment]
https://docs.pymc.io/notebooks/rugby_analytics.html is a decent one (disclosure: I am the author) https://docs.pymc.io/notebooks/stochastic_volatility.html -- Stochastic Volatility is a good one too.

**Comment by eigenfoo** [comment]
Hello @jazzmuesli - just wanted to check in on the state of this PR. Are you still working on #2942, or is it alright for me to take a stab at that issue? Would love to have the opportunity, but definitely don't want to steal your thunder 😃

**Comment by fonnesbeck** [comment]
@eigenfoo thanks for offering to help. It would be great if you could pick this up if the original author is unable/unwilling to finish it up.

**Comment by eigenfoo** [comment]
@fonnesbeck glad for the opportunity! I'll try and mock something up over the weekend, unless @jazzmuesli replies.

**Comment by eigenfoo** [comment]
@fonnesbeck @jazzmuesli I started a new PR for this issue
