### ISSUE TITLE
SGMCMC is slow due to scan

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#2903]
I tried using SGMCMC but it turned out to be quite slow due to the scan in https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/sgmcmc.py#L55. Is it possible to vectorize this? CC @shkr.

**Comment by shkr** [comment]
Yeah. Definitely possible. Just need a d (logL + prior) evaluated for each observed data point. I wrote a scan because it is simple like a for loop. I will look into this. All Stochastic Gradient techniques will benefit.

**Comment by twiecki** [comment]
Don't we have this already in the `Model` class?

**Comment by junpenglao** [comment]
We have `logp_elemwise` but not `dlogp_elemwise`. Maybe it is not too difficult to add?
https://github.com/pymc-devs/pymc3/blob/6dd0e81c9a29153ddf08a5a20a2c934a9e5738ae/pymc3/model.py#L167-L169

**Comment by shkr** [comment]
Good point. Yeah having that api in `model` will solve this issue.

**Comment by shkr** [comment]
@junpenglao even logp_elemwise is not implemented. Since logp_elemwiset variable is never intiialized in `Model`'s __init__ method

**Comment by twiecki** [comment]
We should probably deprecate these samplers, not sure anyone uses them, unless @shkr has time to do some more work on them.
