### ISSUE TITLE
 How update to master branch of PyMC3

### ISSUE THREAD

**Issue by Blockhead3** [pymc-devs/pymc#2910]
Right to use the MvNormal mixture, I need to update to master branch of PyMC3 (the fix is recently push).
I entered  the following commands in the Anaconda prompt:

''pip3 install git+https://github.com/pymc-devs/pymc3@master''

but when I implement  MvNormal mixture model ,it still worng.

> 
''ValueError: operands could not be broadcast together with shapes (9,6) (1,9)''

Where is the update method wrong

## Versions and main components

* PyMC3 Version:3-3.3
* Theano Version:1.01
* Python Version:3.6
* Operating system:windows7
* How did you install PyMC3: (conda/pip) conda install -c conda-forge pymc3

**Comment by twiecki** [comment]
That's the right pip command from what I can tell. Do you use a virtual env?

**Comment by Blockhead3** [comment]
I run my code in spyder,Does this mean that I use a conda env?is it not feasible to use the pip command in Anaconda prompt?

**Comment by ColCarroll** [comment]
You may be able to run

```
> !python -m pip install git+https://github.com/pymc-devs/pymc3@master 
```

from the spyder ipython console.  The `!` runs a shell command, and `python -m` makes sure you use whichever `pip` is connected with your current python binary.  (I don't actually use spyder, so apologies if this is nonsensical)

**Comment by Blockhead3** [comment]
Thank you very much for your reply，in addition to Spyder, is there a better compiler to implement the Bayesian model ,or say ,which Python compiler is more suitable for using pymc3 to simulate Bayesian models,could you please give me some advice,thank you.

**Comment by junpenglao** [comment]
Just FYI, Spyder is not a compiler, but an integrated development environment (IDE).

I used to use Spyder as well (I was a Matlab user before), but now mostly use the Jupyter notebook or JupyterLab for doing data analysis. I also have pycharm installed for developing codes.

You are using Spyder that comes with Anaconda right? I think it should use the same env - try checking the env in Anaconda and uninstall/reinstall pymc3 from master.

**Comment by Blockhead3** [comment]
Thank-you for your help.

**Comment by ColCarroll** [comment]
Closing since this isn't specifically a `PyMC3` bug, but please hop onto https://discourse.pymc.io/ which is better suited for this sort of thing!
