### ISSUE TITLE
Metropolis working with discrete and continuous variables

### ISSUE THREAD

**Issue by charlotteburki** [pymc-devs/pymc#2916]
For the metropolis step when working with both continuous and discrete variables and when blocked='True' (so updating all parameters together) there is an error that the continous variables are of integer type. This is because in the metropolis script:

```python
        if self.any_discrete:
            if self.all_discrete:
                delta = np.round(delta, 0).astype('int64')
                q0 = q0.astype('int64')
                q = (q0 + delta).astype('int64')
            else:
                delta[self.discrete] = np.round(
                    delta[self.discrete], 0).astype('int64')
                q = (q0 + delta).astype('int64')
        else:
            q = floatX(q0 + delta)
```
     
q = (q0 + delta).astype('int64') transform the numpy vector containing all the variables into a vector that can contain only int. As you can not have different types of variables in a numpy vector 

I fixed my local version of the code with:
```python
        if self.any_discrete:
            if self.all_discrete:
                delta = np.round(delta, 0).astype('int64')
                q0 = q0.astype('int64')
                q = (q0 + delta).astype('int64')
            else:
                delta[self.discrete] = np.round(
                    delta[self.discrete], 0)
                q = (q0 + delta)
        else:
            q = floatX(q0 + delta)`
```
This should maybe be a pull request but I'm not that confident that my solution is the most efficient/elegant one.

**Comment by junpenglao** [comment]
I think this is fine. Did you try to run the test locally to see if the change pass the test?

**Comment by charlotteburki** [comment]
Yes I tested it, it works

**Comment by junpenglao** [comment]
Send a PR then ;-)

**Comment by charlotteburki** [comment]
Alright!

**Comment by charlotteburki** [comment]
Sorry, this is actually my first time sending a pull request. I created a new branch called metropolis_variable_type and try to send a pull request using sourcetree but I get the following error message:

remote: Permission to pymc-devs/pymc3.git denied to charlotteburki

I initally just comitted and pushed the branch changes, I'm sorry. I hope this doesn't have any negative impact on the PyMC3 packages.

**Comment by junpenglao** [comment]
Dont worry - you dont have push access to pymc3 branches. The changes you made are on your own port, if you go to your own github port, there should be something highlighted as create a Pull request or something like that.
