### ISSUE TITLE
Additional diagnostics for loo/waic/compare

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#2930]
@avehtari and the stan dev recently release `loo 2.0`, I had a look seems most of our algorithms are up-to-date with the paper (I also cross reference with the `psis-loo` python code). 
However, it would be good to implement the additional diagnostics tool they have - the ks table:
```
Pareto k diagnostic values:
                         Count Pct.    Min. n_eff
(-Inf, 0.5]   (good)     240   91.6%   205
 (0.5, 0.7]   (ok)         7    2.7%   48
   (0.7, 1]   (bad)        8    3.1%   7
   (1, Inf)   (very bad)   7    2.7%   1
```
And the ks plot 
![image](https://user-images.githubusercontent.com/12952641/38854838-0e004ec8-4222-11e8-8143-67c012d2d6fd.png)

I was working on porting @avehtari's [modelselection_tutorial](https://github.com/avehtari/modelselection_tutorial), with some potential refactoring of the loo/waic function to output ks and related statistics: https://github.com/junpenglao/modelselection_tutorial/tree/PyMC3_nb/PyMC3_nb
it should be a good beginner issue.

**Comment by aloctavodia** [comment]
This would be great! Maybe this should go directly to ArviZ, given that during 3.5 we are going to deprecate all plots, stats and diagnostics.

**Comment by junpenglao** [comment]
Sure. Although we should still keep the diagnostics as the warning system depends on them.

**Comment by aloctavodia** [comment]
@agustinaarroyuelo can help us implementing this (into ArviZ) as part of the bonding period. Is this OK with you @junpenglao

**Comment by junpenglao** [comment]
Good idea ;-)

**Comment by agustinaarroyuelo** [comment]
great! I'll start working on this
