### ISSUE TITLE
grin 1.2.1 requires argparse>=1.1, which is not installed.

### ISSUE THREAD

**Issue by ibobak** [pymc-devs/pymc#2931]
When installing using command  
pip install git+https://github.com/pymc-devs/pymc3

I am getting an error
grin 1.2.1 requires argparse>=1.1, which is not installed

It is not a big issue, of course, to install this package, but http://docs.pymc.io/notebooks/getting_started  this page should be updated then. 

```


Requirement already satisfied: scipy>=0.14 in c:\anaconda2\lib\site-packages (from theano>=1.0.0->py
mc3==3.4rc2) (0.19.1)
Requirement already satisfied: python-dateutil in c:\anaconda2\lib\site-packages (from pandas>=0.18.
0->pymc3==3.4rc2) (2.6.1)
Requirement already satisfied: pytz>=2011k in c:\anaconda2\lib\site-packages (from pandas>=0.18.0->p
ymc3==3.4rc2) (2017.2)
Building wheels for collected packages: pymc3, theano
  Running setup.py bdist_wheel for pymc3 ... done
  Stored in directory: c:\users\ibobak\appdata\local\temp\pip-ephem-wheel-cache-vwyl9e\wheels\a1\e3\
71\a696f2af0dd40bccc0ce672d616d21cc9dd90dbdd3f03242f4
  Running setup.py bdist_wheel for theano ... done
  Stored in directory: C:\Users\ibobak\AppData\Local\pip\Cache\wheels\a7\8a\6c\aad33a6144dc30cc65d43
7c444090076136d2c0f289f3ce183
Successfully built pymc3 theano
grin 1.2.1 requires argparse>=1.1, which is not installed.
Installing collected packages: numpy, theano, joblib, tqdm, pymc3
  Found existing installation: numpy 1.11.3
    Uninstalling numpy-1.11.3:
      Successfully uninstalled numpy-1.11.3
Successfully installed joblib-0.11 numpy-1.14.2 pymc3-3.4rc2 theano-1.0.1 tqdm-4.23.0




```

## Versions and main components

* PyMC3 Version:  the latest (pip install git+https://github.com/pymc-devs/pymc3)
* Theano Version:  have no idea (the one has just been installed)
* Python Version: 2.7.14
* Operating system:  Win7
* How did you install PyMC3: pip install git+https://github.com/pymc-devs/pymc3

**Comment by ColCarroll** [comment]
I do not think `grin` is a requirement - does this continue to happen?

**Comment by RustyStryker** [comment]
I"m having the same issue. Did you ever find a solution?  can we drop grin from the install?

**Comment by ColCarroll** [comment]
Can you figure out what's requesting `grin`? it isn't clear from the stack trace above, and I have never seen it before.

**Comment by tukeyone** [comment]
Did you solve it?

**Comment by Vital-Fernandez** [comment]
I am getting that same error with all the pip installations (ubuntu 18.04 with anaconda python 2.7)

**Comment by ZapDos7** [comment]
How is this issue solved then?

**Comment by ColCarroll** [comment]
I am still not sure how this problem is happening -- `grin` is definitely not in the requirements, and I am fairly certain it is not a secondary requirement.  

Can anyone with the issue post a reproducible example, preferably starting with a clean virtual environment or conda environment?

**Comment by ZapDos7** [comment]
I was suggested to install argparse:
`pip install argparse `
which solved my issue.

**Comment by BritneyMuller** [comment]
Ran into the same thing when trying to run
`pip install beautifulsoup4`

`pip install argparse`fixed it for me as well. Thank you ZapDos7!

**Comment by RustyStryker** [comment]
Sorry for the delay.  I went onto studying something else while I was stuck.

I started up a new virtual machine and installed Anaconda 3.6.  seemed to
go much better.

**Comment by rahuls321** [comment]
pip install argparse
This will solve your problem

**Comment by twiecki** [comment]
Not sure how this relates to pymc3, but since there is a solution will close.

**Comment by joaolodi** [comment]
I think you should use: pip install argparse

**Comment by BlackSouthAsianPenguin** [comment]
Just fix it by pip install argsparse 
if you have another problem like no Pyhamcrest 
just fix it by installing
pip install Pyhamcrest
