### ISSUE TITLE
Theano does not sample from HalfCauchy and Lognormal together

### ISSUE THREAD

**Issue by philastrophist** [pymc-devs/pymc#2948]
Theano does not sample from a very simple model.

I have purged the theano cache, reinstalled theano/pymc3 to no avail.
I always get an error relating to dimension mis-match. I don't understand.

The model runs fine if I leave out `nu` or `sigma`. Both together just results in the error message below.

    import theano
    theano.compile.DebugMode = True
    print(theano.__version__)
    print(pm.__version__)

    ndim = 3
    with pm.Model() as model:
        sigma = pm.Lognormal('sigma', np.zeros(ndim), np.ones(ndim), shape=ndim)  # variance for the correlation matrix
        nu = pm.HalfCauchy('nu', beta=10) 
        pm.sample(10)

Answer:

    1.0.1
    3.4.1

    ValueError: Input dimension mis-match. (input[0].shape[0] = 3, input[1].shape[0] = 1)
    Apply node that caused the error: Elemwise{Composite{((-i0) + i1 + i2)}}(Elemwise{Composite{log(exp(i0))}}.0, TensorConstant{(1,) of -1.0}, TensorConstant{(1,) of 1.0})
    Toposort index: 8
    Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, (True,))]
    Inputs shapes: [(3,), (1,), (1,)]
    Inputs strides: [(8,), (8,), (8,)]
    Inputs values: [array([-0.0915752 ,  0.1090227 , -0.38337466]), array([-1.]), array([ 1.])]
    Outputs clients: [[IncSubtensor{InplaceInc;int64:int64:}(Alloc.0, (d__logp/dsigma_log__), Constant{1}, Constant{4})]]
    
    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.1
* Python Version: 3.6.5
* Operating system: Scientific Linux  3.10.0-514.el7.x86_64
* How did you install PyMC3: (conda/pip):
`pip install git+https://github.com/pymc-devs/pymc3.git`

**Comment by philastrophist** [comment]
It says in the traceback that there are three inputs! But I've only given two!

**Comment by junpenglao** [comment]
Seems to be a bug in Lognormal distribution

**Comment by philastrophist** [comment]
I can confirm that this model works in `pymc3=3.0` and `theano=0.9 or 1.0.1` on pythons 2.7&3.6

**Comment by philastrophist** [comment]
It appears to be in this commit: fcd7ac5, where the bug was introduced (git bisect)

**Comment by junpenglao** [comment]
Thanks for investigating. However that PR is completely unrelated so I doubt that is the issue.

**Comment by junpenglao** [comment]
Tested few other distributions (Normal, LogitNormal etc) instead of Lognormal and there is no error. the gradient output from 

https://github.com/pymc-devs/pymc3/blob/fcd7ac57048978f144ba8bdd5b90ff2f1b45c51a/pymc3/model.py#L448

is incorrect when using Lognormal...

**Comment by philastrophist** [comment]
Actually found it now (866c482). 
My bisect script found other errors last time

**Comment by junpenglao** [comment]
thanks for investigating. cc @aseyboldt

**Comment by aseyboldt** [comment]
Just a guess at this point, but could it be that this bug is related to the names of the theano ops that compute the logp? That is the only change in that commit that sounds to me like it might be connected. If some ops end up with the same name, then maybe some optimization gets confused. I'm really not sure why things might end up with the same name though.
