### ISSUE TITLE
Conditioning in Reinforcement Learning Setup

### ISSUE THREAD

**Issue by kapilagrawal95** [pymc-devs/pymc#2958]
If you have questions about a specific use case, please post it to our discourse channel: https://discourse.pymc.io  
If you are not sure whether this is a bug or not, please also post it on discourse.

## Description of your problem
Hi
I am working on a reinforcement learning problem wherein the model works in a loop until time is not over.
Something like this:
**Please provide a minimal, self-contained, and reproducible example.**
with pm.Model():
    timeLeft = 7(say)
    while(timeLeft>0):
    //sample from a distribution and compute an outcome based on defined action
    //store the outcome in an array
    timeLeft = timeLeft-1

after I come out of the model
I get an array of outcome of length 7.
I am interested in conditioning this array of outcome to the actual array and see the posterior distribution of latent variables.

How do I write the code for the conditioning part and the inference part?

If there are any existing issues that solve my problems please point to them.

Thanks
**Please provide the full traceback.**

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:3.3
* Theano Version:1.0.1
* Python Version:3
* Operating system:Ubuntu
* How did you install PyMC3: conda

**Comment by junpenglao** [comment]
Hi there, please post questions to our discourse. I will close this for now.

**Comment by kapilagrawal95** [comment]
I have posted it on discourse too.
