### ISSUE TITLE
Error documentation distributions.multivariate.LKJCholeskyCov

### ISSUE THREAD

**Issue by JackCaster** [pymc-devs/pymc#2973]
In example of LKJCholeskyCov, [at line 863](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L863) it reads:

```
vals_raw = pm.Normal('vals_raw', mu=np.zeros(10), sd=1)
```
but it should be:
```
vals_raw = pm.Normal('vals_raw', mu=0, sd=1, shape=10)
```
otherwise an error is raised
```
TypeError: For compute_test_value, one input test value does not have the requested type.

The error when converting the test value to that variable type:
Wrong number of dimensions: expected 0, got 1 with shape (10,).
```
If it is an error, I could create a PR.

**Comment by junpenglao** [comment]
I think at some point we change the `distribution.default` behaviour, which is now causing this error.
Would you like to give it a stab to fix that? Otherwise, a PR to change the docstring will do.
