### ISSUE TITLE
posteriorplot.py rope keyword to accept list of lists

### ISSUE THREAD

**Issue by elzurdo** [pymc-devs/pymc#2976]
Request for posteriorplot.py to accept a list of lists for `rope` - rope pair value for each variable.  
`rope` currently accepts only one pair value and then used for all variables.
However, it makes sense when exploring parameters from different orders of magnitude.
## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.1
* Python Version: 3.6.5
* Operating system: OSX
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
Good suggestion. @aloctavodia put it in https://github.com/arviz-devs/arviz?

**Comment by aloctavodia** [comment]
Thanks @elzurdo for the suggestion.I will add this to ArviZ ASAP

**Comment by aloctavodia** [comment]
I realized this is already implemented #2382
I will improve the docstring in ArviZ
