### ISSUE TITLE
Missing information in documentation of distributions

### ISSUE THREAD

**Issue by AllenDowney** [pymc-devs/pymc#2992]
This page:
http://docs.pymc.io/prob_dists.html
documents the interface for distributions:
```
class SomeDistribution(Continuous):

    def random(self, point=None, size=None, repeat=None):
        ...
        return random_samples

    def logp(self, value):
        ...
        return total_log_prob
```
But I can't find an explanation of what the arguments of `random()` mean, not even in the source code.

I have other suggestions on the documentation.  Is opening an issue a good way to proceed?

**Comment by fonnesbeck** [comment]
Allen, opening an issue like this is a great way to proceed. We are always looking for feedback on improving our docs, so this is much appreciated.

**Comment by fonnesbeck** [comment]
In particular, the `repeat=None` argument is not used anymore, so we should get rid of that.

I wish Python allowed inheritance of method docstrings. Its going to be laborious to add them to every subclass.

**Comment by AllenDowney** [comment]
Thanks, Chris.
Repeating docstrings on subclasses definitely sounds problematic.  I don't know what best practice is for this.
In this case, I think it would be sufficient to document these arguments on `draw_values()`, and to add a couple of sentences to the docs page I linked.

**Comment by springcoil** [comment]
Open an issue please!

**Comment by fonnesbeck** [comment]
This issue is fine.

I added some candidate docstrings to `Uniform`. If we like them I can propagate to others:

random:

        """
        Draw random values from Uniform distribution.

        Parameters
        ----------
        point : Point, optional
            Point on which random values are to be conditioned. 
        size : int, optional
            Desired size of random sample.

        Returns
        -------
        array
        """

logp:

        """
        Calculate log-probability of Uniform distribution at specified value.

        Parameters
        ----------
        value : numeric
            Value for which log-probability is calculated. 

        Returns
        -------
        TensorVariable
        """

**Comment by junpenglao** [comment]
> I wish Python allowed inheritance of method docstrings. Its going to be laborious to add them to every subclass.

I saw tensorflow/probability and edward has that - not sure how exactly it is generated tho.

**Comment by canyon289** [comment]
@fonnesbeck I'm willing to take on updating the docstrings!  If so it might take me a couple of weeks to get ramped up and make the changes. Would that be acceptable?

**Comment by twiecki** [comment]
@canyon289 much appreciated!

**Comment by fonnesbeck** [comment]
@canyon289 sounds good. Have a look at #2993 for what I came up with. Feel free to improve if you have any ideas.

**Comment by canyon289** [comment]
Thanks for the opportunity!

To make sure I'm on the same page the scope is everything in the https://github.com/pymc-devs/pymc3/tree/master/pymc3/distributions directory and any external documentation that references it?

**Comment by canyon289** [comment]
Just a heads up! I'm actively getting situated on contributing to this by getting a dev environment setup and digging into the library. Super excited to learn but do let me know if I'm holding anything up and/or need to speed up

**Comment by mdesgroseilliers** [comment]
Just drawing your attention to the fact that per the last few comments, it looks like this issue can be closed.

**Comment by junpenglao** [comment]
Thanks!
