### ISSUE TITLE
Theano dependency in conda-forge

### ISSUE THREAD

**Issue by JackCaster** [pymc-devs/pymc#2995]
Although the latest version of Theano is already installed (currently 1.0.2), the installation of PyMC3 from conda-forge still requires Theano to be installed.

The conda environment was created as:
```
conda create -n pymc3_test python=3 numpy scipy cython mkl-service
source activate pymc3_test
pip install git+https://github.com/theano/theano #install latest version theano
```
Then, when PyMC3 is about to be installed:
```
conda install -c conda-forge pymc3
```
the output is:
```
The following NEW packages will be INSTALLED:
    ...
    theano:          1.0.2-py36_0         conda-forge
    ...
```
The installation of PyMC3 from git `pip install git+https://github.com/pymc-devs/pymc3`, instead, recognises that Theano has been already installed.

## Versions and main components

* PyMC3 Version: `pymc3-3.4.1`
* Theano Version: `theano-1.0.2`
* Python Version: `3.6.5`
* Operating system: `OSX 10.11.6` and `Win 10 Pro` 
* How did you install PyMC3: (conda/pip) `conda-forge`

**Comment by ColCarroll** [comment]
Can you verify the output of `which pip` is the one from the conda environment?

**Comment by JackCaster** [comment]
> Can you verify the output of which pip is the one from the conda environment?

`which pip` returns `/Users/.../miniconda3/envs/pymc3_test/bin/pip`. 
The `pip` version is `10.0.1`

**Comment by ColCarroll** [comment]
Darn, that would have been easy.  But I have a wild theory:

- 9 days ago, [theano pushed prep for the 1.0.2 release](https://github.com/Theano/Theano/commit/3b51141a46affe9505f0e3f283020820b2c0251e)
- This included setting `FALLBACK_VERSION = "1.0.2+unknown"`
- When `conda` goes to search for `theano`, it finds `"1.0.2-py36_0"`
- For whatever reason conda decides the version it found is better, but pip does not.  [This](https://github.com/conda/conda/issues/2071) might be the more relevant issue?

I'll try this in a clean install, but wanted to write it down on the off chance I'm right. I am fairly certain there is not a change other than pinning a `theano` version that we could make on our side to fix this.

**Comment by ColCarroll** [comment]
Gosh, I can't figure this out -- maybe @ericmjl can explain why this happens?  I am not sure how the conda-forge stuff works, but I can confirm I get the same behavior on ubuntu.

**Comment by ericmjl** [comment]
@ColCarroll yes, I think pinning versions is the source of this issue. I don't have more details that I can think of, except that I've noticed empirically that conda-forge packages generally have somewhat stronger requirements on versioning. I'm hoping this gets changed in the future.

**Comment by ColCarroll** [comment]
Thanks, @ericmjl !  Closing since I don't think we can fix this here.
