### ISSUE TITLE
Stopiteration exception when run find_MAP()

### ISSUE THREAD

**Issue by kristosh** [pymc-devs/pymc#2996]
I am trying to use a default example of pmf that I found [in that thread](https://stats.stackexchange.com/questions/146547/pymc3-implementation-of-probabilistic-matrix-factorization-pmf-map-produces-a). However, when I try to run the code:

```
      with pm.Model() as pmf:
              pmf_U = pm.MvNormal('U', mu=0, tau=alpha_u * np.eye(dim), shape=(n, dim), testval=np.random.randn(n, dim)*.01)
              pmf_V = pm.MvNormal('V', mu=0, tau=alpha_v * np.eye(dim), shape=(m, dim), testval=np.random.randn(m, dim)*.01)
              pmf_R = pm.Normal('R', mu=theano.tensor.dot(pmf_U, pmf_V.T), tau=alpha, observed=train)
    start = pm.find_MAP(fmin=sp.optimize.fmin_powell)  
    step = pm.NUTS(scaling=start)
    trace = pm.sample(500, step, start=start)
```

I am receiving an stopiteration exception in `start = pm.find_MAP(fmin=sp.optimize.fmin_powell)  ` . How can I tackle that issue?

**Comment by junpenglao** [comment]
Hi @kristosh , the API for `pm.find_MAP` is changed and also using the MAP to compute scaling to initialize NUTS is no longer the best practice. I recommand you to check out our doc for more updated usage.
If you have further question please post to our discourse: https://discourse.pymc.io/. Closing this here.

**Comment by kristosh** [comment]
Could you please provide a link to the documentation, everything that i find for performing the PMF produce the same error.
