### ISSUE TITLE
Inference fails with "list index out of range" for LDA ADVI AEVB example notebook

### ISSUE THREAD

**Issue by ahmadsalim** [pymc-devs/pymc#3005]
## Description of your problem

When running the [LDA ADVI AEVB](http://docs.pymc.io/notebooks/lda-advi-aevb.html) notebook locally, I am currently experiencing a "list index out of range" error when I run the inference (In\[10\]) portion. 

It seems that somehow it is failing because NaN is met during optimization (probably the root cause), but the error message fails to be printed. I would assume that the example would have worked in a previous version of PyMC3, so even the NaN error seems weird by itself.

Can you kindly take a look at the issue?
Thanks!

## Traceback

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-d75645c485ba> in <module>()
     10 inference.fit(10000, callbacks=[reduce_rate], obj_optimizer=pm.sgd(learning_rate=s), 
     11               more_obj_params=encoder_params, total_grad_norm_constraint=200,
---> 12               more_replacements={doc_t:doc_t_minibatch})

~/Documents/SourceControl/probprog-sandbox/venv/lib/python3.6/site-packages/pymc3/variational/inference.py in fit(self, n, score, callbacks, progressbar, **kwargs)
    133         with tqdm.trange(n, disable=not progressbar) as progress:
    134             if score:
--> 135                 state = self._iterate_with_loss(0, n, step_func, progress, callbacks)
    136             else:
    137                 state = self._iterate_without_loss(0, n, step_func, progress, callbacks)

~/Documents/SourceControl/probprog-sandbox/venv/lib/python3.6/site-packages/pymc3/variational/inference.py in _iterate_with_loss(self, s, n, step_func, progress, callbacks)
    209                     for ii in index:
    210                         errmsg.append('The current approximation of RV `{}`.ravel()[{}]'
--> 211                                       ' is NaN.'.format(*name_slc[ii]))
    212                     errmsg.append(suggest_solution)
    213                     raise FloatingPointError('\n'.join(errmsg))

IndexError: list index out of range
```

## Versions and main components

* PyMC3 Version: master
* Theano Version: 1.0.2
* Python Version: 3.6.5
* Operating system: MacOS High Sierra (10.13)
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
Thanks for reporting. I track down the issue - it is the change after v3.3 in the `math.invlogit` (it was also reported in https://github.com/pymc-devs/pymc3/issues/3003).

I will fix this (also make the error report more robust to avoid indexing error)

**Comment by junpenglao** [comment]
Should be fixed on master now ;-)

**Comment by ahmadsalim** [comment]
Awesome, thanks!
