### ISSUE TITLE
Add TensorFlow backend

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3019]
https://github.com/pymc-devs/pymc3/pull/3009/ already made a great start that gets basic functionality working. I merged this into the `tensorflow` branch. As the code that is yet to be ported is commented out, individual PRs could enable small parts of code and do PRs onto that branch.

Contributions welcome!

**Comment by crgagne** [comment]
Hey Thomas, great to hear from you! 

Thanks for creating this new branch. Having people add functionality by uncommenting sections, making the changes, and submitting PR requests is a good idea. 

I was looking over my code a bit more and noting where adding tensorflow functionality is more difficult. As you mentioned, changing the distributions would be easy, and getting the gradient-based samplers to work would be a bit trickier. I’m going to take a stab at that in the next week. If there are any particularly interesting reasons why TF and Theano implementations need to be fundamentally different I’ll add a note to this issue. 

Cheers, 
Chris

**Comment by kyleabeauchamp** [comment]
TODOs:

- [ ] Pull in changes from master into tensorflow branch
- [ ] Replace commented-out code with decorators or some other way to dynamically determine codepath and/or available objects
- [ ] Gradient-based sampler implementation (E.g., HMC)
- [ ] Replace notebook-based test with a simple CLI script.

**Comment by lucianopaz** [comment]
What's the status on this, given that pymc4 will be based on tensorflow? Should we close this?

**Comment by kyleabeauchamp** [comment]
Presumably?  I haven't done anything.

**Comment by crgagne** [comment]
I unfortunately ended up stopping working on it, due to time constraints.

**Comment by ericmjl** [comment]
We should just close this issue, because pm4 is already in development. Going ahead and closing this, feel free to reopen if there's really anything pressing, but otherwise, I think we should take this to the pm4 repository.

**Comment by crgagne** [comment]
Sounds good. Thanks.
