### ISSUE TITLE
cores > 1 hanging while sampling w/ 3.4.1

### ISSUE THREAD

**Issue by pindapuj** [pymc-devs/pymc#3030]
Hello,

My 2015 Macbook hangs when running 
`trace = pm.sampling.sample(draws=num_draws, cores=4)`

When I set cores=1/njobs =1, sampling works fine, albeit slowly. I have the following set-up: 
enum34==1.1.6 
h5py==2.7.0
joblib==0.9.4
numpy==1.14.2
pandas==0.22.0
patsy==0.5.0
pymc3==3.4.1
six==1.11.0
Theano==1.0.1
tqdm==4.8.4
python2.7

I rolled back my version of joblib from 11.0 as it was suggested in a previous issue. However, this did not fix the problem. Rolling back to pymc3==3.1 allowed multiprocessing to work however, even with joblib==11.0. 

Does anyone have any suggestions on fixing this? Also, aside from speed and the use of multiple cores, are the results from running the following equivalent? I'm still a little unclear on the relationship between njobs, chains and cores: 
`trace = pm.sampling.sample(draw=num_draw,cores=4)`
`trace = pm.sampling.sample(draw=num_draw,chains=4, cores=1)`
`trace = pm.sampling.sample(draw=num_draw,chains =4, njobs=1)`
`trace = pm.sampling.sample(draw=num_draw,chains=4)`

Thank you!

**Comment by junpenglao** [comment]
We just merge a fix to replace joblib so it might work now - try updating to master

`chains` is the kwarg for number of MCMC chains you will get (i.e., the number of chain in the resulting `trace`). `cores` and `njobs` does the same thing but `njobs` has been deprecated.

**Comment by pindapuj** [comment]
I switched my code over to python3 after updating to master and its moves along nicely. However, my python2 version of the code still hangs on njobs > 1. 

Thank you!

**Comment by junpenglao** [comment]
Thanks for reporting back - we are discontinuing the python2 support so this probably wont be fixed. Closing...
