### ISSUE TITLE
Random in Categorical returns wrong shape for 2D parameter

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#3035]
Running:
```python
p = np.random.rand(10, 5)
pm.Categorical.dist(p=p).random()
```
gives a (10, 5) array instead of (10, ).

cc @ColCarroll

**Comment by junpenglao** [comment]
Currently there are 2 similar copies of Categorical Random generation in the code:
https://github.com/pymc-devs/pymc3/blob/ea5cbf3e838973b4f992674d0a8a6bd9a443b229/pymc3/distributions/mixture.py#L150-L158

https://github.com/pymc-devs/pymc3/blob/ea5cbf3e838973b4f992674d0a8a6bd9a443b229/pymc3/distributions/discrete.py#L713-L720

We should unify them into one function.

**Comment by canyon289** [comment]
@junpenglao I would be happy to help here if I can understand a couple of things.

What is the expected output for the function when an (x,y) input is passed as an argument?
Is the Categorical Random in discrete.py or mixture.py more preferred?

Let me know if help here is desired!

**Comment by junpenglao** [comment]
> What is the expected output for the function when an (x,y) input is passed as an argument?

(x, ) or (x, 1), as the last dimension of the input `p` (with shape `(x, y)`) is expected to be equal to the number of categories. Currently Categorical Random in discrete.py returns (x, ) and mixture.py returns (x, 1) - it is easier to return (x, 1) in a mixture for indexing so I suggest this to be the default.

**Comment by canyon289** [comment]
Got it, If you're open to it I would like to try my hand at this one!

Is there any urgency on when this needs to be completed?

I'm still wrapping my head around the specifics and may need to get a couple of reviews before it's nailed down.

**Comment by junpenglao** [comment]
Go ahead! Let me know if you have any questions ;-)
