### ISSUE TITLE
Rename sample_ppc to sample_posterior_predictive

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3037]
`sample_ppc` is a misnomer, as the c stands for check, while there is no check performed.
We now have `sample_prior_predictive` and should thus rename `sample_ppc` to `sample_posterior_predictive` (while still keeping `sample_ppc` as an alias with a deprecation warning).

Also, we should add `sample_posterior()` to which `sample()` provides an alias.

**Comment by Dpananos** [comment]
I'm not familiar with aliasing a function name or deprecation warnings, but am willing to take this on as a learning experience.

**Comment by twiecki** [comment]
Great @Dpananos. You can use `warnings.warn(message, DeprecationWarning, stacklevel=2)`, or if you want to be fancy, use a decorator. The alias would just be calling the new function from the old function forwarding the args and kwargs.

**Comment by ColCarroll** [comment]
specifically, something like this.  There'll be a bunch of extra work tracking down usages in docstrings, tests, examples, and notebooks.

```python
    def sample_ppc(*args, **kwargs):
        """Docstring pointing to `sample_prior_predictive`"""
        warnings.warn(message, DeprecationWarning, stacklevel=2)
        return sample(*args, **kwargs)
```

**Comment by Dpananos** [comment]
Should I also rename `sample_ppc_w`?

**Comment by aloctavodia** [comment]
Hi, @Dpananos yes you should, thank you.

**Comment by Dpananos** [comment]
Are there any tests I need to run before I make a PR?  Sorry for all the questions.  My only other contribution was to pandas, and they had a suite of tests to run before making a PR.

**Comment by aloctavodia** [comment]
There are a bunch of tests under the `tests` folder. I guess the only relevant for your PR should be `test_sampling.py`. BTW, questions are totally fine!

**Comment by Dpananos** [comment]
Running into issues with Docker and testing.  Following instructions found [here](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md) Docker is failing with the following error:

```
Command "python setup.py egg_info" failed with error code 1 in /home/jovyan/
The command '/bin/sh -c /bin/bash /home/jovyan/scripts/create_testenv.sh --global --no-setup' returned a non-zero code: 1
Unable to find image 'pymc3:latest' locally
docker: Error response from daemon: pull access denied for pymc3, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```


Let me know if you need any more information in order to help.

**Comment by Dpananos** [comment]
Also, `pytest --cov=pymc3 pymc3/tests/tests_for_package.py` fails with error

`ERROR: file not found: pymc3/tests/tests_for_package.py`.

Doesn't look like `test_for_packages.py` is in that directory.  Are the contribution docs up to date?

**Comment by ColCarroll** [comment]
Ooh, that second one was meant as an example name - we should make that more clear!

In your case, try `pytest -v pymc3/tests/test_sampling.py`

I think @AustinRochford is currently working to update the dockerfile.

**Comment by Dpananos** [comment]
@ColCarroll Oh, that would make sense.  I think adding some `<>` would serve to make that clearer.  I can add those.

**Comment by Dpananos** [comment]
Running through some notebooks to test the warnings.  They don't pop up in jupyter notebook, but do pop up when I run the code in terminal. Ideas on how to fix that?

**Comment by AustinRochford** [comment]
The Dockerfile should be fixed as of #3032.  If it doesn't work for you on master, please open another issue and tag me @ColCarroll @Dpananos.

**Comment by leka0024** [comment]
Hi, I'm very new to PyMC3. I was attempting to follow Example 1 code for Gaussian Processes notebook (link here: https://docs.pymc.io/notebooks/GP-Latent.html) In this notebook it says to use "sample_posterior_predictive()" function. The code line I used is:

```
# Sample from the GP conditional distribution
with model:
    pred_samples = pm.sample_posterior_predictive(trace, vars=[f_pred], samples=1000)
```

But when I try to follow this, in fact I get an error message "
AttributeError: module 'pymc3' has no attribute 'sample_posterior_predictive'".

I just install PyMC3, so my version is 3.5. Running on Ubuntu system, with Python 3.6.

Should I actually be using sample_ppc, with the exact same arguments?? Why is the notebook saying this if the function isn't in the code (yet?)?

**Comment by fonnesbeck** [comment]
@leka0024 Apologies for this. The renamed function is actually in the master branch, but has not yet been released, whereas the docs appear to reflect master. If you really want this to work, you can upgrade your PyMC3 via:

`pip install -U git+https://github.com/pymc-devs/pymc3/git`

**Comment by leka0024** [comment]
@fonnesbeck Thank you! Since I will likely leave v3.5 in my virtualenv, I will just use sample_ppc() for now. I replaced in my code and it works great, just like the example notebook.

By the way, in the earlier part of code, lines:

```
with pm.Model() as model:
    ...
    trace = pm.sample(1000)
```

my install of Theno gave a warning message as follows:

```
.../python3.6/site-packages/theano/tensor/basic.py:6592: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result[diagonal_slice] = x
```

I checked and it is from the pm.sample(...) line, not the other lines.

So this maybe an issue that your team should look into, if there isn't already open issue. Thanks again!

**Comment by fonnesbeck** [comment]
The docs should now be fixed to reflect the current release, via #3158

**Comment by fonnesbeck** [comment]
The original issue seems to be addressed in current master, so closing.

**Comment by mjhajharia** [comment]
i was just going through some documentation, which still uses sample_ppc

**Comment by OriolAbril** [comment]
Thanks for reporting! Can you share the links @almostmeenal ? It is probably worth it to create an issue to update the relevant docs, either here or at https://github.com/pymc-devs/pymc-examples

**Comment by mjhajharia** [comment]
my bad, that was some old documentation now that I revisited it.
https://pymc3.readthedocs.io/en/latest/notebooks/posterior_predictive.html
