### ISSUE TITLE
load MCMC chains from naive txt format

### ISSUE THREAD

**Issue by yuanshuoastro** [pymc-devs/pymc#3043]
Dear all,

I have a lot of MCMC chains in txt format with 5  colomns:
weight Likelihood p1 p2 p3 
where p1 p2 ... are sampling of model parameters, and Likelihood is the Likelihood at (p1,p2,p3), weight is the repeating times of (p1,p2,p3).

Now I would like to try PyMC the analisis these chains, how can I load them in into PyMC's MC.Samples varibles?

My idea is try to use numpy.loadtxt to load txt into numpy.array. but how to transform them into pymc?

Thank you!

**Comment by ColCarroll** [comment]
That will be a bit tricky! In PyMC3, the `MultiTrace` objects contain references to objects that are not serializable (the `pm.Model` instance, along with the `theano` variables).  You _might_ be able to fake it if you read the data into a dictionary, but I imagine that will be frustrating.

We are working on a project (http://arviz-devs.github.io/arviz/) that will make analysis of MCMC chains from any source easy, but it is still very much in development.  

I'm closing this as not an issue we are working on here, but feel free to repost in https://discourse.pymc.io/ !
