### ISSUE TITLE
Updated mixture model breaks with multi-dimension mixtures

### ISSUE THREAD

**Issue by ahmadsalim** [pymc-devs/pymc#3044]
The following multi-dimensional mixture model seems to break after the fixes in PR #3004:
```
import pymc3 as pm
import numpy as np

with pm.Model() as model:
    mus = pm.Normal('mus', shape=(6,12))
    taus = pm.Gamma('taus', alpha=1, beta=1, shape=(6, 12))
    ws = pm.Dirichlet('ws', np.ones(12))
    mixture = pm.NormalMixture('m', w=ws, mu=mus, tau=taus)
```

I now get the error, while it was working before:
```
IndexError: index 10 is out of bounds for size 6
```

## Versions and main components

* PyMC3 Version: master
* Theano Version: 1.0.2
* Python Version: 3.6.5
* Operating system: Windows 10
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
Actually, this is not broken by #3004 but likely something in the mixture that I change - will try to send a fix.

**Comment by ahmadsalim** [comment]
Awesome, thanks!

I believe I could get it to work using the previous commit on master, but I am not 100% sure.

**Comment by junpenglao** [comment]
Your code should work now - but you need to be more careful of the shape for latent variables:
```python
mixture = pm.NormalMixture('m', w=ws, mu=mus, tau=taus, shape=6)
```
Specifying the shape for the latent variable in many cases are necessary now as we accumulated quite a lot of code changes for shape handling. Even if we rewrite the shape handling in the future this is likely still needed.

**Comment by ahmadsalim** [comment]
@junpenglao Great! Thank you very much for the fix 😄
