### ISSUE TITLE
sample_smc calls _initial_population to set step.population even if start parameter is supplied

### ISSUE THREAD

**Issue by TStesco** [pymc-devs/pymc#3061]
For SMC sampling with ```sample_smc``` you can provide a parameter ```start``` that is a list of starting points (dict of model parameters, e.g. trace object) for the SMC Markov chains which is set as ```step.population```.

As discussed on [discourse](https://discourse.pymc.io/t/smc-sampling-appears-to-not-allow-supplying-a-starting-trace/1428), ```_initial_population```, which generates a list of starting points by sampling the prior model, is called by ```sample_smc``` even if the ```start``` parameter is supplied and overwrites the ```step.population```. See this line in ```sample_smc``` in [smc.py](https://github.com/pymc-devs/pymc3/blob/d829f560c3ee46a4d54a2790ede833ff8b5fd947/pymc3/step_methods/smc.py#L493).

A simple fix being to only call ```_initial_population``` if ```start``` is not provided.

Currently this is on the master branch, not the current 3.4.1 release.

**Comment by junpenglao** [comment]
Closed in #3062
