### ISSUE TITLE
Sampling from GaussianRandomWalk

### ISSUE THREAD

**Issue by sachinruk** [pymc-devs/pymc#3073]
It seems that you cannot sample from a GaussianRandomWalk looking at https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/timeseries.py#L134 or any other distribution in timeseries.py. Think this is partly due to the fact that the initial (default) distribution is defined to be `Flat`.

Just wondering if it's worth changing into something like `uniform(-2,2)` for the sake of being able to sample. If that is the case, I'm happy to write a PR to sample from (some of) these.

**Comment by junpenglao** [comment]
Sample you mean random generation right? In that case you should pass a `pm.Uniform.dist(-2, 2)` to init

**Comment by kyleabeauchamp** [comment]
Yeah, I think we need to add a note about this in the docstring.  I spent over an hour tracking this down and assumed I had a botched theano installation...

**Comment by twiecki** [comment]
@kyleabeauchamp Yes, a note is a good idea.

Note that you can sample (if the GaussianRandomWalk is an observed) by adding `nans` over the period you want to sample.

**Comment by ricardoV94** [comment]
Closing this as https://github.com/pymc-devs/pymc3/pull/4388 seems to fix this issue.

See also https://github.com/pymc-devs/pymc3/issues/4337 for a general timeseries random issue.
