### ISSUE TITLE
find_hessian() Compilation failed (return status=1):

### ISSUE THREAD

**Issue by homofortis** [pymc-devs/pymc#3075]
## Description of your problem
call to find_hessian() results to a compilation error:
```
import pymc3 as pm
with pm.Model() as model:
    p = pm.Uniform('p',0,1)
    w = pm.Binomial('w',n=9,p=p,observed=6)
    mean = pm.find_MAP()
    pm.find_hessian(mean,vars=[p])
```

**Please provide the full traceback.**
```
You can find the C code in this temporary file: /var/folders/pp/f5zwnkbx0_l7xwr_mn8y7bpm0000gn/T/theano_compilation_error_nxni11uy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py in <module>()
     47     if version != getattr(scan_perform, '_version', None):
---> 48         raise ImportError()
     49 except ImportError:

ImportError: 

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py in <module>()
     62             if version != getattr(scan_perform, '_version', None):
---> 63                 raise ImportError()
     64         except ImportError:

ImportError: 

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-66-77a55fa51277> in <module>()
      3     w = pm.Binomial('w',n=9,p=p,observed=6)
      4     mean = pm.find_MAP()
----> 5     pm.find_hessian(mean,vars=[p])

/usr/local/lib/python3.7/site-packages/pymc3/tuning/scaling.py in find_hessian(point, vars, model)
     84     """
     85     model = modelcontext(model)
---> 86     H = model.fastd2logp(vars)
     87     return H(Point(point, model=model))
     88 

/usr/local/lib/python3.7/site-packages/pymc3/model.py in fastd2logp(self, vars)
    239     def fastd2logp(self, vars=None):
    240         """Compiled log probability density hessian function"""
--> 241         return self.model.fastfn(hessian(self.logpt, vars))
    242 
    243     @property

/usr/local/lib/python3.7/site-packages/theano/configparser.py in res(*args, **kwargs)
    115         def res(*args, **kwargs):
    116             with self:
--> 117                 return f(*args, **kwargs)
    118         return res
    119 

/usr/local/lib/python3.7/site-packages/pymc3/theanof.py in hessian(f, vars)
    133 @change_flags(compute_test_value='ignore')
    134 def hessian(f, vars=None):
--> 135     return -jacobian(gradient(f, vars), vars)
    136 
    137 

/usr/local/lib/python3.7/site-packages/pymc3/theanof.py in jacobian(f, vars)
    115 
    116     if vars:
--> 117         return tt.concatenate([jacobian1(f, v) for v in vars], axis=1)
    118     else:
    119         return empty_gradient

/usr/local/lib/python3.7/site-packages/pymc3/theanof.py in <listcomp>(.0)
    115 
    116     if vars:
--> 117         return tt.concatenate([jacobian1(f, v) for v in vars], axis=1)
    118     else:
    119         return empty_gradient

/usr/local/lib/python3.7/site-packages/pymc3/theanof.py in jacobian1(f, v)
    107         return gradient1(f[i], v)
    108 
--> 109     return theano.map(grad_i, idx)[0]
    110 
    111 

/usr/local/lib/python3.7/site-packages/theano/scan_module/scan_views.py in map(fn, sequences, non_sequences, truncate_gradient, go_backwards, mode, name)
     68                      go_backwards=go_backwards,
     69                      mode=mode,
---> 70                      name=name)
     71 
     72 

/usr/local/lib/python3.7/site-packages/theano/scan_module/scan.py in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict, return_list)
   1075             pass
   1076         scan_inputs += [arg]
-> 1077     scan_outs = local_op(*scan_inputs)
   1078     if type(scan_outs) not in (list, tuple):
   1079         scan_outs = [scan_outs]

/usr/local/lib/python3.7/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    668                 # compute output value once with test inputs to validate graph
    669                 thunk = node.op.make_thunk(node, storage_map, compute_map,
--> 670                                            no_recycling=[])
    671                 thunk.inputs = [storage_map[v] for v in node.inputs]
    672                 thunk.outputs = [storage_map[v] for v in node.outputs]

/usr/local/lib/python3.7/site-packages/theano/scan_module/scan_op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    923             cython_destroy_map = np.asarray(cython_destroy_map,
    924                                             dtype='int32')
--> 925             from . import scan_perform_ext
    926 
    927             def p(node, args, outs):

/usr/local/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py in <module>()
    120             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
    121                                              preargs=preargs,
--> 122                                              hide_symbols=False)
    123             # Save version into the __init__.py file.
    124             init_py = os.path.join(loc, '__init__.py')

/usr/local/lib/python3.7/site-packages/theano/gof/cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2386             # difficult to read.
   2387             raise Exception('Compilation failed (return status=%s): %s' %
-> 2388                             (status, compile_stderr.replace('\n', '. ')))
   2389         elif config.cmodule.compilation_warning and compile_stderr:
   2390             # Print errors just below the command line.

Exception: Compilation failed (return status=1): /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:11860:65: error: too many arguments to function call, expected 3, have 4.     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);.            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:100:18: note: expanded from macro 'NULL'. #    define NULL __null.                  ^~~~~~. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12617:21: error: no member named 'exc_type' in '_ts'.     *type = tstate->exc_type;.             ~~~~~~  ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12618:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     *value = tstate->exc_value;.                      ^~~~~~~~~.                      curexc_value. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12619:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     *tb = tstate->exc_traceback;.                   ^~~~~~~~~~~~~.                   curexc_traceback. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12626:24: error: no member named 'exc_type' in '_ts'.     tmp_type = tstate->exc_type;.                ~~~~~~  ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12627:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tmp_value = tstate->exc_value;.                         ^~~~~~~~~.                         curexc_value. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12628:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tmp_tb = tstate->exc_traceback;.                      ^~~~~~~~~~~~~.                      curexc_traceback. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12629:13: error: no member named 'exc_type' in '_ts'.     tstate->exc_type = type;.     ~~~~~~  ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12630:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tstate->exc_value = value;.             ^~~~~~~~~.             curexc_value. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12631:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tstate->exc_traceback = tb;.             ^~~~~~~~~~~~~.             curexc_traceback. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12686:24: error: no member named 'exc_type' in '_ts'.     tmp_type = tstate->exc_type;.                ~~~~~~  ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12687:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tmp_value = tstate->exc_value;.                         ^~~~~~~~~.                         curexc_value. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12688:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tmp_tb = tstate->exc_traceback;.                      ^~~~~~~~~~~~~.                      curexc_traceback. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12689:13: error: no member named 'exc_type' in '_ts'.     tstate->exc_type = local_type;.     ~~~~~~  ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12690:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tstate->exc_value = local_value;.             ^~~~~~~~~.             curexc_value. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/zardoz/.theano/compiledir_Darwin-17.6.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12691:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tstate->exc_traceback = local_tb;.             ^~~~~~~~~~~~~.             curexc_traceback. /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. 16 errors generated..
``` 
**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.2
* Python Version:  3.7.0
* Operating system: Mac OS 10.13.5
* How did you install PyMC3: pip3

**Comment by junpenglao** [comment]
Runs fine locally for me - anybody else reproduce this error?

**Comment by canyon289** [comment]
@junpenglao I'm able to reproduce the error with the same version of python, Theano and Pymc3 installed via pip

but when I install Theano 1.0.2 with conda everything works

> Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
> [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pymc3 as pm
> >>> with pm.Model() as model:
> ...     p = pm.Uniform('p',0,1)
> ...     w = pm.Binomial('w',n=9,p=p,observed=6)
> ...     mean = pm.find_MAP()
> ...     pm.find_hessian(mean,vars=[p])
> ... 
> logp = -1.8075, ||grad|| = 1.5: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 2084.05it/s]
> 
> You can find the C code in this temporary file: /var/folders/gt/28pvdm614vd_2tn01llmx3s00000gp/T/theano_compilation_error_abza_qn4
> Traceback (most recent call last):
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 45, in <module>
>     try_import()
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 35, in try_import
>     import scan_perform
> ModuleNotFoundError: No module named 'scan_perform'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 60, in <module>
>     try_import()
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 35, in try_import
>     import scan_perform
> ModuleNotFoundError: No module named 'scan_perform'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 5, in <module>
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/tuning/scaling.py", line 86, in find_hessian
>     H = model.fastd2logp(vars)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/model.py", line 240, in fastd2logp
>     return self.model.fastfn(hessian(self.logpt, vars))
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/configparser.py", line 117, in res
>     return f(*args, **kwargs)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/theanof.py", line 135, in hessian
>     return -jacobian(gradient(f, vars), vars)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/theanof.py", line 117, in jacobian
>     return tt.concatenate([jacobian1(f, v) for v in vars], axis=1)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/theanof.py", line 117, in <listcomp>
>     return tt.concatenate([jacobian1(f, v) for v in vars], axis=1)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/pymc3/theanof.py", line 109, in jacobian1
>     return theano.map(grad_i, idx)[0]
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_views.py", line 70, in map
>     name=name)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan.py", line 1077, in scan
>     scan_outs = local_op(*scan_inputs)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/gof/op.py", line 670, in __call__
>     no_recycling=[])
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 925, in make_thunk
>     from . import scan_perform_ext
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/scan_module/scan_perform_ext.py", line 122, in <module>
>     hide_symbols=False)
>   File "/Users/username/.miniconda3/envs/test/lib/python3.7/site-packages/theano/gof/cmodule.py", line 2388, in compile_str
>     (status, compile_stderr.replace('\n', '. ')))
> Exception: Compilation failed (return status=1): /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:11860:65: error: too many arguments to function call, expected 3, have 4.     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);.            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~. /Users/username/.miniconda3/bin/../lib/clang/4.0.1/include/stddef.h:100:18: note: expanded from macro 'NULL'. #    define NULL __null.                  ^~~~~~. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12617:21: error: no member named 'exc_type' in '_ts'.     *type = tstate->exc_type;.             ~~~~~~  ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12618:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     *value = tstate->exc_value;.                      ^~~~~~~~~.                      curexc_value. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12619:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     *tb = tstate->exc_traceback;.                   ^~~~~~~~~~~~~.                   curexc_traceback. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12626:24: error: no member named 'exc_type' in '_ts'.     tmp_type = tstate->exc_type;.                ~~~~~~  ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12627:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tmp_value = tstate->exc_value;.                         ^~~~~~~~~.                         curexc_value. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12628:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tmp_tb = tstate->exc_traceback;.                      ^~~~~~~~~~~~~.                      curexc_traceback. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12629:13: error: no member named 'exc_type' in '_ts'.     tstate->exc_type = type;.     ~~~~~~  ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12630:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tstate->exc_value = value;.             ^~~~~~~~~.             curexc_value. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12631:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tstate->exc_traceback = tb;.             ^~~~~~~~~~~~~.             curexc_traceback. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12686:24: error: no member named 'exc_type' in '_ts'.     tmp_type = tstate->exc_type;.                ~~~~~~  ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12687:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tmp_value = tstate->exc_value;.                         ^~~~~~~~~.                         curexc_value. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12688:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tmp_tb = tstate->exc_traceback;.                      ^~~~~~~~~~~~~.                      curexc_traceback. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12689:13: error: no member named 'exc_type' in '_ts'.     tstate->exc_type = local_type;.     ~~~~~~  ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12690:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?.     tstate->exc_value = local_value;.             ^~~~~~~~~.             curexc_value. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here.     PyObject *curexc_value;.               ^. /Users/username/.theano/compiledir_Darwin-17.5.0-x86_64-i386-64bit-i386-3.7.0-64/scan_perform/mod.cpp:12691:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?.     tstate->exc_traceback = local_tb;.             ^~~~~~~~~~~~~.             curexc_traceback. /Users/username/.miniconda3/envs/test/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here.     PyObject *curexc_traceback;.               ^. 16 errors generated.. `

**Comment by rpgoldman** [comment]
Going to dismiss this as "fixed upstream" (in theano). Reopen if that's inaccurate.

**Comment by sammosummo** [comment]
I reproduce this error with up-to-date PyMC3 installed via conda on macOS:

Theano 1.1.2
pymc3 3.11.2
Python 3.8.8
