### ISSUE TITLE
sample_ppc() output generates ValueError

### ISSUE THREAD

**Issue by MPinter2** [pymc-devs/pymc#3081]
While running posterior predictive checks, I encountered a ValueError when attempting to plot the output from sample_ppc(). To test further, I ran the following from the Posterior Predictive Checks tutorial:
```python
data = np.random.randn(100)

with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sd=1, testval=0)
    sd = pm.HalfNormal('sd', sd=1)
    n = pm.Normal('n', mu=mu, sd=sd, observed=data)

    trace = pm.sample(5000)

ppc = pm.sample_ppc(trace, samples=500, model=model, size=100)
print("ppc shape: " + str(np.asarray(ppc['n']).shape))
for i in ppc['n']:
    sns.kdeplot(i, color='r', alpha=0.1)
```
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sd, mu]
Sampling 4 chains: 100%|██████████| 22000/22000 [00:10<00:00, 2042.78draws/s]
100%|██████████| 500/500 [00:00<00:00, 910.69it/s]

ppc shape: (500, 100, 100)
```
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/BayesAnalysis/Test_predict.py", line 35, in <module>
    main()
  File "C:/Users/PycharmProjects/BayesAnalysis/Test_predict.py", line 30, in main
    sns.kdeplot(i, color='r', alpha=0.1)
  File "C:\Users\Anaconda3\lib\site-packages\seaborn\distributions.py", line 630, in kdeplot
    x, y = data.T
ValueError: too many values to unpack (expected 2)
```
It appears that each predicted sample has an extra data sample appended.

Easy fix in the for loop:   for i in ppc['n'][0]: 

But this can't be SOP and the sample_ppc() output shape does not correspond to that shown in the tutorial.

Thanks.

* PyMC3 Version: 3.4.1 
* Theano Version: 1.0.2
* Python Version: 3.6
* Operating system: Windows 7 
* How did you install PyMC3: (conda/pip) pip from github master

**Comment by junpenglao** [comment]
Could you try from master? I recently push a PR supposedly should deal with these better.

**Comment by MPinter2** [comment]
I should have clarified that I am running from the master.  Downloaded less than 24 hrs ago (ca 2100 NYC, 7/6/2018).  Is your PR more recent than that?

**Comment by junpenglao** [comment]
Actually the shape is correct, as the output shape is (samples,) + (size, ) + data.shape, which gives (500, 100, 100) in this case.
You probably want `ppc = pm.sample_ppc(trace, samples=500, model=model)`

**Comment by MPinter2** [comment]
The syntax
ppc = pm.sample_ppc(trace, samples=500, model=model
runs correctly and returns shape (500, 100).

To clarify, the sample array size always defaults to the length of trace?  Would you please clarify the intent of the kwarg size? The API is a bit unclear.

**Comment by junpenglao** [comment]
The kwarg size is meant to be the repeated generation from a single posterior sample/point.

**Comment by MPinter2** [comment]
Thanks.  Curious how In [5] @ https://docs.pymc.io/notebooks/posterior_predictive.html generates a (500, 100) shape.

**Comment by junpenglao** [comment]
Right, that notebook needs to be updated. Previously ObservedRVs does not record the shape of the observed, which we sometimes use the size kwarg as a hack.
