### ISSUE TITLE
Cannot import name gp

### ISSUE THREAD

**Issue by rocasaifo** [pymc-devs/pymc#3089]
## Description of your problem
I am getting the same errors of this issu https://github.com/pymc-devs/pymc3/issues/1732. 

I get the error cannot import gp

**Please provide the full traceback.**
I tried to reinstall the package usgin versions on the pip install but got no success. Could any one help me out how to solve this?

## Versions and main components

* PyMC3 Version: pymc3==3.4.1
* Theano Version: Theano==1.0.2
* Python Version: 2.7
* Operating system: Linux
* How did you install PyMC3: (pip)

**Comment by fonnesbeck** [comment]
Most likely pip is not installing the package into the `site-packages` directory that you think it is. This often happens when you have multiple Python interpreters on your system, and the `pip` in `/usr/local/bin` (or wherever) is associated with the wrong one. Are you using Anaconda?

**Comment by rocasaifo** [comment]
Hey @fonnesbeck, I am sorry for the delay... actually I have been trying to install it on databricks. have you ever seen someone trying to do that? https://databricks.com/

**Comment by fonnesbeck** [comment]
I have no experience with DataBricks, but you might post a query on our [Discourse site](https://discourse.pymc.io/).

**Comment by eigenfoo** [comment]
@rocasaifo I assume that issue has been resolved, but feel free to continue discussion on our forums if not! Closing now.
