### ISSUE TITLE
improve trace.add_values to allow overwriting values

### ISSUE THREAD

**Issue by JackCaster** [pymc-devs/pymc#3091]
When I fiddle with the posterior samples I like to add new variables to the trace. In this way all the nice plotting functionalities in PyMC3 work without problems. However, the method `add_values` does not allow to update the values in the trace and the error `ValueError: Variable name ... already exists.` is raised. This hinders the interaction you get with the Jupyter notebook, for example (right now the cell containing this assignment can be run only once). Can we add a flag to allow overwriting the trace? Something like `trace.add_values(..., overwrite=True)` (with default to `False` of course).

**Comment by aloctavodia** [comment]
Sounds good to me. Do you want to send a PR, or you would like me to add this feature?

**Comment by JackCaster** [comment]
If it is easy enough for you, then I would greatly appreciate if you could do it :) Otherwise, I will submit a PR.
I was also thinking: would it make sense to add also a method to remove values from the trace (e.g., `remove_values(...)`)?
