### ISSUE TITLE
DLL Load cutils_ext.cutils_ext Import Error

### ISSUE THREAD

**Issue by MisterRedactus** [pymc-devs/pymc#3093]
I am unable to get pymc3 to run on a Windows 10 laptop. The laptop has no GPU. In all cases, I have installed Anaconda3, and have then have installed PyMC3, typically using:

conda install -c conda-forge pymc3

followed by:

conda install mingw libpython

I have then attempted to run the following normal distribution fit adapted from the PyMC3 documentation:

[Regression_Case.txt](https://github.com/pymc-devs/pymc3/files/2194079/Regression_Case.txt)

I receive the first set of output charts for the simulated data as specified by the code, followed by the following traceback:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\cutils.py", line 112, in <module>
    from cutils_ext.cutils_ext import *  # noqa
ImportError: DLL load failed: The specified procedure could not be found.

The full traceback is provided below:

[Cutils_ext Error Traceback.txt](https://github.com/pymc-devs/pymc3/files/2194091/Cutils_ext.Error.Traceback.txt)

I have tried this installation using a PyMC3 install via pip as well and get the same error. Any assistance you can provide will be appreciated.

**Comment by MisterRedactus** [comment]
Given the problems I've already described above for the PyMC3 installation on this Windows 10 laptop, I have tried the steps provided at http://datahans.blogspot.com/2016/04/installing-pymc3.html, which use Anaconda2 and a different order of Theano and PyMC3 installation commands. This also fails on the test Python program with a different but similar error:

Traceback (most recent call last):
  File ".\Regression_Case.py", line 35, in <module>
    alpha = pm.Normal('alpha', mu=0, sd=10)
  File "C:\Anaconda2\lib\site-packages\pymc3\distributions\distribution.py", line 41, in __new__
    dist = cls.dist(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\pymc3\distributions\distribution.py", line 52, in dist
    dist.__init__(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\pymc3\distributions\continuous.py", line 402, in __init__
    self.variance = 1. / self.tau
  File "C:\Anaconda2\lib\site-packages\theano\tensor\var.py", line 203, in __rtruediv__
    return theano.tensor.basic.true_div(other, self)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 670, in __call__
    no_recycling=[])
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\Anaconda2\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1219, in make_thunk
    res = _CThunk(cthunk, init_tasks, tasks, error_storage, module)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cc.py", line 1693, in __init__
    from theano.gof.cutils import run_cthunk  # noqa
  File "C:\Anaconda2\lib\site-packages\theano\gof\cutils.py", line 126, in <module>
    compile_cutils()
  File "C:\Anaconda2\lib\site-packages\theano\gof\cutils.py", line 91, in compile_cutils
    preargs=args)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 2397, in compile_str
    return dlimport(lib_filename)
  File "C:\Anaconda2\lib\site-packages\theano\gof\cmodule.py", line 309, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: The specified procedure could not be found.

In any event, still trying various installation approaches, but feeling increasingly dead in the water...

**Comment by MisterRedactus** [comment]
This is an update to my previous comment. In accordance with the recommendation at https://github.com/Theano/Theano/issues/6181, I went ahead and removed mingw, replacing it with m2w64-toolchain:

conda remove mingw
conda install m2w64-toolchain

Re-running the Regression_Case code then produced this new error:

"If you are using conda, update the numpy packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU"

Attempting to update numpy resulted in a message that all packages were up to date. I therefore used the windows system (right-click on This PC in Windows File Explorer, select Advanced System Settings, and added a new system environment variable MKL_THREADING_LAYER which I set to GNU). After re-booting the computer, this appears to have done the trick. I am impressed by how quickly the program runs.

Moving forward, I would like to get this installation running with Python 3.6/3.7, but at this point, I just need a stable PyMC3 installation. Therefore, I will experiment with this installation on my other PC (see PyMC3 Issue 3087). In general, since it appears that the original installation problem for my laptop appears to be addressed, this issue (3093) should probably be closed out, with the following caveat: My sense so far is that installing PyMC3 on a Windows system can be pretty tricky. (I can't address how easily it goes in Linux at this point; feedback would be appreciated.) It would be really useful for PyMC3 newbies if more bulletproof instructions for the special case off a Windows install were provided.

**Comment by junpenglao** [comment]
Windows installation is at times a bit tricky due to theano... thanks for reporting back.

**Comment by xz1220** [comment]
Thank you very much for your sharing. I successfully solved my problem.

**Comment by twiecki** [comment]
@xz1220 How did you solve it?

**Comment by xiawenwen49** [comment]
How did you solve it?
