### ISSUE TITLE
Gamma function in deterministic variable

### ISSUE THREAD

**Issue by pan-forsteri** [pymc-devs/pymc#3094]
I want to calculate mean of Weibull distribution in pm. Deterministic. But I cannot use gamma function. Can I use gamma function with calculating deterministic variable in PyMC3 model?

This is my code. I could calculate m, nu, mode almost exactly.

```
``  with pm.Model() as model_weibull:
     m = pm.Uniform('m', 0, 10000000)
     nu = pm.Uniform('nu', 0, 10000000)
     pred_y = pm.Weibull('pred_y', alpha = m, beta = nu, observed = y)
    
     mode = pm.Deterministic('mode', nu * (1 - (1/m))**(1/m))
     #mean = pm.Deterministic('mean', nu * Gamma(1+1/m))
    
     step = pm.Metropolis()
     trace = pm.sample(1000, step=step, chains=1, `njobs=1)`
```

## Versions and main components
Python 3.6.6
PyMC3 3.4.1
Theano 1.0.2
Windows 10
I installed PyMC3 with conda.

**Comment by eigenfoo** [comment]
Hello! I think the core dev team wants to reserve the GitHub issue tracker for bugs only. Questions and discussion should take place on https://discourse.pymc.io/. I expect this issue will be closed shortly.

That being said, here are a couple of comments on your code (more details in the PyMC3 docs).

1. A uniform prior over a large interval is usually a bad idea. A HalfNormal or Exponential would be better.
2. The Metropolis sampler is known to be inefficient. The default sampler is NUTS, which is much more robust.
3. Always run more than one chain!

As to your question, it depends on what you want. If you want a _distribution_ of the mean and mode, you can probably use [`scipy.special.gamma`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.gamma.html) inside the `Deterministic`. If you want a _point estimate_ for the mean and mode, you're much better off sampling from the posterior and taking the mean and mode of your samples.

Hope this helped!

**Comment by pan-forsteri** [comment]
Thank you!!
