### ISSUE TITLE
Add prior visualization

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#3104]
Now that `sample_prior_predictive` exists, it would be nice to have a plot that can show histograms/kdes/ecdfs of the prior, and optionally the posterior.  See https://gist.github.com/ColCarroll/f2f700e92a56f42dd6a80194f047d216 for an example.  I would prefer not to require seaborn, though `arviz` might work with a little bit of prodding.  The intended output looks something like this:

![image](https://user-images.githubusercontent.com/2295568/42892748-98919578-8a80-11e8-81a6-4dd6a0ff0747.png)

**Comment by aloctavodia** [comment]
Shouldn't this be something for ArviZ?

**Comment by ColCarroll** [comment]
I think it is a little further down ArviZ's dev roadmap, since we don't really have a way of specifying a prior there yet (but I'd love it to be there eventually!).

**Comment by canyon289** [comment]
Is plain matplotlib acceptable until arviz is mature enough to deprecate this feature?

**Comment by ColCarroll** [comment]
Yah, I think so (unless @aloctavodia has plans for how to implement it there - I think the next object to get a handle on are sampler statistics and divergences).  Worst case scenario, an implementation here makes it easier to port over there.

Note in other plotting functions how we do not import `matplotlib` directly, since it is an optional dependency.

**Comment by canyon289** [comment]
By not directly do you mean try except block to handle import errors? Example below

https://github.com/pymc-devs/pymc3/blob/master/pymc3/plots/posteriorplot.py

If no ones taken this up I wouldn't mind going for it

**Comment by aloctavodia** [comment]
Thanks @canyon289  adding this to PyMC3 will be a very good contribution.

**Comment by canyon289** [comment]
Great I'm on it! Thanks all!

**Comment by canyon289** [comment]
Doing some research would this functionality fit as a part of the posterior plot in Arviz?

The big difference I see is @ColCarroll's gist shows a histogram while this seems to be a KDE line plot but in terms of being able to gauge distribution shapes either one will work I believe?

If it indeed does fit in Arviz I can submit a PR against that codebase but do let me know

http://arviz-devs.github.io/arviz/examples/posteriorplot.html

**Comment by canyon289** [comment]
Hey, I'll be able to start getting something together this weekend. Sorry for the delay

**Comment by canyon289** [comment]
For visibility
Right now I'm just trying to figure out how posteriorplot works in depth. To that extent figured I could make useful documentation for people at the same time.

https://github.com/arviz-devs/arviz/pull/145

**Comment by springcoil** [comment]
Any update on this @canyon289 ?

**Comment by canyon289** [comment]
At this point I think it is better off to implement this directly in Arviz. @ColCarroll has laid the groundwork for specifying priors in an InferenceData object which will allow for az.posteriorplot to handle this ask

After the merge of https://github.com/arviz-devs/arviz/pull/186, I believe this ask can be moved to arviz and implemented there. That's my perception anyway, If I am mistaken please let let me know!

**Comment by springcoil** [comment]
Ahh cool. Arviz makes sense

**Comment by adityalahiri** [comment]
Is this still open to be addressed or are we leaving it to arviz?

**Comment by canyon289** [comment]
Leaving it to arviz unless I'm mistaken @ColCarroll

**Comment by ColCarroll** [comment]
Yeah, let's do it in arviz!
