### ISSUE TITLE
Favicon for Docs would be cool

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#3112]
I didn't know where to put this.

I think the rocket logo as a favicon for the documentation page would be great. Would help a lot when going through the documentation
<img width="709" alt="screen shot 2018-07-22 at 10 30 45 am" src="https://user-images.githubusercontent.com/7213793/43048320-63c88a0a-8d9a-11e8-84d9-70d3fffd0515.png">

**Comment by twiecki** [comment]
Great suggestion @canyon289, if you know how to do it, want to do a PR?

**Comment by canyon289** [comment]
I would be happy to do so, Just to double check all the html/web files for the docs are generated from the docs folder using this script?

Is there a good way to "test" the changes as they would appear in the typical build?

https://github.com/pymc-devs/pymc3/blob/master/build_and_deploy_docs.sh
