### ISSUE TITLE
Dimension problem with more_replacements on sample_node

### ISSUE THREAD

**Issue by plison** [pymc-devs/pymc#3130]
I'm trying to reproduce the example of multilabel logistic regression with variational inference that is detailed in https://docs.pymc.io/notebooks/variational_api_quickstart.html, but I get a dimensionality error even before the start of the inference.

Here is my code (taken from the quickstart example mentioned above):

```python
import sklearn.datasets, sklearn.model_selection
import pymc3 as pm
import theano
import theano.tensor as tt

# Loading the Iris dataset
X, y = sklearn.datasets.load_iris(True)
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y)
Xt = theano.shared(X_train)
yt = theano.shared(y_train)

with pm.Model() as iris_model:
    
    # Creating the model
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3))
    alfa = pm.Flat('alfa',shape=(3,))
    z = tt.nnet.softmax(Xt.dot(beta) + alfa)
    yl = pm.Categorical('yl', p=z, observed=yt)
  
    inference = pm.SVGD(n_particles=500, jitter=1)
    approx = inference.approx
    
    # Tracking the accuracy of the model being fitted on train and test sets
    test_probs = approx.sample_node(z, more_replacements={Xt: X_test})
    test_ok = tt.eq(test_probs.argmax(-1), y_test)
 
```

The error I get is ``ValueError: Input dimension mis-match. (input[0].shape[0] = 112, input[1].shape[0] = 38)``.  

It seems the variable replacements made through the ``sample_node`` call are at the source of this error, since 112 is the size of the training set, while 38 is the size of the test set.  That's why the ``tt.eq`` fails, since it cannot compare arrays of difference size. 

I'm using PyMC3 version 3.5 (from ``pip install``)  and Theano 1.0.2 (with ``device=cpu``).

**Comment by junpenglao** [comment]
I never realize this but you cannot put test_ok within the model context, instead something like below would work:
```python
with pm.Model() as iris_model:
    
    # Creating the model
    beta = pm.Normal('beta', mu=0, sd=10, shape=(4,3))
    alfa = pm.Flat('alfa',shape=(3,))
    z = tt.nnet.softmax(Xt.dot(beta) + alfa)
    yl = pm.Categorical('yl', p=z, observed=yt)
  
    inference = pm.SVGD(n_particles=500, jitter=1)
    approx = inference.approx
    
    # Tracking the accuracy of the model being fitted on train and test sets
    test_probs = approx.sample_node(z, more_replacements={Xt: X_test})
test_ok = tt.eq(test_probs.argmax(-1), y_test)
```
Maybe @ferrine can explain why this is the case.
