### ISSUE TITLE
SMC - AttributeError: 'NoneType' object has no attribute 'likelihood_name'

### ISSUE THREAD

**Issue by jtlz2** [pymc-devs/pymc#3136]
Following

http://pymc3.readthedocs.io/en/latest/notebooks/SMC2_gaussians.html,

I get:

```
    model=ATMIP_test)
  File "/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/smc.py", line 465, in sample_smc
    'in `step`.'.format(step.likelihood_name))
AttributeError: 'NoneType' object has no attribute 'likelihood_name'
```

Any ideas? Thanks!

**Comment by aloctavodia** [comment]
That example is outdated, could you check [this one](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/SMC2_gaussians.ipynb)?
