### ISSUE TITLE
Feature Request: "db" option for other sampling methods

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3137]
The main sampling method has a way of writing the sample data into files using the `db` option.  But now there are two additional sampling methods, for the prior predictive and posterior predictive, but they produce results of different types (dictionaries, instead of traces), and don't support the `db` argument.  It would be nice to extend their API to be more orthogonal.

Also, I wonder if it's best to have their return values be simple dictionaries instead of some kind of object, because it means there's no place to hang methods for them.  For example, there's no place to put a method that will extract points from these results.

**Comment by ColCarroll** [comment]
Closed in favor of #2189
