### ISSUE TITLE
A question about sample_posterior_predictive function

### ISSUE THREAD

**Issue by zhengq01** [pymc-devs/pymc#3138]
I am trying the code in the tutorial as below,
 ```
data = np.random.randn(100)
with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sd=1)
    sd = pm.HalfNormal('sd', sd=1)
    obs = pm.Normal('obs', mu=mu, sd=sd, observed=data)

    trace = pm.sample()

with model:
    post_pred = pm.sample_posterior_predictive(trace, samples=500, size=len(data))

post_pred['obs'].shape
```

In my trying, I use pm.sample_ppc() to replace pm.sample_posterior_predictive() and all of the others keep the same. However, my result, i.e., post_pred['obs'].shape, is (500,100,100), which is different from the official answer, i.e., (500,100). I don't know the newly added dimension means.

**Comment by junpenglao** [comment]
Duplicated with https://github.com/pymc-devs/pymc3/issues/3081
