### ISSUE TITLE
Automate simplextransform

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#315]
Enforcing the sum-to-one constraint for Dirichlet should be automatic. Having to manually transform via `simplextransform` seems uneccessary, since you would never use a Dirichlet without this constraint.

**Comment by jsalvatier** [comment]
My thought was that there are multiple ways you could want to do this, but
having n-1 elements is probably the most common by far.

**Comment by twiecki** [comment]
Agree with the n-1 normalization method.

**Comment by twiecki** [comment]
@jsalvatier I think you did this change with #390?

**Comment by jsalvatier** [comment]
No I don't think I did.

**Comment by twiecki** [comment]
A user stumbled over this here: http://stats.stackexchange.com/questions/120209/pymc3-dirichlet-distribution/120418#120418

Anyway, I think we agree that we want to change it, just have to do it.

**Comment by jsalvatier** [comment]
fixed with automatic transforms.
