### ISSUE TITLE
Fix automated build on dockerhub

### ISSUE THREAD

**Issue by whilp** [pymc-devs/pymc#3160]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

The log of recent builds on dockerhub only shows failures:

https://hub.docker.com/r/pymc/pymc3/builds/

**Please provide the full traceback.**

The most recent attempt to build an image tagged `latest` failed as follows:

https://hub.docker.com/r/pymc/pymc3/builds/bpwkzmbbmaezgks6tblddnd/
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-1-tp5', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-06-23T07:58:56.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'1b30665', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-06-23T07:58:56.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-1-tp5
MinAPIVersion: 1.12
GitCommit: 1b30665
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/pymc/pymc3:latest...
Step 1/10 : FROM jupyter/minimal-notebook
 ---> c656e0daddcd
Step 2/10 : ARG SRC_DIR
 ---> Running in 46ac1fd850e2
Removing intermediate container 46ac1fd850e2
 ---> fc8e8a334c2b
Step 3/10 : MAINTAINER Austin Rochford <austin.rochford@gmail.com>
 ---> Running in b257c1381c53
Removing intermediate container b257c1381c53
 ---> a1feef46d7d2
Step 4/10 : ADD $SRC_DIR /home/jovyan/
 ---> c44955efa738
Step 5/10 : RUN /bin/bash /home/jovyan/scripts/create_testenv.sh --global --no-setup
 ---> Running in d01b6cc2d106
/bin/bash: /home/jovyan/scripts/create_testenv.sh: No such file or directory
Removing intermediate container d01b6cc2d106
The command '/bin/sh -c /bin/bash /home/jovyan/scripts/create_testenv.sh --global --no-setup' returned a non-zero code: 127
```

**Please provide any additional information below.**

[`scripts/create_testenv.sh`](https://github.com/pymc-devs/pymc3/blob/master/scripts/create_testenv.sh) appears to be in the right spot in this repository. Instead, I suspect that `ARG` isn't getting set as expected when building in dockerhub's infra.

https://github.com/pymc-devs/pymc3/blob/096d6fa062ad178b0e777652b9bf4ed65e6d3aee/scripts/Dockerfile#L3
https://github.com/pymc-devs/pymc3/blob/096d6fa062ad178b0e777652b9bf4ed65e6d3aee/scripts/start_container.sh#L13

Perhaps it would be sufficient to modify `Dockerfile` to include a default value for `SRCDIR` as follows:

```docker
ARG SRCDIR=.
```

https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

## Versions and main components

(n/a)

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by AustinRochford** [comment]
Thanks for reporting, I'll take a look

**Comment by AustinRochford** [comment]
See #3161. I'll check to see if the dockerhub build worked in a few hours

**Comment by whilp** [comment]
Right on!

**Comment by AustinRochford** [comment]
It does not appear to have worked.

https://hub.docker.com/r/pymc/pymc3/builds/bgncohmnyeg26i3otsyajkk/

**Comment by whilp** [comment]
Weird idea, but perhaps try “../“ (on the theory that dockerhub has the
dockerfile’s parent dir as the working directory.

**Comment by AustinRochford** [comment]
I'll give that a shot once I figure out how to test on dockerhub without merging to master.

**Comment by michaelosthege** [comment]
Hi @AustinRochford !
It looks like the `pymc3:latest` Docker image is [still broken](https://github.com/pymc-devs/pymc3/issues/4749#issuecomment-858474773) with the same bug as in #4386.
The builds probably need to be updated to distinguish between `v4`, latest `main` and the upcoming `v4`.

But where does the build even happen? Which system is responsible? Possibly the best option could be to move the image build into the [release GitHub Action pipeline](https://github.com/pymc-devs/pymc3/blob/main/.github/workflows/release.yml).

**Comment by michaelosthege** [comment]
Closing in favor of #5939
