### ISSUE TITLE
pymc3.distributions.dist_math.normal_lcdf breaks ADVI in FAST_COMPILE mode (yields nans), NUTS samples just fine

### ISSUE THREAD

**Issue by lapsh** [pymc-devs/pymc#3163]
## Description of your problem
Using normal_lcdf from pymc3.distributions.dist_math.normal_lcdf seems to break ADVI somewhere. NUTS samples from this model just fine (with about 5-7% of divergent samples, but the trace looks just fine). ADVI gives an error. Sometimes earlier, sometimes later. Larger learning_rates make it earlier.

"normal_lcdf" is a necessary component for this bug to reproduce, but it only manifests with ADVI (and other variational inferences). It only manifests in the FAST_COMPILE mode of Theano.

However, tracking the mean and variance of the only variable in the model does not reveal any unusual values. I know, this model is useless, but it's mathematically ok. This model has a nice proper posterior (one can plot model.logp as it has only one variable). It's the minimal model I found to reproduce the effect.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import theano
theano.config.mode = 'FAST_COMPILE'
import pymc3 as pm
from pymc3.distributions.dist_math import normal_lcdf

model = pm.Model()
with model:
    sigma = pm.Exponential('sigma', 1.0)
    pot_upper = normal_lcdf(0.0, sigma, 1.0) 
    pm.Potential('Ratings', pot_upper)
    ad = pm.ADVI()
    tracker = pm.callbacks.Tracker(
        mean=ad.approx.mean.eval,  # callable that returns mean
        std=ad.approx.std.eval  # callable that returns std
    )
    ad.fit(callbacks=[tracker])
```

**Please provide the full traceback.**
```python
Average Loss = 0.20976:  69%|████████▎   | 6909/10000 [00:38<00:17, 181.17it/s]
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-6-31967d5745ad> in <module>()
     12         std=ad.approx.std.eval  # callable that returns std
     13     )
---> 14     ad.fit(callbacks=[tracker])

C:\Programs\Anaconda3\envs\pymc3\lib\site-packages\pymc3\variational\inference.py in fit(self, n, score, callbacks, progressbar, **kwargs)
    134         with tqdm.trange(n, disable=not progressbar) as progress:
    135             if score:
--> 136                 state = self._iterate_with_loss(0, n, step_func, progress, callbacks)
    137             else:
    138                 state = self._iterate_without_loss(0, n, step_func, progress, callbacks)

C:\Programs\Anaconda3\envs\pymc3\lib\site-packages\pymc3\variational\inference.py in _iterate_with_loss(self, s, n, step_func, progress, callbacks)
    218                     except IndexError:
    219                         pass
--> 220                     raise FloatingPointError('\n'.join(errmsg))
    221                 scores[i] = e
    222                 if i % 10 == 0:

FloatingPointError: NaN occurred in optimization. 
The current approximation of RV `sigma_log__`.ravel()[0] is NaN.
Try tracking this parameter: http://docs.pymc.io/notebooks/variational_api_quickstart.html#Tracking-parameters
```

**Please provide any additional information below.**
The tracker plot is like this.
![image](https://user-images.githubusercontent.com/7813589/44402989-ef49d380-a55b-11e8-8892-b8b9f3aed47b.png)

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.2
* Python Version: 3.6.4 :: Anaconda, Inc. (x64)
* Operating system: Windows 7 (x64)
* How did you install PyMC3: "pip install pymc3" from Anaconda Prompt

**Comment by junpenglao** [comment]
Anybody reproduce this? Runs fine on my env (Linux, same PyMC3 etc version).

**Comment by lapsh** [comment]
I'm sorry. You have to have Theano in the FAST_COMPILE mode for this. Everything runs fine without it. Sorry for not including this earlier. I've updated the code above. I've created a brand new environment in Anaconda to check. It reproduces. Here's what I've done:

```
conda create -n test
conda activate test
conda install numpy scipy matplotlib theano
pip install pymc3
```

Edit: I was also able to reproduce it using a Docker container with a Linux env.

Edit2: It also reproduces in Google Colab (you have to do `!pip install pymc3` first):
https://colab.research.google.com/gist/lapsh/84d92b6d25fbe685472da7c1b3f44b9c/reproduce_bug_3163.ipynb

**Comment by ricardoV94** [comment]
I can confirm this bug in the latest version. Only happens with fast_compile

**Comment by ricardoV94** [comment]
There is probably a relevant stabiliziation optimization that only shows up in `fast_run`. It seems like this is too much of an edge case to warrant investigation on our behalf. Closing for the time being
