### ISSUE TITLE
'Model' object has no attribute 'logp_elemwiset'

### ISSUE THREAD

**Issue by eigenfoo** [pymc-devs/pymc#3172]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm

with pm.Model() as model:
    pm.Normal('x')
    pm.sample()

model.logp_elemwise()
```

**Please provide the full traceback.**
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d2571f9b5606> in <module>()
      5     pm.sample()
      6
----> 7 model.logp_elemwise()

~/Desktop/pymc3/pymc3/model.py in logp_elemwise(self)
    206     @property
    207     def logp_elemwise(self):
--> 208         return self.model.fn(self.logp_elemwiset)
    209
    210     def dlogp(self, vars=None):

AttributeError: 'Model' object has no attribute 'logp_elemwiset'
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.2+2.gc449c86
* Python Version: 3.6.4
* Operating system: macOS
* How did you install PyMC3: (conda/pip) pip

**Comment by twiecki** [comment]
Where is a reference to that?

**Comment by eigenfoo** [comment]
There are quite a few references to `self.logp_elemwiset` in `model.py`. Not sure what it's for, though.

**Comment by junpenglao** [comment]
It's for RV only.
