### ISSUE TITLE
Minor edit to docs: https://docs.pymc.io/prob_dists.html

### ISSUE THREAD

**Issue by sidravi1** [pymc-devs/pymc#3173]
Hi,

The example for the exponential survival function should be:

$$
\begin{split}f(c, t) = \left\{ \begin{array}{l} \exp(-\lambda t), \text{if c=1} \\            \lambda \exp(-\lambda t), \text{if c=0}  \end{array} \right.\end{split}
$$

it is missing the negative sign in front of the lambda.

**Comment by eigenfoo** [comment]
Thanks for the report @sidravi1!
