### ISSUE TITLE
Error in trace.report._run_convergence_checks()

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3179]
Running sample with `trace=db` for `db` a text backend, causes an error in `trace.report._run_convergence_checks()`.

## Description of your problem

If I create a `pm.backends.Text` instance, and pass it as the `trace` argument to the `pm.sampling.sample()` function, I get an error.  When I remove that argument, the call terminates successfully.

Investigating the traceback, I find that when I pass the `trace=db` with multiple chains, the above function receives a trace (return value from `get_values`) that is of type `Array[nchains]` where each entry in the array is of type `numpy.ndarray[nsamples]`.  However, the code **expects** a trace of type `Array[nchains][nsamples]`.  In particular, it expects `shape` to be a 2-tuple, when it's only `(20,)`.

**Please provide a minimal, self-contained, and reproducible example.**
```python
    with model.model:
        # db = pm.backends.Text(trace_filename)
        model.trace = pm.sampling.sample(num_draws=10000, chains=20, cores=4, tune=1000) # , trace=db)
```
The above is not fully reproducible, I am afraid.

**Please provide the full traceback.**
```python
ValueError                                Traceback (most recent call last)
<ipython-input-73-88e4799fa24e> in <module>()
----> 1 do_main('NOR')

~/projects/xplan/yeast-gates-data/Three_Layer_Analysis.py in do_main(gate)
    237     with model.model:
    238         db = pm.backends.Text(trace_filename)
--> 239         model.trace = pm.sampling.sample(num_draws=10000, chains=20, cores=4, trace=db)
    240     entropy = model.entropy()
    241     return entropy

~/Library/Python/3.7/lib/python/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    467                 warnings.warn("The number of samples is too small to check convergence reliably.")
    468             else:
--> 469                 trace.report._run_convergence_checks(trace, model)
    470 
    471         trace.report._log_summary()

~/Library/Python/3.7/lib/python/site-packages/pymc3/backends/report.py in _run_convergence_checks(self, trace, model)
     81                 varnames.append(rv_name)
     82 
---> 83         self._effective_n = effective_n = diagnostics.effective_n(trace, varnames)
     84         self._gelman_rubin = gelman_rubin = diagnostics.gelman_rubin(trace, varnames)
     85 

~/Library/Python/3.7/lib/python/site-packages/pymc3/diagnostics.py in effective_n(mtrace, varnames, include_transformed)
    298 
    299     for var in varnames:
--> 300         n_eff[var] = generate_neff(mtrace.get_values(var, combine=False))
    301 
    302     return n_eff

~/Library/Python/3.7/lib/python/site-packages/pymc3/diagnostics.py in generate_neff(trace_values)
    276         # Iterate over tuples of indices of the shape of var
    277         for tup in np.ndindex(*list(x.shape[:-2])):
--> 278             _n_eff[tup] = get_neff(x[tup])
    279 
    280         if len(shape) == 2:

~/Library/Python/3.7/lib/python/site-packages/pymc3/diagnostics.py in get_neff(x)
    217         """
    218         trace_value = x.T
--> 219         nchain, n_samples = trace_value.shape
    220 
    221         acov = np.asarray([autocov(trace_value[chain]) for chain in range(nchain)])

ValueError: not enough values to unpack (expected 2, got 1)
```

**Please provide any additional information below.**

See my discussion here: https://discourse.pymc.io/t/chains-parameter-and-multiprocess-sampling/1844

Note that when I pass a `text` backend to trace, I am passing an instance of `backends.text` which is **not** an instance of `MultiTrace`.  I believe that the root of the problem is the difference between the method for `get_values` on `backends.text`:

    def get_values(self, varname, burn=0, thin=1):
        """Get values from trace.

        Parameters
        ----------
        varname : str
        burn : int
        thin : int

        Returns
        -------
        A NumPy array
        """
        self._load_df()
        var_df = self.df[self.flat_names[varname]]
        shape = (self.df.shape[0],) + self.var_shapes[varname]
        vals = var_df.values.ravel().reshape(shape)
        return vals[burn::thin]

and the version for `MultiTrace`:

    def get_values(self, varname, burn=0, thin=1, combine=True, chains=None,
                   squeeze=True):
        """Get values from traces.

        Parameters
        ----------
        varname : str
        burn : int
        thin : int
        combine : bool
            If True, results from `chains` will be concatenated.
        chains : int or list of ints
            Chains to retrieve. If None, all chains are used. A single
            chain value can also be given.
        squeeze : bool
            Return a single array element if the resulting list of
            values only has one element. If False, the result will
            always be a list of arrays, even if `combine` is True.

        Returns
        -------
        A list of NumPy arrays or a single NumPy array (depending on
        `squeeze`).
        """
        if chains is None:
            chains = self.chains
        varname = str(varname)
        try:
            results = [self._straces[chain].get_values(varname, burn, thin)
                       for chain in chains]
        except TypeError:  # Single chain passed.
            results = [self._straces[chains].get_values(varname, burn, thin)]
        return _squeeze_cat(results, combine, squeeze)

These two methods can return values of pretty different types, that need to be indexed differently.

## Versions and main components

* PyMC3 Version:  HEAD -- 76c024312fc4d84dc7f56885f895adb09fb74d09
* Theano Version: 
* Python Version: 3.7
* Operating system: MacOS
* How did you install PyMC3: (conda/pip) pip from the source

**Comment by rpgoldman** [comment]
P.S. I will see if a workaround is possible by disabling the convergence checks for now.

**Comment by rpgoldman** [comment]
Yes, it seems that passing `compute_convergence_checks=False` to `sample` avoids this bug.  Suggestion: patch `sample` so that `compute_convergence_checks` is **disabled** when `trace != None` -- and I would suggest emitting a warning string when that is done, so the user realizes that the tests have been disabled.  That would avoid fatal errors like this while permitting traces to be saved.

An alternative work-around suggestion would be to wrap an error handler around the convergence checks and skip them with a warning message if they fail.

I believe some workaround like this is desirable because making all the various `get_values` methods consistent might take some effort and break other code (is there a test suite for this?).  This is a case where type hinting might be helpful, but I have not tried putting type hints into the body of PyMC3, since they would make it unusable in Python versions before 3.6.  I don't believe there's any way to make fully type-hinted code backwards compatible.

**Comment by michaelosthege** [comment]
Issue is outdated. The text backend was removed.
