### ISSUE TITLE
did not display the figures when using pm.traceplot(trace)

### ISSUE THREAD

**Issue by fangqx** [pymc-devs/pymc#3183]
when i am using pm.traceplot in python console after finishing the sampling process, the figures do not display. I tried to add the plt.show(), it still does not work. could anyone help me find the reason? thanks.

pm.traceplot(trace)
Out[6]: 
array([[<matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25B7A0F0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25DCE208>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25EF64E0>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25DF97B8>],
       [<matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25E22AC8>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x0000022B25E4AD68>]],
      dtype=object)
Figure size 864x432 with 6 Axes

* PyMC3 Version:3.0
* Theano Version:
* Python Version:3.5
* Operating system:win10
* How did you install PyMC3: (conda)

**Comment by fonnesbeck** [comment]
This is likely a Matplotlib issue rather than PyMC. Can you confirm which backend you are using for plotting? Can you display a generic Matplotlib plot for instance?

**Comment by fangqx** [comment]
@fonnesbeck Thanks. Yes, it is a Matplotlib problem!  I removed the Matplotlib and re-install it (2.23 version). it works! However, the pymc3 was removed also (i donot know why) after re-installing the Matplotlib. So I install pymc3 further and same problem appeared (plot does not display). The two packages are conflict in my system. does any one have similar problem to me?

import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,4,9,16], 'ro')
plt.axis([0, 6, 0, 20])
plt.show()
Figure size 432x288 with 1 Axes

**Comment by fangqx** [comment]
WHEN i imported the matplotlib separately, the following message appeared, and the plot display works.  Does anyone know the reason for this? Thanks. 

import matplotlib.pyplot as plt 
Backend Qt5Agg is interactive backend. Turning interactive mode on.

**Comment by giri786** [comment]
it worked for me when i used %matplotlib inline
