### ISSUE TITLE
`ndarray` backend does not comply with advertised API

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3184]
The documentation here: https://docs.pymc.io/api/backends.html reports that 

    Saved backends can be loaded using load function in the module for the specific backend.

However, if we read down further in this page, we see in the discussion of `backends.ndarray` that the function for reloading is `load_trace`.  This isn't a disaster, but certainly `pymc3.backends.ndarray.load_trace` should be renamed to `load`, with `load_trace` being kept as an alias for backwards compatibility (and deprecated).

**Comment by rpgoldman** [comment]
See pull request #3186

**Comment by Raahul-Singh** [comment]
Hi! Is more work required here?

**Comment by rpgoldman** [comment]
@Raahul-Singh I actually gave up on this, because it seemed too hard to fix: MultiTrace really does not comply with the backends protocol, and I'm not sure that any of the other backends do, either.

It seems like PyMC3 is moving towards just deprecating and removing the other protocols, which would make the ndarray one all there is, and drop the alleged protocol.

So probably easier to simply fix the docs to remove discussion of this protocol.

**Comment by michaelosthege** [comment]
not dramatic enough to take care of.. closing as part of cleanup
