### ISSUE TITLE
save and reload using text backend does not preserve iteration properties

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3185]
## Description of your problem

A `MultiTrace` with multiple chains can be iterated over, indexed by the points (including points in all chains).  A `MultiTrace` that has been saved to `backends.text` and then reloaded does not correctly support iteration (`for point in trace`), instead only through the `points` (`for point in trace.points([i])` where `i` is a chain number).

This issue is a placeholder for now.  I will either get a minimal, self-contained example, or see if I can figure out why the iteration doesn't work the same in the two cases.

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**
No error trace.

**Please provide any additional information below.**
### Here is my original report to discourse

I have this line of code that I use as part of computing (approximating) the entropy of a posterior distribution: 
``` python
         trace_logps: np.ArrayLike[np.longdouble] = \ 
            np.fromiter((self.logp_point(i) for i in self.trace),
                         np.longdouble) 
``` 
This line of code works fine when I have just created a trace. *However*, if I _save_ a trace to the `text` backend, and then use `pm.backends.text.load()` to reload it, the above bit of code no longer works. AFAICT, if I have a "fresh" `MultiTrace`, then I can iterate over it, and the iteration passes over all the points of all the chains.  *But* if I get a "reloaded" `MultiTrace`, this iterator does not work, and instead I get 
```
 In [55] np.fromiter((model.logp_point(i) for i in trace), np.longdouble) 
Out [55] array([], dtype=float128) 
```
so it seems like somehow the original `MultiTrace` is iterable and the reloaded one is not.  
Is this a bug?  Should I replace this to *always* use `for i in trace.points()`?  If so, it still seems like something's wrong with the way traces are being handled and/or "rehydrated."

### Another data point
Here's what I see when I look at a `MultiTrace` and then what should be the same `MultiTrace` after reloading from the text backend:
```
In [81]: len(list(stored_trace.points()))
Out[81]: 30000

In [82]: len(list(xnor_model.trace.points()))
Out[82]: 10000
```
The "unstored" model, `xnor_model.trace` seems to have the right count, given the definition in the docs, since the sampling parameters included `chains=20, draws=10000`.
I don't know why the restored model, `stored_trace` reports 30000 points.

*However* when I try to enumerate the points in each of the chains for the two traces, I get very odd numbers:
```
n [86]: ( [len(list(xnor_model.trace.points(chains=[i]))) for i in range(xnor_model.trace.nchains)],[len(list(stored_trace.points(chains=[i]))) for i in range(stored_trace.nchains)] )
Out[86]: 
([500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500,
  500],
 [1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500,
  1500])
```
I believe each of these should be lists of length 20, with either 500 or 10,000 elements -- the docs for `sample` aren't that clear about whether `draws` is "total draws' or "draws per chain."
## Versions and main components

* PyMC3 Version: HEAD: bef5f143c3e4cc95f9aca74c1cf63bbc0c81249e
* Theano Version: 1.0.2
* Python Version: 3.7.0
* Operating system: MacOS 10.13.6
* How did you install PyMC3: (conda/pip) pip3 from source

**Comment by rpgoldman** [comment]
Quick update -- the problem is likely to be in serialization.  According to the above, each of the 20 chains in my source `MultiTrace` has 500 entries, but looking at the `.csv` files for the saved trace, each has 1500 lines.

**Comment by rpgoldman** [comment]
I *suspect* this is a problem in multiprocess sampling, but need to check and see if it occurs with uniprocess sampling, as well.

**Comment by rpgoldman** [comment]
OK, I checked overnight and when running with `chains=20` and `cores=1` I still see the divergence in the number of elements in the stored trace (judging from number of lines in the `.csv` files).  So I'm not sure what is going on in there, but I believe there's something wrong in the way traces are saved to `text` backends.  Has anyone else been using these?  Seeing anything similar? If I get time today, I will see if I can write a test that demonstrates the issue.

**Comment by junpenglao** [comment]
FYI, you might not want to spend too much time on it as we will likely deprecate the text backend and move to xarray for storing trace.

**Comment by rpgoldman** [comment]
OK, that makes things more clear.  So as a workaround I should try using `Text.backends.NDArray`?  Are we confident that it works better?  I'm not sure what "xarray" is, since I'm not a real python programmer.

Based on my experience, I'd be inclined to mark the `text` backend as deprecated today -- it seems like it might simply be broken.  Right now, having the docs and code out there is just an invitation for users to lose a lot of time (as I have done).

I'm looking into one of the csv files and it seems like it has duplicate rows.  I'm fighting with Excel, but will report back, if I find that that's the issue.  In that case, it *might* be possible to rapidly identify what's responsible for writing these duplicates.

Something that concerns me is that these CSV files are written as a side-effect of the sampling process (i.e., they are not dumped later), so I wonder if all the backends will have the same issues.

**Comment by junpenglao** [comment]
I think the NDArray is the most recent one so it likely works better, @ColCarroll?

**Comment by rpgoldman** [comment]
I was able to use `NDArray` if I did a `save_trace` followed by a `load`, but if I tried to make the `NDArray` object using the `trace` keyword argument to `sample`, it didn't work (got a garbled data structure).  So I think for now saving and loading traces is best done by hand, rather than as a side-effect of sampling.

**Comment by rpgoldman** [comment]
This causes me to reflect on my question about `load` and `load_trace` some more. It seems to me that the `ndarray` backend is something quite different from the other two backends, in that it is a way to persist a trace *after you have it* while the other two backends can only be used to save a trace *while you are collecting it*.  The latter task seems much harder (for one thing, it has to be reimplemented for each sampling strategy), so maybe it's not surprising that it doesn't work as well as just collecting a trace, writing it to a file, and then reading it back in again.

**Comment by rpgoldman** [comment]
@junpenglao Is there any chance that the change from lists almost everywhere to iterators almost everywhere could be causing this?  I'm getting so many odd behaviors when I try to save traces, that I wonder if `save_trace` could be "emptying" some iterator.  Or if, when I iterate over the points in a trace estimating the entropy that I might be emptying an iterator.

**Comment by junpenglao** [comment]
Hmm, your assessment is correct re 
> It seems to me that the ndarray backend is something quite different from the other two backends, in that it is a way to persist a trace after you have it while the other two backends can only be used to save a trace while you are collecting it. The latter task seems much harder (for one thing, it has to be reimplemented for each sampling strategy), so maybe it's not surprising that it doesn't work as well as just collecting a trace, writing it to a file, and then reading it back in again.

However, I am not too familiar with text_backend, pinning @ColCarroll

**Comment by eigenfoo** [comment]
> It seems to me that the ndarray backend is something quite different from the other two backends, in that it is a way to persist a trace after you have it while the other two backends can only be used to save a trace while you are collecting it.

As I understand, this distinction is the point of having the `text` and `sqlite` backends: for applications in which you don't want to/can't store the entire trace in memory, and therefore must write as you sample.

I think it's important to have at least one backend that supports this. I'm not sure how arviz's xarray backends work, but I'm guessing that it doesn't support this? In which case, deprecating the text `backend` would certainly close this issue, but we should definitely keep the `sqlite` backend around.

I don't know much about the backends though, so I'll defer to the core devs 😃 

FYI @rpgoldman xarray is [this OSS project](https://xarray.pydata.org/en/stable/)

**Comment by michaelosthege** [comment]
Given that we're likely deprecting backends (see https://github.com/pymc-devs/pymc3/issues/2189) I'm closing this already...
