### ISSUE TITLE
pymc3 - GLM 

### ISSUE THREAD

**Issue by andreagiussani** [pymc-devs/pymc#3191]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Question
Hi everyone,
I have an issue when applying the standard GLM formula with many features.
Is there any way to write Y ~ X1+X2 +...+Xn (with n very large) without using the symbol +?
I would love using a more compact syntax, such as X1:Xn.

**This is a small example of what I am basically trying to do.**
```python
niter = 10000
with pm.Model() as model0:
    pm.glm.GLM.from_formula('target ~ feat1+feat2 + feat3', df, family=pm.glm.families.Binomial()) 
    trace0 = pm.sample(niter, step=pm.Metropolis(), random_seed=123, progressbar=True)
```

## Versions and main components

* Python Version: 3.5
* Operating system: Windows 10
* How did you install PyMC3: (conda/pip) pip

**Comment by andreagiussani** [comment]
I moved the question on  https://discourse.pymc.io

**Comment by twiecki** [comment]
Best to ask this on discourse.

**Comment by andreagiussani** [comment]
thanks
