### ISSUE TITLE
Changepoint Model

### ISSUE THREAD

**Issue by gcgibson** [pymc-devs/pymc#3204]
I'm having a little trouble translating the following JAGS model to pymc3 

```
   model {
      for (i in 1:N) {
           tau[i] <- ifelse(i < cp, tau1,tau2)
           N_t_inf[i] ~ dnorm(fcast[i],tau[i])
           N_t_T[i] ~ dbinom(pstar[i],round(N_t_inf[i]))
      }  
      
      cp ~ dunif(1,N)   
     
      invTau1 ~ dgamma(100, 1)
      tau1 <- 1/invTau1

      invTau2 ~ dgamma(1, 1)
      tau2 <- 1/invTau2

      }"
```

The issue is that I need a index specific change-point but I only see pymc3 likelihoods written over all observations, not indexed by obs. Is there someway I can do this in pymc3?

**Comment by twiecki** [comment]
Can you post that question to our discourse?
