### ISSUE TITLE
MultiTrace.points() documentation needs expansion

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3211]
Discussing this with a colleague, we seem to have discovered that the `points` method on `MultiTrace` returns an iterator *that includes the tuning samples*.
This is not stated in the docstring.
Are we correct in this interpretation?  If so, it seems worthy of an addition to the docstring, and I could do a PR for that, but I wanted to check.

**Comment by ColCarroll** [comment]
I am not seeing that, at least on master:

```
import pymc3 as pm

with pm.Model():
    pm.Normal('x')
    trace = pm.sample(draws=500, chains=2, tune=2000)

len(list(trace.points()))  # 1000
```

Let me know if this matches with your observation!

**Comment by ColCarroll** [comment]
By the way - I agree the `MultiTrace` object is confusing - any documentation improvements would be _greatly_ appreciated, and I would be happy to help talk about API improvements as well. There was a discussion some time ago about `draws=500, chains=2` meaning each chain gets 500 samples, which might be counterintuitive, but ended up being the agreed upon interpretation.

**Comment by rpgoldman** [comment]
I'll work this with my colleague -- we were seeing odd results where iterating over the traces directly versus using the `points()` iterator.  I'll grab an example and post it here.

**Comment by rpgoldman** [comment]
Here's what is confusing us:
```
In [5]: trace[0]
Out[5]: 
{'normal': -0.10992042333396544,
 'half_log__': -1.0339894351592123,
 'half': 0.35558554166307577}

In [6]: ps = trace.points()
n [8]: next(ps)
Out[8]: 
{'normal': 0.11418676968992847,
 'half_log__': -0.40930139567214885,
 'half': 0.6641140410575538}
```
Shouldn't the first element in the `ps` iterator be the same as `trace[0]`?

**Comment by rpgoldman** [comment]
My colleague, Alex, put me straight.  This is because the numerical iterator of `MultiTrace` iterates only over the *last* chain, and the `points()` iterator iterates over *all* chains, from first to last.  Is that right?

**Comment by rpgoldman** [comment]
@ColCarroll With respect to this, as far as I can tell the MultiTrace docstring is not hooked into the API documentation for PyMC3.  I'm not sure I fully understand how restructured text works, but I can try to make a pull request to get that in, if it would be helpful.

**Comment by OriolAbril** [comment]
Closing this given how the idea is moving away from multitrace and it has already been done wherever easy-ish
