### ISSUE TITLE
User-defined diagonal noise for stabilized covariance to avoid non-PSD in GP

### ISSUE THREAD

**Issue by Guangyi-Z** [pymc-devs/pymc#3217]
I have posted all the details in the forum.
https://discourse.pymc.io/t/a-very-simple-gp-fails-giving-not-positive-semidefinite-covariance-and-nan-prediction/1976/10

I think it makes sense to provide an extra parameter to let the user define a larger diagonal noise to stabilize the covariance, in extreme cases like mine.
If you guys agree, I am glad to make a pull request.

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.2
* Python Version: 3.6.5
* Operating system: OSX 10.13.6
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
I think this is already an option in GP, @bwengals ?

**Comment by Guangyi-Z** [comment]
Not really.
Either you provide all `X, y, noise` or you stay with the default `1e-6` noise.

**Comment by bwengals** [comment]
no its not currently option.  In the `stabilize` function in the gp/utils.py file its fixed at 1e-6 I believe.   We could make it an additional kwarg for each of the GP implementations.  As a user you could get around it quickly by adding a `cov.WhiteNoise(1e-4)` or something to the covariance matrix.  

What do people think about adding this as a kwarg?

**Comment by Guangyi-Z** [comment]
Oh, true. We can add `cov.WhiteNoise(1e-4)` when we setup the cov function.
In that case, this option seems not very necessary.
Thanks.

**Comment by bwengals** [comment]
I guess just keep in mind that you're really using an offset of 1e-4 + 1e-6 then
