### ISSUE TITLE
pm.sample does not warn when using an unused argument is passed

### ISSUE THREAD

**Issue by nbud** [pymc-devs/pymc#3226]
## Description of your problem

```python
with model:
    trace = pm.sample(500, core=4, target_accept=0.95)
```

This code raises no exception or warning despite ``core`` and ``target_accept`` are unused arguments. This code won't have the intended effect and is hard to debug. The desired behaviour would be to raise a warning or an exception when unused arguments are passed.

For the record, the corrected code is:
```python
with model:
    trace = pm.sample(500, cores=4, nuts_kwargs=dict(target_accept=0.95))
```

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version:
* Python Version: 3.6
* Operating system: Windows
* How did you install PyMC3: conda

**Comment by fonnesbeck** [comment]
We should remove `nuts_kwargs` and simply have step methods look for their arguments in `kwargs`

**Comment by ColCarroll** [comment]
Would you prefer that to throwing errors when unused arguments are passed? I think it would be easy to support one or the other, but not both.

**Comment by springcoil** [comment]
I think @fonnesbeck is right here. It'd be better API wise - by being clearer as a user - to remove `nuts_kwargs` than have errors.

**Comment by nbud** [comment]
Either way, it would be good to warn the user when an unused argument is passed, including for example passing ``target_accept`` or ``nuts_kwargs`` (depending on the chosen implementation) to a Step which does not use these arguments.

**Comment by eigenfoo** [comment]
@fonnesbeck what about `step_kwargs`? Currently it looks like there are three ways to pass an option: through `nuts_kwargs`, through `step_kwargs`, or as a regular kwarg. I think the most sensible thing to is to agree on one, and deprecate the other two?

This issue is related to #3197

**Comment by fonnesbeck** [comment]
Unifying them under `kwargs` would be my preference. I will try nd put a PR together later today.
