### ISSUE TITLE
pm.Model() is missing in Bayes_factor.ipynb

### ISSUE THREAD

**Issue by Chetanbuye12** [pymc-devs/pymc#3232]
In the notebook Bayes_factor.ipynb the initialization of pm.Model() cell is missing, please do resolve it.

**Comment by twiecki** [comment]
@Chetanbuye12 How does the NB execute without that?

**Comment by Chetanbuye12** [comment]
It's not implementing. To the best of my knowledge one ipynb cell is missing in the file Bayes_factor.ipynb

**Comment by twiecki** [comment]
Want to do a PR with the fix?

**Comment by Ahanmr** [comment]
pm.summary(traces[0], varnames='a').round(2) here, traces is not defined, and hence it is not working, any suggestion?
![screenshot_2018-11-12 pymc3 issue fix](https://user-images.githubusercontent.com/26196002/48327964-b48d9e00-e667-11e8-9577-6180cf408488.png)
