### ISSUE TITLE
Speed of tests on Travis

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#3236]
I just wanted to put this, as a general point. I think our speed of tests on travis CI is a bit slow.
Does anyone else agree? Is this something we could fix?

**Comment by MarcoGorelli** [comment]
Closing as travis is no longer used (there already seem to be some speed gains from using GitHub Actions instead, it's usually taking less than 40 minutes - I think travis would sometimes take longer than that to even start)
