### ISSUE TITLE
sample_posterior_predictive  appears to be missing on PyPi distribution

### ISSUE THREAD

**Issue by minggli** [pymc-devs/pymc#3243]
According to the docs, on https://docs.pymc.io/api/inference.html?highlight=sample_posterior_predictive, there is a `sample_posterior_predictive` method at package root level, but for `3.5.0` installed from PyPi, the method is missing in the code if I'm not wrong.

```python
import pymc3 as pm
pm.__version__
pm.sample_posterior_predictive
```

```python
'3.5'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pymc3' has no attribute 'sample_posterior_predictive'
```
When cloning from master, it works fine.

## Versions and main components

* PyMC3 Version: 3.5.0
* Theano Version: 1.0
* Python Version: 3.7.0
* Operating system: MacOS
* How did you install PyMC3: pip

**Comment by twiecki** [comment]
Indeed, that seems to have not made it into the release for some reason. For now you can use `sample_ppc` which is the same, or install the current master branch, or wait for the next release.

**Comment by minggli** [comment]
@twiecki thanks. looking forward to next release. 

By the way, I think you are going to a Bayesian Mixer meet up in London. hope to see you there.

**Comment by twiecki** [comment]
@minggli Great, see you there!

**Comment by springcoil** [comment]
@minggli I'm glad you mentioned this in a pub last night :)

**Comment by eigenfoo** [comment]
@twiecki [we're on `v3.6` now](https://github.com/pymc-devs/pymc3/tree/v3.6), and `sample_posterior_predictive` is now released. We can close this 😄
