### ISSUE TITLE
Deprecated data source used in "Getting Started With PyMC3"

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [pymc-devs/pymc#3262]
## Deprecated data source used in "Getting Started With PyMC3"

The tutorial uses pandas-datareader for reading financial data from Yahoo, but that is now deprecated:

From the pandas-datareader documentation:

"As of v0.6.0 Yahoo!, Google Options, Google Quotes and EDGAR have been immediately deprecated due to large changes in their API and no stable replacement. "

Obtaining the data still works, but now (Nov 18 2018) a NaN value is stored in the first position of the series and must be removed by hand. And of course the whole data may stop being provided any time, so you might want to modify the tutorial so that people remain able to run the example in the future.

**Comment by twiecki** [comment]
Thanks, we should probably store the CSV file instead.

**Comment by eigenfoo** [comment]
@twiecki this PR is resolved by #3288, looks like we can close it 😃

**Comment by twiecki** [comment]
Thanks @eigenfoo!
