### ISSUE TITLE
MultiTrace object doesn't fully implement Mapping API

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3264]
## Description of your problem

I was trying to make an informative type stub for `MultiTrace`, which intuitively seems to me to be a `Mapping[Union[int ,str, Tuple[str,slice]], ndarray]`.  _But_ the `Mapping` protocol requires `__iter__` in addition to `__getitem__` and `__len__`, and `MultiTrace` doesn't offer that.  

Would it be reasonable to add an `__iter__` that iterates over the variables, producing `ndarray`s?  The problem with this is that it doesn't really seem to make sense to iterate over the variables without knowing what the variables.

The alternative would be to add an iterator based on time points, that would return `Point` dictionaries, but that adds a new kind of complexity, and we have other ways of pulling out points.  The big advantage of this is that implicit indexing makes more sense over an ordered set like time points.

TBH, it seems kind of wrong that the python type system doesn't provide a protocol for a mapping that is not iterable, but there it is.

I'd be happy to provide a PR with this method definition if the community thinks it would be a good idea.

**Comment by rpgoldman** [comment]
I guess an alternative would be to have an iterator that generates `Tuple[Varname, ndarray]`.

**Comment by junpenglao** [comment]
Similar discussion has come up before: https://github.com/pymc-devs/pymc3/pull/2802
I think it is a good idea, but approaching it might be a bit difficult as currently it is not done consistently (the way ppl use iter to access what from the trace), so it might break some code...

**Comment by rpgoldman** [comment]
I see.  I was working on this, and as I looked deeper it became clear that it would not be easy to implement the `Mapping` python type for a number of reasons.  For one, the `Mapping` protocol is a higher order one, and requires that the `__iter__()` method's type should agree with the type of the `__getitem__()` method, which I believe is difficult, if not impossible, because of the flexibility of the ways that `MultiTrace` can be indexed.  I believe that the `__getitem__()` signature is
``` python
    def __getitem__(self, idx: Union[int,str,Tuple[str,slice]]) -> ndarray: ...
```
which would require that the `MultiTrace` be a 
```
Mapping(Union[int, str, Tuple[str, slice]], ndarray)
```
and hence be an
```
Iterable(Union[int, str, Tuple[str, slice]])
```
... which I'm not sure even makes any sense.  I could be wrong about this, but I believe that the problem is that the behavior that `MultiTrace` exhibits is because it is not just a mapping from keys to values, but is also slice-able, which in the Python typing world is an attribute of the `Sequence` type, and both `Mapping` and `Sequence` carry along obligations that it will be hard to make `MultiTrace` honor.

Let me take a step back and say what I was after in the type signature -- I would like to be able to distinguish which functions and methods in PyMC3 will accept *only* a `MultiTrace` and which will accept *either* a `MultiTrace` or the dictionaries returned by `sample_prior_predictive` and `sample_posterior_predictive`, because it would be helpful to have a typechecker tell you when you can and can't pass those things.
I can think of two ways to achieve this objective:
1. Define a type or protocol that defines what things like `traceplot` expect so that the programmer can know whether they will work with only a `MultiTrace` or also with a dictionary.
2. Add a supertype of `MultiTrace`, call it `AbstractTrace`, and modify the return values of the two predictive samplers so that they are subtypes of `AbstractTrace`, and then we can tell when they are and are not usable.
Does this make sense?

**Comment by rpgoldman** [comment]
Quick follow-up question -- would it make sense to implement `keys()` on `MultiTrace` to return an iterator over the varnames?

**Comment by rpgoldman** [comment]
See #3269 -- just a WIP, but it might be a step towards a solution.

**Comment by rpgoldman** [comment]
OBE because we are moving more towards InferenceData which better addresses uniform interfaces.
