### ISSUE TITLE
Zero probability in Categorical distribution

### ISSUE THREAD

**Issue by zplizzi** [pymc-devs/pymc#3272]
I am trying to switch between two categorical probability distributions based on another boolean variable. However, it doesn't seem to work, although it doesn't raise any errors. Here's code to reproduce:

```python
import pymc3 as pm
import numpy as np

basic_model = pm.Model()

with basic_model:
    a = pm.Bernoulli("a", .05)

    p1 = [0, 1 / 2, 1 / 2]
    p2 = [1, 0, 0]
    b = pm.Categorical("b", pm.math.switch(a, p1, p2), observed=[0])

    trace = pm.sample(2500)

print(np.mean(trace[a]))
```

Whether you set the observation to `0` or `1` or `2`, the estimate for the variable `a` is always 0. However, for observations of `1` or `2`, the value of `a` should be `1`. There's no way to observe a value of `1` or `2` if the distribution `p2` is selected by an `a`-value of 0.

If this usage is not supported, an error should be raised.

**Comment by junpenglao** [comment]
p cannot be 0 in Categorical, see in our doc: 
> p (array of floats) – p > 0 and the elements of p must sum to 1. They will be automatically rescaled otherwise

You can try setting it to a really small value instead of 0
```python
    p1 = [1e-50, 1 / 2-1e-50/2, 1 / 2-1e-50/2]
    p2 = [1-1e-50*2, 1e-50, 1e-50]
```

**Comment by zplizzi** [comment]
This is quite unintuitive - perhaps zeros should automatically be changed
to small positive values, or at least there could be a check and error
thrown?

**Comment by zplizzi** [comment]
That said, your suggestion did fix the issue at least in this simple example - much appreciated.

**Comment by junpenglao** [comment]
> This is quite unintuitive - perhaps zeros should automatically be changed
to small positive values, or at least there could be a check and error
thrown?

Agree - we should probably enforce it with a check like https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/continuous.py#L436-L437

**Comment by zplizzi** [comment]
One issue with the approach of "upgrading" zeros to small positives is in the following example. Suppose we modify the p's like so:

```python3
p1 = [0, 1, 0]
p2 = [1, 0, 0]
```

Ideally, if we observed a value of `2`, an error should be thrown indicating this is an impossible situation. If we "upgrade" the zeros to small positives, the model estimates `a` as `.5` - which is quite misleading, although accurate given the new specification. Is there a way to deal with this issue in a general way in pymc3?

**Comment by zplizzi** [comment]
Also just found a case where the small positive values don't seem to work properly, when I remove the observation entirely:

```python3
import pymc3 as pm
import numpy as np

basic_model = pm.Model()

with basic_model:
    a = pm.Bernoulli("a", .5)

    p1 = [1e-10, 1 - 2e-10, 1e-10]
    p2 = [1 - 2e-10, 1e-10, 1e-10]
    b = pm.Categorical("b", pm.math.switch(a, p1, p2))

    trace = pm.sample(2000)

print(np.mean(trace[a]))
print(np.mean(trace[b]))
```

This prints `0.0` for both `a` and `b` - seemingly never sampling a `1` value from `a`. 

It does work if I change the zero-ish values to `.1`, making me suspect this is caused by the small positive value hack.

**Comment by junpenglao** [comment]
Sample from the prior (i.e., when there is no observed) should be done using a forward sample scheme (`pm.sample_prior_predictive`), as the metropolis within gibbs that sample from free parameters is not very reliable in that case (especially when there are discrete unobserved RVs).

**Comment by zplizzi** [comment]
Thanks, that does work.

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/3386.
