### ISSUE TITLE
Bayes_factor.ipynb does not run

### ISSUE THREAD

**Issue by mshumko** [pymc-devs/pymc#3282]
Bayes_factor.ipynb does not successfully run because pm.model.marginal_likelihood attribute does not exist. I ran the entire notebook with no modification, and it crashed while attempting to execute the following code:

```
BF_smc = models[1].marginal_likelihood / models[0].marginal_likelihood
print(round(BF_smc))
```
The error I got was
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-eb4714e0aa53> in <module>
----> 1 BF_smc = models[1].marginal_likelihood / models[0].marginal_likelihood
      2 print(round(BF_smc))

AttributeError: 'Model' object has no attribute 'marginal_likelihood'
```
I am running this notebook on Mint Linux 64 bit, with python 3. PyMC3 version is 3.5 (same as the Bayes factor notebook) and I installed PyMC3 via pip.

**Comment by twiecki** [comment]
CC @aloctavodia

**Comment by aloctavodia** [comment]
Hi @mshumko, sorry for the inconvenience. I updated the example thinking on the next release. If you want to compute BF using SMC you need to install PyMC3 from master `pip install git+https://github.com/pymc-devs/pymc3` or wait for the 3.6 release (that should be available soon).

**Comment by mshumko** [comment]
Thanks for the clarification. I will try out the development version.
