### ISSUE TITLE
DLL load error on windows 10

### ISSUE THREAD

**Issue by Abraxas2071** [pymc-devs/pymc#3284]
```
D:\ProgramData\Miniconda3\python.exe “F:/PyCharm 2018.3/Global_Observer.py”
Traceback (most recent call last):
File “F:/PyCharm 2018.3/Global_Observer.py”, line 31, in 
**_start = pm.find_MAP()_**
File “D:\ProgramData\Miniconda3\lib\site-packages\pymc3\tuning\starting.py”, line 77, in find_MAP
dlogp_func = bij.mapf(model.fastdlogp_nojac(vars))
File “D:\ProgramData\Miniconda3\lib\site-packages\pymc3\model.py”, line 249, in fastdlogp_nojac
return self.model.fastfn(gradient(self.logp_nojact, vars))
File “D:\ProgramData\Miniconda3\lib\site-packages\pymc3\model.py”, line 939, in fastfn
f = self.makefn(outs, mode, *args, **kwargs)
File “D:\ProgramData\Miniconda3\lib\site-packages\pymc3\model.py”, line 909, in makefn
mode=mode, *args, **kwargs)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function.py”, line 317, in function
output_keys=output_keys)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\compile\pfunc.py”, line 486, in pfunc
output_keys=output_keys)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function_module.py”, line 1841, in orig_function
fn = m.create(defaults)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\compile\function_module.py”, line 1715, in create
input_storage=input_storage_lists, storage_map=storage_map)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\link.py”, line 699, in make_thunk
storage_map=storage_map)[:3]
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\vm.py”, line 1091, in make_all
impl=impl))
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\op.py”, line 955, in make_thunk
no_recycling)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\op.py”, line 858, in make_c_thunk
output_storage=node_output_storage)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cc.py”, line 1217, in make_thunk
keep_lock=keep_lock)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cc.py”, line 1157, in compile
keep_lock=keep_lock)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cc.py”, line 1620, in cthunk_factory
key=key, lnk=self, keep_lock=keep_lock)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cmodule.py”, line 1181, in module_from_key
module = lnk.compile_cmodule(location)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cc.py”, line 1523, in compile_cmodule
preargs=preargs)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cmodule.py”, line 2397, in compile_str
return dlimport(lib_filename)
File “D:\ProgramData\Miniconda3\lib\site-packages\theano\gof\cmodule.py”, line 309, in dlimport
rval = import(module_name, {}, {}, [module_name])
ImportError: DLL load failed: 找不到指定的模块（can’t find model）。
```
I using conda(miniconda)… I was crazy fast!!
Help me! ┭┮﹏┭┮

* PyMC3 Version:pymc3 3.5
* Theano Version:theano 1.03
* Python Version:3.7
* Operating system:win10
* How did you install PyMC3: (conda/pip)pycharm

**Comment by twiecki** [comment]
It seems your installation is still not right. The error message stumps me though. I think you might have muddled things with your various attempts to install using pip and conda. Try to uninstall every theano installation you can find and reinstall once using conda.

**Comment by Abraxas2071** [comment]
> It seems your installation is still not right. The error message stumps me though. I think you might have muddled things with your various attempts to install using pip and conda. Try to uninstall every theano installation you can find and reinstall once using conda.

@twiecki 
Our Dear Thomas. Thank you for your reply! (oﾟ▽ﾟ)o  
uninstall theano/pymc3...install theano/pymc3... I did it over and over again a few hours ago
It didn't work...

If I use "conda pymc3" , matplotlib/numpy/pandas and so on will be happen wrong...so I use Pycharm install pymc3

I use this link's method。Dear Thomas...Help me...I am very painful...~~o(>_<)o ~~
https://stackoverflow.com/questions/34508431/installing-theano-on-windows-dll-load-failed?tdsourcetag=s_pcqq_aiomsg
New WARNING happen
![1](https://user-images.githubusercontent.com/38712030/49432193-1619d600-f7ea-11e8-929c-61c7de95c988.jpg)
![2](https://user-images.githubusercontent.com/38712030/49432236-2df15a00-f7ea-11e8-8cef-bab0a1b7d6bc.jpg)

====================Some times happen=======================
![3](https://user-images.githubusercontent.com/38712030/49432819-7f4e1900-f7eb-11e8-9a16-0165e3de6d42.jpg)

**Comment by Abraxas2071** [comment]
@twiecki 

When I uninstall "mingw-w64-install"/"tdm64-gcc-5.1.0-2", the code is working
Just WARNING "no g++"/"no c++"
What is your idea??

Help meφ(>ω<*) Our Dear Thomas....

**Comment by junpenglao** [comment]
Discussion is currently in https://discourse.pymc.io/t/dll-load-error-on-windows-10/2312/. Close here for now.
