### ISSUE TITLE
Runtime Performance Markedly Different between two Macs

### ISSUE THREAD

**Issue by EPGM-DES** [pymc-devs/pymc#3298]
## Description of your problem

I am running the same model on two different Macs (Late 2014 iMac, Intel i5 3.5GHz and 2017 MB Pro Intel i5 2.3 GHz). Why would the iMac be sampling at an order of magnitude slower or more? Has anyone noticed similar issues?

## Versions and main components
Same for both machines.
* PyMC3 Version: 3.5
* Theano Version: 1.0.3
* Python Version: 3.7.1
* Operating system: Mac OS Mojave 10.14.1
* How did you install PyMC3: conda

**Comment by twiecki** [comment]
Sure they both have MKL installed?

**Comment by EPGM-DES** [comment]
Yes, both machines are running mkl version 2018.0.3

**Comment by twiecki** [comment]
How different are the speeds? Those machines are quite different in specs so I would definitely expect this.

**Comment by twiecki** [comment]
Closing as I don't  yet think this is a pymc3 problem, feel free to keep asking questions.
