### ISSUE TITLE
Fix for conda installation breaking the environment

### ISSUE THREAD

**Issue by Nathan-Furnal** [pymc-devs/pymc#3336]
Hello everyone,

Recently, I submitted [this issue](https://github.com/pymc-devs/pymc3/issues/3305#event-2057568055) that basically shows that installing on conda [breaks the environment](https://stackoverflow.com/questions/53635462/anaconda-prompt-closes-immediately-the-system-was-unable-to-find-the-specified).

Yet this didn't happen with pip and it left me wondering why for quite a bit.

I think that I have found the reason now and it might probably be because of the compiler, at least on **Windows** but it might prove to be a problem for OSX users too but I can't seem to find why.

I think that I found a fix though, it comes from [Pystan documentation for Windows](https://pystan.readthedocs.io/en/latest/windows.html).

Installing the mingW-w64 compiler proved to fix my problem with the conda install : 

`conda install libpython m2w64-toolchain -c msys2`

I now have a conda env under Python 3.6 where Pystan and PyMC3 coexist and it doesn't cause any errors as far as I'm aware.

Thought I'd say it for others who might have the same problem.

**Comment by fonnesbeck** [comment]
Thanks. 

Ref #3305

**Comment by Nathan-Furnal** [comment]
After some more exploration, the offending package seems to be `vs2015_win-64`. It's probably better to use another compiler in the default conda-forge package to avoid that issue.
