### ISSUE TITLE
Expectations - PyMC4 (Google Summer of Code '19)

### ISSUE THREAD

**Issue by vsomnath** [pymc-devs/pymc#3339]
Hi, 
I came across the PyMC4 project idea for GSCO 2019, using Tensorflow Probability support. 
I am interested in working on the project, and would like to know what are the main expectations / deliverables of the project.

Thanks & Regards,
Vignesh

**Comment by fonnesbeck** [comment]
Not PyMC3 issue. Closing.

Please use our discourse site (discourse.pymc.io) for general questions.
