### ISSUE TITLE
Jupiter NoteBook Error while working in DarkFlow

### ISSUE THREAD

**Issue by nerds-coding** [pymc-devs/pymc#3347]
I'm working on Darknet for object detection 
when I do

from darkflow.net.build import TFNet
import matplotlib.pyplot as plt
import cv2

 options={
    'model':'cfg/yolo.cfg',
    'load':'bin/yolo.weights',
    'thresold':0.3,
    'gpu':1.0
}
tfNet=TFNet(options)

it gives me this following error

AssertionError                            Traceback (most recent call last)
<ipython-input-7-d2139f71417c> in <module>
      6 }
      7 
----> 8 tfNet=TFNet(options)

/anaconda3/lib/python3.6/site-packages/darkflow/net/build.py in __init__(self, FLAGS, darknet)
     56 
     57                 if darknet is None:
---> 58                         darknet = Darknet(FLAGS)
     59                         self.ntrain = len(darknet.layers)
     60 

/anaconda3/lib/python3.6/site-packages/darkflow/dark/darknet.py in __init__(self, FLAGS)
     11 
     12     def __init__(self, FLAGS):
---> 13         self.get_weight_src(FLAGS)
     14         self.modify = False
     15 

/anaconda3/lib/python3.6/site-packages/darkflow/dark/darknet.py in get_weight_src(self, FLAGS)
     45         else:
     46             assert os.path.isfile(FLAGS.load), \
---> 47             '{} not found'.format(FLAGS.load)
     48             self.src_bin = FLAGS.load
     49             name = loader.model_name(FLAGS.load)

AssertionError: bin/yolo.weights not found

I'm working on Mac Operative System

**Comment by lucianopaz** [comment]
Could you post a brief description of what you were attempting to do, and include a code example of what produced your error? From the traceback alone it's impossible to know what you were doing. Furthermore, the error does not seem to involve pymc3 at all. It says that `darknet` failed to load weights from `bin/yolo.weights`. `pymc3` is not even mentioned in the traceback.
