### ISSUE TITLE
Move SFGS, CSG and Elliptical Slice samplers to pymc3-experiments

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3353]
These three samplers are not well supported and do not appear to really be used. They are mostly experimental and should be in the main software. Thus, they should be moved to https://github.com/pymc-devs/pymc3-experimental alongside any tests and docs (tests and docs do not need to compile/function). If someone picks them up and demonstrates their usefulness they can certainly make their way back, but they have lied dormant for too long.

**Comment by Akamoha** [comment]
So this would mean removing all the work done in pymc-devs#2544?

**Comment by twiecki** [comment]
@Akamoha Yes, alongside the SFGS.

**Comment by eigenfoo** [comment]
#3233 and #3357 are both problems to do with the CSG sampler. Is the plan to simply remove CSG altogether? If so, then perhaps we should close those issues.

**Comment by junpenglao** [comment]
Could we move to a new repo maybe? (pymc-devs/experiment?) Along with Elliptical Slice Sampling.

**Comment by twiecki** [comment]
@junpenglao I like that.

**Comment by twiecki** [comment]
I created https://github.com/pymc-devs/pymc3-experimental.

**Comment by junpenglao** [comment]
Awesome ;-)

**Comment by junpenglao** [comment]
I can finally dump all my codes on Laplace approximation etc there :-|||||

**Comment by twiecki** [comment]
@Akamoha Do you want to take this one on?

**Comment by harshitbansal05** [comment]
hey, @twiecki can I work on this one?

**Comment by twiecki** [comment]
Yes! thank you for volunteering.

**Comment by fonnesbeck** [comment]
ESS should not be experimental, and is useful for GPs. [One of the demo notebooks uses it](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-slice-sampling.ipynb).

**Comment by ferrine** [comment]
I remember @ColCarroll was working on this https://github.com/ColCarroll/l2hmc_pymc3
Its worth potring as well

**Comment by junpenglao** [comment]
@fonnesbeck In that case maybe we should have some more example of using ESS - eg how it is used with other Samplers

**Comment by ColCarroll** [comment]
@ferrine just added a license so it can be copied/moved with or without my permission (whoever wants to move it has my permission, but prominent acknowledgments to the authors should stay close to the code!) I can also move it... soon.

**Comment by vbsinha** [comment]
Hi @twiecki, Can I work on this issue?
From the previous comments, it is not clear to me if I should move Elliptical Slice as well. Could you please clarify that? I did a quick grep for EllipticalSlice and found that only [one notebook](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/GP-slice-sampling.ipynb) uses it in the entire repo. It is nowhere else mentioned apart from its [definition](https://github.com/pymc-devs/pymc3/blob/c496378db707f402c89add9b00ea70015ecab50c/pymc3/step_methods/elliptical_slice.py) and [tests](https://github.com/pymc-devs/pymc3/blob/c496378db707f402c89add9b00ea70015ecab50c/pymc3/tests/test_step.py).
Moreover, should I simply move the classes SFGS, CSG and Elliptical Slice to pymc3-experimental? I mean that standalone classes in the experimental repo won't make much sense. So do I move all the other python files involved with these samplers to pymc3-experimental repo?

**Comment by twiecki** [comment]
@vbsinha Definitely. You can leave Elliptical Slice here.

To the extend that whole files can be moved that's what I'd do. Ideally we can still retain the functionality in that repo, it should just require redirecting imports to pymc3 instead of relative imports.

**Comment by vbsinha** [comment]
@twiecki It seems that these notebooks ([this](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/bayesian_neural_network_with_sgfs.ipynb) and [this](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/sgfs_simple_optimization.ipynb)) are using SGFS while this [one](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/constant_stochastic_gradient.ipynb) is using CSG. Could you please suggest how should I proceed? Should we move these notebooks to pymc3-experimental repo as well or leave SGFS and CSG intact in this repo?

**Comment by twiecki** [comment]
The NBs should be ported too. Basically the idea is that there is no mention of SGFS or CSG in pymc3, but if someone wants to try them, they can install pymc3-experimental.

**Comment by junpenglao** [comment]
Would there be a way to index the doc on the website still? Maybe under a tab call Experimental?
Basically, it would show how to install the experimental feature, which NB example of how to use some of them.

**Comment by canyon289** [comment]
@junpenglao 
I think(?) all you need to do is add an "Experimental api" header to the api.rst file and then add the relevant modules below

https://github.com/pymc-devs/pymc3/blob/master/docs/source/api.rst

**Comment by twiecki** [comment]
Closed by #3391.
