### ISSUE TITLE
xlim of traceplot does not cover all range of values

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3359]
## Description of your problem

xlim of traceplot may not cover all range of traces for discrete variables. For example, if I get two chains: one with mean 28, another one with mean 32. Then the traceplot will show only one bar at x=28 and xlim from 27.5 to 28.5.

I am not sure I need to attach a reproducible example here, but if necessary I may check the disasters problem with two changepoints and try to reproduce my problem there.

![arcolinux_2019-01-27_16-01-25](https://user-images.githubusercontent.com/2173206/51797762-f7b1e300-224c-11e9-8679-44fa1c58d1db.png)

For discrete values I used DiscreteUniform:
```python
timestep=1.5
with pm.Model() as model_two_switches_11:
    delaymean = pm.Uniform('delaymean',1,28,shape=3)
    k = pm.Uniform('k',0.8,8,shape=3)
    
    switch1 = pm.DiscreteUniform('switch1',df['T'].min()//7,df['T'].max()//7-timestep-1)
    switch2 = pm.DiscreteUniform('switch2',switch1+timestep+1,df['T'].max()//7)
    
    idx = tt.switch(df['t'].values>=(switch1*7),0,1)+tt.switch(df['t'].values>=(switch2*7),0,1)
    
    θ = delaymean/tt.gamma(1+1/k)
    delaysd = pm.Deterministic('delaysd',delaymean/tt.gamma(1+1/k)*tt.sqrt(tt.gamma(1+2/k)-tt.gamma(1+1/k)**2))
    
    delay_p = (1-tt.exp(-(df['δt0'].values/θ[idx])**k[idx]))/(1-tt.exp(-(df['δt'].values/θ[idx])**k[idx]))
    
    confirmed = pm.Poisson('confirmed',\
                    mu=df['confirmed'].values*delay_p+0.001,\
                    observed=df['confirmed0'].values)
    
    start = {'switch1': 22, 'switch2': 28}
    step = pm.Slice([switch1,switch2])
    trace_two_switches_11 = pm.sample(number_of_iterations, tune=length_of_tunein, cores = number_of_jobs,
                                      start=start, step=step)

model_two_switches_11.name = 'Two switches_11'

vrnames = ['switch1','switch2','delaymean','delaysd']
pm.traceplot(trace_two_switches_11,varnames=vrnames);
pm.summary(trace_two_switches_11)
```

ps: I assume that it's because the fraction of those points outside of chosen xlim-range is rather small, but it would be nice to see the consistent picture between left and right panels

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.3
* Python Version: 3.7.1
* Operating system: linux
* How did you install PyMC3: (conda/pip) latest version from github

**Comment by twiecki** [comment]
Can you move this to the arviz issue tracker? That's where this code lives now and the plotting code here will be deprecated soon.

**Comment by aakhmetz** [comment]
hai, I will do it. Arigatou!
