### ISSUE TITLE
(enhancement) implement list for starting points for pm.sample

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3360]
I think it would nice to allow the parameter *start* in *pm.sample* to vary in similar manner as another parameter *random.seed*.

## Description of your problem

The code
```python
with model_kawaii_on_TV:
    start = [{'kawaii_broadcasting_rate': starting_point} for starting_point in starting_points]
    trace = pm.sample(1000, cores = ncores, start=start, random_seed=[1 for _ in range(ncores)])
```
gives the same output because *start* is not iterated. But it would be nice (and a bit helpful) to allow iteration in start parameter as well. At present, this has been made possible for *random_seed* parameter.

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.3
* Python Version: 3.7.1
* Operating system: linux
* How did you install PyMC3: (conda/pip) latest version from github

**Comment by twiecki** [comment]
To initialize individual chains separately?

**Comment by aakhmetz** [comment]
yes - it can helpful when there are multiple equilibrium points, and then it is good to investigate the whole range of possible parameter values. It's similar to one [approach](https://kingaa.github.io/sbied/mif/mif.html) recommended for POMP in R. 

At least it has been done for random seed, so it could be done the same way for starting point.

**Comment by twiecki** [comment]
That's a reasonable request, want to give it a go and do a PR?

**Comment by aakhmetz** [comment]
@twiecki Hai - sorry, after several days thinking I have decided that such enhancement is not really something important, and after reading some more manual on stan/nuts, I concluded that it may contradict to its philosophy (like choosing a starting point close to the equilibrium may not be in the typical set). So I think it's better to put the resolution of my current issue a bit aside

**Comment by aakhmetz** [comment]
@twiecki Sorry, but is there any way to retrieve the number of a chain while running pymc3-model? I am asking because once I can identify it, I can assing the chain number to some model parameter, for example, the starting point or a changepoint in my process

**Comment by eigenfoo** [comment]
Hi @aakhmetz: we'd prefer if you directed any questions about using PyMC3 to our discourse forums. The issue tracker is solely for discussing development to PyMC3.

**Comment by aakhmetz** [comment]
Hi @eigenfoo, sounds good - thanks!
