### ISSUE TITLE
Inconsistency in displaying warning messages while using ipython magic *%%capture --no-display*

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3371]
## Description of your problem

The use of ```%%capture --no-display``` in particular cell causes disruption in warning display between other cells of the notebook.

**Please provide the full traceback.**
Please see [the gist](https://gist.github.com/aakhmetz/cdf01b8209e6a646216f485e49f686b3)

**Please provide any additional information below.**
I would be actually nicer to have control over the warnings. For example, if I run pm.sample in a for loop, sometimes I wish to have a more compact output from pymc3 w/o many warnings. I could not find this option in the manual.

## Versions and main components

* PyMC3 Version: 3.6 (github version from 20190208)
* Theano Version: 1.0.3
* Python Version: 3.7.1
* Operating system: archlinux
* How did you install PyMC3: pip with the latest version from github

**Comment by lucianopaz** [comment]
I don't know enough about ipython's magic but I'm not sure if this is actually a pymc3 issue. It looks more like ipython's redirection of stderr and stdout is not well encapsulated into a single cell. Maybe you could raise a separate issue with them, referencing this issue.

**Comment by aakhmetz** [comment]
I see - thanks!
