### ISSUE TITLE
Documentation does not specify the difference b/w logpt and logp_nojac

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3372]
## Description of your problem

[Documentation](https://docs.pymc.io/api/model.html) gives the same description for **logpt** and **logp_nojac**. Are they the same?

**Comment by junpenglao** [comment]
They are not, thanks for reporting.
For models with constrained free parameters, pymc3 transformed the parameter to $R$. This transformation need to account for the Jacobian. logp_nojac is the version that _without_ the jacobian, which is only used internally for MAP optimization.

**Comment by KrUciFieR-Jr** [comment]
Hey, I would like to work on this. How do you want me to proceed?

**Comment by junpenglao** [comment]
Please go ahead! You can edit the docstring and send a pull request.

**Comment by divyanshu132** [comment]
@junpenglao should I replace it with `logp_nojact: Theano scalar of log-probability of the model without the jacobian` and `logpt: Theano scalar of log-probability of the model with the jacobian`

**Comment by junpenglao** [comment]
Maybe:
```
logp_nojact: 
    Theano scalar of log-probability of the model but without the jacobian 
    if transformed Random Variable is presented.
logpt: 
    Theano scalar of log-probability of the model
```
