### ISSUE TITLE
Sampling with Text backend automatically converts to NDArray

### ISSUE THREAD

**Issue by skatenerd** [pymc-devs/pymc#3385]
## Description of your problem

I'm attempting to pass a Text backend into `sample`.  I want to prevent lots of data from being written to memory, so I'm writing to the filesystem instead.  I would hope that there are never any NDArrays being used to hold the bulk of my data, but it seems like such NDArrays are being created, and it's out of the end-user's control.

I could be mistaken, but I think this is a problem because this means we're loading all (or most) of the sampling data into memory, which defeats the purpose of using a Text backend to begin with.

I can attempt to put together a self-contained example, but for now, I have a stack trace which describes the path to the creation of the NDArray

**Please provide the full traceback.**
```python
  /usr/local/lib/python3.6/dist-packages/pymc3/sampling.py(472)sample()
    471         discard = tune if discard_tuned_samples else 0
--> 472         trace = trace[discard:]
    473 

  /usr/local/lib/python3.6/dist-packages/pymc3/backends/base.py(292)__getitem__()
    291         if isinstance(idx, slice):
--> 292             return self._slice(idx)
    293 

  /usr/local/lib/python3.6/dist-packages/pymc3/backends/base.py(496)_slice()
    495         """Return a new MultiTrace object sliced according to `slice`."""
--> 496         new_traces = [trace._slice(slice) for trace in self._straces.values()]
    497         trace = MultiTrace(new_traces)

  /usr/local/lib/python3.6/dist-packages/pymc3/backends/base.py(496)<listcomp>()
    495         """Return a new MultiTrace object sliced according to `slice`."""
--> 496         new_traces = [trace._slice(slice) for trace in self._straces.values()]
    497         trace = MultiTrace(new_traces)

  /usr/local/lib/python3.6/dist-packages/pymc3/backends/text.py(144)_slice()
    143             raise ValueError('Stop value in slice not supported.')
--> 144         return ndarray._slice_as_ndarray(self, idx)
    145 

  /usr/local/lib/python3.6/dist-packages/pymc3/backends/ndarray.py(316)_slice_as_ndarray()
    315 def _slice_as_ndarray(strace, idx):
--> 316     sliced = NDArray(model=strace.model, vars=strace.vars)
    317     sliced.chain = strace.chain

> /usr/local/lib/python3.6/dist-packages/pymc3/backends/ndarray.py(161)__init__()
    160         import ipdb; ipdb.set_trace()
--> 161         super(NDArray, self).__init__(name, model, vars, test_point)
    162         self.draw_idx = 0
```

## Versions and main components

* PyMC3 Version: 3.5
* Theano Version: 1.0.3
* Python Version: 3.6
* Operating system: Ubuntu
* How did you install PyMC3: piip

**Comment by fonnesbeck** [comment]
Can you post a reproducible example to help us debug this?

**Comment by twiecki** [comment]
And why are you using the text backend?

**Comment by fonnesbeck** [comment]
No response; closing.

**Comment by skatenerd** [comment]
Hi, sorry.  I haven't had time to put together an example to replicate the failure.  I personally have a workaround for now (just buying more RAM and not using the file backend).  I think it's fine to close this ticket.  Hopefully if someone encounters this issue in the future, they can at least see that they're not the only one etc.
