### ISSUE TITLE
Categorical FreeRV can fail because of testval choice.

### ISSUE THREAD

**Issue by helmutsimon** [pymc-devs/pymc#3392]
The model below uses a categorical distribution as a prior. It does not converge correctly (in this case MCMC should have mode around 3) if testval=0 or 10 or default. If testval is set to a non-edge value of the support the sample converges correctly (e.g. change testval to 2, 9 etc).

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
from pymc3 import *
from pymc3.distributions.discrete import Poisson, Categorical
import theano
import theano.tensor as tt
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt


def run_true_MCMC(n, obs, draws):
    obs = np.array(obs)
    with Model() as model: 
        
        pn = np.ones(n) / n
        x = Categorical('x', pn, testval=0)
        sfs_obs = Poisson('sfs_obs', mu=x, observed=obs) 

    with model:
        trace = sample(draws, tune=0) 
    plt.show(forestplot(trace, varnames=['x']))
    traceplot(trace, varnames=['x'])
    print(summary(trace, varnames=['x']))
    return trace

obs = 3
draws = 10000
n = 10
trace = run_true_MCMC(n, obs, draws)
```

**Please provide the full traceback.**
```python
Multiprocess sampling (2 chains in 2 jobs)
CategoricalGibbsMetropolis: [x]
Sampling 2 chains: 100%|██████████| 20000/20000 [00:04<00:00, 4131.15draws/s]
/Users/helmutsimon/miniconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py:2961: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=0.0, right=0.0
  'left=%s, right=%s') % (left, right))

   mean   sd  mc_error  hpd_2.5  hpd_97.5  n_eff  Rhat
x   0.0  0.0       0.0      0.0       0.0    NaN   NaN
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.0
* Python: 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 12:43:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by ricardoV94** [comment]
I don't think this is really a defect, but a model misspecification.

1. The `Categorical` allows for 0 values, which lead to a -inf probability in the `Poisson` likelihood (given the observed value of 3).
2. Since all the initial probabilities are equal, the mode is arbitrarily set to `0` (used for the default `testval`).
3. A `testval` of 10 is also invalid (0 based index)

A correct model would have been:
```python
with pm.Model() as m:
    x = pm.Categorical('x', p=np.array([0, 1, 1, ..., 1])
    y = pm.Poisson('y', mu=x, observed=np.array(3))
```

**Comment by MarcoGorelli** [comment]
Closing then as this doesn't look like a defect, but please do ping if this assessment is incorrect (and thanks @ricardoV94 for triaging!)
