### ISSUE TITLE
Rerun NBs now that plotting backend is switched

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3393]
After merging https://github.com/pymc-devs/pymc3/pull/3338 we should rerun the NBs.

@ColCarroll did you have a script for this?

**Comment by ColCarroll** [comment]
It is on PyPI! 

https://github.com/ColCarroll/carpo

Give me a day to make sure it is up-to-date with all the changes jupyter's made in the last year, though.

**Comment by ColCarroll** [comment]
Also want to make clear that making a PR with 1 or more notebooks rerun with pymc3 master is a valuable contribution -- a few of the notebooks take ~1 hr to run on my laptop.

**Comment by twiecki** [comment]
> Also want to make clear that making a PR with 1 or more notebooks rerun with pymc3 master is a valuable contribution -- a few of the notebooks take ~1 hr to run on my laptop.

Do you mean you'd like help? Maybe in that case we should divide them up somehow.

**Comment by canyon289** [comment]
I can run these all on my desktop when I get back home in a couple days if
you guys would like.

**Comment by Dpananos** [comment]
I've got a machine at home that I don't use often.  I can run then all when I get back Monday.

**Comment by lucianopaz** [comment]
Thanks @Dpananos, but this was mostly done in #3397. The only notebook that was left out was the GP_manua_loa2, which @canyon289 was going to try and do.

**Comment by Ahanmr** [comment]
Hi, Is there anything still left in this issue? #3397  mostly re-runs all the notebooks, please let me know if there's anything else to work on. I believe GP_manua_loa2 was also re-run, since it's mentioned as completed in the PR, Thanks!

**Comment by twiecki** [comment]
Thanks for all your contributions so far @Ahanmr and being on top of the tracker!

**Comment by Ahanmr** [comment]
@twiecki  Thanks a lot for the opportunity to contribute!
