### ISSUE TITLE
Inconsistent argument ordering for NormalMixture (version 3.6) 

### ISSUE THREAD

**Issue by fredcallaway** [pymc-devs/pymc#3400]
I installed from the master repo.  Here is `__init__` signature for `NormalMixture`:
`def __init__(self, w, mu, comp_shape=(), *args, **kwargs)`

In a previous version, I was able to use `NormalMixture('name', w, mu, sigma)` but now this breaks. I think it would be more consistent with the rest of the library (and the order in which parameters are [documented](https://docs.pymc.io/api/distributions/mixture.html#pymc3.distributions.mixture.NormalMixture)) if `sigma` was given as an explicit keyword argument, after `mu`.

**Comment by lucianopaz** [comment]
Thanks @fredcallaway. I agree that it looks better to add `sigma` and `tau` before `comp_shape`. I think that we cannot change this in an instant. We should keep backwards compatibility in mind for users that may have relied on positional arguments for `comp_shape`. Maybe raise a future warning in 3.7 and at a later version, change the function signature.

**Comment by twiecki** [comment]
Hm, yeah, that's an unfortunate string of events that lead to this. I agree that `sigma` should be in the signature just like everywhere else. I think it's actually fine to change this directly as I think it's fair to call this a bug.

**Comment by fredcallaway** [comment]
Note also that from my perspective (I unfortunately forget what version I had previously), putting sigma in the signature would *restore* backwards compatibility. I noticed the discrepancy because I was previously assuming sigma as a positional argument and got an exception after updating to master.

**Comment by twiecki** [comment]
Want to do a PR?

**Comment by fredcallaway** [comment]
Sure!

**Comment by lucianopaz** [comment]
Closed by #3405
