### ISSUE TITLE
pm.compareplot fails as it is looking for lower case column name

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#3401]
Should be easy to fix, but maybe it is better to fix it in arviz.

**Comment by canyon289** [comment]
Is this now an ArviZ issue because we forward the api?

**Comment by junpenglao** [comment]
Yes, I am sending a quick fix.

**Comment by canyon289** [comment]
For pymc3 users this will remain broken until another ArviZ release on pypi. Is that ok or alternative solutions needed?
