### ISSUE TITLE
PyMC3 doesn't show any progress

### ISSUE THREAD

**Issue by aliolion** [pymc-devs/pymc#3407]
Hi, 
I've tried to run the following code:
```
import numpy as np
import pandas as pd
import scipy.stats as ss
import scipy.special as sp
import pymc3 as pm


model = pm.Model()
hd_fnmr = pd.DataFrame(pd.read_csv("process.txt", delim_whitespace=True)
n_shape = len(hd_fnmr.data_name.values)

with model:

   mubar = pm.Normal('mubar', mu = 0.25, sd = 0.1)
    sigbar = pm.Normal('sigbar', mu = 0.1, sd = 0.05)
 
    # Prior distribution for mu and sigma:
    mu = pm.Normal('mu_prior', mu = mubar, sd=0.1, shape = n_shape)
    sigma = pm.Gamma('sigma_prior', alpha=2.0, beta=0.5, shape = n_shape)
   
    # Likelihood function for data: Gaussian
    observations = [pm.Normal('obs_{}'.format(i+1), mu = mu[i], sd = sigma[i],
                              observed = hd_fnmr[hd_fnmr.data_name.values==i+1].Hamming_distance.values)
                    for i in range(n_shape)]

    trace = pm.sample(3000, tune=2000, njobs=1)

pm.traceplot(trace)
#pm.summary(trace)
pm.plot_posterior(trace)
#pm.autocorrplot(trace)
#pm.energyplot(trace)
pm.densityplot(trace)
```
 the previous runs with the same code it seems to work well. But at some point it suddenly stop working. PyMC3 doesn't even show any progress. For example, it doesn't try to show up the line: 

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...

to just notify me that it is working. I've waited for 10-15 min but nothing show up, then I eventually gave up.

I've tried many attempts: clear my computer cache, clear theano cache... However nothing work

I've tried with another code that from internet: https://docs.pymc.io/notebooks/rugby_analytics.html
and it seems to work fine.

I think it has something relate to theano-cache writing? Any suggestion?

Best Regards

* PyMC3 Version: 3.6
* Theano Version: 1.0.4
* Python Version: 3.5.2
* Operating system: Debian
* How did you install PyMC3: (conda/pip) pip

**Comment by fonnesbeck** [comment]
Can you share the input data, or part of it so that we can reproduce the problem? Is the data very large? You can also try running without any init (`init=None`) and see if the model is hanging up in initialization.

**Comment by aliolion** [comment]
Hi,
Here's the data. It is more than 8 mil of entries. I'll try with your suggestion first. Thanks
[process_FNMR.txt](https://github.com/pymc-devs/pymc3/files/2964351/process_FNMR.txt)

**Comment by fonnesbeck** [comment]
Ok, that's almost certainly the issue. MCMC does not scale well with large datasets. Just to verify, try running it on a few thousand rows and see if it works. 

For large data you should look at PyMC's variational inference methods.

**Comment by aliolion** [comment]
Hi,
In the mean time I also made a test with a much smaller amount of data from it. And it seems to work with no such issue. 

Thanks for your suggestion. I'll try with it

**Comment by aliolion** [comment]
Hi,
In the mean time I also made a test with a much smaller amount of data from it. And it seems to work with no such issue. 

Thanks for your suggestion. I'll try with it

**Comment by rpgoldman** [comment]
I think this issue has been resolved by @fonnesbeck 's suggestion.  Closing.
