### ISSUE TITLE
sample_prior_predictive fails with GaussianRandomWalk

### ISSUE THREAD

**Issue by sempwn** [pymc-devs/pymc#3409]
Cannot sample the prior predictive distribution using a Gaussian random walk. 

## minimal code

```python
import pymc3 as pm
from pymc3.distributions.timeseries import GaussianRandomWalk

with pm.Model():
    rw = GaussianRandomWalk("random_walk",mu=0, tau=10, shape=(10,)) 
    prior_trace = pm.sample_prior_predictive(samples=1000)
```

```python
File "//anaconda/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py", line 1325, in sample_prior_predictive
    values = draw_values([model[name] for name in names], size=samples)

File "//anaconda/envs/py36/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 388, in draw_values
    raise ValueError('Cannot resolve inputs for {}'.format([str(params[j]) for j in to_eval]))

ValueError: Cannot resolve inputs for ['random_walk']
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.3
* Python Version: 3.6
* Operating system: osx 10.14.3 
* How did you install PyMC3: conda

**Comment by lucianopaz** [comment]
The error is a bit obscure but what is actually happening is that no time series distribution has a `random` method implemented. What this means is that you can't sample from the prior, nor can you sample from the posterior predictive, if the time series is an observed RV. I started to work on adding `random` to them but haven't finished yet. The only distributions I haven't done yet are `MvGaussianRandomWalk` and `MvStudentTRandomWalk`, but I'm short on time and haven't been able to work on them.
