### ISSUE TITLE
Feature Request: Include variable bounds in MAP

### ISSUE THREAD

**Issue by aflaxman** [pymc-devs/pymc#341]
As identified in the Gamma(1,1) model (Issue #334), it can sometimes be very helpful to include bounds when optimizing.  Ideally, this would happen automatically.

Here is an example of how it can be done manually for a simple model:

```
with mc.Model() as m: tau = mc.Gamma('tau', alpha=.1, beta=.1)

bij = mc.DictToArrayBijection(mc.ArrayOrdering(m.vars), theta)

lower = dict(tau=.01)
lower = bij.map(lower)

upper = dict(tau=inf)
upper = bij.map(upper)

bounds = zip(lower, upper)

with m: mc.find_MAP(fmin=scipy.optimize.fmin_l_bfgs_b, bounds=bounds)
```

**Comment by twiecki** [comment]
`pylearn2` has constrained optimization (and uses Theano): http://blog.safaribooksonline.com/2014/02/13/constrained-optimization-pylearn2/

They also have optimization that gets around inverting the hessian:
https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/optimization/linear_cg.py

**Comment by jsalvatier** [comment]
Wouldn't be too difficult to automatically pull bounds based on the constraints of the prior. I think based on the likelihood might be a little tougher. 

For the prior, all we need to do is just add `upper_bound` and `lower_bound` properties on the distributions and then extract those if they're constant.

**Comment by jsalvatier** [comment]
I think this is mostly not necessary anymore since bounded variables are now automatically made unbounded. Anything I'm missing?

**Comment by aflaxman** [comment]
I have not kept up with all the recent development, but I think this could still be useful.  Does the example I posted above work for you still?  I'm having some trouble with it.  Does the following work for you now?

```
with mc.Model() as m: tau = mc.Gamma('tau', alpha=.1, beta=.1)
with m: mc.find_MAP()
```

I think my install needs a little love, I'm getting the following error

```
===============================
In file included from /usr/include/limits.h:25:0,
                 from /homes/abie/anaconda/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include-fixed/limits.h:168,
                 from /homes/abie/anaconda/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include-fixed/syslimits.h:7,
                 from /homes/abie/anaconda/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include-fixed/limits.h:34,
                 from /homes/abie/anaconda/include/python2.7/Python.h:19,
                 from /snfs2/HOME/abie/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.10-64/tmph5VPHQ/mod.cpp:1:
/homes/abie/anaconda/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/include-fixed/features.h:338:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.

```

**Comment by jsalvatier** [comment]
Yeah, the following worked for me. What is the main use case for this? I would expect that transforming constrained spaces into unconstrained spaces would get rid of most of the need for automatic bounds computing. 

I can still see it might be useful to manually add bounds sometimes. And we could probably give it a nicer format, where you pass in  "upper" and "lower" points and the bounds object is computed automatically.

```
import pymc3 as mc
import numpy as np 
import scipy 

with mc.Model() as m: 
    tau = mc.Gamma('tau', alpha=.1, beta=.1, transform=None)

    bij = mc.DictToArrayBijection(mc.ArrayOrdering(m.vars), m.test_point)

    lower = mc.Point(tau=.001)
    lower = bij.map(lower)

    upper = mc.Point(tau=np.inf)
    upper = bij.map(upper)

    bounds = zip(lower, upper)

    start = mc.find_MAP(fmin=scipy.optimize.fmin_l_bfgs_b, bounds=bounds)
```

**Comment by jsalvatier** [comment]
I've never seen an error like that before. Looks like maybe some kind of library that Theano is trying to pull in but failing?

**Comment by twiecki** [comment]
@aflaxman are you on the most recent `theano`?

**Comment by aflaxman** [comment]
I have a conda testenv that it works in.  There must be some old Theano gunk hanging around in my main environment...

When I use the working environment, both code blocks work, but they return different start values.  How can I have a truncated Gamma distribution? Does this should work:

```
with mc.Model() as m: tau = mc.Gamma('tau', alpha=.1, beta=.1, transform=mc.transforms.interval_transform(.001,np.inf))

with m: s2 = mc.find_MAP()
```

**Comment by twiecki** [comment]
That should work I think.

`stan` also supports truncation (via the same mechanism) with something like this syntax:
`tau ~ Gamma(.1, .1)[.1, inf]`

Maybe truncation could be implemented with some syntactic sugar in pymc3. In stan, the transformation is chosen automatically. Maybe something like 
`tau = mc.Gamma('tau', alpha=.1, beta=.1, lower=0.1)`
`lower` would be shared with `Uniform` but it actually has the same meaning.

**Comment by fonnesbeck** [comment]
It always pays to delete your `~/.theano` from time to time.

**Comment by fonnesbeck** [comment]
How about via a method:

```
tau = mc.Gamma('tau', alpha=.1, beta=.1).truncate(lower=0.1)
```

**Comment by aflaxman** [comment]
The use case behind this issue is coming back to me now... I should have written more detail into the original post.

For truncated Gamma, I like @fonnesbeck 's syntax more than `Stan`'s or @twiecki 's, since it makes things explicit.  But I think my favorite would be to simply have an additional continuous distribution called `TruncatedGamma`, since that seems _most_ explicit.

However, this issue was motivated by the situation where I want an honest Gamma as my prior, and I want to start MCMC from a good initial value, but the log-likelihood of the MAP is infinite.  Therefore, I still think it would be a useful feature for me.  

Based on this, I think it should _not_ create bounds automatically, since they are a subjective choice by the modeler (really the computation time optimization engineer, if you have one).  Also, I think I understand the code well enough to take on implementing this feature, which I think should take the form

```
mc.find_MAP(fmin=scipy.optimize.fmin_l_bfgs_b, bounds={'tau':{'lower':.001}})
```

**Comment by twiecki** [comment]
So you actually don't want to transform the Gamma, but only get around the optimization problem?

Irrespective, truncation is something that we can support very easily now.

**Comment by aflaxman** [comment]
Yes, this issue is about optimization in models with infinite posterior density at the MAP.  Sorry for the confusion.

**Comment by twiecki** [comment]
Well, still a useful discussion.

Couldn't you use a constrained optimizer? http://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#bounded-minimization-method-bounded

**Comment by jsalvatier** [comment]
So I think the transformation of variables at least mostly fix your MAP finding issue since it stretches out the near zero part of the distribution. The log transform here makes the MAP non-degenerate.

For example, the following works fine and doesn't lead to an extreme value (tau_log ends up at 0, tau ends up at 1)

```
import pymc3 as mc

with mc.Model() as m: 
    tau = mc.Gamma('tau', alpha=.1, beta=.1, testval=6)
    start = mc.find_MAP()
```

However, its still good to have a general solution for bounding distributions. We have an existing one that is okay, but its a bit tricky to use. I can still imagine some uses for constrained optimization, but I think most of the obvious ones are handled by automatic transformation of variables.

Right now there's the `Bound` class for bounding distributions where you can do 

```
BoundedGamma = Bound(Gamma, lower=.1)
tau = BoundedGamma('tau', alpha=.1, beta=.1)
```

This is okay, but I think could probably be a lot more intuitive. I'd have to think about how to integrate Chris' syntax or your syntax in a natural way.

**Comment by aflaxman** [comment]
I think I will retract this feature request for now, since I am not able to generate a convincing example of when I would want to use it.  Here is the closest I've come:

```
import numpy as np, pandas as pd, pymc3 as pm
import theano.tensor as tt

np.random.seed(12345) # set random seed for reproducibility

# simulate data
n=10
p=3
beta_true = np.random.normal(size=p)
X = np.random.normal(size=(n,p))
y = np.dot(X, beta_true)


# setup model
gamma_model = pm.Model()
with gamma_model:
    beta = pm.Normal('beta', mu=0, sd=1, shape=p)
    sd = pm.Gamma('sd', alpha=1, beta=1)
    y_obs = pm.Normal('y_obs', mu=tt.dot(X, beta), sd=sd, observed=y)

    # obtain starting values via MAP
    start = pm.find_MAP()

# using this starting point is not good

# fit model
with gamma_model: 
    # instantiate sampler
    step = pm.Metropolis() 

    # draw 500 posterior samples
    trace = pm.sample(10000, step, start=start) 
```

However, using a different starting point is not good, either. I think that the model is what needs work.  Changing it so that

```
    sd = pm.Bound(pm.Gamma, lower=.1)('sd', alpha=1, beta=1)
```

seems to sort things out on the model side.

**Comment by jsalvatier** [comment]
I think with the new auto-applied transformations sampling from the previous model will also work.
