### ISSUE TITLE
Remove live plots

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3411]
I just ran the live plot NB and saw that the functionality is broken, which means that no one is using it, we should just remove that feature.

**Comment by ColCarroll** [comment]
It was a cool feature, but I have not used it either. 

For anyone picking this up, this could be done in one or two pull requests:
1. deleting the notebooks 
2. deleting the functionality

**Comment by junpenglao** [comment]
Should we move it to experimental (I think we should remove it as well, but just an option)?

**Comment by twiecki** [comment]
In this case I think we should get rid of it. It's not that it's experimental but apparently just not required.

**Comment by p-murli** [comment]
Hey, if this issue is open I would like to take it up. I'm a newcomer so if you could give me a few pointers on how to get started, that would be great.

**Comment by twiecki** [comment]
Great, definitely. Basically look into the sample function and see where
the live plotting code happens and rip that out and everything that only
depends on that.

**Comment by p-murli** [comment]
I went through the sample function in `sampling.py` and found the following block containing reference to live plots as well as in the function call

```
try:
        strace = None
        for it, strace in enumerate(sampling):
            if live_plot:
                if live_plot_kwargs is None:
                    live_plot_kwargs = {}
                if it >= skip_first:
                    trace = MultiTrace([strace])
                    if it == skip_first:
                        ax = plots.traceplot(trace, live_plot=False, **live_plot_kwargs)
                    elif (it - skip_first) % refresh_every == 0 or it == draws - 1:
                        plots.traceplot(trace, ax=ax, live_plot=True, **live_plot_kwargs)
```

Can this block be removed entirely as it is dependent on live_plot?

**Comment by twiecki** [comment]
@p-murli Yes, exactly. There's probably more places as well.

**Comment by josephwillard** [comment]
Hey, is anyone still working on this?

**Comment by twiecki** [comment]
Not to my knowledge, want to take it on?

**Comment by josephwillard** [comment]
Yeah,  I'll take a look into it.

**Comment by josephwillard** [comment]
I removed all references I could find to live plots in PR #3445.

**Comment by twiecki** [comment]
Closed by #3445.

**Comment by davidbrochart** [comment]
Live plots work in the classic Jupyter Notebook with `%matplotlib notebook`. But in Jupyter Lab we get an error (`Javascript Error: IPython is not defined`), because only `%matplotlib inline` is supported, which unfortunately doesn't allow to have live plots.

**Comment by arose13** [comment]
I tried using many times because I wanted to use it, it just never worked.

**Comment by akruzliak** [comment]
Hi, would you mind removing it from the documentation as an argument into `pymc3.sampling.sample()` ? Apparently it has been removed a year ago but the [documentation](https://pymc3-testing.readthedocs.io/en/rtd-docs/api/inference.html#module-pymc3.sampling) still points to it as a valid argument. Thanks a lot!
