### ISSUE TITLE
pymc3.summary still uses `varnames`, change to var_names

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3412]
We changed `varnames` to `var_names` in most cases, but seem to have missed `pm.summary`. Also needs the deprecation warning.

**Comment by chang111** [comment]
I am very interested in this, but I don't know if you can describe it in more detail.
Thank You

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/blob/02f0b7f9a487cf18e9a48b754b54c2a99cf9fba8/pymc3/stats.py#L853 takes `varnames` but we recently renamed it to `var_names` (to follow arviz). It's probably as simple as decorating that function with this: https://github.com/pymc-devs/pymc3/blob/55f25120bccfd1fc87d2299651daa8dd3c0ef0d4/pymc3/plots/__init__.py#L32 and renaming the kwarg. Does that make sense?

**Comment by chang111** [comment]
Oh,I get it. Thank You very much

**Comment by twiecki** [comment]
Same for gelman rubin https://github.com/pymc-devs/pymc3/blob/d5e0a68a02ce6cd4bf02c713bde055d30dbb3a5c/pymc3/diagnostics.py#L100. @aloctavodia @ColCarroll shouldn't that one map to arviz as well?

**Comment by ColCarroll** [comment]
We moved gelman-rubin to [rhat](https://arviz-devs.github.io/arviz/generated/arviz.rhat.html#arviz.rhat), per a suggestion from Aki Vehtari. 

Part of the issue is that we only ported plotting over so far, and no one has looked at moving diagnostics and statistical computations.
