### ISSUE TITLE
Travis is unhappy about missing matplotlib

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3423]
No idea why that shows up now. Did we stop installing matplotlib?

```
++++pylint --rcfile=.pylintrc pymc3
************* Module pymc3.gp.util
pymc3/gp/util.py:101: [E0401(import-error), plot_gp_dist] Unable to import 'matplotlib.pyplot'
************* Module pymc3.examples.GHME_2013
pymc3/examples/GHME_2013.py:3: [E0401(import-error), ] Unable to import 'matplotlib.pyplot'
************* Module pymc3.examples.custom_dists
pymc3/examples/custom_dists.py:11: [E0401(import-error), ] Unable to import 'matplotlib.pyplot'
************* Module pymc3.tests.test_examples
pymc3/tests/test_examples.py:1: [E0401(import-error), ] Unable to import 'matplotlib'
```

```
________________ ERROR collecting pymc3/tests/test_examples.py _________________
ImportError while importing test module '/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
pymc3/tests/test_examples.py:1: in <module>
    import matplotlib
E   ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by chang111** [comment]
This error also happens in PR 3414

**Comment by canyon289** [comment]
Technically PyMC3 does not require matplotlib anymore, even for dev, but it should be captured in the ArviZ requirements.

Is this still an issue? if so I can dive in


https://github.com/pymc-devs/pymc3/blob/master/requirements.txt
https://github.com/pymc-devs/pymc3/blob/master/requirements-dev.txt

**Comment by chang111** [comment]
@canyon289 I can help if necessary.

**Comment by canyon289** [comment]
@chang111 You're welcome to take lead on the issue! I'd be happy to review a PR. Let me know if you'd like to do that

**Comment by chang111** [comment]
@canyon289 Yes It is my pleasure to fix this issue

**Comment by chang111** [comment]
After analysis, I think there should be two solutions, one is to add Matplotlib to the installation file, the other is to delete all the sentences in Pymc3 that need to reference Matplotlib.

**Comment by canyon289** [comment]
> After analysis, I think there should be two solutions, one is to add Matplotlib to the installation file, the other is to delete all the sentences in Pymc3 that need to reference Matplotlib.

In regards to either option, are we certain that matplotlib is not being installed in TravisCI? If you want to do me a favor could you post a CI log for one of the failing builds? Was unable to find it myself.

**Comment by chang111** [comment]
@canyon289 The above log that twiecki has given is what you want?

**Comment by canyon289** [comment]
He gave me a part but I was looking for the full log :)
https://travis-ci.org/pymc-devs/pymc3/builds/509884252

I'm curious why the matplotlib requirement is not being installed via arviz. 

For adding matplotlib as a requirement, I would hope we don't need to do that because it adds extra weight for either regular users or dev users when they might not want it. 

As you suggested though maybe the matplotlib tests need to be removed, but I figure let's see why its not being installed before we do all the work of taking it out!

I created this PR here to have TravisCI list all the packages in the environment to verify if matplotlib is present or not in the environment

https://github.com/pymc-devs/pymc3/pull/3425

**Comment by canyon289** [comment]
So this is weird. Without any changes matplotlib is installed and all tests pass so something else is going on in those failing builds.....

Maybe we can rebase those PRs once we merge https://github.com/pymc-devs/pymc3/pull/3425 and see if the error persists

https://travis-ci.org/pymc-devs/pymc3/jobs/510748115#L1083

**Comment by twiecki** [comment]
I cleaned the caches, that's probably it.

**Comment by twiecki** [comment]
Thanks for the help everyone!

**Comment by canyon289** [comment]
@chang111 Thanks so much for the help! Much appreciated

**Comment by lucianopaz** [comment]
This reappeared in PR #3433.

The test env fetches its [cache data here](https://travis-ci.org/pymc-devs/pymc3/jobs/512374480#L474-L485), it creates the test env, which includes matplotlib, [here](https://travis-ci.org/pymc-devs/pymc3/jobs/512374480#L586-L613), and attempts to pip-install the dev requirements [here](https://travis-ci.org/pymc-devs/pymc3/jobs/512374480#L721-L860). In particular, [arviz is found to already exist](https://travis-ci.org/pymc-devs/pymc3/jobs/512374480#L722), which means that it's being pulled from the cache. However, it does not check if its requirements, like matplotlib being installed, are satisfied. Is this an arviz problem with the requirements checks or is it just a faulty travis cache? What are your thoughts @canyon289, @ColCarroll, @twiecki?

**Comment by twiecki** [comment]
It's quite confusing. I deleted the cache again and retried.

**Comment by canyon289** [comment]
Now there's some other problem.... Restarting again

**Comment by canyon289** [comment]
We could turn off pip caching by using the option `--no-cache-dir`. Based off the description this sounds like itll fix the problem

https://pip.pypa.io/en/stable/reference/pip_install/#caching

**Comment by canyon289** [comment]
Is this an issue still? Asking for two reasons

1. I can try fixing this as is
2. I'm part of NumFOCUS working group so I can bring this up as one of the issues with TravisCI for the group

**Comment by twiecki** [comment]
Seems to still reoccur.

**Comment by ColCarroll** [comment]
https://travis-ci.org/pymc-devs/pymc3/jobs/513912275 this morning, for example.

**Comment by canyon289** [comment]
Ugh,
Will try to fix in ~10 hours.

Thanks for the update
