### ISSUE TITLE
documentaion on Weibull distribution contains a mistake

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3432]
I am sorry, but I think the variance of Weibull distribution shown in https://docs.pymc.io/api/distributions/continuous.html#pymc3.distributions.continuous.Weibull is simply wrong. It does not equal to ```\beta^2\Gamma(1+2/\alpha-\mu^2)```, but ```\beta^2(\Gamma(1+2/\alpha)-\mu^2/\beta^2)```. At least, the Wikipedia page on Weibull distirubution confirms my guess

**Comment by chang111** [comment]
well, I think you are right. Let me to make a pr to fix it.

**Comment by aakhmetz** [comment]
@chang111 Because it is on the same page, you could also remove an unnessary closing bracket in the denominator of the p.d.f. of Wald distribution (just after ```\pi```)

**Comment by chang111** [comment]
Good advice!

**Comment by aakhmetz** [comment]
Thanks!
