### ISSUE TITLE
PyPI Issue with PyMC3

### ISSUE THREAD

**Issue by hectormz** [pymc-devs/pymc#3452]
When trying to look for outdated packages (`pip list -o`), the process seemed to stall. 
When running it again with the verbose option (`pip list -o -v`) everything proceeded normally until reaching pymc3, and the following was displayed:

```
1 location(s) to search for versions of pymc3:
* https://pypi.org/simple/pymc3/
Getting page https://pypi.org/simple/pymc3/
Looking up "https://pypi.org/simple/pymc3/" in the cache
Request header has "max_age" as 0, cache bypassed
https://pypi.org:443 "GET /simple/pymc3/ HTTP/1.1" 304 0
```
If I didn't interrupt the console, this would be stopped forever it seems.
If I were to uninstall pymc3, and attempt to reinstall via pip, the same issue occurs. I think this first happened last night. I'm only reporting this here because it seemed to stall at pymc3, and was not an issue once pymc3 was uninstalled. My current pymc3 version is form pip installing from GitHub.

## Versions and main components

* PyMC3 Version: 3.6
* Theano Version: 1.0.4
* Python Version: 3.6.7
* Operating system: Windows 10
* How did you install PyMC3: pip

**Comment by ericmjl** [comment]
@HectorM14, do you have other packages that are also installed from GitHub? Do they stall as well?

If so, this may be an issue with pip, rather than PyMC3.

If not, though, I'm not quite sure how to debug this.

**Comment by hectormz** [comment]
Hi @ericmjl , thanks for the response. To clarify, I only pip installed from GitHub while troubleshooting this, since I was no longer able to install from PyPI. 

It seems like this was an issue with cache I had for PyMC3. Pip installing with `--no-cache-dir` worked, but I still had issues with pip stalling for other purposes until I cleared out my cache. I guess it was just a coincidence that it was consistently an issue with PyMC3. 

This can be closed.
