### ISSUE TITLE
Solid draft of documentation

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#346]
There's a skeleton already, but needs to be filled out.

**Comment by jsalvatier** [comment]
@fonnesbeck We should put together a plan for getting the docs done. First off, who's taking the lead? Is this something you're planning on tackling? Or should I take it on? 

I feel a bit intimidated by the idea of writing the docs, but that might just mean it would be a good learning experience.

**Comment by fonnesbeck** [comment]
I'm comfortable writing documentation, but will not be able to get to it until late November, since I have a heavy teaching load right now. So, if you have the time, feel free to get started, otherwise I will pick it up in a couple months.

**Comment by fonnesbeck** [comment]
One thing the docs are going to have to have is a pretty extensive Theano tutorial. The one on deeplearning.net is not very good. Having data interact with PyMC objects is not straightforward; For example, making linear combinations of values of data with values of distributions for use in other parts of the model. This aspect of PyMC will be the biggest learning hurdle for folks coming across from PyMC 2.

**Comment by twiecki** [comment]
Maybe we can start by adapting the pymc2 documentation which is pretty good. Things like the disaster model are already ported so parts like the tutorial should be trivial.

**Comment by twiecki** [comment]
Another idea would be to use @camdavidsonpilon's Probabilistic Programming for Hackers book which could be ported to pymc3 without too much effort and already covers most of the bases.

https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/issues/155

**Comment by jsalvatier** [comment]
Very clever, I like it. We should ask the Cam, though. 

That seems like it might annoy him and/or violate his copyrights.

**Comment by jsalvatier** [comment]
@fonnesbeck What's the best way for me to contribute to working on the docs?

**Comment by fonnesbeck** [comment]
I think borrowing chunks of the PPH book is a good idea, but there are big sections of the book that probably would not work as part of a user's guide. It also does not touch on one of the biggest aspects of PYMC 3, which is the gradient-based MC.

@jsalvatier I would pick a section in the existing skeleton and start fleshing it out. That skeleton is based entirely on PyMC 2, so it is not exactly what we need. For example, we need an entire Theano section, since it is such a central part of the new version.

One choice we need to make is whether to stick with reStructuredText/Sphinx or move to some flavor of Markdown. The world seems to be moving toward the latter, but there are advantages to reST in a Python context.

**Comment by CamDavidsonPilon** [comment]
I have plans to convert the book to PyMC3 already, but I agree with @fonnesbeck that the book is currently too broad to be used as specific documentation for PyMC3. Power users of PyMC2/3 would find the text too high level for their needs too.

**Comment by fonnesbeck** [comment]
I'm also working on a book for Springer that will be geared towards advanced statistical applications, and include a fair bit of theoretical background. So between Cam's book and mine there should be a fair quantity of "extended documentation" for those who are interested. That should allow us to keep the docs focused as mostly a technical reference and quick start for users.

**Comment by jsalvatier** [comment]
Writing the documentation, I'm noticing that our language of FreeRV and ObservedRV is pretty different than Stochastic. I wonder if we can bring the language closer. 

I also notice that a Potential is not longer a class, but just a function. We should probably make it a class that inherits from Factor just to make it consistent with PyMC2

**Comment by twiecki** [comment]
Different how? Isn't FreeRV == stochastic and ObservedRV == observed?

**Comment by jsalvatier** [comment]
Well we didn't have Observed in PyMC2, stochastic referred to both Free and
Observed, but maybe we should have Stochastic refer to just Free?

**Comment by twiecki** [comment]
For me the current distinction makes intuitive sense. Having Free refer to Stochastic also makes sense.

**Comment by twiecki** [comment]
Current draft lives at http://pymc-devs.github.io/pymc3/.
