### ISSUE TITLE
Int32 or Int64 for discrete?

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#3475]
Through a recent [discourse thread](https://discourse.pymc.io/t/keyerror-setting-mixture-proportions-for-mixture-model/3217/19) I found that `Discrete` allows int16 or int64 dtypes. Given what we had done for parameters regarding #2366 (we set int16 if floatX is float32 and int32 if floatX is float64), should we change `Discrete` to work with int16 and int32? What do we do with int64's?

**Comment by ricardoV94** [comment]
Related to #4553

**Comment by ferrine** [comment]
Every dtype makes sense, can we specify it with dtype arg? I remember struggling with that and fixed in v3, but not v4

**Comment by ricardoV94** [comment]
Let's not coerce dtype of integer parameters then

**Comment by ricardoV94** [comment]
Should be closed by #7114
