### ISSUE TITLE
theano.gpuarray: pygpu was configured but could not be imported or is too old (version 0.7 or higher required)

### ISSUE THREAD

**Issue by caxelrud** [pymc-devs/pymc#3478]
I am getting this message when importing theano:
"ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None"

* Vpygpu=0.7.6
* PyMC3 Version: 3.6
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: Windows 10

* Installation:
- NVIDIA, Installed latest drivers using GeForce Experience Application
- Installed CUDA 9.0
- Installed dnn at "C:\tools\cuda"
- Installed Theano:
conda install numpy scipy mkl-service libpython m2w64-toolchain
conda install theano pygpu

*Set Windows Environment:
CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
Add to PATH:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\CUPTI\lib64
C:\tools\cuda\bin

*Extras:
Create file at C:\Users\MYSELF\.theanorc with:
[global]
device = cuda
floatX = float32
[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
[dnn]
enabled = True
include_path=C:\tools\cuda\include
library_path=C:\tools\cuda\lib\x64

*pyMC3:
conda install -c conda-forge pymc3

**Comment by twiecki** [comment]
I would recommend to use the CPU as often GPU is not faster (and often times slower).

**Comment by twiecki** [comment]
If you do need the GPU this seems like a theano issue.
