### ISSUE TITLE
Todo: Improve traceplot documentation

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3495]
The `traceplot` documentation states that its functionality is delegated to `arviz`, but doesn't specify which `arviz` function.  I suggest adding a link to the documentation of `plot_trace`.  The documentation of the `coords` argument is also sketchy.  Finally, I wasn't sure why there's no `dimensions` dictionary to parallel the `coords` argument.
If someone would like to clue me in about this a little (particularly about the coordinates), I could try to improve the docstring a little.

**Comment by fonnesbeck** [comment]
Not relevant now that ArVIZ handles plotting.
