### ISSUE TITLE
pymc3 v3.7: python_requires is not recognized by pip

### ISSUE THREAD

**Issue by jakevdp** [pymc-devs/pymc#3496]
Example:
```
$ python2 -m pip install pymc3
Collecting pymc3
  Downloading https://files.pythonhosted.org/packages/af/a3/4e759f5707902a2ab03d01be4589bba029d291dcc9bda9043db8bd180eaf/pymc3-3.7.tar.gz (30.8MB)
     |████████████████████████████████| 30.8MB 64.8MB/s 
ERROR: pymc3 requires Python '>=3.5.4' but the running Python is 2.7.15
```
for comparison:
```
$python2 -m pip install scipy
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/81/39/f1457091d0a45a84a2bd7815e2cf6bd45d4fe240728e9ed567cbb17c8abe/scipy-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (24.8MB)
     |████████████████████████████████| 24.8MB 1.3MB/s 
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python2.7/dist-packages (from scipy) (1.16.3)
Installing collected packages: scipy
Successfully installed scipy-1.2.1
```
Notice that pip knows not to use the 1.3 release, which is incompatible with Python 2, and so it chooses 1.2. The pymc install on Python 2 should similarly know to choose version 3.6.

I'm not entirely certain what's causing this, because setup.py specifies ``python_requires``. I have a couple hypotheses:

1. perhaps python_requires cannot handle micro versions like ``python_requires=">=3.5.4"``?
2. perhaps the pymc3 3.7 wheels were built with an old version of setuptools, as suggested by the note in the [packaging guide](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)?

My pip version is up to date, so that shouldn't be an issue
```
$ python2 -m pip --version
pip 19.1.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

**Comment by jakevdp** [comment]
Another possibility is that the distribution was uploaded to pypi via ``python setup.py upload`` rather than twine, and it left the required Python version out of the PyPI metadata.

**Comment by lucianopaz** [comment]
Ping @twiecki

**Comment by ColCarroll** [comment]
Yeah, it looks like we have only uploaded the .tar.gz, not the wheel, and so it is not picking up the version:

![image](https://user-images.githubusercontent.com/2295568/58751897-54c7da80-8473-11e9-9754-38a504213ee7.png)

Here is 3.5 by comparison:

![image](https://user-images.githubusercontent.com/2295568/58751888-3bbf2980-8473-11e9-8ce9-141e308e11b0.png)

I'm not familiar with this, so I also checked out altair. Check out the `python version` column in each screen shot:

![image](https://user-images.githubusercontent.com/2295568/58751908-8b9df080-8473-11e9-8a81-eb8d7c454953.png)

**Comment by twiecki** [comment]
Yes, I did not use twine, so that's probably the problem.

**Comment by twiecki** [comment]
I tried it now with twine, can someone confirm if it works correctly now?

**Comment by twiecki** [comment]
![image](https://user-images.githubusercontent.com/674200/59092691-795c0080-8912-11e9-88e9-92baecab9a56.png)

**Comment by snazzybloke** [comment]
You might have solved the issue for python2, but for python3 it still persists:
pip3 install -U pymc3
Collecting pymc3
  Using cached https://files.pythonhosted.org/packages/42/c2/86e8be42b99d64932fa12611b502882a5f4d834b6d1d126bf3f956ad6428/pymc3-3.7-py3-none-any.whl
ERROR: Package 'pymc3' requires a different Python: 3.5.2 not in '>=3.5.4'
