### ISSUE TITLE
PyMC 3.7: traceplot `lines` argument not backwards compatible

### ISSUE THREAD

**Issue by clausherther** [pymc-devs/pymc#3497]
In <= 3.6, I was able to pass in a dictionary of values for each variable to the `lines` argument in `traceplot`, such as 
```python
{'intercept': 146.08760340374477,
 'coeff__0': 0.479108443336752,
 'coeff__1': 0.4108381183948031}
```
For example, the following snippet shows a commonly used way to extract the means of each trace to plot as a line on the traceplot. 
```python
pm.traceplot(trace, 
                 var_names=varnames, 
                 divergences=None,
                 combined=True, 
                 lines={k: v['mean'] for k, v in pm.summary(trace).iterrows()}
                )
```

In 3.7, the new arviz traceplot takes a different format for the lines argument. As a result, the values for lines are ignored and not plotted. 
Also, there doesn't seem to be a good example of how to reformat code to support this. I'd be happy to update the doc string or doc website, but I can't seem to find any good hints on how to format the values correctly.

**Comment by ColCarroll** [comment]
Thanks for filing -- @twiecki also pointed this problem out today. I can explain the design decision (and happy for input!) if there's interest, but suffice to say that the correct answer here (and I realize it doesn't look good) is:

```python
pm.traceplot(trace, 
    var_names=varnames, 
    divergences=None,
    combined=True, 
    lines=[[k, {}, [v['mean']] for k, v in pm.summary(trace).rows()])
```

The documentation is here:

https://arviz-devs.github.io/arviz/generated/arviz.plot_trace.html

and the section of it is here:

![image](https://user-images.githubusercontent.com/2295568/58589420-d5969480-822f-11e9-8568-cd1ea2343097.png)

**Comment by clausherther** [comment]
Thanks @ColCarroll ! I definitely looked at the docs, but I'm not sure I could have come up with your solution. I'll try that.
I'm also running into a similar issue in #3498 .

**Comment by clausherther** [comment]
FYI, I think it's:

```python
pm.traceplot(trace, lines=[(k, {}, [v['mean']]) for k, v in pm.summary(trace).iterrows()])
```

**Comment by clausherther** [comment]
And this doesn't seem to work for the multi-valued variables, like the `coeff` in this example:

![image](https://user-images.githubusercontent.com/7342749/58590175-5f3a6800-8218-11e9-80c7-0fe4e1707ab4.png)

The passed-in list of tuples:
```python
[(k, {}, [v['mean']]) for k, v in pm.summary(trace).iterrows()]
```
```python
[('intercept', {}, [146.08760340374477]),
 ('coeff__0', {}, [0.479108443336752]),
 ('coeff__1', {}, [0.4108381183948031]),
 ('intercept_sd', {}, [513.4722334788605]),
 ('coeff_sd', {}, [3.6212886889302633]),
 ('coeff_diff', {}, [-0.06827032494194529]),
 ('coeff_perc_diff', {}, [0.8578315563876061]),
 ('err', {}, [505.49752567011234])]
```

**Comment by twiecki** [comment]
This API is really cumbersome.

**Comment by ColCarroll** [comment]
Actually, this issue of an example of _why_ it is cumbersome (so, not disagreeing, just explaining), since `coeff` is a 2d variable, you need to supply the coordinate to put the line on:

```python
[('intercept', {}, [146.08760340374477]),
 ('coeff', {'coef_dim_0': 0}, [0.479108443336752]),
 ('coeff', {'coef_dim_1': 1}, [0.4108381183948031]),
 ('intercept_sd', {}, [513.4722334788605]),
 ('coeff_sd', {}, [3.6212886889302633]),
 ('coeff_diff', {}, [-0.06827032494194529]),
 ('coeff_perc_diff', {}, [0.8578315563876061]),
 ('err', {}, [505.49752567011234])]
```

Note that you need all this data to define a line! The way we identify a plot is by variable name, and coordinate (`{'coef_dim_0': 0}` is a coordinate). Variables can have multiple coordinates, which is why that argument is a dictionary.

**Comment by clausherther** [comment]
I'll give that shot, thx @ColCarroll!

Do you want me to close this issue then, or keep open for visibility?

**Comment by ColCarroll** [comment]
I'm going to close, but if you (or thomas, or anyone) has suggestions for a nicer API, I remain interested!

**Comment by clausherther** [comment]
So, it took me a bit to get this right, and this probably still preeetty hacky.

Would it make sense to add this sort of handling of `lines` to pymc3 as an optional parameter somehow? Or a helper/utility function to arviz?

I think the key is to get the dimensions right. In this case it was `coef_dim_0` for both coefficients, but the position was `0` and `1`.

```python
[('intercept', {}, [146.08760340374477]),
 ('coeff', {'coeff_dim_0': 0}, [0.479108443336752]),
 ('coeff', {'coeff_dim_0': 1}, [0.4108381183948031]),
 ('intercept_sd', {}, [513.4722334788605]),
 ('coeff_sd', {}, [3.6212886889302633]),
 ('coeff_diff', {}, [-0.06827032494194529]),
 ('coeff_perc_diff', {}, [0.8578315563876061]),
 ('err', {}, [505.49752567011234])]
```
```python
def get_lines_value_tuple(key, value, agg="mean"):
    
    key_name = key.split("__")
    
    return (key_name[0], 
            {f"{key_name[0]}_dim_0": int(key_name[1])} if len(key_name) > 1 else {}, 
            [value[agg]]) 
    
def trace_plot(trace, var_names=None):
    
    var_names = var_names if var_names else trace.varnames
    
    lines = [get_lines_value_tuple(k, v, "mean") 
             for k, v in pm.summary(trace).iterrows()]

    pm.traceplot(trace, 
                 var_names=var_names, 
                 divergences=None,
                 combined=True, 
                 lines=lines
                )
 ```

<img width="880" alt="image" src="https://user-images.githubusercontent.com/7342749/58715591-0b489400-837c-11e9-9365-fd6f361fc3f5.png">
