### ISSUE TITLE
PyMc3 v3.7 Nuts sampling

### ISSUE THREAD

**Issue by mofe23** [pymc-devs/pymc#3501]
Hi!

First: Thanks for maintaining, keep up the good work :) 

## Description of your problem
Today i updated from v3.5 to 3.7 and our code broke :(
```
    with model:
        trace = pm.sample(
            draws=draws,
            tune=1000,
            progressbar=False,
            nuts_kwargs=dict(target_accept=0.9)
        )
```

Looking at your release notes i found that:
> nuts_kwargs and step_kwargs have been deprecated in favor of using the standard kwargs to pass optional step method arguments.

So i changed our code to
```
    with model:
        trace = pm.sample(
            draws=draws,
            tune=1000,
            progressbar=False,
            target_accept=0.9,
        )
```

Which led to this Exception:
```python
/opt/conda/lib/python3.6/site-packages/pymc3/sampling.py:406: in sample
    step = assign_step_methods(model, step, step_kwargs=kwargs)
/opt/conda/lib/python3.6/site-packages/pymc3/sampling.py:155: in assign_step_methods
    return instantiate_steppers(model, steps, selected_steps, step_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

model = <pymc3.model.Model object at 0x7f0047b2a9b0>
steps = [<pymc3.step_methods.hmc.nuts.NUTS object at 0x7f00335fe3c8>, <pymc3.step_methods.metropolis.BinaryGibbsMetropolis object at 0x7f001c9fada0>]
selected_steps = defaultdict(<class 'list'>, {<class 'pymc3.step_methods.hmc.nuts.NUTS'>: [pi_outlier_logodds__, a_eta, b_eta, tau_eta_...lon, eta, epsilon, r_normal, sd, nu_log__], <class 'pymc3.step_methods.metropolis.BinaryGibbsMetropolis'>: [lambda_t]})
step_kwargs = {'target_accept': 0.9}
    def instantiate_steppers(model, steps, selected_steps, step_kwargs=None):
        if step_kwargs is None:
            step_kwargs = {}
    
        used_keys = set()
        for step_class, vars in selected_steps.items():
            if len(vars) == 0:
                continue
            args = step_kwargs.get(step_class.name, {})
            used_keys.add(step_class.name)
            step = step_class(vars=vars, **args)
            steps.append(step)
    
        unused_args = set(step_kwargs).difference(used_keys)
        if unused_args:
>           raise ValueError('Unused step method arguments: %s' % unused_args)
E           ValueError: Unused step method arguments: {'target_accept'}

/opt/conda/lib/python3.6/site-packages/pymc3/sampling.py:81: ValueError
```
## Aditional Info

I'm no pymc3 expert, to be honest i can;t event describe what our code does :)

What i see is that, in the for loop of `instantiate_steppers` values of `step_kwargs` that match`pymc3.step_methods.hmc.nuts.NUTS#name` (nuts) will get extracted. I only passed `{"target_accept": 0.9}`, so the `ValueError` telling me about unused variables gets thrown.

When i change the call to `pm.sample` to the following, our tests pass again.
```
    with model:
        trace = pm.sample(
            draws=draws,
            tune=1000,
            progressbar=False,
            nuts={"target_accept": 0.9},
        )
```

#3327 introducted the changes that lead to described behavior. Is this a bug in pymc3 or did we use the library in a wrong way?
(In a test, commit 990d2487c0cca918148bcd5d5688334d4cd17837 added an assertion around a call that is excactly what i thought i should do to fix that error.)

## Versions and main components

* PyMC3 Version: 3.7
* Theano Version: Theano==1.0.4
* Python Version: Python 3.6.0 :: Continuum Analytics, Inc.
* Operating system: alpine:3.6
* How did you install PyMC3: conda

**Comment by fonnesbeck** [comment]
I think you may not have updated PyMC as you think you have. The following works fine with the PyMC 3.7 release version on a clean conda env:

```
>>> import pymc3 as pm
>>> with pm.Model() as mod:
...     x = pm.Normal('x')
... 
>>> with mod:
...     trace = pm.sample(target_accept=0.99)
... 
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [x]
Sampling 2 chains: 100%|███████████████████████| 2000/2000 [00:01<00:00, 1446.25draws/s]
```

Please confirm your PyMC version and let us know.

**Comment by mofe23** [comment]
Thanks for the quick response!

I can confirm that i run on  version 3.7, but i can also confirm that when i run your example, everything works as expected.

I will check with my collegues on  monday. closing this for now, will get back on you on this later.

**Comment by xialang2012** [comment]
I also need to change the target_accept. This failed for me `trace = pm.sample(epohs, cores=1, tune=3000, target_accept=0.9)`. Do you know the correct way to change the target_accept?

I installed the PYMC3 bu using `pip install git+https://github.com/pymc-devs/pymc3` last week.

**Comment by aloctavodia** [comment]
@xialang2012 I am not able to reproduce your error. I am using PyMC3 from master. Maybe you have more than one version of PyMC3 in your system and you are not running the updated one.

**Comment by xialang2012** [comment]
@aloctavodia 

`print(pm.__version__)` I got `3.7`. 

I think my problem is the sampler failed to init NUTS sampler, pls see the output
> Auto-assigning NUTS sampler…
> Initializing NUTS using jitter+adapt_diag…
> Initializing NUTS failed. Falling back to elementwise auto-assignment.
> Traceback (most recent call last):
> File “C:\Miniconda3\lib\site-packages\pymc3\sampling.py”, line 396, in sample
> progressbar=progressbar, **kwargs)
> File “C:\Miniconda3\lib\site-packages\pymc3\sampling.py”, line 1515, in init_nuts
> step = pm.NUTS(potential=potential, model=model, **kwargs)
> File “C:\Miniconda3\lib\site-packages\pymc3\step_methods\hmc\nuts.py”, line 152, in init
> super().init(vars, **kwargs)
> File “C:\Miniconda3\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py”, line 72, in in

Do you know what the `Falling back to elementwise auto-assignment.` meaning it is? I mean, when NUTS failed, what kind of sample mathod would be used by PYMC3. Thank you.
