### ISSUE TITLE
Stopping sampling early, similarly to pm.fit method

### ISSUE THREAD

**Issue by michael-ziedalski** [pymc-devs/pymc#3510]
When working with Pymc3, I find most of the time that even the smallest realistic models I can create, on a decently fast work-station, take at least a few minutes to run.

That being the case that probably everyone has to deal with, what would it take to implement something like `pm.fit`'s [early halting method](https://docs.pymc.io/notebooks/variational_api_quickstart.html) (which is found a bit toward the bottom under "hard stop"), if a particular instance is taking too long to run?

I've looked into the matter, in [pm.fit](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/inference.py) and [callbacks'](https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/callbacks.py) sources (and if my analysis is amateurish, please do correct me), and it seems that `callback` by default keeps track of 1) the amount of time the model has been going, and 2) how many its/sec is occurring atm. To halt the model early, it calls `StopIteration` (line [173](https://github.com/pymc-devs/pymc3/blob/183bc5fa08416824a5ea5fd08179962c5c1997bc/pymc3/variational/inference.py#L173)), which then primarily calls `progress.close()`.

My question is if within `sample` it would make sense to code in `StopIteration` to hijack `KeyboardInterrupt`'s activity (such as line [990](https://github.com/pymc-devs/pymc3/blob/183bc5fa08416824a5ea5fd08179962c5c1997bc/pymc3/sampling.py#L990)) to similarly halt models? 

Any advice would be welcome.

**Comment by ColCarroll** [comment]
To clarify, you're asking for an "elegant" way to do this, right? It sounds like you spotted that `KeyboardInterrupt` will save progress.

**Comment by michael-ziedalski** [comment]
Well, yes, because reusing the current functionality in this way seems not only to be clean and elegant, but wouldn't clutter up the code-base.

**Comment by twiecki** [comment]
I think a callback for `pm.sample()` is a great feature request.

**Comment by michael-ziedalski** [comment]
If `cores=1`, it seems that `_sample()` ends up creating the progress bar through tqdm (line [541](https://github.com/pymc-devs/pymc3/blob/e33cd624af07057fa8be59c3e857b8f53bf852a4/pymc3/sampling.py#L541)), which gains constant access to the constantly changing variables, like it/sec, through `_iter_sample()` (line [596](https://github.com/pymc-devs/pymc3/blob/e33cd624af07057fa8be59c3e857b8f53bf852a4/pymc3/sampling.py#L596)) because it feeds it a generator object.

How would one access the generator object?

**Comment by michael-ziedalski** [comment]
Going through the codebase, could someone help explain what exactly is fed into `tqdm` to create the progress-bar that allows it to estimate a time to completion? `_iter_sample` ([596](https://github.com/pymc-devs/pymc3/blob/a3fcc861ae0f160111afb95a574540272de644a3/pymc3/sampling.py#L596)) feeds an iterable object in,  but I'm having trouble making sense of it.

**Comment by Overlord2335** [comment]
Hi I'd like to work on this. If it's available can someone tell me which part of code is this related to? And some basic reading material before I dive into the code?

**Comment by twiecki** [comment]
This issue looks fixed but thanks @Overlord2335.
