### ISSUE TITLE
Show grid with plot_forest()

### ISSUE THREAD

**Issue by petrushev** [pymc-devs/pymc#3515]
Before the arviz integration, the forest plots of traces showed the grids by default.
Can we have that behavior back again?

Right now I'm doing:

    fix, axes = pm.plot_forest(trace, var_names[...])
    axes[0].grid()

but I feel like in general this is needed, at least for the vertical grid.
(Also, not sure if I should report this to arviz? I think it's better to provide defaults here instead, but would be happy to have it anywhere)

**Comment by ColCarroll** [comment]
Are you setting any style defaults, via `plt.style.use('...')` or `az.style.use('...')`? 

A philosophy in arviz is to return the axes handle so you can customize just like you did, but I guess it is just as easy to customize the grid _away_.

**Comment by petrushev** [comment]
> Are you setting any style defaults, via `plt.style.use('...')` or `az.style.use('...')`?

I am, using `plt.style.use('seaborn-whitegrid')`.

> A philosophy in arviz is to return the axes handle so you can customize just like you did, but I guess it is just as easy to customize the grid _away_.

I tried, and it seems somewhere this default is being overridden when I use `plot_forest`...

**Comment by OriolAbril** [comment]
Looks like this is a problem with line [204](https://github.com/arviz-devs/arviz/blob/1a810ee3b92bfd8999f4d2fabebf9368f3883caf/arviz/plots/forestplot.py#L204) in forestplot.py.

About posting issues here or there, maybe there could be some guidelines in the issues templates? Mainly thinking about the poster, I think they will probably get faster response/solution/bug solve posting in ArviZ.
