### ISSUE TITLE
regression with Dirichlet process mixtures

### ISSUE THREAD

**Issue by Fangwq** [pymc-devs/pymc#3520]
I want to do regression with Dirichlet process mixtures model. And I refer to the example provided by this package. However, I do not figure it out. And I also tried  Dirichlet process density regression. But it can't be used for data prediction.(I think this demo is wrong: https://docs.pymc.io/notebooks/dependent_density_regression.html).

The prediction error that the output dimension doesn't match:
'''
ax.plot(lidar_pp_x, pp_trace['obs'].mean(axis=0),
        c='k', zorder=6,
        label='Posterior expected value');
'''
Does anyone know how to do regression with Dirichlet process mixtures? thank you very much!
I use pymc3-3.6 and theano-1.04.

**Comment by lucianopaz** [comment]
These questions should be asked in [our discourse channel](https://discourse.pymc.io/) and not in the issue tracker. Please ask it there.
