### ISSUE TITLE
Add back plot prior with traceplot() feature

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#3523]
I believe this feature is not implemented in arviz.

**Comment by ahartikainen** [comment]
It could be (we have `prior` dataset). There also should be possibility to add dictionary.

That said, these plots are meaningfull only low-dim cases, right?

**Comment by junpenglao** [comment]
You can also plot the marginal but in general yes.

**Comment by Mind-The-Data** [comment]
I would love this feature. As I just updated and am using arviz I am not able to plot priors over posteriors. This is very helpful when trying to ascertain how much influence priors have on particularly difficult hyper parameters.

**Comment by sammosummo** [comment]
> It could be (we have `prior` dataset). There also should be possibility to add dictionary.
> 
> That said, these plots are meaningfull only low-dim cases, right?

I also would appreciate this.

**Comment by ricardoV94** [comment]
Should this issue be moved to the arviz repo?

**Comment by OriolAbril** [comment]
If it is still an issue yes, I have to recognize I don't understand the request though, I probably never saw the old plot and I'm missing the reference, so an example or sketch would be great.

**Comment by ricardoV94** [comment]
I think you could plot the trace with the posterior and the prior overlaying on top of each other, but I could be wrong.

**Comment by ricardoV94** [comment]
I think you could plot the trace with the posterior and the prior overlaying on top of each other, but I could be wrong.

**Comment by ricardoV94** [comment]
https://discourse.pymc.io/t/how-i-get-traceplot-or-something-else-to-show-priors/207

**Comment by ricardoV94** [comment]
This is how it used to be implemented before: https://github.com/pymc-devs/pymc3/blob/d1c039f49472e2919fbdaa51c4af28a3932e26f2/pymc3/plots/traceplot.py#L8-L47

**Comment by aloctavodia** [comment]
ArviZ has a prior_posterior plot arviz-devs/arviz#1148, than in general should be a better solution.

**Comment by ricardoV94** [comment]
Sounds good. I'll close this then. If anyone would like to request it to also be part of the traceplot, it should be done in the arviz repo.
