### ISSUE TITLE
Terms in gelman_rubin are canceling out

### ISSUE THREAD

**Issue by twolodzko** [pymc-devs/pymc#3539]
In [the source code of `gelman_rubin`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/diagnostics.py#L152) we can find the following:

```python
  def rscore(x, num_samples):
    # Calculate between-chain variance
    B = num_samples * np.var(np.mean(x, axis=1), axis=0, ddof=1)
​
    # Calculate within-chain variance
    W = np.mean(np.var(x, axis=1, ddof=1), axis=0)
​
    # Estimate of marginal posterior variance
    Vhat = W * (num_samples - 1) / num_samples + B / num_samples
​
    return np.sqrt(Vhat / W)
```

Notice that variance is first multiplied by `num_samples` and then, when calculating `Vhat`, it is divided by `num_samples`, so basically the function can be simplified to:

```python
  def rscore(x, num_samples):
    # Calculate between-chain variance
    B = np.var(np.mean(x, axis=1), axis=0, ddof=1)
​
    # Calculate within-chain variance
    W = np.mean(np.var(x, axis=1, ddof=1), axis=0)
​
    # Estimate of marginal posterior variance
    Vhat = W * (num_samples - 1) / num_samples + B
​
    return np.sqrt(Vhat / W)
```

**Comment by junpenglao** [comment]
Thanks for reporting, seems there is a same problem in ArviZ as well: https://github.com/arviz-devs/arviz/blob/6dd6f94fe0f268322e4bfde0c9dd54c955b17b64/arviz/stats/diagnostics.py#L622-L641

**Comment by fonnesbeck** [comment]
The formulae are correct. I'd be tempted to leave it as-is for clarity, since an extra couple of scalar multiplications aren't likely to slow things down much. If it is simplified, I would note it in the docstring.

**Comment by twolodzko** [comment]
I didn't propose PR in case it's by design, just wanted to notice you on that.

**Comment by twiecki** [comment]
Thanks for highlighting that!
