### ISSUE TITLE
TypeError when implementing beta.cdf (Scipy)

### ISSUE THREAD

**Issue by jensdebruijn** [pymc-devs/pymc#3541]
Similar to https://github.com/pymc-devs/pymc3/issues/1209, implementing a beta function in the model returns a TypeError (see below). Unfortunately, implementing a solution similar to https://github.com/pymc-devs/pymc3/issues/1209 is not straigtforward because the stander erfc cannot be used.

**Please provide a minimal, self-contained, and reproducible example.**
```
from pymc3 import *
from math import sqrt
import numpy as np
from scipy.stats import norm

from pymc3 import *
from math import sqrt
import numpy as np
from scipy.stats import beta

x_obss = [0.01, 0.02, 0.05, 0.1, 0.22, 0.46, 1.0, 2.15, 4.64, 10.0]
y_obss = [50.0, 51.0, 57.0, 55.0, 63.0, 62.0, 82.0, 94.0, 99.0, 100.0]

with Model() as model:
    alpha = Normal('alpha', mu=70, sd=20)  # What is the building stock?
    # Model error
    eps = HalfNormal('error', sd=0.1)  # Sigma is bound between 0 and 0.2. Sigma should always be strictly positive.
    # Expected value
    mu = beta.cdf(1 / alpha, 2, 2)
    # Data likelihood
    y_obss = Normal('y_obss', mu=mu, sd=eps, observed=y_obss)
    find_MAP() 
```

**Please provide the full traceback.**
```python
File ".\GRADE\curves\bayesian_updating beta.py", line 15, in <module>
mu = norm.cdf((1 / beta) * np.log(x_obss / alpha))
File "C:\Users\default\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1747, in cdf
cond1 = self._open_support_mask(x) & (scale > 0)
File "C:\Users\default\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 877, in _open_support_mask
return (self.a < x) & (x < self.b)
File "C:\Users\default\Anaconda3\lib\site-packages\theano\tensor\var.py", line 91, in __bool__                              "Variables do not support boolean operations."
TypeError: Variables do not support boolean operations.
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.7
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: Windows
* How did you install PyMC3: conda

**Comment by fonnesbeck** [comment]
SciPy's functions won't work here; you would have to have Theano functions for the beta CDF. Unfortunately, there is not an incomplete beta function implemented in Theano, so you'd have to do it by hand.

**Comment by lucianopaz** [comment]
The `pymc3.distribution.dist_math` module provides a theano implementation of the `incomplete_beta` function. You can check out how our `Beta` distribution implements the `logcdf` method to get a better understanding of how it should be used.
