### ISSUE TITLE
How to get chi-squared values / likelihood evaluations from trace? 

### ISSUE THREAD

**Issue by pearsonkyle** [pymc-devs/pymc#3546]
Is it possible to get the likelihood/chi-squared or whatever your minimization metric is for each sample in the trace? Is this something that pymc3 spits out or do I have to compute AFTER the mcmc with each sample in the trace?

**Comment by lucianopaz** [comment]
Hi @pearsonkyle, questions like this should be posted on our [discourse channel](https://discourse.pymc.io/). To answer your question, there is no minimization metric when you call `pm.sample`. HMC has the energy in `trace.get_sampler_stats("energy")`. If you want the model's `logp` instead, you can calculate it like this:

```python
with pm.Model() as model:
    # some model
    trace = pm.trace()
logp = model.logp
values = np.array([logp(point) for point in trace.points()])
```

**Comment by pearsonkyle** [comment]
if possible, I'd like to open this up and add a feature support label. 

It seems that the logp values are re-evaluated from every point in the trace and not actually saved during the sampling itself. This is highly inefficient especially if my model takes e.g. 1 sec to compute and I have 100,000 parameter space evaluations. I don't want to compute my model 100,000 extra times after sampling just to get chi-squared values. 

It's important to have chi-squared/logp values because it helps with the burn-in as opposed to arbitrarily picking a number of points to discard during the 'tuning' phase. Also, it can be very enlightening for determining local solutions and degeneracies that is hard to tell from a scatter plot of points. Not to mention making chi-squared maps, e.g. for investigating the sensitivity of each parameter

**Comment by ColCarroll** [comment]
Can do, @pearsonkyle!

This would probably be easiest to put into `sample_stats`, but I have not looked at how easy that "plumbing" would be (and likely won't be able to get to this myself any time soon). 

Note that [arviz extracts the log likelihood](https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pymc3.py#L54) using the method @lucianopaz outlined above, which might help anyone tackling this.

**Comment by ricardoV94** [comment]
Closing in favor of https://github.com/pymc-devs/pymc/discussions/5395
