### ISSUE TITLE
number of effctive samples 

### ISSUE THREAD

**Issue by jktis** [pymc-devs/pymc#3558]
I had a look at `get_neff` function in `.diagnostics` and I was wondering about the line
```python
acov_t = acov[:, 1] * n_samples / (n_samples - 1.)
```
The autocovariances are computed in `.stats`. The denominator of each autocovariance is the number of elements in the sum. That is `n` for the autocovariance at lag 0, `n -1` at lag 1 and so on. 
Is this refactorizing of the autocovariance at lag 1 intentional? 
The autocovariances at later lags are not refactorized in that way. 
Is it possible that this is just a "copy-paste error" from the previous line which reads
```python
chain_var = acov[:, 0] * n_samples / (n_samples - 1.)
```
This is used to compute the within-variance as defined in Gelman et al. (2004) (2nd edition p. 296). As the within-variance uses a factor of 1/(n-1), instead of 1/n, the refactorizing makes sense here.  

* PyMC3 Version: 3.7
* Python Version: 3.7.3
* Operating system: Windows 10
* How did you install PyMC3: conda

**Comment by junpenglao** [comment]
You are right, I think it should be `acov_t = acov[:, 1]` only.
The version in arviz seems to be correct, but could you please confirm @canyon289?

**Comment by OriolAbril** [comment]
I think using ArviZ directly should have solved this.

**Comment by michaelosthege** [comment]
Closing because diagnostics were deferred to ArviZ.
