### ISSUE TITLE
35x slower sampling with patsy dmatrices compared to formula interface

### ISSUE THREAD

**Issue by m-dz** [pymc-devs/pymc#3565]
## Description of your problem

As title says, in my tiny example below sampling using a `pm.glm.GLM(y=y, x=X, priors=priors)` interface is about 35x slower than with what I think _should_ be an equivalent `pm.glm.GLM.from_formula("y ~ x + C(i)", df, priors=priors)`, please see the screenshot below and the code a bit further down (from a Jupyter notebook).
![image](https://user-images.githubusercontent.com/15376817/61859020-343e5e80-aebf-11e9-82c2-9043807fc9f6.png)

As a side note, values obtained from the "patsy's" trace seem to be rather incorrect, while formula interface gives me correct ones (see screenshots below), I would appreciate if someone could point me to where my mistake is here.

**Please provide a minimal, self-contained, and reproducible example.**
```python
%matplotlib inline
import pymc3 as pm
import pandas as pd
import numpy as np
import patsy as pt
import matplotlib.pyplot as plt


np.random.seed(42)

size = 200
int_1, slo_1 = 1, 3
i_1, i_2, i_3 = 2, -1.5, 0

# Create priors
priors_patsy = {"x": pm.Normal.dist(mu=3, sd=0.01),
                "C(i, Treatment(-1.5))[2.0]": pm.Normal.dist(mu=3.5, sd=0.01)}

priors_formula = {"x": pm.Normal.dist(mu=3, sd=0.01),
                  "C(i)[T.2.0]": pm.Normal.dist(mu=3.5, sd=0.01),}

x = np.linspace(0, 1, size)

# Get y's as y = (a + b * x) + i
y_clean_1 = (int_1 + slo_1 * x) + i_1
y_clean_2 = (int_1 + slo_1 * x) + i_2
y_clean_3 = (int_1 + slo_1 * x) + i_3

# Add some randomness
y_1 = y_clean_1 + np.random.normal(scale=.5, size=size)
y_2 = y_clean_2 + np.random.normal(scale=.5, size=size)
y_3 = y_clean_3 + np.random.normal(scale=.5, size=size)

df = pd.DataFrame({"y": np.concatenate([y_1, y_2, y_3]),
                   "x": np.concatenate([x, x, x]),
                   "i": np.concatenate(
                       [np.repeat(i_1, size),
                        np.repeat(i_2, size),
                        np.repeat(i_3, size)])})

y, X = pt.dmatrices("y ~ x + C(i, Treatment(-1.5))", df, return_type="dataframe")
X = X.drop(columns={"Intercept"}) # Drop as pymc3 seams to add it anyway?


with pm.Model() as model:
    pm.glm.GLM(y=y, x=X, priors=priors_patsy)
    trace_patsy = pm.sample(100, cores=2, tune=1000)

with pm.Model() as model:
    pm.glm.GLM.from_formula("y ~ x + C(i)", df, priors=priors_formula)
    trace_formula = pm.sample(100, cores=2, tune=1000)


plt.figure(figsize=(7, 7))
pm.traceplot(trace_patsy)
plt.tight_layout();

plt.figure(figsize=(7, 7))
pm.traceplot(trace_formula)
plt.tight_layout();
```

**Please provide any additional information below.**
Screenshot from the **incorrect** patsy's traceplot:
![image](https://user-images.githubusercontent.com/15376817/61858830-c5610580-aebe-11e9-9e0e-02ebbef0a5e0.png)

Screenshot from the correct formula's traceplot:
![image](https://user-images.githubusercontent.com/15376817/61858800-b9754380-aebe-11e9-9656-3348f0e52379.png)

## Versions and main components

* PyMC3 Version: pymc3==3.7 (installed from here)
* Theano Version: Theano==1.0.4
* Python Version: Python 3.7.3
* Operating system: Windows 10 Pro N, build 17134
* How did you install PyMC3: (conda/pip) pip from Github

**Comment by junpenglao** [comment]
I dont have time to take a look but just a quick pointer I think it might be something to do with the parameterization. Try compare the predictor matrix under both setting and see if there is a differences.

**Comment by m-dz** [comment]
Thanks, I will have a look at this in the next few days.

**Comment by m-dz** [comment]
@junpenglao , I played a bit with the model object, but couldn't find a way to get the data out of it, could you please point me to a way of accessing it?

**Comment by aseyboldt** [comment]
This seems to be related to the type of `X` and `y`. If they are `np.matrix`, it samples quickly. (ie change to `pm.glm.GLM(y=np.asmatrix(y.values[:, -1]), x=np.asmatrix(X.values), priors=priors_patsy)`. That sure seems like a bug of some kind. Also, we shouldn't be using numpy matrices at all, they are a mess and I think deprecated by now.

**Comment by aseyboldt** [comment]
Ok, I found the problem. Turns out the usage of `np.matrix` really wasn't the problem. We should still remove that, but it seems it really doesn't change things, since we convert the values to theano vars right afterwards, and theano automatically turns the values into ndarrays again.
@m-dz There is a shape problem in your code (or possible bad API in pymc? I haven't made up my mind yet). Your data `y` is a dataframe, so it has shape `(n_observed, 1)`, but it should have shape (n_observed,). I get correct results if I use `pm.glm.GLM(y=y['y'], x=X, priors=priors_patsy)`. It broadcasts your dataset otherwise to `(n_observed, n_observed)`, which is not what you want.
BTW, you can disable the automatic intercept if you pass `intercept=False` to `pm.glm.GLM`.

Maybe we should think about the implications of that shape issue a bit. You might not be the first with that problem, at least a warning would be nice...

**Comment by aseyboldt** [comment]
@m-dz I made a separate issue for this. Please reopen this
```
y, X = pt.dmatrices("y ~ x + C(i, Treatment(-1.5))", df, return_type="dataframe")

with pm.Model() as model:
    pm.glm.GLM(y=y['y'], x=X, priors=priors_patsy, intercept=False)
    trace_patsy = pm.sample(cores=2, tune=1000)
```
doesn't work for you.

**Comment by m-dz** [comment]
Thank you, it's all good now with extracting a `pd.Series` from the y df.

I also tried the `y.values`, but it is returning an `ndarray` of the `(n_observed, 1)` shape, so sampling is again extra slow. It is definitely worth checking the shape and reshaping to `(n, )` if it's `(n, 1)` with a simple warning message, fully agree. I wonder why the `(n, 1)` is automatically broadcasted if it is not a desired outcome, maybe this can be switched off somehow?

Thank you once again!

Edit: A simple `np.reshape(y.values, (-1,))` somewhere in the code would great!
