### ISSUE TITLE
Broadcasting observed vars in pm.glm

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#3569]
If you pass a two dimensional object (dataframe or ndarray) with shape `(n_observed, 1)` into `pm.glm.GLM` as left hand side, it will silently broadcast that to `(n_observed, n_observed)`, which pretty much always isn't what you want. Should we print a warning in those cases? Can we just make it fail with an exception without breaking something?
See also #3565.

**Comment by m-dz** [comment]
As I mentioned in #3565, a simple `np.reshape(y.values, (-1,))` with warning message could do the work. Maybe with a flag that would force the broadcasting in case this is really what someone wants.

**Comment by m-dz** [comment]
I'll PR a branch I created with type checks for `(pd.Series, pd.DataFrame, np.array, np.ndarray)` and reshaping from `(-1,1)` to `(-1,)` if passed as df or ndarray. Currently only supporting `(-1,1)`, but if other dimensions are expected I can loosen the checks a bit.

**Comment by ricardoV94** [comment]
Closing as we have deprecated the GLM module. It is also unclear whether the issue had been solved in the linked PR.
