### ISSUE TITLE
numpy implementation of backward-stick-breaking fails

### ISSUE THREAD

**Issue by katosh** [pymc-devs/pymc#3577]
## Description of the problem

The numpy implementation of backward stick-breaking transformation fails.

Reproduce with:
```python
import pymc3 as pm
import numpy as pn
tf = pm.distributions.transforms.StickBreaking()
tf.backward_val(np.ones(1))
```

Traceback:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-ff6962363b46> in <module>
      2 import numpy as pn
      3 tf = pm.distributions.transforms.StickBreaking()
----> 4 tf.backward_val(np.ones(1))

~/Envs/noteEnv4/lib/python3.6/site-packages/pymc3/distributions/transforms.py in backward_val(self, y_)
    486         k = np.arange(Km1)[(slice(None),) + (None,) * (y.ndim - 1)]
    487         eq_share = nplogit(1.0 / (Km1 + 1 - k).astype(str(y_.dtype)))
--> 488         z = expit(y + eq_share, self.eps)
    489         yl = np.concatenate([z, np.ones(y[:1].shape)])
    490         yu = np.concatenate([np.ones(y[:1].shape), 1 - z])

TypeError: return arrays must be of ArrayType
```

The error comes from `scipy.special.expit` which does not take an argument `eps` in this line:
https://github.com/pymc-devs/pymc3/blob/ebb7488303f518f34e2bd82c3c4c416f5e25cbcc/pymc3/distributions/transforms.py#L488
It might be ok to just remove the argument since it probably does not make a large difference in the desired result.

## Versions and main components

* SciPy Version: 1.2.1
* PyMC3 Version: 3.7
* Theano Version: 1.0.4
* Python Version: 3.7.4
* Operating system: Ubuntu 18.04.2 LTS
* How did you install PyMC3: pip

**Comment by katosh** [comment]
Related issue: #3001

**Comment by twiecki** [comment]
@katosh Thanks for reporting, want to try doing a PR?

**Comment by katosh** [comment]
I hope just removing the argument is alright?

**Comment by katosh** [comment]
There is another PR that gets rid of the `eps` entirely: https://github.com/pymc-devs/pymc3/pull/3620
