### ISSUE TITLE
Mixture of discrete and contiuous distributions

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#3582]
Our samplers won't work correctly (except perhaps ABC) for variables that are neither discrete nor continuous. We should not allow the creation of such variables or we should throw and error when sampling from the model.
```
with pm.Model() as model:
    zero = pm.Constant.dist(DELTA)
    w = pm.Dirichlet('w', a=np.array([1,1]))

    # Should throw an error
    pm.Mixture("log_dist", w=w, comp_dists=[zero, nonzero])

    # TODO is this working correctly?
    pm.Mixture("log_obs", w=w, comp_dists=[zero, nonzero], observed=samples)
```
See
https://discourse.pymc.io/t/sampling-from-a-learned-mixture-of-zeros-and-lognormal/3671

**Comment by junpenglao** [comment]
Yeah in general I dont think the mixture class should support components that have different support - this invalidate the mixture distribution assumption -  but I am not sure what is the best way to enforce this, we can check the domain if the comp_dist are pymc3 distributions, but if it is user supply density function there is no way to know.
