### ISSUE TITLE
Move TransformedVar into global namespace

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#360]
There is a small inconsistency I feel, e.g.:

``` python
with Model() as model:
    sigma, log_sigma = model.TransformedVar('sigma', Exponential.dist(1./.02, testval = .1), logtransform)
    tau = Deterministic('tau', sigma**-2)
```

Makes no sense to me that I can't just call TransformedVar but that it's a method of the model.

**Comment by fonnesbeck** [comment]
Bumping this one. Can `TransformedVar` not be modified to use the context manager, just as other variables can?

**Comment by jsalvatier** [comment]
Yes, and actually it would be great to be able to specify `Normal('a', 0,
1, transform=logtransform)` or something and have it work. I'm less sure
about that.

**Comment by twiecki** [comment]
@jsalvatier agreed. `stan` even takes it a step further and does that automatically for any constrained dist.

**Comment by jsalvatier** [comment]
Done.
