### ISSUE TITLE
Weibull distribution variance is wrong

### ISSUE THREAD

**Issue by cfriedland5** [pymc-devs/pymc#3604]
Parentheses are wrong

Current implementation in pymc3/continuous.py:
```python
        self.variance = (beta**2) * \
        tt.exp(gammaln(1 + 2. / alpha - self.mean**2))
```

Should be:
```python
        self.variance = (
            beta**2 * tt.exp(gammaln(1 + 2. / alpha)) 
            - self.mean**2
        )
```

Additionally you could use `gamma()` instead of `exp(gammaln())` unless there was a deliberate reason for that choice.

Thank you for your attention and effort on this project.

**Comment by junpenglao** [comment]
Thanks for reporting. Feel free to send a pull request ;-)

**Comment by fonnesbeck** [comment]
There is not currently a `gamma()` function implemented. Only the log-gamma function is available (keep in mind they all have to be Theano functions).
