### ISSUE TITLE
why y_est = np.squeeze(SSParr[np.argmin(abs(SSPage - b))]) can not work in pm.Model

### ISSUE THREAD

**Issue by chenymnju** [pymc-devs/pymc#3612]
I was trying to fit a galaxy spectrum (two free parameters: a, b) using pymc3. But it seems to me the following code do not work.

(by the way, in the following code SSParr is an array with shape (177, 3276), SSPage is an array with shape (177,), ydata is an array with shape (3276,))

```python
with pm.Model() as model:
        a = pm.Uniform('a', 0., 1.) #fburst
        b = pm.Uniform('b', 0., 2.) #burst_age        
        sigma = pm.Uniform('sigma', 0., 2.)
        y_est = (1-a) * specarr_old + a * np.squeeze(SSParr[np.argmin(abs(SSPage - b))])
        #y_est = (1-a) * specarr_old + a * specarr_young
        y_obs = pm.Normal('y_obs', mu=y_est, sigma=sigma, observed=ydata)
        trace = pm.sample(4000)
```

 But if I fix b (namely only one free paramter : a), then set 

```python
specarr_young = np.squeeze(SSParr[np.argmin(abs(SSPage - b))])
y_est = (1-a) * specarr_old + a * specarr_young
```
the code works fine. Could someone please tell me why 
```python
np.squeeze(SSParr[np.argmin(abs(SSPage - b))]) 
```
does not work here.

**Comment by fonnesbeck** [comment]
We would appreciate it if you would post general questions to our [Discourse page](https://discourse.pymc.io/). Thanks.
