### ISSUE TITLE
Categorical not working while Multinomial (n=1) does.

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#3622]
## Description of your problem

I found this issue recently in two different examples of models that implement linear softmax regression. One of the examples is from Osvaldo Martin Bayesian Analysis with Python Book ([see issue](https://github.com/aloctavodia/BAP/issues/48)), and the other is mine ([see discourse](https://discourse.pymc.io/t/softmax-regression-with-shared-coefficients-between-classes/3816)).  

**Please provide a minimal, self-contained, and reproducible example:**
```python
iris = sns.load_dataset('iris')
y_s = pd.Categorical(iris['species']).codes
x_n = iris.columns[:-1]
x_s = iris[x_n].values
x_s = (x_s - x_s.mean(axis=0)) / x_s.std(axis=0)

hot_encoding = [[1,0,0],[0,1,0],[0,0,1]]
y_hs = np.array([hot_encoding[y] for y in y_s])

with pm.Model() as model:
    α = pm.Normal('α', mu=0, sd=2, shape=2)
    β = pm.Normal('β', mu=0, sd=2, shape=(4,2))
    α_f = tt.concatenate([[0] ,α])
    β_f = tt.concatenate([np.zeros((4,1)) , β], axis=1)
    μ = pm.Deterministic('μ', α_f + pm.math.dot(x_s, β_f))
    θ = tt.nnet.softmax(μ)
#     yl = pm.Categorical('yl', p=θ, observed=y_s)
    yl = pm.Multinomial('yl', n=1, p=θ, observed=y_hs)
    trace = pm.sample(1000)
```
It works with Multinomial but fails to converge with Categorical.

## Versions and main components

* PyMC3 Version: 3.7 (on Google Colab)
* Theano Version: ...
* Python Version: ...
* Operating system: ...
* How did you install PyMC3: N/A

**Comment by junpenglao** [comment]
could you try to install PyMC3 from master? this is recently fixed.
