### ISSUE TITLE
pm.SMC() failed to run

### ISSUE THREAD

**Issue by xialang2012** [pymc-devs/pymc#3624]
I used this model to get some parameters from an eco-system model. In `CallOutFunc`, it calls the eco-system model and returns results.

```
@as_op(itypes=[tt.dvector], otypes=[tt.dvector, tt.dvector])
def CallOutFunc(x):
    a, b = synS.GetSynthesis(x)
    return a, b

with pm.Model() as basic_model:

    # Priors for unknown model parameters
    beta = pm.TruncatedNormal('beta', sigma=10, lower=uniMin, upper=uniMax, shape=varNum)

    # Expected value of outcome
    mu, observedYGpp = CallOutFunc(beta)    
    
    # Likelihood (sampling distribution) of observations
    y_Obs = pm.Normal('y_Obs', mu=mu, sigma=1, observed=observedYGpp)  

def run():
    with basic_model:
        epohs = 1000
        trace = pm.sample(epohs, chains=500, step=pm.SMC(), cores=1, njobs=1)
        pm.traceplot(trace)
        print(pm.summary(trace))
        pm.save_trace(trace, resourcePath + os.sep + 'result-' + str(epohs) + '.trace')
        #plt.savefig('result-' + str(epohs) + '.trace.png', dpi=300)

if __name__ == '__main__':
    run()    
    plt.show()
```

These codes failed to run, as shown

> __SynthesisSiteSimulation__
> Sample initial stage: ...
> Traceback (most recent call last):
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
>     main(ptvsdArgs)
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
>     run()
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "C:\Miniconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Miniconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Miniconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "c:\Users\xialang2012\Desktop\bgc-data-20\3-par\trymcmc.py", line 336, in <module>
>     run()
>   File "c:\Users\xialang2012\Desktop\bgc-data-20\3-par\trymcmc.py", line 328, in run
>     trace = pm.sample(epohs, chains=500, step=pm.SMC(), cores=1, njobs=1)
>   File "C:\Miniconda3\lib\site-packages\pymc3\sampling.py", line 340, in sample
>     random_seed=random_seed)
>   File "C:\Miniconda3\lib\site-packages\pymc3\step_methods\smc.py", line 155, in sample_smc
>     posterior, var_info = _initial_population(draws, model, variables)
>   File "C:\Miniconda3\lib\site-packages\pymc3\step_methods\smc_utils.py", line 19, in _initial_population
>     init_rnd = pm.sample_prior_predictive(draws, model=model)
>   File "C:\Miniconda3\lib\site-packages\pymc3\sampling.py", line 1322, in sample_prior_predictive
>     values = draw_values([model[name] for name in names], size=samples)
>   File "C:\Miniconda3\lib\site-packages\pymc3\distributions\distribution.py", line 413, in draw_values
>     raise ValueError('Cannot resolve inputs for {}'.format([str(params[j]) for j in to_eval]))
> ValueError: Cannot resolve inputs for ['y_Obs']

But  `trace = pm.sample(epohs, cores=1, njobs=1)`  runs well. Does the SMC sampler not support my code?
The version of PYMC3 is 3.7

**Comment by aloctavodia** [comment]
SMC is not running because `pm.sample_prior_predictive` is failing to sample. I guess this is related to `observedYGpp` being generated by `CallOutFunc(beta)`. Could you try to update to master and see if your model runs. Version on master excludes observed variables when generating a sample from the prior ditribution

**Comment by xialang2012** [comment]
Thank you.
After updating to master, I run the test codes from here https://docs.pymc.io/notebooks/SMC2_gaussians.html
Besides, it seems the smc has been moved out from the step folder in lastest master, the codes in the above link did not work well. So I revised it, `from pymc3.smc import smc ` and `step=smc.sample_smc()`. 

```
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt

from pymc3.smc import smc   # I changed it
import theano.tensor as tt
import shutil

chains = 500
n = 4

mu1 = np.ones(n) * (1. / 2)
mu2 = -mu1

stdev = 0.1
sigma = np.power(stdev, 2) * np.eye(n)
isigma = np.linalg.inv(sigma)
dsigma = np.linalg.det(sigma)

w1 = 0.1
w2 = (1 - w1)

def two_gaussians(x):
    log_like1 = - 0.5 * n * tt.log(2 * np.pi) \
                - 0.5 * tt.log(dsigma) \
                - 0.5 * (x - mu1).T.dot(isigma).dot(x - mu1)
    log_like2 = - 0.5 * n * tt.log(2 * np.pi) \
                - 0.5 * tt.log(dsigma) \
                - 0.5 * (x - mu2).T.dot(isigma).dot(x - mu2)
    return tt.log(w1 * tt.exp(log_like1) + w2 * tt.exp(log_like2))

with pm.Model() as ATMIP_test:
    X = pm.Uniform('X',
                   shape=n,
                   lower=-2. * np.ones_like(mu1),
                   upper=2. * np.ones_like(mu1),
                   testval=-1. * np.ones_like(mu1))
    llk = pm.Potential('llk', two_gaussians(X))

if __name__ == '__main__':
    with ATMIP_test:
        trace = pm.sample(5000, chains=chains, step=smc.sample_smc(), n_jobs=12)     # I changed it
    pm.traceplot(trace)
```
I got some errors

> Sample initial stage: ...
> Stage:   0 Beta: 0.010 Steps:  25
> Stage:   1 Beta: 0.029 Steps:  11
> Stage:   2 Beta: 0.065 Steps:  13
> Stage:   3 Beta: 0.142 Steps:  14
> Stage:   4 Beta: 0.302 Steps:  19
> Stage:   5 Beta: 0.640 Steps:  25
> Stage:   6 Beta: 1.000 Steps:  25
> Traceback (most recent call last):
>   File "C:\Miniconda3\lib\site-packages\pymc3\sampling.py", line 133, in assign_step_methods
>     assigned_vars = assigned_vars.union(set(step.vars))
> AttributeError: 'dict' object has no attribute 'vars'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
>     main(ptvsdArgs)
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
>     run()
>   File "c:\Users\xialang2012\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "C:\Miniconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Miniconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Miniconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "c:\Users\xialang2012\Documents\PythonApplication1\PythonApplication1\bgc-parameters-ana\smc-pm3.py", line 42, in <module>
>     trace = pm.sample(5000, chains=chains, step=smc.sample_smc(), n_jobs=12)
>   File "C:\Miniconda3\lib\site-packages\pymc3\sampling.py", line 378, in sample
>     step = assign_step_methods(model, step, step_kwargs=kwargs)
>   File "C:\Miniconda3\lib\site-packages\pymc3\sampling.py", line 135, in assign_step_methods
>     for method in step.methods:
> AttributeError: 'dict' object has no attribute 'methods'

**Comment by xialang2012** [comment]
@aloctavodia I made a mistake, the correct way to use SMC is like this
`trace = pm.sample_smc()`

I am a freshman here, can I ask a question?

As it mentioned, `pm.sample_smc()` use  `metropolis `as kernel method for the SMC sampler, so what is the difference between the sampler `pymc3.step_methods.metropolis.Metropolis` and `pm.sample_smc(), metropolis `?  Thank you.

Besides, this link should be updated https://docs.pymc.io/notebooks/SMC2_gaussians.html to corresponding with https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/SMC2_gaussians.ipynb

**Comment by aloctavodia** [comment]
Glad it works. Here you will find a description of SMC and thr differences with plain metropolis. https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/SMC2_gaussians.ipynb

Also notice that smc allows you to perform Approximate Bayesian Computation ABC. As explained here https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/SMC-ABC_Lotka-Volterra_example.ipynb (notice this is still experimental).

We are working on improving metropolis within SMC and also on adding more kernels (currently we have `metropolis` and `abc`)
