### ISSUE TITLE
Sequential sampling does not reset iter_count in HMC.

### ISSUE THREAD

**Issue by byblian** [pymc-devs/pymc#3627]
I am following up on [No early tuning in sequential second chain](https://discourse.pymc.io/t/no-early-tuning-in-sequential-second-chain/2852/7)

I believe this is caused due to the following in pymc3/sampling.py:
```
    if not parallel:
        if has_population_samplers:
            _log.info('Population sampling ({} chains)'.format(chains))
            _print_step_hierarchy(step)
            trace = _sample_population(**sample_args, parallelize=cores > 1)
        else:
            _log.info('Sequential sampling ({} chains in 1 job)'.format(chains))
            _print_step_hierarchy(step)
            trace = _sample_many(**sample_args)

```

In _sample_population, it calls _prepare_iter_population() which has code to copy the step methods, even with a comment: "need indepenent samplers for each chain"

But in the no population samplers case, _sample_many simply calls _sample() for each chain, without duplicating the step methods:
```
def _sample_many(draws, chain, chains, start, random_seed, step, **kwargs):
    traces = []
    for i in range(chains):
        trace = _sample(draws=draws, chain=chain + i, start=start[i],
                        step=step, random_seed=random_seed[i], **kwargs)
 ```

**Comment by junpenglao** [comment]
I dont think this is a problem, as you dont need to copy step methods in sequential sampling. The reason we do this copy in population sampling setting is because we need to copy the whole process and pickle it to run on different CPU cores. Maybe @aseyboldt could comment a bit more.

**Comment by byblian** [comment]
But don't the step methods keep state?

You'd be using the state from the previous chain. For example, my issue above (no early tuning) might be due to the following in pymc3/step_methods/hmc/nuts.py:

```
    def _hamiltonian_step(self, start, p0, step_size):
        if self.tune and self.iter_count < 200:
            max_treedepth = self.early_max_treedepth
        else:
            max_treedepth = self.max_treedepth
```

In other words, since "self.iter_count" was already incremented by the previous chain to beyond 200, the early tree depth is not used.

**Comment by junpenglao** [comment]
> But don't the step methods keep state?

No it doesnt, they are resetted when `_iter_sample` is called in `_sample`.

I am firmly believe that the problem of your model is https://discourse.pymc.io/t/no-early-tuning-in-sequential-second-chain/2852/7?u=junpenglao, so I am closing this for now. But feel free to continue the discussion here or on discourse.

**Comment by byblian** [comment]
I don't see in the code where the step is being reset and as you can see below, a test appears to confirm that the step is not being reset.

To verify this, I added the following line in _hamiltonian_step() in nuts.py:
```
print(max_treedepth, self.iter_count)
```

I then ran a version of the example model provided in https://docs.pymc.io/history.html
You can look at the notebook: [SequentialSamplingDoesNotCopyStepMethod.zip](https://github.com/pymc-devs/pymc3/files/3617263/SequentialSamplingDoesNotCopyStepMethod.zip)
(I ran this on Colab, and after the !ldconfig cell, I restarted the runtime)

As you can see from the output:
```
Only 300 samples in chain.
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [beta, alpha]
Sampling chain 0, 0 divergences:   7%|▋         | 56/800 [00:00<05:27,  2.27it/s]

8 0
8 1
...
8 199
10 200
...
10 787
10 788
10 

Sampling chain 0, 0 divergences: 100%|██████████| 800/800 [00:02<00:00, 379.07it/s]
Sampling chain 1, 0 divergences:   6%|▋         | 50/800 [00:00<00:01, 492.05it/s]

789
10 790
...
10 799
10 800
10 801
```

So the iter_count is never reset and the early sampling tree depth does not apply to the second chain.

**Comment by junpenglao** [comment]
Oh right I see what you meant. Yes you are right the iter_count is not reseted.
