### ISSUE TITLE
Unable to install/upgrade pymc3 for python3

### ISSUE THREAD

**Issue by snazzybloke** [pymc-devs/pymc#3633]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by snazzybloke** [comment]
pip3 install -U pymc3
Collecting pymc3
  Using cached https://files.pythonhosted.org/packages/42/c2/86e8be42b99d64932fa12611b502882a5f4d834b6d1d126bf3f956ad6428/pymc3-3.7-py3-none-any.whl
ERROR: Package 'pymc3' requires a different Python: 3.5.2 not in '>=3.5.4'

**Comment by fonnesbeck** [comment]
You need to have a Python version 3.5.4 or higher. You are attempting to install under 3.5.2.
