### ISSUE TITLE
Source code for pymc3 function doc does not use pymc3 function

### ISSUE THREAD

**Issue by vlbrown** [pymc-devs/pymc#3636]
## Description of your problem

Refer to [pymc3.readthedocs.io: pymc3.distributions.continuous.Exponential](https://pymc3.readthedocs.io/en/latest/api/distributions/continuous.html#pymc3.distributions.continuous.Exponential) or [docs.pymc.io: pymc3.distributions.continuous.Exponential](https://docs.pymc.io/api/distributions/continuous.html#pymc3.distributions.continuous.Exponential)

When I download and view the "[Source code](https://pymc3.readthedocs.io/en/latest/api/distributions/continuous-4.py)", it does not reference the documented function.

**Please provide a minimal, self-contained, and reproducible example.**
```
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st
x = np.linspace(0.0, 5.0, 1000)
fig, ax = plt.subplots()
f = lambda lam : st.expon.pdf(x, scale=1.0/lam)
plot_pdf = lambda lam : ax.plot(x, f(lam), label=r'$\lambda$={0}'.format(lam))
plot_pdf(0.5)
plot_pdf(1.0)
plot_pdf(1.5)
plt.legend(loc='upper right', frameon=False)
ax.set(xlim=[0,5], ylim=[0,1.6], xlabel='x', ylabel='f(x)')
plt.show()
```

**Please provide any additional information below.**
I expected to see a call to `pm.Exponential` not `st.expon.pdf`.

## Versions and main components

* PyMC3 Version: n/a
* Theano Version: n/a
* Python Version: n/a
* Operating system: n/a
* How did you install PyMC3: (conda)

**Comment by vlbrown** [comment]
Same issue for [Gamma](https://docs.pymc.io/api/distributions/continuous.html#pymc3.distributions.continuous.Gamma)

**Comment by fonnesbeck** [comment]
The source code that you cite does not contain any PyMC3 code. Where did you get that snippet, and how does it relate to PyMC3?

**Comment by fonnesbeck** [comment]
OK, I think I see what you are reporting; The code that generates the figures is not PyMC3 code. True enough. The objective is to show the distribution as a reference, more than to show off PyMC3. We would happily accept a PR if you feel inclined to swap it out.

**Comment by vlbrown** [comment]
> On Sep 30, 2019, at 18:00 , Chris Fonnesbeck <notifications@github.com> wrote:
> 
> OK, I think I see what you are reporting; The code that generates the figures is not PyMC3 code. True enough. The objective is to show the distribution as a reference, more than to show of PyMC3. We would happily accept a PR if you feel inclined to swap it out.
> 

I was hoping for a lot more example code.

Sadly, I am so low on the learning curve that I'm very much not the right person to do the PR / update.


-- Vicki

Vicki Brown
cfcl.com/vlb

**Comment by fonnesbeck** [comment]
Right, I understand. That code in particular was just to generate plots of various distributions, rather than to teach PyMC. I recommend checking out our tutorials for more extensive learning material. 

https://docs.pymc.io/nb_tutorials/index.html

Digging into the source code is probably not the best place to start.

Also, if you search on YouTube, several developers have given tutorials that have been recorded. Those can also be good for getting started.
