### ISSUE TITLE
 signature for random callable in class DensityDist is wrong

### ISSUE THREAD

**Issue by yusri-dh** [pymc-devs/pymc#3637]
https://github.com/pymc-devs/pymc3/blob/5746788874b7e940a2b0f020f378e5d08fc64a8f/pymc3/distributions/distribution.py#L234-L243

The signature for random callable is wrong, it should read random(point=None, size=None, **kwargs)

**Comment by junpenglao** [comment]
Follow up of https://discourse.pymc.io/t/example-of-sampling-from-densitydist-in-pymc3-source-code-does-not-work/3911/
