### ISSUE TITLE
Marginal likelihood / Bayes factor calculation of GLM (logistic regression)

### ISSUE THREAD

**Issue by adam-rysanek** [pymc-devs/pymc#3642]
I would like to estimate the Bayes factor for a logistic regression problem, but as I understand it, it's not possible to estimate marginal likelihood of a GLM (at least using a simple function as per https://docs.pymc.io/notebooks/Bayes_factor.html), specifically using ```.marginal_likelihood ```.

Is it correct to say that the only way to currently estimate marginal likelihood / Bayes factor is using models that are described explicitly as opposed to via a GLM?
The difference between 'explicit' and GLM being described here: https://docs.pymc.io/notebooks/GLM-model-selection.html

Many thanks,
Adam

**Comment by aloctavodia** [comment]
Hi @adam-rysanek, you can define and run a Generalized Linear Model (GLM) using either the "explicit" syntax or the one available trough the GLM module. One restriction that is valid for both ways of specifying the model is that you can not use a "Flat" prior, so if the GLM module  is using as default a Flat prior you should change it to a proper prior.

**Comment by adam-rysanek** [comment]
@aloctavodia Thanks for your response. Apologies that my question wasn't clear. The main question was if there is a way to easily estimate the marginal likelihood when using the GLM module?

**Comment by aloctavodia** [comment]
Don't worry it was clear, maybe my answer wasn't :-) You can estimate the marginal likelihood using the SMC sampler and the GLM module, as long as you avoid using a `pm.Flat` prior
.
