### ISSUE TITLE
Shared vars dirty values in Deterministic RVs

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#3643]
sample_posterior_predictive is susceptible to "bad" ordering of var_names.
The problem arises only when using theano.shared vars for observed RVs. 
It seems that when sample_posterior_predictive is given var_names in an order in which a Deterministic RV is placed before the RV(s) it is based on, the samples will contain wrong values for that deterministic variable.
Namely - the values for the deterministic rv in the ppc trace will be values based on the "original" theano.shared values.

One possible fix is reordering var_names inside sample_posterior_predictive to be consistent with
```python
free_RVs + observed_RVs + deterministics
```
As far as I tested this ordering works, but this might be just a workaround hiding a deeper problem. Not sure.

If the reordering solution is the right way to go, better to topologically order the rvs, though I didn't find a way in the API to retrieve their dependencies.

See reproduction below.

```python
np.random.seed(123)
        obs_a = theano.shared(np.array([10., 20., 30.]))

        with pm.Model() as m:
            pm.Normal('mu', 3, 5)
            a = pm.Normal('a', 20, 10, observed=obs_a)
            pm.Deterministic('b', a * 2)

            trace = pm.sample(10)

        # var_names = ['a', 'b'] # GOOD ORDERING
        var_names = ['b', 'a'] # BAD ORDERING
        ppc = pm.sample_posterior_predictive(trace, model=m, var_names=var_names)
        sa = ppc['a'][0, 0]
        sb = ppc['b'][0, 0]
        if sa*2 != sb:
            print(f'a = {sa}')
            print(f'b = {sb}')
            raise ValueError('wrong')
        
        print('OK')
```

* PyMC3 Version: 3.7
* Theano Version: 1.0.4
* Python Version: 3.7.3
* Operating system: macOS High Sierra
* How did you install PyMC3: pip

**Comment by lucianopaz** [comment]
Thanks for reporting @uri-datorama. This highlights a problem in `draw_values`. In particular, in how the output from `pymc3.model.get_named_nodes_and_relations` is handled. I'll work on a fix later today.
