### ISSUE TITLE
Complex values in custom likelihood Function

### ISSUE THREAD

**Issue by ramav87** [pymc-devs/pymc#3653]
Hi,

I am trying to implement a custom likelihood function with pymc3. It's trivial, but I can't seem to get it to work. The basic hickup is that when I try to pass a complex value to my custom function,

`logpvar = pm.DensityDist("logpvar", logp_func, observed={'mu':mu, 'ydata':ydata})`

I get the error that this is not allowed (TypeError: Casting from complex to real is ambiguous: consider real(), imag(), angle() or abs()). Is there a workaround? My apologies, I am new to this space.

**Comment by lucianopaz** [comment]
This kind of question should be posted on the [discourse channel](https://discourse.pymc.io/) so I'll close the issue.

To help you fix the problem we need some more information on the `logp_func` that you are using. The only constraint it has, is that it must return a real number. Maybe your function computes everything with complex numbers, and the final value's imaginary part is zero except for rounding errors. If that were the case, you could take the [real part](http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor._tensor_py_operators.real) of the result and return it.
