### ISSUE TITLE
Prior predictive sample contains anomalous entries for fixed Deterministics

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3665]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

I have a model (attached) that has a `Deterministic` as a function of a set of predictors (fixed model inputs).  When I sample from this distribution with `sample_prior_predictive`, I get an entry for this variable in the trace, but only one, instead of *n* for a sample with *n* draws.

I noticed this because later, when I try to process this trace with arviz, arviz errors out in `from_pymc3`, because it expects an array of shape `(n, k)` and gets an array of`(1, k)` instead.

### minimal, self-contained, and reproducible example

```python
from scipy.stats import uniform

import pymc3 as pm
import arviz as az


SEED = 123

with pm.Model() as model:
    pred = pm.Data('predictor', uniform(0, 20).rvs(20))
    zs = pm.Deterministic('z', pred - pred.mean() / (pred.max() - pred.min()))
    obs = pm.Normal('o', mu=zs, shape=20)

prior_trace = pm.sample_prior_predictive(model=model)

for var in ['z', 'o']:
    print('%s shape in prior predictive trace is %s'%(var, prior_trace[var].shape))

# this call causes an error in arviz

id = az.from_pymc3(None, prior=prior_trace, model=model,
                   dims={'predictor': ['subjects'], 'z': ['subjects'], 'obs': ['subjects']},
                   coords={'subjects': range(0, 20)})
```
## What I would expect

Either that variables like `z` would not appear in the trace, or that they would be replicated.

## Versions and main components

* PyMC3 Version: 53e4966240097f53634c970d72df51c94ef93297
* Theano Version: 1.0.4
* Python Version: 3.6.8
* Operating system: Mac
* How did you install PyMC3: pip -e from git

**Comment by ricardoV94** [comment]
This snippet is working fine in `V4`. The variable `z` is properly replicated.

```
z shape in prior predictive trace is (500, 20)
o shape in prior predictive trace is (500, 20)
```
