### ISSUE TITLE
var_names and sigma variable in normal distribution errors.

### ISSUE THREAD

**Issue by edhearn84** [pymc-devs/pymc#3675]
When I use the var_names command with traceplots or forestplots, there is a kwarg error that pops up specifying an unidentified parameter. This also happens when I specify the sigma parameter of a Normal distribution (although, the kwarg "sd" works).

**Comment by lucianopaz** [comment]
Could you add the code that produced your error along with the pymc3 version that you are using?

**Comment by edhearn84** [comment]
After reading the new release updates for Version 3.7, these issues are all addressed by updating to that version. However, I am having trouble updating to the newest version. How do I do this through conda and/or Jupyter Notebooks?

**Comment by fonnesbeck** [comment]
You can run `conda update pymc3` (add a -y flag if you are running it from inside a notebook), or `pip install -U pymc3`.
