### ISSUE TITLE
draw_values not generating samples from joint distribution with HalfNormal or Bound(Normal)

### ISSUE THREAD

**Issue by adrn** [pymc-devs/pymc#3685]
## Description of your problem

`draw_values()` does not draw from the joint distribution for `HalfNormal`, or `Bound`'ed `Normal` distributions.

My understanding of #3273 is that `draw_values()` should now properly generate samples in joint distributions instead of the individual marginals. This works for, e.g., `Normal`, but doesn't seem to work for a `Bound(Normal)`, or for `HalfNormal`, as demonstrated in this notebook: https://gist.github.com/f4269724588b4bfbe4ae597cf5c6d39a

## Versions and main components

* PyMC3 Version: 3.7
* Theano Version: 1.0.7
* Python Version: 3.7.3
* Operating system: macOS
* How did you install PyMC3: pip

**Comment by ColCarroll** [comment]
I'll dig in more, but just want to verify I can reproduce. Also, problem persists with `sample_prior_predictive`, but `sample` works fine still (thank goodness).

```python
with pm.Model() as model:
    P = pm.Uniform('P', 1, 100)
    sigma_e = pm.Deterministic('sigma_e', 1/P)
    e = pm.HalfNormal('e', sigma=sigma_e)
    prior = pm.sample_prior_predictive(100_000)
    trace = pm.sample(25_000)

az.plot_joint(prior, var_names=['P', 'e'], joint_kwargs=dict(s=1));
```
![image](https://user-images.githubusercontent.com/2295568/69111872-dd036180-0a4c-11ea-9927-5a9c9028b72f.png)

```python
az.plot_joint(trace, var_names=['P', 'e'], joint_kwargs=dict(s=1));
```
![image](https://user-images.githubusercontent.com/2295568/69111903-f1475e80-0a4c-11ea-8314-ae31e36f8fe5.png)
