### ISSUE TITLE
Can pymc be applied on an optimization problem ?

### ISSUE THREAD

**Issue by weiczhu** [pymc-devs/pymc#3691]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
For example, if there is an objective
profit = w0 * x0 + w1 * x1

Can we use pymc to find the optimal w0, and w1 to give the maximum profit ?
Thanks

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by CloudChaoszero** [comment]
I may help out; I'll respond soon.

**Comment by CloudChaoszero** [comment]
Hello @weiczhu ,

Hope you are well! From looking at the documentation, maybe a recommendation for using the DifferentialEquation method in the `pymc3.ode import DifferentialEquation
` portion of the API, [seen here](https://docs.pymc.io/notebooks/ODE_API_introduction.html?highlight=differential). 


The example I feel is most relevant in this scenario is the ["A Differential Equation for Freefall"](https://docs.pymc.io/notebooks/ODE_API_introduction.html?highlight=differential#A-Differential-Equation-For-Freefall), but re-configuring or working with the method's parameters to solve your use case.

> Alternatively, I recommend looking at non-bayesian ML tools/APIs to help out with this topic as well. For example, I was thinking about a Linear Regression model from Sklearn to help you out. :) 
> https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

For additional questions related to this, please feel free to post this to the PyMC3 discourse channel https://discourse.pymc.io

**Comment by eigenfoo** [comment]
Thanks for your question @weiczhu. We try to keep the GitHub issues for development issues, instead of user support for PyMC3 or modelling questions. For those, please check out our Discourse Forums: https://discourse.pymc.io/

Closing now, but feel free to continue the discussion on the forums!
