### ISSUE TITLE
Still much memory is occupied after running and terminating SMC

### ISSUE THREAD

**Issue by aakhmetz** [pymc-devs/pymc#3697]
After running sequential Monte-Carlo, I still have some subprocess occupying the memory, which I believe should not be.
```python
@as_op(itypes=[tt.lscalar, tt.dscalar, tt.dscalar, tt.lscalar], otypes=[tt.dmatrix])
def get_values(nconvolutions, μ, σ, length):
    ....
    return res

n_chains = 25000

ntimepoints = np.dtype('int64').type((max(Df['t'])-min(Df['t'])+1)+42)
incidence, _ = np.histogram(Df['t']-min(Df['t']), bins=ntimepoints, range=(0, ntimepoints+1))

maxngenerations = np.dtype('int64').type(5)
with pm.Model() as model_multigeneration:
    μ = pm.Normal('μ', 3, sd=10, testval=3.0838)
    σ = pm.Uniform('σ',0, 10, testval=0.291159)
    pm.Deterministic('gtmean', tt.exp(μ+σ**2/2))
    pm.Deterministic('gtsd', tt.sqrt((tt.exp(σ**2)-1)*tt.exp(2*μ+σ**2)))
    
    Δ = pm.Data('Δ', df_pairs['Δ'].values)
    SI_period = pm.Lognormal('SI_period', μ, σ, observed = Δ+0.5)

    N = pm.HalfNormal('N',sd=10,testval=30)
    gts = get_values(theano.shared(maxngenerations), μ, σ, theano.shared(ntimepoints))
    R = pm.HalfNormal('R', 1, shape=maxngenerations-1, testval=1.)

    λ = N*(gts[0,:] + pm.math.dot(R,gts[1:,:]))
    pm.Poisson('likelihood', λ[1:]+1e-6, observed = incidence[1:])
    
    trace = pm.sample(1000, progressbar=False, #start=startsmc, 
                      chains=n_chains, step=pm.SMC(), 
                      cores=48, random_seed=123)
```

Then for example,  I still have numerious ZMQbg/1 process in my ```Processes``` with 0% CPU usage and memory occupation of 818.1MiB each. Were they not supposed to be terminated?

![Screenshot from 2019-11-29 14-06-42](https://user-images.githubusercontent.com/2173206/69849339-c6b49b80-12bf-11ea-8f81-54840d2aa129.png)

I have had this problem on my Ubuntu and ArchLinux systems. The versions of PyMC3 and theano are the latest from github. I used conda to install other packages.

**Comment by aloctavodia** [comment]
Hi @aakhmetz 
Could yo try with the version on master? This should be fixed there.

You should run it using something like
`pm.sample_smc(1000, cores=48, parallel=True, random_seed=123)`

You could try also with `parallel=False`.

This will run 1000 chains and you will get 1000 final samples.

**Comment by aakhmetz** [comment]
Dear @aloctavodia, I did that and it looks like my problem was resolved. 

Could you advice what the number of chains is needed for final sampling?  Because in my mind, ```n_chains``` is a number of particles, so the number of particles should large (like e.g. 10,000). Thank you in advance

**Comment by aakhmetz** [comment]
@aloctavodia sorry for disturbing, I found the info https://github.com/pymc-devs/pymc3/blob/master/pymc3/smc/sample_smc.py

**Comment by aakhmetz** [comment]
Just noticing a bit related thing. Since I work with Jupyter, and I interrupt the kernel, the processes still remain in the memory. I assume that it is just difficult to manage and terminate them properly
