### ISSUE TITLE
DEMetropolis: tune lambda instead of epsilon

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3720]
Our `DEMetropolis` tunes the scaling factor of the noise distribution:
https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/metropolis.py#L572-L581

My feeling these days is that tuning the noise distribution is a bit pointless after the first few iterations & could obscure the warmup, or even lead to slingshots if it overshoots.

Instead, we could tune `lambda` parameter. It's optimal value depends on the (dimensionality of the) target density ([ter Braak (2006)](https://doi.org/10.1007/s11222-006-8769-1)), so it should be a good candidate for tuning.
This approach is described in [Nelson _et al._ (2013)](https://arxiv.org/abs/1311.5229), section 4.1.2.

**Comment by michaelosthege** [comment]
On my test problem (50-dim MvNormal) the tuning converges to the same rule of thumb that was used before (2.38 / sqrt(2*ndim)).
Here the progression of the tuned parameter (3000 tuning its)
![image](https://user-images.githubusercontent.com/5894642/71010428-17176000-20ec-11ea-9479-0bbc436b0380.png)

I also see no significant difference in the effective sample size...

I'm thinking to ditch tuning of scaling/lambda alltogether. What do you think?
cc @junpenglao

**Comment by junpenglao** [comment]
Could you try on a ODE example?

**Comment by michaelosthege** [comment]
> Could you try on a ODE example?

I tried with Demetris benchmark example, but it was very slow & inefficient (--> noisy) while having just 2 dimensions.

**Comment by junpenglao** [comment]
Do you mean slower than no tuning?

**Comment by michaelosthege** [comment]
> Do you mean slower than no tuning?

No the sampling was just slow/inefficient because it's an ODE. Also `DifferentialEquation` computes sensitivities that `DEMetropolis` doesn't use.
So I'd have to wait very long for the benchmark results to give a significant answer.

I could also implement a kwarg like `DEMetropolis(tune_par=x)` with `x in {None, 'epsilon', 'lambda'}` where `None` is the default because tuning `epsilon` is a bit pointless & tuning `lambda` is not necessarily better than `lambda = 2.38 / sqrt(2*ndim)`.

Maybe the result of my testing is simply that `DEMetropolis` doesn't need hyperparameter tuning. (Needs warmup/burnin though.)

**Comment by junpenglao** [comment]
I see. Thanks! Feel free to close.
