### ISSUE TITLE
Small typo in the Bayes factor notebook.

### ISSUE THREAD

**Issue by p16i** [pymc-devs/pymc#3726]
Hi,

I found a small typo in this notebook. I guess it should be `It's` or `It is`. 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1214890/70795226-9ed53580-1d9f-11ea-833d-de8aabb35816.png">

https://docs.pymc.io/notebooks/Bayes_factor.html

**Comment by aloctavodia** [comment]
Hi @heytitle, thanks for reporting this issue. Do you want to do a pull request to fix this typo?

**Comment by p16i** [comment]
actually, I've just also found another issue on https://docs.pymc.io/notebooks/SMC2_gaussians.html.

Maybe we can combine these issues into the same PR. 
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1214890/70796763-5ddf2000-1da3-11ea-90c7-0517f3ad31e4.png">

 @aloctavodia yeah, I might have time to do it during this (or next) weekend.

**Comment by aloctavodia** [comment]
great, thanks!

**Comment by ac-optimus** [comment]
hi @aloctavodia & @heytitle, If no one is working on this can I PR this solving these two issues?

**Comment by aloctavodia** [comment]
Sounds good to me, but let's wait a little bit for @heytitle answer

**Comment by ac-optimus** [comment]
ya sure!

**Comment by p16i** [comment]
hi @ac-optimus @aloctavodia!

sorry for my late reply. @ac-optimus, feel free to take over the issue.

**Comment by ac-optimus** [comment]
okay sure, thanks!
