### ISSUE TITLE
Remove `trajectory.py`?

### ISSUE THREAD

**Issue by eigenfoo** [pymc-devs/pymc#3729]
I'm beginning to work towards isolating the HMC/NUTS implementation into a separate library, and I've noticed that [`trajectory.py`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/hmc/trajectory.py) is not really used at all, nor are its functions imported by any other module.

According to [the developer guide](https://github.com/pymc-devs/pymc3/blob/a460468468081db708ba10b928e6fcfa1789ef2c/docs/source/developer_guide.rst#dynamic-hmc), its an implementation of dynamic HMC purely in Theano, but isn't used. Should we remove it, or should we keep it for posterity? If so, I can submit a PR to document that in the code.

cc @junpenglao

**Comment by junpenglao** [comment]
Yeah it's there more for historical reason. I think we can remove it, and if we decide to implemented a theano based NUTS we can then bring it back.
