### ISSUE TITLE
Bayes factor example does not execute

### ISSUE THREAD

**Issue by elephantmipt** [pymc-devs/pymc#3742]
I'm trying to run example `Bayes_factor.ipynb` from repository. But in the cell
```
BF_smc = np.exp(models[1].marginal_log_likelihood - models[0].marginal_log_likelihood)
print(round(BF_smc))
```
I get an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-b837350ebbf3> in <module>
----> 1 BF_smc = np.exp(models[1].marginal_log_likelihood - models[0].marginal_log_likelihood)
      2 print(round(BF_smc))

AttributeError: 'Model' object has no attribute 'marginal_log_likelihood'
```

Well, I saw similar result in issue #3282  but it was with PyMC3 version 3.6.  Am I missing something or there is still no attribute with marginal likelihood?
## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.3
* Operating system: Mac Os 10.15
* How did you install PyMC3: pip

**Comment by aloctavodia** [comment]
Sorry for the confusion, the version of PyMC3 on master (unreleased) computes the marginal likelihood in the log scale as shown in the Bayes factor notebook example. For the version 3.8 please use:

`models[1].marginal_likelihood / models[0].marginal_likelihood`

**Comment by elephantmipt** [comment]
Thank you for the quick reply! This solution works for me.
