### ISSUE TITLE
Sampling using GPU: [GLM: Hierarchical Linear Regression]

### ISSUE THREAD

**Issue by prgrmmraben** [pymc-devs/pymc#3745]
I am trying to apply Hierarchical Linear Regression on my case following https://docs.pymc.io/notebooks/multilevel_modeling.html

I do not know where could GPU intervene, probably sampling ? Any way, running on my data with 2,2 million entry and it is taking 2 hours for only 20%

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (8 chains in 8 jobs)
NUTS: [sd, XXXXx, YYYYYY, WWWWW, HHHHHH, Intercept, grp_sd, grp_mean]
Sampling 8 chains, 175 divergences:  34%|███▍      | 4067/12000 [39:10<1:54:22,  1.16draws/s]

ps: I have Nvidia Cuda installed and working for Tensorflow, Keras ...

**Comment by fonnesbeck** [comment]
Please post usage questions to [Discourse](discourse.pymc.io).
