### ISSUE TITLE
Try to free Memory after a memory exception

### ISSUE THREAD

**Issue by prgrmmraben** [pymc-devs/pymc#3746]
Running such sample, 
```
with Model() as model:
    lm = glm.LinearComponent.from_formula('y ~ x', data)
    sigma = Uniform('sigma', 0, 20)
    y_obs = Normal('y_obs', mu=lm.y_est, sigma=sigma, observed=y)
    trace = sample(2000, cores=2)
```

but with more variables and entries ended with an exception: Memory
After I run gc.collect() which returned 125551 as the number of unreachable objects which seems to be a lot (I cannot estimate in memory)

**Comment by ricardoV94** [comment]
Closing this as low priority for the time being.
