### ISSUE TITLE
`test_quadpotential.py` Should be added to test suite

### ISSUE THREAD

**Issue by eigenfoo** [pymc-devs/pymc#3748]
Discovered this while isolating NUTS into its own library.

In our [`.travis.yml`](https://github.com/pymc-devs/pymc3/blob/master/.travis.yml), it appears that we don't run the tests in [`test_quadpotential.py`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_quadpotential.py). We should add this to the test runs.

**Comment by rushabh-v** [comment]
Hello @eigenfoo  I have opened a PR that closes this issue. Can you take a look, please? see #3774
