### ISSUE TITLE
Fatsprogress import

### ISSUE THREAD

**Issue by ahartikainen** [pymc-devs/pymc#3749]
## Description of your problem

fastprogress 0.2.0 has new location for `progress_bar`

**Please provide a minimal, self-contained, and reproducible example.**

`from fastprogress import progress_bar` --> `from fastprogress.fastprogress import progress_bar`

**Please provide the full traceback.**
```
from fastprogress import progress_bar
ImportError: cannot import name 'progress_bar'
```

**Comment by michaelosthege** [comment]
... and that's why you don't release on christmas...
