### ISSUE TITLE
Add reasonable timeout for HMC/NUTS

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#375]
I've run into situations where NUTS will never initialize itself for sampling, even for a reasonably small model, and end up running all night without any samples being drawn.  The model in https://github.com/fonnesbeck/autism_screening is one example of this. We need to add a mechanism for giving up if these sorts of conditions arise.

**Comment by aloctavodia** [comment]
I guess this is not longer a general issue. At least your model now runs smoothly.
