### ISSUE TITLE
small discrepancy between `pm.quantiles` and `np.quantile` when chains are large and numerous

### ISSUE THREAD

**Issue by bersavosh** [pymc-devs/pymc#3761]
I noticed a small discrepancy between `pm.quantiles` and `np.quantile` when chains are large and numerous. I presume this stems from something like a round-off issue and it is not intrinsically significant. However, I thought to bring it up as it can potentially impact when dealing with parameters which their actual value and sampling interval are on different scales.

Example:
```python

import sys
import numpy as np
import pymc3 as pm

# Package versions:
print('Running on:')
print(f'\tPython:\t\t{sys.version[:5]}')
print('\tNumpy\t\t{}'.format(np.__version__))
print('\tPyMC3\t\t{}'.format(pm.__version__))

with pm.Model() as model:
    x = pm.Normal('x',mu=2,sd=1)
    sample = pm.sample(10000,tune=1000,chains=12)

np_q = np.quantile(sample.get_values('x'),0.5)
pm_q = pm.quantiles(sample.get_values('x'), [50])[50]
print(f'Numpy: {np_q}, PyMC: {pm_q}, Difference = {((np_q-pm_q)/np_q)*100} %')
```

Output:
```
Running on:
	Python:		3.6.9
	Numpy		1.17.4
	PyMC3		3.6

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (12 chains in 4 jobs)
NUTS: [x]
Sampling 12 chains: 100%|██████████| 132000/132000 [00:11<00:00, 11820.76draws/s]
The acceptance probability does not match the target. It is 0.8812625683723161, but should be close to 0.8. Try to increase the number of tuning steps.

Numpy: 1.9941481106459507, PyMC: 1.9941525904109327, Difference = -0.0002246455495539025 %

```

Thanks!

**Comment by michaelosthege** [comment]
Looks like `quantiles` was removed at some point. Not mentioned in our changelog though.
This is the implementation on v3.6:

https://github.com/pymc-devs/pymc3/blob/081e7f4a55ce45ef50a03f8062611051d9c00ce8/pymc3/stats.py#L803-L837

**Comment by aloctavodia** [comment]
From 3.8 ArviZ is a requirement, and handles plotting, diagnostics, and statistical checks. That's why quantiles was removed.
