### ISSUE TITLE
 sample_prior_predictive fails with Gamma. ValueError: Domain error in arguments.

### ISSUE THREAD

**Issue by jonsedar** [pymc-devs/pymc#3764]
Hi gang, 

I get an error trying to `pm.sample_prior_predictive` for a `pm.Gamma` that is a dependent observed RV: it seems to be shape related. 

Note that `pm.sample_prior_predictive` works correctly for a "non-dependent" prior `pm.Gamma`, and it works for some other dependent observed RVs e.g. a `pm.Normal`

I've jotted a min reproducible example, with package and OS info in this gist: https://gist.github.com/jonsedar/eb886fa8a69e469e6a1711e6be002003

I think I've been careful with the shapes... Do you have any ideas? Thanks!

**Comment by ColCarroll** [comment]
Thanks for the reproducible example, made this a ton faster!

`alpha` needs to be positive. 

Something like this works, even if it probably is not what you are after:

```python
n_obs = 100
y = np.random.randint(low=0, high=2, size=n_obs)
x = np.random.randint(low=0, high=10, size=n_obs)

with pm.Model() as mdl:
   
    tmx_ex = pm.Data('tmx_ex', x)                          # (n, )
    tmx_en = pm.Data('tmx_en', y)                          # (n, )
    n = tmx_ex.eval().shape[0]
   
    # state prior on linear coef
    coef = pm.Normal('coef', mu=0, sigma=3)                # (1, )
      
    # dispersion psi
    psi = pm.Uniform('psi', lower=0.1, upper=5)            # (1, )
    alpha = pm.Deterministic('alpha', tt.dot(tmx_ex, coef)/psi)
    
    alpha_prime = tt.switch(alpha > 0, alpha, 1)
    # likelihood as Gamma
    yhat = pm.Gamma('yhat', alpha=alpha_prime,
                          beta=1/psi, 
                          shape=(n,), observed=tmx_en)     # (n, )
```

**Comment by jonsedar** [comment]
A very rapid response sir!

Thanks for the switch, that's a good idea... In the meantime I realised my stupidity on the alpha and set the prior to always turn out positive but I still get the error... I've update the gist to reflect this - any ideas?

**Comment by ColCarroll** [comment]
I'm pretty sure the inequality is strict, and `tmx_ex` is still 0 sometimes, so `alpha` is still zero in the updated gist.

**Comment by jonsedar** [comment]
You're right... alpha in (0, inf)

Will just try a couple more things. Learning by failing
