### ISSUE TITLE
Saving and loading trace does not restore sampler stats

### ISSUE THREAD

**Issue by rpgoldman** [pymc-devs/pymc#3772]
## Description of your problem

I was reading in a model trace in order to compute WAIC with Arviz.  After loading the trace, `trace.stat_names` was `set()`.  Here's an example:

![image](https://user-images.githubusercontent.com/3274/72656512-46c2bd80-3961-11ea-8741-84a06708f36d.png)

What's especially disappointing is that when I look at the `metadata.json` file in one of the chain subdirectories of the trace directory, I can see that the statistics are there.  So it seems like a bug in `pm.load_trace()` not to restore them.

## Versions and main components

* PyMC3 Version:  `master` as of today
* Theano Version: ditto
* Python Version: 3.6
* Operating system: MacOS
* How did you install PyMC3: `pip -e`

**Comment by rpgoldman** [comment]
@ColCarroll @aseyboldt -- I tagged you two with this because git blame showed that you had worked on the backend, so I was hoping you would have insight.

**Comment by ColCarroll** [comment]
Heh, they're in there, but it is an implementation detail that they're not easily accessible. I can fix.

![image](https://user-images.githubusercontent.com/2295568/72656895-7f1bc900-396c-11ea-9959-1e8c8598c5a0.png)

**Comment by rpgoldman** [comment]
@ColCarroll Ahhh, yes, I see.  They are in the `_straces` but not hooked in for access from the `MultiTrace`, right?

**Comment by ColCarroll** [comment]
Yep. Lemme know what you think!
