### ISSUE TITLE
HamiltonianMC fails on a certain dataset while NUTS works just fine

### ISSUE THREAD

**Issue by geomesch** [pymc-devs/pymc#3777]
## Possible bug in HamiltonianMC

pymc3 produces an error when using HamiltonianMC as a step for a fairly simple model
```python
import numpy as np
import pymc3 as pm

np.random.seed(2020)
x = np.loadtxt('x.txt', delimiter='\t')
y = np.loadtxt('y.txt', delimiter='\t')

with pm.Model() as model:
    l = pm.Gamma('lambda', alpha=5, beta=1)
    beta = pm.Normal('beta', mu=0.5, sd=l ** (-2))
    g = pm.Normal('g', mu=x * beta, sd=1, observed=y)
    step = pm.HamiltonianMC([beta, l])
    trace = pm.sample(1000, chains=1, step=step, start={'beta': 0.5, 'lambda': 5})
```
Data:
[x.txt](https://github.com/pymc-devs/pymc3/files/4083148/x.txt)
[y.txt](https://github.com/pymc-devs/pymc3/files/4083149/y.txt)

Exception:
```python
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `lambda_log__`.ravel()[0] is zero.
The derivative of RV `beta`.ravel()[0] is zero.
```

However, NUTS runs just fine and produces correct parameters' estimates. My own toy implementation of Hamiltonian MC also gives correct estimates.
I think I need to add, just for the sake of clarity, that the same code but for a different dataset produces correct results as well:
```python
x = np.linspace(0, 10, 100)
y = 3 * x + np.random.normal(size=len(x))

with pm.Model() as model:
    l = pm.Gamma('lambda', alpha=5, beta=1)
    beta = pm.Normal('beta', mu=0.5, sd=l)
    g = pm.Normal('g', mu=x * beta, sd=1, observed=y)
    step = pm.HamiltonianMC([beta, l])
    trace = pm.sample(1000, chains=1, step=step, start={'beta': 0.5, 'lambda': 5})
```

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.4
* Operating system: Archlinux

**Comment by aseyboldt** [comment]
This is indeed a bug in HamiltonianMC. It did not check if the energy change is nan, and instead assumed that the acceptance probability was 1 in these cases, because for some reason `max(1, np.nan) == 1`. This leads to misbehaving step size adaptation.
Thanks for reporting this.

**Comment by aseyboldt** [comment]
Actually, `max(1, nan) == 1`, but `max(nan, 1) == nan`. This is a fun corner case of the std max function...

**Comment by ColCarroll** [comment]
Cool cool cool

![image](https://user-images.githubusercontent.com/2295568/72730656-c74f0d00-3b5f-11ea-97fd-4ca306d30d9b.png)
