### ISSUE TITLE
installing pymc3 has ruined my base env.

### ISSUE THREAD

**Issue by cmp1** [pymc-devs/pymc#3786]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

Conda install of pymc3 lead to multiple errors upon load, and now after removal I am no longer able to import keras/tensorflow etc.

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**
```python

<ipython-input-8-848db44b64a8> in <module>
      7 import keras
      8 import tensorflow as tf
----> 9 import pymc3

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\pymc3\__init__.py in <module>
     11 from .model_graph import model_to_graphviz
     12 from . import ode
---> 13 from .stats import *
     14 from .sampling import *
     15 from .step_methods import *

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\pymc3\stats\__init__.py in <module>
      8 import warnings
      9 
---> 10 import arviz as az
     11 
     12 def map_args(func):

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\arviz\__init__.py in <module>
     25 
     26 from .rcparams import rcParams, rc_context
---> 27 from .data import *
     28 from .plots import *
     29 from .stats import *

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\arviz\data\__init__.py in <module>
      1 """Code for loading and manipulating data structures."""
      2 from .inference_data import InferenceData, concat
----> 3 from .io_netcdf import from_netcdf, to_netcdf
      4 from .datasets import load_arviz_data, list_datasets, clear_data_home
      5 from .base import numpy_to_data_array, dict_to_dataset, CoordSpec, DimSpec

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\arviz\data\io_netcdf.py in <module>
      2 
      3 from .inference_data import InferenceData
----> 4 from .converters import convert_to_inference_data
      5 
      6 

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\arviz\data\converters.py in <module>
     10 from .io_numpyro import from_numpyro
     11 from .io_pymc3 import from_pymc3
---> 12 from .io_pyro import from_pyro
     13 from .io_pystan import from_pystan
     14 

~\AppData\Local\Anaconda\anaconda3\lib\site-packages\arviz\data\io_pyro.py in <module>
      2 import logging
      3 import numpy as np
----> 4 from packaging import version
      5 import xarray as xr
      6 

ModuleNotFoundError: No module named 'packaging'
'
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: Python 3.8
* Operating system: Windows 
* How did you install PyMC3: (conda/pip) Pip

**Comment by ericmjl** [comment]
I won't speak for the rest of the dev team, but as far as I know, it's a best practice to have one environment per project. It looks like you're using `conda`; if I may, I'd like to recommend some tools, detailed in my [blog post][blog], that I hope make your time easier.

[blog]: https://ericmjl.github.io/blog/2018/12/25/conda-hacks-for-data-science-efficiency/

In particular, creating an environment with pinned versions is usually good practice.

I'm going to close this, as I'm not sure there's a good solution any of us can provide easily apart from recommending that you move to isolated conda environments instead.

However, if you do try conda envs, and something still looks broken, please feel free to reopen the issue.
