### ISSUE TITLE
Mixture of Beta fails (because Beta has no mode)

### ISSUE THREAD

**Issue by TheDerivator** [pymc-devs/pymc#3797]
The following code executes without problems. 

```
import pymc3 as pm
alpha1_, beta1_ = pm.Exponential.dist(0.1).random(size=2)
alpha2_, beta2_ = pm.Exponential.dist(0.1).random(size=2)
w_ = pm.Dirichlet.dist(a=np.ones(2), shape=2).random(size=1)
p0 = pm.Gamma.dist([alpha1_, alpha2_], [beta1_, beta2_], shape=(n,2))
p_ = pm.Mixture.dist(w = w_, comp_dists = p0, shape=n).random(size=1)
```
But the same code with Beta instead of Gamma fails with `AttributeError: 'Beta' object has no attribute 'mode'. `

The exception is thrown in `pymc3\distributions\mixture.py in _comp_modes(self)` which is called from the constructor of Mixture. As a backup strat, it tries to compute the modes of the separate distributions as if it were an iterable of distributions. But that fails too, because p0 is not iterable and it throws ` TypeError: 'Beta' object is not iterable  `. Then it goes back to the constructor of the class Mixture which catches AttributeError, ValueError and IndexError. But because the actual error is a TypeError is isn't caught there and the exception halts the execution.

I think there are probably two issues:
 - Beta doesn't define a mode (although it easily could?)
 - Mixture doesn't catch TypeError, although it should because it can occur in this case

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.8.1
* Operating system: Windows 10
* How did you install PyMC3: Conda

**Comment by ricardoV94** [comment]
This issue seems to have been accidentally fixed by this commit 7 months ago: https://github.com/pymc-devs/pymc3/commit/87702590ad6d18db13eafbafc1bb96eb8e31e520

I can reproduce the issue by reverting back to before that commit, and it no longer happens after that commit or in the current master version.

**Comment by twiecki** [comment]
Thanks @ricardoV94!
