### ISSUE TITLE
formula for pseudo Bayesian averaging is wrong

### ISSUE THREAD

**Issue by HVoltBb** [pymc-devs/pymc#3798]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
Here is the link https://docs.pymc.io/notebooks/model_averaging.html
You are missing a minus sign there.
**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by aloctavodia** [comment]
Thanks! You are right. Do you want to submit a PR?

**Comment by HVoltBb** [comment]
Done. This is my first pull request to a shared project!

**Comment by aloctavodia** [comment]
Thanks! And congratulations!
