### ISSUE TITLE
Building docs fails on master branch

### ISSUE THREAD

**Issue by zoj613** [pymc-devs/pymc#3800]
## Description of your problem

running ` source build_and_deploy_docs.sh` or manually doing it via `make html` raises an error, after cloning the master branch to my local machine.

```
Notebook error:
NotebookValidationError in notebooks/GLM-model-selection.ipynb:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1', 'version_major': 2, 'version_minor': 0} is not valid under any of the given schemas

Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:

On instance['cells'][6]['outputs'][0]['data']['application/vnd.jupyter.widget-view+json']:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1',
 'version_major': 2,
 'version_minor': 0}
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 2
```

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.6.8
* Operating system: Ubuntu 18.04
* How did you install PyMC3: `pip setup.py install`

**Comment by twiecki** [comment]
@zoj613 Thanks for the report. What happens if you open `notebooks/GLM-model-selection.ipynb` with the jupyter notebook, save it, and then try building the docs again?

**Comment by zoj613** [comment]
@twiecki I just tried that and got the same error message. Here are the additional warnings thrown right before the error:
```/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/pymc3-3.8-py3.6.egg/pymc3/sampling.py:docstring of pymc3.sampling.sample:119: WARNING: Inline literal start-string without end-string.
/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/pymc3-3.8-py3.6.egg/pymc3/backends/base.py:docstring of pymc3.backends.base.MultiTrace:56: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/pymc3/docs/source/api/math.rst:61:<autosummary>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/pymc3/docs/source/api/math.rst:61:<autosummary>:1: WARNING: Inline emphasis start-string without end-string.
/home/pymc3/docs/source/api/math.rst:61:<autosummary>:1: WARNING: Undefined substitution referenced: "`a`".
/home/pymc3/docs/source/developer_guide.rst:861: WARNING: duplicate label inference, other instance in /home/pymc3/docs/source/api/inference.rst
/home/pymc3/docs/source/notebooks/Bayes_factor.ipynb:312: WARNING: duplicate label sequential monte carlo, other instance in /home/pymc3/docs/source/api/inference.rst
/home/pymc3/docs/source/notebooks/DEMetropolisZ_tune_drop_fraction.ipynb:2111: WARNING: duplicate label inspecting the sampler stats, other instance in /home/pymc3/docs/source/notebooks/DEMetropolisZ_EfficiencyComparison.ipynb
/home/pymc3/docs/source/notebooks/GLM-hierarchical.ipynb:610: WARNING: duplicate label references, other instance in /home/pymc3/docs/source/notebooks/BEST.ipynb
/home/pymc3/docs/source/notebooks/GLM-hierarchical-binominal-model.ipynb:468: WARNING: duplicate label conclusion, other instance in /home/pymc3/docs/source/notebooks/DEMetropolisZ_EfficiencyComparison.ipynb
/home/pymc3/docs/source/notebooks/GLM-hierarchical-binominal-model.ipynb:478: WARNING: duplicate label references, other instance in /home/pymc3/docs/source/notebooks/GLM-hierarchical.ipynb
/home/pymc3/docs/source/notebooks/GLM-linear.ipynb:42: WARNING: duplicate label linear regression, other instance in /home/pymc3/docs/source/notebooks/GLM.ipynb
/home/pymc3/docs/source/notebooks/GLM-linear.ipynb:400: WARNING: duplicate label summary, other instance in /home/pymc3/docs/source/notebooks/GLM-hierarchical.ipynb
/home/pymc3/docs/source/notebooks/GLM-logistic.ipynb:803: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/pymc3/docs/source/notebooks/GLM-logistic.ipynb:803: WARNING: Inline interpreted text or phrase reference start-string without end-string.
```

**Comment by rpgoldman** [comment]
This is a known problem.  @ColCarroll has worked on the documentation a bunch, but it's in a bit of a bad state.  We'd like to get it to a point where it builds cleanly, but that could be a long way.

Note also that there are a ton of warnings about un-referenced pages.  I _believe_ this is because our "cover page" is hand-generated, so sphinx doesn't know there are links to the notebooks, but I don't understand Sphinx well enough to be certain.

For a start, we could work our way through the source files, and bring them into compliance with the numpy standard style.  That would go a long way.

**Comment by zoj613** [comment]
@twiecki @rpgoldman is there a way I can get an offline copy of the documentation that i can view via dash or zeal ? I dont always have access to the internet so this helps a lot if I can have offline docsets for libraries I am interested in.

**Comment by rpgoldman** [comment]
@zoj613 I *think* you can use the HTML to Dash translation to get an offline copy.  I haven't done this lately, since I have the PyMC3 repo locally, so I can just generate the docs and open them in a browser.

They do build for me, although I get a zillion warnings, as you do.  So you are actually getting an error, not just a warning?

I just checked out the `master` branch, went to `docs/source` and did `make html`.  I get 171 warnings (!), but the docs build successfully with no fatal errors.  This is with Sphinx version 2.0.1.  What Sphinx version are you using?

I'm not sure what is going on with your notebook validation error there.  Maybe this is a jupyter or version issue? Here is what I have:
```
$ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
(pymc3) rpg@rpg-macbook-pro: ~/src/pymc3/docs/source $ pip freeze | grep ipython
ipython==7.3.0
ipython-genutils==0.2.0
```

**Comment by zoj613** [comment]
@rpgoldman I am using sphinx v2.3.1 and the following is the output for the versions of jupyter and ipython
```
$ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.2
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
```
```
$ pip freeze | grep ipython
ipython==7.12.0
ipython-genutils==0.2.0
```
I tried it again with this environment setup and it gave the same error. I am using python 3.6.8. Maybe i should downgrade to sphinx v2.0.1?


EDIT: just tried with sphinx v2.0.1 and after pulling in the latest changes on master. Got the same error. Here are the last few lines:
```
Notebook error:
NotebookValidationError in notebooks/GLM-model-selection.ipynb:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1', 'version_major': 2, 'version_minor': 0} is not valid under any of the given schemas

Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:

On instance['cells'][6]['outputs'][0]['data']['application/vnd.jupyter.widget-view+json']:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1',
 'version_major': 2,
 'version_minor': 0}
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 2
```

if no solution seems to work, i'd be happy if you shared the html folder you managed to build so i can convert it to Dash.

**Comment by zoj613** [comment]
Okay @rpgoldman I decide to run `make clean` and retry, then now I get an extended error msg:

```

Notebook error:
NotebookValidationError in notebooks/GLM-model-selection.ipynb:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1', 'version_major': 2, 'version_minor': 0} is not valid under any of the given schemas

Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:

On instance['cells'][6]['outputs'][0]['data']['application/vnd.jupyter.widget-view+json']:
{'model_id': '3f7c2b0604ab4d6aae55867976e7f8d1',
 'version_major': 2,
 'version_minor': 0}
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<class 'netCDF4._netCDF4.Dataset'>, '/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/arviz/data/_datasets/non_centered_eight.nc', mode='r', kwargs={'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 243, in __del__
  File "/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 217, in close
  File "/home/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<class 'netCDF4._netCDF4.Dataset'>, '/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/arviz/data/_datasets/centered_eight.nc', mode='r', kwargs={'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 243, in __del__
  File "/home/.pyenv/versions/3.6.8/envs/absa-py36/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 217, in close
  File "/home/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 2
```

**Comment by zoj613** [comment]
UPDATE: It finally worked after fiddling around with packages
1) I activated a different environment, then did `pip install -r requirements.txt` then got the error: `ERROR: xarray 0.15.0 has requirement pandas>=0.25, but you'll have pandas 0.24.2 which is incompatible.`
2) The i did `pip install -U pandas` then `pip install -r requirements.txt` again (ran successfully)
3) When I tried to build the html it complained about pymc3 not being installed so I ran: `python setup.py develop`
4) When I tried to rerun the command it complained about numpydoc not being installed so I ran `pip install -U numpydoc`
5) Finally I managed to run `make html` without error but a ton of warnings.

**Comment by rpgoldman** [comment]
> UPDATE: It finally worked after fiddling around with packages
> 
>     1. I activated a different environment, then did `pip install -r requirements.txt` then got the error: `ERROR: xarray 0.15.0 has requirement pandas>=0.25, but you'll have pandas 0.24.2 which is incompatible.`
> 
>     2. The i did `pip install -U pandas` then `pip install -r requirements.txt` again (ran successfully)
> 
>     3. When I tried to build the html it complained about pymc3 not being installed so I ran: `python setup.py develop`
> 
>     4. When I tried to rerun the command it complained about numpydoc not being installed so I ran `pip install -U numpydoc`
> 
>     5. Finally I managed to run `make html` without error but a ton of warnings.

One thing I notice in the above is that you have installed the contents of `requirements.txt` but not `requirements-dev.txt`.  It's only in the requirements for the *development* environment that `numpydoc` is installed, for example.  I believe we regard building the docs as a developer task, not a user task.

The tons of warning, as I said earlier, are just the state of the docs right now, so I think that this is "fixed."  Getting the docs to make cleanly, without warnings, is probably going to take a while.
