### ISSUE TITLE
`summary()` fails with the new pandas release

### ISSUE THREAD

**Issue by bersavosh** [pymc-devs/pymc#3805]
Pandas 1.0 has been [released](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html) and the keyword `joint_axis` is [now removed](https://github.com/pandas-dev/pandas/pull/22318) from `concat()`.

This causes pymc3's `summary()` to fail with the following error:

```
~/anaconda3/lib/python3.6/site-packages/pymc3/stats.py in summary(trace, varnames, transform, stat_funcs, extend, include_transformed, alpha, start, batches)
    980         rhat_pd = dict2pd(rhat, 'Rhat')
    981         return pd.concat([dforg, n_eff_pd, rhat_pd],
--> 982                          axis=1, join_axes=[dforg.index])
    983 
    984 

TypeError: concat() got an unexpected keyword argument 'join_axes'
```

**Comment by junpenglao** [comment]
Could you please update your pymc3 install to the newest version - this is not a problem in the newer versions as we are using arviz for diagnostic and plotting.

**Comment by bersavosh** [comment]
Oh sorry, did not notice that. Will do, thanks for the reply.
