### ISSUE TITLE
Notebook example on Bayes factor

### ISSUE THREAD

**Issue by HVoltBb** [pymc-devs/pymc#3807]
In this notebook,
https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/Bayes_factor.ipynb
section "Sequential Monte Carlo".
The text is talking about increasing the accuracy through increasing n_chains. Perhaps you mean the number of draws. Increasing n_chains won't give you anything better except shorter exec time. Also, there's no argument called n_chains in sample_smc.

I would say "increase the number of **adaptation** n_steps and **draws** for a more accurate estimation of the marginal likelihood."  Let me know if the text is clearer this way.

**Comment by aloctavodia** [comment]
Thanks @HVoltBb I will reword that sentence and made other (minor) fixes to that notebook.
