### ISSUE TITLE
Small Typo on Bayes Factors and Marginal Likelihood notebook

### ISSUE THREAD

**Issue by p16i** [pymc-devs/pymc#3817]
Hi,

It seems that there is a writing inconsistence of the the parameter prior on on [Bayes Factors and Marginal Likelihood](https://docs.pymc.io/notebooks/Bayes_factor.html). In the beginning, the parameter prior under a model is written using a conditional form:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1214890/75370717-d3985980-58c5-11ea-89dd-cfcebcd73f56.png">

When [discussing remarks](https://docs.pymc.io/notebooks/Bayes_factor.html#Some-remarks), the parameter prior is instead written as a joint distribution:
<img width="347" alt="Screen Shot 2020-02-26 at 6 24 08 PM" src="https://user-images.githubusercontent.com/1214890/75370635-b2376d80-58c5-11ea-9848-5a1f470b704a.png">

IMHO, the later seems to be a typo. What do you think?

**Comment by aloctavodia** [comment]
@heytitle Good Catch. You are right about the typo, do you want to send a PR?

**Comment by p16i** [comment]
ok, done!

Noting, because the fix is a small change, I edited the file directly without using Jupyter. I hope it's ok.
