### ISSUE TITLE
Dependencies on Patsy and Statsmodels should be handled more directly

### ISSUE THREAD

**Issue by aflaxman** [pymc-devs/pymc#382]
I'm installing PyMC on a fresh Anaconda distribution of Python 2.7, and it fails with an error about Patsy:

```
In [1]: import pymc
Warning: statsmodels not found, only importing parts of glm.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/snfs2/HOME/abie/pymc/pymc/__init__.py in <module>()
     18 from .tests import test
     19
---> 20 import glm

/snfs2/HOME/abie/pymc/pymc/glm/__init__.py in <module>()
      6 except ImportError:
      7     print "Warning: statsmodels not found, only importing parts of glm."
----> 8     from .glm import linear_component

/snfs2/HOME/abie/pymc/pymc/glm/glm.py in <module>()
      2 import numpy as np
      3 from pymc import  *
----> 4 import patsy
      5 import theano
      6 import pandas as pd

ImportError: No module named patsy
```

Can this dependency be added to the `setup.py install` process automatically somehow?

Related, after I've installed Patsy, I get similar complaints about statsmodels:

```
In [1]: import pymc
Warning: statsmodels not found, only importing parts of glm.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/snfs2/HOME/abie/pymc/pymc/__init__.pyc in <module>()
     18 from .tests import test
     19
---> 20 import glm

/snfs2/HOME/abie/pymc/pymc/glm/__init__.py in <module>()
      6 except ImportError:
      7     print "Warning: statsmodels not found, only importing parts of glm."
----> 8     from .glm import linear_component

/snfs2/HOME/abie/pymc/pymc/glm/glm.py in <module>()
      6 import pandas as pd
      7 from collections import defaultdict
----> 8 from statsmodels.formula.api import glm as glm_sm
      9 import statsmodels.api as sm
     10 from pandas.tools.plotting import scatter_matrix

ImportError: No module named formula.api
```

With `conda install patsy statsmodels` everything works, so this is no big deal, just some information that could help make pymc3 easier to get started with.

**Comment by twiecki** [comment]
Thanks @aflaxman. Should be fixed with https://github.com/pymc-devs/pymc/commit/22e661e7dc9a893e880d5be0b592c0f85e2bcef8, please reopen if not.

**Comment by attilacsordas** [comment]
similar complaints here: Warning: statsmodels and/or patsy not found, not importing glm submodule. Python 2.7.5 (default, Mar  9 2014, 22:15:05), mac os x 10.9.5, installed statsmodels separately, installed pymc again, using PyCharm Community 3.4, re-opening PyCharm gives: Failed modules
Python 2.7.5 (/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7) 
matplotlib._qhull
statsmodels.nonparametric._smoothers_lowess
statsmodels.nonparametric.linbin
statsmodels.tsa.kalmanf.kalman_loglike

**Comment by twiecki** [comment]
Can you do "import statsmodels; print(statsmodels.**version**)" ? 

Does this also happen without PyCharm?

**Comment by attilacsordas** [comment]
both with and w/o PyCharm I get:

Traceback (most recent call last):
  File "/Users/attilacsordas/PycharmProjects/palindrome/test.py", line 1, in <module>
    import statsmodels
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/**init**.py", line 8, in <module>
    from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/tools/**init**.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/tools/tools.py", line 11, in <module>
    from statsmodels.datasets import webuse
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/datasets/**init**.py", line 5, in <module>
    from . import (anes96, cancer, committee, ccard, copper, cpunish, elnino,
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/datasets/anes96/**init**.py", line 1, in <module>
    from .data import *
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/datasets/anes96/data.py", line 90, in <module>
    from statsmodels.datasets import utils as du
  File "/Library/Python/2.7/site-packages/statsmodels-0.6.1-py2.7-macosx-10.9-intel.egg/statsmodels/datasets/utils.py", line 13, in <module>
    from pandas import read_csv, DataFrame, Index
ImportError: No module named pandas

**Comment by twiecki** [comment]
glm was refactored recently which should address this.
