### ISSUE TITLE
Documenting internals

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3825]
## Description of your problem
I recently made a [draw.io](https://draw.io) chart of the control flow in `sampling.py`.
I'm creating a wiki page for such documentation of internal structure: https://github.com/pymc-devs/pymc3/wiki/PyMC3-Internals-(for-devs)

However, one can't upload file attachments to the wiki directly, so instead I'll comment the image & file here, so I can link it from the wiki.

I suppose this issue can serve the same purpose for other wiki attachments.

**Comment by michaelosthege** [comment]
### Internals - control flow in sampling.py
![sampling](https://user-images.githubusercontent.com/5894642/76105608-873fce80-5fd5-11ea-89cf-9e8bf9f354c5.png)

draw.io file: [sampling.zip](https://github.com/pymc-devs/pymc3/files/4299428/sampling.zip)

**Comment by eigenfoo** [comment]
@michaelosthege perhaps this could find a home in the developer guide?
