### ISSUE TITLE
sample_posterior_predictive from InferenceData?

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3828]
### Description of your problem
In some scenarios, sampling and prediction do not happen at the same time or even in the same process.
`sample_posterior_predictive` can be fed with a `MultiTrace`, but in many scenarios, the trace is saved via `arviz.to_netcdf` and only the `arviz.InferenceData` is kept.

With this small function, one can convert an `xarray.Dataset` (the `InferenceData.posterior`) to a list of points that may be consumed by `sample_posterior_predictive`.

```python
def _to_points(posterior:xarray.Dataset) -> typing.List[dict]:
    samples = {
        vn : posterior[vn].values
        for vn in posterior.keys()
    }
    points = []
    for c in posterior.chain:
        for d in posterior.draw:
            points.append({
                vn : s[c, d]
                for vn, s in samples.items()
            })
    return points
```

The list of points is probably not the most performant option. Maybe `sample_posterior_predictive` could be modified to consume the `InferenceData` object directly?

**Comment by rpgoldman** [comment]
> The list of points is probably not the most performant option. Maybe `sample_posterior_predictive` could be modified to consume the `InferenceData` object directly?

Yes, for the vectorized version, I am already redoing the input away from being a set of points.

We could definitely consume the `InferenceData` object more directly, but `sample_posterior_predictive` needs access to the `pm.Model` object, so it's not sufficient to have a save and restore solution that is limited to the posterior trace alone.
