### ISSUE TITLE
GP Latent variable Inference : Problem deterministically reproducing f from f_rotated_

### ISSUE THREAD

**Issue by vr308** [pymc-devs/pymc#3830]
In the [GP latent variable implementation](https://docs.pymc.io/notebooks/GP-Latent.html) which uses the automatic reparameterization in terms of the cholesky, so essentially 

_f = cholesky(K).dot(f_rotated_)_

_f_rotated__ is the the std. normal variable which is sampled and returned in the trace. The trace also returns _f_ along with the free_RV f_rotated__

## Description of your problem
I am trying to deterministically construct f using the cholesky relation. I am also sampling the lengthscale hyper. 

    # number of data points
    n = 200

    # x locations
    x = np.linspace(0, 1.5, n)

    # true covariance
    l_true = 0.1
    n_true = 1.0
    cov_func = n_true**2 * pm.gp.cov.ExpQuad(1, l_true)
    K = cov_func(x[:,None]).eval()

    # zero mean function
    mean = np.zeros(n)

    # sample from the gp prior
    f_true = np.random.multivariate_normal(mean, K + 1e-6 * np.eye(n), 1).flatten()

    # link function
    def invlogit(x, eps=sys.float_info.epsilon):
        return (1.0 + 2.0 * eps) / (1.0 + np.exp(-x)) + eps

    # y-data
    y = pm.Bernoulli.dist(p=invlogit(f_true)).random()

    with pm.Model() as model:

        # hypers

        l = pm.Gamma("l", alpha=2, beta=2)
        n = 1.0
        cov = n**2 * pm.gp.cov.ExpQuad(1, l)

        gp = pm.gp.Latent(cov_func=cov)

        # make gp prior
        f = gp.prior("f", X=x[:,None], reparameterize=True)

        # logit link and Bernoulli likelihood
        p = pm.Deterministic("p", pm.math.invlogit(f))
        y_ = pm.Bernoulli("y", p=p, observed=y)

        trace = pm.sample(50, chains=1)

    # Trying to recreate f returned in the trace from f_rotated_ using the relation =>  f = cholesky(K).dot(f_rotated_)

    f_recovered = np.empty(shape=(50,200))

    for i in np.arange(50):
        print(i)
        l_current = trace['l'][i]
        cov_current = 1.0**2 * pm.gp.cov.ExpQuad(1, l_current)
        K = cov_current(x[:,None]) + 1e-12*np.eye(len(x))
        v = trace['f_rotated_'][i]
        f_current = cholesky(K).dot(v)
        f_recovered[i] = f_current.eval()

    # f_recovered should be equal to trace['f'] but it is not.

    plt.figure()
    plt.plot(x, f_recovered.T, color='b', label='Reconstructed')
    plt.plot(x, trace['f'].T, color='grey', label='From trace')

**Please provide any additional information below

![err](https://user-images.githubusercontent.com/17442913/76459115-88a53880-63d3-11ea-8401-3dd88f473059.png)
.**

Blue = recreation, Grey = plotted directly from trace 
Can't understand why there seems to a delta when they should match exactly as f is just a deterministic transform. 
## Versions and main components

* PyMC3 Version:3.8
* Theano Version:1.0.4
* Python Version: 3.6.10
* Operating system: Ubuntu 18.04.3 LTS
* How did you install PyMC3: (conda/pip) conda

**Comment by tirthasheshpatel** [comment]
This is expected as you have the length scale (``l``) and amplitude parameter (``n``) in the model context that get tuned during MCMC sampling. Meaning your kernel parameters change at each sampling step while in your ``for`` loop, the parameters remain constant for all the steps.

**Comment by tirthasheshpatel** [comment]
Have you tried ``K = cov_current(x[:,None]) + 1e-6*np.eye(len(x))``? PyMC3 adds ``1e-6`` noise. I think this should do it as the plot also looks awfully similar and shifted by just a little amount from actual trace

**Comment by vr308** [comment]
I have kept n constant in the model and update the lengthscale in the
for-loop ..as l is being learnt not n. 

I use the current value of the lengthscale (l) from the trace to construct K
at each iteration...

**Comment by tirthasheshpatel** [comment]
Setting the noise ``1e-6`` does it!
![sol](https://user-images.githubusercontent.com/43181252/76518360-f8273080-6484-11ea-807a-406ac5cfebca.png)

**Comment by vr308** [comment]
Ok agreed, it seems to be what stabilize does!
Thank you.
