### ISSUE TITLE
API docs for ODE are missing

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#3848]
It seems like the ODE API docs are not getting generated: https://docs.pymc.io/api.html

Probably just need to add them to the docs sources somewhere.

CC @Dpananos

**Comment by Dpananos** [comment]
Will get to it today

**Comment by Dpananos** [comment]
To confirm, I have to create an `ode.rst` file and then add that to `api.rst`?

**Comment by twiecki** [comment]
That sounds right.

**Comment by Dpananos** [comment]
@twiecki made a pr.

Let's wait and see if I did it correctly before closing.  I built the docs before making the pr, so all should be good.

**Comment by twiecki** [comment]
Thanks @Dpananos!
