### ISSUE TITLE
Number of samples is high when init='nuts'

### ISSUE THREAD

**Issue by rosgori** [pymc-devs/pymc#3861]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

When you use the option `init='nuts'` in `pm.sample()`, the number of samples is really high

```python
import pymc3 as pm
import numpy as np

N = 1000
x = np.random.normal(loc=0, scale=2, size=N)

with pm.Model() as model:
    
    mu = pm.Normal('mu', 0, 5)
    sigma = pm.HalfNormal('sigma', sd=5)
    
    obs = pm.Normal('obs', mu=mu, sigma=sigma, observed=x)
    
with model:
    trace = pm.sample(draws=100, tune=100, init='nuts')
    
print(pm.summary(trace))
```

**Please provide the full traceback.**
```python
Sampling 4 chains, 0 divergences:   1%|▏         | 15137/1200000 [00:05<07:25, 2661.65draws/s]
```

As you see, the number `1200000` always appear, it doesn't matter if you change `draws` or `tune` in `pm.sample`.

Should that number change when you change `draws` and `tune`?

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.6
* Operating system: Ubuntu 16.04.6 LTS
* How did you install PyMC3: (conda/pip) conda

**Comment by twiecki** [comment]
Thanks, that init method should just be dropped. Where did you find it referenced?

**Comment by AlexAndorra** [comment]
It seems to be in `pm.sample` doc:

> nuts: Run NUTS and estimate posterior mean and mass matrix from the trace.

Then, in the source code, when the init method is "nuts", it samples with `n_init` as the number of `draws`:
```(python)
 elif init == "nuts":
      init_trace = pm.sample(
          draws=n_init, step=pm.NUTS(), tune=n_init // 2, random_seed=random_seed
      )
```
Since `pm.sample` defaults to `n_init=200_000`, this yields 200_000 + 100_000 samples per chain, which is, I think, where the 1_200_000 come from (since you're sampling 4 chains in the example).

**Comment by twiecki** [comment]
Yeah this is a left-over, we have better ones now so should just remove it.

**Comment by AlexAndorra** [comment]
Ok, seems straightforward -- I'll do it

**Comment by Ahanmr** [comment]
@twiecki @AlexAndorra  This issue is fixed right? Is there still anything pending on this one? Looks like init='nuts' is mostly dropped already.
