### ISSUE TITLE
Problem importing DifferentialEquation

### ISSUE THREAD

**Issue by iteimouri** [pymc-devs/pymc#3867]
I am trying to run [this example](https://docs.pymc.io/notebooks/ODE_API_introduction.html). I did !pip install pymc3 and this was installed just fine. Yet when I run from pymc3.ode import DifferentialEquation I get error `ModuleNotFoundError: No module named 'pymc3.ode'`

**Comment by twiecki** [comment]
Could you move this to our discourse?
