### ISSUE TITLE
ModuleNotFoundError: No module named 'corner'

### ISSUE THREAD

**Issue by Ahanmr** [pymc-devs/pymc#3868]
## Description of your problem
Found an un-run Notebook in docs/source/notebooks called blackbox_external_likelihood.ipynb with a ModuleNotFoundError: No module named 'corner'
**Please provide a minimal, self-contained, and reproducible example.**
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
 in ()
     19 import matplotlib
     20 import emcee
---> 21 import corner
     22 import os
     23 print("Python version:     {}".format(platform.python_version()))

ModuleNotFoundError: No module named 'corner'
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: Master

This is a Notebook in the Master repository, needed feedback on whether this needs to be removed and re-run the notebook.

**Comment by techytushar** [comment]
Is the `corner` module installed on your computer?

**Comment by Ahanmr** [comment]
I'm suggesting a change to the notebook on the master. What's it got to do with `corner` installed on my computer?

**Comment by techytushar** [comment]
Oh sorry, I misinterpreted the issues

**Comment by Ahanmr** [comment]
https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/blackbox_external_likelihood.ipynb

Check this out!

**Comment by Ahanmr** [comment]
I think it's a helper notebook, so need to change it!
