### ISSUE TITLE
WAIC & LOO scaling

### ISSUE THREAD

**Issue by tobywise** [pymc-devs/pymc#3874]
I’ve just noticed that the newest ArviZ release (0.7.0) has changed from deviance to log scale for WAIC and LOO statistics, which PyMC3 relies on. This is contrary to previous PyMC3 behaviour (and the documentation https://docs.pymc.io/api/stats.html). The PyMC3 requirements file indicates ArviZ>=0.4.1, so new installs will get 0.7.0 with this changed behaviour.

I think this is something that needs to be dealt with fairly rapidly as it can actually invert previous PyMC3 results (i.e. flipping from lower WAIC=better to higher=better) without any warning. Had I not noticed this I would likely have proceeded to publish work based on inverted model comparison stats, which would not have been good…

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: Linux/Windows
* How did you install PyMC3: (conda/pip): pip

**Comment by AlexAndorra** [comment]
Hi Toby,
Thanks for reporting this!

- Regarding the ArviZ functionalities, we'll probably add a warning to the relevant functions. This warning will be temporary though, since the DataFrame is already ordered and we also provide a rank number. So, a permanent warning would probably be redundant.

- Regarding the PyMC doc, it's true that it still indicates deviance as the default (which is the case before ArviZ 0.7.0), instead of log. The best would perhaps be to redirect directly to ArviZ doc for this part of PyMC docs? But it's a choice for the PyMC team.

**Comment by tobywise** [comment]
Hi Alex,

Thanks for your quick response! 

- I agree with a permanent warning probably being unnecessary for the compare function, as you say it returns an ordered DataFrame and it also explicitly states the scale. However for the individual WAIC/LOO functions a permanent warning might be helpful as there's no ranking etc, and these are frequently reported on the deviance scale (e.g. in Stan)
- I'd agree about redirecting to the arviz docs, unless PyMC3 sticks with a specific arviz version and ensures their docs are in line with this, otherwise they could easily diverge again in the future

**Comment by aloctavodia** [comment]
Hi @tobywise, thanks for taking the time to fill this issue. 

I think the warnings should be temporary for the 3 functions. We changed the default scale to the log-scale by recommendation of Aki Vehtari from the Stan team, so if they are still using the deviance scale, they will switch soon.

**Comment by ahartikainen** [comment]
@avehtari

Has `loo` possibility for the deviance scale output?

**Comment by avehtari** [comment]
`loo` package still has -2 multiplier in some outputs and unfortunately the process is slow to get rid of it.

I think it's problematic to call it deviance scale, as the deviance was originally defined in context of point estimates. WAIC was originally defined with -1 multiplier which makes more sense than -2.The reason for not using -2, is that it makes inferring the relation to the effective number of parameters more difficult and it has only historical reason why it used to be useful for maximum likelihood and nested GLM.

I guess it would be useful for some users to have argument for the multiplier or choose the utility or loss, e.g. "log-score", "negative-log-score", "MSE", etc. If the multiplier for log-score is allowed to be only 1 or -1, then the output could be changing as elpd_loo vs. enlpd_loo and elpd_waic vs. enlpd_waic, where nlpd is negative log predictive density. This comment was based on how `loo` package output looks like, but I can't remember how does the arviz output look like. There's a bit of additional discussion of additional utility/loss functions in https://avehtari.github.io/modelselection/CV-FAQ.html and the plan is to make it easier to choose between different utility/loss functions. Then it would be possible for users to define their own loss functions including "deviance" even if we would not support it by default.

**Comment by AlexAndorra** [comment]
I think this can be closed thanks to [this PR](https://github.com/arviz-devs/arviz/pull/1150).
I don't know what the PyMC team thinks, but redirecting directly to ArviZ doc for this part of PyMC docs seems like a good idea to me.
