### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by aaparab** [pymc-devs/pymc#3882]
## Small error in documentation

In the documentation for the [`Mixture` distribution](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/mixture.py), the support of `f` should be the `union` of the support of each `f_i`. Line 51 of the above file should read 
```
    Support   :math:`\cup_{i = 1}^n \textrm{support}(f_i)`
```

**Comment by twiecki** [comment]
Want to do a PR?

**Comment by aaparab** [comment]
I will be happy to. I'm a git noob so this might be a good excuse to learn more.
