### ISSUE TITLE
Infeasable MAP solution

### ISSUE THREAD

**Issue by mario-schiappacasse-ug** [pymc-devs/pymc#3889]
## Description of your problem
Infeasable MAP solution for coin example.

Given p a Uniform Variable between 0.1 and 0.9, pm.find_MAP() gives a 'p' value of -0.5 which is of course not posible.

```python
import pymc3 as pm

with pm.Model() as model:
  n = pm.DiscreteUniform('n', 0, 8)
  p = pm.Uniform('p', lower=0.1, upper=0.9, transform=None)
  y = pm.Binomial('k', n, p, observed = [3, 2, 1, 0])
  print(pm.find_MAP())
```

```python
{'n': array(4, dtype=int64), 'p': array(-0.5)}
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: pymc3==3.8
* Theano Version: Theano==1.0.4
* Python Version:  3.6.10
* Operating system: Windows 10-64bit
* How did you install PyMC3: conda

**Comment by mario-schiappacasse-ug** [comment]
```python
with pm.Model() as model:
  n = pm.DiscreteUniform('n', 4, 8)
  p = pm.Uniform('p', lower=0.1, upper=0.9, transform=None)
  y = pm.Binomial('k', n, p, observed = [3, 2, 1, 0])
  print(pm.find_MAP())
```
Also gives the same problem, just in case.

**Comment by rpgoldman** [comment]
This seems to be related to the `transform=None` you have in your Uniform RV.

When I do this:
```
with pm.Model() as model:
  n = pm.DiscreteUniform('n', 4, 8)
  p = pm.Uniform('p', lower=0.1, upper=0.9)
  y = pm.Binomial('k', n, p, observed = [3, 2, 1, 0])
  print(pm.find_MAP())
```
I get back:
```
{'n': array(6), 'p_interval__': array(-1.46633698), 'p': array(0.25000001)}
```
I think setting the `transform` to `None` messes with PyMC3's ability to transform that RV and sample from it properly.

**Comment by brandonwillard** [comment]
Yeah, as @rpgoldman said, some kind of transform (e.g. an analytic one that cleans up the feasible regions) is needed in order to make that optimization problem approachable using the Newton-like methods mostly likely employed by `find_MAP`.

**Comment by rpgoldman** [comment]
I think it's unfortunate that `None` can be explicitly passed in here, and that doing so seems to have different effects from not supplying anything.

As much as anything, that's Python's fault, not PyMC3's.

But since this is resolved by not passing that `transform` argument, I am going to close this issue.  It can be reopened if it needs more attention.

**Comment by brandonwillard** [comment]
API aside, I don't think this kind of problem can really be answered by PyMC3 alone; it looks like a classic optimization problem with a "real" solution that lies outside of this project's scope.  For example, something like AMPL might be better suited for non-MCMC approaches to problems like this one.
