### ISSUE TITLE
switch point and piecewise function

### ISSUE THREAD

**Issue by rizman18** [pymc-devs/pymc#3890]
Hi, I want to fit my data, here is my data

![warp](https://user-images.githubusercontent.com/20876282/80000860-e014e900-84e7-11ea-896a-2f9409f45c1b.png)

The function is
![equation2](https://user-images.githubusercontent.com/20876282/80002179-83b2c900-84e9-11ea-9e13-2ffd659be5c5.png)

when R < R1, psi = 0, psi starts to deviate at R1 < R < R2, and psi equals psi maximum at R = R2, with psi_maximum is set at a certain value.

I want to fit the data with these equation and need to know the best value of R1, R2, and alpha.

Can you give me advice or some references to study.

Thanks

**Comment by rpgoldman** [comment]
Questions like this should go on `discourse.pymc.io`, rather than be PyMC3 issues.  I'm going to close this now, but please repost your question there, where I hope you will find good answers!

**Comment by rizman18** [comment]
I'm sorry. 
Thanks
