### ISSUE TITLE
Request: pm.math.factorial

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#3910]
It would be really helpful to be able to compute the factorial of a variable (for instance to compute the binomial coefficient) for designing custom likelihood functions.

Would it be feasible to add this to the pymc.math module?

**Comment by ColCarroll** [comment]
The factorial is already available through [the gamma function](https://en.wikipedia.org/wiki/Gamma_function), which is available as `theano.tensor.gamma`: specifically, `n! = tt.gamma(n + 1)`. 

Remember that factorials (and the gamma function) get very large very fast, so you have to be careful about computing with them (and preferably don't compute them). Concretely, PyMC3 defines `pm.distributions.special.gammaln` as the log of the gamma function, and [uses that here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/dist_math.py#L86) to compute the log of the factorial, and the log of the binomial density.

I'm closing for now, but feel free to keep discussing, or reopen if you think some action should still be taken!
