### ISSUE TITLE
plot_gp_dist fails to plot band on some inputs

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#3917]
## Description of your problem
The `pymc3.gp.util.plot_dist` helper function is super useful, making really beautiful plots most of the time.

On some inputs however, it reproducibly fails to plot the band.

Here are numpy arrays of GP samples, one of them works, the other doesn't:

[x_dense.txt](https://github.com/pymc-devs/pymc3/files/4605589/x_dense.txt)
[y_samples_bad.txt](https://github.com/pymc-devs/pymc3/files/4605590/y_samples_bad.txt)
[y_samples_good.txt](https://github.com/pymc-devs/pymc3/files/4605591/y_samples_good.txt)

```python
for cond in ['good', 'bad']:
    print(f'With {cond} inputs:')
    x_dense = numpy.loadtxt('x_dense.txt')
    y_samples = numpy.loadtxt(f'y_samples_{cond}.txt')
    print(f'y_samples.shape = {y_samples.shape}')

    fig, axs = pyplot.subplots(ncols=2, figsize=(9, 3), dpi=140, sharey='row')

    pymc3.gp.util.plot_gp_dist(axs[0], y_samples, x_dense)
    axs[0].set_title('plot_gp_dist')

    axs[1].set_title('pyplot.plot')
    for line in y_samples:
        axs[1].plot(x_dense, line, color='black', linewidth=0.2, alpha=0.1)

    pyplot.show()
```

![image](https://user-images.githubusercontent.com/5894642/81498582-0dbea800-92c6-11ea-989b-2d9b422ced96.png)

I've seen the problem before, but always assumed it was because of a bad trace or so, but it's clearly just a plotting issue.

## Versions and main components

* PyMC3 Version: master
* Python Version: 3.6
* Operating system: Windows

**Comment by michaelosthege** [comment]
Turns out the bad samples contained 5 rows of: `nan`

```
np.isnan(y_samples).any(axis=1).sum()
# >> 5
```

But how did they get there? That means `sample_posterior_predictive` returned them...

**Comment by michaelosthege** [comment]
The hyperparameters for these samples contained a lenghscale that was 5x higher than for the other samples, causing `sample_posterior_predictive` to predict `nan` conditionals.

Any ideas if we can/should do something about it? Warnings, errors, ...?

**Comment by tirthasheshpatel** [comment]
> Any ideas if we can/should do something about it?

I think the `nan`s in traces and posterior_predicitve samples are due to non-positive semi-definiteness of the covariance matrix calculated during GP inference. This can be resolved by adding more diagonal shift in the covariance matrix for larger datasets. Also, this frequently occurs in larger datasets with around 1000 entries or more.

**Comment by michaelosthege** [comment]
Yes, the larger the number of observations, the more often it happens..

In https://github.com/pymc-devs/pymc3/pull/3913 I've added a warning about `nan` entries. It does not fix the problem, but at least it alerts the user.
