### ISSUE TITLE
How to  use the previous pm.gp.GP and pm.gp.sample_gp function in the latest pymc3?

### ISSUE THREAD

**Issue by al00014** [pymc-devs/pymc#3922]
I followed the GP tutorial on docs/source/notebooks/GP-introduction.ipynb, but I cannot proceed, it seems that the pymc3 package does not contain codes for gp.GP and gp.sample_gp anymore.

Version:
pm.__version__
'3.8'
platform: centos

**Comment by michaelosthege** [comment]
I don't see a "GP-Introduction.ipynb" notebook in the [notebooks of release 3.8](https://github.com/pymc-devs/pymc3/tree/ca35f4f1a2a637bf8ccb40aefaebff49bd27f42e/docs/source/notebooks)

You can check out the examples for "Latent" and "Marginal" GPS on https://docs.pymc.io

**Comment by rpgoldman** [comment]
@al00014 I poked around in the history, and that notebook was split into the two notebooks for latent and marginal almost 3 years ago:

```
 $ git show --summary 89127b26f29275eb6668184b025e203674c0155f
commit 89127b26f29275eb6668184b025e203674c0155f
Author: Bill Engels <w.j.engels@gmail.com>
Date:   Mon Aug 7 17:38:31 2017 -0500

    split GP-introduction into two examples

 create mode 100644 docs/source/notebooks/GP-Latent.ipynb
 create mode 100644 docs/source/notebooks/GP-Marginal.ipynb
 delete mode 100644 docs/source/notebooks/GP-introduction.ipynb
```

I'm going to close this for now; please re-open it if you have more problems.

Also, usage questions are often better posed on discourse.pymc.io
