### ISSUE TITLE
Having issue with minibatch 

### ISSUE THREAD

**Issue by Jiji-tonton** [pymc-devs/pymc#3934]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem
I am using toy data used in this post[https://twiecki.io/blog/2018/08/13/hierarchical_bayesian_neural_network/](https://twiecki.io/blog/2018/08/13/hierarchical_bayesian_neural_network/).

 I used the following code for variation inference:

**Please provide a minimal, self-contained, and reproducible example.**
```
Xss  = theano.shared(Xs_train)
Yss  = theano.shared(Ys_train)
hbnn = construct_hierarchical_nn(Xss, Yss)

minibatch_x = pm.Minibatch(Xs_train, batch_size=[1,50,2])
minibatch_y = pm.Minibatch(Ys_train, batch_size=[1,50])

with hbnn:
    advi_fit = pm.fit(method=pm.ADVI(), n=10000,
                      more_replacements={Xss: minibatch_x, Yss:minibatch_y})
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**
I got the following error:

       ValueError: Shape mismatch: batch sizes unequal. x.shape is (1, 50, 2), y.shape is (4, 2, 5).
      **Apply node that caused the error: BatchedDot(Minibatch, Elemwise{Composite{((i0 * i1) + i2)}}.0)**
**      Toposort index: 126**
**     Inputs types: [TensorType(float64, 3D), TensorType(float64, 3D)]**
**     Inputs shapes: [(1, 50, 2), (4, 2, 5)]**
**     Inputs strides: [(800, 16, 8), (80, 40, 8)]**
**     Inputs values: ['not shown', 'not shown']**
**    Outputs clients: [[Elemwise{Tanh}[(0, 0)](BatchedDot.0)]]**

Any help on how I can fix this!!

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by rpgoldman** [comment]
For a help request, please repost on our Discourse unless you are certain this is an actual bug.
