### ISSUE TITLE
PyMC3 Fails on Windows Python 3.8 (Theano dll imports)

### ISSUE THREAD

**Issue by hectormz** [pymc-devs/pymc#3946]
## Description of your problem

Running `pymc3` on Windows fails for me when using python 3.8. Running the same code with same package versions on my machine with python 3.7 works. From what I can tell, this is a `Theano` issue and not specifically a `pymc3` problem, but figured other users might find this issue in the future.

It seems that the resolution of DLLs has changed in Python 3.8 for Windows:

> New in version 3.8: Previous versions of CPython would resolve DLLs using the default behavior for the current process. This led to inconsistencies, such as only sometimes searching PATH or the current working directory, and OS functions such as AddDllDirectory having no effect.

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

* https://bugs.python.org/issue36085
* https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
* https://docs.python.org/3/library/os.html#os.add_dll_directory

I wasn't sure if someone had a fix that didn't involve updating how dll's are loaded in Windows by `Theano`. Otherwise I can open an issue about this with `Theano`, which I think `pymc3` is helping shepherd since it is not actively developed anymore.

This is not a problem with `Anaconda`, which could be a solution for some folks.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import numpy as np


# set the seed
np.random.seed(1)

n = 100 # The number of data points
X = np.linspace(0, 10, n)[:, None] # The inputs to the GP, they must be arranged as a column vector

# Define the true covariance function and its parameters
ℓ_true = 1.0
η_true = 3.0
cov_func = η_true**2 * pm.gp.cov.Matern52(1, ℓ_true)

# A mean function that is zero everywhere
mean_func = pm.gp.mean.Zero()

# The latent function values are one sample from a multivariate normal
# Note that we have to call `eval()` because PyMC3 built on top of Theano
f_true = np.random.multivariate_normal(mean_func(X).eval(),
                                       cov_func(X).eval() + 1e-8*np.eye(n), 1).flatten()

# The observed data is the latent function plus a small amount of T distributed noise
# The standard deviation of the noise is `sigma`, and the degrees of freedom is `nu`
σ_true = 2.0
ν_true = 3.0
y = f_true + σ_true * np.random.standard_t(ν_true, size=n)


with pm.Model() as model:
    ℓ = pm.Gamma("ℓ", alpha=2, beta=1)
    η = pm.HalfCauchy("η", beta=5)

    cov = η**2 * pm.gp.cov.Matern52(1, ℓ)
    gp = pm.gp.Latent(cov_func=cov)

    f = gp.prior("f", X=X)

    σ = pm.HalfCauchy("σ", beta=5)
    ν = pm.Gamma("ν", alpha=2, beta=0.1)
    y_ = pm.StudentT("y", mu=f, lam=1.0/σ, nu=ν, observed=y)

    trace = pm.sample(1000, chains=1)
```

**Please provide the full traceback.**
```python
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "latent_var.py", line 22, in <module>
    f_true = np.random.multivariate_normal(mean_func(X).eval(),
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\graph.py", line 522, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\vm.py", line 1087, in make_all
    thunks.append(node.op.make_thunk(node,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cmodule.py", line 2405, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing m8f27cf6f6495a72b3883db0ff3f5d581f67a3adfd26460692f0372611b85620b: The specified module could not be found.
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.8.3
* Operating system: Windows 10
* How did you install PyMC3: pip

**Comment by AlexAndorra** [comment]
Thanks for reporting Hector! I guess it's already a good thing if this is not a problem with Anaconda...
This is out my league, so I can't really help here, but pinging @ahartikainen, to see if they saw something similar in PyStan 🤷‍♂️ In which case, this would probably mean this is not directly due to Theano.

**Comment by ahartikainen** [comment]
Are you sure that you are not mixing anaconda/defaults channel with conda-forge packages? There are some cornercases which can be fixed with using only one specified channel (e.g. geopandas needs one specific channel).

I would try first creating a new conda environment with conda-forge channel.

    conda create -n myenv python=3.8 -c conda-forge
    conda activate myenv
    conda install ...
    pip install ...

Also, is there a reason for not installing pymc3 from conda?

**Comment by hectormz** [comment]
Hi @ahartikainen I did not have Anaconda at all on this machine. I was doing everything with "vanilla" python. I know Pymc3 recommends using Anaconda, so I checked to see if that made a difference with the .DLLs on Windows. Up until now I had been fine using "vanilla" python with Pymc3 (and other packages).

**Comment by hectormz** [comment]
@AlexAndorra an update!

This does seem to be caused by DLL resolving in Python 3.8+ and Windows. After some tinkering, I found that the GCC dll's are not being found on this line in `Theano`:

https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L317

The solution is to add the directory to my gcc dll's:
```python
os.add_dll_directory('C:/Users/hectormz/scoop/apps/gcc/current/bin')
```

I'm not sure where this line should be added in `Theano`, but seemingly it can be added anywhere, even upstream in `PyMC3`. I also don't know the specifics of figuring out where the files are stored automatically. I suppose that I should add a `Theano` issue/PR request, but I know it's no longer maintained.

Worst case scenario, I think it would be worthwhile to add this somewhere in `PyMC3` for those of us using Python3.8+ on Windows.

**Comment by AlexAndorra** [comment]
Thanks for the detailed update @hectormz ! This is getting out of my current knowledge, so I'm adding @aseyboldt and @lucianopaz in the loop -- I'm pretty sure they'll have valuable input.

**Comment by hectormz** [comment]
This is a reminder to myself to see if anything has changed, or if anything is different with `aesara`

**Comment by hectormz** [comment]
Still happening with following:

## Versions and main components

* PyMC3 Version: 3.11.2
* Theano-PyMC Version: 1.1.2
* Python Version: 3.8.9
* Operating system: Windows 10
* How did you install PyMC3: pip

And even still with:
* Aesara: 2.0.7


But I still think the change might reside in `aesara` going forward

**Comment by hectormz** [comment]
This should eventually be addressed by https://github.com/pymc-devs/aesara/pull/408 once `pymc3` uses a newer version of `aesara`

**Comment by hectormz** [comment]
With the change in `aesara`, this is now fixed on the `v4` branch. Feel free to close this issue @AlexAndorra , unless you want to wait until this is included in a PyPI-released version first.

**Comment by michaelosthege** [comment]
Closing because the issue no longer applies to the latest versions.
