### ISSUE TITLE
Creating Non-Central Student T distribution

### ISSUE THREAD

**Issue by Moj-ild** [pymc-devs/pymc#3947]
I have been looking into creating the Non-Central Student T distribution using the idea from scipy, however, in scipy, it uses a special function called confluent hypergeometric function. Is there a way to or mathematical equation in your package that is close to this function as I am trying to create a class for this distribution and change NumPy functions into theano function? Because when I run the class code, the code just freezes and gives out the message:

> INFO (theano.gof.compilelock): Refreshing lock C:\Users\Admin\AppData\Local\Theano\compiledir_Windows-10-10.0.18362-SP0-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-3.7.6-64\lock_dir\lock

For reference to my code for the class can be found in the link in discourse [NCT Distribution Class](https://discourse.pymc.io/t/how-to-create-non-central-students-t-distribution-and-what-priors-to-use-with-the-distribution/5203)

**Comment by fonnesbeck** [comment]
Please ask usage questions on our [Discourse site.](https://discourse.pymc.io/) The issue tracker is for bugs only.
