### ISSUE TITLE
Sampler does not start for some datasets

### ISSUE THREAD

**Issue by synapsesanddendrites** [pymc-devs/pymc#3950]
I am running PyMC3 (ver 3.8) on Python (ver 3.7) on a Macbook (oS 10.12.6). I am using Spyder and installed everything with conda. I am trying to run inference with the same model (with slice sampling) on a number of datasets, which will be added to on an ongoing basis. Unfortunately, for about one in a hundred of these datasets, the sampler does not start and does not produce an error (it remains with no samples and ?s/draw for a long period). Otherwise everything works fine and the samplers converge (I am unable to see why it fails for some specific datasets by comparing them). I therefore have to manually restart the script at various points.

As it usually converges, a solution would be to wrap everything in a timeout command that produces an error after a certain period. I am unable to get this working with the timeout module due to the multithreading in PyMC3 (running on one core would be a very large drop in efficiency). Is there a way to reliably produce an error if the chain does not initiate?

**Comment by synapsesanddendrites** [comment]
I have found a solution using the 'signal' module (see https://discourse.pymc.io/t/timeout-on-pymc3-sampling-sample/4104).

**Comment by michaelosthege** [comment]
Issue refers to an outdated version and it looks like a workaround was found.
