### ISSUE TITLE
Kernel dies

### ISSUE THREAD

**Issue by jeffensen** [pymc-devs/pymc#3966]
Hi,

I am trying to get pymc3 running, but the Python Kernel always dies after NUTS sampling reaches 100%.

```python
from pymc3 import *
import numpy as np

mu, sigma = 0, 5 # mean and standard deviation
data =  np.random.normal(mu, sigma, 1000)

with Model() as model:
    # Parameters with priors
    mu  = Uniform('mu', lower = -10, upper = 10)
    std = Uniform('std', lower = 0, upper = 10)
    
    # Distribution of data
    obs = Normal('obs', mu = mu, sigma = std, observed = data)
    
    sampler = NUTS()
    trace = sample(2000, sampler)
    
az.plot_trace(trace)
```
As suggested here (https://github.com/pymc-devs/pymc3/issues/1788) I already upgraded pymc3 and theano package to master:

* PyMC3 Version: 3.9.0
* Theano Version: 1.0.4 + 51.gf1e4ec47c
* Python Version: 3.7.6
* Operating system: Ubuntu 18.04.4 LTS
* How did you install PyMC3: pip

**Comment by michaelosthege** [comment]
1. are there any error messages logged to the terminal running jupyter?
2. does it also happen with `cores=1` ?

**Comment by jeffensen** [comment]
1. yes there is the following error message:

/home/user/anaconda3/bin/python: symbol lookup error: /home/user/anaconda3/lib/python3.7/site-packages/mkl/../../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

2. yes, same behavior and same error message with:
```python
trace = sample(2000, sampler, cores=1)
```
Otherwise, it's 4 cores.

**Comment by jeffensen** [comment]
Googled the error and fixed the issue by running `conda update intel-openmp`
as described here: https://github.com/ContinuumIO/anaconda-issues/issues/10195
Thank you @michaelosthege for guiding me on that track

**Comment by isosphere** [comment]
I'm having the same issue that the above installation did not resolve. 

All I get in my output is:
```
INFO:pymc3:Sampling 8 chains for 1_000 tune and 1_000 draw iterations (8_000 + 8_000 draws total) took 729 seconds.
```

and in Jupyter:

```
[I 2021-07-28 11:15:44.597 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
```

Theano 1.1.2, pymc3 3.11.2, python 3.7.10, Ubuntu 20.04.2 LTS. Installed via conda. 

I'll update my comment if I can discover anything more by digging.

Is there a logger I should be tweaking the log level of to get better output?

u:

Upgraded pymc3 and aesara to the main branch git versions as recommended, confirmed by this import warning:

```
You are running the v4 development version of PyMC3 which currently still lacks key features. You probably want to use the stable v3 instead which you can either install via conda or find on the v3 GitHub branch: https://github.com/pymc-devs/pymc3/tree/v3
```

Versions are now reported as aesara 2.1.2 and pymc3 3-4.0

Inferencing is now much slower, so it'll take awhile for the result to be clear.

**Comment by michaelosthege** [comment]
PyMC3 doesn't make much use of the logger (contributions welcome), but maybe you can set the basic config to be more verbose.

**Comment by isosphere** [comment]
Looks like upgrading to the git main versions gives me an error message instead of a kernel crash:

```
MemoryError: Unable to allocate 20.9 GiB for an array with shape (8, 1000, 351370) and data type float64
```

Happily, this is a virtual machine on a host with a beastload of memory. I'll allocate more, set the logger to DEBUG for extra fun, and try again.

Yup, that did it. Looks like my issue was a lack of memory, and the current conda-forge release of pymc3 or theano does not catch this gracefully.
