### ISSUE TITLE
Rational Quadratic Kernels gives wrong results!

### ISSUE THREAD

**Issue by tirthasheshpatel** [pymc-devs/pymc#3968]
Here's the output of `RatQuad` kernel on `np.array([[1., 2.], [3., 4.]])`
```python
>>> x = np.array([[1., 2.], [3., 4.]])
>>> k = pm.gp.cov.RatQuad(1, 1., 1.)
>>> k(x, x).eval()
array([[1.        , 0.33333333],
       [0.33333333, 1.        ]])
```

This is a wrong result. Comparing with tensorflow_probability and custom implementation, the result should be ``np.array([[1., 0.2], [0.2, 1.]])``

```python
>>> x = np.array([[1., 2.], [3., 4.]])
>>> k = tfp.python.math.psd_kernels.RationalQuadratic(1., 1., 1.)
>>> k.matrix(x, x)
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.        , 0.19999999],
       [0.19999999, 1.        ]], dtype=float32)>
```

I was not able to identify what the problem is by looking briefly at the source. This came up while I was testing some PyMC4 kernels.

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.6.9
* Operating system: Linux
* How did you install PyMC3: git source

**Comment by junpenglao** [comment]
It should be 
```
k = pm.gp.cov.RatQuad(input_dim=2, alpha=1., ls=1.)
```
otherwise the 2nd dim is ignored.

**Comment by junpenglao** [comment]
FWIW tho, I am not sure if the slicing in https://github.com/pymc-devs/pymc3/blob/683faaa9d7e58701f0689b1a1fd4080151f7e057/pymc3/gp/cov.py#L396 is obvious to user - maybe a warning should be raised if the part of the input is ignored?

**Comment by tirthasheshpatel** [comment]
Yeah! My bad... I got confused between the `active_dims` and `input_dims` arguments!

**Comment by tirthasheshpatel** [comment]
Will try to work on it today!
