### ISSUE TITLE
Introduce class-level dimension and parameter info

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#3984]
This is a `Distribution` design change proposal that attempts to address some of the shape-based complexity and allow for random variable indexing.

## Changes

1) The first set of changes involve the addition of *required* class-level dimension and parameter information, which could take the following form:
- `Distribution.ndim_support: int`: the dimension of a distribution's support, and
- `Distribution.ndim_params: List[int]`: the dimensions of each required parameter (under a fixed "canonical" parameterization).

2) Next, a `Distribution` would be required to provide a class-level property, which we'll call `Distribution.params: List[Tensor]`, that returns the canonical parameterization in an order matching `Distribution.ndim_params` and satisfying `type(dist_obj).dist(*dist_obj.params) == dist_obj`.

## Motivation

The first set of changes are analogous to the operator-level information required by [`RandomVariable`](https://github.com/pymc-devs/symbolic-pymc/blob/add-symjax-support/symbolic_pymc/theano/ops.py#L84), which itself follows [this shape handling design and example Gist](https://gist.github.com/brandonwillard/d4ec9f9f2753d1d9ef1aab71799860f7) from four years back.  This information makes it much easier to generalize simple shape and sampler operations, [as demonstrated by this exposition detailing `RandomVariable`'s construction and capabilities](https://brandonwillard.github.io/random-variables-in-theano.html).

The second change&mdash;combined with the first&mdash;makes it possible to efficiently index a wide range of random variables.  For example, with these changes, it's possible to perform the following index "lift": `MvNormal('a', mu, Sigma)[idx] == MvNormal('a', mu[idx], Sigma[idx])`.  
With the ability to index a random variable, samples can be draw directly from the indexed subset, instead of wastefully sampling the entirety of `MvNormal('a', mu, Sigma)` and discarding the unused samples by indexing.  The same is true for log-likelihood calculations over an indexed subset of a random variable, which is required&mdash;for example&mdash;when computing the likelihoods of mixtures with time varying parameters (conditional on known mixture components).

## Discussion

To be clear, this proposal does not include the addition of indexing operations for `Distribution` or any other PyMC3 classes.

For many basic distributions, the information provided by 1) and 2) is sufficient for implementing an index lift, but, for cases where it is not, we could provide some class-level means of providing the necessary support/parameters mappings.

An implication in 1) and 2) is that the `Distribution` constructor signatures be standardized, and that a single parameterization must be chosen in order to establish a canonical parameterization.  This requirement is stricter than necessary, since we could provide the information required in 1) and 2) for all accepted parameterizations; however, the strictness reduces complexity, so, unless there are concrete limitations involved in the use of a single canonical parameterization, this approach is preferable.  Otherwise, the non-canonical parameterizations can coexist alongside other ones, just as they currently do (e.g. `MvNormal.__init__`'s optional `tau` and `chol` arguments), and, in general, the canonical parameterizations can simply follow the current parameterizations implied by the current `Distribution.__init__` argument orders.

**Comment by lucianopaz** [comment]
I really like this but I would prefer `Distribution.ndim_params` and the returned `Distribution.params` to be dictionaries `{parameters_name: value}` so that `type(dist_obj).dist(**dist_obj.params) == dist_obj`.
Another thing that i hadn't thought of before is how would these things apply to `Mixture` and `DensityDist`. The `Mixture` distribution may be problematic because it can either accept a list of distributions or a multidimensional distribution as the `comp_dist`. The `DensityDist` is a problem because it has no explicit knowledge of parameters or support, or anything for that matter.

**Comment by brandonwillard** [comment]
> I really like this but I would prefer `Distribution.ndim_params` and the returned `Distribution.params` to be dictionaries `{parameters_name: value}` so that `type(dist_obj).dist(**dist_obj.params) == dist_obj`.

That sounds good, as long as they're ordered dictionaries.


> Another thing that i hadn't thought of before is how would these things apply to `Mixture` and `DensityDist`. The `Mixture` distribution may be problematic because it can either accept a list of distributions or a multidimensional distribution as the `comp_dist`. The `DensityDist` is a problem because it has no explicit knowledge of parameters or support, or anything for that matter.

A `Mixture` is polymorphic/a parameterized type; i.e. it requires the types of its mixture components in order to be fully/concretely defined.  We can implement `Mixture` as a meta class that generates concrete `Distribution` classes given its inputs/mixture components.  This matches the high-level math/type theory better anyway.

`DensityDist` is a naturally troublesome idea in these regards, but, again, we can probably use the same "meta" approach in this case.

Also, recall that it's possible to get concrete dimension information from Theano objects (i.e. via the `.ndim` property), so we can attempt to use this to our advantage in the proposed metaclass `__new__` constructors.

**Comment by brandonwillard** [comment]
This is covered by the [`v4`](https://github.com/pymc-devs/pymc3/labels/v4) work.
