### ISSUE TITLE
GP Periodic Kernel uses uncommon formula

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/pymc#3987]
As discussed [on the Discourse](https://discourse.pymc.io/t/gp-periodic-kernel-is-pymc3-different-from-other-sources/5348/2), PyMC3's `Periodic` kernel is [implemented as](https://docs.pymc.io/api/gp/cov.html#pymc3.gp.cov.Periodic):

![equation](https://latex.codecogs.com/svg.latex?k%28x%2C%20x%27%29%20%3D%20%5Cmathrm%7Bexp%7D%5Cleft%28%20-%5Cfrac%7B%5Cmathrm%7Bsin%7D%5E2%28%5Cpi%20%7Cx-x%27%7C%20%5Cfrac%7B1%7D%7BT%7D%29%7D%7B2%20%5Cell%5E2%7D%20%5Cright%29)

But, in other sources such as David Duvenaud’s [Kernel Cookbook](https://www.cs.toronto.edu/~duvenaud/cookbook/), as well as the [NB for mean and cov functions](https://docs.pymc.io/notebooks/GP-MeansAndCovs.html?highlight=periodic#Constructing-Periodic-using-WarpedInput), the formula is given by:
![equation](https://latex.codecogs.com/svg.latex?k%28x%2C%20x%27%29%20%3D%20%5Cmathrm%7Bexp%7D%5Cleft%28%20-%5Cfrac%7B2%20%5Cmathrm%7Bsin%7D%5E2%28%5Cpi%20%7Cx-x%27%7C%20%5Cfrac%7B1%7D%7BT%7D%29%7D%7B%5Cell%5E2%7D%20%5Cright%29)

According to @bwengals, this changes the interpretation of the lengthscale: a constant factor changes how you think of the lengthscale and what priors you’d set on it. 
So, **ideally, PyMC3's implementation should be changed to the second equation above** -- note that this would not be backwards-compatible then, so it should be accompanied by a warning. _Does anybody disagree?_

A final note: it seems like we’re using another slightly different implementation in PyMC**4**:

![equation](https://latex.codecogs.com/svg.latex?k%28x%2C%20x%27%29%20%3D%20%5Csigma%5E2%20%5Cmathrm%7Bexp%7D%5Cleft%28%20-%5Cfrac%7B2%5Cmathrm%7Bsin%7D%5E2%28%5Cpi%20%7C%7Cx-x%27%7C%7C%5E2%20%5Cfrac%7B1%7D%7BT%7D%29%7D%7B%5Cell%5E2%7D%20%5Cright%29)
@tirthasheshpatel do you confirm it is equivalent to the standard formula? I notice there is a new `sigma ** 2` parameter and the distance between `x` and `x'` is squared 🤔

**Comment by tirthasheshpatel** [comment]
> ![equation](https://camo.githubusercontent.com/c1f830a358e242856e484c6ef53ef403f7d917d8/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f6b25323878253243253230782532372532392532302533442532302535437369676d61253545322532302535436d617468726d2537426578702537442535436c6566742532382532302d25354366726163253742322535436d617468726d25374273696e253744253545322532382535437069253230253743253743782d7825323725374325374325354532253230253543667261632537423125374425374254253744253239253744253742253543656c6c253545322537442532302535437269676874253239)
> @tirthasheshpatel do you confirm it is equivalent to the standard formula? I notice there is a new `sigma ** 2` parameter and the distance between `x` and `x'` is squared 🤔

Where did you see this equation in PyMC4? Is it present in the docs or notebooks? Actually PyMC4 doesn't use this. Instead, it uses the implementation from the kernel cookbook.  And yes, the `sigma ** 2` is the amplitude which was implemented in PyMC3 by externally multiplying the kernel with it.

**Comment by tirthasheshpatel** [comment]
Oh sorry! It is present in the notebooks. I will change that. Thanks for noticing!

**Comment by AlexAndorra** [comment]
Yes, it was in the NB with all the cov functions, in your PR.
FWIW, I find it better to integrate to amplitude parameter into the kernel formula, as we do in PyMC4 👍
