### ISSUE TITLE
Systematized Distribution testing overlooks Theano arguments

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#4001]
I noticed that our testing framework doesn't perform tests using Theano arguments (not within our systematized tests&mdash;like `TestMatchesScipy`&mdash;at least).  

This seems like a pretty big oversight, and appears to have let #3999 go unchecked.

In general, I would say that Theano arguments make a much better default than NumPy, so perhaps we should consider changing our test framework to use them.

_Originally posted by @brandonwillard in https://github.com/pymc-devs/pymc3/pull/4000#issuecomment-653925924_

**Comment by ricardoV94** [comment]
@brandonwillard I think the main `check_logp` and `check_logcdf` (the later after #4736) in `TestMatchesScipy` are now testing with aesara arguments via `shared` variables. Should we close this one?

**Comment by brandonwillard** [comment]
If we're talking about `v4`, then the concerns expressed in this issue aren't really the same/present.  This issue was prompted by errors in our our mixed use of symbolic/non-symbolic values (i.e. special handling for values that could be either type).
