### ISSUE TITLE
Progress bar (pymc 3.9) does not work with Voila-dashboard view

### ISSUE THREAD

**Issue by gg2uah** [pymc-devs/pymc#4013]
Hello,

I was trying to use pymc3 (3.9.2) with Voila (https://voila.readthedocs.io/en/stable/) and I cannot see the progress bar running in the Voila-dashboard view (it works fine with the classic notebook). All i see is a grey box:

<img width="834" alt="1" src="https://user-images.githubusercontent.com/56398096/87561987-69712d00-c68b-11ea-93eb-b1c2a5ebc564.png">

But when i use pymc3 (3.7), which has the older version of progress bar, I can see the progress bar running just fine. 

You can check it here:
https://mybinder.org/v2/gist/atharvahans1/68044ff6d1f093b7d1d788929231754d/master

How can I fix this?

Thanks,
Atharva

**Comment by fonnesbeck** [comment]
I've had similar behavior running notebooks in VScode. However, this should be reported to fastprogress, as they are the maintainers of the progress bar.
