### ISSUE TITLE
MCMC.sample missing call to _halt

### ISSUE THREAD

**Issue by jscholz** [pymc-devs/pymc#402]
Just noticed that the upgrade to 2.3 broke some code I had which was monitoring a variable and calling self._model.halt() from within a step method.  

Poked around and it seems like the function MCMC.sample is missing the following block, which is at the end of it's parent:

``` python
        if self.status == 'halt':
            self._halt()
```

EDIT: seems related to an issue from 2 months back regarding isample: https://github.com/pymc-devs/pymc/issues/323

**Comment by fonnesbeck** [comment]
This block is inside `_loop` (line 333 of `MCMC.py`), which is called by `sample` (line 249 of `Model.py`). Are you saying that calls to `MCMC.halt()` are not working?

**Comment by jscholz** [comment]
Yes, I'll submit a small pull request to show what I'm up to

**Comment by fonnesbeck** [comment]
Closing. Update if this is still relevant.
