### ISSUE TITLE
sample_posterior_predictive does not handle InferenceData well

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4025]
`sample_posterior_predictive` seems to require an old-school trace, but does not directly accept an `InferenceData` object. There is an easy workaround to just call `sample_posterior_predictive(inference_object.trace)` but I think it would be nice if it would detect that.

**Comment by rpgoldman** [comment]
@michaelosthege has fixed this to the best of my knowledge, and there are even tests. If you can't use an inference data in place of a trace, it's a bug: please give details.

**Comment by rpgoldman** [comment]
Plus, in general `fast_sample_posterior_predictive` is probably preferable...

**Comment by twiecki** [comment]
I see, this is only fixed on master by https://github.com/pymc-devs/pymc3/pull/4006. Should probably do a new bugfix release.

**Comment by AlexAndorra** [comment]
Yeah probably. Could be a good time to update the docs too 😉
