### ISSUE TITLE
Release 3.9.3

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4026]
We do have a few new features and bugfixes on master so we should cut a new release. Anyone volunteering to be release manager?

**Comment by kyleabeauchamp** [comment]
I may have some time over the weekend to help with reviews etc.

**Comment by twiecki** [comment]
Do you want to be release manager for this one then? We have a pretty good
and quick process.

**Comment by kyleabeauchamp** [comment]
Yeah, I can volunteer as long I get some instruction.

**Comment by twiecki** [comment]
Awesome, appreciate it! @michaelosthege who was the other release manager last time? are there some instructions written down somewhere? Otherwise we should probably start jotting that down.

**Comment by michaelosthege** [comment]
Alex did v3.9.2. Instructions are here: https://github.com/pymc-devs/pymc3/wiki/PyMC3-Release-Checklist

**Comment by twiecki** [comment]
Perfect. @kyleabeauchamp ideally our process gets better and better documented each time.

**Comment by kyleabeauchamp** [comment]
If anyone has any critical PRs that need merging before release, we should finalize those today IMHO, otherwise I think we're on track for release.

**Comment by kyleabeauchamp** [comment]
I added the 3.9.3 milestone to all PRs merged after the previous 3.9.2 release.

**Comment by twiecki** [comment]
@kyleabeauchamp All PRs tagged for this release are merged. You can go ahead and release 3.9.3.

**Comment by kyleabeauchamp** [comment]
I was drafting a release but I noticed that there are build failures on master: https://travis-ci.org/github/pymc-devs/pymc3/builds/712731940

**Comment by kyleabeauchamp** [comment]
```
            elif pickle_backend == 'dill':
                try:
>                   import dill
E                   ModuleNotFoundError: No module named 'dill'
pymc3/parallel_sampling.py:435: ModuleNotFoundError
```

**Comment by kyleabeauchamp** [comment]
```
E   pytest.PytestDeprecationWarning: Passing arguments to pytest.fixture() as positional arguments is deprecated - pass them as a keyword argument instead.
```

**Comment by kyleabeauchamp** [comment]
OK we have a green build on master again.  What is our plan on the various open PRs that have been approved?  Do we ask people to update their branches and then merge once green?

**Comment by michaelosthege** [comment]
> OK we have a green build on master again. What is our plan on the various open PRs that have been approved? Do we ask people to update their branches and then merge once green?

Yes. If the PR authors checked the "maintainers can edit" box, you can also do it for them.

**Comment by AlexAndorra** [comment]
Maybe we can also just relaunch the tests jobs on each PR: on the Mauna Loa PR, I just pushed commits without rebasing on master and tests passed, so it should work in most cases 😉 
Otherwise, what Kyle suggested sounds good 👌

**Comment by AlexAndorra** [comment]
I just relaunched the Travis jobs on all PRs that could be included in 3.9.3 -- let's see how it goes 😉

**Comment by twiecki** [comment]
I think we already merged everything in we wanted for 3.9.3, let's just push the trigger :).

**Comment by AlexAndorra** [comment]
Yeah, that's also fine by me 🤷‍♂️ 
Just an FYI, I just rebased off master several PRs that could be included. Let's see whether the test turn green 😬

**Comment by twiecki** [comment]
I suppose doc PRs that just need merging after rebasing are fine, but it's easy to get on the treadmill of "just this one more PR" and delay a release.

**Comment by kyleabeauchamp** [comment]
Release is made: https://github.com/pymc-devs/pymc3/releases/tag/v3.9.3

**Comment by kyleabeauchamp** [comment]
I got an email notification about a github actions failure.  It looks like the github release action was expecting the pypi release to be available for installation, but it was not able to find it.  Does that sound familiar?

**Comment by michaelosthege** [comment]
> I got an email notification about a github actions failure. It looks like the github release action was expecting the pypi release to be available for installation, but it was not able to find it. Does that sound familiar?

Yes this happened the last times too. **Don't re-trigger** the pipeline. PyPI won't accept another upload of the same version number. Just ignore it. 

I guess we should take out this installation step then. Though it works for my pyrff package with an even shorter delay..

**Comment by twiecki** [comment]
Thanks @kyleabeauchamp!!
