### ISSUE TITLE
model_to_graphviz display bug when missing value is involve.

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc#4043]
```python
x = np.random.randn(10) + 10.
x = np.concatenate([x, [np.nan], [np.nan]])
x = np.ma.masked_array(x, np.isnan(x))

with pm.Model() as m:
    a = pm.Normal('a')
    pm.Normal('x', a, 1., observed=x)
    pm.model_to_graphviz(m)
```

gives: 
![image](https://user-images.githubusercontent.com/12952641/89727092-0bcdc780-da22-11ea-9af8-51183ec913ca.png)

which is technically correct as we define x_missing as a NoDistribution: https://github.com/pymc-devs/pymc3/blob/ee57bed9aa5f73dc48081dd3c82267dd4f0f2834/pymc3/model.py#L1672-L1677

the reason of doing so is that we fill in the missing value into the original data: https://github.com/pymc-devs/pymc3/blob/ee57bed9aa5f73dc48081dd3c82267dd4f0f2834/pymc3/model.py#L1683-L1684

and to not double count the log_prob, the data tensor need to be a FreeRV (so we sample from it) with no log_prob (as the log_prob already accounted for in `x` in this example).

I think the easiest way to fix is to overwrite the `_repr_` here with the `_repr_` from parent.

**Comment by junpenglao** [comment]
Actually, to get the graphviz display correctly there is a bit more complicated, as currently the logpt is not connected to any ancestor. we can put a logic in model_graph.py so it [replace NoDistribution](https://github.com/pymc-devs/pymc3/blob/master/pymc3/model_graph.py#L141) to the underlying parent_dist, but the graph link will still be incorrect...

**Comment by nicospinu** [comment]
Thank you @junpenglao

**Comment by ricardoV94** [comment]
@junpenglao What would be the correct graph here? Something like this?

![image](https://user-images.githubusercontent.com/28983449/105174586-1046f200-5b23-11eb-827f-49ecd082316a.png)


`
