### ISSUE TITLE
Update release instructions

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4046]
From: https://github.com/pymc-devs/pymc3/issues/4026

> > I got an email notification about a github actions failure. It looks like the github release action was expecting the pypi release to be available for installation, but it was not able to find it. Does that sound familiar?

> Yes this happened the last times too. Don't re-trigger the pipeline. PyPI won't accept another upload of the same version number. Just ignore it.

> I guess we should take out this installation step then. Though it works for my pyrff package with an even shorter delay.."

**Comment by AlexAndorra** [comment]
FYI, the release checklist is [here](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Release-Checklist)

**Comment by michaelosthege** [comment]
Actually, this is already listed under "Troubleshooting".
