### ISSUE TITLE
Parameter Samples all have the same value 

### ISSUE THREAD

**Issue by cmp1** [pymc-devs/pymc#4052]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

I have developed a copy of the Challenge Shuttle disaster model in [here](https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter2_MorePyMC/Ch2_MorePyMC_PyMC3.ipynb)

Where I am modelling the probability of hitting zero stock (i.e. a stock out situation) as a function of current stock levels to answer the question: 

'If your current inventory reaches N '000 tonnes, what is the probability of running out of stock'

I have implemented a similar model but the output of for parameters Beta( for the logistic function) and Alpha (the bias term) are all the same value.

**Note: stock_inventory  mean value is quite high, 12.3k tonnes. Stock_out is a binary [0, 1] bounded feature.**

I would be really grateful if someone could please point out where I have made an error here, thank you!

**Please provide a minimal, self-contained, and reproducible example.**

```python
# Sort values by inventory value
df_a.sort_values('vault_inventory', inplace=True)

# Get inventory vals
vault_inventory_observed = np.array(df_a.loc[:, 'vault_inventory']) # Note - Mean val is 12,315 tonnes, std is 9043 tonnes

# Stock out 0,1 
stock_out_counts = np.array(df_a.loc[:, 'stock_out'])

# Define model
import theano.tensor as tt

# Model stock out probability as a function of inventory
with pm.Model() as stock_out_model:
  beta = pm.Normal("beta", mu=0, tau=0.001, testval=0)
  alpha = pm.Normal("alpha", mu=0, tau=0.001, testval=0)
  p = pm.Deterministic("p", 1.0/(1. + tt.exp(beta * vault_inventory_observed + alpha)))
  observed = pm.Bernoulli("bernoulli_obs", p, observed=stock_out_counts)
  step = pm.Metropolis()
  trace = pm.sample(30000, step=step, start=start)
  burn_trace = trace[10000::2]

# Get samples from trace
alpha_samples = burn_trace["alpha"][:, None] # All return values are -1.81e-08
beta_samples = burn_trace["beta"][:, None] # All return values are -0.00057355

```

**Please provide the full traceback.**
```python

beta_samples all have value -0.000573
alpha_samples all have value -1.81e-08


```

**Please provide any additional information below.**
Thank you for your help.

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3
* Operating system: Windows 10
* How did you install PyMC3: (conda/pip): Conda install

**Comment by aseyboldt** [comment]
Closing, as this looks like a question for discourse, I don't think it is a pymc bug.

I don't see the problem right now, but a few pointers:
- Don't use metropolis, the default sampler is better. If it gives you an error, that might point you to the solution of the problem
- Use the logit_p argument to `Bernoulli` (you might be having trouble with overflows)
- Don't specify testval
- No need to use tau in `pm.Normal`, sigma is more intuitive.
- Don't specify `start` in sample
- Check your data. Are there any nan values? infs?...

**Comment by cmp1** [comment]
Your suggestions helped a lot - I found removing Metropolis and adding SD
instead of tau worked - many thanks, much appreciated!
