### ISSUE TITLE
Confusion of precision and variance in autoregression (AR) example

### ISSUE THREAD

**Issue by mschmidt87** [pymc-devs/pymc#4059]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

In the autoregressive model example (https://docs.pymc.io/notebooks/AR.html), the variance and precision of the innovation term in the model are confused when the artificial data is generated and later plotted to compare posterior samples of the precision with the true value. 

In cell [3], `true_tau` should read `true_std` (or something like that) and then later when the true value is compared to the posterior samples, we should plot the inverse of the squared (`1/true_tau **2` or better `1/true_std**2`). 
With the chosen value of 1 for the precision, this doesn't make a difference of course, but it is slightly misleading for readers (at least it confused me).

(I skipped most of the template for issue because this is a pure documentation issue).

**Comment by fonnesbeck** [comment]
Good catch. Really, the `AR1` class should accept either precision or sd, but for some reason it only accepts precision.

**Comment by mschmidt87** [comment]
What would you suggest to do, just change the example or extend the `AR1` class to accept precision? I would be happy to try to create a PR, either way.

**Comment by fonnesbeck** [comment]
I've just fixed the notebook; feel free to change the AR1 model if you are game.
