### ISSUE TITLE
Automated convergence diagnostics during sampling

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#406]
I'd like to automate the Gelman-Rubin statistic within `psample` so that it can optionally be calculated periodically, and could potentially be used to terminate sampling early.

**Comment by jsalvatier** [comment]
That sounds very useful.

**Comment by springcoil** [comment]
Has this been done by other stuff? Like the ADVI improvements for example?

**Comment by springcoil** [comment]
@fonnesbeck Any views? @twiecki @aseyboldt

**Comment by junpenglao** [comment]
I purpose closing this issue. Rhat is not the best metric to judge convergence. There are past discussions (also on the Stan side) to use effective sample size as a metric (e.g., stop sampling once effective_n >= 2000), but I think it is difficult to archive.

**Comment by ColCarroll** [comment]
I think aseyboldt's contributions here are good enough to close.
Automating something like this is interesting but super tricky and I fear
it would be misleading for the library to just say "you've got a good
sample now". In particular, I would never feel comfortable saying that if
only one chain was used!

**Comment by ColCarroll** [comment]
(feel free to reopen if this would be useful)
