### ISSUE TITLE
Adding doc notebook for log Gaussian Cox process

### ISSUE THREAD

**Issue by ckrapu** [pymc-devs/pymc#4084]
I've written a short tutorial on the LGCP and its marked Poisson process extension per the discussion here: https://discourse.pymc.io/t/cox-process-in-pymc3/389/2. The notebook can be viewed [here](https://github.com/ckrapu/pymc3/blob/master/docs/source/notebooks/log-gaussian-cox-process.ipynb). It requires a small CSV data file with a few hundred lines. I'm not aware of any specific checklist for doc notebooks so I followed these guidelines:

* Use Jupyter settings for high-resolution images (e.g. `%config InlineBackend.figure_format = 'svg'
`)
* Included required dataset so that it can be loaded using `pm.get_data`
* Added a watermark and authorship statement
* Ran with most recent PyMC3 version

One potential issue is that the entire run time is ~5 hours since part of the model involves a latent GP with 350 points in space. I didn't try using ADVI in this notebook. Additional feedback / suggestions would be greatly appreciated!

**Comment by AlexAndorra** [comment]
This sounds like a great PR @ckrapu !
You'll find the [NB style guide here](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style), and regarding your points:

> Included required dataset so that it can be loaded using `pm.get_data`

Yep, perfect 👌 

> One potential issue is that the entire run time is ~5 hours

I don't see this as a big issue personally: if the model is useful and interesting, it's worth it! Plus, I'm all in favor of more advanced educational resources on our repo. As an example, the last model of the GP Mauna Loa 2 NB takes 20 hours to sample, but it's an amazing example, as it shows how to do advanced GP stuff with PyMC3.

Looking forward to your PR, and don't hesitate if you have questions 😉

**Comment by ckrapu** [comment]
Got it, thanks for linking to the style guide! I do have an additional question. I can see that I'll have to add an entry in `table_of_contents_examples.js` and that Sphinx will autogenerate a thumbnail from the last image in the notebook. Are you aware of any other locations where I'll have to specify details for the new notebook?

**Comment by AlexAndorra** [comment]
Mmmh, I don't think so but you can check by doing a `grep` on another notebook that you know is well catalogued and see where it appears 🤷‍♂️
