### ISSUE TITLE
PYMC3/Pytorch/Transformers incompatibility resulting in jupyter lab kernel restarting

### ISSUE THREAD

**Issue by azdaly** [pymc-devs/pymc#4094]
#4094 PYMC3/Pytorch/Transformers incompatibility results in jupyter lab kernel restarting. I believe the issue is with an incompatibility between pytorch and HDF5. Installing the latest PYMC3 version using the following

```unix
conda install -c conda-forge pymc3
```   

Results in killing and restarting the jupyter lab notebook when the following lines were present:  

```python
from tokenizers.implementations import ByteLevelBPETokenizer
from tokenizers.processors import BertProcessing
import torch
from torch.utils.data import Dataset
from transformers import( DistilBertConfig,
                                           DistilBertForMaskedLM,
                                           LineByLineTextDataset, DistilBertTokenizer, 
                                           DataCollatorForLanguageModeling,
                                          Trainer, TrainingArguments, pipeline)
```   

Removing the above import lines, or the entire PYMC3 module was sufficient to resolve the problem. 

## Versions and main components

* PyMC3 Version: Whichever one conda installs on 9/10/20
* Transformers: 3.1.0
* Torch: 1.5.1 
* How did you install PyMC3: conda

**Comment by ferrine** [comment]
What about pytorch 1.6?

**Comment by azdaly** [comment]
I haven't checked yet - you're welcome to close this issue - it turns out it's very specifically an h5py problem...

**Comment by ferrine** [comment]
Ok
