### ISSUE TITLE
unreachable code in pymc3/model.py?

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4098]
I haven't figured out (yet) what the intended behaviour is here, so just opening as a placeholder. In pymc3/model.py, there is this:

```python
    def get_context(cls, error_if_none=True) -> Optional[T]:
        """Return the most recently pushed context object of type ``cls``
        on the stack, or ``None``. If ``error_if_none`` is True (default),
        raise a ``TypeError`` instead of returning ``None``."""
        idx = -1
        while True:
            try:
                candidate = cls.get_contexts()[idx]  # type: Optional[T]
            except IndexError as e:
                # Calling code expects to get a TypeError if the entity
                # is unfound, and there's too much to fix.
                if error_if_none:
                    raise TypeError("No %s on context stack" % str(cls))
                return None
            return candidate
            idx = idx - 1
```

The line `idx = idx - 1` is unreachable, as far as I can tell. Rather than just removing it, it's probably best to figure out what it was meant to do...I'll get back to this later

**Comment by rpgoldman** [comment]
As of fe0b52f7a this wasn't vacuous: there was a check for `isinstance(candidate, cls)`. 

Returning unconditionally was added in 501146f70, when I split the context stacks instead of having only a single context stack with different kinds of entries mixed.  I can simplify this.

**Comment by rpgoldman** [comment]
Waiting to see if this passes the tests.

**Comment by junpenglao** [comment]
Thanks for fixing it @rpgoldman and thanks for reporting @MarcoGorelli
