### ISSUE TITLE
positive definite error from quadpotential.pyc

### ISSUE THREAD

**Issue by jangevaare** [pymc-devs/pymc#410]
Hello,
I have a model here that works fine with Hamiltonian Monte Carlo (when using guess_scaling or find_hessian) and Metropolis Hastings. When I attempt to run it with the No-U-Turn Sampler, or HMC without guess_scaling or find_hessian, I receive a positive definite error from quadpotential.pyc

Is this behaviour expected for some models?

```
with model:
    ...:     stepNUTS = NUTS()
    ...:     traceNUTS = sample(3000, stepNUTS, start)
---------------------------------------------------------------------------
PositiveDefiniteError                     Traceback (most recent call last)
<ipython-input-30-3c6f74c12d1e> in <module>()
      1 with model:
----> 2     stepNUTS = NUTS()
      3     traceNUTS = sample(3000, stepNUTS, start)

/Users/justin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pymc/step_methods/nuts.pyc in __init__(self, vars, scaling, step_scale, is_cov, state, Emax, target_accept, gamma, k, t0, model)
     66 
     67 
---> 68         self.potential = quad_potential(scaling, is_cov, as_cov=False)
     69 
     70         if state is None:

/Users/justin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pymc/step_methods/quadpotential.pyc in quad_potential(C, is_cov, as_cov)
     33         return QuadPotential_SparseInv(C)
     34 
---> 35     partial_check_positive_definite(C)
     36     if C.ndim == 1:
     37         if is_cov != as_cov:

/Users/justin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pymc/step_methods/quadpotential.pyc in partial_check_positive_definite(C)
     56     if len(i):
     57         raise PositiveDefiniteError(
---> 58             "Simple check failed. Diagonal contains negatives", i)
     59 
     60 

PositiveDefiniteError: Scaling is not positive definite. Simple check failed. Diagonal contains negatives. Check indexes [0 1] 
```

**Comment by jsalvatier** [comment]
Looks like the hessian at the default point (model.test_point https://github.com/pymc-devs/pymc/blob/master/pymc/step_methods/nuts.py#L55) has some negative diagonal elements, specifically the first and second variables. Try passing the `start` to `NUTS`, it will automatically `guess_scaling` there.

Question: is there a more intuitive error message that would have made it more clear to you what was going on? Or maybe more intuitive behavior from NUTS?

**Comment by twiecki** [comment]
Maybe we could point out that this is likely due to a bad starting point and the user should run find_MAP() and pass in `scaling=start` (I think that's what the kwarg is called, no?).

**Comment by jangevaare** [comment]
Thank you gentlemen.

@jsalvatier how about: `Scaling for the momentum distribution is not positive definite at model.test_point, try specifying a different point (e.g. MAP) within the step method`

**Comment by jsalvatier** [comment]
I think that might be a little too specific to this situation, but I think
describing what may have happened and making the suggestion to try a
different point (say the MAP) is a good idea.
