### ISSUE TITLE
mamba failure on travis

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4101]
```
+++mamba env update -f environment-dev.yml
+++'[' -x /usr/lib/command-not-found ']'
+++/usr/lib/command-not-found -- mamba
No command 'mamba' found, did you mean:
 Command 'samba' from package 'samba' (main)
mamba: command not found
```

**Comment by twiecki** [comment]
Seems to be resolved.

**Comment by gmingas** [comment]
I still get this error in my fork [here](https://travis-ci.com/github/alan-turing-institute/pymc3/builds/186193161) although it does not appear in the PR we created which has the exact same code [here](https://travis-ci.org/github/pymc-devs/pymc3/builds/729589372).

Is there a know solution to this?
