### ISSUE TITLE
Getting error in calculation of deviance information criterion (DIC)

### ISSUE THREAD

**Issue by rrptm** [pymc-devs/pymc#4102]
while execution of ```pm.dic(trace,model=model)```
i am getting this error ```AttributeError: module 'pymc3' has no attribute 'dic'```

## Versions and main components

* PyMC3 Version: 2.9.3
* Python Version: 3.7.4
* Operating system: windows 10
* How did you install PyMC3: pip

**Comment by MarcoGorelli** [comment]
Hi @rrptm - that's because `pymc3` doesn't have a `dic` attribute...what were you trying to do?

> PyMC3 Version: 2.9.3

3.9.3, I guess?

EDIT
----

Ah, I see, it comes from the docs https://pymc3.readthedocs.io/en/latest/notebooks/model_comparison.html#Deviance-Information-Criterion-(DIC) . This was removed here https://github.com/pymc-devs/pymc3/pull/2754 

```git
$ git log -S pm.dic docs/source/notebooks/model_comparison.ipynb
commit 391f5fd143b5a963daa869508adf1eaa051c346e
Author: Osvaldo Martin <aloctavodia@gmail.com>
Date:   Thu Dec 14 00:41:42 2017 -0300

    add deprecation warning BPIC and DIC (#2754)
    
    * add deprecation warning BPIC and DIC
    
    * fix typo
    
    * do not hide warning messages

commit dad7d7f2bb33ed50875440cf3dfbd800d30a2297
Author: aloctavodia <aloctavodia@gmail.com>
Date:   Thu Jun 8 13:02:39 2017 +0200

    add example, fix minor issues
```

 I guess the docs still need updating

**Comment by AlexAndorra** [comment]
I don't think this link is our official doc (I have actually never seen it before 😅 ): [these are our docs](https://docs.pymc.io/api/stats.html), and `.dic` has indeed been removed.
Closing now, as people should use use `az.loo` or `az.waic` instead, as [discussed on Discourse](https://discourse.pymc.io/t/getting-error-during-calculation-of-deviance-information-criterion-dic/5782) 🖖

**Comment by MarcoGorelli** [comment]
> I have actually never seen it before sweat_smile

:rofl:

@AlexAndorra is there a way to remove the readthedocs documentation, to avoid confusion? It looks like they were generated from an old commit, on the bottom it says

> © Copyright 2016, John Salvatier, Christopher Fonnesbeck, Thomas Wiecki. Revision e4692c76. 

which is a commit from 2017

```
$ git show -s e4692c76
commit e4692c769ec5b08f106cac8aa7e95b364e22d247
Author: aloctavodia <aloctavodia@gmail.com>
Date:   Fri Nov 10 09:55:27 2017 -0300

    improve docstring
```

**Comment by MarcoGorelli** [comment]
Also, it looks like readthedocs is still trying to generate these docs daily https://readthedocs.org/projects/pymc3/builds/

cc @twiecki

**Comment by AlexAndorra** [comment]
Ha ha this definitely looks like an artefact from the past 😆 
I think we shoudl get rid of this to avoid confusion, but @twiecki knows more about the history than me

**Comment by twiecki** [comment]
Ah yeah, never switched that off but we should.
