### ISSUE TITLE
jitter init should not give up if first try is nan

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4107]
Our default init is quite brittle when it comes to models that easily have nans or -infs for certain parts of the parameter space. STAN retries multiple times if the current value is no good and I think we should too. We could output to the user how many times we had to try and if it's high enough maybe tell them to try and make the model more robust.

**Comment by ricardoV94** [comment]
I could work on this. Does anyone happen to have a simple "brittle" model that could be used as a testing case?

**Comment by twiecki** [comment]
You could try with a model like htis:
```python
with pm.Model():
    pm.HalfNormal('x', transform=None)
```

I haven't tried it so it might not work with this, but maybe can serve as a starting point.

**Comment by ricardoV94** [comment]
Seems to work after a few tries. Thanks
