### ISSUE TITLE
Apply black formatter

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4109]
xref https://github.com/pymc-devs/pymc3/pull/4108#issuecomment-694462527

Reviewing PRs which change code _and_ change formatting can be tricky, so my suggestion is to apply `black` to batches of 10-15 files at a time, merge those in, and then add `black` to `.pre-commit-config.yaml`.

This would make for a good beginner-friendly issue. Make sure you're using `black` version 20.8b1 for this.

See  #4110 for an example of how to open a PR for this

EDIT
----

have removed the list of files as it looks like existing PRs might be enough to close this off. Please see #4095 for a similar issue to tackle

EDIT2
----

As of 2020-10-08, existing PRs should be enough to address all files. To close this issue, a pre-commit hook should be added

**Comment by aliakbars** [comment]
I'd like to help on this. Are there prioritised files?

**Comment by MarcoGorelli** [comment]
@aliakbars that's great! I don't think there's any prioritisation, no

**Comment by aliakbars** [comment]
@MarcoGorelli Will the above checklist get updates automatically?

**Comment by MarcoGorelli** [comment]
Nope, been doing it manually do far

**Comment by satrio-hw** [comment]
Hi, I'd like to help.. I'm working on :

- [x]  pymc3/tests/test_shape_handling.py
- [x]  pymc3/tests/test_ode.py
- [x]  pymc3/tests/test_text_backend.py
- [x]  pymc3/tests/test_tracetab.py
- [x]  pymc3/tests/test_tuning.py
- [x]  pymc3/tests/test_quadpotential.py
- [x]  pymc3/tests/test_updates.py
- [x]  pymc3/tests/test_types.py
- [x]  pymc3/tests/test_mixture.py
- [x]  pymc3/tests/test_util.py

**Comment by MarcoGorelli** [comment]
Hi @AlexAndorra - it looks like linking the issue resulted in this being closed then #4150 was merged - could it stay open until there's a pre-commit / CI check in place?

**Comment by AlexAndorra** [comment]
Ah yes, I thought it was done -- reopened 😉
