### ISSUE TITLE
Pickling error

### ISSUE THREAD

**Issue by ahartikainen** [pymc-devs/pymc#4112]
## Description of your problem

ArviZ compiles and then saves the model with the pickle.

https://github.com/arviz-devs/arviz/blob/master/arviz/tests/helpers.py

**Please provide the full traceback.**
```python
_pickle.PicklingError: Can't pickle <class 'theano.gof.utils.TensorVariable_pymc3_Deterministic'>: attribute lookup TensorVariable_pymc3_Deterministic on theano.gof.utils failed
```

https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=3384&view=logs&j=d2997e82-6058-5a08-e2d8-90083b995f86&t=b9272250-ff1d-580c-f3a3-e4ef0487d78f&l=80

**Please provide any additional information below.**

Last successful commit was run against cb05743eb2f14762a469b7ea82d6ecd52602ea91    
And first failed commit was run against f0b95773047af12f3c0ded04d707f02ddc4d4f6b

I think #4076 caused this (not sure)

https://github.com/pymc-devs/pymc3/blob/56ccabbdb88343fc0dc7c34672dd7509574dc3ac/pymc3/util.py#L158

Maybe this could be fixed as

```python
    try:
        if isinstance(var, TensorVariable):
            return super(TensorVariable, var).__str__()
    except:
        pass
    return str(var)
```

## Versions and main components

* PyMC3 Version: master
* Theano Version: 1.0.5
* Python Version: 3.8
* Operating system:  Ubuntu
* How did you install PyMC3: pip

**Comment by canyon289** [comment]
@dfm Any thoughts on this issue? I think it was maybe related to your pr? Fishing for thoughts here

**Comment by aloctavodia** [comment]
The problem is related to this PR #4076 and these new lines
 https://github.com/pymc-devs/pymc3/pull/4076/files#diff-1f25198dab6a35cd27fffe043b7e1b9dR1882-R1889

**Comment by canyon289** [comment]
Ill work in this in ~8 hours or so. Will essentially start by "reverting" the commit and adding a test to pickle, but with the greater goal of moving a discussion forward of how to fix permanently

**Comment by AlexAndorra** [comment]
Thanks for the investigative work @ahartikainen and @aloctavodia ! Pinging @Spaak, as he's the author of #4076, so I'm guessing he'll have an idea on how to fix this 😉

**Comment by Spaak** [comment]
Hey, thanks for the ping! I'll have a look (and hopefully a fix) tomorrow (Sunday, Europe time). If it works out, maybe the revert PR can be avoided?
