### ISSUE TITLE
Add alternative parameterization to negative binomial distribution?

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4126]
The current parameterization in terms of mu and alpha is very useful in relation to the less flexible Poisson distribution.

However, the negative binomial distribution is often discussed in terms of the number of failures observed until a target number of successes is reached. In this case it is usually parameterized  by a parameter p (the probability of observing a success in each trial), and a parameter n (the target number of successes). Would it make sense to add this alternative parameterization to the Negative Binomial distribution?

* n is equivalent to the alpha parameter
* p is equivalent to n / (n + mu) or, equivalently, mu = n(1-p)/p

This parameterization is implemented and discussed in the [R implementation](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/NegBinomial.html)

**Comment by twiecki** [comment]
Great, want to do a PR @ricardoV94?

**Comment by ricardoV94** [comment]
I can try :)
