### ISSUE TITLE
Project meeting?

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4153]
Hi,

The Wiki references a project meeting which happens every month (next one being tomorrow?) https://github.com/pymc-devs/pymc3/wiki/PyMC-Project-Meeting-Minutes

Is this open to the public? If so, and if welcome, I'd appreciate being able to tune in, I just don't know how to join.

Sorry to open an issue for this, I couldn't find any further info

**Comment by fonnesbeck** [comment]
Yes, they are public but we don't really advertise them. We have a Google Meet link that isn't very reliable, and we usually end up starting up a new one that day. Why don't you send me your email (my Gmail is "fonnesbeck") and I will make sure you get the info. We need to make it easier for folks to tune in, so thanks for asking.
