### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4154]
## Description of your problem
The readme (landing page) has some out-of-date information.

Most importantly, https://discourse.pymc.io is not linked prominently enough.

The code of conduct should probably be linked too.

**Comment by Overlord2335** [comment]
I'm new to open source and I'd like to work on this. Could someone point me in the right direction? I've already cloned the repo.

**Comment by twiecki** [comment]
@Overlord2335 great, here is a starter: https://opensource.com/article/19/7/create-pull-request-github

**Comment by Overlord2335** [comment]
@twiecki Thanks, but more specifically could you tell me how do I know which information is out-dated in the README. I've added code of conduct and [https://discourse.pymc.io/](url) this in the README and created a pull request. Please check it out and suggest any further changes in it.
