### ISSUE TITLE
AR class producing anomalous results related to shape issues

### ISSUE THREAD

**Issue by luisroque** [pymc-devs/pymc#4164]
## Description of your problem

The behavior of the AR class (time series), when working with more than 1 time series and for an AR(1) process, can raise issues regarding the shape of the `rho` parameter used.

**Please provide a minimal, self-contained, and reproducible example.**

```python
# Generates data
N, s = 52*6, 4 # number of points per serie and number of series
x = np.zeros((N,s))

#hyperparameters
true_hyper_theta_mu=0.7
true_hyper_theta_sigma=0.1
# true thetas:
true_thetas = np.repeat(np.array([[true_hyper_theta_mu]]),s).reshape(1,s) + np.random.normal(0, true_hyper_theta_sigma, s)
# true variance of the innovation
true_taus = stats.halfnorm.rvs(8, 0.4, size=s)

x[0]=0

for i in range(1, N):
    x[i] = true_thetas[0] * (x[i-1]) + stats.norm.rvs(0, np.sqrt(1/true_taus), s)
```

If I fit a model with a shape for rho of a vector of 4 elements (we have 4 time series) I'll run into problems because of the way the AR class is implemented. It will basically do an AR(p=4) for each series but with only 4 parameters in total (and using the wrong data to estimate them).

```python
with pm.Model() as m_ar:
    
    # adaptative priors
    k = pm.Normal('k', 0, 1, shape=4)
    tau = pm.HalfNormal('tau', sd=1, shape=4)
    alpha = pm.Normal('alpha', mu=5, sd=1)
    
    # AR Process
    η_t = pm.AR("η_t", rho=k, tau=tau,  observed=x)
    
    trace_ar = pm.sample(
        2000,
        tune=2000,
        target_accept=0.9,
        init="advi+adapt_diag"
    )
    idata = az.from_pymc3(trace_ar)
```

The correct way to use it is with the shape of (p, s). You have an AR1 class, but this one is the generalization and you can also perform AR(1) with it. It is somehow documented in the class as:

 Parameters
    ----------
    rho: tensor
        Tensor of autoregressive coefficients. The first dimension is the p lag.

But still, it is very easy to run into problems if you think you can omit the p value because it is an AR(1) process. In my opinion, it could be asserted that the dimensions are correctly set up for the problem at hand.

**Please provide the full traceback.**
```python
with pm.Model() as m_ar:
    
    # adaptative priors
    k = pm.Normal('k', 0, 1, shape=4)
    tau = pm.HalfNormal('tau', sd=1, shape=4)
    alpha = pm.Normal('alpha', mu=5, sd=1)
    
    # AR Process
    η_t = pm.AR("η_t", rho=k, tau=tau,  observed=x)
    
    trace_ar = pm.sample(
        2000,
        tune=2000,
        target_accept=0.9,
        init="advi+adapt_diag"
    )

# It gives nonsense results
np.round(true_thetas,3)  # array([[0.523, 0.716, 0.646, 0.711]])
np.round(trace_ar['k'].mean(0),3) # array([ 0.66, -0.01,  0.  ,  0.02])
```

**Please provide any additional information below.**
Again, in my opinion, it could be asserted that the dimensions are correctly set up for the problem at hand.

Also, this if is somewhat redundant. 
```python
        if self.p == 1:
            x = self.rho * value[:-1]
        else:
            x = tt.add(
                *[self.rho[i] * value[self.p - (i + 1) : -(i + 1)] for i in range(self.p)]
            )
```

**Comment by mathfish** [comment]
If no one objects, I would like to try to work on this to start contributing to pymc3. Is there any more detail on how this should be fixed or is what is mentioned sufficient?

**Comment by AlexAndorra** [comment]
Awesome, thanks @mathfish ! I think you can give it a go with what's already there and add tests to make sure it's doing what's expected -- this will help you figure out whether additional steps are needed 👌 
And of course feel free to ask questions 😉

**Comment by mathfish** [comment]
Sorry for moving so slow on this. Trying to learn and figure what is going on in the code at many different levels with this ticket but my newbness is definitely not helping. I don't want to clutter up this area with dumb questions that are probably general in nature. Should I open up a discussion in PyMC Discourse to ask more questions about this ticket? Of course anybody who wants to finish off this ticket please feel free. I don't want to block anyone.

**Comment by ricardoV94** [comment]
The shape of the AR and coefficients is much more clear in V4. 

You can also manually specify `ar_order` although the original case won't fail explicitly because the logp expression happens to still work well (it simply ignores the last 3  `rho` parameters). 

We could add an explicit Aesara assert that `rho.shape[-1] == ar_order` 

Anyway here is the correct way to specify this model in V4:
```python
import pymc as pm
with pm.Model() as m_ar:
    
    # adaptative priors
    k = pm.Normal('k', 0, 1, shape=(4, 1))
    tau = pm.HalfNormal('tau', sigma=1, shape=4)
    alpha = pm.Normal('alpha', mu=5, sigma=1)
    
    # AR Process
    η_t = pm.AR("η_t", rho=k, tau=tau,  observed=x.T, ar_order=1)
```
