### ISSUE TITLE
Weibull AFT Fitting

### ISSUE THREAD

**Issue by bacalfa** [pymc-devs/pymc#4166]
Not an issue, but a question. I'm following this [tutorial](https://docs.pymc.io/notebooks/weibull_aft.html) on accelerated failure time (AFT) modeling and I'm not sure how to extract shape and scale parameters for the Weibull AFT model. To simplify, suppose there are not covariates. If I were to use `lifelines`' [WeibullAFTFitter](https://lifelines.readthedocs.io/en/latest/fitters/regression/WeibullAFTFitter.html) or `survival`'s [survreg](https://www.rdocumentation.org/packages/survival/versions/3.2-3/topics/survreg), I'd estimate two parameters: shape and scale. In the pymc3 tutorial, is the shape related to `s`, while the scale is related to `beta`? See these [notes](http://personal.psu.edu/drh20/525/weekly/weibull.pdf) on `survreg`'s parameterization.

**Comment by bwengals** [comment]
You would have to compare the docstring on how pm.Weibull is parameterized vs. survreg or lifelines.  You can use `pm.Deterministic`s to translate from one to the other.

We try to keep issues for bug reports and the like, but please feel free to post your Q to [the discourse site](https://discourse.pymc.io/).
