### ISSUE TITLE
blackbox_external_likelihood.ipynb contains "modulenotfound" in first cell

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4182]
Seems this was introduced in commit a3622d3f5c66f5fcc4dbcc52f8b1653a1f812583
```console
$ git log --pretty=oneline -G "ModuleNotFoundError" -- docs/source/notebooks/blackbox_external_likelihood.ipynb
a3622d3f5c66f5fcc4dbcc52f8b1653a1f812583 Update more NBs. Remove Dawid-Skene.
```

See https://nbviewer.jupyter.org/github/pymc-devs/pymc3/blob/master/docs/source/notebooks/blackbox_external_likelihood.ipynb :

```python-traceback
The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython
Running on PyMC3 v3.6
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-1cf6341006dd> in <module>()
     19 import matplotlib
     20 import emcee
---> 21 import corner
     22 import os
     23 print("Python version:     {}".format(platform.python_version()))

ModuleNotFoundError: No module named 'corner'
```

---

cc @twiecki

**Comment by twiecki** [comment]
Thanks @MarcoGorelli. We should probably just remove that dependency and use arviz for plotting. Want to do a PR?

**Comment by MarcoGorelli** [comment]
sure, I'll take it up later this week!

**Comment by MarcoGorelli** [comment]
Hi @twiecki 

I tried running this notebook, but got to cell 4 and got
```python-traceback
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-e2f2f0233a4c> in <module>
      7 ctrue = 3.0  # true y-intercept
      8 
----> 9 truemodel = my_model([mtrue, ctrue], x)
     10 
     11 # make data

NameError: name 'my_model' is not defined
```

----

I have `Cython` installed and am able to run the example from https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#primes 

Is there any extra setup I need to do to be able to run this one?

**Comment by ricardoV94** [comment]
Should this be moved to pymc-examples @OriolAbril ?

**Comment by OriolAbril** [comment]
We already have https://github.com/pymc-devs/pymc-examples/issues/48 to track this. Some more context is probably good though
