### ISSUE TITLE
New NegativeBinomial parametrization broke repr and model graph

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4186]
## Description of your problem
It looks like the addition of a `p` kwarg also requires setting it as an attribute:

**Please provide a minimal, self-contained, and reproducible example.**
```python
with pm.Model() as pmodel:
    pm.NegativeBinomial(
        "nb",
        mu=pm.Normal("mu", shape=(4,)),
        alpha=pm.Gamma("alpha", mu=6, sigma=1),
        observed=[1,2,3,4]
    )
    
print(pmodel["nb"])
```

**Please provide the full traceback.**
```python
AttributeError: 'NegativeBinomial' object has no attribute 'p'
```

**Please provide any additional information below.**
Related commit: https://github.com/pymc-devs/pymc3/commit/6f3193d0ce8d179b79c510e2c82d621d3dc7e08f#diff-261a77bdd4256cfbcba0070411f44915028fd09e673694f91f32b6303158e77b

## Versions and main components

* PyMC3 Version: latest master
* Theano Version: theano-pymc 1.0.9

**Comment by Sayam753** [comment]
Hi @michaelosthege 
I suspect this should be fixed similar to how `MvNormal` resolves its parametrization type [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L330:L331) and then passes appropriate arguments to build repr strings. Any thoughts on this?

**Comment by michaelosthege** [comment]
@Sayam753 sounds like a good solution

**Comment by Sayam753** [comment]
Awesome. Let me send a PR for this.
