### ISSUE TITLE
"Abort trap 6" error with OpenCL under macOS

### ISSUE THREAD

**Issue by dgazzoni** [pymc-devs/pymc#4190]
## Description of your problem

PyMC3 aborts (with an Abort Trap 6 error) when OpenCL is used on a MacBook Pro with an AMD 560X GPU. No such error happens when using the CPU.

Possibly this is an error with one of the libraries used by PyMC3, but seeing as I'm not familiar with them and have no idea how to test them directly, I thought it'd be appropriate to start here.

```python
import numpy as np
import pymc3 as pm

if __name__ == '__main__':
    baseline = np.random.normal(0, 1, 100)

    with pm.Model() as model:
        x = pm.Normal('x', mu=0, sd=1)
        y = pm.Normal('y', mu=x, sd=1, observed=baseline)

        trace = pm.sample(draws=2000)
```

As expected, no issues when running in the CPU.

```
$ ./temp.py
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [x]
Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 13 seconds.12000/12000 00:03<00:00 Sampling 4 chains, 0 divergences]
```

Passing the appropriate flags to make it run on the GPU, the program aborts.

```
$ THEANO_FLAGS=device=opencl0:2,floatX=float32 ./temp.py
Mapped name None to device opencl0:2: AMD Radeon Pro 560X Compute Engine 
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Abort trap: 6
```

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: 3.8.5
* Operating system: macOS 10.15.7
* How did you install PyMC3: conda

**Comment by fonnesbeck** [comment]
As it currently stands, you aren't going to get a any kind performance boost from using a GPU with PyMC3. We hope to support GPU hardware better in the future when JAX backends are supported. 

See #3341.
