### ISSUE TITLE
Broken web links in the plotting documentation

### ISSUE THREAD

**Issue by sarajcev** [pymc-devs/pymc#4191]
Links on the PyMC3 web page for the plotting documentation (which should point to the ArviZ web site) are all [broken](https://docs.pymc.io/api/plots.html).

**Comment by junpenglao** [comment]
Thanks for reporting!

**Comment by OriolAbril** [comment]
There is no need to change the source, only to regenerate the docs

**Comment by MarcoGorelli** [comment]
closing as this is the same as #4319 , and there's most of a discussion there
