### ISSUE TITLE
NUTS initialization gets slower and slower then crush

### ISSUE THREAD

**Issue by AlbertYuChen** [pymc-devs/pymc#4194]
I'm using pymc3 on ubuntu. The NUTS initialization gets slower and slower. The whole program takes 3 min in the beginning then slows down to 30 min. The jupyter-notebook kernel will finally cush. This is crazy! I feel something is getting stuck at RAM. Anyone know why this happens and how to fix it?

Only 300 samples in chain.
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
(get stuck here up to half an hour)

Here is my code.
```
    hir_model = pm.Model()
    with hir_model:
      sd_dist = pm.Exponential.dist(1.0)
      chol, _, _ = pm.LKJCholeskyCov('sigma', eta=1, n=2,
          sd_dist=sd_dist, compute_corr=True)

      q = pm.MvNormal('q', mu=np.zeros(2), chol=chol,
          shape=(10, 2))
      lam = pm.math.exp(2.5 + q)
      for a in range(2):
        for r in range(10):
          pm.Poisson(f'spkcnt_{r}_{a}', mu=lam[r,a], observed=data[r,a])  # Positive integer valued data, 10 x 2 matrix. 
```

**Comment by fonnesbeck** [comment]
Hi Albert. Can you post a reproducible example for us? Sounds like NUTS is having problems with your model, which can often be solved either by having better initialization or by reparameterizing the model, but its hard to tell without more information.

**Comment by AlbertYuChen** [comment]
> Hi Albert. Can you post a reproducible example for us? Sounds like NUTS is having problems with your model, which can often be solved either by having better initialization or by reparameterizing the model, but its hard to tell without more information.

@fonnesbeck I have inserted the code. The weird thing is that the code works fine on Windows, but the problem only exists on Ubuntu. I wonder whether the program cleans the memory after one each run.

**Comment by michaelosthege** [comment]
Closing.. Two years old, missing info, old version...
