### ISSUE TITLE
FutureWarning: use `arr[tuple(seq)]` instead of `arr[seq]`

### ISSUE THREAD

**Issue by AlbertYuChen** [pymc-devs/pymc#4196]
I get warning like this all the time. why?

C:\ProgramData\Anaconda3\lib\site-packages\theano\tensor\subtensor.py:2197: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  rval = inputs[0].__getitem__(inputs[1:])

theano: 1.0.4
pymc3: 3.9.0

**Comment by AlexAndorra** [comment]
Hi Albert,
This has to do with your Theano version: if you update to the latest version (1.0.5), the warning will disappear.
Closing this, as it's not related to PyMC3 and is not an issue _per se_.
