### ISSUE TITLE
Cut new release 3.10

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4202]
Release early, release often.

We have a couple of nice new features on the docket and our release process is getting more stream-lined.

We do need a release manager, anyone wants to volunteer?

**Comment by twiecki** [comment]
Actually with the new MLDA stepper and the switch to Theano-PyMC we should make a `3.10` release.

**Comment by twiecki** [comment]
We should also reorder the release notes. Put new features at top and MLDA stepper at top. Roughly in order of significance.

**Comment by michaelosthege** [comment]
> 
> 
> We should also reorder the release notes. Put new features at top and MLDA stepper at top. Roughly in order of significance.

When editing the release notes, please link to these PRs that were not yet mentioned:
+ https://github.com/pymc-devs/pymc3/pull/4217

**Comment by Spaak** [comment]
See #4227 for an update to the release notes mentioning the new string representations.
