### ISSUE TITLE
resume running  pymc3 code from where it was stopped?

### ISSUE THREAD

**Issue by soroushnajafian** [pymc-devs/pymc#4203]
If I run the pymc3 code such as:
```
modell = pm.Model()
func = IntegrateOpFUN(z_l,z_s) 
with modell:
    Omega_m = pm.Uniform('OMM',lower=0.1, upper=0.45)
    a = pm.Uniform('a', lower=1.1, upper=2.2)
    thetaMu = func(OMM,a)
    obs = pm.Normal('obs', mu=thetaMu, sd=D_tobserr, observed=D_tobs)
    start = pm.find_MAP()
    step = pm.Metropolis()
    db = pm.backends.Text('drive/My Drive/stronglensing_tsalli GPU')
    trace = pm.sample(25000, step, start=start, chains=1, trace=db)
```

and while it is running it will abort for some reason such as power outage (when iteration= 6000).
Is it possible when problem solve
I will resume from where I stop?  (in my case continue from 6000).

**Comment by ckrapu** [comment]
For questions like these, it's recommended that you post to the Discourse channel at https://discourse.pymc.io/. 

With regard to your problem, I am assuming that your interruption is going to occur with no warning (i.e. you will not have time to stop and turn off the computer) yet you still want to have your progress saved. Is this true?

**Comment by soroushnajafian** [comment]
> For questions like these, it's recommended that you post to the Discourse channel at https://discourse.pymc.io/.
> 
> With regard to your problem, I am assuming that your interruption is going to occur with no warning (i.e. you will not have time to stop and turn off the computer) yet you still want to have your progress saved. Is this true?

Thank's for your response.I will post it to the Discourse channel.
 I can save progress as you see with this command
```
db = pm.backends.Text('drive/My Drive/stronglensing_tsalli GPU')
```
if I run program again I want skip iteration from 6000(that it was saved base above code) where my program halted not from beginning.
