### ISSUE TITLE
Posterior Predictive from Inf Data versus Trace is different for model vars and slower

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4209]
## Description of your problem
For some reason the posterior predictive distribution of model variables is "jagged" when providing `inf_data` to `pm.sample_posterior_predictive`. On top of that its 8x slower.

However the observed quantity comes out just fine. Expectation is that speed and result of trace and infdata would be exactly the same

Note: This may be an ArviZ bug assuming the KDE estimate issue is separate from the sampling. If so I'll move the issue ticket over to that project

Gist of notebook
https://gist.github.com/canyon289/92921b442aa619a721010d8e52530719

```
import pymc3 as pm
from scipy import stats
import arviz as az
import matplotlib.pyplot as plt

pm.__version__
az.__version__
y = stats.norm().rvs(10000)

with pm.Model() as model:
    sigma = pm.HalfNormal("sigma", 10)
    mu = pm.Normal("mu", 1, 100)
    
    trace = pm.Normal("y", mu, sigma, observed=y)
    
    trace = pm.sample(random_seed=0)
    inf_data = pm.sample(random_seed=0, return_inferencedata=True)

with model:
    trace_ppc = pm.sample_posterior_predictive(trace, var_names=["y", "mu"], random_seed=0)
    inf_ppc = pm.sample_posterior_predictive(inf_data, var_names=["y", "mu"], random_seed=0)

fig, ax = plt.subplots()
az.plot_dist(trace_ppc["mu"], ax=ax)
az.plot_dist(inf_ppc["mu"], ax=ax)

fig, ax = plt.subplots()
az.plot_dist(trace_ppc["y"], ax=ax)
az.plot_dist(inf_ppc["y"], ax=ax)

```

**Please provide any additional information below.**

![image](https://user-images.githubusercontent.com/7213793/98458611-683aa300-2147-11eb-8028-dee6484336fd.png)

## Versions and main components
![image](https://user-images.githubusercontent.com/7213793/98458590-31648d00-2147-11eb-9ca8-e131ae9a85b9.png)

* PyMC3 Version:
* Theano Version:
* Python Version: 
* Operating system: Ubuntu 20.04
* How did you install PyMC3: pip

**Comment by ricardoV94** [comment]
According to @aloctavodia in #4212:

> This fix half of #4209. Now Inf Data versus Trace will be the same. The speed difference is related to InfereceData not storing transformed variables.

Do we want to save the transformed variables to solve the speed issue, or can we close this issue?
