### ISSUE TITLE
transforms.ordered doesn't apply to samples found with .random()

### ISSUE THREAD

**Issue by EdAyers** [pymc-devs/pymc#4213]
**Please provide a minimal, self-contained, and reproducible example.**

Modified version of example given at https://docs.pymc.io/api/distributions/discrete.html?highlight=ordered#pymc3.distributions.discrete.OrderedLogistic

```python
import pymc3 as pm
import numpy as np
with pm.Model() as model:
    cutpoints = pm.Normal("cutpoints", mu=[-1,1], sigma=10, shape=2,
                          transform=pm.distributions.transforms.ordered, testval=np.asarray([.5, .9]))
    for i in range(10):
        c = cutpoints.random()
        print(c, c[0] < c[1])
```

**Please provide the full traceback.**
```python
[-1.78978722  2.24029602] True
[ 7.27625258 -9.98526886] False
[-2.3456616   6.17737276] True
[-12.42092868  -2.94677656] True
[0.8365788  9.45209727] True
[-12.07594385  13.38498445] True
[ 4.94704378 17.77777978] True
[7.0118523  7.82261754] True
[ -3.387632   -10.23571222] False
[ 8.48851098 -3.25975408] False
```

Expected result: c[0] is always < c[1]

However the full demo given at the URL works fine. So I guess that one of the members of the `Transform` subclass has a bug in it?
Or maybe I misunderstood the API and when you call `X.random()` you are supposed to see the sample before the transform?
It seems quite likely this is a bug but apologies if this is actually correct behaviour.

Here is another one where someone is sampling an ordered pair but no output.
https://github.com/pymc-devs/pymc3/issues/3680

## Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version: 3.8.6
* Operating system: Arch Linux
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
Thanks for reporting - we need a `pm.Sort` class similar to `pm.Bound` to solve this properly (I had a twitter thread for this actually https://twitter.com/junpenglao/status/1263927315194576898)

**Comment by ricardoV94** [comment]
Could we resort to some costly rejection sampling in here? Or mix rejection sampling and truncated sampling for those distributions we have cdf / inverse cdf methods.

**Comment by junpenglao** [comment]
i dont think that's necessary - just need to sort the forward simulation

**Comment by ricardoV94** [comment]
> i dont think that's necessary - just need to sort the forward simulation

That only works if the sorted distributions are identically distributed

**Comment by ricardoV94** [comment]
Random forward methods in general don't (and can't) respect transforms that change the density of a distribution (they are not even aware of them). We can create distributions that generate forward samplers that are equivalent to the transformed distribution that is sampled by MCMC, but otherwise users shouldn't expect the two forms of sampling to match when using non-default transformations. For the case of sorting we would need something like https://github.com/aesara-devs/aeppl/issues/44
