### ISSUE TITLE
why pm.sample() is so slow even using pm.Metropolis()?

### ISSUE THREAD

**Issue by ClaireGyn** [pymc-devs/pymc#4236]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io  

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
step_name = pm.Metropolis()
ndraws = 500  # number of draws from the distribution
nburn = 100  # number of "burn-in points" (which we'll discard)
trace = pm.sample(ndraws, tune=nburn, chains=2, cores=4, discard_tuned_samples=False, step=step_name)
```

**Please provide the full traceback.**
```python
[The error output here]
```
![image](https://user-images.githubusercontent.com/34539124/99789473-9b286200-2b5d-11eb-893a-ed635f6fed81.png)
![image](https://user-images.githubusercontent.com/34539124/99789714-f8241800-2b5d-11eb-8c83-427903696a11.png)

**Please provide any additional information below.**

Hi, everyone. I used the above settings for running MCMC, but found that even running 500 draws with 100 burn-in points needed around 4hrs. But it will be too slow to be implemented in my further research. Could I ask whether the time consumption is normal or I set something inappropriate making it so slow?
## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7.1
* Operating system: win 10
* How did you install PyMC3: (conda/pip) conda

**Comment by twiecki** [comment]
Thanks for the report @ClaireGyn. This is a question better suited for our discourse. It would also help if you posted the model, without that info it's impossible to say why (or if) your model is slow.

**Comment by ClaireGyn** [comment]
Hi @twiecki , thanks for your reply. Actually, I use blackbox_external_likelihood as illustrated in 
![image](https://user-images.githubusercontent.com/34539124/99904206-70c4d900-2d04-11eb-942a-1a4f59e8f180.png)
https://github.com/mattpitkin/pymc3/blob/master/docs/source/notebooks/blackbox_external_likelihood.ipynb. Also, I insert my own model, which only consumes 1.5s to run once, into the likelihood function. But don't know why the time consumption increases so much in the sampling process.

**Comment by ClaireGyn** [comment]
could u please re-open the issue? Thank you very much!

**Comment by twiecki** [comment]
1.5s per likelihood evaluation is very slow so I'm not surprised it's so slow. I don't think this is a bug or technical issue with pymc3 so it shouldn't be a github issue. Did you open a thread on discourse?

**Comment by ClaireGyn** [comment]
Ok. I will try to reduce my model time consumption (1.5 s) further and open a thread on discourse later. Thanks for the quick reply
!
