### ISSUE TITLE
Stochastic volatility example does not run

### ISSUE THREAD

**Issue by ecod3r** [pymc-devs/pymc#425]
Using the latest Anaconda (and inclyding the required DYLD_FALLBACK_LIBRARY_PATH) on OS X 10.9.1 yields

``` python
from scan_perform.scan_perform import *
Traceback (most recent call last):
  File "stochastic_volatility.py", line 113, in <module>
    step = NUTS(model.vars, hessian(start, 6))
  File "stochastic_volatility.py", line 84, in hessian
    h = H(Point(point))
  File "/Users/eu/anaconda/lib/python2.7/site-packages/pymc/point.py", line 9, in __call__
    return self.f(**state)
  File "/Users/eu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 565, in __call__
    self.inv_finder[c]))
TypeError: Missing required input: log_sigma
```

For the sake of clarity, I am running

``` bash
python stochastic_volatility.py
```

rather than the IPython notebook

**Comment by twiecki** [comment]
Can you try running the ipynb? That should be more updated and we could just convert it to python.

**Comment by raddy** [comment]
I'm seeing the same error with either the .py or nb versions.

**Comment by fonnesbeck** [comment]
I can't replicate this. Which version of Theano do you have installed?

**Comment by ecod3r** [comment]
Same as raddy, both the .py and the IPython notebook give the same error. I have theano v0.6.0

**Comment by fonnesbeck** [comment]
Are you also on Anaconda @ecoskian ?

**Comment by ecod3r** [comment]
Yes @fonnesbeck, the latest Anaconda with Accelerate

**Comment by fonnesbeck** [comment]
I'm going to have to talk with Anaconda folks about this. Not sure why there are always problems with PyMC on Anaconda, but I cannot get either PyMC 2.3 or 3 run on my system (the former does not even build).

**Comment by minabks** [comment]
hello ,  i am looking for a python simulation of the gaussian / heston  stochastic model in volatility discretization

**Comment by twiecki** [comment]
@minabks Can you open a new issue for this?
