### ISSUE TITLE
Switch from Travis to Github Actions

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4251]
from @ColCarroll: we may run into a problem with travis soon, they are limiting build hours for open source now. seeing no builds in the last few hours (PRs from ~10hrs and ~2hrs ago not building). I think we're frozen until we move or pay up.

Initial PR by @aseyboldt: https://github.com/pymc-devs/pymc3/pull/4017 which @MarcoGorelli agreed to take over.

**Comment by fonnesbeck** [comment]
Is GitHub Actions preferable to TravisCI, or should we find a way to pay for it?
