### ISSUE TITLE
Runaway Theano warnings during/after sampling

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#426]
I'm getting some pretty bizarre behavior when trying to run a model with the current master. I am running (what appears to be) a pretty straightforward model:

```
 with Model() as model:

            # Mean PDGT10
            theta = Normal('alpha', 0, 0.001)

            # Season covariates
            phi = Normal('theta', 0, 0.001, shape=len(sma_dataset.season.unique()))

            # Season mean
            mu = tinvlogit([(theta, theta + phi[s-1])[s>0] for s in sma_dataset.season])

            # Variance
            var = Gamma('var', 1, 1)

            # Convert to beta parameters
            alpha = mu * (mu*(1-mu)/var - 1)
            beta = (1 - mu) * (mu*(1-mu)/var - 1)

            # Likelihood
            pdgt10 = Beta('pdgt10', alpha, beta, observed=y)

            start = model.test_point
            step = NUTS()

            tr = psample(iterations, step, start=start) 
```

But when I sample, I get a continuous stream of what appears to be warning output (assuming because of the pink background) that consists of hundreds of thousands of lines of C code. I've posted a screen shot because it still hasn't finished printing. I'm assuming this is a Theano thing, but its pretty awful. Anyone have any idea what this is about?

![error](http://f.cl.ly/items/3j0d303e1a013007192p/Screen%20Shot%202013-12-19%20at%2012.19.38%20PM.png)

**Comment by fonnesbeck** [comment]
This occurs for `sample` as well as `psample`:

![](http://f.cl.ly/items/0y272v433t2I3N341S1Y/Screen%20Shot%202013-12-19%20at%202.14.20%20PM.png)

**Comment by jsalvatier** [comment]
Agree that its awful. I think its a Theano thing too. I've run into this a
couple of times too. I would post a bug with them. Maybe try deleting
~/.theano and/or reinstalling theano?

On Thu, Dec 19, 2013 at 12:16 PM, Chris Fonnesbeck <notifications@github.com

**Comment by fonnesbeck** [comment]
[Posted issue with Theano](Theano/Theano#1680). Sounds like it may be default stdout behavior for the Theano dev code. Going to try running with a release.
