### ISSUE TITLE
sample_posterior_predictive() resamples arrays instead of using model factory values

### ISSUE THREAD

**Issue by bridgeland** [pymc-devs/pymc#4272]
### Description  

**pm.sample_posterior_predictive()** fails to use array values copied in from another trace. It works fine on scalar values copied in, but ignores array values copied in.

### Example

This example is a model factory, derived from @lucianopaz's [pioneering work](https://discourse.pymc.io/t/how-do-we-predict-on-new-unseen-groups-in-a-hierarchical-model-in-pymc3/2571/2). 

```python
import pymc3 as pm

def model_factory():
    """Create a model with a scalar normal and an array normal"""
    with pm.Model() as model:
        foo = pm.Normal('foo', 0, 1)
        foo_array = pm.Normal('foo_array', 0, 1, shape=10)
        pm.Deterministic('bar', foo)
        pm.Deterministic('bar_array', foo_array)
    return model

# Create a model and sample it
with model_factory() as antecedent:
    ant_trace = pm.sample(draws=600, chains=2, tune=500)

# Create a second model, copy the values for foo and foo_array
# from the first model to the second to the model. Then sample posterior
with model_factory() as consequent:
    ant_trace_df = pm.trace_to_dataframe(ant_trace, varnames=['foo', 'foo_array'])
    conseq_trace = pm.sample_posterior_predictive(
        trace=ant_trace_df.to_dict('records'),
        var_names=['bar', 'bar_array'],
        samples=len(ant_trace_df))
```

Create two identical models, **antecedent** and **consequent**. Sample **antecedent**, and copy the values for **foo** and **foo_array** from **antecedent**'s trace to **consequent**. Then sample **consequent** with **pm.sample_posterior_predictive()**.

Examine one sample (e.g. 42) in the traces of **antecedent** and **consequent**. Note that we cannot examine **foo** in **consequent**'s trace, as it does not exist in the trace. But we can examine **bar**, a simple deterministic that takes the value of **foo**. The values for **bar** are identical in **antecedent** and **consequent**, as expected:

![image](https://user-images.githubusercontent.com/5245697/100542716-c5db8000-3219-11eb-9570-30659a8e4235.png)

**foo_array** is just like **foo**, except it is an array of shape 10 instead of a scalar. And **bar_array** is just like **bar**, except it is also an array of shape 10 instead of a scalar. But the values for **bar_array** are completely different between the traces of **antecedent** and **consequent**:

![image](https://user-images.githubusercontent.com/5245697/100542724-d25fd880-3219-11eb-86b3-10005069958f.png)

**pm.sample_posterior_predictive()** seems to be ignoring the values of **foo_array** copied in from **antecedent**, and instead resampling the normal distribution.

### Versions and main components

* PyMC3 Version: 3.9.3
* Theano Version: 1.0.5
* Python Version:  3.8.5
* Operating system: macOS v10.15.7
* How did you install PyMC3: conda

**Comment by lucianopaz** [comment]
Thanks for reporting. I'll look into it during the week.

**Comment by lucianopaz** [comment]
@bridgeland, sorry for the late reply. I dug into the problem and found out the cause.

The problem is caused by `pm.trace_to_dataframe(ant_trace, varnames=['foo', 'foo_array'])`. This creates a pandas dataframe where the entries for `foo_array` are split across columns named `foo_array_0`, `foo_array_1`, etc. These are then passed on to `sample_posterior_predictive` but there is no way for the sampler to understand that `foo_array_0`, `foo_array_1`, and the rest should be stacked together into a single `foo_array` value.

There are two ways to address this problem:

1. Don't convert to a `DataFrame` and drop the values from the `MultiTrace` directly:

```python
with model_factory() as consequent:
    ant_trace.remove_values("bar")
    ant_trace.remove_values("bar_array")
    conseq_trace = pm.sample_posterior_predictive(
        trace=ant_trace,
        var_names=['bar', 'bar_array'],
    )
```

2. Use `arviz.InferenceData` that stores the posterior samples in an `xarray.Dataset`, that can understand the multidimensional `foo` and `foo_bar` without problems.

```python
with model_factory() as antecedent:
    ant_trace = pm.sample(draws=600, chains=2, tune=500, return_inferencedata=True)

# Create a second model, copy the values for foo and foo_array
# from the first model to the second to the model. Then sample posterior
with model_factory() as consequent:
    ant_trace.posterior = ant_trace.posterior.drop_vars(["bar", "bar_array"])
    conseq_trace = pm.sample_posterior_predictive(
        trace=ant_trace,
        var_names=['bar', 'bar_array'],
    )
```

**Comment by lucianopaz** [comment]
Since this was an issue that came up because of trace postprocessing, it isn't actually a pymc3 issue, so I'll close.
