### ISSUE TITLE
Adding software using pymc3

### ISSUE THREAD

**Issue by vitkl** [pymc-devs/pymc#4286]
Hi PyMC-devs team!

Would be great if you can add our package to your list of software using pymc3 

Comprehensive mapping of tissue cell architecture via integrated single cell and spatial transcriptomics (cell2location model)
https://github.com/BayraktarLab/cell2location

Thanks, and please let me know if you have any questions.

Vitalii

**Comment by fonnesbeck** [comment]
You bet. Thanks for the link, and thanks for creating what looks to be a fantastic library!
