### ISSUE TITLE
Finish IPython notebook progress bar

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#429]
It would be great to get the JS progress bar working, as the text progress bar leaves a ton of artifacts in the notebook JSON.

**Comment by PaulSorenson** [comment]
I noticed while looking at #707, an IPython widget warning is displayed when running in the console, presumably due to imports related to the progressbar.

```
:0: FutureWarning: IPython widgets are experimental and may change in the future.
```

Although presumably harmless it is bit of a surprise.  I am not sure if there is a robust way to detect whether you are in an IPython notebook unless you explicitly import IPython first.  Searching through sys.modules.keys() might be overkill.

**Comment by twiecki** [comment]
I think it's fine to have a try/except block around the import, not an uncommon way to do optional deps/runtimes.

**Comment by PaulSorenson** [comment]
I don't have a problem with the try/except.  If you are running from the console and you happen to have ipython notebook packages installed, the import succeeds and hence the warning messages from inside IPython.

Not pushing for a change - just something that caused a double take.

**Comment by twiecki** [comment]
I think that warning also appears from inside the NB, no?

**Comment by PaulSorenson** [comment]
Yes - but warnings about notebook widgets are not out of place in notebooks.  On the command line they are.

Your suggestion in #707 to use get_ipython() to figure out if you are running in IPython could be added to the try/except.  If you are not in IPython importing widgets from IPython is a bit superfluous.

**Comment by twiecki** [comment]
Ah, point taken. Your suggestion sounds good. :+1: Want to do a PR?

**Comment by PaulSorenson** [comment]
Ok I'll have a look.  I notice there is a test already that looks for `__IPYTHON__` which returns True if running in IPython (notebooks or console).  That seems a more robust test for now.

Using `get_ipython()` we can differentiate between terminal-interactive vs notebook-interactive.  That could be useful for the progress bar implementation.

**Comment by PaulSorenson** [comment]
pull request: https://github.com/pymc-devs/pymc3/pull/715
