### ISSUE TITLE
GLM.from_formula not working with priors

### ISSUE THREAD

**Issue by Rabeez** [pymc-devs/pymc#4307]
I was playing around with the [Poisson regression example](https://docs.pymc.io/notebooks/GLM-poisson-regression.html) (same dataframe) from the docs. I'm getting this error only if I pass the `priors` argument to the function. 

The model builds normally with the default flat priors (if I don't pass any). 

```python
def formula_model_factory(data_df):
    with pm.Model() as model:
        # priors on parameters
        priors = {
            'Intercept': pm.Normal('α', 0, 1),
            'Regressor': pm.Normal('β', 0, 1)
        }
        
        # model specification
        pm.glm.GLM.from_formula('nsneeze ~ alcohol + nomeds + alcohol * nomeds',
                                data=data_df,
                                priors=priors,
                                family=pm.glm.families.Poisson())

    return model

formula_model = formula_model_factory(df[['nsneeze','alcohol','nomeds']])
formula_model
```

**Please provide the full traceback.**
<details summary="Traceback"><p>
TypeError                                 Traceback (most recent call last)

<ipython-input-95-efbfb6911a49> in <module>
----> 1 formula_model = formula_model_factory(df[['nsneeze','alcohol','nomeds']])
      2 formula_model

<ipython-input-94-c005667b34dc> in formula_model_factory(data_df)
      8 
      9         # model specification
---> 10         pm.glm.GLM.from_formula('nsneeze ~ alcohol + nomeds + alcohol * nomeds',
     11                                 data=data_df,
     12                                 priors=priors,

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\glm\linear.py in from_formula(cls, formula, data, priors, vars, family, name, model, offset, eval_env)
    190         y, x = patsy.dmatrices(formula, data, eval_env=eval_env)
    191         labels = x.design_info.column_names
--> 192         return cls(np.asarray(x), np.asarray(y)[:, -1], intercept=False,
    193                    labels=labels, priors=priors, vars=vars, family=family,
    194                    name=name, model=model, offset=offset)

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\model.py in __call__(cls, *args, **kwargs)
    364         instance = cls.__new__(cls, *args, **kwargs)
    365         with instance:  # appends context
--> 366             instance.__init__(*args, **kwargs)
    367         return instance
    368 

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\glm\linear.py in __init__(self, x, y, intercept, labels, priors, vars, family, name, model, offset)
    150                  priors=None, vars=None, family='normal', name='',
    151                  model=None, offset=0.):
--> 152         super().__init__(
    153             x, y, intercept=intercept, labels=labels,
    154             priors=priors, vars=vars, name=name,

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\glm\linear.py in __init__(self, x, y, intercept, labels, priors, vars, name, model, offset)
     75                     v = Deterministic(name, vars[name])
     76                 else:
---> 77                     v = self.Var(
     78                         name=name,
     79                         dist=priors.get(

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\model.py in Var(self, name, dist, data, total_size, dims)
   1069             if getattr(dist, "transform", None) is None:
   1070                 with self:
-> 1071                     var = FreeRV(
   1072                         name=name, distribution=dist, total_size=total_size, model=self
   1073                     )

~\Anaconda3\envs\pymc\lib\site-packages\pymc3\model.py in __init__(self, type, owner, index, name, distribution, total_size, model)
   1586         if distribution is not None:
   1587             self.dshape = tuple(distribution.shape)
-> 1588             self.dsize = int(np.prod(distribution.shape))
   1589             self.distribution = distribution
   1590             self.tag.test_value = (

<__array_function__ internals> in prod(*args, **kwargs)

~\Anaconda3\envs\pymc\lib\site-packages\numpy\core\fromnumeric.py in prod(a, axis, dtype, out, keepdims, initial, where)
   2997     10
   2998     """
-> 2999     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
   3000                           keepdims=keepdims, initial=initial, where=where)
   3001 

~\Anaconda3\envs\pymc\lib\site-packages\numpy\core\fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     83                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     84             else:
---> 85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
     87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

TypeError: prod() got an unexpected keyword argument 'out'
</p></details>

## Versions and main components

> Python implementation: CPython
Python version       : 3.8.5
IPython version      : 7.19.0<br>
pymc3     : 3.9.3
pandas    : 1.1.3
numpy     : 1.19.2
theano    : 1.0.5
matplotlib: 3.3.2
arviz     : 0.10.0
seaborn   : 0.11.0
sklearn   : 0.23.2

* How did you install PyMC3: conda on windows

**Comment by ricardoV94** [comment]
Closing, GLM module has been deprecated in favor of Bambi: https://github.com/bambinos/bambi
