### ISSUE TITLE
Error while "import pymc3"

### ISSUE THREAD

**Issue by stealcompass** [pymc-devs/pymc#4317]
Hello everyone, 

I have this error when importing pymc3 package:

**ImportError: cannot import name 'is_same_graph' from 'theano.gof.toolbox' (/opt/anaconda3/lib/python3.7/site-packages/theano/gof/toolbox.py)**

The installation of pymc3 was done by the command: conda install pymc3
Theano: conda install theano
Python version: Python 3.7.4
Operating system: macOS mojave 10.14.6

To work with the code I use VSCode

**Comment by MarcoGorelli** [comment]
Hi @stealcompass 

I don't think you need to do _both_ `conda install pymc3` and `conda install theano`. 

In fact, the README recommends
```
conda install -c conda-forge pymc3
```
can you try that please?

----

I just tried that and it works for me:
```
conda create -n temp python=3.8 -y
conda activate temp
conda install -c conda-forge pymc3
python -c "import pymc3; print(pymc3.__version__)"
```
shows `3.10.0`

**Comment by MarcoGorelli** [comment]
closing for now due to insufficient info, but please do let us know if you still have this issue or face any further ones
