### ISSUE TITLE
GLM-hierarchical-jax example links to nowhere

### ISSUE THREAD

**Issue by ivlis** [pymc-devs/pymc#4328]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
The release notes for 3.10 mention an example notebook for the new `sample_jax` function. However, the link https://docs.pymc.io/notebooks/GLM-hierarchical-jax.html leads to a 404 error.

**Please provide the full traceback.**
NA

**Please provide any additional information below.**
NA

## Versions and main components

Not relevant

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by MarcoGorelli** [comment]
Thanks @ivlis for the report!

The docs still need re-building, it'll appear when that's done

cc @ColCarroll  - I know there's the outstanding issue of how `parameter: type` displays, but do we want to re-build the docs so the new notebooks appear and then fix that issue later?

**Comment by ricardoV94** [comment]
Seems to be fixed already?
