### ISSUE TITLE
Suggestion: CDF methods for discrete variables

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4331]
Is there a reason why all discrete variables lack the logcdf method? 

Stan, for example, provides this functionality for several distributions (Poisson, Binomial, Negative binomial, Bernoulli)

Is this something people might be interested?

Best,
Ricardo

**Comment by twiecki** [comment]
@ricardoV94 Yes, we'd definitely be interested in a PR implementing these.

**Comment by ricardoV94** [comment]
@twiecki That's great. I'll give it a try.
