### ISSUE TITLE
Docs: Move all notebooks to /notebooks

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4335]
The true location of the notebooks is `/docs/source/notebooks`.

Symlinks (don't work on Windows!)
+ `/notebooks`
+ `/pymc3/examples/notebooks`

Instead of symlinking, the notebooks should be moved to `/notebooks`.
To include them in the docs, we should use the [`nbsphinx_link`](https://github.com/vidartf/nbsphinx-link) package.

**Comment by fonnesbeck** [comment]
We should probably go ahead and move the notebooks to their own repo.

**Comment by ricardoV94** [comment]
> We should probably go ahead and move the notebooks to their own repo. 

pymc-devs/resources ?

**Comment by fonnesbeck** [comment]
pymc-devs/pymc-examples

**Comment by twiecki** [comment]
We moved these over to pymc-examples now.
