### ISSUE TITLE
Docs: Clean up example files / merge with notebooks

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4336]
At https://github.com/pymc-devs/pymc3/tree/master/pymc3/examples we have example files that we not updated for years.

```
for example in /pymc3/examples:
    if example.is_covered_by_notebooks or example_is_irrelevant:
        example.delete()
    else:
        example.refactor_into_notebook()
```

Related issue #4335

**Comment by michaelosthege** [comment]
@MarcoGorelli you did the PR on `pymc-examples` , so naturally you could do this and #4335 as well?
Also how should we proceed with PRs such as #4325 that target the notebooks?

**Comment by MarcoGorelli** [comment]
I think they should be moved so they target pymc-examples directly

I haven't yet figured out how to build the docs in a way with what's consistent with the website, so have removed my assignment til then

**Comment by michaelosthege** [comment]
Closing because the files were moved already.
