### ISSUE TITLE
.random() methods missing from some timeseries distributions

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4337]
Timeseries distributions with a `.random()` method:
+ `GaussianRandomWalk`

Timeseries distributions where `.random is None`:
+ `MvGaussianRandomWalk`
+ `MvStudentTRandomWalk`
+ `AR`
+ `AR1`
+ `GARCH11` 
+ `EulerMaruyama`

At least for the two `Mv` distributions is should be straightforward to implement.

Make sure to include them in `test_distributions_random.py`, just like `GuassianRandomWalk` already is!

**Comment by awray3** [comment]
Hi, I am new to contributing and would like to work on this issue. Can I work on it?

**Comment by michaelosthege** [comment]
@awray3 of course, go ahead!
Just make sure to mention this issue when opening a PR, so it gets linked.
Also check out the wiki pages. We have some code style guidance there.

**Comment by awray3** [comment]
Is `MvGaussianRandomWalk` intended to only take one of `cov`, `tau`,  or `chol`, much like how `GaussianRandomWalk` only accepts one of `tau` and `sigma` but not both?

Also, are each of the random walks conventionally taken to start at 0 like `GaussianRandomWalk`?

**Comment by AlexAndorra** [comment]
> Is `MvGaussianRandomWalk` intended to only take one of _cov_, _tau_, or _chol_, much like how `GaussianRandomWalk` only accepts one of `tau` and `sigma` but not both?

Yes, these three parameters are just three different ways of expressing the covariance matrix. You can [take a look at `MvNormal`](https://docs.pymc.io/api/distributions/multivariate.html#pymc3.distributions.multivariate.MvNormal) to get a better idea if needed.

> Also, are each of the random walks conventionally taken to start at 0 like `GaussianRandomWalk`?

Yes, I think so. I'm guessing it's like Gaussian Processes: you can just add the mean separately afterwards to center the random walk on something else than 0

**Comment by awray3** [comment]
@AlexAndorra Thank you for the pointer; it lead me to `_QuadFormBase` which had exactly what I needed.

**Comment by awray3** [comment]
General question on time series in PyMC3, which I could not find in the documentation: what should the shape parameter be for a multivariate time series random variable? My guess after sorting through some of the code was that it should be something like `shape = (time, n_dims)`, but I found no definite answer. I will consider adding `shape` to the docstrings for these functions to eliminate any guesswork.

**Comment by mjhajharia** [comment]
Entire time series is being refactored so maybe we can close this @michaelosthege ?

**Comment by ricardoV94** [comment]
I would leave it open until those are implemented, as a reminder issue
