### ISSUE TITLE
Dependency Import error -- Theano (Sphinx docs Make)

### ISSUE THREAD

**Issue by CloudChaoszero** [pymc-devs/pymc#4338]
Hello Team! Hope you are doing well!

## Description of your problem

I receive the following error after trying to run this command in Docs/Source `make html`:

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/CloudChaoszero/Documents/Projects-Dev/pymc3/docs/source/conf.py", line 18, in <module>
    import pymc3
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/__init__.py", line 39, in <module>
    __set_compiler_flags()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymc3/__init__.py", line 35, in __set_compiler_flags
    current = theano.config.gcc.cxxflags
AttributeError: 'TheanoConfigParser' object has no attribute 'gcc'

make: *** [html] Error 2
```

I noticed the Python version is pointing to 3.7, instead of the 3.8.5 from my conda .environment

```
conda create -n temp python=3.8 -y
conda activate temp
conda install -c conda-forge pymc3
python -c "import pymc3; print(pymc3.__version__)"
```
> Similar to #4317 ?

Could I change the MAKE file on my local machine, and point to the right python version, before running `sphinx-build`?

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: `pymc3  3.10.0`
* Theano Version: `theano-pymc 1.0.11 `
* Python Version: `3.8.5`
* Operating system: `Mac`
* How did you install PyMC3: (conda/pip)
`conda install -c conda-forge pymc3`

**Comment by MarcoGorelli** [comment]
I was able to build the docs using Python3.8

I'm inclined (though haven't confirmed) to suggest that the issue is that you've tried building the docs with `pymc3` installed from `conda-forge`, rather than from source. Could you try following the instructions in the README for how to setup a dev environment and then try to build the docs from within that?

**Comment by CloudChaoszero** [comment]
@MarcoGorelli Thanks for the quick response!

It turns out that I was going through the dreaded local machine python default issue, and the `sphinx-build` was not referencing my environment version... 😢 
> I'll be closing this Issue.
___
## Notes on how I fixed this
1. `cd ~` &  `vim .bash_profile`
2. Change export PATH to be
```
# Anaconda path
export PATH="/anaconda3/bin:$PATH"
. /anaconda3/etc/profile.d/conda.sh
```
3.  From your mention on setup, I did a `pip install requirements-dev.txt`, when I had my conda source activated
> This part added the required dependencies for development.

Again, thanks!
