### ISSUE TITLE
Remove some logic from tests

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4339]
Some of the test functions are so complicated it almost feels like they need their own test - example:
```
        def get_random_variable(self, shape, with_vector_params=False, name=None):
            if with_vector_params:
                params = {
                    key: value * np.ones(self.shape, dtype=np.dtype(type(value)))
                    for key, value in self.params.items()
                }
            else:
                params = self.params
            if name is None:
                name = self.distribution.__name__
            with self.model:
                if shape is None:
                    return self.distribution(name, transform=None, **params)
                else:
                    try:
                        return self.distribution(name, shape=shape, transform=None, **params)
                    except TypeError:
                        if np.sum(np.atleast_1d(shape)) == 0:
                            pytest.skip("Timeseries must have positive shape")
                        raise
```
from `pymc3/tests/test_distributions_random.py`.

[Putting logic in tests isn't great](https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html), I think it'd be worthwhile to simplify these tests (with more repetition, if necessary - principles like "don't repeat yourself" don't necessarily apply to writing tests). From the above article:

> simplicity is more important than flexibility in tests

**Comment by ricardoV94** [comment]
This issue needs to identify tests that should be simplified. Otherwise its not really actionable. The original example is no longer relevant in V4

**Comment by MarcoGorelli** [comment]
Agreed - closing for now then, thanks for having brought this up!
