### ISSUE TITLE
setup.py says we use nose for testing, but we don't

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4341]
Someone noticed a few weeks back that there's also a dependency on `nose` in one of the requirements file.

We changed to `pytest` and I'm not aware of any `nose` usage anywhere, so let's take it out.

**Comment by ColCarroll** [comment]
To add historical context, this was a dependency through theano, which _for reasons_ required it to even import the project. If pymc-theano removes that, then this should be straightforward.
