### ISSUE TITLE
Flaky test: test_distributions_random.py::TestNestedRandom::test_TruncatedNormal

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4346]
A wild, flaky test has appeared.

On `master` it's currently failing here: https://github.com/pymc-devs/pymc3/runs/1562295314#step:8:1434

I already observed the flaky tests in a recent PR but it went away after re-running the CI.

**Comment by Sayam753** [comment]
Same flaky test appeared in https://github.com/pymc-devs/pymc3/runs/1638797078

**Comment by twiecki** [comment]
Probably just needs a seed.

**Comment by Sayam753** [comment]
Another one https://github.com/pymc-devs/pymc3/pull/4416/checks?check_run_id=1714255767

**Comment by michaelosthege** [comment]
Amazing how often they appear. And always in the same test, but sometimes with different parametrizations?!

But I just added the "wontfix" label, because all the `random` stuff will be replaced as we switch to `RandomVariable`. Let's hope it goes away then.

**Comment by Sayam753** [comment]
Sounds great :star_struck:. Is there a doc listing all the features that `RandomVariable` Op will add?

**Comment by michaelosthege** [comment]
> 
> 
> Sounds great 🤩. Is there a doc listing all the features that `RandomVariable` Op will add?

Not for the `RandomVariable` `Op` that is already implemented in Theano.
However there is Brandon's blogpost from three years ago when he birthed the idea: https://brandonwillard.github.io/random-variables-in-theano.html#orged59f09

My understanding is that essentially the `.eval()` of the `TensorVariable` will result in drawing random samples - also on dependent variables that are created _from_ a  `RandomVariable`.
This way we don't need to walk up the graph in PyMC3 as we currently do in `draw_samples` and the like.

**Comment by ricardoV94** [comment]
Test seems to be stable for a while now
