### ISSUE TITLE
Replace TravisCI badge with GitHubActions one

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4350]
The readme and the docs (docs/source/semantic_sphinx/layout.html) both reference a badge from TravisCI.

These should be replaced with a badge from GitHubActions, reflecting the current build status: https://github.com/pymc-devs/pymc3/workflows/pytest/badge.svg

**Comment by CloudChaoszero** [comment]
Hey there @MarcoGorelli! I went ahead and took a stab at on this issue.
* You can see the mentioned PR ⬆️  on it.

I hope it helps :D
