### ISSUE TITLE
pymc-examples submodule should track main branch

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4357]
Currently, it you do
```
git submodule update --init --recursive
```
then the git submodule pymc-examples is checked out in detached state at commit 729eb084116fad9e9b9df52eca76728f80a5c023

It would be better if it tracked the `main` branch  - some answers [here](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule/18799234#18799234) probably do that. I can take this up later, but any new contributor wanting to take this on is welcome to

**Comment by CloudChaoszero** [comment]
@MarcoGorelli I can look into this sometime soon.

**Comment by MarcoGorelli** [comment]
Hi @CloudChaoszero - awesome, thanks!

**Comment by CloudChaoszero** [comment]
Sounds great @MarcoGorelli! Made a PR, but unsure if it will solve the issue, as my local test/attempt did not work on my end. See the PR for details
