### ISSUE TITLE
Remove Plots & Diagnostics from PyMC Code Base

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/pymc#4371]
Plots and diagnostics are still accessible via PyMC3 but are actually implemented by ArviZ now. Although this was a good call when ArviZ was still nascent, now this causes confusion for new comers and overhead for devs, who have to mirror the functions in ArviZ, which is more work when ArviZ adds or changes functions (e.g `pm.hpd` vs. `az.hdi`).

To make all this more robust and easier to maintain, _we should completely remove plots and diagnostics from the PyMC code base_ and rely on ArviZ, since the latter library is now much more known and flies on its own (yeah, I'm a part-time poet).

The coming 4.0 major release is an opportunity to make this breaking change -- plus, it'll make the code base cleaner and leaner 👌 Feel free to comment if you wanna take on this issue 🖖

**Comment by MarcoGorelli** [comment]
> yeah, I'm a part-time poet

Must come from all that listening to Baba Brinkman ;)

**Comment by CloudChaoszero** [comment]
+1  lol ^^^
____
Hey there @AlexAndorra, is this an Issue I can participate in? 

Also, when do you think the ETA/Due Date for the coming 4.0 major release would be?

**Comment by AlexAndorra** [comment]
> Hey there @AlexAndorra, is this an Issue I can participate in?

Of course @CloudChaoszero ! I just assigned it to you. Feel free to ask questions 😉 

> Also, when do you think the ETA/Due Date for the coming 4.0 major release would be?

We usually don't give hard deadlines but are all commited and working to make that happen as soon as possible 🙂 
Getting new contributions is definitely helpful in that regard, so thank you!

**Comment by CloudChaoszero** [comment]
Great! I'll reach out if I have questions etc @AlexAndorra.

**Comment by CloudChaoszero** [comment]
@AlexAndorra Hey there! 

I was looking looking at the codebase, particularly [Pymc's plots/__init__.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/plots/__init__.py), and I saw functions like `compareplot` and `traceplot` borrow functionality from [arviz](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_compare.html), but do a couple of work arounds.

![Example](https://user-images.githubusercontent.com/19514362/103452313-0009c880-4c83-11eb-8779-2401965b67ee.png)




These workarounds tries to relabel `kwargs` parameters, and other related items like that.

I was wondering should the `kwargs` param renaming be copied to arviz repo, or should the expected breakchanges for v4.0 assume users rename the params themselves?

**Comment by AlexAndorra** [comment]
Yes, you can just remove all this @CloudChaoszero, as the idea is to completely delegate to ArviZ.
As a sidenote, [we just switched](https://github.com/arviz-devs/arviz/pull/1473) `compact` to `True` by default in `az.plot_trace` anyway 😉

**Comment by CloudChaoszero** [comment]
> Yes, you can just remove all this @CloudChaoszero, as the idea is to completely delegate to ArviZ.
> As a sidenote, [we just switched](https://github.com/arviz-devs/arviz/pull/1473) `compact` to `True` by default in `az.plot_trace` anyway 😉

Sounds great, thanks!

**Comment by CloudChaoszero** [comment]
@AlexAndorra  Quick Question: Should customer function `plot_posterior_predictive_glm `[Source](https://github.com/pymc-devs/pymc3/blob/master/pymc3/plots/posteriorplot.py) be removed as well, and users would try to adopt their function to arviz? I  only see arviz's `plot_posterior` [Source](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_posterior.html) right now.
* Note:  I can try to make a migration PR for it into Arviz, if necessaary

**Comment by AlexAndorra** [comment]
Ugh, that's a good question -- we discussed it recently with @MarcoGorelli and decided to keep it around IIRC. But the 4.0 release is a good opportunity to remove it and completely switch to ArviZ. 

`plot_posterior_predictive_glm` can probably be easily replicated with `az.plot_ppc` 🤔 
Curious about what @OriolAbril think: is it worth it to migrate it to ArviZ, or are ArviZ's current methods enough?

**Comment by OriolAbril** [comment]
I don't know how `plot_posterior_predictive_glm` works internally, but my guess is that is should be kept in PyMC3 until there are regression plots in ArviZ, that is when https://github.com/arviz-devs/arviz/issues/313 and https://github.com/arviz-devs/arviz/issues/512 are solved. Maybe in [this year's GSoc](https://github.com/arviz-devs/arviz/wiki/GSoC-2020-projects#increase-support-for-time-series-and-regressions)? 

How does that sound? It may not match the 3-4 timeline though

**Comment by MarcoGorelli** [comment]
`plot_posterior_predictive_glm` is just a few lines of code - if you have e.g. a model of the form `y = Normal(a + bx, sigma)` then it takes samples from the trace and plots `a + bx` for the various samples. Granted my knowledge here is really limited, but given that in the above example it disregards the values of `sigma` and just plots the regression lines `a + bx`, is it fair to call it "posterior predictive"?

**Comment by AlexAndorra** [comment]
> should be kept in PyMC3 until there are regression plots in ArviZ

Agreed @OriolAbril, let's do that then -- if this function proves hard to maintain because of v4 changes though, we'll probably remove it before ArviZ has regression functionalities.

> is it fair to call it "posterior predictive"?

Good catch @MarcoGorelli ! I think these are indeed no posterior _predictive_ samples but rather predictive _pushforward_ samples. As the function is meant to disapear soon though (see my answer above), let's not change the name, as that would be a breaking change for just a few months

**Comment by CloudChaoszero** [comment]
Sounds good, I'll update the PR accordingly!
