### ISSUE TITLE
JAX sampler fails when chains=1

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#4383]
I've found a bug where the jax numpyro sampler fails in the case of a single chain.  The failure is that the sampling proceeds but hangs at the end of sampling, requiring a keyboard interrupt to exit.  A simple reproducing example is below:

```
import numpy as np
import pymc3 as pm
import pymc3.sampling_jax

use_jax = True
sample = pm.sampling_jax.sample_numpyro_nuts if use_jax else pm.sample

n_steps = 25
chains = 1
n_samples, n_features = 100, 500

x = np.random.normal(size=(n_samples, n_features))
y = np.random.normal(size=n_samples)

with pm.Model() as model:
    weights = pm.Normal("weights", 0.0, sigma=10.0, shape=n_features)
    bias = pm.Normal("bias", 0.0, sigma=10.0)

    mu = pm.math.dot(x, weights) + bias
    observed = pm.Normal("observed", mu, 1.0, observed=y)

    tr = sample(n_steps, chains=chains)
```

In particular, the test fails for (jax+chains=1) but passes for (jax+chains=2), (pymc+chains=1), and (pymc+chains=2).  

This was tested on my own branches of pymc and theano-pymc, which roughly correspond to the latest master.

**Comment by roblem** [comment]
Perhaps related: I am also seeing a similar hang after sampling is completed when `chains>1` and the sampler uses `chain_method='vectorized'`  [here](https://github.com/pymc-devs/pymc3/blob/aedc8e9006c7e672e461774a5ee095562405c99c/pymc3/sampling_jax.py#L159) for better batching (but also occurs for `chains=1`).

**Comment by ricardoV94** [comment]
We have a test that uses `chains=1` and it is passing:

https://github.com/pymc-devs/pymc/blob/a5b13d4d78fbf397204f5b2f33b3b23b91ca008b/pymc/tests/test_sampling_jax.py#L30
