### ISSUE TITLE
Improve legibility of formula from developer guide

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4384]
[This formula in the developer guide](https://docs.pymc.io/developer_guide.html#reflection) doesn't look great

![image](https://user-images.githubusercontent.com/33491632/103155611-51085100-4799-11eb-9f03-b1d08a2d28bc.png)

I think it should be possible to write it with LaTex?

Am opening this as a good first issue, but I'll take it if nobody does. New contributors welcome!

**Comment by CloudChaoszero** [comment]
Hey @MarcoGorelli! Hope you had a good holiday. 

I am happy to submit a PR for this, and other LATEX-related formula inconsistencies on this page.

**Comment by MarcoGorelli** [comment]
awesome, thanks!
