### ISSUE TITLE
PyMC3 docker container from version 3.9.3  and above does not find module 'theano'

### ISSUE THREAD

**Issue by mdapri** [pymc-devs/pymc#4386]
Hi, I am using Docker Desktop on windows 10.
I have pulled the  version latest, 3.10.0 and 3.9.3 version  and the behavior is the same
The issue does not appear in version 3.9.2

opening the _api_quickstart.ipynb_  jupyter notebook located in  **/home/jovyan/notebooks** and running the first cell 

`import arviz as az`
`import matplotlib.pyplot as plt`
`import numpy as np`
`import pymc3 as pm`
`import theano.tensor as tt`
`import warnings`

`warnings.simplefilter(action="ignore", category=FutureWarning)`

the following  error appears

`.... ModuleNotFoundError: No module named 'arviz'`

Commenting the 
`import arviz as az`
the error becomes
`ModuleNotFoundErrorTraceback (most recent call last)`
`...`
`~/pymc3/__init__.py in __set_compiler_flags()`
`     31 def __set_compiler_flags():`
`     32     # Workarounds for Theano compiler problems on various platforms`
`---> 33     import theano`
`     34     current = theano.config.gcc.cxxflags`
`     35     theano.config.gcc.cxxflags = f"{current} -Wno-c++11-narrowing"`

`ModuleNotFoundError: No module named 'theano'`

No  issue on version 3.9.2

## Versions and main components
Docker Desktop with Docker Engine v19.03.13
OS: Windows 10
Docker pull commands:

- docker pull pymc/pymc3:version-3.9.3
- docker pull pymc/pymc3:version-3.10.0

**Comment by twiecki** [comment]
This is odd, the container should use the same install chain as our test env. @MarcoGorelli any idea?

**Comment by MarcoGorelli** [comment]
Hi @mdapri , thanks for the report

I hadn't yet looked at the Dockerfile, but I've noticed that it contains
```
    mamba env update -f environment-dev.yml
  else
    conda config --add channels conda-forge
    conda config --set channel_priority strict
    conda install -c conda-forge mamba --yes
    mamba env create -f environment-dev.yml
```
which may need to be updated to use `conda-envs/environment-dev-py38.yml` - are you interested in trying that out and then opening a pull request? If so, [here](https://github.com/pymc-devs/pymc3/blob/master/CONTRIBUTING.md)'s the contributing guide

---

having said that, the `environment-dev.yml` file still existed when 3.9.3 was released, so I don't know what would have caused that one to fail
