### ISSUE TITLE
Attribute Error using graphviz

### ISSUE THREAD

**Issue by Sayam753** [pymc-devs/pymc#4391]
I am trying to render graphviz plot for covariation_intercept_slope model from [Multilevel modelling notebook](https://docs.pymc.io/notebooks/multilevel_modeling.html). But it fails with Attribute Error.

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
with pm.Model() as model:
    sd_dist = pm.Exponential.dist(0.5)
    chol, corr, stds = pm.LKJCholeskyCov("chol", n=2, eta=2.0, sd_dist=sd_dist, compute_corr=True)
pm.model_to_graphviz(model)
```

**Please provide the full traceback.**
<details>
<summary>Traceback
</summary>

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-4f1383808ed6> in <module>
----> 1 pm.model_to_graphviz(model)

~/Desktop/pymc/pymc3/pymc3/model_graph.py in model_to_graphviz(model, formatting)
    241         raise ValueError(f"Unsupported formatting for graph nodes: '{formatting}'. See docstring.")
    242     model = pm.modelcontext(model)
--> 243     return ModelGraph(model).make_graph(formatting=formatting)

~/Desktop/pymc/pymc3/pymc3/model_graph.py in make_graph(self, formatting)
    207                 with graph.subgraph(name="cluster" + label) as sub:
    208                     for var_name in var_names:
--> 209                         self._make_node(var_name, sub, formatting=formatting)
    210                     # plate label goes bottom right
    211                     sub.attr(label=label, labeljust="r", labelloc="b", style="rounded")

~/Desktop/pymc/pymc3/pymc3/model_graph.py in _make_node(self, var_name, graph, formatting)
    148             label = f"{var_name}\n~\nData"
    149         else:
--> 150             label = v._str_repr(formatting=formatting).replace(" ~ ", "\n~\n")
    151 
    152         graph.node(var_name.replace(":", "&"), label, **attrs)

~/Desktop/pymc/pymc3/pymc3/model.py in _str_repr(self, name, dist, formatting)
     77         if dist is None and hasattr(self, "distribution"):
     78             dist = self.distribution
---> 79         return self.distribution._str_repr(name=name, dist=dist, formatting=formatting)
     80 
     81     def _repr_latex_(self, *, formatting="latex_with_params", **kwargs):

~/Desktop/pymc/pymc3/pymc3/distributions/distribution.py in _str_repr(self, name, dist, formatting)
    210 
    211         param_names = self._distr_parameters_for_repr()
--> 212         param_values = [
    213             get_repr_for_variable(getattr(dist, x), formatting=formatting) for x in param_names
    214         ]

~/Desktop/pymc/pymc3/pymc3/distributions/distribution.py in <listcomp>(.0)
    211         param_names = self._distr_parameters_for_repr()
    212         param_values = [
--> 213             get_repr_for_variable(getattr(dist, x), formatting=formatting) for x in param_names
    214         ]
    215 

~/Desktop/pymc/pymc3/pymc3/util.py in get_repr_for_variable(variable, formatting)
    132 def get_repr_for_variable(variable, formatting="plain"):
    133     """Build a human-readable string representation for a variable."""
--> 134     name = variable.name if variable is not None else None
    135     if name is None and variable is not None:
    136         if hasattr(variable, "get_parents"):

AttributeError: 'float' object has no attribute 'name'
```
</details>

Ping @Spaak 

## Versions and main components

* PyMC3 Version: on master 3cfee77
* Theano Version: 1.0.12
* Python Version: 3.8.6
* Operating system: macOS Big Sur
* How did you install PyMC3: (conda/pip) pip

**Comment by ArturoBell** [comment]
I've been having the same issue recently after changing macs and doing a fresh install. Curiously enough, the problem seems to arise when using a multivariate model (it displayed it correctly when building a simple univariate model). I think that the problem is not in the `pm.model_to_graphviz` function itself, but rather the model output is not being stored correctly (if you try to call only `model` or `model?` you will note that there is no information regarding the names of the variables and their distributions).

Edit: Closed the last parenthesis.

**Comment by Sayam753** [comment]
I debugged into this and suspect the source of bug here -

https://github.com/pymc-devs/pymc3/blob/2824027837931a6c2f1d4ac5f210eb36b8fdf7a7/pymc3/distributions/multivariate.py#L965-L967

Maybe we need to wrap both `n` and `eta` as tensor variables.

**Comment by Spaak** [comment]
Hey, sorry for the slow reply here, I was on holiday (at home, of course ;) ). I think @Sayam753 is right, in fact I've run into similar cases in some other distributions before, which resulted in similar errors (and I fixed them by indeed wrapping the parameters as tensors). I'll file a PR which also makes `get_repr_for_variable` a bit more robust to such cases in the future.
