### ISSUE TITLE
Update installation instructions to mention conda requirement

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4398]
If you try to `pip install pymc3`, like our readme instructs, you will have a bad time on most platforms because:
* You will have a hard time linking your system compilers to theano
* It will be super slow because mkl will not be installed

So really, it is required to at least install the dependencies of theano and pymc3 via conda/conda-forge and we should update our instructions accordingly.

**Comment by CloudChaoszero** [comment]
I can take this on @twiecki.

**Comment by twiecki** [comment]
Thanks @CloudChaoszero!
