### ISSUE TITLE
Error message with az.plot_trace(trace_h)

### ISSUE THREAD

**Issue by Jacques2101** [pymc-devs/pymc#4400]
## Description of your problem

Hi, I am new in PYMC3 then I try to use example from books to learn. From Bayesian Analysis with Python, I tried this code : 
```
N_samples = [30, 30, 30]
G_samples = [18, 18, 18]  

group_idx = np.repeat(np.arange(len(N_samples)), N_samples)
data = []
for i in range(0, len(N_samples)):
    data.extend(np.repeat([1, 0], [G_samples[i], N_samples[i]-G_samples[i]]))

with pm.Model() as model_h:
    μ = pm.Beta('μ', 1., 1.)
    κ = pm.HalfNormal('κ', 10)

    θ = pm.Beta('θ', alpha=μ*κ, beta=(1.0-μ)*κ, shape=len(N_samples))
    y = pm.Bernoulli('y', p=θ[group_idx], observed=data)

    trace_h = pm.sample(2000)

az.plot_trace(trace_h)
```

**Please provide the full traceback.**
```
/Users/jacques/opt/anaconda3/envs/bayes/lib/python3.8/site-packages/arviz/data/io_pymc3.py:87: FutureWarning: Using `from_pymc3` without the model will be deprecated in a future release. Not using the model will return less accurate and less useful results. Make sure you use the model argument or call from_pymc3 within a model context.
  warnings.warn(
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:  3.8 
* Theano Version:  1.0.4   
* Python Version: 3.8.5
* Operating system: macOS Big Sur 1.1
* How did you install PyMC3: conda

**Comment by twiecki** [comment]
That's just a warning, do you see a plot?

**Comment by OriolAbril** [comment]
Closing this as it's the same as https://github.com/arviz-devs/arviz/issues/1483. Let us know if we have missed something @Jacques2101
