### ISSUE TITLE
Update codebase to use new theano.gof.graph stack_search, inputs, etc., generator functions

### ISSUE THREAD

**Issue by Spaak** [pymc-devs/pymc#4404]
The API for `theano.gof.graph.stack_search` was updated (improved) in https://github.com/pymc-devs/Theano-PyMC/pull/259. This function is used here (and nowhere else in the PyMC3 codebase, I checked):

https://github.com/pymc-devs/pymc3/blob/240c372cf2709e1d3212aa5873b648aa6a6855cc/pymc3/model_graph.py#L72

At first I thought a simple change of argument names would do the trick, but this yields empty results. So I'm hoping @brandonwillard has a pointer on how to rewrite the old-style API to the new one :)

**Comment by twiecki** [comment]
This is a generator now, so maybe just wrapping this into `list` will do the trick?

**Comment by brandonwillard** [comment]
Yeah, wrapping the results of the new generator-based functions with `list` should do the trick; however, depending on how the results are used (e.g.  a one-time call to `node in inputs([graph])`, it can be a lot more efficient to use the generator directly.

**Comment by brandonwillard** [comment]
I've just created a `rel-1.0.15` release that can be used for this PR.

**Comment by Spaak** [comment]
Ah yes of course, I got thrown off by the return value not being used in `model_graph` (instead the ancestors are built up as a side effect of the `_expand` function), but also in that case wrapping in `list` should work. Thanks!
