### ISSUE TITLE
Multiple independent random walks with differing innovation sds

### ISSUE THREAD

**Issue by martiningram** [pymc-devs/pymc#4409]
Hi all,

Following on from a [post on discourse](https://discourse.pymc.io/t/multiple-independent-random-walks-with-differing-innovations/6541), Junpeng asked me to open an issue.

I am trying to declare a `GaussianRandomWalk` prior on multiple time series, each independent and with its own random walk standard deviation. I tried:

```python
mean_sigma = pm.HalfNormal('mean_rw_sigma', 1., shape=n_tourneys)
prior_means = pm.GaussianRandomWalk('prior_means', sigma=mean_sigma, shape=(n_years-1, n_tourneys))
```

but this does not compile, giving the error:

```
ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 4)
```

Junpeng mentioned that this likely used to work but was broken by [a helper](https://github.com/pymc-devs/pymc3/blob/2824027837931a6c2f1d4ac5f210eb36b8fdf7a7/pymc3/distributions/timeseries.py#L219-L225). He also mentioned a workaround with a diagonal covariance matrix, which should work but presumably this version would be more efficient.

## Versions and main components

* PyMC3 Version: 3.10.0
* Theano Version: 1.0.14
* Python Version: 3.7.9
* Operating system: Ubuntu
* How did you install PyMC3: pip

**Comment by junpenglao** [comment]
To add some context, the helper function is assuming the first dimension is time dimension. One workaround is to check the shape and only execute if the mu.shape[0] == shape[0]

**Comment by Sayam753** [comment]
I think the issue is similar to #4010

**Comment by junpenglao** [comment]
You are right, mark as duplicate.
