### ISSUE TITLE
GitHub Actions failing to install dependencies on Windows

### ISSUE THREAD

**Issue by Sayam753** [pymc-devs/pymc#4422]
PyMC3 does not get installed for windows in GitHub Actions run here - https://github.com/pymc-devs/pymc3/pull/4416/checks?check_run_id=1719646411

**Comment by michaelosthege** [comment]
I was able to create a fresh environment locally on Windows using the instructions from our Wiki.

The failure must be related to how we create the CI env 😐

**Comment by Sayam753** [comment]
Here is the related issue on cftime repo https://github.com/Unidata/cftime/issues/222 

Will it be a good idea to add the similar [fix](https://github.com/yt-project/yt/pull/3022/files) for PyMC3?

**Comment by Sayam753** [comment]
Closing the issue because the upstream `cftime` issues are fixed as per https://github.com/Unidata/cftime/issues/222#issuecomment-762362763
