### ISSUE TITLE
pymc3: unexpected minor version effect from 3.10.0 to 3.11.0

### ISSUE THREAD

**Issue by zeroaltitude** [pymc-devs/pymc#4430]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

In pymc3==3.10.0, it was valid to say

```
import pymc3 as pm
pm.summary(...)
```

That is, the summary method existed.

As of version 3.11.0, this is no longer the case: calling ```pm.summary()``` gives a ```no method found``` error.

The semantic versioning specification (https://semver.org/) seems to indicate that minor version updates should not break backwards compatibility. This is important because many projects pin versions using a fragment that looks like this ```pymc3>=3,<4``` to "band pin", which allows us to take minor and patch updates that are inevitable because of the perils of conflicts with exact version matches in complex projects, while still safely anticipating backwards compatibility.

## Versions and main components

* PyMC3 Version: 3.11.0
* Python Version: 3.8
* How did you install PyMC3: pip

**Comment by ricardoV94** [comment]
It seems this change was also missed in the Release Notes

**Comment by twiecki** [comment]
Ouch, sorry about that @zeroaltitude! You can just use `az.summary()` instead. We definitely need to adjust release notes for that. I even wonder if we should undo this change and cut a new release :-/.

**Comment by zeroaltitude** [comment]
@twiecki No worries -- I suspect that overall, it's better to eat this one. I mention it merely so that the team can move forward with this in mind. Undoing a release can be even more disruptive. But thank you so much for your future sensitivity to the issue -- I'm psyched to know this community is so thoughtful.

**Comment by zeroaltitude** [comment]
Also, do you mean that pm.summary() is an alias to arviz.summary()?

**Comment by michaelosthege** [comment]
> 
> 
> Ouch, sorry about that @zeroaltitude! You can just use `az.summary()` instead. We definitely need to adjust release notes for that. I even wonder if we should undo this change and cut a new release :-/.

We'll likely cut a `3.11.1` release soon, because of un-silenced warnings from `Theano-PyMC` (updating to Theano-PyMC 1.1.1).
However, this is just one of the ArviZ-delegated functions that we removed with #4397. Maybe this was a bit too fast, but it is certainly not the only change that was not preceeded by deprecation warnings. So I would actually not revert this change.

__Unfortunately, we do not follow a semantic versioning scheme.__

**Comment by twiecki** [comment]
@zeroaltitude Yes, all analysis and plotting functions were aliases that we now removed.

**Comment by twiecki** [comment]
At least we need to update the release information.

**Comment by zeroaltitude** [comment]
@michaelosthege It's worth considering whether using semver would be valuable -- your version identifiers are certainly in the format that would suggest it. Thanks for all the help and information!
