### ISSUE TITLE
Sampling from Poisson distribution  gives negative values

### ISSUE THREAD

**Issue by dchui1** [pymc-devs/pymc#4434]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pymc3 as pm
import theano.tensor as tt

def test_k(k):
  levels, distributions = np.unique(k, return_counts=True)
  print("Levels", levels, distributions)
  if levels[0] < 0:
    raise ValueError("Negative levels")
  return np.log(sum(k))

def model_with_value_individualk():
  model = pm.Model()
  with model:
    num_subjects = 500
    # num_subjects = len(data)
    tau = pm.Uniform('tau', lower=0, upper=3)
    k = pm.Poisson('k', tau, shape=num_subjects)
    myop = IndividualKOp(test_k)
    D_obs = pm.Potential("D_obs", myop(k))
                         # , observed={'thet': theta, 'data': data})

  return model

class IndividualKOp(tt.Op):
  itypes = [tt.lvector]
  otypes = [tt.dscalar]

  def __init__(self, likelihood_func):
    self.likelihood = likelihood_func
    # self.data = data
    # self.allocations = allocations


  def perform(self, node, inputs, outputs):
    # theta = inputs[0]
    k = inputs[0]
    # print("Theta", theta)
    logl = self.likelihood(k)
    outputs[0][0] = np.array(logl)


def main():
  res = model_with_value_individualk()
  with res:
    trace = pm.sample()

if __name__=="__main__":
  main()

```

**Please provide the full traceback.**
```python
Multiprocess sampling (4 chains in 4 jobs)
CompoundStep
>NUTS: [tau]
>Metropolis: [k]
Levels [1] [500]-----------------------| 0.00% [0/8000 00:00<00:00 Sampling 4 chains, 0 divergences]
Levels [1] [500]
Levels [1] [500]
Levels [1] [500]
Levels [1] [500]
Levels [1] [500]
Levels [-2 -1  0  1  2  3  4] [  4  30 132 178 116  37   3]
Levels [-2 -1  0  1  2  3  4] [  2  27 123 201 113  33   1]
Levels [-2 -1  0  1  2  3  4] [  7  28 116 196 124  26   3]
Levels [1] [500]
Levels [1] [500]
Levels [-2 -1  0  1  2  3  4  5] [  2  23 113 196 117  45   3   1]
pymc3.parallel_sampling.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/dchui/miniconda3/envs/be35/lib/python3.6/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
  File "/Users/dchui/miniconda3/envs/be35/lib/python3.6/site-packages/theano/gof/op.py", line 913, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Users/dchui/workspace/behavioral_econometrics/analysis/mcmc_bug.py", line 39, in perform
    logl = self.likelihood(k)
  File "/Users/dchui/workspace/behavioral_econometrics/analysis/mcmc_bug.py", line 10, in test_k
    raise ValueError("Negative levels")
ValueError: Negative levels

During handling of the above exception, another exception occurred:

```

**Please provide any additional information below.**

I'm trying to sample from a poisson distribution with an unknown mean and do a custom likelihood calculation dependent on the sampled value, based on the example provided [here](https://docs.pymc.io/notebooks/blackbox_external_likelihood.html). However, the sampled values coming from the Poisson distribution seem to be negative which should not be possible. I've created a minimal example that doesn't have any external dependencies and am still encountering this issue

## Versions and main components

* PyMC3 Version: 3.10
* Theano Version: 1.05
* Python Version: 3.6.10
* Operating system: OSX 11.1
* How did you install PyMC3: Pip

**Comment by ricardoV94** [comment]
Does your final trace include negative poison values when you don't raise the ValueError?

I would imagine those are just proposed values that always get rejected by the Metropolis sampler in the end but that you are observing them in the pm.Potential before this is done. 

If this is the case you can check for it in your custom likelihood function (if it causes some issue like divide by zero or log of negative numbers) or if it's too much trouble you may replace the pm.Potential with a pm.DensityDist.

**Comment by dchui1** [comment]
Ah, that explains it. Thanks!  So am I to understand that these observed values wouldn't have been accepted as an acceptable value anyways?
