### ISSUE TITLE
Option to build docs quickly

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4435]
Currently, building the docs takes a while because all the notebooks need to render.

It would be good to have a way to build them quickly, so that if you want to check whether links and other things display correctly, then you can iterate quickly without needing to wait for the notebooks to re-render each time.

Maybe a flag could be added to docs/source/sphinxext/gallery_generator.py , or maybe there should be an empty branch in pymc-examples. Not sure yet - opening as a beginner-friendly issue for now, but I'll take a look later if nobody takes it on

**Comment by Pyrsos** [comment]
Hi, I'd like to work on this if possible. Any pointers on where to start?

**Comment by MarcoGorelli** [comment]
Hi @Pyrsos - first thing would be to check that you're able to build the docs locally.

Then, I think I'd advise:
- in the pymc-examples submodule, make a new branch (maybe called `fast-docs`, or something else if you think of a better name) in which you remove all the ipynb notebooks and make the table of contents files ([here](https://github.com/pymc-devs/pymc-examples/blob/main/examples/table_of_contents_examples.js) and [here](https://github.com/pymc-devs/pymc-examples/blob/main/examples/table_of_contents_tutorials.js)) have empty dictionaries, e.g. `Gallery.contents = {}`
- check whether building the docs with the submodule checked out to this branch does indeed skip the notebooks and is quicker
- if so, then open a pull request to `pymc-examples` from this new branch, and document this new process somewhere here

In a bit of a hurry now, hope this is clear enough to get started - if not, please do write and I'll explain further later

**Comment by OriolAbril** [comment]
@MarcoGorelli I think this can be closed already

**Comment by MarcoGorelli** [comment]
indeed, thanks 👍
