### ISSUE TITLE
Simplify Wald's logcdf method

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4436]
Wald's logcdf checks a lot of conditions for degenerate distribution parameters/values that `=0` or `=np.inf` to decide whether to return a logcdf of `-inf` or `0`. As far as I can tell, this is the only distribution that goes to such lengths to accommodate degenerate cases, some of which are not even allowed by the distribution initialization (or the docstrings or the logp):

https://github.com/pymc-devs/pymc3/blob/823906a3efcf66897eac8a4c89052d9153bca49e/pymc3/distributions/continuous.py#L1138-L1162

Note that the explicit bound parameter checks were added only recently in #4421 and were not in the original implementation of the logcdf method. In fact, they overwrite several of the degenerate `lam == 0` checks as well as some implicit (I think) `value >= mu & mu == 0` checks.

Also, AFAIK these degenerate conditions are not being tested anywhere.

Unless there is a good reason for it, I would suggest stripping away the degenerate case switches, and simply have something like the following (which I haven't tested yet):

```python
return bound(
    a + tt.log1p(tt.exp(b - a)),
    0 < value, 
    0 < mu,
    0 < lam,
    0 <= alpha,
)

**Comment by Spaak** [comment]
That seems like a good simplification to me. What is the worst that can happen if the degenerate case holds? If no untraceable disaster, then EAFP.

**Comment by ricardoV94** [comment]
The degenerate case is not supposed to be allowed as per the docstrings / conventional definition of parameter support (e.g., Wikipedia). In this case it will simply be captured by the bound and return `-np.inf`. This is no worse than what happens with a Normal with sigma=0 (that one actually raises a ZeroDivisionError).
