### ISSUE TITLE
not working with M1 Mac?

### ISSUE THREAD

**Issue by keyuchen21** [pymc-devs/pymc#4442]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem
try to run pymc3 on m1 macbook

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm

X, y = linear_training_data()
with pm.Model() as linear_model:
    weights = pm.Normal("weights", mu=0, sigma=1)
    noise = pm.Gamma("noise", alpha=2, beta=1)
    y_observed = pm.Normal(
        "y_observed",
        mu=X @ weights,
        sigma=noise,
        observed=y,
    )

    prior = pm.sample_prior_predictive()
    posterior = pm.sample()
    posterior_pred = pm.sample_posterior_predictive(posterior)
```

**Please provide the full traceback.**
```python
[The error output here]
<img width="480" alt="WeChat7f9f2341bf0dd8f2fc8c5239481de045" src="https://user-images.githubusercontent.com/54015474/105778887-488f6b80-5f3b-11eb-9de3-2b769de23017.png">

```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by ericmjl** [comment]
The stack below PyMC3 is pretty heavily dependent on having x86 processors. The move to JAX will also be a bit of an issue. Resolving this problem will take time, and is mostly dependent on the bottom of the stack (JAX, in particular) gaining arm64 support. 

I am going to close this issue, as there's nothing much the dev team can do about it at the moment. That said, I will also pin it to the issue tracker, as it's fairly important for other users to be able to see the response here.

Not that I don't sympathize with the lack of M1 support, but M1 being a totally different architecture compared to what the DS world is used to, there will be a bit of time needed before things are fully ported over. In my prior experience, the community takes about a year to catch up to architectural changes.

**Comment by fonnesbeck** [comment]
@km5ar I am able to run PyMC3 on an M1 machine, but it needs to be run under Rosetta2 rather than in ARM Python, at least for the tine being.

**Comment by keyuchen21** [comment]
@fonnesbeck could you told me what should I do in order to run under rosetta2?

**Comment by fonnesbeck** [comment]
Just install the Intel Python as you would for an older Mac. It will use Rosetta automatically. Don't install native ARM Python.

**Comment by keyuchen21** [comment]
@fonnesbeck  Thank you it worked for me.
