### ISSUE TITLE
Upgrade pyupgrade

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4453]
Issue here is:

1. in `.pre-commit-config.yaml`, change the `ref` of `pyupgrade` from v2.7.4 to v2.8.0
2. run `pre-commit run pyupgrade --all-files`
3. run `pre-commit run pylint --all-files` - there will be lots of errors from unused imports, so you should remove them (or you could look into using [autoflake](https://github.com/myint/autoflake) to do it for you)
4. if both `pre-commit run pylint --all-files` and `pre-commit run pyupgrade --all-files` both pass, then open a pull request :rocket: 

---

xref #4451

**Comment by asinghgaba** [comment]
Hey @MarcoGorelli 👋 I did all the tasks described in your comment. I have opened a pull request, if you could please look over it and let me know if there is anything else I can do. Thanks!

**Comment by Sayam753** [comment]
@MarcoGorelli , is this issue resolved by #4455?

**Comment by MarcoGorelli** [comment]
yup, thanks
