### ISSUE TITLE
`RecursionError` when pickling a larger sample. Small sample is fine.

### ISSUE THREAD

**Issue by Alexander-Serov** [pymc-devs/pymc#4478]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

I'm trying to run my pymc model on different subsets of my data set (gradually increasing the number of elements.).

When I run it on a small data set, it runs just fine:
```
Parameters: {'chains': 4, 'draws': 1000, 'max_treedepth': 10, 'target_accept': 0.95, 'tune': 1000}
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 15 jobs)
NUTS: [sigma_total_error, B]
:---------------------------------------------------------------| 0.19% [15/8000 00:03<28:02 Sampling 4 chains, 0 divergences]]
```

However, when I increase the length of my data set (while keeping exactly the same model, code and data types), I get a `RecursionError`:
```
Parameters: {'chains': 4, 'draws': 1000, 'max_treedepth': 10, 'target_accept': 0.95, 'tune': 1000}
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 15 jobs)
NUTS: [sigma_total_error, B]
Traceback (most recent call last):
  File ".\main.py", line 57, in <module>
    trace = pm.sample(**sampling_kwargs, cores=cores, return_inferencedata=True)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\sampling.py", line 557, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\sampling.py", line 1470, in _mp_sample
    pickle_backend=pickle_backend,
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\parallel_sampling.py", line 423, in __init__
    step_method_pickled = pickle.dumps(step_method, protocol=-1)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\theano\graph\basic.py", line 562, in __getstate__
    d = self.__dict__.copy()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Please provide a minimal, self-contained, and reproducible example.**
```python
with model:
      trace = pm.sample(draws = 1000,
        tune =1000,
        chains = 4,
        target_accept = 0.95,
        max_treedepth=10, cores=15, return_inferencedata=True)
```

// Sorry for not providing a reproducible example yet: part of it is confidential. I will need to modify it if you guys need it. Please let me know.

**Please provide the full traceback (same as above).**
```python
Parameters: {'chains': 4, 'draws': 1000, 'max_treedepth': 10, 'target_accept': 0.95, 'tune': 1000}
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 15 jobs)
NUTS: [sigma_total_error, B]
Traceback (most recent call last):
  File ".\fit_pv_forecast.py", line 57, in <module>
    trace = pm.sample(**sampling_kwargs, cores=cores, return_inferencedata=True)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\sampling.py", line 557, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\sampling.py", line 1470, in _mp_sample
    pickle_backend=pickle_backend,
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\pymc3\parallel_sampling.py", line 423, in __init__
    step_method_pickled = pickle.dumps(step_method, protocol=-1)
  File "C:\tools\miniconda3\envs\packaged\lib\site-packages\theano\graph\basic.py", line 562, in __getstate__
    d = self.__dict__.copy()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Please provide any additional information below.**
I was wondering whether you have encountered this problem before and could know what it is related to? What kind of dictionary with recursion could it encounter? I am very puzzled. Sorry if it's something evident and I have missed it. Thanks!

It seems that the parallel sampler is unable to pickle the step function. But what could be wrong with it if it’s automatically created?
I've checked: using `dill` fails as well.

Single-core sampling (`core=1`) samples just fine even on the large data set:
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [sigma_total_error, B]
 |██---------------------------------------------------------------------------------------------| 2.60% [52/2000 01:26<53:57 Sampling chain 0, 0 divergences]
```

## Versions and main components

* PyMC3 Version: 3.11.0
* Theano Version: Theano-PyMC   1.1.0
* Python Version: 3.7.8
* Operating system: Win 10 64
* How did you install PyMC3: pip

**Comment by Alexander-Serov** [comment]
Seems like https://github.com/pymc-devs/pymc3/issues/4273 can be related.
On Linux, the same code does not fail but is just stuck indefinitely at 0.

**Comment by ricardoV94** [comment]
@Alexander-Serov Do you still find this issue in `v3.11.2`?

We would definitely need a fully reproducible example to figure this out.
