### ISSUE TITLE
Error Importing PyMC3:  'TheanoConfigParser' object has no attribute 'gcc__cxxflags'

### ISSUE THREAD

**Issue by RylanSchaeffer** [pymc-devs/pymc#4479]
## Description of your problem

I try importing PyMC3 and get the following error:

```
(base) rylansch@openmind7 /om2/user/rylansch/FieteLab-ddCRP$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3 as pm
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/om2/user/rylansch/anaconda3/lib/python3.7/site-packages/pymc3/__init__.py", line 39, in <module>
    __set_compiler_flags()
  File "/om2/user/rylansch/anaconda3/lib/python3.7/site-packages/pymc3/__init__.py", line 35, in __set_compiler_flags
    current = theano.config.gcc__cxxflags
AttributeError: 'TheanoConfigParser' object has no attribute 'gcc__cxxflags'

```

## Versions and main components

* PyMC3 Version: 3.11.1
* Theano Version: 1.0.5
* Python Version: 3.7.4
* Operating system: LSB Version:    :core-4.1-amd64:core-4.1-noarch
* How did you install PyMC3: (conda/pip) pip
* Operating system:
```
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core

```

**Comment by RylanSchaeffer** [comment]
I can import `theano` apparently without problem:

```
(base) rylansch@openmind7 /om2/user/rylansch/FieteLab-ddCRP$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
>>> 
```

**Comment by brandonwillard** [comment]
This version of PyMC3 requires [`theano-pymc==1.1.2`](https://github.com/pymc-devs/pymc3/blob/0fd439f5d70f90d74f5304f956be872819d3961f/requirements.txt#L8).

**Comment by RylanSchaeffer** [comment]
@brandonwillard , I also have that version installed:

```
$ pip install theano-pymc==1.1.2
Requirement already satisfied: theano-pymc==1.1.2 in /rdma/vast-rdma/vast/fiete/rylansch/anaconda3/lib/python3.7/site-packages (1.1.2)
```

**Comment by RylanSchaeffer** [comment]
Is it possible `theano` is conflicting with `theano-pymc`?

**Comment by RylanSchaeffer** [comment]
I uninstalled `theano` and now I have a new error:

```
(base) rylansch@openmind7 /om2/user/rylansch/FieteLab-ddCRP$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/om2/user/rylansch/anaconda3/lib/python3.7/site-packages/pymc3/__init__.py", line 39, in <module>
    __set_compiler_flags()
  File "/om2/user/rylansch/anaconda3/lib/python3.7/site-packages/pymc3/__init__.py", line 35, in __set_compiler_flags
    current = theano.config.gcc__cxxflags
AttributeError: module 'theano' has no attribute 'config'
```

**Comment by RylanSchaeffer** [comment]
This [SO comment](https://stackoverflow.com/questions/51338107/module-theano-has-no-attribute-compile) directed me to this [SO post](https://stackoverflow.com/questions/41174995/import-theano-gives-the-attributeerror-module-theano-has-no-attribute-gof/41191592#41191592), which suggests there's some problem with Theano's installation.

**Comment by brandonwillard** [comment]
The old Theano package will conflict with the Theano-PyMC package, so you can't have them both installed in the same environment.

**Comment by RylanSchaeffer** [comment]
Yep! Uninstalling everything and reinstalling PyMC3 with conda worked.

**Comment by isosphere** [comment]
A `pip uninstall theano` fixed this for me, for folks that would like to try a minimal solution.

**Comment by Aiman73** [comment]
@RylanSchaeffer how to uninstall everything?

**Comment by leoTiez** [comment]
@Aiman73 
This should do the trick
```
python3 -m pip uninstall theano
python3 -m pip uninstall theano-pymc
python3 -m pip uninstall pymc3
python3 -m pip install pymc3
```
Replace `python3` with your preferred python version.

**Comment by jtlz2** [comment]
@leoTiez Thank you!

**Comment by 19Kaushiki** [comment]
I am trying to import theano and pymc3 but using following versions
PyMC3 Version: 3.11.4
Theano Version: 1.0.5
Python Version: 3.10.13
Using MacOS M2
 I get the following error:
'TheanoConfigParser' object has no attribute 'change_flags'

**Comment by fonnesbeck** [comment]
@19Kaushiki You should be using the latest PyMC version from this repository, and not PyMC3. That version is long outdated, and may not work at all with a M2 Mac.

**Comment by 19Kaushiki** [comment]
I tried importing pymc. I am still facing an error:

AttributeError: module 'numpy.__config__' has no attribute 'get_info'

Also theano throws the same error:

AttributeError: 'TheanoConfigParser' object has no attribute 'change_flags'

**Comment by fonnesbeck** [comment]
You should not be using Theano at all with PyMC v5. I would try again with a clean conda environment. Just do `conda install pymc` from a new conda env and it should set everything up properly.

**Comment by 19Kaushiki** [comment]
It is still giving me the error:
AttributeError: module 'numpy.config' has no attribute 'get_info'

I have created new environment and uninstalled and re-installed pymc. I do not understand what might be creating a problem

**Comment by 19Kaushiki** [comment]
I figured it out - was able to import pymc - thank you

**Comment by canyon289** [comment]
Glad you figured it out PyMC3 is deprecated. For anyone else dont try importing it. If its installelde in your environment delete it and probably the whole env. Im locking this issue as such
