### ISSUE TITLE
Fixup warning about inferencedata

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#4481]
https://github.com/pymc-devs/pymc3/blob/0fd439f5d70f90d74f5304f956be872819d3961f/pymc3/sampling.py#L465-L470

Task is:

- add `stacklevel=2` to the `FutureWarning`
- clarify the warning so it says "In v4.0" rather than "in an upcoming release"

some tests may need updating too

**Comment by Pyrsos** [comment]
I'd like to have a go with this. @MarcoGorelli can you let me know what I need to look for with updating the tests?

**Comment by MarcoGorelli** [comment]
@Pyrsos look for any test which makes an assertion about the warning message, and update it

**Comment by canyon289** [comment]
Looks like this one has a merged PR so closing. Feel free to reopen if I'm mistaken
