### ISSUE TITLE
Convert bash build scripts to Python

### ISSUE THREAD

**Issue by Pyrsos** [pymc-devs/pymc#4483]
Currently there are two different shell scripts for building the docs (`build_and_deploy_docs.sh` and `fast_build_docs.sh`). These can be changed from bash scripts to Python scripts. In addition there should be an option for building the docs but not deploying them, therefore a third script.

@MarcoGorelli do you think it might be better to have just a single Python script, where arguments are passed upon execution, instead of having three separate scripts? So someone can do `build_script.py --mode=fast`?

I can start working on this.

**Comment by MarcoGorelli** [comment]
@ColCarroll thoughts on this? You're the one using the `build_and_deploys_docs.sh` script, so maybe it's best leaving that one alone and only making Python scripts for building the docs locally (as they are what contributors would be doing)?

**Comment by ricardoV94** [comment]
Is this still relevant?

**Comment by MarcoGorelli** [comment]
Not sure - @OriolAbril do you know?

**Comment by OriolAbril** [comment]
Not sure. I updated the [makefile](https://github.com/pymc-devs/pymc/blob/main/Makefile) which is the default way for building docs provided by sphinx and documented how to use it at https://docs.pymc.io/en/latest/contributing/build_docs.html, I don't know how OS sensitive it is, I only tested it on my computer using ubuntu (also only tested make clean and make html). 

We definitely need some clean up, the build and deploy is not needed anymore, but it might be worth to have a build docs that is equivalent to the makefile?

**Comment by OriolAbril** [comment]
Closing this. Building the documentation is now significantly easier and doesn't need scripts. Given how the original bash scripts have been completely removed, it doesn't make sense to translate them anymore, everything is working without scripts at all.
