### ISSUE TITLE
Non-reproducible random draws with `sample_prior_predictive` and set random seed

### ISSUE THREAD

**Issue by alcrene** [pymc-devs/pymc#4490]
If I have a code file with the following:

```python
# non_reproducible.py
import pymc3 as pm
import theano.tensor as tt

with pm.Model() as model:
    pm.Normal('a')
    pm.Normal('b')
    pm.Normal('c')
    pm.Normal('d')

pp = pm.sample_prior_predictive(samples=1, model=model,
                                random_seed=100)
print({k:pp[k] for k in sorted(pp)})
```
and run it multiple times, I get different results. (In the example below, values for `a` and `c` are swapped.)
```bash
python non_reproducible.py
# {'c': array([-1.74976547]), 'b': array([0.3426804]), 'a': array([1.1530358]), 'd': array([-0.25243604])}
python non_reproducible.py
# {'a': array([-1.74976547]), 'b': array([0.3426804]), 'c': array([1.1530358]), 'd': array([-0.25243604])}
```
In my opinion this defeats the whole purpose of being able to set the random seed.
(Note: it is essential to run the code in different sessions python sessions to see the effect.)

The reason is that the function [uses `set` to get a unique set of variable names](https://github.com/pymc-devs/pymc3/blob/47b36586676a0af6505f376afff2193ab5a5ed84/pymc3/sampling.py#L1935), and the random draws depend on the  (undefined) ordering of the returned set.

A simple fix might be to sort the variables names before sampling, as I've done [here](https://github.com/alcrene/pymc3/commit/c0753dbb0a7de6d0af0711be0223c80ecd7a5432). This has the side-effect of making the result independent of the order in which variables are specified, which I think is nice.

I'm not proposing my fix as a PR because figuring out and testing consistency with other functions goes beyond my current needs. For example, `sample_posterior_predictive` is (I think) reproducible given a random seed, because it just takes the list of variable names. But it likely _does_ depend on the order in which variables are specified.

## Versions and main components

* PyMC3 Version: master ([27 Feb 2021](https://github.com/pymc-devs/pymc3/tree/47b36586676a0af6505f376afff2193ab5a5ed84))
* Theano Version: Theano-PyMC 1.1.2
* Python Version: 3.8.6
* Operating system: OpenSUSE LEAP 15.2
* How did you install PyMC3: pip  (dependencies with conda)

**Comment by ricardoV94** [comment]
Thanks for your detailed input. It is really helpful. 

We are currently rewriting the random sampling system so we'll keep a look on this issue and have it sorted out.

Linking to #4463

**Comment by alcrene** [comment]
Glad I could be of help !

If you are rewriting the random sampling system, you may want to consider switching to the new [Generator](https://numpy.org/doc/stable/reference/random/index.html#quick-start) objects rather than seeding the global legacy generator as you are doing now with `np.random.seed`. In addition to making it easier to maintain multiple separate RNGs, the new interface provides for better/faster generators.

The rational for the new RNG API is well explained in [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html).
