### ISSUE TITLE
Error wrapping model in MAP/MCMC

### ISSUE THREAD

**Issue by ihrke** [pymc-devs/pymc#451]
(this is pymc version 2.3)

I get a weird error, when I try to set up a hierarchical model.
pymc allows me to specify and link all the nodes, but as soon as I put the model into an `MCMC` or `MAP` instance, it breaks.

I compiled a detailed description of the problem here:

http://nbviewer.ipython.org/gist/ihrke/8316068

My model-setup code is relatively (maybe overly) complex. Maybe I abused pymc too much? Or might it be a real bug?

Thanks,

Matthias

**Comment by fonnesbeck** [comment]
`Model` is not intended to be instantiated directly. Best just to pass the variables as a list to `MAP`. I like to generate models with a function, returning the `locals()` whenever the function is called.

**Comment by ihrke** [comment]
ok. Then again, I've seen calls to `pymc.Model` in several examples (maybe blogs etc).
Is there a specific reason why it cannot be instantiated directly?

**Comment by fonnesbeck** [comment]
Its a common mistake. Its not that you _can't_, but it is not how we intended models to be constructed. For one, it adds an extra, unnecessary step to specifying the model. None of our examples (on the wiki) should call `Model` directly, but let me know if this is not the case.
