### ISSUE TITLE
Request: Consider using a more compatible polya-gamma random sampler

### ISSUE THREAD

**Issue by zoj613** [pymc-devs/pymc#4520]
## Description of your feature request

This is a feature request following a comment by @brandonwillard in https://github.com/pymc-devs/symbolic-pymc/pull/107 .

Looking at the source code, it appears that for random sampling, aesara uses a polya-gamma distribution random sampler whose API isn't quite compatible to scipy's. 
https://github.com/pymc-devs/aesara/blob/6c5a8fa044aae27a7ce2b6f90ef49f119bf5bdcd/aesara/tensor/random/basic.py#L387-L421

I would like to propose an alternative that has a scipy compatible API, which I think would ease the maintenance burden. `polyagamma` (repo: https://github.com/zoj613/polya-gamma) uses the same API as scipy/numpy statistical functions and is flexible and performant.

Here is an example usage:
```python
import numpy as np
from polyagamma import polyagamma

o = polyagamma()

# Get a 5 by 10 array of PG(1, 2) variates.
o = polyagamma(z=2, size=(5, 10))

# Pass sequences as input. Numpy's broadcasting rules apply here.
h = [[1, 2, 3, 4, 5], [9, 8, 7, 6, 5]]
o = polyagamma(h, 1)

# Pass an output array
out = np.empty(5)
polyagamma(out=out)
print(out)

# one can choose a sampling method from {devroye, alternate, gamma, saddle}.
# If not given, the default behaviour is a hybrid sampler that picks a method
# based on the parameter values.
o = polyagamma(method="saddle")

# We can also use an existing instance of `numpy.random.Generator` as a parameter.
# This is useful to reproduce samples generated via a given seed.
rng = np.random.default_rng(12345)
o = polyagamma(random_state=rng)
```

**Comment by brandonwillard** [comment]
This would need to be done in the `v4` branch.

**Comment by zoj613** [comment]
Are you suggesting i submit a PR to said branch?

**Comment by brandonwillard** [comment]
Yeah, that would be possible now.  The package would likely need to be a conditional dependency (i.e. require a `try` block that attempts the import), and it would probably belong in `pymc3.distributions.continuous`.

**Comment by zoj613** [comment]
@brandonwillard see #4531 for a draft. I am not sure how random generators are passed around by the distributions in the continuous.py module. The distribution class in distribution.py uses a `rng` variable in the `__new__` method that doesnt seem to be directly used by any of the subclasses so I am not sure what is the correct way to make use of it in the PolyaGamma class.

**Comment by brandonwillard** [comment]
At the moment, it's safe to assume that most design questions like that probably haven't been completely worked out, yet.
