### ISSUE TITLE
Check that correct Theano-PyMC version is installed

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4527]
There are lot of users who seem to have both, `Theano`,  and `Theano-PyMC` installed which is causing all kinds of problems. We should thus do two things:

* Specify for pip and conda that `Theano` can *not* be installed (I think at least conda has that option)
* Upon PyMC3 import, make sure that the correct Theano-PyMC version is installed and give an informative error message with instructions for installing the correct version

**Comment by michaelosthege** [comment]
Closed by #4540
