### ISSUE TITLE
Install on Apple Silicon fails because of missing theano-pymc

### ISSUE THREAD

**Issue by stnatter** [pymc-devs/pymc#4532]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```
conda install -c conda-forge pymc3
```

**Please provide the full traceback.**
```
Problem: nothing provides theano-pymc 1.0.11 needed by pymc3-3.10.0-pyhd8ed1ab_0
```

**Please provide any additional information below.**
above is the more informative output I get from mamba instead of conda. 
suspecting the problem is [this](https://github.com/conda-forge/theano-pymc-feedstock)
The theano-pymc feedstock is archived?

## Versions and main components

* PyMC3 Version: 3.10
* Aesara Version:
* Python Version: 3.8.8
* Operating system: macOS big sur
* How did you install PyMC3: (conda/pip)

**Comment by twiecki** [comment]
Can you try again with the new PyMC 3.11.2 release?

**Comment by stnatter** [comment]
With a minimal conda environment with `Python 3.9.2` I get the following using `mamba`:
```
(test) Steffens-M1-MBP:~ steffen$ mamba install -c conda-forge pymc3=3.11.2
        mamba (0.8.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

Looking for: ['pymc3=3.11.2']

conda-forge/osx-arm64    Using cache
conda-forge/noarch       Using cache
pkgs/main/osx-arm64      Using cache
pkgs/main/noarch         Using cache
pkgs/r/noarch            Using cache
pkgs/r/osx-arm64         [====================] (00m:00s) 404 Failed
Encountered problems while solving.
Problem: nothing provides mkl-service needed by pymc3-3.11.2-pyhd8ed1ab_0
```
and using `conda`:
```
(test) Steffens-M1-MBP:~ steffen$ conda install -c conda-forge pymc3=3.11.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                           

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
of course Intel's mkl-service is really not needed here.

**Comment by twiecki** [comment]
Hm, seems like `mkl-services` is not compiled for your machine. I opened an issue here: https://github.com/conda-forge/mkl-service-feedstock/issues/15

@fonnesbeck You also have a new Mac but are running PyMC3 just fine, no?

**Comment by fonnesbeck** [comment]
The easiest way to get it working is to run Intel Python and not native M1 Python. The Python scientific stack (except for Tensor flow) works fine on the former, and Rosetta2 makes it plenty fast.

**Comment by stnatter** [comment]
Thanks gents. Everything else in the scientific stack (other than `pymc3`) works natively on macOS-arm64. This includes Tensorflow 2.4 (from Apple fork) as well as things like `numba` and `dask`. Am hoping that I soon can use `pymc3` natively too. BTW I added `pymc3` to the conda-forge migration for Apple Silicon already. Seems Google hasn't released `jax` and `jaxlib` for macOS-arm64 yet.
@twiecki if `pymc3` runs natively I don't see why Intel's math kernel lib should be needed.

**Comment by stnatter** [comment]
https://github.com/conda-forge/pymc3-feedstock/pull/53

**Comment by ricardoV94** [comment]
Closing this as stale
