### ISSUE TITLE
Remove MultiObservedRV in v4

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#4534]
`MultiObservedRV` support hasn't been implemented in `v4` (because I couldn't really tell what it was).  @OriolAbril explained it to me [here](https://github.com/pymc-devs/pymc3/pull/4489#discussion_r583973328_), and it sounds like something we should remove entirely.

I'm opening this issue so that someone can inform us of any important functionalities that `MultiObservedRV` exclusively provides, so that we can implement those in some other way before removing the old `MultiObservedRV`-related code.

**Comment by ricardoV94** [comment]
This is somewhat related to the DensityDist, no? We should also decide what to do with that.

**Comment by lucianopaz** [comment]
`DensityDist` was the only distribution that used `MultiObservedRV`. It was a hackish way to pass distribution parameters into the user's supplied `logp`.

If you had a `logp` function that was defined like this:

```python
def logp(value, mu, sigma):
    return -0.5*np.log(2 * np.pi) - at.log(sigma) - 0.5*((value - mu)/sigma)**2
```

In v3 you had to do this to be able to pass parameter values to `value`, `mu` and `sigma`

```python
with pm.Model():
    mu = pm.Normal("mu")
    sigma = pm.HalfNormal("sigma")
    pm.DensityDist("dist", logp, observed={"value": np.ones(10), "mu": mu, "sigma": sigma})
```

In #5026, we completely changed the API of `DensityDist`s and made it much more similar to other distributions. With the new API, you need to do:

```python
with pm.Model():
    mu = pm.Normal("mu")
    sigma = pm.HalfNormal("sigma")
    pm.DensityDist("dist", mu, sigma, logp=logp, observed=np.ones(10))
```

The new `DensityDist` relies on the positional arguments to define the distribution's parameters, and those are then supplied into all the customizable methods: `logp`, `logcdf`, `random` and `get_moment`.

If #5026 is approved and merged, we should just completely remove `MultiObservedRV`.

**Comment by ricardoV94** [comment]
This Class seems to not be present anymore in the codebase, so the only thing left is to remove old tests:

https://github.com/pymc-devs/pymc/blob/600fe90d3101412787e63d8a5bfc106db4b85b1a/pymc/tests/test_idata_conversion.py#L391-L446
