### ISSUE TITLE
Running Error: 'OverflowError: Python int too large to convert to C long'

### ISSUE THREAD

**Issue by Hossein-1991** [pymc-devs/pymc#4535]
## Description of your problem

Hi 
In the following code, I've encountered an unusual error! please help me to solve that...
```python
with pm.Model():
    s = pm.Lognormal('s', mu = 100 , sigma = 0.33)
    obs = pm.Poisson('obs',mu = s ,observed = 1)
    step = pm.Metropolis()
    trace = pm.sample(20000,step)
tracee = trace[:]['obs']
sns.distplot(tracee,kde_kws={'color':'k'})
plt.show()
```

```
OverflowError: Python int too large to convert to C long
```
## Versions and main components

* PyMC3 Version: 3.11.1
* Aesara Version:
* Python Version: 3.8.1
* Operating system: Windows
* How did you install PyMC3: (conda/pip) conda

**Comment by ricardoV94** [comment]
That mu of 100 in the Lognormal sounds a bit insane. That means your distribution has a mean ~ exp(100). Did you mean this?

**Comment by Hossein-1991** [comment]
> That mu of 100 in the Lognormal sounds a bit insane. That means your distribution has a mean ~ exp(100). Did you mean this?

what a naive mistake!! I thought 'mu' is mean in Lognormal (though in normal dist, it is mean!)
