### ISSUE TITLE
Rename aesara.tensor import from aet to at

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4538]
Ref https://github.com/pymc-devs/aesara/issues/328

**Comment by farhanreynaldo** [comment]
Hello, do we change every aet to at in the codebase? I would really love to work on this issue and really glad if you could guide solving the issue.

**Comment by twiecki** [comment]
Yes, all of them. Would be great if you wanted to take this on.

**Comment by farhanreynaldo** [comment]
Sure! I will start working on this issue.
