### ISSUE TITLE
plotting prior

### ISSUE THREAD

**Issue by Hossein-1991** [pymc-devs/pymc#4539]
## Description of your problem
Hi
I want to visualize prior and posterior in a single plot (which is usually done with plt.legend () ). How can I do this in pymc3 environment?? For example, in the following code, I want to add pm.Lognormal to the posterior plot (trace)

```python
with pm.Model():
    s = pm.Lognormal('s', mu = 4.605 , sigma = 0.33)
    obs = pm.Poisson('obs',mu = s ,observed = 1)
    step = pm.Metropolis()
    trace = pm.sample(20000,step)
tracee = trace[:]['s']
sns.distplot(tracee,kde_kws={'color':'k'})
plt.show()
```
## Versions and main components

* PyMC3 Version: 3.11.1
* Aesara Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by OriolAbril** [comment]
You have to sample from the prior first to be able to plot samples from it. This notebook: https://docs.pymc.io/notebooks/posterior_predictive.html shows how to sample from prior, posterior and prior predictive. And you may also be interested in using https://arviz-devs.github.io/arviz/api/generated/arviz.plot_dist_comparison.html (see https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html#from-pymc3 on how to convert data in a format accepted by plot_dist_comparison)

**Comment by Hossein-1991** [comment]
> You have to sample from the prior first to be able to plot samples from it. This notebook: https://docs.pymc.io/notebooks/posterior_predictive.html shows how to sample from prior, posterior and prior predictive. And you may also be interested in using https://arviz-devs.github.io/arviz/api/generated/arviz.plot_dist_comparison.html (see https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html#from-pymc3 on how to convert data in a format accepted by plot_dist_comparison)

Great!! It was so helpful. Thank you very much

**Comment by OriolAbril** [comment]
Glad I could help, I will close the issue. If you have more questions I'd recommend asking at https://discourse.pymc.io/
