### ISSUE TITLE
jax is missing from requirements.txt

### ISSUE THREAD

**Issue by yurivict** [pymc-devs/pymc#4545]
Version 3.11.2 installs ```sampling_jax.py``` that contains ```import jax``` but jax isn't in ```requirements.txt```.

**Comment by brandonwillard** [comment]
JAX should be an _optional_ dependency, although it currently isn't in the Conda version of the mandatory dependency Aesara/Theano-PyMC.

**Comment by twiecki** [comment]
Yes, it's optional. I don't think there is a way to have an optional dependency in `conda`.

**Comment by michaelosthege** [comment]
It doesn't look like JAX is going to be a dependency any time soon. One reason is their decision to not officially support Windows (unlike PyMC3). Another, like with any Google project, is the risk of breaking API changes..

Closing this issue so that it doesn't clutter our backlog.
