### ISSUE TITLE
Stochastic's `observed` argument does not accept tuples

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#456]
Passing a tuple (rather than a NumPy array) to a stochastic as the `observed` value results in a TypeError. We should be able to pass lists and tuples of data.

Here is an example:

```
from pymc import Model, Normal, Uniform, sample, NUTS, Deterministic

post_op_stool = 0.19,0.24,0.29,0.32,0.44,0.44
stoma_output = 0.33,0.36,0.42,0.44,0.44,0.49,0.52
tissue_adherent = 0.5,0.52

with Model() as model:

    sigma = Uniform('sigma', 0, 100)
    tau = Deterministic('tau', sigma ** -2)

    mu_po = Normal('mu_po', 0, 0.001)
    mu_so = Normal('mu_so', 0, 0.001)
    mu_ta = Normal('mu_ta', 0, 0.001)

    y_po = Normal('y_po', mu_po, tau, observed=post_op_stool)
    y_so = Normal('y_so', mu_so, tau, observed=stoma_output)
    y_ta = Normal('y_ta', mu_ta, tau, observed=tissue_adherent)

    diff_so_po = Deterministic('diff_so_po', mu_so - mu_po)
    diff_ta_po = Deterministic('diff_ta_po', mu_ta - mu_po)
```

Results in:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-82417f5a4deb> in <module>()
     14     mu_ta = Normal('mu_ta', 0, 0.001)
     15 
---> 16     y_po = Normal('y_po', mu_po, tau, observed=post_op_stool)
     17     y_so = Normal('y_so', mu_so, tau, observed=stoma_output)
     18     y_ta = Normal('y_ta', mu_ta, tau, observed=tissue_adherent)

/Users/fonnescj/Code/pymc/pymc/distributions/distribution.pyc in __new__(cls, name, *args, **kwargs)
     17             data = kwargs.pop('observed', None)
     18             dist = cls.dist(*args, **kwargs)
---> 19             return model.Var(name, dist, data)
     20         elif name is None:
     21             return object.__new__(cls) #for pickle

/Users/fonnescj/Code/pymc/pymc/model.pyc in Var(self, name, dist, data)
    145             self.free_RVs.append(var)
    146         else:
--> 147             var = ObservedRV(name=name, data=data, distribution=dist, model=self)
    148             self.observed_RVs.append(var)
    149         self.add_random_variable(var)

/Users/fonnescj/Code/pymc/pymc/model.pyc in __init__(self, name, data, distribution, model)
    355             args = [t.constant(args[0], name=name)]
    356 
--> 357         self.logp_elemwiset = distribution.logp(*args)
    358         self.model = model
    359 

TypeError: logp() takes exactly 2 arguments (3 given)
```

**Comment by jsalvatier** [comment]
Hmm, the reason for that is that some logp functions take multiple arguments, and I was trying to support that. I'm open to ideas on how to support both.

**Comment by fonnesbeck** [comment]
Why would we pass multiple data items to `observed=`? What is the use case?

**Comment by jsalvatier** [comment]
The most common use case will probably be distributions where summary
statistics are observed rather than the actual data points.

I am currently using multiple items to `observed` for a survival
distribution with parameters `(start, end, died)`. Another use case I've
played with for meta-analysis is the normal distribution where the average,
stdev and n are observed (rather than the actual values).

Does that make sense?

**Comment by fonnesbeck** [comment]
Can we use a dict for that? Alternately, if the observation is a summary (mean and sd) it could make sense to pass a distribution object.

**Comment by jsalvatier** [comment]
A dict could work. I hadn't thought of that.  I don't think a distribution
would work, but that's an interesting thought.

**Comment by jsalvatier** [comment]
@twiecki What do you think about switching to using a dict if a distribution takes multiple arguments?

**Comment by twiecki** [comment]
That makes sense and I've seen this used elsewhere as well.

**Comment by fonnesbeck** [comment]
A dict for the observed value, you mean?

**Comment by jsalvatier** [comment]
Yeah. Where else have you seen it used?

**Comment by twiecki** [comment]
It's not for data, but `seaborn` allows you to forward kwargs to individual functions getting called inside the plotting function, e.g.:

``` python
sns.lmplot("total_bill", "tip", tips,
           scatter_kws={"marker": ".", "color": "slategray"},
           line_kws={"linewidth": 1, "color": "seagreen"});
```

**Comment by twiecki** [comment]
I suppose it ties us to using kwargs as parameters for the likelihood (if it takes multiple arguments). Not unreasonable and definitely better than a tuple which is less explicit.

**Comment by jsalvatier** [comment]
right now my inclination is to use `Normal('x', mu, 1, observed=array)` if there is only one input, and requiring `SummaryNormal('x', mu, 1, observed={'mean' : arr_mean, 'N' : n, 'stdev' : arr_stdev})` for distributions that have multiple inputs for their observations.

**Comment by twiecki** [comment]
I like that syntax a lot.

**Comment by jsalvatier** [comment]
This should address this: 

https://github.com/pymc-devs/pymc3/pull/712
