### ISSUE TITLE
Remove all uses of `*.tag.test_value` and replace with a new initial value framework

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/pymc#4567]
We need to set up a framework for setting and getting initial values for a model; one that doesn't rely on Aesara's test values.

In many cases, this may be as simple as renaming parts of the existing API (e.g. `Model.test_point` to `Model.initial_point`, `Model.check_test_point` to `Model.check_initial_point`, change the `testval` `Distribution` argument to `initial_value`, etc.), but, in some cases, we'll need to add new variables and logic.  

Specifically, it seems like we'll need to store the initial values in the `Model` object and, in multiple places, obtain those values from a `Model` object.

**Comment by farhanreynaldo** [comment]
I would like to take on this issue. Should I do the pull request on `v4` branch? Would also really appreciate feedback and your help on this issue

**Comment by brandonwillard** [comment]
You might need to wait until #4577 goes through, because it looks like I'll need to implement some of this for other reasons.

**Comment by farhanreynaldo** [comment]
Sure thing, I will start working when it's merged.

**Comment by ricardoV94** [comment]
For whomever takes this one, the `Flat` and `HalfFlat` are examples of pymc3 "distributions" that require special care because they cannot be sampled from directly, and as such an initial value has to be chosen some other way.

**Comment by ricardoV94** [comment]
@brandonwillard can we close this one?

**Comment by twiecki** [comment]
Sounds like this is implemented now.
