### ISSUE TITLE
Using `trace=NDArray()` in `sample` leads to identical chain number error 

### ISSUE THREAD

**Issue by ckrapu** [pymc-devs/pymc#4568]
Currently, the following code presents an error regarding non-uniqueness of the chain numbers. In this example, each of the individual traces in the MultiTrace would have `chain = 4`.

```
import pymc3 as pm

with pm.Model() as model:
    x = pm.Normal('x')
    backend = pm.backends.ndarray.NDArray()
    trace   = pm.sample(trace=backend, cores=1, chains=4)
```
While this is a fairly contrived example and is easily worked around, this exact issue also presents challenges in the development of a satisfactory solution for the issue raised in #4562. The precise cause of this error is that the same `NDArray` object is used multiple times and the repeated application of `_sample` only increments its chain index rather than creating a new object altogether. Since `_sample` ends up returning multiple references to the same object, the creation of a [MultiTrace from several single traces at ](https://github.com/pymc-devs/pymc3/blob/97b54f0da10074b0f3f62ff7040de2dc7c79a7ad/pymc3/sampling.py#L733) is done with references to the same object, obviously sharing the same chain number.

A simple solution that appears to work fine is by [applying `copy` to the incoming `trace` variable](https://github.com/pymc-devs/pymc3/blob/97b54f0da10074b0f3f62ff7040de2dc7c79a7ad/pymc3/sampling.py#L846) at the beginning of `_sample`.

**Comment by michaelosthege** [comment]
Additionally, we can blame the `_choose_backend` function for not checking the chain number: https://github.com/pymc-devs/pymc3/blob/97b54f0da10074b0f3f62ff7040de2dc7c79a7ad/pymc3/sampling.py#L1374

> A simple solution that appears to work fine is by applying copy to the incoming trace variable at the beginning of _sample.

Maybe even at the beginning of `sample`, so it has an effect on all backend?

If you want to open a PR for this one, it should be rather straightforward - also with the test cases.

**Comment by ckrapu** [comment]
Applying `copy` within `sample` won't solve the problem since the required copying of objects has to happen a few layers deeper within the sampling code. I think that since this is only an issue for the single process sampling, it should be okay to make the change within the `_sample` function.
