### ISSUE TITLE
docs.pymc.io is down?

### ISSUE THREAD

**Issue by rsarky** [pymc-devs/pymc#4578]
Seems like the github page that hosts documentation is down.

**Comment by OriolAbril** [comment]
We are looking into that, it seems that http://pymc-devs.github.io/pymc3/ is working though, you can read the docs there in the meantime

**Comment by rsarky** [comment]
Thanks! @OriolAbril

**Comment by rsarky** [comment]
> We are looking into that, it seems that http://pymc-devs.github.io/pymc3/ is working though, you can read the docs there in the meantime

FYI, the examples on this one are down

**Comment by rsarky** [comment]
Works now. Closing.
