### ISSUE TITLE
jupyterlab, PyMC3, conda

### ISSUE THREAD

**Issue by lrlgogo** [pymc-devs/pymc#4581]
pymc3 installed as the guide in github for windows, use conda prompt. It can work well in Pycharm, but cant work normally in jupyter-lab. I've upgrade numpy, but there is still a some problems.

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas__ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (DLL load failed while importing _fblas: 找不到指定的模块。)
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

**Comment by fonnesbeck** [comment]
Did you get this figured out? If not, please post a complete example demonstrating the error, along with installation details.

**Comment by twiecki** [comment]
Closing in the interim.
