### ISSUE TITLE
mistake in formula in docs

### ISSUE THREAD

**Issue by patel-zeel** [pymc-devs/pymc#4587]
The formula below is missing log
[docs link](https://docs.pymc.io/notebooks/GP-Marginal.html#:~:text=The%20unknown%20latent%20function%20can,is%20called%20the%20marginal%20likelihood.&text=%CE%A3%20is%20the%20covariance%20matrix%20of%20the%20Gaussian%20noise.)
![Image](https://raw.githubusercontent.com/patel-zeel/Adhoc/master/images/mgp.PNG)

**Comment by OriolAbril** [comment]
Thanks for reporting! Do you want to send a PR to fix it?

**Comment by patel-zeel** [comment]
I searched and tried but couldn't do it. You may do it from your end.

**Comment by digitalsimboja** [comment]
Hi Oriol,

I am successful in the initial application for Outreachy on this round.
Could I take on this task to start making contributions to the community?

Thanks and regards

**Comment by OriolAbril** [comment]
The source for the file that generates this page is in [pymc-examples](https://github.com/pymc-devs/pymc-examples), like all the notebooks in the `tutorials` and `examples` pages of the docs. We are in the process of updating all the notebooks, so I have added this to the corresponding tracker issue. If you are interested in working on that, you should take a look at https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md.
