### ISSUE TITLE
`Model._str_repr()` keeps `TransformedDistribution`

### ISSUE THREAD

**Issue by tomicapretto** [pymc-devs/pymc#4597]
In Bambi we call `pymc3.Model.__str___()` when a user calls `bambi.Model.__str__()`, and `TransformedDistribution`s are not being filtered. I think the problem is in the following lines of code, where the string should be `"TransformedDistribution"` instead of `"TransformedDistribution()"`

https://github.com/pymc-devs/pymc3/blob/2dee9dafb3541043ae23b66fe9262e70fbd2769a/pymc3/model.py#L1410-L1413

**Please provide a minimal, self-contained, and reproducible example.**

```python
import bambi as bmb
import statsmodels.api as sm

data = sm.datasets.get_rdataset('dietox', 'geepack').data
model = bmb.Model(data)
results = model.fit("Weight ~ Time + (Time|Pig)")
model
```
Which prints the following 

```
           Intercept ~ Normal
                Time ~ Normal
   1|Pig_sigma_log__ ~ TransformedDistribution
        1|Pig_offset ~ Normal
Time|Pig_sigma_log__ ~ TransformedDistribution
     Time|Pig_offset ~ Normal
  Weight_sigma_log__ ~ TransformedDistribution
         1|Pig_sigma ~ HalfNormal
               1|Pig ~ Deterministic
      Time|Pig_sigma ~ HalfNormal
            Time|Pig ~ Deterministic
        Weight_sigma ~ HalfStudentT
              Weight ~ Normal
```

---
Bambi: 0.4.0
PyMC3: 3.11.2

**Comment by tomicapretto** [comment]
Btw, I can fix it in a PR if you want.

**Comment by ricardoV94** [comment]
Closing this as it's V3 specific.
