### ISSUE TITLE
Give NoDistribution a random method so that `sample_prior_predictive` can work

### ISSUE THREAD

**Issue by jonsedar** [pymc-devs/pymc#4598]
## Issue

NOTE: issue as experienced and described in my gist for full reproducible MRE in pymc3.9.3: https://gist.github.com/jonsedar/070319334bcf033773cc3e9495c79ea0. See also my post on Discourse https://discourse.pymc.io/t/cant-seem-to-sample-prior-predictive-on-model-with-missing-value-imputation/7130

I've specified a model using automatic imputation of missing values (see gist) with the critical specification as:

```python
...
x1ma = np.ma.masked_array(x1, mask = np.isnan(x1))
...
with pm.Model() as mdl:   
    x_mu = pm.Normal('x_mu', 0, 2, dims='names')
    x_pred = pm.Normal('x_pred', mu=x_mu, sigma=1., observed=x1ma, dims=['obs', 'names'])
...
```

In this case, the model build sees the observed value is a masked array and creates a new RV `x_pred_missing` which uses a `NoDistribution`. By design, the `NoDistribution` has a `logp()` and so it's possible to `sample()` the model and estimate the missing values. This works great.

**However**, I want to also `sample_prior_predictive()` for my model, and this currently fails with a shape error due to something related to `x_pred_missing` (see gist)

## Possible solution

I've dug through the code and it appears that `NoDistribution` does not have a `random()` function and I suspect this is the root cause of the problem.

So we could add a `random()` function to `NoDistribution`, where the returned value is influenced by the testval of the parent distribution testval (here `x_pred`)

In fact, at build time, the testval is passed: https://github.com/pymc-devs/pymc3/blob/2dee9dafb3541043ae23b66fe9262e70fbd2769a/pymc3/model.py#L1763, but seemingly ignored https://github.com/pymc-devs/pymc3/blob/2dee9dafb3541043ae23b66fe9262e70fbd2769a/pymc3/distributions/distribution.py#L287

So I propose:
1. Un-ignoring this value at init `self.testval = testval`
2. Creating a new `random()` function

## Quick demo implementation

I've implemented a dirty hack with the following code entered at line https://github.com/pymc-devs/pymc3/blob/2dee9dafb3541043ae23b66fe9262e70fbd2769a/pymc3/distributions/distribution.py#L305

Notes:
1. This uses the same signature as `random()` as used in other other distributions, 
2. It uses `generate_samples` because I want to use the shape handling there for consistency
3. This means I need to pass a generator, elsewhere in the package this is a `scipy.distribution.rvs`, so in a vain attempt of least surprise I've used `np.random.default_rng(); rng.choice` with `a=1` to guarantee an array of ones, and it seems to work. Possibly this isn't the best way to do it though...
4. I multiply that array of ones by the array of testvals (which are actually all the same value, but it seems least surprising to use all of them)

```
def random(self, size=None, **kwargs):
        """
        Draw static values from testval. 
        Parameters
        ----------
        size: int, optional
            Desired size of random sample (returns one sample if not
            specified).
        Returns
        -------
        array
        """
        rng = np.random.default_rng()
        return generate_samples(rng.choice, a=np.ones(1), 
                            dist_shape=self.shape, size=size) * self.testval

```

In testing this seems to allow `sample_prior_predictive` to run without issue, and the generated samples have the correct shape and testval of the parent

<img width="806" alt="Screenshot 2021-04-01 at 14 05 32" src="https://user-images.githubusercontent.com/708325/113246233-90dc5880-92f3-11eb-9ff2-d9db7029a5ce.png">

## Should I PR this?

I'm aware there's lots of aesara work in v4 that probably negates the need for this solution above. Is it worth a PR?

**Comment by ricardoV94** [comment]
Thanks for the detailed description. Indeed this might have been solved already in V4. I'll check it when I have some time. 

In any case it might be good to add as a test if it's not already covered.

**Comment by ricardoV94** [comment]
I don't think this is due to the NoDistribution thing, but the fact you are using `dims`. I am able to sample just fine if using shape:

```python
with pm.Model() as mdl:    
    x_mu = pm.Normal('x_mu', 0, 2, shape=2) 
    x_pred = pm.Normal('x_pred', mu=x_mu, sigma=1., observed=np.array([[np.nan, 2], [1, np.nan], [1, 2]])) 
    prior = pm.sample_prior_predictive()
```

If you try `pm.sample_prior_predictive` and pass `var_names` explicitly in order to ignore `x_pred_missing` does it work? 
`prior = pm.sample_prior_predictive(var_names=['x_mu', 'x_pred']` 

@michaelosthege Any idea why the dims would make the auto-imputed values fail in prior_predictive?

**Comment by jonsedar** [comment]
Oh that's interesting - I'll give it a try in a day or so!

**Comment by michaelosthege** [comment]
> @michaelosthege Any idea why the dims would make the auto-imputed values fail in prior_predictive?

Without looking into the details, my best guess is that it could be related to the fact that in `v3` imputed model variables are split into two tensors? And then the dims no longer apply..

A test for `v4` would be great.

**Comment by ricardoV94** [comment]
Closing as we have removed `NoDistribution`
