### ISSUE TITLE
Provide wrappers for statsmodels timerseries models

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4599]
This is a simple and general way of wrapping statsmodels into PyMC3: https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_sarimax_pymc3.html

With this we can easily provide a `pymc3.timeseries` that wraps all of `statsmodels` timeseries models.

**Comment by farhanreynaldo** [comment]
I would like to tackle this issue. I have read the article, and does every time series models in `statsmodels` follow the log likelihood code as written in the article?

**Comment by twiecki** [comment]
@farhanreynaldo That's great. My advice would be to start with just the one from the blog post and then experiment with more from there. I would assume that they all follow the same API so this should work globally.

**Comment by 7ayushgupta** [comment]
Hey @twiecki ! I was going through the blog post, and it does look like a really simple idea to add `statsmodels` TS models to PyMC3 easily. Ideally, we can have more support for TS by beginning with a `pymc3.timeseries` module, which can wrap `statsmodels`. Would a PR with an addition of 1-2 basic models serve as a good reference for discussion on this issue?

**Comment by twiecki** [comment]
Yes that'd be perfect.

**Comment by canyon289** [comment]
Just a general note. GSOC also includes a time series project so be aware if a student happens to take on time series work we're going to have to coordinate PRs

**Comment by 7ayushgupta** [comment]
Hey @canyon289! I am actually interested in working on a GSOC for PyMC3 (especially the time series project) - if there was no one else interested, but it looks like someone's already building up a proposal. Hard luck, I think it would be futile for two people vying for the same project.

**Comment by farhanreynaldo** [comment]
If that's the case, I would retract from this issue.

**Comment by canyon289** [comment]
@farhanreynaldo sorry about that theres a lot of traffic around this one

@7ayushgupta you can still submit a GSOC proposal for any PyMC3 project as well as time series!

**Comment by twiecki** [comment]
This issue should not be confused with the timeseries project in GSoC. This is basically a hack to get that functionality in quick, with a few lines of codes.

However, having implementations of these in PyMC3 directly is still the better way to go and is the goal of the GSoC project.

Having said that, it's definitely great foundation for the GSoC work.

@farhanreynaldo @7ayushgupta Anyone interested in taking this simple one on?

**Comment by 7ayushgupta** [comment]
Yes, I was still working on it. I was facing some simple issues with the blog's code (somewhere Theano couldn't convert a list to a tensor variable). 
I'll try to complete this regardless of GSoC soon.

**Comment by OriolAbril** [comment]
@7ayushgupta note that we have frozen PRs to `master` (see [timeline](https://github.com/pymc-devs/pymc3/wiki/Timeline)) until we merge `v4` into it. You should therefore _not_ be using Theano but [Aesara](https://github.com/pymc-devs/aesara) instead. I haven't gone through the code in the blogpost carefully but I don't want you yo try updating the code to latest Theano only to see you also have to update it to Aesara too.

**Comment by almostmeenal** [comment]
hi, I was writing my time series proposal, and as i saw @twiecki 's comment. Adding ARIMA would also require(or atleast it'd be good if we did that) Augmented dickey-fuller test to check stationarity wrt mean, statsmodels.tsa has an implementation of the same, But i think it'd be better if we had a pymc3 implementation from scratch instead of using that one right?

**Comment by brendandoner** [comment]
@twiecki @7ayushgupta, I am starting to work on this one as well and currently working on building the helper functions for aesara.

**Comment by mjhajharia** [comment]
closing this because we're actually porting things now and going for an in house thing
