### ISSUE TITLE
Error in Gamma Distribution Description

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#4601]
The Gamma distribution is described as the sum of alpha exponential variables with mean beta, but appears to be parametrized as the sum of alpha exponential variables with _rate_ beta (mean 1/beta).

**Comment by twiecki** [comment]
Thanks @Closed-Limelike-Curves, want to fix that in a PR?

**Comment by ghost** [comment]
> Thanks @Closed-Limelike-Curves, want to fix that in a PR?

Not sure what a PR is (Sorry, I'm new to GitHub).

Also worth noting that there may be a similar error in the Inverse-Gamma, although I didn't look closely enough to be sure.

**Comment by 7ayushgupta** [comment]
@Closed-Limelike-Curves PR (pull request) is a way to make a change to the repository (code-base). This is a short and sweet [guide](https://guides.github.com/activities/hello-world/#pr) to understand what that is.
That said, in case you are too busy to make the change yourself, can I send in a quick PR for these changes?

**Comment by ghost** [comment]
> @Closed-Limelike-Curves PR (pull request) is a way to make a change to the repository (code-base). This is a short and sweet [guide](https://guides.github.com/activities/hello-world/#pr) to understand what that is.
> That said, in case you are too busy to make the change yourself, can I send in a quick PR for these changes?

Yes, that would be great, thank you!

**Comment by ricardoV94** [comment]
> Also worth noting that there may be a similar error in the Inverse-Gamma, although I didn't look closely enough to be sure.

Did we check this one as well?

**Comment by 7ayushgupta** [comment]
The Inverse-Gamma function's description is much less verbose and does not talk about the parameterization in detail. 
```
alpha: float, Shape parameter (alpha > 0).
beta: float, Scale parameter (beta > 0).
mu: float, Alternative shape parameter (mu > 0).
sigma: float, Alternative scale parameter (sigma > 0).
```
This is the only reference there, and thus doesn't need any correction.

**Comment by ricardoV94** [comment]
Thanks for checking it!
