### ISSUE TITLE
Typos in the survival_analysis notebook

### ISSUE THREAD

**Issue by olgadk7** [pymc-devs/pymc#4603]
Hello, found some typos:

1. <img width="201" alt="Screen Shot 2021-04-02 at 5 58 26 PM" src="https://user-images.githubusercontent.com/32032123/113458782-75e81200-93e1-11eb-9819-c630af23a4d7.png">

2. <img width="229" alt="Screen Shot 2021-04-02 at 5 59 01 PM" src="https://user-images.githubusercontent.com/32032123/113457294-75e61300-93dd-11eb-8d5a-4dd21e17cf94.png">

3. <img width="247" alt="Screen Shot 2021-04-02 at 5 57 38 PM" src="https://user-images.githubusercontent.com/32032123/113457306-7b435d80-93dd-11eb-8a08-8e870be08134.png">

4. <img width="329" alt="Screen Shot 2021-04-02 at 6 02 56 PM" src="https://user-images.githubusercontent.com/32032123/113457425-b8a7eb00-93dd-11eb-8824-de36fbbc38d9.png">

5. <img width="134" alt="Screen Shot 2021-04-02 at 6 08 33 PM" src="https://user-images.githubusercontent.com/32032123/113457706-77640b00-93de-11eb-98fa-107ad82c9b22.png">

6. <img width="133" alt="Screen Shot 2021-04-02 at 6 25 12 PM" src="https://user-images.githubusercontent.com/32032123/113458594-cd39b280-93e0-11eb-8d56-863ec5c216f7.png">

7. <img width="330" alt="Screen Shot 2021-04-02 at 6 28 58 PM" src="https://user-images.githubusercontent.com/32032123/113458744-505b0880-93e1-11eb-8430-0b0e74dec482.png">

Lastly, metastized should be metastasized..

https://docs.pymc.io/notebooks/survival_analysis.html

Thank you for everything you do, 
Olga

**Comment by fonnesbeck** [comment]
Hey, thanks for reviewing this. If you have the time/inclination feel free to submit a PR, otherwise we will get to it soon.

**Comment by olgadk7** [comment]
@fonnesbeck submitted, thanks!

**Comment by OriolAbril** [comment]
Hi, thanks for reporting and submitting the PR, as I commented in the PR, this should be done in pymc-examples instead, the notebooks are not hosted in this repo anymore. Here is the current location of the survival analysis notebook: https://github.com/pymc-devs/pymc-examples/blob/main/examples/survival_analysis/survival_analysis.ipynb
