### ISSUE TITLE
Replace "a aesara" with "an aesara

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4618]
In many places the docs were changed from "a theano ..." to "a aesara" which is a step in the right direction, but falls short of English grammar rules.

All occurences of "a aesara" should be replaced with "an aesara". An example of one such occurence is below
https://github.com/pymc-devs/pymc3/blob/d7172c0a1a76301031d1b3b411d00643c416a0c4/pymc3/model.py#L148

In terms of timing this is a low priority change and should only be worked on after the V4 merge to master.

**Comment by brandonwillard** [comment]
We should also capitalize Aesara.

**Comment by larryshamalama** [comment]
I can work on this!

**Comment by canyon289** [comment]
Thank you @larryshamalama, looks like you got many of them!!

I'm still finding  couple instances however. Keeping this open until we're more sure that all instances are fixed.
 
https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L155

**Edit**
Nevermind, I see it was merged into V4 and I'm looking at master. My apologies! Will close this one.
