### ISSUE TITLE
Prediction by Bayesian linear regression 

### ISSUE THREAD

**Issue by Moharez** [pymc-devs/pymc#4628]
If you have questions about a specific use case, or you are not sure whether this is a bug or not, please post it to our discourse channel: https://discourse.pymc.io

## Description of your problem

Hello all,

I am quite new to Python and Bayesian Linear Regression. I could write a code for the Bayesian Linear Regression model (Although I don't know if it is good or not) to predict a SINGLE "x". However, my data consists of 3 independent variables and 1 dependent variable and I like to predict my dependent variable based on 3 inputs, not just 1 input as you can see in the following code. 

Could you please help me with how to change the code? 

I also could not understand how the model trained itself because in the model context (pymc3) there is no sign of using x_train or x_test! That is confusing to me. 

Thank you all.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np
import pandas as pd
import scipy
import theano
import pymc3 as pm


dataset = pd.read_csv('PV-PCM.csv')


from sklearn.model_selection import train_test_split

X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,3].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)


with pm.Model() as linear_model:
    # Intercept
    intercept = pm.Normal('Intercept', mu = 0, sd = 10)
    
    # Slope 
    slope = pm.Normal('slope', mu = 0, sd = 10)
    
    # Standard deviation
    sigma = pm.HalfNormal('sigma', sd = 10)
    
    # Estimate of mean
    mean = intercept + slope * dataset.iloc[:,0].values
    
    # Observed values
    Y_obs = pm.Normal('Y_obs', mu = mean, sd = sigma, observed = y)
    
    # Sampler
    step = pm.NUTS()
    
    # Posterior distribution
    linear_trace = pm.sample(1000, step)
    
    pm.traceplot(linear_trace, figsize = (12, 12))
    
    pm.plot_posterior(linear_trace, figsize = (12, 10))
    
    bayes_prediction = linear_trace['Intercept'] + linear_trace['slope'] * "Any number for ONE IV"
```

**Please provide the full traceback.**
```python
[The error output here]
```

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version: 3
* Aesara Version:
* Python Version: 3.8
* Operating system: Windows 10
* How did you install PyMC3: conda

**Comment by OriolAbril** [comment]
Hi, can you post that same question on https://discourse.pymc.io? You can tag me @OriolAbril and we'll answer. As this is not an issue but a usage question, we prefer to answer there as it's better suited for this and easier for other people to find afterwards

**Comment by Moharez** [comment]
> Hi, can you post that same question on https://discourse.pymc.io? You can tag me @OriolAbril and we'll answer. As this is not an issue but a usage question, we prefer to answer there as it's better suited for this and easier for other people to find afterwards

Hi Oriol
I posted there now. Thank you. I also mentioned you in the reply to my post.

**Comment by OriolAbril** [comment]
Great, I'll close the issue then
