### ISSUE TITLE
Change **kargs to **kwargs

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4630]
While the definition `**kargs` is arbitrary and functional in python it is inconsistent with both convention `**kwargs` and with the kwargs operator spelled per convention in the same class multiple time below

https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L282
https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L305

**Comment by Swanand01** [comment]
Hi. I am a first time contributor to open source and I would like to take this up.
