### ISSUE TITLE
Update model.register_rv argument documentation

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4631]
The transform argument here is underdocumented. It doesnt indicate that its optional and what the default is. It also is unclear on what objects could be passed to it and why

https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L920

**Comment by Aut0R3V** [comment]
Hi @canyon289 I'd like to work on this. For the transform argument, would details from this code - https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/transforms.py be included? 
Thanks!

**Comment by michaelosthege** [comment]
hi @Aut0R3V ,
Make sure to fork from the `v4` branch as we're not taking PRs into master (see https://github.com/pymc-devs/pymc3/wiki/Timeline).

Some information about the transforms may be helpful, but in general we don't want to duplicate such information. There is the possibility to make a link in docstrings, such that it is also rendered as a link by Sphinx. I saw something with `func::` or so in other docstrings, but you'll have to look it up.

**Comment by OriolAbril** [comment]
You can take a look at [ArviZ docs](https://arviz-devs.github.io/arviz/contributing/developer_guide.html#hyperlinks) for some guidance on docstrting hyperlinks, either from pymc3 to external libs or to other pymc3 objects.

**Comment by Aut0R3V** [comment]
Thanks a lot for the details @michaelosthege & @OriolAbril. I'll make a pull request from the v4 branch and incorporate all these changes.

**Comment by OriolAbril** [comment]
Closing as this is superseeded by #5459
