### ISSUE TITLE
Remove model.check_test_point

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4633]
## Description of your problem
`model.check_test_point` is marked for deprecation. V4 seems like a good time to remove it. Opening a discussion to get a second opinion. If we agree it is a good time to remove it we can turn this into an "actionable" issue

https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L1357

@ricardoV94 seems like you've got some related thoughts given the discussion in this issue ticket
https://github.com/pymc-devs/pymc3/issues/4205

**Comment by ricardoV94** [comment]
This was marked as deprecation just now. Users will not have not seen this deprecation prior to changing to V4.

**Comment by OriolAbril** [comment]
Will random variables still accept a `testval` argument? Maybe we should discuss which changes should be "plain" breaking changes and which should have some kind of deprecation to ease transition. 

I see the value in ensuring a smooth transition, but I think it would be even better to break everything with v4 and then have a stable api (or an as stable as possible api). I think this could have two positive outcomes: 1) it could decrease the opposition to pinning pymc3 versions and have people working on the latest release regularly and 2) accelerate pymc3 4.x adoption (given that pinning to 3.x and not updating anything is always an option, I'm not sure if users will prefer to do "significant" updates to their code once or minor nearly insignificant changes that can drag along for a while).

**Comment by brandonwillard** [comment]
> Will random variables still accept a `testval` argument?

Yes, but we should call it something else, like "initial value".  See #4567.

**Comment by ricardoV94** [comment]
Closed via https://github.com/pymc-devs/pymc/pull/6237
