### ISSUE TITLE
Update docstring for model.point_logps

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4634]
The argument `point_logps` method is underdocumented. It doesnt indicate that both arguments are optional and what the defaults are

https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L1364

**Comment by farhanreynaldo** [comment]
Hi, would you assign me for this issue? 

For starter, do you think the documentation below would help to clarify the method?

```python
def point_logps(self, point=None, round_vals=2):
        """
        Computes the log probability of `point` for all random variables in the model.

        Parameters
        ----------
        point: Point, default 'None'
            Point to be evaluated.  If ``None``, then ``model.initial_point``
            is used.
        round_vals: int, default '2'
            Number of decimals to round log-probabilities.

        Returns
        -------
        Pandas Series
        """
```

**Comment by canyon289** [comment]
@farhanreynaldo This looks great. Feel free to make a PR but do know that we'll hold off on merging until the V4 branch to avoid conflicts

**Comment by farhanreynaldo** [comment]
> @farhanreynaldo This looks great. Feel free to make a PR but do know that we'll hold off on merging until the V4 branch to avoid conflicts

I just noticed that the method only available in `V4` branch. Should I do the pull request to that branch?
