### ISSUE TITLE
Update docstring for fastfn

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4635]
Docstring is missing default arguments and is missing a parameter entirely

https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L1507

**Comment by CloudChaoszero** [comment]
Is [this docstrings](https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L1672) and #4636 now added?

> I checked via Blame, and looks like they were updated years ago. However,  I see they are added, seen in the viz below


<img width="937" alt="Screen Shot 2021-05-23 at 9 34 24 PM" src="https://user-images.githubusercontent.com/19514362/119296993-e73c8800-bc0e-11eb-9373-b5ac19e9bb04.png">


If not to preference, I can update them 😄

**Comment by canyon289** [comment]
Looks like they still need to be updated, but lets hold off until v4 is merged as not to add to the traffic jam. Ill assign this to you though so you get first chance to claim it once v4 is merged

**Comment by canyon289** [comment]
This is up for grabs again as v4 is merged!

**Comment by ricardoV94** [comment]
fastfn no longer exists!

**Comment by canyon289** [comment]
My favorite kind of issue resolution!
