### ISSUE TITLE
Update docstring for Point

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4636]
Docstring is missing default arguments and is missing a parameter entirely

https://github.com/pymc-devs/pymc/blob/v4-archived/pymc3/model.py#L1752

**Comment by tblazina** [comment]
I would take this one, if its not being worked on.

**Comment by mjhajharia** [comment]
@canyon289 can you provide the updated link to the source code for this issue?

**Comment by canyon289** [comment]
Done

**Comment by OriolAbril** [comment]
Closing this as it is contained in https://github.com/pymc-devs/pymc/issues/5459 and having it open here as a separate issue will be confusing
