### ISSUE TITLE
Memory leak for repeated use of `gp.predict`

### ISSUE THREAD

**Issue by ckrapu** [pymc-devs/pymc#4644]
This issue documents a problem discussed previously at [this Discourse thread](https://discourse.pymc.io/t/memory-leak-for-gp-prediction/6860/12). The following script shows increasing memory usage despite no obvious state being retained:

```
import numpy as np
import pymc3 as pm
import os, psutil

X = np.random.randn(100, 1)
y = np.random.randn(100, 1)

with pm.Model() as model:
    ls   = pm.Uniform('ls', lower=0.1, upper=4.0) 
    matern   = pm.gp.cov.Matern52(1, ls=ls, active_dims=[0])
    gp = pm.gp.Marginal(cov_func=matern)
    ll = gp.marginal_likelihood('ll', X, y, noise=1.0, is_observed=True)
    trace = pm.sample(chains=1, cores=1, tune=2, draws = 2)
    
    Xnew = np.random.randn(200,1)
    process = psutil.Process(os.getpid())
    for i in range(30):
        _ = gp.predict(X, diag=False)
        
        print('Memory usage (GB):', process.memory_info().rss/ 1_000_000_000)
```

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara Version: 2.0.6
* Python Version: 3.8.5
* Operating system: MacOS
* How did you install PyMC3: pip into a virtualenv

**Comment by ckrapu** [comment]
After running the above script with a larger number of prediction steps, the memory usage periodically drops back to baseline level which (I think) is expected behavior from the cache.

**Comment by twiecki** [comment]
Thanks for confirming @ckrapu!

**Comment by OriolAbril** [comment]
Is it possible to configure the cache? IIUC, using the cache is faster but meeds more memory, not using the cache is slower but needs less memory. From discourse it looks like the cache can use up to 22gb before reaching its max. This is a significant ammount of memory and we may want to stop caching before

**Comment by brandonwillard** [comment]
> Is it possible to configure the cache?

It should be, but is it the amount of objects being cached that's the issue, or the implicit size of those objects (e.g. via references held by them)?
