### ISSUE TITLE
Set keep_size=True in v4

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#4647]
By default, the output of `sample_posterior_predictive` and `fast_sample_posterior_predictive` returns an array with the chain and draw dimensions flattened. This makes conversion to `InferenceData` more complicated. I propose changing the default to `keep_size=True`, simplify the code in `to_inferencedata` and do not support conversion to inferencedata without `keep_dims`. Users would still be able to get the flattened samples, but to use "on their own". cc @rpgoldman

**Comment by brandonwillard** [comment]
Sounds fine to me.

**Comment by rpgoldman** [comment]
I’d suggest you make `keep_size` default to the same value as the value of `return_inference_data` to avoid unnecessary breakage to user code. If you do that, then old user code that uses the old return data structures instead of `InferenceData` will behave as before.
