### ISSUE TITLE
Add type annotations to `convert_observed_data`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4650]
We use this function to typecast a zoo of different objects. When using it, it is completely unclear what you'll get back..

**Comment by ricardoV94** [comment]
The name should also be changed as it is no longer pandas specific (eg it has special functionality for masked arrays)

**Comment by MarcoGorelli** [comment]
https://github.com/pymc-devs/pymc3/blob/7e35cddd7e54e6e6f51fc1aa3ed3df76016aa00a/pymc3/aesaraf.py#L89-L90

What inputs could end up there, other than pandas objects?

**Comment by michaelosthege** [comment]
Someone could implement their own type with a `to_numpy` function I guess? At least there are no checks that prevent that from happening.

Probably more of a theoretical possibility though, but `hasattr` leaves that door open.

**Comment by MarcoGorelli** [comment]
True, but then you're assuming that their implementation of `isnull` returns either a numpy array or that it returns an object with `to_numpy`

FWIW I think just checking
```
if isinstance(data, (pd.Series, pd.DataFrame)):
    ...
elif isinstance(data, pd.Index):
    ...
```
could lead to fewer surprises

**Comment by michaelosthege** [comment]
If you promise that pandas won't remove the `to_numpy` and `isnull` methods in the future that's fine ;)

And it could help `mypy` so there's that.

**Comment by michaelosthege** [comment]
The function is being renamed by #5743.

**Comment by fonnesbeck** [comment]
It appears that `convert_data` (the new name) now has a return type.

**Comment by michaelosthege** [comment]
closed by https://github.com/pymc-devs/pymc/pull/7299 and https://github.com/pymc-devs/pymc/pull/7334
