### ISSUE TITLE
Sparse GPs with the collapsed bound 

### ISSUE THREAD

**Issue by vr308** [pymc-devs/pymc#4660]
I wanted to learn inducing points by optimising the evidence lower bound in [Titsias, (2009)](https://www.semanticscholar.org/paper/Variational-Learning-of-Inducing-Variables-in-Titsias/f4de6082e2af026b5925810f7e7a1b04736496e2?p2df). 

I guess, setting a flat prior on Xu and doing MAP is as close as one can get to that?
 
```
Xu_init = 10 * np.random.rand(20)

with pm.Model() as model:
    ℓ = pm.Gamma("ℓ", alpha=2, beta=1)
    η = pm.HalfCauchy("η", beta=5)

    cov = η ** 2 * pm.gp.cov.Matern52(1, ℓ)
    gp = pm.gp.MarginalSparse(cov_func=cov, approx="VFE")

    # set flat prior for Xu
    Xu = pm.Flat("Xu", shape=20, testval=Xu_init)

    σ = pm.HalfCauchy("σ", beta=5)
    y_ = gp.marginal_likelihood("y", X=X, Xu=Xu[:, None], y=y, noise=σ)

    mp = pm.find_MAP()
```

**Comment by fonnesbeck** [comment]
Hi @vr308. Would you mind posting this usage question to our [Discourse forum](https://discourse.pymc.io/)? The issue tracker is intended for managing bugs and feature requests only. Thanks!
