### ISSUE TITLE
Replace custom RandomVariable for WeibullBetaRV

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4683]
Reminder issue to remove the RandomVariable for WeibullBetaRV (introduced in #4640) once we have the automatic multiplication logp working (e.g., #4653)

**Comment by brandonwillard** [comment]
We might be able to use `aesara.compile.builders.OpFromGraph` in the interim.  `OpFromGraph` will create a new `Op` to which we can assign a `_logp` specialization.  This removes the need to create a `RandomVariable` `Op` for cases in which operations that are already covered by existing `Op`s are applied to existing `RandomVariable`s.

**Comment by ricardoV94** [comment]
Same for the Wald which is just the numpy offering + optional shifting. #4711
