### ISSUE TITLE
Port remaining distributions to v4

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4686]
There are still various continuous distributions missing for `v4` that need to get ported.
Here is an example of how to do this port for where `aesara` does not provide a `RandomVariable` (which is all of the currently missing ones): https://github.com/pymc-devs/pymc3/blob/v4/pymc3/distributions/continuous.py#L2648

Here is a list of the missing continuous ones:
- [x] `Flat` #4723 
- [x] `HalfFlat` #4723
- [x] `TruncatedNormal` #4711
- [x] `Wald` #4711
- [x] `Kumaraswamy`  #4706
- [x] `Laplace` #4691
- [x] `AsymmetricLaplace` #4746
- [x] `StudentT` #4694
- [x] `Pareto` https://github.com/pymc-devs/pymc3/pull/4691
- [x] `ChiSquared` #4695 
- [x] `HalfStudentT` #4746
- [x] `ExGaussian`  #4746
- [x] `SkewNormal` #4705
- [x] `Rice` #4705
- [x] `LogitNormal`  #4703
- [x] `Interpolated` #4746
- [x] `Moyal`  #4704
- [x] `DensityDist` #5026 

And the missing multivariate ones:
- [x] `MvStudentT`  #4731 
- [x] `DirichletMultinomial` #4758
- [x] `Wishart` https://github.com/pymc-devs/pymc3/pull/4777
- [x] `LKJCorr` #5382 
- [x] `LKJCholeskyCov` #5382
- [x] `MatrixNormal` #4777 
- [x] `KroneckerNormal` #4774
- [x] `CAR` #4596

Would be very important to add these to get an alpha out.

See @ricardoV94's comment below for a step-by-step guide on how to port a distribution.

**Comment by ricardoV94** [comment]
The refactored distributions have this line at the beginning of the class `rv_op = x` and generally don't have a random method and the `logp/logcdf` start with `value` instead of `self`. That should be enough to identify them :p

**Comment by twiecki** [comment]
@ricardoV94 Thanks, edited the above. If you have time, perhaps you could write a short list of steps of what to do to port them. (Unless you want to take these on yourself :)).

**Comment by ricardoV94** [comment]
Also missing the following multivariate distributions:
* `MvStudentT`
* `DirichletMultinomial`
* `Wishart`
* `LKJCorr`
* `MatrixNormal`
* `KroneckerNormal`
* `CAR` (being taken care in https://github.com/pymc-devs/pymc3/pull/4596)

**Comment by ricardoV94** [comment]
> @ricardoV94 Thanks, edited the above. If you have time, perhaps you could write a short list of steps of what to do to port them. (Unless you want to take these on yourself :)).

This PR illustrates well with a single distribution refactoring I think: https://github.com/pymc-devs/pymc3/pull/4615/files. What is needed is:

1. Create a new `RV op` by inheriting from aesara `RandomVariable`, porting the code in the old `random` method to the `rng_fn` `classmethod` of the new `RandomVariable`. 
2. Add the new (instance) of the `RandomVariable` to the `rv_op` field in the respective PyMC3 distribution.
3. Port any initialization logic in the old `__init__` to the new `dist` `classmethod`
4. Refactor `logp` and `logcdf` to expect arguments in this order: `value, arg1, arg2, ... argn`
5. Re-enable tests in `test_distributions.py`
6. Create new test in `test_distributions_random.py` as seen [here](https://github.com/ricardoV94/pymc3/blob/d52ae504c19fdb31e2103481b47fcc957830eb58/pymc3/tests/test_distributions_random.py#L446-L465), and remove old `BaseTestCase` in that file.
7. Re-enable other tests that depended on this distribution in other test files.

Importantly, if there are multiple parametrizations, one will have to be set as the default in the `dist` `classmethod` in step 3. This will be the one that the `RandomVariable` is defined in terms of. If the random methods and logp/logcdf methods use different parametrizations, they will have to be converted to the ones that the `RandomVariable` is defined in terms of in step 3, and converted back to the `logp` and `logcdf` methods in step 4. 

More details can be found here: https://github.com/pymc-devs/pymc3/issues/4518#issuecomment-806236360

**Comment by farhanreynaldo** [comment]
I would like to help on this issue. Should we create a separate PR for each distribution?

**Comment by twiecki** [comment]
No you can do multiple in one go, just mark the ones you are working on.

**Comment by ricardoV94** [comment]
> I would like to help on this issue. Should we create a separate PR for each distribution?

That might be too much. You can group a couple (or all) in a single PR.

I would suggest you start with the univariate distributions. The multivariate ones will probably be a bit more tricky.

**Comment by ricardoV94** [comment]
@brandonwillard what should we do with the `flat` and `halfFlat` distributions that don't have a random method? Should we create a `RandomVariable` whose `rng_fn` returns the same `ValueError("Cannot sample from Flat distribution")` as in `V3`?

**Comment by brandonwillard** [comment]
> @brandonwillard what should we do with the `flat` and `halfFlat` distributions that don't have a random method? Should we create a `RandomVariable` whose `rng_fn` returns the same `ValueError("Cannot sample from Flat distribution")` as in `V3`?

Yeah, we can do that for now.

**Comment by AlexAndorra** [comment]
Was `LKJCholeskyCov` refactored? I don't see it in the list

**Comment by twiecki** [comment]
@alexandorra I added it to the list.

**Comment by twiecki** [comment]
> opened this issue on May 12, 2021 

Holy cow, can't believe we finally got them all! 🥳
