### ISSUE TITLE
How can we pip the last version?

### ISSUE THREAD

**Issue by Jiang2019Code** [pymc-devs/pymc#4710]
In my project,I used the python 3.6 and many other packages.I manage the them using the pip.How can we install the last version using the pip?
Because the 3.10 cannot work  using the NUTS when sampling multidimension.So I want to upgrade the version.
I have noticed the information using the anaconda.But many other package relying the current project.Any solution for me?

**Comment by OriolAbril** [comment]
Hi, [pymc3 no longer supports python 3.6](https://github.com/pymc-devs/pymc3/blob/v3/setup.py#L85). To upgrade you'll also need to upgrade python. After upgrading python, a `pip install pymc3` as indicated in the docs should be enough.

**Comment by twiecki** [comment]
For further questions please use https://discourse.pymc.io/
