### ISSUE TITLE
Link V3 to next release of theano-pymc

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4725]
Once https://github.com/pymc-devs/aesara/issues/444 goes through

See discussion in #4658

**Comment by michaelosthege** [comment]
Closing because there are no plans for a Theano-PyMC patch release. See https://github.com/aesara-devs/aesara/issues/444 and https://github.com/pymc-devs/pymc3/wiki/Project-Meeting-Minutes#friday-august-13-2021
