### ISSUE TITLE
HMC unable to handle impossible parameter values

### ISSUE THREAD

**Issue by jangevaare** [pymc-devs/pymc#477]
from @jsalvatier in https://github.com/pymc-devs/pymc/issues/472

> As for the exception, it looks like HMC is trying some impossible values
> for the model. It should be able to handle those. Would you open an issue
> about that? Maybe there's a way in theano to have linalg exceptions return
> nan's or something like that. Otherwise, perhaps we want to wrap the calls
> to theano to catch LinalgExceptions.

Looked around a bit, doesn't seem like it is an option currently to have theano return nan's instead of the numpy's linalg exception... Use/creation of an optional wrapper was mentioned here https://groups.google.com/forum/#!topic/theano-dev/B3K8_CR8TmM , but it doesn't look like that ended up happening.

**Comment by jsalvatier** [comment]
The issue seems to be that if inverting a matrix fails within theano it will break hmc/nuts.

**Comment by stonebig** [comment]
Shall we see a beta2 soon ? It would be sad to not reach release after such a long effort

**Comment by twiecki** [comment]
@stonebig completely agree. just have to do it, really.
