### ISSUE TITLE
Refactor `sample_posterior_predictive_w` for V4

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4807]

**Comment by ricardoV94** [comment]
Maybe we should deprecate this one instead?

**Comment by aloctavodia** [comment]
And move the functionality to sample_posterior_predictive?

**Comment by ricardoV94** [comment]
> And move the functionality to sample_posterior_predictive?

I was discussing deprecating it altogether (not saying we should, just asking).

**Comment by aloctavodia** [comment]
I think we should keep the functionality either in this function or in `sample_posterior_predictive`

**Comment by ricardoV94** [comment]
@aloctavodia would you be interested/available to refactor this one? Nobody volunteered in a long time now :)

**Comment by twiecki** [comment]
@zaxtax I think expressed interest.

**Comment by zaxtax** [comment]
I have something that works and passes unit tests, but is not efficient. Maybe I can open a WIP for it.

**Comment by ricardoV94** [comment]
> I have something that works and passes unit tests, but is not efficient. Maybe I can open a WIP for it.

Definitely!

**Comment by ricardoV94** [comment]
I suggest removing this feature due to low interest from the community

**Comment by zaxtax** [comment]
@ricardoV94 I agree. I think this should be deprecated in favour of https://github.com/arviz-devs/arviz/pull/2147 when it is merged.
