### ISSUE TITLE
Random Effects for Generalized BART

### ISSUE THREAD

**Issue by jlevy44** [pymc-devs/pymc#4817]
Hi there! Really exciting developments with BART. I think a pymc3 implementation will be a huge boost to the biomedical research community.

I am particularly excited about the work on Generalized BART with custom link functions (eg. probit/logit): https://github.com/pymc-devs/pymc3/pull/4709 . I am wondering, are there efforts to include random intercepts / slopes to estimation of the conditional means, https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.8347?

I know with the current implementation, for continuous outcomes, random intercepts can be drawn using NUTS, while BART draws of the conditional mean prior to the addition of the random intercept are handled with Particle Gibbs. However, for the link function implementation in https://github.com/pymc-devs/pymc3/pull/4709, it would seem that incorporating a random intercept with a logit/probit link function for instance would not be possible under the current formulation. As an alternative, I am also thinking of the discussed implementation at the bottom of pg. 32: https://arxiv.org/pdf/1901.07504.pdf

What do you think would need to be done to incorporate this into the software?

**Comment by jlevy44** [comment]
For instance, is a simple solution to implement a link function to translate the BART sample back to a space where a random intercept can be added, then run HMC on that? Or should the random intercepts be added to the Particle Gibbs sampler directly?

**Comment by jlevy44** [comment]
I believe this library has implementation of random intercepts for dichotomous outcomes

https://github.com/vdorie/dbarts/blob/4ed4eafc772e95d788d5a135d9f4e4728b9516ec/R/rbart.R#L5

**Comment by aloctavodia** [comment]
Hi @jlevy44 thanks for your comments and enthusiasm. We have plans to extend BART to accommodate these cases and provide better integration with the rest of PyMC. Currently the "y" that is passed to BART is a python object (a numpy array or dataframe, etc). I think the solution is to allow "y" to be an Aesara tensor so we can then combine BART with other pymc distributions and then build more complex models. We hope to do this during the next semester,

**Comment by jlevy44** [comment]
Great, very exciting!
