### ISSUE TITLE
Iterating a `MultiTrace` only yields samples from chain 0

### ISSUE THREAD

**Issue by helmutsimon** [pymc-devs/pymc#4819]
In the code below, I run a simple example model (the details of the model don't seem relevant to the problem). There should be 2000 draws, so why does the array `xvars`  have only 1000? In contrast, tracetab.trace_to_dataframe results in a dataframe with 2000 rows, as I would expect. My system details are:
Numpy  1.16.3
PyMC3  3.11.0
Theano  1.1.0
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

```
import sys
import numpy as np
import pymc3
from pymc3.distributions.discrete import Poisson, Categorical
from pymc3.sampling import sample
from pymc3 import Model
from pymc3.backends import tracetab
import theano


def run_MCMC(n, obs, draws):
    obs = np.array(obs)
    with Model() as model: 
        
        pn = np.ones(n) / n
        x = Categorical('x', pn, testval=0)
        sfs_obs = Poisson('sfs_obs', mu=x + 1, observed=obs) 

    with model:
        trace = sample(draws, tune=0, return_inferencedata=False) 
    return trace

print('Numpy ', np.__version__)
print('PyMC3 ', pymc3.__version__)
print('Theano ', theano.__version__)
print(sys.version_info)
obs = 3
draws = 1000
n = 10
trace = run_MCMC(n, obs, draws)
xvars = [t['x'] for t in trace]
print(len(xvars))
print(xvars[:10])
trace_df = tracetab.trace_to_dataframe(trace)
print(trace_df.shape)
```

Output is:
Numpy  1.16.3
PyMC3  3.11.0
Theano  1.1.0
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
Multiprocess sampling (2 chains in 2 jobs)
CategoricalGibbsMetropolis: [x]

 100.00% [2000/2000 00:02<00:00 Sampling 2 chains, 0 divergences]
Sampling 2 chains for 0 tune and 1_000 draw iterations (0 + 2_000 draws total) took 11 seconds.
1000
[3, 6, 7, 0, 7, 4, 1, 1, 1, 1]
(2000, 1)

**Comment by michaelosthege** [comment]
I don't know by heart what an iterator like `for t in trace` gives you, but it looks like the `np.shape(xvar)` might be `(1000, 2)`?

In general I recommend to switch to `InferenceData`, because it gives you more explicit access to the draws in a more standardized fashion.

**Comment by helmutsimon** [comment]
Thank you for drawing my attention to `InferenceData`. If I set `return_inferencedata=True`, then I do indeed get an array of shape (2, 1000), which underlines my point.  However, using MultiTrace, as in the above example, `xvars` is a list of 1000 integers only, as can be seen in the example above, which I have modified.

The MultiTrace object  is the current default option for trace data and it looks like this is to be supported even after it ceases to be the default.  It appears from my example that this feature is not following the behaviour documented [here](https://pymc3.readthedocs.io/en/latest/api/backends.html#Selecting-values-from-a-backend), specifically ``The call will return the sampling values of x, with the values for all chains concatenated''. Unless I am mistaken here, this would be seriously misleading to any PyMC3 users still using the default inference method.

**Comment by michaelosthege** [comment]
Ah okay, running your code sample helped:

`MultiTrace` does not implement a `__iter__` method, but for some reason you can still do `for t in trace`. The `len(trace) == ndraws`, but iteration over the trace yields dicts of chain 0 only..

The problem here is really that `MultiTrace` has different shapes and API depending on how you look at it. That's why nudge everybody to `InferenceData` and want to get rid of `MultiTrace` in the long run.
I'm changing the title to be a little more exact.

I don't think it's worth to invest time to fix it. We should just get rid of `MultiTrace` and replace it with something less fragile.

**Comment by ricardoV94** [comment]
We could just raise a `NotImplementedError` on `__iter__` no?

Maybe we even catch some bugs in the codebase

**Comment by helmutsimon** [comment]
I see now that I should have used `xvars = trace['x']`.  Not sure where I got the idea to iterate over trace, but feel it should be fixed or warning/error raised.

**Comment by michaelosthege** [comment]
> We could just raise a NotImplementedError on __iter__ no?

Sounds doable. Want to open a PR, @helmutsimon ?

**Comment by helmutsimon** [comment]
I will have a go.
