### ISSUE TITLE
Get the codecov back

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4829]
The codecov stopped commenting on PRs some time ago. Would be nice to have it back. Can we also get the same we have in Aesara that comments on the changed files?

**Comment by michaelosthege** [comment]
Probably closed by #4838 but I'm leaving this open until we figure out if it actually works.

Plan B is to copyedit the [testing workflow from Aesara](https://github.com/aesara-devs/aesara/blob/main/.github/workflows/test.yml), which is more efficient overall, but involves a YAML file that reads like a messed-up hybrid gibberish mixup of YAML, bash, pytest and GitHub-Actions specific templating.

**Comment by ricardoV94** [comment]
Seems to be working?
