### ISSUE TITLE
Refactor or deprecate `DensityDist`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4831]
We need to decide whether we want to deprecate `DensityDist` and if so, provide at least documentation on how to add simple logp terms to a model or how to quickly implement a custom Distribution.

If we want to refactor it, it is probably good time to get rid of the whole dictionary as observed thing and force the distribution parameters to go into the signature as normal arguments in other distributions

```python
# V3 allows this
def my_logp(value, param1, param2):
    return value * param1 - param2

param1 = pm.Normal('param1', 0, 1)
param2 = pm.Normal('param2', 0, 1)
y = pm.DensityDist('y', my_logp, observed=dict(value=data, param1=param1, param2=param2))
```

```python
# V4 should work only like this (if not deprecated)
y = pm.DensityDist('y', my_logp, param1, param2, obeserved=data)

**Comment by ricardoV94** [comment]
CC @lucianopaz, if you want to assign this to yourself. Seems like we are pretty close to having a working solution

**Comment by OriolAbril** [comment]
looks related to https://github.com/pymc-devs/pymc3/issues/4534, and I also wanted to leave a link to https://discourse.pymc.io/t/using-a-random-variable-as-observed/7184/5 so we are aware of all the (in my opinion strange and redundant) things DensityDist allows, expecially when taking a dictionary as `observed` (which I also think is the only Distribution that does). 

As I have commented a few times and started changing in https://github.com/pymc-devs/pymc3/pull/4433, I think it's a bad idea to allow `FreeRVs` to be values in the dictionary passed as observed. If this is a feature that is really important to DensityDist, I would suggest doing this `givens` extra argument or following @ricardoV94 suggestion.
