### ISSUE TITLE
"More chains than draws" for Metropolis step method

### ISSUE THREAD

**Issue by dermesser** [pymc-devs/pymc#4839]
**Describe the bug**
I am not entirely sure if this is an ArviZ bug or a PyMC bug -- if it is the former, please do tell me so!

I use a blackbox likelihood model (documented [here](https://docs.pymc.io/notebooks/blackbox_external_likelihood.html)), which comes with a few weirdnesses. In any case, due to lack of a defined gradient, I cannot use the standard NUTS sampler, so I have tried both the default sampler (`Slice`, as far as I know) and `Metropolis`. Where my issue starts is exactly here:

* With `Slice`, everything works fine.
* With `Metropolis`, I see warnings like this: `lib/python3.8/site-packages/arviz/data/base.py:169: UserWarning: More chains (320) than draws (2). Passed array should have shape (chains, draws, *shape)`

I believe this to be a bug (so far), because obviously I don't pass any samples. The only place I get to interact is when passing a `MultiTrace` into `arviz.from_pymc3()`, which doesn't seem to give me the opportunity to do much wrong. The only difference is that (again due to using a blackbox model) I pass `density_dist_obs=False` to `from_pymc3()`. Another quirk is that I update existing chains in the same `MultiTrace`, to be a bit more crash-resistant. 

for reference, this is my code; although in the next section I have some more easily reproducible code:

for reference, this is my code:

```python
    with pm.Model() as model:
        powercap = pm.Uniform("powercap", 1000, 1300)
        u235frac = pm.Uniform("u235frac", 0.01, 0.1)

        start_point = {powercap: 1100, u235frac: 0.05}
        pm.DensityDist("observed", lambda v: loglikop(v), observed={'v': tt.as_tensor_variable([u235frac, powercap])})

        trace = None
        step = None
        if args.algorithm == 'metropolis':
            step = pm.Metropolis()

        for i in range(0, args.iterations):
            # Refer to https://discourse.pymc.io/t/blackbox-likelihood-example-doesnt-work/5378
            trace = pm.sample(args.samples, tune=int(args.samples/10), chains=args.chains, return_inferencedata=False,
                    compute_convergence_checks=False, step=step,
                    random_seed=RANDOM_SEED+args.index, trace=trace)
            # this is https://github.com/pymc-devs/pymc-examples/issues/48#issue-839287296
            # see https://arviz-devs.github.io/arviz/api/generated/arviz.from_pymc3.html#arviz-from-pymc3
            az.from_pymc3(trace, density_dist_obs=False).to_netcdf(samples_output_path(i, args.run, default=args.output_path))

    log.log_print("Success")
```

**To Reproduce**

Unfortunately the setup is quite involved, so I'm afraid I cannot give you an exact scenario where this happens. You can see quite in the middle the switch between metropolis or default assigned sampler. I've confirmed that with `Slice`, the warning doesn't occur.

In my attempts to reproduce it with a toy model of my own, it seems that `chains=1` is the crucial difference. If `chains=1` is given to `sample()`, then the warning appears; otherwise, it doesn't. This tells me that there may be some implicit conversion somewhere in the library?

However, this same warning shows up, also with the Metropolis sampler and with `chains=1`, in the ["How to debug a model"](https://docs.pymc.io/notebooks/howto_debugging.html#How-to-debug-a-model) page, although it is not mentioned in the text and otherwise ignored. I'm able to reproduce it with model `[3]` there!

this is from *How to debug a Model*

```python
import pymc3 as pm
import arviz as az
import numpy as np
import theano.tensor as tt

x = np.random.randn(100)

with pm.Model() as model:
    mu = pm.Normal("mu", mu=0, sigma=1)
    sd = pm.Normal("sd", mu=0, sigma=1)

    mu_print = tt.printing.Print("mu")(mu)
    sd_print = tt.printing.Print("sd")(sd)

    obs = pm.Normal("obs", mu=mu_print, sigma=sd_print, observed=x)
    step = pm.Metropolis()
    trace = pm.sample(
        3, step, tune=0, chains=1, progressbar=False
    )  # Make sure not to draw too many samples
```

**Expected behavior**

I expect the same behavior as in the `Slice` case, i.e. no warning.

**Additional context**

Python 3.8, with pip arviz/pymc3, on Ubuntu 20.04

```
>>> arviz.__version__
'0.11.2'
>>> pymc3.__version__
'3.11.2'
>>> theano.__version__
'1.1.2'
```

**Comment by dermesser** [comment]
Possibly, for just one chain, samples are stored in an `(nsamples, 1)` array instead of `(nsamples,)`? This function is called before the warning, and it as well as `atleast_2d()` would seemingly do the right thing, unless that's the case.

```python
# arviz/utils.py
376 def two_de(x):                                                                      
377     """Jitting numpy at_least_2d."""                                               
378     if not isinstance(x, np.ndarray):                          
379         return np.atleast_2d(x) 
380     if x.ndim == 0:                                                        
381         result = x.reshape(1, 1)        
382     elif x.ndim == 1:                                                     
383         result = x[newaxis, :]                                        
384     else:           
385         result = x                                 
386     return result 
```

**Comment by dermesser** [comment]
I also just noticed that this propagates into NetCDF files, when attempting to save the trace through arviz.InferenceData.to_netcdf:

```
group: sample_stats {
  dimensions:
        chain = 1000 ;
        draw = 2 ;
  variables:
        int64 chain(chain) ;
        int64 draw(draw) ;
        byte accepted(chain, draw) ;
                accepted:dtype = "bool" ;
        double accept(chain, draw) ;
                accept:_FillValue = NaN ;
        double scaling(chain, draw) ;
                scaling:_FillValue = NaN ;

  // group attributes:
                :created_at = "2021-07-04T11:12:02.853658" ;
                :arviz_version = "0.11.2" ;
                :inference_library = "pymc3" ;
                :inference_library_version = "3.11.2" ;
                :sampling_time = 6674.04905176163 ;
                :tuning_steps = 100L ;
  } // group sample_stats
}
```

**Comment by jwnki** [comment]
I noticed the same thing in pymc3 3.11.4. I have a very similar setup (also a blackbox likelihood with metropolis step), as the one described above. In my case this _only_ happens when converting the trace from `MultiTrace` to `InferenceData` via `arviz.from_pymc3` function.

**Comment by ricardoV94** [comment]
I think this may have been resolved sometime ago. Please open an issue if it resurfaces
