### ISSUE TITLE
How to increase fontsize of axes ticks and title of traceplot?

### ISSUE THREAD

**Issue by ad1995-geek** [pymc-devs/pymc#4842]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
[The complete error output here]
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by michaelosthege** [comment]
Hi @ad1995-geek ,

The `pm.plot_trace` function is just an alias for the corresponding ArviZ function: https://arviz-devs.github.io/arviz/api/generated/arviz.plot_trace.html

It returns the axes instances, so you can work with them tweak the design: `axs = arviz.plot_trace(...)`.
For further questions, please go to the ArviZ project: https://github.com/arviz-devs/arviz/issues/new/choose
