### ISSUE TITLE
Switch from dill to cloudpickle

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#4856]
Other major packages (like airflow) are moving to cloudpickle: https://github.com/apache/airflow/issues/7870

It also seems that cloudpickle as some incompatibilities with dill (as per @michaelosthege) during installation.

**Comment by Spaak** [comment]
So far the default serialization method is `pickle`, with an optional `pickle_backend` parameter to `pm.sample` which can be set to `"dill"` (required in certain cases, e.g. custom `DensityDist`). Do we want to keep this as a customizable parameter? Or should we always use `cloudpickle`? (I think at the very least we want to set `cloudpickle` to be the default if we make the effort of switching.) I think simply always using `cloudpickle` (and removing the `pickle_backend` parameter) would be fine, I don't see any scenario when someone would want to explicitly fall back to using `pickle`. (But me not seeing it is not enough to conclude there cannot be one ;) )

**Comment by twiecki** [comment]
Agree with your logic, seems like we can just use that as a default.

**Comment by Spaak** [comment]
Closed via #4858
