### ISSUE TITLE
Update docstrings of distributions `logp` and `logcdf` methods.

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4859]
We should update the docstrings of these methods. They are quite verbose, and the same information could be easily conveyed by type hints. More importantly, they are also outdated (e.g., the methods no longer expect only a value as input)

https://github.com/pymc-devs/pymc3/blob/9c7a92481856e1f86c15868b93a65a5d778b0c22/pymc3/distributions/continuous.py#L2198-L2211

**Comment by zoj613** [comment]
Are you suggesting they be removed entirely?

**Comment by ricardoV94** [comment]
> Are you suggesting they be removed entirely?
> 

Maybe... they are not user facing anymore and all work in the same way. Perhaps it's enough to have the documentation at the parent class level?

What do others suggest?

**Comment by zoj613** [comment]
> > Are you suggesting they be removed entirely?
> 
> Maybe... they are not user facing anymore and all work in the same way. Perhaps it's enough to have the documentation at the parent class level?
> 
> What to others suggest?

I do agree. If they don't ever appear in the docs then maybe they can be removed. This will helping scroll easier since the file is getting bigger.

**Comment by mjhajharia** [comment]
maybe we can do away with the doctoring and have something like `rng_fn` for `logp`, I mean this is enough for explaining the input and output types

```
def rng_fn(
        cls,
        rng: np.random.RandomState,
        loc: np.ndarray,
        scale: np.ndarray,
        size: Tuple[int, ...],
    ) -> np.ndarray:
```

**Comment by OriolAbril** [comment]
Updating the labels as it's not clear how to go about this or even if this should be done at all. 

For some more details see https://github.com/pymc-devs/pymc/issues/5282#issuecomment-1035652666 and https://github.com/pymc-devs/pymc/issues/5308
