### ISSUE TITLE
glm.plot_posterior_predictive fails when covariates are not named "x"

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#486]
`plot_posterior_predictive` generates a KeyError when models' independent variables are not called `x`. The name is hard-coded into the function.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-88-ee71b8754a08> in <module>()
----> 1 glm.plot_posterior_predictive(trace)

/Users/fonnescj/Code/pymc/pymc/glm/glm.pyc in plot_posterior_predictive(trace, eval, lm, samples, **kwargs)
    195     for rand_loc in np.random.randint(0, len(trace), samples):
    196         rand_sample = trace[rand_loc]
--> 197         plt.plot(eval, lm(eval, rand_sample), **kwargs)
    198         # Make sure to not plot label multiple times
    199         kwargs.pop('label', None)

/Users/fonnescj/Code/pymc/pymc/glm/glm.pyc in <lambda>(x, sample)
    182 
    183     if lm is None:
--> 184         lm = lambda x, sample: sample['Intercept'] + sample['x'] * x
    185 
    186     if eval is None:

KeyError: 'x'
```

**Comment by twiecki** [comment]
Right, yeah this is a bad default and I'm happy for suggestions.

If you do not have the default-named-model you're supposed to specify `lm` (and probably `range` as well).

**Comment by jsalvatier** [comment]
I think this is a general problem. We will probably want to be able to
identify independent and dependent variables more or less  automatically
for things like generating predictions on new data.

Don't have any great ideas though. Maybe I'll take some time to brainstorm
some ideas.

**Comment by fonnesbeck** [comment]
There are two options I can think of:
1. Use patsy to give us the names; presumably it knows the names of the predictor variable. I guess this would require passing the model, which could be done implicitly if run inside the context manager.
2. Pass the name of the predictor variable explicitly as an argument to the function.

**Comment by twiecki** [comment]
Perhaps we could tie the `glm` somehow to the `Model` object where it could be accessed if `plot_posterior_predictive` is called with that context.

**Comment by aganders3** [comment]
> There are two options I can think of:
> 1. Use patsy to give us the names; presumably it knows the names of the predictor variable. I guess this would require passing the model, which could be done implicitly if run inside the context manager.
> 2. Pass the name of the predictor variable explicitly as an argument to the function.

I am getting this error when using the simple patsy model `'y ~ x'` where `x` is 7x3 and the predictor variables come out as `x[0]`, `x[1]`, and `x[2]`. I don't know if option 1 would work in that case. This otherwise works for solving the problem and plotting with `traceplot()`.

**Comment by springcoil** [comment]
Is this still an issue?

**Comment by fonnesbeck** [comment]
I think so, yes.

**Comment by bhargavvader** [comment]
`plot_posterior_predictive` isn't a part of the source code anymore. Either that, or it's been moved somewhere else and I can't find it - I'm trying to find a previous commit where it existed and put it back in. @fonnesbeck , could you help with this - do you happen to know which previous release/commit has the latest version of this?

**Comment by ColCarroll** [comment]
@bhargavvader -- just did a bit of a dive, looks like it was removed in https://github.com/pymc-devs/pymc3/commit/d37e7a12c8d1ce1de0e17de8f18842d3014dc812, might want to make a single issue of it.

**Comment by harc007** [comment]
Looks like this is still an issue. Used both the below techniques:
1)
from pymc3 import glm
with Model() as model:
    glm.GLM.from_formula('col1 ~ col2', data_frame)
    trace = sample(3000, cores=2)
plot_posterior_predictive_glm(trace, samples=100, label='posterior predictive regression lines')

2)
from pymc3 import GLM
with Model() as model:
    GLM.from_formula('col1 ~ col2', data_frame)
trace = sample(3000, cores=2)
plot_posterior_predictive_glm(trace, samples=100, label='posterior predictive regression lines')

Error in both cases:
----> 4 plot_posterior_predictive_glm(trace, samples=100, label='posterior predictive regression lines')
      5 
      6 plt.title('Posterior predictive regression lines')

/home/a635137/.local/lib/python2.7/site-packages/pymc3/plots/posteriorplot.pyc in plot_posterior_predictive_glm(trace, eval, lm, samples, **kwargs)
    151     for rand_loc in np.random.randint(0, len(trace), samples):
    152         rand_sample = trace[rand_loc]
--> 153         plt.plot(eval, lm(eval, rand_sample), **kwargs)
    154     # Make sure to not plot label multiple times
    155         kwargs.pop('label', None)

/home/a635137/.local/lib/python2.7/site-packages/pymc3/plots/posteriorplot.pyc in <lambda>(x, sample)
    138     """
    139     if lm is None:
--> 140         lm = lambda x, sample: sample['Intercept'] + sample['x'] * x
    141 
    142     if eval is None:

KeyError: 'x'

**Comment by twiecki** [comment]
@harc007 Can you format your post using markdown so that it's easier to see what's going on?
