### ISSUE TITLE
erratic failing conda test on main

### ISSUE THREAD

**Issue by Spaak** [pymc-devs/pymc#4862]
CI is occasionally [failing on `main`](https://github.com/pymc-devs/pymc3/runs/3056519926) due to some conda error:

In the step `Updating 'pymc3-dev-py38' env from conda env update...`:
```
InvalidArchiveError('Error with archive C:\\Users\\runneradmin\\conda_pkgs_dir\\m2w64-gcc-5.3.0-6.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
```

We get the same [error in at least this PR](https://github.com/pymc-devs/pymc3/pull/4849/checks?check_run_id=3057613107), though related to a different file:
```
 InvalidArchiveError('Error with archive C:\\Users\\runneradmin\\conda_pkgs_dir\\mkl-2020.4-hb70f87d_311.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')
```

**Comment by michaelosthege** [comment]
That looks like the conda error that is happening every now and then, also for different platforms.
On the latest runs of the CI on `main` everything was ✔.

**Comment by Spaak** [comment]
Ideally this error would never happen of course. Perhaps let's keep this issue open for if/when we want to fix the error permanently? And close the issue if/when the error hasn't happened for a while?
