### ISSUE TITLE
Return prior & posterior predictive samples as xarray object

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#4863]
As of now, sampling returns an [xarray](http://xarray.pydata.org/en/stable/) object, but when doing posterior predictive checks the posterior predictive samples are _not_ returned as xarray objects. Perhaps this could be changed for increased consistency?

**Comment by ricardoV94** [comment]
I guess the same applies to the prior predictive

**Comment by OriolAbril** [comment]
afaik this has already been fixed, I will make it so it is closed with #5268 which should in addition make this more user friendly.
