### ISSUE TITLE
JAX tests in CI fail for v3

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4865]
It's because of the omnistaging thing..

https://github.com/pymc-devs/pymc3/runs/3066108503#step:8:25

@twiecki it looks like it was fixed on `main`?
Can't we just remove JAX support on `v3`? I don't see how experimental JAX support is sustainable on both `v3` and `main`  branches.

**Comment by twiecki** [comment]
Yeah, I agree we should just remove it.

**Comment by michaelosthege** [comment]
closed by #4866
