### ISSUE TITLE
minor pymc3.gp.cov.Exponential documentation confusion

### ISSUE THREAD

**Issue by katosh** [pymc-devs/pymc#4871]
Currently, the [doc](https://docs.pymc.io/api/gp/cov.html#pymc3.gp.cov.Exponential) for the `ls` parameter in `pymc3.gp.cov.Exponential` states it is involved as as a square: 
https://github.com/pymc-devs/pymc3/blob/bc2c24a3fda645e97e180b7e45d045340476e0b3/pymc3/gp/cov.py#L446

However, the implementation seems to imply it is is not squared in this formula:
```python
import numpy as np
import pandas as pd
from pymc3.gp.cov import Exponential
import plotnine as p9

ls = 100
grid = np.arange(2000)

fn = Exponential(1, ls=ls)

def Exp(l, x):
    return np.exp(-np.abs(x)/(2*l))

def Exp2(l, x):
    return np.exp(-np.abs(x)/(2*l**2))

df0 = pd.DataFrame({
    'function':'pymc3.gp.cov.Exponential(ls)(x)',
    'x':grid,
    'cov':fn(np.zeros((1, 1)), grid[:, None]).eval().ravel(),
})
df1 = pd.DataFrame({
    'function':'np.exp(-np.abs(x)/(2*ls))',
    'x':grid,
    'cov':Exp(ls, grid),
})
df2 = pd.DataFrame({
    'function':'np.exp(-np.abs(x)/(2*ls**2))',
    'x':grid,
    'cov':Exp2(ls, grid),
})
lcorrdf = pd.concat([df0, df1, df2], axis=0)
pl = (
    p9.ggplot(lcorrdf)
    + p9.aes('x', 'cov', color='function')
    + p9.geom_line(alpha=.5)
    + p9.ggtitle(f'ls = 500')
    + p9.theme(figure_size=(6, 4))
)
pl
```
![image](https://user-images.githubusercontent.com/4857068/126263164-f44f86c0-fde5-4852-a795-ec00b75e5449.png)

**Comment by katosh** [comment]
I find the implementation correct and would suggest to change the documentation.

**Comment by bwengals** [comment]
Yes, thank you very much for finding and checking this.  It does look like a problem with the docs.  If you have the time, feel free to submit a pull request to fix this.

**Comment by ricardoV94** [comment]
@bwengals Do you know if this has been sorted out?

**Comment by fonnesbeck** [comment]
Looks like the change is only in the fork, and no PR was created. I can do one now.
