### ISSUE TITLE
Allow `Domain` to work with sparse arrays as input.

### ISSUE THREAD

**Issue by zoj613** [pymc-devs/pymc#4873]
When passing sparse arrays as input for the `Domain` objects in tests, a `ValueError` is raised. Is it possible to support scipy sparse arrays?

```
self = <pymc3.tests.test_distributions.Domain object at 0x7f66bceaaaf0>
vals = [<500x500 sparse matrix of type '<class 'numpy.float64'>'
	with 2042 stored elements in Compressed Sparse Row format>,..., <500x500 sparse matrix of type '<class 'numpy.float64'>'
	with 1912 stored elements in Compressed Sparse Row format>]
dtype = None, edges = None, shape = None

    def __init__(self, vals, dtype=None, edges=None, shape=None):
        avals = array(vals, dtype=dtype)
        if dtype is None and not str(avals.dtype).startswith("int"):
>           avals = avals.astype(aesara.config.floatX)
E           ValueError: setting an array element with a sequence.
```

**Comment by ricardoV94** [comment]
`Domain` is just supposed to be a helper method, so we don't want to build too much things on top of it. But you can subclass a `SparseDomain` and override the parts that fail with sparse inputs.

**Comment by Sayam753** [comment]
If there is some interest, can we plan to use [hypothesis](https://hypothesis.readthedocs.io/en/latest/) to help generate inputs for these test cases?

**Comment by ricardoV94** [comment]
> If there is some interest, can we plan to use [hypothesis](https://hypothesis.readthedocs.io/en/latest/) to help generate inputs for these test cases?

After working a lot with those tests... I wouldn't recommend. 

It's very easy to get extreme combinations of parameters that underflow to `-inf` in Scipy or on our side --usually not at the same points-- which would fail the tests. 

Also we are comparing digit equality regardless of whether it is a difference between `-600.1` vs `600.0` or `0.1` vs `0.0` logp. We would need to do something smarter there to have a useful hypothesis framework
