### ISSUE TITLE
BLAS and GPU nonfunctional

### ISSUE THREAD

**Issue by markbegma** [pymc-devs/pymc#4876]
## BLAS and GPU nonfunctional

Hello,
When I try to run any kind of model, i get two following warnings:

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)

**What I tried:**

I felt these problems have one reason of being unable to use my GPU, which has CUDA and tensorflow working with it just fine. It seems that this might be caused by problems installing pygpu.
I tried this guide:

https://github.com/Theano/libgpuarray/blob/master/doc/installation.rst#step-by-step-install-system-library-as-admin

**Everything works fine until this step:**

cmake .. -DCMAKE_BUILD_TYPE=Release

**where I see the following traceback:**

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.28.29910.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at CMakeLists.txt:26 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - not found
-- Found PkgConfig: C:/MinGW/bin/pkg-config.exe (found version "0.26")
-- Checking for one of the modules 'check'
Tests disabled because Check was not found
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project: CMAKE_BUILD_TYPE

-- Build files have been written to: C:/Users/markbegma/libgpuarray/Build

**And when I try to execute the following command "make", I get a message saying something is absent:**

make: *** No targets specified and no makefile found.  Stop.

Am I right about absent libgpuarray being the reason for the warnings? If yes, then what am I doing wrong?

Thank you in advance!

Below are the specs. I did read that conda is the best way to install, but the problem is that my work can't be going in the conda environments.

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara/Theano Version: 1.1.2
* Python Version: 3.9
* Operating system: Windows 10
* How did you install PyMC3: pip

**Comment by twiecki** [comment]
Did you use conda to install?

We are removing pygpu so this problem should go away with 4.0.
