### ISSUE TITLE
Add return types in docstrings for logprob.py

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4880]
Add return types in docstring for all methods in `logprob.py` following the numpy style. Theyre missing and it would be nice to include them for consistency and readability

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html
https://github.com/pymc-devs/pymc3/blob/main/pymc3/distributions/logprob.py#L48

**Comment by osdev-in** [comment]
Hey @canyon289 , I want to take up this. Would you please help me to understand what they return ? or Do I have to go through the code and figure out?

**Comment by canyon289** [comment]
@kadatatlukishore youre welcome to take this up! To answer your question I actually dont specifically know what they all return at a level needed for a docstring. Youd need to either go through the code to figure it out or ping a couple of the devs who wrote the code (using git blame to find that out) and fill it in

Feel free to break this apart and submit a PR per method to make things easier if you like. If after all that this still sounds interesting let me know and I can assign the ticket to you

**Comment by osdev-in** [comment]
Thanks @canyon289 . Will figure out a way to complete this work

**Comment by canyon289** [comment]
Thanks! Assigned the ticket to you

**Comment by LorenSantana** [comment]
It seems like the link to `logprob.py` is broken in your original note @canyon289. It should be:
https://github.com/pymc-devs/pymc/blob/main/pymc/distributions/logprob.py

If this is available, I don't mind working on it. 
From doing a quick pass at the file, the last two definitions don't have `Parameter` specifications. Would you like me to add those too?

**Comment by canyon289** [comment]
Thanks for noting that. This certainly is available. And yes please feel free to add anything that will improve the documentation
