### ISSUE TITLE
 step_methods/hmc/quadpotential.py:224: What is this about?

### ISSUE THREAD

**Issue by pythonometrist** [pymc-devs/pymc#4882]
The full error  during inference is 
...step_methods/hmc/quadpotential.py:224: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)

I checked the data, none of the variables have zeros variance. Any pointers would be most welcome.

Thanks

**Comment by twiecki** [comment]
This is better suited for our discourse forum: https://discourse.pymc.io/
