### ISSUE TITLE
`Lognormal` distribution is not in camel case, unlike all the other distributions

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#4885]
All of the distribution names with two or more parts use camel case (i.e. `DiscreteUniform`, `ZeroInflatedPoisson`, etc).

The exception however is the [`Lognormal`](https://docs.pymc.io/api/distributions/continuous.html#pymc3.distributions.continuous.Lognormal) distribution. 

I propose that this distribution be changed to `LogNormal`.

**Comment by twiecki** [comment]
Agreed.

**Comment by fonnesbeck** [comment]
Let's make an alias to `Lognormal`, of course, so nothing breaks.

**Comment by canyon289** [comment]
> Let's make an alias to `Lognormal`, of course, so nothing breaks.

Perhaps with a deprecation warning as well so it can be removed in the future?
