### ISSUE TITLE
Remove initval arg or fix docstring

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#4893]
## Description of your problem
The usage of `initval` is not clear in this method. Verify if it indeed is needed. If it is fix the docstring spelling
https://github.com/pymc-devs/pymc3/blob/main/pymc3/distributions/distribution.py#L261

**Comment by michaelosthege** [comment]
My PR removes it: https://github.com/pymc-devs/pymc3/pull/4867

Unfortunately it seems to be stalled :(
It works though.
