### ISSUE TITLE
Glossary terms

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#4899]
I thought it may be more convenient to have an issue where anyone can propose terms to be added to the glossary instead of requiring a PR for every term. So far, #4797 adds only functional programming and dispatching terms.

**Comment by ally-lee** [comment]
Some terms from pymc-devs/pymc-examples#185 to potentially add to the glossary:
- Equidispersion: variance = mean
- Underdisperson: variance < mean
- Overdispersion: variance > mean
- Generalized Poisson PMF:
<img width="345" alt="Screen Shot 2021-08-14 at 12 15 57 PM" src="https://user-images.githubusercontent.com/30029312/129457905-1f526c03-3eeb-4d23-8e92-7acf11cd4874.png">
<img width="521" alt="Screen Shot 2021-08-14 at 12 16 06 PM" src="https://user-images.githubusercontent.com/30029312/129457909-022ac711-f236-45b4-b35d-69732f4661bf.png">

**Comment by ricardoV94** [comment]
The staples: Prior, Likelihood, Posterior, MC, MCMC, Markov chain, Probability density, Probability mass, MAP, MLE...

**Comment by martinacantaro** [comment]
Work has already started on building this glossary. Here are the details:

**Goal**
Building a useful Glossary with definitions of common terms, that can be linked to from the documents.

**How to contribute**
 1. Pick a term from the list below, excluding those labeled `in progress` (those have already been picked)
 2. Comment this issue to inform us that you are working on it.
 3. Make a PR editing the [docs/source/glossary.md](https://github.com/pymc-devs/pymc3/tree/main/docs) file following [this format](https://jupyterbook.org/content/content-blocks.html?highlight=glossary#glossaries)
 4. Include the following ID string in your PR title or commit message (this will help us keep track of it in Clickup): CU-5t5y0p

**List of terms:**

* Maximum Likelihood Estimation (MLE) `(in progress)`
* Probability density `(in progress)`

**Comment by jyoti-bhogal** [comment]
I would add the term Ordinary Differential Equation (ODE)

**Comment by xiaoye-hua** [comment]
I will add the term Maximum a Posteriori (MAP)

**Comment by amrith8** [comment]
I will add the term Hamiltonian Monte Carlo

**Comment by ricardoV94** [comment]
Is this issue still needed?
