### ISSUE TITLE
Theano 1.1.2 does'nt work with gpu under windows 

### ISSUE THREAD

**Issue by ivvaan** [pymc-devs/pymc#4909]
## Description of your problem
Taken from https://github.com/twiecki/Theano-PyMC
**Theano 1.0.11** (from December 2020) after fixing problem with gpuarray __init__.py ('from theano.compile import optdb' must be moved in a string just befor 'optdb.add_tags(...)')and dnn.py (WIN32_CUDNN_NAMES should be ["cudnn64_8.dll","cudnn64_7.dll", "cudnn64_6.dll", "cudnn64_5.dll"]) **does work with CUDA gpu on windows**, but pymc3  3.11.2 does'nt work with that theano version.

On the other hand, **Theano 1.1.2** (from January 2021) after fixing the same problems **does'nt work with CUDA gpu**, though compartible with pymc3  3.11.2. Somthing bad happend with Theano between December and January.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import os
os.environ["THEANO_FLAGS"] = "device=cuda0"
import theano
from theano import function, config, shared
import numpy
vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], theano.tensor.exp(x))
print(f.maker.fgraph.toposort())
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python

```
Mapped name None to device cuda0: NVIDIA GeForce GTX 1650 with Max-Q Design (0000:02:00.0)
ERROR (theano.graph.opt): SeqOptimizer apply <theano.gpuarray.opt.GraphToGPU object at 0x000001449548AC70>
ERROR (theano.graph.opt): Traceback:
ERROR (theano.graph.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\graph\opt.py", line 245, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\graph\opt.py", line 83, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\gpuarray\opt.py", line 374, in apply
    new_ops = lopt.transform(
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\graph\opt.py", line 1209, in transform
    return self.fn(*args, **kwargs)
TypeError: local_gpua_elemwise() missing 1 required positional argument: 'outputs'

ERROR (theano.graph.opt): Optimization failure due to: local_gpua_elemwise
ERROR (theano.graph.opt): node: Elemwise{exp,no_inplace}(HostFromGpu(gpuarray).0)
ERROR (theano.graph.opt): TRACEBACK:
ERROR (theano.graph.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\graph\opt.py", line 2017, in process_node
    replacements = lopt.transform(fgraph, node)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\graph\opt.py", line 1209, in transform
    return self.fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano_pymc-1.1.2-py3.8.egg\theano\gpuarray\opt_util.py", line 497, in local_opt
    new_op = maker(node.op, context_name, node.inputs, node.outputs)
TypeError: local_gpua_elemwise() missing 1 required positional argument: 'outputs'

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC3 Version:3.11.2
* Aesara/Theano Version:1.1.2
* Python Version:3.8
* Operating system: windows 10
* How did you install PyMC3: (conda/pip) conda

**Comment by fonnesbeck** [comment]
PyMC3 is not designed to take advantage of the GPU, either for sampling or variational inference. Hopefully we will have support for some approximation algorithms in the future once we can compile to different backends with Aesara, but for now GPUs are not supported. I will close this because it is not a PyMC3 bug.
