### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by KennethEnevoldsen** [pymc-devs/pymc#4916]
There seems to be a broken link in the documentation:

in the section [Arbitrary deterministic](https://docs.pymc.io/notebooks/getting_started.html#Arbitrary-deterministics) in the getting started. The broken link is the "[a more elaborate example of the usage of as_op.](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/disaster_model_theano_op.py)". It seems to refer to the examples folder which I could not find?

**Comment by twiecki** [comment]
Thanks for the report, we moved the examples over to https://github.com/pymc-devs/pymc-examples.

**Comment by twiecki** [comment]
Want to do a PR with the fix?

**Comment by KennethEnevoldsen** [comment]
I have opened a PR over on the PyMC-examples with the fix. Also checked if any other link were broken in the tutorial.

**Comment by twiecki** [comment]
Awesome, thanks!
