### ISSUE TITLE
Got nothing from data of a saved netcdf file (.nc).

### ISSUE THREAD

**Issue by ivaquero** [pymc-devs/pymc#4917]
## Description of your problem

Hi community, 

I am learning Bayesian Inference using PyMC3 and ArviZ. When trying to do posterior predictive checks, I got nothing from `pm.sample_posterior_predictive()`. Please help.

> I can get correct results by using `trace` generated by `pm.sample()`

```python
import pymc3 as pm
import arviz as az

np.random.seed(123)
trials = 4
theta_real = 0.35  # unknown value in a real experiment
data = stats.bernoulli.rvs(p=theta_real, size=trials)

with pm.Model() as model1:
    θ = pm.Beta('θ', alpha=1., beta=1.)
    y = pm.Bernoulli('y', p=θ, observed=data)
    trace = pm.sample(1000, random_seed=123, return_inferencedata=True)

# trace.to_netcdf("../data/ch1/bern_coin.nc")
trace = az.from_netcdf("../data/ch1/bern_coin.nc") # this an arviz.InferenceData

with pm.Model() as model1:
    y_pred = pm.sample_posterior_predictive(trace, 200)

print(y_pred) # {}
```

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara/Theano Version: 1.1.2
* Python Version: 3.9.6
* Operating system: MacOS Big Sur
* How did you install PyMC3: conda

**Comment by michaelosthege** [comment]
Your second `with` context creates a new model that doesn't have any variables.
For the posterior predictive you must re-use the `model1` from your first modelcontext:
```python
with model1:
    y_pred = pm.sample_posterior_predictive(...)
```

**Comment by ivaquero** [comment]
Thank you for the reply. 

Yeah, I understand that `sample_posterior_predictive` needs to be used with context. Then, how can I use `sample_posterior_predictive` with data of a saved `netcdf` file since I don't want to sample every time (sometimes it took so long) ?

**Comment by michaelosthege** [comment]
You don't need to run the `pm.sample` line from the first context. You just need the creation of the model.
You could make an if/else based on if your save file exists and either sample and save or load it.

**Comment by ivaquero** [comment]
Thank you ! It's a really helpful suggestion.

**Comment by michaelosthege** [comment]
You're welcome. I suppose we can close this now.
