### ISSUE TITLE
How can I get marginal likelihood of a model ?

### ISSUE THREAD

**Issue by ivaquero** [pymc-devs/pymc#4930]
## Description of your problem

Hi community, 

I am learning Bayesian Inference using PyMC3 following the book "Bayesian Analysis with Python" by Osvaldo Martin. In the notebook `Model Comparison` (about Bayesian Factor), I got the following message when I tried to calculate marginal likelihood of models:

AttributeError: 'Model' object has no attribute 'marginal_likelihood'

```python
with pm.Model() as model_bf_0:
    θ = pm.Beta('θ', 4, 8)
    y = pm.Bernoulli('y', θ, observed=y_d)
    # trace_bf_0= pm.sample_smc(2500)

with pm.Model() as model_bf_1:
    θ = pm.Beta('θ', 8, 4)
    y = pm.Bernoulli('y', θ, observed=y_d)
    trace_bf_1 = pm.sample_smc(2500)

model_bf_0.marginal_likelihood / model_bf_1.marginal_likelihood
```

How can I deal with this ?

## Versions and main components

* PyMC3 Version: 3.11.2
* Aesara/Theano Version: 1.1.2
* Python Version: 3.9.6
* Operating system: MacOS Big Sur
* How did you install PyMC3: conda

**Comment by ricardoV94** [comment]
The marginal likelihood will be in the trace `trace_bf1.report.log_marginal_likelihood` if I am not mistaken.

**Comment by integzz** [comment]
Hi @ricardoV94, I tried. But, I got `AttributeError: 'InferenceData' object has no attribute 'report'`.

**Comment by ivaquero** [comment]
Thank you, @ricardoV94. It worked. If you don't mind, I have one more question, how can I convert `InferenceData` into `MultiTrace` ?

**Comment by ricardoV94** [comment]
> Thank you, @ricardoV94. It worked. If you don't mind, I have one more question, how can I convert `InferenceData` into `MultiTrace` ?

You shouldn't have to. InferenceData will contain the same information under `sample_stats`, otherwise you can specify when sampling `return_inferencedata=False` to receive a MultiTrace but that's not recommended.

If you have more questions feel free to open an entry in our discourse at https://discourse.pymc.io/ and tag me if needed.

I'll close this issue as we try to keep development only issues here.
