### ISSUE TITLE
Show code example and output in `Graphic Models` API section

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#4940]
From an unrelated PR, this is how the `Graphic Models` API section looks for the main branch: 

![image](https://user-images.githubusercontent.com/28983449/129710944-00272ecc-9a60-4a9b-8875-22ce655f4ea8.png)

It would be cool to show some python code calling `pm.model_to_graphviz` and the example output, as this is a very neat ability we have.

**Comment by percevalve** [comment]
Looking into it, let me post a PR.
