### ISSUE TITLE
`pm.MvNormal` handles covariance matrices with large values incorrectly

### ISSUE THREAD

**Issue by colehaus** [pymc-devs/pymc#4951]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pymc3 as pm
import theano.tensor as tt

data1 = np.random.random((200, 3))

with pm.Model() as model:
  chol, corr, stds = pm.LKJCholeskyCov("chol", eta=2, n=3, sd_dist=pm.Exponential.dist(1), compute_corr=True)
  cov = tt.dot(chol, chol.T)
  test1 = pm.MvNormal("test1", mu=np.zeros(3), cov=cov, shape=3)
  test2 = pm.MvNormal("test2", mu=np.zeros(3), cov=cov*1000000, shape=3)
  test3 = pm.MvNormal("test3", mu=np.zeros(3), cov=cov*1000000000000, shape=3)

  idata = pm.sample(1000, tune=100, return_inferencedata=True, cores=1, chains=1)
  az.summary(idata)
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

  | mean | sd | hdi_3% | hdi_97% | mcse_mean | mcse_sd | ess_mean | ess_sd | ess_bulk | ess_tail | r_hat
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
test1[0] | 0.000 | 0.001 | -0.002 | 0.002 | 0.000 | 0.000 | 16.0 | 16.0 | 18.0 | 23.0 | NaN
test1[1] | -0.000 | 0.001 | -0.002 | 0.001 | 0.000 | 0.000 | 15.0 | 8.0 | 12.0 | 37.0 | NaN
test1[2] | 0.120 | 0.007 | 0.109 | 0.131 | 0.005 | 0.004 | 2.0 | 2.0 | 2.0 | 8.0 | NaN
test2[0] | 0.973 | 0.003 | 0.968 | 0.978 | 0.002 | 0.002 | 1.0 | 1.0 | 1.0 | 11.0 | NaN
test2[1] | 0.721 | 0.004 | 0.714 | 0.727 | 0.001 | 0.001 | 9.0 | 9.0 | 9.0 | 15.0 | NaN
test2[2] | 2.708 | 0.018 | 2.690 | 2.743 | 0.015 | 0.014 | 1.0 | 1.0 | 2.0 | 4.0 | NaN
test3[0] | -4.343 | 0.023 | -4.371 | -4.296 | 0.013 | 0.010 | 3.0 | 3.0 | 3.0 | 13.0 | NaN
test3[1] | 1.709 | 0.015 | 1.693 | 1.738 | 0.012 | 0.012 | 1.0 | 1.0 | 1.0 | 19.0 | NaN
test3[2] | 0.113 | 0.006 | 0.103 | 0.121 | 0.004 | 0.004 | 2.0 | 2.0 | 2.0 | 18.0 | NaN
</details>

**Please provide any additional information below.**

As you can see, the hdi doesn't really scale as you'd expect. Compare these results to those from `pm.MvNormal.dist` which seem more correct:

```python
print(pm.MvNormal.dist(mu=np.zeros(3), cov=np.fill_diagonals(np.zeros((3,3)), 1), shape=3).random(size=100))
```
<details>
[[ 0.65331524  0.65331524  0.65331524]
 [ 0.76423486  0.76423487  0.76423487]
 [ 0.97887766  0.97887766  0.97887766]
 [ 0.02084732  0.02084733  0.02084733]
 [ 1.03297487  1.03297487  1.03297487]
 [-0.63086283 -0.63086283 -0.63086283]
 [ 0.03849237  0.03849238  0.03849238]
 [ 0.53447744  0.53447745  0.53447745]
 [ 1.61402405  1.61402406  1.61402406]
 [-2.79061495 -2.79061495 -2.79061495]
 [-0.95743741 -0.95743741 -0.95743741]
 [-0.0382744  -0.0382744  -0.0382744 ]
 [ 0.65412606  0.65412605  0.65412605]
 [ 0.61702663  0.61702663  0.61702663]
 [ 1.40097661  1.40097661  1.40097661]
 [-1.86004183 -1.86004182 -1.86004182]
 [ 2.04550826  2.04550826  2.04550826]
 [ 0.87495883  0.87495882  0.87495882]
 [-0.6540124  -0.65401241 -0.65401241]
 [ 1.70925977  1.70925977  1.70925977]
 [ 0.44789299  0.44789299  0.44789299]
 [ 0.81427187  0.81427187  0.81427187]
 [ 1.79745071  1.7974507   1.7974507 ]
 [-0.31955533 -0.31955533 -0.31955533]
 [ 0.15792177  0.15792177  0.15792177]
 [ 1.66290411  1.6629041   1.6629041 ]
 [-0.3533083  -0.35330829 -0.35330829]
 [-1.95595892 -1.95595891 -1.95595891]
 [ 1.21137927  1.21137927  1.21137927]
 [ 1.55877134  1.55877135  1.55877135]
 [-0.1331685  -0.13316851 -0.13316851]
 [-0.9059326  -0.90593261 -0.90593261]
 [-0.82404826 -0.82404826 -0.82404826]
 [-0.17710764 -0.17710764 -0.17710764]
 [-1.15807688 -1.15807688 -1.15807688]
 [ 1.15033348  1.15033347  1.15033347]
 [ 0.19440014  0.19440014  0.19440014]
 [-0.29690549 -0.29690549 -0.29690549]
 [ 0.66913967  0.66913967  0.66913967]
 [-1.05960398 -1.05960398 -1.05960398]
 [-0.27137114 -0.27137114 -0.27137114]
 [ 0.26604117  0.26604116  0.26604116]
 [ 0.80285412  0.80285413  0.80285413]
 [-0.62198547 -0.62198547 -0.62198547]
 [-0.60731523 -0.60731523 -0.60731523]
 [ 1.17897325  1.17897323  1.17897323]
 [ 0.3810071   0.3810071   0.3810071 ]
 [ 1.64490105  1.64490106  1.64490106]
 [ 0.67246128  0.67246129  0.67246129]
 [-0.94191183 -0.94191183 -0.94191183]
 [ 0.91922621  0.91922621  0.91922621]
 [-0.18969437 -0.18969437 -0.18969437]
 [-0.58957846 -0.58957845 -0.58957845]
 [-0.94872513 -0.94872513 -0.94872513]
 [-2.093297   -2.09329701 -2.09329701]
 [-0.04542965 -0.04542966 -0.04542966]
 [-0.61409809 -0.61409809 -0.61409809]
 [ 0.12194284  0.12194282  0.12194282]
 [ 0.25887569  0.2588757   0.2588757 ]
 [ 0.01218348  0.01218348  0.01218348]
 [ 0.23576144  0.23576144  0.23576144]
 [ 0.55266584  0.55266584  0.55266584]
 [-0.72054884 -0.72054884 -0.72054884]
 [ 0.36716143  0.36716142  0.36716142]
 [-0.37913325 -0.37913326 -0.37913326]
 [ 0.06552322  0.06552322  0.06552322]
 [-1.15073997 -1.15073997 -1.15073997]
 [-0.40420701 -0.40420701 -0.40420701]
 [-0.6482042  -0.6482042  -0.6482042 ]
 [ 1.56847633  1.56847633  1.56847633]
 [ 0.52477581  0.52477581  0.52477581]
 [-1.52880353 -1.52880353 -1.52880353]
 [ 0.61764213  0.61764213  0.61764213]
 [-0.4625687  -0.46256871 -0.46256871]
 [-2.09012151 -2.09012151 -2.09012151]
 [-1.46331191 -1.46331192 -1.46331192]
 [ 0.40336523  0.40336524  0.40336524]
 [-1.44547384 -1.44547385 -1.44547385]
 [-0.57532605 -0.57532604 -0.57532604]
 [-0.05204153 -0.05204153 -0.05204153]
 [ 1.52696098  1.52696099  1.52696099]
 [-0.80745697 -0.80745697 -0.80745697]
 [ 1.15541042  1.15541043  1.15541043]
 [-1.70233001 -1.70233    -1.70233   ]
 [ 0.41031209  0.41031209  0.41031209]
 [-1.03611244 -1.03611245 -1.03611245]
 [-1.53420438 -1.53420437 -1.53420437]
 [ 0.31128644  0.31128645  0.31128645]
 [ 0.18075452  0.18075452  0.18075452]
 [-0.38323549 -0.38323549 -0.38323549]
 [ 0.18750288  0.18750288  0.18750288]
 [ 0.33231942  0.33231943  0.33231943]
 [ 1.10765438  1.10765438  1.10765438]
 [ 0.40746374  0.40746374  0.40746374]
 [ 0.70559804  0.70559804  0.70559804]
 [-0.2988029  -0.29880289 -0.29880289]
 [ 0.88225628  0.88225628  0.88225628]
 [-0.33973009 -0.3397301  -0.3397301 ]
 [ 0.88525081  0.8852508   0.8852508 ]
 [-1.67117136 -1.67117135 -1.67117135]]
</details>

```python
print(pm.MvNormal.dist(mu=np.zeros(3), cov=np.fill_diagonals(np.zeros((3,3)), 1000000), shape=3).random(size=100))
```
<details>
[[ 1.50147000e+03  1.50147002e+03  1.50147002e+03]
 [ 2.32819491e+03  2.32819493e+03  2.32819493e+03]
 [-1.32738320e+02 -1.32738360e+02 -1.32738360e+02]
 [-3.17472572e+02 -3.17472568e+02 -3.17472568e+02]
 [-8.07177146e+02 -8.07177162e+02 -8.07177162e+02]
 [ 5.24100705e+02  5.24100767e+02  5.24100767e+02]
 [-9.63160009e+02 -9.63160014e+02 -9.63160014e+02]
 [-5.41524054e+02 -5.41524041e+02 -5.41524041e+02]
 [-8.49429832e+02 -8.49429827e+02 -8.49429827e+02]
 [-2.73692793e+02 -2.73692767e+02 -2.73692767e+02]
 [-8.98887063e+02 -8.98887046e+02 -8.98887046e+02]
 [-4.32242522e+02 -4.32242544e+02 -4.32242544e+02]
 [ 1.01668965e+03  1.01668967e+03  1.01668967e+03]
 [ 5.18840492e+02  5.18840499e+02  5.18840499e+02]
 [-9.18290320e+02 -9.18290293e+02 -9.18290293e+02]
 [ 9.06965287e+01  9.06965669e+01  9.06965669e+01]
 [ 1.22624407e+03  1.22624406e+03  1.22624406e+03]
 [ 1.56909220e+02  1.56909220e+02  1.56909220e+02]
 [ 5.43909994e+02  5.43909919e+02  5.43909919e+02]
 [ 4.54447268e+02  4.54447268e+02  4.54447268e+02]
 [ 9.22614242e+02  9.22614268e+02  9.22614268e+02]
 [-1.07502455e+03 -1.07502453e+03 -1.07502453e+03]
 [-6.61710366e+01 -6.61710555e+01 -6.61710555e+01]
 [ 9.64559056e+02  9.64559079e+02  9.64559079e+02]
 [-8.37661501e+02 -8.37661491e+02 -8.37661491e+02]
 [ 1.76390366e+03  1.76390360e+03  1.76390360e+03]
 [-1.06248089e+03 -1.06248088e+03 -1.06248088e+03]
 [-4.16982865e+02 -4.16982854e+02 -4.16982854e+02]
 [-1.06920410e+03 -1.06920411e+03 -1.06920411e+03]
 [ 7.55460160e+02  7.55460183e+02  7.55460183e+02]
 [-2.11643716e+03 -2.11643713e+03 -2.11643713e+03]
 [-7.68224187e+02 -7.68224189e+02 -7.68224189e+02]
 [ 7.93609817e+02  7.93609833e+02  7.93609833e+02]
 [-2.42338765e+03 -2.42338763e+03 -2.42338763e+03]
 [ 2.47751357e+03  2.47751358e+03  2.47751358e+03]
 [-7.33178099e+02 -7.33178120e+02 -7.33178120e+02]
 [-3.00971395e+02 -3.00971411e+02 -3.00971411e+02]
 [ 6.34117646e+02  6.34117635e+02  6.34117635e+02]
 [ 1.39104767e+03  1.39104767e+03  1.39104767e+03]
 [-1.46724667e+03 -1.46724671e+03 -1.46724671e+03]
 [ 9.10426275e+01  9.10425825e+01  9.10425825e+01]
 [ 1.04111462e+03  1.04111459e+03  1.04111459e+03]
 [-1.33091391e+03 -1.33091391e+03 -1.33091391e+03]
 [ 9.84550596e+02  9.84550622e+02  9.84550622e+02]
 [ 9.67340217e+01  9.67340482e+01  9.67340482e+01]
 [-1.17210289e+03 -1.17210289e+03 -1.17210289e+03]
 [ 8.82954784e+01  8.82954810e+01  8.82954810e+01]
 [ 2.00559927e+02  2.00559915e+02  2.00559915e+02]
 [-7.77167938e+01 -7.77168006e+01 -7.77168006e+01]
 [-7.20059238e+02 -7.20059208e+02 -7.20059208e+02]
 [-5.74537700e+02 -5.74537623e+02 -5.74537623e+02]
 [ 1.00306139e+03  1.00306138e+03  1.00306138e+03]
 [ 1.25790914e+03  1.25790914e+03  1.25790914e+03]
 [-6.20282984e+02 -6.20282946e+02 -6.20282946e+02]
 [ 6.43501481e+02  6.43501514e+02  6.43501514e+02]
 [-1.01785044e+02 -1.01785037e+02 -1.01785037e+02]
 [ 1.35027909e+03  1.35027910e+03  1.35027910e+03]
 [-5.80645071e+02 -5.80645076e+02 -5.80645076e+02]
 [-7.79569131e+01 -7.79569139e+01 -7.79569139e+01]
 [ 3.44866281e+02  3.44866251e+02  3.44866251e+02]
 [-6.94342471e+02 -6.94342497e+02 -6.94342497e+02]
 [ 1.44597201e+03  1.44597207e+03  1.44597207e+03]
 [-1.85557523e+03 -1.85557520e+03 -1.85557520e+03]
 [ 4.52138648e+02  4.52138585e+02  4.52138585e+02]
 [ 9.55639959e+01  9.55640049e+01  9.55640049e+01]
 [-1.63502170e+03 -1.63502170e+03 -1.63502170e+03]
 [ 2.90524946e+02  2.90524995e+02  2.90524995e+02]
 [ 1.88987964e+03  1.88987967e+03  1.88987967e+03]
 [-8.50845227e-01 -8.50853243e-01 -8.50853243e-01]
 [ 6.37973309e+02  6.37973317e+02  6.37973317e+02]
 [ 1.44244234e+03  1.44244232e+03  1.44244232e+03]
 [ 1.51252395e+03  1.51252402e+03  1.51252402e+03]
 [-1.57354339e+03 -1.57354339e+03 -1.57354339e+03]
 [-3.71867639e+02 -3.71867619e+02 -3.71867619e+02]
 [ 2.66110386e+02  2.66110401e+02  2.66110401e+02]
 [ 2.51315333e+01  2.51315468e+01  2.51315468e+01]
 [-3.39863723e+02 -3.39863711e+02 -3.39863711e+02]
 [ 1.23436669e+03  1.23436670e+03  1.23436670e+03]
 [ 1.41802659e+03  1.41802660e+03  1.41802660e+03]
 [-6.29538760e+01 -6.29538922e+01 -6.29538922e+01]
 [ 2.98078658e+02  2.98078675e+02  2.98078675e+02]
 [-1.60129842e+02 -1.60129852e+02 -1.60129852e+02]
 [ 5.62961771e+02  5.62961785e+02  5.62961785e+02]
 [ 2.89728421e+00  2.89724734e+00  2.89724734e+00]
 [ 2.16684090e+02  2.16684092e+02  2.16684092e+02]
 [ 3.26102633e+02  3.26102670e+02  3.26102670e+02]
 [-2.70488804e+02 -2.70488783e+02 -2.70488783e+02]
 [-1.44065327e+02 -1.44065295e+02 -1.44065295e+02]
 [-7.01944496e+02 -7.01944490e+02 -7.01944490e+02]
 [ 1.09242355e+03  1.09242354e+03  1.09242354e+03]
 [ 4.75603139e+02  4.75603159e+02  4.75603159e+02]
 [-2.22098361e+01 -2.22098002e+01 -2.22098002e+01]
 [ 6.58155623e+02  6.58155615e+02  6.58155615e+02]
 [ 1.33049504e+03  1.33049496e+03  1.33049496e+03]
 [-8.31962150e+00 -8.31959742e+00 -8.31959742e+00]
 [-7.99102301e+01 -7.99102123e+01 -7.99102123e+01]
 [ 7.37191693e+01  7.37191967e+01  7.37191967e+01]
 [-1.79167914e+03 -1.79167912e+03 -1.79167912e+03]
 [ 6.97580109e+02  6.97580071e+02  6.97580071e+02]
 [ 1.26217618e+02  1.26217600e+02  1.26217600e+02]]
</details>

```python
print(pm.MvNormal.dist(mu=np.zeros(3), cov=np.fill_diagonals(np.zeros((3,3)), 1000000000000), shape=3).random(size=100))
```
<details>
[[ 5.11642242e+05  5.11642231e+05  5.11642231e+05]
 [-1.44390863e+06 -1.44390865e+06 -1.44390865e+06]
 [ 6.99051106e+05  6.99051118e+05  6.99051118e+05]
 [-7.28951968e+05 -7.28951984e+05 -7.28951984e+05]
 [ 1.15728742e+06  1.15728743e+06  1.15728743e+06]
 [ 7.12614103e+05  7.12614134e+05  7.12614134e+05]
 [-6.47424693e+05 -6.47424701e+05 -6.47424701e+05]
 [ 1.20477537e+06  1.20477537e+06  1.20477537e+06]
 [-5.64559711e+05 -5.64559717e+05 -5.64559717e+05]
 [ 7.07609681e+05  7.07609718e+05  7.07609718e+05]
 [ 1.71080710e+06  1.71080712e+06  1.71080712e+06]
 [-3.91652185e+05 -3.91652186e+05 -3.91652186e+05]
 [ 4.50898038e+05  4.50898033e+05  4.50898033e+05]
 [ 1.96793327e+04  1.96793129e+04  1.96793129e+04]
 [-7.38947308e+05 -7.38947305e+05 -7.38947305e+05]
 [-1.21688110e+05 -1.21688082e+05 -1.21688082e+05]
 [ 1.62578860e+06  1.62578861e+06  1.62578861e+06]
 [-9.94662793e+05 -9.94662806e+05 -9.94662806e+05]
 [ 1.83087539e+05  1.83087531e+05  1.83087531e+05]
 [ 6.82030857e+05  6.82030840e+05  6.82030840e+05]
 [-8.62130738e+05 -8.62130720e+05 -8.62130720e+05]
 [ 1.96772906e+05  1.96772913e+05  1.96772913e+05]
 [ 5.74454635e+05  5.74454639e+05  5.74454639e+05]
 [-7.51314565e+05 -7.51314582e+05 -7.51314582e+05]
 [-4.08559455e+05 -4.08559463e+05 -4.08559463e+05]
 [ 1.79469258e+05  1.79469238e+05  1.79469238e+05]
 [ 2.03395611e+05  2.03395613e+05  2.03395613e+05]
 [-2.19985245e+05 -2.19985247e+05 -2.19985247e+05]
 [ 5.71152725e+05  5.71152737e+05  5.71152737e+05]
 [ 4.68961387e+05  4.68961361e+05  4.68961361e+05]
 [ 4.30683826e+05  4.30683818e+05  4.30683818e+05]
 [ 4.98107489e+05  4.98107503e+05  4.98107503e+05]
 [ 3.86999213e+05  3.86999238e+05  3.86999238e+05]
 [ 1.12127810e+06  1.12127807e+06  1.12127807e+06]
 [ 1.24394088e+06  1.24394089e+06  1.24394089e+06]
 [-3.84940804e+05 -3.84940808e+05 -3.84940808e+05]
 [-1.71070523e+06 -1.71070522e+06 -1.71070522e+06]
 [ 2.53434658e+06  2.53434658e+06  2.53434658e+06]
 [-2.18036048e+06 -2.18036050e+06 -2.18036050e+06]
 [-1.09120164e+06 -1.09120163e+06 -1.09120163e+06]
 [ 5.96194679e+05  5.96194673e+05  5.96194673e+05]
 [ 5.74207056e+04  5.74207005e+04  5.74207005e+04]
 [ 7.23620391e+05  7.23620402e+05  7.23620402e+05]
 [-2.02540656e+06 -2.02540653e+06 -2.02540653e+06]
 [ 9.49327724e+05  9.49327725e+05  9.49327725e+05]
 [-1.06697328e+06 -1.06697329e+06 -1.06697329e+06]
 [-6.36419982e+05 -6.36419984e+05 -6.36419984e+05]
 [ 7.40432290e+05  7.40432259e+05  7.40432259e+05]
 [ 2.29875699e+06  2.29875703e+06  2.29875703e+06]
 [-9.42726580e+04 -9.42726389e+04 -9.42726389e+04]
 [ 1.56327389e+06  1.56327391e+06  1.56327391e+06]
 [-9.15619364e+02 -9.15631350e+02 -9.15631350e+02]
 [-5.45206350e+05 -5.45206346e+05 -5.45206346e+05]
 [ 8.70305723e+05  8.70305697e+05  8.70305697e+05]
 [ 6.51263429e+05  6.51263482e+05  6.51263482e+05]
 [ 1.96010921e+05  1.96010939e+05  1.96010939e+05]
 [ 4.74882747e+05  4.74882738e+05  4.74882738e+05]
 [-2.03988917e+06 -2.03988915e+06 -2.03988915e+06]
 [ 5.09520135e+05  5.09520135e+05  5.09520135e+05]
 [ 2.74049978e+06  2.74049981e+06  2.74049981e+06]
 [-3.60112790e+05 -3.60112827e+05 -3.60112827e+05]
 [ 3.41898608e+05  3.41898636e+05  3.41898636e+05]
 [-3.00526475e+05 -3.00526488e+05 -3.00526488e+05]
 [-1.69140949e+06 -1.69140954e+06 -1.69140954e+06]
 [-5.61644845e+05 -5.61644867e+05 -5.61644867e+05]
 [-1.18867666e+06 -1.18867667e+06 -1.18867667e+06]
 [ 1.46245295e+06  1.46245293e+06  1.46245293e+06]
 [-1.34411752e+05 -1.34411770e+05 -1.34411770e+05]
 [-2.31632317e+06 -2.31632312e+06 -2.31632312e+06]
 [ 1.77379244e+05  1.77379239e+05  1.77379239e+05]
 [ 9.01901047e+05  9.01901045e+05  9.01901045e+05]
 [ 6.22677803e+05  6.22677785e+05  6.22677785e+05]
 [ 1.03428120e+06  1.03428122e+06  1.03428122e+06]
 [-1.19305574e+06 -1.19305571e+06 -1.19305571e+06]
 [-1.96043215e+06 -1.96043217e+06 -1.96043217e+06]
 [ 7.59448136e+05  7.59448100e+05  7.59448100e+05]
 [ 1.03354514e+06  1.03354517e+06  1.03354517e+06]
 [-1.73927272e+05 -1.73927299e+05 -1.73927299e+05]
 [-5.24351807e+05 -5.24351822e+05 -5.24351822e+05]
 [ 1.62019447e+06  1.62019446e+06  1.62019446e+06]
 [ 1.38662470e+06  1.38662474e+06  1.38662474e+06]
 [ 1.28671960e+06  1.28671961e+06  1.28671961e+06]
 [-1.06839751e+06 -1.06839752e+06 -1.06839752e+06]
 [-1.98996438e+05 -1.98996466e+05 -1.98996466e+05]
 [-1.23619534e+06 -1.23619535e+06 -1.23619535e+06]
 [-2.19527250e+06 -2.19527253e+06 -2.19527253e+06]
 [-1.38477474e+06 -1.38477473e+06 -1.38477473e+06]
 [ 1.07856521e+05  1.07856522e+05  1.07856522e+05]
 [-1.04683970e+06 -1.04683969e+06 -1.04683969e+06]
 [ 2.47153834e+05  2.47153863e+05  2.47153863e+05]
 [ 3.31417432e+05  3.31417432e+05  3.31417432e+05]
 [-4.39462478e+05 -4.39462505e+05 -4.39462505e+05]
 [-2.92579357e+05 -2.92579327e+05 -2.92579327e+05]
 [-5.59099830e+05 -5.59099831e+05 -5.59099831e+05]
 [ 8.56624244e+05  8.56624241e+05  8.56624241e+05]
 [-9.53921074e+05 -9.53921083e+05 -9.53921083e+05]
 [-1.96241069e+06 -1.96241069e+06 -1.96241069e+06]
 [ 1.61149320e+05  1.61149289e+05  1.61149289e+05]
 [ 2.60256869e+05  2.60256871e+05  2.60256871e+05]
 [ 8.38669976e+05  8.38669958e+05  8.38669958e+05]]
</details>

## Versions and main components

* PyMC3 Version: v3.9.3
* Aesara/Theano Version: v1.0.5
* Python Version: 3.7.10 
* Operating system: NixOS
* How did you install PyMC3: (conda/pip) Nix shell

(I couldn't repro on a more recent version because of https://github.com/pymc-devs/pymc3/issues/4950.)

**Comment by ricardoV94** [comment]
You are probably hitting numerical precision issues with those huge covariances. Don't you get warnings during sampling?

Otherwise, the general advice is to always to scale variables into reasonable scales.

**Comment by colehaus** [comment]
Ahh, thanks so much! Bumping up the tuning steps quite a bit seems to resolve the problem. I hadn't tried that yet because my original use case (before shrinking it down for the bug report) was `find_map`. I guess I'll have to abandon the speed of `find_map` and just look at the full posterior. Thanks again.
