### ISSUE TITLE
Aesara 2.2.0 release broke tests on `main`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4961]
## Description of your problem

The recent merge of #4955 broke lots of tests on `main`:
https://github.com/pymc-devs/pymc3/actions/runs/1153556997

The authors & reviewers of #4955 are not to blame though, because over there the CI was green ✔ on 2021-08-19T17-33Z.

At 2021-08-19T19-37Z (two hours later) however a new [Aesara version 2.2.0](https://github.com/aesara-devs/aesara/releases/tag/rel-2.2.0) was released.

The next CI run was on `main` after the merge and blew up.`

The automated PR #4960 has a red CI because of this.

## Versions and main components

* PyMC3 Version: `main`
* Aesara/Theano Version: `2.2.0`

**Comment by twiecki** [comment]
I suppose the question is whether it's an intentional API breakage (in which case we need to fix PyMC3) or an apsara issue.

**Comment by michaelosthege** [comment]
There are tons of failures in the CI, so I don't know if it's the only breakage, but this quote from the release notes definitely has a lot of consequences:
> TensorConstant is now a subclass of TensorVariable
>
>    Code that was previously using isinstance(..., TensorVariable) as a means of filtering out TensorConstants will need to be updated

**Comment by twiecki** [comment]
So we probably need to go through our `isinstance` checks.

**Comment by michaelosthege** [comment]
quick fix to pin the version <2.2.0 so we don't stall out the other PRs?

**Comment by twiecki** [comment]
Good idea.
