### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'A_structure' when importing pymc3

### ISSUE THREAD

**Issue by falkeura** [pymc-devs/pymc#4966]
## Description of your problem

I'm using this container: https://hub.docker.com/r/pymc/pymc3 on an M1 MacBook.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
You are running the v4 development version of PyMC3 which currently still lacks key features. You probably want to use the stable v3 instead which you can either install via conda or find on the v3 GitHub branch: https://github.com/pymc-devs/pymc3/tree/v3
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-ba1e19314b2f> in <module>
----> 1 import pymc3 as pm
      2 
      3 #print(f"Running on PyMC3 v{pm.__version__}")

~/pymc3/__init__.py in <module>
     43 __set_compiler_flags()
     44 
---> 45 from pymc3 import gp, ode, sampling
     46 from pymc3.aesaraf import *
     47 from pymc3.backends import (

~/pymc3/gp/__init__.py in <module>
     13 #   limitations under the License.
     14 
---> 15 from pymc3.gp import cov, mean, util
     16 from pymc3.gp.gp import TP, Latent, LatentKron, Marginal, MarginalKron, MarginalSparse

~/pymc3/gp/util.py in <module>
     22 from scipy.cluster.vq import kmeans
     23 
---> 24 solve_lower = Solve(A_structure="lower_triangular")
     25 solve_upper = Solve(A_structure="upper_triangular")
     26 solve = Solve(A_structure="general")

TypeError: __init__() got an unexpected keyword argument 'A_structure'
```

</details>

**Please provide any additional information below.**

github.com/pymc-devs/pymc3/tree/v3

I've also tried installing v3 using `!python -m pip install git+https://github.com/pymc-devs/pymc3@v3` but still got the same error.

## Versions and main components

* PyMC3 Version: v4
* Aesara/Theano Version: 2.1.3/1.1.2
* Python Version: 3.9.2
* Operating system: MacOS 11.5.2 https://hub.docker.com/r/pymc/pymc3 (latest: 228c01a53746)
* How did you install PyMC3: (conda/pip) it was installed in the docker image

**Comment by michaelosthege** [comment]
Hi @falkeura,

that Docker image is outdated (3 months old) and there's probably a mixum of dependencies in your container (e.g. Theano must not be installed for working with v4).
The problem is primarily that the automated Docker builds broke and no one has looked into it yet. Relevant tickets are #4386 and #3160.

The error you mentioned also appeared on our CI pipeline 10 days ago (see #4943) but magically went away.

**Comment by ricardoV94** [comment]
@falkeura did you manage to solve this issue?

**Comment by falkeura** [comment]
Thanks for the reply! I went with a workaround of using Colab and running it in the cloud, instead of my local machine.
