### ISSUE TITLE
Remove unused `Model.__init__` kwargs without warnings

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#4981]
## Description of your problem

The two kwargs `model` and `aesara_config` of the `Model.__init__` are not accessed.

They don't have any effect, but there's also no warning or docstring about it.

## Versions and main components

* PyMC3 Version: `main`

**Comment by itsguneetsingh** [comment]
I'm a little new here. Could maybe tell me where exactly I would find the Model.__init__ (like in which directory?)

**Comment by Sayam753** [comment]
Yes. The related Model class is in `pymc3/model.py` and [here](https://github.com/pymc-devs/pymc3/blob/main/pymc3/model.py#L627-L635) are `__init__` lines.

**Comment by itsguneetsingh** [comment]
I want to try this issue. could anyone please assign me this issue?

**Comment by itsguneetsingh** [comment]
Thanks @Sayam753

**Comment by Sayam753** [comment]
Awesome. Assigned you the issue.

**Comment by itsguneetsingh** [comment]
If I have this right, I just have to delete "model" and "aesara_config" present on line no. 630 and 631. Is that it?

**Comment by Sayam753** [comment]
Yes. Along with cleanup of the docstrings would work.

**Comment by itsguneetsingh** [comment]
Hey, made some changes could you maybe have a look? https://github.com/pymc-devs/pymc3/pull/5013
