### ISSUE TITLE
Issues with BART

### ISSUE THREAD

**Issue by jonathan-taylor** [pymc-devs/pymc#4990]
## Description of your problem

Reading the PGBART code (possibly want to make a standalone implementation of https://arxiv.org/pdf/1502.04622.pdf which describes the sampler. I noticed the history variables will not act as desired because one keeps appending a list without copying it, e.g. here https://github.com/pymc-devs/pymc3/blob/d80b7f183c036b015a22576b5cfa8dee49b4d9af/pymc3/step_methods/pgbart.py#L331 

After several T iterations you will have T pointers to the same list. Similarly if you do not copy the tree you will again have T pointers to the same tree in your history.

**Please provide the full traceback.** No traceback -- not a runtime bug.

**Please provide any additional information below.**

Other comments: the paper describing the sampler uses a marginal likelihood to determine weights which I gather is not going to agree with the likelihood as implemented here. For one thing, for tree `j`, the marginal likelihood uses the residual  $R_j$ (in that paper's notation) while calls to `self.likelihood_logp` here add back in the current tree's output e.g. here https://github.com/pymc-devs/pymc3/blob/d80b7f183c036b015a22576b5cfa8dee49b4d9af/pymc3/step_methods/pgbart.py#L174 So, I can't tell that this is computing the same quantity (though it could be). This marginal likelihood should be a function of R_j, \sigma, as well as prior mean (0) and std (`mu_std`)

Not clear that the values in the nodes are ever sampled using the correct distribution, I believe they should ultimately be drawn as a posterior draw from a likelihood centered around the mean of R_{\eta,j} with prior centered at 0 with prior std of `mu_std`. And they only need to be drawn for the final tree, (Step 8 of Algorithm 1 of https://arxiv.org/pdf/1502.04622.pdf)

## Versions and main components

* PyMC3 Version: commit d80b7f183c036b015a22576b5cfa8dee49b4d
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
CC @aloctavodia

**Comment by aloctavodia** [comment]
Hi, 

I will check the history variables.  The sampler implemented in PyMC3 is not exactly the one described in that paper, but it is very closely related to that. Also our implementation of BART is not the same as the one described by Chipman or even others after that. There a few deviations from the published methods most of them intended to have a more general implementation of BART that works in the context of a PPL, and not as a stand-alone Machine-Learning type of model.  We are still testing and working on improving this implementation, and we may publish a paper providing more details.

**Comment by jonathan-taylor** [comment]
Fair enough, though given that you are not using the marginal likelihood in the weights (i.e. weights appear to depend on \mu's so the ratio of weights are ratios of densities on different dimensional spaces -- something that reversible jump MCMC is often needed for), it is not obvious to me that the stationary distribution is as described in any of the BART literature. AFAICT there are various papers that basically try to improve the tree sampling step with each implementation usually trying to sample from Chipman et al's proposal. So, it's not clear what the stationary distribution of such a sampler is. I would think a PPL would be concerned about knowing what the stationary distribution is (more so even then a stand-alone machine learning implementation...) 

In any case, there is a bug in the history -- copying a list does not freeze its state. You can see this by printing e.g. `[id(h) for h in self.expansion_nodes_history]` -- they are identical. Hence `np.all([h == self.expansion_nodes_history[0] for h in self.expansions_nodes_history]) == True`.  You could append `tuple(self.expansion_nodes)` which would freeze the state. 

The trees are also not copied so if you are relying on changes in state of the tree to record history this will also have a problem. A copy of the tree is made on `__init__` but not in storing in the history...

**Comment by aloctavodia** [comment]
You are totally right. Thanks for reporting this issue, I will solve it ASAP. I am working on other features and refactor and I will include this.
