### ISSUE TITLE
Attempting to call `Model.add_coords()` twice with same argument raises an error.

### ISSUE THREAD

**Issue by tomicapretto** [pymc-devs/pymc#4992]
## Description of your problem

If you add a coordinate whose name already exists in the model, PyMC3 attempts to compare the values of the coordinates using a `.equal()` method, which is something that we don't have in lists.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm

coords = {"groups": ["a", "b", "c"]}

model = pm.Model()
model.add_coords(coords)
model.add_coords(coords)
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
AttributeError: 'list' object has no attribute 'equals'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-d57219f0c33f> in <module>
      5 model = pm.Model()
      6 model.add_coords(coords)
----> 7 model.add_coords(coords)

~/anaconda3/envs/bmb/lib/python3.8/site-packages/pymc3/model.py in add_coords(self, coords)
   1106                 )
   1107             if name in self.coords:
-> 1108                 if not coords[name].equals(self.coords[name]):
   1109                     raise ValueError("Duplicate and incompatiple coordinate: %s." % name)
   1110             else:

AttributeError: 'list' object has no attribute 'equals'
```

</details>

## Versions and main components

* PyMC3 Version: 3.11.2
* Theano Version: 1.1.2
* Python Version: 3.8.5
* Operating system: Ubuntu 20.04.3 LTS
* How did you install PyMC3: pip

**Comment by michaelosthege** [comment]
The comparison is now done using `np.array_equal` after conversion to tuples.

https://github.com/pymc-devs/pymc/blob/4d2f3a8d5f99fc773bc0a1aad6d51e4f3f047698/pymc/model.py#L1076-L1082

This issue was closed by 8796272c6ad95c5438110831b11fe70115fe02c3.

-----

```python
model = pm.Model()
model.add_coords({"groups": ["a", "b", "c"]})
model.add_coords({"groups": [1, 2, 3, 4]})
# >>> ValueError: Duplicate and incompatible coordinate: groups.
```
