### ISSUE TITLE
MethodNotDefined: ('grad', <class 'theano.scalar.basic_scipy.GammaInc'>, 'GammaInc')

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#4999]
## Description of your problem

In trying to infer copula marginal distribution parameters alongside copula structure, I encounter the error as mentioned in the title.

**Please provide a minimal, self-contained, and reproducible example.**

Please see [this GitHub gist](https://gist.github.com/ericmjl/4fb88b6c03e6f654d1b3daf6fe172bb2) for a minimal reproducible example.

**Please provide the full traceback.**

The Gist contains the full traceback.

**Please provide any additional information below.**

I have a suspicion that this is something that should be fixed in the upcoming `aesara` library. However, I am not quite sure where to go about starting to fix this. Tagging @brandonwillard - might you have any advice here?

## Versions and main components

All of the below information are recorded at the end of the notebook [in the gist](https://gist.github.com/ericmjl/4fb88b6c03e6f654d1b3daf6fe172bb2).

* PyMC3 Version:
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
The derivative of gammainc is still not implemented. Wip can be found here: https://github.com/aesara-devs/aesara/pull/513

Closing this issue as it's already referenced on Aesara
