### ISSUE TITLE
Parametrize Binomial and Categorical distributions via logit_p

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/pymc#5005]
## Description of your problem

`Bernoulli` can take `logit_p` as an argument:

https://github.com/pymc-devs/pymc3/blob/59ce9af97f0b840f992322f33ec8dee203d7d1c0/pymc3/distributions/discrete.py#L334-L339

Could `Binomial` also take this argument?

**Comment by MarcoGorelli** [comment]
My bad, I linked to Bernoulli, `Binomial` doesn't take `logit_p`

**Comment by ricardoV94** [comment]
Yes, it could. Also categorical

**Comment by purna135** [comment]
I would like to work on this.

**Comment by ricardoV94** [comment]
> I would like to work on this.

Go ahead :)

**Comment by cluhmann** [comment]
Anything left here or can this be closed?

**Comment by ricardoV94** [comment]
> Anything left here or can this be closed?

Yeah, it's done in #5637
