### ISSUE TITLE
saving (`pickle.dump`) of a `pm.Model` fails due to `functools.partial` in v4.0

### ISSUE THREAD

**Issue by falkmielke** [pymc-devs/pymc#5012]
## saving (`pickle.dump`) of a `pm.Model` fails due to `functools.partial`

this is referring to the current development version (v4). I thought I'd post it with the partial solution below.

#### example
```python
import pymc3 as pm
import pickle

model = pm.Model()

with open('test.mdl', 'wb') as store:
    pickle.dump(model, store)

```

#### traceback

<details><summary>Complete error traceback</summary>

```python
Traceback (most recent call last):
  File "MinimalPickle.py", line 9, in <module>
    pickle.dump(model, store)
  File "/usr/lib/python3.9/pickle.py", line 1755, in _dump
    _Pickler(file, protocol, fix_imports=fix_imports,
  File "/usr/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/usr/lib/python3.9/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.9/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.9/pickle.py", line 975, in save_dict
    raise ae
  File "/usr/lib/python3.9/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.9/pickle.py", line 1002, in _batch_setitems
    save(v)
  File "/usr/lib/python3.9/pickle.py", line 578, in save
    rv = reduce(self.proto)
AttributeError: 'functools.partial' object has no attribute '__name__'

```

</details>

#### suggested solution
`functools.partial` might need to be wrapped (cf. 
http://louistiao.me/posts/adding-__name__-and-__doc__-attributes-to-functoolspartial-objects/ )
```
def wrapped_partial(func, *args, **kwargs):
    partial_func = functools.partial(func, *args, **kwargs)
    functools.update_wrapper(partial_func, func)
    return partial_func
```

...and then in pymc3/model.py/Model.__init__():
```
        self._repr_latex_ = types.MethodType(
            wrapped_partial(str_for_model, formatting="latex"), self
        )

```

NOTE: there are other occurrences of `functools.partial` which cause the same error when more components get added to the model.

## Versions and main components

* PyMC3 Version: '4.0'
* Aesara/Theano Version: '2.2.2'
* Python Version: 3.9.7
* Operating system: arch linux
* How did you install PyMC3: git pull <...> && python setup.py develop

**Comment by twiecki** [comment]
We switched to `cloudpickle` internally, try with that.

**Comment by falkmielke** [comment]
Thank you, Thomas, I will try!
