### ISSUE TITLE
Add analog of Containers in PyMC 3

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#502]
In PyMC2, we have a mechanism for being able to create a list of stochastics, which are then automatically added to the model's list of stochastics. It is useful in situations like this:

```
eta = [Normal('eta%i' % i, 0, tau_eta[i], shape=len(mchat_studies)) for i in range(3)]
```

Or more complex situations where we need to index values from a node and assign them to components of the container iteratively. I realize this will be difficult, but we'll need to be able to allow for more complex associations between multivariate nodes for a lot of applications. This will require some `scan` voodoo, but I hope we can hide much of this from the user.

**Comment by fonnesbeck** [comment]
An obvious use case here is setting up a matrix (e.g. a design/projection matrix, covariance matrix) where elements of the array are functions of other nodes in the model.

**Comment by twiecki** [comment]
I used `stack()` and `stacklist()` before for that but it ran into maximum recursion and memory issues.

**Comment by jsalvatier** [comment]
Yes, I think this will be a little bit tricky to work out.

**Comment by usptact** [comment]
This ticket is very old; is there an alternative to Container in pymc3?

**Comment by fonnesbeck** [comment]
Not really. You can use list comprehensions to create a set of variables, but they won't be block updated like they were in PyMC2.

**Comment by usptact** [comment]
@fonnesbeck I started to use T.stack to create "a list" of random variables. Is this the way to go?

E.g.
`Z = T.stack( [pm.Dirichlet('z_'+str(i)),p=rho,shape=K) for i in range(N)] )`

**Comment by fonnesbeck** [comment]
That's what I currently do, yes.

**Comment by mcavallaro** [comment]
@fonnesbeck and @usptact I didn't find this in the documentation, actually. Does the Metroplis step method update all the discrete random variables toghether, regardless whether the list comprension is used or not? And what is the advantage of using T.stack()?

**Comment by usptact** [comment]
@mcavallaro I think what T.stack() does is creates a Theano list of variables, which are then used by the PyMC3 algos. I would say, yes, depending what inference algo you use, the updates should simultaneous (except Gibbs which is by nature sequential?).

**Comment by mcavallaro** [comment]
@usptact Thanks for that, but I think that a slightly more definite answer can be really helpful ... Probably the developers can help too! @fonnesbeck I understood that pm.Metropolis does not block update. How is the update rule of a list of RVs  in pm.Metropolis, then? Element by element or all toghether (as when using a multivariate proposal) ?

**Comment by fonnesbeck** [comment]
Metropolis does not block update by default, but can be instructed to do so:

    blocked_step = Metropolis(my_blocked_vars, blocked=True)
