### ISSUE TITLE
Do we need the ability to control whether jacobian of transforms should be added to log-probablity graphs or not ?

### ISSUE THREAD

**Issue by kc611** [pymc-devs/pymc#5022]
## Description of your problem

PyMC `v4` provided us the ability to have control over whether we wanted to include the jacobian term for respective transforms to be added into the log-probability graphs using the `jacobian` argument to `logpt` function.

https://github.com/pymc-devs/pymc3/blob/53e572caa3144f77951e233f6bcca72b63084bd8/pymc3/distributions/logprob.py#L138-L139

With #4887 as of now we lose the ability to have this type of control. `aeppl` by default adds the jacobian terms and doesn't have an option to exclude them if required. 

This brings us to the current discussion, do we want to support this type of capability from PyMC side ? (which would ultimately come from `aeppl`, cc @brandonwillard @ricardoV94 ) and it's possible use cases and such.

**Comment by ricardoV94** [comment]
@aseyboldt mentioned that this is pretty useful for optimizations, such as MAP

**Comment by twiecki** [comment]
I think this should go into `aeppl`, what do you think @brandonwillard?

**Comment by brandonwillard** [comment]
This should be a feature request in AePPL.  Regardless, here's a quick implementation of such a feature: https://github.com/aesara-devs/aeppl/pull/68.

**Comment by twiecki** [comment]
Thanks @brandonwillard, closing here.
