### ISSUE TITLE
Invalid values being used for testing Beta distribution

### ISSUE THREAD

**Issue by kc611** [pymc-devs/pymc#5023]
## Description of your problem

This was pointed out in #4887 that the testing for `Beta` distribution used values that might lead to invalid combination of arguments in the following test: 

https://github.com/pymc-devs/pymc3/blob/53e572caa3144f77951e233f6bcca72b63084bd8/pymc3/tests/test_distributions.py#L1164-L1169

The values for `mu` and `sigma` are picked randomly from their respective `Domain`. However in this particular case we only have certain value pairs which are valid. In the current `v4` testing it simply returns `NaN` values for invalid cases. With #4887 we will require a new mechanism/value `Domain`s to be placed over here.

**Comment by ricardoV94** [comment]
@lucianopaz Suggested we should drop the `sigma` parameterization altogether, and use `mu + nu` instead, with `nu` being what we call `kappa` in here: https://github.com/pymc-devs/pymc3/blob/53e572caa3144f77951e233f6bcca72b63084bd8/pymc3/distributions/continuous.py#L1224

Wikipedia calls this mean + sample size: https://en.wikipedia.org/wiki/Beta_distribution#Mean_and_sample_size
This avoids the hard constraints of `sigma` that are making the tests fail (and it's also easier to work with).

**Comment by lucianopaz** [comment]
Just to add on this, from what I found this is called the mean and sample size parametrization. The advantage that it has is that the mu and nu bounds are independent from each other: mu must be in the (0, 1) interval and nu must only be positive.
