### ISSUE TITLE
MarginalSparse shouldn't use DensityDist internally

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#5024]
## Description of your problem

The `MarginalSparse` Gaussian Process uses `DensityDist` internally to compute the `marginal_likelihood` ([here](https://github.com/pymc-devs/pymc3/blob/main/pymc/gp/gp.py#L733-L756)). We should refactor that code to use a proper RandomVariable instead

## Versions and main components

* PyMC3 Version: 4.0
* Aesara/Theano Version: 2.2.2
* Python Version: 3.8.5
* Operating system: Ubuntu 18.04
* How did you install PyMC3: (conda/pip) pip

**Comment by bwengals** [comment]
This would be nice to do.  It would allow `pm.sample_posterior_predictive` to work correctly over the original input domain `X` (so, to see the fit) without the need to append an additional `gp.conditional` rv.  Is there another benefit?  

In the interest of keeping #5055 smaller, I think it should be done after that's in, or branched off of it in a separate PR.  I might be mistaken, but I think it's more of an enhancement than something broken that must be fixed before v4.  

It also makes me wonder if other GP implementations would be better refactored into `RandomVariable`s as well.

**Comment by ricardoV94** [comment]
@bwengals Are you interested in pursuing this one? Or should we add a "help wanted" label?

**Comment by michaelosthege** [comment]
Closed by #6076
