### ISSUE TITLE
Refactor `gp` submodule

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5035]
The `gp` submodule was not yet refactored for `v4`.

Here's one low-hanging fruits to start with:
+ `pymc/tests/test_gp.py::TestMarginalVsMarginalSparse::testApproximations` is fixed by changing the shape of the `p` `ndarray` that's passed into `model.logp(...)` by slicing with `[None, :]`.

Some tests are marked with an XFAIL about the `MvNormal` not being refactored yet, but meanwhile it _is_ refactored.

Also related to #5024

**Comment by twiecki** [comment]
CC @bwengals

**Comment by twiecki** [comment]
Fixed by #5055.
