### ISSUE TITLE
Adjust pre-commit step in CI to run every time, but fast fail if red

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5041]
In a glossary PR I merged yesterday the docs step ran, but the pre-commit step did not.
We can easily run the pre-commit also for PRs of new contributors.

Also we should probably fast-fail the CI if the pre-commit is red.

**Comment by michaelosthege** [comment]
Looks like this is really hard when pre-commit and tests are separate GitHub Actions workflows: https://github.com/pre-commit-ci/issues/issues/106

**Comment by ricardoV94** [comment]
Could we have the pre-commit run in each job? Would that make things easier?

**Comment by michaelosthege** [comment]
It looks like we're getting a switch to `mamba` with #5387, but to solve this issue, I'd prefer to pursue this:

> [...] combine pre-commit.yml, arviz_compat.yml and pytest.yml into the same workflow.
> Then we could fail-fast all jobs when the pre-commit doesn't pass (#5041)

quoted [my comment in #5375](https://github.com/pymc-devs/pymc/issues/5375#issuecomment-1017650388)

That'll be less steps in total and cancel/rerun would be a single click.

**Comment by michaelosthege** [comment]
I'm not sure how to interpret the docs about the `fail-fast` setting. (Asked a question in https://github.com/github/docs/issues/16401)

The trigger filters are another hurdle: They apply to the workflow but we want to run pre-commit every time. So if we include a pre-commit job in the `tests.yml` workflow, we'll have to keep the other pre-commit workflow around too.

All in all not elegant either way.

**Comment by michaelosthege** [comment]
Update: the `fail-fast` only applies to the same matrix. So we'd have to restructure everything into the same matrix, or make all jobs depend on the `pre-commit` job (delays all jobs by a few minutes).

**Comment by ricardoV94** [comment]
Second option doesn't sound so bad
