### ISSUE TITLE
Remove temporary workaround in ArviZ backend

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5042]
I noticed this line https://github.com/pymc-devs/pymc/blob/main/pymc/backends/arviz.py#L116-L118
stating that there's a temporary workaround that can be removed after the ArviZ 0.11.2 release which is available now.

## Versions and main components

* PyMC3 Version: `main`

**Comment by OriolAbril** [comment]
also update requirement file to ask for `arviz>=0.11.3`
