### ISSUE TITLE
KeyError: 'b_log__' when using sample_smc() with Simulator

### ISSUE THREAD

**Issue by arthur-e** [pymc-devs/pymc#5045]
## Description of your problem

I'm trying to use the `Simulator` class for approximate Bayesian computing. I've run into a problem when trying to use this with the SMC sampler. The problem persists for both the default kernel and the ABC kernel. The problem also persists for "identity" and "sort" summary statistics.

**Example:**

```python
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pymc3 as pm

NUM_DRAWS = 5000

def model(params, x, n = 1000):
    'Our black-box model; really, a simulator of Gaussian random vars'
    return np.random.normal(*params, n)

# Observed data
data = np.random.normal(loc = 0, scale = 1, size = 1000)

basic_model = pm.Model()
with basic_model:
    a = pm.Normal('a', mu = 0, sd = 5)
    b = pm.HalfNormal('b', sd = 1)

    sim = pm.Simulator(
        'sim', model, params = (a, b), epsilon = 1, sum_stat = 'identity',
        observed = data)
    trace = pm.sample_smc(
        draws = NUM_DRAWS, start = {'a': 1, 'b': 10})
```

**Traceback:**

```python
Traceback (most recent call last):
  File "example_ABC_Simulator.py", line 60, in <module>
    main()
  File "example_ABC_Simulator.py", line 52, in main
    trace = pm.sample_smc(
  File "/usr/local/lib/python3.8/dist-packages/pymc3/smc/sample_smc.py", line 205, in sample_smc
    results.append(sample_smc_int(*params, random_seed[i], i, _log))
  File "/usr/local/lib/python3.8/dist-packages/pymc3/smc/sample_smc.py", line 266, in sample_smc_int
    smc.initialize_population()
  File "/usr/local/lib/python3.8/dist-packages/pymc3/smc/smc.py", line 102, in initialize_population
    point = Point({v.name: init_rnd[v.name][i] for v in self.variables}, model=self.model)
  File "/usr/local/lib/python3.8/dist-packages/pymc3/smc/smc.py", line 102, in <dictcomp>
    point = Point({v.name: init_rnd[v.name][i] for v in self.variables}, model=self.model)
KeyError: 'b_log__'
```

## Versions and main components

* PyMC3 Version: 3.11.4
* Aesara/Theano Version: `Theano-PyMC==1.1.2`
* Python Version: 3.8.0
* Operating system: Ubuntu GNU/Linux 18.04
* How did you install PyMC3: (conda/pip) `pip` inside a `virtualenv`

**Comment by arthur-e** [comment]
I think the problem is related to the `start` argument to `sample_smc()`, although [it is supposed to accept a `dict` instance](https://github.com/pymc-devs/pymc/blob/main/pymc/smc/sample_smc.py#L63)... I've probably misapprehended how `start` in `sample_smc()` differs from `sample()`.

**Comment by ricardoV94** [comment]
I think your start start needs a value per particle for each variable, but you provided a single one.

**Comment by ricardoV94** [comment]
Also you might need to specify the values of b in the transformed scale, that is `b_log__`

**Comment by arthur-e** [comment]
I'm not sure how (or why) to transform `b` (scale) variable... But I did try renaming the key for the starting value:

```py
NUM_CORES = 6

trace = pm.sample_smc(
    draws = NUM_DRAWS, kernel = 'ABC', cores = NUM_CORES, parallel = True,
    start = {'a': [1] * NUM_CORES, 'b_log__': [10] * NUM_CORES})
```

I had assumed that the number of particles was equal to the number of cores, but perhaps not? I am getting an `IndexError` now that suggests...more particles than starting values?

```
Initializing SMC sampler...
Sampling 6 chains in 6 jobs
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/pythonenv/pydream/lib/python3.8/site-packages/pymc3/smc/sample_smc.py", line 266, in sample_smc_int
    smc.initialize_population()
  File "/usr/local/pythonenv/pydream/lib/python3.8/site-packages/pymc3/smc/smc.py", line 102, in initialize_population
    point = Point({v.name: init_rnd[v.name][i] for v in self.variables}, model=self.model)
  File "/usr/local/pythonenv/pydream/lib/python3.8/site-packages/pymc3/smc/smc.py", line 102, in <dictcomp>
    point = Point({v.name: init_rnd[v.name][i] for v in self.variables}, model=self.model)
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example_ABC_Simulator2.py", line 57, in <module>
    trace = pm.sample_smc(
  File "/usr/local/pythonenv/pydream/lib/python3.8/site-packages/pymc3/smc/sample_smc.py", line 196, in sample_smc
    results = pool.starmap(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

Then I tried:

```py
trace = pm.sample_smc(
    draws = NUM_DRAWS, kernel = 'ABC', cores = NUM_CORES, parallel = True,
    start = {'a': [1] * NUM_DRAWS, 'b_log__': [10] * NUM_DRAWS})
```

**And it is running now, but...** Previously, the tempering (beta) reached 1.0 quickly in 6 stages. Now, it takes 25 stages, jumps from `beta = 0` to `beta = 1` in a single stage, and produces very poor results.
```

**Comment by ricardoV94** [comment]
Yes, the number of particles is the number of draws. 

Setting all the particles to the same value is probably a very bad idea, as SMC relies on the distribution of the population of particles for its internal logic. 

By default we sample from the prior. Is there a reason why you want to specify the initial values manually?

Also note that you should specify the initial values on the respective scale. If you wanted b to start as 10, you should give `b_log__` the value of `np.log(10)`

**Comment by arthur-e** [comment]
There probably isn't a good reason to specify the initial values in a real problem. I like to do it in a toy problem like this so I can get a sense of the jumping rate or the convergence speed. Moreover, I was just confused about the API in this case, since `start` works differently here. Thanks!
