### ISSUE TITLE
Find instances of rv.logp(x) in PyMC and correct to pm.logp(rv,x)

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5051]
## Description of your problem
Scan all docs, including pymc-examples for `rv.logp()` signature and relpace with `pm.logp(rv, x)`

See https://github.com/pymc-devs/pymc/issues/5048 for an example

**Comment by ricardoV94** [comment]
Btw this also applies to `.logcdf` and to a lesser extent `.random`.

**Comment by DebadityaPal** [comment]
Does this issue still need to be worked upon? if so, I'd like to do it.

**Comment by ricardoV94** [comment]
> Does this issue still need to be worked upon? if so, I'd like to do it.

Very late reply, but yes I think it still needs to be worked out.

**Comment by mjhajharia** [comment]
@canyon289 are we maintaining backward compatibility for v3 users? if not, maybe a warning or something?

**Comment by canyon289** [comment]
We're not maintaining full backwards compatibility. There was another PR merged that made sure things didnt totally break, but this issue isnt about that.

This PR is to update references to the new usage pattern. Hope that clarifies things

**Comment by mjhajharia** [comment]
> We're not maintaining full backwards compatibility. There was another PR merged that made sure things didnt totally break, but this issue isnt about that.
> 
> This PR is to update references to the new usage pattern. Hope that clarifies things

gotcha, thanks ravin! as ricardo pointed out the other api changes we need to update, we should probably make a checklist from the release notes maybe?

**Comment by canyon289** [comment]
Checklist or issues, whatever works best for the team

**Comment by LucyJimenez** [comment]
I would like to work on this one.

**Comment by canyon289** [comment]
@LucyJimenez Assigned to you! Thank you and let us know if you need help

**Comment by OriolAbril** [comment]
This issue is now relevant only to 
* the developer guide which needs to be updated to v4 as a whole and already has an issue https://github.com/pymc-devs/pymc/issues/5346
* to the probability_distributions and pymc and aesara guides whose future will be discussed in the next docs meeting 
* and the notebooks in pymc-examples that have all their own issues there

I am therefore closing the issue
