### ISSUE TITLE
Backport `pm.logp` and related functional syntax to `v3`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5052]
## Description of your problem
To reduce the rate of users running into problems like #5048, we should backport the `pm.logp`, `pm.logcdf` etc syntax to `v3`.

While it will of course not have all the features available in `v4` (for example doing `pm.logp()` on things other than what's returned by `Distribution()`), the availability of the new syntax allow us to replace all uses of `rv.logp(x)` with forwards-compatible `pm.logp(rv, x)` (like #5051).

The actual implementation may be as simple as:
```python
def logp(rv, x):
    return rv.logp(x)
```

## Versions and main components

* PyMC3 Version: `v3.11.x`

**Comment by canyon289** [comment]
For other examples of why this cohesiveness is desirable see related issue https://github.com/pymc-devs/pymc/issues/5052 and https://github.com/pymc-devs/pymc/issues/5048

**Comment by michaelosthege** [comment]
The backport of `pm.logp` was merged to `v3` which does not automatically close issues.
