### ISSUE TITLE
Disable sampling of transformed variables from `prior_predictive`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5076]
This was added to facilitate sampling from the prior as a starting point for SMC, but with the new functions added in #4983 this is no longer needed.

https://github.com/pymc-devs/pymc/blob/6d2aa5ddebed01d81c2ab66b9d4bd02194f82508/pymc3/sampling.py#L1983-L1999

**Comment by markvrma** [comment]
I'd like to take up this issue.

**Comment by purna135** [comment]
Is it okay if I work on this?

**Comment by ricardoV94** [comment]
> Is it okay if I work on this?

Sure

**Comment by purna135** [comment]
I need some assistance in replacing the following code with `make_initial_point_fn`
https://github.com/pymc-devs/pymc/blob/e6fc2ec100dafacca4f0b9eab40661174707afcd/pymc/smc/smc.py#L179-L184

https://github.com/pymc-devs/pymc/blob/d84c71884762fb925eb7272b9d28e879399e326a/pymc/initial_point.py#L130

**Comment by ricardoV94** [comment]
You will have to change the parameters of `make_initial_point_fn` so that it is returning draws from the transformed prior. You can do that by setting the overrides dictionary so that every value variable strategy is "prior", and also switching the default from "moment" to "prior". Then you will need to make sure you call the returned function with a different seed `self.draws` times.
