### ISSUE TITLE
Implement a standardized interface for filtering RVs to jitter

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5077]
## Description of your problem
The initial point evaluation, primarily in `init_nuts` is the one and only place in the `pm.sample` control flow when we want to add jitter.
That's because the jitter needs to be seeded and initial points for decendant RVs must be conditioned on the jittered initial points of their ancestors.

In #4983 we defined a function `filter_rvs_to_jitter` that is already called by the respective code in `init_nuts`, but this function is not yet implemented.

The task for this issue is to implement an interface for all step methods, such that `filter_rvs_to_jitter` can "ask" steppers if they'd like the RVs assigned to them to be jittered.

## Versions and main components

* PyMC/PyMC3 Version: `main`

**Comment by ricardoV94** [comment]
I suggest removing this feature since it's unused for over a year now
