### ISSUE TITLE
Theano issue pymc3 with python3.3

### ISSUE THREAD

**Issue by MarcDNL** [pymc-devs/pymc#509]
I have tried to install pymc3 using:

pip install git+https://github.com/pymc-devs/pymc

When importing pymc, I am getting the error mentioned in issue#388. Apparently, there is still something conflicting between theano versions pymc3 and python 3.3. Can anyone please explain how to solve this?

**Comment by kyleam** [comment]
The above works on my end. Are you sure files from any old theano
installs were completely removed?

**Comment by MarcDNL** [comment]
I tried again. First, I've used pip to uninstall both theano and pymc. Next, I reinstalled by using the command mentioned above (pip install git+https://github.com/pymc-devs/pymc). Importing PyMC still gives an error, but a different one now ('cannot import name gof'', see below). It looks like this still relates to Theano. For completeness: I am using WinPython-64bit-3.3.3.3 on windows 8.1. 

![screen capture](https://f.cloud.github.com/assets/6962904/2430601/acbc6aa0-acf4-11e3-8656-dab9d47097e1.JPG)

**Comment by kyleam** [comment]
I won't be able to help much with Windows, but the Theano site gives
pretty detailed instructions for installing on Windows.

  http://deeplearning.net/software/theano/install.html#windows

**Comment by twiecki** [comment]
I think theano is available via anaconda -- you might have better luck using that and then pip installing only pymc3. http://continuum.io/downloads

**Comment by neuronphysics** [comment]
I am not a root user in my institute pc and I use anaconda, how could I install pymc3 on my pc without using pip?

**Comment by fonnesbeck** [comment]
Anaconda should install everything in your user directory. In fact, you can use `conda create` to specify an entire environment in your home directory for running PyMC3.
