### ISSUE TITLE
Add a Testimonials section in the website

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc#5097]
We have [this collection of testimonials](https://github.com/pymc-devs/pymc/wiki/Testimonials) that have no place in our [website](https://docs.pymc.io/). 

I propose adding them to the front page, using the [card carrousel](https://sphinx-design.readthedocs.io/en/latest/cards.html) feature of sphinx-design. Each individual testimonial would be inside a card.

**Comment by twiecki** [comment]
I like that, some more testimonials would help too.

**Comment by Donnyvdm** [comment]
I'll pick up this issue (PyMC sprint @ pydataglobal)
