### ISSUE TITLE
Update installation docs on project wiki

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#5101]
- [ ] https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Linux) and others
- [ ] https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(MacOS)
- [ ] https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Windows)
Is a bit outdated, need to take care of it once we make v4 release

**Comment by fonnesbeck** [comment]
I can work on some of these. Just picked up a Windows machine.

Makes sense to divide the guides into two sections for the time being: v3 and v4 installation.

**Comment by fonnesbeck** [comment]
I've updated the Windows instructions with something that works on my machine. However, resulting installations generate the NumPy BLAS warning for both v3 and v4, despite MKL being installed.

**Comment by flimao** [comment]
I was able to get rid of the NumPy BLAS warning in Windows by creating a file called `.theanorc` in the Home Folder (`C:\Users\<USER>\.theanorc`), like so:

```shell
[blas]
ldflags = -LC:\ProgramData\Anaconda3\Library\bin -lmkl_intel_thread -lmkl_core -lpthread -lm
```

and restarting my Anaconda Prompt.

I'm using:
* Windows 10
* Python 3.9.7
* PyMC 3.11.4

**Comment by fonnesbeck** [comment]
@flimao very cool! I'm using Miniforge, so the above works even without the bin path for Anaconda. Can you see if it works without that as well? Would be nice if users don't have to customize it.

**Comment by flimao** [comment]
It does work for me too!

**Comment by twiecki** [comment]
Interesting, so it seems that by default it's not compiling using MKL, even if it's installed. That's an aesara issue then I'd say.

**Comment by percevalve** [comment]
HI There,

Tested the PyMC4 installation on Mac for both M1 and Intel, small typo (corrected) but all works.
Also tested and copied the instruction for Linux (Debian)

**Comment by twiecki** [comment]
@percevalve Great, thanks for reporting back. So for Intel you installed with MKL then?

**Comment by amrith8** [comment]
I just went through the windows installation guide and it works fine for both V3 and V4 installation. 

I'm using:

- Windows 10
- Python 3.8.5
- conda 4.10.1

**Comment by flimao** [comment]
I'm not sure if this is the right place for it, but here goes:

Upon following the install instructions for Windows and PyMC3, I find that the resulting conda environment crashes the Python kernel without any error messages every time I plot any sort of graph.

Just a heads-up: apparently this is a [bug](https://github.com/matplotlib/matplotlib/issues/21511) in `matplotlib`. For me the solution was to downgrade the `freetype` package from 2.11.0 to 2.10.4.

**Comment by mjhajharia** [comment]
I have added the sprint label to this issue but we probably need to make the issue description clear and divide it into sub issues
