### ISSUE TITLE
pm.OrderedProbit bug

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#5103]
So the new `pm.OrderedProbit` looks great. I've been trying to work through some examples and I've noticed a mismatch between the docstring and the working of the function. In the docstring it states that you can provide a `sigma` kwarg (i.e. "The standard deviation of probit function"). However when trying to do a simple example, this errors out. Example...

```python
import pymc3 as pm
import seaborn as sns

samples = pm.OrderedProbit.dist(cutpoints=[-2, 0, 1, 2], eta=0, sigma=1).random(size=500)
sns.countplot(x=samples, color='C0');
```

but it errors with
```
TypeError: __init__() got an unexpected keyword argument 'sigma'
```

So basically the `pm.OrderedProbit` doesn't yet do what it states in the docstring. Taking a look at the code, it looks like the function does not have `sigma` as a kwarg and doesn't do anything with `sigma`.

Version details...
```
Python implementation: CPython
Python version       : 3.9.7
IPython version      : 7.28.0

theano: 1.1.2
xarray: 0.19.0

pandas    : 1.3.4
theano    : 1.1.2
arviz     : 0.11.4
pymc3     : 3.11.2
seaborn   : 0.11.2
matplotlib: 3.4.3
numpy     : 1.21.3
```

**Comment by ricardoV94** [comment]
It seems a sigma should go in these lines (main branch):

https://github.com/pymc-devs/pymc/blob/0a172c87e39ee64bf5101a5887281ad6548e6ea4/pymc/distributions/discrete.py#L1772-L1774

Intead of those `0, 1` in the cdf function, it would be `0, sigma`
