### ISSUE TITLE
Exception: ('Compilation failed (return status=1)

### ISSUE THREAD

**Issue by kuvychko** [pymc-devs/pymc#5107]
### Summary  
I just installed pymc3, following latest instructions from [here](https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Windows)), using coda and pip. Installation proceeded with no issues, but when I try to create a model I first get this warning:

```import pymc3 as pm

with pm.Model() as model:
    alpha = 1.0/count_data.mean()  # Recall count_data is the
                                   # variable that holds our txt counts
    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)
    
    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data - 1)

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

Then when I try to run the model I get this exception. It looks like Theano is not compiling correctly. I looked online and tried a bunch of things but I keep getting this error.

```
with model:
    idx = np.arange(n_count_data) # Index
    lambda_ = pm.math.switch(tau > idx, lambda_1, lambda_2)

You can find the C code in this temporary file: C:\Users\kuvychko\AppData\Local\Temp\theano_compilation_error_49a3or71
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19904/1411181576.py in <module>
      1 with model:
      2     idx = np.arange(n_count_data) # Index
----> 3     lambda_ = pm.math.switch(tau > idx, lambda_1, lambda_2)

~\Anaconda3\envs\pymc3\lib\site-packages\theano\tensor\var.py in __gt__(self, other)
     39 
     40     def __gt__(self, other):
---> 41         rval = theano.tensor.basic.gt(self, other)
     42         rval._is_nonzero = False
     43         return rval

~\Anaconda3\envs\pymc3\lib\site-packages\theano\graph\op.py in __call__(self, *inputs, **kwargs)
    251 
    252         if config.compute_test_value != "off":
--> 253             compute_test_value(node)
    254 
    255         if self.default_output is not None:

~\Anaconda3\envs\pymc3\lib\site-packages\theano\graph\op.py in compute_test_value(node)
    124 
    125     # Create a thunk that performs the computation
--> 126     thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
    127     thunk.inputs = [storage_map[v] for v in node.inputs]
    128     thunk.outputs = [storage_map[v] for v in node.outputs]

~\Anaconda3\envs\pymc3\lib\site-packages\theano\graph\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    632             )
    633             try:
--> 634                 return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
    635             except (NotImplementedError, MethodNotDefined):
    636                 # We requested the c code, so don't catch the error.

~\Anaconda3\envs\pymc3\lib\site-packages\theano\graph\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    598                 print(f"Disabling C co
[theano_compilation_error_49a3or71.txt](https://github.com/pymc-devs/pymc/files/7431095/theano_compilation_error_49a3or71.txt)
de for {self} due to unsupported float16")
    599                 raise NotImplementedError("float16")
--> 600         outputs = cl.make_thunk(
    601             input_storage=node_input_storage, output_storage=node_output_storage
    602         )

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\basic.py in make_thunk(self, input_storage, output_storage, storage_map)
   1201         """
   1202         init_tasks, tasks = self.get_init_tasks()
-> 1203         cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1204             input_storage, output_storage, storage_map
   1205         )

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\basic.py in __compile__(self, input_storage, output_storage, storage_map)
   1136         input_storage = tuple(input_storage)
   1137         output_storage = tuple(output_storage)
-> 1138         thunk, module = self.cthunk_factory(
   1139             error_storage,
   1140             input_storage,

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\basic.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map)
   1632             for node in self.node_order:
   1633                 node.op.prepare_node(node, storage_map, None, "c")
-> 1634             module = get_module_cache().module_from_key(key=key, lnk=self)
   1635 
   1636         vars = self.inputs + self.outputs + self.orphans

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\cmodule.py in module_from_key(self, key, lnk)
   1189             try:
   1190                 location = dlimport_workdir(self.dirname)
-> 1191                 module = lnk.compile_cmodule(location)
   1192                 name = module.__file__
   1193                 assert name.startswith(location)

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\basic.py in compile_cmodule(self, location)
   1541             try:
   1542                 _logger.debug(f"LOCATION {location}")
-> 1543                 module = c_compiler.compile_str(
   1544                     module_name=mod.code_hash,
   1545                     src_code=src_code,

~\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2544             # difficult to read.
   2545             compile_stderr = compile_stderr.replace("\n", ". ")
-> 2546             raise Exception(
   2547                 f"Compilation failed (return status={status}): {compile_stderr}"
   2548             )

Exception: ('Compilation failed (return status=1): C:\\Users\\kuvychko\\AppData\\Local\\Temp\\ccNwfwin.s: Assembler messages:\r. C:\\Users\\kuvychko\\AppData\\Local\\Temp\\ccNwfwin.s:100: Error: invalid register for .seh_savexmm\r. ', 'FunctionGraph(Elemwise{gt,no_inplace}(<TensorType(int64, (True,))>, TensorConstant{[ 0  1  2 ..71\n 72 73]}))')</summary>
```
### Excerpt from the C code log file referenced in the error message
```
===============================
Problem occurred during compilation with the command line below:
"C:\Users\kuvychko\Anaconda3\envs\pymc3\Library\mingw-w64\bin\g++.exe" -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wno-c++11-narrowing -march=knl -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mavx512f -mno-avx512er -mavx512cd -mno-avx512pf -mno-prefetchwt1 -mclflushopt -mxsavec -mxsaves -mavx512dq -mavx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mclwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=16896 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Users\kuvychko\Anaconda3\envs\pymc3\lib\site-packages\numpy\core\include" -I"C:\Users\kuvychko\Anaconda3\envs\pymc3\include" -I"C:\Users\ivkuvych\Anaconda3\envs\pymc3\lib\site-packages\theano\link\c\c_code" -L"C:\Users\ivkuvych\Anaconda3\envs\pymc3\libs" -L"C:\Users\kuvychko\Anaconda3\envs\pymc3" -o "C:\Users\ivkuvych\AppData\Local\Theano\compiledir_Windows-10-10.0.19042-SP0-Intel64_Family_6_Model_85_Stepping_7_GenuineIntel-3.9.7-64\tmp2ek9r7vj\mc1f4d5aa16af0197cc70b7bc597a62d848acd658b811a4198cff42bb584d9a62.pyd" "C:\Users\kuvychko\AppData\Local\Theano\compiledir_Windows-10-10.0.19042-SP0-Intel64_Family_6_Model_85_Stepping_7_GenuineIntel-3.9.7-64\tmp2ek9r7vj\mod.cpp" -lpython39C:\Users\kuvychko\AppData\Local\Temp\ccNwfwin.s: Assembler messages:

C:\Users\kuvychko\AppData\Local\Temp\ccNwfwin.s:100: Error: invalid register for .seh_savexmm
```

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* Aesara/Theano Version: theano-pymc-1.1.2
* Python Version: 3.9.7
* Operating system: Windows 10
* How did you install PyMC/PyMC3: (conda/pip) conda + pip, currently recommended method

**Comment by fonnesbeck** [comment]
Can you post a complete example? The snippet you've posted does not appear to be a complete model. I'm able to run what you have posted on my Windows setup,  but its not really doing anything.

**Comment by kuvychko** [comment]
It's from the 1st chapter of [Probabilistic Programming
and Bayesian Methods for Hackers](https://nbviewer.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb). I just installed pymc3 on a different Windows 10 machine, and everything is working. I'm still getting this Theano warning though: 
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```
But I can run the notebook with no faults. The only difference during install was that I ran Anaconda Prompt as the administrator. I'm checking if I can do the same on my work machine, I'll update on the results.

**Comment by kuvychko** [comment]
Unfortunately no luck on my work machine, I'm getting a similar error in the same place:
```
Exception: ('Compilation failed (return status=1): C:\\Users\\kuvychko\\AppData\\Local\\Temp\\ccKMbeBr.s: Assembler messages:\r. C:\\Users\\kuvychko\\AppData\\Local\\Temp\\ccKMbeBr.s:100: Error: invalid register for .seh_savexmm\r. ', 'FunctionGraph(Elemwise{gt,no_inplace}(<TensorType(int64, (True,))>, TensorConstant{[ 0  1  2 ..71\n 72 73]}))')
```
Any recommendation on how to fix this or next steps to try? It looks like it has something to do with access control. I do want to use pymc3 for work, so if I cannot fix this issue I won't be able to use pymc3... Thanks for the help!!

**Comment by fonnesbeck** [comment]
I'm not able to reproduce this error on my system (Win11 on 11th gen core i7). I'm just running the notebook that you link to in VSCode using the Jupyter extension and the kernel that gets installed via the install instructions. You should not have to be doing anything as an administrator. 

I would avoid using the Anaconda Prompt (in fact, I would recommend using Miniforge instead of Anaconda, as it pull everything from conda-forge by default). Best to just use Powershell, in non-administrator mode. Can you try a clean install there?

One other alternative you may have is to run it under WSL2.

**Comment by kuvychko** [comment]
Thanks Chris, I'll try Powershell. I haven't tried using Jupyter extension for VSCode, but that was on my to-do list anyway, so if Powershell route fails I'll try that. WSL2 will be the option of last resort. I'll post on the progress (and hopefully solution).

**Comment by fonnesbeck** [comment]
The only ongoing issue I have is getting the BLAS warning to go away. 

For everyday use WSL2 is really the way to go. It integrates seamlessly with VSCode which makes it very nice, and keeps all my Python dev stuff in the same container. I realize we want to have Windows installing easier and more reliably, but even when it does, I will continue to use WSL primarily.

**Comment by kuvychko** [comment]
Powershell solution didn't work. I'll try WSL2, but that will take me some time. As I want to use pymc3 for work, with the ultimate goal for it to be adopted by other folks these complications are really unfortunate. I hope your team will release pymc4 in a not too distant future (I can make tensorflow and tensorflow-probability run just fine). Using tensorflow-probability directly looks way way harder than pymc3, so I'll try to power through the install issues. Let me know if you'd like me to close this issue for now (it will take me a couple of weeks before I get to WSL2 test). Thanks again for your help!

**Comment by kuvychko** [comment]
WSL2 path worked like a charm, BLAS warning went away too. Thanks for the help Chris, I really appreciate it!

Here are detailed WSL2/Windows 10 install instructions with some helpful links, in case anybody else runs into this issue.

1. Install WSL2. Open PowerShell in Admin mode, and run `wsl --install`.
	a. After initial install is done, reboot your computer per message. Install will continue upon restart. This part will take ~5min or so. Follow prompts, make sure to setup and save your UNIX username and password. For details, see:  https://docs.microsoft.com/en-us/windows/wsl/install 
	b. Optional - check best practices for WSL2: https://docs.microsoft.com/en-us/windows/wsl/setup/environment#set-up-your-linux-user-info 
2. Install Windows Terminal from Windows Store.
	a. Modify settings.json for Windows Terminal to set appropriate home directory for WSL2 (Ubuntu): https://goulet.dev/posts/how-to-set-windows-terminal-starting-directory/
	b. To figure out location of WSL2 home directory, run `explorer.exe .` in your Ubuntu shell (note: period is important).
3. Install miniconda:  https://docs.conda.io/en/latest/miniconda.html#linux-installers (Python 3.9 Miniconda3 Linux 64-bit).
4. Create a new Python environment for pymc3 and activate it
	a. Install pymc3 using recommended method: `conda install -c conda-forge pymc3 mkl-service`
			i. See: https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Linux) 
	b. Install g++: `sudo apt-get install g++`: https://developpaper.com/installation-method-of-theano-and-keras-in-ubuntu-system/
	c. Install jupyter and any other packages needed
		i. To run Jupyter in WSL, run: `jupyter notebook --no-browser`, then Control-click on the URL displayed in the Terminal. For details, see: https://towardsdatascience.com/configuring-jupyter-notebook-in-windows-subsystem-linux-wsl2-c757893e9d69
