### ISSUE TITLE
Remove load_trace and save_trace functions

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5108]
There are deprecation warnings about this for 2 years: https://github.com/pymc-devs/pymc/pull/3902 We should remove them for 4.0.

**Comment by twiecki** [comment]
There are a few more here: https://github.com/pymc-devs/pymc/pull/5109

**Comment by ariepratama** [comment]
hi @twiecki! I might be able to work on this issue 😄 


do I need to add examples onto the documentation too? on how to save and load using arviz?
