### ISSUE TITLE
Create more issue type templates?

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymc#5119]
Currently these are the available templates for creating an issue:

![Screen Shot 2021-10-30 at 19 09 54](https://user-images.githubusercontent.com/6120897/139559870-d09a7e96-9398-4d1c-bad4-09f1b62e1085.png)

But many of our open issues are about other things, like documentation, feature requests or enhancements. When creating this issue, for example, I selected the bug report and just deleted the whole template and started typing on an empty textbox. 

I propose creating templates for:
- Documentation
- Feature requests

So far, I'm thinking just a basic two step template: describe the issue and describe the proposed solution. More ideas are welcome!

**Comment by michaelosthege** [comment]
Issue template types we should add:
+ Feature request (needs motivation, possibly implementation proposal)
+ Maintenance ToDo (needs motivation, todo-list)
+ Question? (direct people to Discussions or Discourse)

**Comment by michaelosthege** [comment]
Closed by #6327

**Comment by ricardoV94** [comment]
We need an issue for development/ feature request

**Comment by michaelosthege** [comment]
> We need an issue template for development/ feature request. None of the current ones fit.

@ferrine added one, but GitHub doesn't like it: https://github.com/pymc-devs/pymc/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml

not sure why

**Comment by ricardoV94** [comment]
Should we revert or someone wants to fix it soon?
