### ISSUE TITLE
Installing Jupyter Lab on pymc3_env

### ISSUE THREAD

**Issue by jago2216** [pymc-devs/pymc#5122]
Hello,
I recently created a pymc3 conda environment using the following command in terminal:
conda create -c conda-forge -n pymc3_env python=3.9 pymc3 theano-pymc mkl mkl-service
However, when I try to install Jupyter Lab or Jupyter Notebook on this environment it fails to install.

Any suggestions on how to fix this?

Thanks,
Jeff
**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
[The complete error output here]
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 3
* Aesara/Theano Version: theano-pymc
* Python Version: 3.9
* Operating system: MacOS Mojave
* How did you install PyMC/PyMC3: conda

**Comment by MarcoGorelli** [comment]
>  it fails to install

Hi - can you show your output please?

**Comment by bwengals** [comment]
Also, if necessary you can take a look in [this directory](https://github.com/pymc-devs/pymc/tree/main/conda-envs) for working conda environments that you can use for trying pymc out in a fresh environment.  Best to refer to the [installation instructions](https://github.com/pymc-devs/pymc#installation) though.

```bash
conda env create -f windows-environment-test-py38.yml
```

Also, I'd recommend installing jupyterlab into your `base` conda environment, and then adding the conda environment to it as a kernel.  You can follow the instructions in the [answer here](https://stackoverflow.com/a/53546634).  This way you have one reusable and stable jupyterlab configuration.

```bash
conda activate pymc-dev-py38
(pymc-dev-py38)$ conda install ipykernel
(pymc-dev-py38)$ ipython kernel install --user --name=pymc-dev-py38
(pymc-dev-py38)$ conda deactivate
(base)$ jupyter lab  ## you should see an option to launch a notebook in the pymc-dev-py38 conda env
```
