### ISSUE TITLE
Remove deprecated functions

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5124]
Throughout the code-base there are quite a few things we deprecated a while ago and should remove for 4.0. Here are a few: https://github.com/pymc-devs/pymc/pull/5109

But in general, searching for `DeprecationWarning` or `FutureWarning` should bring those up.

**Comment by farhanreynaldo** [comment]
I would like to work on this issue.

**Comment by twiecki** [comment]
Great, it's yours!
