### ISSUE TITLE
Remove EllipticalSlice for V4

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5137]
This step method has not been refactored yet:

https://github.com/pymc-devs/pymc/blob/3cc457ba10188f80d6c3829ae1a7713c41cf2aac/pymc3/step_methods/elliptical_slice.py#L103

**Comment by ghost** [comment]
Since this is something we are simply not carrying over to v4, I don't think we need to deprecate it (since it won't work and we aren't going to port it). So this will be a removal, rather than a deprecation.
