### ISSUE TITLE
Add support for nightly builds

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5144]
Seems like that's quite straight-forward: https://github.com/aesara-devs/aesara/pull/656

**Comment by twiecki** [comment]
@dfm Are you interested in helping set this up?

**Comment by dfm** [comment]
@twiecki: I'm a little up to my eyeballs for the next 2 weeks, but I'd be happy to submit a PR after that. The aesara workflow is all a little hacky (see e.g. https://github.com/aesara-devs/aesara/pull/700), but something similar would be easy enough to set up here.

**Comment by theorashid** [comment]
I am on this
