### ISSUE TITLE
Mention missing features in beta1 release

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5149]
We should look at the milestones for beta2 and V4, for a comprehensive list of missing features and write them in the migration guide or release notes.

From the top of my mind the following are not working yet:

- Cholesky* dists
- Mixtures
- Timeseries
- find_MAP
- Variational inference
- GPs
- EllipticalSlice
- BaseStochasticGradient
- sample_predictive_w
- Probably more...

Otherwise we will have a lot of people opening unnecessary issues

**Comment by michaelosthege** [comment]
And ideally we should link these tickets right in the exception message.
