### ISSUE TITLE
Deprecate `assert_negative_support`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5162]
In a lot of distributions we have a call to `assert_negative_support` which in V4 is not doing anything because we are not using the output anywhere:

https://github.com/pymc-devs/pymc/blob/bdd4d1992f11cab9202774b14b8044ddf0cb7674/pymc/distributions/continuous.py#L200-L203

https://github.com/pymc-devs/pymc/blob/bdd4d1992f11cab9202774b14b8044ddf0cb7674/pymc/distributions/continuous.py#L841-L851

But we might not want to use this as is, see https://github.com/aesara-devs/aeppl/issues/84

In V3 it seems this was doing some hackish test: https://github.com/pymc-devs/pymc/blob/c332f8c957bb2ebaf346832f440e5ee94b65026a/pymc3/distributions/continuous.py#L120-L138

Should we just remove the call? If we want to do the kind of V3 check era we should probably do it properly by adding domain information to the RandomVariables instead of doing the -1e-6 logp test.

**Comment by ricardoV94** [comment]
I think it's time to just remove those lines. All our logp/logcdf methods should assert for domain constraint (and our tests check this as long as the parameter domains are properly defined)

What we were doing in V3 was a bit costly as well: call `pm.logp(parameter, -1e-6).eval()` (equivalent with tag.test_value) and check if it's not ninf.

**Comment by OriolAbril** [comment]
The `no_assert` arguments still present in some distributions should also be removed.

**Comment by vitaliset** [comment]
Me and @pibieta are working on this issue.
#DataUmbrellaPyMCSprint
Cc: @reshamas

**Comment by aloctavodia** [comment]
closed by #5963
