### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by MaxLewter16** [pymc-devs/pymc#5183]
## Description of your problem

Hello! I have installed pymc3 in a conda environment on python 3.8 because I need to also use the matlab engine. I have been having installation difficulties for a while now and this is my most recent one using a basic tutorial. It involves receiving a "Compilation Failed (return status=1)" error. 
![image](https://user-images.githubusercontent.com/56984396/141702291-ec05665c-69c0-4d9e-b1a4-a17649063f47.png)

Warning Error:
![image](https://user-images.githubusercontent.com/56984396/141702324-333bd948-9171-4bd9-b46c-741960da72c1.png)

Traceback Error:
![image](https://user-images.githubusercontent.com/56984396/141702349-2f75b18c-bc7c-4456-853a-1e6d7d583262.png)
![image](https://user-images.githubusercontent.com/56984396/141702383-d5999e37-10ac-498e-995d-b535504130b7.png)
![image](https://user-images.githubusercontent.com/56984396/141702418-410b4365-91ae-4026-81f6-fbb8b3b3346a.png)

I believe this may be an issue with Theano or compilers although I used Anaconda for part of the setup which I thought was supposed to take care of it. I am a novice and as such apologize if this is a simple solution or something that I am missing. 

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* Aesara/Theano Version: theano-pymc 1.1.2
* Python Version: 3.8.12
* Operating system: Windows 10 
* How did you install PyMC/PyMC3: (conda/pip) I installed using the recommended conda environment setup on github followed by a pip install of pymc3

**Comment by KTada777** [comment]
Perhaps the information in the following link (MSYS2's latest compilers installation and path settings) might be helpful. 
https://github.com/pymc-devs/pymc/issues/4937#issuecomment-988466747
If it works, please report the CPU you are using.

**Comment by michaelosthege** [comment]
I'm cleaning up the open issues.. This one is about the old version, and is most likely an installation problem.

The compilation failed error can happen if there are bugs in seldom used Ops, but the example above is a really simple model, so this is not the problem here.

Generally with these issues: delete the conda environment and create a new one following the installation instructions.
