### ISSUE TITLE
Include results of `sampling_jax` workflow on codecov coverage

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5195]
The results of `sampling_jax` workflow are not included in the codecov report. Not sure if it's possible to combine reports from different workflows... would be great if we could.

**Comment by Saransh-cpp** [comment]
Hi @ricardoV94! I am new to `pymc`, can I take up this issue?

I think we can -
- upload the `xml` coverage file from `jaxtests.yml` as an artifact using the [upload-artifact](https://github.com/actions/upload-artifact) workflow.
- download the artifact in `pytest.yml` using [action-download-artifact](https://github.com/dawidd6/action-download-artifact) (as the traditional `download-artifact` workflow provided by GitHub does not allow accessing artifacts from another workflow, which is our case).
- combine this downloaded file with the rest of the coverage reports.
- and upload it to codecov.

**Comment by ricardoV94** [comment]
CC @OriolAbril

**Comment by OriolAbril** [comment]
I think codecov should be able to receive all reports independently and combine them on their end. I'll try it out as that would require much less maintenance on our end going forward, it it were not to work then let's go with @Saransh-cpp proposal
