### ISSUE TITLE
`n`/`p` parametrization missing from ZeroInflatedNegativeBinomial

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5196]
The NegativeBinomial has this alternative parametrization. We should add it to the ZeroInflated version.

**Comment by farhanreynaldo** [comment]
I am interested in working on this issue. Are we basically just need to add arguments identical to the `NegativeBinomial` and create corresponding tests for these new arguments?

We should also update the docstring accordingly.

**Comment by ricardoV94** [comment]
> I am interested in working on this issue. Are we basically just need to add arguments identical to the `NegativeBinomial` and create corresponding tests for these new arguments?
> 
> We should also update the docstring accordingly.

Yes that's pretty much it
