### ISSUE TITLE
Create a GH Action to update pinned `aeppl` version every time there's a new release

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5204]
## Description of your problem
Every now and then we need to pin/unpin Aesara and aeppl versions, because something breaks (#5194 #5203 #4963).

Instead of that manual work can't we just keep the version pinned and have a bot open a new PR every time there's a new release?

Then we don't break main, but can swiftly upgrade if there are no blockers.

@twiecki @MarcoGorelli you strike me as the GitHub robot tamers around here. Can you help out?

**Comment by twiecki** [comment]
Good idea, I don't know how to do that though.

**Comment by MarcoGorelli** [comment]
I wouldn't know either, I'm afraid - though seeing as Aesala / aeppl releases are owned by the same team, I'd suggest that the manual process would be enough?
