### ISSUE TITLE
Run test suite on Python `3.10`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5209]
We should run our tests in Python `3.10` to see if anything is broken or dependencies are missing

**Comment by 5hv5hvnk** [comment]
Hi, do we have to run tests from pymc/tests 
``` pytest --cov=pymc pymc/tests/<name of test>.py```
with python3.10 and updated version of requirements?

**Comment by ricardoV94** [comment]
> Hi, do we have to run tests from pymc/tests 
> ``` pytest --cov=pymc pymc/tests/<name of test>.py```
> with python3.10 and updated version of requirements?

You would need to replace the py37 environments here and create a new ones with py310

https://github.com/pymc-devs/pymc/tree/main/conda-envs

Then in the workflows bump the conda environment files by 1. For instance here it would become py38: https://github.com/pymc-devs/pymc/blob/8b063f9c3b344753acdf91416cf2bb3c4533f80a/.github/workflows/pytest.yml#L138-L145

here py39:
https://github.com/pymc-devs/pymc/blob/8b063f9c3b344753acdf91416cf2bb3c4533f80a/.github/workflows/pytest.yml#L223-L230

and here py310:
https://github.com/pymc-devs/pymc/blob/8b063f9c3b344753acdf91416cf2bb3c4533f80a/.github/workflows/arviz_compat.yml#L71-L78

There might be other places in the worflows that need updating, and probably in this file: https://github.com/pymc-devs/pymc/blob/main/setup.py

@michaelosthege might be able to spot other things I am missing

**Comment by michaelosthege** [comment]
Are Aesara and aeppl already testing on 3.10?
If not that should be the first step.

Also to not increase our CI resource use by a third, I think we should first combine the workflows and reorganize the test suite. Then we can more easily split the load across Python versions.

**Comment by ricardoV94** [comment]
> Are Aesara and aeppl already testing on 3.10?
> If not that should be the first step.

~~I think they are. Aesara for sure, Aeppl doesn't matter as it relies on Aesara alone~~

> Also to not increase our CI resource use by a third, I think we should first combine the workflows and reorganize the test suite. Then we can more easily split the load across Python versions. 

Why increase by a third? I would just bump everything one version up and drop the 3.7, which is no longer supported by numpy anyway.

**Comment by ricardoV94** [comment]
Correction, Aesara seems to test only 3.7-3.9

**Comment by ricardoV94** [comment]
For reorganizing the test suite, there's a somewhat related discussion here: https://github.com/pymc-devs/pymc/discussions/5579

**Comment by 5hv5hvnk** [comment]
@ricardoV94  I created a new environment for python3.10, did the expected changes in pytest.yml file and executed the script to run tests, the output was very similar to [comment](https://github.com/pymc-devs/pymc/discussions/5579#discussioncomment-2394270)

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/17161999/159351903-805e30e5-3159-4325-b86b-8fefc6305e79.png">


Should I try rename the tests in a manner as mentioned in [#5579](https://github.com/pymc-devs/pymc/discussions/5579) ?

**Comment by michaelosthege** [comment]
> Should I try rename the tests in a manner as mentioned in https://github.com/pymc-devs/pymc/discussions/5579 ?

No, that will need a lot of refactoring. To set realistic expectations: This will take months; we can only do one at a time. Splitting `test_distribution.py` and `test_distribution_moments.py` has the highest priority.

Can you try to run some of the tests locally in a Python 3.10 environment? `pytest -v pymc\tests\test_sampling.py`
The Aesara CI only tests with Python 3.8.. But conda-forge has it listed for 3.10 so maybe it could actually work.

**Comment by 5hv5hvnk** [comment]
it completes with  81 passed, 5 skipped, 6 xfailed, 71 warnings
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/17161999/159364741-03aab3f7-de5e-4649-9c21-6115bcc23db7.png">

**Comment by michaelosthege** [comment]
Sounds promising. Do you want to open a PR?

Note that we don't want to increase our use of CI resources here. So just swapping the version of an existing job should be enough

**Comment by 5hv5hvnk** [comment]
I have opened a PR, please have a look
> Note that we don't want to increase our use of CI resources here. So just swapping the version of an existing job should be enough

what does CI resources imply I have read this in a lot of your comments and don't know what it means exactly

**Comment by michaelosthege** [comment]
The cumulative runtime of our CI test pipelines was 6.5 hours and we just reduced it to 3.75.
This is still a lot of compute on quite powerful machines and they eat a lot of electricity doing that.
We don't have to pay for it, but we all live on this planet together and should save energy wherever we can.

Also there's an upper limit of CI minutes per month and if we hit that the jobs start queuing up.

**Comment by ricardoV94** [comment]
In case that was the source of confusion, CI stands for continuous integration, which is another obscure name for "running python tests on Github servers"
