### ISSUE TITLE
Document `get_moment`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5210]
With #5140 the `get_moment` function will be a requirement for all standard distributions and we have to document it properly in a place that users can find easily as well as in this [dev guide](https://github.com/pymc-devs/pymc/blob/77f2c9844bcfaf451648289e9e30ec7475dfcce1/docs/source/developer_guide_implementing_distribution.md).

**Comment by amyoshino** [comment]
Hi, I would like to work on that! It will be my first contribution to this repo so apologies if I make mistakes in first commits. 

Some follow up questions regarding this issue:
1 - Is something like this enough as docstrings? 
Replacing the text in [] for the corresponding one, for example if Normal Distribution then [highest-order moment / calculated moment] will be replaced with mean (or mu).

```
"""
        Compute the [highest-order moment / calculated moment] for the [Distribution Name] distribution.
        Parameters
        ----------
        rv : RandomVariable
            The RandomVariable called by the Model.
        other parameter 1: ...
        other parameter 2: ...
        ...
        Returns
        -------
        TensorVariable
"""
```
I then customize each docstring to match the distribution name and the corresponding calculated moment.

2 - I see in #5078 item 2.1. only the "higher-order" moment is supported. So should we add an observation in the docstring remembering that? 

3 - In addition to docstrings and the dev guide, I'm looking for any other place that it needs to be documented. Let me know if you have any other place in mind. 

Thank you!

**Comment by ricardoV94** [comment]
Looks like a good start. I wouldn't emphasize "higher moment", but something like "stable moment from which to start sampling"

We don't need docstrings for every distribution moment function, just document what the `get_moment` does and how devs/users should write (and test) it for their custom distributions, in the docs.

**Comment by amyoshino** [comment]
Quick update about my progress, so there is no feeling it's abandoned. 
@ricardoV94 Thank you for your guidance! Apologies for taking some time to open a PR, I've been a little busy with work during this week but I will work on it in the weekend.
