### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [pymc-devs/pymc#5213]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/PyMC/lokal -name '*.py')
```

**Comment by michaelosthege** [comment]
Doesn't appear that there's much interest in this.

I never heard of augmented assignment statements before. They seem interesting, but to keep the codebase accessible to people without deep Python knowledge I don't think that we should use them.

Closing this to clear up our issue backlog...

**Comment by elfring** [comment]
:thinking: Can you reopen this issue if you would like to take information (like the following) better into account?
* I find that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) can indicate also motivation for another bit of collateral evolution.
* Would you dare to try a variant of the shown Perl command example out on another test repository?
* The proposed software adjustment should influence run time characteristics of affected components in desirable directions.
  How do you think about measuring any differences?

**Comment by ricardoV94** [comment]
Is the proposal to automatically replace `x = x +y` by `x += y`? If that's the case I dont' think it's worth the trouble. 

Note that we use a computational backend in most of our codebase whose objects do not support augmented assignments.

**Comment by elfring** [comment]
>Note that we use a computational backend in most of our codebase whose objects do not support augmented assignments.

:thought_balloon: Were any source code places marked for protection according to unwanted changes?

**Comment by ricardoV94** [comment]
No, why would we have done that?
