### ISSUE TITLE
Enforce MvStudentT nu to be a scalar variable

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5214]
#5173 revealed a bit of an edge case in the MvStudentT with broadcasting when `nu` is a vector. Since we haven't tested whether the RV, logp, and logcdf, are doing the right thing in that case, we should assert that `nu` is a scalar in the `make_node` method of the respective RandomVariable.

We can always remove this restriction if we confirm things are working consistently with the rules of broadcasting.

**Comment by sagartomar** [comment]
I would like to work on this. It looks like we need to override the make_node method in MvStudentTRV class and need to check if nu is scalar and if the check passes then call the super class' make_node method.

**Comment by twiecki** [comment]
Great, go for it @sagartomar :+1:.
