### ISSUE TITLE
Suggestion: additional format for start dict

### ISSUE THREAD

**Issue by ccaprani** [pymc-devs/pymc#5221]
I'm exploring a multimodal posterior with a medium-sized model. Setting the start points helps me push some chains into different 'valleys'. A very *very* minor quibble is that with lots of parameters, the start list of dicts has a lot of unnecessary code. For example, for 4 chains:
```python
start = [{'β':3.0,'n':1,....},
         {'β':3.0,'n':2,....},
         {'β':-0.5,'n':1,....},
         {'β':-0.5,'n':2,....}]
```
Although the NUTS pre-processor beautifully fills in any variables missing from the start list, the variables cannot (and should not) change between chains, and so the variable names are redundant. The following would avoid this:
```python
start = {'β': np.array(3.0,3.0,-0.5,-0.5), 
         'n': np.array(1.0,2.0,1.0,2.0),
         ...}
```
where each variable array is `nchains` long. In other words, instead of a list of dicts, a dict of variables and arrays of length no. chains.

To not break the existing API, this would be an additonal 'formatting' of the argument, but would be reasonably easy to implement I think. If there is merit in this, I'll be happy to give it a first go once v4 is out.

**Comment by michaelosthege** [comment]
Hi @ccaprani,
the `start` kwarg is a hot topic and subject to change with the upcoming `v4.0.0` release. It will be superseeded by `initvals` that will allow also for initialization _strategies_ such as `"prior"`.

Shapes are treacherous, so we probably don't want to add "smart" reshaping to the `start/initvals` kwargs. It would need quite a bit of shape evaluation and guesswork to breadcast elements like you proposed.

Instead I would recommend to write a combined list/dict-comprehension that expands your 2nd example to the 1st:

```python
def expand(start: dict, nchains) -> list:
    return [
        {
            k : v[c]
            for k, v in start.items()
        }
        for c in range(nchains)
    ]

start = {
    'β': np.array(3.0,3.0,-0.5,-0.5), 
    'n': np.array(1.0,2.0,1.0,2.0),
}

print(expand(start))
```

**Comment by ccaprani** [comment]
@michaelosthege Many thanks indeed for responding. I appreciate the complexities. It was worth raising it for your super neat list/dict comprehension snippet! Thanks again.
