### ISSUE TITLE
Propose gp.MarginalSparse rename before v4

### ISSUE THREAD

**Issue by bwengals** [pymc-devs/pymc#5228]
What do folks think about renaming `gp.MarginalSparse` to `gp.MarginalApprox` for v4?  

Reasons for:
- It would be nice to add a `LatentApprox` set of implementations.  They may use the eigendecomposition, the Hilbert space GP, random Fourier features, or DTC/Projected process, not all of which make sense to be called "sparse".
- It'd be nice to have `LatentApprox` match up with `MarginalApprox`, instead of `LatentApprox` and `MarginalSparse`.
- "Approx" is a clearer name than "Sparse" for GP approximations, whether they are "sparse" approximations or not.

**Comment by fonnesbeck** [comment]
Makes sense to me. You can deprecate and alias the `MarginalSparse`. Or, is it better to have it as a specific subclass of `MarginalApprox`?

**Comment by bwengals** [comment]
I think just aliasing `MarginalSparse` would be good enough, I think it's fairly safe to say that all the good "Marginal" (assume Gaussian noise) approximations are "sparse".

**Comment by michaelosthege** [comment]
Closed by #5242
