### ISSUE TITLE
Add JAX backend installation instructions with PyMC4

### ISSUE THREAD

**Issue by martiningram** [pymc-devs/pymc#5239]
Hi everyone,

I've been working with PyMC v3, but thought I'd give the new PyMC4 a go. I installed it following the instructions here:

https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Linux)#pymc-v4-installation

I'd like to try the JAX backend, but neither `numpyro` nor `JAX` are included. That's fine as they're optional (I saw a previous issue), but I think it would be good to have a short note about how to install them, or at least which versions should work. If it's helpful, I can try to use the latest version of `numpyro` and a recent version of `JAX` (unfortunately I can't use the very latest because of an older CUDA version) and report whether they worked OK.

**Comment by zaxtax** [comment]
I definitely think that the instructions for the JAX backend should be there. I suspect if you follow the installation instructions for numpyro you end up with everything you need for the JAX backend to run.

**Comment by michaelosthege** [comment]
The install instructions were moved to https://www.pymc.io/projects/docs/en/latest/installation.html

This page now also mentions optional JAX dependencies.
