### ISSUE TITLE
Automated scaling choice for HMC/NUTS

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#524]
One of the things that jumps out at me using PyMC 3 regularly is that it is often very difficult to choose starting values for even very simple models that do not result in PositiveDefiniteErrors when using the NUTS step method. It often takes much trial and error, and in many cases I have to abandon NUTS for Metropolis or Slice. I know this will befuddle many users, so it would be nice to have PyMC try out various choices of start values until it finds one that works. Points derived automatically using mean/mode/median or find_MAP don't do the trick in these cases.

**Comment by twiecki** [comment]
Yeah, that's a huge problem for me too. Anyone know what `stan` does?

**Comment by jsalvatier** [comment]
Yeah, we could use a lot of work in this area. Often the problem doesn't
show up as an error even, so we'll need to come up with a good way to say
"this works".

**Comment by jsalvatier** [comment]
I'm eager for examples of models that have this problem. If you have one please post.

**Comment by twiecki** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/1523.

**Comment by fonnesbeck** [comment]
@twiecki your'e on a roll

**Comment by twiecki** [comment]
:)
