### ISSUE TITLE
sample_prior_predictive generates NxN samples instead of N for samples=N

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#5254]
Running 3.11.4 on Colab, with a likelihood as follows:

```python
    # Likelihood
    pm.NegativeBinomial('obs',
                 growth,
                 alpha=pm.Gamma("alpha", mu=6, sigma=1),
                 observed=confirmed_data)
    
    prior_pred = pm.sample_prior_predictive(100)
```

and

```python
confirmed_data = pm.Data('confirmed', df_country.confirmed.values)
```

having shape `(650,)` results in `prior_pred["obs"]` having shape `(100, 100, 650)`. The graph shows no evidence of an extra dimension anywhere.

**Comment by fonnesbeck** [comment]
Perhaps relatedly, for some models `sample_prior_predictive` appears to add a redundant dimension to the sample:

![image](https://user-images.githubusercontent.com/81476/145689465-2e01b51f-82ae-4e77-87c1-67177f72c196.png)

In any case, there is a shape issue with `sample_prior_predictive`

**Comment by fonnesbeck** [comment]
Note that this does *not* occur in `sample_posterior_predictive`, but just in prior sampling.

**Comment by fonnesbeck** [comment]
The problem here is the `Bound` nodes. Removing them fixes the issue in both examples.

**Comment by twiecki** [comment]
Does the problem exist in 4.0?

**Comment by ricardoV94** [comment]
You can't sample from a Bound in V4 on purpose
