### ISSUE TITLE
pymc3 does not work properly with lower versions of Glibc

### ISSUE THREAD

**Issue by GradientLive** [pymc-devs/pymc#5257]
## Description of your problem

I am trying to install pymc3 on a centos6 server. The various environment software versions on the server are relatively low.
I used miniconda3 to create an environment to install pymc3, and I can install it successfully, but it reports an error when importing pymc3.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
```

**error output information**:
> GLIBC2.14 not found
> GLIBC2.15 not found
> GLIBC2.17 not found

**Please provide the full traceback.**

I tried installing a higher version of glibc(2.17,2.20) and adding the newly installed glibc to the PATH and LD_LIBRARY_PATH in my environment variables. This had worse results, it almost ruined my whole development environment(**ls、 mv、vim... almost all commands not work**)!

I now think the likely reason is that pymc3 works fine in a slightly higher version of the glibc environment (>=2.17). But since glibc is a relatively low-level environment, I don't know how to apply it to my environment.

## Versions and main components

* PyMC/PyMC3 Version:   3.11.2
* Theano Version:       1.0.5
* Python Version:       3.9.2
* Operating system:     centos6
* How did you install PyMC/PyMC3: miniconda3
    conda install pymc3 -c conda-forge

I was wondering if there is a manual compilation method to install pymc3(not use conda), and if the manual compilation can take advantage of the environment information on my server to compile so that it can work in a lower GLIBC version environment?
Thanks guys!

**Comment by rosgori** [comment]
What version of gcc are you using?

**Comment by ricardoV94** [comment]
Closing for lack of details
