### ISSUE TITLE
Increase codecov threshold

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5258]
Should we increase the codecov threshold at which tests fail? Right now it's set at 50% of modified lines.

**Comment by fonnesbeck** [comment]
Are we seeing a trend of reduced overall coverage at all? If not, I'd say keep it where it is, otherwise a bump might be justified.

**Comment by ricardoV94** [comment]
We haven't used it for very long do the trend is wobbly: https://app.codecov.io/gh/pymc-devs/pymc/

The codecov should be a guide not a target in itself. My intuition for raising it is that authors/reviewers will be less likely to miss changes that are not convered by tests.

Also if some lines don't warrant test coverage I think it's better to explicitly put an inline comment like we would do for cases where we don't want pylint to apply.

**Comment by fonnesbeck** [comment]
I think you can also exclude lines in the .coveragerc file. Not sure how though.
