### ISSUE TITLE
Add random walk distribution for V4

### ISSUE THREAD

**Issue by mjhajharia** [pymc-devs/pymc#5290]
created this issue linked to the project for porting time series distributions to v4

**Comment by mjhajharia** [comment]
related to #4642

**Comment by canyon289** [comment]
Linking to direct comment https://github.com/pymc-devs/pymc/issues/4642#issuecomment-1002251912

Task is to create random walk distribution in V4 that will serve as a building block for other time series distributions

**Comment by drbenvincent** [comment]
Related to #5433

**Comment by ricardoV94** [comment]
Closed via #5298
