### ISSUE TITLE
Add autoregressive model to V4

### ISSUE THREAD

**Issue by mjhajharia** [pymc-devs/pymc#5291]
created this issue linked to the project for porting time series distributions to v4

**Comment by mjhajharia** [comment]
related to #4642

**Comment by ricardoV94** [comment]
@mjhajharia Can you give a more descriptive name to this issue?

**Comment by canyon289** [comment]
Add at minimum AR1 model to PyMC v4, ideally add AR(n) to facilitate addition of ARMA model
