### ISSUE TITLE
API proposal: Add sample_all()

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5299]
All the good Bayesians who are following the proper Bayesian workflow are writing things like:

```python
with model:
    idata = pm.sample()
    idata.extend(pm.sample_prior_predictive())
    idata.extend(pm.sample_posterior_predictive(idata_simple))
```

these days. Besides this syntax not being that pretty because of the extend, it's also verbose. So how about instead we have a `pm.sample_all()` that returns an `InferenceData` with posterior, prior, prior predictive, and posterior predictive, all in one command?

I think that would also help enforce best practices and make it much simpler, especially for beginners to do The Right Thing.

**Comment by ricardoV94** [comment]
What is the point of `sample_prior`? Is it the same as `prior_predictive` without draws from the likelihood?

**Comment by twiecki** [comment]
@ricardoV94 Right, I don't think we need it here (removed it above).

**Comment by canyon289** [comment]
Im in favor of this, would be really nice syntactic sugar. It also will make downstream arviz usage eaiser for beginners since itll reduce the number of "you dont have prior/posterior predictive samples" which are needed for many plots and diagnostics

**Comment by michaelosthege** [comment]
I like it. Would make some backend things easier too.
But I'd prefer to have kwargs so one can choose to do only some of the steps. `sample_all` could still be added as a short-hand notation for `pm.sample(prior_predictive=True, posterior_predictive=True)`.

Related proposal: Setting `discard_tuned_samples=False` by default? They are saved in separate idata groups already and it would help understanding, diagnosis and performance tweaking.

**Comment by fonnesbeck** [comment]
I'm not sure how much you would want to automate all of this. The Good Bayesian would want to look at the prior predictive output before they go ahead and fit the model, right? There is something to be said for deliberately conducting the workflow yourself, and adjusting as necessary along the way.

**Comment by ericmjl** [comment]
Crazy idea: what if we added the function, but kept its presence "for the experts' in the house" only?

I'm maybe a quarter serious about this idea.

There's value for expert practitioners who are familiar with their domain to automate routine things. I can see the reasons why @twiecki would want this automation.

At the same time, I also see @fonnesbeck's point about deliberately conducting the workflow.

I see no harm in it being present as a convenient shortcut that we don't have to write on our own. I would maybe only caution against using the shortcut in our examples, that's all.

**Comment by twiecki** [comment]
I think our prior and posterior predictive sampling is very fast now. What if we just, by default, when calling `pm.sample()` we also run predictive samples and return them? There would be an option to switch them off. In that case, if you follow the Good Bayesian workflow you still explicitly call `sample_prior_predictive()` but if you actually draw posterior samples, you always have a fully populated `InferenceData` object.
