### ISSUE TITLE
Revamp our negative binomial explanation

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5300]
## Description of your problem
Our explanation of negative binomial parametrisation is either confusing, or wrong, I don't know which.

More specifically  the explanation of the mu parameter itself is confusing, I personally dont understand how poisson is being parameterized twice, both by gamma samples controlled by alpha, and mu

Stans documentation does a much better job explaining the effect of each parameter, perhaps we can incorporate some of their wording
https://mc-stan.org/docs/2_20/functions-reference/nbalt.html

![image](https://user-images.githubusercontent.com/7213793/147835765-f2e53d18-63ed-49ea-88be-8de23c651276.png)

**Comment by canyon289** [comment]
From @junpenglao 

It's because pymc is explaining the parameterzation with NegBino being Gamma Poisson mixture https://en.wikipedia.org/wiki/Negative_binomial_distribution#Gamma%E2%80%93Poisson_mixture, and Stan is explaining NegBino being overdispersed Poisson (https://en.wikipedia.org/wiki/Negative_binomial_distribution#Poisson_distribution and https://en.wikipedia.org/wiki/Negative_binomial_distribution#Overdispersed_Poisson)

**Comment by samO2I1** [comment]
@canyon289 can I work on this issue?

**Comment by canyon289** [comment]
Please do! Let us know how we can help

**Comment by samO2I1** [comment]
@canyon289 can you please share the source code link?

**Comment by canyon289** [comment]
Here it is https://github.com/pymc-devs/pymc/blob/main/pymc/distributions/discrete.py#L665

**Comment by samO2I1** [comment]
@canyon289 I am not able to understand that at which points Poisson is parameterized twice?

**Comment by canyon289** [comment]
The documentation somewhat confusingly describes
* The poisson distribution is parametrized by the gamma distribution
* The poisson distribution (somehow is also) parameterized by mu
* The gamma distribution is parameterized by alpha

I've provided a directly link here. To be honest I don't know what the correct explanation is so I won't be able to provide much guidance there.
https://docs.pymc.io/en/v3/api/distributions/discrete.html#pymc3.distributions.discrete.NegativeBinomial

**Comment by herve-91** [comment]
Hello

In the context, considered in the documentation, where the negative binomial is introduced as a poisson random variable whose rate is gamma distributed, I believe both <img src="https://render.githubusercontent.com/render/math?math=\alpha"> and <img src="https://render.githubusercontent.com/render/math?math=\mu"> should be presented as parameters of the gamma distribution: 
- <img src="https://render.githubusercontent.com/render/math?math=\alpha"> is the shape of the gamma distribution
- <img src="https://render.githubusercontent.com/render/math?math=\mu"> is the mean of the gamma distribution.

Indeed, if we consider a poisson distribution whose rate is gamma distributed:

<img src="https://render.githubusercontent.com/render/math?math=p(x \mid \alpha, \beta)=  \int_0^\infty  f(x \mid \lambda) g(\lambda \mid \alpha, \beta)  d\lambda ">
where

- <img src="https://render.githubusercontent.com/render/math?math=f(x \mid \lambda)= \frac{e^{-\lambda}}{x!} \lambda^x"> is a poisson distribution with rate <img src="https://render.githubusercontent.com/render/math?math=\lambda ">

- <img src="https://render.githubusercontent.com/render/math?math=g(\lambda \mid \alpha, \beta) = \frac{ \beta^\alpha \lambda^{\alpha - 1} e^{-\beta \lambda}}{\Gamma(\alpha)}"> is a gamma distribution with shape parameter <img src="https://render.githubusercontent.com/render/math?math=\alpha"> and rate parameter <img src="https://render.githubusercontent.com/render/math?math=\beta">

We have:

<img src="https://render.githubusercontent.com/render/math?math=p(x \mid \alpha, \beta)= \binom{\alpha %2B x -1}{ x }  (\frac{1}{\beta %2B 1})^{x} (\frac{\beta}{\beta %2B 1})^{\alpha}  ">

from which we can recover the formula of the documentation if we replace <img src="https://render.githubusercontent.com/render/math?math=\beta"> by <img src="https://render.githubusercontent.com/render/math?math=\alpha / \mu"> where  <img src="https://render.githubusercontent.com/render/math?math=\mu"> is the mean of the gamma  distribution :


<img src="https://render.githubusercontent.com/render/math?math=p(x \mid \alpha, \mu)= \binom{\alpha %2B x -1}{ x } (\frac{\mu}{\mu %2B \alpha})^{x} (\frac{\alpha}{\mu %2B \alpha})^{\alpha} ">

Regards,

**Comment by canyon289** [comment]
This is great and much less confusing. Would you like to add some version of it the docs? Thank you for investigating!

**Comment by canyon289** [comment]
Thanks @herve-91
