### ISSUE TITLE
Rename `model.recompute_initial_point` to `model.compute_initial_point`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5301]
Nitpick one. There is no longer an initial_point (it is deprecated) so the `re` does not really mean much. We can save 2 letters xD

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?

**Comment by twiecki** [comment]
@Vaibhav-Chopra-GT Go for it :+1:.

**Comment by samO2I1** [comment]
@twiecki  @ricardoV94  Can i work on this issue?

**Comment by twiecki** [comment]
This is closed by https://github.com/pymc-devs/pymc/pull/5360.

@samO2I1 let me know if I should suggest other beginner-friendly issues, but you can also have a look yourself first.
