### ISSUE TITLE
`pm.Data` silently missing from `InferenceData` when dims match the variable name

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5309]
Xarray, and thereby `InferenceData` don't support labeling dimensions with the same name as the variable.

```python
with pm.Model() as pmodel:
    pm.Data("city", numpy.arange(5), dims="cities") # ✔ ends up in .constant_data as expected

    pm.Data("time", numpy.arange(5), dims="time")   # ❌ silently missing
    pm.Normal("a")                                  # ❌ errors in InferenceData conversion
    idata = pm.sample(chains=1)
```

Only variable "a" caused an error - but unfortunately only after MCMC.
```
MissingDimensionsError: 'a' has more than 1-dimension and the same name as one of its dimensions ('chain', 'draw', 'a').
xarray disallows such variables because they conflict with the coordinates used to label dimensions.
```

Since dims are passed at creation of the variables, we should raise that error in `Model.add_random_variable`. That will raise the error much earlier, and work for variables and data.

https://github.com/pymc-devs/pymc/blob/14c4f39122ae313e25b2698195067ec44b69b26a/pymc/model.py#L1416-L1429

## Versions and main components

* PyMC/PyMC3 Version: latest

**Comment by parthb83** [comment]
Hey @michaelosthege! I would like to work on this issue. Kindly guide me on how to solve this issue.

**Comment by michaelosthege** [comment]
Please follow the solution I suggested in the issue description.
Adding a corresponding test case in `test_idata_conversion.py` is also important. Again see the issue description.

**Comment by purna135** [comment]
I would like to work on this one.

**Comment by michaelosthege** [comment]
It doesn't look like anyone has opened a PR to fix it yet.
So everybody feel free to fix this issue - you don't need to request permission to work on it, but we're also not taking reservations for bugfix contributions.

Just letting people know you're working on it is a good idea.

**Comment by kimbochen** [comment]
Hi I can't reproduce the error.
This is the code I input:
```python
import pymc as pm
import numpy as np
with pm.Model() as pmodel:
    pm.Data("time", np.arange(5), dims="time")
    pm.Data("city", np.arange(5), dims="cities")
    pm.Normal("a")
    idata = pm.sample(chains=1)
```
This is the output:
```
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (1 chains in 1 job)
NUTS: [a]
Sampling 1 chain for 1_000 tune and 1_000 draw iterations (1_000 + 1_000 draws total) took 3 seconds.3<00:00 Sampling chain 0, 0 divergences]
Only one chain was sampled, this makes it impossible to run some convergence checks
```

**Comment by ricardoV94** [comment]
@kimbochen Just to confirm, the error does not show even after sampling is finished?

**Comment by kimbochen** [comment]
Yes, it does not show any error.
There is one warning though:
```
~/Projects/pymc/pymc/data.py:647:
FutureWarning: The `mutable` kwarg was not specified.
Currently it defaults to `pm.Data(mutable=True)`, which is equivalent to using `pm.MutableData()`.
In v4.1.0 the default will change to `pm.Data(mutable=False)`, equivalent to `pm.ConstantData`. 
Set `pm.Data(..., mutable=False/True)`, or use `pm.ConstantData`/`pm.MutableData`.
  warnings.warn(
```

**Comment by OriolAbril** [comment]
This warning is unrelated to the issue, we can ignore it.

Can you share the output you get for the variable `idata`? If you can try the following 3 commands and comment the output below:

```
print(idata)
print(idata.posterior)
print(idata.constant_data)
```

**Comment by kimbochen** [comment]
This is the output I get:
```
Inference data with groups:
	> posterior
	> sample_stats
	> constant_data
<xarray.Dataset>
Dimensions:  (chain: 1, draw: 1000)
Coordinates:
  * chain    (chain) int64 0
  * draw     (draw) int64 0 1 2 3 4 5 6 7 8 ... 992 993 994 995 996 997 998 999
Data variables:
    a        (chain, draw) float64 -0.3702 -0.7995 -0.9138 ... -1.325 -0.5703
Attributes:
    created_at:                 2022-02-20T07:37:39.648419
    arviz_version:              0.11.4
    inference_library:          pymc
    inference_library_version:  4.0.0b2
    sampling_time:              2.329646110534668
    tuning_steps:               1000
<xarray.Dataset>
Dimensions:  (time: 5, cities: 5)
Coordinates:
  * time     (time) int32 0 1 2 3 4
  * cities   (cities) int64 0 1 2 3 4
Data variables:
    city     (cities) int32 0 1 2 3 4
Attributes:
    created_at:                 2022-02-20T07:37:39.665067
    arviz_version:              0.11.4
    inference_library:          pymc
    inference_library_version:  4.0.0b2
```
I also tried to print the shape of `pmodel.a`:
```
TensorConstant{[]}
```

**Comment by OriolAbril** [comment]
It doesn't error now out but the issue of missing data is still there. `time` is only a coordinate, not a data variable. Unlike city which is a data variable with cities being a coordinate.

Using an arange inside the pm.Data is confusing because coordinate values default to an arange too. If you change that to any other array it will be much easier to see how this data is lost during conversion
