### ISSUE TITLE
Create helper `pm.draw()` to take draws from a given variable

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5311]
> `eval()` should be aliased to something more intuitive like `sample()` or `draw()` where appropriate.

We have been using `eval` in our examples as a substitute to the old random method. This is just the standard Aesara debug feature that exists for any node, and shouldn't be used for more than that.

We can have a function wrapper that compiles a "proper" aesara function and takes a given number of draws. For analogy with V3 it could be named `pm.random`, but I like the `pm.draw` name better.

```python
with pm.Model() as m:
  x = pm.Normal("x")

x_draws = pm.draw(x, draws=100)
```

Adding default updates to RNGs could then more justifiable be done in `pymc.aesaraf.compile_pymc` which already does this for Simulator variables anyway, and which `pm.random`/ `pm.draw` would call. That would be one less thing that Distribution has to be concerned with.

https://github.com/pymc-devs/pymc/blob/75ea2a80cb27773e93b7b207043077953940e6ff/pymc/aesaraf.py#L968

_Originally posted by @ricardoV94 in https://github.com/pymc-devs/pymc/issues/5308#issuecomment-1005171139_

**Comment by danhphan** [comment]
Hi @ricardoV94, I would like to work on this task. Could you please give some more detailed suggestions (like which file should we put the pm.draw function wrapper, and is there a similar wrapper function to follow). Thank you.

**Comment by ricardoV94** [comment]
> Hi @ricardoV94, I would like to work on this task. Could you please give some more detailed suggestions (like which file should we put the pm.draw function wrapper, and is there a similar wrapper function to follow). Thank you.

Thanks for offering. I assigned the issue to you.

Good question about where it should go... `sampling.py` perhaps? This is basically a striped down version of `prior_predictive`. @fonnesbeck what do you think?

A rough sketch of what it could look like:
```python
def draw(vars, draws=1, mode=None, **kwargs):
  if not isinstance(vars, (list, tuple)):
    vars = [vars]
  f = pm.aesaraf.compile_pymc([], vars, mode=mode, **kwargs)
  return [f() for _ in range(draws)]
```

Type hints would be a nice plus

**Comment by danhphan** [comment]
Hi yes, thank you for the suggestion.

I am setting up the dev environment with docker and start reading the sample_prior_predictive function in sampling.py and related files. I will let you know if I face any issue :)
