### ISSUE TITLE
Remove Theano import warning

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5312]
It works without problems to have PyMC3 and Theano as well as PyMC 4.0 and aesara in the same environment, so I don't think we need that warning which is quite verbose if you run multiple chains.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/674200/148162769-966331b6-f01a-43f1-9ce5-943476f926b1.png">

**Comment by samO2I1** [comment]
@twiecki sir can i work on this issue?

**Comment by ricardoV94** [comment]
> @twiecki sir can i work on this issue?

Sure. I've assigned the issue to you. Let us know if you have any questions

**Comment by samO2I1** [comment]
@ricardoV94 can you provide me with the source code link?

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc/blob/75ea2a80cb27773e93b7b207043077953940e6ff/pymc/__init__.py#L35

**Comment by samO2I1** [comment]
@twiecki if I comment out the whole warning in init.py will this work out for this issue ? as this will not give warning whenever Theano is imported.

**Comment by twiecki** [comment]
Just delete the whole if thing with the warning as well as the one below.

**Comment by samO2I1** [comment]
@twiecki I have created a PR . Please check!! #5328
