### ISSUE TITLE
Add pre-commit check for sphinx cross-references

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#5317]
Now that we have versioned docs, we can't use urls for internal links if we want each version to point to themselves. I think we should add a pre-commit check to ensure there are no links pointing to `docs.pymc.io` anywhere inside the `docs/source/` folder.

I don't know pre-commit but it seems like this should be easy for someone who does know their way around it. cc @MarcoGorelli if you agree with this, can you label it beginner friendly?

**Comment by MarcoGorelli** [comment]
yeah I think just a pygrep check for this would be good

**Comment by symeneses** [comment]
Hi, I would like to work on this issue ✋🏽

**Comment by OriolAbril** [comment]
Assigned it to you
