### ISSUE TITLE
Remove FastPointFunc and LoosePointFunc

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5319]
### Discussed in https://github.com/pymc-devs/pymc/discussions/5237

<div type='discussions-op-text'>

<sup>Originally posted by **ricardoV94** December  3, 2021</sup>
It seems that the difference is that `LoosePointFunc` allows you to evaluate a  `logp`/`dlogp`/ what have you with args and kwargs, instead of just passing a dictionary, but at the cost of being slower because it has to wrap them in a dictionary (Point) before calling logp.

```python
import pymc as pm

with pm.Model() as m:
    x = pm.Normal('x')
    y = pm.Normal('y', 0, 1, observed=0)

# Uses `LoosePointFunc` under the hood
m.logp({'x': 0})
m.logp(x=0)
m.logp([('x', 0)])  # Couldn't think of any other way of using `args`

# Uses `FastPointFunc` under the hood
m.fastlogp({'x': 0})
m.fastlogp(x=0) # Fails
m.fastlogp([('x', 0)]) # Fails
```

Does anyone actually use this? Should the default be the "fast" version that only accepts a dictionary, and the flexible one be called something like "slow"? Do we even need the slow version?

https://github.com/pymc-devs/pymc/blob/f6f1a8e807a0719a07fdb17ed79af9adce065814/pymc/model.py#L1722-L1766</div>

**Comment by ricardoV94** [comment]
We both did the same @twiecki xD. Closing in favor of #5318 because that one has one more tag!
