### ISSUE TITLE
Upgrade Aesara and NumPy upper version limits

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5321]
Aesara is currently pinned and can't be updated to the latest version until https://github.com/aesara-devs/aesara/issues/707 is fixed.

That means we also don't get the NumPy 1.22 compatibility fix until we can upgrade.

Until that Aesara upgrade we'll want to pin  `numpy<1.22.0` and keep this issue open until we can upgrade Aesara *and* remove the NumPy version pin.

*For stability, we should still pin Aesara at the minor, or even the patch version.*

**Comment by canyon289** [comment]
Note on this issue. When installing PyMC from master using `requirements.txt`. and `requirements-docs.txt` numpy 1.22 is installed, causing import errors on OSX


> /Users/canyon/miniconda3/envs/pymc/bin/python3 "/Users/canyon/Library/Application Support/JetBrains/PyCharm2021.1/scratches/aeppl/aesara_shape.py"
> Traceback (most recent call last):
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/configparser.py", line 239, in fetch_val_for_key
>     return self._aesara_cfg.get(section, option)
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/configparser.py", line 781, in get
>     d = self._unify_values(section, vars)
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/configparser.py", line 1152, in _unify_values
>     raise NoSectionError(section) from None
> configparser.NoSectionError: No section: 'blas'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/configparser.py", line 355, in __get__
>     val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/configparser.py", line 243, in fetch_val_for_key
>     raise KeyError(key)
> KeyError: 'blas__ldflags'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/canyon/Library/Application Support/JetBrains/PyCharm2021.1/scratches/aeppl/aesara_shape.py", line 1, in <module>
>     import aesara.tensor as at
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/__init__.py", line 79, in <module>
>     from aesara import scalar, tensor
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/tensor/__init__.py", line 96, in <module>
>     from aesara.tensor import (  # noqa
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/tensor/blas.py", line 166, in <module>
>     from aesara.tensor.blas_headers import blas_header_text, blas_header_version
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/tensor/blas_headers.py", line 1015, in <module>
>     if not config.blas__ldflags:
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/configparser.py", line 359, in __get__
>     val_str = self.default()
>   File "/Users/canyon/miniconda3/envs/pymc/lib/python3.9/site-packages/aesara/link/c/cmodule.py", line 2628, in default_blas_ldflags
>     blas_info = numpy.distutils.__config__.blas_opt_info
> AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'

**Comment by twiecki** [comment]
https://github.com/aesara-devs/aesara/issues/707 is fixed now and has an aesara release 2.3.5 https://github.com/aesara-devs/aesara/releases/tag/rel-2.3.5 which we should pin.

**Comment by twiecki** [comment]
We should cut a new release. CC @michaelosthege
