### ISSUE TITLE
Strategy to convert `Model.logpt` from property to more flexible method.

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5333]
In #5320 We removed most of the Factor property variations in favor of 3 methods that accept optional `vars` and `jacobian` arguments (and `sum` in the case of `logp`).

This was pretty painless except for the need to add (or rather make use of the not yet implemented) but verbose `Model.logp_elemwiset` as the default flexible method to extract `logp` terms. Ideally this would be done by a `Model.logpt(vars=None, jacobian=True, sum=True)` method in line with the `Model.dlogpt` and `Model.d2logpt`, but since the `model.logpt` is a property (and a commonly used one I guess), this is not trivial to refactor without breaking changes. 

Unless we are okay with a breaking change in time for V4, this is the strategy I could see:

1. V4.0 `Model.logpt` (property) -> `Model.scalar_logpt` (property); FutureWarning: `Model.logpt` will become a method in the next release.
2. V4.1 `Model.logp_elemwiset` (method) -> `Model.logpt` (method) (**GOAL**); FutureWarning `Model.logp_elemwiset` and `Model.scalar_logpt` will be deprecated in favor of `Model.logpt`.
3. V4.2 Remove both `Model.scalar_logpt` and `Model.logp_elemwiset`.

***

The whole `Factor` BaseClass is also pretty useless at this point since only `Model` inherits from it in `V4`.

**Comment by twiecki** [comment]
I think we should have a breaking change, we change so many things already, like `RV.logp()` and this one is very internal.

**Comment by canyon289** [comment]
Break things and lets move into the future please! Whats becoming really confusing in this codebase is 3 ways to do things, the old way, the new "temporary way", the "when everything is ready way". Keeping the old way around "just for compatibility" has a big downside
