### ISSUE TITLE
Data object attribute error

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#5342]
## Description of your problem

When creating a `Data` object like the following:

```python
pitcher_idx = pm.Data('pitcher_idx', pitcher_indices, dims='obs_id')
```

It generates an AttributeError related to checking a version that does not exist:

<details><summary>Complete error traceback</summary>

```
AttributeError                            Traceback (most recent call last)
/var/repos/pie_live/research/projections/src/pitchers/ageing_curves.py in <module>
      99 with pm.Model(coords=coords) as age_model:
      100 
----> 101     pitcher_idx = pm.Data('pitcher_idx', pitcher_indices, dims='obs_id')
      102     age_idx = pm.Data('age_idx', age_indices, dims='obs_id')
     103 

/tmp/local/pymc/pymc/data.py in Data(name, value, dims, export_index_as_coords, mutable, **kwargs)
    637     if mutable is None:
    638         current = version.Version(pm.__version__)
--> 639         mutable = current.major == 4 and current.minor < 1
    640         if mutable:
    641             warnings.warn(

AttributeError: 'Version' object has no attribute 'major'
```

</details>

The following simple example will also trigger the exception:

```python
with pm.Model():

    d = pm.Data('d', np.random.randint(10, size=10))
```

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b1
* Aesara/Theano Version: 2.3.2
* Python Version: 3.8.9
* Operating system: Linux Docker container
* How did you install PyMC/PyMC3: build from master

**Comment by ghost** [comment]
Looks like my version of `packaging` is too old. Do we want to have this dependency just for this use? If so, we should formally add it to the dependencies with a minimum version. Probably not worth it just to check the version of PyMC.
