### ISSUE TITLE
Organize API changes in the release notes by severity

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5354]
The list of breaking changes in the RELEASE-NOTES.md is quite long, but most of these are only relevant for a tiny fraction of users/models.

To make the release notes less deterrent, we should split the API changes into two sections.
Something like:
* Important API changes
* Internal/Advanced API changes

An example: With #5320 the old `Model.logpt` property became a method and many other model properties were removed. Of these breaks `Model.logpt → Model.logpt()` is probably the only one worth mentioning for the "important" section.

**Comment by soma2000-lang** [comment]
@michaelosthege  I want to work on this issue but how can I know that among so many APIs ,which one I included in the advanced ones and which one as important.

**Comment by michaelosthege** [comment]
> @michaelosthege I want to work on this issue but how can I know that among so many APIs ,which one I included in the advanced ones and which one as important.

This is not really a beginner friendly issue. Please do one issue at a time. There are several others you wanted to work on.

**Comment by AlexAndorra** [comment]
Will work on that starting tomorrow 😉
