### ISSUE TITLE
installing pymc v4 on windows

### ISSUE THREAD

**Issue by moeketsims** [pymc-devs/pymc#5359]
Hi, I am installing pymc v4 on windows. I am at the root of the repo pymc\
when I run: 
conda env create -f .\conda\windows-environment-test-py38.yml 
I get: 
EnvironmentFileNotFound: '......\pymc\conda\windows-environment-test-py38.yml' file not found 

Please help!!.

**Comment by twiecki** [comment]
Can you try: `conda env create -f .\conda\windows-environment-dev-py38.yml`?

**Comment by moeketsims** [comment]
> Can you try: `conda env create -f .\conda\windows-environment-dev-py38.yml`?

Thanks Thomas - it worked, I had to use "conda-envs" instead of "conda"
that is:
conda env create -f .\conda-envs\windows-environment-dev-py38.yml
