### ISSUE TITLE
Cannot create a model with unobserved binomial distribution

### ISSUE THREAD

**Issue by cserpell** [pymc-devs/pymc#5362]
## Description of your problem

I would like to create a model where some variables are binomial, but unobserved, and I cannot do it. This is a minimal example, the following code works, as the variable is observed:

```python
import pymc3
with pymc3.Model() as model:
    rate = pymc3.Beta('rate', alpha=2, beta=2)
    input_var = pymc3.Data('input_var', [1, 2, 3])
    output_var = pymc3.Binomial('output_var', n=input_var, p=rate, observed=[1, 1, 1])
pymc3.model_to_graphviz(model)
```

![example](https://user-images.githubusercontent.com/858784/149787609-58cac2eb-96e4-4543-a0b5-1f039e7f807d.png)

But, the following one fails, because the binomial variable is unobserved and its parameter depends on other variable:

```python
import pymc3
with pymc3.Model() as model:
    rate = pymc3.Beta('rate', alpha=2, beta=2)
    input_var = pymc3.Data('input_var', [1, 2, 3])
    output_var = pymc3.Binomial('output_var', n=input_var, p=rate)
pymc3.model_to_graphviz(model)
```

Is it even possible to do what I am trying to do? Note that this is just an example, my model is bigger, with other variables depending on the binomial one, and those others may be observed (although I cannot declare that model because of this problem).

<details><summary>The stack trace when trying in a local jupyter notebook.</summary>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_3827/2775009730.py in <module>
      3     rate = pymc3.Beta('rate', alpha=2, beta=2)
      4     input_var = pymc3.Data('input_var', [1, 2, 3])
----> 5     output_var = pymc3.Binomial('output_var', n=input_var, p=rate)#, observed=[1, 1, 1])
      6 pymc3.model_to_graphviz(model)

~/git/example/p3/lib/python3.9/site-packages/pymc3/distributions/distribution.py in __new__(cls, name, *args, **kwargs)
    120         else:
    121             dist = cls.dist(*args, **kwargs)
--> 122         return model.Var(name, dist, data, total_size, dims=dims)
    123 
    124     def __getnewargs__(self):

~/git/example/p3/lib/python3.9/site-packages/pymc3/model.py in Var(self, name, dist, data, total_size, dims)
   1136             if getattr(dist, "transform", None) is None:
   1137                 with self:
-> 1138                     var = FreeRV(name=name, distribution=dist, total_size=total_size, model=self)
   1139                 self.free_RVs.append(var)
   1140             else:

~/git/example/p3/lib/python3.9/site-packages/pymc3/model.py in __init__(self, type, owner, index, name, distribution, total_size, model)
   1666             self.dsize = int(np.prod(distribution.shape))
   1667             self.distribution = distribution
-> 1668             self.tag.test_value = (
   1669                 np.ones(distribution.shape, distribution.dtype) * distribution.default()
   1670             )

~/git/example/p3/lib/python3.9/site-packages/theano/graph/utils.py in __setattr__(self, attr, obj)
    264 
    265         if getattr(self, "attr", None) == attr:
--> 266             obj = self.attr_filter(obj)
    267 
    268         return object.__setattr__(self, attr, obj)

~/git/example/p3/lib/python3.9/site-packages/theano/tensor/type.py in filter(self, data, strict, allow_downcast)
    179 
    180         if self.ndim != data.ndim:
--> 181             raise TypeError(
    182                 f"Wrong number of dimensions: expected {self.ndim},"
    183                 f" got {data.ndim} with shape {data.shape}."

TypeError: Wrong number of dimensions: expected 0, got 1 with shape (3,).
```
</details>

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* Aesara/Theano Version: Theano-PyMC 1.1.2
* Python Version: 3.9.7
* Operating system: Ubuntu 21.10
* How did you install PyMC/PyMC3: (conda/pip) pip inside a python's virtual environment (`python3 -m venv p3`, then `. p3/bin/activate`, then `pip install pymc3`)

**Comment by larryshamalama** [comment]
I might have a solution for you, but not so much of an in-depth explanation. I believe that this has to do with shapes and, when the binomial is unobserved, you avoid the error by specifying `shape = (3,)`.

I believe that this will no longer be an issue in v4, but I will have to double-check that.

Here's a quick notebook that I drafted about this issue: https://github.com/larryshamalama/pymc3-playground/blob/master/notebooks/shortcomings/binomial-graphviz-issue-5362.ipynb

**Comment by cserpell** [comment]
It passed the declaration and then failed when sampling. Anyway, I moved to a continuous approximation model, and it works...

**Comment by ricardoV94** [comment]
I confirmed that this is not an issue in V4
