### ISSUE TITLE
Ajax Sampling 

### ISSUE THREAD

**Issue by luiswilbert** [pymc-devs/pymc#5380]
Dear all
## I have been trying to use the Ajax Sampling from pymc and I got this error:

/usr/local/lib/python3.7/dist-packages/jax/experimental/optimizers.py:30: FutureWarning: jax.experimental.optimizers is deprecated, import jax.example_libraries.optimizers instead
  FutureWarning)
/usr/local/lib/python3.7/dist-packages/jax/experimental/stax.py:30: FutureWarning: jax.experimental.stax is deprecated, import jax.example_libraries.stax instead
  FutureWarning)
Compiling...
/usr/local/lib/python3.7/dist-packages/aesara/graph/opt.py:278: UserWarning: Supervisor is not added. Please build a FunctionGraphvia aesara.compile.function.types.std_graph()or add the Supervisor class manually.
  sub_prof = optimizer.optimize(fgraph)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-02bf6e1dcce2> in <module>()
    102 
    103 #likelihood--------------------------------------------------------------------------------------------------
--> 104     trace = pm.sampling_jax.sample_numpyro_nuts( target_accept=0.95)
    105     #trace = pm.sample(draws=500, tune=500, target_accept=0.99, random_seed=100,cores=4,chains=4,init="advi+adapt_diag")

18 frames
/usr/local/lib/python3.7/dist-packages/aesara/link/jax/dispatch.py in jax_funcify_ScalarOp(op, **kwargs)
    157 
    158     if "." in func_name:
--> 159         jnp_func = reduce(getattr, [jax] + func_name.split("."))
    160     else:
    161         jnp_func = getattr(jnp, func_name)

AttributeError: module 'jax.scipy.special' has no attribute 'erfcx'
 -----------------------------------------------------------------------------------------------------------

Do you know what is erfcx?

Thanks

**Comment by ricardoV94** [comment]
It's an operator that is not implemented in JAX, meaning we cannot convert that specific PyMC model to JAX.

**Comment by twiecki** [comment]
Which Op is it?

**Comment by ricardoV94** [comment]
Erfcx https://github.com/aesara-devs/aesara/issues/609
