### ISSUE TITLE
`convert_size` wrongly assumes symbolic sizes have to be scalars

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5394]
```python
import pymc as pm
import aesara.tensor as at

s = at.scalar('s')
size = at.stack([s, s])
x = at.random.normal(size=size)
x.eval({s: 2})
# array([[-0.66285345,  0.97341598],
#        [ 0.05158132,  2.03399059]])

pm.Normal.dist(size=size)
# ValueError: The `size` parameter must be a tuple, TensorVariable, int or list. Actual: <class 'aesara.tensor.var.TensorVariable'>
```

The error comes from this check here:
https://github.com/pymc-devs/pymc/blob/915592235ea6920689f89bece48e2d679e8ed4f1/pymc/distributions/shape_utils.py#L475

CC @michaelosthege

**Comment by michaelosthege** [comment]
The functions signature is correct, but the implementation doesn't account for the `TensorVariable` case it advertised in the type hint.

Probably needs `TensorVariable` to be added to the allow-list in the first `else` branch.
Plus a `raise` on `size.ndim > 1`.

**Comment by 5hv5hvnk** [comment]
I did some changes and the code executes without any error 
in line 475 `size.ndim>=1`
in line 476 `size=tiple(size,)`

how should I proceed further (should I generate the pull request?)

**Comment by ricardoV94** [comment]
@5hv5hvnk I am not sure what you are proposing is correct but feel free to open a PR and we can have a look over there, with the actual code changes :)

**Comment by 5hv5hvnk** [comment]
Oh okay is there a way I can run tests on it to check if its been fixed ?

**Comment by ricardoV94** [comment]
You can try `pytest pymc/tests/test_distributions_random.py` to check nothing obvious is broken. You should also add a mew test for this new logic, wherever the relevant function is being tested. 

When you open a PR with us it will automatically run the entire test suite plus whatever new tests you added.

**Comment by 5hv5hvnk** [comment]
I have opened PR #5417 please have a look at it and share if any changes I have to make in order to fix the issue.
