### ISSUE TITLE
`DiscreteUniform` `moment unitest may not be complete.

### ISSUE THREAD

**Issue by zoj613** [pymc-devs/pymc#5405]
Not sure if this is intentional or not but it looks like the unittest for `DiscreteUniform` is not complete and is missing the assertion line other tests include. See:
https://github.com/pymc-devs/pymc/blob/fa233aa78d92b986f80cfc3a33c3bc971f8848b4/pymc/tests/test_distributions_moments.py#L749-L752

cc @ricardoV94

**Comment by ricardoV94** [comment]
Definitely, can you open a PR?
