### ISSUE TITLE
Consider removing `test_distributions.py` from arviz-compatibility workflow

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5410]
This job usually takes more than 45-50 minutes in MacOS, while all others jobs (Ubuntu/Windows/MacOs) take less than 30 minutes, so we end up in fact always waiting for this one. This divergence is pretty clear here:

![image](https://user-images.githubusercontent.com/28983449/151337834-9766e2bb-8f84-4134-ba12-4bd2b768ffbd.png)

Blue: `arviz-compatibility.yml`
Orange: `pytest.yml` (includes all tests in `arviz-compatibility.yml` and more)

Obtained from https://share.streamlit.io/koaning/gitlit/main

We could consider replacing this test by something else, perhaps a more `CI-like` suite of tests as opposed to this number crunching one, which is already covered in `pytest.yml` (Ubuntu 18.04 only).

**Comment by parthb83** [comment]
Hey @ricardoV94! Do you want to remove `test_distributions.py` only from the `macOS-latest` workflow or from the `ubuntu-latest` workflow as well in `arviz_compat.yml`?

**Comment by ricardoV94** [comment]
We could remove from both, but more importantly we should think what tests to use instead

**Comment by parthb83** [comment]
So should we create a new test or replace it with an existing one? If we replace it with an existing one, which test/set of tests would be better according to you?

**Comment by michaelosthege** [comment]
There are good reasons to combine all workflows into one (#5041) and then we could easily shift tests around to reduce wall-clock runtime.
For `test_distributions.py` in particular I think it should be split up into 2-3 parts. Then we could run parts on different operating systems.

**Comment by ricardoV94** [comment]
We could split the distribution tests according to their modules: `discrete`, `continuous`, `multivariate`
