### ISSUE TITLE
Recently tightened test just failed

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5411]
This line was recently changed in https://github.com/pymc-devs/pymc/pull/5366

https://github.com/pymc-devs/pymc/blob/4eecf14f067f546073b935d9fc1b7ef9b913a0e3/pymc/tests/test_sampling.py#L511

And now failed in:

https://github.com/pymc-devs/pymc/runs/4963994741?check_suite_focus=true

Given this is a recent change, it suggests to me the new bound may be too strict for the frequency of tests we run. 

CC @austereantelope

**Comment by austereantelope** [comment]
@ricardoV94 After more investigation, we have found that by tightening this bound we do not gain much (only 0.02 increase in mutation score). I think we can revert the test back to pval > 0.001 to keep the original pass rate. Let me know what you think. Thanks!

**Comment by ricardoV94** [comment]
@austereantelope that sounds good
