### ISSUE TITLE
SMC Sampler - AttributeError: 'ValidatingScratchpad' object has no attribute 'test_value' when running parallel 

### ISSUE THREAD

**Issue by NathanielF** [pymc-devs/pymc#5412]
I'm also getting the an Attribute error with the SMC sampler when trying to replicate the Approximate Bayesian Computation referenced in https://bayesiancomputationbook.com/notebooks/chp_08.html

```python
  import pandas as pd
  import numpy as np
  from scipy import stats
  from scipy import optimize
  import sys
  import pymc3 as pm
  import sys
  
  class g_and_k_quantile:
      def __init__(self):
          self.quantile_normal = stats.norm(0, 1).ppf
          self.pdf_normal = stats.norm(0, 1).pdf
  
      def ppf(self, x, a, b, g, k):
          z = self.quantile_normal(x)
          return a + b * (1 + 0.8 * np.tanh(g*z/2)) * ((1 + z**2)**k) * z
  
      
      def rvs(self, samples, a, b, g, k):
          x = np.random.uniform(0, 1, samples)
          return self.ppf(x, a, b, g, k)
  
      def cdf(self, x, a, b, g, k, zscale=False):   
          optimize.fminbound(f, -5, 5)
  
      def pdf(self, x, a, b, g, k):
          #z = cdf(x, a, b, g, k)
          z = x
          z_sq = z**2
          term1 = (1+z_sq)**k
          term2 = 1+0.8*np.tanh(g*x/2)
          term3 = (1+(2*k+1)*z_sq)/(1+z_sq)
          term4 = 0.8*g*z/(2*np.cosh(g*z/2)**2)
  
          deriv = b*term1*(term2*term3+term4)
          return self.pdf_normal(x) / deriv
  
  
  def octo_summary(x):
      e1, e2, e3, e4, e5, e6, e7 = np.quantile(x, [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875])
      sa = e4
      sb = e6 - e2
      sg = (e6 + e2 - 2*e4)/sb
      sk = (e7 - e5 + e3 - e1)/sb
      return np.array([sa, sb, sg, sk])
  
  pollution_df = pd.read_csv('../input_data/pollution.csv')
  bsas_co = pollution_df["co"].dropna().values
  
  gk = g_and_k_quantile()
  def gk_simulator(a, b, g, k):
      return gk.rvs(len(bsas_co), a, b, g, k)
  
  bsas_co = np.array([0.5, 0.4, 0.3])
  
  
  if __name__ == '__main__':
  
      with pm.Model() as gkm:
          a = pm.HalfNormal('a', sd=1)
          b = pm.HalfNormal('b', sd=1)
          g = pm.HalfNormal('g', sd=1)
          k = pm.HalfNormal('k', sd=1)
  
          s = pm.Simulator('s', gk_simulator, params=[a, b, g, k],
                           sum_stat=octo_summary,
                           epsilon=0.1,
                           observed=bsas_co)
  
          trace_gk, sim_data_gk = pm.sample_smc(kernel="ABC",
                                                parallel=True,
                                                save_sim_data=True
                                                )
```

![image](https://user-images.githubusercontent.com/10588167/151331375-470d1876-44ce-4fc7-970a-3fa81b55e7f0.png)

Environment: 

name: bmcp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - pip=21.2.4
  - python-graphviz==0.17
  - pip:
    - arviz==0.11.2
    - ipython==7.26.0
    - jupyter==1.0.0
    - jupyterlab==3.2.1
    - matplotlib==3.4.3
    - mkl==2021.3.0
    - numpy==1.19.5
    - numpyro==0.7.2
    - pandas==1.3.2
    - pydot==1.4.2
    - pymc3==3.11.4
    - statsmodels==0.12.2
    - scipy==1.7.1
    - tensorflow_probability==0.15.0
    - tensorflow==2.7.0
    - theano-pymc==1.1.2
    - xarray== 0.19.0

---------
UPDATE - The error disappears if i remove the parrallel=True, which is weird. So probably related to multithreading rather than purely the attribute error above

![image](https://user-images.githubusercontent.com/10588167/151335436-7c042443-822c-4abf-8714-be84b19003a8.png)

**Comment by ricardoV94** [comment]
It seems the old codebase was relying too much on there being a `test_value` which seems to somehow break in the parallel mode for you:

https://github.com/pymc-devs/pymc/blob/b5bb2e41b0be2e0b6d86fb0b77aa6683b9b6524d/pymc3/theanof.py#L276

This is not an issue in our next release, so we will probably not fix it. I am not sure it is a trivial fix either, because many things rely on test values in the old codebase. If anyone wants to try this is how that line looks like now:

https://github.com/pymc-devs/pymc/blob/1b320709703f3a98146375040f4afb970e83a2bb/pymc/aesaraf.py#L640-L641

**Comment by ricardoV94** [comment]
Would it be possible for you to use `parallel=False`? If not, I suggest you try our newer beta release

**Comment by NathanielF** [comment]
Thanks Ricardo, yes that's fine for me at the minute. Am just using parallel=False and it seems to run fine. Just thought you might want to know.
