### ISSUE TITLE
Update CONTRIBUTING.md to point to actual contributing guide in docs

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5425]
## Description of your problem
~~I'm trying to contribute docs but I'm not sure how to compile them. Contributing guide doesn't tell me how to go about this, just how to push changes, and mostly focuses on code changes~~

https://github.com/pymc-devs/pymc/blob/main/CONTRIBUTING.md

See @OriolAbril's comment below

**Comment by OriolAbril** [comment]
We do at https://docs.pymc.io/en/latest/contributing/build_docs.html. We should update the github contributing thing to be only a link to the actual contributing guide in the docs
