### ISSUE TITLE
Add remove-toctrees to dev dependencies

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5426]
## Description of your problem
Installed dev environment and tied compiling docs and got an exception that `remove-toctrees` was not installed. We should remove this friction by adding a requirements-docs.txt 

https://github.com/executablebooks/sphinx-remove-toctrees
![image](https://user-images.githubusercontent.com/7213793/151708682-62fb26da-d28a-478d-b334-1afc297b6b13.png)

**Comment by ricardoV94** [comment]
Can't we just add it to the dev dependencies?

**Comment by canyon289** [comment]
That works too!

**Comment by danhphan** [comment]
Hi @canyon289 @ricardoV94 I'm happy to work on this task :smile:

**Comment by canyon289** [comment]
Thanks @danhphan, it's assigned to you. let us know if you need any help

**Comment by OriolAbril** [comment]
It is already in https://github.com/pymc-devs/pymc/blob/main/conda-envs/environment-dev-py38.yml (otgerwise readthedocs check would not have passed). It is however a new doc dependency I added very recently and you probably used the old env withoyt it to create your current conda env

**Comment by danhphan** [comment]
Hi yes, that's good to know :D
