### ISSUE TITLE
with pm.Model raises an unhelpful exception. Can it be more helpful?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5436]
## Description of your problem
This is just a suggestion

if I write I get the attribute error below. What if we modify the exception to be more useful, perhaps "AttributeError: Did you mean to write model()" or something like that? It's a little change but reduces a small amount of friction for the users that make this mistake.
```
with pm.Model:
  ...
```

![image](https://user-images.githubusercontent.com/7213793/151911900-319fbbf4-bfac-4b79-8188-bea548132683.png)

**Please provide the full traceback.**

```python
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_21635/3894983869.py in <module>
----> 1 with pm.Model as pmodel:
      2     pm.Normal("scalar") # shape=()

AttributeError: __enter__
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/ Version: '4.0.0b2'
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by fonnesbeck** [comment]
I doubt it. You are at the mercy of the context manager there, so its not going to be straightforward to customize the exception.

**Comment by canyon289** [comment]
Thanks @fonnesbeck

**Comment by iuimaki** [comment]
Have you solved this problem? I also met such error message and don't know how to fix it.
