### ISSUE TITLE
question about speed

### ISSUE THREAD

**Issue by jacobeisenstein** [pymc-devs/pymc#544]
![image](https://cloud.githubusercontent.com/assets/905244/2972559/807f8c38-db75-11e3-9871-b0c65f85a2f9.png)

Noob question. I'm trying pymc for what seems like a relatively simple model. But the NUTS sampling is really slow. What's weird is that the CPU time is 15 minutes, when the sampling time is just 2 seconds. It seems like there's some startup cost to the sample() call that I'm not understanding. The design matrix is full-rank. It's plenty fast when I set the step to Metropolis instead of NUTS.

**Comment by jsalvatier** [comment]
Hmm, @twiecki is most familiar with the glm stuff. Seems like it must be
taking a long time to compile, finding the local minimum, or to find the
scaling parameters in the NUTS setup. How many parameters do you have? Also
the sampling seems a bit slow too, it may be finding bad scaling
parameters.

**Comment by twiecki** [comment]
You actually don't have to call `find_MAP()` manually as `glm()` already initializes the model. So maybe try again with the starting values set by glm?

**Comment by jacobeisenstein** [comment]
Thanks. I'll try without find_MAP and see if that works better. The number of parameters was less than 100.

**Comment by jacobeisenstein** [comment]
Removing <code>find_MAP()</code> made no noticeable difference. I ran a smaller model, only a few parameters (TAG can take three values, GDEL is binary). Still takes a couple of minutes with NUTS, versus a fraction of a second with Metropolis. HamiltonianMC is somewhere in between. When I run it on a different machine, HamiltonianMC is equally fast as Metropolis, but NUTS is still slow.

Maybe I don't have something configured properly? Anyway, this isn't on the critical path for me, so I'm probably going to drop it for now. But I thought you guys might want to know that the speed performance of these samplers can be really variable.

![image](https://cloud.githubusercontent.com/assets/905244/3008512/55645c02-debf-11e3-85cc-2aacf41d60e3.png)

**Comment by jsalvatier** [comment]
(sorry for the late response, I meant to send this earlier)

Thank you for the feedback. This kind of thing is very valuable.

Oh, actually the %time'd part is just the step method setup, so it can't be
only find_MAP that is expensive. It must either be compilation or finding
the scaling parameters.

If you turn off computing test values, does this speed things up much? `
theano.config.compute_test_value = 'off'`

**Comment by fonnesbeck** [comment]
I'm also getting some pretty slow sampling, even for our simple built-in example:

![slow](http://d.pr/i/3pVt+)

**Comment by twiecki** [comment]
My strong guess is that our likelihoods (and/or the gradients) are slow. So I think we'd need a profiling setup where we compare individual likelihoods from pymc2 to pymc3. Once we establish that it should be much easier to drill deeper into what's happening at that level.

**Comment by fonnesbeck** [comment]
[Here is the profiling output](http://d.pr/n/K50c) for the above example. Lots of time spent in `theano.tensor.elemwise.Elemwise`.

**Comment by fonnesbeck** [comment]
Interesting: It runs much faster under HMC, so it appears to be a NUTS-specific issue:

![hmc](http://d.pr/i/h1ow+)

**Comment by twiecki** [comment]
Revisiting this. The other samplers are faster but don't converge. I suspect that the high correlation is causing NUTS problems. 

The time is all spent in `build_tree`. If you pass in a scaling matrix estimated via `approx_hessian()` sampling is done 0.8 secs.

**Comment by twiecki** [comment]
@jacobeisenstein Can you try:

``` python
C = approx_hessian(model.test_point)
step = NUTS(scaling=C)
```

to see if that speeds things up.

**Comment by jacobeisenstein** [comment]
Yes, that helps. I can't find the exact code and data from before, but for a related problem, I get the following wall times:
- metropolis: 9s
- HMC: 49s
- NUTS: 45s
- NUTS + approx_hessian: 15s

As before, the sampling times are a small fraction of the wall times: 2s for NUTS without the approx_hessian, 0.9s with it.

**Comment by twiecki** [comment]
> As before, the sampling times are a small fraction of the wall times: 2s for NUTS without the approx_hessian, 0.9s with it.

That's to be expected. Theano is optimized for execution, not compilation.

**Comment by twiecki** [comment]
As the sampling is fast with correct initializtion I'm going to close this.
