### ISSUE TITLE
Refactor Multivariate distributions due to new meaning of size

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5446]
The next Aesara release will include https://github.com/aesara-devs/aesara/pull/446 which altered the meaning of `size` for multivariate distributions, to be more consistent with that of univariate distributions.

Size will now specify the number of replications + dimensions implied by batched parameters. It is equivalent to `shape[:-ndim.supp]`. We will likely need to update our multivariate distributions and/or some tests (e.g. in [test_distributions_random.py](https://github.com/pymc-devs/pymc/blob/1005d20b3c12d9b9a424c069f6a0f9962d73c41d/pymc/tests/test_distributions_random.py))

These changes should also be incorporated in https://github.com/pymc-devs/pymc/pull/5437

**Comment by michaelosthege** [comment]
Important detail:
It's `size == shape[:len(shape)-ndim_supp]`, **NOT** `shape[:-ndim_supp]`

That's because
```python
>>> (1,2,3)[:-0]
()
```

**Comment by ricardoV94** [comment]
> Important detail:
> It's `size == shape[:len(shape)-ndim_supp]`, **NOT** `shape[:-ndim_supp]`
> 
> That's because
> ```python
> >>> (1,2,3)[:-0]
> ()
> ```

Stupid -0 slicing heh :D

**Comment by twiecki** [comment]
@michaelosthege Do you have time to work on this?

**Comment by michaelosthege** [comment]
I will pick it up once the CI is green again on main. Don't want to solve two problems at the same time

**Comment by twiecki** [comment]
OK, CI is green again.
