### ISSUE TITLE
Remove pin of SciPy 1.8.0 once we run Aesara 2.4.0

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5448]
## Description of your problem
 There's a new SciPy release 1.8.0 and they refactored their public/private API.

https://github.com/scipy/scipy/releases/tag/v1.8.0

Aesara has some import incompatibilities and this is causing our CIs to fail.

Related Aesara issue: https://github.com/aesara-devs/aesara/issues/810

The incompatibility will most probably affect `v3` too, so we'll want to backport a pin of the upper SciPy version.

## Versions and main components
* PyMC/PyMC3 Version: `<=3.11.4`, `<=4.0.0b2`
* Aesara/Theano Version: all `<=2.3.8`

**Comment by ricardoV94** [comment]
The temporary pin can be removed once we update our Aesara dependency (pending #5446)
