### ISSUE TITLE
Memory overload on apple M1 max

### ISSUE THREAD

**Issue by fbarfi** [pymc-devs/pymc#5465]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
[Your code here]
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
[The complete error output here]
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version:
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by ericmjl** [comment]
@fbarfi thanks for pinging in. Unfortunately, I don't see much detail here that can help us debug, so I'm going to close the issue. Please feel free to update the issue with additional detail and then re-open.
