### ISSUE TITLE
Remove Pandas dependency

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5469]
Pandas is quite a large dependency that is not truly critical to PyMC. AFAIK we use it in two contexts (there could be more):

1. Format the output of `model.point_logps` (old `model.check_test_point`) by converting it into a Pandas Series. We can do just fine with a dictionary here
2. Do some data wrangling / detect NAN when a distribution is "observed". We can probably keep supporting this with an optional pandas import (try/except).

**Comment by twiecki** [comment]
Agreed.
