### ISSUE TITLE
Installing pymc3 with sampling_jax

### ISSUE THREAD

**Issue by fteufel** [pymc-devs/pymc#5470]
## Description of your problem

I tried following the tutorial at https://docs.pymc.io/en/v3/pymc-examples/examples/samplers/GLM-hierarchical-jax.html?highlight=jax to sample using JAX. The `pymc3jax` branch described there does not seem to exist anymore. I also tried installing the current main from github, but also there
```
import pymc3.sampling_jax

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-fae6c727f0a1> in <module>
----> 1 import pymc3.sampling_jax

ModuleNotFoundError: No module named 'pymc3.sampling_jax
```

How can `sampling_jax` currently be installed?

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* How did you install PyMC/PyMC3: pip and from main

**Comment by twiecki** [comment]
Yes, JAX support was dropped in 3.11.4, you would need to use pymc 4.0.0b2.
