### ISSUE TITLE
Remove backends/tracetab.py

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5473]
PyCharm tells me that the two functions from this module are only used in the respective tests :D 

https://github.com/pymc-devs/pymc/blob/d018cba35d8cb685832cf9b561b636882f8b9df4/pymc/backends/tracetab.py

https://github.com/pymc-devs/pymc/blob/d018cba35d8cb685832cf9b561b636882f8b9df4/pymc/tests/test_tracetab.py

If this is not being used anywhere, we should remove it.

**Comment by twiecki** [comment]
Fixed by https://github.com/pymc-devs/pymc/pull/5479.
