### ISSUE TITLE
Conflicting declarations of function chbevl

### ISSUE THREAD

**Issue by tautschnig** [pymc-devs/pymc#549]
Hi,

During a rebuild of all Debian packages in a clean sid chroot (using cowbuilder
and pbuilder) the build failed with the following error. Please note that we
use our research compiler tool-chain (using tools from the cbmc package), which
permits extended reporting on type inconsistencies at link time.

[...]
/usr/bin/gfortran -Wall -Wall -shared build/temp.linux-x86_64-2.7/cephes/i0.o build/temp.linux-x86_64-2.7/cephes/c2f.o build/temp.linux-x86_64-2.7/cephes/chbevl.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/pymc/flibmodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortranobject.o build/temp.linux-x86_64-2.7/pymc/flib.o build/temp.linux-x86_64-2.7/pymc/histogram.o build/temp.linux-x86_64-2.7/pymc/flib_blas.o build/temp.linux-x86_64-2.7/pymc/blas_wrap.o build/temp.linux-x86_64-2.7/pymc/math.o build/temp.linux-x86_64-2.7/pymc/gibbsit.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/pymc/flib-f2pywrappers.o -L/usr/lib -llapack -lblas -lgfortran -o build/lib.linux-x86_64-2.7/pymc/flib.so

error: conflicting function declarations "chbevl"
old definition in module i0 file cephes/protos.h line 22
double (double, void *, signed int)
new definition in module chbevl file cephes/chbevl.c line 67
double (double x, double *array, signed int n)

While this will work correctly at present, it seems that i0.c could be compiled in different ways and passing anything but a double array to chbevl will cause invalid memory accesses. Thus the following two declarations should be adjusted:

http://sources.debian.net/src/pymc/2.2+ds-1/cephes/protos.h?hl=22#L22
http://sources.debian.net/src/pymc/2.2+ds-1/cephes/i0.c?hl=355#L355

Best,
Michael

**Comment by fonnesbeck** [comment]
Done, and passes tests.
