### ISSUE TITLE
RuntimeError: Could not import 'mkl'.

### ISSUE THREAD

**Issue by purna135** [pymc-devs/pymc#5494]
## Description of your problem
After completing all of the procedures outlined in https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Windows), running pytest returns the following errors:

```
E   RuntimeError:
E   Could not import 'mkl'.  If you are using conda, update the numpy
E   packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
E   your environment for MKL 2018.
E
E   If you have MKL 2017 install and are not in a conda environment you
E   can set the Aesara flag blas__check_openmp to False.  Be warned that if
E   you set this flag and don't set the appropriate environment or make
E   sure you have the right version you *will* get wrong results.
```

I followed the steps below to fix these issues.
```
conda install mkl==2020.4
conda install mkl-service==2.3.0
set MKL_THREADING_LAYER=GNU
```
yet I'm still getting the issues listed below and the error was not fixed by `conda install aesara`
```
E   ModuleNotFoundError: No module named 'aesara'
```

## Versions and main components

* PyMC/PyMC3 Version: v4
* Aesara/Theano Version: 2.3.8 
* Python Version: 3.9.7
* Operating system: Windows 10
* How did you install PyMC/PyMC3 (conda/pip): conda

**Comment by danhphan** [comment]
Hi @purna135 , this may help:
https://discourse.pymc.io/t/getting-a-working-pymc3-windows-10-installation-using-anaconda-an-installation-guide/8641

**Comment by purna135** [comment]
Thank you @danhphan 
Let me chose this issue.
