### ISSUE TITLE
Add test for `_get_scaling`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5515]
This function has a somewhat long and complicated sequence of conditional branches. AFAICT there is no direct test, so we should add one that covers all the expected cases to facilitate future maintenance and refactoring.

Bonus points for adding type hints

https://github.com/pymc-devs/pymc/blob/114e4391f6950eb9454381d41cf656b82ce137ea/pymc/distributions/logprob.py#L46-L107

Related to #4582

**Comment by Diwakar-Gupta** [comment]
@ricardoV94 can you share some resources to know what exactly `_get_scaling` does.

**Comment by chritter** [comment]
@Icyshaman and I are working on this issue.
