### ISSUE TITLE
Issues finding valid starting values for models under HMC

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#552]
In [this notebook](http://nbviewer.ipython.org/gist/fonnesbeck/04f5da535d71c8377df6), I'm calling `find_map` to get a starting point for the model, but you will notice it fails with a `ValueError`:

```
Optimization error: max, logp or dlogp at max have non-finite values. Some values may be outside of distribution support
```

For some reason the Gamma stochastic has a test point of an array of zeros, which are invalid for this distribution.

**Comment by fonnesbeck** [comment]
Also note that, for this model, passing a dict of valid values returns a `PositiveDefiniteError` for every combination of values that I've tried. Selection of valid starting values for NUTS/HMC is something that has to get automated, otherwise we will get this problem cropping up for bigger models (this model is not very big).

**Comment by fonnesbeck** [comment]
Changed the title of the issue to be more general.

**Comment by fonnesbeck** [comment]
Even restricting the NUTS sampler to the `beta` node, which is just a vector-valued normal results in a `PositiveDefiniteError`:

```
with model:
    #start = find_MAP()
    start = {dL0: np.random.gamma(0.1, 0.1, size=T),
             c: 1,
             r: 1,
             beta: np.random.normal(size=7)}
    step1 = NUTS(vars=[beta], scaling=start)
    step2 = Metropolis(vars=[c,r,dL0], scaling=start)
    trace = sample(2000, (step1, step2), start)
```

This is curious, since there is no reason for that to be non-positive definite. Am I doing something wrong here?

**Comment by bjedwards** [comment]
This could be a case of a bad selection of `model.test_point`, what happens if you give `find_MAP` different start values? The other option might be to use a different optimization technique for `find_MAP`. There are a few options in [this example](http://nbviewer.ipython.org/github/pymc-devs/pymc/blob/master/pymc/examples/discrete_find_MAP.ipynb).

**Comment by fonnesbeck** [comment]
`find_MAP` tends to diverge here, populating the gamma-distributed variable with negative numbers, which is outside its support. I tried using Powell's as the `fmin` which treated the gamma parameters better, but still diverged with large negative dlogp values. I'll triple-check the model specification.

**Comment by fonnesbeck** [comment]
I've [updated the notebook](http://nbviewer.ipython.org/gist/fonnesbeck/04f5da535d71c8377df6) to include the original BUGS model, incase someone can spot the issue.

**Comment by fonnesbeck** [comment]
I've pinpointed the issue regarding the infinite logp values -- our Poisson does not allow the parameter to equal zero, which strictly speaking is correct, but does not allow us to have indicators that mask positive means, which is helpful in some models. I now recall this cropping up in PyMC 2, and we do constrain the parameter to non-negative there (which is consistent with BUGS). 

I still cannot for the life of me get a positive definite scaling for this model, however.

**Comment by jsalvatier** [comment]
Yeah, its positive definitive issue seeming like a bigger and bigger
problem.

On Sat, Jun 21, 2014 at 12:04 PM, Chris Fonnesbeck <notifications@github.com

**Comment by jsalvatier** [comment]
How much has this been an issue recently? 

Currently, the transform branch seems to fix this if you replace `step = NUTS(scaling=scaling)`.

Has this been an issue elsewhere? Anyone have examples?

**Comment by twiecki** [comment]
Can this be closed?

**Comment by fonnesbeck** [comment]
Yes. There are still issues with NUTS startup, but this particular issue is solved.
