### ISSUE TITLE
Review potentially outdated docs

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#5538]
There are some files closely related to v3 internals that should be reviewed to choose if we want to update and keep them or get rid of them (and maybe write something similar but not the same from scratch).

Those files are:

* [x] https://github.com/pymc-devs/pymc/blob/main/docs/source/guides/Gaussian_Processes.rst by @canyon289 
* [x] https://github.com/pymc-devs/pymc/blob/main/docs/source/guides/Probability_Distributions.rst being refactored by @juanitorduz 
* [x] https://github.com/pymc-devs/pymc/blob/main/docs/source/PyMC_and_Aesara.rst Claimed by @ricardoV94 
* [x] https://github.com/pymc-devs/pymc/blob/main/docs/source/Advanced_usage_of_Aesara_in_PyMC.rst Todo: Remove by @AlexAndorra

**Comment by juanitorduz** [comment]
Hi! @ricardoV94 has some very useful notes which I could build on top of. I will open a PR soon.

**Comment by ricardoV94** [comment]
### Advanced_usage_of_Aesara_in_PyMC.rst

I think we can remove it.
1. It mentions shared variables, which are wrapped in the more user friendly `pm.MutableData`, 
2. It shows the creation of an `Op`, which we have some examples of in pymc-examples. The one advantage of that `Op` example is that unlike those in pymc-examples it is an intermediate `Op` and not just a likelihood term, which might bridge a gap in the documentation. In any case a separate issue for a doc or pymc-examples should be made for that

Tracking issue #5729 

### PyMC_And_Aesara.rst
This one is not in a terrible state, but should be expanded beyond describing how variables are used for the logp graph, to also explain how RandomVariables are used for the random graph, and how PyMC goes back and forth between those. That's probably where @juanitorduz would be contributing

Shoud be replaced by #5721 

### Probability_Distributions.rst
We can replace this entirely by the new dev guide on how to develop new distributions and by updating this pymc-example: https://github.com/pymc-devs/pymc-examples/pull/185

### Gaussian_Processes.rst
Not my expertise, perhaps @bwengals can chime in.

Tracking issue #5720

**Comment by juanitorduz** [comment]
I do have a working [branch and notebook](https://github.com/juanitorduz/pymc/blob/docs/aesara_pymc_nb/docs/intro_pymc_codebase.ipynb) where I am trying to add comments and understand @ricardoV94 nice intro notebook. Nevertheless, I still have a long way to fully understand. Specifically, starting from section `Graph manipulation 102` things become less clear for me. I would live to work on this one but to be honest it would take much more than initially planned. Hence, if there is some desire to have it soon (in view of the next release) maybe some else could jump in as well :)

**Comment by ricardoV94** [comment]
@juanitorduz no need to include any graph manipulation parts. You can also just open a PR with what you have and iterate from there :)

**Comment by canyon289** [comment]
`Gaussian_Processes.rst` will be updated by a combination of myself and @bwengals over the coming months. if it helps with tracking I can open an issue and assign it to myself.

For now I can add a disclaimer at the top stating its V3 specific and slated for an update

**Comment by AlexAndorra** [comment]
Done: https://github.com/pymc-devs/pymc/pull/5826

**Comment by ricardoV94** [comment]
Anyone objects removing https://github.com/pymc-devs/pymc/blob/main/docs/source/PyMC_and_Aesara.rst now that we have https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_aesara.html?

**Comment by OriolAbril** [comment]
No, sounds good
