### ISSUE TITLE
add coords argument to pymc.set_data

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#5547]
`pymc.set_data` is a wrapper around `pymc.Model.set_data` method that supports setting multiple data variables at the same time and it is currently missing the `coords` argument. Adding a coord argument to pymc.set_data and passing it to the method when called should already work.

Sources
* [pymc.set_data](https://github.com/pymc-devs/pymc/blob/4223b6e0600232b1074c1959337a1bea43b570b9/pymc/model.py#L1727) (the one to be updated)
* [set_data method](https://github.com/pymc-devs/pymc/blob/4223b6e0600232b1074c1959337a1bea43b570b9/pymc/model.py#L1126)

cc @michaelosthege

**Comment by purna135** [comment]
I would like to work on this.

**Comment by OriolAbril** [comment]
Hi @purna135, sorry for the late reply. @soma2000-lang has already submitted a PR so you should not work on this issue to avoid duplicated work. 

@soma2000-lang (to be read after https://github.com/pymc-devs/pymc/pull/5588#pullrequestreview-910060108). I know finding issues to contribute when getting started with a new library is tricky, I personally struggled with it when I started and I still struggle sometimes when trying to contribute to new libraries, even after years being a maintainer of PyMC and ArviZ. However, you should still find an issue, comment there that you are planning to work on it (or simply start with "I am interested but the issue is not clear" before saying you'll work on that) and then submit the pull request. We are many people working and contributing to pymc, and we do not want to work double. If you send PRs for issues that have been assigned to someone else it is probable that we'll end up with two PRs that fix the same issue and would be forced to reject one of them. We don't want to reject PRs not want any contributor to work on changes that are eventually discarded and following this process is the way we have to make sure we don't have to discard anyone's work.

I would also like to highlight the upcoming office hours, that both of you can attend and ask any and all questions related to contributing to PyMC and GSoC, there will be some of the potential GSoC mentors and participants from previous rounds attending. See https://discourse.pymc.io/t/pymc-office-hours/9018. 

I am really happy to see people interested in PyMC and I hope everyone can find issues to work on and can submit a proposal and be accepted for GSoC. Which is also partially why I dedicate a lot of my time to documentation efforts hoping to make using and contributing to PyMC more and more clear every day, but like with the rest of the developers, I do that on my free time so my availability is not constant or even regular and the ammount of work and reviews I can do is limited so I often answer late or are forced to answer in very short comments that might not be very clear.

**Comment by purna135** [comment]
> Hi @purna135, sorry for the late reply. @soma2000-lang has already submitted a PR so you should not work on this issue to avoid duplicated work.

@OriolAbril Thank you for your response; I'm currently working on other issues.

**Comment by soma2000-lang** [comment]
> Hi @purna135, sorry for the late reply. @soma2000-lang has already submitted a PR so you should not work on this issue to avoid duplicated work. 
> 
> @soma2000-lang (to be read after https://github.com/pymc-devs/pymc/pull/5588#pullrequestreview-910060108). I know finding issues to contribute when getting started with a new library is tricky, I personally struggled with it when I started and I still struggle sometimes when trying to contribute to new libraries, even after years being a maintainer of PyMC and ArviZ. However, you should still find an issue, comment there that you are planning to work on it (or simply start with "I am interested but the issue is not clear" before saying you'll work on that) and then submit the pull request. We are many people working and contributing to pymc, and we do not want to work double. If you send PRs for issues that have been assigned to someone else it is probable that we'll end up with two PRs that fix the same issue and would be forced to reject one of them. We don't want to reject PRs not want any contributor to work on changes that are eventually discarded and following this process is the way we have to make sure we don't have to discard anyone's work.
> 
> I would also like to highlight the upcoming office hours, that both of you can attend and ask any and all questions related to contributing to PyMC and GSoC, there will be some of the potential GSoC mentors and participants from previous rounds attending. See https://discourse.pymc.io/t/pymc-office-hours/9018. 
> 
> I am really happy to see people interested in PyMC and I hope everyone can find issues to work on and can submit a proposal and be accepted for GSoC. Which is also partially why I dedicate a lot of my time to documentation efforts hoping to make using and contributing to PyMC more and more clear every day, but like with the rest of the developers, I do that on my free time so my availability is not constant or even regular and the ammount of work and reviews I can do is limited so I often answer late or are forced to answer in very short comments that might not be very clear. 

@OriolAbril I would definitely attend the meeting.
