### ISSUE TITLE
error message : Graph contains shared variables with default_update which cannot be safely replaced.

### ISSUE THREAD

**Issue by fbarfi** [pymc-devs/pymc#5557]
#Getting error message :
Graph contains shared variables with default_update which cannot be safely replaced.

I am not using any shared variables in my code/model

Please provide a minimal, self-contained, and reproducible example.

pm.sampling_jax.sample_numpyro_nuts()
Please provide the full traceback of any errors.

```
[ValueError                                Traceback (most recent call last)
Input In [7], in <module>
      1 SEED =123456
      3 with SAR_model:
----> 4         idata = pm.sampling_jax.sample_numpyro_nuts(draws=100,tune=100)

File /opt/homebrew/Caskroom/miniforge/base/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/sampling_jax.py:230, in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, initvals, model, var_names, progress_bar, keep_untransformed, chain_method, idata_kwargs, nuts_kwargs)
    221 print("Compiling...", file=sys.stdout)
    223 init_params = _get_batched_jittered_initial_points(
    224     model=model,
    225     chains=chains,
    226     initvals=initvals,
    227     random_seed=random_seed,
    228 )
--> 230 logp_fn = get_jaxified_logp(model)
    232 if nuts_kwargs is None:
    233     nuts_kwargs = {}

File /opt/homebrew/Caskroom/miniforge/base/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/sampling_jax.py:102, in get_jaxified_logp(model)
    100 def get_jaxified_logp(model: Model) -> Callable:
--> 102     logp_fn = get_jaxified_graph(inputs=model.value_vars, outputs=[model.logpt()])
    104     def logp_fn_wrap(x):
    105         # NumPyro expects a scalar potential with the opposite sign of model.logpt
    106         res = logp_fn(*x)[0]

File /opt/homebrew/Caskroom/miniforge/base/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/sampling_jax.py:79, in get_jaxified_graph(inputs, outputs)
     73 def get_jaxified_graph(
     74     inputs: Optional[List[TensorVariable]] = None,
     75     outputs: Optional[List[TensorVariable]] = None,
     76 ) -> List[TensorVariable]:
     77     """Compile an Aesara graph into an optimized JAX function"""
---> 79     graph = _replace_shared_variables(outputs)
     81     fgraph = FunctionGraph(inputs=inputs, outputs=graph, clone=True)
     82     # We need to add a Supervisor to the fgraph to be able to run the
     83     # JAX sequential optimizer without warnings. We made sure there
     84     # are no mutable input variables, so we only need to check for
     85     # "destroyers". This should be automatically handled by Aesara
     86     # once https://github.com/aesara-devs/aesara/issues/637 is fixed.

File /opt/homebrew/Caskroom/miniforge/base/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/sampling_jax.py:62, in _replace_shared_variables(graph)
     59 shared_variables = [var for var in graph_inputs(graph) if isinstance(var, SharedVariable)]
     61 if any(hasattr(var, "default_update") for var in shared_variables):
---> 62     raise ValueError(
     63         "Graph contains shared variables with default_update which cannot "
     64         "be safely replaced."
     65     )
     67 replacements = {var: at.constant(var.get_value(borrow=True)) for var in shared_variables}
     69 new_graph = clone_replace(graph, replace=replacements)

ValueError: Graph contains shared variables with default_update which cannot be safely replaced.
```
## Versions and main components

* PyMC/PyMC3 Version: lates PyMC dev
* Aesara/Theano Version: aesara 2.4
* Python Version: 3.9.10
* Operating system: Apple M1
* How did you install PyMC/PyMC3: (conda/pip) git source

**Comment by fbarfi** [comment]
Forgot to mention that I am not using any shared variable in the code

**Comment by fbarfi** [comment]
My Question: is there a way to change this default_update value for shared variable in the pm.Model or aesara graph? thanks.

**Comment by ricardoV94** [comment]
Can you post a minimal reproducible example? 

Does you model use a Simulator or Scan? Otherwise you should not have issues with shared variables in your model.

**Comment by fbarfi** [comment]
I am using any simulator or scan. 

here is the model:

with pm.Model(coords=coords) as SAR_model:

    tt_X = pm.ConstantData('tt_X',X, dims = ('X_dim_0','X_dim_1'))
    tt_y = pm.ConstantData('tt_y',y, dims = 'X_dim_0')
    tt_W = pm.ConstantData('tt_W',W, dims = ('X_dim_0','W_dim_2'))
    μ_0 = pm.ConstantData('μ_0', μ_ols,dims = 'X_dim_1')
    σ_0 = pm.ConstantData('σ_0', σ_ols ,dims = ('σ_dim_0','σ_dim_1' ))
    tt_N = pm.ConstantData('tt_N',N)
    
    A = pm.Deterministic('A', A_func(ρ, tt_W)  )

    X_β = pm.Deterministic('X_β', X_func(β, tt_X))
    
    η = pm.Deterministic('η', η_func(X_β, A))
    
    Ω = pm.Deterministic('Ω', Ω_func(ω))
    
    z = pm.Deterministic('z', z_func(tt_y,η,ω))
 
    ω = pm.Deterministic('ω',pm.PolyaGamma.dist(h=1, z = η,size=tt_N ))
    
    σ_bar = pm.Deterministic('σ_bar', σ_func(tt_X,Ω,σ_0))
    
    μ_bar = pm.Deterministic('μ_bar', μ_func(σ_bar,tt_X,Ω,A,z,μ_0,σ_0))
    
    β = pm.MvNormal('β', mu = μ_bar,cov = σ_bar, dims = 'X_dim_1')

    ξ = pm.Beta.dist(1.,1.,shape=2)

    ρ = pm.DensityDist('ρ',ξ, tt_W, X_β,Ω,z,ndims_params = [1,2,1,2,1],
                       logp=logp,random=random)
                              
It does not matter I I remove the pm.Deterministic  and just use aesara expressions.

**Comment by fbarfi** [comment]
I meant I AM NOT using simulator or scan  (sorry for the typo)

**Comment by ricardoV94** [comment]
Unfortunately, that example is not minimal nor reproducible. 

We would need something that we can copy/paste and run to trigger the error, but the definition of several functions used in your model is missing.

Also that example would need to be trimmed as much as possible so that only the relevant lines needed to trigger the error are present. Otherwise feedback is likely to be much slower on our end.

**Comment by fbarfi** [comment]
Looking at the SAR_model.__dict__

this is part of what I see a the beginning:
{'_parent': None,
 '_aesara_config': {},
 '_config_context': <aesara.configparser._ChangeFlagsDecorator at 0x29647ecd0>,
 'name': '',
 'check_bounds': True,
 'rng_seeder': RandomState(MT19937) at 0x2956A4640,
 'rng_seq': [RandomStateSharedVariable(<RandomState(MT19937) at 0x2956A4A40>),
  RandomStateSharedVariable(<RandomState(MT19937) at 0x2956A4E40>)],
 '_initial_values': {β: None, ρ: None}

Is this rug_seq key that is causing the problem?

**Comment by ricardoV94** [comment]
No, its coming from either one of the functions you use in your model or a bug on our side that's introducing a shared variable with updates.

**Comment by fbarfi** [comment]
Here are the functions, if you do not mind. 

def ols_model(X,y):
    data = pd.DataFrame(data = X)
    res = sm.OLS(y, data).fit()
    cov = res._results.normalized_cov_params
    coef = res._results.params
    return coef, cov

def logp(value,ξ, tt_W, X_β,Ω,z):
    A = 1. - (value-pm.Beta.dist(ξ[0],ξ[1]))*tt_W
    tt_A = at.tensordot(z,A,[[0],[1]]) - X_β
    log_det  = at.sum(at.log(at.abs(at.linalg.svd(A, compute_uv=False))))
    log_p =  log_det -.5* matrix_dot(tt_A.T, Ω, tt_A)
    return -log_p

def random(ξ, rng=None, size=None):
    return rng.beta(alpha = ξ[0],beta=ξ[1], size=size)

def A_func(x, M):
    return 1. - x*M

def X_func(x, M):
    return at.tensordot(x,M,[[0],[1]])

def η_func(x, M):
    return at.tensordot(x ,matrix_inverse(M),[[0],[1]]) 

def Ω_func(x):
    return at.eye(x.shape[0])* at.outer(at.ones(x.shape), x) 

def z_func(a,b,c):
    return (a - .5*at.ones(b.shape))/c  

def σ_func(X,O,s):
    return matrix_inverse(matrix_dot(X.T, O, X)+ matrix_inverse(s)) 

def μ_func(S, X, O, M, z, mu,sig):
    return S@(at.dot(matrix_dot(X.T,O,M),z) 
                                + at.tensordot(mu,matrix_inverse(sig),[[0],[1]]))

**Comment by ricardoV94** [comment]
> def logp(value,ξ, tt_W, X_β,Ω,z):
> A = 1. - (value-pm.Beta.dist(ξ[0],ξ[1]))

You are introducing a random variable inside the logp in that line. Do you want your logp to be stochastic?

Note that our random variables don't work in JAX, so the Numpyro sampler would not be a good target for that model.

That's also probably where the default updates are coming from, as random variables work with shared variables.

**Comment by fbarfi** [comment]
Are you referring to the variables in DensityDist?

**Comment by ricardoV94** [comment]
> Are you referring to the variables in DensityDist? 
> 

In the logp function of the DensityDist

**Comment by fbarfi** [comment]
thanks ricardoV94. 
even after I remove the pm.Beta.dist and the variable X_\beta (which has beta =pm.MvNorma)  from the logp , I still get the same error message.

**Comment by ricardoV94** [comment]
There are too many things going on your model right now to be able to understand the problem without more investigation. Try to find exactly what line is causing it and which ones can just be removed from your example.

Once you have the smallest model/function that still fails please write here with all the code needed to see the problem in one single comment.

As a tip, you can put your code inside triple backticks to format it more nicely

    ```python
    # code goes here 
    ```

**Comment by fbarfi** [comment]
thanks. I'll do that. and thank you for the tip, I was wondering how to do it (it reminds me of R markdown way).

**Comment by fbarfi** [comment]
I found that the problem comes from jax not being able to recognize the Ops for the two distributions I am using: MvNormal and Polyagamma. I am using Normal and the original polyagamma distribution. sampling_jax is working now without errors.

**Comment by fbarfi** [comment]
here is the message I get for using MvNormal

``` python
NotImplementedError: No JAX conversion for the given `Op`: SolveTriangular{lower=True, trans=0, unit_diagonal=False, check_finite=True}
```

**Comment by fbarfi** [comment]
By the way using 
``` python
chain_method = 'vectorized'
```
increases the speed for MCMC

**Comment by ricardoV94** [comment]
> here is the message I get for using MvNormal
> 
> ```python
> NotImplementedError: No JAX conversion for the given `Op`: SolveTriangular{lower=True, trans=0, unit_diagonal=False, check_finite=True}
> ```

Yeah, we need to get the JAX converter for that Op. I opened an issue here: https://github.com/aesara-devs/aesara/issues/846

**Comment by ricardoV94** [comment]
@fbarfi I'll close this issue for now. Let us know if you find other issues.
