### ISSUE TITLE
Highlight contribution options in other repositories

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5567]
Not sure how to do this, but we should highlight PyMC Examples (and possibly Resources, Experimental) repositories, and nudge people who are looking for beginner-friendly issues to check those as well.

Perhaps in a pinned issue in this repository?

**Comment by OriolAbril** [comment]
Sounds great, I already opened #5460 to drive people to pymc-examples. But a pinned issue highlighting several ways for new contributors to get started, with a link to the sprint materials... would be better. I think we can draft its content here and then post and pin the issue.

**Comment by michaelosthege** [comment]
We're now mentioning these repos in several places in the contribution guides, so I think we can close this issue.
