### ISSUE TITLE
Flaky test `test_mixture.py::TestMixture::test_list_univariate_components_deterministic_weights`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5575]
I think this is new, probably introduced by 620b11d3bf86bcd9121eed2d57016993b5cbe044.

Saw it happen in https://github.com/pymc-devs/pymc/runs/5497901632?check_suite_focus=true#step:7:903 (belongs to #5572) and https://github.com/pymc-devs/pymc/runs/5488262408?check_suite_focus=true#step:7:990 (beloging to #5571).

cc @ricardoV94

**Comment by ricardoV94** [comment]
I guess with float32 and the low sigma the probability of identical draws is not that small. I am getting fed up with these float32 tests by the day xD

https://github.com/pymc-devs/pymc/blob/c3c76c5024aab209524788eeef16e1bfe2c26105/pymc/tests/test_mixture.py#L192-L193

**Comment by ricardoV94** [comment]
It should be sufficient to increase the sigma slightly. This issue and related PR by @LukeLB are a good example of how to make sure flaky tests are fixed properly: https://github.com/pymc-devs/pymc/issues/5409

**Comment by ricardoV94** [comment]
We are no longer testing in float32 so this should not be a problem anymore (I think)
