### ISSUE TITLE
Remove sd optional kwarg from distributions

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5576]
Several continuous univariate distributions have an old undocumented alternative `sd` kwarg, which should be removed in favor of `sigma`

This was brought up in #5546 and discussed internally in Slack

**Comment by ricardoV94** [comment]
@purna135 Do you want me to assign this issue to you?

**Comment by purna135** [comment]
Yes, Please ☺️

Can I remove sd from all distributions where it is required and create a single RP?

**Comment by ricardoV94** [comment]
> Yes, Please relaxed
> 
> Can I remove sd from all distributions where it is required and create a single RP?

Yes, that would be the best

**Comment by purna135** [comment]
Hi @ricardoV94,
removing `sd` from pymc/distributions/mixture.py and pymc/distributions/timeseries.py resulting some test fail with bellow messages.
```
55/76 files pass as expected.
2 files unexpectedly passed the type checks:
pymc/sampling_jax.py
pymc/step_methods/sgmcmc.py
This is good news! Go to scripts/run-mypy.py and add them to the list.
```

I am making a draft PR, please have a look.

**Comment by ricardoV94** [comment]
> Hi @ricardoV94,
> removing `sd` from pymc/distributions/mixture.py and pymc/distributions/timeseries.py resulting some test fail with bellow messages.
> ```
> 55/76 files pass as expected.
> 2 files unexpectedly passed the type checks:
> pymc/sampling_jax.py
> pymc/step_methods/sgmcmc.py
> This is good news! Go to scripts/run-mypy.py and add them to the list.
> ```
> 

I also see that locally in some of my PRs regardless of what I change, but it fails on Github if I add those to the list. CC @michaelosthege

**Comment by michaelosthege** [comment]
> > Hi @ricardoV94,
> > removing `sd` from pymc/distributions/mixture.py and pymc/distributions/timeseries.py resulting some test fail with bellow messages.
> > ```
> > 55/76 files pass as expected.
> > 2 files unexpectedly passed the type checks:
> > pymc/sampling_jax.py
> > pymc/step_methods/sgmcmc.py
> > This is good news! Go to scripts/run-mypy.py and add them to the list.
> > ```
> 
> I also see that locally in some of my PRs regardless of what I change, but it fails on Github if I add those to the list. CC @michaelosthege

Run it always as `pre-commit run mypy --verbose`. The difference is due to which dependencies are installed in your vs. the pre-commit environment.

**Comment by purna135** [comment]
Thank you : )
