### ISSUE TITLE
Deprecate remaining VI methods

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5581]
#4582 left some old VI methods marked as NotImplemented

Normalizing flows: https://github.com/pymc-devs/pymc/blob/ef5f91b41d733c64cf3ea785ec2760caae5d1bd4/pymc/variational/approximations.py#L363

And these: https://github.com/pymc-devs/pymc/blob/e987950b359edfe4a49c92ee67c57983fe0fc5d9/pymc/variational/opvi.py#L959-L962

We should decide whether we want to refactor or remove them

**Comment by ricardoV94** [comment]
CC @ferrine, @fonnesbeck, @twiecki

**Comment by twiecki** [comment]
My vote is on removing them, don't think anyone uses those. If they do, they'll probably complain. We could ask on discourse too.

**Comment by fonnesbeck** [comment]
I'm pretty sure OVPI can go, but normalizing flows are something we would want. They are a pretty  useful and are available in most VI implementations these days (e.g. pyro, TF). That said, they can always be added back if anyone ever wants to implement them.

**Comment by ferrine** [comment]
I'd vote for removal, agree with @fonnesbeck. This functionality did not prove to be super useful.

**Comment by fonnesbeck** [comment]
@ferrine do you think it will be straightforward to get normalizing flows ported? Were they fully functional in v3?

**Comment by ferrine** [comment]
they were, but that time I struggled with shape inference for parameter creation. In v3 I relied on test values for NF, now test values are less strict and it broke the internals. To fix this issue new mechanism has to be implemented to initialize normalizing flows.

**Comment by ferrine** [comment]
To summarize there are 3 blocks of features

- [AEVB](https://arxiv.org/abs/1312.6114) that is all `self.local` occasions. It is rarely used, and not PyMC focus
- batched block sparse inference. All `self.batched` occasions. Was used to improve UX of AEVB
- Normalizing flows. Normalizing flows API is nice but stays very far from PyMC focus. I'm ok to just delete it

**Comment by ricardoV94** [comment]
So shall we delete everything and open an issue to re-implement normalizing flows in the future (either here or in pymc-experimental)?

**Comment by twiecki** [comment]
That sounds good to me.

**Comment by fonnesbeck** [comment]
Yes, seems sensible, assuming "everything" is all methods with NotImplementedInference exceptions.

**Comment by purna135** [comment]
I would like to work on this.

**Comment by twiecki** [comment]
@purna135 Great, just open a draft PR when you have a start so that others can see that you're working on this.

**Comment by purna135** [comment]
Sure @twiecki, Thank You
