### ISSUE TITLE
Automatic Relevance Determination / Sparse Bayesian Learning

### ISSUE THREAD

**Issue by FlorianWilhelm** [pymc-devs/pymc#559]
Lately, I've been playing around with PyMC and Automatic Relevance Determination.  Since PyMC 3 also encompasses GLM, I wondered if ARD might be an interesting addition too. Would you be interested in a contribution of ARD?

**Comment by twiecki** [comment]
Certainly! Might work best as an example or would this require more in-depth changes?

**Comment by FlorianWilhelm** [comment]
I could start with an example but I think it could also be extended to a regression like in glm.glm. Scikit-Learn also includes it: http://scikit-learn.org/stable/auto_examples/linear_model/plot_ard.html

**Comment by twiecki** [comment]
I'm not familiar with ARD. A quick glimpse at this paper "A New View of Automatic Relevance Determination", I'm not sure how it could be implemented efficiently in pymc, but as I said, I'm not familiar enough. How would you implement it?

**Comment by FlorianWilhelm** [comment]
The implementation in Scikit-Learn is based on an iterative method. For PyMC, given a linear regression y = Xw + e with n features x_1, ... x_n, I would create n gamma distributed tau_1, ..., tau_n random variables as well as n normally distributed weight variables w_i ~ N(0, 1/tau_i) for i=1...n. The target variable y is also normally distributed as y ~ N(X_w, 1/alpha) where alpha is also gamma distributed. This is basically just the definition of ARD but if n is not too large it works in PyMC. Of course, if n is too large the curse of dimensionality bites you. For the n-dimensional regression problem, we'll have 2_n + 2 random variables that need to be infered with MCMC. 
@twiecki What do you think? Is it worth to be included as an example? In PyMC3, I noticed that GLM are provided. For the special case of a n-dimensional linear regression, you'll need n+1 random variables, right?

**Comment by twiecki** [comment]
I see. So maybe you could add this as a family to `glm`? E.g. https://github.com/pymc-devs/pymc/blob/master/pymc/glm/families.py#L81 Seems like you're only changing the priors here unless I'm missing something.

**Comment by FlorianWilhelm** [comment]
Good idea, I'll have a look into it. The company I work for sponsors some working hours to work on OSS projects, I just needed to make sure that a potential contribution is welcome. I'll let you know when I have something to show.

**Comment by twiecki** [comment]
That's great. We're always happy about contributions. Perhaps the best way forward would be for you to write the model without glm (as an example). If that works well it's much easier to port it to glm.

**Comment by FlorianWilhelm** [comment]
I was working on ARD yesterday but could not quite figure it out. I had it working on PyMC 2 a few months again but I am having a hard time with PyMC 3. Here is my small example https://gist.github.com/FlorianWilhelm/cb7870ab87df6545bb8c
This is really an oversimplified example. The problem I have is that whenever `n_features` is larger than 3, find_MAP() just does not seem to work all `w_i` are exactly 0 and `tau_i` are 1. Is this to be expected? Surely I did a mistake regarding the definition of RVs in PyMC 3. Also I get the runtime warning: `theano/scan_module/scan_perform_ext.py:85: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *`.

**Comment by twiecki** [comment]
I adapted (and broke) your code a bit in response to the gist.

For `find_MAP()` you can pass in  `fmin=scipy.optimize.fmin_l_bfgs_b` which often does a better job (this should probably be default since stan recently switched to that as well).

**Comment by jsalvatier** [comment]
(IIRC there seemed to be some cases where fmin_l_bfgs_b was very slow, I
think we had some discussion about it)

**Comment by springcoil** [comment]
Was there ever any progress on this? @FlorianWilhelm @twiecki

**Comment by twiecki** [comment]
Closing because of age. Feel free to reopen if you want to fix this up.

**Comment by Shbnmhz** [comment]
Has this been added to the PyMC3? Alternatively, can you refer to a stable version of ARD implementation in pymc?

**Comment by fonnesbeck** [comment]
Only in the context of Gaussian processes. Outside of that, you can use horseshoe priors to induce sparseness in regression models.

**Comment by rschiemer** [comment]
Just found this thread. I have problems getting ARD to work with Gaussian processes. Could you provide me a link to some working examples out there?

**Comment by FlorianWilhelm** [comment]
Sorry for not responding for almost 4 years, it completely slipped my mind. From my side, there has been no further progress on this matter since 2014.
