### ISSUE TITLE
Reorder sigma and lam parameter in StudentT distribution 

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5602]
It's a bit surprising that lam appears before sigma, when defining a StudentT with positional arguments.

https://github.com/pymc-devs/pymc/blob/09bddde70b33a54cd8aa494bb15d8d11462805ec/pymc/distributions/continuous.py#L1917

The docstrings suggest sigma comes before, and this is actually the case for the HalfStudentT. In the Normal, sigma also shows up before tau. I think we should reverse them so that sigma takes precedence here as well.

This would warrant a user warning about the changed behavior, which would need a dummy new variable like `_sigma=None` so that we can detect a positional only argument was used.

This emerged recently in discourse: https://discourse.pymc.io/t/pymc3-produces-different-results-than-stan-numpyro/9030/5

**Comment by cluhmann** [comment]
This seems reasonable to me.  Hopefully this will be less of an issue as the docs are updated, but it seems like it should at least be consistent across student, half student, normal, half normal, etc.  Are there any other distributions with surprising "defaults" like this?

**Comment by ricardoV94** [comment]
>  Are there any other distributions with surprising "defaults" like this?

I didn't look for more. Do you want to have a look?

**Comment by twiecki** [comment]
I agree, the reason is that there used to be only the `lam` parameter so `sigma` is the "alternative" parameterization. Nonetheless, that's anachronistic and there are many good reasons to change it as you mention. In addition, it seems to bring us in line with other packages which is also good.

**Comment by cluhmann** [comment]
> > Are there any other distributions with surprising "defaults" like this?
> 
> I didn't look for more. Do you want to have a look?

I can poke around and see if I see any other weirdness.

**Comment by michaelosthege** [comment]
Instead of changing the order, why don't we require these as explicit kwargs?
That way we still break code that passes them positionally, but at least we don't break it silently.

**Comment by cluhmann** [comment]
That is certainly my practice.  Not only are there are alternative ways of specifying a given moment (sigma vs. precision), but there are cases in which there are entire specifications (e.g., gamma) and I don't trust myself to remember which one which is the default one.  Ultimately, I think this boils down to a tradeoff between verbosity and explicitness (and I know I value the latter).

**Comment by cluhmann** [comment]
I went through the continuous and discrete distributions.  Normal, HalfNormal, TruncatedNormal, and LogNormal all adhere to the same `mu`, `sigma`, `tau`, `sd` argument order.  SkewNormal and HalfStudentT use this same order but take `alpha` (SkewNormal) and `nu` (HalfStudentT) first, before these other parameters.

- As mentioned above, StudentT deviates from this by taking arguments in the order: `nu`, `mu`, `lam`, `sigma`, `sd`.

- The other oddity is that HalfStudentT defaults to `nu=1`, whereas StudentT has no default value for `nu`.  I can't see any reason for this difference.

- The only other thing that jumped out at me was that Laplace takes arguments `mu` and `b`, whereas AsymmetricLaplace takes `b`, `kappa`, and then `mu`.

- In addition, AsymmetricLaplace has a default value of `mu=0` (which may be related to why it is last in the signature?) whereas Laplace has no default value for `mu`.

- Finally, I guess an argument could be made that AsymmetricLaplace should take `kappa` as its first argument given the signatures of SkewNormal and [Half]StudentT.

**Comment by ricardoV94** [comment]
I think those all benefit from being standardized @cluhmann. Would you be interested in opening a PR to fix it?

**Comment by cluhmann** [comment]
Messing with such a central part of the package makes me slightly nervous, but sure.
