### ISSUE TITLE
Memory leaks with PyMC `4.0.0b3`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5604]
## Description of your problem
In `4.0.0b2` we pinned `aesara==2.3.2`.

In `4.0.0b3` we pinned `aesara==2.4.0`.

Unfortunately, [`aesara==2.3.3` introduced a memory leak](https://github.com/aesara-devs/aesara/issues/852#issuecomment-1064602927).

The leak was fixed in [`aesara==2.5.1`](https://github.com/aesara-devs/aesara/releases/tag/rel-2.5.1).

Consequently we need to update to Aesara 2.5.1 as soon as possible.
Since there was a minor version bump 2.4→2.5, we'll probably run into incompatibilities.

## Versions and main components

* PyMC/PyMC3 Version: `4.0.0b3`, `main`
* Aesara/Theano Version: `2.4.0...2.5.0`

**Comment by ricardoV94** [comment]
We already updated the dependency to `2.5.1`, just need a new release

**Comment by ricardoV94** [comment]
In this PR: https://github.com/pymc-devs/pymc/pull/5582

**Comment by twiecki** [comment]
Let's make a new release!

**Comment by twiecki** [comment]
`4.0.0b4` is released.
