### ISSUE TITLE
import pymc will set theano.config.compute_test_value to 'raise'

### ISSUE THREAD

**Issue by yangky11** [pymc-devs/pymc#561]
> > > import theano
> > > print theano.config.compute_test_value
> > > import pymc
> > > print theano.config.compute_test_value

Output:

```
off
raise
```

I don't know whether this is an issue, but theano.config.compute_test_value == 'raise' requires test values to be provided for theano, which causes problems when I use pymc together with theano

**Comment by twiecki** [comment]
Closing in favor of #566.
