### ISSUE TITLE
Dead link to getting started guide

### ISSUE THREAD

**Issue by aaelony** [pymc-devs/pymc#5610]
The link https://github.com/pymc-devs/pymc-examples#pymc-examples states:

"
PyMC Examples
Supporting examples and tutorials for PyMC, the Python package for Bayesian statistical modeling and Probabilistic Machine Learning!

Check out the [getting started guide](http://docs.pymc.io/notebooks/getting_started), or interact with live examples using Binder! 
"
which is a dead link.  Should it rather be corrected to point to https://docs.pymc.io/en/v3/pymc-examples/examples/pymc3_howto/api_quickstart.html ?

**Comment by zaxtax** [comment]
Good catch! Do you want to open up a PR on the pymc-examples repo? Maybe point it to https://docs.pymc.io/en/latest/learning.html#learning as pymc v4 should be releasing soon?

**Comment by aaelony** [comment]
will do.
