### ISSUE TITLE
Wrong broadcasting of size 1 vector distributions defined with dims

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5613]
> And this particular situation of not broadcasting two 1d arrays of lenghts 1 and 10 feels strange, how does broadcasting differ between Aesara and numpy?

Somehow the dims is turning the output variable into something that is not (known) to be broadcastable:

```python
import pymc as pm

with pm.Model(coords={"slopes":["x_1"]}) as m:

    b_dim = pm.Normal("b_dim", sigma=1000, dims=("slopes"))
    b_size = pm.Normal("b_size", sigma=1000, size=1)

print(b_dim.broadcastable, b_size.broadcastable)
# (False,) (True,)
```

_Originally posted by @ricardoV94 in https://github.com/pymc-devs/pymc/issues/5561#issuecomment-1071047299_

**Comment by ricardoV94** [comment]
The issue might come from this line, which implies the size is not fixed as it is wrapped in a `aesara.shared`:

https://github.com/pymc-devs/pymc/blob/08b6b01e825de321d75177ec031e5a9118f3dd57/pymc/model.py#L1113

I assume this is done to allow resizing by changing dims? 

~~We need to enforce the broadcastable pattern of the shared variable~~ We must not use shared variables for initial dims of size 1 or give users the tools to chose for themselves.

**Comment by ricardoV94** [comment]
CC @michaelosthege

**Comment by michaelosthege** [comment]
Yes, the `aesara.shared` is to enable a later re-sizing.

It was also my first suspicion that it's because of `aesara.shared`, but I `dprint`ed the resulting variables and I didn't see `SharedVariable` there.
But maybe my analysis was not thorough enough.

**Comment by ricardoV94** [comment]
I assume this is what is happening?

```python
import aesara
import aesara.tensor as at
x = at.random.normal(size=aesara.shared(1))
print(x.type)   # TensorType(float64, (None,))
```

**Comment by ricardoV94** [comment]
The shared variable is there in the PyMC distribution, just not obvious because it prints the type and it has no name:

```python
aesara.dprint(d_dim)
```
```
normal_rv{0, (0, 0), floatX, False}.1 [id A] 'b_dim'   
 |RandomStateSharedVariable(<RandomState(MT19937) at 0x7FBD51C9CC40>) [id B]
 |SpecifyShape [id C] ''   
 | |MakeVector{dtype='int64'} [id D] ''   
 | | |<TensorType(int64, ())> [id E]
 | |TensorConstant{(1,) of 1} [id F]
 |TensorConstant{11} [id G]
 |TensorConstant{0} [id H]
 |TensorConstant{1000.0} [id I]
```

`[id E]` is the shared variable, I think

**Comment by ricardoV94** [comment]
I think we have to disable resizing of dims of length 1. Aesara needs the distinction as soon as we create the graph. 

The value variables would also need to be recreated if the broadcastable pattern of the RV were to change

**Comment by ricardoV94** [comment]
@michaelosthege any input on this one?

**Comment by michaelosthege** [comment]
> @michaelosthege any input on this one?

Sorry, no I'm not fluent enough to spontaneously be helpful, and I don't have the time to dig deeper right now

**Comment by ricardoV94** [comment]
The issue is caused by using shared variables for sizes defined via dims, the question is if it's fine to not allow that for the cases where the original dims have a size of 1, as that affects the broadcasting pattern of the variables.

**Comment by ricardoV94** [comment]
In the slack we proposed something like:

* All dims defined from coords via `model.set_coord` (this is the case for `pm.Model(coords=...) )` should be `TensorConstant`
* All non-specified dims defined from `pm.MutableData` should be ScalarSharedVariable
  * Users can specify shapes/broadcastable dimensions for the underlying shared variables, so in that case we can consider them fixed.
* Everything else is TensorConstant

**Comment by ricardoV94** [comment]
The issue with the broadcastable will hopefully go away with https://github.com/aesara-devs/aesara/pull/928, so we can just wait it out.

Otherwise, the downsides I see with keeping all variables defined by dims resizable is a slightly slower predictive sampling and potentially slower logp graphs / smaller chance that a model logp can be compiled to JAX which is finicky about undetermined shapes.

**Comment by michaelosthege** [comment]
> The issue with the broadcastable will hopefully go away with [aesara-devs/aesara#928](https://github.com/aesara-devs/aesara/pull/928), so we can just wait it out.

I think we should go ahead with the proposal from above (fixed dim lengths for dimensions created through `coords`) because it reduces the chance of shape problems. Plus speed.

**Comment by michaelosthege** [comment]
@ricardoV94 close this issue and #5181 in favor of #5751 ?
