### ISSUE TITLE
Split floatX tests into their own CI job

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5626]
Currently our CI has a `floatX` job matrix on Ubuntu and Windows, running each set of tests with both float32 and float64.

But there are just a handful of tests where floatX actually makes a difference.
Only these tests should run with a floatX job matrix, thereby dramatically reducing total CI runtime.

The following screenshot is an incomplete list of candidates:

![image](https://user-images.githubusercontent.com/5894642/159133495-627cb1dd-f5af-4a1e-8e60-b35b15e1ebaf.png)

**Comment by ricardoV94** [comment]
I would definitely remove test_distributions from float32 tests. Those xfails are not informative of anything because they arise from comparing with scipy methods that are always computed on float64

**Comment by ricardoV94** [comment]
Some tests I think make sense parametrizing with both floatX:

https://github.com/pymc-devs/pymc/blob/b895e40a2272210ee51519fa0431b6170b46b66e/pymc/tests/test_mixture.py#L662

https://github.com/pymc-devs/pymc/blob/b895e40a2272210ee51519fa0431b6170b46b66e/pymc/tests/test_distributions_random.py#L1577-L1581

https://github.com/pymc-devs/pymc/blob/b895e40a2272210ee51519fa0431b6170b46b66e/pymc/tests/test_smc.py#L317

https://github.com/pymc-devs/pymc/blob/b895e40a2272210ee51519fa0431b6170b46b66e/pymc/tests/test_smc.py#L336

Probably `pm.floatX` helper is also tested directly, hopefully with the flags as a parametrization or something.

There should be also a `DensityDist` test that checks the dtype follows floatX

This list is pretty ad hoc though

**Comment by michaelosthege** [comment]
Running this on Windows indicates a previously unknown... behavior.
```
    @pytest.mark.parametrize("floatX", ["float32", "float64"])
    def test_dtype(self, floatX):
        with aesara.change_flags(floatX=floatX):
            assert pm.Constant.dist(2**4).dtype == "int8"
            assert pm.Constant.dist(2**16).dtype == "int32"
>           assert pm.Constant.dist(2**32).dtype == "int64"
E           AssertionError: assert 'uint64' == 'int64'
E             - int64
E             + uint64
E             ? 
```
Also for `-(2**32)` is becomes uint64.

~What should I do about it?~
Looks like an Aesara bug. I opened https://github.com/aesara-devs/aesara/issues/871 and will reference in a conditional XFAIL.
