### ISSUE TITLE
Selectively import pymc 2.3 vs pymc 3

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pymc-devs/pymc#563]
It looks like they both use the same import (`import pymc`), but just in case, is there any way selectively load/use `pymc 2.3` vs `pymc3` ? (i.e. have them installed in the same virtual environment / python installation and choosing which one to load via `import` or some other mechanism).

**Comment by quantology** [comment]
For any package, you can do the following (assuming `pymc` is at `/path/to/parent/dir/pymc/...`):

``` python
import imp
pymc = imp.load_module("pymc", *imp.find_module("pymc", ["/path/to/parent/dir/"]))
```

Then pymc is in local namespace, and any script calling `import pymc` after this will load from this location as well.

For side-by-side loading:

``` python
import imp
pymc2 = imp.load_module("pymc2", *imp.find_module("pymc", ["/path/to/pymc2/parent/dir/"]))
pymc3 = imp.load_module("pymc3", *imp.find_module("pymc", ["/path/to/pymc3/parent/dir/"]))
```

Though note with the second one that any `import pymc` statement will revert to default path; python registers the module under the name given by the first argument.

**Comment by twiecki** [comment]
I agree that this is probably a common use-case to have both pymc versions side-by-side. Personally I'd be in favor of naming pymc 3 `pymc3`.

**Comment by aflaxman** [comment]
I've got a branch where the module is called `pymc3` [here](https://github.com/aflaxman/pymc/commit/f1c386915cf982d005d30be19b74dd73c81f3b1f).  Would you like a pull request?

**Comment by quantology** [comment]
For an in-module solution, you could do something in the **init**.py:

``` python
import imp, os # assuming this is pymc3
imp.load_module("pymc3", *imp.find_module("pymc", [os.path.basedir(__file__]))
```

Which solves the problem of listing pymc as pymc3 post-import (`import pymc; import pymc3` would work), but I can't imagine how the user would be able to selectively import without some imp magic unless the packages were renamed, per @twiecki 's suggestion. Though perhaps a new pymc2 module (simple fork of current) would cause better forward compatibility than renaming pymc3?

**Comment by fonnesbeck** [comment]
In PR #576 I've replaced absolute with relative import statements, which allows PyMC 3 to be imported using `imp` as shown by @metaperture above.

**Comment by twiecki** [comment]
Closing in favor of #677 /
