### ISSUE TITLE
Simulator logprob not implemented for float32

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5632]
https://github.com/pymc-devs/pymc/runs/5618251798?check_suite_focus=true#step:7:178

cc @ricardoV94  it's working for the scalar case, so I assume it's not intentionally not implemented.

**Comment by ricardoV94** [comment]
> https://github.com/pymc-devs/pymc/runs/5618251798?check_suite_focus=true#step:7:178
> 
> cc @ricardoV94  it's working for the scalar case, so I assume it's not intentionally not implemented.

I think it has to do with changing flags after import. It would work fine if the float32 was set globally.

**Comment by michaelosthege** [comment]
Sound like something that should be fixed at the Aesara level in the long run.
In #5630 I added an XFAIL mark so I guess we can just be patient and hopefully some day it magically starts working?
And if not that's also ok.

This issue is linked in the XFAIL mark. Shall we close it to not clutter our backlog?

**Comment by ricardoV94** [comment]
Yes I think we can close it
