### ISSUE TITLE
GP Marginal issue with conditional posterior predictive samples

### ISSUE THREAD

**Issue by rundel** [pymc-devs/pymc#5643]
## Posterior predictive samples incorrect for gp.marginal's conditional when using full posterior trace

In recently working through the GP marginal likelihood example I came across an issue when attempting to sample posterior predictive values from a conditional component for new X values. When following the example and using the MAP values with `sample_posterior_predictive()` I obtain results that match what I would expect for the model, however if instead I use the trace (InferenceData or MultiTrace) obtained from `sample()` with `sample_posterior_predictive()` I get results that do not make sense. 

The example below demonstrates the issue and includes the plots that result from each code chunk to hopefully illustrate the differences. My expectation is that the 2nd (incorrect) example should be producing output similar to what is seen from the 3rd example. 

### Setup and Initialization
```python
import numpy as np
import pymc3 as pm
import matplotlib.pyplot as plt

np.random.seed(12345)

n = 50
x = np.linspace(0, 1, n)
X = x.reshape(-1,1)

nugget = 0.75
sigma2_true = 4.0
l_true = 10

cov_func = sigma2_true * pm.gp.cov.ExpQuad(1, 1/l_true)
mean_func = pm.gp.mean.Zero()

y_true = np.random.multivariate_normal(
    mean_func(X).eval(), cov_func(X).eval(), 1
).flatten()

y = y_true + nugget * np.random.randn(n)

with pm.Model() as gp_marginal:
  nugget = pm.HalfCauchy("nugget", beta=5)
  sigma2 = pm.HalfCauchy("sigma2", beta=5)
  l      = pm.HalfCauchy("l",      beta=5)

  cov = sigma2 * pm.gp.cov.ExpQuad(input_dim=1, ls=1/l)
  gp = pm.gp.Marginal(cov_func=cov)

  y_ = gp.marginal_likelihood("y", X=X, y=y, noise=nugget)

with gp_marginal:
    step = pm.NUTS([nugget, sigma2, l])
    trace = pm.sample(
        return_inferencedata = True, chains = 2, step = step
    )

    mp = pm.find_MAP()

X_pred = np.linspace(0, 1, 1000)[:, None]

with gp_marginal:
    y_pred = gp.conditional("y_pred", X_pred)
```

### Using the MAP (correct)

```python
with gp_marginal:
    pp = pm.sample_posterior_predictive([mp], var_names=["y_pred"], samples=500)

plt.figure(figsize=(12,6))
plt.plot(x,y,".r")
lines = plt.plot(X_pred, pp["y_pred"].T, '-b', alpha=0.01)
```

![pymc1](https://user-images.githubusercontent.com/273926/159566137-7654f827-3bd1-4f78-a19c-fa3bf20b9bcc.png)

### Using the trace (incorrect)

```python
with gp_marginal:
    pp = pm.sample_posterior_predictive([trace], var_names=["y_pred"], samples=500)

plt.figure(figsize=(12,6))
plt.plot(x,y,".r")
lines = plt.plot(X_pred, pp["y_pred"].T, '-b', alpha=0.01)
```

![pymc2](https://user-images.githubusercontent.com/273926/159566106-7fe00db8-dd01-4019-80bb-08a56cf1aa7a.png)

### Using single posterior values (correct)

```python
res = []
for i in range(500):
    test  = {
        'nugget': trace.posterior["nugget"].values[0,i],
        'sigma2': trace.posterior["sigma2"].values[0,i],
        'l':      trace.posterior["l"].values[0,i]
    }
    with gp_marginal:
        pp = pm.sample_posterior_predictive([test], var_names=["y_pred"], samples=1, progressbar=False)
    
    res.append(pp["y_pred"])

res = np.array(res).reshape(500,-1)

plt.figure(figsize=(12,6))
plt.plot(x,y,".r")
lines = plt.plot(X_pred, res.T, '-b', alpha=0.01)
```

![pymc3](https://user-images.githubusercontent.com/273926/159566098-ae54bac9-05d2-449e-92de-c5bd1e8f055c.png)

## Versions and main components

* PyMC/PyMC3 Version: 3.11.5
* Aesara/Theano Version: 1.1.2
* Python Version: 3.9.10
* Operating system: macOS 12.3 (M1 Pro)
* How did you install PyMC/PyMC3: pip

**Comment by ghost** [comment]
This does appear to work in v4 (renamed it `pp2` to avoid overwriting objects):

```python
with gp_marginal:
    pp2 = pm.sample_posterior_predictive(trace, var_names=["y_pred"], samples=500, keep_size=False)

plt.figure(figsize=(12,6))
plt.plot(x,y,".r")
lines = plt.plot(X_pred, pp1.posterior_predictive["y_pred"].values.squeeze().T, '-b', alpha=0.01)
```

![image](https://user-images.githubusercontent.com/96543055/159729433-c19e1a27-c73e-4ffc-a3f4-3a301f7b5fe1.png)

**Comment by danhphan** [comment]
Hi @rundel , I think that the `PyMC3` Version works fine as well.

From docstring of the `pm.sample_posterior_predictive` method:
> 
> trace : backend, list, xarray.Dataset, arviz.InferenceData, or MultiTrace
>     **Trace generated from MCMC sampling, or a list of dicts** (eg. points or from find_MAP()),
>     or xarray.Dataset (eg. InferenceData.posterior or InferenceData.prior)

So, when using the **trace** as input in the `pm.sample_posterior_predictive` method, we should not wrap **trace** in a list. Hence, **[mp]** is right, but **[trace]** is wrong => **trace** (without a list) is right. 

**Using the trace (correct)**
```
with gp_marginal:
    pp = pm.sample_posterior_predictive(trace, var_names=["y_pred"], samples=500)

plt.figure(figsize=(12,6))
plt.plot(x,y,".r")
lines = plt.plot(X_pred, pp["y_pred"].T, '-b', alpha=0.01)
```

![download](https://user-images.githubusercontent.com/25697956/160265422-98d9ee58-7e60-49ee-9a23-c9dfbb3fa930.png)

This run at pymc3 version 3.11.4.

**Comment by ricardoV94** [comment]
Should we do anything here?

**Comment by rundel** [comment]
Thanks @danhphan for point out my error. 

With that said this seems like an easy mistake to make and it seems quite undesirable to have no error and incorrect results produced in this specific circumstance.

**Comment by fonnesbeck** [comment]
I'm going to close this for now, since there is no bug and it is following the behavior that is documented. If anyone wants to create a PR to generate a warning based on the input type, however, feel free to do that.
