### ISSUE TITLE
set_subtensor with a random variable then dot product results in a compilation error

### ISSUE THREAD

**Issue by keithyipkw** [pymc-devs/pymc#5644]
## Description of your problem

Using `set_subtensor` with a random variable as the source, then doing a `dot` product with another tensor results in a compilation error:

<pre>
Exception: ('The following error happened while compiling the node', CGer{non-destructive}(TensorConstant{(1, 1) of 0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 1.0}, IncSubtensor{Set;int64}.0), '\n', 'Compilation failed (return status=1): C:/Users/user/.conda/envs/pm/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmkl_rt\r. collect2.exe: error: ld returned 1 exit status\r. ', 'FunctionGraph(CGer{non-destructive}(TensorConstant{(1, 1) of 0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 1.0}, <TensorType(float64, (True,))>))')
</pre>

However, doing a `dot ` product with a constant tensor is fine. Is the former an unsupported operation so this is actually not a bug?

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import numpy as np
import matplotlib.pyplot as plt
import arviz as az
from theano import tensor as tt

if __name__ == '__main__':
    np.random.seed(0)

    with pm.Model() as model:
        
        mu = pm.Normal("mu", mu=0, sigma=1)
        obs = pm.Normal("obs", mu=mu, sigma=1, observed=np.random.randn(100))
        
        # compilation error
        t = tt.zeros(1)
        t = tt.set_subtensor(t[0], mu)
        s = tt.ones(1)
        s = tt.dot(s, t)
        pm.Deterministic('s', s)
        
        # set_subtensor with a constant then dot
        # compilation error
        # t = tt.zeros(1)
        # t = tt.set_subtensor(t[0], 1)
        # s = tt.ones(1)
        # s = tt.dot(s, t)
        # pm.Deterministic('s', s)
        
        # only dot
        # works
        # t = tt.zeros(1)
        # s = tt.ones(1)
        # s = tt.dot(s, t)
        # pm.Deterministic('s', s)
        
        # set_subtensor then dot a constant tensor
        # works
        # t = tt.zeros(1)
        # t = tt.set_subtensor(t[0], mu)
        # s = tt.constant(np.array([1]))
        # s = tt.dot(s, t)
        # pm.Deterministic('s', s)
        
        # set_subtensor then dot an auto converted constant tensor
        # works
        # t = tt.zeros(1)
        # t = tt.set_subtensor(t[0], mu)
        # s = np.array([1])
        # s = tt.dot(s, t)
        # pm.Deterministic('s', s)
        
        trace = pm.sample(500, chains=4, cores=1)
        
        az.plot_trace(trace)
        az.plot_posterior(trace, ['s'])
        
    plt.show()
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
pymc2bug.py:49: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(500, chains=4, cores=1)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (4 chains in 1 job)
NUTS: [mu]
 |--------------------------------------------------------------------------------------------------| 0.00% [0/1500 00:00<00:00 Sampling chain 0, 0 divergences]
You can find the C code in this temporary file: C:\Users\user\AppData\Local\Temp\theano_compilation_error_58br5o15
library mkl_rt is not found.
Traceback (most recent call last):
  File "pymc2bug.py", line 49, in <module>
    trace = pm.sample(500, chains=4, cores=1)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\sampling.py", line 597, in sample
    trace = _sample_many(**sample_args)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\sampling.py", line 713, in _sample_many
    trace = _sample(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\sampling.py", line 855, in _sample
    for it, (strace, diverging) in enumerate(sampling):
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\fastprogress\fastprogress.py", line 47, in __iter__
    raise e
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\fastprogress\fastprogress.py", line 41, in __iter__
    for i,o in enumerate(self.gen):
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\sampling.py", line 978, in _iter_sample
    strace = _choose_backend(trace, chain, model=model)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\sampling.py", line 1379, in _choose_backend
    return NDArray(**kwds)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\backends\ndarray.py", line 219, in __init__
    super().__init__(name, model, vars, test_point)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\backends\base.py", line 67, in __init__
    self.fn = model.fastfn(vars)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\model.py", line 1293, in fastfn
    f = self.makefn(outs, mode, *args, **kwargs)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\pymc3\model.py", line 1254, in makefn
    return theano.function(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\compile\function\__init__.py", line 337, in function
    fn = pfunc(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\compile\function\pfunc.py", line 524, in pfunc
    return orig_function(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\compile\function\types.py", line 1981, in orig_function
    fn = m.create(defaults)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\compile\function\types.py", line 1836, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\basic.py", line 266, in make_thunk
    return self.make_all(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\vm.py", line 1131, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\graph\op.py", line 634, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\graph\op.py", line 600, in make_c_thunk
    outputs = cl.make_thunk(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\basic.py", line 1203, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\basic.py", line 1138, in __compile__
    thunk, module = self.cthunk_factory(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\basic.py", line 1634, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\cmodule.py", line 1191, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\basic.py", line 1543, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\user\.conda\envs\pm\lib\site-packages\theano\link\c\cmodule.py", line 2546, in compile_str
    raise Exception(
Exception: ('The following error happened while compiling the node', CGer{non-destructive}(TensorConstant{(1, 1) of 0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 1.0}, IncSubtensor{Set;int64}.0), '\n', 'Compilation failed (return status=1): C:/Users/user/.conda/envs/pm/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmkl_rt\r. collect2.exe: error: ld returned 1 exit status\r. ', 'FunctionGraph(CGer{non-destructive}(TensorConstant{(1, 1) of 0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 1.0}, <TensorType(float64, (True,))>))')
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4 py38haa244fe_1
* Aesara/Theano Version: theano-pymc 1.1.2 py38h885f38d_0
* Python Version: 3.8.12 h7840368_2_cpython
* Operating system: Windows 10
* How did you install PyMC/PyMC3: (conda/pip) conda

<details><summary>conda list</summary>
<pre>
# Name                    Version                   Build  Channel
arviz                     0.11.4             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cachetools                5.0.0              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cftime                    1.6.0            py38h6f4d8f0_0    conda-forge
curl                      7.82.0               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
fastprogress              1.0.2              pyhd8ed1ab_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.31.1           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
importlib-metadata        4.11.3           py38haa244fe_0    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
kiwisolver                1.4.0            py38hbd9d945_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.82.0               h789b8ee_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libgpuarray               0.7.6             h8ffe710_1003    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpython                 2.1              py38haa244fe_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.38.0           py38h57a6900_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
mako                      1.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38h294d835_0    conda-forge
matplotlib                3.5.1            py38haa244fe_0    conda-forge
matplotlib-base           3.5.1            py38h1f000d6_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mkl-service               2.4.0            py38hb96a4b1_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
netcdf4                   1.5.8           nompi_py38h0500770_101    conda-forge
numba                     0.55.1           py38h5858985_0    conda-forge
numpy                     1.21.5           py38hcf66579_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py38h5d928e2_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pillow                    9.0.1            py38hd8e0db4_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pygpu                     0.7.6           py38h6f4d8f0_1003    conda-forge
pymc3                     3.11.4           py38haa244fe_1    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38haa244fe_8    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge
pyqtchart                 5.12             py38h885f38d_8    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
scipy                     1.8.0            py38ha1292f7_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
setuptools                60.10.0          py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.1               h8ffe710_0    conda-forge
statsmodels               0.13.2           py38h6f4d8f0_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
theano-pymc               1.1.2            py38h885f38d_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.1              py38h294d835_2    conda-forge
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py38h294d835_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
vs2017_win-64             19.16.27033          hb90652a_6    conda-forge
vswhere                   3.0.1                h57928b3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
</pre>
</details>

**Comment by ricardoV94** [comment]
@keithyipkw note that we are no longer supporting theano-pymc. 

Could you retry with Aesara (and pymc=4.0.0b5), to see if the problem is still present? If so, we should then make it a pure Aesara example (no PyMC code), but there's no point in doing that if it is no longer a problem in Aesara

**Comment by keithyipkw** [comment]
Because of my improper linker config, the compiler could not find mkl_rt. In 4.0.0b5, the error is better formatted so now I have spotted the error.

<pre>
C:/Users/user/.conda/envs/pm4/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmkl_rt
collect2.exe: error: ld returned 1 exit status

Apply node that caused the error: CGer{non-destructive}(TensorConstant{(1, 1) of 0.0}, TensorConstant{1.0}, TensorConstant{(1,) of 1.0}, IncSubtensor{Set;int64}.0)
Toposort index: 2
Inputs types: [TensorType(float64, (1, 1)), TensorType(float64, ()), TensorType(float64, (1,)), TensorType(float64, (1,))]
</pre>

Going back to the original log, there was indeed a message "library mkl_rt is not found." and "cannot find -lmkl_rt" in the exception. Fixing the linker fixes the problem in both PyMC3 and 4.
