### ISSUE TITLE
Rename `model.compute_initial_point` to `model.initial_point`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5650]

**Comment by purna135** [comment]
Hi @ricardoV94, I would like to work on this but I have a doubt here
in model.py it's mentioned as "Model.initial_point has been deprecated. Use Model.compute_initial_point(seed=None)"
should we remove the deprecation worning and rename compute_initial_point to initial_point?

https://github.com/pymc-devs/pymc/blob/fa015e3c1f7e087ea5577ba777ca8a631ed7eccd/pymc/model.py#L1006-L1012

**Comment by ricardoV94** [comment]
Yes

**Comment by ricardoV94** [comment]
Closed via #5661
