### ISSUE TITLE
az.to_netcdf errors in variables containing / in names

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#5657]
## Description of your problem
in #5607 variable scopes became separated by `/` which appeared to be an [incompatibility](https://www.unidata.ucar.edu/blogs/developer/en/entry/netcdf_identifiers_and_character_escape) with HDF5 format. No longer these models save with `az.to_netcdf`

We need a different semantic separator for scopes that is compliant with hdf5 saving

## Versions and main components

* PyMC/PyMC3 Version: '4.0.0b5'
* Aesara/Theano Version: not ralated
* Python Version: not ralated
* Operating system: Linux
* How did you install PyMC/PyMC3: (conda/pip) conda

**Comment by ricardoV94** [comment]
Vertical pipe `|`? 

... Until we find another backend that fails with those xD

**Comment by ferrine** [comment]
I'm on the PR, changing to `|`
