### ISSUE TITLE
Don't set compute_test_value to raise

### ISSUE THREAD

**Issue by nouiz** [pymc-devs/pymc#566]
In this Theano issue, a user got problem, as pymc set compute_test_value to raise by default.

The problem is that there is one pymc op compiled. So when Theano load its cache, it load pymc, that change Theano compute_test_value, even if the user didn't load pymc itself:

https://github.com/Theano/Theano/issues/1951#event-138734769

It is not yet documented, but Theano now give much better error message for shape error. Here is an example:

```
import theano
x,y = theano.tensor.vectors('xy')
f = theano.function([x,y], x+y)
f([1], [2,3])
Traceback (most recent call last):
  File "test_err.py", line 4, in <module>
    f([1], [2,3])
  File "/home/nouiz2/repos/Theano/theano/compile/function_module.py", line 589, in __call__
    self.fn.thunks[self.fn.position_of_error])
  File "/home/nouiz2/repos/Theano/theano/compile/function_module.py", line 579, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 1, input[1].shape[0] = 2)
Apply node that caused the error: Elemwise{add,no_inplace}(x, y)
Inputs types: [TensorType(float64, vector), TensorType(float64, vector)]
Inputs shapes: [(1,), (2,)]
Inputs strides: [(8,), (8,)]
Inputs scalar values: [array([ 1.]), 'not scalar']

Backtrace when the node is created:
  File "test_err.py", line 3, in <module>
    f = theano.function([x,y], x+y)
  File "/home/nouiz2/repos/Theano/theano/tensor/var.py", line 117, in __add__
    return theano.tensor.basic.add(self, other)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint of this apply node.
```

Check, I print the backtrave when the node was created. So the user know when the node was created without using test value! This isn't in the released version of Theano.

I would suggest you to don't change theano default value for compute_test_value and if people ask questions about shape error, tell them about this. If you don't like this, I would recommand to at least change compute_test_value to "warn" instead of "raise".

**Comment by twiecki** [comment]
If I understand you correctly, you're saying that test_value should not be changed after creating the theano op. For a little while I thought we should instead have the current point in `Model` rather than in the theano ops. `find_MAP()` would then set that internal value, similar to how in pymc 2. @jsalvatier?

**Comment by twiecki** [comment]
Oh I see, this is related to https://github.com/pymc-devs/pymc/issues/561.

**Comment by jsalvatier** [comment]
The reason I set 'raise' was to avoid silent and mysterious failures when data arrays don't line up. The problem is that if we don't set raise, we only get an error when we try to sample. Since the likelihood may be quite complicated, it will be difficult to figure out where this error is coming from. 

Is there a way we can set 'raise' only temporarily? Perhaps within `with Model() as model:`? 

@twiecki how come you want to store the point within Model?

**Comment by nouiz** [comment]
With the dev version, now there is a decorator that allow you to do so:

```
@theano.configparser.change_flags(**{'vm.lazy': True})
```

**Comment by jsalvatier** [comment]
Oh cool. Its a function decorator that changes it for the duration of the function? It would be really nice to have a function that returns the old config values, modifying the current one. And a function that applies the old context. 

PyMC uses `__enter__` and `__exit__` functions in its `with Model() as model:` syntax and this would be the ideal place to do this. Perhaps we need to roll our own.

**Comment by nouiz** [comment]
That is a good idea. I won't have time shortly for this. If you do it, can
you do it on in theano?

**Comment by jsalvatier** [comment]
Sure.

**Comment by twiecki** [comment]
> Oh cool. Its a function decorator that changes it for the duration of the function? It would be really nice to have a function that returns the old config values, modifying the current one. And a function that applies the old context.

@nouiz did this get implemented by any chance?

**Comment by nouiz** [comment]
There is this decorator that change a value of a flag:

@theano.configparser.change_flags(compute_test_value='off')

**Comment by twiecki** [comment]
Right, ideally it could used as a function call though because we're using a context manager and not a function that can be decorated.

**Comment by nouiz** [comment]
Go see in theano/configparser.py. You probably change change the
implementation of the current decorator to do what you want.
