### ISSUE TITLE
Flakiness in tests/test_step.py test_step_continuous

### ISSUE THREAD

**Issue by zaxtax** [pymc-devs/pymc#5665]
Related to #5646, the current `test_step_continuous` in `test_step.py` is a bit flaky and I'm not sure what it's designed to test.

Can I get some insight into test so I can refactor it to be more robust?

**Comment by ricardoV94** [comment]
This was flaky due to random seeding not working for single chain for a while.

It should now be possible to deterministically seed it (and even better reduce the number of samples needed): https://github.com/pymc-devs/pymc/pull/5377

**Comment by ricardoV94** [comment]
This hasn't been an issue for a long time.
