### ISSUE TITLE
Add menu item for "Consulting"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#5675]
@twiecki 
What do you think of adding a menu item to the website, such as "Consulting" and pointing it to the PyMC Labs website?

This website has a lot of menu items, and possibly some can be consolidated.
https://docs.pymc.io/en/latest/index.html

Example:
Contributing
-- Installation
-- Examples

cc:  @OriolAbril

**Comment by OriolAbril** [comment]
I moved the issue as it is about the `docs.pymc.io` website (generated from the content in https://github.com/pymc-devs/pymc/tree/main/docs/source) and not about the `pymc.io` draft and currently dormant website (generated from https://github.com/pymc-devs/pymc.io and for now with previews at https://pymc-devs.github.io/pymc.io/). 

This will ensure we take care of it. 

We could combine the installation and learning into a getting started section, not sure much to do about the other ones, maybe combining community and about us. The "examples" one is an external link (I do want to move it at the end and make it have the []/ icon thingy)

**Comment by twiecki** [comment]
That would be great, thanks for the initiative @reshamas!

I agree that there currently seems room for some consolidation. Agree with @OriolAbril that a "Getting Started" with installation and learning underneath would work well. Perhaps even community could be included there too.

**Comment by OriolAbril** [comment]
> Perhaps even community could be included there too.

I would keep community separated because the goals and audiences are quite different. getting started is about using pymc, community is about connecting with other pymc users and contributors

**Comment by ricardoV94** [comment]
If we want to point to PyMC Labs under a consulting section on the PyMC website, we should add a line about what the requirements are for other consulting companies that would also like to be displayed on there (even if there are none at the moment)

**Comment by twiecki** [comment]
@ricardoV94 Good point. Several qualifiers come to mind, we can discuss which ones we want to use:
* Consulting primarily on PyMC modeling
* Supports PyMC development
* Is run largely by PyMC core members

Alternatively it could just be something that the steering council decides upon on a case-by-case basis.

**Comment by reshamas** [comment]
Close via #5833.
https://www.pymc.io/projects/docs/en/latest/learn/consulting.html
