### ISSUE TITLE
Make mypy precommit script easier to understand

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5685]
## Description of your problem
The mypy output on failure is dense and hard to read. It would benefit from improvements to smooth development workflow

### Ideas
   *  Break apart failures that are preexisting, versus the ones introduced last commit
   * Make the output easier to read by segmenting by file more cleanly than the massive wall of text right now such as
     * Split errors from notes
      * Format the output so the error is more readable, right now its a mix of single or multi line so its hard to discern easily where one starts and the other ends

The output is a dataframe that can be easily iterated over and worked with.

Script is here 
https://github.com/pymc-devs/pymc/blob/741d45540016ab52a15ad5bff521614b6ae1d835/scripts/run_mypy.py

**Comment by soma2000-lang** [comment]
@canyon289 I am new to solving this kind of issue/It would be great if you can me get started

**Comment by canyon289** [comment]
If youre totally new to contributing Id suggest this issue which is closer to the main line codebase. if youre definitely sure youd ilke to work on this issue, the idea would be to format the output to be easier to read

https://github.com/pymc-devs/pymc/issues/5729
