### ISSUE TITLE
problem with the gamma function definition

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc#569]
I was trying to reproduce results from the book "Doing Bayesian Data Analysis...". I had two problems: 1) I was unable to set the "alpha" parameter to a value of 1 or lower and 2) even using a close value to 1 like (1.0000001) I was not able to reproduce some of the results from the book. I think the problem is that the median (for the gamma function) is defined as:
self.median = maximum((alpha - 1) / beta, 0)
but that is the definition of the mode, hence the correct line should be
self.mode = maximum((alpha - 1) / beta, 0)

**Comment by twiecki** [comment]
Yep, you're right. Want to make a PR?

**Comment by aloctavodia** [comment]
OK, Done it.

**Comment by twiecki** [comment]
Thanks, merged. I'm doubtful it fixes your problem though...

**Comment by aloctavodia** [comment]
Not really, I'm still having problem to reproduce one distribution. If you want, you can take  a look and check the distribution of the kappa parameter [here](https://github.com/aloctavodia/Doing_bayesian_data_analysis/blob/master/09_BernBetaMuKappaPyMC.py) (compare with figure 9.11 and 9.12 from the book)

**Comment by aloctavodia** [comment]
Hi, I am able to [reproduce](https://github.com/aloctavodia/Doing_bayesian_data_analysis/blob/master/09_BernBetaMuKappaPyMC.py) the figures from the book if I use a Nuts sampler for kappa, and a Metropolis sampler for theta. It seems I can use any sampler for mu. Using other combinations (like using only NUTS or only Metropolis) lead to results that differ from the ones in the book (the results using only NUTS are really weird). 
I made a mistake in my code or is this a bug in PyMC3? 
Thanks!

**Comment by twiecki** [comment]
Model looks OK to me and the fact that some combination of samplers works is supporting that. We had some problems with the metropolis sampler before. The nuts problem could result from the narrow support [0, 1] of the distribution and that it's bumping against the edge (nuts only works on fully continuous I think). 

Have you tried the slice sampler?

**Comment by aloctavodia** [comment]
I tried a couple of combinations of distributions (using an unrelated example) like a gamma distribution with a normal distribution and I had no problem. I think the problem could be the combination of the gamma and beta distributions, the later been restricted to [0, 1]. (I think you re saying the same, I am right?).
As you suggested, I tried the Slice sampler (although I am not familiar with that sampler). It works for sampling the 3 parameters altogether. It does not work if I use slice for kappa or mu, and metropolis for the rest. in that case i get the error "TypeError: 'float' object has no attribute '**getitem**'"

**Comment by twiecki** [comment]
Can you post the full traceback for that error? I think slice is probably the best sampler for smaller, restricted models.

**Comment by aloctavodia** [comment]
Here it is.

``` python
Traceback (most recent call last):
  File "<stdin>", line 45, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 89, in sample
    return sample_func(*sample_args)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 98, in _sample
    for i, trace in enumerate(sampling):
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 180, in _iter_sample
    point = step.step(point)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/compound.py", line 14, in step
    point = method.step(point)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/arraystep.py", line 24, in step
    apoint = self.astep(bij.map(point), *inputs)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/slicer.py", line 58, in astep
    yi = logp(qi)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/blocking.py", line 119, in __call__
    return self.fa(self.fb(x))
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/blocking.py", line 64, in rmap
    dpt[var] = np.reshape(apt[slc], shp)
TypeError: 'float' object has no attribute '__getitem__'
```

**Comment by twiecki** [comment]
Ah, I fixed that bug on another branch and cherry-picked it here:
https://github.com/pymc-devs/pymc/commit/3eb2237a8005286fee32776c304409ed9943cfb3

So if you update that problem should go away.

**Comment by aloctavodia** [comment]
Nice, thanks!

I was doing some extra "experiments". By using different combinations of samplers I found another interesting thing. If I use only one sampler for the 3 parameters (whatever the sampling method) the autocorrelation of the kappa parameter is always really high and the ability to reproduce the figures in the book is poor (with Slice providing the closest results to the book, but not exactly comparable to the book). The interesting thing is that if I use one sampler for kappa and the same for the other 2 parameters I get good results! 

``` python
step1 = pm.Metropolis([theta, mu])
step2 = pm.Metropolis([kappa])
trace = pm.sample(5000, [step1, step2], progressbar=False)
```

It seems like decoupling the sampling of the parameters provides better sampling, is this something general? Is this a bug or a good strategy to increase the efficiency of the sampling. If the later, why don`t use a sampler per parameter always? Which will be the downside? Too many questions?

**Comment by twiecki** [comment]
Yes, that is to be expected. If you don't sample the RVs component-wise you'll get a very low acceptance probability, so applying a separate sampler (could be all metropolis) to each RV is often the way to go.

It's a bit confusing that the samplers don't work like that by default but there's the `single_component` branch https://github.com/pymc-devs/pymc/pull/450 where I implemented `SingleComponentMetropolis` and `SingleComponentSlice`. I guess I could merge that since it's been a while.

**Comment by aloctavodia** [comment]
Thanks for the clarification. I also think is confusing, because one (at least I) was expecting a component-wise sampling as the default behavior.

**Comment by twiecki** [comment]
Yeah, that's the way it's in every package (including pymc 2). Perhaps we should change `ComponentSlice` to `Slice`, and `Slice` to `SliceGroup` or something like that.

**Comment by aloctavodia** [comment]
I think something like this, would be nice.

```
step = pm.Sampler()  # component-wise
step = pm.Sampler(block=True)  # block-wise
```

BTW (in case you find useful)
In my example, the following code works (in the sense of reproducing the figures in the book) If "Sampler" is Metropolis or Slice, but not with NUTS. 

``` python
step1 = pm.Sampler([theta, mu])
step2 = pm.Sampler([kappa])
trace = pm.sample(5000, [step1, step2], progressbar=False)
```

The following does not behave consistently sometimes works sometimes doesn't .

``` python
step = pm.HamiltonianMC()
trace = pm.sample(5000, step, progressbar=False)
```

and If I use HMC to sample theta (but not the other parameters), like

``` python
step = pm.HamiltonianMC([theta])
```

I get this error

``` python
Traceback (most recent call last):
  File "<stdin>", line 65, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 89, in sample
    return sample_func(*sample_args)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 98, in _sample
    for i, trace in enumerate(sampling):
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/sampling.py", line 180, in _iter_sample
    point = step.step(point)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/compound.py", line 14, in step
    point = method.step(point)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/arraystep.py", line 24, in step
    apoint = self.astep(bij.map(point), *inputs)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/hmc.py", line 82, in astep
    q, p = leapfrog(H, q0, p0, nstep, e)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/step_methods/hmc.py", line 104, in leapfrog
    p = p - (e/2) * -dlogp(q)  # half momentum update
ValueError: operands could not be broadcast together with shapes (5,) (3,) 
```

**Comment by twiecki** [comment]
Can you use ``` around your code and tracebacks so that it's more readable?

I agree that a block argument is probably best. Did you use `find_MAP` with NUTS? It definitely needs a good starting point.

**Comment by aloctavodia** [comment]
Sorry about the (lack of) markdown. 

Yes, I'm using `find_MAP`.

**Comment by twiecki** [comment]
Can you link to the file that produces the traceback?

**Comment by aloctavodia** [comment]
[here](https://github.com/aloctavodia/Doing_bayesian_data_analysis/blob/master/09_BernBetaMuKappaPyMC_b.py) you have.

**Comment by twiecki** [comment]
@aloctavodia Is this still an issue?
