### ISSUE TITLE
sample_blackjax_nuts not found

### ISSUE THREAD

**Issue by fbarfi** [pymc-devs/pymc#5693]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
pymc.sampling_jax.sample_blackjax_nuts()
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
sample_blackjax_nuts not found
```

</details>

**Please provide any additional information below.**

## Versions and main components
Compiler    : Clang 11.1.0 
OS          : Darwin
Release     : 21.4.0
Machine     : arm64
Processor   : arm
CPU cores   : 10
Architecture: 64bit

json  : 2.0.9
pymc  : 4.0.0b3
numpy : 1.21.5
aesara: 2.4.0

**Comment by ricardoV94** [comment]
The sampling_jax module has to be imported explicitly because it is optional.

```python
import pymc.sampling_jax
pymc.sampling_jax.sample_blackjax_nuts()
```

**Comment by ricardoV94** [comment]
Also I am not sure blackjax was already in pymc 4.0.0b3. You can try our latest version instead.

**Comment by fbarfi** [comment]
Thanks. I'll try it and let you know.

**Comment by ricardoV94** [comment]
Closing this in favor of #5710
