### ISSUE TITLE
Handle broadcasting of parameters in Censored distributions

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5703]
When size is not specified, the base distribution is not resized and can broadcast with `lower` / `upper`, with repeated draws.

```python
import aesara.tensor as at
import pymc as pm
rng = at.random.default_rng(123)
x = pm.Censored.dist(pm.Normal.dist(0), lower=[-1, -1, -1], upper=[1, 1, 1], rngs=(rng,))
x.eval()  # array([-0.98912135, -0.98912135, -0.98912135])
```

We need to do something like in:
https://github.com/pymc-devs/pymc/blob/4702bd413376e6bd01c34b10228619e906875a9d/pymc/distributions/timeseries.py#L185-L187

**Comment by ghost** [comment]
Can you please be more specific? What should one to do fix this without changing base code?

**Comment by ricardoV94** [comment]
What do you mean without changing the base code?

**Comment by ricardoV94** [comment]
If you just want an immediate workaround, you can just make sure to pass size explicitly:

```python
x = pm.Censored.dist(pm.Normal.dist(0), lower=[-1, -1, -1], upper=[1, 1, 1], size=3)
```
