### ISSUE TITLE
Why doesnt PyMC automatically fill in N in binom from observed?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5712]
## Description of your problem
Seems weird that we have to fill in N for `x=pm.Binom("x", p=p, n=100, observed=bernoull_random(100))`

With all our new shape magic can we make this simpler now? If we can't thats fine, close this issue. Just curious if we can

CC @twiecki

**Comment by twiecki** [comment]
Agree that it would make beginner examples easier that if `n` isn't provided we infer it from the length of the observed.

**Comment by ricardoV94** [comment]
Something is off. The observations don't determine `n`. If it was a multinomial that would be the case.

**Comment by twiecki** [comment]
oh, you're right, observed here is just an int, not the array of binary data like in the Bernoulli.
