### ISSUE TITLE
Rename Constant to DiracDelta and add docstring warning about sampling it

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5716]
A problem with `pm.Constant` recently cropped up here: https://discourse.pymc.io/t/typeerror-when-combining-constant-and-normal-distribution-in-function-within-deterministic-node/9219

`Constant` should only be used in special cases like Mixtures, not as a direct sampled variable.  We should make this point clear in the docstrings, mentioning constant python/numpy values can be used in a PyMC models and if traces are desired `pm.Deterministic` can be used. If the goal is to show up in graphviz, `pm.ConstantData` can be used.

We can probably raise a UserWarning in `pm.Constant.__new__` to the same end.

**Comment by ricardoV94** [comment]
Or maybe renaming it `DiracDelta` is enough to dissuade people from using it as "Constants"

**Comment by cluhmann** [comment]
Agree.  This seems like something that is going to crop up over and over if it's not made clear early.

**Comment by ricardoV94** [comment]
> Agree.  This seems like something that is going to crop up over and over if it's not made clear early.

Want to take a go at it?

**Comment by cluhmann** [comment]
I am heading out of town this week, but if this can wait I'm happy to tackle it.
