### ISSUE TITLE
Update Gaussian_Processes.rst for v5

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5720]
## Description of your problem
As title reads update the docs. Bill and I are on it and will get it done sometime by July. Creating this issue to track

https://github.com/pymc-devs/pymc/issues/5538
https://github.com/pymc-devs/pymc/blob/main/docs/source/guides/Gaussian_Processes.rst

**Comment by OriolAbril** [comment]
Whenever we get to update this page, we have to make sure to add a target `additive_gp` at the section on additive GPs. 

---

With myst, targets are added with:

```markdown
(additive_gp)=
## Section heading
```

with rst it is instead:

```rst
.. _additive_gp:

Section heading
---------------
```

(the underscore is important and part of the syntax, not of the target)

**Comment by daniel-saunders-phil** [comment]
Hi all, I would be interested in picking this up. It would be helpful to get some sense of what needed changes have already been identified. I imagine the main one is just executing the code and making small adjustments to ensure compatibility with version 5. But any other concerns come to mind?

**Comment by daniel-saunders-phil** [comment]
It looks like the change from pymc3 to 4/5 didn't introduce any problems that require the code to adjust. The core functionality of the gp module has stayed pretty consistent across version. The only change I noticed was that `noise` is now called `sigma`. I also spotted and fixed a broken link. Otherwise, I'm not sure what else needs to be done. The content is still very helpful and fills an important gap between the GP examples and the GP documentation.

**Comment by OriolAbril** [comment]
Are there code examples that can be executed? If so I'd update the content to jupyter or myst notebook ([example of myst notebook](https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/plots_arguments_guide.md) in case it helps, it is a raw text notebook format) and move it to the [core notebooks](https://github.com/pymc-devs/pymc/tree/main/docs/source/learn/core_notebooks) folder. 

If the code snippets there should not be executed, keep it as rst but move it to the core notebooks folder too.

After that, add it to the toctree in https://github.com/pymc-devs/pymc/blob/main/docs/source/learn/core_notebooks/index.md and it will appear again on the docs

**Comment by daniel-saunders-phil** [comment]
Looks like the code was originally designed to be more schematic and wasn't intended to be executed. I submitted a PR to move the .rst file and also added it to the toctree.
