### ISSUE TITLE
Broken links early in the README

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc#5728]
The [README](https://github.com/pymc-devs/pymc/blob/main/README.rst) almost immediately suggests that users:

- "Check out the [PyMC overview](https://docs.pymc.io/en/latest/learn/examples/pymc_overview.html)", but the link is broken and with the new docs, I'm not entirely sure where it's supposed to be pointing
- and "[interact with live examples](https://mybinder.org/v2/gh/pymc-devs/pymc/main?filepath=%2Fdocs%2Fsource%2Fnotebooks) using Binder", but that link is also broken (and, again, not sure what it is supposed to be linking to)

**Comment by cluhmann** [comment]
Under "Getting started", there's a link to "the [PyMC tutorial](https://docs.pymc.io/en/latest/learn/examples/pymc_overview.html)", which is the same as "the [PyMC overview](https://docs.pymc.io/en/latest/learn/examples/pymc_overview.html)" referenced above and thus also broken.

**Comment by danhphan** [comment]
> Check out the [PyMC overview](https://docs.pymc.io/en/latest/learn/examples/pymc_overview.html), or [interact with live examples](https://mybinder.org/v2/gh/pymc-devs/pymc/main?filepath=%2Fdocs%2Fsource%2Fnotebooks) using Binder! For questions on PyMC, head on over to our [PyMC Discourse](https://discourse.pymc.io/) forum.

The first point to look at may be this link: https://docs.pymc.io/en/latest/index.html , which will lead to this: https://docs.pymc.io/en/latest/learning.html#learning . In that, we can find the [PyMC overview](https://docs.pymc.io/en/latest/learn/core_notebooks/pymc_overview.html#pymc-overview) notebook.

The `interact with live examples` is this one: https://docs.pymc.io/projects/examples/en/latest/
In these examples, each notebook can be run with `Binder` or `Google Colab`, for example, this notebook on [GLM binomial regression](https://docs.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-binomial-regression.html)

The [README](https://github.com/pymc-devs/pymc/blob/main/README.rst) needs to be updated, but maybe we need to wait for other parts of documentations for PyMC V4 to be updated first.

I think @OriolAbril can have a better opinion on this.

**Comment by OriolAbril** [comment]
the pymc overview notebook was moved from the `examples` folder to the `core_notebooks`, the internal links didn't need to be modified because they use sphinx cross-references but external ones need to be modified.

I agree with the interact with live examples pointing to the pymc-examples website instead of pointing to binder directly. Many notebooks won't really run on binder and doing this will give the option to users to choose github/binder/colab at will for each notebook. 

I think it can already be updated. Once v4 is out we should again update all the links to make sure the links to the versioned docs point to `docs.pymc.io/en/stable` not `v3` not `latest` (unless we added some specific v3 or dev version links)

**Comment by cluhmann** [comment]
Are both "the PyMC overview" and "the PyMC tutorial" supposed to be pointing to [the overview](https://docs.pymc.io/en/latest/learn/core_notebooks/pymc_overview.html#pymc-overview)?

**Comment by OriolAbril** [comment]
yep

**Comment by cluhmann** [comment]
And is it ok to point to the "latest" version of these docs for now?  Or would some other version be better?

**Comment by OriolAbril** [comment]
latest is the best for now. As a general rule, given pymc is quite mature and stable, links to docs should preferably point to `stable` (so they will need to be updated but stable is missing many pages now with the restructure) and links to community pages and contributing docs should point to `latest` (so every commit updates the web, not only every release)

**Comment by cluhmann** [comment]
Yup.  I only asked because I couldn't find the overview in "stable".
