### ISSUE TITLE
Docs subpages with a single item should just show it immediately

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5740]
No reason to require a double click in these cases... unless it's too much work to change the behavior of course :)

![image](https://user-images.githubusercontent.com/28983449/166660338-5251d7d5-d391-463a-8daf-b69a11b03d50.png)

**Comment by OriolAbril** [comment]
are there other cases of this? 

This is also related to #5282. Do we want `pm.Censored` to have its own subsection or do we want to restructure the subsections inside "Distributions"

**Comment by ricardoV94** [comment]
There are couple more, Simulator comes to mind. 

I think our docs structure does not need to follow the project one

**Comment by OriolAbril** [comment]
closed by https://github.com/pymc-devs/pymc/pull/6781
