### ISSUE TITLE
Improve default GaussianRandomWalk and AR init distributions

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5744]
When refactoring the GaussianRandomWalk to V4, we set the `init` to default to `Normal(mu, sigma)`, which does not make much sense. `mu` is the drift parameter, and says nothing about the expected starting location of the series. `sigma` probably also makes little sense, as it assumes the uncertainty about the initial location has anything to do with the innovations noise. 

Possible alternatives:
* `init = Normal.dist(0, 1)`
* `init = Flat.dist()`, which was the default in V3, but it means that prior and posterior predictive will fail by default.

We should also rename `init` to `init_dist` to emphasize this parameter must de a distribution.

https://github.com/pymc-devs/pymc/blob/c76b9b9e74ee6f13993f255dd09d9290b882d6ab/pymc/distributions/timeseries.py#L239

A similar question arises in the AR, where we again reuse the innovation noise `sigma` for the uncertainty about the initial location of the series.

https://github.com/pymc-devs/pymc/blob/c76b9b9e74ee6f13993f255dd09d9290b882d6ab/pymc/distributions/timeseries.py#L429

**Comment by ricardoV94** [comment]
Reopening the issue @twiecki. 

After #5779 we are using unit normals as default. Other proposed options:
1. Use Flat again and let it fail when doing predictive sampling
2. Use a unit normal with larger sigma
3. Do not provide a default, user must always specify it.

**Comment by twiecki** [comment]
Decision: Raise warning if not specified, increase standard deviation to 100.

**Comment by AlexAndorra** [comment]
I'll take this on

**Comment by lucianopaz** [comment]
Is it Possible to set it to the stationary distribution? At least for the AR?

**Comment by lucianopaz** [comment]
Another alternative is to set it to a Dirac delta at 0

**Comment by ricardoV94** [comment]
@lucianopaz I think the initial point does not affect the stationarity?

**Comment by lucianopaz** [comment]
> @lucianopaz I think the initial point does not affect the stationarity?

I meant to set the initial distribution to the AR stationary distribution. For AR1 there’s a formula in terms of the coefficients. I don’t know what happens for AR(p) though

**Comment by ricardoV94** [comment]
> > @lucianopaz I think the initial point does not affect the stationarity?
> 
> I meant to set the initial distribution to the AR stationary distribution. For AR1 there’s a formula in terms of the coefficients. I don’t know what happens for AR(p) though

Won't that perhaps introduce very strong constraints on the initial point? 

Btw, a DiracDelta would break everything, as no draws would ever be accepted unless we implemented a custom sampler (or transform) for the AR alone
