### ISSUE TITLE
Travis test times

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#575]
Am I [reading this](https://s3.amazonaws.com/archive.travis-ci.org/jobs/30497275/log.txt) correctly (see end of file)? Each of the distribution tests are taking >30 minutes to run? If so, we may need to rethink our distribution unit tests.

**Comment by jsalvatier** [comment]
Yes, it sure looks like it, but I don't believe it since the tests time out
after 10 minutes of no output. Maybe there's something wrong with
nose-timer?

**Comment by jsalvatier** [comment]
Most of the test suits seem to be running in less than 15 minutes total now. https://travis-ci.org/pymc-devs/pymc3

**Comment by twiecki** [comment]
Actually we still see timeouts sometimes.

**Comment by jsalvatier** [comment]
Do you know which tests? I saw one example of MultivariateNormal3 I think.
Any other ones?

**Comment by twiecki** [comment]
That's the only one I think.

**Comment by jsalvatier** [comment]
Lets just make it smaller or something then.

**Comment by jsalvatier** [comment]
Maybe we could tag tests as slow: http://nose.readthedocs.org/en/latest/plugins/attrib.html

**Comment by jsalvatier** [comment]
maybe we just don't even need to test mvnormal3. testing 2 is probably fine.

**Comment by twiecki** [comment]
That's probably easiest. We should get correctness by mathematical induction ;)
