### ISSUE TITLE
Allow for size with Ellipsis

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5750]
As far as I could tell, there is no reason this can't be allowed?

```python
import pymc as pm
x = pm.Normal.dist([0, 0], 1, shape=(5, ...))
x.shape.eval()  # array([5, 2])
```
```python
x =  pm.Normal.dist([0, 0], 1, size=(5, ...))
```
```
ValueError: The `size` parameter cannot contain an Ellipsis. Actual: (5, Ellipsis)
```

**Comment by ricardoV94** [comment]
CC @michaelosthege

**Comment by michaelosthege** [comment]
That's because of the "`size` is exactly the same as in Aesara" kwarg interpretation.

https://github.com/pymc-devs/pymc/blob/dd23c9008302fc184298076669d0a3a332aa59f0/RELEASE-NOTES.md?plain=1#L115

**Comment by michaelosthege** [comment]
After the discussion yesterday, can we close this as "wontfix" ?
