### ISSUE TITLE
Fix dim lengths created from `coords` or `ConstantData`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5751]
In [this comment](https://github.com/pymc-devs/pymc/issues/5613#issuecomment-1107752199) we proposed to make dimensions created from `coords` non-resizeable, because it would prevent users from running into issues like #5181.

## What needs to be done
In https://github.com/pymc-devs/pymc/blob/dd23c9008302fc184298076669d0a3a332aa59f0/pymc/model.py#L1070-L1076 the `set_coord` method could take another kwarg `resizable: bool=False` or `fixed: bool=True`.

Then we can actively turn off re-sizing of dimensions that are created from `ConstantData` or `coords`.

**Comment by ricardoV94** [comment]
Let's remember to add #5181 as a test

**Comment by LukeLB** [comment]
Hi guys just been looking at how this can be implemented. Can I check my understanding first... So this line:
```
self._dim_lengths[name] = length or aesara.shared(len(values))
```
Is causing the problem due to the `aesara.shared(len(values))` being resizeable. So the sugestion here is to create a new kwarg which we can use in an if statement, something like:
```
if fixed:
    self._dim_lengths[name] = length or aesara.tensor.constant(len(values))
else: 
    self._dim_lengths[name] = length or aesara.shared(len(values))
```

**Comment by michaelosthege** [comment]
@LukeLB yes, that's the idea

**Comment by canyon289** [comment]
@LukeLB Did you want to take a shot at fixing this, and if so when were you planning on doing so? I ask as this is holding up the Bambi migration to V4 so we want to get fixed soon here!

**Comment by LukeLB** [comment]
@canyon289 I've got time today so I'll have a crack at it.

**Comment by canyon289** [comment]
Sounds great! Looking forward to the PR and thank you. Let us know if you need any help.

**Comment by LukeLB** [comment]
@canyon289 just put in a WIP-PR as I'm heading out and was having some problems with locally failing tests.
