### ISSUE TITLE
Incorporate AePPL into GaussianRandomWalk

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#5762]
A recent PR #5298 added GaussianRandomWalk distribution to v4. It would be possible to use AePPL to obtain the Aesara graph corresponding to desired `rv_op` and retrieve the correct log-probability graph. The use of AePPL here would be desirable as we will no longer need to implement a corresponding `RandomVariable` class nor implement the logp method. Moreover, it would generalize the random walk to make use of non-Gaussian distributions.

cc @ricardoV94

**Comment by ricardoV94** [comment]
Closed via #6072
