### ISSUE TITLE
Add a pyscript example to our docs

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5767]
## Description of your problem
It would be pretty awesome to have an autoloaded example for ueers. Pyscript is a bit early so there might be some challenges but lets try it out anyway

This will depend on ArviZ and Aeppl and other packages for smooth installation but we'll get it done for sure

**Comment by ricardoV94** [comment]
What does an autoloaded example mean exactly?

**Comment by canyon289** [comment]
@ericmjl's blog shows it the best. He has an in browser demo of NetworkX https://ericmjl.github.io/blog/2022/5/1/pyscript-python-in-the-web-browser

Upfront there'll be challenges with computation speed etc but I'm pretty confident we can get something compelling up and if we can't we don't have to do it either. Just adding an issue so we don't forget to try it.

**Comment by ricardoV94** [comment]
Are the binaries downloaded lazily?

**Comment by twiecki** [comment]
We could even have that be interactive -- i.e. the user can adapt the code.

**Comment by twiecki** [comment]
Here are some explanations of how to do this: https://www.pymc-labs.io/blog-posts/pymc-in-browser/

For now still had to create a small fork that didn't include the `netcdf` dependency.

**Comment by canyon289** [comment]
Closing in favor of https://github.com/pymc-devs/pymc/issues/5770 which is better
