### ISSUE TITLE
Mirror codebase structure in tests

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5777]
### Discussed in https://github.com/pymc-devs/pymc/discussions/5579

<div type='discussions-op-text'>

<sup>Originally posted by **ricardoV94** March 11, 2022</sup>
I think the tests files should mirror the original codebase. So they should be in a file with the same name as where the functions/classes that it tests are defined. E.g.,, timeseries tests should be in tests/distributions/test_timeseries.py. This is how Aesara does it and its much easier to find what tests relate to what code, and also to spot gaps in our tests.

_Originally posted by @ricardoV94 in https://github.com/pymc-devs/pymc/pull/5298#discussion_r822280003_

This would also allow to break up the immensely large and slow `test_distributions.py`, which was already brought up in https://github.com/pymc-devs/pymc/issues/5410#issuecomment-1029759988

Also, https://github.com/pymc-devs/pymc/pull/5577#discussion_r824542298</div>

**Comment by Armavica** [comment]
What would you think to also move `tests` out of `pymc`? I think that it is the standard practice: [ref 1](https://packaging.python.org/en/latest/tutorials/packaging-projects/), [ref 2](https://docs.python-guide.org/writing/structure/). This typically allows to grep for something in the code while avoiding plenty of matches from the tests, something which I do often.

**Comment by ricardoV94** [comment]
> What would you think to also move `tests` out of `pymc`? I think that it is the standard practice: [ref 1](https://packaging.python.org/en/latest/tutorials/packaging-projects/), [ref 2](https://docs.python-guide.org/writing/structure/). This typically allows to grep for something in the code while avoiding plenty of matches from the tests, something which I do often.

I have no idea. Any downsides to that?

**Comment by Armavica** [comment]
I can't see any. Aesara also has their tests outside of the code directory.

**Comment by ricardoV94** [comment]
@Armavica do you want to open a discussion for moving the tests out of pymc?
