### ISSUE TITLE
Implement save_state for sqlite database backend

### ISSUE THREAD

**Issue by stefan-pdx** [pymc-devs/pymc#578]
I've come across instances where I'd like to save an mcmc object in a sqlite backend for 2.3, but noticed that it still [has yet to be implemented](https://github.com/pymc-devs/pymc/blob/2.3/pymc/database/sqlite.py#L210-L225). I'll look into making a PR for this.

**Comment by fonnesbeck** [comment]
Moved to pymc-devs/pymc#3
