### ISSUE TITLE
Remove size from signature and raise warning if used

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5789]
Ref https://github.com/pymc-devs/pymc/issues/5754

**Comment by mjhajharia** [comment]
is this done, now that #5788 is merged

**Comment by michaelosthege** [comment]
In my opinion yes.

We can add warnings to nudge users towards certain API flavors in a patch release, so this should no longer block `4.0.0`.

I'll close this issue. Proposals to add `UserWarning`s should be made in new, much more specific issues.
