### ISSUE TITLE
Graphviz does not properly show observed `ConstantData` when subjected to intermediate Ops

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#5795]
```python
with pm.Model() as model:
    data = pm.ConstantData("data", [0, 0, 1, 1], dtype=np.int64)
    p = pm.Beta("p", 1, 1)
    bern = pm.Bernoulli("response", p, observed=data)
    
pm.model_to_graphviz(model)
```

yields

<img width="323" alt="image" src="https://user-images.githubusercontent.com/24764859/169923807-e9b2033a-bc6c-4e2b-83ec-1130c6f94a8e.png">

In other words, there should be an arrow from `response` to `data`. This is because `model["data"].tag.observations` is in fact an `Elemwise` operation rather than `data` as defined under the context manager. I don't think that this was broken from the recently merged PR #5634.

**Comment by ricardoV94** [comment]
I don't know the internals of model_graph, but one thing worth noting is that data only exists in the logp graph (as do other elements like potentials).

**Comment by larryshamalama** [comment]
On my end, I'm not as familiar with the internals of the initialization of the logp graph under a `pm.Model()`, but the observed nodes in graphviz are obtained by checking `observed_rv.tag.observations` as per [this line](https://github.com/pymc-devs/pymc/blob/main/pymc/model.py#L1390).

**Comment by drbenvincent** [comment]
not 100% sure, but this is cropping up quite a bit. Eg
<img width="667" alt="Screenshot 2022-07-14 at 10 47 42" src="https://user-images.githubusercontent.com/6765047/178954826-4a340ee4-6582-4c3d-b6af-231cb06dd2f1.png">
(from here https://www.pymc.io/projects/examples/en/latest/causal_inference/excess_deaths.html)

Personally, I think this is a relatively high priority defect

**Comment by larryshamalama** [comment]
Can try to have a closer look before the weekend. Thanks for sharing!

**Comment by larryshamalama** [comment]
> not 100% sure, but this is cropping up quite a bit. Eg <img alt="Screenshot 2022-07-14 at 10 47 42" width="667" src="https://user-images.githubusercontent.com/6765047/178954826-4a340ee4-6582-4c3d-b6af-231cb06dd2f1.png"> (from here https://www.pymc.io/projects/examples/en/latest/causal_inference/excess_deaths.html)
> 
> Personally, I think this is a relatively high priority defect

I will submit a PR that would close this issue, but I am doubtful that it would fix this problem (which should be very fixable). I will investigate further soon.
