### ISSUE TITLE
module 'pymc3' has no attribute '__version__'

### ISSUE THREAD

**Issue by BeiYaaa** [pymc-devs/pymc#5811]
## Description of your problem

I'm getting below error when import pymc3. Would really appreciate it if anyone could provide guidance.

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 10>()
      8 from theano import shared
      9 from sklearn import preprocessing
---> 10 print('Running on PyMC3 v{}'.format(pm.__version__))

AttributeError: module 'pymc3' has no attribute '__version__'

Window 10
Environment: Anaconda Python 3.8.13

Steps taken:
conda install -c conda-forge pymc3
conda install -c conda-forge theano-pymc

pip freeze:
Theano==1.0.5
Theano-PyMC @ file:///D:/bld/theano-pymc_1611363605764/work
pymc3 @ file:///Users/ktietz/demo/mc3/conda-bld/pymc3_1629812637918/work

**Comment by dchu1991** [comment]
you can dig up the discourse for the warning, e.g.: https://discourse.pymc.io/t/installation-guide-issue-warning-theano-tensor-blas-using-numpy-c-api-based-implementation-for-blas-functions/8274

as to the version, I think it should be ```pm.__version__``` instead of ```pm.version```

**Comment by michaelosthege** [comment]
This sounds like an incomplete installation.
Do `print(pm)` and then check the directory that's printed. Sometimes an uninstall can be incomplete, failing to delete the directory. If this happens, the `import pymc3` can still work, but there's not actually any code inside.
Delete the directory and try again.

Also, you shouldn't have to install Theano-PyMC separately. If anything do it before installing pymc3.

Please remember to come back and close the issue when you found a solution :)

**Comment by BeiYaaa** [comment]
> This sounds like an incomplete installation. Do `print(pm)` and then check the directory that's printed. Sometimes an uninstall can be incomplete, failing to delete the directory. If this happens, the `import pymc3` can still work, but there's not actually any code inside. Delete the directory and try again.
> 
> Also, you shouldn't have to install Theano-PyMC separately. If anything do it before installing pymc3.
> 
> Please remember to come back and close the issue when you found a solution :)

Hi Michael, thanks for your reply!

Yes, I feft the installation isn't correct or complete. Because when I run the model, I got below error:
```
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 basic_model = pm.Model()
      3 # Y as normally-distributed observations with an expected value mu that is a linear function of two predictor variables, X1 and X2.
      4 # alpha is the intercept, and beta is the coefficient for covariate X, while sigma represents the observation error. 
      5 with basic_model:
      6 
      7     # Priors for unknown model parameters

AttributeError: module 'pymc3' has no attribute 'Model'
```


I also tried to print the directory. The result of print(pm) is like below. I don't see the directory.
```
import pymc3 as pm
print(pm)
```
`<module 'pymc3' (namespace)>`

**Comment by ricardoV94** [comment]
if you print `pm.__path__` it will show you where it is importing the library from. That will likely be an empty directory that you will want to remove before trying to install pymc again

**Comment by michaelosthege** [comment]
This "namespace" thing is the symptom of that empty directory problem.
If `pm.__path__` doesn't work, you can do print any other module instead:
```
import os
print(os.__path__)
```
(It's under the "site-packages" directory in the environment.)

**Comment by BeiYaaa** [comment]
I've recreated the evn, and installed the pymc3 onlyl. and it worked!
