### ISSUE TITLE
Slice sampler does not converge in simple MvNormal prior model

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5815]
This example is taken from the step_tests here: https://github.com/pymc-devs/pymc/blob/4d2f3a8d5f99fc773bc0a1aad6d51e4f3f047698/pymc/tests/test_step.py#L89

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc as pm
import numpy as np

mu = np.array([-0.1, 0.5, 1.1])
p = np.array([[2.0, 0, 0], [0.05, 0.1, 0], [1.0, -0.05, 5.5]])
tau = np.dot(p, p.T)

with pm.Model() as model:
    pm.MvNormal( "x",  mu, tau=tau,)

expected_mean = mu
expected_std = np.diag(np.linalg.inv(tau)) ** 0.5

with model:
    trace = pm.sample(
        tune=10_000,
        draws=10_000,
        chains=1,
        step=pm.Slice(),
        return_inferencedata=False,
    )

# Very bad, the second mean seems to be consistently biased
print(expected_mean, trace["x"].mean(axis=0))
# [-0.1  0.5  1.1] [-0.14368236  1.76355742  1.11952911]

# Quite good
print(expected_std, trace["x"].std(axis=0)) 
# [ 0.56672996 10.00041321  0.18181818] [0.56335647 9.88682831 0.18468393]
```

This was also the case in V3: https://colab.research.google.com/drive/1Pw7a-1J-bnb4dPsPvxwuWH6TdFENYb5m?usp=sharing

**Comment by ricardoV94** [comment]
Well, Metropolis is even worse?

changing to `step=pm.Metropolis()`, I sometimes get stuff like:

```python
# Very bad, the second mean seems to be consistently biased
print(expected_mean, trace["x"].mean(axis=0))
# [-0.1  0.5  1.1] [  0.29549842 -14.04723709   1.09591073]

# Also poor
print(expected_std, trace["x"].std(axis=0)) 
# [ 0.56672996 10.00041321  0.18181818] [0.53156382 4.79229857 0.18407155]
```

Edit: Metropolis can cope if we pass an appropriate `S` to it for the covariance of the proposal

**Comment by twiecki** [comment]
What do the traces look like?

**Comment by ricardoV94** [comment]
Slice sampler:
![image](https://user-images.githubusercontent.com/28983449/170827922-aae3880e-09e4-4eae-8692-c032bf56f659.png)

Metropolis sampler:
![image](https://user-images.githubusercontent.com/28983449/170827962-b96ae5c2-4ead-4585-85ef-38177eaa9075.png)

NUTS:
![image](https://user-images.githubusercontent.com/28983449/170827995-0f5c5194-5fc2-4bf0-92b0-b3755d2ca7f7.png)

**Comment by ricardoV94** [comment]
I understand the default Metropolis has one single proposal distribution (?), but the Slice should propose values independently per dimension, so I don't understand why is it still biased. 

~~Maybe it's not too biased, it's just the crazy standard deviation of the second component?~~

~~Edit: Yeah, maybe the test was just too damn strict~~

**Comment by ricardoV94** [comment]
I think I found a bug in the Slice sampler. It is no longer biased after fixing it
