### ISSUE TITLE
Bring back Books + Videos page

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5825]
Personally I'm not a big fan of the latest learning page: https://docs.pymc.io/en/latest/learning.html

It has too much text, lacks images, and the structure is quite confusing.

So I think we should bring back the old Learning page (Books + Videos): https://docs.pymc.io/en/v3/learn.html

**Comment by canyon289** [comment]
Also agree, this was one of the first pages that caught my attention and got me interested in Bayesian stats
