### ISSUE TITLE
Add `logp` migration table to the migration guide

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#5831]
Even the core devs are struggling with `logp` migrations.

We should have a before/after table with concise code examples for `logp` migrations.

This includes:

* `rv.logp()`
* `pmodel.logp()`
* with or without givens

For example:
+ In the dev guide: https://github.com/pymc-devs/pymc/pull/5810/files#diff-2dd3f1e1d9830aa03aa4abc57b71c2d307d439c1349987fc12cfd1db7fff85acR93-R98
+ A code block in `calibr8` where logps are calculated with `v3`, `v4` and SciPy: https://github.com/JuBiotech/calibr8/blob/363c526d755eebd40502a5790c36f9b9b7db3c2c/calibr8/core.py#L525-L532

**Comment by twiecki** [comment]
This would be nice to have but I don't think is a blocker for v4. We have some notes on this in the release notes.

**Comment by ricardoV94** [comment]
Closing this as it didn't seem to be a problem in the end.
