### ISSUE TITLE
DiscreteUniform for fixed point generates unexpected test value

### ISSUE THREAD

**Issue by arthur-e** [pymc-devs/pymc#5836]
Based on [this previous example](https://github.com/pymc-devs/pymc/issues/2185), I can demonstrate some unexpected behavior in `DiscreteUniform`:

```python
import pymc3 as pm

model1 = pm.Model()
with model1:
    a = pm.DiscreteUniform('a', lower = 0.1, upper = 0.1)
print('test_point model1: {}'.format(model1.test_point))

model2 = pm.Model()
with model2:
    b = pm.DiscreteUniform('a', lower = 0.1, upper = 0.1, testval = 0.1)
print('test_point model2: {}'.format(model2.test_point))
```

```
test_point model1: {'a': array(0)}
test_point model2: {'a': array(0)}
```

In both cases, I would have expected the test value to be 0.1. There is further interesting behavior with different number types:

```python
import pymc3 as pm

model1 = pm.Model()
with model1:
    a = pm.DiscreteUniform('a', lower = -8, upper = -8)
print('test_point model1: {}'.format(model1.test_point))

model2 = pm.Model()
with model2:
    b = pm.DiscreteUniform('a', lower = 3.6, upper = 3.6)
print('test_point model2: {}'.format(model2.test_point))
```

```
test_point model1: {'a': array(-8)}
test_point model2: {'a': array(3)}
```

It's possible I'm abusing `DiscreteUniform` here, although it does work in sampling (i.e., posterior probability mass is concentrated at a single value). I'm trying to allow for parameters that might be fixed under certain circumstances without changing my model's API.

## Versions and main components

* PyMC/PyMC3 Version: 3.11.4
* `Theano-PyMC==1.1.2`
* Python Version: 3.8.10
* Operating system: Ubuntu GNU/Linux 20.04
* How did you install PyMC/PyMC3: `pip`

**Comment by arthur-e** [comment]
I can confirm that this impacts PyMC3 version 3.11.5 (latest), as well, and that the same result is obtained using `pm.Constant`:

```python
import pymc3 as pm

model1 = pm.Model()
with model1:
    a = pm.Constant('a', c = 0.1)
print('test_point model1: {}'.format(model1.test_point))

model2 = pm.Model()
with model2:
    a = pm.Constant('a', c = 0.1, testval = 0.1)
print('test_point model2: {}'.format(model2.test_point))

model3 = pm.Model()
with model3:
    a = pm.Constant('a', c = -8)
print('test_point model3: {}'.format(model3.test_point))
```

```
test_point model1: {'a': array(0)}
test_point model2: {'a': array(0)}
test_point model3: {'a': array(-8)}
```

**Comment by ricardoV94** [comment]
The discrete uniform only allows for discrete values, so those bounds don't apply. At some point we truncate those values and that's why you get the 3

**Comment by ricardoV94** [comment]
For `pm.Constant` you can use float values but you probably don't want to be sampling it as an unobserved variable in the first place (see #5716)
