### ISSUE TITLE
Add wrapper for theano as_op

### ISSUE THREAD

**Issue by karlnapf** [pymc-devs/pymc#584]
Hi there,

is there a way to make pymc3 use custom density functions that are not theano compatible?
Say I have some black box c-code to evaluate my log-pdf, and now I want to use this with one of pymc3's gradient free samplers such as metropolis.

Currently, trying this gives me things like `object of type 'TensorVariable' has no len()` when trying to use my own python code to evaluate a log-pdf (which assumes the input is a numpy array).

Thanks for your help and for the great package!

**Comment by twiecki** [comment]
Hi Heiko,

Seems to be a dupe of https://github.com/pymc-devs/pymc/issues/507. E.g.

``` python
@theano.compile.ops.as_op(itypes=[t.lscalar, t.dscalar, t.dscalar],otypes=[t.dvector])
def rate(switchpoint,early_mean, late_mean):
    ''' Concatenate Poisson means '''
    out = empty(years)
    out[:switchpoint] = early_mean
    out[switchpoint:] = late_mean
    return out
```

Let me know if that works or doesn't work for you.

**Comment by twiecki** [comment]
Closing, feel free to reopen if this doesn't work for you.

**Comment by karlnapf** [comment]
Hi Thomas,

thanks for the help, that fixed the problem. Amazing! Now I can do pseudo-marginal MCMC models using PyMC, which is something I am working on and would like to use PyMC for.

For others, here is how I did it:
http://nbviewer.ipython.org/gist/karlnapf/8ed7de163eed39e733da

**Comment by twiecki** [comment]
Cool, thanks for sharing!

**Comment by twiecki** [comment]
I also wonder if we should create a wrapper around `@theano.compile.ops.as_op(itypes=[T.dscalar],otypes=[T.dscalar])` because it requires another call to `pm.DensityDist('y', logp)`. Something along the lines of:

``` python
@CustomDensity(itypes=[T.dscalar],otypes=[T.dscalar])
def MyCustomDist():...

with model:
    my_dist = MyCustomDist('y', ...)
```

CC @fonnesbeck @jsalvatier

**Comment by jsalvatier** [comment]
Yes, that's true. I wonder if it should be T.dvector though, since that
seems like a more common case. I like this idea.

**Comment by fonnesbeck** [comment]
I like it too. In favor of anything that hides the Theano complexity from most users.

**Comment by jsalvatier** [comment]
https://github.com/Theano/Theano/issues/3094 issue should make it easier to make as_op make theano ops.

**Comment by fonnesbeck** [comment]
Is this still something we worry about? Its pretty easy to create custom distributions now.

**Comment by twiecki** [comment]
Yeah, I think it's fine, haven't heard many complaints.
