### ISSUE TITLE
Add a guide on how to build the docs

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5843]
## Description of your problem
I can't find the guide where I'd expect it. Adding a link to instructions would be great

https://github.com/pymc-devs/pymc/blob/main/CONTRIBUTING.md
![image](https://user-images.githubusercontent.com/7213793/171867504-5424a2b3-b1f1-4526-bc19-f0a9258c314a.png)

**Comment by OriolAbril** [comment]
The guide is already at https://docs.pymc.io/en/latest/contributing/build_docs.html. It probably needs to be improved but it is there. It is missing form these quick links though. We can add them but I think it would probably be best to reword them so it is crystal clear that these are not the contributing guide and that something missing from there doesn't mean it does not exist.
