### ISSUE TITLE
Run test suite only for earliest and latest Python releases

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#5844]
We currently test on 3.7, 3.8, 3.9. We should instead just test on 3.8 and 3.10 only.

**Comment by aloctavodia** [comment]
Actually it should be 3.8 instead of 3.7 https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by ricardoV94** [comment]
Note that we are not running duplicated tests in different versions anymore, but split tests across different OSes and supported Python versions

**Comment by ricardoV94** [comment]
Closing this issue. I think #5911 simplified things well enough and is now easier to decide what tests to run in what Python versions
