### ISSUE TITLE
name 'platform' is not defined with pymc3==3.11.5 and py37

### ISSUE THREAD

**Issue by Alexander-Serov** [pymc-devs/pymc#5858]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**

We are unable to run pymc3 tests on our CI with version 3.11.5 with a weird error message:

```
my_module.py:11: in <module>
    import pymc3 as pm
/usr/local/lib/python3.9/site-packages/pymc3/__init__.py:115: in <module>
    from pymc3 import gp, ode, sampling
/usr/local/lib/python3.9/site-packages/pymc3/gp/__init__.py:16: in <module>
    from pymc3.gp.gp import TP, Latent, LatentKron, Marginal, MarginalKron, MarginalSparse
/usr/local/lib/python3.9/site-packages/pymc3/gp/gp.py:25: in <module>
    from pymc3.distributions import draw_values
/usr/local/lib/python3.9/site-packages/pymc3/distributions/__init__.py:15: in <module>
    from pymc3.distributions import shape_utils, timeseries, transforms
/usr/local/lib/python3.9/site-packages/pymc3/distributions/timeseries.py:21: in <module>
    from pymc3.distributions import distribution, multivariate
/usr/local/lib/python3.9/site-packages/pymc3/distributions/distribution.py:27: in <module>
    from deprecat.sphinx import deprecat
/usr/local/lib/python3.9/site-packages/deprecat/sphinx.py:35: in <module>
    if platform.python_implementation() == "PyPy":
E   NameError: name 'platform' is not defined
```

Downgrading to 3.11.4 solves the problem. Locally, I cannot reproduce on Windows.

But I have a feeling there should be a simple fix for this bug, perhaps fixing the sphinx version?

**Please provide the full traceback.**

N/A

**All packages installed by the CI**

Successfully installed arviz-0.12.1 cfgrib-0.9.9.0 deprecat-2.1.1 eccodes-1.4.2 execnet-1.9.0 fastprogress-1.0.2 findlibs-0.0.2 julian-0.14 kaleido-0.2.1 missingno-0.5.1 numpy==1.21.5 patsy-0.5.2 ply-3.11 pydivsufsort-0.0.6 pymc3-3.11.5 pyomo-6.4.1 pytest-forked-1.4.0 pytest-xdist-2.5.0 seaborn-0.10.1 semver-2.13.0 singledispatchmethod-1.0 statsmodels-0.13.2 theano-pymc-1.1.2 xarray-einstats-0.2.2

## Versions and main components

* PyMC/PyMC3 Version: 3.11.5
* Aesara/Theano Version: Theano 1.1.2
* Python Version: 3.7
* Operating system: Linux
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by twiecki** [comment]
Can you try on pymc 4.0?

**Comment by PolarSprings** [comment]
This fails with pymc===4.0.

**Comment by twiecki** [comment]
@PolarSprings The most recent pymc version, rather.
