### ISSUE TITLE
Remove `t` suffix from `Model` methods

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#5859]
`model.logpt`, `model.dlogpt` and `model.d2logpt` would be a bit more intuitive without the `t` suffix. Historically that was done to distinguish the `tensor` graphs from the compiled functions, but those are now obtained via `model.compile_logp`, `model.compile_dlogp` and `model.compile_d2logp`.

**Comment by twiecki** [comment]
I never knew what the `t` stood for, so yes, best to remove.

**Comment by ricardoV94** [comment]
If anyone wants to take a go, this should be a simple deprecation PR: 
1. Rename the new methods to `pymc.model.Model` without the `t` suffix, 
2. Keep the old ones as a simple wrapper that issues a FutureWarning in between. 
3. Change all the tests to make use of the new names,
4.  Add some tiny tests to make sure the deprecation is being issued,
5. Create a new Github Issue to remove the deprecated names in `v4.2`

**Comment by cuchoi** [comment]
I can take this one if that's ok!

**Comment by twiecki** [comment]
@cuchoi Great, just open a draft PR so that people see you're working on it.

**Comment by cuchoi** [comment]
Should I update `datalogpt`, `varlogpt`, `observedlogpt`, and `potentiallogpt`, `distributions.joint_logpt` as well?

**Comment by ricardoV94** [comment]
> Should I update `datalogpt`, `varlogpt`, `observedlogpt`, and `potentiallogpt`, `distributions.joint_logpt` as well?

Yes! I forgot about those

**Comment by cuchoi** [comment]
Cool. Should I update documentation such as docs/source/contributing/developer_guide.rst and docs/source/learn/core_notebooks/pymc_aesara.ipynb?

**Comment by ricardoV94** [comment]
> Cool. Should I update documentation such as docs/source/contributing/developer_guide.rst and docs/source/learn/core_notebooks/pymc_aesara.ipynb?

Yes

**Comment by ricardoV94** [comment]
Opening this as a reminder to deprecate in a future major release
