### ISSUE TITLE
update link to blog or example

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#5866]
@drbenvincent 
Can you share the updated link to this:
https://docs.pymc.io/projects/examples/en/latest/case_studies/regression_discontinuity.html

It seems to be broken since the release.

cc: @kanaliberyl

**Comment by drbenvincent** [comment]
Hi. The link to the regression discontinuity example is
https://www.pymc.io/projects/examples/en/latest/case_studies/regression_discontinuity.html

Where is it that has the old/broken link?

**Comment by drbenvincent** [comment]
I tweeted out a list of all the updated url's here https://twitter.com/inferencelab/status/1542818623298969600. Well, for the notebooks I've authored at least

So we think this issue can be closed, or is there anything else @reshamas?

**Comment by reshamas** [comment]
Thanks @drbenvincent
