### ISSUE TITLE
Remove all install guides from wiki and move to source control

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5868]
## Description of your problem
People can edit wiki silently which is an issue for install guides
https://twitter.com/pymc_devs/status/1534472124072591362

Moving to source control means they can't be edited without visibility and approval

**Comment by twiecki** [comment]
> People can edit wiki silently which is an issue for install guides

This used to be the case but isn't anymore.

Regardless moving them is a good idea. We can now also merge all installation instructions into one.

Ref https://github.com/pymc-devs/pymc/pull/5835
