### ISSUE TITLE
Install Guide links are broken

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5872]
## Description of your problem
I believe we're working through updating just flagging 
![image](https://user-images.githubusercontent.com/7213793/172861534-216c633a-54b1-43e0-b5f7-56deaa20ab59.png)

**Comment by twiecki** [comment]
Where did they go?!

**Comment by canyon289** [comment]
Im a little behind on the current status of things as I know were moving fast on this, but I believe this is what was the last update

For install guides being a bit more proactive with reporting, even if theres false positives, due to the release and the security issues. Hope thats alright. I can help fix after my workday as well, for now just have time to report

https://github.com/pymc-devs/pymc/pull/5869

**Comment by twiecki** [comment]
OK, looks like @fonnesbeck deleted them, I think that was premature as we haven't updated everything and the new ones are not in place and linked properly. The security risk is gone now so there's no problem having them up there and there's no rush.

I recovered them for now.
