### ISSUE TITLE
pm.sample() raises AttributeError

### ISSUE THREAD

**Issue by ThomasHoppe** [pymc-devs/pymc#5876]
Running on PyMC3 v4.0.0
under Python 3.8.10

Unclear from where this error originates 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [21], in <module>
      1 with basic_model:
----> 2     trace = pm.sample(draws=1000,tune=2000)

File ~/.local/lib/python3.8/site-packages/pymc/sampling.py:524, in sample(draws, step, init, n_init, initvals, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, **kwargs)
    521         auto_nuts_init = False
    523 initial_points = None
--> 524 step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    526 if isinstance(step, list):
    527     step = CompoundStep(step)

File ~/.local/lib/python3.8/site-packages/pymc/sampling.py:215, in assign_step_methods(model, step, methods, step_kwargs)
    213 if has_gradient:
    214     try:
--> 215         tg.grad(model_logpt, var)
    216     except (NotImplementedError, tg.NullTypeGradError):
    217         has_gradient = False

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:635, in grad(cost, wrt, consider_constant, disconnected_inputs, add_names, known_grads, return_disconnected, null_gradients)
    632     if hasattr(g.type, "dtype"):
    633         assert g.type.dtype in aesara.tensor.type.float_dtypes
--> 635 rval = _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
    637 for i in range(len(rval)):
    638     if isinstance(rval[i].type, NullType):

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1439, in _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
   1436     # end if cache miss
   1437     return grad_dict[var]
-> 1439 rval = [access_grad_cache(elem) for elem in wrt]
   1441 return rval

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1439, in <listcomp>(.0)
   1436     # end if cache miss
   1437     return grad_dict[var]
-> 1439 rval = [access_grad_cache(elem) for elem in wrt]
   1441 return rval

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

    [... skipping similar frames: _populate_grad_dict.<locals>.access_grad_cache at line 1392 (4 times), <listcomp> at line 1064 (3 times), _populate_grad_dict.<locals>.access_term_cache at line 1064 (3 times)]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1219, in _populate_grad_dict.<locals>.access_term_cache(node)
   1211         if o_shape != g_shape:
   1212             raise ValueError(
   1213                 "Got a gradient of shape "
   1214                 + str(o_shape)
   1215                 + " on an output of shape "
   1216                 + str(g_shape)
   1217             )
-> 1219 input_grads = node.op.L_op(inputs, node.outputs, new_output_grads)
   1221 if input_grads is None:
   1222     raise TypeError(
   1223         f"{node.op}.grad returned NoneType, expected iterable."
   1224     )

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:529, in Elemwise.L_op(self, inputs, outs, ograds)
    526 from aesara.tensor.math import sum as at_sum
    528 # Compute grad with respect to broadcasted input
--> 529 rval = self._bgrad(inputs, outs, ograds)
    531 # TODO: make sure that zeros are clearly identifiable
    532 # to the gradient.grad method when the outputs have
    533 # some integer and some floating point outputs
    534 if any(out.type.dtype not in continuous_dtypes for out in outs):
    535     # For integer output, return value may only be zero or undefined
    536     # We don't bother with trying to check that the scalar ops
    537     # correctly returned something that evaluates to 0, we just make
    538     # the return value obviously zero so that gradient.grad can tell
    539     # this op did the right thing.

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:629, in Elemwise._bgrad(self, inputs, outputs, ograds)
    627         ret.append(None)
    628         continue
--> 629     ret.append(transform(scalar_igrad))
    631 return ret

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:602, in Elemwise._bgrad.<locals>.transform(r)
    600 def transform(r):
    601     # From a graph of ScalarOps, make a graph of Broadcast ops.
--> 602     if isinstance(r.type, (NullType, DisconnectedType)):
    603         return r
    604     if r in scalar_inputs:

AttributeError: 'float' object has no attribute 'type'

**Comment by ricardoV94** [comment]
Can you post the model?

**Comment by ThomasHoppe** [comment]
Here comes the model: a model for generating virtuell bags of M&Ms
Under pymc3 it is working (except for the renaming of .eval() to .random() and pm.math to tt

---------------------------

```python
basic_model = pm.Model()

with basic_model:
    
    Anzahl = pm.DiscreteUniform('N', lower=125, upper= 135)
    
    color_model = pm.Model()
    
    with color_model:
        
        N = Anzahl.eval()
    
        #Gewichtsverteilung eines einzelnen M&Ms
        GewichtEinMuM = pm.TruncatedNormal('GewichtEinMuM', mu=2.33, sigma=0.44, lower=1.)
        #Gewichtsverteilung einer Tüte mit N M&Ms
        GewichtTüteMuM = pm.TruncatedNormal('GewichtTüteMuM', mu=2.33, sigma=0.44, lower=1., shape=(1,N))
        # Gewicht einer Tüte M&Ms
        TütenGewicht = pm.Deterministic('TütenGewicht', pm.math.sum(GewichtTüteMuM))
        
        # Das Gewicht einer Tüte kann potentiell um ein M&M nach unten oder oben abweichen
        GueltigeTuete = pm.Potential('GültigeTüte', 
                                     pm.math.switch((TütenGewicht < 300), N,
                                               pm.math.switch((TütenGewicht < 300+GewichtEinMuM), N,
                                                         0)))
        
        TuetenMuMFarbe = pm.Categorical('M&M', p=[.207, .205, .198, .135, .131, .124], shape=(1,N))
```

**Comment by michaelosthege** [comment]
You're probably mixing up imports.
If you have `pymc==4.0.0` installed, your imports should be updated to this:

```
import pymc as pm
import aesara.tensor as at
```

And, for example, instead of `tt.switch` do `at.switch`

**Comment by ThomasHoppe** [comment]
> 

No, sorry I uploaded the wrong model. I've just seen that some seconds ago. I included now the correct model above.
Sorry for the inconvinience.

**Comment by michaelosthege** [comment]
Ok I reformatted the code to not have two nested models:

```python
N = pm.DiscreteUniform.dist(lower=125, upper= 135).eval()

with pm.Model() as basic_model: 
    # Gewichtsverteilung eines einzelnen M&Ms
    GewichtEinMuM = pm.TruncatedNormal('GewichtEinMuM', mu=2.33, sigma=0.44, lower=1.)
    
    # Gewichtsverteilung einer Tüte mit N M&Ms
    GewichtTüteMuM = pm.TruncatedNormal('GewichtTüteMuM', mu=2.33, sigma=0.44, lower=1., shape=(1,N))
    
    # Gewicht einer Tüte M&Ms
    TütenGewicht = pm.Deterministic('TütenGewicht', pm.math.sum(GewichtTüteMuM))

    # Das Gewicht einer Tüte kann potentiell um ein M&M nach unten oder oben abweichen
    GueltigeTuete = pm.Potential(
        'GültigeTüte', 
        pm.math.switch(
            (TütenGewicht < 300),
            N,
            pm.math.switch(
                (TütenGewicht < 300+GewichtEinMuM),
                N,
                0
            )
        )
    )

    TuetenMuMFarbe = pm.Categorical('M&M', p=[.207, .205, .198, .135, .131, .124], shape=(1,N))
```

With this it can be sampled with `pm.Metropolis()` but not with NUTS, because your `Potential` is not differentiable. (It's either 0 or `N`, where `N` is a non-symbolic integer.)

**Comment by ThomasHoppe** [comment]
> 

Thanx, but I don't think, that this reformulation will do what I intend. Anyway, the error remains the same, if I just use:

trace = pm.sample(draws=1000,tune=2000)

Shouldn't pm.sample() figure out on its own, which sampler to use?

With (The documentation https://docs.pymc.io/en/latest/api/generated/pymc.sample.html is a bit unclear) :

with basic_model:
    trace = pm.sample(draws=1000,tune=2000,step='metropolis')    
I get another bug:

---------------------------------------------------------------------------

```
AttributeError                            Traceback (most recent call last)
Input In [9], in <module>
      1 with basic_model:
----> 2     trace = pm.sample(draws=1000,tune=2000,step='metropolis')

File ~/.local/lib/python3.8/site-packages/pymc/sampling.py:524, in sample(draws, step, init, n_init, initvals, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, **kwargs)
    521         auto_nuts_init = False
    523 initial_points = None
--> 524 step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    526 if isinstance(step, list):
    527     step = CompoundStep(step)

File ~/.local/lib/python3.8/site-packages/pymc/sampling.py:202, in assign_step_methods(model, step, methods, step_kwargs)
    200         steps.append(step)
    201     for step in steps:
--> 202         assigned_vars = assigned_vars.union(set(step.vars))
    204 # Use competence classmethods to select step methods for remaining
    205 # variables
    206 selected_steps = defaultdict(list)

AttributeError: 'str' object has no attribute 'vars'
```

**Comment by michaelosthege** [comment]
The `pm.sample(step=...)` kwarg doesn't accept a string.
You'll have to pass a step method instance (`pm.Metropolis()`).

We could raise a more informative error though.

**Comment by ThomasHoppe** [comment]
OK,  I experimented further.

Using pm.sample( ...., step = pm.Metropolis()) the sampling works, but gives different results as the same model under pymc3 :-( 

Using under pymc3 now:

with basic_model:
    step = [pm.Metropolis([Anzahl]),
     pm.CategoricalGibbsMetropolis([TuetenMuMFarbe]),
     pm.NUTS([GewichtTüteMuM, GewichtEinMuM])]
    trace = pm.sample(draws=1000,tune=2000,step=step)     

I get, what I expect.

![grafik](https://user-images.githubusercontent.com/13870131/173191160-f1577aca-a3e3-4d4e-9d16-2f69c7f61aa2.png)

Running it under pymc:

I get:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [18], in <module>
      1 with basic_model:
      2     #step = pm.Metropolis()
      3     step = [pm.Metropolis([Anzahl]),
      4      pm.CategoricalGibbsMetropolis([TuetenMuMFarbe]),
----> 5      pm.NUTS([GewichtTüteMuM, GewichtEinMuM])]
      6     trace = pm.sample(draws=1000,tune=2000,step=step)

File ~/.local/lib/python3.8/site-packages/pymc/step_methods/hmc/nuts.py:169, in NUTS.__init__(self, vars, max_treedepth, early_max_treedepth, **kwargs)
    111 def __init__(self, vars=None, max_treedepth=10, early_max_treedepth=8, **kwargs):
    112     r"""Set up the No-U-Turn sampler.
    113 
    114     Parameters
   (...)
    167     `pm.sample` to the desired number of tuning steps.
    168     """
--> 169     super().__init__(vars, **kwargs)
    171     self.max_treedepth = max_treedepth
    172     self.early_max_treedepth = early_max_treedepth

File ~/.local/lib/python3.8/site-packages/pymc/step_methods/hmc/base_hmc.py:95, in BaseHMC.__init__(self, vars, scaling, step_scale, is_cov, model, blocked, potential, dtype, Emax, target_accept, gamma, k, t0, adapt_step_size, step_rand, **aesara_kwargs)
     92 else:
     93     vars = [self._model.rvs_to_values.get(var, var) for var in vars]
---> 95 super().__init__(vars, blocked=blocked, model=self._model, dtype=dtype, **aesara_kwargs)
     97 self.adapt_step_size = adapt_step_size
     98 self.Emax = Emax

File ~/.local/lib/python3.8/site-packages/pymc/step_methods/arraystep.py:276, in GradientSharedStep.__init__(self, vars, model, blocked, dtype, logp_dlogp_func, **aesara_kwargs)
    273 model = modelcontext(model)
    275 if logp_dlogp_func is None:
--> 276     func = model.logp_dlogp_function(vars, dtype=dtype, **aesara_kwargs)
    277 else:
    278     func = logp_dlogp_func

File ~/.local/lib/python3.8/site-packages/pymc/model.py:636, in Model.logp_dlogp_function(self, grad_vars, tempered, **kwargs)
    632 ip = self.initial_point(0)
    633 extra_vars_and_values = {
    634     var: ip[var.name] for var in extra_vars if var in input_vars and var not in grad_vars
    635 }
--> 636 return ValueGradFunction(costs, grad_vars, extra_vars_and_values, **kwargs)

File ~/.local/lib/python3.8/site-packages/pymc/model.py:370, in ValueGradFunction.__init__(self, costs, grad_vars, extra_vars_and_values, dtype, casting, compute_grads, **kwargs)
    367     givens.append((var, shared))
    369 if compute_grads:
--> 370     grads = aesara.grad(cost, grad_vars, disconnected_inputs="ignore")
    371     for grad_wrt, var in zip(grads, grad_vars):
    372         grad_wrt.name = f"{var.name}_grad"

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:635, in grad(cost, wrt, consider_constant, disconnected_inputs, add_names, known_grads, return_disconnected, null_gradients)
    632     if hasattr(g.type, "dtype"):
    633         assert g.type.dtype in aesara.tensor.type.float_dtypes
--> 635 rval = _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
    637 for i in range(len(rval)):
    638     if isinstance(rval[i].type, NullType):

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1439, in _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
   1436     # end if cache miss
   1437     return grad_dict[var]
-> 1439 rval = [access_grad_cache(elem) for elem in wrt]
   1441 return rval

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1439, in <listcomp>(.0)
   1436     # end if cache miss
   1437     return grad_dict[var]
-> 1439 rval = [access_grad_cache(elem) for elem in wrt]
   1441 return rval

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

    [... skipping similar frames: _populate_grad_dict.<locals>.access_grad_cache at line 1392 (3 times), <listcomp> at line 1064 (2 times), _populate_grad_dict.<locals>.access_term_cache at line 1064 (2 times)]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in _populate_grad_dict.<locals>.access_term_cache(node)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1064, in <listcomp>(.0)
   1060 if node not in term_dict:
   1062     inputs = node.inputs
-> 1064     output_grads = [access_grad_cache(var) for var in node.outputs]
   1066     # list of bools indicating if each output is connected to the cost
   1067     outputs_connected = [
   1068         not isinstance(g.type, DisconnectedType) for g in output_grads
   1069     ]

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1392, in _populate_grad_dict.<locals>.access_grad_cache(var)
   1389 for node in node_to_idx:
   1390     for idx in node_to_idx[node]:
-> 1392         term = access_term_cache(node)[idx]
   1394         if not isinstance(term, Variable):
   1395             raise TypeError(
   1396                 f"{node.op}.grad returned {type(term)}, expected"
   1397                 " Variable instance."
   1398             )

File ~/.local/lib/python3.8/site-packages/aesara/gradient.py:1219, in _populate_grad_dict.<locals>.access_term_cache(node)
   1211         if o_shape != g_shape:
   1212             raise ValueError(
   1213                 "Got a gradient of shape "
   1214                 + str(o_shape)
   1215                 + " on an output of shape "
   1216                 + str(g_shape)
   1217             )
-> 1219 input_grads = node.op.L_op(inputs, node.outputs, new_output_grads)
   1221 if input_grads is None:
   1222     raise TypeError(
   1223         f"{node.op}.grad returned NoneType, expected iterable."
   1224     )

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:529, in Elemwise.L_op(self, inputs, outs, ograds)
    526 from aesara.tensor.math import sum as at_sum
    528 # Compute grad with respect to broadcasted input
--> 529 rval = self._bgrad(inputs, outs, ograds)
    531 # TODO: make sure that zeros are clearly identifiable
    532 # to the gradient.grad method when the outputs have
    533 # some integer and some floating point outputs
    534 if any(out.type.dtype not in continuous_dtypes for out in outs):
    535     # For integer output, return value may only be zero or undefined
    536     # We don't bother with trying to check that the scalar ops
    537     # correctly returned something that evaluates to 0, we just make
    538     # the return value obviously zero so that gradient.grad can tell
    539     # this op did the right thing.

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:629, in Elemwise._bgrad(self, inputs, outputs, ograds)
    627         ret.append(None)
    628         continue
--> 629     ret.append(transform(scalar_igrad))
    631 return ret

File ~/.local/lib/python3.8/site-packages/aesara/tensor/elemwise.py:602, in Elemwise._bgrad.<locals>.transform(r)
    600 def transform(r):
    601     # From a graph of ScalarOps, make a graph of Broadcast ops.
--> 602     if isinstance(r.type, (NullType, DisconnectedType)):
    603         return r
    604     if r in scalar_inputs:

AttributeError: 'float' object has no attribute 'type'

----- 

So, I don't think that is an issue with my model. Instead it seems still to be a difference between pymc3 and pymc.

**Comment by ThomasHoppe** [comment]
This issue is resolved. There was a formulation problem within the model. 
Anyway the error messages should be made more clearer
