### ISSUE TITLE
Self-pointing arrow with observed nodes

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#5892]
```python
import pymc as pm
import numpy as np

data = np.random.normal(loc=5., scale=1.5, size=[1000,])

with pm.Model() as model:
    mu = pm.Normal(name="mu", mu=0., sigma=5.)
    y = pm.Normal(name="y", mu=mu, sigma=3., observed=data)
    
pm.model_to_graphviz(model)
```

yields:

<img width="181" alt="Screen Shot 2022-06-13 at 11 03 44 PM" src="https://user-images.githubusercontent.com/24764859/173445153-e270d8c7-1576-4d2a-aea3-cd89d2e2e693.png">

Notice the arrow from the `y` node to itself because `data` is a NumPy array and hence does not have a name.

**Comment by ricardoV94** [comment]
My guess is that the arrow comes from the resizing of the RV to match the observed data. Does it disappear when you pass shape explicitly?

**Comment by ricardoV94** [comment]
There are some "annoying" arrows from data to likelihood in these examples for the same reason: https://mobile.twitter.com/pymc_devs/status/1518280058699501569

**Comment by michaelosthege** [comment]
The self-referencing arrow goes away when the `data` is wrapped in a `pm.Data`.

**Comment by larryshamalama** [comment]
> My guess is that the arrow comes from the resizing of the RV to match the observed data. Does it disappear when you pass shape explicitly?

It has to do with how we're checking for observed nodes:

https://github.com/pymc-devs/pymc/blob/5d003dc31d49dbdaf647f6848ca03a641fb34e32/pymc/model_graph.py#L100-L105

Here, `obs_name` would also be `"y"` and that's why there is a self-pointing arrow
