### ISSUE TITLE
PyMC and Aesara always activate use of GPUs.

### ISSUE THREAD

**Issue by Sangwon91** [pymc-devs/pymc#5894]
## Description of your problem

Hi. For my system, the use of GPU is too slow so it has to be disabled.
It seems I can disable the GPUs using environment variables as below

```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['AESARA_FLAGS'] = 'device=cpu,force_device=True'
os.environ['THEANO_FLAGS'] = 'device=cpu,force_device=True'

import numpy as np

from scipy.interpolate import interp1d

import matplotlib as mpl
import matplotlib.pyplot as plt

import pymc as pm

import aesara
import aesara.tensor as at

print(
    aesara.config.device,
    aesara.config.force_device,
)

import arviz as az
```
And I got this message:

```python
WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl
cpu True
```

Unfortunately, whenever I execute the graph (e.g. via ``pm.sample``) task manager tells that
PyMC and Aesara utilize GPUs... and it takes almost infinite time to get the result of sampling.

Any suggestions? Thank you.

## Versions and main components

* PyMC/PyMC3 Version: PyMC
* Aesara/Theano Version: Aesara
* Python Version: 3.8.12
* Operating system: Windows
* How did you install PyMC/PyMC3: conda

**Comment by ricardoV94** [comment]
PyMC/Aesara is not using any GPUs, unless you use sampling_jax, but that is not available on Windows

Are you sure usage comes from PyMC and not say hardware acceleration from your browser (e.g. with jupyter notebook) or something else?

Otherwise, could it be some malware on your system?

**Comment by Sangwon91** [comment]
If so I think I have to find the reason from other sides.
Thank you for your response!
