### ISSUE TITLE
Is there a way to represent a model as a DAG in Pymc3?

### ISSUE THREAD

**Issue by bpajusco** [pymc-devs/pymc#590]
I liked the the graph generation functionality provided by PyDot in Pymc 2 and assumed it would have ported to Pymc3 so I tried to import 'graph' from pymc and got a cannot import module 'graph' error. The error message is self explanatory but makes me wonder whether we have that possibility with Pymc3. Given that is based on Theano I'm inclined to believe that is possible to generate a graph of the model but I have no idea how to. Is there a way to learn about this?

Thanks,
Bruno

**Comment by fonnesbeck** [comment]
There is no DAG graphing currently in PyMC 3, but it is something we need. I know theano has a `FunctionGraph` object, and [others have devised ways of turning these into DAGs](https://github.com/mrocklin/dicdag/blob/master/dicdag/theano/theano_dag.py). I would be inclined to incorporate [igraph](igraph.org) to do the graphical side of this.

**Comment by datnamer** [comment]
would this project be helpful?  http://daft-pgm.org/

**Comment by majidaldo** [comment]
wouldn't this be just following the parent/child relationships of the nodes?

**Comment by twiecki** [comment]
@majidaldo Yes, but we don't have that relationship encoding anywhere right now.

**Comment by fonnesbeck** [comment]
You can certaintly use Theano's `pydotprint` to get a DAG of the Theano graph, but you might not like the look of it:

```
with pymc3.Model() as basic_model:
    # Priors for unknown model parameters
    sigma_beta = pymc3.HalfNormal('sigma_beta', 0.5)
    alpha = pymc3.Normal('alpha', mu=0, sd=1)
    sigma = pymc3.HalfNormal('sigma', 1.5)
    beta = pymc3.Normal('beta', mu=0, sd=sigma_beta, shape=2)

    mu = alpha + beta[0] * X1 + beta[1] * X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pymc3.Normal('Y_obs', mu=mu, sd=sigma, observed=Y) 

```

```
from theano.printing import pydotprint

pydotprint(basic_model.logpt)
```

![](http://d.pr/i/19LBN/4QuI1IXp+)

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/pull/1683
