### ISSUE TITLE
Extremely variable MCMC sampling time

### ISSUE THREAD

**Issue by jmerkin** [pymc-devs/pymc#591]
I have some code (summarized below) that does some MCMC sampling with (in my mind) surprising behavior. 

Observed behavior: MCMC sampling sometimes completes in 2-3 seconds and sometimes takes minutes (same input data). 

Expected behavior: I set the same seed each time, so I would have thought it'd be exactly the same between runs.

Is the seed used by pymc different from the numpy.random.seed, or am I wrong for assuming the time run time should be the same given the same initial conditions?

Example run:
$python mcmc.py
[-------          20%                  ] 4183 of 20000 complete in 0.5 sec
[---------------  39%                  ] 7977 of 20000 complete in 1.0 sec
[-----------------58%--                ] 11798 of 20000 complete in 1.5 sec
[-----------------77%---------         ] 15594 of 20000 complete in 2.0 sec
[-----------------97%----------------  ] 19412 of 20000 complete in 2.5 sec
[-----------------100%-----------------] 20000 of 20000 complete in 2.6 sec

$python mcmc.py
[                  0%                  ] 38 of 20000 complete in 0.5 sec
[                  0%                  ] 66 of 20000 complete in 1.0 sec
[                  0%                  ] 95 of 20000 complete in 1.5 sec
...
[-----------------99%----------------- ] 19955 of 20000 complete in 380.2 sec
[-----------------99%----------------- ] 19980 of 20000 complete in 380.7 sec
[-----------------100%-----------------] 20000 of 20000 complete in 381.1 sec

code:

```
np.random.seed(42)

o1 = np.array([1 for _ in xrange(n1a)] + [0 for _ in xrange(n1b)])
o2 = np.array([1 for _ in xrange(n2a)] + [0 for _ in xrange(n2b)])

p1 = pm.Beta('p1', alpha=2, beta=2)
m1 = pm.Bernoulli('model1', p1, value=o1, observed=True)
p2 = pm.Beta('p2', alpha=1., beta=1.)
m2 = pm.Bernoulli('m2', p2, value=o2, observed=True)

@pm.deterministic
def delta(p1=p1, p2=p2):
    return p1 - p2

mcmc = pm.MCMC([p1, p2, delta, o1, o2])
mcmc.sample(20000, 1000)
```

**Comment by fonnesbeck** [comment]
I've been unable to replicate this behavior on my machine. I've run the script 20+ times, and each time it takes under 2s on my MB Air. Are you sure nothing is going on in the background on your machine? Can you replicate this behavior on another machine?

**Comment by jmerkin** [comment]
Thanks for the witch response (and great package!). I have replicated the
issue on 3 machines (they are all running the same rhel 5.X image) using an
up to date anaconda install.

I can give you an example of the actual observed data tomorrow though I am
very skeptical that it is the particular data. The machine isn't under
heavy load when I run it. It is iterating through a file and running this
analysis many times so it is the same data each time. When i observe one
example running slowly like this, all of them will (or at least the 5-10 i
had the patience to wait through will). If i kill and restart it, it may
switch state to the quick running state and blast through the analyses.

Let me know what other information i can provide and I'll do my best to
provide it.

**Comment by fonnesbeck** [comment]
What version of PyMC are you using? 2.3.3 or another? There have been some odd issues coming up in 2.3.3 that can't be replicated in the current 2.3 branch, so perhaps this is another.

**Comment by jmerkin** [comment]
I am using 2.3.3 (installed through anaconda), so that may be it. Is there
any debugging information I can run here that would help?

Jason Merkin

**Comment by pstjohn** [comment]
For whats its worth, I also saw similar differences in performance between runs using version 2.3.3.
Upgrading to 2.3.4 seems to have fixed the issue

**Comment by fonnesbeck** [comment]
I'm going to assume from the above that upgrading to 2.3.4 fixes this. Please reopen if not.
