### ISSUE TITLE
Pseudo Marginal MCMC & MH step

### ISSUE THREAD

**Issue by karlnapf** [pymc-devs/pymc#592]
Hi there,

I would like to use PyMC for pseudo marginal MCMC (likelihood is replaced by unbiased estimator, this still converges to the correct invariatn distribution). Based on #584 I can easily let pymc run on a custom density function, which returns an unbiased estimator of the likelihood the way I want it to be.

However, in Pseudo-marginal MCMC, once a state is accepted in the MH accept/reject step, the likelihood needs to be stored (its noisy), and all subsequent comparisons against that state must use the stored likelihood. Currently, the metropolis step method does
`q_new = metrop_select(logp(q) - logp(q0), q, q0)`
which has two problems:
- the likelihood is re-computed in every iteration, this means wasted computation since one could re-use the result from the previous iteration. If the likelihood is expensive to compute, this is bad.
- pseudo-marginal mcmc does not work this way. As mentioend above, in order for the existing step method to work with PM, the likelihood needs to be stored

So kind request: Please make the metropolis class store and re-use the likelihood. If you tell me how you would like this to look, I can also send a PR.

Thanks!

**Comment by kyleabeauchamp** [comment]
Heiko: I am also interested in exploring pseudo marginal MCMC, let me know how things proceed.  We might also chat sometime, as this is slightly further into theory-land than I usually adventure...

PS: we met at your recent MSKCC talk...

**Comment by fonnesbeck** [comment]
Yes, we definitely need to implement some sort of cacheing strategy, as we have with LazyFunction in PyMC 2.3. There is a `memoize` decorator, which we may be able to modify to be smarter, in terms of checking to see if any of a node's parents have changed prior to re-calculating.

I agree that having pseudo-marginal MCMC would be great, particularly as Gaussian processes are implemented.

**Comment by karlnapf** [comment]
Hi @kyleabeauchamp 
Yes I remember you from the talk. Nice that you are getting back!
Once I find the time (probably in between aistats and icml), I will try to finish the pseudo-marginal implementation in pymc, and also add the adaptive kernel proposal.

BTW using pseudo-marginal is super easy: Its just a std metropolis hastings with an unbiased estimator for the likelihood (not log-likelihood), and then store the likelihood value that you used to accept a sample for the next comparison. 

@fonnesbeck good to know about the decorator. Not sure what you mean with the GPs. If you want a good pseudo-marginal sampler on hyperparameters of a GP, as for example in Mark Girolami's paper on PM for GPs, you need to have access to some fast approximate inference schemes (EP, Laplace approx) for the importance sampling estimator of the marginal likelihood. So I think its better to leave this to people to provide custom estimators (using Shogun, pyGP, or similar)
