### ISSUE TITLE
2.3.4 Release

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#594]
There appear to have been a couple of bugs that crept into 2.3.3 that magically disappear in 2.3.4. I'm thinking then of creating a 2.3.4 bug fix release. Are the conda build issues sorted out yet? I was not sure based on the thread.

**Comment by fonnesbeck** [comment]
I've created a 2.3.4 release. If anyone can build conda binaries for various platforms, that would be great.

**Comment by kyleabeauchamp** [comment]
So I have a Vagrant CentOS VM available that is probably quite useful for this task.  That version of Centos has a sufficiently old version of glibc to be useful on a range of linux machines.  

My VM is here:

https://github.com/pandegroup/openmm/tree/master/devtools/build-vm/linux

**Comment by kyleabeauchamp** [comment]
Oh, I guess my VM is a bit heavy on dependencies, though, as it's intended to build a CUDA-capable library.

**Comment by kyleabeauchamp** [comment]
Playing with this now

**Comment by kyleabeauchamp** [comment]
PS: you may need to upload to pypi as well.

**Comment by kyleabeauchamp** [comment]
Also, I noticed that the conda recipe points to the pypi tarball, rather than the GitHub release.  I wonder if it makes sense for the conda recipe to point to the Github release (https://github.com/pymc-devs/pymc/archive/2.3.4.tar.gz) instead.

**Comment by kyleabeauchamp** [comment]
Also MD5 seems wrong in the conda recipe?

**Comment by kyleabeauchamp** [comment]
See #625

**Comment by fonnesbeck** [comment]
Crap, forgot about PyPI. Will do this now.

**Comment by twiecki** [comment]
Did you merge into the `2.3` branch?

**Comment by kyleabeauchamp** [comment]
Requested merge into 2.3, still not yet merged

**Comment by fonnesbeck** [comment]
I don't see a PR anymore. I assume this was this done? Open a PR on the pymc-devs/pymc repo if not.
