### ISSUE TITLE
Remove PyMC ODE

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5941]
## Description of your problem
Right now because PyMC ODE is there I'd expect it to "work well". But after some discussion in slack from @michaelosthege and with @Dpananos on twitter it seems like it doesnt provide as great as functionality as we'd expect, with @Dpananos and I finally concluding it should be deleted. 

To be clear this as no reflection on any person's ability to code or anything like that. Its simply a question of whether we should either bring this code up  more usable state, considering that SunODE exists, or remove it entirely to streamline PyMC.

Given the discussions thus far I'm proposing deleting it. Curious what other core devs think

https://github.com/pymc-devs/pymc/tree/main/pymc/ode

**Comment by twiecki** [comment]
Agreed, we should point people to SunODE which seems superior in every way (most importantly speed).

**Comment by michaelosthege** [comment]
I'm not so convinced: `sunode` is more difficult to install and `pm.ode` turned out to be a **magnet for new users**. Also it's been **remarkably stable**, even throughout the v4 migration.

We could also flexibly adapt to the availability of `sunode`: The signatures are quite similar, and we could make `pm.ode.DifferentialEquation` be a wrapper around `sunode` and fall back to the native Aesara/PyMC implementation?

**Comment by canyon289** [comment]
The magnet for new users has me a bit unconvinced though. I didnt have a great experience on even a basic predator prey model and if this was my first attempt to PyMC I'd be convinced bayesian methods are too slow. To @michaelosthege point I tried using SunODE and I couldn't get it installed in my env due to some c library and I gave up so its not the best user experience. It also could use a big documentation refresh if were intending it to be the goto tool for ODEs

 For specific proposals of next steps based on this discussion we could

1. Update all documentation (Code, notebooks etc) to explicitly mention this implementation is slow and if youre experiencing slowness try SunODE
2. Remove PyMC ODE entirely and point users to Sun ODE
  * If we do this we should update the docs for SunODE with more examples and installation instructions
3. Wrap SunODE in PyMC with fallbacks

I definitely think we should do point 1 while we discuss points 2 and 3. If there's no disagreements on that I can open an issue. What do you both think?

**Comment by michaelosthege** [comment]
Note that predator-prey models are notoriously slow because of their cyclic nature.

@canyon289 I guess you can do a PR to https://github.com/pymc-devs/pymc/blob/main/docs/source/api/ode.rst right away.
<sup>Please do, because otherwise it'll take ages before someone picks up the issue.</sup>

**Comment by aseyboldt** [comment]
I recently pushed some fixes to sunode, so by now I hope it is at least better than before (although there still is a fix in aesara waiting for the next release), but I agree that there are a lot of things there that could be improved:
- Better testing of installation
- Fix a few annoying bugs: eg it requires at least one fixed parameter
- Implement an aesara backend for the right-hand-side function. With the new numba backend we can finally do this, and therefor improve the user experience a lot I think (better compile times and no need to use sympy)
- Add examples!

Unfortunately sunode didn't have a high priority recently for me, I wasn't using it for anything myself.

I'm not sure what we should do about `pm.ode` though.

If we really want to push ODEs in pymc I think we also need a bit more work: For instance many ode's really do take too long to solve to realistically work with HMC, but I think there might be lot's of possible improvements if we have some build-in support for surrogate models.

**Comment by michaelosthege** [comment]
> If we really want to push ODEs in pymc I think we also need a bit more work

Totally agree. But IMO that doesn't mean we should roll back existing, stable functionality.

> For instance many ode's really do take too long to solve to realistically work with HMC

And tuning is hard.

The best performance will only be achieved by fine-tuning which backend to use for a given ODE model.
But we could keep `pm.ode.DifferentialEquation` as a user-friendly entry point that flexibly chooses native PyMC/Aesara, `sunode` or `jax.experimental.odeint` Ops behind the scenes.

**Comment by canyon289** [comment]
> @canyon289 I guess you can do a PR to https://github.com/pymc-devs/pymc/blob/main/docs/source/api/ode.rst right away. Please do, because otherwise it'll take ages before someone picks up the issue.

Update the docs is a great issue for a sprint since its straightforward. Created an issue to track

**Comment by michaelosthege** [comment]
Looks like for now we settled on adding a warning?

I guess we can then close this ticket in favor of #5948.
