### ISSUE TITLE
Update PyMC version in Windows installation instructions

### ISSUE THREAD

**Issue by zbraiterman** [pymc-devs/pymc#5943]
## Description of your problem

The PyMC installation instructions on https://www.pymc.io/projects/docs/en/stable/installation.html (running `conda create -c conda-forge -n pymc_env pymc`) found at did not work on my Windows 10 system.  However, running ‘’ (specifying `"pymc>=4"`), as mentioned on the GitHub wiki (https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Windows)), seems to have worked. 

If other Windows users have the same experience, I propose changing to `pymc>=4`.

## Versions and main components

* PyMC/PyMC3 Version: <4
* Aesara/Theano Version: aesara 2.7.3
* Python Version: 3.9.12
* Operating system:  Windows 10
* How did you install PyMC/PyMC3: conda

**Comment by ricardoV94** [comment]
Why does this happen? Because the conda list is outdated?

**Comment by cluhmann** [comment]
Not clear, but this been suggested on discourse at least once (e.g., [here](https://discourse.pymc.io/t/installing-pymc-on-ubuntu-20-04/9759/6)).

**Comment by twiecki** [comment]
Some conda thing that in existing environments it sometimes solves for older versions. i'll do a PR.
