### ISSUE TITLE
Add docs to PyMC ODE lettnig users know to expect some slowness

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#5948]
In an effort to help save users headache it would be good to provide add some information to the docs that due to the nature of the model and solvers it may be slow, and perhaps even point them to SunODE.

Scope of this PR is to update the ODE docs

From original discussion
@canyon289 I guess you can do a PR to https://github.com/pymc-devs/pymc/blob/main/docs/source/api/ode.rst right away.
<sup>Please do, because otherwise it'll take ages before someone picks up the issue.</sup>

_Originally posted by @michaelosthege in https://github.com/pymc-devs/pymc/issues/5941#issuecomment-1173108780_

**Comment by OriolAbril** [comment]
The [api/ode.rst](https://github.com/pymc-devs/pymc/blob/main/docs/source/api/ode.rst) file linked has no actual content, only directives that get the content from the docstrings into the website. What is generated is [this page](https://www.pymc.io/projects/docs/en/stable/api/ode.html). As expected, it lists `DifferentialEquation` class, but it also has

> This submodule contains tools used to perform inference on ordinary differential equations.

This part comes from the **module level docstring** which is in [`pymc/ode/__init__.py`](https://github.com/pymc-devs/pymc/blob/main/pymc/ode/__init__.py). IMO it is in that docstring (it can have multiple lines) where the message should go.

**Comment by dmburt** [comment]
We are working on this--#DataUmbrellaPyMCSprint

**Comment by azulcou** [comment]
@dmburt and I are working on this @reshamas

**Comment by michaelosthege** [comment]
Closed by #5965
