### ISSUE TITLE
Can't find Theano

### ISSUE THREAD

**Issue by daviddoria** [pymc-devs/pymc#597]
When running:
python setup.py install

I get:
....
Searching for Theano==0.6.0
Reading http://pypi.python.org/simple/Theano/
error: Connection reset by peer

**Comment by fonnesbeck** [comment]
Can you provide some details regarding your system and setup?

**Comment by daviddoria** [comment]
I'm on RedHat 6, and this is a fresh clone of pymc. I actually ran:
python setup.py install --prefix ~/PythonPackages/
because I don't have root on this system.

Please let me know if you need any other information.

**Comment by fonnesbeck** [comment]
You might want to check to see if the PyMC dependencies are installed (e.g. via `help('modules')`). An easier way to ensure this is to install via `pip`.
