### ISSUE TITLE
`assert_negative_support` function is being used inside the `StickBreakingWeights` multivariate distribution.

### ISSUE THREAD

**Issue by pibieta** [pymc-devs/pymc#5997]
## Remove calls to the `assert_negative_support`
In relation to the issue #5162 where the calls to the  `assert_negative_support` function were removed. We should also remove the calls of this function inside the `Multivariate` module, the only class that uses this function is `StickBreakingWeights`.

https://github.com/pymc-devs/pymc/blob/f9e0dfd6b898ec5085ffaf85b031b65305b1e3f0/pymc/distributions/multivariate.py#L2286-L2294

Moreover, the function is being imported from the `continuous.py`:
https://github.com/pymc-devs/pymc/blob/f9e0dfd6b898ec5085ffaf85b031b65305b1e3f0/pymc/distributions/multivariate.py#L46-L51
that will be deprecated in future versions of pyMC. Shouldn't we remove the calls and the import from this module?

#DataUmbrellaPyMCSprint
cc: @reshamas, @vitaliset, @ricardoV94, @OriolAbril

**Comment by dihanster** [comment]
Working on it!

**Comment by michaelosthege** [comment]
Closed by #6034
