### ISSUE TITLE
Are the posterior predictive about predictions kwarg docs wrong?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#6001]
## Description of your problem
I'm fairly sure the `predictions` argument adds a predictions group to InfData, and doesnt do what's stated in the docstring, I dont see a function transformation in the code  Can someone verify if this wording is indeed correct and I'm just confused?

https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.sample_posterior_predictive.html
https://github.com/pymc-devs/pymc/blob/main/pymc/sampling.py#L1972
![image](https://user-images.githubusercontent.com/7213793/180587342-1cfef55e-c4fe-4922-8d09-86cfe6b377de.png)

**Comment by OriolAbril** [comment]
It does choose the function used to **convert/add** the samples to InferenceData, it has nothing to do with sampling itself. As `idata_kwargs` docstring explains:

> Keyword arguments for [pymc.to_inference_data()](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.to_inference_data.html#pymc.to_inference_data) if predictions=False or to [pymc.predictions_to_inference_data()](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.predictions_to_inference_data.html#pymc.predictions_to_inference_data) otherwise.
