### ISSUE TITLE
Broken link in PyMC3 docs

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pymc#6003]
A Google search of "bayesian linear regression pymc" leads me to [this old page](https://docs.pymc.io/en/v3/pymc-examples/examples/generalized_linear_models/GLM-linear.html), which has the handy link at the top:

> Note
>
> You are not reading the most recent version of this documentation. [v4.1.3](https://docs.pymc.io/en/v4.1.3/pymc-examples/examples/generalized_linear_models/GLM-linear.html) is the latest version available.

Unfortunately this link looks broken. The correct link seems to be [https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/GLM_linear.html](https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/GLM_linear.html).

**Comment by reshamas** [comment]
Thanks @maresb.  We have opened a related issue on this with #5996.

**Comment by OriolAbril** [comment]
I am not sure there is anything we can do other than making the 404 page more friendly or informative. Very little pages have not been modified and restructured between v3 and v4, and the version switcher changes the version but not the rest of the url (which is what would be needed here).

**Comment by michaelosthege** [comment]
The google search now leads to this issue, and the old page didn't show up for me at all..

Also, we have abandoned `v3`, so... `wontfix`

**Comment by maresb** [comment]
For me it looks like this:
![image](https://user-images.githubusercontent.com/15216687/202861857-0f704fe6-3849-40af-827b-7995ceb7445f.png)

The top PyMC3 link has the same issue as before, but at least the second link is now the correct one. Not perfect, but at least the correct page is now easily discoverable, so good enough. Thanks for closing!
