### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#6013]
https://github.com/pymc-devs/pymc/pull/6010 added support for Python 3.7 temporarily to get it working on colab. As we have a release that supports this now, we should drop it again.

**Comment by michaelosthege** [comment]
@canyon289 I'm getting some import errors with PyMC 4.1.4 and under Python 3.7 in thie CI pipeline run: https://github.com/michaelosthege/mcbackend/runs/7531219139?check_suite_focus=true

The install in this CI pipeline uses pip.

```
mcbackend/test_adapter_pymc.py:6: in <module>
    import pymc as pm
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pymc/__init__.py:119: in <module>
    __set_compiler_flags()
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pymc/__init__.py:100: in __set_compiler_flags
    import aesara
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/aesara/__init__.py:64: in <module>
    from aesara.configdefaults import config
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/aesara/configdefaults.py:11: in <module>
    from setuptools._distutils.spawn import find_executable
E   ModuleNotFoundError: No module named 'setuptools._distutils'
```

**Comment by canyon289** [comment]
> @canyon289 I'm getting some import errors with PyMC 4.1.4 and under Python 3.7 in thie CI pipeline run: https://github.com/michaelosthege/mcbackend/runs/7531219139?check_suite_focus=true
> 
> The install in this CI pipeline uses pip.
> 
> ```
> mcbackend/test_adapter_pymc.py:6: in <module>
>     import pymc as pm
> /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pymc/__init__.py:119: in <module>
>     __set_compiler_flags()
> /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pymc/__init__.py:100: in __set_compiler_flags
>     import aesara
> /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/aesara/__init__.py:64: in <module>
>     from aesara.configdefaults import config
> /opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/aesara/configdefaults.py:11: in <module>
>     from setuptools._distutils.spawn import find_executable
> E   ModuleNotFoundError: No module named 'setuptools._distutils'
> ```

Trying it again here, though I'm not sure what the error is. Ive been ad hoc testing in colab and things have worked fine there 
https://github.com/pymc-devs/pymc/pull/6016

![image](https://user-images.githubusercontent.com/7213793/181139359-d74f6535-f94d-4f67-b906-ce53e971e2e6.png)

**Comment by michaelosthege** [comment]
Looks like the setuptools minimum version specified in v2.7.8 / https://github.com/aesara-devs/aesara/pull/1050 was not enough. Or even a problem with lower-level dependencies: https://stackoverflow.com/questions/63683262/modulenotfounderror-no-module-named-setuptools-distutils

@maresb could this be something that needs a fix in the Aesara feedstock?

**Comment by maresb** [comment]
Ya, it does appear at first glance to be an issue with the minimum version of setuptools. Could someone report a particular version of `setuptools` which is problematic?

**Comment by maresb** [comment]
Looks like a typo, the pin should be `setuptools >=48.0.0` but it's currently `setuptools >=45.0.0`. @brandonwillard?

**Comment by maresb** [comment]
Sorry, I should have shown my work...

Look at the history of the `_distutils` folder, which originates at [this commit](https://github.com/pypa/setuptools/commit/bb9fb1fcfe37c1ef1e29e1e6d1fc4e483c743380). Looking at the tags at the top, it came into the `v48.0.0` release. And indeed comparing that release with the previous version confirms this is when it was included.

As for what to do about it, we should probably fix it for the next release. We could also issue a repodata patch to retroactively fix affected versions on Conda-Forge.

**Comment by maresb** [comment]
Sorry I didn't follow up sooner... We should also raise this issue in Aesara and fix the version pin and patch the CF repodata there, no? Or has someone taken care of it already?

**Comment by maresb** [comment]
Upstream fixes have been submitted in https://github.com/aesara-devs/aesara/pull/1100 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/307.
