### ISSUE TITLE
Docker build fails with Username and password required

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#6015]
```
Run docker/login-action@v2
  with:
    username: ***
    ecr: auto
    logout: true
  env:
    CONTAINER_NAME: build-test
Error: Username and password required

```

https://github.com/pymc-devs/pymc/runs/7524618924?check_suite_focus=true

https://github.com/pymc-devs/pymc/pull/5966

CC @symeneses

**Comment by twiecki** [comment]
Weird. The secrets weren't set correctly, so I fixed them but it still shows the same error. Maybe the secrets don't update.

**Comment by symeneses** [comment]
> Weird. The secrets weren't set correctly, so I fixed them but it still shows the same error. Maybe the secrets don't update.

We can do a test PR with a new workflow getting authenticated in Docker Hub to check if the secrets are configured. Not sure if I will have time today for that, but I will try to do ASAP.

**Comment by michaelosthege** [comment]
It's just a typo in the secret's names
![grafik](https://user-images.githubusercontent.com/5894642/181236054-aef46d6e-135e-43a6-a6fd-b7462f92c025.png)

See #6017
