### ISSUE TITLE
Move DensityDist docstrings from `__new__` to class

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6031]
Otherwise they don't show up in the docs: https://www.pymc.io/projects/docs/en/v4.1.4/api/distributions/generated/pymc.DensityDist.html

**Comment by rafaelcharris** [comment]
Hi, I am willing to this.

**Comment by ricardoV94** [comment]
> Hi, I am willing to this.
> 

Go ahead!
