### ISSUE TITLE
Raise informative error if dictionary is passed as observed of DensityDist 

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6032]
This is a common source of confusion in people switching from V3 to V4. We could print an informative message when users try to do it.

**Comment by juanitorduz** [comment]
It is still a confusion for me (I had to use `pm.Potential`) 🙈  , what is the correct type for the `observed` parameter? (I can add a fix accordingly)

**Comment by ricardoV94** [comment]
`observed` should be exactly the same as for other distributions (pd.Series, np.array, pm.Data). Dictionaries are no longer a thing.
