### ISSUE TITLE
Categorical variable always zero

### ISSUE THREAD

**Issue by kiudee** [pymc-devs/pymc#604]
I’m currently implementing a Dirichlet process model in PyMC 3 and got the stick-breaking process to
work using the new theano decorator `as_op`:

``` python
    @theano.compile.ops.as_op(itypes=[t.dvector],otypes=[t.dvector])
    def pFunc(v):
        out = empty(n_dp)
        out[:] = [u * np.prod(1 - v[:i]) for i, u in enumerate(v)]
        out[-1] = 1 - np.sum(out[:-1])
        return out

    with pm.Model() as mod:
        # DP:
        conc = Uniform('concentration', lower=0.3, upper=10)
        v = Beta('v', alpha=1, beta=conc, shape=n_dp)
        p = pm.Deterministic('p', pFunc(v))
        category = Categorical('category', p, shape=n_algs)

        # Hyperpriors for Baseline distributions:
        mean_mu = Normal('mean_mu', mu=45, sd=100)
        mean_sigma = Uniform('mean_sigma', lower=0, upper=100)
        baseline = Normal('baseline', mu=mean_mu, tau=mean_sigma**-2, shape=n_dp)

        E_dp = pm.Deterministic('E_dp', t.dot(p, baseline))
        eps = pm.Uniform('eps', lower=0, upper=100)
        time_like = pm.Normal('time_like', mu=baseline[category][alg_idx], tau=eps**-2,
                              observed=data.time)
```

Furthermore I sample the variables as follows:

``` python
    with mod:
        step2 = pm.Metropolis([v, category])
        step1 = pm.NUTS([conc, mean_mu, mean_sigma, baseline, eps])
        trace = pm.sample(1000, step=[step1, step2])
```

The theano operator works as intended and the trace for `p` shows probability mass on several components:
![Trace for variable `p`](https://cloud.githubusercontent.com/assets/564473/4260442/18c2bcfa-3b3d-11e4-9787-b9ee8742af57.png)

But the `Categorical` variable always assumes the value zero.
Could this be a problem because of using several step methods at once or is there some bug elsewhere?

**Comment by kiudee** [comment]
### Addendum:

I tried initializing the `Categorical` variable as follows:

```
start = {'category': np.arange(n_algs, dtype=int)}
step2 = pm.Metropolis([v, category])
step1 = pm.NUTS([conc, mean_mu, mean_sigma, baseline, eps])
trace = pm.sample(1000, step=[step1, step2], start=start)
```

which produced this trace for `category`:
![cat_trace](https://cloud.githubusercontent.com/assets/564473/4260585/318cf4a6-3b44-11e4-98d9-4aaa193948c2.png)

**Comment by kiudee** [comment]
### Fix:

I thought a little bit more about this problem and it occured to me that the Metropolis sampler appears to be rejecting almost all of the changes for the category.
My idea was that since it is responsible for two variables `v` and `category` its scaling value is simply too low.

Thus I changed the sampling as follows:

```
step1 = pm.Metropolis([category])
step2 = pm.Metropolis([v])
step3 = pm.NUTS([conc, mean_mu, mean_sigma, baseline, eps])
trace = pm.sample(1000, step=[step1, step2, step3], start=start)
```

and the result was the following trace for `category`:
![cat_trace_working](https://cloud.githubusercontent.com/assets/564473/4263919/60e0f4ca-3c0a-11e4-8a1b-fb952c8048fa.png)
Which looks like the expected behavior for the Dirichlet process model.
Furthermore the scaling values differed significantly (0.08 for `step1` to 0.4 for `step2`) for both Metropolis samplers confirming my suspicion.

**Comment by twiecki** [comment]
There's also e.g. `pm.ElemwiseCategoricalStep(var=category,values=[0,1,2])` for sampling from categoricals.

**Comment by kiudee** [comment]
Good that you bring that up `ElemwiseCategoricalStep` was the first sampler I tried on this model:

``` python
step3 = pm.ElemwiseCategoricalStep(category, values=np.arange(n_dp))
```

Sadly it fails with the following error:

``` python
step_methods/gibbs.py in elemwise_logp(model, var)
     39 def elemwise_logp(model, var):
     40     terms = [v.logp_elemwiset for v in model.basic_RVs if var in inputs([v.logpt])]
---> 41     return model.fn(add(*terms))
     42 
     43 
[... theano calls ...]
TypeError: list indices must be integers, not float
```

**Comment by jsalvatier** [comment]
If you have the rest of the exception for this, I would like to see it, otherwise, this issue looks solved.
