### ISSUE TITLE
Model docstring is outdated

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#6040]
We no longer have self.Var("name", dist) to register random variables. We need to fix that with a correct API call

https://github.com/pymc-devs/pymc/blob/ad16bf48a1703b80cee3d3fef9df1dd0ae552d7c/pymc/model.py#L469

**Comment by alekracicot** [comment]
Pretty new to pymc. I can fix that today, but by correct API call do you mean something like this: 

with pm.Model() as exemple: 
    mu = pm.Normal('mu', mu=0, sigma=1) # < --- 
    
 Thanks for the work between this package is awesome.

**Comment by ricardoV94** [comment]
The new equivalent to that would be `model.register_rv`
