### ISSUE TITLE
New "isample" implementation

### ISSUE THREAD

**Issue by akloster** [pymc-devs/pymc#605]
I'd like to know if there is any interest in implementing a new machinery for interactive sampling in PyMC3, using the IPython notebook machinery. I've experimented with the widget API, and I think it would be easy to build a widget which can show a real progressbar (or progress graph) and allow you to stop the sampler with a stop button (and without an ugly exception).

Before starting with this, I'd like to ask you if you have any suggestions for this.

I implemented some animated bokeh graphs to visualize a sampler in realtime: https://github.com/akloster/nb-bokeh-animations

But there I just used the setup and record methods of the backend API to update Bokeh data sources, so this isn't exactly interactive....

**Comment by twiecki** [comment]
I think this would be really neat. Note that there is `iter_sample` https://github.com/pymc-devs/pymc/blob/master/pymc/sampling.py#L105 which is a generator you can iterate over to draw individual samples.

**Comment by akloster** [comment]
I finished a prototype for this widget, you can check it out here:
https://github.com/akloster/pymc/commit/143ce68718a3b38f2d9c94e9b271331cd432f3b3

Some caveats: I'm not sure how this method interacts with the multiprocess features, and my isample method doesn't work in plain IPython. So maybe it should be called something else.

**Comment by akloster** [comment]
It would be nice if some of the maintainers/collaborators could weigh in on what they'd like to see in an interactive sampling widget.

I also thought about adding a simple callback infrastructure so that you can update some bokeh graphs during sampling. These visualizations would be optional.

**Comment by twiecki** [comment]
This looks great. I'll try to take a look soon.

**Comment by fonnesbeck** [comment]
Just having a peek now, and it looks really nice. 

I guess the obvious feature suggestion for an interactive sampler would be the ability to pause and restart.

The Bokeh animations are also very nice. The suggestion that comes to mind there is to have a moving window for the plot, rather than the full trace.

Regarding the name, if this is a notebook-only function (which it clearly is), perhaps something like "nbsample" would be suitable?

Thanks again for working on this. Its something I've thought about in the past but would never have gotten around to doing!

**Comment by akloster** [comment]
Pause and restart aren't very useful concepts in IPython notebook's execution model. I've chosen to do the computation in a kernel-side loop. That way we spend the least amount of time possible waiting for messages from the client. It also means that the computation could be independent from an attached client. It will still run when you close the browser tab, for example. How reattaching or attaching multiple notebook tabs works, I'm not exactly sure.

The Stop/Pause button sends a message to the kernel, which then updates a variable inside a very short callback, and the loop finishes when next checking the variable. A restart button would have to have access to the inside of the loop as function, and resume it there. Not impossible, but it requires a lot of rethinking. Also I think it's not very meaningful to stop and restart computations, unless explicitly by using multiple chains or appending to an old one.

I agree to naming it nbsample.

The visualizations I'd like to put in there should be generic. But there is only a limited set of "generic" visualizations that work for everything pymc can sample. For single dimensions, I think a running line plot of the last few hundred samples, a histogram, and an autocorrelation plot will probably work regardless of the data. The rest needs to be configured more manually to look ok.

**Comment by twiecki** [comment]
@akloster Would it also be possible to turn this into a `ProgressBar` object that can be passed to `sample()` where `.draw()` gets called? That might be a better abstraction. This way, we could check if we're running inside a NB and use it as a default.

**Comment by akloster** [comment]
I don't like the ProgressBar idea, which doesn't mean it's necessarily bad or impossible. I think it would be better to be explicit about the loop, instead of calling "do_one_iteration" somewhere in the passed object.

This would also mean that there are multiple details for the end-user to get right: You need to create the widget, display it, pass it to the sampler. The created widget needs to call do_one_iteration and it needs to provide something to stop the sampler.

I'm going to think some more about this. Currently, just having an nbsample method seems to me the easiest way for end-users.

**Comment by twiecki** [comment]
Good points, I'm fine with keeping it this way. So I think after addressing @fonnesbeck's points we can merge, it's a great feature!

**Comment by twiecki** [comment]
Looks like we merged the PRs.
