### ISSUE TITLE
logo link no longer points to www.pymc.io

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#6054]
we use `logo_link` to make clicking on the logo go to www.pymc.io instead of the build based homepage (learn for versioned docs and gallery for pymc-examples). This no longer works with the new version of the theme, it should now use a different way to set this as explained in https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/branding.html#customize-logo-link. The same thing probably happens over at pymc-examples but I haven't checked nor opened an issue (at least so far). Ideally fixing this would mean checking pymc-examples and making 1-2 prs on both repos, otherwise, please open an issue on pymc-examples to track this

**Comment by rowan-schaefer** [comment]
I can have a go at this!

**Comment by OriolAbril** [comment]
Thanks!

**Comment by hdnl** [comment]
I changed
```
"logo_link": "https://www.pymc.io",
```
(line 259 from https://github.com/pymc-devs/pymc/blob/f3ac08b96641a418569f8423a68c44e22cfc483e/docs/source/conf.py)
to
```
    "logo": {
        "link": "https://pymc.io",
        },
```
which didn't seem to work.

The logo from my generated HTML point to `http://[::]:8000/https%3A//www.pymc.io.html` after this code fix. I attempted variants of `https://pymc.io` for the purposes of testing, but all of them produced a similar, relative URL-link (as opposed to an absolute-link). I'm unsure why this is the case. Could this be from Sphinx's end?

**Comment by OriolAbril** [comment]
There is a bug in the latest release of the sphinx theme we use (0.10.1) which has already been fixed and release 0.11.0 will probably be released in the coming days (multiple release candidates have been released already). I would recommend already opening a draft PR and triggering a rebuild once the next release for the theme is out. The fix should happen in both pymc and pymc-examples repo.

Note: `https://pymc.io` is not a valid link, not sure why but the `www` part is necessary.

**Comment by OriolAbril** [comment]
I have fixed the issue for pymc-examples in https://github.com/pymc-devs/pymc/issues/6054. Same thing still needs to happen in pymc repo though. @hdnl or @rowangayleschaefer, will any of you be able to do that?

**Comment by hdnl** [comment]
I can -- give me about ~24 hours.
