### ISSUE TITLE
Variable in `_get_scaling` is never used

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6061]
PyCharm tells me this variable is never used:

https://github.com/pymc-devs/pymc/blob/4ca3414e2f4e95a9cc8b393e1310de22d3afa473/pymc/distributions/logprob.py#L94

CC: @ferrine and @chritter

**Comment by fonnesbeck** [comment]
Looks like there should be an `else` block for the code below that assignment, representing `begin` and `end` lengths that are neither scalar nor too large.
