### ISSUE TITLE
`TestMarginalVsMarginalApprox` is now flaky

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6069]
The test has failed in both #6062 and #6067 

I never saw it fail before, so I presume it's due to changes introduced in #6055. It should be enough to set the jitter manually to 0 as it was before. Is this reasonable?

CC @danhphan @bwengals

**Comment by danhphan** [comment]
Yes, thanks @ricardoV94, let me check it in detail.

**Comment by bwengals** [comment]
Ah thanks guys.  It's reasonable in the short term.  Long term these tests need to be updated alongside a fix for #5922.  It might be best to just mark these as xfail in the meantime.

**Comment by ricardoV94** [comment]
> It might be best to just mark these as xfail in the meantime.

We have a strict xpass, so our tests would fail whenever something marked as xfail actually passes.

**Comment by danhphan** [comment]
Thanks @bwengals for the fix :)

**Comment by bwengals** [comment]
Sure @danhphan, but please take a look.  I *think* the issue was just the sensitivity, but I know you've been dealing with jitter issues lately so would still appreciate if you checked #6076 over
