### ISSUE TITLE
Rather different compilation times when PyMC is installed from pip and from conda-forge

### ISSUE THREAD

**Issue by JovanVeljanoski** [pymc-devs/pymc#6075]
Hello, 

I am not sure if this is a bug, but perhaps a peculiar behavior that I'd like to report. 

Over the past few weeks I noticed this: compiling a model takes anywhere between 20 and 80 seconds when PyMC is installed via conda-forge (most often in the 30-34 seconds range), and 1-2s when PyMC is installed via pip. In all cases I am using the experimental jax / numpyro sampler tho. I have not (yet checked) if this is also true when using the regular NUTS sampler.

The sampling time is practically identical - so no issue there. 

I was just wondering if you are aware of this, and maybe it could point to a potential problem somewhere. I have done various checks, and there is no difference in the results between PyMC installed via pip and via conda-forge, apart from this rather large model compilation times.

In case it matters, the models I am compiling contains 2-4 Gaussian distributions, sometimes, a couple of Beta/Bernoulli distributions, and some deterministic ones. Nothing all that special or fancy in any way. 

Cheers!

## Versions and main components

* PyMC/PyMC3 Version: 4.1.4, 4.1.5
* Aesara/Theano Version: 2.8.2
* Python Version: 3.9
* Operating system: Linux
* How did you install PyMC/PyMC3: conda & pip

**Comment by ricardoV94** [comment]
My guess is that any differences would come from the JAX compilation side. Would be useful to have an exact example so that someone else can try to replicate it locally.

**Comment by JovanVeljanoski** [comment]
Ok, let me see if I can provide an example over the next couple of days. Thanks!

**Comment by ricardoV94** [comment]
Closing this for lack of info. Feel free to reopen / comment if there are new details so we can reproduce.
