### ISSUE TITLE
Use only `sigma` as a parameter in gp.marginal_likelihood()

### ISSUE THREAD

**Issue by danhphan** [pymc-devs/pymc#6094]
Hi, this is not really a bug, but a small change to improve the code consistency in the pymc gp module.

In `pymc.gp.gp.py` file, several GP classes such as "[Marginal](https://github.com/pymc-devs/pymc/blob/a90c420b8b31fe4996f11d8ca9b3cc80abf4a97d/pymc/gp/gp.py#L415)" and "[MarginalApprox"](https://github.com/pymc-devs/pymc/blob/a90c420b8b31fe4996f11d8ca9b3cc80abf4a97d/pymc/gp/gp.py#L729) use `noise` as a parameter in their `marginal_likelihood()` function, while other GP classes like "[MarginalKron](https://github.com/pymc-devs/pymc/blob/a90c420b8b31fe4996f11d8ca9b3cc80abf4a97d/pymc/gp/gp.py#L1138)" use `sigma` as a parameter.

As discussed in https://github.com/pymc-devs/pymc/discussions/6077, it could be better to change the `noise` parameter to `sigma`, as well as update documentations to make it clearer.

If anyone is interested in doing this task and need more details, please let me know.

* PyMC Version: 4 latest

Thank you.

**Comment by williambdean** [comment]
I also saw this inconsistency in the gp module docs the other day. I agree `sigma` would be a good consistent solution. 

I'd be willing to take a stab at this but @danhphan I see you had some interest. 

I'm guessing there would want to be backward compatibility and throw a FutureWarning if using the previous `noise` parameterization. I'm seeing all the code changes and docstring changes would happen in the pymc/gp/gp.py file.

**Comment by danhphan** [comment]
Hi @wd60622 , please go ahead to make a PR for this task.

Yes, most of the code and docstring changes should be in [gp.py](https://github.com/pymc-devs/pymc/blob/main/pymc/gp/gp.py) file, and maybe also in [test_gp.py](https://github.com/pymc-devs/pymc/blob/main/pymc/tests/gp/test_gp.py).

Also, a FutureWarning is a good idea! Thank you

**Comment by williambdean** [comment]
Sounds great. Will open up PR. 

I'm first time contributor, but will follow the [guidelines](https://github.com/pymc-devs/pymc/blob/main/CONTRIBUTING.md)

**Comment by danhphan** [comment]
I close this issue as @wd60622 fixed it in #6145 .Thanks @wd60622 !
