### ISSUE TITLE
Ways to parallelize at the "node" level

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#610]
I have a bunch of really slow deterministic nodes.  I want to use a third-party library to calculate them, which I have already implemented.  

However, I'm finding that my calculations are still too slow, and are limited by the calculation of these deterministics.  I'm curious if we can think of a clever way (e.g. via a decorator) to use a compute cluster to parallelize the computation of these slow deterministics.  

To clarify: say I have a single parent node theta with slow deterministic children X1... Xn.  The deterministic children are then observed, with a normal RV.  

I imagine the challenge right now is that I'd need some way pymc to barrier while  X1... Xn get scattered to compute nodes for calculation.  Does this seem feasible?

**Comment by kyleabeauchamp** [comment]
(In reality, my slow "deterministic" nodes are actually MCMC chains performed in a highly-optimized domain-specific library, but I don't think that's relevant to the current discussion)

**Comment by aflaxman** [comment]
I've played around with something related to this in PyMC 2. In short, think more EM than MCMC. I'll search for some of the code if that would be useful to you.

**Comment by kyleabeauchamp** [comment]
Sure, id be interested if it's easy to find.  I also have some ideas but
haven't started playing with them yet.

**Comment by aflaxman** [comment]
Here is an EM-style approach where IPython.parallel halves the wall time: http://nbviewer.ipython.org/gist/aflaxman/0d3d0f21b1023390dac9

And here is an incomplete application of this approach to a PyMC3 model: http://nbviewer.ipython.org/gist/aflaxman/28f22c3d3558b063cbee

How has your playing gone?

**Comment by kyleabeauchamp** [comment]
Thanks!  I still haven't quite started, as I'm simultaneously exploring lots of different ways to approach my problem...

**Comment by twiecki** [comment]
@aflaxman Is that proper EM? Don't you have to integrate out the latent variables or something to compute the expectation?

**Comment by aflaxman** [comment]
I'm not sure what does and does not qualify as proper EM, but here is one of the examples from the original EM paper implemented in PyMC2: http://healthyalgorithms.com/2013/01/11/classic-em-in-python-multinomial-sampling/
