### ISSUE TITLE
Improve docstrings of `aesaraf.join_non_shared_inputs`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6105]
This function could benefit from some more clear docstrings and example. 

* Point is actually optional when `make_shared` is False
* Explain `shared`
* Make `shared` optional

https://github.com/pymc-devs/pymc/blob/761f77dad29116650ef3ca043645042219654a5c/pymc/aesaraf.py#L565-L586

**Comment by williambdean** [comment]
I am looking into this a bit but am currently understanding the function a bit more. 

Is the `point` actually optional with `make_shared` = False? 
I am seeing that `point` will be indexed in the [for loop](https://github.com/pymc-devs/pymc/blob/761f77dad29116650ef3ca043645042219654a5c/pymc/aesaraf.py#L606-L607) which seems like it will cause an error. Am I reading that wrong?

Seems like there would need some additional logic to make that happen.

**Comment by ricardoV94** [comment]
@wd60622 You're right. In that case the error message in the ifelse branch makes no sense. We can just make the point a required argument and remove the message.

**Comment by williambdean** [comment]
> @wd60622 You're right. In that case the error message in the ifelse branch makes no sense. We can just make the point a required argument and remove the message.

Gotcha. Also noticing that when this function is called ([smc](https://github.com/pymc-devs/pymc/blob/2f0af646e89e0f76392ca5cc356ee69c3f43c64f/pymc/smc/smc.py#L605) and [metropolis](https://github.com/pymc-devs/pymc/blob/761f77dad29116650ef3ca043645042219654a5c/pymc/step_methods/metropolis.py#L1056) files in helper functions), the `make_shared` is never set from the default. i.e. raised error never touch with the currently implemented pymc code. Where you suggesting removing the error raising? Is there justification for keeping that ifelse branch in all together. 

Obviously different scope. I can at least take a stab at adding to the type hints, better documenting what currently exists, and try to make some example based on the code I see for the docstring
