### ISSUE TITLE
Consider removing old shape handling functions

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6107]
Now that random draws are done by Aesara, we might not need some/all of these anymore:

https://github.com/pymc-devs/pymc/blob/761f77dad29116650ef3ca043645042219654a5c/pymc/distributions/shape_utils.py#L38-L42

First step would be to check which ones are still used and where.

**Comment by Armavica** [comment]
As far as I can say,

* `shapes_broadcasting` is only used in `broadcast_dist_samples_shape` and `get_broadcastable_dist_samples`,
* `broadcast_dist_samples_shape` is only used in `get_broadcastable_dist_samples`,
* `get_broadcastable_dist_samples` is only used in `broadcast_distribution_samples` and `broadcast_dist_samples_to`,
* `broadcast_distribution_samples` is not used anywhere,
* `broadcast_dist_samples_to` is the only of these functions used somewhere else in the code, and only in `MatrixNormalRV`.

**Comment by ricardoV94** [comment]
So we should check if we can get something more immediate to replace `broadcast_dist_samples_to` in `MatrixNormalRV`? I haven't looked at what it is doing

**Comment by mattiadg** [comment]
Is this still an open issue? I am interested in working on it

**Comment by thomasaarholt** [comment]
This issue can be closed, all the functions mentioned in OP are removed.

**Comment by ricardoV94** [comment]
> This issue can be closed, all the functions mentioned in OP are removed.

Thanks!
