### ISSUE TITLE
readthedocs build is failing

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#6115]
rtd is failing both on latest and all recent PRs, see for example: https://readthedocs.org/projects/pymc/builds/18031171/. I suspect this is related to the latest theme release. 

Can someone try to pin `pydata-sphinx-theme<0.10.1` and if it still doesn't work `pydata-sphinx-theme<0.10.0` to see if this fixes the issue? cc @reshamas @cluhmann

**Comment by OriolAbril** [comment]
https://github.com/pymc-devs/pymc/pull/6120 fixed this for pymc repo, we now need to fix pymc.io and pymc-examples

**Comment by OriolAbril** [comment]
It would also be nice to try if things are working in `main`. From https://github.com/pydata/pydata-sphinx-theme/issues/913 and https://github.com/pydata/pydata-sphinx-theme/pull/915 it looks like it has already been fixed. If so, then the pin could be `pydata-sphinx-theme!=0.10.1`

**Comment by reshamas** [comment]
@OriolAbril 
Is this issue resolved? If not, @choldgraf said we could send him more information.

**Comment by ricardoV94** [comment]
We can now unpin, as the latest release does not have the issue

**Comment by michaelosthege** [comment]
It is fixed for this repo. If problems remain in other repos, an issue should be tracked in those repos.
