### ISSUE TITLE
[doc] pymc3 imports in examples

### ISSUE THREAD

**Issue by adrn** [pymc-devs/pymc#6123]
## Description of your problem

I was clicking through some examples in the new documentation and noticed there are still a few imports that reference pymc3 instead of pymc. Here are a few that I noticed:

- https://www.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-robust.html
- https://www.pymc.io/projects/examples/en/latest/generalized_linear_models/GLM-out-of-sample-predictions.html
- https://www.pymc.io/projects/examples/en/latest/gaussian_processes/GP-smoothing.html
- https://www.pymc.io/projects/examples/en/latest/gaussian_processes/GP-Marginal.html
(but I don't think this list is complete)

I'm not sure if these were just missed in the updates, or if these are tutorials that need edits to handle the updated API. If the latter, it might be useful to put a banner on to note this and invite help in migrating the tutorial to pymc.

(PS: thank you all for the hard work -- pymc is awesome!)

**Comment by twiecki** [comment]
@adrn Yes, these are notebooks that still need to be ported. Want to help out? 

Closing this as we're tracking these on https://github.com/pymc-devs/pymc-examples/issues/333.

**Comment by adrn** [comment]
Got it - sorry I missed that issue, and yes I'll have a look!
