### ISSUE TITLE
object was probably modified after being freed

### ISSUE THREAD

**Issue by vitillo** [pymc-devs/pymc#614]
The snippet below is causing some random crashes with pymc 2.3.3 and 2.3.4:

```
python(33611,0x7fff717e6310) malloc: *** error for object 0x10c7d83a8: incorrect checksum for freed object - object was probably modified after being freed.
```

``` python
import numpy as np
import pymc as pm

data = np.array([8,4,6,3,1,4,4,6,4,2,2,1,1,4,3,3,2,6,3,4])
prior = pm.distributions.Beta("prior", alpha=3.5, beta=6.5)
stories = pm.distributions.Binomial("stories", n=10, p=prior, value=data, observed=True)

model = pm.Model([prior, stories])
mcmc = pm.MCMC(model)
mcmc.sample(40000, 10000, 1)
```

**Comment by fonnesbeck** [comment]
I get the same with [this notebook](https://gist.githubusercontent.com/fonnesbeck/4479d93cf2d7e092ac0f/raw/853ed8edd08aac3bb4c5dbe56fbb66b30dc7df0f/dying_kernel.ipynb). No idea why. This one also uses the binomial model--perhaps there's a problem in that likelihood?

```
python(73992,0x7fff77888300) malloc: *** error for object 0x1098bd3c8: incorrect checksum for freed    object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

**Comment by fonnesbeck** [comment]
I think the issue may be when the size of the binomial probability is not the same size as the data; in other words, when you use a scalar value. Making the parameter vector-valued seems to work around the bug. Must be a problem with the binomial likelihood.

**Comment by fonnesbeck** [comment]
Please test the current 2.3 branch for a fix.

**Comment by twiecki** [comment]
Probably works.
