### ISSUE TITLE
Split MCMC and Forward sampling functions in sampling.py

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6141]
That file is quite long, and anyway `draw` and `sample_prior/posterior_predictive` behave very differently from `sample` so we could separate them across two files (and same for tests). WDYT?

**Comment by twiecki** [comment]
How would you split them? We could have a submodule `sample` with `prior.py`, `posterior.py` (or `mcmc.py`).

**Comment by ricardoV94** [comment]
I was thinking `forward.py` vs `mcmc.py`

**Comment by twiecki** [comment]
We don't call it `forward` anywhere else though, do we?

**Comment by ricardoV94** [comment]
@lucianopaz does. I used to call it ancestral sampling. We do call it here: https://github.com/pymc-devs/pymc/blob/4c92adf9720f6578e51b9ef21e33c29871c67a83/pymc/sampling.py#L1619

**Comment by twiecki** [comment]
OK, I'm fine with either.

**Comment by twiecki** [comment]
We could move the jax sampling functionality then into that subdir too. We could also make it even more general and have `inference/sampling/` and `inference/vi/`.

**Comment by twiecki** [comment]
Or just have `inference` and put both in there.
