### ISSUE TITLE
Flaky `tests/gp/test_util.py::TestKmeansInducing::test_kmeans`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6143]
I've seen this fail a couple of times, most recently in 
* https://github.com/pymc-devs/pymc/actions/runs/3104834907/jobs/5029759150
* https://github.com/pymc-devs/pymc/actions/runs/3104845472/jobs/5029781127

Might need to be seeded or given a higher tolerance

**Comment by ricardoV94** [comment]
CC @bwengals

**Comment by bwengals** [comment]
Weird!  The K-means initialization hasn't changed in a long time.  Maybe a change upstream.  Will take a look

**Comment by ricardoV94** [comment]
I didn't notice flakiness locally, so it could be a windows only issue...
