### ISSUE TITLE
`sampling_jax.sample_numpyro_nuts()` acceptance rate not updated after divergence

### ISSUE THREAD

**Issue by hans-ekbrand** [pymc-devs/pymc#6144]
## acceptance rate not updated after divergence

When watching the output of `sampling_jax.sample_numpyro_nuts()` the acceptance rate is not updated correctly if there was a divergence. Instead it always just outputs `acc. prob=0`

```
warmup:  42%|▍| 850/2000 [8:33:20<11:41:52, 36.62s/it, 1023 steps of size 1.38e-03. acc. prob=0.
```

## Versions and main components

* PyMC/PyMC3 Version: pymc                    4.1.7
* Aesara/Theano Version: aesara                  2.8.2
* Python Version: Python 3.9.10
* Operating system: Debian unstable
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by hans-ekbrand** [comment]
After tuning, the acceptance probability is updated correctly again.
```
sample:  96%|▉| 1912/2000 [19:20:45<53:46, 36.67s/it, 1023 steps of size 1.37e-03. acc. prob=0.7
```

**Comment by ricardoV94** [comment]
Sounds like a numpyro question not pymc, try to open an issue with them. We don't do any of the numpyro sampling logging.

**Comment by hans-ekbrand** [comment]
OK!
