### ISSUE TITLE
Adding constants to vector-valued node

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#616]
For many regression problems, it is important to be able to fix particular elements of a parameter vector to zero (e.g. for a baseline value of a variable). In PyMC 2, this is easy: just create a deterministic that prepends a zero to a vector-valued stochastic node. Its not clear how you would achieve this with Theano. Is this where TensorConstants come into play? Or, is this where the `@theano.compile.ops.as_op` decorator comes into play?

**Comment by jsalvatier** [comment]
This is pretty easy (unless I'm misunderstanding).

```
x = Normal('x', shape=5)
t.concat([0], x)
```

There's also `t.hstack` and `t.vstack` for stacking vectors.
