### ISSUE TITLE
error using pymc.Multinomial

### ISSUE THREAD

**Issue by zjachc** [pymc-devs/pymc#6163]
I am attempting to use the multinomial model but am getting the following error:
TypeError: Variables do not support boolean operations.

with pm.Model() as model9:
    p0 = pm.Beta('p0', alpha=1, beta=1)
    p1 = pm.Beta('p1', alpha=1, beta=1)
    N = pm.DiscreteUniform('N', num_seen, 350)
    
    q0 = 1-p0
    q1 = 1-p1
    ps = [q0*q1, q0*p1, p0*q1, p0*p1]
    
    k00 = N - num_seen
    data = pm.math.stack((k00, k01, k10, k11))
    y = pm.Multinomial('y', n=N, p=ps, observed=data)

```TypeError                                 Traceback (most recent call last)
Input In [22], in <cell line: 5>()
     14 k00 = N - num_seen
     15 data = pm.math.stack((k00, k01, k10, k11))
---> 16 y = pm.Multinomial('y', n=N, p=ps, observed=data)

File ~\anaconda3\lib\site-packages\pymc\distributions\distribution.py:594, in Discrete.__new__(cls, name, *args, **kwargs)
    591 if kwargs.get("transform", None):
    592     raise ValueError("Transformations for discrete distributions")
--> 594 return super().__new__(cls, name, *args, **kwargs)

File ~\anaconda3\lib\site-packages\pymc\distributions\distribution.py:263, in Distribution.__new__(cls, name, rng, dims, initval, observed, total_size, transform, *args, **kwargs)
    259     raise TypeError(f"Name needs to be a string but got: {name}")
    261 # Create the RV and process dims and observed to determine
    262 # a shape by which the created RV may need to be resized.
--> 263 rv_out, dims, observed, resize_shape = _make_rv_and_resize_shape(
    264     cls=cls, dims=dims, model=model, observed=observed, args=args, **kwargs
    265 )
    267 if resize_shape:
    268     # A batch size was specified through `dims`, or implied by `observed`.
    269     rv_out = change_rv_size(rv=rv_out, new_size=resize_shape, expand=True)

File ~\anaconda3\lib\site-packages\pymc\distributions\distribution.py:165, in _make_rv_and_resize_shape(cls, dims, model, observed, args, **kwargs)
    162 """Creates the RV and processes dims or observed to determine a resize shape."""
    163 # Create the RV without dims information, because that's not something tracked at the Aesara level.
    164 # If necessary we'll later replicate to a different size implied by already known dims.
--> 165 rv_out = cls.dist(*args, **kwargs)
    166 ndim_actual = rv_out.ndim
    167 resize_shape = None

File ~\anaconda3\lib\site-packages\pymc\distributions\multivariate.py:530, in Multinomial.dist(cls, n, p, *args, **kwargs)
    527 @classmethod
    528 def dist(cls, n, p, *args, **kwargs):
    529     if isinstance(p, np.ndarray) or isinstance(p, list):
--> 530         if (np.asarray(p) < 0).any():
    531             raise ValueError(f"Negative `p` parameters are not valid, got: {p}")
    532         p_sum = np.sum([p], axis=-1)

File ~\anaconda3\lib\site-packages\aesara\tensor\var.py:68, in _tensor_py_operators.__bool__(self)
     66     return True
     67 else:
---> 68     raise TypeError("Variables do not support boolean operations.")

TypeError: Variables do not support boolean operations.
```

</details>

**Please provide any additional information below.**

## Versions and main components

* PyMC/PyMC3 Version: 4.2.0
* Aesara/Theano Version: 2.6.6
* Python Version: 3.9.12
* Operating system: windows 10
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by ricardoV94** [comment]
Thanks for reporting, this is the same issue as https://github.com/pymc-devs/pymc/issues/5514

You can avoid it in the meantime by writing `ps = pm.math.stack([q0*q1, q0*p1, p0*q1, p0*p1])`

**Comment by zjachc** [comment]
Thank you!

**Comment by zjachc** [comment]
However,

I then ran:
with model9:
    idata9 = pm.sample(1000)

and received this error:

ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 1>()
      1 with model9:
----> 2     idata9 = pm.sample(1000)

File ~\anaconda3\lib\site-packages\pymc\sampling.py:530, in sample(draws, step, init, n_init, initvals, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, **kwargs)
    527         auto_nuts_init = False
    529 initial_points = None
--> 530 step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    532 if isinstance(step, list):
    533     step = CompoundStep(step)

File ~\anaconda3\lib\site-packages\pymc\sampling.py:206, in assign_step_methods(model, step, methods, step_kwargs)
    203 # Use competence classmethods to select step methods for remaining
    204 # variables
    205 selected_steps = defaultdict(list)
--> 206 model_logp = model.logp()
    208 for var in model.value_vars:
    209     if var not in assigned_vars:
    210         # determine if a gradient can be computed

File ~\anaconda3\lib\site-packages\pymc\model.py:758, in Model.logp(self, vars, jacobian, sum)
    756 rv_logps: List[TensorVariable] = []
    757 if rv_values:
--> 758     rv_logps = joint_logp(list(rv_values.keys()), rv_values, sum=False, jacobian=jacobian)
    759     assert isinstance(rv_logps, list)
    761 # Replace random variables by their value variables in potential terms

File ~\anaconda3\lib\site-packages\pymc\distributions\logprob.py:260, in joint_logp(var, rv_values, jacobian, scaling, transformed, sum, **kwargs)
    250 unexpected_rv_nodes = [
    251     node
    252     for node in aesara.graph.ancestors(list(temp_logp_var_dict.values()))
   (...)
    257     )
    258 ]
    259 if unexpected_rv_nodes:
--> 260     raise ValueError(
    261         f"Random variables detected in the logp graph: {unexpected_rv_nodes}.\n"
    262         "This can happen when DensityDist logp or Interval transform functions "
    263         "reference nonlocal variables."
    264     )
    266 # aeppl returns the logp for every single value term we provided to it. This includes
    267 # the extra values we plugged in above, so we filter those we actually wanted in the
    268 # same order they were given in.
    269 logp_var_dict = {}

ValueError: Random variables detected in the logp graph: [N].
This can happen when DensityDist logp or Interval transform functions reference nonlocal variables.

**Comment by ricardoV94** [comment]
I suggest you open an issue on Discourse for this kind of questions: https://discourse.pymc.io/

And use triple backticks ` before and after your code so it renders nicely.
