### ISSUE TITLE
Rebalance test allocation across jobs

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6170]
Now that #5777 is completed many tests changed place. We should check if the jobs need to be rebalanced to have similar runtimes

**Comment by ricardoV94** [comment]
CC @michaelosthege

**Comment by ricardoV94** [comment]
@Armavica is this something you would be interested in? It boils down to checking the last ~3 successful jobs and checking the total time each one took to try and redistribute tests from long jobs to short ones

**Comment by Armavica** [comment]
Sure, I will do that.

**Comment by Armavica** [comment]
Ubuntu and Windows can be redistributed, but `test_sampling.py` is especially slow on Mac, and this will be the slowest runner after we rebalance Ubuntu and Windows.

![tests](https://user-images.githubusercontent.com/5855503/198926253-4d21a2a1-b636-42ae-8aaf-9e96ca32e5b0.png)

**Comment by ricardoV94** [comment]
@Armavica Yeah we've noticed the Mac machines are quite slow. There were plans to split the contents of sampling.py in two files, so that might help: https://github.com/pymc-devs/pymc/issues/6141

Otherwise we can move those tests to another platform

**Comment by Armavica** [comment]
Ok thanks, I will try to find a solution.

> Otherwise we can move those tests to another platform

They are actually being tested on all three platforms.

**Comment by Armavica** [comment]
To try and see through the variability of the GitHub runners, I put together a hierarchical model and analyzed the last 9 runs. It is not perfect but it seems consistent with what I usually observe. This will help to rebalance the tests.

Two things to note:
* The macos runners are indeed about 2x as slow as the Windows or Linux ones
* Besides the OS, there remains indeed a large variability at the instance level, of about two natural orders of magnitude (~x7).

![results](https://user-images.githubusercontent.com/5855503/200101505-12585d20-e691-4778-905a-165f4a1305cd.png)
