### ISSUE TITLE
How should I solve the case where the two experimental values are correlated，in PYMC3?

### ISSUE THREAD

**Issue by JokerPan3** [pymc-devs/pymc#6175]
Suppose I have three experimental values ABC, A and B are independent experimental values, but A and C come from the same data. At this time, I need to use the experimental values of ABC to fit parameter X. So what do I have to do with the correlation between A and B to make it more statistically significant?In the more complicated case, only part of A and C are derived from the same data, and the rest are derived from unrelated data. In other words, in addition to having the same data, the sources of A and C are also averaged with other experimental results, so the correlation between A and C is not 100%. In this case, how do I adjust some of the inputs in PYMC3 to fit?

**Comment by ricardoV94** [comment]
Hi @JokerPan3, user questions of this kind should be placed on our discourse: https://discourse.pymc.io/

We reserve GitHub for development issues

**Comment by JokerPan3** [comment]
> 



> 嗨，@JokerPan3，这种用户问题应该放在我们的话语中：https://discourse.pymc.io/
> 
> 我们保留 GitHub 用于解决开发问题

I'm sorry, I didn't know that. I have transferred the question to the website you mentioned.
