### ISSUE TITLE
Can a model produce posterior samples without an observed kwarg in the model (and no potential either)?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc#6179]
## Description of your problem
A user showed this model which I'm surprised actually samples and produces a posterior distribution, but I'm confused how given there is no observed kwarg in any variable, therefore no likelihood. Is this expected behavior?

```python
num_visitors = 500
with pm.Model() as ab_test_model:
    conversion_rate = pm.Beta("conversion rate",
    alpha = 2,
    beta = 2) 
    likelihood = pm.Binomial("likelihood",
    p=conversion_rate,
    n=num_visitors)
    
    idata = pm.sample()

fig, ax = plt.subplots(figsize=(24,8))
az.plot_posterior(idata.posterior, ax=ax)
```

![image](https://user-images.githubusercontent.com/7213793/193710566-6236f081-b9cf-481c-bee8-5b2affedc366.png)

## Versions and main components

* PyMC/PyMC3 Version: '4.1.5'
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
A posterior is just a prior for someone else ;) There's nothing special about a likelihood other than its values are fixed.

**Comment by canyon289** [comment]
But there is something special about a likelihood in that its necessary to produce a posterior right? In this case especially it seems weird that we get an idata with a posterior when there hasnt been any conditioning on data?

**Comment by ricardoV94** [comment]
Is the question that the samples are stored in the posterior group of InferenceData? That's just an assumption from the usual use of pm.sample.

Technically, in your case, those samples should go into the prior group. But then a user would always have to specify which group he wants the samples to go, which is a nuisance when 99.9% of the time, people are indeed conditioning on some observations.

**Comment by ricardoV94** [comment]
You can just manipulate the output InferenceData. Something like this should be possible:

```python
idata = pm.sample()
idata.prior = idata.posterior
idata.posterior = {}  # or `del idata.posterior`?
```

**Comment by canyon289** [comment]
Thanks! Good to know from a theory point I'm correct, this isn't a posterior. For the fix, that assumes the modeler knows whats going on and/or isn't confused by the results. Which wasn't the case for both me and the user I'm working it.

I totally get that the assumption simplifies the code. What do we think of raising a warning perhaps, that the model doesnt contain any likelihood? This should be a pretty mild way of helping folks that make this mistake unknowingly

**Comment by ricardoV94** [comment]
I don't think it's worth the trouble. Again, this model could be a posterior, it's all subjective:

```python
with pm.Model() as m:
  x = pm.Beta("x", 5, 1)
```

The above is the well known posterior to a beta-binomial model with prior x ~ Beta(1, 1) and y ~ Binomial(n=4, p=x, observed=4). Just happens to have a closed form solution and be written weirdly in PyMC.

**Comment by aseyboldt** [comment]
@canyon289 I guess you could interpret a posterior without a likelihood as a special case of "posterior with $n$ observations", where $n=0$. :-)

**Comment by canyon289** [comment]
Stats is sure fun. Thanks for going on that journey with me guys :partying_face:
