### ISSUE TITLE
BART's predict function with sampling jax doesn't work

### ISSUE THREAD

**Issue by yoshida0102** [pymc-devs/pymc#6180]
## BART's predict function with sampling jax doesn't work

```python
# args are like 3000 as m, 1000 as tune, 42 as RANDOM_SEED, 0.9 as target_accept
# "pmb" is a bart module installed as "pip install pymc_bart"

σ = pm.Normal("σ", model_params["Normal"]["σ"]) 
μ = pmb.BART("μ", df_X[use_cols], df_y[target_cols[0]], m=model_params["BART"]["m"], alpha=model_params["BART"]["alpha"])
y = pm.Normal("y", μ, σ, observed=df_y[target_cols[0]])

trace = pm.sampling_jax.sample_numpyro_nuts(tune=model_params["MCMC"]["tune"], random_seed=RANDOM_SEED, target_accept=model_params["MCMC"]["target_accept"])
predict = pmb.predict(trace, rng, df_X[use_cols].values, 100)
```

<details><summary>Complete error traceback</summary>

```python
AttributeError                            Traceback (most recent call last)
[<ipython-input-27-7b696563d831>](https://localhost:8080/#) in <module>
     43     # from numpy import random
     44     # rng = random.default_rng()
---> 45     predict = pmb.predict(trace, rng, df_X[use_cols].values, 100)
     46 
     47     predict2 = predict.transpose(1, 0, 2)

1 frames
[/usr/local/lib/python3.7/dist-packages/xarray/core/common.py](https://localhost:8080/#) in __getattr__(self, name)
    245                     return source[name]
    246         raise AttributeError(
--> 247             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
    248         )
    249 

AttributeError: 'Dataset' object has no attribute 'bart_trees'
```

</details>

The bart's predict function with pymc's sample function(not jax) works well.

## Versions and main components

* PyMC/PyMC3 Version: 4.2.1
* Aesara/Theano Version: 2.8.2
* Python Version: 3.9
* Operating system: Ubuntu(Google Colab)
* How did you install PyMC/PyMC3: (conda/pip) pip

**Comment by ricardoV94** [comment]
It's not supposed to work with sampling_jax. BART requires a custom sampler, cannot just use the NUTS sampler from Numpyro

**Comment by yoshida0102** [comment]
Thank you.

**Comment by aloctavodia** [comment]
Hi @yoshida0102, the reason that you can run BART by calling `pm.sample()` is that this function will automatically assign different samplers to different kind of variables. As Ricardo said, BART variables needs a custom sampler. So, in your example, if you call `pm.sample()`, σ will be assigned to NUTS and  μ to PGBART. Instead, when you call  `pm.sampling_jax.sample_numpyro_nuts` all variables will be assigned to NUTS.

**Comment by yoshida0102** [comment]
So that's how it is, I see.

I was actually looking for a way to speed up the process and tried this.
Is there any other way to sample faster while using BART?

Thanks.
