### ISSUE TITLE
Sparse Approximation Example gives Value Error: Random variables detected in the logp graph: [η, ℓ].

### ISSUE THREAD

**Issue by aegonwolf** [pymc-devs/pymc#6181]
## Description of your problem

I tried to run the example from examples and got the error in the title. I remember this happens from time to time with updates and someone asked me before to post them here so these can be updated.

**Please provide a minimal, self-contained, and reproducible example.**
```python
[[Your code here]](https://www.pymc.io/projects/examples/en/latest/gaussian_processes/GP-SparseApprox.html)
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python



**Please provide any additional information below.**
```
ValueError                                Traceback (most recent call last)
[<ipython-input-23-7bbe6d125702>](https://localhost:8080/#) in <module>
     13     y_ = gp.marginal_likelihood("y", X=X, Xu=Xu, y=y, noise=σ)
     14 
---> 15     trace = pm.sample(1000)

3 frames
[/usr/local/lib/python3.7/dist-packages/pymc/sampling.py](https://localhost:8080/#) in sample(draws, step, init, n_init, initvals, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, **kwargs)
    522 
    523     initial_points = None
--> 524     step = assign_step_methods(model, step, methods=pm.STEP_METHODS, step_kwargs=kwargs)
    525 
    526     if isinstance(step, list):

[/usr/local/lib/python3.7/dist-packages/pymc/sampling.py](https://localhost:8080/#) in assign_step_methods(model, step, methods, step_kwargs)
    205     # variables
    206     selected_steps = defaultdict(list)
--> 207     model_logp = model.logp()
    208 
    209     for var in model.value_vars:

[/usr/local/lib/python3.7/dist-packages/pymc/model.py](https://localhost:8080/#) in logp(self, vars, jacobian, sum)
    755         rv_logps: List[TensorVariable] = []
    756         if rv_values:
--> 757             rv_logps = joint_logp(list(rv_values.keys()), rv_values, sum=False, jacobian=jacobian)
    758             assert isinstance(rv_logps, list)
    759 

[/usr/local/lib/python3.7/dist-packages/pymc/distributions/logprob.py](https://localhost:8080/#) in joint_logp(var, rv_values, jacobian, scaling, transformed, sum, **kwargs)
    255     if unexpected_rv_nodes:
    256         raise ValueError(
--> 257             f"Random variables detected in the logp graph: {unexpected_rv_nodes}.\n"
    258             "This can happen when DensityDist logp or Interval transform functions "
    259             "reference nonlocal variables."

ValueError: Random variables detected in the logp graph: [η, ℓ].
This can happen when DensityDist logp or Interval transform functions reference nonlocal variables.
ValueError: Random variables detected in the logp graph: [η, ℓ].This can happen when DensityDist logp or Interval transform functions reference nonlocal variables.
</details>
```

## Versions and main components

* PyMC/PyMC3 Version: 4.14
* Aesara/Theano Version:
* Python Version: 3.8
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
Try to update to the latest version of PyMC. I think this was fixed recently

**Comment by ricardoV94** [comment]
Can someone test if the sparse approximation example still fails or not?
