### ISSUE TITLE
Improve Latex representation of symbolic distributions

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6202]
Symbolic distributions often (or *always(?)*) use other distributions as input. As such, when displaying the data-generating model in Latex, it does not look properly rendered, although we can understand what the model is. Here are two examples:

```python
with pm.Model() as censored_model:
    mu = pm.Normal("mu", 0., 5.)
    sigma = pm.HalfCauchy("sigma", 2.5)
    normal_dist = pm.Normal.dist(mu=mu, sigma=sigma)
    censored_normal = pm.Censored("censored_normal", normal_dist, lower=-2., upper=2., observed=[1, 0, 0.5])
```
yields
<img width="636" alt="Screen Shot 2022-10-11 at 9 32 16 AM" src="https://user-images.githubusercontent.com/24764859/195104940-682c4537-33db-4ad2-bf75-fa4bb40f34a1.png">

and

```python
with pm.Model() as mix_model:
    w = pm.Dirichlet("w", [1, 1])
    mix = pm.Mixture("mix", w=w, comp_dists=[pm.Normal.dist(0., 5.), pm.StudentT.dist(7.)])
```

yields
<img width="686" alt="Screen Shot 2022-10-11 at 9 33 08 AM" src="https://user-images.githubusercontent.com/24764859/195105143-1d713bd8-999f-4a96-a134-1b6a61b6f2fd.png">

**Comment by ricardoV94** [comment]
That looks like a rendering bug

**Comment by mattiadg** [comment]
Any entry points for this? Or at least a minimal script to reproduce the bug? I honestly don't know how to generate a latex from a pm Model

**Comment by larryshamalama** [comment]
> Any entry points for this? Or at least a minimal script to reproduce the bug? I honestly don't know how to generate a latex from a pm Model

You can produce the Latex display by using Jupyter's pretty print (I think that's what it's called). Essentially, you can run the following:

```python
import pymc as pm

with pm.Model() as model3:
    mu = pm.Normal("mu", sigma=5.)
    normal_dist = pm.Normal.dist(mu=mu, sigma=1.0)
    censored_normal = pm.Censored("censored_normal", normal_dist, lower=-1, upper=1)
    
model3 # pretty prints!
```

As for pointers, I haven't looked *too* carefully but I suspect that the problem will be resolved if we remove the extra $ signs in the Latex rendering because the distribution is now a "parameter". I believe that these $ signs would have to be stripped somewhere [in these lines](https://github.com/pymc-devs/pymc/blob/main/pymc/printing.py#L38-L128) after checking the structure of the model graph.

@ricardoV94 can perhaps confirm if these pointers are accurate

**Comment by mattiadg** [comment]
Sounds good, I will work on it

Il mar 18 ott 2022, 04:26 larryshamalama ***@***.***> ha
scritto:

**Comment by mattiadg** [comment]
I've been able to reproduce it, I will work on it hopefully tomorrow.

**Comment by mattiadg** [comment]
With the changes in #6231 the two distributions in the first post become
![latex1](https://user-images.githubusercontent.com/4108706/198152846-92bb901c-47bc-42cf-9a33-abd426695c16.PNG)
and
![latex2](https://user-images.githubusercontent.com/4108706/198152863-8464e53b-716d-40a4-8270-bf52e7ffa395.PNG)

**Comment by larryshamalama** [comment]
Hi @mattiadg, thanks for the PR, it looks mostly good! I have been busy with some personal business so I'll get to your PR with a more detailed review tomorrow :) Thanks for your patience!
