### ISSUE TITLE
Blackjax breaking change coming down the pipe!

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#6204]
Wanted to call out that [this change](https://github.com/blackjax-devs/blackjax/commit/74eeb2e12327304ab79cc8ae73d6d4c3b27ab429) will cause `sampling_jax.sample_blackjax_nuts` to fail, since `num_steps` is passed differently now. 

Fix:
[This argument](https://github.com/pymc-devs/pymc/blob/main/pymc/sampling_jax.py#L205) should be passed on line 208 instead. 

Fixing forward seems straightforward, but this not in a released blackjax version yet. My 2 cents is to wait for next blackjax release and not be backward compatible.

@rlouf in case you have any wisdom.

**Comment by rlouf** [comment]
No wisdom, but one advice: pin the version of Blackjax and manually bump it before v1 is released.

**Comment by michaelosthege** [comment]
It's already pinned ✔
https://github.com/pymc-devs/pymc/blob/534b89bb73c11eb32f65b71344199b45717c8914/.github/workflows/tests.yml#L347
