### ISSUE TITLE
Flaky test: `test_normal_scalar`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6211]
If failed in https://github.com/pymc-devs/pymc/actions/runs/3240831110/jobs/5311953513

with

```
_______________________ TestSamplePPC.test_normal_scalar _______________________

self = <pymc.tests.test_sampling.TestSamplePPC object at 0x1240cd4c0>

    def test_normal_scalar(self):
        nchains = 2
        ndraws = 500
        with pm.Model() as model:
            mu = pm.Normal("mu", 0.0, 1.0)
            a = pm.Normal("a", mu=mu, sigma=1, observed=0.0)
            trace = pm.sample(
                draws=ndraws,
                chains=nchains,
            )
    
        with model:
            # test list input
            ppc0 = pm.sample_posterior_predictive(
                10 * [model.initial_point()], return_inferencedata=False
            )
            # # deprecated argument is not introduced to fast version [2019/08/20:rpg]
            ppc = pm.sample_posterior_predictive(trace, var_names=["a"], return_inferencedata=False)
            # test empty ppc
            ppc = pm.sample_posterior_predictive(trace, var_names=[], return_inferencedata=False)
            assert len(ppc) == 0
    
            # test keep_size parameter
            ppc = pm.sample_posterior_predictive(trace, return_inferencedata=False)
            assert ppc["a"].shape == (nchains, ndraws)
    
            # test default case
            idata_ppc = pm.sample_posterior_predictive(trace, var_names=["a"])
            ppc = idata_ppc.posterior_predictive
            assert "a" in ppc
            assert ppc["a"].shape == (nchains, ndraws)
            # mu's standard deviation may have changed thanks to a's observed
            _, pval = stats.kstest(
                (ppc["a"] - trace.posterior["mu"]).values.flatten(), stats.norm(loc=0, scale=1).cdf
            )
>           assert pval > 0.001
E           assert 0.0005430565350[245](https://github.com/pymc-devs/pymc/actions/runs/3240831110/jobs/5311953513#step:7:246)692 > 0.001

pymc/tests/test_sampling.py:653: AssertionError
```

**Comment by mattiadg** [comment]
Hi all, I'm new here and would like to work on this.

**Comment by michaelosthege** [comment]
Sure - please investigate why the `stats.kstest` is even in there.
In the end changing the p-value threshold will always work, but if the assert is not checking anything useful you can remove it alltogether..

**Comment by mattiadg** [comment]
In the same test, we have that lines 630 and 634 are dead code. They are not testing anything and the output is not used. The only apparent use is to be sure that nothing crashes. However, in line 630 it tests with list input, so I would add a test on the output here, but delete the other one, which doesn't look like is testing anything.

Then, we also have at line 633 the comment `# # deprecated argument is not introduced to fast version [2019/08/20:rpg]`, but the following line doesn't have any deprecated arguments that I can see. I would remove also this line.

Finally, the reason for kstest is to check that the posterior distribution is also normal. I didn't see many asserts of this kind in the same file. I am not sure if it should stay there or not. 

Also, this is a SeededTest, I don't see how it can fail randomly. Aren't the sampled distributions always the same with the same seed? I can't manage to make it fail on my Windows machine. Maybe I should try on MacOs or Ubuntu 20, the ones where it failed in the CI.

**Comment by michaelosthege** [comment]
> In the same test, we have that lines 630 and 634 are dead code. They are not testing anything and the output is not used. The only apparent use is to be sure that nothing crashes. However, in line 630 it tests with list input, so I would add a test on the output here, but delete the other one, which doesn't look like is testing anything.
>
> Then, we also have at line 633 the comment # # deprecated argument is not introduced to fast version [2019/08/20:rpg], but the following line doesn't have any deprecated arguments that I can see. I would remove also this line.

sounds good

> Also, this is a SeededTest, I don't see how it can fail randomly. Aren't the sampled distributions always the same with the same seed? I can't manage to make it fail on my Windows machine. Maybe I should try on MacOs or Ubuntu 20, the ones where it failed in the CI.

That's indeed very strange. Also, I find the comment `# mu's standard deviation may have changed thanks to a's observed` confusing: It asserts that PP matches a unit Normal distribution and does *not* allow for sigma to change..

Could you add a comment there, asking people to report failures back to the thread of this issue?

**Comment by mattiadg** [comment]
Considering that also #6206 is on the same line, maybe the design of tests didn't match the design of the sampling code.
