### ISSUE TITLE
Raise informative error when non-value variables are assigned to samplers

### ISSUE THREAD

**Issue by dfm** [pymc-devs/pymc#6223]
## Description of your problem

In PyMC3, the `pm.inputvars` would (correctly, I think!) identify and the top-level input variables, whereas in PyMC v4 (`main` branch and released), it basically seems to be a no-op. To be more explicit, the following passes in PyMC3 (things get a bit more complicated with transformed variables - that's a different but related conversation!):

```python
with pm.Model():
    x = pm.Normal("x")
    assert pm.inputvars([x]) == [x]

    y = pm.Normal("y")
    assert len(inputvars([x, y])) == 2
    assert x in pm.inputvars([x, y])
    assert y in pm.inputvars([x, y])

    z = x + y
    assert len(pm.inputvars([z])) == 2
    assert x in pm.inputvars([z])
    assert y in pm.inputvars([z])

    w = pm.Deterministic("w", x + y)
    assert len(pm.inputvars([w])) == 2
    assert x in pm.inputvars([w])
    assert y in pm.inputvars([w])
```

but in PyMC (v4) all these asserts fail, since every call to `pm.inputvars` returns an empty list. This can be mitigated to some extent using `Model.rvs_to_values` (see [here](https://github.com/pymc-devs/pymc/blob/9822ce5c7d23ff27734bf1cdebc7efd34e5e6480/pymc/tuning/starting.py#L99-L101), for example), for reasons that I don't totally understand - adding this makes things work correctly for `x` and `y` in the example above, but still returns the empty list for `z` and `w`.

The real issue seems to be that `aesara.graph.basic.graph_inputs` walks up the graph too far:

```python
from aesara.graph.basic import graph_inputs
with pm.Model():
    x = pm.Uniform("x")
    print(list(graph_inputs([x])))

# prints: [RandomGeneratorSharedVariable(<Generator(PCG64) at 0x7F4FFBFCC7D0>), TensorConstant{[]}, TensorConstant{11}, TensorConstant{0.0}, TensorConstant{1.0}]
```

I'm opening the issue here instead of over on Aesara, because I think that Aesara is providing the intended behavior, but PyMC is incorrectly using the results.

**What is affected?** I noticed this when using `pm.find_MAP`, but this also leads to strange behavior in `Model.compile_fn` where `inputvars` is used to determine the relevant inputs. This function shows up in a few other spots throughout the codebase where I think issues could pop up.

I tried to look into fixing this, but I don't really follow the core back end details enough to know what the best approach is!

**Comment by dfm** [comment]
One quick follow-up, if `inputvars` had access to the model context, something like the following works at least for the test case above, but I have no idea if it is sensible:

```python
from aesara.graph.basic import ancestors

def inputvars(vars, model):
    return [model.rvs_to_values[v] for v in ancestors(vars) if v in model.rvs_to_values]
```

**Comment by ricardoV94** [comment]
The difference comes PyMC model now defining the random generative graph by default and not the logp graph as was done in V3. 

Indeed there are usually no input variables for a random graph (RNGs are shared variables and don't show in that function, nor do constants). You can look at `aesara.dprint(model.basic_RVs)` to confirm that.

What you seem to want are the inputvars of the logp graph, but this does not exist anywhere until you call `model.logp`. If you call inputvars on this, you will get the V3 results `pm.inputvars(model.logp())`, as that graph is equivalent to the V3 one.

This is explained here (just noticed there's a typo in that first cell): https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_aesara.html#what-is-going-on-behind-the-scenes

**Comment by ricardoV94** [comment]
You can also use `pm.inputvars(model.value_vars)` or `pm.inputvars(model.unobserved_value_vars)` which includes transformations and deterministics as well.

**Comment by twiecki** [comment]
Is `pm.inputvars` still used then for something?

**Comment by dfm** [comment]
@twiecki — As I described in the issue report above: while this doesn't affect NUTS, [this function is used throughout the code base,](https://github.com/pymc-devs/pymc/search?l=Python&q=inputvars) and several less commonly used features and debugging interfaces are broken.

@ricardoV94 — Thanks! Yes I'm aware of everything that you're saying, but that's not the issue! The whole _point_ is that `inputvars` is commonly used with user input. For example, if I want to maximize the posterior for just a couple of parameters, I might run:

```python
with pm.Model():
    x = pm.Normal("x")
    y = pm.Normal("y")
    soln = pm.find_MAP(vars=[x])
```

This works here, but let's say I then try:

```python
with pm.Model():
    x = pm.Normal("x")
    y = pm.Normal("y")
    z = pm.Deterministic("z", x + y)
    soln = pm.find_MAP(vars=[z])
```

In this case, I would expect this to optimize both `x` and `y`, but that instead crashes with the following traceback:

<details>
<summary>Traceback</summary>

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [1], line 6
      4 y = pm.Normal("y")
      5 z = pm.Deterministic("z", x + y)
----> 6 soln = pm.find_MAP(vars=[z])

File /opt/homebrew/Caskroom/miniforge/base/envs/exoplanet-pymc/lib/python3.10/site-packages/pymc/tuning/starting.py:152, in find_MAP(start, vars, method, return_raw, include_transformed, progressbar, maxeval, model, seed, *args, **kwargs)
    149     compute_gradient = False
    151 try:
--> 152     opt_result = minimize(
    153         cost_func, x0.data, method=method, jac=compute_gradient, *args, **kwargs
    154     )
    155     mx0 = opt_result["x"]  # r -> opt_result
    156 except (KeyboardInterrupt, StopIteration) as e:

File /opt/homebrew/Caskroom/miniforge/base/envs/exoplanet-pymc/lib/python3.10/site-packages/scipy/optimize/_minimize.py:699, in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    696     res = _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
    697                              **options)
    698 elif meth == 'l-bfgs-b':
--> 699     res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    700                            callback=callback, **options)
    701 elif meth == 'tnc':
    702     res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
    703                         **options)

File /opt/homebrew/Caskroom/miniforge/base/envs/exoplanet-pymc/lib/python3.10/site-packages/scipy/optimize/_lbfgsb_py.py:292, in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, finite_diff_rel_step, **unknown_options)
    289 bounds = [(None if l == -np.inf else l, None if u == np.inf else u) for l, u in bounds]
    290 # LBFGSB is sent 'old-style' bounds, 'new-style' bounds are required by
    291 # approx_derivative and ScalarFunction
--> 292 new_bounds = old_bound_to_new(bounds)
    294 # check bounds
    295 if (new_bounds[0] > new_bounds[1]).any():

File /opt/homebrew/Caskroom/miniforge/base/envs/exoplanet-pymc/lib/python3.10/site-packages/scipy/optimize/_constraints.py:415, in old_bound_to_new(bounds)
    406 def old_bound_to_new(bounds):
    407     """Convert the old bounds representation to the new one.
    408 
    409     The new representation is a tuple (lb, ub) and the old one is a list
   (...)
    413     -np.inf/np.inf.
    414     """
--> 415     lb, ub = zip(*bounds)
    417     # Convert occurrences of None to -inf or inf, and replace occurrences of
    418     # any numpy array x with x.item(). Then wrap the results in numpy arrays.
    419     lb = np.array([float(_arr_to_scalar(x)) if x is not None else -np.inf
    420                    for x in lb])

ValueError: not enough values to unpack (expected 2, got 0)
```
</details>

Which is a strange error to get, but I traced it down to the fact that it silently decides not to optimize for anything because `inputvars` produces an empty list, hence the original issue. You might ask why I'd want to do such a thing, instead of passing `x` and `y` directly, but that's a longer conversation, so please just give me the benefit of the doubt that this is something one may want (which previously worked and no longer does).

I know that y'all hate `find_MAP` (that's fine, I can write my own!), but it also affect some other parts of the code (as linked above). For example, I would expect the following to give me a function to evaluate `z` for some values of `x` and `y` (perhaps that's not what it's supposed to do!):

```python
import pymc as pm

with pm.Model() as model:
    x = pm.Normal("x")
    y = pm.Normal("y")
    z = pm.Deterministic("z", x + y)
    eval_z = model.compile_fn(z)
```

but that compiles an Aesara function that takes no inputs, so I can't figure out which `state` one needs to pass to it. The following does work (perhaps as expected):

```python
model.compile_fn(z, point_fn=False)()
```

This executes and (I assume) samples from `z`.

I don't use SMC or slice sampling enough to check whether or not the behavior is problematic over there.

If you're not interested in supporting these use cases, or if you don't think there's a problem, please feel free to close this issue, and I'll implement versions that work for me separately!

**Comment by twiecki** [comment]
Thanks for explaining @dfm, that's starting to make more sense. And just to make sure: `pm.find_MAP(vars=[z])` would work in pymc3 and optimize `x` and `y`?

> I know that y'all hate `find_MAP`

Actually I don't hate it at all, I think there's just some scar-tissue because people continued to use it for starting point initialization and that's usually bad practice.

**Comment by dfm** [comment]
> just to make sure: `pm.find_MAP(vars=[z])` would work in pymc3 and optimize `x` and `y`?

Yep! Running the following in PyMC3 (v3.11.5)

```python
import pymc3 as pm

with pm.Model():
    x = pm.Normal("x", testval=10.0)
    y = pm.Normal("y", testval=-5.0)
    z = pm.Deterministic("z", x + y)
    soln = pm.find_MAP(vars=[z])
    print(soln)
```

doesn't crash and prints

```python
{'x': array(8.8817842e-16), 'y': array(-4.4408921e-16), 'z': array(4.4408921e-16)}
```

as I would expect!

**Comment by ricardoV94** [comment]
@dfm We need to do a better work at separating the random and logp graphs. I suggest to stay away from `model.compile_fn` which was there mostly for backwards compatibility.

Instead I would suggest you use `aesaraf.compile_pymc`, and be explicit about what are the outputs and inputs as with any aesara function. This way you won't get mixed up.

If you say:
```python
with pm.Model() as m:
  x = pm.Normal("x")
  y = pm.Normal("y")
  z = pm.Deterministic("z", x + y)

```
Then the following are all valid functions built on top of the random graph (sans some unused variable errors)
```python
combs =  ([], [x], [y], [z], [x, y], [x, z], [y, z], [x, y, z])
for inps in combs:
  for outs in combs:
    compile_pymc(inps, outs)
```

And these are all valid functions built on top of the logp graph
```python
combs =  ([], [x], [y], [x, y])
for comb in coms:
  logp_graph = m.logp(vars=combs)
  compile_pymc(pm.inputvars(logp_graph), logp_graph))
```

You can also use deterministics as input and outputs of logp graphs, but then you have to reason a bit more about what graph you are actually trying to define...

**Comment by ricardoV94** [comment]
For the `find_map`, I think the error comes from not expecting a user to pass a deterministic (and we have some forgiving logic so users can pass both RVs or their values, that might have further masked things up). We could definitely fix that up.

Edit: In that issue, before we call `inputvars`, we would have to call `aesaraf.rvs_to_value_vars` for any vars that are not pure RVs. That should probably be a model method:

```python
with pm.Model() as m:
  x = pm.Normal("x")
  y = pm.Normal("y")
  z = pm.Deterministic("z", x + y)

m.rvs_to_values([x, y, z]) == [x.tag.value_var, y.tag.value_var, (x.tag.value_var + y.tag.value_var)]
```

**Comment by ricardoV94** [comment]
`inputvars` cannot know whether you intend to work on the random or logp side of a model... the user must somehow tell you that. It simply walks up from some nodes and finds the non-shared/non-constant inputs.

It's also possible and correct that `inputvars` would return a non-empty list from a random graph, as in the following example:
```python
with pm.Model() as m:
  x = at.scalar("x")
  y = pm.Normal("y", x)

pm.inputvars([y])  # [x]
```

So it's definitely not a no-op

**Comment by dfm** [comment]
> I suggest to stay away from model.compile_fn which was there mostly for backwards compatibility.

Might be worth adding something like that to the docstring or elsewhere (maybe it already exists and I didn't see it!), since it's part of the public interface, but no stress.

Your suggestion of a `rvs_to_values` method sounds like a good idea to me. Probably doesn't totally solve my issues, but I'll just develop those separately since it seems like most people's model debugging techniques are pretty different from the ones my community uses!

**Comment by dfm** [comment]
I can confirm that the following seems to do what I want for `find_MAP`:

```python
pm.find_MAP(vars=pm.aesaraf.rvs_to_value_vars([z]))
```

which is excellent - thanks for the tip!
