### ISSUE TITLE
Beta parameter in Gamma RV displays as f() in Latex due to `TrueDiv` scalar Op

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6224]
```python
with pm.Model() as model:
    a = pm.Gamma("a", 1., 5.)

model
```
yields $a \sim \text{Gamma}(1, f())$ due to the second parameter/last input being an `Elemwise{true_div,no_inplace}.0`. dprint yields:
```
gamma_rv{0, (0, 0), floatX, False}.1 [id A] 'a'
 |RandomGeneratorSharedVariable(<Generator(PCG64) at 0x184C99E00>) [id B]
 |TensorConstant{[]} [id C]
 |TensorConstant{11} [id D]
 |TensorConstant{1.0} [id E]
 |Elemwise{true_div,no_inplace} [id F]
   |TensorConstant{1.0} [id G]
   |TensorConstant{5.0} [id H]
```

**Comment by ricardoV94** [comment]
Yeah, it's because Aesara or PyMC uses the rate and the other uses the shape parametrization

**Comment by larryshamalama** [comment]
Should the Latex display be adapted just for the Gamma distribution? Are there other instances of a `TrueDiv` being "incorrectly" displayed?

**Comment by ricardoV94** [comment]
It's not incorrect though. If you used the mu/sigma parametrization you would also always get `f()` in the parameters. This is a more broad question of how to display transformed parameters

**Comment by larryshamalama** [comment]
Okay, I see what you mean. I'm not the biggest fan of seeing $a \sim \text{Gamma}(1, f())$ with `pm.Gamma("a", 1., 5.)` initialization as I would be expecting $a \sim \text{Gamma}(1, 5)$. However, regarding the more broad question, I don't have a solution in mind; displaying `f()` may be best for transformed parameters. Shall we leave it this way then? Can we incorporate a specific fix for the case where the Gamma distribution is used with 1) an alpha, beta initialization and 2) the parameters are constant? Or would this be too specific...

**Comment by ricardoV94** [comment]
@larryshamalama yes that would be too specific a change. You might want to study https://github.com/aesara-devs/aeppl/blob/main/aeppl/printing.py (and https://github.com/aesara-devs/aeppl/blob/main/tests/test_printing.py) to get some ideas of how a more general solution may work. I agree that it would be great to get rid of most of those opaque `f()`, but we should do it in a way that generalizes well
