### ISSUE TITLE
graphviz model doesn't work seamlessly on databricks

### ISSUE THREAD

**Issue by omrihar** [pymc-devs/pymc#6226]
## Description of your problem
When trying to display a graphviz model on databricks, the graphviz object does not display properly. 
Instead, it shows the graphviz object string representation.

It's fairly simple to display a model on databricks by using the following helper function:
```python
def show_model(model: pm.Model):
  g = pm.model_to_graphviz(model)
  displayHTML(g._repr_mimebundle_()['image/svg+xml'])
```
Basically I'm wondering whether a functionality to autodetect the databricks situation is feasible,
or perhaps adding a parameter to `model_to_graphviz` indicating to use the abovementioned
solution (or any other that works) would be a nice addition to the library.

**Please provide a minimal, self-contained, and reproducible example.**
```python
# Running on databricks
with pm.Model() as test_model:
    μ = pm.Normal("μ", 0, 1)
    σ = pm.HalfNormal("σ", 5)
    like = pm.Normal("likelihood", μ, σ, observed=[1,2,3,4,5])

pm.model_to_graphviz(test_model)

# >>> ["Out[2]: ","<graphviz.graphs.Digraph at 0x7f91d94c5640>"]
```

## Versions and main components

* PyMC/PyMC3 Version: 4.2.2
* Aesara/Theano Version: 2.8.7
* Python Version: 3.9.5
* Operating system: DBR 11.2 (Databricks Runtime)
* How did you install PyMC/PyMC3: pip

**Comment by michaelosthege** [comment]
I'm not familiar with databricks, but this sounds like something that should be done at either the databricks or [`graphviz`](https://github.com/xflr6/graphviz) level, no?

**Comment by omrihar** [comment]
databricks is a notebook environment that enables working with spark to parallelize massive computations. It natively runs on clusters and allocates resources for computations when using the native spark dataframe instead of pandas. 
It may be indeed the case that this is more of a databricks issue. I just thought it may be a nice-to-have option to wrap this little piece of code I sent for people who try to use pymc on databricks. I'll close for now, since it may indeed be better to separate the platform-specific code from the library code. When someone searches the issues for databricks and graphviz, though, they may run into this code-snippet and use it.
