### ISSUE TITLE
Multinomial moment produces invalid values for some parameters

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6233]
Reported in https://discourse.pymc.io/t/pm-multinomial-gives-sampling-error/10639

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc as pm

with pm.Model() as m:
  p = [0.1441,0.1363,0.1385,0.1348,0.1521,0.1500,0.1442]
  x = pm.Multinomial("x", n=4, p=p)

m.initial_point()  # {'x': array([-2,  1,  1,  1,  1,  1,  1])}
```

The function that generates initial values for the Multinomial is here: https://github.com/pymc-devs/pymc/blob/b5b63f5d6c8d5891382cce1af9bd5ea22de795cf/pymc/distributions/multivariate.py#L560-L569

**Comment by ricardoV94** [comment]
#6933 doesn't provide a 100% safe case, but improves it drastically. A complete solution would require an iterative algorithm that doesn't seem justified at this point. We can reassess at some point down the road if it become important for folks

**Comment by aerubanov** [comment]
@ricardoV94 since #6933 is merged, can we close the issue?
