### ISSUE TITLE
timeseries test fails

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#6247]
## Description of your problem

Was working on PR and had [this `distributions/test_timeseries.py` test](https://github.com/pymc-devs/pymc/actions/runs/3333999768/jobs/5516504990) fail with no related changes. 

Seems to be associated with the precision in a EulerMarauyama test
`FAILED pymc/tests/distributions/test_timeseries.py::TestEulerMaruyama::test_linear_model - assert 0.946843853820598 > 0.95`
[test code here](https://github.com/pymc-devs/pymc/blob/570e6e83c5ce9f5d51e63a8f94adb5ad24e2ef26/pymc/tests/distributions/test_timeseries.py#L949)

## Versions and main components

tests on github

**Comment by ricardoV94** [comment]
Also failed in https://github.com/pymc-devs/pymc/actions/runs/3298291428/jobs/5440209557

**Comment by ricardoV94** [comment]
CC @junpenglao

**Comment by williambdean** [comment]
Can the sampling in the test get a seed? 
I just had the test pass. There must be some change of value <= 0.95

Either that or loosen the 0.95
