### ISSUE TITLE
Use `_get_seeds_per_chain` utility in `smc/sampling.py`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6258]
https://github.com/pymc-devs/pymc/blob/bcffce264c4e26df85efa72c5678f763f48a645c/pymc/smc/sampling.py#L186-L199

This logic is better handled by the newer utility, also the type-hints for `random_seed` can be updated

It's curretly located here: https://github.com/pymc-devs/pymc/blob/e57d1d7f7df6970297afcbfd7cd26009b9b1643c/pymc/sampling.py#L258-L305

But will likely move after #6257

**Comment by juanitorduz** [comment]
@ricardoV94 I wanna take this one (see https://github.com/pymc-devs/pymc/pull/6298) . What do you mean by "update the type-hints for random_seed"? Meaning add type-hints to `sample_smc`? or just add something specific on the docstrings?

**Comment by ricardoV94** [comment]
@juanitorduz thanks for taking on this one. Yes update (actually add) a type-hint for the `random_seed` argument in `sample_smc`.
