### ISSUE TITLE
New EulerMaruyama tests are flaky

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6276]
Tests for this distribution have been failing. Should investigate if the frequency is expected, and if so, just seed them.

Latest examples:
* https://github.com/pymc-devs/pymc/actions/runs/3417535845/jobs/5688782811
* https://github.com/pymc-devs/pymc/actions/runs/3427788411/jobs/5711219008

**Comment by wd60622** [comment]
Cool. I can take a look at the PyMC3 code as well and look for any differences in the tests. 

Since these failing tests are checking for data generating parameters being outside of a posterior confidence interval, I'd expect them fail with some frequency already.

**Comment by ricardoV94** [comment]
Seems to have been fixed
