### ISSUE TITLE
Duplicated `initial_point` method

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#6290]
## Description of your problem

The `initial_point` method for the `Model` class shows up twice. 

https://github.com/pymc-devs/pymc/blob/5d7283ea581266e05ca88ce2123d71bcba5f7c8e/pymc/model.py#L998-L1007

https://github.com/pymc-devs/pymc/blob/5d7283ea581266e05ca88ce2123d71bcba5f7c8e/pymc/model.py#L1262-L1271

**Please provide any additional information below.**

Seems to be a mistake. 

Another side note, the `seed` parameter seems to be inconsistent with many of the other methods using `random_seed` named argument. 

## Versions and main components

* PyMC/PyMC3 Version: 4.3.0
* Aesara/Theano Version:
* Python Version:
* Operating system:
* How did you install PyMC/PyMC3: (conda/pip)

**Comment by ricardoV94** [comment]
I think I just fixed that... let me check

**Comment by ricardoV94** [comment]
@wd60622 Would you like to open a PR to fix it?

We can rename seed to random_seed, but even more useful would be type hint for what is actually allowed. I think it accepts less types than the pymc sampling functions...

**Comment by wd60622** [comment]
> @wd60622 Would you like to open a PR to fix it?
> 
> We can rename seed to random_seed, but even more useful would be to add a type hint for what is actually allowed. I think it accepts less types than the other pymc sampling functions...

Sure thing. I will remove the duplication and add to type hints / docstring

**Comment by ricardoV94** [comment]
Also worth checking we don't have any other duplications xD

**Comment by wd60622** [comment]
> Also worth checking we don't have any other duplications xD

Will check for functionality in the linter

**Comment by wd60622** [comment]
Interestingly enough, used [pyflakes](https://stackoverflow.com/questions/10761988/how-can-i-detect-duplicate-method-names-in-a-python-class) and only seems to be in this file lol. I will address them all

```bash 
(linter) ➜  pymc git:(duplicate_initial_point_method) python -m pyflakes pymc | grep "redefinition"
pymc/model.py:1262:5: redefinition of unused 'initial_point' from line 998
pymc/model.py:1274:5: redefinition of unused 'initial_values' from line 1010
pymc/model.py:1282:5: redefinition of unused 'set_initval' from line 1018
