### ISSUE TITLE
`testTPvsLatentReparameterized` suffers from precision problems

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6299]
Today it failed twice on `main`, once on Ubuntu, once on Windows:
* https://github.com/pymc-devs/pymc/actions/runs/3463369440/jobs/5783504362
* https://github.com/pymc-devs/pymc/actions/runs/3463447214/jobs/5783695185

more runs:
* https://github.com/pymc-devs/pymc/actions/runs/3412996830/jobs/5679199829
* https://github.com/pymc-devs/pymc/actions/runs/3530040880/jobs/5921616117
* https://github.com/pymc-devs/pymc/actions/runs/3523479244/jobs/5907689216
* https://github.com/pymc-devs/pymc/actions/runs/3463369440/jobs/5783504362
* https://github.com/pymc-devs/pymc/actions/runs/3463447214/jobs/5783695185

...and there were only the ones on `main` 😬

**Comment by ricardoV94** [comment]
Less frequently but `TestLatentKron` also failed sometimes in a similar manner
