### ISSUE TITLE
pymc.T fails for exactly nu=2.0 

### ISSUE THREAD

**Issue by agoldin** [pymc-devs/pymc#630]
import pymc as pm, matplotlib.pyplot as plt, numpy as np

t_dist = pm.T.dist(mu=0, lam=1, nu=2.0)
x_eval = np.linspace(-4, 4, 300)

plt.plot(x_eval, t_dist.logp(x_eval).eval(), label='Student T', lw=2.)
plt.xlabel('x')
plt.ylabel('Probability density')
plt.legend();

Offending line:

pymc/distributions/continuous.py 

```
    336         self.mean = self.median = self.mode = self.mu = mu
    337 
--> 338         self.variance = switch((nu > 2) * 1, nu / (nu - 2) / lam, inf)
    339 
```

**Comment by fonnesbeck** [comment]
What is the error you are getting here?

**Comment by agoldin** [comment]
ZeroDivisionError: float division by zero

**Comment by twiecki** [comment]
I think we need to use `theano`'s comparison operators (this is probably also related to #638): http://deeplearning.net/software/theano/tutorial/conditions.html

Here it also seems that `IfElse` is more appropriate.

**Comment by twiecki** [comment]
Ah, this problem occurs because `switch` evaluates both sides. `IfElse` should be the right choice: "In this example, the IfElse op spends less time (about half as much) than Switch since it computes only one variable out of the two."

**Comment by aloctavodia** [comment]
I try to use `IfElse` instead of `switch`, but I get the same result (ZeroDivisionError: float division by zero).  I guess it is related to the comment in the [theano docs](http://deeplearning.net/software/theano/tutorial/conditions.html) "Unless linker='vm' or linker='cvm' are used, ifelse will compute both variables and take the same computation time as switch"

As a workaround I tried to use "pure Python" and it works as expected. It is really necessary to use Theano to compute the variance?

``` python
if  nu > 2:
    self.variance = nu / (nu - 2) / lam
else:
    self.variance = inf
```

**Comment by twiecki** [comment]
Yes, it is. In the probabilistic program one can reference the variance of a RV that will always be up-to-date while with Python it would remain fixed to what the prior specified.

@nouiz I'm sure there's a way to handle this in theano where one side of the expression would raise an exception?

**Comment by nouiz** [comment]
The expected way is to use ifelse. If you didn't change Theano flags mode or linker, or passed the parameter mode to theano.function(), then the linker cvm should be used.

But there is known problems where we compute too much stuff in similar case with ifelse and the grad:

https://github.com/Theano/Theano/issues/1318

I don't know anyone that can work on this one shortly, except one of you. The other work around I think is to implement that in your own op with its grad in a different op, or use an epsilon in that graph. You could also check if nu is a constant. If it is and you algo do not allow it to change, you could use the work around in another post.

**Comment by jsalvatier** [comment]
Actually, I think this only happens because nu was a float.
