### ISSUE TITLE
module 'pymc' has no attribute 'sampling_jax'

### ISSUE THREAD

**Issue by zhebushipinyin** [pymc-devs/pymc#6307]
## module 'pymc' has no attribute 'sampling_jax'

I'm trying to use the sampling_jax method, but I get an error
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [45], line 1
----> 1 pm.sampling_jax

AttributeError: module 'pymc' has no attribute 'sampling_jax'
```
I installed the pymc follwing the [Installation instructions](https://www.pymc.io/projects/docs/en/latest/installation.html) on the web. The jax package works well (without gpu).

## Versions and main components

* PyMC Version:4.3.0
* Aesara Version: 2.8.7
* jax Version: 0.3.24
* Python Version: 3.11.0
* Operating system:  Ubuntu 22.4
* How did you install PyMC: conda

**Comment by twiecki** [comment]
Did you `import pymc.sampling_jax`?
