### ISSUE TITLE
Do not expect model variables to always have `str_repr`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6311]
When we create RVs via the the Distribution interface, they get some `str_repr` methods glued to them:

https://github.com/pymc-devs/pymc/blob/4acd98ee2bc31ef1fb63accdfb1012ba64fcebd5/pymc/distributions/distribution.py#L302-L306

The `Model.str_repr` then expects all named variables to have this method, which fails for automatically generated RVs such as those in automatic imputation

```python
import numpy as np
import pymc as pm

with pm.Model() as m:
   pm.Normal("x", observed=[np.nan, 0, 0])
m.str_repr()  # Called automatically in a Jupyter environment for pretty-printing
```
```
AttributeError: 'TensorVariable' object has no attribute 'str_repr'
```

It also which makes it annoying to replace / register variables manually: 

```python
x = pm.Normal.dist()  # No `str_repr` attached
with pm.Model() as m:
  m.register_rv(x, name="x")
m.str_repr()  # Same error
```

## Suggestion
Do not rely on the methods being attached for `model.str_repr`

https://github.com/pymc-devs/pymc/blob/fd5a6ccbcda955197c2c57384407786e245d6f36/pymc/printing.py#L103

Instead just use a dispatch base approach to pretty-print any model variables based on their Op types as discussed elsewhere.

**Comment by larryshamalama** [comment]
I'd love to! However, I'm quite busy this month and probably can only get to this once the semester is over. If anyone else reading this thread wants to take this issue in the meanwhile, you are more than welcome. 

Adding @ricardoV94's relevant [comment](https://github.com/pymc-devs/pymc/discussions/6261#discussioncomment-4047204) from a discussion thread about this.

**Comment by larryshamalama** [comment]
Some progress is being made, but mostly taking nearly verbatim the code from [aeppl/printing.py](https://github.com/aesara-devs/aeppl/blob/main/aeppl/printing.py)...

Should we still attach `str_repr` to `pm.Model` instances and RVs created via the Distribution interface? It is my understanding that Latex printing in a Jupyter notebook relies on RV/model instances having a `_repr_latex_` method. In other words,

```python
import pymc as pm
from pymc.printing import str_repr # newly created dispatch function

with pm.Model() as model:
    x = pm.Normal("x", 0., 1.)
    y = pm.Normal.dist(0., 1.)
    model.register(y, name="y")

# (1)
x.str_repr()
y.str_repr()
model.str_repr()

# (2)
str_repr(x)
str_repr(y)
str_repr(model)
```

Should we expect (1), (2) or both of the examples above to work?

**Comment by ricardoV94** [comment]
I think it's enough if the Model has the pretty rendering, we don't need each variable to have it by itself.

Would be good to adapt the code to work with dispatching so that RVs/Ops created by third party libraries can be given nice printing as well without PyMC having to know about them.

**Comment by ricardoV94** [comment]
I think we can keep attaching it to the Model and variables created via Distributions, we should just make sure the Model does not expect all it's variables to have the attached method.
