### ISSUE TITLE
Errors in core notebooks should fail doc build

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc#6323]
Seeing #6322 I realized that when execution of core notebooks fails, the doc build continues. The main goal in having the notebooks here in this repo and _executing them with every doc build_ is to prevent the notebooks from ever having outdated code that no longer runs. We should update https://github.com/pymc-devs/pymc/blob/main/docs/source/conf.py to make sure errors in notebook execution fail the doc build.

I think https://myst-nb.readthedocs.io/en/latest/computation/execute.html#error-reporting-warning-vs-failure outlines the solution, but it needs to be done and checked.

**Comment by thomasaarholt** [comment]
I'll add here that this one failed too: https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_overview.html#pymc-overview

There's a KeyboardInterrupt that happens halfway down the page.

**Comment by OriolAbril** [comment]
Thanks, this might be due to that cell taking too long, there is nobody who can keyboardinterrupt sampling when readthedocs automatically parses and executes the notebooks 🤔
