### ISSUE TITLE
BUG: Codecov checks are failing

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6346]
Right now we have almost all PRs with ❌ pipelines, and a lot of those are because an alleged decresase of coverage.

Clearly there's something wrong with the upload.

**Comment by michaelosthege** [comment]
Since it's working for PyTensor we should probably just align them:

https://github.com/pymc-devs/pytensor/blob/main/codecov.yml

https://github.com/pymc-devs/pytensor/blob/main/.github/workflows/test.yml#L135-L149

**Comment by OriolAbril** [comment]
Is this still an issue?

**Comment by michaelosthege** [comment]
don't think so
