### ISSUE TITLE
step_methods_dict values not saved

### ISSUE THREAD

**Issue by jseabold** [pymc-devs/pymc#635]
Still working with 2.x branch.

Are the StepMethods serializable? Round-tripping a model from an hdf5 backend (haven't tried others), the `step_methods_dict` dictionary comes back with empty lists for the values. I just wanted to see if it was a trivial fix or not possible. If not, I can get my hands dirty working on this a bit, if desired.

**Comment by fonnesbeck** [comment]
Sampler serialization in PyMC is not robust. You will notice there is zero test coverage. All the action is in Model.py (see `get_state`, `save_state` and `restore_sampler_state`), along with the various backends. `get_state` does retrieve the current state of the step methods, so the information is there:

```
{'sampler': {'_burn': 0,
  '_burn_till_tuned': False,
  '_current_iter': 1000,
  '_iter': 1000,
  '_thin': 1,
  '_tune_interval': 1000,
  '_tune_throughout': True,
  '_tuned_count': 0,
  'status': 'ready'},
 'step_methods': {'Metropolis_alpha': {'accepted': 277.0,
   'adaptive_scale_factor': 1.0,
   'check_before_accepting': True,
   'proposal_distribution': 'Normal',
   'proposal_sd': 2.9989601673303579,
   'rejected': 723.0},
  'Metropolis_beta': {'accepted': 224.0,
   'adaptive_scale_factor': 1.0,
   'check_before_accepting': True,
   'proposal_distribution': 'Normal',
   'proposal_sd': 16.848596303164868,
   'rejected': 776.0}},
 'stochastics': {'alpha': array(1.1625872181179409),
  'beta': array(5.847169528273765)}}
```

Some, like SQLite don't even have the methods implemented. Feel free to tinker and PR!

**Comment by twiecki** [comment]
@fonnesbeck Still need to move this.
