### ISSUE TITLE
Implement logprob for SpecifyShape and CheckAndRaise

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6352]
### Description

The logp should be pretty simple:

For SpecifyShape:
```python
def logprob_specify_shape(op, values, inner_rv, *shapes, **kwargs):
  (value,) = values
  # transfer specify_shape from rv to value
  value = at.specify_shape(value, shapes)
  return logprob(inner_rv, value)
```

Similarly, for CheckAndRaise (e.g., `assert_op`), it would involve transfering the CheckAndRaise operation from the RV to the value variable

**Comment by michaelraczycki** [comment]
I could take care of that, my question would be: Do is there some reason why we want to call the function with _specify_shape postfix? I assume that SpecifyShape is the class that needs this function, so it would be redundant to include it

**Comment by ricardoV94** [comment]
I have no strong opinion about the name, just picked that to make the example readable. 

Better to check what names we give to other logprob functions in the logprob submodule and try to be consistent with that.

Note that we also need a rewrite that converts a SpecifyShape or Assert of a MeasurableVariable into a MeasurableSpecifyShape/Assert Op.

This might be a good template...

**Comment by michaelraczycki** [comment]
Just to make sure, following the example from cumsum, I should create a file with a class extending SpecifyShape op, and within the class create the logprob_specify_shape function right? Then do accordingly with Assert, all within the logprob folder

**Comment by ricardoV94** [comment]
> Just to make sure, following the example from cumsum, I should create a file with a class extending SpecifyShape op, and within the class create the logprob_specify_shape function right? Then do accordingly with Assert, all within the logprob folder

Yes :)

**Comment by michaelraczycki** [comment]
I think I might have overshot with taking this task so early in my learning process. If anyone would like to take it and finish, feel free to do so. I need to start with some easier tasks than pytensor functionality adding, as I don't fully understand nor know the library well enough to add this.

**Comment by ricardoV94** [comment]
> I think I might have overshot with taking this task so early in my learning process. If anyone would like to take it and finish, feel free to do so. I need to start with some easier tasks than pytensor functionality adding, as I don't fully understand nor know the library well enough to add this.

That's totally fine. Thanks for giving it a try

**Comment by Dhruvanshu-Joshi** [comment]
Hey I would like to work on this issue.
Before starting, I have a question. I referred https://github.com/pymc-devs/pymc/blob/main/pymc/logprob/cumsum.py and from my understanding, here ```MeasurableCumsum``` is a subclass of ```CumOp``` defined as an extra_ops in Pytensor. I would like to know what class will our ```MeasurableSpecifyShape``` inherit from and if not what will we pass as argument to the decorator?
Basically, I would like to know what class would ```@node_rewriter([Op])``` contain in place of Op and if not will passing ```None``` be acceptable?

**Comment by ricardoV94** [comment]
You should subclass the original Class, so Assert or SpecifyShape

**Comment by Dhruvanshu-Joshi** [comment]
I have a question. While transfering the Assert from the RV to the value variable, is using ```assert_op``` a possible solution ?
```
def logprob_assert(op, values, inner_rv, *assertion, **kwargs):
    (value,) = values
    # transfer assertion from rv to value
    value = at.assert_op(assertion, value)
    return logprob(inner_rv, value)
```
If the assertion is true, the value variable will retain its value and if its false, a ValueError will be raised.

**Comment by ricardoV94** [comment]
Yes that' the idea, but you would want to use exactly the same `AssertOp` that was used in the original graph (Assert can be subclassed to raise specific error types with specific messages). You have access to the original Op in the logprob function, so you can simply do `op(value, assertion)`
