### ISSUE TITLE
Off by one error in sample() or trace()?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc#636]
So I'm finding that the last entry in my trace is outside of the support of my prior.  To me, this suggests an off-by-one error that's causing the final step of my mcmc to simply be a `zeros` array.  Drive code below, tested using pymc 2.3.4 (conda):

```
import pymc

x = pymc.Uniform("x", 1.0, 2.0)

variables = [x]

mcmc = pymc.MCMC(variables)
mcmc.sample(10000, thin=20, burn=25)

values = mcmc.trace("x")[:]
assert values.min() >= 1.0, "Must be within [1.0, 2.0], found %f at position %d" % (values.min(), values.argmin())


AssertionError: Must be within [1.0, 2.0], found 0.000000 at position 498

```

Or maybe I'm misunderstanding the inputs here...

**Comment by fonnesbeck** [comment]
Yes, looks like a rounding error when preallocating the array with zeros in the ram backend. 

```
(10000−25)/20 = 498.75
```

The easiest solution is to get rid of thinning altogether, since its a little pointless.
