### ISSUE TITLE
DOC: Add link to `CausalPy` package from PyMC ecosystem page

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#6367]
### Issue with current documentation:

The current ecosystem page https://www.pymc.io/about/ecosystem.html is great. But it lacks a link to the new package [`CausalPy `](https://github.com/pymc-labs/CausalPy).

### Idea or request for content:

- [ ] Add a link to [`CausalPy`](https://github.com/pymc-labs/CausalPy) on the ecosystem page https://www.pymc.io/about/ecosystem.html under the Domain Specific subsection. 
- [ ] Brief description could be "A package focussing on causal inference in quasi-experimental settings."

**Comment by twiecki** [comment]
We should also add it to the causal pymc-examples examples.
