### ISSUE TITLE
write_csv issue

### ISSUE THREAD

**Issue by mamacneil** [pymc-devs/pymc#637]
Hi gents,
I have used write_csv regularly to send my PyMC results over to R for plotting. However running some code from a month ago yesterday I'm getting the following error:

> IndexError: index 2 is out of bounds for axis 0 with size 2

which appears to be related to the arrayed stochastics; if I pass just the single-valued nodes to write_csv it all works fine. Any ideas on how I can debug? I'll use the sqlite backend in the meantime...
Thanks A

**Comment by twiecki** [comment]
Can you post a minimal example to reproduce the behavior?

**Comment by fonnesbeck** [comment]
I've been squashing bugs related to multivariate nodes when calculating summary statistics. I'm betting this is related, since we have no unit tests for `write_csv`.

**Comment by fonnesbeck** [comment]
Please test.

**Comment by mamacneil** [comment]
Yup - that was it; thanks for the quick repair!

**Comment by mamacneil** [comment]
This appears to have returned - also failing for plotting traces and histograms using Matplot.plot() for multi-node stochastics. #pymc2

**Comment by fonnesbeck** [comment]
This should be opened over at the [PyMC issues tracker](https://github.com/pymc-devs/pymc); this is the PyMC3 issue tracker. Open an issue there with a reproducible example, and I will have a peek.
