### ISSUE TITLE
Inconsistent kwarg `progressbar` or `progress_bar`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6377]
Naming seems to be inconsistent, we should fix it:

https://github.com/pymc-devs/pymc/blob/8b8e49bc22c261b6b97156630ffea5128e8a7a61/pymc/sampling/mcmc.py#L225

https://github.com/pymc-devs/pymc/blob/c14ad14b98b9088191c4abdf22a73ec28221a1aa/pymc/sampling/jax.py#L476

**Comment by aadya940** [comment]
We just need to replace progress_bar with progressbar, Is that it? Or am I missing something?

**Comment by michaelraczycki** [comment]
Should this issue be closed, or the naming convention issue still needs some investigation to find other inconsistencies?

**Comment by Armavica** [comment]
It looks like we are using `progressbar` everywhere now, so I am closing this, thank you!
