### ISSUE TITLE
Bug in conversion of `None` dims to InferenceData

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6379]
### Description

This snippet hast the effect of shifting the known dims to the "left":

https://github.com/pymc-devs/pymc/blob/6b60804c3a5fdb75f95cc60042061a6e38ec72a3/pymc/backends/arviz.py#L217-L220

```python
import pymc as pm

with pm.Model(coords={"a": range(5)}) as m:
    x = pm.Normal("x", shape=(10, 5), dims=(None, "a"))        
    pm.sample()
```
```
ValueError: conflicting sizes for dimension 'a': length 10 on the data but length 5 on coordinate 'a'
```
Whereas this wrong specification goes unnoticed:
```python
    x = pm.Normal("x", shape=(5, 10), dims=(None, "a"))        
```

Do we need `None` dims? It's annoying if we want to create Xarray datasets in multiple places as in #6374

More generally, it seems we don't do any sort of type check. The following are all allowed at creation time. I don't know if that's by design.

```python
import pymc as pm
with pm.Model(coords={"a": range(5)}) as m:
    x = pm.Normal("x", shape=(10, 5), dims=("a", ..., 5, pm.Normal.dist()))        
    pm.sample()
```

**Comment by OriolAbril** [comment]
Potential fix:

```
model_dims = { 
     var_name: [dim if dim is not None else f"{var_name}_dim_{i}" for i, dim in enumerate(dims)] 
     for var_name, dims in self.model.named_vars_to_dims.items() 
} 
```

**Comment by ricardoV94** [comment]
Can we do that at variable creation time? Otherwise every function that has to handle dims must worry about it

**Comment by OriolAbril** [comment]
I would assume the fact that some dims are none is used when defining shapes from dims and broadcasting
