### ISSUE TITLE
BUG: example with the black box likelihood function doesn't work in pymc=5.

### ISSUE THREAD

**Issue by andyfaff** [pymc-devs/pymc#6390]
### Describe the issue:

I have some code in my project that's based off the [pymc black box example](https://www.pymc.io/projects/examples/en/latest/case_studies/blackbox_external_likelihood_numpy.html). Since upgrading to `pymc==5` the example on the pymc page no longer works (I need it to work to get my project to work)
The [aesara-without-grad cell](https://www.pymc.io/projects/examples/en/latest/case_studies/blackbox_external_likelihood_numpy.html#aesara-op-without-grad) fails.

### Reproduceable code example:

```python
# See the aesara-without-grad cell, https://www.pymc.io/projects/examples/en/latest/case_studies/blackbox_external_likelihood_numpy.html#aesara-op-without-grad
```

### Error message:

```shell
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/type.py:281, in TensorType.dtype_specs(self)
    280 try:
--> 281     return self.dtype_specs_map[self.dtype]
    282 except KeyError:

KeyError: 'object'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[8], line 25
     22 c = pm.Uniform("c", lower=-10.0, upper=10.0)
     24 # convert m and c to a tensor vector
---> 25 theta = at.as_tensor_variable([m, c])
     27 # use a Potential to "call" the Op and include it in the logp computation
     28 pm.Potential("likelihood", logl(theta))

File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/__init__.py:49, in as_tensor_variable(x, name, ndim, **kwargs)
     17 def as_tensor_variable(
     18     x: TensorLike, name: Optional[str] = None, ndim: Optional[int] = None, **kwargs
     19 ) -> "TensorVariable":
     20     """Convert `x` into an equivalent `TensorVariable`.
     21 
     22     This function can be used to turn ndarrays, numbers, `ScalarType` instances,
   (...)
     47 
     48     """
---> 49     return _as_tensor_variable(x, name, ndim, **kwargs)

File ~/miniconda3/envs/aesara/lib/python3.10/functools.py:889, in singledispatch.<locals>.wrapper(*args, **kw)
    885 if not args:
    886     raise TypeError(f'{funcname} requires at least '
    887                     '1 positional argument')
--> 889 return dispatch(args[0].__class__)(*args, **kw)

File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/basic.py:166, in _as_tensor_Sequence(x, name, ndim, dtype, **kwargs)
    161     # In this case, we have at least one non-`Constant` term, so we
    162     # couldn't get an underlying non-symbolic sequence of objects and we to
    163     # symbolically join terms.
    164     return stack(x)
--> 166 return constant(x, name=name, ndim=ndim, dtype=dtype)

File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/basic.py:227, in constant(x, name, ndim, dtype)
    221             raise ValueError(
    222                 f"ndarray could not be cast to constant with {int(ndim)} dimensions"
    223             )
    225     assert x_.ndim == ndim
--> 227 ttype = TensorType(dtype=x_.dtype, shape=x_.shape)
    229 return TensorConstant(ttype, x_, name=name)

File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/type.py:110, in TensorType.__init__(self, dtype, shape, name, broadcastable)
    107         return s
    109 self.shape = tuple(parse_bcast_and_shape(s) for s in shape)
--> 110 self.dtype_specs()  # error checking is done there
    111 self.name = name
    112 self.numpy_dtype = np.dtype(self.dtype)

File ~/miniconda3/envs/aesara/lib/python3.10/site-packages/aesara/tensor/type.py:283, in TensorType.dtype_specs(self)
    281     return self.dtype_specs_map[self.dtype]
    282 except KeyError:
--> 283     raise TypeError(
    284         f"Unsupported dtype for {self.__class__.__name__}: {self.dtype}"
    285     )

TypeError: Unsupported dtype for TensorType: object
```

### PyMC version information:

```
conda create -n aesara python=3.10
conda activate aesara
pip install aesara arviz jupyter matplotlib numpy pymc
pip list
```
> aesara                   2.8.9
anyio                    3.6.2
appnope                  0.1.3
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
arviz                    0.14.0
asttokens                2.2.1
attrs                    22.1.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
cachetools               5.2.0
certifi                  2022.9.24
cffi                     1.15.1
cftime                   1.6.2
cloudpickle              2.2.0
comm                     0.1.2
cons                     0.4.5
contourpy                1.0.6
cycler                   0.11.0
debugpy                  1.6.4
decorator                5.1.1
defusedxml               0.7.1
entrypoints              0.4
etuples                  0.3.8
executing                1.2.0
fastjsonschema           2.16.2
fastprogress             1.0.3
filelock                 3.8.2
fonttools                4.38.0
fqdn                     1.5.1
idna                     3.4
ipykernel                6.19.2
ipython                  8.7.0
ipython-genutils         0.2.0
ipywidgets               8.0.3
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.8
jupyter-console          6.4.4
jupyter_core             5.1.0
jupyter-events           0.5.0
jupyter_server           2.0.1
jupyter_server_terminals 0.4.2
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.4
kiwisolver               1.4.4
logical-unification      0.4.5
MarkupSafe               2.1.1
matplotlib               3.6.2
matplotlib-inline        0.1.6
miniKanren               1.0.3
mistune                  2.0.4
multipledispatch         0.6.0
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.6
nbformat                 5.7.0
nest-asyncio             1.5.6
netCDF4                  1.6.2
notebook                 6.5.2
notebook_shim            0.2.2
numpy                    1.23.5
packaging                22.0
pandas                   1.5.2
pandocfilters            1.5.0
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.3.0
pip                      22.3.1
platformdirs             2.6.0
prometheus-client        0.15.0
prompt-toolkit           3.0.36
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pycparser                2.21
Pygments                 2.13.0
pymc                     5.0.0
pyparsing                3.0.9
pyrsistent               0.19.2
pytensor                 2.8.10
python-dateutil          2.8.2
python-json-logger       2.0.4
pytz                     2022.6
PyYAML                   6.0
pyzmq                    24.0.1
qtconsole                5.4.0
QtPy                     2.3.0
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
scipy                    1.9.3
Send2Trash               1.8.0
setuptools               65.5.0
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
terminado                0.17.1
tinycss2                 1.2.1
toolz                    0.12.0
tornado                  6.2
traitlets                5.7.1
typing_extensions        4.4.0
uri-template             1.2.0
wcwidth                  0.2.5
webcolors                1.12
webencodings             0.5.1
websocket-client         1.4.2
wheel                    0.37.1
widgetsnbextension       4.0.4
xarray                   2022.12.0
xarray-einstats          0.4.0

### Context for the issue:

I use a slightly modified black box example in my package. If this black box example doesn't work, then I can't use pymc to sample the posterior using my package. This example represents one of the core competencies of pymc, so to not have it work is significant.

Please consider running this black box example during CI to check for future regressions.

**Comment by andyfaff** [comment]
Hopefully this is the correct place to do this bug report. I know that https://github.com/pymc-devs/pymc-examples exists, but this seems like a bug in pymc rather than the example being written incorrectly.

**Comment by ricardoV94** [comment]
You have to replace aesara imports by pytensor in V5. We have an explicit error for the most common cases, but it doesn't seem to trigger this more complex case with a list of variables going into `as_tensor_variable`: https://github.com/pymc-devs/pymc/blob/f96594bb215b44197615c695130c9d60e1bf9601/pymc/pytensorf.py#L97-L109

**Comment by OriolAbril** [comment]
Might be worth noting that we have just updated the notebook to use pytensor:
