### ISSUE TITLE
`clone_replace` imports yield `ImportError`?

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6391]
### Description

In light of https://github.com/pymc-devs/pytensor/pull/66, I believe that the PyMC codebase still has `clone_replace` being imported from the wrong PyTensor file. Below is an example

https://github.com/pymc-devs/pymc/blob/f96594bb215b44197615c695130c9d60e1bf9601/pymc/logprob/transforms.py#L45

**Comment by ricardoV94** [comment]
We always pin a specific version of PyTensor because the API is changing quickly. This will be addressed when we next update the dependency.

**Comment by larryshamalama** [comment]
> We always pin a specific version of Aesara/PyTensor because the API is changing quickly. This will be addressed when we next update the dependency.
> 
> There's a couple of other things that need to be updated

Okay, I see. I didn't follow PyTensor updates too closely lately. I have the habit of importing the most up-to-date PyMC and PyTensor libraries, whether that's the most efficient way or not.

Is it worth addressing this issue _alone_, or should it be grouped with the other updates (in light of API changes)?

**Comment by ricardoV94** [comment]
It's worth releasing again and updating what is needed in PyMC. You can't fix this issue alone because our current PyTensor dependency is incompatible with the latest version on main of PyTensor.

**Comment by larryshamalama** [comment]
Oh, right, I understand. I had not thought of that...

**Comment by larryshamalama** [comment]
This error arose when trying to create a conda environment on a Mac as a `ResolvePackageNotFound` was obtained...

<img width="570" alt="Screen Shot 2022-12-13 at 3 19 51 AM" src="https://user-images.githubusercontent.com/24764859/207262987-af998f71-8ee7-4f9a-b683-ba99b949bd0d.png">

Adding `pytensor==2.8.10` under the pip section solves the problem for my Mac and the `environment-dev.yml` does not yield errors on my Ubuntu machine. I'm not _as_ familiar with managing conda environments, so I leave this issue closed for now although there may be other installation challenges related to this issue
