### ISSUE TITLE
ENH: Add code example to Potential docstrings

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6399]
https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.Potential.html

Note: This is labeled beginner friendly because it is self-contained, it requires modifiying only a single file and not too many lines either. It does require being a PyMC user who knows how to use pymc.Potential. Thus, it is a good choice for someone who is already a PyMC user but has never contributed to the library or to any open source library, while at the same time it is a bad choice for an experienced oss contributor who has never used PyMC.

**Comment by YASHMANMODE2502** [comment]
Hi @ricardoV94 

I can solve this issue. Do we have to just provide a code example of `pymc.Potential()` function?
If yes then where I can update the code?

Thank you

**Comment by reshamas** [comment]
> Hi @ricardoV94
> 
> I can solve this issue. Do we have to just provide a code example of `pymc.Potential()` function? If yes then where I can update the code?
> 
> Thank you

One of the learning steps in contributing is to explore the code base and find which file(s) need to be updated. Want to give that a try? ;)

**Comment by YASHMANMODE2502** [comment]
Hi @reshamas 

Yes I want to give it a try, will you help me so that i will learn how to explore the codebase.

**Comment by reshamas** [comment]
To learn more about the pymc project, check out this playlist:
https://www.youtube.com/playlist?list=PLBKcU7Ik-ir99uTvN0315hIVLuyj4Q1Gt

**Comment by reshamas** [comment]
@ricardoV94 @OriolAbril 
I removed the "beginner friendly" label for this one.

cc:  @SangamSwadiK @BerylKanali

**Comment by YASHMANMODE2502** [comment]
> To learn more about the pymc project, check out this playlist:
> https://www.youtube.com/playlist?list=PLBKcU7Ik-ir99uTvN0315hIVLuyj4Q1Gt

Thank you @reshamas for your help, I will be connected to get some help and give others some help :)

**Comment by ricardoV94** [comment]
> @ricardoV94 @OriolAbril 
> I removed the "beginner friendly" label for this one.
> 
> cc:  @SangamSwadiK @BerylKanali

I think that is setting the bar for beginner friendly issues a bit too low.

**Comment by OriolAbril** [comment]
Added the label again and extended the description

**Comment by larryshamalama** [comment]
Closed by #6559
