### ISSUE TITLE
ENH: VonMises Default Parameter Behavior

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#6418]
### Before

```python
for distribution_type in [pm.Normal, pm.VonMises]: 
    # No parameter default
    dist = distribution_type.dist()
    print(pm.draw(dist, 3, random_seed=42))

# [0.41832997 0.60557617 0.02878786]
# [nan nan nan]


# Within model... Think this calls dist cls method anyway
with pm.Model(): 
    normal = pm.Normal("normal") 
    vonmises = pm.VonMises("vonmises") 

pm.draw([normal, vonmises], draws=3, random_seed=42)

# [array([0.41832997, 0.60557617, 0.02878786]), array([nan, nan, nan])]
```

### After

```python
for distribution_type in [pm.Normal, pm.VonMises]: 
    # No parameter default
    dist = distribution_type.dist()
    print(pm.draw(dist, 3, random_seed=42))

# [0.41832997 0.60557617 0.02878786]
# [0.82669683 -0.82282542 -1.25868009]


# Within model... Think this calls dist cls method anyway
with pm.Model(): 
    normal = pm.Normal("normal") 
    vonmises = pm.VonMises("vonmises") 

pm.draw([normal, vonmises], draws=3, random_seed=42)

# [array([0.41832997, 0.60557617, 0.02878786]), array([0.82669683, -0.82282542, -1.25868009])]
```

### Context for the issue:

The `VonMises` distribution supports defaults arguments. However, the behavior is a bit different than the other distributions where it won't sample. Would it make sense to either require arg or support similar behavior? 
Not sure if there is additional context, I am missing.

**Comment by wd60622** [comment]
I can take the issue if it seems like it would be useful. Also, would fix the doc rendering while I'm at it 😄 

![von-mises-issue](https://user-images.githubusercontent.com/57733339/209855507-8e4cae9e-fb0a-4d9c-9a9b-b208dba07d77.PNG)

**Comment by ricardoV94** [comment]
Yes it sounds useful to fix. `kappa` should either have a default value or not be optional. Which one do you suggest? `kappa=1` by default?

**Comment by wd60622** [comment]
I would say `kappa=1` is fine default. Work for you?

**Comment by ricardoV94** [comment]
Yeah sounds good

**Comment by wd60622** [comment]
PR up
