### ISSUE TITLE
Yosemite pymc doesn't work

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#642]
Hey guys,

I tried installing PyMC, and was successful, but when I tried importing it, I get the following error:

> > > import pymc
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/**init**.py", line 30, in <module>
> > >     from .CommonDeterministics import *
> > >   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
> > >     from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
> > >   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
> > >     from . import flib
> > > ImportError: dlopen(/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/Cellar/gfortran/4.8.2/gfortran/lib/libgfortran.3.dylib
> > >   Referenced from: /Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/flib.so
> > >   Reason: image not found

Any clue what might be going on?

**Comment by fonnesbeck** [comment]
How did you install it? Are you using Homebrew at all?

**Comment by ericmjl** [comment]
Update: Sorry, I should have mentioned, I'm not using Homebrew.

I had followed some instructions that I found via Googling earlier on, and for some reason was able to get it to work. However, when I retried installation directly from source, I now have the following errors:

customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Could not locate executable gfortran
Could not locate executable f95
customize NAGFCompiler
customize AbsoftFCompiler
Could not locate executable f90
Could not locate executable f77
customize IBMFCompiler
Could not locate executable xlf90
Could not locate executable xlf
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
warning: build_ext: f77_compiler=None is not available.
error: extension 'pymc.flib' has Fortran sources but no Fortran compiler found

When I fire up Python, I get the following:
Python 2.7.8 |Continuum Analytics, Inc.| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

I've been having issues installing GCC 4.9.1 on Yosemite, seems like they haven't put out an official patched version (from what I've been reading).

**Comment by ericmjl** [comment]
Having installed gfortran, I now get the following errors:

gfortran:f77: build/src.macosx-10.5-x86_64-2.7/pymc/flib-f2pywrappers.f
/usr/local/bin/gfortran -Wall -m64 -Wall -undefined dynamic_lookup -bundle build/temp.macosx-10.5-x86_64-2.7/cephes/i0.o build/temp.macosx-10.5-x86_64-2.7/cephes/c2f.o build/temp.macosx-10.5-x86_64-2.7/cephes/chbevl.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fortranobject.o build/temp.macosx-10.5-x86_64-2.7/pymc/flib.o build/temp.macosx-10.5-x86_64-2.7/pymc/histogram.o build/temp.macosx-10.5-x86_64-2.7/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-2.7/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-2.7/pymc/math.o build/temp.macosx-10.5-x86_64-2.7/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/pymc/flib-f2pywrappers.o -L/Users/ericmjl/anaconda/envs/py27/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.9.0 -L/Users/ericmjl/anaconda/envs/py27/lib -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lgfortran -o build/lib.macosx-10.5-x86_64-2.7/pymc/flib.so
ld: library not found for -lmkl_lapack95_lp64
collect2: error: ld returned 1 exit status
ld: library not found for -lmkl_lapack95_lp64
collect2: error: ld returned 1 exit status
error: Command "/usr/local/bin/gfortran -Wall -m64 -Wall -undefined dynamic_lookup -bundle build/temp.macosx-10.5-x86_64-2.7/cephes/i0.o build/temp.macosx-10.5-x86_64-2.7/cephes/c2f.o build/temp.macosx-10.5-x86_64-2.7/cephes/chbevl.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/pymc/flibmodule.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/fortranobject.o build/temp.macosx-10.5-x86_64-2.7/pymc/flib.o build/temp.macosx-10.5-x86_64-2.7/pymc/histogram.o build/temp.macosx-10.5-x86_64-2.7/pymc/flib_blas.o build/temp.macosx-10.5-x86_64-2.7/pymc/blas_wrap.o build/temp.macosx-10.5-x86_64-2.7/pymc/math.o build/temp.macosx-10.5-x86_64-2.7/pymc/gibbsit.o build/temp.macosx-10.5-x86_64-2.7/build/src.macosx-10.5-x86_64-2.7/pymc/flib-f2pywrappers.o -L/Users/ericmjl/anaconda/envs/py27/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.9.0 -L/Users/ericmjl/anaconda/envs/py27/lib -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lgfortran -o build/lib.macosx-10.5-x86_64-2.7/pymc/flib.so" failed with exit status 1

**Comment by fonnesbeck** [comment]
OK, next question: where did you get the Fortran compiler? This suggests an incompatible compiler. Fortran compilers are tricky, because they need to be compatible with the gcc that you are using. 

We are working on updated conda packages with statically-compiled Fortran, so you don't have to worry about this, but they are not quite ready yet.

**Comment by fonnesbeck** [comment]
OK, try this installer. Should not require any compilers:

```
conda install -c https://conda.binstar.org/fonnesbeck pymc
```

**Comment by ericmjl** [comment]
Thanks for your input! I tried the installation using 

`conda install -c https://conda.binstar.org/fonnesbeck pymc`

Installation was successful on both my python 2.7 and 3.4 environments.

However, when I tried to import pymc, the same error came up:

> import pymc
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
>     from .CommonDeterministics import *
>   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
>     from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
>   File "/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
>     from . import flib
> ImportError: dlopen(/Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libquadmath.0.dylib
>   Referenced from: /Users/ericmjl/anaconda/envs/py27/lib/python2.7/site-packages/pymc/flib.so
>   Reason: image not found

Would this be an issue with fortran still? (Pardon my lack of knowledge here, I am trained as a biochemistry/microbiology major.)

As for Fortran, I obtained it from here: https://gcc.gnu.org/wiki/GFortranBinaries, specifically obtaining the version for Mavericks (even though I know I'm on Yosemite). I was not able to install GCC 4.9.2, as it exited with an error.

**Comment by fonnesbeck** [comment]
Yeah, you have an old version of gcc. Can you upgrade Xcode on your machine (at least the command line tools).

**Comment by ericmjl** [comment]
Hmm, I've run:  `xcode-select --install` on my machine, and I get back `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. 

When I check the Updates tab on the Mac App Store, I have also found that I've got Xcode 6.1 installed. 

When I run `gcc --version`, I get back: 
`gcc: warning: couldn’t understand kern.osversion ‘14.0.0
gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

However, when I run Python in the terminal, I notice that Anaconda's Python distribution is using GCC 4.2.1, as shown by:
`Python 3.4.2 |Continuum Analytics, Inc.| (default, Oct 21 2014, 17:42:20) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin`

From your experience, are there issues with the Anaconda distribution of Python? I will be posting there to see if I can find a way to get Anaconda Python to recognize GCC 4.8.2; however, this doesn't solve the inability to install 4.9.1 either, for which I will ask the GCC people.

**Comment by fonnesbeck** [comment]
I otice that you said the installation of 4.9.2 failed. I wonder if you ended up with something half-installed. Definitely a good question for the Anaconda folks (@asmeurer ?).

**Comment by asmeurer** [comment]
The version listed in the version information is the version used to compile Python. Is there a binary compatibility problem between gcc versions?

Note that you can get my gcc 4.8 package for OS X or Linux with `conda install -c asmeurer gcc`. We are also working at https://github.com/pymc-devs/pymc/issues/556 to get a conda package for pymc working.

**Comment by fonnesbeck** [comment]
Please reopen in the pymc-devs/pymc repo if this is still an issue
