### ISSUE TITLE
BUG: `model_to_graphviz` nodes become detached if a named node is between two dependent random variables

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#6421]
### Describe the issue:

`model_to_graphviz` is completely dependent on named `Variables` in the pytensor graph that relates random variables, deterministics, and all other model components. If a named node is at some intermediate stage between random variables, the nodes become disconnected in the graphviz representation.

### Reproduceable code example:

```python
import pymc as pm

with pm.Model() as m1:
    a = pm.Normal("a", 0, 1, shape=3)
    b = pm.Normal("b", a.mean(axis=-1), 1)

with pm.Model() as m2:
    a = pm.Normal("a", 0, 1)
    b = a + 1
    b.name = "b"
    c = pm.Normal("c", b, 1)

pm.model_to_graphviz(m1)
pm.model_to_graphviz(m2)
```

### PyMC version information:

pymc version: 5.0.0

### Context for the issue:

The code snippet above produces the following graphviz representations

For m1:

![image](https://user-images.githubusercontent.com/5230109/210012411-c785be5f-6389-4f34-829d-e826cdb64e23.png)

For m2:

![image](https://user-images.githubusercontent.com/5230109/210012491-50ab1992-6e43-42ba-91a1-4cbf97611336.png)

**Comment by ricardoV94** [comment]
Wow that's a shocker. 

We should check such named nodes are ancestors of each other. Perhaps @ferrine has an idea how to do that elegantly?

**Comment by lucianopaz** [comment]
I would simply forego the named nodes entirely and check if the `Variable` is in the model. That would elegantly skip intermediate named nodes that aren't tracked by the model during sampling and all other high level tasks.

**Comment by ricardoV94** [comment]
I mean we still need to build the dependency graph. The nodes are easy: just the variables in the model (aka `named_vars`). But the edges require checking ancestry relationship. I guess the current implementation is short sighted and only sees edges when there is a direct connection between two model variables.

The name-based thing is not the challenge, it's finding the edges between the model variables

**Comment by lucianopaz** [comment]
> I mean we still need to build the dependency graph. The nodes are easy: just the variables in the model (aka `named_vars`). But the edges require checking ancestry relationship. I guess the current implementation is short sighted and only sees edges when there is a direct connection between two model variables (or probably named variables).
> 
> Moving away from the name-based thing is not the challenge, it's finding the edges between the model variables.
> 
> Shouldn't be too bad. The whole submodule is in some need of refactoring though.

What I meant is that the ancestry tracking is already in place, the problem is that the ancestry tracking [stops when it finds a named node](https://github.com/pymc-devs/pymc/blob/a7f361bdccfed131481700e9086e004963989ce5/pymc/model_graph.py#L66-L67), but it should only stop when it hits a variable that is being tracked by the model object itself.

**Comment by ricardoV94** [comment]
I see, in that case should be enough to check if a variable is in model.named_vars instead of just having a name.

I still have the urge to refactor that whole module but that can always wait :P
