### ISSUE TITLE
DOC: Add missing Matern12 gp cov

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#6428]
### Issue with current documentation:

The Matern12 class is missing from the [docs](https://www.pymc.io/projects/docs/en/stable/learn.html). 

It seems that the class is missing from the `__all__` variable of the file which I think causes the issue

There might be an issue with the rendering of the math with the missing .. math:: block as well.
https://github.com/pymc-devs/pymc/blob/f6a502aabb6ae4454b284cd992f91f6b6a0aead2/pymc/gp/cov.py#L514-L524

### Idea or request for content:

I don't think that this is intended. This would add the variable in the GP docs section

**Comment by wd60622** [comment]
Thanks @fonnesbeck !
