### ISSUE TITLE
DOC: Inaccurate literature references in Dawid-Skene notebook

### ISSUE THREAD

**Issue by bob-carpenter** [pymc-devs/pymc#6450]
### Issue with current documentation:

`docs/source/notebooks/dawid-skene.ipynb` starts with

> The Dawid-Skene model (1979) is perhaps one of the first models to discover true item states/effects from multiple noisy measurements. Since then, there have been multiple models that improve over the basic model. This notebook covers the Dawid-Skene model which has been enhanced with priors.

I'm not sure what the authors were thinking in terms of discovering effects from noisy measurements, but the psychometricians introduced these kinds of models several decades earlier.  For instance, the Bradley-Terry model dates from 1950, which estimates team abilities from the results of matches.  The IRT models are from about the same time and are very similar in flavor to Dawid and Skene's model.

Also, the notebook uses Bayesian inference, which is closer to a follow-on paper.  

> Paun, S., Carpenter, B., Chamberlain, J., Hovy, D., Kruschwitz, U. and Poesio, M., 2018. Comparing Bayesian models of annotation. Transactions of the Association for Computational Linguistics, 6, pp.571-585.

Becky and I just used penalized maximum likelihood estimates (largely so as not to confuse reviewers, because full Bayes was largely unheard of in NLP at the time and I'd gotten lots of anti-Bayes pushback on earlier submissions).

### Idea or request for content:

1.  Drop the "first models" comment.
2.  Mention that it moves from the MLE approach of Dawid and Skene to full Bayesian inference.

**Comment by OriolAbril** [comment]
This notebook doesn't exist anymore (not even the folder does), and I can't find the source on the website either. Could you share the link where you found that?

**Comment by bob-carpenter** [comment]
https://pymc3-testing.readthedocs.io/en/rtd-docs/notebooks/dawid-skene.html

P.S.  I like quoted Google searches for this kind of thing.  In this case, searching for `"The Dawid-Skene model (1979) is perhaps one of the first models to discover true item states/effects"` finds the case study and this issue.

**Comment by OriolAbril** [comment]
I was searching only in our website: [www.pymc.io](https://www.pymc.io/welcome.html).

The link you shared is the [`pymc3-testing` project on readthedocs](https://readthedocs.org/projects/pymc3-testing/) which is generated from [this fork of pymc](https://github.com/owlas/pymc3) (you can see that from the "Edit on GitHub" button at the top right of the page you shared). That fork is 3837 commits behind pymc-devs:main as of today, and both the fork and the readthedocs projects can only be modified by their owner (note it is a private repo not a team one like pymc-devs): `owlas`.

**Comment by bob-carpenter** [comment]
Wow.  Thanks for clarifying.  I somehow found that shadow site when looking for PyMC doc and didn't realize it wasn't the official doc!
