### ISSUE TITLE
Add simple tests for nutpie

### ISSUE THREAD

**Issue by aseyboldt** [pymc-devs/pymc#6456]
### Description

It would be great if we had some tests in pymc to make sure we don't break nutpie. It broke a few days ago when the `logpt` model attribute was removed (my bad, it was deprecated after all...), and it would be nice if we noticed this before a release in the future.
(see https://github.com/pymc-devs/nutpie/issues/34)

**Comment by ricardoV94** [comment]
In this case, shouldn't the test be in nutpie?

**Comment by ricardoV94** [comment]
We can't test nutpie: https://github.com/pymc-devs/pymc/pull/6531/commits/f59adee99688ca34f19eacc46907124e2d9e9a64

 Must be the other way around
