### ISSUE TITLE
BUG: Graphviz error - omits edge when ZeroSumNormal is a parent of a deterministic

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc#6460]
### Describe the issue:

The graphviz representation of a model does not include an edge between a parent (when it's a ZeroSumNormal). In this case, the child in a deterministic.

In this graphviz output (see MWE below), there should be en edge from the `ZeroSumNormal` to the `Deterministic`
![Screenshot 2023-01-19 at 17 35 52](https://user-images.githubusercontent.com/6765047/213518729-80defaaa-016b-4260-8b18-c1d7a6fab780.png)

### Reproduceable code example:

```python
import pymc as pm
import aesara.tensor as at


coords = {"predictor": ["pred1", "pred2"], "group": np.arange(4)}
with pm.Model(coords=coords) as model:
    coords = {"predictor": ["pred1", "pred2"], "group": np.arange(4)}
    beta = pm.Deterministic(
        "beta",
        at.transpose(
            pm.ZeroSumNormal("_beta", zerosum_axes=1, dims=["predictor", "group"])
        ),
        dims=["group", "predictor"],
    )
    
pm.model_to_graphviz(model)
```

### Error message:

```shell
N/A
```

### PyMC version information:

Sorry this was done in v4 due to constraints of a particular project I'm working on.

PyMC version 4.4.0
aesara version 2.8.7

### Context for the issue:

This is not a major error in that it doesn't produce incorrect results. But the printed graphviz _is_ wrong. Many people rely on the visual representation of the model to spot errors etc, so addressing this would certainly be useful.

**Comment by lucianopaz** [comment]
Did you try whether this works with the latest version? There were some changes to model_graph functions that fixed missing edges

**Comment by drbenvincent** [comment]
Problem _not_ fixed under 5.0.1. 

I know that 5.0.2 was released 4 hours ago, but `mamba update pymc 5.0.2` not working.

**Comment by ricardoV94** [comment]
The relevant PR should be in 5.0.2 though: https://github.com/pymc-devs/pymc/pull/6426

**Comment by drbenvincent** [comment]
Sure. I guess it takes a while for things to update before I can `mamba update`?

**Comment by drbenvincent** [comment]
Ok. Using a local install of 5.0.2, this problem disappears.

**Comment by michaelosthege** [comment]
> Sure. I guess it takes a while for things to update before I can `mamba update`?

Usually a bot opens a PR which one of the highly trained monkeys must approve and merge.

It looks like there is no PR for 5.0.2 yet:https://github.com/conda-forge/pymc-feedstock/pulls

I don't know what triggers the bot, but one can manually open a PR as soon as the PyPI release is there.
