### ISSUE TITLE
BUG: Untagged PyMC version

### ISSUE THREAD

**Issue by SangamSwadiK** [pymc-devs/pymc#6466]
### Describe the issue:

Hi, I'm following the official guide to contributing to PyMC from [https://docs.pymc.io/en/latest/contributing/pr_tutorial.html](https://docs.pymc.io/en/latest/contributing/pr_tutorial.html).

`PyMC v4.1` got installed the first time I tried, but when I redid the entire thing, This `0+untagged.9350.g310ebaf` version came up. 
I'm on Miniconda as suggested on the pr_tutorial guide.
Any suggestions on helping me to install the v5 would be helpful.

Thanks !

### Reproduceable code example:

```python
import pymc as pm
```

### Error message:

```shell
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc as pm
>>> pm.__version__
'0+untagged.9350.g310ebaf'
```

### PyMC version information:

>>> pm.__version__
'0+untagged.9350.g310ebaf'

### Context for the issue:

Attaching a snippet of conda list
![image](https://user-images.githubusercontent.com/35230623/213906577-11aaf5d9-8a84-4e33-972c-6c1b17ac0468.png)

**Comment by michaelosthege** [comment]
If you `import pymc` and `print(pymc.__dict__)` it should say the path from where the it was imported from.
That should be your local clone.

Typically what I do is `mamba create -n pmdev -c conda-forge pymc` followed by activation, cloning of the PyMC repo and a `pip install -e .` to replace the version installed by mamba with an editable install of the local repository

**Comment by reshamas** [comment]
@michaelosthege 
Should we add this note to the contributing guide?

**Comment by michaelosthege** [comment]
> @michaelosthege Should we add this note to the contributing guide?

My procedure does not follow the contribution guide, and I'm not sure if the `+untagged` thing is related to the tips about finding the imported source, or maybe even completely expected `versioneer` behavior

**Comment by OriolAbril** [comment]
How did you clone the repo @SangamSwadiK? Maybe it doesn't have access to the whole history or to the tags and this happens? I know very little about versioneer but it seems like this is being triggered: https://github.com/pymc-devs/pymc/blob/main/pymc/_version.py#L238-L246

**Comment by michaelosthege** [comment]
g310ebaf is just the commit you are on

**Comment by michaelosthege** [comment]
Retrospectively I think there might just have been some confusion about the version number produced by versioneer...
