### ISSUE TITLE
BUG: Drawing samples with a single chain logs an incorrect warning and produces incorrect summary statistics

### ISSUE THREAD

**Issue by laurence-kobold** [pymc-devs/pymc#6484]
### Describe the issue:

Creating an `InferenceData` from a `MultiTrace` with a single chain logs an incorrect warning and produces an inference data with incorrect summary statistics. For instance, if the trace has 500 samples, the following warning will be logged:

```UserWarning: More chains (500) than draws (1). Passed array should have shape (chains, draws, *shape)```

The summary statistics will have 500 chains. The data for all chains but the first will be NaNs

### Reproduceable code example:

```python
import pymc as pm
import numpy as np

# Generate data
rng = np.random.default_rng(8927)
alpha, sigma = 1, 1
beta = [1, 2.5]
size = 100
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2
Y = alpha + beta[0] * X1 + beta[1] * X2 + rng.normal(size=size) * sigma

model = pm.Model()
with model:
    # Set up model
    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta = pm.Normal("beta", mu=0, sigma=10, shape=2)
    sigma = pm.HalfNormal("sigma", sigma=1)
    mu = alpha + beta[0] * X1 + beta[1] * X2
    pm.Normal("Y_obs", mu=mu, sigma=sigma, observed=Y)

    # Draw samples without using dask
    idata = pm.sample(draws=50, tune=50, chains=1, cores=1)
```

### PyMC version information:

pymc: 5.0.2
pytensor: 2.9.1
python: 3.9.16
OS: Debian 11 (Bullseye)
pymc was installed via pip

### Context for the issue:

The incorrect warning and sample statistics are misleading to users. The incorrect sample statistics also break some of the `arviz` functions that are used to analyze the inference data (e.g. `plot_trace`).

I realize that drawing samples for a single chain is not generally advisable, but this is actually part of a distributed inference workflow allowing me to draw samples using multiple machines. The workflow is as follows:
- Create N tasks to draw samples from a single chain
- Distribute those tasks across my machines (in my case, using `dask`)
- Combine the results of the tasks using `az.concat`

**Comment by ricardoV94** [comment]
I think the warning was fixed in https://github.com/pymc-devs/pymc/pull/6407

Not sure about the summary statistics

**Comment by laurence-kobold** [comment]
@ricardoV94 That's great. Thanks! I'm pretty sure that should fix the summary statistics as well. Do you know when the next version of pymc will be released?
