### ISSUE TITLE
ENH: Add `BlockedStep.stats_dtypes_shapes` to step signatures

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6503]
### Description

# Motivation

The current `BlockedStep.stats_dtypes` class attribute has some downsides:
- It does not pre-register shape information, which makes it impossible to preallocate memory for stats
- It's a list of dicts, but a dict should be sufficient. This creates a lot of added complexity across the codebase.

# Proposal

We should replace `stats_dtypes` by something that includes shape information:
* `()` for always-present, scalar stats
* `(1, 2, 3)` or the like for always-present, array stats
* `(2, 0)` for always-present stats with dynamic shape
* `None` for unknown/dynamic shape, or sparsely emitted stats

For always-present scalar/array stats we can preallocate memory.
Sparse, unknown or dynamic shape stats will end up in `dtype=object` arrays.
For comparison: https://github.com/michaelosthege/mcbackend/blob/6a75046b1496b1c24d1d8b0b22c4078f1c05592d/mcbackend/core.py#L22-L42

We could introduce a  `BlockedStep.stats_dtypes_shapes: Dict[str, Tuple[StatDtype, StatShape]` property with
* `StatDtype = Union[type, np.dtype]`
* `StatShape = Optional[Sequence[int]]`

Its default implementation as a property `BlockedStep.stats_dtypes_shapes` could inspect the old `BlockedStep.stats_dtypes` while defaulting the shape info to `None`.
Thereby we could refactor the internal code, get memory preallocation for stats and maintain backwards-compat to external/custom samplers.

## The `CompoundStep` case

`CompoundStep` might have been why `stats_dtypes` was defined as a list of dicts in the first place.
However, IMO we should flatten the stats of multiple samplers and rename them in one of the following ways:
* Prefixing with `sampler_#__`, for example `sampler_0__accepted` and `sampler_0__accepted`
* Prefixing with `{samplername}_{number}__`, for example `NUTS_0__accepted`, `Metropolis_0__accepted`, `Metropolis_1__accepted`

# Related issues
* #6207 
* #6194
* #5883

**Comment by covertg** [comment]
I think this is the best place to add this, but apologies if not.

If I may add a couple of use cases that could potentially come out of this (and the interconnected issues). It would be nice to be able to have sample stats that are available per-variable. It would also be nice to have sample stats that only change during the tuning process. An example that combines these two is: being able to easily check out the evolution of the Slice sampler's adaptation of slice width `w` for each variable. (I've been working with slice sampler a lot recently so it's on the mind...)
