### ISSUE TITLE
Raise if step sampler has variables that are not in `model.value_vars`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6511]
### Description

This showed up in https://discourse.pymc.io/t/incorrect-step-assignments-with-custom-step-function/11360/5

It should be easy to check that step samplers only have variables from `model.value_vars`

**Comment by michaelraczycki** [comment]
I'd like to try that out

**Comment by michaelraczycki** [comment]
From what I found out, sample() calls 'assign_step_methods' to get all the steps initialized. I think that adding something like you can see in line 172-173 can solve this issue of unnoticed incorrect step assignments, but I'm not sure whether we want to raise an error or a warning, and in case of an error - which one?
<img width="671" alt="Zrzut ekranu 2023-02-14 o 20 42 22" src="https://user-images.githubusercontent.com/119355382/218847380-5eb89040-e374-4e21-bded-7d10ec5d7920.png">

**Comment by ricardoV94** [comment]
Probably a ValueError saying the step samplers should only have value variables that belong to the model.

**Comment by michaelosthege** [comment]
Closed by #6524
