### ISSUE TITLE
ENH: enabling wider manual execution of tests before commit

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-devs/pymc#6525]
### Context for the issue:

Would it be possible to either document how to replicate the checks that GitHub pipelines are doing? If executing those tests manually is unavailable it would speed up the process of working on new features for new developers (like myself), if we would come up with some ways of doing it. Currently pre-commit checks are all passing, and only after the gitlab pipelines crash I know that some of the tests have failed. This makes debugging and incremental bug fixing much harder and longer. Not all devs will have previous experience with pytest, so providing some tips on how to make sure everything is covered before pushing would be very helpful.

**Comment by ricardoV94** [comment]
Running the entire test suite as part of the pre-commit would not be feasible (it would take hours everytime one commits). We have some documentation on how to run the tests locally here: https://www.pymc.io/projects/docs/en/stable/contributing/running_the_test_suite.html
