### ISSUE TITLE
arviz has no attribute from_pymc3

### ISSUE THREAD

**Issue by mhlg** [pymc-devs/pymc#6539]
### Description

arviz>=0.13.0 should be made arviz==0.14.0 
because with arviz==0.15.0 any time we call 
`pm.sample(100, tune=1000, initvals=start, cores=1)`
 we get AttributeError: module 'arviz' has no attribute 'from_pymc3'

**Comment by michaelosthege** [comment]
Sounds like you're on an outdated PyMC version. The `from_pymc` function is no longer called from the PyMC codebase.

**Comment by carinathrs** [comment]
> Sounds like you're on an outdated PyMC version. The `from_pymc` function is no longer called from the PyMC codebase.

hi, do you have any suggestions on resolving this issue?

**Comment by michaelosthege** [comment]
Make sure to install PyMC as described in the documentation: https://www.pymc.io/projects/docs/en/stable/installation.html

If you still get the error, we'll need a traceback to be able to help.
So far this issue contains no information about the PyMC or ArviZ versions, how the environment was installed or the traceback of the error message!

**Comment by ilyapopov** [comment]
Usage of from_pymc3 is still referred to in arviz docs here: https://python.arviz.org/en/latest/getting_started/CreatingInferenceData.html#from-pymc3
And in current pymc docs here: https://www.pymc.io/projects/examples/en/latest/ode_models/ODE_API_introduction.html

When I try it, is gives the error: 

    AttributeError: module 'arviz' has no attribute 'from_pymc3'. Did you mean: 'from_pyro'?

What shall i use instead?

**Comment by michaelosthege** [comment]
Yes, the notebook was not updated in a while. [This is the corresponding issue](https://github.com/pymc-devs/pymc-examples/issues/104).

`pm.sample()` already returns an `arviz.InferenceData`, so just ignore that `az.from_pymc3` stuff and do `idata = pm.sample()`

**Comment by Edmarotta** [comment]
Can you pls tell me in which file to make this change? I have looked at Classic.py; which line is it?
