### ISSUE TITLE
Installation of PyMC3 to Windows 11 using Spyder

### ISSUE THREAD

**Issue by Dresse97** [pymc-devs/pymc#6541]
### Describe the issue:

Hi
I am trying to install PyMC3 for studying purpose (Bayesian Updating) but cannot make it work.

I would like to use PyMC3 with Spyder and install it using Anaconda3.

Does anyone have a complete installation guide or maybe some ideas why it might work?

I have tried many different procedures posted online and controlled the installation using their examples.

I am new into this environment, so please help me.

### Reproduceable code example:

```python
.
```

### PyMC version information:

PyMC3

**Comment by twiecki** [comment]
PyMC3 is very outdated, follow the installation instructions here: https://www.pymc.io/projects/docs/en/latest/installation.html

Also, for questions, please use our discourse: https://discourse.pymc.io/
