### ISSUE TITLE
DOC: update sponsors to add Mistplay

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#6569]
### Issue with current documentation:

Page:
https://github.com/pymc-devs/pymc#sponsors

Add Mistplay.  You can get their logo from this repo:
https://github.com/pymc-devs/pymcon_web_series_website

**Comment by reshamas** [comment]
@Raj-Parekh24 yes, you can take this issue.

**Comment by Raj-Parekh24** [comment]
Hi @reshamas ,

I have updated the documentation for adding the sponsor image with their homepage link.

I have raised PR #6570 for this issue.

Please review it and suggest any required changes.
