### ISSUE TITLE
Rename `at` aliases to `pt`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6572]
### Description

We used to do `import aesara.tensor as at`, and for ease we just changed it to `pytensor.tensor as at`. Since we don't depend directly on any Aesara or Aesara-related library we should go with the new default `pytensor.tensor as pt`.

**Comment by Raj-Parekh24** [comment]
Hey @ricardoV94,

I am currently getting acquainted with the repository, I have raised PR for fixes in documentation issue #6569. For this I have set-up the local environment.

Can I take this issue to get myself acquainted with the code base.

**Comment by shreyas3156** [comment]
Hi, @Raj-Parekh24 I actually just made the changes for this issue and am in the process of submitting a PR.

**Comment by ricardoV94** [comment]
By all means, go ahead

**Comment by Raj-Parekh24** [comment]
Ok @shreyas3156,

Thanks for the update.

**Comment by shreyas3156** [comment]
Hi @ricardoV94, I have created a PR implementing the changes that would close this issue. It would be great if you could review it and provide a feedback as this is my first contribution to this repo.
