### ISSUE TITLE
DOC: correct minor typos in code examples for Potential function in model.py

### ISSUE THREAD

**Issue by chriswmann** [pymc-devs/pymc#6574]
### Issue with current documentation:

Code examples were recently added to the ``Potential`` function (#6559). However, the first and second code examples contain small typos (spurious minus signs) in the text that are inconsistent with the 'code' for the examples.

The 'actual' constraint added in the first example on line 2089, is ``pm.math.log(pm.math.switch(constraint, 1, 0.0))``. Given the constraint of ``constraint = x >= 0``, this correctly returns ``-inf`` if the constraint is ``false``. In the text on line 2080, the constraint is written as ``-pm.math.log(pm.math.switch(constraint, 1, 0))`` (minus sign at the front).

The same occurs in the second example, which is for a soft constraint that ``x >= 0``. The description uses ``-pm.math.log(pm.math.switch(constraint, 1, 0.5))`` (line 20910 but the 'code' uses ``pm.math.log(pm.math.switch(constraint, 1, 0.5))`` (line 2103).

**Comment by chriswmann** [comment]
I would like to fix this, if I may.

**Comment by ricardoV94** [comment]
@chriswmann go ahead. We should also make that warning shorter, it's a tad too verbose. The only thing it needs to convey is that Potentials apply to the logp, so they only influence logp based sampling (i.e., `sample` but not `sample_prior_predictive`/ `sample_posterior_predictive`)

**Comment by chriswmann** [comment]
Great, thanks @ricardoV94. I'll sort out the warning too.

**Comment by michaelosthege** [comment]
Closed by #6575
