### ISSUE TITLE
Proposal: Add ParticleStep class for samplers with many particles

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#659]
There exist an interesting class of samplers that instead of running a single chain, run many chains (particles) in parallel. One example is `emcee` which we could include (https://github.com/dfm/emcee/issues/140). Another one is `LHCM` (https://github.com/Sohl-Dickstein/LAHMC/issues/2).

My thought is to have a class next to `ArrayStep` that instead of a single state holds an 1d-array of states and proposes jumps on each one of them. This should somehow be integrated with theano to get parallelization over the particles (or the parallel logp evals).

I'm not sure what this would mean for the backend though. Do you have any thoughts on that @kyleam?

**Comment by kyleam** [comment]
> I'm not sure what this would mean for the backend though.

We may have to scrap the current design.  I'd suggest that you get things going independently of the backends (using whatever container for arrays works best).  Once that's up and running, I can focus on modifying the backends.

What do you think?

**Comment by twiecki** [comment]
Thanks @kyleam that makes sense. The `MultiTrace` does have support for multiple chains though, couldn't we leverage that (each particle == its own chain)?

Another idea would be to just always flatten the samples from each of N particles. Thus for each step there'd be N samples written to the backend. Looking at the trace would be non-sensical then but we it'd be pretty easy to unflatten.

**Comment by kyleam** [comment]
> The `MultiTrace` does have support for multiple chains though,
> couldn't we leverage that (each particle == its own chain)?

It has support for accessing multiple chains, but it doesn't know
anything about the sampling context.  It's just a container and
interface for single-trace objects.

> Another idea would be to just always flatten the samples from each of
> N particles. Thus for each step there'd be N samples written to the
> backend. Looking at the trace would be non-sensical then but we it'd
> be pretty easy to unflatten.

That makes sense, but this seems like the current backend design is
restricting the sampler design, which is why I'd be in favor of getting
the sampling going with whatever structure seems most appropriate and
then adapting and redesigning the backends as needed.

**Comment by kyleabeauchamp** [comment]
Sorry to crash the thread, but I wanted to chime in that particle-based samplers might be once place where larger-scale parallelism (#610) might be useful / convenient to build in.  For example, MPI / celery / ipython / map() based approaches.  

This might be simpler than supporting full parallel decomposition of the entire likelihood model.  emcee also seems to support this style of parallelism.
