### ISSUE TITLE
DOC: Add Welcome Bot to pymc repo

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#6601]
## Welcome Bot docs
- https://github.com/behaviorbot/welcome?setup_action=request
- https://github.com/behaviorbot/welcome?setup_action=request#usage

## Example PR
https://github.com/pymc-devs/pymc-data-umbrella/pull/192
https://github.com/pymc-devs/pymc/pull/6602

**Comment by ricardoV94** [comment]
I don't know, I think bots like this take away from the real  typed messages from other devs
