### ISSUE TITLE
BUG: target_accept ignored by numpyro and blackjax samplers

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#6613]
### Describe the issue:

I noticed the following behavior while sampling a large model:

<img width="624" alt="Screenshot 2023-03-19 at 4 05 03 PM" src="https://user-images.githubusercontent.com/81476/226206796-f6b8c612-aec4-4c13-98ca-602ec6af4297.png">

It appears that `target_accept` is not being used by either the numpyro or blackjax samplers. Acceptance rates tend to be around 90%. This occurs using both `pm.sample(nuts_sampler=...)` or the `sampler_*_nuts` functions.

### Reproduceable code example:

```python
import pymc as pm
import numpy as np
from pymc.sampling_jax import sample_numpyro_nuts

with pm.Model() as model:
    x = pm.Normal('x')
    y = pm.Normal('y', x * np.arange(10), sigma=1, observed=np.random.randn(10))

with model:
    trace = pm.sample(target_accept=0.7, nuts_sampler='numpyro')

trace.sample_stats.acceptance_rate.mean()

with model:
    trace = sample_numpyro_nuts(1000, tune=2000, target_accept=0.7)

trace.sample_stats.acceptance_rate.mean()
```

### Error message:

```shell
>>> trace.sample_stats.acceptance_rate.mean()
<xarray.DataArray 'acceptance_rate' ()>
array(0.86995989)
```

### PyMC version information:

5.1.1, 5.1.2 and current main

**Comment by fonnesbeck** [comment]
This is a little baffling, because the `target_accept` argument in `sample_numpyro_nuts` very clearly gets passed to:

```
nuts_kernel = NUTS(
        potential_fn=logp_fn,
        target_accept_prob=target_accept,
        **nuts_kwargs,
    )
```

**Comment by symeneses** [comment]
The `target_accept` is not being ignored. Trying the same example you gave with 0.95 and 0.99, with numpyro and blackjax, the mean acceptance rate is around the given values.

**Comment by fonnesbeck** [comment]
Yeah, looks like a different issue. I'm able to get high acceptance rates (0.95 and above), but not low acceptance (e.g. 0.7)
