### ISSUE TITLE
Remove `joint_logprob` function from `tests.logprob.util` submodule

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6619]
### Description

This function is not very helpful and only used in tests. We should be able to remove it, and use either `logp` or `factorized_joint_logprob` in the tests.

https://github.com/pymc-devs/pymc/blob/83cd926e572e710dc659ed4481de9e556b31bcf8/tests/logprob/utils.py#L50-L74

**Comment by shreyas3156** [comment]
Hi @ricardoV94, I'd like to take this issue up and get a better idea of logprob-related modules in the process.

There is a snippet inside the `logp()` method in `model.py` where `joint_logp()` is used.
https://github.com/pymc-devs/pymc/blob/2fcce433548a411f695d684ffb2d001a82a35f20/pymc/model.py#L758-L765

Should the logic from `joint_logp()` simply be added to the above section itself, to handle this single usage?

**Comment by ricardoV94** [comment]
@shreyas3156 Apologies, I referenced the wrong function. The one that should be removed is: https://github.com/pymc-devs/pymc/blob/83cd926e572e710dc659ed4481de9e556b31bcf8/tests/logprob/utils.py#L50-L74
