### ISSUE TITLE
problem with linalg 

### ISSUE THREAD

**Issue by rgn216** [pymc-devs/pymc#662]
I have an issue when I try to import pymc : "ImportError: No module named nlinalg" Do you have an idea where this might come from ?

Thank you, 

Roland

**Comment by twiecki** [comment]
Try updating theano to the master branch.

**Comment by jasonmhite** [comment]
Not OP, but I wanted to chime in and say that switching to the master branch of Theano fixed this error for me.

**Comment by rgn216** [comment]
thank you, I will try that.

Closed #662 https://github.com/pymc-devs/pymc/issues/662.

—
Reply to this email directly or view it on GitHub
https://github.com/pymc-devs/pymc/issues/662#event-213820359.
