### ISSUE TITLE
What is the order of the distributions?

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#6621]
### Description

On these pages:
https://www.pymc.io/projects/docs/en/latest/api/distributions.html

https://www.pymc.io/projects/docs/en/latest/api/distributions/continuous.html

What is the order that the distributions are listed?
They are not alphabetical.

**Comment by Dhruvanshu-Joshi** [comment]
Hey @larryshamalama @reshamas I would like to work on this

**Comment by ricardoV94** [comment]
Closed via #6653
