### ISSUE TITLE
Raise more informative logp initial point evaluation errors

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6629]
### Description

In the line 1782 `f"Initial evaluation results:\n{initial_eval}" ` below:

https://github.com/pymc-devs/pymc/blob/f3ce16f2606f523137c27466069f1ab737626f21/pymc/model.py#L1778-L1783

It would be good to specify that these initial evaluations correspond to the values of the log-probability at starting values of corresponding parameters. Changing line 1782 to `f"Logp initial evaluation results:\n{initial_eval}"` or something along these lines would work. Here is an example on how the current output of this error from [issue 214](https://github.com/pymc-labs/pymc-marketing/issues/214) in pymc-marketing:

```python
SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'a_log__': array(0.), 'b_log__': array(0.), 'alpha_log__': array(0.), 'r_log__': array(0.)}

Initial evaluation results:
{'a': 0.0, 'b': 0.0, 'alpha': 0.0, 'r': 0.0, 'likelihood': nan}
```

CC @ricardoV94

**Comment by shreyas3156** [comment]
Hi @larryshamalama! Co-incidentally, I just encountered this error while sampling through a `pm.Censored` likelihood on a censored data, while understanding the 'Support automatic derivation of arbitrary censoring logp' GSoC project. I then had to go through censoring regression examples to understand that I had to censor the dataset just like in the likelihood. 

In short, a better error message would definitely have helped conclude that the `-inf` I saw at the initial values in my parameters was infact its `logp`.

I would be happy to make this change and open a PR.

**Comment by Dhruvanshu-Joshi** [comment]
@shreyas3156 I actually started working on this PR before and am left with pushing it. Will it be okay if I do so?

**Comment by shreyas3156** [comment]
@Dhruvanshu-Joshi Sure, please go ahead!

**Comment by larryshamalama** [comment]
> Hi @larryshamalama! Co-incidentally, I just encountered this error while sampling through a `pm.Censored` likelihood on a censored data, while understanding the 'Support automatic derivation of arbitrary censoring logp' GSoC project. I then had to go through censoring regression examples to understand that I had to censor the dataset just like in the likelihood.
> 
> In short, a better error message would definitely have helped conclude that the `-inf` I saw at the initial values in my parameters was infact its `logp`.

Great to hear! Censored likelihoods and time-to-event are definitely tricky. If you have interest in applying or have general questions, don't hesitate to reach out to @ricardoV94 or I 🙂
