### ISSUE TITLE
Implement more types of measurable elemwise transformations

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6631]
We already have support for
- [x] add (and subtraction via addition)
- [x] mul (and division and neg via multiplication)
- [x] pow (inludes reciprocal, sqrt, sqr, etc...)
- [x] exp
- [x] log
- [x] abs

Other operations we could support
- [x] cosh, sinh and tanh (maybe other?)
- [x] erf, erfc, erfcx?
- [x] arcsinh, arctanh (see https://discourse.pymc.io/t/the-sinh-arcsinh-normal-distribution/12136)
- [x] arccosh is multivalued, or complex? Didn't have time to dig

https://github.com/pymc-devs/pymc/blob/f3ce16f2606f523137c27466069f1ab737626f21/pymc/logprob/transforms.py#L339

Other operations we can support via rewrites to already supported forms
- [x] exp2, log2, log10
- [x] log1p
- [x] expm1
- [x] log1mexp
- [x] log1pexp (softplus)
- [x] sigmoid

Example of such rewrites: https://github.com/pymc-devs/pymc/blob/f3ce16f2606f523137c27466069f1ab737626f21/pymc/logprob/transforms.py#L467-L483

**Comment by LukeLB** [comment]
@ricardoV94 is this just a continuation of the work done here https://github.com/pymc-devs/pymc/pull/6414/files? If so I can follow what I did there and knock a few of these off

**Comment by ricardoV94** [comment]
Yes, 👍

**Comment by LukeLB** [comment]
I've created Transform classes for cosh, sinh, tanh, erf, erfc however there doesn't appear to be an inverse function available for erfcx in pytensor or `pymc.math`. Any suggestions on what to do here? It feels like writing a new function in pytensor for erfcxinv may be overkill for this issue...

**Comment by ricardoV94** [comment]
You can check if it exists in `pytensor.tensor`. `pymc.math` is just a restricted subset of those.

If not you can play with the equivalence between erfcx and erfc

**Comment by LukeLB** [comment]
So if I rewrite it into that form I can get the foward function, but I don't understand how to get the backward function from that? This discussion on the inverse of erfcx in Matlab seems to suggest writing a specific functon https://www.mathworks.com/matlabcentral/answers/302915-inverse-of-erfcx-scaled-complementary-error-function

**Comment by LukeLB** [comment]
Not to worry, it did have me confused for a bit there! 

This is all a learning experience for me so happy to add value (even if small) wherever I can. What do you reccomend I do? 

Presumably open a new issue in PyTensor and link to this issue? Or can I just directly put in a PR on PyTensor for the function?

**Comment by ricardoV94** [comment]
I think you can implement it directly in pymc using Scan and Switch statements as building blocks.

**Comment by ricardoV94** [comment]
@LukeLB any interest in picking some of the new ones I added: arcsinh and arctanh?

A user on discourse was asking how to implement the sinh-arcsinh normal distribution: https://discourse.pymc.io/t/the-sinh-arcsinh-normal-distribution/12136 

The only ingredient missing is the arcsinh I think

**Comment by LukeLB** [comment]
@ricardoV94 really sorry I seem to have messed up by notifications when switching email addresses and didn't get an email through for this. Yes, I'd be interested in implementing these additional transformations! I'll have a look this week.

**Comment by ricardoV94** [comment]
No problem @LukeLB, still very much welcome and timely :)

**Comment by ricardoV94** [comment]
Closed via #6826
