### ISSUE TITLE
Bug in `rng_fn` of `HalfStudentT`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6657]
https://github.com/pymc-devs/pymc/blob/b7764dd09b9266006f24db021f1c4a8b825d7534/pymc/distributions/continuous.py#L2483

`sigma` should be passed by keyword as `scale`, otherwise it’s read as `loc`

Found in https://discourse.pymc.io/t/pm-halfstudentt-dist-failing-to-give-correct-shape/11821

**Comment by Dhruvanshu-Joshi** [comment]
Hey @ricardoV94 . I am working on this and will link a PR concerning this soon.

**Comment by ricardoV94** [comment]
Closed via #6658
