### ISSUE TITLE
BUG: Can't slice by a generator in observed data

### ISSUE THREAD

**Issue by alang9** [pymc-devs/pymc#6666]
### Describe the issue:

I tried updating the code from https://discourse.pymc.io/t/creating-unshuffled-sequential-minibatches/1118 to modern pymc but it results in this error

Simply removing the check here allows the code to run so maybe the check is simply too strict: https://github.com/pymc-devs/pymc/blob/640480545da026827a3b610a49e089958c7dd59a/pymc/model.py#L1337-L1352

PS: is this the recommended way of having sequential minibatches?

### Reproduceable code example:

```python
import pymc as pm
import pytensor
import pytensor.tensor as at
import numpy as np


def gen1(batchsize, totalsize):
    i = 0
    k = totalsize // batchsize
    while True:
        yield np.arange(batchsize) + batchsize * i
        i += 1
        # reset counter
        if i == k:
            i = 0


genvar = pm.generator(gen1(100, 1000))

X = np.random.randn(1000, 5)
beta = np.random.randn(5, 1)
y = X.dot(beta) + np.random.randn(1000, 1) * 0.75

Xshared = pytensor.shared(X)
yshared = pytensor.shared(y)
with pm.Model() as m:
    b = pm.Normal("b", 0.0, 100.0, shape=(5, 1))
    sd = pm.HalfNormal("sd", 5.0)
    yhat = at.dot(Xshared[genvar], b)
    obs = pm.Normal("y", yhat, sd, observed=yshared[genvar])
    approx = pm.fit()
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/alang/tmp/gibbs/test.py", line 30, in <module>
    obs = pm.Normal("y", yhat, sd, observed=yshared[genvar])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alang/tmp/gibbs/venv/lib/python3.11/site-packages/pymc/distributions/distribution.py", line 312, in __new__
    rv_out = model.register_rv(
             ^^^^^^^^^^^^^^^^^^
  File "/home/alang/tmp/gibbs/venv/lib/python3.11/site-packages/pymc/model.py", line 1344, in register_rv
    raise TypeError(
TypeError: Variables that depend on other nodes cannot be used for observed data.The data variable was: AdvancedSubtensor.0
```

### PyMC version information:

pymc-5.2.0, pytensor-2.10.1 via pip on on x86_64 linux

**Comment by ricardoV94** [comment]
Can you use `pm.Minibatch` directly?

**Comment by alang9** [comment]
I couldn't find a way to use `pm.Minibatch` to yield only sequential minibatches

**Comment by ferrine** [comment]
Hi, generator functionality was supposed to be used in case traditional minibatches do not fit memory, the usage described in the issue was supposed to work, but it was like this long time ago. It is a indeed a bug

**Comment by ricardoV94** [comment]
@alang9 does that fix your problem?

**Comment by alang9** [comment]
it does, thanks!
