### ISSUE TITLE
Doc for pymc3

### ISSUE THREAD

**Issue by hitalex** [pymc-devs/pymc#667]
The user guide at http://pymc-devs.github.io/pymc/ is for pymc2. Is there a doc for pymc3?

**Comment by twiecki** [comment]
Not yet, alas.

**Comment by hitalex** [comment]
I suppose I will leave this issue open until the doc for pymc3 is ready.

**Comment by twiecki** [comment]
We already have one here: https://github.com/pymc-devs/pymc/issues/346
