### ISSUE TITLE
Problem installing pymc: no module named nlinalg 

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc#669]
I installed pymc from default github branch using pip. When I try to import `pymc`, I get this error:

```
In [2]: import pymc
...
      1 from .dist_math import *
      2 
----> 3 from theano.tensor.nlinalg import det, matrix_inverse, trace
      4 from theano.tensor import dot, cast
      5 from theano.printing import Print
ImportError: No module named nlinalg
```

That seems related to the issue here (https://github.com/pymc-devs/pymc/issues/662) but since I did not explicitly clone `theano`, not sure how to fix this.

**Comment by kyleam** [comment]
Try removing any previous Theano installs and then installing with pip again.

**Comment by yarden** [comment]
I have never installed theano before - it's all within a local virtualenv that never had it.

**Comment by twiecki** [comment]
`pip install -U --no-deps git+https://github.com/theano/theano`

**Comment by yarden** [comment]
Thanks, that fixed it (but not sure why or what the problem was?).

**Comment by kyleam** [comment]
I can reproduce this. Despite the hack in 177c4061903ba72b65e39cbac78b1c69ea12a7c0, pip is installing the Theano from PyPI.  However, with `python setup.py install` from the pymc repo, the github version of Theano is installed.  I think this was working with pip at some point.

**Comment by kyleam** [comment]
As of [version 1.5](https://pip.pypa.io/en/latest/news.html), pip won't use dependency links unless the ([deprecated](https://groups.google.com/forum/#!topic/pypa-dev/tJ6HHPQpyJ5)) `--process-dependency-links` flag is passed.  I'll update the install instructions.

**Comment by shobhitverma** [comment]
I faced the same problem but the solution proposed here by @twiecki fixed it
