### ISSUE TITLE
📄 Change loggers to `getLogger(__name__)` to make them filterable

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc#6694]
### Description

Currently, all of PyMC logs with a logger named just `"pymc"`, which makes it impossible to filter logs by module.

For comparison, libraries such as `matplotlib` use loggers named after the current module:

https://github.com/matplotlib/matplotlib/blob/v3.7.1/lib/matplotlib/axes/_axes.py#L39

We should probably rename loggers across the PyMC (and PyTensor) codebase to adopt this practice:

```python
_log = logging.getLogger(__name__)
```

**Comment by pdb5627** [comment]
Is this really as simple as just find/replace `getlogger("pymc")` -> `getlogger(__name__)`? I'm very beginner but would be glad make pull request(s) with those changes.

**Comment by michaelosthege** [comment]
yes, almost

some tests may need to be updated to the new logger names

**Comment by pdb5627** [comment]
Ok, I'll have a go at it.

**Comment by pdb5627** [comment]
For anyone who might need to know, the test assertions were affected thusly:

Assertions of the form
`assert caplog.record_tuples == [("pymc", logging.INFO, "Sampling: [x, z]")]`
**do** need to have the full logger name set exactly, such as
`assert caplog.record_tuples == [("pymc.sampling.forward", logging.INFO, "Sampling: [x, z]")]`.
The changes in this pull request **did** require these to be changed.

It seems that any work done within contexts set up by
`with caplog.at_level(logging.DEBUG, logger="pymc")`
**do** need to have the logger name set, but it seems that it is **not** necessary to drill down further into the logging hierarchy than `"pymc"`. The changes in this pull request did **not** require these to be changed.
