### ISSUE TITLE
Progress bar didn't show up when using the `pymc.sample()` method

### ISSUE THREAD

**Issue by RickChauYanChak** [pymc-devs/pymc#6727]
### Describe the issue:

When using VSCode (v1.78) instead of the web-browser-based jupyter notebook, the progress bar of the sampling didn't show up, but when VSCode was downgraded to v1.73, the progress bar showed up again. If I'm using the browser-based jupyter notebook, then everything's fine.

### Reproduceable code example:

```python
import pymc as pm
pm.sample(1000)
```

### PyMC version information:

Version: 5.0.1

**Comment by fonnesbeck** [comment]
Hey @RickChauYanChak, this sounds like a VSCode issue rather than a PyMC issue. We just use the `fastprogress` package for our progress bars--there is nothing that PyMC does to modify them in any way, AFAIK.
