### ISSUE TITLE
DOC: Links to images in the `pymc_pytensor.ipynb` notebook are broken

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#6733]
### Issue with current documentation:

All the image links in the `pymc_pytensor.ipynb` notebook are broken. They appear not to have been updated when the notebook was moved.

**Comment by jaharvey8** [comment]
I can take this one. Looks like some of the images might have changed names (or maybe I'm looking in the wrong place). I'll post here to make sure I grabbed the correct one.

**Comment by twiecki** [comment]
@jaharvey8 That'd be great!

**Comment by OriolAbril** [comment]
closed by #6739
