### ISSUE TITLE
DOC: GLM Tutorial Comments out Bambi. Says waiting for PyMC5 compatability.

### ISSUE THREAD

**Issue by GeoffNordling** [pymc-devs/pymc#6734]
### Issue with current documentation:

Not sure when Bambi updated, but I uncommented the code and it works with PyMC5 now.

https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/GLM_linear.html
![Screenshot 2023-05-24 at 19 31 04](https://github.com/pymc-devs/pymc/assets/33404577/7ccec12a-bc37-499b-a696-ac2f286978f6)

### Idea or request for content:

Code looks like it can be uncommented now.

**Comment by twiecki** [comment]
@GeoffNordling Thanks for reporting, want to do a PR?
