### ISSUE TITLE
Use numpy testing utilities instead of custom `close_to*`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6748]
https://github.com/pymc-devs/pymc/blob/e1d36cacb2cfb946f56872ee03e8678dc6ccf7f4/tests/checks.py#L18-L27

Numpy testing routines already take care of asserting / printing failures nicely. We should just use them: https://numpy.org/doc/stable/reference/routines.testing.html

**Comment by error9098x** [comment]
Hi, I have changed the testing utility to numpy, now how do I test my changes locally ?

**Comment by ricardoV94** [comment]
This may help? https://www.pymc.io/projects/docs/en/stable/contributing/running_the_test_suite.html
