### ISSUE TITLE
DOC: Installation instructions need to be updated?

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc#6750]
### Issue with current documentation:

The current installation instructions:

```
conda create -c conda-forge -n pymc_env "pymc>=4"
```
can, under certain (unknown) circumstances, pull  a version of of pymc that is >4 but <5.  Can we just update the instructions?
```
conda create -c conda-forge -n pymc_env "pymc>=5"
```

@reshamas

**Comment by ricardoV94** [comment]
Yes we can and should update it

**Comment by error9098x** [comment]
Yeah, also how about using Mamba in the docs as an alternative too ?

**Comment by error9098x** [comment]
I believe it would be a good idea to update the installation docs for PyMC to ensure that versions of pymc<5 are not installed in unknown circumstances.

**Comment by cluhmann** [comment]
> Yeah, also how about using Mamba in the docs as an alternative too ?

There has been some informal discussion regarding this idea.  However, the choice was made (around the time v4 was released) to minimize the number of "official" installation methods.  Prior to this time, there were separate instructions for Windows/OSX/Linux, for conda, for homebrew, for pip, etc.  It was a mess.  Mamba is definitely worthy of a recommendation.  However, I am a bit wary as a) conda is far more mature and pervasive and b) if a user is already using mamba instead of conda, the "official" installation instructions can essentially be used "as-is" (and a mamba user would likely know this).
