### ISSUE TITLE
Can't replicate results in Bayes Factor page.

### ISSUE THREAD

**Issue by flimao** [pymc-devs/pymc#676]
Hello,

I'm not sure if this is the appropriate forum to ask this question. If it isn't, please let me know where I can find help.

Anyway, the page in question is this: [Calculating Bayes factors with PyMC](http://stronginference.com/bayes-factors-pymc.html). This issue was originally posted on [another GitHub repo](https://github.com/fonnesbeck/fonnesbeck.github.io/issues/1), but since I didn't get any answers, I thought to try asking here.

I ran the [model in it](https://github.com/pymc-devs/pymc/wiki/BayesFactor), using:

``` python
>>> M_m = Model('M_mm', [ Ylike, true_model, mu, p ])
>>> map_ = MAP(M_m)
>>> M = MCMC(M_m)
>>> M.sample(500000, burn=250000)
```

 but I keep getting probabilities of the Poisson model being True like these:

``` python
>>> true_model.stats()['mean']
0.56470799999999999
```

The traces look like these:

![image](https://cloud.githubusercontent.com/assets/5827775/6028070/ca56d6a8-abcd-11e4-88e6-b42a50bb68ad.png)

![image](https://cloud.githubusercontent.com/assets/5827775/6028074/d0e57970-abcd-11e4-9d28-325f313e22b3.png)

![image](https://cloud.githubusercontent.com/assets/5827775/6028076/d8c7eaa6-abcd-11e4-9991-f6e938277758.png)

Changing the burn-in, or thinning the posterior sample, doesn't change the outcome. 

I speculated that maybe including the `deterministic` variable `p` in the model was making the sampler's job harder (because it's correlated with `mu`), but removing it from the model specification didn't change the outcome either.

I'm not sure what's going wrong here. Can you help me, please? I'm using version 2.3.4 of PyMC, running it in Python 3.4.1 x64.

Cheers!

**Comment by fonnesbeck** [comment]
This should work now with either Categorical or Bernoulli. Please test.

**Comment by flimao** [comment]
Will do that shortly.

**Comment by flimao** [comment]
Commit does indeed fix the issue:

``` python
>>> true_model.stats()['mean']
0.39368
```

as shown on [webpage](http://stronginference.com/bayes-factors-pymc.html).

Thank you!
