### ISSUE TITLE
Rename module to pymc3

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#677]
This point has been discussed a bunch before (e.g. https://github.com/pymc-devs/pymc/issues/563) but I want to revisit it. I'm in favor of naming `pymc` version 3 `pymc3` for these reasons:
- The two are completely separate.
- Version 2 is widely used and will not be superseded anytime soon, especially given the slow pace of v3 development these past few months.
- As soon as we release a packaged version of `pymc3`  under the name `pymc` all libraries and user code that depend on `pymc` v2  that run `pip install -U pymc` will break.

I think the third point above weighs most heavily. An alternative would be to name the package `pymc3` on pypi but still leave the name `pymc` for the library. This would not allow having both installed at the same time.

The only contra I see is the import but I think this solution is quite feasible:
`import pymc3 as pm` and then everything else stays the same. Makes it explicit which is used.

Thoughts?

**Comment by aflaxman** [comment]
+1

**Comment by fonnesbeck** [comment]
I have a philosophical objection to including the version in the name (cf `ggplot2`), but all these points are valid. Since I'm not one to stand on principle, I will give it a +1 as well.

**Comment by twiecki** [comment]
@fonnesbeck I agree with that objection, although I think it should mainly apply if you're only breaking some parts of the API rather than a complete rewrite with 0% API compatibility. I think this is the conservative approach that won't step on anyone's toes. Moreover, since it'll be easier to have both side-by-side it might help adoption as the hurdle to install pymc3 will be lower.

**Comment by kyleam** [comment]
I'm not in favor of this.  The API is completely different, but that's reflected in the major version bump.  I don't think the problem of managing stable and developmental versions on the same system should be handled by changing the package name.

(I'm not strongly against it, given that it's just as easy for me to type `import pymc3 as pm`.)

**Comment by fonnesbeck** [comment]
I think the strongest reason for renaming is, as Thomas pointed out, that these two versions will likely be used and maintained for a long time, rather than having PyMC 3 replace PyMC 2 from the outset. So, many users may want to have both at their disposal, and this makes it easer to do so.

**Comment by kyleam** [comment]
Yes, I do think that is a fair point.
