### ISSUE TITLE
TestGARCH11::test_batched_size is failing under uncertain conditions

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#6787]
### Description

Tests are failing under uncertain conditions

https://github.com/pymc-devs/pymc/actions/runs/5334979522/jobs/9667560750?pr=6780

in #6780 

[FAILED tests/distributions/test_timeseries.py::TestGARCH11::test_batched_size[True-alpha_1]](https://github.com/pymc-devs/pymc/blob/f91dd1caa4995dcb684c2ec36b561454318106d0/tests/distributions/test_timeseries.py#L779)

**Comment by ricardoV94** [comment]
Would be useful to put the name of the test on the title of the issue

**Comment by ricardoV94** [comment]
For anyone investigating, usually these boil down to seeding issues
