### ISSUE TITLE
BUG: SamplingError: Initial evaluation of model at starting point failed! caused by -np.inf in pm.Potential

### ISSUE THREAD

**Issue by ThomasHoppe** [pymc-devs/pymc#6791]
### Describe the issue:

The documentation of PYMC 5.5.0 says for the description of Potential:
"The potential value is incorporated into the model log-probability, so it **should be -inf (or very negative) when a constraint is violated**, so that those draws are rejected. 0 won’t have any effect and positive values will make the proposals more likely to be accepted." 

Setting an -np.inf causes an
`SamplingError: Initial evaluation of model at starting point failed!

...

Logp initial evaluation results:
{'N': -2.4, 'M&M': -212.63, 'SingleM&MWeight': -0.38, 'BagofM&Ms': -51.02, 'GültigeTüte': -inf}
You can call model.debug() for more details.`

However using a large negative value like -10000000. works as expected.

see attached zipped notebook: 
[Startvalue Problem.zip](https://github.com/pymc-devs/pymc/files/11837576/Startvalue.Problem.zip)

### Reproduceable code example:

```python
with pm.Model() as model1: 

    number = pm.DiscreteUniform('N', lower=125, upper= 135)
    
    N = number.eval()
    
    colorsInMaMBag = pm.Categorical('M&M', p=[.207, .205, .198, .135, .131, .124], shape=(1,N))
    
    SingleMaMWeight = pm.TruncatedNormal('SingleM&MWeight', mu=2.33, sigma=0.44, lower=1.)
    
    BagofMaMs = pm.TruncatedNormal('BagofM&Ms', mu=2.33, sigma=0.44, lower=1., shape=(1,N))
    
    # Gewicht einer Tüte M&Ms
    WeightOfMaMBag = pm.Deterministic('WeightOfM&MBag', pm.math.sum(BagofMaMs))
        
    # Das Gewicht einer Tüte kann potentiell um ein M&M nach unten oder oben abweichen
    ValidBag = pm.Potential('ValidBag',
                            pm.math.switch(abs(WeightOfMaMBag - 300) < SingleMaMWeight, WeightOfMaMBag, -np.inf))
```

### Error message:

```shell
---------------------------------------------------------------------------
SamplingError                             Traceback (most recent call last)
Input In [13], in <module>
      1 with model1:
----> 2     trace = pm.sample(draws=2000,tune=2000)

File ~/.local/lib/python3.8/site-packages/pymc/sampling/mcmc.py:689, in sample(draws, tune, chains, cores, random_seed, progressbar, step, nuts_sampler, initvals, init, jitter_max_retries, n_init, trace, discard_tuned_samples, compute_convergence_checks, keep_warning_stat, return_inferencedata, idata_kwargs, nuts_sampler_kwargs, callback, mp_ctx, model, **kwargs)
    687 ip: Dict[str, np.ndarray]
    688 for ip in initial_points:
--> 689     model.check_start_vals(ip)
    690     _check_start_shape(model, ip)
    692 # Create trace backends for each chain

File ~/.local/lib/python3.8/site-packages/pymc/model.py:1784, in Model.check_start_vals(self, start)
   1781 initial_eval = self.point_logps(point=elem)
   1783 if not all(np.isfinite(v) for v in initial_eval.values()):
-> 1784     raise SamplingError(
   1785         "Initial evaluation of model at starting point failed!\n"
   1786         f"Starting values:\n{elem}\n\n"
   1787         f"Logp initial evaluation results:\n{initial_eval}\n"
   1788         "You can call `model.debug()` for more details."
   1789     )

SamplingError: Initial evaluation of model at starting point failed!
Starting values:
{'N': array(130), 'M&M': array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'SingleM&MWeight_interval__': array(0.), 'BagofM&Ms_interval__': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])}

Logp initial evaluation results:
{'N': -2.4, 'M&M': -204.75, 'SingleM&MWeight': -0.38, 'BagofM&Ms': -49.13, 'ValidBag': -inf}
You can call `model.debug()` for more details.
```

### PyMC version information:

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 8.0.1

numpy     : 1.24.3
pandas    : 2.0.2
arviz     : 0.15.1
matplotlib: 3.7.1
scipy     : 1.10.1
pymc      : 5.4.1

Watermark: 2.3.0

### Context for the issue:

Since I found a work around my work is no longer affected, nevertheless if it is a bug it should be removed.
Also the description under model1.debug() actually does not help

**Comment by ricardoV94** [comment]
>     N = number.eval()

You don't want to do that, as it will break the relationship between the `N` variable and `colorsInMaMBag`.
Once you do that, you have a different problem which is PyMC samplers can't handle variables with changing number of dimensions so your model is not supported.

About the Potential, it's just an example. If your model is specified in such a way that it is impossible at the start value `model.initial_point()` sampling will fail. You can change the default start values for each variable via `initval` so that it won't fail because of that. I think the most recent examples all have valid start values now:

https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.Potential.html

It's in `latest`, not `stable` because it corresponds to the next release of PyMC.

**Comment by ricardoV94** [comment]
I am going to close this as there seems to be no concrete bug and the documentation for Potential is already updated. If you have specific questions about your model, please open a topic in our discourse: https://discourse.pymc.io/

**Comment by ThomasHoppe** [comment]
Thank you for the comment concerning N = number.eval(). 

I have seen that in the dev version of the documentation the part about:

"The potential value is incorporated into the model log-probability, so it should be -inf (or very negative) when a constraint is violated, so that those draws are rejected. 0 won’t have any effect and positive values will make the proposals more likely to be accepted."

is removed.

From my point of view, it is a valuable feature, to use Potentials for such a kind of constraint in order to reject certain states of the model known to make no sense or intended to avoid. Like I did with the constraint on the weight of a bag.

What I think should be corrected is the behavior with respect to -np.inf and -10000000. How should a modeller should know which log likelihood is large enough for the rejection ...? Here I would suggest that -np.inf is substitued "under the hood" with the largest negative float of the used architecture (let be 32 or 64bit) ...

And concerning "setting the start values" where is it documented, when to set them? And how to set them? 
Googling "pymc initial start values" shows no useful documentation. Athough the pymc3 docs seem to adress these questions. How should a user know how to use them with pymc

**Comment by ricardoV94** [comment]
> What I think should be corrected is the behavior with respect to -np.inf and -10000000. How should a modeller should know which log likelihood is large enough for the rejection ...? Here I would suggest that -np.inf is substitued "under the hood" with the largest negative float of the used architecture (let be 32 or 64bit) ...

It's just probability. If you have a uniform model and set a constraint that negative numbers are twice less likely `np.log(0.5)`, then the sampler once calibrated, will yield 2x less negative samples than positive ones. If you set -inf, this won't be replaced by a very negative value, it will stay -inf and will never be accepted.

> And concerning "setting the start values" where is it documented, when to set them? And how to set them?
Googling "pymc initial start values" shows no useful documentation. Athough the pymc3 docs seem to adress these questions. How should a user know how to use them with pymc

This is probably in the docstrings of `sample`. Most models should be parametrized in a way that there are no impossible prior states. When you add Potential, as a user, you should be aware that you may now be introducing hard edges on your parameter space (even non-continous steps can be bad for NUTS sampling). In general `Potential` should only be used very sparingly and as a last resource.

**Comment by ThomasHoppe** [comment]
Unfortunately avoiding `N = number.eval()` with 

    N = pm.DiscreteUniform('N', lower=125, upper= 135)
    #N = number.eval()

Doesn' work. 

It gives an  
`
ValueError: Bad shape in start point:
Expected shape (1, 133) for var 'M&M', got: (1, 130)
Expected shape (1, 133) for var 'BagofM&Ms_interval__', got: (1, 130)`

I remember that a similar problem was the reason, that I used the number.eval() solution.

**Comment by ricardoV94** [comment]
That's what I was saying here:

> However, once you do that, you have a different problem which is PyMC samplers can't handle variables with changing dimension sizes so your model is not supported.

We don't have any PyMC samplers that work with variables that change shape
