### ISSUE TITLE
DOC: Fix mathematical notation in `conditional_logprob` docstrings

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6798]
### Description

Nitpick issue here

- $\Sigma$ is conventionally used for covariance matrices, so I prefer using $\sigma$ since the example is univariate.

https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/logprob/basic.py#L433-L434

- For continuous-valued random variables, I would prefer not writing $P(Y = y)$ because, in principle, it is always zero.
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/logprob/basic.py#L448-L449

What I would recommend is perhaps to use the random variables as indices to the log-density and valued variables as arguments to delineate their differences while addressing the point above: $\log p_{Y, \sigma^2}(y, s^2) = \log p_{Y \mid \sigma^2}(y \mid \sigma^2 = s^2) + \log p_{\sigma^2}(s^2)$. To me, this is better, but maybe not for everyone...

The last instance where change may be needed is: https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/logprob/basic.py#L438

**Comment by amyoshino** [comment]
I’m working on this next :)
