### ISSUE TITLE
DOC: Address occurrences of `pytensor-devs`

### ISSUE THREAD

**Issue by larryshamalama** [pymc-devs/pymc#6800]
### Issue with current documentation:

There are several occurrences of `pytensor-devs` in our docstrings. This was probably due to #6365 and some instances were overlooked.

https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/sampling/jax.py#L118
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/logprob/rewriting.py#L421
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/pymc/distributions/shape_utils.py#L410
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/docs/source/learn/core_notebooks/pymc_pytensor.ipynb#L13
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/tests/sampling/test_jax.py#L137
https://github.com/pymc-devs/pymc/blob/7b08fc160bc07adcfcd10e135e727c681ffb1b77/tests/distributions/test_distribution.py#L695

### Idea or request for content:

All occurrences point to issues from Aesara and/or AePPL. The links should be rectified to the original issues that they refer to, unless we want to remove these altogether.

**Comment by jaharvey8** [comment]
I can probably take this one but I'm not 100% I totally follow. pytensor-devs should be changed to pymc-devs correct? But where do some of the referenced issues exist? For example, I can't find https://github.com/pytensor-devs/pytensor/issues/1164. Maybe the issue number changed when switching over to pymc-devs.

**Comment by ricardoV94** [comment]
Those issue exist on `aesara-devs/aesara`. When we forked we replaced the names aesara->pytensor but shouldn't have for the github links.

**Comment by larryshamalama** [comment]
> I can probably take this one but I'm not 100% I totally follow. pytensor-devs should be changed to pymc-devs correct? But where do some of the referenced issues exist? For example, I can't find https://github.com/pytensor-devs/pytensor/issues/1164. Maybe the issue number changed when switching over to pymc-devs.

There is no such thing as "pytensor-devs", just "pymc-devs" as an organization. However, most issues were from the original Aesara and AePPL repositories. In other words, we can make the following substitutions in the comment hyperlinks:

- `pytensor-devs/pytensor` -> `aesara-devs/aesara`
- `pytensor-devs/aeppl` -> `aesara-devs/aeppl`

Feel free to open a PR and we can help you move forward with this!

**Comment by amyoshino** [comment]
Are you planning to work on this @jaharvey8?
If not I can open a PR for this issue :)

**Comment by jaharvey8** [comment]
> Are you planning to work on this @jaharvey8? If not I can open a PR for this issue :)

If you have time in the near future, you should take it. I'm a little swamped the next week or so.
