### ISSUE TITLE
Rectify Return type hint

### ISSUE THREAD

**Issue by Dhruvanshu-Joshi** [pymc-devs/pymc#6811]
### Description

Take a look at the code snippet below:
https://github.com/pymc-devs/pymc/blob/f67ff8bc22fcc72ead96eeeaef04173ed53650cb/pymc/logprob/binary.py#L42-L44

Here, the return type hint is wrong. ```MeasurableComparision``` is an ```Op```, but what is returned are ```TensorVariables``` whose node has that ```Op```.

This needs to be rectified for all the functions which intend to find a ```measurable op```.

CC @ricardoV94 @larryshamalama

**Comment by 5hv5hvnk** [comment]
@larryshamalama 
Just to be sure a fix would be returning the node or changing the return data type?

**Comment by larryshamalama** [comment]
> @larryshamalama Just to be sure a fix would be returning the node or changing the return data type?

Yes, I believe so! Sorry, I missed your question from a while ago

**Comment by vivek-anand-singh** [comment]
It seems like an easy fix. We just need to change variable "MeasurableComparison" in return type to variable "TensorVariable".

Here is the code modifications:
```
def find_measurable_comparisons(
    fgraph: FunctionGraph, node: Node
) -> Optional[List[TensorVariable]]:
```

Could you please verify if this is corrent? I can open a pull request for it.

**Comment by larryshamalama** [comment]
> It seems like an easy fix. We just need to change variable "MeasurableComparison" in return type to variable "TensorVariable".
> 
> Here is the code modifications:
> 
> ```
> def find_measurable_comparisons(
>     fgraph: FunctionGraph, node: Node
> ) -> Optional[List[TensorVariable]]:
> ```
> 
> Could you please verify if this is corrent? I can open a pull request for it.

That should be the case! And that would be great :)
