### ISSUE TITLE
DOC: Installation

### ISSUE THREAD

**Issue by Sinansi** [pymc-devs/pymc#6837]
### Issue with current documentation:

conda create -c conda-forge -n pymc_env "pymc>=5"

### Idea or request for content:

I am having hard time installing the package.
Conda cannot find the package you are referring to!

It says in the documentation, installation is done through conda forge channel, and to enforce the package version to be 5 or greater. But when I check your package on conda forge, it says the latest version available on windows-64 and linux-64 is v4.1.6.

https://anaconda.org/conda-forge/pymc

Can you please provide me with the correct command to install the package on windows-64?

**Comment by Sinansi** [comment]
After about one hour of search, Conda finally found the package.

**Comment by ricardoV94** [comment]
I suggest using mamba, it's way faster than conda.
