### ISSUE TITLE
ENH: JAX OP `MatrixIsPositiveDefinite`

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc#6849]
Hi! I tried to replicate the Correlated priors with `LKJCorr` from https://tomicapretto.github.io/posts/2022-06-12_lkj-prior/#model-4-correlated-priors-with-lkjcorr.-replicate-rstanarm-prior using the `numpyro` sampler and got the error:

### Before

```python
`NotImplementedError: No JAX conversion for the given `Op`: MatrixIsPositiveDefinite`. 
```

So it would be great to add this operator. 

Is this something a newbie like me could try?

### After

```python
We should be able to run the model above wit the JAX sampler from `numpyro`.
```

**Comment by ricardoV94** [comment]
> Can you clarify the second option (Otherwise ignoring like we do for Assert)? I do not get it 🙈

Some Ops like Assert ere not really supported by JAX so our dispatch is basically a pass through :`lambda x : x`

**Comment by juanitorduz** [comment]
I want to try this one out! Just to get started... where should I add the JAX code 

```python
import  jax.numpy as jnp

jnp.any(jnp.isnan(jnp.linalg.cholesky(x)))
```
?

**Comment by ricardoV94** [comment]
Check this guide (for pytensor): https://pytensor.readthedocs.io/en/latest/extending/creating_a_numba_jax_op.html

Then the code would probably go here: https://github.com/pymc-devs/pymc/blob/main/pymc/sampling/jax.py

And the tests in the respective jax tset file.

**Comment by ricardoV94** [comment]
Why we are at it we can remove the SpecifyShape from here: https://github.com/pymc-devs/pymc/blob/a2695a7fcac710edb9ed3e19fcda07defd7ba56f/pymc/sampling/jax.py#L63-L74

Because that's actually supported and well implemented in PyTensor
