### ISSUE TITLE
separating model definition from observations?

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc#686]
Hi,

I wanted to see if it's possible with the current pymc design to separate observations of random variables's values in a probabilistic model from the definition of the model itself. If not, I think it would be a useful feature to add in future. The syntax I imagine would separaet model definition from observations similarly to how the Church/Venture/Anglican probabilistic languages do [1].  Is this separation possible in pymc?  Consider the rain-umbrella Bayes net from AIMA [2], which I wrote in `pymc`:

```
import pymc
import numpy as np

rain = pymc.Bernoulli("rain", 0.5)

def umbrella_logp(value, rain):
    """
    Umbrella node. Initial value is False.

    P(umbrella=True | rain=True)  = 0.9 
    P(umbrella=True | rain=False) = 0.2
    """
    p_umb_given_rain = 0.9
    p_umb_given_no_rain = 0.2
    if rain:
        logp = pymc.bernoulli_like(value, p_umb_given_rain)
    else:
        logp = pymc.bernoulli_like(value, p_umb_given_no_rain)
    return logp

# declare umbrella as observed, with value True
umbrella = pymc.Stochastic(name="umbrella",
                           doc="umbrella var",
                           parents={"rain": rain},
                           logp=umbrella_logp,
                           value=True,
                           observed=True)
rain_hmm = pymc.Model([rain, umbrella])
m = pymc.MCMC(rain_hmm)
m.sample(iter=5000)
print "\n"
print "rain: "
print np.mean(m.trace("rain")[:])
```

The above model codes the conditional dependencies and runs inference for the case where the `umbrella` node is observed to be true. However, it'd be nice to take the model and then run inference in it with different sets of observations, without creating new nodes and new Model() instances.  E.g. run inference in same model where other nodes are observed, like `rain` instead of `umbrella`, or where `umbrella` is observed to be false instead of true. 

I tried instead making the stochastic nodes unobserved when defining them (`observed=False`) and then setting their value using the `.value` attribute, which the manual says is the right way to change values of nodes (http://pymc-devs.github.io/pymc/modelbuilding.html).  That didn't work: nodes that are observed seem to have to be declared as observed from the start, and once they're observed, their values can't change.  

Is there a way to achieve this separation?  Something along the lines of:

```
umbrella = pymc.Stochastic(name="umbrella",
                           doc="umbrella var",
                           parents={"rain": rain},
                           logp=umbrella_logp,
                           random=...)
# define the model, make no references to 'observe='
rain_hmm = pymc.Model([rain, umbrella])
# set observations if any, e.g.
rain_hmm.observe("rain", value=True)
rain_hmm.observe("other_node", ...)  # observe other nodes
# do inference
m = pymc.MCMC(rain_hmm)
...
# now set a new observations, without changing model
rain_hmm.observe("rain", value=np.na)  # rain not observed
rain_hmm.observe("umbrella", value=False) 
```

Thanks. 

[1] See "Inference" section in: http://www.robots.ox.ac.uk/~fwood/anglican/examples/bayes_net/index.html for simple example of separation between model assumptions ("assume" statements) and observations ("observe" statements).

[2] The Bayes net itself is given here: http://en.wikipedia.org/wiki/Forward%E2%80%93backward_algorithm#Example - I only wrote it up for a single time step above

**Comment by twiecki** [comment]
This is a pymc2 issue for which the correct repo is here: https://github.com/pymc-devs/pymc. Can you reopen there?
