### ISSUE TITLE
How to build the docs?

### ISSUE THREAD

**Issue by gabrielelanaro** [pymc-devs/pymc#687]
Hi, is there any instruction on how to build the docs?

**Comment by twiecki** [comment]
I need to add that.

**Comment by twiecki** [comment]
Fixed with https://github.com/pymc-devs/pymc3/commit/cce65025292df5abe6888d29b1d78d75ddf8dc5e. See https://github.com/pymc-devs/pymc3/blob/master/howto_docs.md.
