### ISSUE TITLE
binstar link in readme.md is broken

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc#688]
This link in readme.md leads to a 404: https://binstar.org/pymc/pymc

**Comment by twiecki** [comment]
This is a pymc2 issue: https://github.com/pymc-devs/pymc can you open over there?

**Comment by yarden** [comment]
Sure, though I only see `Binstar` mentioned in pymc3: https://github.com/pymc-devs/pymc3

**Comment by twiecki** [comment]
@yarden Ah, thanks for clarifying. Should be fixed.
