### ISSUE TITLE
Sponsor: add Adia Lab logo

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc#6902]
### Issue with current documentation:

Where to add it:
https://github.com/pymc-devs/pymc/blob/main/README.rst

What to add:
https://github.com/pymc-devs/brand/blob/main/sponsors/sponsor_logos/adia-lab/sponsor_adia_lab.png

Example PR:
https://github.com/pymc-devs/pymc/pull/6770

**Comment by canyon289** [comment]
@purna135 mind doing this one?

**Comment by rag9704** [comment]
@ricardoV94 hey, I am new to the PyMC community! Have picked this issue. Kindly review it!

**Comment by ricardoV94** [comment]
There's already a pull request to do this. Since the sponsor didn't materialize yet I am going to close the issue to avoid confusion.

Feel free to pick up another issue :)
