### ISSUE TITLE
Specify mean for GaussianRandomWalk innovations

### ISSUE THREAD

**Issue by akuz** [pymc-devs/pymc#691]
Currently there is no way to specify mean for GaussianRandomWalk innovations (just hard coded to zero in the code).

**Comment by twiecki** [comment]
Good point, should be easy to fix.

**Comment by akuz** [comment]
Sorry I haven't fixed myself and just left the comment. Planning to contribute in the near future. Possibly other processes for timeseries.py such as O-U process, Geometric Brownian motion, and mean reverting Geometrical Brownian motion (hybrid of O-U and GBM). Great library!

**Comment by twiecki** [comment]
Just took a look at the code. The mean isn't set to 0 (only the mean of the distribution). You can pass in an init distribution to specify the starting point. The mean of all following invocations is determined by `$$x_t \sim \mathcal{N}(x_{t-1}, \sigma)$$`

**Comment by akuz** [comment]
You could enable the drift like this:

$$x_t \sim \mathcal{N}(x_{t-1} + m, \sigma)$$

where the variable $$m$$ would be the common drift (same as parameter sigma).

**Comment by twiecki** [comment]
Oh, the question is in regards to drift, sorry, I misunderstood then.

**Comment by akuz** [comment]
Hi Thomas, I am learning about pull requests on github, once I have the change I will try send one to you.

**Comment by twiecki** [comment]
Great, looking forward to it @akuz.

**Comment by akuz** [comment]
Here it is, pretty simple: https://github.com/pymc-devs/pymc3/pull/896

**Comment by fonnesbeck** [comment]
#896 was merged. Closing.
