### ISSUE TITLE
error when trying to use pymc3 backend Text feature

### ISSUE THREAD

**Issue by xinliy123** [pymc-devs/pymc#6919]
### Describe the issue:

I got an error when trying to use pymc3 backend Text feature

### Reproduceable code example:

```python
import pymc3 as pm
db = pm.backends.Text('test')
trace = pm.sample(..., trace=db)
```

### Error message:

```shell
AttributeError: module 'pymc3.backends' has no attribute 'Text'
```

### PyMC version information:

3.11.5

**Comment by twiecki** [comment]
Thanks @xinliy123, note that `pymc3` is deprecated, you should use pymc 5.8. Also there's no good reason I know for using that text backend. What are you trying to do?
