### ISSUE TITLE
`run_mypy` script failing (due to new Pandas behavior?) 

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6940]
### Description

https://github.com/pymc-devs/pymc/actions/runs/6406798422/job/17392150214?pr=6933

**Comment by ricardoV94** [comment]
CC @michaelosthege

**Comment by michaelosthege** [comment]
Sounds like `failing = set(df.reset_index().file.str.replace(os.sep, "/", regex=False))` has non-`str` types in the `file` column.

Can you try replacing the line by this?

```python
failing = set(df.reset_index()["file"].astype(str).str.replace(os.sep, "/", regex=False))
```

**Comment by ricardoV94** [comment]
Didn't make the trick :)

```
This is good news! Go to scripts/run_mypy.py and remove them from the `FAILING` list.
WOW! All files are passing the mypy type checks!
```

I doubt so ^^

**Comment by ricardoV94** [comment]
Also why are we pinned to mypy 0.99?

**Comment by michaelosthege** [comment]
> Also why are we pinned to mypy 0.99?

Simply put we're pinned because our dependabot only cares about GitHub actions

Locally I can't reproduce this problem

**Comment by ricardoV94** [comment]
> Locally I can't reproduce this problem

Me neither. Probably a specific dependency version
