### ISSUE TITLE
Include `matmul` and other frequent function in `math` module

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6948]
### Description

Useful stuff like `zeros`, `ones`, `fill`, `fill_like`, `broadcast_to`, `mean`, `matmul` is missing.

**Comment by jaharvey8** [comment]
I can take this one.

These just need to get added to the import from pytensor.tensor and the __all__ lists in math.py yes?

**Comment by ricardoV94** [comment]
Yes
