### ISSUE TITLE
Reassess `MutableData` and `coords_mutable`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6972]
We could make all coords mutable by default and replace mutable lengths by constants before doing any operations on a Model object. Same for MutableData. We could have a helper function `freeze_graph` that does that.

Note we already do something similar for jax based sampling since shared variables aren't really supported in that backend

**Comment by jessegrabowski** [comment]
+1 to the 2nd idea. It seems like it should be possible to know which coords are mutable/constant based on the model? Consider this model:

```python

import pymc as pm

coords = {'a':[0], 'b':[0]}
with pm.Model() as mod:
    x = pm.MutableData('x', [3], dims='a')
    y = pm.ConstantData('y', [1], dims='b')
```

Just by looking at `mod.named_vars_to_dims`, we can immediately infer that 'a' is associated with a SharedVariable while 'b' isn't.  From here, it wouldn't be hard to have a helper function that checks all the dims and makes a replacement from a default of all constant -> some mutable or default all mutable -> some  constant.

**Comment by jessegrabowski** [comment]
My only objection to that is that if someday we allowed users to recycle compiled logp functions in pm.sample, it wouldn't be possible to change the data between runs. This is an oft-requested feature on the Discourse. 

I also don't think an on-going discussion about removing the Mutable/Constant data distinction should be a blocker to a PR that removes the distinction for coords.

**Comment by ricardoV94** [comment]
We can allow advanced users to still compile functions with shared variables, but I don't think that has to map directly to the `pm.Data` API, since it hasn't to this point anyway

**Comment by AlexAndorra** [comment]
Completely agree with this too -- making coords mutable by default, inferring which ones are not under the hood, and removing the distinction between Mutable and Constant Data.
All this adds boilerplate to the workflow and tends to make user experience less friendly, especially for beginners
