### ISSUE TITLE
Implement `__copy__` and `__deepcopy__` model methods

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#6985]
### Description

A couple of users on discourse got some nasty bugs when trying to do `copy.deepcopy(model)`. Whatever the default is doing, it ain't great.

We have a `clone_model` in `model/fgraph` that we can use for both copy and deepcopy!

It should work in all cases except for the known issue with GP variables https://github.com/pymc-devs/pymc/issues/6883

**Comment by Dekermanjian** [comment]
Hey @ricardoV94 I'd like to try implementing this. I just need some guidance. I don't quite understand what a shallow copy of a PYMC Model would entail. From what I understand, you can't mutate nested structures in a PYMC Model after you define the model. I think what `clone_model()` does is a deepcopy where making changes to nested structures like random variables that get turned into fixed values by using `pm.do()` won't be propagated to the clone.

**Comment by ricardoV94** [comment]
We don't need a shallow copy, both methods can do a deep copy

pm.do itself also does a deepcopy before doing its business

**Comment by Dekermanjian** [comment]
Oh okay, I see what you are saying. So both `__copy__` and `__deepcopy__` should return the same result that is equivalent to the `clone_model()` method. Did I understand that correctly?

**Comment by ricardoV94** [comment]
Yup

**Comment by Dekermanjian** [comment]
Okay, cool. Thanks!
