### ISSUE TITLE
Defining variables jointly with custom distributions

### ISSUE THREAD

**Issue by Arcanen** [pymc-devs/pymc#699]
Hi,
I'm attempting to define some variables jointly, but can't seem to find any reference on how to do this in pymc3. I'll demonstrate what I'm trying to do and what I've tried via a toy example. 

Let's say we have two random variables X and Y. These are (for the purposes of this toy example; not in general) independent normal rvs, but for the purposes of this problem, we don't know that (though we do know how to compute the joint log probability i.e. log(Prob(X=x,Y=y))). 

How do I define this kind of problem in pymc3? In lots of applications we'll have joint distributions of groups of RVs that we can't (or don't want to) separate. I haven't come across a way to define a DensityDist such that it'll be a joint distribution of more than one variable (e.g. the equivalent of the ndim parameter in emcee)? 

I found the way below using Potentials as a suggestion on stackexchange, but it doesn't seem to work properly either. Metropolis steps given absurd results, and NUTS just hangs forever. But the code (which is indented correctly in the writing, but not in the actual post for some reason) may be useful in showing what I'm attempting. In the general case the f2 function is just one large function of the inputs that we don't want to or can't separate into univariate distributions.

``` python
import pymc3
import theano.tensor as T

def f2(x,y):
    xreturn = T.log((1.0/(1*T.sqrt(2*pi)))*T.exp(-(T.cast(x-0.0,'float64')**2)/(2.0*1**2)))
    yreturn = T.log((1.0/(1*T.sqrt(2*pi)))*T.exp(-(T.cast(y-3.0,'float64')**2)/(2.0*1**2)))
    return xreturn+yreturn

model = pymc3.Model()
with model:
    x = pymc3.Flat('x')
    y = pymc3.Flat('y')
    xy = pymc3.Potential('xy',f2(x,y))
    start = model.test_point
    step = pymc3.NUTS(model.vars, scaling=start)

n=10000
with model:
    trace = pymc3.sample(n, step, start)
```

I also get the following with NUTS if I use anything other than test_point as a starting point:

```
[UserWarning C:\Anaconda\envs\wpymc3\lib\site-packages\theano\gradient.py:529: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: y
  handle_disconnected(elem)
C:\Anaconda\envs\wpymc3\lib\site-packages\theano\gradient.py:549: UserWarning: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <DisconnectedType>
  handle_disconnected(rval[i])]
```

**Comment by twiecki** [comment]
Would `pm.DensityDist` work here? See https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/custom_dists.py for an example.

Also looks like there's a problem with your code above.

**Comment by Arcanen** [comment]
I haven't found a way to define a DensityDist such that it'll be a joint distribution of more than one variable. If that is possible, it would be great. But all the examples I've seen that use DensityDist are for a single input. How do I make pymc3 recognise that I'm defining DensityDest over both X and Y? If I use density dist to refer to the f2(x,y), function ,e.g. with model: section instead has:

``` python
xy = pymc3.DensityDist('xy',lambda x,y: f2(x,y))
x = xy[0]
y = xy[1]

I get the following error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-f18ade5dafbb> in <module>()
     18     #y = pymc3.Flat('y')
     19     #xy = pymc3.Potential('xy',f2(x,y))
---> 20     xy = pymc3.DensityDist('xy',lambda x,y: f2(x,y))
     21     #x = xy2[0]
     22     #x = xy2[1]

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\distributions\distribution.pyc in __new__(cls, name, *args, **kwargs)
     17             data = kwargs.pop('observed', None)
     18             dist = cls.dist(*args, **kwargs)
---> 19             return model.Var(name, dist, data)
     20         elif name is None:
     21             return object.__new__(cls) #for pickle

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\model.pyc in Var(self, name, dist, data)
    141         """
    142         if data is None:
--> 143             var = FreeRV(name=name, distribution=dist, model=self)
    144             self.free_RVs.append(var)
    145         else:

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\model.pyc in __init__(self, type, owner, index, name, distribution, model)
    320             self.tag.test_value = np.ones(
    321                 distribution.shape, distribution.dtype) * distribution.default()
--> 322             self.logp_elemwiset = distribution.logp(self)
    323             self.model = model
    324 

TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

And if I define:

``` python
 xy = pymc3.DensityDist('xy',lambda xylist: f2(xylist))
```

and change f2 to be 

``` python
def f2(xylist):
    x = xylist[0]
    y = xylist[1]
    xreturn = T.log((1.0/(1*T.sqrt(2*pi)))*T.exp(-(T.cast(x-0.0,'float64')**2)/(2.0*1**2)))
    yreturn = T.log((1.0/(1*T.sqrt(2*pi)))*T.exp(-(T.cast(y-3.0,'float64')**2)/(2.0*1**2)))
    return xreturn+yreturn
```

I instead get the error

``` python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-ade8ad31362a> in <module>()
     18     #y = pymc3.Flat('y')
     19     #xy = pymc3.Potential('xy',f2(x,y))
---> 20     xy = pymc3.DensityDist('xy',lambda xylist: f2(xylist))
     21     x = xy[0]
     22     y = xy[1]

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\distributions\distribution.pyc in __new__(cls, name, *args, **kwargs)
     17             data = kwargs.pop('observed', None)
     18             dist = cls.dist(*args, **kwargs)
---> 19             return model.Var(name, dist, data)
     20         elif name is None:
     21             return object.__new__(cls) #for pickle

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\model.pyc in Var(self, name, dist, data)
    141         """
    142         if data is None:
--> 143             var = FreeRV(name=name, distribution=dist, model=self)
    144             self.free_RVs.append(var)
    145         else:

C:\Anaconda\envs\wpymc3\lib\site-packages\pymc3\model.pyc in __init__(self, type, owner, index, name, distribution, model)
    320             self.tag.test_value = np.ones(
    321                 distribution.shape, distribution.dtype) * distribution.default()
--> 322             self.logp_elemwiset = distribution.logp(self)
    323             self.model = model
    324 

<ipython-input-1-ade8ad31362a> in <lambda>(xylist)
     18     #y = pymc3.Flat('y')
     19     #xy = pymc3.Potential('xy',f2(x,y))
---> 20     xy = pymc3.DensityDist('xy',lambda xylist: f2(xylist))
     21     x = xy[0]
     22     y = xy[1]

<ipython-input-1-ade8ad31362a> in f2(xy)
      3 
      4 def f2(xy):
----> 5     x=xy[0]
      6     y=xy[1]
      7     xreturn = T.log((1.0/(1*T.sqrt(2*pi)))*T.exp(-(T.cast(x-0.0,'float64')**2)/(2.0*1**2)))

C:\Anaconda\envs\wpymc3\lib\site-packages\theano\tensor\var.pyc in __getitem__(self, args)
    420                     self, *theano.tensor.subtensor.Subtensor.collapse(
    421                         args,
--> 422                         lambda entry: isinstance(entry, Variable)))
    423 
    424     def take(self, indices, axis=None, mode='raise'):

C:\Anaconda\envs\wpymc3\lib\site-packages\theano\gof\op.pyc in __call__(self, *inputs, **kwargs)
    505         """
    506         return_list = kwargs.pop('return_list', False)
--> 507         node = self.make_node(*inputs, **kwargs)
    508 
    509         if config.compute_test_value != 'off':

C:\Anaconda\envs\wpymc3\lib\site-packages\theano\tensor\subtensor.pyc in make_node(self, x, *inputs)
    460                 len(idx_list), x.type.ndim))
    461             exception.subtensor_invalid = True
--> 462             raise exception
    463 
    464         input_types = Subtensor.collapse(idx_list,

ValueError: The index list is longer (size 1) than the number of dimensions of the tensor(namely 0). You are asking for a dimension of the tensor that does not exist! You might need to use dimshuffle to add extra dimension to your tensor.
```

Apologies, I should have posted all the things I had tried previously. The issue is that I don't know how to get pymc3 (using DensityDist or otherwise) to work when the logprobability is a function of two (or more) variables (i.e. in a more complicated case we're unsure how to separate the two variables, but know how to define their joint pdf) and we want to be performing inference on the values of those two variables. Is there some way to tell DensityDist that the input size is 2 (or more)?

**Comment by twiecki** [comment]
So you have 2D data and want to supply the joint pdf, right? I think in that case something like this might work:

``` python
pymc3.DensityDist('mylike', lambda value: logpdf1(value[0]) + logpdf2(value[1]), 
                  observed=my2d_data)
```

and my2d_data is 2xN.

**Comment by Arcanen** [comment]
It's not quite the case I had in mind. We don't have the ability to separate into logpdf1 and logpdf2. All we have is a single logpdf function. We also don't necessarily have data (but may in more complex examples). We're trying to define and sample from two (or more) random variables where we only know their joint distribution. I'm sure I must be missing something, because this would presumably be a common use case and is possible in pymc2 using code such as:

``` python
# Code that defines the prior: p(a,b)∝(a+b)^(−5/2)
@pm.stochastic
def ab(power=-2.5, value=[1,1]):
    if np.any(value <= 0):
        return -np.Inf
    return power * np.log(value[0]+value[1])

a = ab[0]
b = ab[1]
```

**Comment by jsalvatier** [comment]
I think this is not currently straightforward, but we can probably add it
without too much trouble.

However, you can currently do it with DensityDist by doing something like
this:

def computeLike(value):
  x = value[:n]
  y = value[n:]
  return #computed likelihood

xy = pymc3.DensityDist('mylike', computeLike, observed=my2d_data)

x = xy[:n]

y = xy[n:]

**Comment by Arcanen** [comment]
Still not exactly what I mean because my current example doesn't have observed data; the pymc2 code from my last post is probably clearer than my own example in showing what I'm trying to do. How would I do exactly that example, but with pymc3?

**Comment by jsalvatier** [comment]
``` python
def abLikelihood(value):
    return tensor.switch(any(value <= 0), -np.Inf, power *
np.log(value[0]+value[1])

ab = pymc3.DensityDist('mylike', computeLike, shape=2, testval = [1,1])

a = ab[0]
b = ab[1]
```

We should work on making this more intuitive.

**Comment by Arcanen** [comment]
Great, that seems to do the trick (both for that example and my original toy example). I think the confusion was in the precise meaning of the "shape" variable and the necessity of including the testval (since it doesn't appear to work without it). Previously I had thought shape just the parameter used to draw multiple IID random variables according to the supplied distribution (as opposed to declaring that the function will be of "shape" number of variables).

It seems that the meaning of shape has caused some confusion before, as in https://github.com/pymc-devs/pymc3/issues/535 . I strongly agree with the argument in there that there should be separate shape and dim variables. Perhaps if dim was automatically inferred from the dimensions of testval? Right now shape serves two purposes, and it's not immediately clear.

Anyway, thanks a lot for responding to my questions everyone!

**Comment by LuisPaAl** [comment]
Hello, 

I have found this post and I am hopping you could help me. I am working using pymc3 but i have had some problems programing my own parameter inference code. The problem is that I am trying to fit the model with a new Likelihood (which is not predefined in the pymc3 functions). The Likelihood basically is associated with an hyperparameter method that can be used when several datasets have to be taken into account. This method can be found here: https://arxiv.org/pdf/astro-ph/0203259.pdf, and the Likelihood that I am trying to implement is given by eq. (38) in the paper. I posted my question here, in this foro: "https://stats.stackexchange.com/questions/327386/deffining-a-new-likelihood-in-pymc3". There, you can find the Likelihood that I want to implement, the code that I wrote and the error that I am having.

Could, please, help me and give me a tip for programing my code correctly? Please

Thank you for your time. 

LP

**Comment by fonnesbeck** [comment]
Please use our [Discourse page](https://discourse.pymc.io) for advice on usage. Thanks.

**Comment by ally-lee** [comment]
Has this been implemented? I am having the same issue of wanting to define a custom multivariate distribution.


> I think this is not currently straightforward, but we can probably add it
> without too much trouble.
> 
> However, you can currently do it with DensityDist by doing something like
> this:
> 
> def computeLike(value):
> x = value[:n]
> y = value[n:]
> return #computed likelihood
> 
> xy = pymc3.DensityDist('mylike', computeLike, observed=my2d_data)
> 
> x = xy[:n]
> 
> y = xy[n:]
>

**Comment by lucianopaz** [comment]
@ally-lee, does the [documentation](https://docs.pymc.io/Probability_Distributions.html) help you in any way on how to implement a custom distribution? Furthermore, you should ask this sort of questions on our [discourse channel](https://discourse.pymc.io/) instead of in our issue tracker.
Regarding this issue, it was closed and marked as solved by the user that had opened it. Pymc3 does provide the infrastructure to define custom multivariate distributions. If you find that our documentation on the subject isn't really helpful, I suggest you first try asking on discourse, and then you are more than welcome to open a new issue here asking to improve the package's documentation.

**Comment by ally-lee** [comment]
@lucianopaz Thanks for your response! I haven't been able to figure it out using the documentation, so I posted my question on discourse.
