### ISSUE TITLE
BUG: logp of transformed variables leaks memory

### ISSUE THREAD

**Issue by velochy** [pymc-devs/pymc#6990]
### Describe the issue:

I am working with relatively large glm-s right now, and was running into very severe memory issues. 
So I broke the model into smaller sub-models and running them in sequence. It helped, but the memory footprint is still increasing on the order of gigabytes per model run, and by the fourth sub-piece still maxing out my 30gb of ram. 
If I save the intermediate result, restart the kernel and then run the last model, memory footprint is only ~6gb.

So I tried looking into it myself. First with tracemalloc (which made things very slow) and later with objgraph (which is zero overhead) and they both tell the same story: the issue is with the abstract type system (abc) as all of the .register calls leave a weakref that is never collected, so they just keep accumulating, and as best I could tell with an hour of googling, there is no easy way to reset or release them. 

Tested with all three samplers (regular, jax_numpyro, jax_blackjax) and they all exhibit the same behavior.

It would be quite difficult for me to share the models I am using, as they are generated using a set of rather complex functions that I would all have to share to provide a working example, leading to a very long and convoluted setup to what is a one-line problem. I believe the problem should be easy to reproduce with any decent-sized model and I hope everyone reading this has one lying around. If not, I can add a simple model description here.

### Reproduceable code example:

```python
# Use any decent-sized pymc model as 'model'

import objgraph, gc # Lowest overhead debug tool to show the effect

objgraph.show_growth()
for _ in range(10):
    pm.sampling_jax.sample_numpyro_nuts(model)
    # or pm.sample(model), or pm.sampling_jax.sample_blackjax_nuts(model)
    gc.collect() # Force collection to prove accumulation
    objgraph.show_growth()

# Note counts of weakref and builtin_function_or_method increase with every run
```
In the case of my models, last two steps look like this:

```
weakref                    65217987 +33382139
builtin_function_or_method 65166223 +33371309
dict                         480797   +114889
Var                          260439    +80020
list                         319239    +71068
tuple                        193843    +31638
```

```
weakref                    82420114 +17202127
builtin_function_or_method 82366482 +17200259
dict                         529400    +48603
Var                          294436    +33997
list                         349182    +29943
tuple                        210387    +16544
```

### PyMC version information:

PyMC 5.9.1

### Context for the issue:

Normally, you would not think this is an issue, but in my case, one single sub-model (out of 5) generated more than 3 x 10^9 of such references according to tracemalloc. objgraph shows more modest but still large counts at 3*10^7. In practical matters, however, my 30 GB of memory currently only manages 4 out of the 5 submodels in a row before filling up and forcing me to restart the kernel. 

I am trying to build a pipeline that automatically processes survey data we collect, and needing a python restart for it to fully run makes it really awkward to set up on the devops side.

**Comment by twiecki** [comment]
Thanks for the report. Did you confirm that it only happens with the numpyro sampler? What about the standard python or blackjax samplers?

**Comment by velochy** [comment]
> Thanks for the report. Did you confirm that it only happens with the numpyro sampler? What about the standard python or blackjax samplers?

Good point. Didn't think to check other samplers before. I'll run them both and get back to you :)

**Comment by velochy** [comment]
Same behavior for other two samplers @twiecki . Modifying the initial bug report with that info

**Comment by ricardoV94** [comment]
`sample` calls many functions under the hood. Can you check if the same problem happens if you set `pytensor.config.cxx = ""`,? That will disable PyTensor-related C code and may help narrowing down the problem

**Comment by velochy** [comment]
> `sample` calls many functions under the hood. Can you check if the same problem happens if you set `pytensor.config.cxx = ""`,? That will disable PyTensor-related C code and may help narrowing down the problem

Setting that does not change the behavior with regards to weakref counts. 
Inspecting reference chains for random instances of those weakrefs, they usually reference different RV types defined in PyMC  (example: ![chain](https://github.com/pymc-devs/pymc/assets/5527789/3caefd6b-7130-4c2b-9e6a-e436d00813c0)) so I'm decently confident in my assessment it has to do with the typing inside pymc. 

Code for inspection:
```
import random
objgraph.show_chain(
    objgraph.find_backref_chain(
        random.choice(objgraph.by_type('weakref')),
        objgraph.is_proper_module),
    filename='chain.png') 
```

**Comment by ricardoV94** [comment]
> so I'm decently confident in my assessment it has to do with the typing inside pymc

What do you mean?

**Comment by ricardoV94** [comment]
Btw if you are on the right track, there is no need to sample. You can just call `model.logp()` on a loop and you would see memory usage growing rather fast?

**Comment by ricardoV94** [comment]
> Btw if you are on the right track, there is no need to sample. You can just call `model.logp()` on a loop and you would see memory usage growing rather fast?

If this is the case can you set `transform=None` for all your model variables and check it goes away? The issue then would be here? https://github.com/pymc-devs/pymc/blob/ec4407d3db2c8ebe77e62c65f2eda3f5703e6279/pymc/logprob/transforms.py#L1232

I can see that never being released and it will grow every-time it's called. I do suspect you would need many many calls before exhausting 30 GBs of RAM? In any case if that's the sole problem we can work around it. I think it's the only place where we create a new type and register it every time the logp is calculated.

**Comment by velochy** [comment]
> Btw if you are on the right track, there is no need to sample. You can just call `model.logp()` on a loop and you would see memory usage growing rather fast?

You are right in that running that 100 times indeed throws the weakref count up to the moon:
```
weakref                      733343   +460024
builtin_function_or_method   717890   +458001
tuple                        124072     +2347
cell                          28727      +812
function                      79826      +804
frozenset                      4160      +800
_abc_data                      3799      +800
MetaType                       2155      +800
set                           12910      +794
dict                         145514      +635
```

So I think you put the finger on exactly the issue :)

As my model is complex and auto-generated, It's hard for me to set transform=none on all the variables in use, but I can try that trick with a smaller handmade model and see if it works later.

**Comment by velochy** [comment]
> I can see that never being released and it will grow every-time it's called. I do suspect you would need many many calls before exhausting 30 GBs of RAM? In any case, if that's the sole problem we can work around it. I think it's the only place where we create new types and register them every time the logp is calculated.

Honestly - it feels surreal to me too that typing could eat this much memory, but the fact is somehow my 30gb got filled and all my memory tracing seems to point to these weakrefs. As I am working with models generated by code (some of which compile for 30+ minutes for Jax), it is not inconceivable however.
 
> Edit: Perhaps also if you have a `CustomDist` and you are recreating the model in every iteration
Not to my knowledge. Using pretty standard distributions this time, most esoteric one being ZeroSumNormal.

**Comment by ricardoV94** [comment]
> As my model is complex and auto-generated, It's hard for me to set transform=none on all the variables in use, but I can try that trick with a smaller handmade model and see if it works later

You can use https://www.pymc.io/projects/docs/en/stable/api/model/generated/pymc.model.transform.conditioning.remove_value_transforms.html

**Comment by ricardoV94** [comment]
How many variables do you have in `model.free_RVs`? I imagine a ton of them xD?

Regardless of the problem you may be missing on same batching optimizations? https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/dimensionality.html

**Comment by velochy** [comment]
> > As my model is complex and auto-generated, It's hard for me to set transform=none on all the variables in use, but I can try that trick with a smaller handmade model and see if it works later
> 
> You can use https://www.pymc.io/projects/docs/en/stable/api/model/generated/pymc.model.transform.conditioning.remove_value_transforms.html

Thank you, will try once back at computer.
Does this change the model semantics in any way? And what are the transforms and how do i learn more about them?

**Comment by ricardoV94** [comment]
> Does this change the model semantics in any way? And what are the transforms and how do i learn more about them?

Yes, it's equivalent to setting all `transform=None` and you don't want to use it! I am suggesting just for confirming the source of the issue.

You don't need to worry about transforms, it's done automatically under the hood to make life easier for the sampler.

You do need to worry about having too many distinct variables instead of batching them as that results in a much less efficient graph and could explain how you hit this issue and why compilation takes so long for your model.

**Comment by velochy** [comment]
I am aware of just how magical batching is, and am using it quite widely. But thank you for making sure - it really does speed things up a lot

I realized i can post a graphviz of the model so you'd get a feel for the monsters I have. I'll do that later in the evening :)

**Comment by ricardoV94** [comment]
> I realized i can post a graphviz of the model so you'd get a feel for the monsters I have. I'll do that later in the evening :)

I'm happy with just `model.eval_rv_shapes()` or whatever it's called.

**Comment by velochy** [comment]
> > As my model is complex and auto-generated, It's hard for me to set transform=none on all the variables in use, but I can try that trick with a smaller handmade model and see if it works later
> 
> You can use https://www.pymc.io/projects/docs/en/stable/api/model/generated/pymc.model.transform.conditioning.remove_value_transforms.html

This had the predicted results - weakrefs no longer climb:
```
weakref                       25392     +2195
builtin_function_or_method    14821     +2187
dict                         126389      +102
function                      77177       +44
tuple                        113095       +35
method                        15237       +18
cell                          25527       +11
Config                           26       +11
Comm                             11       +11
set                            8731       +10
```
instead of the +460024 from before

This seems to conclusively prove your theory @ricardoV94 :)

**Comment by velochy** [comment]
As for the model I'm running, the first of the five steps (i.e. the smallest) looks like this: 

{'ls_log__': (), 'ls': (), 'baseline_sd_log__': (), 'baseline_sd': (), 'baseline': (10,), 'α_age_group_income_sd_log__': (1,), 'α_age_group_income_sd': (1,), 'α_age_group_income_offset_zerosum__': (1, 6), 'α_age_group_income_offset': (1, 7), 'α_gender_income_sd_log__': (1,), 'α_gender_income_sd': (1,), 'α_gender_income_offset_zerosum__': (1, 1), 'α_gender_income_offset': (1, 2), 'α_nationality_income_sd_log__': (1,), 'α_nationality_income_sd': (1,), 'α_nationality_income_offset_zerosum__': (1, 1), 'α_nationality_income_offset': (1, 2), 'α_education_income_sd_log__': (1,), 'α_education_income_sd': (1,), 'α_education_income_offset_zerosum__': (1, 2), 'α_education_income_offset': (1, 3), 'α_methods_income_sd_log__': (1,), 'α_methods_income_sd': (1,), 'α_methods_income_offset_zerosum__': (1, 1), 'α_methods_income_offset': (1, 2), 'α_age_group_education_income_zerosum__': (1, 6, 2), 'α_age_group_education_income': (1, 7, 3), 'α_gender_nationality_income_zerosum__': (1, 1, 1), 'α_gender_nationality_income': (1, 2, 2), 'σ_gp_income_log__': (1,), 'σ_gp_income': (1,), 'α_time_offset_income': (1, 5), 'cutpoints_income_ordered__': (5,), 'cutpoints_income': (5,), 'α_age_group_children_sd_log__': (1,), 'α_age_group_children_sd': (1,), 'α_age_group_children_offset_zerosum__': (1, 6), 'α_age_group_children_offset': (1, 7), 'α_gender_children_sd_log__': (1,), 'α_gender_children_sd': (1,), 'α_gender_children_offset_zerosum__': (1, 1), 'α_gender_children_offset': (1, 2), 'α_nationality_children_sd_log__': (1,), 'α_nationality_children_sd': (1,), 'α_nationality_children_offset_zerosum__': (1, 1), 'α_nationality_children_offset': (1, 2), 'α_education_children_sd_log__': (1,), 'α_education_children_sd': (1,), 'α_education_children_offset_zerosum__': (1, 2), 'α_education_children_offset': (1, 3), 'α_methods_children_sd_log__': (1,), 'α_methods_children_sd': (1,), 'α_methods_children_offset_zerosum__': (1, 1), 'α_methods_children_offset': (1, 2), 'α_age_group_education_children_zerosum__': (1, 6, 2), 'α_age_group_education_children': (1, 7, 3), 'α_gender_nationality_children_zerosum__': (1, 1, 1), 'α_gender_nationality_children': (1, 2, 2), 'σ_gp_children_log__': (1,), 'σ_gp_children': (1,), 'α_time_offset_children': (1, 5), 'cutpoints_children_ordered__': (4,), 'cutpoints_children': (4,), 'α_age_group_occupation_sd_log__': (8,), 'α_age_group_occupation_sd': (8,), 'α_age_group_occupation_offset_zerosum__': (8, 6), 'α_age_group_occupation_offset': (8, 7), 'α_gender_occupation_sd_log__': (8,), 'α_gender_occupation_sd': (8,), 'α_gender_occupation_offset_zerosum__': (8, 1), 'α_gender_occupation_offset': (8, 2), 'α_nationality_occupation_sd_log__': (8,), 'α_nationality_occupation_sd': (8,), 'α_nationality_occupation_offset_zerosum__': (8, 1), 'α_nationality_occupation_offset': (8, 2), 'α_education_occupation_sd_log__': (8,), 'α_education_occupation_sd': (8,), 'α_education_occupation_offset_zerosum__': (8, 2), 'α_education_occupation_offset': (8, 3), 'α_methods_occupation_sd_log__': (8,), 'α_methods_occupation_sd': (8,), 'α_methods_occupation_offset_zerosum__': (8, 1), 'α_methods_occupation_offset': (8, 2), 'α_age_group_education_occupation_zerosum__': (8, 6, 2), 'α_age_group_education_occupation': (8, 7, 3), 'α_gender_nationality_occupation_zerosum__': (8, 1, 1), 'α_gender_nationality_occupation': (8, 2, 2), 'σ_gp_occupation_log__': (8,), 'σ_gp_occupation': (8,), 'α_time_offset_occupation': (8, 5)}

And if you want to make more sense of it, graphviz looks like this:
![image](https://github.com/pymc-devs/pymc/assets/5527789/771241e0-bb38-4525-8773-1f1a3aa71ed7)

**Comment by ricardoV94** [comment]
Yeah, that's pretty insane :D

**Comment by velochy** [comment]
I would love to, except it seems I cannot get the package installed properly.

I do what one normally does: clone the repo and run `pip install -e .` inside it. Install seems to work. 

However, including pymc in a notebook starts throwing weird errors, like a circular reference around pymc.pytensor, missing STEP_METHODS or  "AttributeError: module 'pymc' has no attribute 'Deterministic'"

Should I be installing it differently, or running some other commands in the pymc directory before/after pip install?

**Comment by twiecki** [comment]
@velochy Have you done this in a fresh environment? I would install everything *but* PyMC via conda/mamba (especially pytensor) and then do `conda develop .` instead of `pip install -e .`, but that shouldn't matter.

**Comment by velochy** [comment]
Didn't have much experience with conda before today (I'm an old school virtualenv guy), but I worked through the version hell and got it to work.

Based on weakrefs, the issue looks solved. Running my large model overnight to see if the actual memory issue also goes away, but I think this particular ticket can be closed as if there is anothe leak, it likely has a different cause and source.

Thank you for the amazingly quick turnaround @ricardoV94 . Especially considering this seemed to be quite a non-trivial fix based on the commits :) I'm really impressed.

**Comment by velochy** [comment]
Overnight run finished all five steps and came in at just 4Gb memory use. So the issue is indeed fully solved :)
Thank you again.

**Comment by velochy** [comment]
Any chance there will be a release with this fix included soonish? Running a local branch is a pain,  especially to my slightly less tech-savy boss who would also like to use what I built :)

**Comment by ricardoV94** [comment]
Done: https://github.com/pymc-devs/pymc/releases/tag/v5.9.2

Should be on the main channels in a couple of hours

**Comment by tarmojuristo** [comment]
i'll put that "slightly less tech-savy boss" on my business card!
