### ISSUE TITLE
BUG: Command To Install JAX Per Google Works, But Command To Install JAX Per PyMC Does Not

### ISSUE THREAD

**Issue by tslever** [pymc-devs/pymc#6998]
### Describe the issue:

Use `pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` instead of `pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html`. The latter results in an error about `jaxlib` not being found.

### Reproduceable code example:

```python
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
import jax
jax.default_backend()
```

### Error message:

```shell
... jaxlib... not found
```

### PyMC version information:

None

### Context for the issue:

This issue represents a basic inconvenience with installing JAX.

**Comment by twiecki** [comment]
Is this foudn in the installlation instructions somewhere?

**Comment by tslever** [comment]
Yes: https://github.com/pymc-devs/pymc/wiki/Set-up-JAX-sampling-with-GPUs-in-PyMC-v4

**Comment by twiecki** [comment]
Fixed and renamed: https://github.com/pymc-devs/pymc/wiki/Set-up-JAX-sampling-with-GPUs-in-PyMC
Thanks!
