### ISSUE TITLE
apparent glm module regression

### ISSUE THREAD

**Issue by mmacpherson** [pymc-devs/pymc#702]
Following @twiecki 's [post](http://twiecki.github.io/blog/2013/09/12/bayesian-glms-1/) on the glm module exactly, this explicitly specified regression model succeeds:

```
with Model() as model: # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    sigma = Uniform('sigma', 0, 20)
    intercept = Normal('Intercept', 0, sd=20)
    x_coeff = Normal('x', 0, sd=20)

    # Define likelihood
    likelihood = Normal('y', mu=intercept + x_coeff * x, sd=sigma, observed=y)

    # Inference!
    start = find_MAP() # Find starting value by optimization
    step = NUTS(state=start) # Instantiate MCMC sampling algorithm
    trace = sample(2000, step, start=start, progressbar=False) # draw 2000 posterior samples using NUTS sampling
```

but this model, specified using the `glm` module, fails:

```
with Model() as model:
    # specify glm and pass in data. The resulting linear model, its likelihood and 
    # and all its parameters are automatically added to our model.
    glm.glm('y ~ x', data)
    step = NUTS() # Instantiate MCMC sampling algorithm
    trace = sample(2000, step, progressbar=False) # draw 2000 posterior samples using NUTS sampling
```

with the following error:

> PositiveDefiniteError: Scaling is not positive definite. Simple check failed. Diagonal contains negatives. > Check indexes [0 1 2]

When I switch `step` from `NUTS()` to `Metropolis()` in the glm version of the model, the sampling step succeeds, but then when I attempt `traceplot` in the next code block, I get this error:

> LinAlgError: singular matrix

The current glm test code seems to use a different sampler, `Slice()`, which runs but doesn't appear to complete in a reasonable amount of time.

This is running in a `ipython/scipyserver` docker instance with pymc3/Theano installed via pip from the github repo.

**Comment by twiecki** [comment]
OK, I updated the blog posts, fixed some GLM code, and rebuilt the docs. Can you retry with these updates to see if that fixed things?

Note that one of the changes was that you now have to call `find_MAP()` manually.

**Comment by mmacpherson** [comment]
Thank you. I loaded the example notebook (`GLM-linear.ipynb`), and executed each cell successfully until the cell where you set up the glm model. At the `find_MAP` call in that cell, I encounter this error:

> ValueError: Optimization error: max, logp or dlogp at max have non-finite values. Some values may be outside of distribution support. max: {'x': array(0.0), 'Intercept': array(0.0), 'sd': array(0.0)} logp: array(-inf) dlogp: array([ nan,  nan,  nan])Check that 1) you don't have hierarchical parameters, these will lead to points with infinite density. 2) your distribution logp's are properly specified. Specific issues: 

This error is a surprise to me, given the simplicity of the simulated dataset and the model.

**Comment by twiecki** [comment]
I assume you didn't upgrade pymc3, sd was being set to 0 as a test-value so the optimization did not start in a valid place. This is fixed as of the last commit so can you retry after updating pymc3?

**Comment by mmacpherson** [comment]
Thanks again. It appears that I did and do have the newest pymc3; this I confirmed by verifying the presence of the `radon.csv` file added in the relevant commit (e51dd879885ca3eb09a3ecf1aae163d2b6b778d8). I continue to see the same ValueError.

Following your comment about the test-value, I note that the error disappears if I edit `glm/families.py`, and modify line 87 within the definition of the Normal family from:

`priors = {'sd': pm_dists.HalfCauchy.dist(beta=10)}`

to:

`priors = {'sd': pm_dists.HalfCauchy.dist(beta=10, testval=1.0)}`

With that change, the `glm`-specified model runs without error for me, and the subsequent plots in the notebook look essentially similar to those in your published [post](http://twiecki.github.io/blog/2013/09/12/bayesian-glms-1/).

**Comment by twiecki** [comment]
No idea why this didn't get committed but here it is again: https://github.com/pymc-devs/pymc3/commit/5f7ef89d548646d7549e77b093ba28ffdbf85ef6

**Comment by mmacpherson** [comment]
Ah, that explains it. Thanks for your help. Closing the issue.

**Comment by twiecki** [comment]
Cool, thanks for reporting and helping tracking this down!
