### ISSUE TITLE
DOC: Installation instructions - JAX is now supported on windows

### ISSUE THREAD

**Issue by jackhenderson101** [pymc-devs/pymc#7036]
### Issue with current documentation:

In the installation instructions, it states that JAX is not directly supported on windows.

According to this issue https://github.com/google/jax/issues/438 JAX should now be supported on Windows (at least for CPU), and I was able to run numpyro by using pip install with no issues

**Comment by jackhenderson101** [comment]
Just wanted to double check that there wasn't another reason that this message was there.

**Comment by ricardoV94** [comment]
The lack of support was the only reason

**Comment by ricardoV94** [comment]
Closed via #7039
