### ISSUE TITLE
Is blackjax progressbar still broken?

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#7049]
is it still the case? @junpenglao 
https://github.com/pymc-devs/pymc/blob/02cbac6592506a547117b2daa3f05847d16fe063/pymc/sampling/jax.py#L454

**Comment by junpenglao** [comment]
No, Blackjax does not support progress bar under pmap yet. Contribution welcome tho.

**Comment by zaxtax** [comment]
I have a PR that should it be merged will address this: https://github.com/blackjax-devs/blackjax/pull/655
