### ISSUE TITLE
Use theano hessian and jacobian

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#705]
Theano now has functions to calculate the hessian and jacobian, so we should probably use those rather than roll our own.

http://deeplearning.net/software/theano/library/gradient.html#theano.gradient.hessian

**Comment by twiecki** [comment]
:+1:

**Comment by springcoil** [comment]
Has this been used?

**Comment by twiecki** [comment]
Not yet, but would be a great simplification.

**Comment by fonnesbeck** [comment]
The theano functions are definitely not drop-in replacements for ours. They are a little perplexing to use, actually.

**Comment by fonnesbeck** [comment]
One issue is that `hessian` and `jacobian` do not accept scalar variables. Probably best to stick with our own functions.

**Comment by twiecki** [comment]
OK, those do seem to work pretty well.
