### ISSUE TITLE
Silent failure of Dirichlet-multinomial model

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#706]
Specifying a pretty simple multinomial model with a Dirichlet prior on the probabilities fails without generating an error. All the resulting estimated probabilities are `nan`. Here is the model; it is simply estimating the age distribution of a sample population of age groups.

```
import pymc3 as pm

with pm.Model() as age_dist:

    n,k = age_counts.shape

    p_age, p_t = age_dist.TransformedVar(
        'p_age', pm.Dirichlet.dist(np.ones(k), shape=k),
        pm.simplextransform)

    counts = pm.Multinomial('counts', n=np.reshape(age_counts.sum(1), (n,1)), p=p_age, observed=age_counts)
```

[Here are the data](http://d.pr/f/4Z0D).

Secondarily, the `TransformedVar` syntax is very awkward, and needs to be automated. Referring to #315

**Comment by twiecki** [comment]
This is related to pymc trying to set to the mode, which returns nan if x_i < 1. See here: https://github.com/pymc-devs/pymc3/issues/443

**Comment by jsalvatier** [comment]
https://github.com/pymc-devs/pymc3/pull/737 should address this.

**Comment by jsalvatier** [comment]
#737 is merged in
