### ISSUE TITLE
Allow reusing function in `pymc.compute_log_likelihood`

### ISSUE THREAD

**Issue by DanielRobertNicoud** [pymc-devs/pymc#7073]
### Describe the issue:

Calling `pymc.compute_log_likelihood` multiple times on the same model leads to multiple compilations via `compile_fn`. This is a time sink (in some applications) that could easily be solved by storing the compiled function.

### Reproduceable code example:

```python
import numpy as np
import pymc

n = 5_000
n_feat = 3
X_train = np.random.normal(size=(n, n_feat))
y_train = np.random.normal(size=(n))

with pymc.Model() as model:
    # data containers
    X = pymc.MutableData("X", X_train)
    y = pymc.MutableData("y", y_train)
    # priors
    intercept = pymc.Normal("intercept", mu=0, sigma=1)
    b = pymc.MvNormal("b", mu=np.zeros(n_feat), cov=np.eye(n_feat))
    sigma = pymc.HalfCauchy("sigma", beta=10)
    mu = intercept + pymc.math.dot(X, b).flatten()
    # likelihood
    likelihood = pymc.Normal("obs", mu=mu, sigma=sigma, observed=y)

    idata = pymc.sample()

def compute_ll_twice(model, idata):
    n_test = 5
    X_test = np.random.normal(size=(n_test, n_feat))
    y_test = np.random.normal(size=(n_test))
    with model:
        pymc.set_data({"X": X_test, "y": y_test})
        for _ in range(5):
            out = pymc.compute_log_likelihood(idata, extend_inferencedata=False)

%prun -l 20 -s cumtime compute_ll_twice(model, idata)
```

### PyMC version information:

pymc==5.10.1

### Context for the issue:

In a research application I am writing, I need to call `pymc.compute_log_likelihood` many times (sometimes refitting the model in between). The calls to `compile_fn` take up to 60% of my computation time. If this could be easily fixed, it would be extremely helpful for me. Thank you very much in advance!

**Comment by ricardoV94** [comment]
All PyMC Model functions are recompiled everytime, including when you call pm.sample (or sample_posterior_predictive) multiple times with the same model. It's not trivial to know whether a model has changed of if the function we are requesting is the same that was requested in the past. 

I suggest you compile the function for log_likelihood and use it directly. The source code of compute_log_likelihood is not too complicated.

**Comment by DanielRobertNicoud** [comment]
@ricardoV94 That would be a very useful addition in the case where the model has not changed!

Maybe a way could be even to pass the compiled function to the `compute_log_likelihood` function as an optional argument?

**Comment by ricardoV94** [comment]
Closing this is favor of #7177

Thanks for bringing this up!
