### ISSUE TITLE
ENH: LKJCorr should return matrix rather than vector

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#7074]
### Before

`LKJCorr` returns an array corresponding to the off-diagonal elements of an upper-triangular matrix. 

```python
> pm.LKJCorr.dist(eta=1, n=3).eval()
array([ 0.06383647, -0.609944  , -0.13745336])
```

### After

`LKJCorr` should return a matrix with ones on the diagonal and the off-diagonal elements in their appropriate positions.

```python
> pm.LKJCorr.dist(eta=1, n=3).eval()
array([[ 1.        ,  0.06383647, -0.609944  ],
       [ 0.        ,  1.        , -0.13745336],
       [ 0.        ,  0.        ,  1.        ]])
```

### Context for the issue:

In the current implementations, the user is left to arrange this into a matrix themselves, which is cumbersome when there are more than one off-diagonal element. The pytensor `fill_diagonal` function only allows for scalar assignment, not array assignment as is the case with NumPy, so it must be filled by hand. Since almost every application will ultimately require the matrix, it should be returned to the user by default. This is also more consistent with `LKJCholeskyCov`, which returns an actual matrix and not just a flat array of values.

**Comment by ferrine** [comment]
Could it be An optional kwarg not to break the comparability

**Comment by fonnesbeck** [comment]
Or, generalize `pytensor.fill_diagonal` to take vector-valued fills, to be consistent with NumPy and make the construction of the matrix easy.

**Comment by ricardoV94** [comment]
I don't see how `fill_diagonal` helps here. The challenge is in the upper triangular

**Comment by ricardoV94** [comment]
For the specific case in the example, something like this would work:
```python
import pymc as pm
import pytensor.tensor as pt
import numpy as np

n = 3
x = pm.LKJCorr.dist(eta=1, n=n)
x_diag = pt.ones((n*2))
x_diag = pt.set_subtensor(x_diag[[1, 2, 4]], x)
y = pm.math.expand_packed_triangular(n=n, packed=x_diag, lower=False)
pm.draw([x, y])
```

However I am not sure if there's a good rule for the indexes [1, 2, 4], when n is larger

**Comment by ricardoV94** [comment]
Taking a step back, what kind of matrices do people usually create from the LKJCorr? I don't imagine the ones in the examples above or the final goal?

**Comment by ricardoV94** [comment]
Something like this?

```python
import pymc as pm
import pytensor.tensor as pt
import numpy as np

n = 3
length = n * (n - 1) // 2
x = pm.LKJCorr.dist(eta=1, n=n)

tri_index = np.zeros((n, n), dtype="int32")
tri_index[np.triu_indices(n, k=1)] = np.arange(length)
tri_index[np.triu_indices(n, k=1)[::-1]] = np.arange(length)

y = x[tri_index]
y = pt.fill_diagonal(y, 1)

pm.draw([x, y])
# [array([-0.62563319, -0.75617993,  0.6832039 ]),
#  array([[ 1.        , -0.62563319, -0.75617993],
#         [-0.62563319,  1.        ,  0.6832039 ],
#         [-0.75617993,  0.6832039 ,  1.        ]])]
```

**Comment by juanitorduz** [comment]
Yes, at least this output would be useful indeed!

**Comment by ricardoV94** [comment]
We could add it as an optional argument like we do for the LKJCholeskyCov (and if we want to make it a default start adding a warning)

**Comment by velochy** [comment]
Some useful discussion on this topic took place at:
https://discourse.pymc.io/t/using-lkjcorr-together-with-mvnormal/13606/22
