### ISSUE TITLE
TransformedVar and GaussianRandomWalk init

### ISSUE THREAD

**Issue by akuz** [pymc-devs/pymc#710]
I have a transformed var:

```
s, log_s = model.TransformedVar('s', 
                                                      pm.Exponential.dist(10.0, testval=0.1), 
                                                      pm.logtransform)
```

Then I initialise Gaussian random walk, and I want to provide the init distribution for the first value:

```
sigma = GaussianRandomWalk('sigma',
                                                   sd=s,
                                                   init=pm.Normal.dist(mu=0.01, sd=0.01),
                                                   shape=(n,))
```

However, since `s` is sampled in the log space, the init distribution applies to the `log` of the first value in the gaussian process, not to the actual value. So now, I would actually need to convert my init prior into the log space. This is confusing. Perhaps a better way can be found?

**Comment by twiecki** [comment]
Not sure I understand. `s` is sampled in the original, constrained, not-log space, right? `log_s` is the transformed variable.

**Comment by twiecki** [comment]
Closing. Feel free to reopen.

**Comment by jsalvatier** [comment]
Is there a doc that was particularly confusing?

**Comment by akuz** [comment]
I am sorry, it was my misunderstanding. Everything is correct. Variable `s` is sampled in log space as `log_s` variable, and the right exponentiated sample values are provided to gaussian process as values of `s`. All good, sorry, again, it was my misunderstanding.
