### ISSUE TITLE
pre-commit not always running in CI when it should

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pymc#7131]
### Description

#7108 deleted the EOF newline in `requirements-dev.txt`. After merge that broke pre-commit checks on `main`. There were no errors raised in the CI checks in #7108.

**Comment by ricardoV94** [comment]
Did that PR actually run with the new CI?

**Comment by maresb** [comment]
Oh, that's a really good point, it ran with neither the new nor the old. Unfortunately I only had a few minutes to look into why, and I didn't see anything at first glance, hence this issue instead of a solution in a PR.

Maybe it was just some glitch? I'll do a quick test...

**Comment by maresb** [comment]
My test in #7140 suggests that this was a glitch. I'll close, but we should keep an eye on it.
