### ISSUE TITLE
Disable `autofix_prs` in `pre-commit CI`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7142]
### Description

This sidesteps the requirement for manual approval CI for first-time contributors: https://github.com/pre-commit-ci/issues/issues/195

**Comment by ricardoV94** [comment]
Are we using this in other pymc-devs repos @maresb?

**Comment by maresb** [comment]
Fix verified in https://github.com/pymc-devs/pymc/pull/7140
