### ISSUE TITLE
get_tau_sd returns tau=0 when sd is an integer array

### ISSUE THREAD

**Issue by Davidianthompson** [pymc-devs/pymc#716]
sd_array = np.array([2])
get_tau_sd(sd=sd_array)

returns tau = 0: (array([0], dtype=int32), array([2]))

I think the issue is that the array sd_array is created as integer valued.  Then inside get_tau_sd the calculation 

tau = sd *\* -2

creates an integer array tau with zero(s) inside because it is doing an integer division.  Changing to 

tau = sd *\* -2.

seems to fix it.  New result: (array([ 0.25]), array([2]))

**Comment by aflaxman** [comment]
This looks like a good place for a learning-the-workflow pull request.  I'll give it a try, unless you want to.  Key line to edit: https://github.com/pymc-devs/pymc3/blob/255c63273f3ead8dcd51f7bd6ca6e614dd59b253/pymc3/distributions/continuous.py#L24
Good place to test: https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_distributions.py

**Comment by kyleam** [comment]
Thanks, good catch.  I think that in addition to the change you suggest, `get_tau_sd` should be modified so that both `sd` and `tau` are always returned as floats (notice the second element of your result is still an integer).
