### ISSUE TITLE
Rename sample_prior_predictive argument from samples to draws

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7173]
### Description

sample calls it draws, and the default dim is also `draw`. Whenever I want to use a kwarg to specify the number of draws I am always surprised it's called samples. Does everyone agree?

If so we could rename and add a futurewarning for the old arg name.

Or make everything samples... just use the same arg name please :)

**Comment by wd60622** [comment]
I agree with this and am for switching `samples` in `sample_prior_predictive` to `draws`. `draws` matches up with the xarray objects so I'm fine with that name

Will to take this
