### ISSUE TITLE
What about Nested Sampling?

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#719]
Hi guys, 
How feasible is Nested sampling - a la https://github.com/js850/nested_sampling

**Comment by fonnesbeck** [comment]
It looks eminently feasible, given that it's already been done in Python. Is there any sort of comparison of its performance relative to reversible jump MCMC, which is one of the standard ways of model selection via MCMC?

**Comment by springcoil** [comment]
I would need to look this up - to figure out the comparison. http://homepages.inf.ed.ac.uk/imurray2/pub/07thesis/murray_thesis_2007.pdf discusses these improvements.
http://homepages.inf.ed.ac.uk/imurray2/pub/07thesis/

"While not needed by MCMC, normalizers are key quantities: in Bayesian statistics marginal likelihoods are needed for model comparison; in statistical physics many physical quantities relate to the partition function. In this thesis we propose and investigate several new Monte Carlo algorithms, both for evaluating normalizing constants and for improved sampling of distributions.

Many MCMC correctness proofs rely on using reversible transition operators; often these operators lead to slow diffusive motion resembling a random walk. After reviewing existing MCMC algorithms, we develop a new framework for constructing non-reversible transition operators that allow more persistent motion."

**Comment by jsalvatier** [comment]
@timothydmorton also pointed me to [this paper for multimodal nested sampling](http://arxiv.org/pdf/0704.3704v3.pdf).

**Comment by twiecki** [comment]
See also here for a Python implementation of  https://github.com/can-cs/nestedsmc

**Comment by naesseth** [comment]
@twiecki The nested sequential Monte Carlo (NSMC) family of algorithms are not directly related to nested sampling even though they both have "nested" in the name. NSMC is a way to improve particle filters for high dimensional problems in which normal particle filters/SMC methods do not work. For more information on the NSMC see our paper http://arxiv.org/pdf/1502.02536v2.pdf (partly published at ICML this year)

**Comment by ingmarschuster** [comment]
To quote a Harvard Statistics Professor (not sure he would want to see his name here): "Nested Sampling is basically a false promise". Though I must admit that this might be taken with a grain of salt as it is likely said with respect to the original paper. However, it might be telling that there is little work on Nested Sampling coming from the statistics community.
There is an in-depth review, including a comparison to Reversible Jump: _Properties of nested sampling_, Chopin & Robert (2009).  If you are thinking of implementing a MC technique that is not MCMC for model selection, I would rather go with SMC, which provides easy and direct evidence estimates. I have quite some Python code which, given a "step"-Function (in PyMC speak), does either MCMC or SMC. This is very easy actually and could even be reimplemented in two days time.

**Comment by ingmarschuster** [comment]
Sorry, I might have been imprecise: what is needed to be able to do SMC is a function/method returning a proposed new value from the sampling space and the probability of the proposal.

**Comment by timothyb0912** [comment]
To add one more nested sampling implementation to the mix, there is:
http://kbarbary.github.io/nestle/

**Comment by springcoil** [comment]
I'd say this isn't a priority and I'm closing this now unless someone else brings it up.

**Comment by philastrophist** [comment]
Just querying the potential future implementation of nested sampling: wouldn't `pymc3` need to have definitions for the inverse cumulative distribution function for automatic prior transformations?

 I messed around with using `pymc3` likelihoods with `nestle` but I haven't found an easy way to automatically define prior transformations outside of manually referencing the `scipy.dist` implementations of the `ppf`s.
I'd be interested in hearing from knowledgeable people here!

**Comment by mattpitkin** [comment]
I just noticed this [paper](https://arxiv.org/abs/1805.03924) on nested sampling using SMC (they have an implementation of it [here](https://github.com/LeahPrice/SMC-NS), although it's in Matlab), which may be an approach that could more easily be incorporated into PyMC3(4).
