### ISSUE TITLE
Extend support to Python 3.12

### ISSUE THREAD

**Issue by renan-r-santos** [pymc-devs/pymc#7202]
### Description

Now that there's a new `pytensor` [release](https://github.com/pymc-devs/pytensor/issues/472) supporting Python 3.12, would it be possible to do the same for `pymc`?
For reference, here's the last PR where `pytensor` was bumped: https://github.com/pymc-devs/pymc/pull/7020. I'm not sure if the blockers mentioned there still hold.

**Comment by ricardoV94** [comment]
Yes we're planning to bump. Some tests are failing so we need to check
