### ISSUE TITLE
`pymc.testing` attempts to import `pytest` but `pytest` is not in `pymc` install requirements

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc#7218]
### Describe the issue:

a41d5244b8ec78372751924ba0484ed02d57b2cb included the `testing.py` module at the root level of `pymc`. [setup.py](https://github.com/pymc-devs/pymc/blob/main/setup.py#L75) says that the install requires are taken from [requirements.txt](https://github.com/pymc-devs/pymc/blob/main/requirements.txt), and that file does not include `pytest`.

This makes `from pymc.testing import anything` fail unless you already have installed `pytest`. Should `pymc` raise some kind of informative message instead of saying `ModuleNotFoundError: No module named 'pytest'`?

### Reproduceable code example:

```python
from pymc import testing
```

### Error message:

```shell
ModuleNotFoundError: No module named 'pytest'
```

### PyMC version information:

pymc version: 5.11.0

**Comment by ricardoV94** [comment]
Maybe we should import pytest locally, because not everything in there requires it. We are only using pytest for the pytest.warns feature

**Comment by lucianopaz** [comment]
Yes, that's fine with me.

**Comment by bomtall** [comment]
I would like to take this (as part of the hackathon)
