### ISSUE TITLE
The behavior of `.squeeze()` is different between `shape=(...)` and `dims=(...)`.

### ISSUE THREAD

**Issue by tomicapretto** [pymc-devs/pymc#7246]
### Description

See the following example:

```python
import pymc as pm

coords = {
    "x": ["level 1"],
    "group": ["g1", "g2", "g3"]
}

with pm.Model(coords=coords):
    b1 = pm.Normal("b1", shape=(3, 1))
    b2 = pm.Normal("b2", dims=("group", "x"))

print(b1.squeeze().shape.eval())
print(b2.squeeze().shape.eval())
```
```
[3]
[3 1]
```
I got that result after upgrading to PyMC 5.13. With older versions I get `[3]` in both cases. I imagine this is related to the fact that coords are always mutable now, but I'm not sure about it. Also, is this behavior desired?

**Comment by ricardoV94** [comment]
Yes, by default we assume dims can change, so squeeze can't be applied over those axes. One option is to consider dims of length 1 as fixed, and only others are mutable.

**Comment by tomicapretto** [comment]
It makes sense. The only place where I'm using this is in a specific part of Bambi, in a very particular case. But tests were failing so I found it. I think I can do `b[:, 0]` instead of `b.squeeze()`. Do you see any obvious drawback with this?

**Comment by ricardoV94** [comment]
If you know this is the case you can do `pt.specify_broadcastable` before calling squeeze

**Comment by ricardoV94** [comment]
Sounds like a limitation, can you open an issue in PyTensor for it?

**Comment by tomicapretto** [comment]
Of course :)
