### ISSUE TITLE
Move CustomDist logic to its own file

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7247]
### Description

The logic of CustomDist is getting pretty large. After #7239 I would refactor it into it's own file (and same for tests).

**Comment by markgreene74** [comment]
Hi 👋 I am here at the hackathon at Pydata London 2024. I would like to give this a try.

**Comment by Hemant19870601** [comment]
Hi Mate.. Even I am in same area without laptop. If you want any help or ok to work together, Give me shout.

**Comment by markgreene74** [comment]
@Hemant19870601 and I are working on this branch: https://github.com/markgreene74/pymc/tree/issue-7247-move-custom-dist-logic

Made good progress today! We should be able to finish it soon and raise a PR.
