### ISSUE TITLE
`pt.max` is not differentiable in PyMC models

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pymc#7251]
### Description

The following `model.dlogp()` raises a `NotImplemented` error:

```
with pm.Model() as model:
    x = pm.Normal('x', shape=(2,))
    mu = x.max()
    pm.Normal('obs', mu, observed=np.random.uniform())
```

This should be differentiable (`pt.max` has gradients implemented), so it seems like something is going wrong in rewrites, either with respect to logp rewrites or with respect to `MaxAndArgmax`

**Comment by bburan** [comment]
`min` also raises a `NotImplementedError`.

**Comment by ricardoV94** [comment]
`min` is just implemented as negative of max of negative, so that's expected

**Comment by tanish1729** [comment]
hi! i can take up this issue. i can see that this has to sort out dealing with gradients in the rewrites for some specific functions. could you provide some more details for me to start working

**Comment by ricardoV94** [comment]
@tanish1729 this one is not really a beginner friendly issue. I'll try and fix it now myself. Let us know if you need help finding more suitable issues

**Comment by tanish1729** [comment]
oh great i see you did this yourself. i'll go through the code and see if i can understand it.
what are some other good beginner friendly issues open rn?

**Comment by ricardoV94** [comment]
> oh great i see you did this yourself. i'll go through the code and see if i can understand it. what are some other good beginner friendly issues open rn?

You can filter issues on Github by labels: https://github.com/pymc-devs/pymc/issues?q=is%3Aissue+is%3Aopen+label%3A%22beginner+friendly%22

**Comment by bburan** [comment]
@ricardoV94 Thanks so much for fixing this so quickly. I can verify this solved the issue in my model and I am now able to run my model using NUTS only. Brings runtime down from ~2 hours to 10 minutes (3 minutes if I use an experimental NUTS sampler such as numpyro).

**Comment by ricardoV94** [comment]
You're welcome. By the way we don't consider the numpyro integration experimental anymore
