### ISSUE TITLE
Use odo to abstract away from backends

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#726]
@kyleam has written great code to handle traces and already implemented some backends like text, csv and sqlite. 

`odo` is a tool that transparently allows to interact with various data storages. Could we use `odo` to store traces in whatever backend is supported by it? The key feature is that it needs to support streaming.
https://odo.readthedocs.org/en/latest/
CC @mrocklin

**Comment by mrocklin** [comment]
cc @cpcloud

PyMC3 might find the [`chunks(np.ndarray)`](http://odo.pydata.org/en/latest/type-modifiers.html#chunks) node in the odo graph of value.

**Comment by twiecki** [comment]
That's great. So we could do:
`seq = odo(iter_sample, chunks('postgresql://localhost::mytable'))`
where `iter_sample` is a generator that returns each sample drawn (as a dict?).

**Comment by mrocklin** [comment]
`chunks` is a metatype.  It takes a type that odo already knows about.  Here is an example with iris

``` python
In [1]: from odo import odo, chunks, np
Couldn't import dot_parser, loading of dot files will not be possible.

In [2]: seq = iter(odo('sqlite:///iris.db::iris', chunks(np.ndarray), chunksize=5))

In [3]: next(seq)
Out[3]: 
array([(5.1, 3.5, 1.4, 0.2, u'Iris-setosa'),
       (4.9, 3.0, 1.4, 0.2, u'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, u'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, u'Iris-setosa'),
       (5.0, 3.6, 1.4, 0.2, u'Iris-setosa')], 
      dtype=[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8'), ('species', 'O')])

In [4]: next(seq)
Out[4]: 
array([(5.4, 3.9, 1.7, 0.4, u'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, u'Iris-setosa'),
       (5.0, 3.4, 1.5, 0.2, u'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, u'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, u'Iris-setosa')], 
      dtype=[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8'), ('species', 'O')])

In [5]: seq = iter(odo('sqlite:///iris.db::iris', chunks(list), chunksize=5))

In [6]: next(seq)
Out[6]: 
[(5.1, 3.5, 1.4, 0.2, u'Iris-setosa'),
 (4.9, 3.0, 1.4, 0.2, u'Iris-setosa'),
 (4.7, 3.2, 1.3, 0.2, u'Iris-setosa'),
 (4.6, 3.1, 1.5, 0.2, u'Iris-setosa'),
 (5.0, 3.6, 1.4, 0.2, u'Iris-setosa')]

In [7]: next(seq)
Out[7]: 
[(5.4, 3.9, 1.7, 0.4, u'Iris-setosa'),
 (4.6, 3.4, 1.4, 0.3, u'Iris-setosa'),
 (5.0, 3.4, 1.5, 0.2, u'Iris-setosa'),
 (4.4, 2.9, 1.4, 0.2, u'Iris-setosa'),
 (4.9, 3.1, 1.5, 0.1, u'Iris-setosa')]
```

Note that this uses sqlalchemy for extraction from the database and nothing custom/fast.  It will handle all of the type inspecting and coercion and blocking though.

**Comment by twiecki** [comment]
OK, since we know all the shapes ahead of time this should be be a problem.

**Comment by twiecki** [comment]
Actually I had the wrong order above. From an iterator I want to write to a data store (e.g. sqlite) in a chunked way.

**Comment by jsalvatier** [comment]
This would allow us to get rid of most of our custom backend code and let us use all the backends that odo knows about? 

That would be great!

It just has to support some kind of semi-efficient append (we can always batch on our end).

@mrocklin, I think we want to go the other direction, we have a sampler that produces an iterable sequence of dicts and we want to store them in some other source. Does that seem feasible?

**Comment by mrocklin** [comment]
Odo is happy to go in any direction along the graph.  Iterator is one of the nodes.  It will chunk and store as appropriate.  One issue with iterators is that because they are consumable it's hard to discover the relevant datatypes automatically.

``` python

In [1]: from odo import odo
In [2]: import json
In [3]: seq = map(json.loads, open('iris.json'))

In [4]: next(seq)
Out[4]: 
{'petal_width': 0.2,
 'sepal_length': 5.1,
 'species': 'Iris-setosa',
 'petal_length': 1.4,
 'sepal_width': 3.5}

In [5]: odo(seq, 'myfile.hdf5::/iris')  # This h5py dataset isn't yet created
NotImplementedError: Don't know how to discover type map
```

But if you're willing to specify this ahead of time (or create your target ahead of time) then all is well.

``` python
In [6]: from odo import discover, resource

In [7]: discover(resource('iris.json'))
Out[7]: 
dshape("""var * {
  petal_length: float64,
  petal_width: float64,
  sepal_length: float64,
  sepal_width: float64,
  species: string
  }""")

In [8]: ds = _

In [9]: odo(seq, 'myfile.hdf5::/iris', dshape=ds)
Out[9]: <HDF5 dataset "iris": shape (149,), type "|V40">

In [10]: _[:5]
Out[10]: 
array([(1.4, 0.2, 4.9, 3.0, 'Iris-setosa'),
       (1.3, 0.2, 4.7, 3.2, 'Iris-setosa'),
       (1.5, 0.2, 4.6, 3.1, 'Iris-setosa'),
       (1.4, 0.2, 5.0, 3.6, 'Iris-setosa'),
       (1.7, 0.4, 5.4, 3.9, 'Iris-setosa')], 
      dtype=[('petal_length', '<f8'), ('petal_width', '<f8'), ('sepal_length', '<f8'), ('sepal_width', '<f8'), ('species', 'O')])
```

**Comment by jsalvatier** [comment]
Oh, great, yeah I think that should be straightforward.

**Comment by kyleam** [comment]
Great, thanks for the discussion so far.  Below is my current
understanding of the proposal.

**Sampling**
1.  Set up the backend according to
   -   number of variables
   -   shape of each variable
   -   number of chains
   -   number of expected iterations
2.  Receive values for each iteration and, at some point, dump to the
   backend.
   
   _Now_
   
   Each backend subclass defines a method that recieves values at each
   iteration and decides how to store them.
   
   _With odo_
   
   After some amount of splitting and restructuring of the values for a
   given backend, odo will be used to send these to a path in the
   backend.
   
   So the calls would end up as
   
   ```
   odo(values0, backend::path0)
   ...
   odo(valuesN, backend::pathN)
   ```
   
   depending on how the paricular backend is structured.
   
   So far in this thread, I think values0 is being discussed as an
   iterable.  IIUC, this may be more complicated because each sampling
   iteration yields a set of values for all variables, but depending on
   the structure of the backend, these all aren't going to the same path
   in the backend.
3.  Return a trace object.

**Selection**

The returned trace provides access to the sampling values.  Currently,
this behavior includes allowing
-   N iterations to be discarded from the front of each variable.
-   Iterations to be extracted by a step.
-   Specific chains to be selected.

Values for all variables at a specific iteration can also be pulled
out.

_Now_

Each backend subclass is responsible for defining a method for
extracting the values from the database and formatting them according
to the shape of the requested variable.

_With odo_

Based on what is requested and setup of the backend, the values would
be retrieved from the database as

```
odo(backend::path0, ndarray0)
...
odo(backend::pathN, ndarrayN)
```

and then the ndarrays would need to be reshaped as needed so that the
shape matches

```
(number of iterations, ) + original variable shape
```

(Could blaze be used query the database, followed by using odo to
convert that subset to an ndarray?)

**Comment by mrocklin** [comment]
> (Could blaze be used query the database, followed by using odo to convert that subset to an ndarray?)

Yes.

``` python
In [1]: from blaze import Data, odo
Couldn't import dot_parser, loading of dot files will not be possible.

In [2]: d = Data('sqlite:///iris.db::iris')

In [3]: d.fields
Out[3]: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [4]: import numpy as np

In [5]: result = d[['species', 'petal_length', 'sepal_length']]

In [6]: odo(result, np.ndarray)[:5]
Out[6]: 
array([(u'Iris-setosa', 1.4, 5.1), (u'Iris-setosa', 1.4, 4.9),
       (u'Iris-setosa', 1.3, 4.7), (u'Iris-setosa', 1.5, 4.6),
       (u'Iris-setosa', 1.4, 5.0)], 
      dtype=[('species', 'O'), ('petal_length', '<f8'), ('sepal_length', '<f8')])
```

**Comment by jsalvatier** [comment]
@kyleam nicely put!

**Comment by twiecki** [comment]
> So far in this thread, I think values0 is being discussed as an
> iterable. IIUC, this may be more complicated because each sampling
> iteration yields a set of values for all variables, but depending on
> the structure of the backend, these all aren't going to the same path
> in the backend.

I think `odo` supports this case. What do you mean with all aren't going to the same path?

**Comment by twiecki** [comment]
@mrocklin I suppose we could just use the first sample to specify the dshape. Would we have to do that manually or is there a way to set that in odo?

**Comment by kyleam** [comment]
> I suppose we could just use the first sample to specify the dshape

`test_point` has this information.

**Comment by kyleam** [comment]
> What do you mean with all aren't going to the same path?

For each iteration, you're getting data for each variable, but these can be going to different paths in the database.  For example, for HDF5

```
 file.hdf5::/chain0/x
 file.hdf5::/chain0/y
```

`

**Comment by mrocklin** [comment]
> @mrocklin I suppose we could just use the first sample to specify the dshape. Would we have to do that manually or is there a way to set that in odo?

In principle yes, this is a good idea.  The internals of odo make doing this a bit of a pain so this isn't done yet; it probably could be though if we find some time.  One could also do this externally to odo using `itertools.tee` and `odo.discover`

**Comment by twiecki** [comment]
@kyleam You're right, should be trivial to get the dtype from the `test_point`.

To me this whole thing looks very feasible and would greatly simplify the backend code and give us quite a few new backends to chose from. blaze and odo are no small dependencies (but easy with anaconda). that could be optional for people who can't use the memory based trace.

@kyleam has thought most about this, any summarizing thoughts?

**Comment by kyleam** [comment]
> any summarizing thoughts?

Not at the moment.  I'll try to find some time to get something up and
running so that we have something concrete to discuss and work from.

(@mrocklin thanks for taking the time to comment and for your work on
odo and blaze!)

**Comment by kyleam** [comment]
Here's simplified sampling code that I'm trying to get working.  It
ignores chains for the moment, and it targets HDF5 to avoid having to
reshape the values into a table-like structure.

```
#!/usr/bin/env python3

import numpy as np
from odo import odo
import os


def points():
    np.random.seed(70)
    for _ in range(10):
        yield {'x': np.random.randn(4, 3),
               'y': np.random.randint(0, 3, size=())}

# var_dshape = {'x': 'var * {x: 4 * 3 * float64}',
#               'y': 'var * {y: int}'}

## Shapes including iterations
var_dshape = {'x': 'var * {x: 10 * 4 * 3 * float64}',
              'y': 'var * {y: 10 * int}'}

var_names = list(var_dshape.keys())

fname = 'test.hdf5'
if os.path.exists(fname):
    os.remove(fname)
var_path = {v: '{}::/{}'.format(fname, v) for v in var_names}

for pt in points():
    for var in var_names:
        odo(pt[var], var_path[var], dshape=var_dshape[var])
```

This fails with this h5py error:

```
TypeError: Can't broadcast (4, 3) -> (4,)
```

I'm probably missing something obvious, but I haven't had any luck
getting this to work.

**Comment by jsalvatier** [comment]
Looks cool, not sure why its not working.

**Comment by twiecki** [comment]
@mrocklin Any idea why this isn't working?

**Comment by mrocklin** [comment]
If you provide a dshape to an odo call then it expects something of that dshape, not a single slice.

There are two approaches here; one would be to `odo` the entire iterator at once.  It will handle all of the laziness appropriately.

``` python
In [29]: def points():
    np.random.seed(70)
    for _ in range(10):
        yield np.random.randn(4, 3)
   ....:         

In [30]: odo(points(), 'test.hdf5::/x', dshape='var * 4 * 3 * float64')
Out[30]: <HDF5 dataset "x": shape (10, 4, 3), type "<f8">
```

The other would be, as written above, to create the dataset and then use odo many times to handle the appends manually.

``` python
In [39]: x2 = resource('test.hdf5::/x2', dshape='var * 4 * 3 * float64')

In [40]: def points():
    np.random.seed(70)
    for _ in range(10):
        yield np.random.randn(1, 4, 3)  # note that I had to have the same dimension
   ....:         

In [41]: for pt in points():
    odo(pt, x2)
   ....:     

In [42]: x2
Out[42]: <HDF5 dataset "x2": shape (10, 4, 3), type "<f8">
```

**Comment by twiecki** [comment]
Thanks @mrocklin. @kyleam any thoughts/progress?

**Comment by kyleam** [comment]
@twiecki Sorry, I haven't revisited this beyond playing with the
suggestions for the code snippet.  Feel free to work on this because I
think you have a much better sense than I do for what's being proposed
and how it would look.

**Comment by springcoil** [comment]
Do we close this issue?

**Comment by twiecki** [comment]
No, this would still be great to have.

**Comment by ferrine** [comment]
odo looks really cool

**Comment by ColCarroll** [comment]
Closing for age. Feel free to reopen if you want to work on it.
