### ISSUE TITLE
BUG: new progressar adds empty spaces when progressbar=False

### ISSUE THREAD

**Issue by velochy** [pymc-devs/pymc#7264]
### Describe the issue:

As I need to sample the posterior on a very large sample of 1M rows, I have batched the operation and run it in groups of 10k
To monitor the progress, I put a tqdm progress bar on the bach loop. 

This used to behave as expected, but since 5.13.1 this produces the following:
![image](https://github.com/pymc-devs/pymc/assets/5527789/3c559874-a09e-438d-a778-54ba69ba3bdd)

### Reproduceable code example:

```python
import pymc as pm

# Define and sample any model you like into idata

from tqdm import tqdm
with model:   
    for i in tqdm(list(range(10))):
        pm.sample_posterior_predictive(
                    idata,
                    progressbar=False,
                )
```

### PyMC version information:

5.13.1

**Comment by ricardoV94** [comment]
@tomicapretto reports this is not yet fixed
