### ISSUE TITLE
Include minimal pymc example in README

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7267]
### Description

We don't have any

**Comment by HarshvirSandhu** [comment]
I would like to work on this.
@ricardoV94 Is there any specific example you would like to suggest?

**Comment by ricardoV94** [comment]
I cooked up a small example showing the most interesting functionality (imo) here: https://colab.research.google.com/drive/1JyIeu2NMl_z6Y8ZniZn3jDrzzUL3i81q?usp=sharing

**Comment by twiecki** [comment]
@ricardoV94 I like showing the workflow, just not sure what the example is about.

**Comment by ricardoV94** [comment]
> @ricardoV94 I like showing the workflow, just not sure what the example is about.

It's a fake example of linear regression.

**Comment by twiecki** [comment]
but you're using physics terms.

**Comment by ricardoV94** [comment]
> but you're using physics terms.

Didn't want to go down the foo bar route

**Comment by kiramclean** [comment]
This issue can be closed now after merging #7358. Thanks for the opportunity to contribute! Looking forward to learning more about PyMC.

**Comment by twiecki** [comment]
thanks everyone!
