### ISSUE TITLE
New progressbar doesn't show elapsed time

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7269]
### Description

This was really neat in the old progressbar, we would get ETA/Elapsed, now we only get ETA (or Elapsed?). Can we have both? 

CC @fonnesbeck @rob

**Comment by fonnesbeck** [comment]
I was using the percentage as elapsed and the time as ETA. Can certainly add more metrics if we want, but was trying to keep it simple.

**Comment by ricardoV94** [comment]
Percentage doesn't tell you if your run took 1 minute or 2 hours to get to 50% (useful for long sampling when coming back)
