### ISSUE TITLE
First time congratulatory message images are huge

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7323]
### Description

https://raw.githubusercontent.com/pymc-devs/brand/main/welcome-bot/BannerCongratulations.jpg
https://raw.githubusercontent.com/pymc-devs/brand/main/welcome-bot/BannerThanks.jpg

I don't think we need 3634*1930 pixels to say congrats

**Comment by twiecki** [comment]
You're probably right.

**Comment by markgreene74** [comment]
Hi! I just had a quick go at it with ImageMagick.

```
$ identify BannerCongratulations*
BannerCongratulations.jpg JPEG 3634x1930 3634x1930+0+0 8-bit sRGB 466734B 0.000u 0:00.000
BannerCongratulations_resized_1815.jpg JPEG 1815x964 1815x964+0+0 8-bit sRGB 155276B 0.000u 0:00.000
BannerCongratulations_resized_910.jpg JPEG 910x483 910x483+0+0 8-bit sRGB 65279B 0.000u 0:00.000
```

```
$ identify BannerThanks*
BannerThanks.jpg JPEG 3634x1930 3634x1930+0+0 8-bit sRGB 637049B 0.000u 0:00.000
BannerThanks_resized_1815.jpg JPEG 1815x964 1815x964+0+0 8-bit sRGB 206000B 0.000u 0:00.000
BannerThanks_resized_910.jpg JPEG 910x483 910x483+0+0 8-bit sRGB 79989B 0.000u 0:00.000
```

I did the resize on the width and let ImageMagick figure out the rest. Not sure if you have a strong preference between 1815 or 910 or have another size in mind, but if you let me know I am happy to raise a PR in `pymc-devs/brand`. In my opinion 910x483 is more than enough.

I think it would be just easier to make the change in a single place (replace the older, bigger image with the new, smaller one but keep the filename) unless you want to keep the original and the resized images with a suffix in the name.

Examples of different sizes (right-click and open in a new tab):
910
![BannerCongratulations_resized_910](https://github.com/pymc-devs/pymc/assets/18945890/55a6a734-19c7-4464-ba8a-5097ed7e0049)

1815
![BannerCongratulations_resized_1815](https://github.com/pymc-devs/pymc/assets/18945890/5f0b4636-8f9b-400c-a45c-89d8b3a3eca0)

And finally, the code :smile: 
```
convert -resize 1815x BannerCongratulations.jpg -quality 90 BannerCongratulations_resized_1815.jpg
```

**Comment by markgreene74** [comment]
I would also like to suggest to apply the same changes to `BannerWelcome.jpg`, which has a similar size at the moment.

**Comment by ricardoV94** [comment]
Thanks @markgreene74 yes the smaller size and both pictures make sense!

**Comment by markgreene74** [comment]
hi @ricardoV94 just want to be sure I understand correctly :smile: 

> both pictures make sense!

So keep both pictures (the original and the resized version) in `pymc-devs/brand` and make changes to `config.yml` so that the resized version is used from now on?

**Comment by ricardoV94** [comment]
I don't think we need to keep the original, it exists elsewhere?

**Comment by markgreene74** [comment]
> I don't think we need to keep the original, it exists elsewhere?

Sorry, I wasn't sure which way you preferred :smile: I will make the changes to https://github.com/pymc-devs/brand/pull/29 now and close #7394

**Comment by reshamas** [comment]
@ricardoV94 Is the larger image size impacting CI/CD or other items?

If yes, this will help to know because these images are used in various other GitHub organizations.

**Comment by markgreene74** [comment]
As https://github.com/pymc-devs/brand/pull/29 has been merged I think this issue can be closed now? I just had a quick look at one of the PRs using the banners and the new size looks ok.

**Comment by ricardoV94** [comment]
> @ricardoV94 Is the larger image size impacting CI/CD or other items?
> 
> If yes, this will help to know because these images are used in various other GitHub organizations.

I don't think it impacts CI/CD. It could impact email storage, if the pictures are actually sent, but I think only the link. It mostly bothered me because it was rather large when scrolling through issues
