### ISSUE TITLE
DOC: Plots squished in the documentation page

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#7325]
### Issue with current documentation:

Here is an example 
https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/model_comparison.html

![squished-image](https://github.com/pymc-devs/pymc/assets/162124795/51df0f2c-408a-4cd6-9dd2-11eb6502efa8)

### Idea or request for content:

Similar to https://github.com/pymc-labs/pymc-marketing/issues/666

**Comment by hevansDev** [comment]
Taking a look at this today @ PyData 2024 Hackathon

**Comment by hevansDev** [comment]
Fixed by https://github.com/pymc-devs/pymc/pull/7356, this issue can now be closed 😄
