### ISSUE TITLE
DOC: conflicting `fixed_params` type-hint in `find_constrained_prior` 

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#7341]
### Issue with current documentation:

The [find_contrained_prior](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.find_constrained_prior.html) documentation page has "[str](https://docs.python.org/3/library/stdtypes.html#str) or [float](https://docs.python.org/3/library/functions.html#float), optional, default [None](https://docs.python.org/3/library/constants.html#None)" in the docstring type hint but dict[str, float] in the examples and function signature

### Idea or request for content:

Consolidate to the correct type hint. I believe it is dict[str, float]

**Comment by ricardoV94** [comment]
The docstring about only when there are more than 2 params to optimize also seems wrong. Perhaps something that was true in earlier iterations but is no longer?

**Comment by wd60622** [comment]
Closing as the function is being deprecated
