### ISSUE TITLE
PyMC3 slowness

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#739]
For some kinds of sampling PyMC3 seems to be substantially slower than PyMC2, which is probably something we should fix. 

Thoughts on what the source is?

**Comment by jsalvatier** [comment]
From profiling it seems like a lot of time is spent in theano.function.**call** in overhead stuff. I wonder if we can eliminate some of that. https://groups.google.com/forum/#!topic/theano-users/T-WmOxO1uts

**Comment by jsalvatier** [comment]
@fonnesbeck 
When it works, setting `func.trust_inputs=True` and using `*args` instead of `**kwargs` is about 100% faster for smallish Metropolis problems and about 15% faster for NUTS (not sure why is not most of a speedup for NUTS). See this branch: https://github.com/pymc-devs/pymc3/tree/fast

We can probably figure out how to make this work in general.

Also, it looks to me like we might be able to get a speedup by combining the calculation `energy(q0) - energy(q1)` in `buildtree`.

**Comment by twiecki** [comment]
That's really neat. Does 100% bring us back up to pymc2 speed?

**Comment by jsalvatier** [comment]
No, I don't think it does still.

**Comment by twiecki** [comment]
We'll take it nonetheless :).

**Comment by jsalvatier** [comment]
Okay, in NUTS I combined the leapfrog step and the energy computation which lead to a %100 speedup.

I also combined the logp difference in metropolis and got another nice speedup.

I have the theano functions now taking a single array argument of all the combined parameters instead of the wrapping them. This seems to be a bit faster, though currently internally in Theano this uses theano.Split.perform which is in python, and so kind of slow. But hopefully I can get theano to make this into C for a nice speedup.

Also now I'm using shared variables for values not being updated.

**Comment by twiecki** [comment]
That's awesome!

**Comment by jsalvatier** [comment]
Split.perform takes up about 50% of theano time on some problems, so a C implementation would probably speed up things substantially. Its probably not very difficult code, but I don't have time for it right now. I would love it if someone else took a look at how to do that.

I made a Theano issue [here](https://github.com/Theano/Theano/issues/3039).

**Comment by springcoil** [comment]
What is there for this that needs done? Do we have a breakdown of tasks?

**Comment by twiecki** [comment]
Probably the theano devs can help with a c-implementation of split.

**Comment by nouiz** [comment]
Just an update that now in the master of Theano split have C code on the CPU and new GPU back-end.

If someone have time to redo the timing, it would be great.

**Comment by ColCarroll** [comment]
I actually ran this on a very naive benchmark -- just sampling from a normal distribution, so mostly testing the overhead of running the model.  No performance changes stood out, but there was a warning thrown from theano (will need to change the Dockerfile, I guess?):
```
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
```

I may try with a more realistic model later.

100k samples from a normal distribution
NUTS: 3,104 -> 3,045it/s
HMC: 2,634 -> 2,777it/s
Metropolis: 9,128 -> 7,208it/s
Slice: 2,457 -> 2,020it/s

**Comment by twiecki** [comment]
@ColCarroll I think the Split comes in from joining inputs so probably biggest speed-up is for models with many RVs.

**Comment by fonnesbeck** [comment]
This thread appears to have outlived its usefulness. We have benchmarking in place now.
