### ISSUE TITLE
MAP assignment fails when using Python 3 

### ISSUE THREAD

**Issue by bpajusco** [pymc-devs/pymc#741]
I've tried to run some basic notebooks with Pymc3 using Python 3 kernel but it fails with the following error message: 

``` python
---------------------------------------------------------------------------
PositiveDefiniteError                     Traceback (most recent call last)
<ipython-input-12-88df1243ac2f> in <module>()
      3 with Model() as pooled_model:
      4     glm.glm('log_radon ~ floor', srrs_mn)
----> 5     pooled_trace = sample(1000, NUTS())

/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/nuts.py in __init__(self, vars, scaling, step_scale, is_cov, state, Emax, target_accept, gamma, k, t0, model, **kwargs)
     67 
     68 
---> 69         self.potential = quad_potential(scaling, is_cov, as_cov=False)
     70 
     71         if state is None:

/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/quadpotential.py in quad_potential(C, is_cov, as_cov)
     33         return QuadPotential_SparseInv(C)
     34 
---> 35     partial_check_positive_definite(C)
     36     if C.ndim == 1:
     37         if is_cov != as_cov:

/usr/local/lib/python3.4/dist-packages/pymc3/step_methods/quadpotential.py in partial_check_positive_definite(C)
     56     if len(i):
     57         raise PositiveDefiniteError(
---> 58             "Simple check failed. Diagonal contains negatives", i)
     59 
     60 

PositiveDefiniteError: Scaling is not positive definite. Simple check failed. Diagonal contains negatives. Check indexes [0 1 2]
```

Interestingly, it fails on every possible notebook I've tried to run and it breaks on finding the MAP assignment for a linear regression model. This particular report was taken from Chris Fonnesbeck radon example but it keeps happening every time I call glm and looks like it's failing when finding a MAP assignment.

The problem only happens if I use Python 3 as a kernel and everything works fine when I use Python 2. Is there something obviously wrong in my setup that I should correct? For completeness, I'm using anaconda as Python distribution and I have built pymc3 using pip install.

**Comment by twiecki** [comment]
Weird. So all `glm` models fail on python 3 but not on 2 with the same error? Do other, non-glm models work as expected?

**Comment by bpajusco** [comment]
I haven't checked non glm models but I strongly suspect it's an issue 
with MAP and not glm per se, since all glm does is building a regression 
model. I can try to build the same model by hand and see if it fails but 
I'm pretty confident it will.

It could be some weird conflict between Python 3 and 2 interpreters in 
Anaconda and I have really no idea. It could entirely be that this isn't 
a pymc3 bug but more of a setup issue, although I don't know what could 
cause it as I can use Python 2 and 3 interpreters with most other 
libraries without much trouble.

**Comment by twiecki** [comment]
Definitely try it with the simplest model possible as that will help debug the problem.

**Comment by bpajusco** [comment]
Using the explicit approach worked and I managed to get the code to run 
through. Here is what I run instead of making the call to glm and using 
patsy based x ~ y

with pm.Model() as model:

```
 alpha = pm.Normal('alpha', mu=0, sd=20)
 beta = pm.Normal('beta', mu=0, sd=20)
 sigma = pm.Uniform('sigma', lower=0, upper=20)


 y_est = alpha + beta * x


 likelihood = pm.Normal('y', mu=y_est, sd=sigma, observed=y)


 start = pm.find_MAP()
 step = pm.NUTS(state=start)
 trace = pm.sample(2000, step, start=start, progressbar=True)
```

Looks like MAP works after all but I don't understand what could be 
failing in glm.

**Comment by twiecki** [comment]
Can you delete your `~/.theano`?

**Comment by bpajusco** [comment]
I've done that but the problem is still there. Incidentally, what 
difference does make clearing the Theano cache?

**Comment by jsalvatier** [comment]
Can you post the notebook you're using? Also, have you looked at the test point your glm model (`print(pooled_model.test_point)`)? Maybe that's starting off in a really weird spot.

**Comment by jsalvatier** [comment]
What kind of error is MAP giving you?

**Comment by fonnesbeck** [comment]
@bpajusco Is this still an issue?

**Comment by bpajusco** [comment]
No. This stopped happening once I went nuclear and completely re-installed anaconda and the various Python libraries. We can close it now and thanks for your help.
