### ISSUE TITLE
Include README example in docs homepage

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7411]
### Description

https://github.com/pymc-devs/pymc?tab=readme-ov-file#linear-regression-example

⬇️

https://www.pymc.io/projects/docs/en/stable/learn.html

**Comment by KKartikay-27** [comment]
I would like to work on this issue !!

**Comment by UtkershBasnet** [comment]
I would like to resolve this issue please assign it to me

**Comment by pradyutf** [comment]
Hi, @ricardoV94 

I would like to work on the issue. Could you please clarify where you would like the README example to be placed? Should it be in the top list, or under one of the Beginner, Intermediate, or Advanced sections?

I want to ensure I place the example in the right section. Thank you for your guidance!

**Comment by ricardoV94** [comment]
@pradyutf it seems like @UtkershBasnet has shown interest in this issue. Unless @UtkershBasnet is no longer interested / does not respond I would let him take the initiative here. 

For where it should go, perhaps @OriolAbril or @twiecki have a more precise idea than I do

**Comment by twiecki** [comment]
Hmm, not sure where to best place it. Perhaps before https://www.pymc.io/projects/docs/en/stable/learn/core_notebooks/pymc_overview.html#case-study-1-educational-outcomes-for-hearing-impaired-children ?

**Comment by pradyutf** [comment]
Hi @UtkershBasnet, would you be willing to collaborate on this?

**Comment by UtkershBasnet** [comment]
@pradyutf Sure

**Comment by Adityajaiswal03** [comment]
hi @ricardoV94  i would like to solve this issue

**Comment by twiecki** [comment]
> hi @ricardoV94 i would like to solve this issue

Great, just open a (draft) PR.
