### ISSUE TITLE
DOC: Slightly more clarification about the expected target value indexing of pymc.OrderedLogistic

### ISSUE THREAD

**Issue by Mithrillion** [pymc-devs/pymc#7422]
### Issue with current documentation:

While it is possible to deduce that OrderedLogistic expects the observed values to have the typical 0-based indexing as in regular Python, based on the documentation's example:
`y = np.concatenate((1*np.ones(n1_c),
                    2*np.ones(n2_c),
                    3*np.ones(n3_c))) - 1`
the initial line of the documentation `Useful for regression on ordinal data values whose values range from 1 to K as a function of some predictor...` makes it seem like the encoding should be "1,2,3,...K". This can be confusing for users, as this can result in `logp=-inf` error, which does not intuitively trace back to the source of the error here.

### Idea or request for content:

Make it clearer that the target values ("observed") should be 0-based, like in regular Python. Similar change could also be made for OrderedProbit.

**Comment by ricardoV94** [comment]
Sounds good @Mithrillion , wanna push a fix?

**Comment by androemeda** [comment]
@ricardoV94 please assign it to me , i would like to fix it

**Comment by charanbhatia** [comment]
@Mithrillion  can you assign this issue to me?

**Comment by kdotmanoj** [comment]
@Mithrillion  @ricardoV94  Could you please review PR #7457  related to the issue?
