### ISSUE TITLE
BUG: Broken Links in MLDA Intro Page

### ISSUE THREAD

**Issue by dakshkanaujia** [pymc-devs/pymc#7441]
### Describe the issue:

Notebook title: MLDA sampler: Introduction and resources
Notebook url: https://www.pymc.io/projects/examples/en/latest/samplers/MLDA_introduction.html
I ran the Notebook url through a dead link checker and found two broken links. 
### List of Broken Links

| Status         | URL                                                                                                                           | Source Link Text                  |
|----------------|-------------------------------------------------------------------------------------------------------------------------------|-----------------------------------|
| 404 Not Found  | [https://github.com/alan-turing-institute/pymc/blob/mlda_all_notebooks/docs/source/notebooks/MLDA_benchmarks_tuning.ipynb](https://github.com/alan-turing-institute/pymc/blob/mlda_all_notebooks/docs/source/notebooks/MLDA_benchmarks_tuning.ipynb) | Benchmarks and tuning             |
| 404 Not Found  | [https://github.com/alan-turing-institute/pymc/blob/mlda_all_notebooks/docs/source/notebooks/MLDA_adaptive_error_model.ipynb](https://github.com/alan-turing-institute/pymc/blob/mlda_all_notebooks/docs/source/notebooks/MLDA_adaptive_error_model.ipynb) | Adaptive error model              |

### Suggested Actions

1. *Update Links*: Some hyperlinks need to be updated to point to the correct resources.
2. *Review and Correct Broken Links*: Others may be pointing to entities or resources that no longer exist and need to be reviewed for relevance or replacement.

### PyMC version information:

pymc 5.16.2 (conda)

**Comment by Jash2606** [comment]
Hi @cluhmann,
I’ve addressed the broken links mentioned in the issue and submitted a PR with the fixes. Could you please review it ?
 If there are any other links that need updating or if additional changes are needed, please let me know.

**Comment by Jash2606** [comment]
Hey @jessegrabowski  @OriolAbril ,

Could you please review the PR and merge it?

**Comment by cluhmann** [comment]
Where is the PR?
