### ISSUE TITLE
pm.autocorrplot does not work for multidimensional stochastics

### ISSUE THREAD

**Issue by aflaxman** [pymc-devs/pymc#746]
Here is a minimal example demonstrating how this works currently:

```
import pymc3 as pm
with pm.Model() as model:
    x = pm.Normal('x', shape=1)
    tr = pm.sample(10000, step=pm.Metropolis())[5000::5]

pm.autocorrplot(tr)
```

![image](https://cloud.githubusercontent.com/assets/51236/8026578/1701d556-0d31-11e5-9920-838b3c0c5eac.png)

Beautiful.  But if the RV has shape=2, this doesn't work:

```
with pm.Model() as model:
    x = pm.Normal('x', shape=2)
    tr = pm.sample(10000, step=pm.Metropolis())[5000::5]

pm.autocorrplot(tr)
```

raises exception `ValueError: object too deep for desired array`.

What should it do in this case?

**Comment by jsalvatier** [comment]
Probably we want to just plot several plots on top of eachother.

**Comment by aloctavodia** [comment]
Closing as this is now fixed.
