### ISSUE TITLE
`pm.sample` parameter to exclude deterministics

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc#7461]
With the `pm.compute_deterministics` function, the deterministic variables can be computed after the sampling. What is the easiest way to exclude them from the sampling to begin with? Can there be an option in the `pm.sample` to exclude? Or some clear helper to return all the variable names that are not deterministics and would be part of the posterior?

```python
import pymc as pm
import numpy as np

nrows = 10
ncols = 2
X = np.ones((nrows, ncols))

coords = {
    "id": np.arange(nrows),
    "covariates": np.arange(ncols),
}
with pm.Model(coords=coords) as model:
    X_ = pm.Data("X", X, dims=("id", "covariates"))
    beta = pm.Normal("beta", mu=0, sigma=1, dims=("covariates",))
    mu = pm.Deterministic("mu", pm.math.dot(X_, beta), dims="id")
    sigma = pm.Gamma("sigma", mu=1, sigma=0.25)

    y = pm.Normal("y", mu=mu, sigma=sigma, observed=np.random.randn(nrows))

# Left to user ???
variables_to_exclude = model.deterministics + model.potentials + model.observed_RVs
variables_to_exclude = [var.name for var in variables_to_exclude]
variables_to_sample = [var.name for var in model.unobserved_RVs if var.name not in variables_to_exclude]

with model:
    idata = pm.sample(var_names=variables_to_sample)
```

**Comment by cluhmann** [comment]
[`pm.sample()`](https://www.pymc.io/projects/docs/en/stable/api/generated/pymc.sample.html) does have an argument (i.e., `var_names`) that specifics parameters **to include** in the trace.  So the inverse of what you are asking for.  Does [this question/answer](https://discourse.pymc.io/t/compute-deterministics-and-var-names-argument-to-sample/14452) help?

**Comment by wd60622** [comment]
> [`pm.sample()`](https://www.pymc.io/projects/docs/en/stable/api/generated/pymc.sample.html) does have an argument (i.e., `var_names`) that specifics parameters **to include** in the trace. So the inverse of what you are asking for. Does [this question/answer](https://discourse.pymc.io/t/compute-deterministics-and-var-names-argument-to-sample/14452) help?

Yeah, perfect. 

I guess the workflow I'd like is just: 
```python
var_names = [var.name for var in model.free_RVs]
with model:
    idata = pm.sample(var_names=var_names)

# Later
with model:
    idata.posterior = pm.compute_deterministics(idata.posterior, merge_dataset=True)
```

Is `free_RVs` subject to change? That's makes me wonder if a parameter is justified

**Comment by cluhmann** [comment]
> Is `free_RVs` subject to change or always exhaustive?

Can you say more about what you mean by change/exhaustive?

**Comment by ricardoV94** [comment]
@wd60622 your snippet should be fine yes. If that makes you happy we can close the issue

**Comment by wd60622** [comment]
Thanks @cluhmann and @ricardoV94 
Will close the issue then!
