### ISSUE TITLE
Error serializing function

### ISSUE THREAD

**Issue by wcbeard** [pymc-devs/pymc#748]
I tried replicating the BPMF script [here](https://gist.github.com/macks22/00a17b1d374dfc267a9a) and got the error

```
Traceback (most recent call last):
  File "bpmf.py", line 271, in <module>
    trace = pm.sample(nsamples, step, start=start, njobs=njobs)
  File "/Users/me/src/pymc3/pymc3/sampling.py", line 88, in sample
    return sample_func(*sample_args)
  File "/Users/me/src/pymc3/pymc3/sampling.py", line 209, in _mp_sample
    traces = p.map(argsample, args)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<MultiTrace: 1 chains, 3 iterations, 8 variables>]'. Reason: 'PicklingError("Can't pickle <type 'function'>: attribute lookup __builtin__.function failed",)'
```

The error appears to start at 1000373 (but not at the previous commit e0b8ab5). It looks like multiprocessing is somehow trying to serialize the lambda introduced [here](https://github.com/pymc-devs/pymc3/commit/1000373045f96c8eb7354d2a1f00d74674ea6d95#diff-67266bdcac8375424a06b8684806c301R32) which throws the error.

**Comment by fonnesbeck** [comment]
Can you confirm that the model works when you set `njobs=1`? If so, you can try updating Theano to the master branch:

```
pip install -U git+git://github.com/Theano/Theano.git
```

**Comment by wcbeard** [comment]
Yes, it works both at 1000373 and latest with `njobs = 1`

**Comment by fonnesbeck** [comment]
Great. Does updating Theano fix the serialization problem for you?

**Comment by wcbeard** [comment]
No, doesn't look like it. Just updated theano to

```
In [4]: theano.version.git_revision
Out[4]: '83dadc9d65d8d6f037978697129e457e213fe8fc'
```

and still get the error

**Comment by ColCarroll** [comment]
Closed from inactivity.
