### ISSUE TITLE
Latex`_` in variable names is not properly escaped

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc#7495]
https://github.com/pymc-devs/pymc/blob/d596afbe266ae1bdafec6735d73a82885e06dea1/pymc/printing.py#L261

Having this issue for years but did not pay much attention to it

<img width="783" alt="image" src="https://github.com/user-attachments/assets/3a9e42c8-f33b-42e8-839a-d21cfe0a928a">

**Comment by ricardoV94** [comment]
There's an old open PR that was fixing it

**Comment by ricardoV94** [comment]
#6533

**Comment by Dekermanjian** [comment]
Hey, I believe that this is now fixed in #7501
