### ISSUE TITLE
Theano/NumPy throws LinAlgException

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#751]
As Chris brought up, when you have matrix operations, especially matrix inverses, theano can throw LinAlgException. For example, he has an issue with [this model](http://nbviewer.ipython.org/gist/fonnesbeck/ac400c96e1d4c9014662).

[Theano just wraps numpy's `inv` function](https://github.com/Theano/Theano/blob/master/theano/tensor/nlinalg.py), which is where the LinAlgException comes from. There's some Theano discussion [here](https://groups.google.com/forum/#!topic/theano-dev/B3K8_CR8TmM). This behavior messes up `find_MAP` and the step methods. 

Options we have are:
- wrap our calls to theano in find_MAP/step methods in a try/catch and deal with the error there.  
- temporarily set numpy.seterr to just put NaN's instead of raising an error.
- other things

(as an aside, it might be nice to have nan's created during model creation to raise errors by default, but then not raise errors during sampling/optimization).

**Comment by springcoil** [comment]
Is this still an issue?

**Comment by junpenglao** [comment]
I think theano is improved on this end, closing for now.
