### ISSUE TITLE
Module 'pymc3' has no attribute 'model'

### ISSUE THREAD

**Issue by Seymagocmez** [pymc-devs/pymc#7511]
### Description

I have a similar issue that has been reported before and I couldn't find a way around it. 

`def compute_MCMC_results(draws=3000, tune=1000):
    with pm.Model():
        b0 = pm.Uniform('b0', 0, 50)
        A = pm.Uniform('A', 0, 50)
        T = pm.Uniform('T', 0, 100)
        log_alpha = pm.Uniform('log_alpha', -10, 10)`

` with pm.Model():
         ^^^^^^^^
AttributeError: module 'pymc3' has no attribute 'Model'`

**Comment by aloctavodia** [comment]
PyMC3 is no longer mantained. Please update to the latest version of  PyMC.

https://www.pymc.io/projects/docs/en/latest/installation.html
