### ISSUE TITLE
Flaky `tests/gp/test_gp.py::TestMarginalVsLatent::testLatentMultioutput`

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc#7531]
### Description

Probably needs a seed or more forgiving error tolerance.

Seen it fail multiple times. Most recently: https://github.com/pymc-devs/pymc/actions/runs/11252379757/job/31285375154?pr=7473

CC @bwengals @AlexAndorra

**Comment by bwengals** [comment]
Yeah must be flaky, but the error difference looks a bit large too.  Will take a look

**Comment by AlexAndorra** [comment]
Thanks for the ping Ricardo! Happy to help too -- LMK if you need anything
Bill
