### ISSUE TITLE
Howto question: Creating a model where intermediate variables have data

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc#755]
I'm sorry again for bothering everybody here, I hope this is the right place to post a question about this, and that I'm not asking something too elementary.

If I have a model that is specified as such:

```
with Model() as model:
    p_overlap = Beta('p_overlap', 1, 9)
    p_rpc = Beta('p_rpc', 1, 9)

    n_overlaps = Binomial('num_overlaps', 50, p_overlap)
    p_reassort = ProbReassort('prob_reassort', n_overlaps, p_rpc, testval=0.1)

    n_reassortants = Bernoulli('num_reassortants', p_reassort, observed=num_reassortants)
```

As you can see, `n_reassortants` is something for which I have observable data. I can perform the inferences needed, and everything is good.

On the other hand, I also have data for `n_overlaps`. PyMC3 doesn't allow me to specify that `n_overlaps` is observed, because it would throw an error. 

In this particular case, would anybody have advice on how I should specify the model correctly? Again, I'm sorry if this is the wrong place, I am happy to repost elsewhere if the package maintainers feel it's better there instead.

If it helps, the model re-specified as a generative model is as such (using `numpy`):

```
p_overlap = 0.1 # simulated - prior should be Beta or Uniform 0,1
num_overlaps = np.random.binomial(50, p_overlap, size=1E6) # number of overlaps
p_rpc = 0.01 # simulated probability of reassortment for per overlap cell - should be Beta or Uniform 0,1
p_reassort = (1 - (1 - p_rpc) ** num_overlaps) # probability of reassortment over all cells.
num_reassortants = np.random.binomial(1, p_reassort) # effectively a Bernoulli distribution
```

**Comment by fonnesbeck** [comment]
I don't see why it should generate an error for being observed. What is the error exactly? Also, what is ProbReassort? Is it a custom stochastic you have defined elsewhere?

**Comment by ericmjl** [comment]
Thanks for responding, @fonnesbeck! My apologies for not responding earlier.

I've defined ProbReassort as the following custom `Continuous` stochastic:

```
import theano.tensor as T
class ProbReassort(Continuous):
    def __init__(self, m, p, *args, **kwargs):
        super(ProbReassort, self).__init__(*args, **kwargs)
        self.m = m
        self.p = p

    def logp(self, value):
        m = self.m
        p = self.p
        return T.log(1 - (1 - p)**m)
```

I have used `theano`'s function as I get a `theano` error when using `numpy`'s `log` function. Thread is here: https://github.com/pymc-devs/pymc3/issues/754#issuecomment-112580454

The error message I get is as follows:

```
TypeError: unsupported operand type(s) for ** or pow(): 'TensorVariable' and 'ObservedRV'
```

On the other hand, if I specify that `n_overlaps` is not observed, the error message goes away.

**Comment by fonnesbeck** [comment]
Are you using a build from the current master branch? This may have been resolved when @jsalvatier added missing value support. Can you confirm, John?

**Comment by ericmjl** [comment]
Hmm... after installing the latest version of the master branch, I re-ran and the error indeed went away.

I also realized I may have been setting up the model incorrectly, which gave me weird results (traces were single-valued). This was my own inexperience and lack of care in setting up the model. 

Thanks @fonnesbeck for the help! Shall I close the thread?

**Comment by fonnesbeck** [comment]
Glad this fixed it.
