### ISSUE TITLE
Combine trace values by default?

### ISSUE THREAD

**Issue by kyleam** [pymc-devs/pymc#759]
There are three ways to get sampling values for a variable from a
trace.
1.  `trace[variable]`
2.  `trace.variable`
3.  `trace.get_values(variable)`

Currently, all of these return a list of arrays, where each array
belongs to a chain.  (However, if there is only one chain, an array,
not a list of arrays, is returned by default.)  The last method,
`get_values`, has a keyword argument, `combine`, that will concatenate
values from all chains into one array.

As I mentioned in #758, I'd like to make the the methods above return
a combined array by default, leaving the individual chain values to be
accessed by setting the `combine` argument of `get_values` to `False`.
I prefer this as the default because I think that, particularly for
interactive use, it's convenient to be able to treat a trace the same
regardless of the number of chains, without having to rely on the more
verbose `get_values`.

Thoughts?

**Comment by jsalvatier** [comment]
Yes, I think it is more common to want the combined values than the
separated values.

**Comment by jsalvatier** [comment]
Would simplify the use of seaborg's violinplot as here: 
https://github.com/pymc-devs/pymc3/issues/752#issuecomment-111981596

This is the use case I've run into most often, wanting to plot traces and for that you usually want them combined.
