### ISSUE TITLE
PyMC3 extra variables, and issues with theano?

### ISSUE THREAD

**Issue by FedericoV** [pymc-devs/pymc#772]
Hi,

Inspired by one of @twiecki's notebooks, I tried using PyMC3 to fit a hierarchical linear model to some data with categorical variables.  I used emcee first, which I'm quite familiar with, and got some reasonable results - then tried porting the code directly to PyMC3 and got a few weird issues.

First issue:

``` python
with pm.Model() as individual_model:
    # Slope prior
    b = pm.Normal('beta', mu=0, sd=10)

    # Model error prior
    eps = pm.Uniform('eps', lower = 0, upper = 2)

    # Linear model
    enrich_est = b * del_cells

    # Data likelihood
    enrich_like = pm.Normal('enrich_like', mu=enrich_est, sd=eps, observed=tip_fluorescence)

    # Inference button (TM)!
    step = pm.NUTS()
    trace = pm.sample(2000, step=step, progressbar=False)
```

In my case, del_cells is a boolean vector, that is only equal to one when a particular treatment is present.

Plotting the trace, I don't just get posterior distributions for b and eps, but an additional variable called 'eps_interval' which I don't quite understand. 

The second problem that I get is this:  I get a bunch of warnings from theano about:

ValueError: Cannot construct a ufunc with more than 32 operands (requested number were: inputs = 34 and outputs = 1)

I presume this is a theano specific issue - and seems to be related to theano falling back in pure python mode if it cannot find a compiler.  I'll investigate it separately.

Final issue, is that running the code above in a loop seems to give a huge memory leak.  My memory consumption increases massively over time.. I'm guessing maybe some of the implicit symbolic variables are not being cleaned up properly?

Addendum:
I'm using the bleeding edge versions of numpy, pymc3, and theano.

**Comment by fonnesbeck** [comment]
Easy answer for the `eps_inteval` question: PyMC transforms the constrained parameter to an unconstrained space to improve sampling, so there is a transformed and non-transformed version of the variable. This may be something we want to hide, as it will confuse users.

**Comment by FedericoV** [comment]
That makes sense, thank you.

Any tips on how to investigate the memory leak?  For reference, the snippet I pasted above is run within a triple loop (over gs, GFP, and deletion) and I've noticed a huge increase in memory consumption over the iteration.  When trying it with emcee, I have absolutely no problems and memory usage stays flat.

My intuition is that it might be some symbolic variables that are not getting properly cleaned up - I've tried directly importing the gc module, and forcing collections at every iteration but that didn't help.

**Comment by jsalvatier** [comment]
The memory leak is with creating many models rather than the `sample` loop, right?
I wonder if we're keeping a reference to the model somehow. Very curious about this memory leak. Would you try installing `memory_profiler` and doing `%mprun` in IPython notebook (ipython notebook is super nice for profiling). Instructions [here](http://pynash.org/2013/03/06/timing-and-profiling.html). I would love to see the output.

**Comment by FedericoV** [comment]
I added a little code snippet to my loop:

```
mem_usage = []
GFPs = ['tea1', 'pom1', 'tea3', 'sts5', 'tip1']
deletions = ['tea1', 'pom1', 'tea3', 'sts5', 'tip1']
growth_stages = ['U', 'B', 'S']

GFPs = full_dataframe.GFP.unique()
deletions = full_dataframe.Deletion.unique()

for gfp in GFPs:
    gfp_df = full_dataframe[full_dataframe.GFP == gfp]

    for gs in growth_stages:
        gs_df = gfp_df[gfp_df['class'] == gs]

        for deletion in deletions:

            if deletion == gfp:
                continue

            wt_cells = (gs_df.Deletion == 'none').values.astype(int)
            del_cells = (gs_df.Deletion == deletion).values.astype(int)

            tip_fluorescence = gs_df['x.greenAvgFluor_corr'].values

            # substract mean of WT:
            tip_fluorescence -= tip_fluorescence[wt_cells].mean()

            with pm.Model() as individual_model:
                # Slope prior
                b = pm.Normal('beta', mu=0, sd=5)

                # Model error prior
                eps = pm.Uniform('eps', lower = 0, upper = 2)

                # Linear model
                enrich_est = b * del_cells

                # Data likelihood
                enrich_like = pm.Normal('enrich_like', mu=enrich_est, sd=eps, observed=tip_fluorescence)

                # Inference button (TM)!
                step = pm.NUTS()
                trace = pm.sample(2000, step=step, progressbar=False)

            mem_string = process.get_memory_info()[0] / float(2 ** 20)  
            mem_usage.append(mem_string)
```

And after a few iterations, the memory usage looks like this:

```

[910.01171875, 937.85546875, 975.8125, 1008.375, 1037.546875, 1062.4296875, 1086.375, 1123.25, 1156.43359375, 1177.125, 1229.640625, 1240.875, 1282.07421875, 1299.375, 1343.55859375, 1357.30859375, 1409.875, 1417.625, 1463.0703125, 1497.9921875, 1498.2265625, 1545.65234375, 1583.0078125, 1584.52734375, 1637.2265625, 1699.64453125, 1700.50390625, 1746.1640625, 1833.91015625, 1884.453125, 1884.64453125, 1942.24609375, 2030.1953125, 2079.98828125, 2080.2109375, 2131.90234375, 2219.8515625, 2307.7109375, 2305.33984375, 2316.08984375, 2397.43359375, 2485.29296875, 2573.39453125, 2568.9609375, 2568.9609375, 2632.81640625, 2720.76171875, 2808.765625, 2848.7421875, 2848.81640625, 2848.81640625, 2915.26171875, 3001.3515625, 3087.64453125, 3173.99609375, 3154.5703125, 3154.80078125, 3184.30078125, 3268.6796875, 3354.86328125, 3440.17578125, 3525.24609375, 3506.01171875, 3506.16796875, 3521.609375, 3595.6171875, 3682.1640625, 3769.07421875, 3855.703125, 3894.84765625, 3894.84765625, 3894.94140625, 3907.67578125, 3979.59765625, 4066.3828125, 4153.1015625, 4239.83984375, 4321.671875, 4319.82421875, 4319.85546875, 4319.85546875, 4339.7421875, 4413.26171875, 4498.28125, 4583.29296875, 4668.4375, 4753.53125, 4839.46875, 4813.21484375, 4813.21875, 4813.21875, 4819.84765625, 4884.828125, 4972.234375, 5059.75, 5147.24609375, 5234.72265625, 5322.25, 5350.98828125, 5350.98828125, 5350.98828125, 5350.98828125, 5357.34375, 5415.8125, 5503.25, 5590.6953125, 5678.16796875, 5765.68359375, 5853.20703125, 5940.60546875, 5951.80078125, 5954.8046875, 5954.8046875, 5954.96484375, 5954.96484375, 5990.65625, 6059.95703125, 6142.59765625, 6225.125, 6308.03125, 6390.8203125, 6473.54296875, 6556.3125, 6639.0234375, 6635.80078125, 6635.80078125, 6635.80078125, 6635.80078125]
```

So it's clearly holding a reference to some data somewhere.  I have memory profiler installed, and I can try to dig into it further as soon as I have a bit more time.

**Comment by jsalvatier** [comment]
The only thing I can think of is that its holding a copy of the logp functions which will have a copy of your observed data, which seems like it could be bad. Do you have a lot of observations? If you don't do the sampling, do you see the same increase? How about if you don't attach the observations?

**Comment by nouiz** [comment]
We merged the fix in Theano about the problem here.

**Comment by twiecki** [comment]
Thanks @nouiz!
