### ISSUE TITLE
NUTS sampler gets 'stuck' for very long periods

### ISSUE THREAD

**Issue by FedericoV** [pymc-devs/pymc#776]
Hi!

Sorry to keep opening issues - but just noticed this:

Working on a hierarchical model, again very similar to the standard model described by Thomas Wiecki:

``` python
        with pm.Model() as hierarchical_model:
            mu_b = pm.Normal('mu_beta', mu=0., sd=100**2)
            sigma_b = pm.Uniform('sigma_beta', lower=0, upper=100)

            b = pm.Normal('beta', mu=mu_b, sd=sigma_b, shape=3)

            # Model error prior
            eps = pm.Uniform('eps', lower = 0, upper = 2)

            # Linear model
            enrich_est = b[gs_code] * del_idx
            # Check to make sure this is right.

            # Data likelihood
            enrich_like = pm.Normal('enrich_like', mu=enrich_est, sd=eps, observed=tip_fluorescence)

        with hierarchical_model:
            start = pm.find_MAP()
            step = pm.NUTS(scaling=start)
            hierarchical_trace = pm.sample(2000, step, start=start, progressbar=True)
```

After a few looops, that mostly took this timing:

```
[-----------------100%-----------------] 2001 of 2000 complete in 63.5 sec
```

It's currently stuck like so:

```
 [-                 3%                  ] 62 of 2000 complete in 11487.3 sec
```

I suspect this is largely because of this line:

```
 b[gs_code] * del_idx
```

del_idx is a boolean array of length n, while gs_code is an array with 3 possible values (0, 1, 2), and the values are quite imbalanced:

``` python
print ((gs_code == 0) * del_idx).sum()
print ((gs_code == 1) * del_idx).sum()
print ((gs_code == 2) * del_idx).sum()
print len(gs_code)
104
16
38
4925
```

I also had to simplify the model quite a bit, because when I was fitting an alpha term independently (as in the original Wiecki notebook) the iteration times were incredibly long.  So I just did some independent mean centering for each condition as a pre-processing step - which is of course far less precise.

``` python
        for gs in [0, 1, 2]:
            wt_and_gs_code = np.logical_and(wt_idx, gs_code == gs)
            # Get cells that are wild type and in a specific growth stage
            m = tip_fluorescence[wt_and_gs_code].mean()
            # Get mean of wild type population in a specific growth stage
            tip_fluorescence[gs_code == gs] -= m
            # Substract mean from all cells in a specific growth stage
```

**Comment by jsalvatier** [comment]
This is actually quite useful for us. Any chance you could post the full model and data somewhere? I would love to be able to dig into this and optimize the slow parts. I suspect that if NUTS goes from fast to slow, that it has begun to make very large trees, which we can probably fix some way.

**Comment by FedericoV** [comment]
I'd be happy too - I'm currently running the other model (the one that ran out of memory) in a loop over night on my workstation to see where exactly is the leak.

I do not know how reproducible that 'frozen' state actually is though.

**Comment by jsalvatier** [comment]
Great, let me know when you're able to post the model/data, and I'll take a look.

**Comment by FedericoV** [comment]
I sent you an e-mail with the subset of the data.

**Comment by jsalvatier** [comment]
Thanks :)

**Comment by jwjohnson314** [comment]
I'm having the same issue, also on a model similar to that described above. My data are pretty well balanced.

**Comment by twiecki** [comment]
Any data/NB to reproduce the problem?

**Comment by FedericoV** [comment]
I had e-mailed the data to John as soon as he asked for it, but didn't hear
back.  In the meanwhile, I had reformulated the problem to use emcee, and
it worked fine there.

I also ran into a limitation of the pymc3 API I could not work around, so
emcee worked well.  Should I open a different ticket for that?

**Comment by twiecki** [comment]
@FedericoV sure. Can you send me the data as well? firstname.lastname@gmail.com

**Comment by twiecki** [comment]
I think this is related to the model being close to undetermined. You place a hyperprior on the three beta coefficients which is not a whole lot to infer mu and sd for them. Here is an example the illustrates the problem:

``` python
import pymc3 as pm

with pm.Model():
    mu = pm.Normal('mu', 0, 1)
    sd = pm.HalfCauchy('sd', 1)
    obs = pm.Normal('obs', mu=mu, sd=sd, observed=[0.1, -0.1])

    start = pm.find_MAP()
    step = pm.NUTS(scaling=start)
    trace = pm.sample(2000, step, start=start)
```

![image](https://cloud.githubusercontent.com/assets/674200/11036473/0941bc28-86f9-11e5-8368-f8f2387b309c.png)

Now I'm not sure whether this is a bug or a property of the posterior space which is just extremely flat.

In any case, if I remove the hyperprior in your model it converges just fine. If I keep the hyperprior but sample using Metropolis and then using the last sample as the starting point for NUTS it also works well (although there are some convergence instabilities).

@jwjohnson314 How many coefficients are in your hierarchical model?

**Comment by jwjohnson314** [comment]
68 - it's a hierarchical model similar to the radon model with varying
intercept and slope terms, over 34 different sets of observations.

**Comment by twiecki** [comment]
Have you tried sampling with Metropolis or Slice?

**Comment by jwjohnson314** [comment]
No. I'll give it a go a let you know how it does.

**Comment by springcoil** [comment]
Was this error resolved - maybe we could add it to some sort of user guide - or just add a warning somewhere.

**Comment by twiecki** [comment]
With the new init (https://github.com/pymc-devs/pymc3/pull/1523) and some model tweaks this works pretty well:
![image](https://cloud.githubusercontent.com/assets/674200/20435889/1dedfc22-adae-11e6-8f14-10543fc69867.png)
