### ISSUE TITLE
Random variates via pymc3

### ISSUE THREAD

**Issue by drapadubok** [pymc-devs/pymc#777]
In pymc2 it was possible to pull out random variates from stochastic variables, but I'm not sure I can find similar behavior in the pymc3. Is it possible? The reason why I'm asking, is that I use to pull out random variates from scipy.stats now, but sometimes the way distributions are parametrized in pymc3 are different from default way in scipy.stats, and I felt like it would have been very nice to just get them out from the model in pymc3.

One thing I tried was to just run sampler without any likelihood function defined, am I right to assume that in such case I just get random variates? I need this to visualize priors, to get better grip on whether I understand correctly what kind of prior I'm about to have.

Here is the example, I basically want to show how the priors for my priors and hyperpriors would look like:

``` python
with pymc3.Model() as hierarchical_model:
    # define the group hyperparameters
    k_minus_two1 = pymc3.Gamma('k_minus_two1', alpha=s, beta=r)
    k1 = pymc3.Deterministic('k1', k_minus_two1 + 2)
    w1 = pymc3.Beta('w1', alpha=1, beta=1)

    k_minus_two2 = pymc3.Gamma('k_minus_two2', alpha=s, beta=r)
    k2 = pymc3.Deterministic('k2', k_minus_two2 + 2)
    w2 = pymc3.Beta('w2', alpha=1, beta=1)    

    # define the prior for group, want to tie story specific theta to it's group theta
    theta1 = pymc3.Beta('theta1', alpha=(w1 * k_minus_two1) + 1, beta=((1-w1)*k_minus_two1)+1)
    theta2 = pymc3.Beta('theta2', alpha=(w2 * k_minus_two2) + 1, beta=((1-w2)*k_minus_two2)+1)

    # Generate a MCMC chain
    step = pymc3.Metropolis() # Instantiate MCMC sampling algorithm
    trace = pymc3.sample(10000, step, njobs=1, progressbar=True) 
```

**Comment by jsalvatier** [comment]
Yup, if you don't have any data you'll just get the priors. 

@fonnesbeck, do we have any plans to make the random variables more accessible? 

I'm also hoping to add a nice way to just plot the PDF for different variables, but not sure what would be a nice interface. Thoughts?

**Comment by twiecki** [comment]
I wrote some hacky code once to print the pdf of the priors of the model, it figured out the support etc. I'll try to dig it up.

We also still have https://github.com/pymc-devs/pymc3/pull/442 which is pretty close I think.

**Comment by twiecki** [comment]
but something like `RV.plot(xlim=(0, 2))` could also be nice.

**Comment by fonnesbeck** [comment]
We now have `random` methods in most distributions, so I will go ahead and close this.
