### ISSUE TITLE
AssertionError with theano

### ISSUE THREAD

**Issue by hadim** [pymc-devs/pymc#778]
I am trying to port the first pymc2 example from the book "Bayesian Methods for Hackers" to pymc3 but I have the following error:

``` python
count_data = np.loadtxt("/home/hadim/txtdata.csv")

@theano.compile.ops.as_op(itypes=[t.dscalar, t.dscalar, t.dscalar], otypes=[t.dvector])
def lambda_(tau, lambda_1, lambda_2):
    out = np.zeros(n_count_data)
    out[:tau] = lambda_1  # lambda before tau is lambda1
    out[tau:] = lambda_2  # lambda after (and including) tau is lambda2
    return True

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)

    observation = pm.Poisson("observation", mu=lambda_(tau, lambda_1, lambda_2), observed=count_data)
```

```

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-47-33fca4e63eeb> in <module>()
     17     tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)
     18 
---> 19     observation = pm.Poisson("observation", mu=lambda_(tau, lambda_1, lambda_2), observed=count_data)

/home/hadim/local/conda/envs/st/lib/python3.4/site-packages/theano/gof/op.py in __call__(self, *inputs, **kwargs)
    505         """
    506         return_list = kwargs.pop('return_list', False)
--> 507         node = self.make_node(*inputs, **kwargs)
    508 
    509         if config.compute_test_value != 'off':

/home/hadim/local/conda/envs/st/lib/python3.4/site-packages/theano/compile/ops.py in make_node(self, *inputs)
    487     def make_node(self, *inputs):
    488         assert len(inputs) == len(self.itypes)
--> 489         assert all(inp.type == it for inp, it in zip(inputs, self.itypes))
    490         return theano.Apply(self, inputs, [o() for o in self.otypes])
    491 

AssertionError: 
```

Any idea ?

**Comment by twiecki** [comment]
Not sure what the error is about, but the model seems similar to the disaster model which can be done in full theano: https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/disaster_model.py#L41

**Comment by hadim** [comment]
Thank you ! 

The code now works (but I can't get the same results as in the book... :-()

``` python
count_data = np.loadtxt("/home/hadim/txtdata.csv")

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=len(count_data))

    days = np.zeros(len(count_data))
    lambda_ = pm.switch(tau >= days, lambda_1, lambda_2)

    observation = pm.Poisson("observation", mu=lambda_, observed=count_data)

with model:
    step = pm.NUTS()
    trace = pm.sample(10000, step)
```

**Comment by twiecki** [comment]
@hadim how different is it?

**Comment by hadim** [comment]
In the book λ1 is around 18 and λ2 is around 23 and tau is near 45 while my code returns λ1 is around 18 and λ2 is around 23 and `tau.mean() == 37`, `lambda_1.mean() == 19.7` and `lambda_2.mean() == 20.4`.

They use this code to do the learning step:

``` python
# Mysterious code to be explained in Chapter 3.
mcmc = pm.MCMC(model)
mcmc.sample(40000, 10000, 1)
```

**Comment by jsalvatier** [comment]
Ah, the issue is that NUTS ignores non-continuous variables, so tau isn't being sampled. If you also sample with metropolis, it should work. 

The original issue is that you were returning true instead of 'out', I think.

**Comment by jsalvatier** [comment]
We should add a warning when a user isn't sampling all variables.

**Comment by hadim** [comment]
+1 it works !!! Thank you :-)

Indeed a warning will be really helpfull for this kind of subtlety.

**Comment by hadim** [comment]
@jsalvatier about the original issue the `True` returned is  copy/paste mistake from me (I was doing some tests). I confirm the original code (with `return out`) raise an `AssertionError`.

**Comment by jsalvatier** [comment]
oh, hmm. The other issue I see is that itypes asks for a double as first argument, but you pass an int. The error here is terrible though. Would you mind making an [Theano issue](https://github.com/Theano/Theano/issues/new) so they fix that? That error is really uninformative.

**Comment by hadim** [comment]
I will.

**Comment by jsalvatier** [comment]
Much appreciated :)

**Comment by hadim** [comment]
You are correct it was a Theano type issue : 

``` python
count_data = np.loadtxt("/home/hadim/txtdata.csv")

@theano.compile.ops.as_op(itypes=[t.lscalar, t.dscalar, t.dscalar], otypes=[t.dvector])
def lambda_(tau, lambda_1, lambda_2):
    out = np.zeros(n_count_data)
    out[:tau] = lambda_1  # lambda before tau is lambda1
    out[tau:] = lambda_2  # lambda after (and including) tau is lambda2
    return out

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)

    print(tau.dtype, t.lscalar)
    print(lambda_1.dtype, t.dscalar)
    print(lambda_2.dtype, t.dscalar)

    observation = pm.Poisson("observation", mu=lambda_(tau, lambda_1, lambda_2), observed=count_data)
```

```
int64 TensorType(int64, scalar)
float64 TensorType(float64, scalar)
float64 TensorType(float64, scalar)
```

Using `t.lscalar` for `tau` make it work.

**Comment by hadim** [comment]
One other comment guys (ask if you want me to open a new issue) : 

These two code should do the same thing, however the second one (using `@theano.compile.ops.as_op`) give the same results as the [Bayesian Methods for Hackers book](http://nbviewer.ipython.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Chapter1.ipynb#Interpretation) while the first one (with `pm.switch()`) give wrong results.

Any idea ?

``` python
count_data = np.loadtxt("/home/hadim/txtdata.csv")

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=len(count_data))

    days = np.zeros(len(count_data))
    lambda_ = pm.switch(tau >= days, lambda_1, lambda_2)

    observation = pm.Poisson("observation", mu=lambda_, observed=count_data)

    step = pm.Metropolis()
    trace = pm.sample(50000, step)

print()
print("tau", trace['tau'].mean())
print("lambda_1", trace['lambda_1'].mean())
print("lambda_2", trace['lambda_2'].mean())
```

```
 [-----------------100%-----------------] 50000 of 50000 complete in 19.9 sec
tau 37.2129
lambda_1 19.745322838
lambda_2 19.8655585532
```

And

``` python
count_data = np.loadtxt("/home/hadim/txtdata.csv")

@theano.compile.ops.as_op(itypes=[t.lscalar, t.dscalar, t.dscalar], otypes=[t.dvector])
def lambda_(tau, lambda_1, lambda_2):
    out = np.zeros(n_count_data)
    out[:tau] = lambda_1  # lambda before tau is lambda1
    out[tau:] = lambda_2  # lambda after (and including) tau is lambda2
    return out

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)

    observation = pm.Poisson("observation", mu=lambda_(tau, lambda_1, lambda_2), observed=count_data)

    step = pm.Metropolis()
    trace = pm.sample(50000, step)

print()
print("tau", trace['tau'].mean())
print("lambda_1", trace['lambda_1'].mean())
print("lambda_2", trace['lambda_2'].mean())
```

```
[-----------------100%-----------------] 50000 of 50000 complete in 20.7 sec
44.29046
17.7463592118
22.7000483893
```

**Comment by jsalvatier** [comment]
Not sure, I would try `traceplot(trace)` and see if there's something obviously wrong.

**Comment by hadim** [comment]
I should have post it before.

I am very new in bayesian statistics but I don't see anything wrong in the first traceplot comparing to the second one.

With `pm.switch` : 

![figure_1](https://cloud.githubusercontent.com/assets/528003/8363788/a33984a2-1b81-11e5-9dab-b19cf0e8da49.png)

With `@theano.compile.ops.as_op` : 

![figure_2](https://cloud.githubusercontent.com/assets/528003/8363796/bb86ef72-1b81-11e5-95c5-4264655a2d2c.png)

**Comment by hadim** [comment]
Except maybe that `tau` and `lambda_2` variability is bigger in the first traceplot.

**Comment by jsalvatier** [comment]
Ahh, yes, the issue with `tau` is definitely it. The issue seems to be that `days = np.zeros(len(count_data))` is wrong. It should be `days =np.arange(len(count_data))`. Days is the index of the day.

**Comment by hadim** [comment]
Ahahah nice catch @jsalvatier ! You were correct :-) I didn't know how exactly `pm.switch()` was working.

Thanks for all the help.

**Comment by fangqx** [comment]
I have a concern about the function "lambda" and the sampling processes. When multiple samples are produced, the function of lambda will be called multiple times. Under this condition, if i have a complex model which will ran for several minutes, how can I call the function of lambda (or my model) for each sample separately? It looks the sampling process finished first and my model are still running. I want to ran the model with each sample set separately. Thanks

`You are correct it was a Theano type issue :

count_data = np.loadtxt("/home/hadim/txtdata.csv")

@theano.compile.ops.as_op(itypes=[t.lscalar, t.dscalar, t.dscalar], otypes=[t.dvector])
def lambda_(tau, lambda_1, lambda_2):
    out = np.zeros(n_count_data)
    out[:tau] = lambda_1  # lambda before tau is lambda1
    out[tau:] = lambda_2  # lambda after (and including) tau is lambda2
    return out

alpha = 1.0 / count_data.mean()  # Recall count_data is the variable that holds our txt counts

with pm.Model() as model:

    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)

    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data)

    print(tau.dtype, t.lscalar)
    print(lambda_1.dtype, t.dscalar)
    print(lambda_2.dtype, t.dscalar)

    observation = pm.Poisson("observation", mu=lambda_(tau, lambda_1, lambda_2), observed=count_data)`
