### ISSUE TITLE
Error in Dirichlet creation

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#780]
I'm working on moving some of my PyMC2 models over to PyMC3, and I am running into an issue with creating a Dirichlet in PyMC3. 

Here is a post I did with the version 2 model: https://phaethonprime.wordpress.com/2015/06/25/bayesian-modeling-with-pymc-dirichlet-and-a-custom-stochastic/

In creating the new model, I wanted to get up to speed with pymc3 with a simple Dirichlet-Multinomial model on test data. I started with a Dirichlet with k = 6, and setting all the alphas to 1/2. 

```
model = Model()
with model:
     probs = Dirichlet("probs",a=np.array([1/2]*6))
```

This is the issue I get back:

TypeError: For compute_test_value, one input test value does not have the requested type.
The error when converting the test value to that variable type: Wrong number of dimensions: expected 0, got 1 with shape (6L,).

I then tried various Theano vectors (including constants, but I will admit I have no experience with Theano at all) and got the same error each time. When I do the constant, I have:

```
import theano.tensor as T 
model = Model()
with model:
     probs = Dirichlet("probs",a=T.constant(np.array([1/2]*6)))
```

Is the error with me, or something with the code? Thank you in advance.

**Comment by twiecki** [comment]
I think you are creating an int vector. Can you just do .5 instead of 1/2.

**Comment by ghost** [comment]
I get the same error if I try 0.5. I'm in Python 2, and I use `from __future__ import division` as well.

**Comment by jsalvatier** [comment]
Not sure why this would be happening, but try setting `shape=6` in `Dirichlet("probs",a=T.constant(np.array([1/2]*6)), shape=6)`.

Do you have an old version?

**Comment by ghost** [comment]
Setting the shape parameter got the model to build without an error, thank you! I'll get to the rest of the model later.

I'm using: PyMC3 3.0b (June 16th, 2015)

My machine is a Windows 7 64 bit AMD, with 64-bit Python 2.7.6. When I need to, I build libraries with MinGW64.

**Comment by jibietr** [comment]
Hi, I get  the same error when trying to create a one dimensional dirichlet. 

    with pm.Model() as model:   
        pi = pm.Dirichlet("pi", a=np.ones(1), shape=1)

**Comment by fonnesbeck** [comment]
What you have tried to do here is create a Dirichlet with one element (which doesn't make sense for a multivariate distribution). The smallest viable model you could build would be:

```
with pm.Model() as model:   
    pi = pm.Dirichlet("pi", a=np.ones(2))
```
