### ISSUE TITLE
sample() hangs for Multinomial model with more than one observation

### ISSUE THREAD

**Issue by dlinzer** [pymc-devs/pymc#781]
Hi,

I'm having a great time with pymc3 so far, but am running into an issue with a basic Dirichlet-Multinomial model.  Here's a setup with fake data:

```
import numpy as np
from pymc3 import *
sample_size = 1
n = 1000
true_probs = [0.2, 0.1, 0.3, 0.4]
k = len(true_probs)
y = np.random.multinomial(n, true_probs, sample_size)
```

The model works fine as long as `sample_size = 1`.

```
multinom_test = Model()

with multinom_test:
    probs = Dirichlet('probs', a = np.array([0.5] * k), shape = k)
    data = Multinomial('data',
                        n = np.reshape(y.sum(1), (sample_size, 1)),
                        p = probs,
                        observed = y)

with multinom_test:
    trace = sample(5000, Slice())

trace[probs].mean(0)
```

But if I set `sample_size = 2` or greater, the `sample()` command hangs. Breaking out of `sample()` in the notebook shows the error:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-12-bcebb63a4efc> in <module>()
      1 with multinom_test:
----> 2     trace = sample(5000, Slice())

/Users/Drew/PythonEnvs/tracker/lib/python2.7/site-packages/pymc3/sampling.pyc in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
     86         sample_args = [draws, step, start, trace, chain,
     87                        tune, progressbar, model, random_seed]
---> 88     return sample_func(*sample_args)
     89 
     90 

/Users/Drew/PythonEnvs/tracker/lib/python2.7/site-packages/pymc3/sampling.pyc in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
     99                 progress.update(i)
    100     except KeyboardInterrupt:
--> 101         strace.close()
    102     return MultiTrace([strace])
    103 

UnboundLocalError: local variable 'strace' referenced before assignment
```

Any thoughts on what's happening here?  Thanks in advance for your help.

**Comment by fonnesbeck** [comment]
Yes, this is related to #535 which we have yet to resolve. Some design issues at play here.

**Comment by dlinzer** [comment]
Got it. It makes sense to me that the input data `y` would be formatted as a list of lists, like

```
array([[24, 14, 27, 35],
       [17,  5, 36, 42],
       [23, 11, 33, 33],
       [22, 11, 32, 35],
       [18,  6, 32, 44],
       [26,  9, 31, 34],
       [19, 11, 28, 42],
       [15, 10, 37, 38],
       [18, 12, 27, 43],
       [17, 14, 32, 37]])
```

So that the first element `y[0]` corresponds to the first vector of observed outcomes over `n = 100` trials, `array([24, 14, 27, 35])`.  Thanks again for the fantastic software.

**Comment by dlinzer** [comment]
In the meantime, this seems to be an effective work-around:

```
with multinom_test:
    probs = Dirichlet('probs', a = np.array([0.5] * k), shape = k)
    for i in range(sample_size):
        data = Multinomial('data',
                           n = y[i].sum(),
                           p = probs,
                           observed = y[i])
```

**Comment by ghost** [comment]
I'm confused as to your use case. If you only have one prior, why do you need several rows of observations? If all the observations are drawn according to the Dirichlet, couldn't you just combine them into one row?

For example:

```
with multinom_test:
    probs = Dirichlet('probs', a = np.array([0.5] * k), shape = k)
    data = Multinomial('data',
                       n = y.sum(),
                       p = probs,
                       observed = y.sum(axis=0))
```

**Comment by dlinzer** [comment]
That's true, but my application is actually slightly more complex than the code I pasted.  I was trying to simplify the issue I was encountering down to its core.

**Comment by christacular** [comment]
Thanks dlinzer, I was stuck on the same thing and your code was very helpful.  Here is a slight modification that prevents an error from reusing the 'data' variable on each loop:

```
with multinom_test:

    probs = Dirichlet('probs', a = np.array([0.5] * k), shape = k)
    for i in range(sample_size):
        data = Multinomial('data_%d' % (i),
                           n = y[i].sum(),
                           p = probs,
                           observed = y[i])

```

**Comment by fonnesbeck** [comment]
We need to fix this before the release. We should not need to loop over the data like this. /cc @twiecki @springcoil

**Comment by springcoil** [comment]
Yeah agreed - any suggestions on how to fix this though - I'm a bit stumped...

**Comment by twiecki** [comment]
FWIW this seems to work fine with Metropolis (but to wrong values), Slice is in an infinity loop, and NUTS samples but never accepts a jump.

I bet we can change the likelihood to do smart broadcasting just like with MvNormal.

**Comment by fonnesbeck** [comment]
Please test. Works fine for me with either `Metropolis` or `Slice`, but `NUTS` returns a positive definite error -- simplex issues?
