### ISSUE TITLE
Weighting observed data with standard deviation of measurement 

### ISSUE THREAD

**Issue by hadim** [pymc-devs/pymc#782]
Is that possible to feed `pymc3` with uncertainity of observed data (like the standard deviation for example) ?

A more detailed question here : https://stats.stackexchange.com/questions/159768/weighting-observed-data-with-standard-deviation-of-measurement-in-bayesian-model

**Comment by fonnesbeck** [comment]
Just specify the empirical standard deviation directly in the sampling distribution of the observations. For example:

```
s = 5 # known SD of obsevations
y = Normal('y', mu, s**-2, shape=n)
```

mu of course may also be known or unknown, or modeled.
