### ISSUE TITLE
Arbitrary deterministic cannot be used as intermediate node 

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#788]
The arbitrary deterministic decorator `theano.compile.ops.as_op` is very handy for wrapping a function as a PyMC deterministic, but it appears that such nodes cannot be used as arguments in subsequent nodes. When I try to do so, I get messages like the following (where `Iw` is the arbitrary deterministic):

```
AsTensorError: ('Cannot convert FromFunctionOp{Iw} to TensorType', <class 'theano.compile.ops.FromFunctionOp'>)
```

Can we wrap this object further so that it can be used in non-terminal graph nodes?

**Comment by jsalvatier** [comment]
It seems to me that you're trying to use the result of as_op() directly. However, as_op, returns a function not a tensor! I'm not quite sure how best to resolve this. Seems sticky, not quite sure what to do.

**Comment by fonnesbeck** [comment]
Do we need to re-wrap the function output as a Tensor? I was using the `as_op` to avoid having to use `scan` for a node that requires a nested loop.

**Comment by jsalvatier** [comment]
No, I think what's going on is this. Are you doing something like this?

```
@deterministic(...)
def mything(a, b): 
   return ...

x = mything + 1
```

This would cause the error above and the solution would be to do this instead

```
@deterministic(...)
def mything(a, b): 
   return ... 

x = mything(a,b) + 1
```

Can you post your example?

**Comment by aloctavodia** [comment]
Closing as this is no longer an issue.
