### ISSUE TITLE
Indexing problem when using SQLite backend

### ISSUE THREAD

**Issue by DeliciousHair** [pymc-devs/pymc#790]
Hello!

Not quite sure how to describe this, so I'll just go with an example to demonstrate, specifically the intro model from the tutorial page.

<pre><code>
import numpy as np
from pymc3 import *
from scipy import optimize

np.random.seed(123)
alpha, sigma = 1, 1
beta = [1, 2.5]
size = 100

X1 = np.linspace(0, 1, size)
X2 = np.linspace(0,.2, size)
Y = alpha + beta[0]*X1 + beta[1]*X2 + np.random.randn(size)*sigma

basic_model = Model()

with basic_model:
    alpha = Normal('alpha', mu=0, sd=10)
    beta = Normal('beta', mu=0, sd=10, shape=2)
    sigma = HalfNormal('sigma', sd=1)
    mu = alpha + beta[0]*X1 + beta[1]*X2

    Y_obs = Normal('Y_obs', mu=mu, sd=sigma, observed=Y)

    start = find_MAP(fmin=optimize.fmin_powell)
    step = NUTS(scaling=start)
    backend = backends.SQLite('demo_sampling.sqlite')
    trace = sample(500, step, start=start, trace=backend)
</code></pre>

This works fine.  The problem arises when I try to use the <code>traceplot</code> method with some indexing:

<pre><code>
In [17]: traceplot(trace[500::5])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-4e39ad6300c4> in <module>()
----> 1 traceplot(trace[500::5])

/usr/local/lib/python2.7/dist-packages/pymc3/backends/base.pyc in __getitem__(self, idx)
    159     def __getitem__(self, idx):
    160         if isinstance(idx, slice):
--> 161             return self._slice(idx)
    162 
    163         try:

/usr/local/lib/python2.7/dist-packages/pymc3/backends/base.pyc in _slice(self, idx)
    215         """Return a new MultiTrace object sliced according to `idx`."""
    216         new_traces = [trace._slice(idx) for trace in self._traces.values()]
--> 217         return MultiTrace(new_traces)
    218 
    219     def point(self, idx, chain=None):

/usr/local/lib/python2.7/dist-packages/pymc3/backends/base.pyc in __init__(self, traces)
    140         self._traces = {}
    141         for trace in traces:
--> 142             if trace.chain in self._traces:
    143                 raise ValueError("Chains are not unique.")
    144             self._traces[trace.chain] = trace

AttributeError: 'NoneType' object has no attribute 'chain'
</code></pre>

Clearly, there is something wrong with how the traces are being read --<code>traces</code> not being passed to <code>MultiTraces</code> or something perhaps? But I cannot seem to figure this out as calling <traceplots> like this when using the default RAM backend works fine.  Any ideas where I might want to look?

**Comment by twiecki** [comment]
Thanks for reporting. @kyleam any ideas?

**Comment by kyleam** [comment]
Thanks.  The SQLite backend doesn't support slicing (there should be a
warning before the error you reported), so the output should have been
checked for Nones.  I've pushed a commit that does this, but that
doesn't make your snippet work (instead you are now going to be passing
a None to traceplot).  For that, I've opened a PR that allows SQLite and
Text to be sliced.

**Comment by DeliciousHair** [comment]
Thanks @kyleam, that makes perfect sense! Digging through <code>backends/sqlite.py</code> I see this is indeed mentioned, ~~but I would also mention that I did not receive the warning message you alluded to~~. Will check out your PR to see how this fix works :-)
