### ISSUE TITLE
Break out MCMC plotting library?

### ISSUE THREAD

**Issue by ariddell** [pymc-devs/pymc#793]
Just testing the waters to see if there's interest in breaking out some common code for dealing with MCMC samples into independent packages. For example, R has [coda](https://cran.r-project.org/web/packages/coda/index.html) which brings together a lot of common routines.

Code for plotting MCMC samples seems like a good candidate for being placed in a separate library for a couple of reasons that I'd be happy to go into.

I also wonder if one couldn't standardize on some of the conventions used by seaborn. (Creating this issue was occasioned by seeing @twiecki's comment on seaborn, https://github.com/mwaskom/seaborn/pull/643#issuecomment-125160428)

**Comment by twiecki** [comment]
I'm generally in favor of trying to standardize across  packages and plotting seems like a good place for that. We also talked about leveraging seaborn at one point. Would certainly simplify our code. In any case, for this to be successful we probably need community support from pystan and the likes. Aren't you involved?

**Comment by ariddell** [comment]
Yes. If there were a common plotting library, PyStan would use it.

**Comment by twiecki** [comment]
Did you have a look at the code we have? What do you think of the API?

**Comment by fonnesbeck** [comment]
I think this is a good idea, in general. It should also be pretty straightforward, as we are probably just talking about a function library here. @ariddell are you going to be at JSM next month?

**Comment by ariddell** [comment]
@twiecki For plotting, I'm happy with the current API (although I know so little matplotlib that I'm probably not the right person to ask). Standardizing on seaborn conventions (or using seaborn routines), to the extent that that's possible, seems like a good thing.

@fonnesbeck I'm not going to be there, but there will be Stan folks there. I take it you'll be there?

**Comment by twiecki** [comment]
@ariddell Does `pystan` have any plotting capabilities?

**Comment by ariddell** [comment]
Not really. PyStan borrows an old version of traceplot from pymc but I'm not sure how much it's used.

**Comment by PaulSorenson** [comment]
I am not familiar with coda but over at https://github.com/aloctavodia/Doing_bayesian_data_analysis the examples replicate plots in Kruschke which might be helpful.

**Comment by ariddell** [comment]
Thanks, the Kruschke plots would be great to look at.

Perhaps an initial step would be to just try breaking out the existing pymc plotting routines into a separate library (`mcmcplotlib`?) and then seeing if there are places to borrow things from seaborn? I don't have time to work on this in the near term but I think I will in a month or two.

**Comment by twiecki** [comment]
I like the name and I think that's a good path forward.

**Comment by aloctavodia** [comment]
I also like the name and I will be happy to help. Probably this is the excuse I need to resume porting the examples in Kruschke (and cleaning the code) :-)

**Comment by twiecki** [comment]
@aloctavodia Thanks for chiming in and offering help. Lots of people are quite excited about your Kruschke port :).

Should we host this under the `pymc-devs` org or create a new one?

**Comment by twiecki** [comment]
https://github.com/mcmcplotlib/mcmcplotlib You should all be invited.

**Comment by yasminlucero** [comment]
I would like to add a related, but distinct request to this thread. Would you consider adding the goal to remove matplotlib as a dependency of pymc3? Perhaps the plotting functionality can be completely refactored into the plotting library.

I am using pymc3 in a production environment as part of a training service. The training service will not ever make plots, because that kind of work would always be done in a different environment. However, currently we need to install matplotlib every time we stand up a new training environment (nightly). It is a heavy dependency with lots of potential for issues. For example, I put a hack into place to make the back end install properly on my os x laptop during dev. This is a hassle for functionality that isn't actually required for my service.

I assume there are others out there who would prefer a lighter dependency for deployment reasons.

Thanks in advance for your consideration.

**Comment by ColCarroll** [comment]
Hey -- that's a reasonable suggestion.  I moved the discussion over to https://discourse.pymc.io/t/issue-break-out-mcmc-plotting-library/299 along with a possible path forward that might be easier to maintain and solve your problem

**Comment by fonnesbeck** [comment]
After some discussion today, we've decided to make matplotlib an optional dependency, which should solve this issue. We will add exceptions when plots are called without having matplotlib installed.

**Comment by twiecki** [comment]
Closed by arviz.
