### ISSUE TITLE
TypeError thrown when running Occupancy Estimation example in tutorial

### ISSUE THREAD

**Issue by rjchacko** [pymc-devs/pymc#794]
I got the following error while trying to follow along with the Occupancy Estimation section of the tutorial. I was using the latest master as of yesterday.:

```
TypeError: expected type_num 7 (NPY_INT64) got 0
Apply node that caused the error: Elemwise{ge,no_inplace}(z_shared, TensorConstant{(1,) of 0})
Inputs types: [TensorType(int64, vector), TensorType(int8, (True,))]
Inputs shapes: [(100,), (1,)]
Inputs strides: [(1,), (1,)]
Inputs values: ['not shown', array([0], dtype=int8)]

Backtrace when the node is created:
File "/usr/local/lib/python2.7/site-packages/pymc3/distributions/discrete.py", line 122, in logp
value >= 0, value <= 1,

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of  this apply node.
```

Here's the code from the tutorial. The error gets thrown on the sample step.:

```
from pymc3 import Beta, Bernoulli, ZeroInflatedPoisson, Uniform, Poisson
from pymc3 import Metropolis, BinaryMetropolis, sample

y = np.array([0, 2, 1, 0, 4, 2, 0, 0, 4, 0, 0, 0, 0, 0, 3, 0, 0, 6, 0, 0, 0, 2, 1,
   2, 0, 0, 0, 1, 0, 0, 0, 4, 2, 0, 0, 0, 1, 0, 2, 4, 0, 0, 1, 0, 0, 0,
   0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0,
   0, 0, 3, 0, 2, 0, 1, 2, 2, 2, 2, 3, 0, 0, 0, 0, 1, 0, 3, 1, 0, 0, 0,
   0, 0, 2, 0, 0, 1, 0, 0])

with Model() as zip_model:
    p = Beta('p', 1, 1)
    z = Bernoulli('z', p, shape=y.shape)
    theta = Uniform('theta', 0, 100)
    yd = ZeroInflatedPoisson('y', theta, z, observed=y)

with zip_model:
    start = {'p': 0.5, 'z': (y > 0), 'theta': 5, 'yd_missing': np.array([1, 1])}
    step1 = Metropolis([theta, p])
    step2 = BinaryMetropolis([z])
    trace = sample(10000, [step1, step2], start)
```

**Comment by jsalvatier** [comment]
I've replicated this.

**Comment by jsalvatier** [comment]
The issue seems to be with Metropolis and the difference between int8 and int64. This is a new problem because we now don't check and cast the input types as much.

I think [this](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/metropolis.py#L111) is the problem area. 

Perhaps we can split things into different type buckets? 

Also, I would expect the quick fix of `z = Bernoulli('z', p, shape=y.shape, dtype='int64')` to work, but it does not appear to.

**Comment by fonnesbeck** [comment]
We definitely want to avoid users having to specify types. Can we cast all ints to int64 unless explicitly overridden?

**Comment by twiecki** [comment]
+1 on automatic int (and float) casting.

**Comment by ajrichards** [comment]
I believe that the error still throws if you copy and paste directly from the documentation.  It might be helpful to know that the [latent_occupancy.py script on github](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/latent_occupancy.py) does not throw the error.  The difference is that start is specified as follows in the script.

```
start = {'p': 0.5, 'z': (y > 0).astype(int), 'theta': 5}
```
