### ISSUE TITLE
understanding shape parameter in for random variables

### ISSUE THREAD

**Issue by lfiaschi** [pymc-devs/pymc#796]
I have a problem understanding the shape parameter in pymc3.

I would like to create a betabinomial model for modeling clicks and impressions of users in online advertisement. An exaplenation of the model can be found in the central part of this paper:

http://www.cs.cmu.edu/~deepay/mywww/papers/kdd07-estimating.pdf 

As a toy example I generate some data according to this distribution:

```
ndata=100
nclusters=1
K=np.random.randint(0,nclusters,ndata)
ALPHA = [.5]
BETAS = [.5]
IMPS = np.random.randint(1,100,ndata)
RATES=list()
CLICKS=list()

for k,i in zip(K,IMPS):

    p=np.random.beta(ALPHA[k],BETAS[k])
    c=np.random.binomial(i,p)
    RATES.append(p)
    CLICKS.append(c)
```

when I train the model assigning explicitly one variable for each user I get estimates for the the posterior rates which are consistent with the true values and the empirical values:

```
with pm.Model() as model:
    for ind_ in range(len(CLICKS)):
        rate = pm.Beta('rate_{}'.format(ind_),0.5,0.5)
        C = pm.Binomial('C_'.format(i),IMPS[ind_],rate,observed=CLICKS[ind_])
```

however the sampler is taking a very long time to initialize and run

```
with model:
    step = pm.Metropolis()
    trace = pm.sample(10000, step)
res=pm.summary(trace[1000:])
```

I thought that the this model would be equivalent to a model which use the shape parameter for the variables:

```
with pm.Model() as model2:
    shape =(ndata,1)
    clicks_array = np.asarray(CLICKS).reshape(shape).astype(np.float32)
    imps_array = np.asarray(IMPS).reshape(shape).astype(np.float32)
    C = pm.Binomial('C',imps_array,rate,observed=clicks_array,shape=shape)

with model2:
    step = pm.Metropolis()
    trace2 = pm.sample(10000, step)
res2=pm.summary(trace[1000:])
```

The sampling step now is fast, however the estimated posteria for the rates are now completely off.

Seems that this two models are inherently different. Can you please explain me why?
How can I get the same results from model1 but with a faster inference? 
I need to be able to scale this model to the size ndata~100k. Would this library able to do this?

**Comment by lfiaschi** [comment]
link to public notebook which summarizes the problem:

http://nbviewer.ipython.org/gist/lfiaschi/b8c5337f0a8b8c13819c

**Comment by twiecki** [comment]
Related discussion: https://github.com/pymc-devs/pymc3/issues/535

**Comment by lfiaschi** [comment]
thanks this clarifies a bit the difference between the two models. Other question: would it be possible to scale a similar model to ~ 100k variables by using this library?

**Comment by jsalvatier** [comment]
I think that would be very slow, but you could probably fit the same model
100k times. Might be a bit slow, but not super duper slow.

**Comment by lfiaschi** [comment]
@jsalvatier thanks, however I am a little puzzled by your answer, if you fit 100k models independently wouldn't you have a bad estimate on alpha, and beta? (since r are conditionally dependent variables).

Do you have any good reference on applying sampling techniques to large scale problems?

**Comment by jsalvatier** [comment]
Ah, sorry I hadn't followed the rest of the thread very carefully. I think
MCMC, even NUTS, will be difficult for such large scale models. Though you
could probably make it work with a gibbs sampler for the 100k variables and
NUTS for your other parameters.

**Comment by lfiaschi** [comment]
thank, any reference on how to implement Gibbs sampling on pymc3?

**Comment by twiecki** [comment]
@lfiaschi @aflaxman has an example of a Gibbs sampler here: http://nbviewer.ipython.org/gist/aflaxman/64f22d07256f67396d3a

We should try to get this into PyMC3.

**Comment by twiecki** [comment]
@lfiaschi See https://github.com/pymc-devs/pymc3/pull/799 for a WIP implementation.

**Comment by fonnesbeck** [comment]
Can we close this? 

In general, I think Gibbs is too hard to generalize and not usually worth the trouble, relative to other options.

**Comment by lfiaschi** [comment]
Hi, I ended up writing my on specialized gibbs sampler, it can be closed for me. I agree Gibbs is very hard to generalize.

**Comment by fonnesbeck** [comment]
Great, thanks. Closing.
