### ISSUE TITLE
Add DIC

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc#797]
Standard measure for model comparison that's very easy to implement. Here's the pymc2 implementation https://github.com/pymc-devs/pymc/blob/895c24f62b9f5d786bce7ac4fe88edb4ad220364/pymc/MCMC.py#L410

**Comment by AustinRochford** [comment]
I was thinking about contributing this, wanted to get your thoughts on #789 in the context of DIC.  I was thinking a warning about transformed RVs and a link to that issue should be included, and am wondering if you think that would be sufficient.

**Comment by jsalvatier** [comment]
A warning for transformed variables seems good.

**Comment by fonnesbeck** [comment]
Done, via #834
