### ISSUE TITLE
NUTS converging to wrong values in hierarchical model

### ISSUE THREAD

**Issue by kiudee** [pymc-devs/pymc#798]
In the following hierarchical Binomial model the observations have widely different sample sizes (3, 5, 10 ...). The expected behavior is that the parameter of observations with low sample size are shrunk to the shared prior distribution. The synthetic data is generated as follows:

``` python
import numpy as np
import scipy.stats as st
thetas = st.beta(8,2).rvs(15)
total = np.array([3, 5, 10, 15, 20, 100, 200, 300, 500, 1000, 1200, 1300, 1500, 2000, 3000])
data = np.random.binomial(n=total, p=thetas)
```

And here is a simple pymc3 model:

``` python
import pymc3 as pm
import scipy.optimize as opt
with pm.Model() as model:
    mu = pm.Beta('mu', alpha=1, beta=1)
    sd = pm.HalfCauchy('sd', 1)
    p = pm.Beta('p', mu=mu, sd=sd, shape=15)
    like = pm.Binomial('like', n=total, p=p, observed=data)

    start = pm.find_MAP(fmin=opt.fmin_l_bfgs_b)
    step = pm.NUTS(scaling=start)
    tr = pm.sample(200000, step, start=start)
```

The produced traceplot appears to have no kinks `pm.traceplot(tr[10000::100])`:
![mcmcplot](https://cloud.githubusercontent.com/assets/564473/9289213/4b2811ac-4368-11e5-88c3-d7134a031b22.png)

But the estimated parameters are far from the true parameters or the global mean, especially for the first observations where the sample size is low:

```
list(zip(tr['p'].mean(axis=0), thetas, data, total)):
[(0.59429747161228141, 0.91144133179704656, 3, 3),
 (0.61329283383894906, 0.85469577301002564, 5, 5),
 (0.61155977297969943, 0.77355772685980384, 8, 10),
 (0.62941342828273406, 0.71355927694781762, 12, 15),
 (0.64396010067724052, 0.63357481433692087, 16, 20),
 (0.78471490407218569, 0.90000639838927843, 87, 100),
 (0.84555262187593117, 0.90784650458678218, 180, 200),
 (0.82619263915705698, 0.8620033015809867, 258, 300),
 (0.83508048878154528, 0.84418494094635788, 428, 500),
 (0.86916210862206567, 0.8828212574343427, 881, 1000),
 (0.65214705145233953, 0.67905418666031125, 786, 1200),
 (0.84470708817840146, 0.87289612086578938, 1109, 1300),
 (0.72716686711391532, 0.72090949555705952, 1097, 1500),
 (0.90930837733972514, 0.92153727881685144, 1832, 2000),
 (0.592667699755555, 0.59795279082587249, 1779, 3000)]
```

I tried this model in an older version version of pymc3, where the logit transform was not implemented. Although NUTS had a lot of problems to find high density regions, in some cases it converged to the expected posterior distribution. Any ideas where this problem might come from?

**Comment by twiecki** [comment]
You're right, something seems to go awry here. I tried the model without the transforms but couldn't get it to converge with NUTS so I used slice:

``` python
import pymc3 as pm
import scipy.optimize as opt
with pm.Model() as model:
    mu = pm.Beta('mu', alpha=1, beta=1, transform=None, testval=0.8)
    sd = pm.HalfCauchy('sd', 1, transform=None, testval=6.)
    p = pm.Beta('p', mu=mu, sd=sd, shape=len(thetas), transform=None, testval=thetas)
    like = pm.Binomial('like', n=total, p=p, observed=data)

    start = pm.find_MAP(fmin=opt.fmin_l_bfgs_b)
    step = pm.Slice()
    tr = pm.sample(5000, step, start=start)
```

Which then produces this output which makes much more sense:

```
[(0.82747689011760828, 0.91010795906661013, 2, 3),
 (0.86595659172705131, 0.81512980284687675, 5, 5),
 (0.90108596227038285, 0.74346124378883882, 10, 10),
 (0.87574850117844383, 0.90105572006038059, 14, 15),
 (0.80159070988848802, 0.85029192718928082, 16, 20),
 (0.85600911611632635, 0.85357165718350747, 84, 100),
 (0.92658902800252585, 0.90662195649845423, 187, 200),
 (0.78584432242674507, 0.78694148507870676, 236, 300),
 (0.82445882166983198, 0.8221859969760229, 413, 500),
 (0.64970825147423039, 0.64746564076715862, 648, 1000),
 (0.86796229721679374, 0.87019126252123613, 1044, 1200),
 (0.64093517976567582, 0.64537721412448512, 832, 1300),
 (0.72415390819634629, 0.73418028487501363, 1083, 1500),
 (0.85812705419630186, 0.86658646913382009, 1717, 2000),
 (0.80455981818835165, 0.82011779633467563, 2414, 3000)]
```

Allowing for transforms with the same sampler produces the output you saw.
CC @jsalvatier

**Comment by twiecki** [comment]
Seems to be an issue with `p` specifically. The model works when switching off that transform:

``` python
p = pm.Beta('p', mu=mu, sd=sd, shape=len(thetas), testval=thetas, transform=None)
```

I wonder if perhaps the shape argument is messing things up.

**Comment by fonnesbeck** [comment]
Interestingly, I get the same general result if I:
1. Use the canonical parameterization of the beta
2. Use Metropolis rather than NUTS

The latter suggests that it is not the NUTS algorithm implementation that is the problem. It also does not seem to vary with respect to the actual data value of the smaller sample sizes.

The same model in PyMC 2.3 seems to come up with something reasonable.

![unknown](https://cloud.githubusercontent.com/assets/81476/9310708/115f3638-44d7-11e5-9e67-11f70a518f09.png)

**Comment by jsalvatier** [comment]
Figured it out, there was a serious flaw with the elementwise transforms where the jacobian was wrong. I have a patch for it here

**Comment by jsalvatier** [comment]
@kiudee could you try out that branch?

**Comment by twiecki** [comment]
With the `transform_fix` branch I now get the same result as without the transform:

```
[(0.84139000895059124, 0.96098430164553861, 3, 3),
 (0.79913226349675337, 0.87179519208715994, 4, 5),
 (0.8449979357233427, 0.75682112505552479, 9, 10),
 (0.72832890101996361, 0.73467667316879104, 10, 15),
 (0.8939819380189763, 0.88316941227468626, 19, 20),
 (0.81833018818821124, 0.8831113141644884, 82, 100),
 (0.89333340596432698, 0.89165686449032244, 180, 200),
 (0.81915497204448673, 0.80612506154071184, 246, 300),
 (0.63646555557694018, 0.65879199256603438, 316, 500),
 (0.67050868457446211, 0.65079331747005842, 669, 1000),
 (0.7812927571654722, 0.77988827213874623, 937, 1200),
 (0.88087766328796591, 0.88966937311715144, 1146, 1300),
 (0.89382057738896459, 0.89643859677987459, 1342, 1500),
 (0.69947406958008895, 0.69317365347555937, 1398, 2000),
 (0.90656910875172181, 0.8969288070796706, 2721, 3000)]
```

Nice catch!

**Comment by kiudee** [comment]
Just to confirm, it’s also working on my end. I will close this issue.

Good job!

**Comment by twiecki** [comment]
@kiudee Thanks for reporting, this was a big one!

**Comment by jsalvatier** [comment]
Indeed, many thanks!
