### ISSUE TITLE
Feature: Generalized additive models with integrated smoothness estimation

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#809]
https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/gam.html
How difficult is it to implement this?

**Comment by arose13** [comment]
It wouldn't be hard to implement but are you imagining this being apart of the PyMC3 package? Like I'm thinking it may be better to do this as a separate package.

**Comment by Irene-GM** [comment]
Hello, is there any development on this enhancement? :-) 
Thanks for your effort!

**Comment by aloctavodia** [comment]
Splines are going to soon be available in Bambi bambinos/bambi#214
