### ISSUE TITLE
How can I have summary statistics in variables?

### ISSUE THREAD

**Issue by ItayLieder** [pymc-devs/pymc#814]
Hi,
I wish to have the output for summary(trace) into a variable that I can later manipulate, mainly because you already calculate the HPD which is non trivial for me to do.

Alternatively, I can save it into file and then read from it. I saw you had a write_csv option on earlier versions, but could not find it in pymc3.

Many thanks!

**Comment by kyleam** [comment]
The current output doesn't offer a convenient way you to do this, but I
agree that it'd be nice.  (You could redirect stdout to a file or a
variable using StringIO, but there currently aren't functions for
parsing the output into any format that could be easily manipulated.)
It's been on my TODO list to add another function (`df_summary`?) that
will return the results of most the statistics currently in `summary` as
a Pandas data frame of the form

```
        stat1 stat2 ... statN
x
y__0
y__1
...
z__0_0
z__0_1
...
z__2_3
```

which is a similar to the format from summary output of Stan.

I'd be interested to hear others' thoughts on this.

**Comment by ItayLieder** [comment]
Thank you for your reply kyleam.
That would indeed be nice

**Comment by fonnesbeck** [comment]
So, you are just looking for an export of `summary`? Would something like this work?

```
summary(trace, vars=['alpha', 'beta'], to_file='summary.csv')
```

**Comment by ItayLieder** [comment]
I want to plot HPD's as a function of the sampling condition (a few dozens), and therefore need to keep each value. Either of you'r suggestions would work for me (the second since I can read the csv and extract what I need).

Thanks

**Comment by twiecki** [comment]
@ItayLieder These PRs are now merged so you should be able to get the stats, can you test this?. I'll close this, feel free to reopen if it doesn't solve your problem.

**Comment by fonnesbeck** [comment]
Many thanks to @kyleam for this!

**Comment by ItayLieder** [comment]
Thanks you very much

**Comment by DerekGrant** [comment]
@kyleam Thx~ I failed to run pm.df_summary, and fixed it by pm_summary.
