### ISSUE TITLE
Unable to use Nelder-Mead optimizer

### ISSUE THREAD

**Issue by stevenmanton** [pymc-devs/pymc#817]
I'm having issues with the default minimizer (BFGS) getting stuck in local minima in a hierarchical model that I'm running. I've [read](http://people.duke.edu/~ccc14/sta-663/BlackBoxOptimization.html) that Nelder-Mead can sometimes work better in these cases, but I'm having trouble getting it to run with pymc3. For instance, if I try to define a nelder-mead minimizer along the lines of

```
model.find_MAP(fmin=partial(optimize.minimize, method='nelder-mead'))
```

I get the error

```
TypeError: <functools.partial object at 0x1809d5a48> is not a Python function
```

Probably, the code should not rely only on `isfunction` before throwing an exception.

Still, if I define the minimizer like the following, 

``` python
def nm_min(*args, **kwargs):
    return optimize.minimize(*args, method='nelder-mead', options=kwargs)

model.find_MAP(fmin=nm_min)
```

then I get a `TypeError: unhashable type` error.

Likely, I just don't understand how to call other minimizers. I might call this just an issue of documentation, since I've seen others online using Nelder-Mead, but I haven't seen the syntax they've used nor do I see anything in the documentation. Tips would be appreciated! I'm happy to try to type up some docs on this and submit a PR if someone can provide a bit of guidance. Thanks for all the great work...

**Comment by twiecki** [comment]
Indeed you can't use the `minimize` interface. Instead, try passing `fmin`: `model.find_MAP(fmin=scipy.optimize.fmin)`

**Comment by stevenmanton** [comment]
Got it. Thanks! I didn't realize that `fmin` used Nelder-Mead already. I guess I was wondering more in general if it was possible to pass any of the available methods in `minimize` for which there isn't a corresponding `fmin_*` function.

**Comment by twiecki** [comment]
Which methods do not have a `fmin_*` analog?

**Comment by stevenmanton** [comment]
[dogleg](http://docs.scipy.org/doc/scipy/reference/optimize.minimize-dogleg.html), for example? I was mostly interested in Nelder-Mead so I think you can close the ticket :-)
