### ISSUE TITLE
Tutorial linear regression bug

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#822]
Rachel Hodos emailed me the following:

I was just looking at the first example shown on the pymc3 website, on linear regression.  I was at first puzzled why the coefficients estimated for beta were so different from the true values, but then I realized that X1 and X2 are defined using linspace, which means that the two features are perfectly correlated, meaning that the model won't be able to distinguish them.  Perhaps it should be replaced by randomly sampled inputs?

**Comment by twiecki** [comment]
Fixed with https://github.com/pymc-devs/pymc3/commit/899b0a9bdc4a0216b3897a9bbae7cbfcb52d46c3.
