### ISSUE TITLE
Move UQ chapter tutorial to main repo

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#823]
That's where it probably belongs

**Comment by twiecki** [comment]
+1

**Comment by twiecki** [comment]
Updated with https://github.com/pymc-devs/pymc3/commit/e3f202baeb9e256f29cfe6bb576295a543b80ea3.

**Comment by twiecki** [comment]
Rendered: http://pymc-devs.github.io/pymc3/getting_started/

**Comment by jsalvatier** [comment]
Awesome :)
