### ISSUE TITLE
Prior for an array of parameters

### ISSUE THREAD

**Issue by ItayLieder** [pymc-devs/pymc#829]
Hello,
I'm doing inference for a large number of parameters and was wondering if it is possible to define a prior, for example:
        theta = pm.Beta('theta', alpha=1, beta=1)
        beta = pm.Bernoulli('beta', p=theta)

such that both theta and beta would be arrays and not a scalars.

Many thanks

**Comment by kiudee** [comment]
Sure, you can specify a `shape` parameter for both distributions and then just pass in parameter vectors for `alpha`, `beta` and `p`:

``` python
data = np.random.randint(0, 2, size=(100, 3))
with pm.Model() as model:
    theta = pm.Beta('theta',
                    alpha=np.array([2, 10, 100]),
                    beta=np.array([2, 10, 100]),
                    shape=3)
    beta = pm.Bernoulli('beta', p=theta, shape=3, observed=data)
    tr = pm.sample(2000, pm.NUTS())
```

**Comment by ItayLieder** [comment]
Thank you kiudee!
