### ISSUE TITLE
Auto-assignment of step methods to model variables

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#832]
It is not always easy for new users to decide which step methods to use with which model variables, and in some cases, the appropriate step method changes with the size of the stochastic (see #818). We should implement a system like PyMC 2 that auto-assigns step methods based on variables' attributes. This was implemented by having a `competence` classmethod that returned a score associated with the step method based on the variable passed as an argument. The variable is then assigned the step method with the largest score.

**Comment by walterreade** [comment]
+1

**Comment by twiecki** [comment]
Closed by #833.
