### ISSUE TITLE
Using a theano function as indices 

### ISSUE THREAD

**Issue by ItayLieder** [pymc-devs/pymc#846]
Hi,
I have a deterministic stage where I need to use a variable K to get the first k indices of a given vector.
Is there any way this could somehow be done?

Thanks!

**Comment by jsalvatier** [comment]
Yup, should be able to just say 

```
vec = Normal('vec', shape= 20)
K = DiscreteUniform('K', 0, 20)
firstKvalues = vec[:K]
```

**Comment by ItayLieder** [comment]
Thanks you
