### ISSUE TITLE
Unlisted Dependency for Python Version 2.7

### ISSUE THREAD

**Issue by missing-semicolon** [pymc-devs/pymc#847]
Hi all,

When executing "from pymc3 import Model, Normal, HalfNormal" in Python Version 2.7 I received the error "ImportError: No module named enum"

I believe in Python versions < 3.4 one needs to specify a dependency on enum34. I pip installed it and now the code works as expected. Maybe this should be added to the code?

**Comment by dstuck** [comment]
I had this same issue while installing pymc3 on a new computer. Looks like the llvmlite package fixed this just for Python 2.7 with the following line in setup.py:
if sys.version_info < (3, 4):
    install_requires.append('enum34')

I added a pull request to fix this.
