### ISSUE TITLE
Way to observe a deterministic transform of a RV

### ISSUE THREAD

**Issue by mjwillson** [pymc-devs/pymc#848]
I may be missing an obvious way to do this, but it seems like there isn't a way to observe a deterministic transform of a random variable. It'd be nice if you could separate the API for observing things from the API for declaring a random variable, e.g.:

``` python
with model:
  ...
  Observe(expression, data)
```

Would this be possible? You'd need the log (absolute) determinant of the jacobian for the transformation, but that should be doable with theano right?

[EDIT: after thinking about this more I see why it might be a bit tricky to do well -- theano only implements jacobian in terms of a scan loop over separate grad's, and seems it's likely to compile you a very slow implementation of `log |det J(x)|` that hasn't benefited from any symbolic optimisations :(

MORE EDIT: or more to the point, you'd need the inverse of the transform anyway (and for it to be invertible), so you might as well just apply that inverse to your data yourself, and the Jacobian can be ignored if you only care about the log-likelihood up to a constant]

**Comment by kyleabeauchamp** [comment]
In the non-degenerate case could you implement this with a potential on the transformed RV?

**Comment by jsalvatier** [comment]
I think a transform _should_ do it, though you'll have to roll your own transform (https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/transforms.py) perhaps.

**Comment by mjwillson** [comment]
Aha, yeah that looks it'll do it. Thanks.

I guess the Jacobian term doesn't actually matter too, unless you care about the joint density, since it doesn't depend on the parameters. If I understand right it looks like the problem with supporting this for general theano expressions is more that theano can't invert the transform for for you symbolically.

Another idea I had is that you could observe a very narrow Gaussian (almost a delta function) around the transformed point. I guess that would mean the inference algorithm is numerically inverting the transform for you in an approximate way. Probably not great from a numerical point of view but might be an option if you don't have a closed form for the inverse?
