### ISSUE TITLE
Blackbox Inference Workshop (Due today)

### ISSUE THREAD

**Issue by jsalvatier** [pymc-devs/pymc#851]
@twiecki @fonnesbeck 

Did you guys see this workshop? 

This workshop brings together developers of black box inference technologies, probabilistic programming systems, and connectionist computing frameworks. The goal is to formulate a shared understanding of how black box methods can enable advances in the design of intelligent learning systems. Topics of discussion will include:

Black box techniques for gradient ascent, variational inference, Markov chain- and sequential Monte Carlo.
Implementation of black box techniques in probabilistic programming systems and computing frameworks for connectionist model families.
Models that integrate top-down and bottom-up model representations to perform amortized inference: variational autoencoders, deep latent Gaussian models, restricted Boltzmann machines, neural network based proposals in MCMC.
Applications to vision, speech, reinforcement learning, motor control, language learning.

http://www.blackboxworkshop.org/

**Comment by twiecki** [comment]
That does look great but it seems like the deadline has already passed :(. We could still try to submit our abstract and see if they accept it still.

**Comment by fonnesbeck** [comment]
I will be going to NIPS, so I will definitely attend the workshop.

**Comment by datnamer** [comment]
@twiecki  @fonnesbeck  @jsalvatier  Here is another one: http://approximateinference.org/
