### ISSUE TITLE
Uniform samples values outside of definition range, variable name changed

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#858]
Dear PYMC developers,
first of all I wanted to thank you for the great job you are doing. I have been successfully using pymc2 so far. Now I have a model case with several hundreds of variables and pymc2 is running, but for ages.
So I decided to try pymc3.
It is a about modeling the slip distributed on an earthquake fault. Where the slip vector m consists of several fault patches with different slips that I wanted to solve for with d=G*m. Where G relates the unit slip of each fault patch with the observed displacement  d at the earths surface(data).
I wanted to initialize the slips so that they add up to a certain moment of the earthquake, which is known (around 7.2e20Nm). So the init_slips are definitely all positive!!!

``` python
import pymc3 as pm
import numpy as num
import theano.tensor as tt

npatch=340
moment=7.2e20
shearm = 33e9
patch_length=2000
patch_width=2000
moments = num.random.dirichlet(num.ones(npatch), 1).transpose()*moment
# convert to slip
init_slips = moments/(shearm*patch_length*patch_width)
mean_slips = num.mean(init_slips)
init_slips = init_slips.squeeze()
with pm.Model() as static_dist_slip:
    #initiallize prior
    m_perp = pm.Normal('m_perp', mu=0, sd=mean_slips, shape=npatch, 
                testval = num.zeros([npatch],dtype=float))
    m_parr = pm.Uniform('m_parr', lower= 0, upper= 5, shape=npatch, testval = init_slips)
    #calculate cost
    for i in range(len(Displ)):
        gres = pm.MvNormal('Cost_{}'.format(i+1), mu=(tt.dot(GFs_par[i],m_parr) +
                        tt.dot(GFs_perp[i],m_perp)), tau=ICxgs[i], observed=Displ[i])      

with static_dist_slip:
    backend =Text('trace')
    step=pm.Metropolis()
    print('Starting to sample ...')
    trace=pm.sample(200000, step=step, tune = 80000 ,njobs=10, trace=backend)
```

So far the model looks really simple, but I am facing several problems.
I. Instead of the variable `m_parr` a variable `m_parr_interval` is being created in `static_dist_slip`
II. Although I defined the boundaries to be between 0 and 5, negative values are being sampled as can be seen from the backend output chain-1.csv (just few columns): (remember all the init_slips as testval are positive!)

```
m_parr_interval__0  m_parr_interval__1  m_parr_interval__2  m_parr_interval__3  m_parr_interval__4
-8.20091829 -1.333660228    -1.487605769    -1.049942258    -3.611551583
-8.20091829 -1.333660228    -1.487605769    -1.049942258    -3.611551583
-8.20091829 -1.333660228    -1.487605769    -1.049942258    -3.611551583
-8.20091829 -1.333660228    -1.487605769    -1.049942258    -3.611551583
-8.20091829 -1.333660228    -1.487605769    -1.049942258    -3.611551583
```

III. There is also the next issue visible- always the same values are being sampled and the `m_parr_interval`, `m_perp` variables are not changing with iterations.
IV. Surprisingly the output finally also contains the variable `m_parr` (as originally defined) although it is not present in `static_dist_slip.m_parr`

```
m_parr__47  m_parr__48  m_parr__49  m_parr__50  m_parr__51  m_parr__52
0.940543617 0.626570381 0.673483407 nan 1.207404878 0.203004832
0.940543617 0.626570381 0.673483407 nan 1.207404878 0.203004832
0.940543617 0.626570381 0.673483407 nan 1.207404878 0.203004832
0.940543617 0.626570381 0.673483407 nan 1.207404878 0.203004832
```

V. It sampled NaN values ...- how is that possible?
VI. I am having several datasets, whose likelihoods `p[1-7]=(d-G[1-7]*m)(C-1[1-7])(d-G[1-7]*m)T)` should be all added up. Now I had to create a Cost variable for each of them. Can this still work? How can I add them up? 
VII. Using the sqlite backend crashes with `njobs>1`, saying database was locked. But thats an SQLite issue I guess, because of the several jobs accessing the file. 

I hope we can clear this up, so that this great package becomes even better ;) .
Best wishes,
Hannes

**Comment by hvasbath** [comment]
Update: 
Most of the issues were related to my errors in programming the model, as I am totally new to these theano tensors. But after getting to know the tensor.tag.test_value function I was able to follow what actually is being calcuIated and I managed rewrite my model so that Issues 2-6 are solved by using the code below.
Apparently the name of the variable is properly assigned as m_parr, if I use transform=None. 

```
with pm.Model() as static_dist_slip:
    #initiallize prior
    m_perp = pm.Normal('m_perp', mu=0, sd=mean_slips, shape=npatch) #, 
                         testval = num.zeros([npatch],dtype=float))
    m_parr = pm.Uniform('m_parr', lower= 0, upper= 8, shape=npatch, 
                         testval = init_slips, transform=None)
    logpts = num.ndarray(ndata,dtype=object)
    #calculate cost
    for i in range(ndata):
        mu=tt.dot(shared(GFs_par[i]),m_parr) + tt.dot(shared(GFs_perp[i]),m_perp)
        res = shared(Displ[i]) - mu
        logpts[i] = res.T.dot(shared(ICxgs[i])).dot(res)

    like = pm.Potential('like',logpts.sum())
```

However, it should be working properly without having to set transform=None! Doesnt it?
It also takes significantly longer to sample if I dont use this. With transformflag 15 Iterations in 1s
without 1 iteration in 5s. For Metropolis with njobs=2.
The NUTS sampler is initiating finally, but samples always the same values according to the output traces.
Whereas Metropolis seems at least to sample the solution space, however the m_perp samples end up around crazy high values of -30k till plus 50k. How is that possible with the m_perp being a Normal centered at 0 mean with std of 1.1- 1.3 ish? Do I still have a bug in my calculation?
Thank you!

**Comment by hvasbath** [comment]
Update: Found the bug: (stupid mistake)

```
logpts[i] = res.T.dot(shared(ICxgs[i])).dot(res)
```

it has to be:

```
logpts[i] = (-1/2)*res.T.dot(shared(ICxgs[i])).dot(res)
```

However, the issue with the variable name change, when not setting transform=None still persists...

**Comment by jsalvatier** [comment]
Glad you were able to solve this. The variable name is changed because the sampling is taking place in a transformed space using the interval transform (that's what the transform parameter does). This often allows more efficient sampling. 

You can also keep track of the actual variable by adding `vars=model.vars + [m_parr]` to `trace=pm.sample(200000, step=step, tune = 80000 ,njobs=10, trace=backend)`.

**Comment by hvasbath** [comment]
Great! Thanks for the clarification! This issue can be considered as closed then!
