### ISSUE TITLE
Programmatically check if `find_MAP` converges

### ISSUE THREAD

**Issue by stevenmanton** [pymc-devs/pymc#859]
I often have an issue when running models that the function `find_MAP` doesn't converge, which then leads to a poor starting point and the MCMC sampling gives bogus distributions. I can see this by passing the `disp=True` option, but it doesn't seem there's a programmatic way to catch this. The underlying [`fmin`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html#scipy.optimize.fmin) functions seem to return this info via `warnflag`, but this is stripped when setting `r`.

I'd like to submit a patch that returns the full output from `fmin` so I can programmatically check for convergence, but I'm not sure what the best way to do so is. Add another option like `return_raw`? Remove the code that strips all elements but `r[0]`? I'm happy to submit a pull request if core devs give some guidance. Thanks!

**Comment by jsalvatier** [comment]
I think actually it would be good to raise an error by default if it doesn't converge. Would that be enough for you? Though I'm a bit worried about this messing up other people. 

Can you show the line where its getting stripped, I'm not clear on what you mean.

**Comment by stevenmanton** [comment]
I agree that raising an exception seems like a more reasonable default action. Maybe there could be a keyword argument like `raise_on_failed_convergence` that defaults to `True` for those that don't like this behavior.

The line I had in mind that strips the return elements from `fmin` is [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tuning/starting.py#L86), line 86.

**Comment by stevenmanton** [comment]
Actually, I think I misunderstood the code -- the line I mentioned doesn't strip the result flags. You actually have to specify `full_output=True` to get them. So, to programatically check for convergence, you need to pass `return_raw=True` and `full_output=True` and check the `warnflag` of the output. The problem is that `warnflag` doesn't appear in the same position for each of the various minimization functions!

I suggest closing this for now since there doesn't seem to be an nice way to check for convergence. I'll likely implement a hackish way for my own purposes.
