### ISSUE TITLE
Drop/clean up hierarchical notebook

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#866]
The `hierarchical.ipynb` example in master looks to be a WIP. There is no supporting documentation for the example, and there are several cells with calculations that are not germane to the model. Was this committed by accident? We should probably ditch it unless someone wants to clean it up.

**Comment by twiecki** [comment]
That looks like WIP indeed. Should be easy to clean up and I think it's a good example.

https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/hierarchical.ipynb
