### ISSUE TITLE
Custom distribution with multiple variables

### ISSUE THREAD

**Issue by ChriZiegler** [pymc-devs/pymc#867]
I want to use DensityDist to make a joint distribution of multiple variables. I have my likelihood as so:

``` python
import pymc3
import numpy as np
import scipy
from math import exp

def my_likelihood(vals):
    l = (vals[0] * exp(-1*(vals[0]**2 + vals[1]**2)) + (vals[0]**2+vals[1]**2)/20) + 1
    return np.log(l)
```

I can, for instance, use `scipy`'s minimize function with this likelihood function:

``` python
x0 = [0.1,0.1]
scipy.optimize.minimize(my_likelihood, x0)
```

I want to use this function to create a custom density, but I am running into problems:

``` python
my_model = pymc3.Model()

with my_model:
    out = pymc3.DensityDist("my_model", my_likelihood, shape=2, testval=x0)
    x = out[0]
    y = out[1]
```

This gives the error `TypeError: a float is required`. `vars[0]` and `vars[1]` appear to be objects of the type `'theano.tensor.var.TensorVariable'`. 

Is there a way for me to adjust my function in order for it to work with `DensityDist`?

**Comment by twiecki** [comment]
You might have to unvectorize, would: `pymc3.DensityDist("my_model", my_likelihood, val0, val1, shape=2, testval=x0)` work?

**Comment by aloctavodia** [comment]
Closing but feel free to re-open.
