### ISSUE TITLE
API limitation for specifying levels with categorical variables

### ISSUE THREAD

**Issue by FedericoV** [pymc-devs/pymc#870]
Let's say that I'm fitting a linear model of type:

```
y = BX + sigma
```

Where X is a categorical variable and I want to estimate a different B for every category.  In my case, X indicates which gene was deleted, and B represents the effect of deleting that gene.

However, in the population, I also have control cells which have no gene deleted.  How do I specify that I wish to treat a particular level of X as the 'null' level?

Using emcee, I wrote this mess of a code - which, however, numba can jit very efficiently so it turns out to be really fast (but horrendous to read + write).

```
@numba.jit(nopython=True)
def log_likelihood(theta, tip_gs_idx, del_idx, wt_code, length, y):
    """Likelyhood of the data, given a model.

    We use a simple linear model, however there are a lot of categorical
    variables that are used as indices into arrays.
    """
    sigma = theta[0]
    alpha = theta[1:7]
    beta_l = theta[7:13]
    beta = theta[13:]

    residuals = 0.0
    for i in range(len(tip_gs_idx)):
        idx = tip_gs_idx[i]

        # This is the base value for a wild type cell with no deletion
         y_model = alpha[idx] + (beta_l[idx]*length[i])

        # Really annoying indexing:
        # del_idx[i] indicates which deletion is present - however, one of
        # the values indicates no deletion (wt_code) - in which case we do not
        # add the extra effect from the deletion.  Writing code like this is fun...
        if del_idx[i] != wt_code:
            if del_idx[i] < wt_code:
                beta_idx = idx + del_idx[i]*6
            else:
                beta_idx = idx + (del_idx[i]-1)*6

            # if a deletion is present, we add it's effect
            y_model += beta[beta_idx]

        # Standard gaussian log pdf.  Could actually use function above, maybe?
        residuals += np.log(2 * np.pi * sigma ** 2) + (y[i] - y_model) ** 2 / sigma ** 2
    residuals *= -0.5    
    return residuals
```

**Comment by fonnesbeck** [comment]
If I understand you correctly, you should probably encode `X` using indicator variables, with the baseline having no indicators. So, for example:

```
[2, 0, 1, 2, 1, 3]
```

would become

```
[[0,1,0], [0,0,0], [1,0,0], [0,1,0], [1,0,0], [0,0,1]]
```

and you would have 3 corresponding `B` parameters. The model would then be:

```
y = mu + BX + epsilon
epsilon ~ N(0, sigma)
```

**Comment by fonnesbeck** [comment]
Probably best to post these sorts of questions to the [PyMC topic on StackOverflow](http://stackoverflow.com/questions/tagged/pymc), since it is not a bug report.
