### ISSUE TITLE
Investigate Tensorfuse, a common interface for Theano, CGT, and TensorFlow ?

### ISSUE THREAD

**Issue by datnamer** [pymc-devs/pymc#871]
https://github.com/dementrock/tensorfuse#running-benchmark

Looks pretty cool:

"The current API for TensorFuse is geared towards migrating existing Theano-based code to using CGT or TensorFlow. Therefore, if you have some code that uses Theano, you can simply change the import statements to

``` python
import tensorfuse as theano
import tensorfuse.tensor as T
```

"

@dementrock, how do you think your library would fare for a fairly complex codebase like Pymc3?

**Comment by twiecki** [comment]
That'd be quite interesting to explore. I'm afraid we use too much theano fancyness, but maybe not.

**Comment by dementrock** [comment]
Hi @datnamer, thanks for your interest! The library is most likely not ready, as many of the APIs aren't bridged yet. However, I think the overall direction is a good way to go to migrate many of the existing Theano-based libraries to support TensorFlow, and it's very easy to extend the library.

One immediate thing that's difficult for this project is that there are classes that inherit from constructs of Theano (e.g. https://github.com/pymc-devs/pymc3/blob/58f3f8e5d2a55edc5e05b33b239fa46631eff895/pymc3/model.py#L415). Not sure if this can be modified to be something less coupled with Theano.

**Comment by dementrock** [comment]
I'm also (partially) porting the Lasagne library (https://github.com/dementrock/Lasagne), but it might be using less theano fancyness..

**Comment by stonebig** [comment]
Any progress on this ? At the moment, Tensorflow looks like the only option going forward for Python-3.5 users on Windows.

**Comment by twiecki** [comment]
@stonebig No progress, and it seems like tensorfuse is inactive. Theano will fix the Python 3.5 issues on Windows, I have no doubts. Seems like they are making good progress: https://github.com/Theano/Theano/issues/3376

I also don't think we are actively pursuing TensorFlow as it would be more of a rewrite of PyMC3 and there is already Edward. Theano is widely used, well supported, and actively developed and has proven very useful for PyMC3.

**Comment by twiecki** [comment]
In the meantime, you can easily create a Python 3.4 environment with conda and run pymc3 there.

**Comment by stonebig** [comment]
Python-3.4 is an ersatz solution. The demise of mingwpy project for Python-3.5/3.6 is a huge blow for Windows users (of Theano)

**Comment by twiecki** [comment]
Seems like there is a work-around for Python 3.5: https://github.com/Theano/Theano/issues/3376#issuecomment-235034897

**Comment by stonebig** [comment]
It seems the less complicated path for me is to use Edward, ... Windows users have not as many **realistic** options as Linux users, sometimes having one is already a great surprise.

**Comment by twiecki** [comment]
@stonebig Edward is great. I think theano have conda packages for 3.5 now: "With the new conda packages, it work." https://github.com/Theano/Theano/issues/3376#issuecomment-267429276
