### ISSUE TITLE
TypeError: Shared variable constructor needs numeric values and not symbolic variables.

### ISSUE THREAD

**Issue by DeliciousHair** [pymc-devs/pymc#882]
Sorry to be such a pest, but this is driving me bonkers!

What I'm trying to do is define a custom distribution (stochastic) and use it via:

```
with model:
    .
    .
    .
    X_obs = MyNewDist('X_obs', mu=mu, observed=data)
    .
    .
    .
```

but the problem is that that I keep getting the above error, the relevant part of my wonky distribution being:

```
    def logp(self, val, size=None):
        mu = self.mu
        mu = shared(mu)
        return my_logp(val, mu)
```

which falls over as

```
>>> lam.__class__
pymc3.model.TransformedRV
```

So basically, I need to somehow ri-jigger this `TransformedRV` object into something more generically compatible with my `val` variable, but I'm just not managing to pull it off. Have combed over so much source code in the past few days it's making my head ache, and I'm still just confused.

Any ideas?

**Comment by twiecki** [comment]
Can you post the full RV? Not sure why you need a shared variable in the first place.

**Comment by fonnesbeck** [comment]
Shared variable was my suggestion based on an earlier interaction (#878). @DeliciousHair was trying to use a Python integer in an operation with a Theano tensor, so I suggested a shared variable as a way of implementing what was intended. Looks like a tensor is needed instead. `mu` should ideally be another PyMC object.

**Comment by DeliciousHair** [comment]
Yes, that's what I've been attempting to do (work not shown here) but I'm really not getting anywhere with it. The shared variable approach makes perfect sense conceptually, but clearly doesn't work for reasons tied back to theano, a tool I have very little experience with. As for the RV--keeping in mind from #878 that I need an incomplete gamma function--I've done the following kludge for now (it's rough, but it get's me in the ballpark):

```
from scipy.stats import rv_continuous
from incomplete_gamma import incomplete_gamma
from numba import vectorize, float64

@vectorize([float64(float64, float64)])
def cpois(X, mu):
    return incomplete_gamma(X, mu)

class continuous_poisson(rv_continuous):
    def _pdf(self, x, a):
        # slow numerical approximation
        d = 1e-6
        return (-cpois(x + 2 * d, a) + 8 * cpois(x + d, a) +
                cpois(x - 2 * d, a) - 8 * cpois(x - d, a)) / (12 * d)

    def _logpdf(self, x, a):
        # oooh this is ugly...
        d = 1e-6
        temp = (-cpois(x + 2 * d, a) + 8 * cpois(x + d, a) +
                 cpois(x - 2 * d, a) - 8 * cpois(x - d, a)) / (12 * d)
        return np.log(temp)

    def _cdf(self, x, a):
        return 1 - cpois(a, x)

    def _ppf(self, q, a):
        return gammainccinv(a, 1 - q)

cpois_dist = continuous_poisson(name='cpois_dist', a=0.0)
```

where `incomplete_gamma` is sped-up version of `scipy.special.gammaincc` I created in FORTRAN--no pointers, so I'm getting about a 40x speedup with a less flexibility .  This is then used to (attempt) to create my distribution:

```
from pymc3 import dist_math as dm
from pymc3 import distribution as dst
from pymc3 import continuous as ct

from theano.compile import as_op
from theano import shared
import theano.tensor as tt

class CPois(ct.PositiveContinuous):
    '''
    Extended Poisson distribution for continuous data, as provided in
    http://ac.inf.elte.hu/Vol_039_2013/137_39.pdf.  Specifically, the
    CDF is represented as:

        F_\mu (x) = \frac{\Gamma(x, \mu)}{\Gamma(x)}

    for x > 0, and zero otherwise.

    Parameters:
    -----------
    x : float, x > 0
    mu : float, mu >= 0
    '''
    def __init__(self, mu=0.0, *args, **kwargs):
        super(CPois, self).__init__(*args, **kwargs)
        self.mean = mu
        self.mu = mu

    def random(self, point=None, size=None, repeat=None):
        mu = dst.draw_values(self.mu, point=point)

        return dst.generate_samples(cpois_dist.rvs, mu, size=size)

    def logp(self, val, size=None):
        mu = shared(self.mu)
        return logp_trick(val, mu)

@as_op(itypes=[tt.dvector, tt.dvector], otypes=[tt.dvector])
def logp_trick(_val, _mu):
    return cpois.logpdf(_val, _mu)
```

There have been a bunch of other things attempted, and of course the above is incorrect, but this is the core of what I've attempted thus far just to get things going. Once that's done, getting the math corrected is easy.

Oh, also tried using the `dist_math.bound` method as is done in most distributions provided with pymc3, but that fell over even worse; the problem in that case is that I run into a much lower-level problem with theano not being able to handle things...

**Comment by hvasbath** [comment]
What helped me dealing with theano is that you first have to make clear what is a 'standard variable' and a symbolic variable in your case here, which I cannot really follow. To me it seems that mu came from a pymc3 distribution, which is already a theano tensor. So it doesnt make sense to make it shared as you would use shared on the 'standard pythonic variables' (spv). Always during the interaction of a tensor with spv's you would need to convert the spv to a symbolic variable, you can do this with shared and sometimes tt.cast(dtype='whatever you need'). But getting a theano tensor in an external program I havent seen so far being able to work. 
Your cpois.logpdf takes the symbolic variables and tries to feed it ultimately into incomplete gamma. Right? So if you dont convert them to spvs with mu.eval() it wont work. 
But I am just guessing and also not so advanced yet.

**Comment by DeliciousHair** [comment]
Ah OK, that's ( heuristically) what I wanted to do in the first place but was getting all sorts of problems. My lack of abilities with theano is really the root cause of the problem, but I'll try your suggestion today.

Thanks so much for the suggestion☺

**Comment by aloctavodia** [comment]
I am closing this, but feel free to reopen if necessary.
