### ISSUE TITLE
cannot compute test values although defined, as_op output problems

### ISSUE THREAD

**Issue by hvasbath** [pymc-devs/pymc#883]
Dear all,

I posted the following problem also in the theano issues,  but as my intention is to build a pymc3 model...
https://github.com/Theano/Theano/issues/3753
(I use the theano development version from GIT and have ubuntu12.04 as OS.)

I would very much appreciate any comments on the following issue:
I wrote a function as an as_op but however I cannot do any operation on its output (tzero in the following). 
The output is properly computed and the function works correctly if I compile it alone.
However I want to use it in a more complex chain of operations.

I cant get the test_value of tzero by doing tzero.tag.test_value
and I guess that is why the following functions fail, because they want to do that.
The input variables have test_values just patch_size has none, because it is a constant.
Is this a problem?
However if I do tzero.tag.test_value.eval() I can get the test_value. But following operators do not do the eval() I guess.
setting config.compute_test_value=ignore does not help anything
Also I want to use this code in a pymc3 model, where test_values are required during chain initialisation so completely switching off is also no option.

Also .shape doesnt work although it should do if I have infer_shape defined right?

It always says:
One of the input test values does not have the proper type.
But if I check the input tensors with .type() they all have the proper type (see also below):

```
slowness = tt.reshape(1/m_velocity, (tt.cast(num_patch_w,dtype='int64'),tt.cast(num_patch_l,dtype='int64')))

slowness.type
TensorType(float64, matrix) --> defined as dmatrix

I did tt.cast(dtype='float64') on patch size before on a numeric value.
patch_size.type
TensorType(float64, scalar)  --> defined as dscalar

nuc_x.type
TensorType(int64, scalar) --> defined as lscalar

nuc_y.type
TensorType(int64, scalar)
```

Best regards and thanks for any potential help!
Hannes

Below the traceback of the error:

```
tzero.shape()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-51-05fa0039771e> in <module>()
----> 1 tzero.shape()

/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/tensor/var.pyc in <lambda>(self)
    279             return theano.tensor.basic.transpose(self, axes)
    280 
--> 281     shape = property(lambda self: theano.tensor.basic.shape(self))
    282 
    283     size = property(lambda self: self.shape[0] if self.ndim == 1 else

/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/op.pyc in __call__(self, *inputs, **kwargs)
    608             for i, ins in enumerate(node.inputs):
    609                 try:
--> 610                     storage_map[ins] = [self._get_test_value(ins)]
    611                     compute_map[ins] = [True]
    612                 except AttributeError:

/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/op.pyc in _get_test_value(cls, v)
    536             # ensure that the test value is correct
    537             try:
--> 538                 ret = v.type.filter(v.tag.test_value)
    539             except Exception as e:
    540                 # Better error message.

/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/tensor/type.pyc in filter(self, data, strict, allow_downcast)
     84         if isinstance(data, Variable):
     85             raise TypeError(
---> 86                 'Expected an array-like object, but found a Variable: '
     87                 'maybe you are trying to call a function on a (possibly '
     88                 'shared) variable instead of a numeric array?')

TypeError: For compute_test_value, one input test value does not have the requested type.

Backtrace when that variable is created:
  File "<ipython-input-48-39f60d4b54f0>", line 1, in <module>
    tzero = fast_sweep.get_rupture_times_symbolic(tt.reshape(1/m_velocity, (tt.cast(num_patch_w,dtype='int64'),tt.cast(num_patch_l,dtype='int64'))),patch_size, nuc_x, nuc_y)
```

The error when converting the test value to that variable type:
Expected an array-like object, but found a Variable: maybe you are trying to call a function on a (possibly shared) variable instead of a numeric array?

The as_op function- sorry for its complexity.

```
import numpy as num
import theano
import theano.tensor as tt
from theano.ifelse import ifelse
from theano.compile.ops import as_op

def infer_shape_fast_sweep(node, input_shapes):
 return [(input_shapes[0][0]*input_shapes[0][1])]

@as_op(itypes=[tt.dmatrix, tt.dscalar, tt.lscalar, tt.lscalar], otypes=[tt.dvector], infer_shape=infer_shape_fast_sweep)
def get_rupture_times_symbolic(slownesses, patch_size, nuc_x, nuc_y):
'''Does the same calculation as get_rupture_times_theano 
just with symbolic variable input and output for pymc3 optimization.
To Do: Create a proper Theano Op so that exactly an Rectangular class 
       with properties can be created.'''
[step_dip_max, step_str_max] = slownesses.shape
StartTimes = num.ones((step_dip_max, step_str_max))*1e8
StartTimes[nuc_y,nuc_x] = 0
StartTimes = theano.shared(StartTimes)

# Stopping check var
epsilon = theano.shared(0.1)
err_val = theano.shared(1e6)

# Iterator matrixes
dip1 = num.repeat(range(step_dip_max), step_str_max)
str1 = num.tile(range(step_str_max), step_dip_max)

dip2 = num.repeat(range(step_dip_max), step_str_max)
str2 = num.tile(range(step_str_max-1,-1,-1), step_dip_max)

dip3 = num.repeat(range(step_dip_max-1,-1,-1), step_str_max)
str3 = num.tile(range(step_str_max-1,-1,-1), step_dip_max)

dip4 = num.repeat(range(step_dip_max-1,-1,-1), step_str_max)
str4 = num.tile(range(step_str_max), step_dip_max)

DIP = theano.shared(num.hstack([dip1, dip2, dip3, dip4]))
STR = theano.shared(num.hstack([str1, str2, str3, str4]))

### Upwind scheme ###
def upwind(dip_ind, str_ind, StartTimes, slownesses, patch_size):
    [n_patch_dip, n_patch_str] = slownesses.shape
    zero = theano.shared(0)
    s1 = str_ind-1
    d1 = dip_ind-1
    s2 = str_ind+1
    d2 = dip_ind+1

    # if a < b return b
    checked_s1 = ifelse(tt.lt(s1,zero),zero,s1)
    checked_d1 = ifelse(tt.lt(d1,zero),zero,d1)

    # if a =< b return a-1
    checked_s2 = ifelse(tt.le(n_patch_str,s2),n_patch_str-1,s2)
    checked_d2 = ifelse(tt.le(n_patch_dip,d2),n_patch_dip-1,d2)

    ST_xmin = tt.min((StartTimes[checked_d1, str_ind], StartTimes[checked_d2, str_ind] ))
    ST_ymin = tt.min((StartTimes[dip_ind, checked_s1], StartTimes[dip_ind, checked_s2] ))

    ### Eikonal equation solver ###
    # The unique solution to the equation
    # [(x-a)^+]^2 + [(x-b)^+]^2 = f^2 * h^2
    # where a = u_xmin, b = u_ymin, is
    # 
    #         | min(a,b) + f*h,                           |a-b|>= f*h
    # xnew =  |
    #         |0.5 * [ a+b+sqrt( 2*f^2*h^2 - (a-b)^2 ) ], |a-b| < f*h
    start_new = ifelse(tt.le(slownesses[dip_ind, str_ind] * patch_size, tt.abs_(ST_xmin-ST_ymin)),
                  tt.min((ST_xmin, ST_ymin)) + slownesses[dip_ind, str_ind]* patch_size,
                  (ST_xmin + ST_ymin + tt.sqrt(2*tt.pow(slownesses[dip_ind, str_ind],2)*tt.pow(patch_size,2) - tt.pow((ST_xmin - ST_ymin),2)))/2)

    # if a < b return a
    output = ifelse(tt.lt(start_new, StartTimes[dip_ind, str_ind]), start_new, StartTimes[dip_ind, str_ind])
    return tt.set_subtensor(StartTimes[dip_ind:dip_ind+1,str_ind:str_ind+1], output)


def loop_upwind(StartTimes, PreviousTimes, err_val, iteration, epsilon):
    [results, updates] = theano.scan(fn = upwind, 
                       sequences = [DIP, STR],
                       outputs_info = [StartTimes],
                       non_sequences = [slownesses, patch_size])

    StartTimes = results[-1]
    err_val = tt.sum(tt.sum(tt.pow((StartTimes-PreviousTimes),2)))
    PreviousTimes = StartTimes.copy()
    return (StartTimes, PreviousTimes, err_val, iteration +1), theano.scan_module.until(err_val < epsilon)

# while loop until err < epsilon
iteration = theano.shared(0)
PreviousTimes = StartTimes.copy()
([result, PreviousTimes, errs, Iteration], updates) =theano.scan(
            fn=loop_upwind,
            outputs_info=[StartTimes, PreviousTimes, err_val, iteration],
            non_sequences=[epsilon],
            n_steps=500)     # arbitrary set usually stops after few iterations

return tt.cast(result[-1].flatten(),dtype='float64')
```

**Comment by hvasbath** [comment]
I can defenitely pin down the problem to the point that the test_value under tzero(output of my as_op) is still a symbolic variable and needs to be evaluated with tzero.tag.test_value.eval(). I tested several other operators- there the test_values are always numeric after operations! Why is the test_value of my as_op still symbolic and does not get evaluated on the fly? Does it need to be a proper Op?
Thanks a lot for your answer!

Hannes

**Comment by hvasbath** [comment]
if I do
tzero = fast_sweep(...)
tzero.tag.test_value = tzero.tag.test_value.eval()
in the chain of my optimization it works!
But I think it is not meant to be like this right? Also I do not want to evaluate the test value in each iteration that makes it horribly slow- isnt it?

**Comment by fonnesbeck** [comment]
I do not see the `fast_sweep` function in the code that you posted above. 

Correct, you should not have to explicitly evaluate the test_value in your code.

**Comment by hvasbath** [comment]
Ah my bad, I am sorry, thats just how I import it in a module. The function itself is the one below the @as_op "get_rupture_times_symbolic" executed like this:
tzero = fast_sweep.get_rupture_times_symbolic(...

**Comment by fonnesbeck** [comment]
What if you evaluate `tzero` in a Theano function? If that works, you should be good, as all that PyMC3 will require is that you have a `logp` from your stochastic that can get evaluated in the sampling loop.

**Comment by hvasbath** [comment]
That doesnt really work as it takes the stochastic variables as inputs that I want to estimate and they are symbolic ...Or did I understood the way how PYMC3 works wrong? I mean I did the effort in reprogramming this, which was really not easy as I am very new to theano, in the symbolic way just to get it running in PYMC3. Can one write the logp calculation in a non symbolic way and still get it running in pymc3? This would make life much easier ;) .

**Comment by fonnesbeck** [comment]
No, you are correct -- the inputs need to be Theano objects -- but I thought your issue was related to needing evaluations of the variables in order to debug and get things working. Of course, what happens inside the `as_op`-decorated function does not have to be Theano, which is why it becomes useful for general model-building in PyMC3.

**Comment by hvasbath** [comment]
The problem got solved:
The as_op decorator only must be used if the content inside its function is non-theano! So removing the as_op decorator solves the issue.
Thanks for your help!

**Comment by arcarchit** [comment]
"The as_op decorator only must be used if the content inside its function is non-theano! So removing the as_op decorator solves the issue."
Helped me solve my issue as well, thanks ! :)
