### ISSUE TITLE
Installation of dependencies is deprecated

### ISSUE THREAD

**Issue by akuz** [pymc-devs/pymc#891]
Just for your info, probably will need to upgrade the installation instructions, got this from pip:

DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.

**Comment by fonnesbeck** [comment]
Is anyone else getting this? I do not.

**Comment by aloctavodia** [comment]
`pip install --process-dependency-links git+https://github.com/pymc-devs/pymc3`

Returns the deprecation warning

`pip install git+https://github.com/pymc-devs/pymc3`

does not complain
