### ISSUE TITLE
Error with categorical variables

### ISSUE THREAD

**Issue by carolfs** [pymc-devs/pymc#894]
The following code runs fine sometimes, but sometimes it generates an error. Not sure about what's going on. I've just updated all packages with pip.

``` python
import numpy as np
import pymc3

with pymc3.Model() as model:
    category = pymc3.Categorical(name='category', p=[0.25,0.25,0.25,0.25])
    trace = pymc3.sample(20)
print(trace['category'])
```

When it doesn't, I get the following error:

```
Assigned Metropolis to category
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
IndexError: index out of bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mpl_bfit.py", line 8, in <module>
    trace = pymc3.sample(20)
  File "/usr/lib/python3.5/site-packages/pymc3/sampling.py", line 156, in sample
    return sample_func(*sample_args)
  File "/usr/lib/python3.5/site-packages/pymc3/sampling.py", line 165, in _sample
    for i, strace in enumerate(sampling):
  File "/usr/lib/python3.5/site-packages/pymc3/sampling.py", line 247, in _iter_sample
    point = step.step(point)
  File "/usr/lib/python3.5/site-packages/pymc3/step_methods/arraystep.py", line 118, in step
    apoint = self.astep(bij.map(point))
  File "/usr/lib/python3.5/site-packages/pymc3/step_methods/metropolis.py", line 125, in astep
    q_new = metrop_select(self.delta_logp(q,q0), q, q0)
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/lib/python3.5/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64}(TensorConstant{(4,) of 0.25}, ScalarFromTensor.0)
Toposort index: 5
Inputs types: [TensorType(float64, vector), Scalar(int64)]
Inputs shapes: [(4,), ()]
Inputs strides: [(8,), ()]
Inputs values: [array([ 0.25,  0.25,  0.25,  0.25]), 4]
Outputs clients: [[Elemwise{Composite{(Switch((GE(i0, i1) * LE(i0, i2)), log(i3), i4) - Switch((GE(i5, i1) * LE(i5, i2)), log(i6), i4))}}(Subtensor{int64}.0, TensorConstant{0}, TensorConstant{3}, Subtensor{int64}.0, TensorConstant{-inf}, Subtensor{int64}.0, Subtensor{int64}.0)]]

Backtrace when the node is created:
  File "/usr/lib/python3.5/site-packages/pymc3/distributions/discrete.py", line 367, in logp
    return bound(log(p[value]),

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by zeneofa** [comment]
Not sure if this will help, but I used the suggestion here: 

https://github.com/pymc-devs/pymc3/blob/a06f957893fd909d90dcb9fdad6a60e5f8be8b2f/pymc3/examples/gaussian_mixture_model.ipynb

Namely using ElemwiseCategoricalStep stepmethod: 

```
import pymc3

with pymc3.Model() as model:

    a = pymc3.Categorical('a', p = [0.25,0.25,0.25,0.25])
    step = pymc3.ElemwiseCategoricalStep(var=a, values=[0,1,2,3])
    trace = pymc3.sample(100, step=step)

print(trace['a'])
```

**Comment by fonnesbeck** [comment]
I can't replicate this error here:

```
Assigned Metropolis to category
[-----------------100%-----------------] 20 of 20 complete in 0.5 sec
[0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 1 2 2 0 0]
```

Can you try updating pymc3 from master?

```
pip install -U git+https://github.com/pymc-devs/pymc3.git
```

**Comment by carolfs** [comment]
I updated pymc3 and I still get the same error, but it's intermittent. I get it once out of maybe 3 or 4 runs. It gets more frequent if I increase the sample size.

**Comment by twiecki** [comment]
@carolfs did you try with pymc3.ElemwiseCategoricalStep(var=a, values=[0,1,2,3])?

**Comment by carolfs** [comment]
I just tried that and it seems to work.

**Comment by twiecki** [comment]
We're assigning the wrong step method to Categorical variables it seems.

**Comment by fonnesbeck** [comment]
`ElemwiseCategoricalStep` does not have a `competence` method. I can fix that.

**Comment by fonnesbeck** [comment]
Its not clear to me how `ElemwiseCategoricalStep` works, in particular why values are passed to the constructor.

**Comment by twiecki** [comment]
It basically randomly proposes the values you pass in.

**Comment by fonnesbeck** [comment]
Kind of hacky, but seems to work. Please test/improve.

**Comment by dobos** [comment]
I'm seeing the same issue with CategoricalGibbsMetropolis in pymc 3.8. It doesn't have the ElemwiseCategoricalStep step method. My model is more complex and I use the categorical variable to index shared theano tensors. I keep getting errors like:

IndexError: index 4 is out of bounds for axis 0 with size 3

The tensor indeed has a size of 3 but the categorical variable is generated with probabilities from a Dirichlet of 3 components.

The mixture model is followed by another, binary mixture down on the graph using pymc3.math.switch, so my guess is that pymc is trying to be smart not to sample from the categorical when the binary variable is such that it won't need that branch of the graph and uses an uninitialized or otherwise dirty tensor but still tries to index the shared tensors with those values.
