### ISSUE TITLE
autocorrplot clobbers axes arg

### ISSUE THREAD

**Issue by jonsedar** [pymc-devs/pymc#899]
Minor issue in `plots.py`: function `autocorrplot()` doesn't actually use the `ax` axes argument, it simply creates new axes regardless:

```
196 |    fig, ax = plt.subplots(len(vars), chains, squeeze=False,
197 |                    sharex=True, sharey=True)
```

This is a pain, since a new fig and new axes get created regardless of the `ax` arg, preventing all sorts of integration into larger plotting frames and figure sizing etc.

Suggest refactoring to check for presence of `ax` in args and handling the axes in a similar way to `traceplot`

**Comment by twiecki** [comment]
Good point, want to do a PR?

**Comment by jonsedar** [comment]
Sure I'll give it a go

J

## 

Jonathan Sedar
jon@sedar.co

**Comment by jonsedar** [comment]
Attempted a fix with PR https://github.com/pymc-devs/pymc3/pull/902
