### ISSUE TITLE
Drop T in favour of StudentT 

### ISSUE THREAD

**Issue by superbobry** [pymc-devs/pymc#904]
Theano docs enforce the convention of importing `theano.tensor` as `T`. Unfortunately, this convention isn't directly applicable to PyMC3 codebase, because there's already a `T` in `pymc3.distributions`. 

An obvious solution to this is to drop the `T` (and `Tpos`) in favour of a slightly longer `StudentT`. What do you think?

**Comment by fonnesbeck** [comment]
Ah, forced conventions! My favorite oxymoron.

I'm not opposed to the change. /cc @twiecki @jsalvatier

**Comment by twiecki** [comment]
Hm, good point indeed. Sounds good to me.

**Comment by jsalvatier** [comment]
Seems fine to me.

**Comment by andykitchen** [comment]
bump

**Comment by superbobry** [comment]
This is part of #905.

**Comment by twiecki** [comment]
#905 was merged. Thanks everyone.
