### ISSUE TITLE
Unable to reproduce Robust regression Hoggs model

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#911]
## I tried replicating the example from Jon Sedar  and got this error in the last cell.

AttributeError                            Traceback (most recent call last)
<ipython-input-13-a53e36fbfa60> in <module>()
      4 lm = lambda x, samp: samp['b0_intercept'] + samp['b1_slope'] \* x
      5 
----> 6 pm.glm.plot_posterior_predictive(traces_ols[-1000:],
      7         eval=np.linspace(-3, 3, 10), lm=lm, samples=200, color='y', alpha=.1)
      8 

AttributeError: 'module' object has no attribute 'plot_posterior_predictive'

I'm using the newest version of PyMC3, and the same yml file.

**Comment by springcoil** [comment]
Fixed after installing Patsy. Maybe this should be added to the yaml file. I submitted a change to the repository.

**Comment by jonsedar** [comment]
`patsy` is used inside `glm/glm.py`, so probably the best place to require this is within the `install_reqs` param within `setup.py`

Could you retest with a new env and open an issue?

FWIW I'll add to the YAML excerpt

**Comment by springcoil** [comment]
I already added it to the YAML excerpt and pushed it. It works with Patsy - I'll open a new issue
