### ISSUE TITLE
PyMC3 beta_like function?

### ISSUE THREAD

**Issue by zeneofa** [pymc-devs/pymc#919]
Hi,
I have a custom distribution that involves using a loop and summing a bunch of Beta distributed values in order to calculate the logp. In PyMC2 there was pm.beta_like(x,a,b) function, is there something equivalent in PyMC3?

I have tried to use scipy.stats, particularly beta.logpdf method, but this results in:

TypeError: Variables do not support boolean operations. This can happen if you do a logical operation (<, <=, >, <=, ==, !=) between a numpy.ndarray and a Theano tensorvariable. Due to NumPy implementation before NumPy 1.8, we cannot make the Python syntax work when the ndarray is on the left, and this results in this error. To work around that, either call theano.tensor.{lt,le,eq,ne,gt,ge}(ndarray, tensor), or use the Python syntax with the Theano tensor on the left. Or update to NumPy 1.8 or above.

gist: https://gist.github.com/zeneofa/6aa4e89040f4c06adadf
the likelihood is on line 55

scipy version 0.16.1
numpy version 1.10.2
theano version 0.7.0.dev-RELEASE

**Comment by fonnesbeck** [comment]
It sounds like you want the beta distribution rather than the PyMC object, which can be accessed using the `dist` classmethod. For example,

```
Beta.dist(1,1).logp(0.3)
```

**Comment by zeneofa** [comment]
Thnks, I changed it accordingly, now I am running into the following very strange error:

```
/jq2/miniconda/envs/pymc/lib/python2.7/site-packages/pymc3/distributions/distribution.pyc 
 __init__(self, shape, dtype, testval=None, defaults=[], transform=None):
     40         self.shape = np.atleast_1d(shape)
---> 41         if False in (np.floor(self.shape) == self.shape):
     42             raise TypeError("Expected int elements in shape")
     43         self.dtype = dtype

AttributeError: 'int' object has no attribute 'floor'

```

gist: https://gist.github.com/zeneofa/6aa4e89040f4c06adadf

**Comment by fonnesbeck** [comment]
The shape for that node is a mixture of a subtensor and an integer, which will not work:

```
(Pdb) self.shape
array([Subtensor{int64}.0, 5], dtype=object)
```

**Comment by zeneofa** [comment]
What is the preferred way to access the shape of another tensor/pymc random variable, as this shape may change when obtaining subtensors, in my model, I therefore need a way to get an integer value for its dimension?

Does the test_value change, or is this set during initialization ie will the number returned from:
`p_0.tag.test_value.shape[1]` , change or remain constant as the algorithm proceeds?

**Comment by fonnesbeck** [comment]
Sorry for the late answer, but you can just evaluate the `shape` attribute to get the dimension.

Closing this as an issue.
