### ISSUE TITLE
Posterior predictive sampling not working for 'transformed distributions'

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#932]
Code to generate PPC fails when Wald or Lognormal distributions are used in the model, but works fine with others including Normal, Poisson and Beta-Binomial (BetaBin).

``` python
ppc = sample_ppc(trace, samples=1000, model=model, size=1, vars=model.basic_RVs)
```

returns this error:

``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-a0a5c30d093c> in <module>()
     58 
     59     # Generate a single synthetic dataset per parameter sample
---> 60     ppc = sample_ppc(trace, samples=1000, model=model, size=1, vars=model.basic_RVs)
     61 
     62     pm.traceplot(trace)

/Applications/anaconda/lib/python3.4/site-packages/pymc3/sampling.py in sample_ppc(trace, samples, model, vars, size)
    339         param = trace[idx]
    340         for var in vars:
--> 341             ppc[var.name].append(var.distribution.random(point=param,
    342                                                          size=size))
    343 

AttributeError: 'TransformedDistribution' object has no attribute 'random'
```

**Comment by springcoil** [comment]
@fonnesbeck this sounds like it is another 'not ready for the big time' case.

**Comment by twiecki** [comment]
CC @stevenmanton Any ideas on how to handle that case?

**Comment by fonnesbeck** [comment]
Can the transformation not be applied to the random number from the original distribution? It occurs to me, however, that we should not really be interested in variables that have been transformed automatically by PyMC, so perhaps they should just be excluded.

**Comment by twiecki** [comment]
You're right, it's actually fairly obvious. The problem is in `sample_ppc` which should skip the transformed variables (and only sample from the untransformed ones).

**Comment by stevenmanton** [comment]
The default `vars` should be any variables of `Observed_RVs` type. Are transformed vars instances of `Observed_RVs`? If so, the simplest fix by be to exclude those from sampling:

``` python
if vars is None:
    vars = [var for var in model.observed_RVs if not isinstance(var, TransformedRV)]
```

Although I think it might make more sense, though be slightly more difficult, for `TransformedRV`'s to inherit the `random` method from the underlying distribution and apply the transform.

What do people think?

**Comment by twiecki** [comment]
@stevenmanton Yeah, the inhertince idea makes sense. It should be fairly straightforward because we already have the transform.

I'm actually curious how you could have transformed observed RVs in the your model, @hughpastoll?

**Comment by ghost** [comment]
@twiecki Many thanks for taking a look at this. I'm rather new to python, so might be doing something silly, but I don't think it's the result of me transforming anything. As far as I understand the Wald distribution is a 'transformed distribution' - here's a very simple model that produces the error and works when the call to `sample_ppc` is commented out:

``` python
%matplotlibinline
from matplotlib import pyplot as plt
import pymc3 as pm

with pm.Model() as model:

    rv_transformed = pm.Wald('rv_transformed', mu=5, phi=2)

    trace = pm.sample(1000)
    pm.traceplot(trace)

    ppc = pm.sample_ppc(trace, samples=1000, model=model, size=1, vars=model.free_RVs)
```

**Comment by stevenmanton** [comment]
@hughpastoll I'm a bit confused what you're trying to do. I can reproduce the error in your example, but it goes away if you remove the `vars` keyword. In that case, you get back an empty dict, which reflects the fact that there's nothing to run a posterior predictive check on.

In most models, you will typically have at least one observed value. Often you're either trying to reason about hidden parameters or see if your model describes your data well. One way to do the latter is to compute a posterior predictive check, which is what `sample_ppc` does. Essentially, this function takes the inferred values of the hidden parameters (saved in `trace`) and runs them through the model to generate "fake" observed data. If the fake observed data looks "similar" to the actual observed data, you can have some confidence in the model. If not, you probably need to adjust your model. You can also use this technique to "predict" values or labels of new data.

Here's a more realistic scenario where you observe data that you hypothesize comes from a Wald distribution, but you just don't know what the right model parameters are. (Here, it's just mu you don't know.) This code will run and generate a ppc on your observed variable `wald`.

``` python
with pm.Model() as model:

    mu = pm.Uniform('mu', 0, 5)
    wald = pm.Wald('wald', mu=mu, phi=2, observed=np.random.wald(1, 1, size=5))

    trace = pm.sample(100)
    pm.traceplot(trace)

    ppc = pm.sample_ppc(trace, samples=100, model=model)
```

**Comment by ghost** [comment]
@stevenmanton Thanks very much for taking the time to reply. I agree I may be using `sample_ppc` in an unorthodox way in my previous example, but I think one might want to use it in this way if you wanted to sample the complete joint distribution. I'm guessing this is part of the reason for being able to set the `vars` parameter of `sample_ppc` to include free variables (`vars=model.free_RVs`)  and not only observed variables (`vars=model.observed_RVs`). 

First, a (overly simple) model the same as the one I posted before works fine using a `Normal` instead of  a `Wald` distribution, suggesting `model.free_RVs` should be returned without a problem in this context and showing that such models **can** (but perhaps not should!) be constructed:

``` python
with pm.Model() as model:

    rv_standard = pm.Normal('rv_standard', mu=0, sd=1)

    trace = pm.sample(1000)
    pm.traceplot(trace)

    ppc = pm.sample_ppc(trace, samples=100, model=model, size=1, vars=model.free_RVs)
```

(The returned dict has an `rv_standard` variable in this instance). 

Second, it fails in the same way as previously indicated when using a `Wald` as a prior for a `Normal` and you want to sample from both the posterior `Wald` and the `Normal` distributions after observing some data (by setting `vars` to `model.basic_RVs` in `sample_ppc`).  I would not expect this failure to occur:

``` python
obs_data = np.random.normal(loc=5, scale=1, size=100)

with pm.Model() as model:

    mu_param = pm.Wald('mu_param', mu=2, lam=1)
    rv = pm.Normal('rv', mu=mu_param, sd=1, observed=obs_data)

    trace = pm.sample(1000)
    pm.traceplot(trace)

    ppc = pm.sample_ppc(trace, samples=100, model=model, size=1, vars=model.basic_RVs)
```

(Again, this works fine if the prior `Wald` is changed to a `Normal`)

As before, I'm fully aware I may be doing something silly and please call me out if I am!

**Comment by stevenmanton** [comment]
Hey @hughpastoll, I think the issue might be more conceptual. You're right that interchanging Wald and Normal distributions doesn't really change anything. I think I'm still unclear what you're trying to accomplish.

Take your first example. Here, you're running MCMC sampling, then trying to compute the ppc as well. But you have no observed data, so your likelihood is constant and you're just sampling from your prior. The `sample_ppc` method, in principle if it worked, would just bootstrap sample from the trace, which is a sample of the prior. Conceptually, I don't see why you would ever do this.

In your second example, it should be fine to run `sample_ppc` on `rv`, but not `mu_param`. If you want the posterior of `mu_param`, just look at the `trace['mu_param']`.

It still seems to me that it only really makes sense to call `sample_ppc` on observed variables, because these are the only ones that don't show up in the trace. (There's a trick where you can define an unobserved variable of the same form as the observed variable so that pymc computes a trace for it as well, but this is less flexible than `sample_ppc`. For example, adding `rv_sim = pm.Normal('rv_sim', mu=mu_param, sd=1)` to your second example.)

**Comment by ghost** [comment]
@stevenmanton It seems you are right - my confusion did arise from me not using pymc3 properly (I should have been indexing straight into the trace instead of trying to call sample_ppc with the `vars` set to `basic_RVs` or `free_RVs`). Thanks again for your responses - definitely helped clear things up!

It still seems there's an issue with 'transformed' distributions though. Do you suggest I keep the issue open (even though it won't be a problem for me right now)?

**Comment by stevenmanton** [comment]
No problem @hughpastoll. I'm no expert in this stuff either, so it's helpful to think about these kinds of issues.

I think you have a great point that the transformation variables should have a `random` attribute, which as @twiecki mentioned might not be tough to implement. I can take a stab at that. Maybe we close this ticket and open a new one? I'm not sure, I'll leave that decision up to the core devs.
