### ISSUE TITLE
Posterior predictive check does not work when random variable is used as an index

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#933]
I have the following model:

``` python

        self.model = pm.Model()
        with self.model:
            self.gamma_pi = pm.Uniform('gamma_pi', 0, 0.5)
            self.gamma_tau = pm.Uniform('gamma_tau', 0, 0.5)
            self.gamma_phi = pm.Uniform('gamma_phi', 0, 0.5)
            print(self.n)

            self.sigma_pi = GaussianRandomWalk(name='sigma_pi', tau=1. / self.gamma_pi, shape=self.n)
            self.sigma_tau = GaussianRandomWalk(name='sigma_tau', tau=1. / self.gamma_tau, shape=self.n, testval=-1)
            self.sigma_phi = GaussianRandomWalk(name='sigma_phi', tau=1. / self.gamma_phi, shape=self.n, testval=-1)
            self.tau = GaussianSVRandomWalk(name='pi', tau=pm.exp(-self.sigma_tau), shape=self.n)

            self.c = pm.Normal('c', 0, 1, shape=12)


            monthIndex = self.inflation['Month'].values - 1
            print(monthIndex)
            self.month = pm.DiscreteUniform(name='month', lower=0, upper=11,
                                            observed=monthIndex)
            self.inflation = pm.Normal(name='inflation',
                                  mu=self.tau + self.c[self.month] * pm.exp(self.sigma_phi / 2),
                                  tau=pm.exp(-self.sigma_pi),
                                  observed=self.inflation['Inflation'])
```

which takes inflation and month as input, and fits fine.

then I am trying to run  Posterior Predictive Check on it like this

ppc = pm.sample_ppc(trace, samples=100, model=self.model, size=100)

and get the following error:

Traceback (most recent call last):
  File "/home/sergey/workspace/cpiproject/main.py", line 719, in <module>
    model = pm.NUTSmodel(simplifiedInflationDf)
  File "/home/sergey/workspace/cpiproject/pymc3model.py", line 165, in **init**
    self.estimate()
  File "/home/sergey/workspace/cpiproject/pymc3model.py", line 222, in estimate
    self.presentSamplePPC(startTrace,'initial')
  File "/home/sergey/workspace/cpiproject/pymc3model.py", line 247, in presentSamplePPC
    ppc = pm.sample_ppc(trace, samples=100, model=self.model, size=100)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/sampling.py", line 343, in sample_ppc
    size=size))
  File "/usr/local/lib/python3.4/dist-packages/pymc3/distributions/continuous.py", line 162, in random
    point=point)
  File "/usr/local/lib/python3.4/dist-packages/pymc3/distributions/distribution.py", line 134, in draw_values
    givens[name] = (node, draw_value(node, point=point))
  File "/usr/local/lib/python3.4/dist-packages/pymc3/distributions/distribution.py", line 179, in draw_value
    input_args = [g[0] for g in givens]
TypeError: 'NoneType' object is not iterable

It appears that indexing by month causes this?

Note that GaussianSVRandomWalk is just

``` python
class GaussianSVRandomWalk(Continuous):
    """
    Random Walk with Normal innovations

    Parameters
    ----------
    tau : tensor
        tau > 0, innovation precision
    init : distribution
        distribution for initial value (Defaults to Flat())
    """

    def __init__(self, tau=None, init=pm.Flat.dist(), sd=None, mean=0., *args, **kwargs):
        super(GaussianSVRandomWalk, self).__init__(*args, **kwargs)
        self.tau = tau
        self.sd = sd
        self.init = init
        self.mean = mean

    def logp(self, x):
        tau = self.tau
        sd = self.sd
        init = self.init
        if sd is not None:
            sd_iml = sd[:-1]
        else:
            sd_iml = None

        if tau is not None:
            tau_iml = tau[:-1]
        else:
            tau_iml = None
        x_im1 = x[:-1]
        x_i = x[1:]

        innov_like = pm.Normal.dist(x_im1, tau_iml, sd=sd_iml).logp(x_i)
        return init.logp(x[0]) + pm.sum(innov_like)

```

**Comment by fonnesbeck** [comment]
Is this related to #932? Can you confirm which variable this is failing for? You can narrow it down by specifying a `vars` argument for `sample_ppc`

**Comment by ghost** [comment]
Tried this earlier by using only "Inflation" variable - didn't help. However, I don't actually need the month to be a random variable , so I removed it and the model works after that - so it is definitely something to do with interaction of indexing by a random variable.

Error in draw_samples was to do with trying to get a 'model' parameter from TensorConstant that seemed to contain the contents of the 'month' variable (not sure why it is a constant?)

**Comment by fonnesbeck** [comment]
Actually, it's not clear how that model runs at all. You refer to `self.inflation` in the definition of `monthIndex` before it is defined on the last line of the model.

**Comment by ghost** [comment]
Thats a red herring - it is defined in constructor as a pandas dataframe.

Have fixed this earlier.

**Comment by ghost** [comment]
I can send you the full source code and data if you like to try this?

**Comment by twiecki** [comment]
@stimakov That would be helpful, yeah.

**Comment by ghost** [comment]
@twiecki Cool, I'll reproduce it this evening (changed the code a bit) and will send you a copy

**Comment by ghost** [comment]
@twiecki  try this https://drive.google.com/file/d/0BxqtPwD3mJvLR2t1a0duVDBJMEE/view?usp=sharing

**Comment by ghost** [comment]
Hi, just wondering if it is solved now - looking at the linked issues there were a few comments there
