### ISSUE TITLE
Add BPIC to PyMC3

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#934]
I saw this in PyMC2 - https://github.com/pymc-devs/pymc/blob/895c24f62b9f5d786bce7ac4fe88edb4ad220364/pymc/MCMC.py#L443 

@AustinRochford

**Comment by jonsedar** [comment]
Bias-adjusted thingummy as per [Ando 2007](http://biomet.oxfordjournals.org/content/94/2/443.abstract). 

Looks about exactly the same as the DIC except for the final return statement, you could give it a cheeky cut&paste? https://github.com/pymc-devs/pymc3/blob/master/pymc3/stats.py

Needs a test of course too: https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_stats.py

**Comment by AustinRochford** [comment]
Yes, it would be nice if we could reuse some code between BPIC and DIC, which shouldn't be too hard.

**Comment by springcoil** [comment]
I will have a look if that can be refactored.

**Comment by AustinRochford** [comment]
Ah sorry, I didn't see that you had opened a pull request already.

**Comment by springcoil** [comment]
Can you review the PR Austin?

**Comment by springcoil** [comment]
This is sorted now :)
