### ISSUE TITLE
Light speed example from STAN

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#936]
I came across this on Stackoverflow. 
http://stackoverflow.com/questions/34532194/improper-flat-priors-in-pymc3

Here is a gist of it. https://gist.github.com/springcoil/bfec5d69449de57a3333

Anyone who knows more than me maybe @twiecki or @fonnesbeck or @jsalvatier able to help me debug this error.

**Comment by fonnesbeck** [comment]
We have a `Flat` distribution that returns zero irrespective of the passed value.
