### ISSUE TITLE
raise ValueError ("For numerical factors,

### ISSUE THREAD

**Issue by smart-patrol** [pymc-devs/pymc#937]
Was following the example doc here :
http://pymc-devs.github.io/pymc3/GLM-logistic/#bayesian-logistic-regression-with-pymc3

and got an error on the call -

```
with pm.Model() as logistic_model:
    pm.glm.glm('income ~ age + age2 + educ + hours', dat, family=pm.glm.families.Binomial())
    trace_logistic_model = pm.sample(2000, pm.NUTS(), progressbar=True)
```

The subset of the US only should be `data = data[data...` but don't think that's the issue.
Attached Ipynotebook for reference. 

[Bayesian Logistic Regression PyMC3.zip](https://github.com/pymc-devs/pymc3/files/93178/Bayesian.Logistic.Regression.PyMC3.zip)

**Comment by twiecki** [comment]
CC @springcoil

**Comment by springcoil** [comment]
Can you reproduce the error message in full?

**Comment by springcoil** [comment]
I tried reproducing your error. But I couldn't do it. Are you using the latest pymc3? and did you try clearing your theano-cache? theano-cache purge

**Comment by smart-patrol** [comment]
Pymc3 is the latest.
I cleared the cache but the error popped up again.

I am not using the C++ implementation of Theano but using the Python native.

**Comment by fonnesbeck** [comment]
Is this an ongoing issue?

**Comment by springcoil** [comment]
I assume this is resolved now
