### ISSUE TITLE
Cross validation in pymc3

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc#940]
Not sure this is a best place to ask - I have a time series model that is implemented in pymc3. I would like to validate the model out of sample by checking how good one step / n step forward forecasts are.

What is the best way to do this in pymc3 without recompiling the model every time for different length of data (I was thinking of giving missing data in input dataframe and then using previous values as starting points in simulation)

**Comment by twiecki** [comment]
I have a method for model caching here: https://github.com/pymc-devs/pymc3/issues/511#issuecomment-125935523

**Comment by jonsedar** [comment]
+1 I've found that technique worked quite well for me too. I plan to add it to [this example notebook](https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/GLM-model-selection.ipynb) soon
