### ISSUE TITLE
Make PositiveDefiniteError return node information 

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#949]
At present, when `quad_potential` fails, it returns a `PositiveDefiniteError` that includes a message like the following:

```
PositiveDefiniteError: Scaling is not positive definite. Simple check failed. 
Diagonal contains negatives. Check indexes [ 2  3  4  5  6  7  8  9 10 11 12]
```

Its not easy to relate those indices back to the offending node(s) in the model. The message ought to instead return the name of the node causing the failure.

**Comment by twiecki** [comment]
+1 Probably need to apply the bijection function to map the indices back.

**Comment by jbwhit** [comment]
I have an example of this error message happening in this gist: https://gist.github.com/jbwhit/a9012e04b0f48e582c22 -- I was hoping to build a hierarchical model but was running into problems. I didn't suspect that StudentT and Normal were different enough to cause errors. Should I post it here? Or should I open a new issue?

**Comment by twiecki** [comment]
I'd try setting test_values to try and get around that.
