### ISSUE TITLE
NUTS target_accept default is 0.8, not 0.65

### ISSUE THREAD

**Issue by jake-westfall** [pymc-devs/pymc#953]
In the [code for the NUTS sampler](https://github.com/pymc-devs/pymc3/blob/aa7546a9ed5bbfcfb66a8317eef83dc77055d2d5/pymc3/step_methods/nuts.py), the commented documentation says that the default value of the target acceptance probability (target_accept) is 0.65, but you can see in the **init** method signature that it's actually set to 0.8. In the Bayesian Data Analysis 3 textbook, the authors suggest that 0.65 is a reasonable guess for a general-purpose default value, so I guess it is the 0.8 in the method signature that is a mistake and should probably be changed to 0.65 to match the documentation.

**Comment by fonnesbeck** [comment]
Good catch!

**Comment by twiecki** [comment]
See http://arxiv.org/abs/1411.6669 for why 0.8 was chosen. This is also what STAN uses now.
