### ISSUE TITLE
Inscrutable Theano code dump using NUTS

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#955]
More debugging nastiness from Theano that is reproducible in the model specified in [this repo](https://github.com/fonnesbeck/uterine_fibroids_MA). Running NUTS results in tens of thousands of lines of Theano-generated C code being dumped into an output cell, and no other information to help debug the problem. `find_MAP` does not work at all on this problem. This is not a terribly complicated model (hierarchical multinomial model), but getting it running is to this point, impossible. Runs reasonably well with Metropolis.

EDIT: way down (I mean waaay down) the page, there is the following:

```
fatal error: bracket nesting level exceeded maximum of 256.
```

which means this may be related to #624, but again, this is a small model with small data, so it is not making sense to me.

**Comment by fonnesbeck** [comment]
Not sure there is much we can do about this, so closing.

**Comment by Fan-Gong** [comment]
Hi I also faced with this error and cannot find any way to resolve it. Is there any update for this topic? Thanks
