### ISSUE TITLE
vars/varnames argument naming consistency

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc#957]
The use of `vars` and `varnames` is used somewhat inconsistently throughout PyMC3. I'm going to propose using `vars` when the argument requires the PyMC objects themselves (e.g. for step methods) and `varnames` when just the names are expected. This would break some stuff, but we should probably enforce consistency before a release. 

For example, `summary` expects a list of strings for a `vars` argument, `find_MAP` expects PyMC variables for a `vars` argument, while `autocorrplot` expects strings for a `varnames` argument. This is confusing.

Thoughts?

**Comment by twiecki** [comment]
Confusing indeed and I like your argument for renaming.
