### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc#972]
Adding this here for discussion - should we implement API docs? Using something like Sphinx?

**Comment by superbobry** [comment]
Definitely yes. Currently the only way to explore the API is by reading the examples or the sources. Both options are much less convenient then a well structured documentation.

**Comment by fonnesbeck** [comment]
Certainly prior to a release.

**Comment by twiecki** [comment]
Actually @superbobry already laid the ground-work for this. Probably just need to add the rest of pymc3 to the sphinx files.

**Comment by springcoil** [comment]
Where is this ground work?

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/tree/master/docs/source

**Comment by springcoil** [comment]
Ok I'll try to have a look next week :)

On Wed, Feb 10, 2016 at 11:12 PM, Thomas Wiecki notifications@github.com
wrote:

> https://github.com/pymc-devs/pymc3/tree/master/docs/source
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/issues/972#issuecomment-182602966.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by twiecki** [comment]
Addressed here: https://github.com/pymc-devs/pymc3/pull/1122
