### ISSUE TITLE
Specifying an array for nu in StudentT() distribution

### ISSUE THREAD

**Issue by hermanc1** [pymc-devs/pymc#996]
I would like to specify an array for `nu` in the `StudentT()` distribution.  Is this at all possible? I can specify arrays for `mu` and `sd`, but I see that `nu` only accepts int.

**Comment by fonnesbeck** [comment]
I can't replicate this issue. Here is a `nu` of length 3:

``` python
In [3]: with Model() as model:
    nu = HalfCauchy('nu', 5, shape=3)
    x = StudentT('x', nu=nu, observed=[-1, 2, 15])
   ...:     
Applied log-transform to nu and added transformed nu_log to model.

In [4]: with model:
   ...:     tr = sample(100)
   ...:     
Assigned NUTS to nu_log
 [-----------------100%-----------------] 100 of 100 complete in 0.1 sec
```

**Comment by hermanc1** [comment]
Well that's a bit embarrassing :) There seems to have been a problem with my correctly sized, positive, non-zero Pandas Series for nu. The error said something about expecting a scalar, but it seems to have been sorted out now. Thank you, and my apologies!

**Comment by twiecki** [comment]
Glad it's working for you.
