### ISSUE TITLE
two small errors in tutorial

### ISSUE THREAD

**Issue by noahaskell** [pymc-devs/pymc#998]
I just finished reading the tutorial, and I noticed a couple small issues. First, there are multiple/ inconsistent names for the Poisson rate parameters in the coal mining disaster model. Second, the _more elaborate example of the usage of_ `as_op` link is broken.

**Comment by fonnesbeck** [comment]
This appears to be squared away in the current version of the notebook. Please reopen (or better yet, submit a PR) if not.
